### ISSUE TITLE
Component Refactor: Paragraph Table

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#10011]
**Description**

Refactor component to allow for DRUPAL API data to get processed/transformed through data_service. This will allow the component to consume a basic object type.

**Acceptance Criteria**

- [x]  Component renders as expected
- [x]  Existing component tests are revised to test the updated 'pure' component
- [x]  The component is added to StoryBook

**Tasks**
- [x]   Update component to use the VA web component
- [x]   Add Unit tests
- [x]   Update demo page
- [x]   Add to storybook

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public Websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`
