### ISSUE TITLE
Component Refactor: Node Promo Banner

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#10013]
**Description**

Refactor component to allow for DRUPAL API data to get processed/transformed through the next-drupal-query mechanism. This will allow the component to consume a basic object type.

**Acceptance Criteria**

- [x]  Component renders as expected
- [x]  Component render markup using the transformed data
- [x]  query will receive JSON:API data and transform it to the format expected by the component
- [x]  Existing component tests are revised to test the updated 'pure' component
- [x]  The component is added to StoryBook

**Tasks**
- [x]   Update component to use the new transformed data
- [x]   Create data_service to transform DRUPAL API and return new object
- [x]   Update Unit tests
- [x]   Update demo page
- [x]   Add to storybook

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public Websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by amponce** [comment]
https://github.com/department-of-veterans-affairs/next-build/pull/89
