### ISSUE TITLE
Make content release orchestration more resilient to failures

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#10019]
## Description

The CMS does a pretty decent job at keeping track of the "happy path" for content releases, but we need to do a better job about handling edge cases and making failures less silent.

## Acceptance Criteria
- [x] When a content release is successfully dispatched, but the GHA workflow fails, the following things should happen:
	- The CMS should be notified (in the same way that other steps of the GHA workflow already does)
	- The release state should be reset to `ready`
	- A content release request should be queued (as a retry)
- [x] If it has been more than 60 minutes since a workflow status notification has come into the CMS, the release state should be reset to `ready` and a content release request should be queued as a retry.
- [x] The CMS should keep track of clock hours and business hours since last successful release and export those metrics to Datadog using the existing metrics pipeline. The GHA workflow should not export those metrics anymore.
- [ ] ~An alert should be configured in Datadog to alert the platform CMS team and the helpdesk team if it has been more than 90 minutes (of business time) since the last successful release.~ moved to #9972 

## Tasks
- [x] add tasks to this ticket
- [x] write the code for the status expiration
- [x] write the cms-side code for the error notification
- [x] send cms metrics in the every minute job instead of every 15 or every 60
- [x] add metrics collectors
	- [x] last build duration
	- [x] rolling average of total build durations (dispatch -> complete; ignore errors; last 5)
	- [x] time between this deploy and last deploy
	- [x] rolling average of deploy interval (last 5)
- [x] write tests
- [x] open CMS PR and get it deployed
- [x] open PR against content release to send error notifications (After previous task)
- [ ] ~datadog alert is configured~ moved to #9972 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
