### ISSUE TITLE
Component Refactor: Node News Story Listing

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#10017]
**Description**

Refactor component to allow for DRUPAL API data to get processed/transformed through data_service. This will allow the component to consume a basic object type.

**Acceptance Criteria**

- [ ]  Component renders as expected
- [ ]  Component render markup using the transformed data
- [ ]  data_service will receive JSON:API data and transform it to the format expected by the component
- [ ]  Existing component tests are revised to test the updated 'pure' component
- [ ]  The component is added to StoryBook

**Tasks**
- [ ]   Update component to use the new transformed data
- [ ]   Create data_service to transform DRUPAL API and return new object
- [ ]   Update Unit tests
- [ ]   Update demo page
- [ ]   Add to storybook

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public Websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
This was done in the context of #10018
