### ISSUE TITLE
<Insert summary of epic>

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10030]
## Background

As we start to think about how to move Help Desk processes to less manual for the HD team, we should explore and evaluate how each issue is being resolved. There are possible solutions to these very-manual processes via #4395, however, we need to understand what we are doing now so that we can automate for better resolution. For future state, we should move into a more self-service approach for editors to fix issues without full handholding from the help desk. 

### User Story or Problem Statement

As a Sitewide CMS product manager, I need to understand how the help desk resolves issues so that I can think of product solutions for an editor self-service model. 

As a help desk manager, I need more automation in my resolution process so that I can be more efficient throughout the day.

As a Sitewide CMS product manager, I need a more automated way to track help desk resolution times so that I can make appropriate metrics and objectives for various initiatives. 

## Problem Description

How might we resolve manual help desk processes in a sustainable and scalable way?

### Affected users and stakeholders

* CMS editors of all products
* Sitewide Crew Help Desk Team

### Hypothesis

We believe that defining and automating certain help desk processes will achieve shorter time to resolve. We will know that to be true when we can time both quantity of help desk tickets and the length of time to resolve in a meaningful way.

## Assumptions
* We assume that there are help desk processes that take up a large amount of time for the help desk.
* We assume there are ways to automate and templatize HD processes.
* We assume that any changes to the current HD process will be a large change management effort.

## Acceptance Criteria
- [ ] HD processes are evaluated for automation
- [ ] Processes are documented and defined
- [ ] Change management is consulted
- [ ] KB articles are updated as needed.

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Discussed with Troy during 9/13 sprint refinement meeting -- Troy is looking into automatic Jira ticket templates

**Comment by stefaniefgray** [comment]
@TroyA6 Automation ticket!
