### ISSUE TITLE
Upgrade servers to PHP 7.3

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1004]
## Tasks:
- [x] Update <devops repo>/ansible/build/roles/cms/meta/main.yml. 
- [x] Update composer.json php version
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593
- [x] Update Tugboat image config:
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593
- [x] Update Lando image config: 
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593

* Requires updating to Lando > v3.0.0-aft.1: https://github.com/lando/lando/releases/tag/v3.0.0-aft.1
* This required me to redo my docker image also so be prepared.

- [x] Drupal core requires 8.8.3.  We are currently on 8.8.1: https://www.drupal.org/project/drupal/issues/3086374
- [x] Fix NodeLinkreport block causing php notice because the `$this->pluginDefinition` is null
```Notice: Trying to access array offset on value of type null in Drupal\Core\Block\BlockBase->baseConfigurationDefaults() (line 90 of core/lib/Drupal/Core/Block/BlockBase.php).```
- [x] Remove `va_gov_notifications` and `workflow_participants` because `va_gov_notifications` is no longer used and is not compible with php7.4
- [x] Update phpcs
- [x] GraphQL update
- [x] Fix paragraphs_browser notices

PHP 7.2 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3775 

## Post Code Compatibility steps:

With the code now compatible with PHP 7.4, the following steps remain.

- [x] Update BRD version:  https://github.com/department-of-veterans-affairs/devops/pull/6559
- [x] Update Composer.json w/ PHP 7.3
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593
- [x] Update Lando Version
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593
- [x] Update Tugboat container
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593
- [ ] phpstan scan see #3775 for context

## Acceptance criteria

- [x] CMS infrastructure supports PHP 7.3
- [x] all modules are compatible with PHP 7.3
- [x] there are no new PHP notices

**Comment by indytechcook** [comment]
This should be bumped up in urgency:  PHP 7.1 is already EOL.  https://www.php.net/supported-versions.php

EOL is defined as:

> A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.

**Comment by indytechcook** [comment]
PHP Unit Failing tests:

```

There was 1 error:

1) tests\phpunit\BulletinQueueTest::testBulletinQueue
Drupal\Core\Entity\EntityStorageException: Trying to access array offset on value of type bool

/app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:846
/app/docroot/core/lib/Drupal/Core/Entity/EntityBase.php:395
/app/tests/phpunit/BulletinQueueTest.php:29

Caused by
PHPUnit\Framework\Error\Notice: Trying to access array offset on value of type bool

/app/docroot/modules/custom/va_gov_notifications/va_gov_notifications.module:74
/app/docroot/core/lib/Drupal/Core/Extension/ModuleHandler.php:403
/app/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php:206
/app/docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:843
/app/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php:500
/app/docroot/core/lib/Drupal/Core/Entity/ContentEntityStorageBase.php:700
/app/docroot/core/lib/Drupal/Core/Entity/EntityStorageBase.php:454
/app/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:837
/app/docroot/core/lib/Drupal/Core/Entity/EntityBase.php:395
/app/tests/phpunit/BulletinQueueTest.php:29

--

There was 1 failure:

1) tests\phpunit\LoginPerformance::testLoginPerformance with data set #0 (2)
Operation took 3.081 seconds which is longer than the benchmark of 2 seconds.

Failed asserting that '3.081' is less than 2.

/app/tests/phpunit/PerformanceLoginTest.php:47

ERRORS!
Tests: 27, Assertions: 62, Errors: 1, Failures: 1.
Script phpunit tests/phpunit --colors=always --exclude-group=disabled handling the va:test:unit event returned with error code 2
```

**Comment by indytechcook** [comment]
The following error occurs when running phpcs.  It occurs several times:

```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated
```

**Comment by indytechcook** [comment]
The current result of failed tests:

```
  va/deploy/0-composer     rm -rf ./docroot/vendor/va-gov/web && composer install --dev --no-interaction --no-progress --ansi | tee /dev/stderr | grep 'Could not apply patch' && exit 1 || true                                                                                                                                 ✔ Passed
  va/deploy/1-cache        drush $DRUSH_ALIAS cr                                                                                                                                                                                                                                                                                 ✔ Passed
  va/deploy/2-update       drush $DRUSH_ALIAS updatedb --yes                                                                                                                                                                                                                                                                     ✔ Passed
  va/deploy/3-config       drush $DRUSH_ALIAS cim --yes                                                                                                                                                                                                                                                                          ✔ Passed
                           drush $DRUSH_ALIAS cr
  va/tests/phpcs           composer va:test:cs                                                                                                                                                                                                                                                                                   ✔ Passed
  va/tests/phplint         composer va:test:lint                                                                                                                                                                                                                                                                                 ✔ Passed
  va/tests/phpunit         phpunit --exclude-group disabled tests/phpunit --colors=always                                                                                                                                                                                                                                        ✘ Failed
  va/tests/accessibility   composer va:test:accessibility                                                                                                                                                                                                                                                                        ✘ Failed (Ignoring)
  va/web/build             composer va:web:build | tee /dev/stderr | grep "Failed to pipe Drupal content into Metalsmith!" -B1000 -C8 && echo "tests.yml | composer va:web:build included the Drupal/Metalsmith error." && exit 1 || echo "tests.yml | Front end site was built! Check $DRUPAL_ADDRESS/static for raw output!"   ✔ Passed
  va/tests/behat           cd tests/behat                                                                                                                                                                                                                                                                                        ✘ Failed
                           behat --colors
```

Lots of errors with PHP Deprecations to look through.

**Comment by indytechcook** [comment]
Updating phpcs with the command:

```
composer req drupal/coder squizlabs/php_codesniffer

Using version ^8.3 for drupal/coder
Using version ^3.5 for squizlabs/php_codesniffer
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Updating squizlabs/php_codesniffer (2.9.2 => 3.5.4): Downloading (100%)
  - Updating drupal/coder (8.2.12 => 8.3.7):  Checking out c11c295765
```

Updating does cause new phpcs failures:

```
❯ lando composer va:test:cs
> phpcs --ignore=*.md,*.min.css,styles.css,wysiwyg.css,*/node_modules/*,*/simplesaml*/* --standard=./docroot/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml docroot/modules/custom docroot/themes/custom --colors

FILE: ...root/modules/custom/va_gov_preview/src/Encoder/StaticEncoder.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 5 | WARNING | [x] Unused use statement
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: .../custom/va_gov_govdelivery/src/Service/ProcessStatusBulletin.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 12 | ERROR | Missing member variable doc comment
 13 | ERROR | Missing member variable doc comment
 15 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: ...pp/docroot/modules/custom/va_gov_migrate/src/Paragraph/Alert.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 16 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: ...s/custom/va_gov_migrate/src/Plugin/migrate/source/VaMenuBase.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 11 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: ...om/va_gov_migrate/src/Plugin/migrate/source/MetalsmithSource.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 69 | ERROR | Missing member variable doc comment
 70 | ERROR | Missing member variable doc comment
 71 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: ...stom/va_gov_migrate/src/Plugin/migrate/source/VaBenefitsMenu.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 17 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: ..._gov_migrate/src/Obtainer/ObtainAndTestPlainTextWithNewLines.php
----------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 17 | ERROR | Missing member variable doc comment
 18 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: /app/docroot/modules/custom/va_gov_bulk/src/AdminModeration.php
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
 14 | ERROR | Missing member variable doc comment
 15 | ERROR | Missing member variable doc comment
 16 | ERROR | Missing member variable doc comment
 17 | ERROR | Missing member variable doc comment
 18 | ERROR | Missing member variable doc comment
 20 | ERROR | Missing member variable doc comment
----------------------------------------------------------------------


FILE: /app/docroot/modules/custom/va_gov_backend/js/script.js
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | [x] Missing file doc comment
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/sass.js
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
  6 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
  9 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 15 | ERROR | [x] No space found before comment text; expected "//
    |       |     Sourcemaps can turned off for prod. Comment this
    |       |     line and the sourcemaps line below if needed." but
    |       |     found "//Sourcemaps can turned off for prod.
    |       |     Comment this line and the sourcemaps line below if
    |       |     needed."
 18 | ERROR | [x] Inline comments must start with a capital letter
 32 | ERROR | [x] No space found before comment text; expected "//
    |       |     Comment this too to remove sourcemaps" but found
    |       |     "//Comment this too to remove sourcemaps"
 32 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: ...pp/docroot/themes/custom/vagovadmin/gulp-tasks/sass-for-build.js
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
  6 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
  9 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 17 | ERROR | [x] Inline comments must start with a capital letter
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/build.js
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
  4 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
  4 | ERROR | [ ] Doc comment short description must be on a single
    |       |     line, further text should be a separate paragraph
 10 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/watch.js
----------------------------------------------------------------------
FOUND 7 ERRORS AFFECTING 6 LINES
----------------------------------------------------------------------
  4 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
  4 | ERROR | [ ] Doc comment short description must be on a single
    |       |     line, further text should be a separate paragraph
  7 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 16 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 17 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 21 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 26 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/sass-lint.js
----------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
  6 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
  8 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
  9 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 17 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 20 | ERROR | [x] No space found before comment text; expected "//
    |       |     ignore: 'design-library/**/_typey**.scss'" but
    |       |     found "//ignore: 'design-library/**/_typey**.scss'"
 20 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 6 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/js-lint.js
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
  6 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
  9 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 10 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/default.js
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
  4 | ERROR | [x] Doc comment short description must end with a full
    |       |     stop
  4 | ERROR | [ ] Doc comment short description must be on a single
    |       |     line, further text should be a separate paragraph
 10 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulp-tasks/pattern-lab.js
----------------------------------------------------------------------
FOUND 25 ERRORS AFFECTING 15 LINES
----------------------------------------------------------------------
  6 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
  9 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 10 | ERROR | [x] Expected 1 space after FUNCTIONScript phpcs --ignore=*.md,*.min.css,styles.css,wysiwyg.css,*/node_modules/*,*/simplesaml*/* --standard=./docroot/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml docroot/modules/custom docroot/themes/custom --colors handling the va:test:cs event returned with error code 2
 keyword; 0 found
 12 | ERROR | [x] Inline comments must start with a capital letter
 12 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 13 | ERROR | [x] Inline comments must start with a capital letter
 13 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 16 | ERROR | [x] Inline comments must start with a capital letter
 16 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 17 | ERROR | [x] Inline comments must start with a capital letter
 17 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 18 | ERROR | [x] Inline comments must start with a capital letter
 18 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 26 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 27 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 29 | ERROR | [x] Inline comments must start with a capital letter
 29 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 30 | ERROR | [x] Inline comments must start with a capital letter
 30 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 33 | ERROR | [x] Inline comments must start with a capital letter
 33 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 34 | ERROR | [x] Inline comments must start with a capital letter
 34 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
 35 | ERROR | [x] Inline comments must start with a capital letter
 35 | ERROR | [x] Inline comments must end in full-stops, exclamation
    |       |     marks, question marks, colons, or closing
    |       |     parentheses
----------------------------------------------------------------------
PHPCBF CAN FIX THE 25 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------


FILE: /app/docroot/themes/custom/vagovadmin/gulpfile.js
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
  1 | ERROR | [x] Missing file doc comment
 35 | ERROR | [x] Expected 1 space after FUNCTION keyword; 0 found
 60 | ERROR | [x] Expected 1 newline at end of file; 0 found
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by indytechcook** [comment]
Patched `node_link_report`: https://www.drupal.org/files/issues/2020-03-19/call_parent_class-3120976-1.patch

**Comment by indytechcook** [comment]
GraphQL needs an update: https://github.com/drupal-graphql/graphql/issues/982

**Comment by indytechcook** [comment]
The GraphQL full error stack from the behat test:

```
      │  stdClass Object
      │  (
      │      [wid] => 576756
      │      [uid] => 1316
      │      [type] => php
      │      [message] => %type: @message in %function (line %line of %file) @backtrace_string.
      │      [variables] => Array
      │          (
      │              [%type] => Notice
      │              [@message] => Drupal\Core\Render\Markup Object
      │                  (
      │                      [string:protected] => Trying to access array offset on value of type bool
      │                  )
      │
      │              [%function] => Drupal\graphql\Routing\QueryRouteEnhancer->enhance()
      │              [%file] => /app/docroot/modules/contrib/graphql/src/Routing/QueryRouteEnhancer.php
      │              [%line] => 36
      │              [@backtrace_string] => #0 /app/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Trying to acces...', '/app/docroot/mo...', 36, Array)
      │  #1 /app/docroot/modules/contrib/graphql/src/Routing/QueryRouteEnhancer.php(36): _drupal_error_handler(8, 'Trying to acces...', '/app/docroot/mo...', 36, Array)
      │  #2 /app/docroot/core/lib/Drupal/Core/Routing/Router.php(260): Drupal\graphql\Routing\QueryRouteEnhancer->enhance(Array, Object(Symfony\Component\HttpFoundation\Request))
      │  #3 /app/docroot/core/lib/Drupal/Core/Routing/Router.php(131): Drupal\Core\Routing\Router->applyRouteEnhancers(Array, Object(Symfony\Component\HttpFoundation\Request))
      │  #4 /app/docroot/core/lib/Drupal/Core/Routing/AccessAwareRouter.php(92): Drupal\Core\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
      │  #5 /app/docroot/vendor/symfony/http-kernel/EventListener/RouterListener.php(113): Drupal\Core\Routing\AccessAwareRouter->matchRequest(Object(Symfony\Component\HttpFoundation\Request))
      │  #6 [internal function]: Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
      │  #7 /app/docroot/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
      │  #8 /app/docroot/vendor/symfony/http-kernel/HttpKernel.php(127): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
      │  #9 /app/docroot/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
      │  #10 /app/docroot/modules/contrib/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(67): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #11 /app/docroot/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #12 /app/docroot/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #13 /app/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #14 /app/docroot/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #15 /app/docroot/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #16 /app/docroot/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #17 /app/docroot/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #18 /app/docroot/core/lib/Drupal/Core/DrupalKernel.php(694): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
      │  #19 /app/docroot/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
      │  #20 {main}
      │          )
      │
      │      [severity] => 5
      │      [link] =>
      │      [location] => http://va-gov-cms.lndo.site/graphql
      │      [referer] => http://va-gov-cms.lndo.site/sections
      │      [hostname] => 172.18.0.2
      │      [timestamp] => 1584715623
      │  )
```

**Comment by indytechcook** [comment]
Patch for https://www.drupal.org/project/paragraphs_browser/issues/3057621 to remove notices.  This patch does not apply to our version.  Need to create a custom patch.

**Comment by indytechcook** [comment]
Code was been deployed, not server need to be updated.

**Comment by ElijahLynn** [comment]
I see there is a blocker on this by Drush 10. Let's post more of a _why_ that is here in this issue.

**Comment by jonpugh** [comment]
FWIW...

Major progress in removing tech debt of aegir/provision and devshop already happened this week. 

It addresses the root cause of the Drush 9/10 blocker, separating platform processes from site processes. 

Follow https://github.com/opendevshop/devshop/pull/539. I'm praying to get this merged in time for Drupal core release window tomorrow.

A follow up task is to review the composer templates and ensure they work OOB. Since these include Drush 8, I'll use this as the chance to create tests to validate drush8/9/10 support.

**Comment by indytechcook** [comment]
Here is the php 7.4 code sniffer for devshop: https://gist.github.com/indytechcook/34ba662a382e2c8f0c83648aef6a7c1a

Running this command: `docker run --rm -v $(pwd):/app vfac/php7compatibility 7.4 -d memory_limit=1G .`

**Comment by indytechcook** [comment]
Just adding a note here https://www.drupal.org/project/menu_breadcrumb/issues/3199016

**Comment by ElijahLynn** [comment]
I am working on the BRD portion of this in https://github.com/department-of-veterans-affairs/devops/pull/6559 and I'll be adding a REMI Ansible role so we can pull in `php74` as it currently isn't available in Amazon Linux 1 repos.

**Comment by ElijahLynn** [comment]
On the BRD front, we are blocked on PHP 7.4 as we are using Amazon Linux 1, or CentOS 6'ish. The Remi repository only offers 7.3 for CentOS 6 and a comment by Remi Collet said this in regards to 7.4 on CentOS 6:
> Sorry but really too much work and perhaps even not possible

source: https://forum.remirepo.net/viewtopic.php?pid=10927#p10927

> Sorry, PHP 7.2 and 7.3 was already a terrible nightmare

source: https://github.com/remicollet/remirepo/issues/131#issuecomment-560294168

The Drupal 9 upgrade does have a minimum requirement of PHP 7.3 so we discussed in this [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1614983007447400) and it I was not interested in blocking the momentum of our D9 upgrade so I attempted to get PHP 7.3 working instead of 7.4, and in the end I was successful (see thread for all the glory) and the changes are pushed to the devops PR! I updated the AC in this ticket to reflect 7.3 instead of 7.4. 

We will need to wait until we move to the new ArgoCD container deploys for PHP 7.4.

**Comment by ElijahLynn** [comment]
With PR https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4593 and https://github.com/department-of-veterans-affairs/devops/pull/6559. 

Lando
```
❯ lando ssh --user root
root@cdaad1124d42:/app# php -v
PHP 7.3.27 (cli) (built: Feb  9 2021 20:26:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
```

Tugboat
```
root@php:/var/lib/tugboat# php -v
PHP 7.3.27 (cli) (built: Feb  9 2021 20:04:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
```

BRD
```
[root@ip-10-247-96-150 ~]# php -v
PHP 7.3.23 (cli) (built: Oct 21 2020 20:24:49) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.23, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.23, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by ElijahLynn** [comment]
Oh, the environments to test this on are:
* BRD: https://test.dev.cms.va.gov/user/147
* Tugboat: https://cms-php73-upgrade-xv24z9am4vg65xlklxdknneu8discatv.ci.cms.va.gov/

**Comment by ElijahLynn** [comment]
There is one notice I see after tests ran on CMS-TEST DEV:
```
Notice: Undefined index: #type in Drupal\Core\Form\FormHelper::processStates() (line 208 of /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormHelper.php)
#0 /var/www/cms/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/cms/do...', 208, Array)
```

http://internal-dsva-vagov-dev-cms-test-1790117836.us-gov-west-1.elb.amazonaws.com/node/16543/edit

**Comment by indytechcook** [comment]
I've seen this one before outside of this upgrade.  Something we should follow up.

> Notice: Undefined index: #type in Drupal\Core\Form\FormHelper::processStates() (line 208 of /var/www/cms/docroot/core/lib/Drupal/Core/Form/FormHelper.php)
#0 /var/www/cms/docroot/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/cms/do...', 208, Array)

> Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException: Not acceptable format: static_html in Drupal\Core\EventSubscriber\RenderArrayNonHtmlSubscriber->onRespond() (line 30 of /var/www/cms/docroot/core/lib/Drupal/Core/EventSubscriber/RenderArrayNonHtmlSubscriber.php).

This comes from devshop used code.  Using Drupal to generate the preview page.  This piece of code generate the URL for the preview button and since this is not on proper BRD then it defaults to the else: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/docroot/modules/custom/va_gov_build_trigger/src/Form/PreviewForm.php#L98
