### ISSUE TITLE
Sprint 65 - Facilities | Aug 15 - Aug 29

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10054]
<details><summary>Quarterly Initiatives</summary>
List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9659  VBA MVP
- #9655 Lovell 
- #9096 Covid status post-launch
</details>

<details><summary>Issue icon legend</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task
</details>

<details><summary>OOO</summary>

Who | When | Backup 
----- | ------ | ------- 
Aslan | 8/15 | Dave P
Roger | 8/26 | David S

</details>

## Facility COVID status post-launch
_No action in Sprint 65
Soft target Sprint 66 for next steps removing Covid status and associated messaging and content modifications_

## VBA Facilities

**Collab Cycle** 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10206 Collab cycle intake issue
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10207 Schedule collab cycle kickff
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10209 Schedule CMS collab cycle kickoff

**Design**
- [ ] #10234 🥅 @davidmpickett 
- [ ] #10186 @ContentBrewmaster 
- [ ] #10192 @jcklpe 
- [ ] Stretch #10252 @jcklpe 

Action Items
- [ ] Denise - create broad CM epic across research streams 
- [ ] Create specific tickets under Business research? https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5872 

Engineering 
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10212  VBA content audit 

### Lovell #9655 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10214 Lovell Midcycle review 
Blocking other Lovell progress
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10163
- [ ] #9847 

**Engineering** 
Side nav can be pulled in #10167 
- [ ] #10166 <- in work in 64 FE menu bifurcation
- [ ] #10169 FE breadcrumbs 
- [ ] #10170 CMS breadcrumbs

- [ ] #9945 Lovell: Build step bifurcation Start this sprint, blocked by field_administration  
- [x] Create duplicate alias pattern - Find Ticket 
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9950

###  #9318 Hours

- [ ] #9357 Implement use facility's hours 

- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10184

## Blocked

<details><summary>Blocked by V1</summary>

- [ ] #8017  Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
  - [ ] #4411 Push CAP data 

</details>

- [ ]  #9849 = Waiting on VHADM

## Other

- [ ] #9924 Other nearby vet centers
