### ISSUE TITLE
Visual indication of all the results in the list of the Facility Locator

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#10083]
## User Story or Problem Statement

How might we better indicate when showing a set of results in the facility locator that the returned result list is longer than what is seen?

![Screen Shot 2022-08-05 at 10 19 37 AM](https://user-images.githubusercontent.com/766573/183110364-f6787ace-c744-4e24-ace4-0d4b9ba58765.png)

## Acceptance Criteria
- [ ] Result list appears to be longer than what is currently shown, meaning that you can scroll to see more results.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
@omahane  I see a scrollbar when I have more results than initially appear in the results area.  I tested in both Chrome and Explorer at different magnifications (see screenshots).  This [page ](https://www.hellotech.com/blog/scroll-bars-disappearing#:~:text=Fortunately%2C%20if%20you're%20experiencing,button%20to%20save%20your%20preferences.) refers to a Mac system setting.  Could that be the culprit?

I have a vague memory of coming across this before. that Mac's sometimes won't display the scrollbar for some tools/controls?  

![image](https://user-images.githubusercontent.com/62269210/184569783-7e8e8209-5b63-40d9-a525-eaf7067b9d5a.png)

![image](https://user-images.githubusercontent.com/62269210/184570102-77de004b-0f09-4284-9ef3-89172957da41.png)

**Comment by mmiddaugh** [comment]
Can we consider this during [mobile map enhancement](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16001) work?

**Comment by Agile6MSkinner** [comment]
Not an issue anymore. Closing as not necessary
