### ISSUE TITLE
Node link report design iteration

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#1009]
### User Story or Problem Statement

As a content editor, I want to know which links in my content are working and which need attention, so that I can ensure quality content and avoid causing problems when publishing.

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

### Related artifacts and issues
* [Node link report - Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1582047974352/d8729998a7a3ea6cdd6aae90b83305f46bfa2483) First iteration of the words Kauff-e worked on
* Swirt's issues #844 & #845

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [x] User research
- [x] Design
- [x] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [x] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [x] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by swirtSJW** [comment]
This issue of the writing has been carried out and merged into the contrib module https://www.drupal.org/project/node_link_report/issues/3116017

Working on making them collapsible now.  https://www.drupal.org/project/node_link_report/issues/3116023

**Comment by swirtSJW** [comment]
The code has been merged.  I am moving this back to In progress though because now we have to work out release notes and messaging before we re-enable the display of this to all editors.  (right now it is limited to just content admins)

**Comment by rachel-kauff** [comment]
Added this to the release notes queue in AT. Will start drafting something. @kevwalsh I assume I should start drafting the release note toward the future when we enable this for all editors?
