### ISSUE TITLE
Create New Knowledge Base Article(s)

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10157]
## Background

The need for KB articles can happen in multiple ways. Most often, requests for these new KBs come from:

- product teams
- other Sitewide Crew teams like Sitewide Content
- a need arises as a result of editor feedback
- Needed for change management

This is not an exhaustive list.

This epic will serve the purpose of tracking all new knowledge base requests until a process is formalized. 

### User Story or Problem Statement

As a CMS editor, I need knowledge base articles so I can learn about various topics that help me provide veterans with accessible and updated content. 

As a CMS editor, I need knowledge base articles to help me learn about CMS topics so I can depend on myself, rather than the helpdesk, to complete my assigned tasks.

As a helpdesk team member and/or Sitewide CMS team member, I need a way to track what new KB articles have been requested so I can create them in a uniform way within the standard UX writing guidelines

### Affected users and stakeholders

* CMS editors of all products
* Sitewide Crew teams

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that tracking KB article requests will achieve greater visibility and tracking for new articles. We'll know that to be true when stakeholders and teams have an understanding of where to request articles. 

## Acceptance Criteria
- [ ] KB article tickets are creating within this epic on an ongoing basis
- [ ] Sitewide CMS works new KB requests into sprints as capacity allows
- [ ] Relay info on new KB articles to helpdesk

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Hi @FranECross this is a CMS Team Epic. Can you confirm with @kellylein prior to closing? There are a lot of other items in the works that relate to updating articles.
