### ISSUE TITLE
Recurring Events: Empty column in Date and time table in CMS Events form

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#10156]
## Description
On the Events content type edit screen there is a date and time table. This has the option to show or hide row weights but the entire column is empty, even when shown.  Empty cells/columns can cause confusion for users

## Screenshot
![image](https://user-images.githubusercontent.com/106678594/184147592-b01b237a-b736-4467-a123-710ac0ba983a.png)

## Accessibility Standard

WCAG version 2.0 A, [Criterion 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html)

## Tasks
- [X] Determine if content should or should not be in this column _Answer: there shouldn't be any content in the column_

## Acceptance Criteria
- [ ] Fix the issue.
- [ ] Accessibility review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsasser** [comment]
Confirmed in prod: 

![Screenshot 2023-12-12 at 2 52 33 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/0485524f-9399-472c-8c5f-d41d18e3797d)
