### ISSUE TITLE
EPIC: VBA - Editor Current State Usability Research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10185]
## Background
#9659 

### Team
- Denise Eisner

### Method
- Structured, remote conversations with VBA MVP employees

### Timeline / Dependencies
- Begin in late September 2022
- 🛑 Need MVP facilities finalized

### User Story or Problem Statement

As a designer, I need to understand the VBA editor perspective so I can make design recommendations for the VBA product.

### Affected users and stakeholders

* CMS editors of VBA
* Facilities Developers
* VBA Office of Strategic Engagement staff

### Hypothesis

We believe that our research will uncover new context among the 6-12 MVP editors for how they will approach the task of gathering, creating and publishing content about their facilities using Drupal CMS. 

We'll know that to be true when we synthesis and share the findings of research with the product team working on the facilities product for a full roll-out.

## Assumptions
* The MVP editors will have low levels of understanding of how 508 compliance relates to publishing facility content.
* The MVP editors will have little to no experience working with structured content.

We will conduct interviews with all the editors identified for the MVP to validate our assumptions and develop the change management strategy and plan for the full roll-out.

## Research Questions

**VBA Editor Persona Questions**
- Number of potential editors (if each editor has a backup) and locations
- Reporting structure
  - Who they take direction from
- Level of understanding (high, medium, low) of web principles (accessibility, web writing, etc.)
  - This will relate to how hardened the content model is
- Other editor responsibilities and which take precedence, if any, over the website
- How editors view the purpose of the website in relation to other channels
- How work priorities are established and monitored
  - Estimated percentage of role that would be dedicated to the website
- Previous experience publishing web content
- Preferred way to learn how to use, or get support for, computer applications and tools at work
  - This will inform training approach
- Preferred way to get updates on changes or additions to the website CMS
  - This will inform change management approaches 

**Detailed VBA Facilities Content Questions for Editors**
- Is the service delivery the same across all locations nationally or locally nuanced? (What specifics would local editors want/need to adjust?)
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?
- Are Events National? Local? Hybrid? And what is the maintenance load?
- Are Spotlights National? Local? Hybrid? And what is the maintenance load?
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?
- Is there a need for timely situational updates related to things such as parking or COVID facility status? 
- Is there an easily identifiable Top Tasks for editors? Can we quantify: Here are the Top XX things I do most frequently when currently updating the site, these other tasks are much less frequent.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [x] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [x] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)
  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by davidmpickett** [comment]
In sprint planning today, Dave C mentioned that he wants the Editor Research to involve showing Drupal designs to the editors. Maybe more of a usability testing angle?

**Comment by ContentBrewmaster** [comment]
@davidmpickett that's how I read that research request.

**Comment by davidmpickett** [comment]
Closing in favor of tracking in follow up via https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9954
