### ISSUE TITLE
EPIC: VBA - Veteran Research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10191]
### User Story or Problem Statement

As a veteran, I need information about benefits locations and regional offices so I can receive my needed benefits.

### Affected users and stakeholders

* Veterans searching for information about the VBA regional offices and benefits offices. 

[Research Repo](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/research/2022-8-veteran-facing)

### Hypothesis

This is generative qualitative research so we don't really have much of a hypothesis so far, it's just getting familiar with the veteran experience and learning how they think and see things. 

### Research Questions

- Participant definition 
  - Has visited a VBA facility in last 6 months (🛑 Limit to MVP sites? )
- What other top task is available (e.g. Talk to someone online?) and do Veterans want that?
- How important to the Veteran is the relationship of "child" locations to the RO
- Do Veterans understand the different types of facilities (or does that matter?)
- What else do Veterans need in order to be prepared for a visit 
  - “What information do you wish you had before your last VBA visit?”
- What are the questions Veterans want answered by calling the phone number(s)?
- Is a list of Veteran Service Organizations (VSOs) located at that facility important?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@jcklpe Please take some time this sprint to update the description of this epic. Should more or less map to the research plan

**Comment by davidmpickett** [comment]
Research findings are documented so this epic is complete
