### ISSUE TITLE
Analytics: Fix Promo Banner click tracking

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10228]
## Description

When the PACT Act promo banner went live, we found out too late that it's not being tracked in GA despite being a design system component.

Brooks Johnson from the Design System team pointed out [in slack](https://github.com/department-of-veterans-affairs/vets-website/blob/57658f5846ee378309cc774133ef7e1aabd41db2/src/platform/site-wide/component-library-analytics-setup.js#L8-L203) how to wire up the promo banner component.:

> The component is already [firing the appropriate event](https://github.com/department-of-veterans-affairs/component-library/blob/3fc3b7d33d9cfe5ac51a54d7aed0b445c26cfe05/packages/web-components/src/components/va-promo-banner/va-promo-banner.tsx#L87-L100). It looks like the web component needs to be added to [this list in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/57658f5846ee378309cc774133ef7e1aabd41db2/src/platform/site-wide/component-library-analytics-setup.js) in order to be tracked.

## Acceptance Criteria
- [ ] Modify the vets-website code
- [ ] Work with Wes to validate using the AdSwerve debugger in Chrome

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Design System team fixed this when we raised it. Should be deployed Mon, 8/15/22.
