### ISSUE TITLE
Queries refactor: Expandable Text paragraph

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10227]
## Description
As a second part to the refactoring, components that were refactored to separate Drupal data mapping from a component's props should be further refactored to follow the next-drupal-query paradigm. 

## Acceptance Criteria
- [x] Any data mapping logic & params are moved from a component's `dataService` file into a the queries directory, setting up an actual data query where needed
- [x] Tests are written for the data mapping/formatter piece of the query.
- [x] The data service file is removed

## Tasks
- [x] Move data mapping logic & params from dataService to the queries directory
- [x] Unit Tests are written for the data mapping/formatter.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
