### ISSUE TITLE
Add Docusign link to appropriate Find-a-form pages

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10243]
**BLOCKED REASON:** Dependency on Forms DB that doesn't have a clear path to resolution (8/14)

## Background

The VA is required to provide a Docusign experience to Veterans for forms, enabling filling out and e-signature. Once the data (expected to be a link) is available in the Forms DB, we need to migrate it into the CMS and display in the front-end.

The first business unit we've heard from is VA Life Insurance. Stakeholders:
- Bowo Akinlabi-Oladimeji <b.akinlabioladimeji@docusign.com> (Docusign employee)
- Primous, April <April.Primous@va.gov>
- Clarke, Nigel A. (ByLight) <Nigel.Clarke@va.gov>
- Jordan, Joe VBAPHLINS <joe.jordan@va.gov>
- Ellis, Daniel G., VBAPHILINS <Daniel.Ellis1@va.gov>

At this time (8/12/22) the architecture has not been discussed. Wes connected the group above with Kevin Reid (Forms DB PM) on 8/11/22.

### User Story or Problem Statement

As a Veteran, I want to find a Docusign link alongside PDF download link so that I can submit appropriately e-signed forms more easily.

## Assumptions
* Forms DB is the right source-of-truth, as it is for PDF links

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Docusign link added to FormsDB migrates to CMS nightly
- [ ] Front-end makes link available
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Kevin Reid owns the VA Forms DB and would have to update the Forms DB to integrate with Docusign. Forms DB is in maintenance only contract, so thus far: Forms DB does not intend to integrate this functionality for us to receive downstream.

**Comment by FranECross** [comment]
Closing as a no  op
