### ISSUE TITLE
Digest Schema.org with respect to Benefit Detail Epic

### ISSUE THREAD

**Issue by chri5tia** [department-of-veterans-affairs/va.gov-cms#10240]
## Description

Essentially, schema org is a way to standardize the way machines and bots find and provide information, by encasing that information in special HTML. This will be useful for the chatbot, and other machines.

Explore existing schema.org schemas to identify ones that might enable our Benefit content model to deliver benefit data directly to organic search results. E.g., Schema.org model for [gov’t services](https://schema.org/GovernmentService).

## Acceptance Criteria
- [x] Read schema.org
- [x] Understand what it is, what it does, how it works
- [x] Explore the drupal.org module `schemadotorg` to see how it works and how it could be utilized

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@jilladams, FYI this is technically unplanned work, but IRL Christia was clearly underutilized coming out of planning. we probably would have planned this if we'd had more time in planning.

**Comment by chri5tia** [comment]
##Schemas
Government service:
https://schema.org/GovernmentService

Government organization:
https://schema.org/GovernmentOrganization

##Shortlist


## How to
- uses special vocabulary along with the [Microdata](http://en.wikipedia.org/wiki/Microdata_(HTML)), [RDFa](http://en.wikipedia.org/wiki/RDFa), or [JSON-LD](http://en.wikipedia.org/wiki/JSON-LD) formats
- `<div itemscope>` and `<[HTML tag item] itemprop="schemavocabulary">`

## Docs
https://schema.org/docs/gs.html

##Drupal

### Schema.org Blueprint Module
https://www.drupal.org/project/schemadotorg

- out of the box functionality
- can create custom entity types and fields
- extendable
- active
- dev version (there is [room here to help contribute](https://www.drupal.org/project/schemadotorg/issues/3279761), though only a few outstanding issues)

**Comment by jilladams** [comment]
I think this is a reasonable start. @chri5tia 3 notes/questions: 
1. it's probably worth reviewing your takeaways with Daniel (informally) next week, just so he's aware of the outcome here for anything he's working on. 
2. Is it possible to subscribe to updates about the blueprint module so we can be aware when it reaches stable release?
3. Can you add a note just re: how this does / doesn't apply to the Benefit Detail page work? (I'm not clear on that & have forgotten where this ticket came from, or maybe it came up while I was out during the sync with Danielle?) In any case: it would be good to tie it back to that work and how it could help us if blueprint was available / what we'd gain.

**Comment by chri5tia** [comment]
This would most likely need to be considered as full site work and implementation, with FE and design work as well. Not restricted to benefits detail hub but it came up during that convo. We may be able to restrict it to just those pages as a pilot.

**Comment by jilladams** [comment]
I made Christia give me a "for dummies" summary since I missed the original conversation: 
Because blueprint module is in pre alpha, didn't spend much time on it. Metatags module is already installed on VA.gov CMS & meta tag submodule exists, which allows slow certain sections to be tagged appropriately per [schema.org](http://schema.org/) vocabulary, and integrates with the metatags module. That would allow us to more easily offer up those pieces of content to chatbot.

**Comment by jilladams** [comment]
Next step would be:
* bring this to Benefit Detail hub planning meetings
* If we want to implement Metatags: would need a ticket to describe how & why & for what based on the final content model plan
