### ISSUE TITLE
DSN: Start creating VBA wireframes in Sketch

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#10252]
## Tasks 
- [x] Assess 2019 wires in meeting 
- [x] Assess delta between what Vet Centers are vs VBA wireframe proposed - we have design components we didn't have then - which might we use?
- [x] Determine if current wireframes are suitable 

## Acceptance criteria 
- [ ] Get PO sign off 

Old [Sketch File](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/design/VBA-Office-template.sketch) - we are not beholden to this, but might be a good base to build from

**Comment by davidmpickett** [comment]
From sprint planning - if Aslan has spare capacity this sprint, (Veteran research takes priority) he should start creating the basic skeleton of wireframes for VBA

**Comment by davidmpickett** [comment]
Pulling this back up per refinement convo

**Comment by jcklpe** [comment]
I know that I'm rolling off this contract, but I had not seen this ticket till now. Just wanted to add that I think the old VBA sketch file looks pretty good. I wasn't aware that we had this already. Is there a reason this design isn't already considered our current design?  
  
Like Conlon was wanting me to do some wires before I left but... this already looks done to me. What's missing? Or am I missing something?  
  
@davidmpickett

**Comment by davidmpickett** [comment]
These wires were made before the VAMC and Vet Center products were built as MVPs, so I'm not sure how well they match the "Vet Center + Events" model that Dave Conlon keeps referencing as the working theory for VBA MVP. 

The action item might be more of a cross-check and an update rather than starting from scratch.

**Comment by jcklpe** [comment]
Here's a preview: 
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/9451726/189705607-a5d21491-c9f0-4a07-ae0c-7dd0d47331ec.png">

From what I can tell it follows the VAMC patterns etc pretty well.

**Comment by jcklpe** [comment]
![](https://user-images.githubusercontent.com/9451726/190267063-9c0ee2cc-3afe-4fe5-980f-e33b97734b81.png)

**Comment by jcklpe** [comment]
Wireframe annotation notes:  
Background: These wireframes were originally made in 2019. I'm annotating them to see where the design suits our current requirements.   
  
1\. This is header is pretty much standard, except for the addition of "My VA". These differences shouldn't matter for a dev.   
  
2\. Standard breadcrumbs. Works the same way as anywhere else. 

3\. This pattern use of a sidebar is pretty much standard with the modern website and the patterns we see with sidebars on a VAMC website.   
 

![](https://user-images.githubusercontent.com/9451726/190267879-38bdf758-415e-4f5d-8f95-137f21892c0c.png)

Houston VAMC for comparison.   
  
It's worth noting that the current version of the sidenav differs from [the current VA design system sidenav](https://design.va.gov/components/sidenav):

![](https://user-images.githubusercontent.com/9451726/190268159-ce3817ff-da24-4eb4-a9ca-582f8a0b0687.png)

Why this is I don't know. It would be my recommendation that we adhere as strictly to the design system as possible barring some very clear reason not to. I think this is the best approach even if it means making the VAMCs and the Regional Offices not match. Hopefully updating the VAMCs to match the current version of the design system would also not be too great a lift. Those are development concerns beyond my knowledge to comment though.   
  
4\. Hero Image of the Regional Office. This seems pretty standard. Vet Centers have a similar thing, as seen in the Houston image above.   
  
5\. This button group is also pretty standard to the Vet Center patten. The current Vet Center also includes a button for register for care. If that is a function we want the Regional Office to have I don't see any issue with adding that button too.   
  
6\. Intro text again very similar to the Vet Center stuff. Looks good to me.   
  
7\. The locations preview page is also very similar to the the Vet Center.   
  
8\. Vet center and the VBA wireframe use a button for moving to a new location. IDK why that was done, the semantic seems wrong, links versus buttons issue. But also not really that big deal. I wouldn't break the pattern without doing more research on if there was a reason why the button was used instead of a link, and doing some testing to confirm any change.   
  
9\. Again very similar to the vet centers. I don't know about what research went into picking these items. I feel like in general there is a lot of stuff on this page. I feel like that about a lot of the designs currently in the modernized VA. I guess this is important. Maybe? I have no clue. I don't have any research to tell me why it is here. The icons look nice and they "break up the visual flow" of the page but I'm not really sure if they necessary. I feel like that with a lot of the designs I see on the VA website. There seems to be variance in how information is presented but I can't locate what the underlying reason is other than "to keep everything from looking so samey". And if everything is going to "look samey" without non-semantic visual design deviations, then perhaps the information architecture of the page should be re thought. Again, I have no research so it's hard for me to contextualize why certain decisions were made.   
  
Also worth noting that no parts of this section's pattern appears in the VA design system. This work should be standardized and upstreamed. I would recommend modeling it after something [in this genre](https://component.gallery/components/list/).    
  
10\. In the spotlight. But everything is the spotlight, right? Again, not sure why this stuff deserves it's own section as compared to the above section. Same basic criticism applies here. This uses the "no icon" variant of the VA design system Alert component. Personally I think this is an inappropriate use of an alert. It seems to be using the component as a means of morphing it's visual rather than adhering to the underlying semantic of the Alert component.   
  
Also this is the same as on the Vet Centers.  
  
11\. Stories works the same as on the Vet Centers website. Looks good to me. Same quibble with the button thing as with the locations page.   
  
Also worth noting that the Locations, Stories, and Events preview sections all basically serve the same repeating feed of (different) queried items. This might be a good candidate for an [Experimental Design Request](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/new?assignees=&labels=vsp-design-system-team%2C+experimental_design&template=3_experimental_design_request.md&title=Experimental+Design+%5Bcomponent+or+pattern+name%5D). 

12\. Very similar to current Vet Centers. Looks good to me.   
  
13\. Okay this is a call out I actually understand why it exists. It's all the different ways to stay in the loop on this office. Looks good. Very similar to the current Vet Center.

**Comment by jcklpe** [comment]
# Cross Reference Features

From [this page](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/regional-offices/design) we have these key features:

Note all my comments are in parentheses and italicized. There are some parentheticals in this list from the original document but they are not italicized. 

*   Some Top tasks _(I believe this follows the annotation 5, except that I don't see a CTA for Ask VA funnel)_ 
    *   Make an appointment
    *   Ask VA (AVA) funnel
*   Basic location information _(This appears to be mostly represented by the wires but will note where lacking_)
    *   Address, link to directions
    *   Photo of facility
    *   Contact info e.g. phone, contact centers (what are the questions Veterans want answered by calling the phone number(s)?) 
    *   Operating status _(appears to be missing)_
    *   Prepare for your visit _(I assume this is available on the Location details pages)_
        *   Parking
        *   Public transit
        *   What to bring (or is this in services?)
*   Other Locations (photo, location, hours, contact, services) _(I assume this would be on the Location details page)_
*   Services _(Not sure where this is. It may just be behind the "view all services" button up top)_
    *   Location of service at that facility
    *   Hours of service (if different than facility)
    *   Contact info for that service (if different than facility)
    *   How a Veteran can make an appointment for that service
    *   Is there an online version of the service/tool
*   Events _(covered by annotation 12)_
*   Subscribe to updates _(covered by annotation 13)_
*   Spotlights _(covered by annotation 10)_

**Comment by jcklpe** [comment]
There doesn't appear to be anything not covered by this 2019 wireframe in the Feature list, at least within the first page of the Regional Office page which is what I have been asked to focus on this sprint.   
  
My general assessment on this stuff is: it seems pretty much like the current VAMCs. And that seems fine. I don't see any reason to create a bunch more disparate patterns for no good reason. I do have some general issues with the VA website design on the whole (as I mention [in this comment, point 9](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10252#issuecomment-1247374456)). I don't see why there is a spotlight section and Manage your benefits online (annotation 9). They both seem to be competing to give similar types of information.   
  
And it's not clear if the Services feature is fully fulfilled by whatever page the "View all Services" link is supposed to take the User to.

**Comment by jcklpe** [comment]
Worth noting that previous comments on this page said that the wires were like the Vet Centers. But I meant "VAMC". I had that open in another tab. They're actually pretty different from the Vet Centers. It isn't clear to me why we don't have one template for all these pages.

**Comment by jcklpe** [comment]
# Vet Center wireframe annotation notes

This is similar to the VAMC notes but instead comparing the wires to the current Vet Center pages. Example [found here](https://www.va.gov/boston-vet-center/). 

1.  Basically the same. 
2.  Same
3.  Vet Centers doesn't have a side nav
4.  Vet Centers doesn't have a hero image. 
5.  Vet Centers doesn't have a top tasks button group. 
6.  The wires and the current Vet Centers both have similar intro text sections. 
7.  Vet Center page only shows the location information for the specific vet center. This more detailed information better follows all the requirements laid out in the Features list above. 
8.  n/a 
9.  Not sure if there is a direct comparison between the "Manage Benefits Online" section of the VBA wireframes and anything on the Vet Center page.
10.  Both pages appear to have "Spotlight" sections but the Vet Center's implementation is substantially different in visual composition. 

Vet Center Spotlights:

![](https://user-images.githubusercontent.com/9451726/190280042-c3d94908-4f13-4457-bd8b-386cbc851e65.png)

11\. Does not appear to be a Stories section on Vet Center

12\. Events appears to be included in the Spotlight. There is no comparable Events focused section (as on the VBA wires) on the Vet Centers page. 

13\. Vet Centers does not appear to have any sort of way to subscribe for updates as the VBA wires show. 

Major thing that Vet Centers has that the VBA does not is extensive accordion lists of the Services at that location.

**Comment by jcklpe** [comment]
Proposed Site Map for VBA:

*   Regional Office Page
    *   Services
        *   Page listing all services. 
    *   Locations
        *   Main Location details page
        *   Child Location details page
    *   Events
        *   Event details pages
    *   Stories
        *   Story details pages
    *   News Releases
        *   New Release details page
    *   About Us
    *   Contact Us

This site map is based on analysis of the 2019 wireframes side nav and comparison to the VAMC pages and the needs listed on the Features List linked above.

**Comment by jcklpe** [comment]
A previously created Site Map: [https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9)  
  
 

![](https://user-images.githubusercontent.com/9451726/190830696-42e7757a-911a-4689-b85d-c39475392899.png)

**Comment by jcklpe** [comment]
I wrote a general assessment of this [in this comment here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10252#issuecomment-1247387035) but I think this deserves a second draft of that for clarity on a few points. 

# Major Takeaways:

*   VBA wireframes basically follow the VAMC pattern. 
*   This seems fine by me, and it should fulfill all requirements laid out in the features list linked above. 
*   I would advise against proliferating additional page level patterns (Templates) unnecessarily. 
*   Major difference between the VBA/VAMC pattern and the Vet Centers pattern is that Vet Centers lacks any sort of child/parent relationship.
