### ISSUE TITLE
queries refactor: personProfile

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10261]
## Description
As a second part to the refactoring, components that were refactored to separate Drupal data mapping from a component's props should be further refactored to follow the next-drupal-query paradigm. 

## Acceptance Criteria
- [x] Any data mapping logic & params are moved from a component's `dataService` file into a the queries directory, setting up an actual data query where needed
- [x] Tests are written for the data mapping/formatter piece of the query.
- [x] The data service file is removed

### Tasks

- [x] Map query data 
- [x] Refactor component
- [x] Write snapshot test for new query
- [x] Storybook if it makes sense
- [x] Verify test coverage 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
