### ISSUE TITLE
EPIC: VBA MVP Change Management Research

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#10276]
## Background
Between 5 and 10 VBA facilities will be involved in the MVP for publishing VBA facility information in Drupal starting in Q3-Q4 2022. 

### User Story

As the **change management lead** working on VBA discovery, I need to understand the context for MVP editors who will use Drupal CMS so that I can build a change management strategy and plan for the full roll-out to all VBA facilities.

### Affected users and stakeholders

* CMS editors of VBA MVP facility product
* OCTO-DE (product owner)
* VBA MVP facility leadership (stakeholder)
* VBA Office of Strategic Engagement (stakeholder)

### Hypothesis

We believe that our firsthand knowledge of VBA MVP editors' behaviours, goals, motivations and constraints will help both our product design efforts as well as VBA editor's adoption of the CMS during the full rollout. We'll know that to be true when:
- editors find the MVP prototype easy to understand and use during testing and interviews
- there are minimal support tickets created with the help desk
  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Closing to fix linking error to issues.
