### ISSUE TITLE
Feature Request via Editor: Stories content type should allow more than one image

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#10283]
## User Story or Problem Statement

As an Editor at VA [Cityname], I would like to publish a Story about annual award recipients that shows all of their photos so that I can give proper credit and recognition to each individual.

or

Problem description. How might we allow for multiple photos/images to be published within one Story?

**Request origin:**  Enhancement was suggested by Stephen Tyler, Visual Information Specialist @ VA Tuscaloosa during a Teams call

## Acceptance Criteria
- [ ] Editors can publish a Story containing more than one image

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by laflannery** [comment]
This is a Facilities product not CMS and this particular ticket is a dup of #15718. I think this should probably be closed in favor of that one @xiongjaneg @jilladams

**Comment by xiongjaneg** [comment]
closing in favor of #15718
