### ISSUE TITLE
Sprint 66 - Facilities | Aug 12 - Sept 12

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10315]
<details><summary>Quarterly Initiatives</summary>
List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9659  VBA MVP
- #9655 Lovell 
- #9096 Covid status post-launch
</details>

<details><summary>Issue icon legend</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task
</details>

<details><summary>OOO</summary>

Who | When | Backup 
----- | ------ | ------- 
David S| 8/30 | Roger 
Denise | 9/1 - 9/9 |
Jay D
Dave C 

</details>

## Facility COVID status post-launch

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10390 Determine COVID approach 

## VBA Facilities

**PM**
 - [ ] Plan for first meeting with Chris at Boston?? <- next step Design strategy meet

**Design**

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10489 Create research runbook 🥅
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10193 VBA Veteran Research Review
- [ ] Plan for first meeting with Chris at Boston?? <- next step Design strategy meet

**Engineering**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10421 Add VBA fields to CMS
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10504 Basic VBA content modeling 🥅

## VAMC

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10378 Audit "support for" on _contact us_ pages 

### Lovell #9655  🥅

**PM** 

 - [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10476

**Engineering** 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9947 Implement Lovell switch
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9946 Make Lovell Canonical 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10170 Implement Lovell Breadcrumbs 🥅
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9847 Design handoff 🥅

**NOTE:** Comfortable releasing some pages to Prod if we put up banner on both instances pointing to legacy Teamsite 

## Lighthouse / Facility API data

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10422 Add VBA data to LH migration 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10454 Block mental health care and Caregiver data _PR ready, need to support testing_ 

## Content backend 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10350 Audit flippers
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10332 Mental Health facilities with > 1 phone
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10406 Performance page changes

## Blocked

<details><summary>Blocked by V1</summary>

- [ ] #8017  Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
  - [ ] #4411 Push CAP data 

</details>
