### ISSUE TITLE
Convert outreach materials page to use KISS

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10321]
## User Story or Problem Statement

As a maintainer of CMS and FE code, I would like https://www.va.gov/outreach-and-events/outreach-materials/ to utillize our [Keep It Simply Static](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8198)  (KISS) data model so that we can reduce the inherent technical debt in this one-off approach.

This is not a critical or urgent issue and could be done in concert with other improvements made to that page.

## Acceptance Criteria
- [ ] [Testable_Outcome_X](https://www.va.gov/outreach-and-events/outreach-materials/) is built and uses a KISS endpoint for its data.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This surfaced as a suggestion from [this Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/552) related to missing items.

**Comment by wesrowe** [comment]
TO DO: What is the future of this page under Fast Publishing?

**Comment by swirtSJW** [comment]
A question was raised as to the primary reasons for doing this.  I see them as the following.

- Tech debt reduction. This page is unique in its function and does things its own way... embedding a bunch of data on the page.  If it was built anew it would have been setup to use  KISS data as this is the kind of thing KISS was designed for.
- Opening the data in a way that can be consumed by others. KISS data has the ability to be open data that anyone else can consume.
- Accelerated publishing could easily leverage this by just pushing the kiss data.

- There are some future plans to improve the materials outreach page, it  might be worth it to refactor first, as opposed to having to re-work the improvements later.

**Comment by ryguyk** [comment]
This would be a significant lift, and might not even be reasonable. Currently, all of the markup for this page is statically generated. The data is pulled at build time and converted - via a Liquid template - to html. The final output is a page (html) with _all_ materials rendered. When a user interacts with the filters, javascript code simply hides/shows as per the filters selected.

This is notably _not_ the use case that KISS is intended to solve. KISS generates static data files that the browser can consume and work with.

**Comment by jilladams** [comment]
Added Icebox, based on conversation in last refinement meeting around this.

**Comment by wesrowe** [comment]
Outreach Materials deprecated in fall of 2022.

**Comment by FranECross** [comment]
Closing as a no op; Outreach Materials deprecated in fall of 2022, as VEO moving the materials elsewhere.
