### ISSUE TITLE
Drupalize VA.gov Footer

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#10339]
## Background

Currently, changes to the VAgov footer require a code deployment. On Fri 8/19/22 we learned of a broken link in the footer, and we had to race the clock to remove it before daily deploy. Making it part of content-build would be much more flexible and would no doubt offer other benefits as well.

Slack thread: https://dsva.slack.com/archives/C52CL1PKQ/p1660917668814859

### User Story or Problem Statement

- As an owner of the VAgov footer I want to make link changes in Drupal so that I don't need a code change to make changes.
- As an owner of the VAgov footer I want to know if an external link returns a 404.

### Affected users and stakeholders

* Sitewide stakeholders
* Tim Cosgrove - re: content-build link checker
* Steve Wirt - re: CMS link checker / Linky
* Erika Washburn / Dawn Pruitt - re: SItewide CMS ownership of CMS link checker

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _adding footer content to the CMS_ will achieve _higher quality and more manageable workflow for footer content_. We'll know that to be true when _TBD._

## Assumptions
* The Mega-menu header is already managed in CMS. We will follow the pattern for footer.
* Code deployments for footer content changes are not optimal.
* Public Websites team is responsible ultimately for footer content and will be primary editors of footer links, in terms of permissions.
  * No change management required, as this is limited to Drupal admins
* The CMS link checker is owned by Sitewide CMS and content-build link checker is owned by Platform CMS. CMS link checker using Linky will be responsible for validating broken links in Drupalized footer content, within its existing constraints. https://dsva.slack.com/archives/C52CL1PKQ/p1660933767994479

(How will these assumptions be validated?)

## Additional context
* Footer data currently pulls from https://github.com/department-of-veterans-affairs/content-build/blob/main/src/platform/static-data/footer-links.json
* [Footer mobile vs. desktop behavior](https://app.mural.co/t/vagov6717/m/vagov6717/1668126089949/23f43e394e95c8fbf39cd39549bb1f6d20ce289e?sender=u252e7152800e3981889d1910) - Mural
* megamenu pulls with this GraphQL query: [https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site[…]build/drupal/graphql/navigation-fragments/header.nav.graphql.js](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/navigation-fragments/header.nav.graphql.js)
* Header & Footer are combined in https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/plugins/create-header-footer.js
* Swirt proposal that footer (and header) could be exposed as KISS and then all the consumers of it would always have access to it. TBD research to validate whether this is a good idea, work required, and whether we should refactor megamenu header to follow the pattern.

## Acceptance Criteria
- [ ] Updated footer will be available on VA.gov and injected websites
- [ ] Broken links are not silently published 
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Priority per Dave: not urgent, but if we can assess effort, let's scrub it for awareness later priority. Could fast follow the homepage effort.
