### ISSUE TITLE
Filter and transform content from CMS export for 6 listing page content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1034]
Work with VSA-facilities team (@brangi) 

# Problem Statement
The data from the CMS export is raw and needs to be filtered and transformed before it can be used in the templates.

# For each ticket in this epic
This list comes from logging out all unique content model names while building out the entity trees of all `node`s in our current tome-sync output (which reflects the all CMS content on VA.gov when it was exported).
For each of these, we need to do the following.

## Task
- [ ] Create a pre-transformation JSON schema at `process-cms-exports/schemas/raw/${content-model-type}.json`
- [ ] Find the test CMS export data and the corresponding bit in the GraphQL response
- [ ] Copy this chunk of the response to `process-cms-exports/tests/transformed-entities/${content-model-type}.json`
- [ ] Create a post-transformation JSON schema at `process-cms-exports/schemas/transformed/${content-model-type}.json`
- [ ] Create a transformation function to map the raw CMS export data to the GraphQL response counterpart

## Goal
The content models after transformation match the result from the GraphQL query.

## Acceptance Criteria
- [ ] The content model shapes after transformation match that of their GraphQL counterpart in `pages.json`
- [ ] Pre- and post-transformation JSON schemas are used to validate the data 
- [ ] The transformation function is unit tested using known-good data

**Comment by oksana-c** [comment]
Outdated. Closing.
