### ISSUE TITLE
EPIC: Support for retiring and replacing the existing COVID status 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10389]
## Background
The current (as of 8/16/2022) specialized COVID status was not successful because the nationalized policy did not account for the operational reality at each location. The status of High/Medium/Low and the associated policies did not provide enough flexibility and granularity. The specialized COVID status will be retired, and instead VAMC editors will be asked to use the Facility Status to convey any critical information to visitors in preparing for their visit to a facility.

### User Story or Problem Statement

As a Veteran, I want accurate and timely status information about a facility so I can knowledgably plan my visit. Are masks required? How many visitors are permitted? 

As an Editor, I want to provide accurate status information that reflects the reality at my Facility. 

### Affected users and stakeholders

* CMS VAMC Editors
* Facilities Change Management
* Facilities Dev team 

#### Links to research

[COVID Facility Status Topline Readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/Topline_research_readout-COVID-Facility-Status.pdf)
[Research Plan for COVID Facility Operating Status](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/COVID-status-round-2-research-plan.md)
[Conversation Guide for COVID Facility Operating Status](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/2022-5-COVID-status-editor-feedback/COVID-status-round-2-conversation-guide.md#conversation-guide-for-covid-facility-operating-status--junejuly-2022)

#### Link to CMS intake request
https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
Not sure how this got in the Icebox, this is ongoing

**Comment by jilladams** [comment]
Closing re: #13681
