### ISSUE TITLE
content-build with next-build runs correctly on content-build CI

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10468]
## Description
Following on from #10467, we need content-build with next-build to run correctly in GHA environments. This will involve multiple repos communicating effectively. 

Modifications will need to be made potentially in the content-build code, content-build Github Actions, and next-build to accommodate this. This code may not end up merged to main on content-build and instead be held in a branch for later inclusion.

## Acceptance Criteria
- [ ] Next-build is not run from content-build unintentionally
- [ ] Content built by next-build can be built, packaged, and deployed to vagov lower environments correctly. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

```[tasklist]
### Tasks
- [ ] thing one
- [ ] thing two
```

**Comment by timcosgrove** [comment]
We are not going to integrate Next.js and Content Build in this manner.
