### ISSUE TITLE
Frontend: Vet Centers are not listed as "VA facilities" when adding an Event location

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10465]
## Description

#9483 adds logic to expose Vet Center facilities in the "Facility location" field on Events. (This PR is not merged.) We need to hook up the front-end, so that when a Vet Center location is specified, that VC address shows in "Where" on the Event.

GraphQL: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/10357#issuecomment-1227705167

## Tasks
* Update GraphQL
* Think about automated testing
* Testing: verify that Vet Center location shows up in the template. Christia would need to rebuild her CMS branch to Tugboat, with pointer to a specific event to look at, and specify this content-build branch provided by Front-end, for testing.

## Acceptance Criteria
- [ ] Review order of operations from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9483#issuecomment-1227773352 to confirm testing & release process
- [ ] An Event with any of the following facility types as Facility Location shows the facility address in "Where"
  - [ ] Vet Center
  - [ ] Vet Center - Community Access Point
  - [ ] Vet Center - Outstation
  - [ ] VAMC Facility

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
This should amount to changing the query for `fieldFacilityLocation` in two places in `src/site/stages/build/drupal/graphql/nodeEvent.graphql.js`
1. Line 69
2. Line 226

This code below:
```
fieldFacilityLocation {
  entity {
    entityBundle
    entityId
    entityType
    ... on NodeHealthCareLocalFacility {
      entityUrl {
        path
      }
      fieldFacilityLocatorApiId
      title
    }
  }
}
```
Should become:
```
fieldFacilityLocation {
  entity {
    entityBundle
    entityId
    entityType
    entityUrl {
      path
    }
    title
  }
}
```

It doesn't appear that `fieldFacilityLocatorApiId` is needed on an Event node, and this was likely just copied over from another query when it was first created. Since we don't need this, we don't need the fragment `... on NodeHealthCareLocalFacility`. We could keep it and add one for vet centers, but we shouldn't need to differentiate any fields between the two types. It should suffice to just grab the fields at the entity level.

**Comment by ryguyk** [comment]
Estimating at 3. The change isn't big, but QA will likely require some time.
