### ISSUE TITLE
Lovell: Develop metrics to evaluate the user journey 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10476]
## Description
A solution for switching between TRICARE benefits and VA Healthcare benefits will be deployed at Lovell Federal Healthcare.

How might we develop metrics that evaluate the user journey, to compare to the pre-switcher state, and to measure the overall performance of Lovell vs other VAMC locations. How might these metrics be used to measure the performance of the site to measure the affect of additional future design modifications 

With a goal of making statements after deploy along the lines of

- _Data indicates that Lovell site users have no additional difficulty or frustration during a session_
- _Data indicates that VA Healthcare beneficiaries have an experience that matches across all other VAMC locations, but that TRICARE beneficiaries have slightly more difficulty_ 
- _Data indicates that after we modified the switcher design, Veterans and service members at Lovell had an improved experience_

Some initial ideas to explore:
- CSAT for Lovell VA compared to average CSAT at other VAMCs after 3 months post cutover - should be on par
- CSAT for Lovell DoD compared to average CSAT at other DoD after 3 months post cutover - should be on par
- The number of average clicks/pages in a session at Lovell compared to the average of other VAMCs 
- For users who performed the top 3 tasks, what was their journey/path? How many clicks/pages?
- What was the journey/path for people who ultimately authenticated as Veterans vs those who authenticated as DoD (can we get this?)
- Relationship of self-identification (service member, VA) to CSAT on Lovell VA should be on par with other VAMCs
- % of self-identification for service member on Lovell DoD responses should be higher than VAMC and VA should be lower we are on par as other DoD sites.. on par 
- Consider how bounce rates factor in to people moving between sites (assumptions on what it means to land on a page and immediately click back with no action) 

## Acceptance Criteria
- [ ] Several metrics are agreed upon and validated with the Analytics team

## Tasks
- [ ] Collect possible metrics/brainstorm session
- [ ] Initial exploration in Domo and/or GA
- [ ] Validate with Analytics, does anything additional need to be requested for Analyltics to collect the data?

## Assumptions
- [ ] We will be able to distinguish between VA and TRICARE data via the location, ie, they will be tracked as distinct locations in DOMO and GA (as based on the URL path `lovell-federal-tricare-health-care` vs `lovell-federal-va-health-care`

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Discussed with Dave C and Roger E several likely metrics we can use - listed in Description in this ticket. Verified with Dev team that Lovell's tricksey URLs will not prevent us from getting distinct metrics from Lovell VA vs Lovell TRICARE.
