### ISSUE TITLE
Content Audit: CMS instances of accordion

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10486]
Content audits can be performed by searching the codebase and compiled site for specific terms ur using an audit tool within drupal. 

**Goal**: the front-end file audit & changes will manage the presentation of accordion headers. We need to understand the nature of accordions in the CMS enough to have sample data to verify the front-end fixes, and ensure we're covering all the cases that exist in the CMS.

## 1. Please provide any context around your audit
re: #10126 , heading levels for accordion web component are incorrect, and we've determined a path to fix (#10136 ). PW will audit the FE code for occurrences. We need to know the CMS occurrences, so we can test against our fix to ensure that it doesn't break existing content / fix works broadly.

## 2. What are the terms you are searching for within the CMS? Are there alternate spellings?
n/a

## 3. Are there components, elements or content types related to your search?
Yes - Accordion 

## 4. Does a corresponding audit need to be run on the Veteran-facing website?  
  - [X] Yes - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10380 will cover the FE template files, but we want to review teh static pages compiled from content-build to identify existing accordions.
  - [ ] No 

## Known accordion fields 
Machine names: 
* basic_accordion
* collapsible_panel
* collapsible_panel_item
* field_va_paragraphs
* field_collapsible_panel_bordered
* field_collapsible_panel_multi
* field_collapsible_panel_expand

## Tasks
* Figure out the scope of what kinds of accordions exist via auditing content-build static pages
* Identify the node templates responsible for printing the accordion fields 
* Verify that all of the accordion field types we found to confirm they all have the 508 error
* Handoff notes to #10526 for front-end changes

## Acceptance criteria
- [ ] #10526 updated with fields / node templates that need the 508 heading update

## CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Steve note on setting up an Accordion Audit view similar to the [Table audit view ](https://prod.cms.va.gov/admin/content/audit/table-audit)  ([Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1661364422311699?thread_ts=1661354422.964899&cid=CT4GZBM8F)):
> Yes... that one I think is a little more complicated as accordions I think are used in multiple types.  So it may be a little more challenging to find them all.  Also I think some only exist on the FE.

PW will own the FE code portion of the audit under https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10380. If we need to own the CMS audit as well, we can, but Erika suspected Nate may have insights to share. 
@ndouglas , care to opine?

Per discussion with Erika: Sitewide CMS cam consult, but PW may need to own the work right now. Not prioritized into Sitewide CMS sprint 66, at minimum. (FYI @wesrowe )

**Comment by jilladams** [comment]
Daniel / Christia sync: 
* Accordions may be various kinds of entities (paragraphs, fields, etc.) If so, it's not easy / advisable to process them all in a single Audit view. 
* It's possible to perform an audit without making it into a view, just wouldn't be reusable later.
* We may not need this audit. Checking the output of content-build will tell us definitively where all accordions are, post CMS > templates.
* The one thing that may be weird is: if somehow in the Drupal UI a heading level can be specified, that conflicts with / overrules the heading set in the template. 
* From a brief survey, it seems that all accordions are parented by nodes so node template review would cover our use cases.

So: a review of compiled static pages is probably more useful in this case than the Audit view. Rewriting.

**Comment by dsasser** [comment]
# Results

[VACMS-10486_ CMS Accordion Audit.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9538088/VACMS-10486_.CMS.Accordion.Audit.pdf)

**Comment by laflannery** [comment]
@jilladams I found a couple translated pages that may have gotten missed in the original audit, I took a look  at the PDF above but didn't see them. Are these able to get updated? Should I create a separate issue?

- The [English](https://www.va.gov/resources/the-pact-act-and-your-va-benefits/) PACT act page has correct H3s for the accordions but [Spanish](https://www.va.gov/resources/the-pact-act-and-your-va-benefits-esp/) and [Tagalog](https://www.va.gov/resources/the-pact-act-and-your-va-benefits-tag/) have H4s
- The [English](https://www.va.gov/coronavirus-veteran-frequently-asked-questions/) Covid FAQs page has correct H3s for the accordions but [Spanish](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-esp/) and [Tagalog](https://www.va.gov/coronavirus-veteran-frequently-asked-questions-tag/) have H4s

**Comment by jilladams** [comment]
@laflannery If you don't mind, a new issue would be very helpful!

**Comment by laflannery** [comment]
@jilladams Added #11205
