### ISSUE TITLE
CMS: Remove TRICARE facilities from the nightly removed from source scan

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#10588]
## User Story or Problem Statement

When the nightly scan is run to look for facilities that have been removed from FAPI, Trucare facilities get flagged as removed from source, because they are never in the source.

![image](https://user-images.githubusercontent.com/5752113/187959219-4fc17ac9-e594-4b29-8ad6-dd4f3066d9bf.png)

## Acceptance Criteria
- [x] When the nightly scan is run, TRICARE facilities are not flagged, "removed from source".
- [ ] After this code goes live, remove the existing flags from the tricare facilities.

## Implementation steps
This scan runs from the drush command va_gov_migrate:flag-missing-facilities
docroot/modules/custom/va_gov_migrate/src/Commands/Commands.php

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Reopening because there is a manual step to remove the flags currently attached to these facilities.

**Comment by JayDarnell** [comment]
I've removed the Removed from source flags from the 5 TRICARE facilities.
