### ISSUE TITLE
Sprint 67 - Facilities | Sept 12 - 26

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10584]
<details><summary>Quarterly Initiatives</summary>
List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9659  VBA MVP
- #9655 Lovell 
- #9096 Covid status post-launch
</details>

<details><summary>Issue icon legend</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task
</details>

<details><summary>OOO</summary>

Who | When | Backup 
----- | ------ | ------- 
Denise | 9/12 - 9/15 |
Jay | 9/22 - 9/23 | 
Dave P | 9/21 | 

</details>

## Transition
- [ ] 🥅 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10686
     Are there issues with access?

## Facility COVID status post-launch
Meeting Monday Afternoon 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10390 Determine COVID approach 
Not using supplemental bullet points - if all we're doing is removing bullets, low lift 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10439 Work with content team
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/45774 Sitewide content ticket
- [ ] #9941 - would be good to do this while Denise is still on team

## VBA Facilities

**PM**
 - [ ] Plan for first meeting with Chris at Boston?? <- next step Design strategy meet
 - [ ]  Scheduling individual presentation meetings with each proposed MVP site. <- Meetings on calendar - Determine tight group for listening in 
- [ ] Any feedback from current VC - how is the dashboard working? Did we do listening sessions? <- DS Editor research from CMS team back in Jan - should be an artifact - check with Denise? Track & capture all research we have done. 

**Design**
- [ ] 🥅 #10193 - still open from sprint 66
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10504 VBA content models 
   - [ ] Content models? - what can we derive/iterate based on what we've done for other facilities ? Intro paras? Etc? What's not in source data? 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10252 Lo-Fi wireframes with fundamental hypothesis (maps, phone numbers, preparing for your visit)
     We know it's a VA facility, we have research on existing facilities 
     Concentrate on Hi Confidence areas - Map, Photo, Intro Para, <- based on where research was done? 
     acknowledge/identify Lower Confidence areas (List of services ?)  
     Determine if existing wireframes are effectively usable - likely not ? How can we build from what was done? 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10472 Participant recruitment for VBA <- Late next sprint, dependent on Review Cycle 
- [ ] #10507 - Denise scheduled review for sept 22. Does that still make sense for this sprint?

**Engineering**
- [ ] #10701 VBA dashboard wireframe
       Maintain facility services - easy and intuitive, prioritized for editors
       What does it look like when events are added? 
       Develop first mock-up to validate 

## VAMC

- [ ] QR code metrics and URL syntax 

### Lovell #9655  🥅

**PM** 
- [ ] Coordination on intake of new editors, CM <- Be very clear 

**Engineering** 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10169 FE Breadcrumbs 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10168 Multiselect Events - Option C
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10167 Menu bifurcation 

**NOTE:** Comfortable releasing some pages to Prod if we put up banner on both instances pointing to legacy Teamsite 

## Lighthouse / Facility API data

- [ ] 🥅 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10454 PR ready, need to support testing <- Make priority for this Sprint. Verify in today's meeting 

## Content backend 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656 Execute on [Flippers Audit ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10350)

## Blocked

<details><summary>Blocked by V1</summary>

- [ ] #8017  Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
  - [ ] #4411 Push CAP data 

</details>

## Other

- [ ] #10489 still open from 66

**Comment by davidmpickett** [comment]
@dsinla @RWEagans I added all Design tickets that are in-flight or otherwise seem like candidates for this sprint since I won't be in Sprint Planning tomorrow
