### ISSUE TITLE
[EPIC]  [Find a Form] Optimize UX for PDF downloads between Search / Form results pages

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10710]
## Background
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9724 identified several opportunities to improve the Form UX within the VA.gov site. 

### User Story or Problem Statement

As a user, I need to have a consistent experience across the site when downloading form PDFs.

### Affected users and stakeholders

* Veterans downloading forms
* Forms managers
* Public Websites maintainers of FInd a form

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9724

### Hypothesis

We believe that streamlining the code, modal appearance, and download link behavior between Forms search and Form detail pages will decrease user confusion, forms download errors, and occurrence of "Bad PDF Link" emails to Forms managers. We'll know that to be true when Sentry metrics around onClick download errors are reduced

## Assumptions
* Reducing the number of round trip API calls required to download a PDF will reduce errors presented to users when trying to download PDF forms
* vets-api latency events may still cause outages for downloading forms

## Acceptance Criteria
- [ ] Forms Search and Detail pages display identical modal styles & text 
- [ ] The forms download modal appears on any form download, instead of current 1ce/24h behavior

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [X] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
