### ISSUE TITLE
PW: Site search discovery & support

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10767]
### User Story or Problem Statement

As the Public Websites Team we need to investigate and understand the architecture of site search in order to support the feature and ensure performance.

### Affected users and stakeholders

* Public Websites team

### Hypothesis

We currently suspect that vets-api latency events may affect site search, which is unexpected. We would like to understand the architecture well enough to disprove this theory.

We also know that robots.txt determines visibility of search results, and need to explore that structure to maintain ongoing updates.

## Acceptance Criteria
- [ ] Understand and document or update documentation about the behavior, API calls, and infrastructure of site search
- [ ] Understand and document or update documentation about the use of robots.txt & propose governance for future updates

### Change management triage

No change management implications as of drafting

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
