### ISSUE TITLE
Connect homepage FE to Drupal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#10785]
## Description
Areas of the redesigned homepage were Drupalized in #10626. This issue will connect the homepage to these new components so that 
- OPIA editors can easily create content for Benefit promo and VA news blocks
- Popular links and other search tools can be changed without engineering time
- the amount of content managed by Drupal can be expanded beyond what is currently 

## Tasks

Connect Front end to new Benefit Promo Custom Block (i.e., PACT Act) for title, description and CTA with link and label

---

Connect Front end to new menu for Other Search tools for UI heading, link, link text, and ordering. 
- ~~Quantity will be controlled on the Front end, rather than constrained in Drupal~~
  - ***Wes: See my comment below about moving this constraint out of this issue, maybe out of MVP***
- pending: what attributes are needed for behavior, such as opening in a new tab

---

Connect Front end to new menu for "Popular on VA.gov" list (formerly "Common Tasks") for UI heading, link, link text, and ordering
- Will need to order in columns 1-5, 6-10
- ~~Quantity to be controlled on the Front end, rather than constrained in Drupal~~
  - ***Wes: See my comment below about moving this constraint out of this issue, maybe out of MVP***

---

Connect Front end to Promo block type for VA News promo block (Pathfinder) for title with link, description, and CTA with link and label
- "VA NEWS" and "More from VA News" will be hard coded in the FE
- Image will not display on mobile

---

**Other tasks will have been done in Homepage: Implement design iteration for next round of Veteran research #10648**
- Portrait row above footer
- Email subscription box
- "create account" block

---
## Additional info
- Graph QL queries are provided here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10626#issuecomment-1266080549
- Drupal changes will not be merged during this work, so the BE data will be coming from a tugboat instance. See PR on #10626 for tugboat.

If you have any questions, talk to @dsasser who implemented the Drupal elements. 

## Acceptance Criteria
- [ ] Benefit Promo block content displays title, description, and CTA with a link using a new clearly labeled content block type in Drupal.
- [ ] VA News promo content displays link, description, CTA with link and photo using Drupal content. 
- [ ] Popular on VA.gov link menu references heading, links, link labels, and their ordering from Drupal. 
- [ ] ~~The FE constrains the Popular on VA.gov link menu list quantity.~~
- [ ] The Other search tools link menu references heading, links, link labels, and their ordering from Drupal.  
- [ ] ~~The FE constrains the Other search tools link menu list quantity.~~

**Comment by wesrowe** [comment]
@apisandipas @ryguyk @swirtSJW – The ticket as written says that the FE template should hold some business rules around how a maximum number of menu items to show in the two new menu-driven lists (other search tools, popular links). I have doubts that this is the best place to put business rules, since everything else about these menus is in Drupal. 

Going through the BE with @dsasser, we noticed that Drupal by default provides "enabled" checkboxes per menu item. This might be a more elegant way to put all the control in Drupal.

I noted in ticket details above that we should discuss. For now, I'm thinking we should remove the business logic from this ticket. (Generally, it seems like lower-priority governance functionality like this is post-MVP, @mmiddaugh).

**Comment by jilladams** [comment]
Proposal: resolve this, open a new ticket for merge to main / verifying with content once it's entered into Drupal. Good idea, @apisandipas ?

**Comment by jilladams** [comment]
@apisandipasThe process we worked out last sprint with the backend changes is to point the branch at an Integration branch, so you can get full code review and merge.  I see that @ryguyk has offered a little code review -- any risks to un-drafting your PR / repointing to an integration branch? At that point, you could merge / close here.

#11296 has been created for merging to main, which we can do ~Nov1 based on today's sync with Michelle.

**Comment by jilladams** [comment]
The PR is up and approved. It appears that tests can't pass til the Drupal changes from #10626 are merged to main, which is scheduled for Nov 1 and will happen under #11296. I'm closing this ticket as done, and #11296 will get the work into main.
