### ISSUE TITLE
Deprecate Cerner hard-coded data method

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10781]
## Background

#8199 / #8201 created a new Drupal-driven data source for determining whether a Facility isCerner or not
#8687 cuts over PW-owned widgets to use the new data source

VFS All teams has been notified of a Dec 1 2022 proposed cutover date for all customers of the isCerner flag to adopt the new API, documented in https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for

This epic tracks deprecating the hard-coded API.

### User Story or Problem Statement

The new Drupal Cerner API should be used, and tech debt for the hard-coded method can and should be removed.

### Affected users and stakeholders

* Downstream users of the `isCerner` flag
* Public Websites engineering

## Assumptions
* Downstream teams will prioritize and migrate to the new Drupal SSOT by Dec 1. If not, timelines must shift.

## Acceptance Criteria
- [ ] Drupal SSOT is only means of validating whether a facility is Cerner or not
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md is updated to reflect state of truth

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [X] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [X] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

 
## Runbook
* https://depo-platform-documentation.scrollhelp.site/developer-docs/how-to-opt-in-to-drupal-as-the-source-of-truth-for
* https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md -- should be updated

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidconlon** [comment]
@jilladams I think we should be able to close this epic because we have deprecated it. There are other "more ideas" that Ryan had that we may want to consider, but we did get this officially across the line.

**Comment by jilladams** [comment]
Makes sense, closing. Will find new homes for the open tickets.
