### ISSUE TITLE
<Insert summary of epic>

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10780]
## Background
#8630 implemented reusable Single Q&A nodes on Resources & Support. 

We want to extend this paradigm to make Single Q&A nodes reusable on: 
* Benefit Hubs
* Campaign Landing Pages
* Vet Centers

### User Story or Problem Statement
- As an editor, I want to reuse existing Single Q&A nodes on additional types of content

### Affected users and stakeholders

* CMS editors of Benefit Hub content (SWC)
* CMS editors of Campaign Landing Page content (VBO editors(?))
* CMS editors of Vet Center content (Vet Center editors)
* Developers of new Next.js content build, PW teams
* Veterans looking for information

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [X] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by wesrowe** [comment]
@swirtSJW – the in-line editing issue has complicated the path to introducing reusable Q&As to more content types. Today Jill and I discussed it with Dave, and he supported the idea of removing the in-line editing capability from all content types. Reasons:
- It's complicated for the UI/Editor to track edits in different workflow states
- There's no way for an Editor to see how edits to a Q&A will impact every context where it's published (as there will be more and more over time)

Dave asked me to run it by Steve, thinking you might have even reached this conclusion before. Are you okay with this path forward?

(Note: I've already written a couple skeletal tickets in this epic for removing in-line editing from R&S and FAQ content types.)

CC @chri5tia @dsasser @jilladams

**Comment by wesrowe** [comment]
Also @EWashb, please see comment above :)

**Comment by jilladams** [comment]
Closing loop: https://dsva.slack.com/archives/C52CL1PKQ/p1681236532807649
>  had a min to ask Swirt about the inline editing in current meeting. He noted: this has come up with Dave before on other products for Facilities, so the topic is familiar and Dave is supportive of disabling it wherever we need to. Sounds like there wasn't a big picture epic to knock it out in all places where it appears.

**Comment by jilladams** [comment]
5/15 DaveC confirmed with Beth & Danielle that Benefit Detail pages are the next strategic priority for adding Q&As.
