### ISSUE TITLE
URLs for Popular links and other search tools

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#10786]
## Description
Links displayed in "Popular on VA.gov" and "Other search tools" will need hard coded links to the appropriate pages on the  prototype in staging for usability testing in October. 

These same urls will need to be added to the Drupal menu (once available).

|	Tasks for 10 popular links on home page	|	Link url	|
|	---	|	---	|
|	VA health care	|	https://www.va.gov/health-care/	|
|	VA medical records	|	https://www.va.gov/health-care/get-medical-records/	|
|	Mental health help	|	https://www.va.gov/health-care/health-needs-conditions/mental-health/	|
|	Travel reimbursement for health care	|	https://www.va.gov/health-care/get-reimbursed-for-travel-pay/	|
|	PACT Act information for Veterans with toxic exposure	|	https://www.va.gov/resources/the-pact-act-and-your-va-benefits/	|
|	Claim or appeal status	|	https://www.va.gov/claim-or-appeal-status/	|
|	Disability compensation	|	https://www.va.gov/disability/	|
|	Education benefits	|	https://www.va.gov/education/	|
|	Your VA payment history	|	https://www.va.gov/va-payment-history/	|
|	Dependents on your disability benefits	|	https://www.va.gov/view-change-dependents	|
				
				
|	Other search tools	|	Link url	|
|	---	|	---	|
|	Find a VA location	|	https://www.va.gov/find-locations	|
|	Find a VA form	|	https://www.va.gov/find-forms/	|
|	Find benefit resources and support	|	https://www.va.gov/resources/	|

## Tasks
- [ ] Get approval from Dave and Danielle
- [ ] Add links to FE of staging prototype (to production)

## Acceptance Criteria
- [ ] Links from staging prototype link to indicated Production urls

**Comment by mmiddaugh** [comment]
@davidconlon @DanielleThierryUSDSVA please review proposed links to confirm accurate urls

**Comment by mnorthuis** [comment]
@mmiddaugh I believe our standard is to use a trailing slash to point to the canonical URL.  Can you add a trailing slash to both the find locations link and the dependents link?  Thanks!

**Comment by mmiddaugh** [comment]
Done! Good catch @mnorthuis - thank you!

**Comment by DanielleThierryUSDSVA** [comment]
Hi, @mmiddaugh. Links all look right to me. Thanks!

**Comment by davidconlon** [comment]
@mmiddaugh concur. Thank you!

**Comment by davidconlon** [comment]
@mmiddaugh @DanielleThierryUSDSVA Just realized something.
Do we want a "Popular on VA.gov" that is also the spotlight content (e.g. PACT act)

I think we need a rule where there is no duplication when we look at the homepage in aggregate.

**Comment by DanielleThierryUSDSVA** [comment]
@davidconlon I don't disagree. I believe that suggestion came from the fact that that page is so high in pageviews right now that it potentially should be in both. But I'm totally open to re-evaluating that. It's also easy to find via search because it's a best bet for numerous related terms. Connected to this: I had raised a similar concern about the more general links (like "VA health care") that are in both Popular and benefit hub page sections, so we might want to talk about that as part of this criteria discussion too.

**Comment by davidconlon** [comment]
I think I'd like the opportunity to "spread the wealth" in terms of use of the homepage. Just as the old homepage separated these topics.
I, too, am concerned about the complete duplication of the health hub links in that area, but I'd rather see how that works via test. I think I'd prefer to see more "Deep linking" in popular, but that's more my preference rather than anything based on data.

**Comment by DanielleThierryUSDSVA** [comment]
Agree on seeing how those links test.

**Comment by jilladams** [comment]
Per homepage sync with Michelle today: pulling into PW sprint as stretch & assigning.

**Comment by apisandipas** [comment]
These URL updates have been made and pushed to the pending PR here:
https://github.com/department-of-veterans-affairs/content-build/pull/1307
