### ISSUE TITLE
KB: Promo banner & Full-width alert articles: Update Path field info to be technically accurate

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10792]
#10801 will update the way Path field works on Promo banners & Full-width alerts. 

Currently we have 2 KB articles that reference behavior from the Path field. Both need to be updated to be technically accurate: 

1. Promo banners = https://prod.cms.va.gov/help/full-width-alert-and-promo-banners/promo-banners
2. Full-width alerts = https://prod.cms.va.gov/help/homepage-alerts-and-promo-banners/full-width-alerts

## Tasks
- [x] Review the final state of #10801 changes in a Review Instance, with the engineer who implemented the changes, to confirm behavior
- [ ] Document the accurate state of Path field behavior

## Acceptance criteria
- [ ] Promo banner and Full-width alert KB articles describe the same Path field behavior
- [ ] Changes are published to KB nodes in prod cms

**Comment by jilladams** [comment]
@EWashb this is the last item in an epic about improving editor experience. Is the right step to have either @BlakeOrgan or @davidmpickett take a pass at content? Or for PW to draft, and then review our draft?

**Comment by jilladams** [comment]
Verified that paths with and without trailing slash are treated the same. 

Both KB articles currently state: 

> Leading and trailing slashes

> Paths must start with an forward slash "/", except for exclusions (see below). 
> Trailing slashes are optional. "/health-care/" and "/health-care" are treated the same. 


Closing as no-op, documentation is already correct.
