### ISSUE TITLE
Initiative - Support Facilities migration from Lighthouse v0 to v1

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#10798]
## Background
Lighthouse plans to release v1 of the Facility API in Q4. The Sitewide Facilities team should be one of the first consumers. 

### User Story or Problem Statement

As a facilities developer, I want to provide the LH team with increased services and other data as CMS becomes the source of truth. 
As a Veteran, I want the Facilities Locator and other Facilities pages to display information about a larger set of services 
As an editor, I want to understand how best to update my Facility data so it is current and accurate for Veterans, and I want to know where to go if I encounter errors or unexpected behavior 

### Affected users and stakeholders

* Lighthouse Dev and design teams 
* CMS Facilities Editors 
* Developers Sitewide Facilities teams
* Sitewide CMS 

## Assumptions
* Must account for Change Management, the editor experience, support team prep, communication, etc 

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Removing `User Support` label

If VA Drupal CMS Help Desk work is needed, separate tickets can be created and linked.

(Also, is there potentially a newer and more detailed version of this ticket re: the Lighthouse upgrade?)

cc: @davidmpickett

**Comment by jilladams** [comment]
Dupe of #12921 12921
