### ISSUE TITLE
Improve editor experience for Promo banner/Full-width alerts

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10791]
### User Story or Problem Statement

As an editor, I need to understand how to publish a full-width alert or Promo banner on specific pages in  VA.gov.

### Affected users and stakeholders

* CMS editors of Full-width alerts & Promo banners
* Developers of PW team

### Hypothesis

We believe that improving the CMS UX and implementation of Path field on Full-width alerts and Promo banners will simplify the process of getting urgent updates out to veterans when required.

The Path field is currently poorly documented but critical to the workflow to publish these content types.

## Acceptance Criteria
- [ ] CMS collab cycle review required to confirm changes
- [ ] Path field is updated to behave predictably, and behavior is documented in the code
- [ ] Path field is documented correctly in full-width alert and promo banner KB articles

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [X] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [X] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@jilladams @wesrowe we should sync about this one. I had a chat with Dave today and he has suggested that the CMS consider improving the baseline CMS experience for banners and then rolling it out to product teams for iteration. I received a quick rundown of this, but I would love more info if you have it. This spawned from Danielle's pain trying to put up banners in this [slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1663715267281239).

**Comment by jilladams** [comment]
Yes, happy to chat. We covered with Dave a little in refinement today and he agreed the work described here to fix the logic in #10801 & link to KBs in #10774 are quick wins. We plan to pull the first into next sprint probably, and the KB content in #10792 is where we could possibly use help once the technical bits are updated. May be worth trying to get us + Dave in a room to make sure we're all saying the same thing.

**Comment by FranECross** [comment]
All tickets in this epic have been completed. Closing.
