### ISSUE TITLE
Drupal Analytics 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#10841]
### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Coordinate with the Analytics team in regard to privacy. Editors are union employees, therefore we should make sure we are considering all implications for privacy. Also- CM for editor transparency and the ability to opt-out for each option.

**Comment by EWashb** [comment]
CM for analytics tracking needs to be considered. Alerts or something of the like. Def launch with an opt-out. We want to make sure that it stays off if they opt out.

**Comment by EWashb** [comment]
The Platform Analytics and insights teams is currently planning a large migration of all GA instances over to GA4. We should pause efforts for third party tooling until GA4 is ready. We could use this migration opportunity as a way to properly implement tags that capture the data we need

**Comment by EWashb** [comment]
This is an interesting [article](https://medium.com/civicactions/better-navigation-tracking-with-google-analytics-4-26361abff82e) about how CivicActions implemented GA4 in Drupal. We could use some of these pointers for our approach as well.

**Comment by BerniXiongA6** [comment]
Let's bring this into Sprint 95. Note to @BerniXiongA6 cc: @EWashb

**Comment by EWashb** [comment]
When we get our analytics setup we need to ensure that we have an accompanying DOMO dashboard.

**Comment by EWashb** [comment]
Also, just to state in the ticket, since I previously had concerns about PII--- I have confirmed that our GA instances do not track personal identifying information. Our tag setup excludes personal data and is approved to use in both authenticated and non-authenticated experiences.
