### ISSUE TITLE
Upgrade to php 8.1 (Q1 FY23)

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#10870]
### User Story or Problem Statement

We need to upgrade to PHP 8.1. Php 7.4 (current version) goes end-of-life on 28 Nov 2022. 

### Affected users and stakeholders

Effects all CMS users and products. 

https://www.php.net/supported-versions.php
![CleanShot 2022-09-26 at 08.37.16.png](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/602bdecd-ac81-4e68-9dec-66343622e4e7)

## Tests and areas that need to be checked
- [x] Test SSO
- [x] Test Content Build
- [ ] Test API endpoints?
- [ ] Manually test Drupal CMS interface and check for errors.

## Acceptance Criteria
- [ ] php 8.1 is installed on prod
- [ ] 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
We need tickets for Tugboat and DDEV too.

**Comment by ElijahLynn** [comment]
Tugboat ticket here > https://github.com/department-of-veterans-affairs/va.gov-cms/pull/11200

**Comment by EWashb** [comment]
@ndouglas would you mind looking over the issues in this epic and let me know what's been completed so far?

**Comment by ndouglas** [comment]
@EWashb #11724 can't be completed until 8.1 is done -- it'll presumably be one of the last things done.  #11800 is a substantial blocker and I'm working on it this morning.  I don't have any familiarity with #10875.  The others are all marked closed and I assume they're closed.

**Comment by ndouglas** [comment]
This can be closed now.
