### ISSUE TITLE
Homepage hero veteran images: Add H1 heading 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#10899]
## Description
In the event that the homepage benefit promo area is replaced by Veteran portraits, we need to ensure that the page still contains an H1 to give context to those using assistive tech or keyboard navigation
<details>
<summary> Screenshots from Sketch file</summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/a7dc8256-433e-49c0-8701-ece22cf57ccd)
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/983f35a9-e84a-4291-81da-e32eaf2bebf6)< 

</details>

## Tasks
- [ ] Add "Welcome to VA.gov" H1 header to Veteran portrait implementation
- [ ] Ensure H1 is announced and receives focus

## Acceptance criteria 
When Veteran portraits replace the benefit promo 
- [ ] Homepage levels are logically ordered, starting with a single h1.
- [ ] When a Veteran uses a mobile screenreader and swipes to browse to a heading, the heading it identifies itself as a heading and the purpose and level are clear. 
- [ ] When a Veteran uses a desktop screenreader (NVDA, JAWS, VoiceOver) Aand uses the arrow key to browse to a heading, 
the heading it identifies itself as a heading and the purpose and level are clear. 
- [ ] When a Veteran uses the arrow key to browse to a heading, the heading comes into view.

**Comment by jilladams** [comment]
Related slack thread: https://dsva.slack.com/archives/C03NSH4SLQY/p1663966886736689
This can wait until the treatment can be updated in the Sketch file, but ticket created to make sure we don't overlook it in final build.

**Comment by wesrowe** [comment]
Moving back to New/Unref since Veteran portrait component isn't MVP

**Comment by wesrowe** [comment]
Merged ACs into #12292 and will close this ticket as dupe.
