### ISSUE TITLE
AP: Public S3 file asset storage

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10894]
### Problem Statement

How might we improve speed and stability of accessing CMS file assets?

### Affected users and stakeholders

* Front-end developers using content-build
* VA.gov-wide developers who depend on content-build for CI
* CMS Editors

### Hypothesis

Our hypothesis is that storing CMS file assets on public S3 will lead to increased stability and speed.

We believe that storing CMS file assets will achieve faster content-build and content release times. We'll know that to be true when we measure timing of content-build in different scenarios and find faster times for those scenarios after the change.

## Assumptions
* Removing file transfer from the content-build process will result in faster content-build runs. This will be validated through measurement of timing of content builds before and after the change.
* Moving CMS asset storage to will not result in any functional or visual change to VA.gov, nor will it require any template changes be made by front-end teams. This will be validated through testing of the output of different content-build scenarios.

## Acceptance Criteria
- [ ] All CMS file asset (media) storage will be moved to a publicly accessible S3 bucket, so that it can be accessed without being transferred during the content-build process.
- [ ] All steps within content-build that deal with CMS asset transfer will be removed, so that transfer of images does not needlessly consume resources and time.
- [ ] Media files will continue to display correctly and/or be accessible, both within the CMS and in statically generated content.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [x] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
To-Do: Determine Content-Build speed improvements

**Comment by timcosgrove** [comment]
Dupe of #14052 14052
