### ISSUE TITLE
[Epic] [AP] Development infrastructure and tools

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10906]
## Requirements & Goals
Engineers working in Next Build will need documentation, support, guidance, and infrastructure to assist their development. 

```[tasklist]
### How will we know we've achieved our goals?
- [x] Enough documentation, tooling, and guidance exists that an incoming engineer can get the repo up and running without assistance
- [x] Technologies that exist to keep code consistent and functioning - linting, type checks, automated tests, etc - are in place and function both locally and within CI
- [x] Engineers are able to review a working instance of the build as part of the code review process
```

## Work and Supporting Info
```[tasklist]
### Tickets
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15064
- [x] Discover source behind random url failures on tugboat environments & fix it
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15625
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14598
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15382
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15065
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10665
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14977
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15138
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14974
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8777
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14710
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14599
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14600
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10803
```

**Comment by timcosgrove** [comment]
We are not going to use this epic in this way.

**Comment by timcosgrove** [comment]
This epic currently does not have a goal.
