### ISSUE TITLE
CMS preview

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#10903]
## Requirements & Goals
As a CMS editor, I need to see how my content will be rendered on the front-end of VA.gov, so I can check that it is correct.

### How will we know we've achieved our goals?
- [x] The CMS can render a single front-end build of content using Next Build
- [x] Next Build preview is able to render previews with draft or otherwise unpublished content.
- [x] Content Build preview continues to work without issue
- [x] CMS uses Content Build preview or Next Build preview as appropriate.
- [x] The UX for CMS preview is unaltered, even when using Next Build - we continue to use the button
- [x] Preview works for Tugboat environments
- [x] Preview works for BRD environments
- [ ] Preview works for local environments

### Tickets
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16474
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16866
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17778
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18544

### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15793
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16949
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16863
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16857
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9886
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15796
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15801
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9887
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16861
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16289
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16283
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16288
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16287
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16187
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15800
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15795
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10068
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9891
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9885
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15798
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15791
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15792
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15240
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14419
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15799
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15794
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15245
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9889

### Assumptions
* We are only building preview for VA.gov front-end. Preview does not take COPE into account (i.e. if the content were used in a chatbot agent, this preview makes no attempt to cover that case).
* We are making no changes to the UX of CMS Preview.

**Comment by laflannery** [comment]
Closing - only outstanding item was preview for local which we don't currently have so is not needed for next-build
