### ISSUE TITLE
BE: Document the process to expose Q&A on new content types

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10936]
## Description
We want to eventually add Q&As to as many content types as possible / that make sense. We will develop the steps to achieve that as an instruction manual to ourselves or future Drupal developers (runbook), and document them for posterity.

## Eng notes
We've done this before in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9737, can use that as a reference.

## Tasks
* Add Q&A with Place Q&A modal to a new content type, similar to the R&S & FAQ implementation
* Document the steps as a runbook that can be used for future content types
* Runbook can either be a Github document in the [COPE docs in VA.gov Team repo Products repo](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/cope-cms-faq-library/product-outline.md), OR an issue template

Since this won't be a repetitive task forever, just until we get through all content types, can be a Github doc rather than an issue template.

## Acceptance Criteria

- [ ] PO expects that runbook author has actually performed the steps and verified them before/while documenting
- [ ] PO expects that Drupal steps have been added to the runbook here: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/cope-cms-faq-library/engineering 
- [x] PO expects that the runbook addresses Drupal steps only. FE steps will be covered via #10937

**Comment by EWashb** [comment]
@jilladams I found this without your label on it

**Comment by jilladams** [comment]
@EWashb thank you!!

**Comment by jilladams** [comment]
Added link to ACs for where this documentation should live. (New doc was created on the FE ticket, and Drupal steps can be added into it before FE info: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/content/tier-2-content-IA-and-design/cope-cms-faq-library/engineering)

**Comment by chri5tia** [comment]
- [ ] Where should I put this in the COPE docs? 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/cope-cms-faq-library/product-outline.md

The instructions are pretty basic if editing an existing Main content block. 

For existing content types, edit the `field_content_block field` (Main content) and select the Q&A paragraph type, then save. Now when editors want to add an existing reusable Q&A they will see it as one of the options for adding main content.

1. In the Drupal UI > Structure > Content types and select your content type.
2. Edit the chosen Entity Reference Revisions field or add a new field, type Paragraph under Reference Revisions.
3. If editing existing field, skip this step. If it's a new field, select Paragraph for "Type of item to reference" and select Unlimited cardinality/allowed number of values.
3. For Paragraph types, select Q&A Group and save. Continue if this is a new field, otherwise you're done.
4. Go to the form display settings and select "Paragraphs Browser - Experimental" for the field widget.
5. For the other field settings (gear symbol) chose the following:
Title: Content block (if keeping with existing pattern)
Plural title: Content blocks (if keeping with existing pattern)
Edit mode: Closed
Form display mode: default
Default paragraph type: none
Paragraphs browser: Main content
Features: Collapse / Edit all
