### ISSUE TITLE
PDF certificate expiration alert

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#10956]
## Description 

[Mural board](https://app.mural.co/t/vagov6717/m/vagov6717/1664838770820/f454c9875a67a1d2db4b5d5331388b38b557e98b?sender=u907f83e01e35bb04de6f8139) for user flows, timeline, etc.

EOY 2022 the current PDF signing certificate will expire. When new cert is issued, all PDFs will need to be reisssued using it. Forms updated after the new cert date are good to go. Forms that have not been updated since that date need to carry a warning for site visitors.

> Adobe Reader Extension Certificate Expires on January 7, 2023
> If end users attempt to use an outdated form after January 7, 2023, they will not be able to access certain features.
> In January, a certificate that enables special features on Adobe forms expires and will need to be replaced. Preparations are underway to ensure seamless access to VA forms, and the Office of Information and Technology (OIT) is leading efforts to ensure that certificates are replaced on every PDF form no later than the January 7, 2023, deadline so VA staff, Veterans, Veteran Service Organizations, and other users can continue to open and download forms from VA websites.
> VA forms that were uploaded to the VA website after March 2, 2022, already have the new Adobe certificate installed. However, many Veterans, dependents, and Veteran Service Organizations (VSOs) access VA forms from locally saved files (such as a copy of a file saved to a personal computer) that have not been updated. If they use an outdated form after January 7, they will not be able to access certain features and will receive an error message that includes the following:
The document has been changed since it was created and use of extended features is no longer available.
> Implementation questions that are not technical or operational can be directed to [Service Delivery Management](mailto:oititopssmpsdm@va.gov).
> Technical issues/concerns: Robert Schmidt, Senior Advisor, DevSecOps (DSO) Office, IT Program Manager, OIT (project sponsor).

### Treatment
This doesn't warrant a full-width alert, and Promo banner is not appropriate. Instead should use the informational or warning alert in the Design system: 
https://design.va.gov/storybook/?path=/docs/components-va-alert--default 
https://design.va.gov/storybook/?path=/docs/components-va-alert-expandable--warning 

This means it likely needs to be hard coded. (Confirm in refinement.)

### Copy
TBD
Will say “forms updated since ____ will have no issues”

### Placement
* Display on Find a form landing page
* Add sniffer & display on forms where the last updated date is older than X.

### Things to clarify
1. Dave proposed maybe adding a CMS field to override showing this banner on specific forms that are not updated since X, but should not warn users. However: also a goal to keep this effort “Down and dirty” - keep it small, e.g. Facility locator notice during COVID. 
2. Are we checking against Issue date, Revision date, or both?  See [history & nuance](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9607#issuecomment-1179352156)
3. What is the date cutoff for which forms show the warning

## Acceptance criteria

- [ ] Warning shows on Find a form landing page
- [ ] Warning shows on Form detail pages with {{?Issue date or Revision date ?}} earlier than {{?line in sand?}}
- [ ] Collab cycle required
  - [Collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49217)

## Background

Resources from email chain Dave C provided:
- Adobe [help page](https://experienceleague.adobe.com/docs/experience-manager-65/forms/administrator-help/configure-acrobat-reader-dc-extensions/updating-expired-reader-extension-certificates.html?lang=en#:~:text=Adobe%20has%20been%20issuing%20certificates%20under%20the%20certificate,features%20dependent%20on%20the%20certificates%20no%20longer%20work.) regarding the issue
  - Adobe's example error message from that page says `The document has been changed since it was created and use of extended features in no longer available. Please contact the author for the orignal version of this document.` will appear _upon attempting to open the pdf_.

Stakeholders
- Brenneman, Tiffany A. <[Tiffany.Brenneman@va.gov](mailto:Tiffany.Brenneman@va.gov)> started email, owns cert update project
- Josh Tuscher (OPIA)
- Robert Schmidt (email chain) says Forms Mgrs will have PDF certs updated by mid-Dec or sooner

**Comment by davidconlon** [comment]
@jilladams @wesrowe isnt' this done?

**Comment by wesrowe** [comment]
Closing.
