### ISSUE TITLE
FE: Implement to consume CMS feature flag to control homepage design deployment for launch

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#10965]
## Description 

During our 9/29 sync, we discussed using a CMS feature flag/config setting to control the  new homepage design deployment to Prod. This issue will implement the Drupal flag/config in the front end which will pull the template into the index during the content build. 

## Tasks

- [ ] Drupal: create CMS feature flag - XS - _to be done during #10626_
- [ ] Implement the flag
- [ ] AR: Ryan to confirm that at this stage of content-build, feature flags are available - S
- [ ] Testing: in Tugboat and locally - M (time consuming bc content-build)

## Acceptance criteria
- [ ] Drupal flag controls whether new version of homepage or old version is deployed on Prod
- [ ] In the event a revert is needed, the feature flag can be used to return the homepage to the previous state.

**Comment by jilladams** [comment]
@ryguyk @dsasser assigning for refinement, just to make sure we caught everything here based on yesterday's discussion. In refinement meeting, we can review any changes we need to make to clarify backend vs. frontend work, as necessary.

**Comment by jilladams** [comment]
Moving this back to Needs Product Definition and assigning to @wesrowe based on our sync with Dave yesterday, in which he suggested: publish both homepage versions, add a modal to allow opting in to the new homepage experience, and collect metrics / qualitative feedback via medallia to inform fully launching the new homepage. We need to settle the discussion around how we are going to launch, before we ask the work suggested here.  (cc @mmiddaugh )

**Comment by jilladams** [comment]
Actually: this should prob be assigned to Michelle, now that I look at it. Updating.

**Comment by wesrowe** [comment]
@mmiddaugh @jilladams, I think we decided against a CMS Feature Flag – instead we'll use a Flipper to control the soft-launch modal. If that sounds right (big IF), we can close.

**Comment by wesrowe** [comment]
this is a no-op - we used a flipper to control the display of the soft-launch modal
