### ISSUE TITLE
Design iteration feedback

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#10982]
## Description
This issue will house feedback on the first pass at the implementation of the Round 2 design iteration for the VA homepage as deployed to https://staging.va.gov/homepage-test/

## Observations in Benefit promo (PACT Act)
`Learn what the PACT Act means to you` link 
- Current: points to staging implementation page
- Expected: should point to https://www.va.gov/resources/the-pact-act-and-your-va-benefits/

## Observations in Other Search tools
Current: `Find a VA facility` link goes to staging version of the Facility Locator, which doesn't work. 
Expected: Should link to va.gov/find-locations

## Observations in Popular links
Typo

- Current: _Dependants_ on your disability benefits
- Expected: Dependents on your disability benefits

## Observations in News promo (Pathfinder)

- Image should not contain any words or fragments of words

**`More VA news` link** 
- Current: points to https://staging.va.gov/homepage-test/
- Expected: should point to https://news.va.gov/

## Observations in Benefit hubs

**Typo in Service member benefits**

- Current: Learn when and how to apply for benefits during service and as _a_ you transition _our_ of service.
- Expected: Learn when and how to apply for benefits during service and as you transition out of service.

**Typo in Disability**

- Current: File and track your _service-connect_ claims and manage your benefits over time.
- Expected: File and track your service-connected claims and manage your benefits over time.

**Typo in Careers and employment**

- Current: Get support for _vocations_ rehabilitation, your small business, or other job-related needs.
- Expected: Get support for vocational rehabilitation, your small business, or other job-related needs.

**Typo in Life insurance**

- Current: Explore life insurance options for _your_ and your family and manage _you_ policy online.
- Expected: Explore life insurance options for you and your family and manage your policy online.

**Typo in Burials and memorials** 

- Current: Plan a burial in a VA national _cemetary,_ request memorial items, and apply for survival benefits.
- Expected: Plan a burial in a VA national cemetery, request memorial items, and apply for survival benefits.

**Typo in Records**

- Current: Apply for a _printer_ Veteran ID card, get your benefit letters and medical records, and learn how to apply for discharge upgrade.
- Expected: Apply for a Veteran ID card, get your benefit letters and medical records, and learn how to apply for discharge upgrade. _(the word would have been printed but should just be ommitted as they are moving to a digital version, fyi)_

**Typo in Family member benefits**

- Current: Find out which benefits you may be eligible for as a _dependant,_ , spouse, survivor, or family caregiver.
- Expected: Find out which benefits you may be eligible for as a dependent, , spouse, survivor, or family caregiver.

**Typo in VA department information**

- Current: Learn more about the VA departments that manage _our_ benefits and health care programs
- Expected: Learn more about the VA departments that manage your benefits and health care programs. _(add period)_
- Link goes to a sign in page - need to determine correct link for this...we may just want to remove the link entirely for usability testing

## Tasks
- [ ]  Update Pathfinder image
- [ ] Update `More VA news` link in News promo area
- [ ] Update `Find a VA facility` link under Other search tools
- [ ] Update/remove Departments link
- [ ] Address typos and punctuation in benefit hubs
- [ ] Add icon needed for VA departments _- this has already been requested from Ryan_

**Comment by laflannery** [comment]
- "Get the tools you need..." Should be a semantic H2, not an H3 as it currently is:
- The SR label added for the search field can be removed.  The search field is a component and a label is already included.  This additional label is not going to be accessible or available to users so it is unnecessary code
![image](https://user-images.githubusercontent.com/106678594/193285686-6448ab3d-53a7-409b-9e63-35fa6e6bd439.png)
- The email signup field above the footer is not labeled correctly.  Can you make the following updates:
  - Remove the SR only label that was added
  - Add an `aria-label="Email Address` to the `<input>`.
  - Please also add `autocomplete="email"` to the `<input>`
![image](https://user-images.githubusercontent.com/106678594/193291378-668549f8-6739-4ea6-b47e-60143cde960e.png)

**Comment by apisandipas** [comment]
The associated PRs have been merged

**Comment by mmiddaugh** [comment]
One of the typos documented in this issue is still present: 
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/5f8aad60-7e79-4e61-b1c1-33ab4673fd0e)

**Comment by mmiddaugh** [comment]
The "Find a VA facility" link in the Other search tools area goes to `https://staging.va.gov/find-a-location/` rather than `https://staging.va.gov/find-locations `

**Comment by mmiddaugh** [comment]
Current: Life insurance benefit hub blurb reads "Explore life insurance options for you and your family and manage `you` policy online."
Expected: "Explore life insurance options for you and your family and manage `your` policy online."

**Comment by mmiddaugh** [comment]
@DanielleThierryUSDSVA @laflannery  I'm wondering if the Pathfinder news promo should say "Read the full article" since it doesn't link to an article.

**Comment by laflannery** [comment]
@mmiddaugh I agree, that is confusing now knowing where it actually links to. @DanielleThierryUSDSVA would you be able to provide more accurate link text - "Learn more about Pathfinder", "Get started with Pathfinder", maybe something along those lines?

**Comment by DanielleThierryUSDSVA** [comment]
Hi @mmiddaugh @laflannery. If this is the news section, I think the better approach would be to make it a rule that anything featured here must link to its full news article. Otherwise the whole section is misleading. Thoughts?

**Comment by apisandipas** [comment]
@mmiddaugh To make clear, all the links were originally implemented as relative links. They would all point to which ever server was hosting the page at the time unless specificed otherwise and I've only changed the ones to point to va.gov that were specified in the original AC. Do they need to all be pointing to the production website? I can make that change if needed.

**Comment by DanielleThierryUSDSVA** [comment]
@laflannery This is a good question. I've joined this effort at a later stage so I'm not sure how the team got to the decision to make this component a news-specific feature.

But the "News" header and then the "More VA news >" link that leads to news.va.gov identify this specifically as news. So I think we need to honor that in what's featured in this component. I think we'd need to ask our OPIA partners if that's too restrictive and, if yes, I think we'd need to then reconsider the component a bit with a broader focus.

**Comment by laflannery** [comment]
For reference for the future - search component works correctly as a `<div>` element with `role=search`.  Bryan and I confirm over slack so he has added that to his most recent PR

**Comment by jilladams** [comment]
@laflannery does that mean we don't need to worry about escalating the `<form>` wrap issue to the Design system team? aka: the `role=search` change is enough to be good for accessibility?

**Comment by cindymerrill** [comment]
I'm still seeing the broken "Find a VA facility link" and typos in the "Service member benefits" and "Life insurance" benefit hub descriptions. When are these expected to be fixed on Staging? I'd like to schedule my pilot tests for after that
. Thanks! @mmiddaugh @jilladams

**Comment by apisandipas** [comment]
I've opened a PR with the fixed Find A VA Facility Link.  The top two items in the issue comment were taken care of in a previous PR. The bottom two remain TBD

**Comment by cindymerrill** [comment]
Thanks for the updates, @apisandipas ! When do you think the fixed Find A VA Facility link will be up on Staging?

**Comment by apisandipas** [comment]
@cindymerrill It will more than likely be sometime tomorrow. I've attempted to accelerate code review, but I'm not certain it will make it thru the process today.

**Comment by apisandipas** [comment]
@cindymerrill it appears the fix to Find VA Location is now up and live at https://staging.va.gov/homepage-test/

**Comment by cindymerrill** [comment]
Yay, looks great. Thanks, @apisandipas !

**Comment by jilladams** [comment]
@mmiddaugh any updates to these 2 items? (Working on mid-sprint report to understand if this ticket is likely to close in sprint): 

1.  Pathfinder news promo CTA Text - Change TBD @mmiddaugh / @DanielleThierryUSDSVA final answer
2.  Staging vs. Prod links - change relative links to be hard links to prod - TBD confirmation from @mmiddaugh

**Comment by jilladams** [comment]
Confirmed with Michelle in scrum these changes will not be included for user testing starting 10/24. 

Created #11287  and #11286 to ensure we follow up on those for launch. Closing.
