### ISSUE TITLE
CMS Codebase and Tech Debt Clean Up 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#11012]
## Background

In an effort to eliminate tech debt, we will have a code clean-up epic to track the items that need to be rectified in our codebase. The reason we do this is to eliminate tech debt and confusion for developers. Also, it will save time in our development process as we create better code. As we perform these clean-up tasks, we can deliver higher quality and more quickly. 

### User Story or Problem Statement

As a CMS developer, I need cleaner code and less tech debt so I can produce more efficiently. 

How might we clean up our code base to deliver higher quality code for editors?

### Affected users and stakeholders

* CMS editors of all products
* Developers of all product teams

### Hypothesis

We believe that a cleaner code base will achieve higher work quality, increased production, and increased satisfaction for developers of the CMS team.

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Less tech debt in the code

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Let's not forget the contrib modules!

**Comment by EWashb** [comment]
this was completed in Q4 2022
