### ISSUE TITLE
Tracking Issue: Checklist for Drupal 10 Upgrade

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11014]
## Description
This is just a compilation of things that we need to do prior to the D10 upgrade.

### Environment
![Screen Shot 2023-01-18 at 8 31 41 AM](https://user-images.githubusercontent.com/1318579/213184483-a4ad0241-e341-4ba6-a713-775dc525dbfc.png)

### Contrib Modules w/ Unknown or Incompatible Status
The following modules need to be checked on an individual basis to determine what their maintenance status is and what their progress is toward Drupal 10 compatibility.

- [ ] Admin Toolbar 3.0.0
- [ ] Automatic Entity Labels 8.x-3.0-beta3
- [ ] Block Content Permissions 8.x-1.10
- [ ] Corresponding Entity References
- [ ] Config Ignore 8.x-2.3
- [ ] Config Override Warn 8.x-1.3
- [ ] Serialization (CSV) 8.x-2.1
- [x] #12261
- [x] #12263
- [ ] Entity Clone 8.x-1.0-beta7
- [ ] Entity diff UI plugins 1.0.1
- [ ] Entity Field Fetch 1.0.2
- [ ] Entity Reference Unpublished 8.x-1.3
- [ ] Entity Reference validators 8.x-1.0-beta1
- [x] #12262
- [ ] Fast 404
- [ ] Flysystem 2.0.0-beta1
- [ ] Flysystem Amazon S3 2.0.0-rc5
- [x] #12264
- [ ] GovDelivery Bulletins 8.x-1.7
- [ ] GraphQL 8.x-3.1
- [ ] GraphQL Menu 8.x-1.0-alpha2
- [ ] GraphQL Metatag 8.x-1.9
- [ ] Health Check URL 8.x-3.1
- [ ] HMS Field
- [ ] Hook Event Dispatcher 3.2.0
- [x] #12265
- [x] #12266
- [ ] JSON:API Views 8.x-1.0
- [ ] Limited Widgets For Unlimited Fields 2.0.4
- [ ] Linkit 6.0.0-beta3
- [ ] Markup 8.x-1.0-beta5
- [ ] Media Entity Generic 8.x-1.1
- [ ] Menu Breadcrumb 8.x-1.16
- [ ] Menu Export 8.x-1.3
- [ ] Menu Force 8.x-1.2
- [ ] Message UI 8.x-1.0-beta4
- [ ] Metatag 8.x-1.21
- [ ] Migrate Plus 8.x-5.3
- [x] #12267
- [ ] Migrate Tools
- [ ] Migration Tools 8.x-2.4
- [ ] Node Title Help Text 8.x-1.2
- [ ] Office Hours 8.x-1.7
- [ ] Override Node Options 8.x-2.6
- [ ] Paragraphs Browser 8.x-1.0
- [x] #12268
- [ ] Password Strength
- [ ] Redirect Import 8.x-1.0-beta5
- [ ] Pathauto 8.x-1.10
- [ ] Pathologic 8.x-1.0-alpha3
- [ ] Post API 2.0.1
- [ ] Redirect Options 2.0.2
- [ ] SimpleSAMLphp Authentication 8.x-3.3
- [ ] Slack 8.x-1.3
- [x] #10490
- [ ] String Field Formatter 2.0.0
- [ ] TableField 8.x-2.3
- [ ] Taxonomy Menu
- [ ] Textfield Counter 2.0.0
- [ ] Toolbar Menu 8.x-2.2
- [ ] Viewfield 8.x-3.0-beta6
- [ ] Views Bulk Operations 8.x-3.12

### Custom Modules
- `va_gov_clone` is flagged to suggest removal, but it serves a purpose for scalability testing with new frontends and should be retained.
- #10999
- #11000
- #11001
- #11003
- #11005
- #11006
- #11013

## Acceptance Criteria
- [ ] Followup issues for addressing each of the above _unaddressed_ issues are opened.

**Comment by EWashb** [comment]
We need to re-refine this once we get our ducks in a row on the Drupal 9.5 upgrade.

**Comment by EWashb** [comment]
Is this still a thing we need to track with @BerniXiongA6? Seems like a duplicate of other tickets, but Nate may have some good stuff listed here that we need to ensure we've accounted for other places

**Comment by BerniXiongA6** [comment]
I've added the "needs refining" label so we don't forget this ticket -- thanks past @ndouglas for creating this ticket for current Nate and Berni. Very helpful as we're finally ready to deploy soon and will need to know "how" to get there. cc: @EWashb

**Comment by ndouglas** [comment]
I'll take a peek at this -- I think it may no longer be relevant, but I'd like to confirm 🙂

**Comment by ndouglas** [comment]
Yep, @edmund-dunn has already addressed all of these.
