### ISSUE TITLE
Editors should not be able to edit archived facilities

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11028]
## User Story or Problem Statement

As a maintainer of facility data, it is important that editors can not accidentally re-open facilities that have already been closed and properly  archived.

![image](https://user-images.githubusercontent.com/5752113/193475489-0194fb4b-a7e0-426c-a7e7-e21e31a835f3.png)

It is  questionalble whether a facility should ever be editable at all once it has been archived.   We might want to either (need to discuss)
A. Prevent save.
B. Prevent Edit tab from showing
C. Its moderation state can only be altered by content admin/admin through request fulfillment

## Acceptance Criteria
- [ ] When a facility is archived, ____

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Suggestion: If publish state is archive, and they're non admin, dont display Save button - or- Remove Edit tab?

**Comment by Dottisea** [comment]
Add a spike ticket for discovery on this workflow - discover and document

**Comment by JayDarnell** [comment]
I've updated this ticket to be slightly more accurate based on recent facility help desk work. However, some refinement is still needed in terms of agreeing upon the most effective solution for the problem.

**Comment by kmariepat-cityfriends** [comment]
@kmariepat-cityfriends talk with CMS team about driving the decision for editor experience when they cant edit things, this card will live on for facilities as strictly implementation

**Comment by davidmpickett** [comment]
Here's another ticket that has some slightly different nuance, but seems very related https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11481

**Comment by davidmpickett** [comment]
And also: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11778

**Comment by davidmpickett** [comment]
And here's an issue for improving a related KB Article https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11243

**Comment by timcosgrove** [comment]
This could easily be implemented as a VAMC Facility-specific workflow that disallows an Archive -> Published or Archive -> Draft transition, or else restricts that transition to admins.

**Comment by davidmpickett** [comment]
The work done in #15869 has created a clear path forward to implementing this. Consider as a possible Q1 ticket? @xiongjaneg @swirtSJW @omahane

**Comment by omahane** [comment]
> The work done in #15869 has created a clear path forward to implementing this. Consider as a possible Q1 ticket? @xiongjaneg @swirtSJW @omahane

When we do so, here's some guidance: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15869#issuecomment-1863191934

**Comment by xiongjaneg** [comment]
See [Slack thread on timing/order](https://dsva.slack.com/archives/C0FQSS30V/p1703093860274259)

**Comment by mmiddaugh** [comment]
This should also apply to VBA facilities

**Comment by davidmpickett** [comment]
> This should also apply to VBA facilities

It already does. 😎  They were the first content type to get migrated over to the Restrictive Archive Workflow. That was completed in #15869.

**Comment by omahane** [comment]
@xiongjaneg I recommend we change this to "Editors should not be able to publish archived facilities," given that the Restricted Archive workflow allows editors to edit archived nodes, but not to publish them.
