### ISSUE TITLE
Upgrade Tugboat from 2.22.7 to 2.22.8

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11058]
### Tasks:
- [x] Change directories to the Tugboat root: `cd /opt/tugboat`
- [x] Fetch the latest tags: `git fetch --tags`
- [x] Checkout v2.22.8: `git checkout v2.22.8`
- [x] Build: `make && make install`
- [x] Reload Tugboat: `tbctl reload`
- [x] Wait for Tugboat to start up successfully. For the lazy: `wget --quiet -O- --tries=100 --retry-on-http-error=404,502,503 --retry-connrefused https://[tugboat-dashboard-host]/_status`

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
yarn.lock was dirty, I wiped out this change so I could checkout 2.22.8.

```diff
[root@ip-172-31-1-159 tugboat]# git diff
diff --git a/yarn.lock b/yarn.lock
index cb95ac4b1..cc7e00a2e 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -13457,7 +13457,7 @@ protobufjs@^7.0.0:
     "@types/node" ">=13.7.0"
     long "^5.0.0"
 
-protocols@^1.1.0, protocols@^1.4.0:
+protocols@^1.4.0:
   version "1.4.8"
   resolved "https://registry.yarnpkg.com/protocols/-/protocols-1.4.8.tgz#48eea2d8f58d9644a4a32caae5d5db290a075ce8"
   integrity sha512-IgjKyaUSjsROSO8/D49Ab7hP8mJgTYcqApOqdPhLoPxAplXmkp+zRvsrSQjFn5by0rhm4VH0GAUELIPpx7B1yg==
```

**Comment by ElijahLynn** [comment]
This is done :heavy_check_mark:.

start: 4:02:44pm PT
end: 4:03:30pm PT

Total downtime 46 seconds.
