### ISSUE TITLE
Upgrade to Tugboat v2.23.0

### ISSUE THREAD

**Issue by q0rban** [department-of-veterans-affairs/va.gov-cms#11051]
### Tasks:

- [x] Change directories to the Tugboat root: `cd /opt/tugboat`
- [x] Fetch the latest tags: `git fetch --tags`
- [x] Checkout the tag (e.g. `git checkout v2.23.0`)
- [x] Build: `make && make install`
- [x] Reload Tugboat: `tbctl reload`
- [x] Wait for Tugboat to start up successfully. For the lazy: `wget --quiet -O- --tries=100 --retry-on-http-error=404,502,503 --retry-connrefused https://[tugboat-dashboard-host]/_status`

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

#### v2.23.0 - 10 Jan, 2023

```
    #4447 chore: bump react-ga from 3.3.0 to 3.3.1
    #4446 chore: bump eslint-plugin-prettier from 4.0.0 to 4.2.1
    #4445 chore: bump inspector-api from 1.4.2 to 1.4.5
    #4444 chore: bump reselect from 4.1.1 to 4.1.6
    #4493 chore: bump @babel/core from 7.15.5 to 7.19.3
    #4503 chore: clean out authenticateRepo argument destructuring (#4504)
    #4486 fix: do not render api authentication section in UI if provider isn't specified (#4499)
    #4507 fix: speed up CLI build
    #4397 fix: change style and language around draft PR option (#4520)
    #4532 chore: bump mongoose from 6.6.0 to 6.7.0 (#4532)
    #4533 fix: increase vagrant cpus to 2 to match tugboat projects
    #4524 fix: handle errored jobs gracefully on agent message queue (#4535)
    #4488 fix: do not assume metadata is an object when logging (#4540)
    #4546 fix: destructure TugboatError off of requires (#4547)
    #4526 chore: bump babel-loader from 8.2.2 to 8.2.5
    #4538 chore: bump qrcode from 1.4.4 to 1.5.1
    #4558 fix: dequeue jobs on the agent from the api (#4569)
    #4580 feat: configurable http listen ports (#4581)
    #4525 fix: handle errors around tagging an image (#4586)
    #4582 feat: report OOMs in log (#4589)
    #4557 chore: bump react-router from 5.3.3 to 5.3.4
    #4578 chore: bump mongoose from 6.7.0 to 6.7.2
    #4590 chore: bump loader-utils from 1.4.0 to 1.4.2
    #4549 feat: make error 137 more explicit in log messages (#4593)
    #4597 fix: do not rebuild 'ready for review' PRs (#4599)
    #4610 fix: bump react-router-dom to 5.6.4
    #4607 chore: bump engine.io from 6.2.0 to 6.2.1
    #4596 chore: bump core-js from 3.25.1 to 3.26.1
    #4627 fix: sync yarn.lock with package.json
    #4562 fix: handle errors thrown from async functions in message queues (#4600)
    #4615 chore: bump dockerode from 3.3.1 to 3.3.4 (#4615)
    #4594 chore: bump redoc from 2.0.0-rc.74 to 2.0.0 (#4594)
    #4541 fix: queue up visual diffs on agent to mitigate memory leakage (#4647)
    #4612 fix: updating handling of exceptions in webhooks service (#4616)
    #4567 feat: add ability to restart agent from admin ui (#4659)
    #4664 feat: support no tty with tugboat cli shell command arg (#4665)
    #4663 chore: bump json5 from 1.0.1 to 1.0.2 (#4663)
    #4641 chore: bump decode-uri-component from 0.2.0 to 0.2.2 (#4641)
    #4042 fix: check if visualdiffs is an array in config
```

#### v2.22.8 - 01 October, 2022

- https://github.com/Lullabot/tugboat/pull/4366 chore: bump passport from 0.5.0 to 0.5.3
- https://github.com/Lullabot/tugboat/pull/4266 accept ADR for the switch from enzyme to RTL
- https://github.com/Lullabot/tugboat/pull/4396 chore: bump mongodb from 4.1.3 to 4.9.0
- https://github.com/Lullabot/tugboat/pull/4395 tests: add a gha workflow to run shellcheck on shell scripts
- https://github.com/Lullabot/tugboat/issues/4400 feat: switch to markdown-only ADRs
- https://github.com/Lullabot/tugboat/issues/4351 feat: add a GitHub pull-request template
- https://github.com/Lullabot/tugboat/issues/4411 fix: only create new GitHub deploy keys if force updating repo auth
- https://github.com/Lullabot/tugboat/issues/4438 feat: stop containers from suspended/stopped previews in clean-agent.sh
- https://github.com/Lullabot/tugboat/pull/4441 chore: bump core-js from 3.22.2 to 3.25.1
- https://github.com/Lullabot/tugboat/pull/4431 chore: bump moment-timezone from 0.5.33 to 0.5.37
- https://github.com/Lullabot/tugboat/pull/4408 chore: bump bytes from 3.1.0 to 3.1.2
- https://github.com/Lullabot/tugboat/pull/4407 chore: bump @opentelemetry/semantic-conventions from 1.5.0 to 1.6.0
- https://github.com/Lullabot/tugboat/issues/4432 fix: add space between link and text (https://github.com/Lullabot/tugboat/pull/4436)
- https://github.com/Lullabot/tugboat/pull/4443 chore: bump socket.io from 4.5.1 to 4.5.2
- https://github.com/Lullabot/tugboat/pull/4442 chore: bump mongoose from 6.0.12 to 6.6.0
- https://github.com/Lullabot/tugboat/pull/4390 chore: bump smtp-server from 3.9.0 to 3.11.0
- https://github.com/Lullabot/tugboat/issues/4428 fix: use pngjs 6.0.0 with blink-diff

**Comment by q0rban** [comment]
Possible duplicate of #11058?

**Comment by q0rban** [comment]
v2.23.0 is released now so I've updated the title and description. cc @ElijahLynn

**Comment by ElijahLynn** [comment]
Thanks @q0rban, we are on:

```
[root@ip-172-31-1-159 tugboat]# git status
HEAD detached at v2.22.8
```

And will get this update soon.

**Comment by ElijahLynn** [comment]
This is done: 

> Dashboard OK: 2.23.0
