### ISSUE TITLE
Form audit tools in CMS

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11066]
## Background

Two important enhancements to Form audit tools in the CMS:

1. The current CMS has a Forms Flags view that is like a news feed for flags of different types. It's a little hard to work with and can't be filtered on a single flag for technical reasons. Also, flags can only be cleared one at a time by unchecking a box on the Edit Detail screen.
2. There's not currently a way to audit Form Detail pages for content existence, quality, etc.

Desired use cases:
- audit Form Detail pages to help manage pages for quality, determine whether to publish/archive, etc.
- view all instances of a single flag type
- take bulk actions on all instances of a single flag type, especially "clear flag"

Existing flags:
- Deleted
- New
- Changed filename
- Changed title

**Recommended pattern:** 

Facilities has a bunch of different views as tabs. 

Screenshot:
![image.png](https://images.zenhubusercontent.com/61a671f5fc46c2a311655f75/a2a41714-0420-4495-83ec-fe580ac29404)

### Affected users and stakeholders

* CMS admins and SW Content team

## Acceptance Criteria
- [ ] New views support more efficient management of Form Details
- [ ] Editors can monitor and respond to forms Flags more efficiently
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
