### ISSUE TITLE
CMS: Lovell Listing page parity enforcement

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11069]
## User Story or Problem Statement

As a Lovell editor I need a guard rail so I can not choose a mismatched section and listing page combination that creates confusion and mayhem on the following content types.

![image](https://user-images.githubusercontent.com/5752113/193959588-5ede032f-57e3-4085-bf85-4ac41c72d0ce.png)

This could be handled either with entity validation that prevents save with an error, or with JS that forces parity once the section is chosen.

## Acceptance Criteria
- [ ] Only applies to the three lovell varieties
- Applies to three content types
   - [ ] Event
   - [ ] Story
   - [ ] News release
- [ ] Can not choose a section that is out of parity with listing page.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
We'll have to decide whether to handle this via entity validation or via JS trickery.

The advantage to JS trickery is that it is a cleaner easier path for editors.
The advantage of entity validation is that we are not loading a bunch of JS for every single instance of a list item. (scope of the js include can not be restricted by Lovell.. only the logic within can)

**Comment by JayDarnell** [comment]
@davidmpickett what adjustments would you make to this error message?

<img width="1481" alt="Screen Shot 2022-10-26 at 5 50 04 PM" src="https://user-images.githubusercontent.com/21045418/198145258-0c99ad3c-5c83-4f36-a818-9421fcf91b1a.png">

**Comment by davidmpickett** [comment]
Adding screenshots of the relevant portion of the Story and News Release node for context 

![Screen Shot 2022-10-27 at 4 22 21 PM](https://user-images.githubusercontent.com/51967950/198401193-eaf3e7b1-cc8f-45a1-b4c9-6e5e4be4b8c0.png)

![Screen Shot 2022-10-27 at 4 24 11 PM](https://user-images.githubusercontent.com/51967950/198401198-c7b4d176-442a-4ee9-8d93-43ccc35edad2.png)

**Comment by davidmpickett** [comment]
Not sure how much control y'all have over this error message, but here's my perspective

Two options here: 
A) Three different error messages, for the three different nodes this could show up on that use the same terminology as those nodes.
B) A single error message that shows up exactly the same in all three nodes 
 
If we want a single error message that has the same wording in all three instances, we need to resolve the fact that the drop-down isn't consistently labeled in those three places.
- "VA.gov event list"
- Where the story will be listed
- "News release listing"

The general template for the error message would be something like:
The "unified term for list" you selected is not part of the section for this "event/story/news release". Please choose a different "unified term for list" or change the section settings to match.

FYI This is what I reference when writing error messages - https://wix-ux.com/when-life-gives-you-lemons-write-better-error-messages-46c5223e1a2f

**Comment by JayDarnell** [comment]
@davidmpickett I believe I can craft the message to explicitly tell the editor which value IS valid. I have access to the content type name and the displayed values in the list page dropdown are simply a concatenation of the <Section name>: <content type>s
