### ISSUE TITLE
The Quality Assurance Metrics Epic

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11070]
(a.k.a. The Quality Assurance Metrics Memorial Orchestra & Tra-La-La Band)

## Description
This epic tries to organize gathering QA metrics, since I recently learned that I'm almost halfway through the "gathering metrics" phase of the Q4 QA Standards initiative.

First, I'ma make a list, then I'ma check it twice, then I'ma create issues for everything in the list, then I'ma close the issues.

## Metrics in DataDog

- [ ] #11082
- [ ] #11081
- [ ] #11079
- [ ] #11075
- [ ] #11080
- [ ] #11077
- [ ] #11078
- [x] #11071
- [x] #10921 

## Meta-Metrics

- [x] #11073
- [x] #11074
- [x] #11083
- [x] #10988 
- [ ] #10990 [Blocked]
- [x] Investigate derivatives of Issue and PR metrics
  - [x] First derivative of issue count
  - [x] First derivative of PR count
- [x] Verify or investigate recording and reporting
  - [x] Open issue count
  - [x] Open PR count
  - [x] Recently opened issues
  - [x] Recently opened PRs
  - [x] Recently closed-as-completed issues
  - [x] Recently closed-as-merged PRs 
  - [x] Stale issue count
  - [x] Stale PR count
  - [x] Length of time PRs are open before final approval
  - [x] Distribution of engineers approving pull requests
- [x] Add to QA Dashboard
  - [x] Sentry errors (depends on #11071)

## Acceptance Criteria
- [x] Individual issues have been created for creating all of the above issues.

**Comment by ndouglas** [comment]
This is really just an organization ticket, so this can be considered done.
