### ISSUE TITLE
FY23 Q1 CMS Monitoring and Alerting

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11076]
## Background
This effort will be timeboxed quarterly for tracking purposes.

Our CMS integrates with multiple external systems. The operation and behavior of these systems can negatively affect CMS functionality. Application performance monitoring was implemented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5796; we will continue to improve visibility into code quality and system performance through further APM enhancements and additional levels of alerting as needed.

### User Story or Problem Statement

As a CMS Engineer, I need to utilize the increased visibility of system usage and performance provided by APM, in order to proactively monitor and improve the system's performance and maintain operation of the CMS system.

### Affected users and stakeholders

* CMS editors
* CMS engineers

### Hypothesis

We believe that documenting and monitoring external dependencies will allow CMS team to be more aware of and respond more effectively to issues that affect the functionality of the CMS. We'll know that to be true when more systems that affect CMS are monitored and the time to resolution is decreased.

## Goals

- [ ] Identify opportunities to proactively address any downtime and system issues 

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
Closing out this epic to shift how we track on the board.
