### ISSUE TITLE
Sprint 69 - Facilities | Oct 10 - Oct 23

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11110]
<details><summary>Quarterly Initiatives</summary>

List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9655 Lovell 
- #9659 VBA MVP
- #1392 Banners 

**Blocked until LH team moves forward**
- #10798  Lighthouse v1
</details>

<details><summary>OOO</summary>

CivicActions Field Days  13, 14 
Jay, Christian, Swirt, Dave P, Aslan

Who | When | Backup 
----- | ------ | ------- 
National Holiday for Many | 10/10 | 
Dave C | 10/10 - 10/18 | Danielle
Dave C | 10/18 - 10/21 Onsite | Danielle
Christian | 10/17 - 10/8  | Jay/Swirt

</details>

🥅   — Sprint goals (pending Sprint planning)

## Facility COVID status post-launch
- [ ] #10842 DSN Operating Status editor interface COVID modifications

## Facility Locator

**PM** 

## VBA Facilities

**PM**
- [ ] #11139 Overall VBA architecture 

**Design**
- [ ] #10195 Synthesize and report 🥅
- [ ] #10196 Document research findings  

**Engineering**
- [ ] #10911 Add VBA fields 🥅
- [ ] #11137 Add VBA service taxonomy fields 
- [ ] #11142 Select new framework with Platform 

**Move to next sprint (these migrations are dependent on work above being completed first)**
- [ ] #10914 Update VBA migrations 🥅
- [ ] #11143 Build initial VBA queries 

## VAMC

- [ ] #10907 Link service to ATC performance data 

### Banners
**Engineering** 
**PM**
- [ ] #11141 Define text limit and guidance for Banners 
- [ ] #9970 Lovell taxonomy needs 

### Lovell #9655
- [ ] #10854 Lovell testing and punchlist
- [ ] #11124 Lovell sitemap 🥅
- [ ] #11123 VA service description  
- [ ] #10168 Lovell support multiple lists 

**Design**
- [ ] #9973 Investigate VISN 12 impact on Lovell 
- [ ] #9770 Lovell taxonomy needs

**PM** 

**Engineering** 
Update Lovell runbook currently in draft  
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11027 Top nonclinical service location 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11069 Lovell Listing page parity

## Vet Centers
- [ ] #10706 Archived CAPs showing in preview
- [ ] #10707  Archived/draft content showing 
- [ ] #10528 Changing mind on office hours 
- [ ] #10739 Account blocked from selecting site section

## Stretch
- [ ] #11040 Limit alerts per system STRETCH <- Can sit as PR til ready to pull trigger

## General Frontend
- [ ] #10656 Execute on [Flippers Audit ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10350)

## Blocked
<details><summary>Blocked by V1 release</summary>
The following Lighthouse issues are dependent on the release of Lighthouse V1

- [ ] #8017 Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
- [ ] #4411 Push CAP data 
</details>

**Comment by RWEagans** [comment]
Closing out Sprint 69
