### ISSUE TITLE
Get up to speed on 508 table accessibility project

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11112]
## Description
As Design Lead, I need to understand the background for 508 table accessibility project, so I can make sure it receives adequate design support in Q4.

## Acceptance Criteria
- [x] Acquaint myself with the background
  - [x] [Original defect report](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10372)
  - [x] [Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10673)
  - [x] [Old Sitewide CMS epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2932)
  - [x] [Figma redesign of tablefield UI](https://www.figma.com/file/GiUzUBdo7HJaRsoNdie38U/Tableview-Patch-UI?node-id=0%3A1)
  - [x] [Table audit](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10793)
  - [x] [Ticket where my input might be needed](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11084)
  - [x] [This ticket that seems important](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10683)
- [ ] Confirm my understandings with key team members and make a plan

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
I've got a good handle on this and feel confident in being able to jump back in when needed.
