### ISSUE TITLE
Outreach materials tag & filtering taxonomy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11131]
## Background

We want to base [Outreach Materials](https://www.va.gov/outreach-and-events/outreach-materials/) tagging and FE filtering on a taxonomy in Drupal in order to:

- Make setup and changes completely Drupal-driven
- Enable a better Veteran experience where there are no zero-result filter options
- Enable multi-tagging
- Create a more consistent experience for Editors and Veterans by sharing a taxonomy with Resources & Support

[Order of operations](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11328)

### User Story or Problem Statement
This is just an epic container for all things [Outreach materials](https://www.va.gov/outreach-and-events/outreach-materials/)

### Affected users and stakeholders

<link to any existing research or data supporting this>

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Outreach Materials deprecated in fall of 2022, as VEO moving the materials elsewhere.

**Comment by FranECross** [comment]
Closing as a no op; Outreach Materials deprecated in fall of 2022, as VEO moving the materials elsewhere.
