### ISSUE TITLE
Roadmap and plan for the transition off of BRD

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11133]
## Background
In preparation for the eventual move off of BRD, we'll need to do some investigative work and map out steps to accommodate.

Because the timeline to transition is unknown there isn't a hard deadline for this that we know.

What we do know is that the Platform Crew will be moving away from BRD to Argo Workflows at some point.

Based on our audit in #9765 our suggested path forward entails:
1. Migrating all identified tasks (build tasks, deployment tasks, run time tasks) from Jenkins to GHA
2. Revisit the current architecture and where Platform Crew is at with their plans for the future
3. Make a determination on where we want to go
4. Implementing that roadmap

## Acceptance Criteria
- [x] Existing CMS build and deployment tasks are documented #9765 
- [ ] A determination has been made on which of those need to be transitioned and how
- [ ] A roadmap is created with steps / issues on the board to complete
  
## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
