### ISSUE TITLE
Crosswalk the  outreach materials field topics with existing R&S taxonomy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11144]
There is a bit of overlap / replication with the field values for outreach_asset:field_benefits (Related Benefits)  and the taxonomy of [Resources and Support](https://prod.cms.va.gov/admin/structure/taxonomy/manage/lc_categories/overview) (lc_categories) 

These two lists need to be studied for overlap and gaps.

Currently the taxonomy has no fields.  There may be a need for additional fields that need to be added to support using it that may emerge from the crosswalk and related discussions.   
examples:

- plain language name vs official name (ie. Burial Benefits And Memorial Items VS Burials and memorials)
- key (machine name) that does not change, even though the Friendly name might  (ie. burial|Burial Benefits And Memorial Items)
- Centralized description?
- url to hub page?
- ? 

## ACs
- [ ] List of terms to be added to Resources and Support Taxonomy and add them to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11148
- [ ] List of any conversions that will be needed in the upcoming migration  from select list to entity reference (ie. General Benefits Information  -> Other topics and questions) and add them to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11147
- [ ] list of fields that need to be added defined on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11146

**Comment by swirtSJW** [comment]
Here are the existing key value pairs from Publication (outreach_asset) :Related Benefits (field_benefits) 
https://prod.cms.va.gov/admin/structure/types/manage/outreach_asset/fields/node.outreach_asset.field_benefits/storage
```
general|General Benefits Information
burial|Burial Benefits And Memorial Items
careers|Careers And Employment
disability|Disability Compensation
education|Education And Training Benefits
family|Family member benefits
healthcare|Health Care
housing|Housing Assistance
insurance|Life Insurance
pension|Pension Benefits
service|Service Member Benefits
records|Records
```

**Comment by wesrowe** [comment]
[copied from Dave Conlon email] The cross walk is shown below. Items in yellow are unique to the original list, one item in red is effectively the same but phrased differently between the two sets.

Outreach materials topics "taxonomy":

    Burials and memorials
    Careers and employment
    Disability
    Education and training
    Health care
    Housing assistance
    Life insurance
    Pension
    Records
    (unique/yellow) Service member benefits
    (unique/yellow) Family member benefits
    (unique/yellow) General benefits information

R&S taxonomy:

    Burials and memorials
    Careers and employment
    (unique/yellow) Decision reviews and appeals
    Disability
    Education and training
    Health care
    (red/wording different) Housing assistance **_and home loans_** (last bit is difference)
    Life insurance
    Pension
    Records
    (unique/yellow) VA account and profile
    (unique/yellow) Other topics and questions

A unified list would look like:

    Burials and memorials
    Careers and employment
    Decision reviews and appeals
    Disability
    Education and training
    Family member benefits
    Health care
    Housing assistance and home loans
    General benefits information
    Life insurance
    Pension
    Records
    Service member benefits
    VA account and profile
    Other topics and questions

## Screenshot with colors
<details>
<summary>Screenshot</summary>
<img width="168" alt="image" src="https://user-images.githubusercontent.com/4054752/196305879-29779e1e-f224-424d-87f9-99210e8c150b.png">
</details>

**Comment by wesrowe** [comment]
@swirtSJW, please see details above. Does this work that Dave C shared complete the cross-walk?

**Comment by swirtSJW** [comment]
@wesrowe I think largely that unified list would cover it.  The taxonomy could be updated to match that list. It is content not config so can be edited by hand.  

There are other questions in the issue about possible need for new fields on the taxonomy.  They are probably not needed or could be added down the road when they are.

**Comment by swirtSJW** [comment]
I updated the list on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11148 to cover the additions and changes from the unified list above.

**Comment by wesrowe** [comment]
Thank you @swirtSJW and I'm closing this issue as complete.

**Comment by jilladams** [comment]
@davidconlon  @wesrowe I am just now realizing: this whole thing started as a means of getting Pact Act into the taxonomy: except it's not in the unified list: 

```
A unified list would look like:

Burials and memorials
Careers and employment
Decision reviews and appeals
Disability
Education and training
Family member benefits
Health care
Housing assistance and home loans
General benefits information
Life insurance
Pension
Records
Service member benefits
VA account and profile
Other topics and questions
```

Wes email on 10/18: 
> Beth & Danielle – FYSA, the PW team is refining this taxonomy work to enable adding PACT Act as a filterable term in Outreach Materials. Looping in Dave Pickett for  the assist on our side. When [this epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11131) is complete, Outreach Materials and R&S will share a taxonomy that includes the PACT Act. And we will have built a more resilient system for the addition of future terms/categories.

It should be added as a new term?
