### ISSUE TITLE
[Research] Conduct research: Income Limits App

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11167]
## Description
An [existing application](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits) allows Veterans, their caregivers, family members, and others to look up the income limits for VA National medical benefits and prescriptions based on location and number of dependents. 

This issue continues the work started by Florence and covers the tasks needed to conduct Veteran research sessions designed to inform the redesign of the application.

[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md)

## Tasks
- [ ]  Print conversation guide
- [ ]  Post to #feedback-backchannel right before session starts with observer instructions and participant description
- [ ]  Conduct scheduled research sessions
- [ ]  Debrief research sessions w/team
- [ ]  Post debrief/updates on slack
- [ ]  Debrief research sessions into note-taking spreadsheet
- [ ]  Download recordings
- [ ]  Download notes from Perigean
- [ ]  Download final participant list from Perigean
- [ ]  Change display name of Perigean Zoom account back to what it was
- [ ]  Close out ticket once all research sessions have been completed (Move to research synthesis ticket)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@cindymerrill @wesrowe @mmiddaugh  - can this ticket now be closed as a no-op?

**Comment by cindymerrill** [comment]
Closing because decision was made to not conduct any more research sessions than have already happened.
