### ISSUE TITLE
[Research] Synthesis and reporting: Income Limits App

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11168]
## Description
This research will inform the redesign of the Income limits app.

## Tasks
- [x]  Clean up notes spreadsheet
- [x]  Write topline summary and share out with team
- [x]  Do data analysis/synthesis of data collected from research
- [x]  Write research report

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cindymerrill** [comment]
@jilladams @mmiddaugh No because I'm still planning to write up a summary of what I learned from the first set of sessions. This work is planned for next week.

**Comment by jilladams** [comment]
@cindymerrill could you point us to the artifact of the summary?

**Comment by cindymerrill** [comment]
I'm just starting to write it, and I'd like to wait to share it until I'm done, if that's OK @jilladams

**Comment by wesrowe** [comment]
That's great, thank you @cindymerrill. @davidmpickett and @thejordanwood might appreciate a little time to ask you questions before you travel, if that turns out to be possible. Jordan is the UX designer who will carry on from your work.

**Comment by cindymerrill** [comment]
@wesrowe Possibly next Monday, if I finish the report early enough in the day?

**Comment by cindymerrill** [comment]
@wesrowe I finished drafting the topline report today, and I'm planning to make revisions on Monday 11/28 after my home page redesign usability test readout ends at 2 pm ET. I could meet with @davidmpickett and @thejordanwood anytime after that, except for 4-5 pm.

**Comment by jilladams** [comment]
From slack: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/topline.md
