### ISSUE TITLE
[Research] Prep Tasks: Income Limits App

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11166]
## Description
An [existing application](https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits) allows Veterans, their caregivers, family members, and others to look up the income limits for VA National medical benefits and prescriptions based on location and number of dependents. This issue covers the tasks needed to prep for Veteran research sessions designed to inform the redesign of the application. 

This continues the work started by Florence. 

[Research plan](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/income-limits-app/research/research-plan.md)

## Tasks

- [x] Update research plan and conversation guide with current timeline and protocol updates
- [x] Share research plan and conversation guide with Shane for approval and recruiting
- [x] Make note-taking spreadsheet
- [x] Schedule pilot
- [x] Change display name of Perigean Zoom account to "Cindy (Moderator)"
- [x] Run pilot
- [x] Debrief pilot
- [x] Send thank you notes to pilot participant
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [ ] Schedule team debrief sessions once a day
- [x] Follow-up with Perigean re participant list
- [ ] Other tasks as needed

## Acceptance Criteria
- [ ] Completed prep tasks in support of research actions

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cindymerrill** [comment]
All prepared for pilot test tomorrow (Fri Oct 14)

**Comment by cindymerrill** [comment]
Run pilot test, debriefed with Wes and Michelle, revised convo guide, scheduled debrief meetings around the research sessions next week. Wes is going to invite team members to the research sessions.

**Comment by cindymerrill** [comment]
All set for sessions starting tomorrow

**Comment by cindymerrill** [comment]
I'll need this task again in November so I can remember to schedule daily debrief sessions then, which I haven't done yet @davidmpickett

**Comment by cindymerrill** [comment]
Closing because won't be running any more research sessions
