### ISSUE TITLE
Sprint 70 - Facilities | Oct 24 - Nov 6

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11206]
<details><summary>Quarterly Initiatives</summary>

List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9655 Lovell 
- #9659 VBA MVP
- #1392 Banners 

**Blocked until LH team moves forward**
- #10798  Lighthouse v1
</details>

<details><summary>OOO</summary>

CA Virtual Summit 1/2 day Oct 28th, Nov 4th

Who | When | Backup 
----- | ------ | ------- 
Dave P | Oct 26 - half day | Aslan & Blake
Dave P | Oct 31- Nov 14 | Aslan & Blake
Ryan | Oct 27 - 31 | Swirt (?)

</details>

🥅   — Sprint goals (pending Sprint planning)

## Facility COVID status post-launch
- [ ] #10842 DSN Operating Status editor interface COVID modifications

## Facility Locator

**PM** 

## VBA Facilities

**PM**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11207

**Design**
- [ ] #10196  Veteran research and readout 🥅
- [ ] #10506 PCT research plan review 
- [ ] #10507 Finalize PCT
- [ ] #11211 PCT Research runbook 
- [ ] #11210 PCT CMS review cycle 
- [ ] #10510 Update VBA MVP after content audit 
 

**Engineering**
- [ ] #11197 Add VBA Services content type
- [ ] #10914 Update VBA migrations
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11138

## VAMC

- [ ] #10907 Link service to ATC performance data 
- [ ] #11311 QR code instructions

### Banners
**Engineering** 
- [ ] #11040 Limit alerts per system STRETCH <- Can sit as PR til ready to pull trigger (Jay - in progress)

**PM**
- [ ] #11141 Define text limit and guidance for Banners 

### Lovell #9655
- [ ] #10854 Lovell testing and punchlist
- [ ] #10168 Lovell support multiple lists 
- [ ] Lovell services assessment/plan - Update with Dave C 

**Design**
- [x] #11215 
- [x] #11214

**PM** 

**Engineering** 
- [ ] Update Lovell runbook currently in draft  ??  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10670

- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11069 Lovell Listing page parity (Jay - in progress)

## Vet Centers
- [ ] #11108  CMS: A11y Lat & long attribute mismatch 

- [ ] #10706 Archived CAPs showing in preview
- [ ] #10739 Account blocked from selecting site section

## Stretch
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9923
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9754

## General Frontend
- [ ] #10656 Execute on [Flippers Audit ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10350)

## Blocked
<details><summary>Blocked by V1 release</summary>
The following Lighthouse issues are dependent on the release of Lighthouse V1

- [ ] #8017 Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
- [ ] #4411 Push CAP data 
</details>

**Comment by davidmpickett** [comment]
@dsinla FYI - I just took a quick pass at this to clear out the complete Design items from 69 and add the issues tagged 70
