### ISSUE TITLE
[Platform CMS] Content Build speed improved by 10%

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11213]
### Problem statements
* As a CMS editor, I want content to be published as quickly as possible and without failure, so that Veterans receive information they need in a timely manner.

* As a CMS engineer, I want the timing of individual steps of the Content Build process to be tracked as metrics, so that I can see if changes to content build are having an impact.

## Acceptance Criteria
- [x] Content Build step timing is collected as metrics in Datadog for each production content release (`node build`)
- [x] Average content build time is reduced by 10% (25.23m to 22.7m at time of writing)
  - Minimum improvement of 28%, from measuring time spent per page or node. See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11213#issuecomment-1352410370.

## Background
In #10740, we established 
* Content build time scales linearly with node volume increases
* Content build on its own (without any archive or deploy processes) will take 45 minutes when the CMS hits approximately 67,000 nodes
* Content build fails with out-of-memory issues at approximately 72,000 nodes.

We believe it is in the best interest of VA.gov's CMS to make incremental improvements to Content Release in the absence of any larger effort to replace Content Build. 

Note that the timing being measure here is the timing of the Content Build process, i.e. the node process. 

Adding the ability to track individual step metrics is part of this epic because the ability to measure these sorts of changes does not currently exist, and therefore we cannot validate improvements due to code changes at this time.

### Affected users and stakeholders

* CMS editors
* CMS engineers

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Platform CMS Team`

**Comment by ElijahLynn** [comment]
Some things to note:
* The parallel GQL requests are currently at 15, and that was up from 5 after my testing a while ago. There wasn't much improvement after 15. BUT, there also wasn't a noticeable bottleneck that I could fine, AND it is worth revisiting that. I think we might be able to get to 30 parallel requests. 
* The file downloads are parallelized too, and I think that is 5 as well. This could probably be easily bumped to 30. They are all served by Apache, not Drupal. So there shouldn't be much PHP processing going on.

**Comment by timcosgrove** [comment]
Datadog view: https://vagov.ddog-gov.com/dashboard/vnk-g4s-fru?from_ts=1667286000000&to_ts=1671064680000&live=false

Relevant graph:
<img width="1561" alt="image" src="https://user-images.githubusercontent.com/203623/207745357-41b9a2cc-dc68-41f7-9310-549a88e59036.png">

November 1, prior to any changes:
* Time / node: 52.13 ms
* Time / page: 85.79 ms

December 14, after changes:
* Time / node: 36.97 ms
* Time / page: 61.65 ms

Percentage improvement:
* Time / node: 36.97 / 52.13 = 0.71, or 29% improvement.
* Time / page: 61.65 / 85.79 = .0.72, or 28% improvement.
