### ISSUE TITLE
Injected Header postmortem follow up

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11242]
## Background

**Incidents**: 
1. **2022-10-07 Web Components breaks Teamsites postmortem**
    * https://dsva.slack.com/archives/C52CL1PKQ/p1665146147067899
    * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11187
3. [2023-04-06 - Injected Header (Organic Adoption Modal) Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-04-06-organic-adoption-postmortem.md)

This epic tracks the follow up items from postmortems related to the injected header.

### User Story or Problem Statement

As a VA development team, I need a clear understanding of how to test the injected header, to prevent issue in production on injected header sites. 

As the Public Websites team, we need to ensure the injected header is easily testable and robust for testing by other teams.

As the owner of the injected header, I need confidence that other teams cannot accidentally break the injected header.

### Affected users and stakeholders

* Any engineers who use web components in modals or the header
* Any engineering teams who may affect the header or footer
* Public Websites

## Assumptions
* Injected header is served using the [proxy-rewrite app](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/applications/proxy-rewrite)
* Teams are responsible for testing their own changes; Public Websites is a code owner of the Header and the Proxy-rewrite app, but not responsible for testing changes from other teams.

## Acceptance Criteria
- [ ] TBD

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [X] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

**Comment by jilladams** [comment]
@wesrowe Post mortem is complete/ merged (https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022/2022-10-07-web-component-breaks-teamsites.md), so we could start refining / prioritizing the action item tickets as it fits into other plans.

**Comment by wesrowe** [comment]
@jilladams, I concur with your assessment on priority. Also, did you notice any clear action items emerge from the post-mortem ticket? The last version I reviewed had a lot of ideas. We can discuss with Dave when he's back from TX.

**Comment by jilladams** [comment]
Yep - the specifics are under [Action Items](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2022/2022-10-07-web-component-breaks-teamsites.md#action-items): 

PW owns:  
#11260 
#11253
#11255
#11256

and contrib on:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/47966
https://github.com/department-of-veterans-affairs/va.gov-team/issues/48415

**Comment by jilladams** [comment]
Sync with Wes & Dave: 
Long-term, the header may be treated as "versioned" where we put injection in maintenance mode and don't allow new customers to onboard to it, in order to eventually sunset the injected header. 

However: near term, it's supported and we should prioritize this work when possible.

**Comment by jilladams** [comment]
Updated epic body to include reference to the latest postmortem. https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2023/2023-04-06-organic-adoption-postmortem.md

**Comment by FranECross** [comment]
Removed the link to this [CMS team ticket](https://app.zenhub.com/workspaces/vagov-sitewide-product-team-6645154188a81a1f7a0a9464/issues/gh/department-of-veterans-affairs/va.gov-team/48415) so that I can close out this epic.
