### ISSUE TITLE
Investigate adding unit tests for injected header / footer in Teamsite instances

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11254]
## User Story or Problem Statement

As a maintainer of the injected header and footer on Teamsites it would be good to know if portions of the header or footer break, so it could be prevented before it breaks the injection.

Note: given the methods by which the header and footer is assembled and injected, it may not be possible to cover it with true "unit" tests and it may be better suited to integration testing in this ticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11253

## Acceptance Criteria
- [ ] Proposed a set of unit tests that would check failure of the injected header
- [ ] Proposed a set of unit tests that would check failure of the injected footer

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
I do not believe unit tests are the answer here. This ticket will likely be closed without action. Keeping open now as the chips continue to fall.
