### ISSUE TITLE
Reveal linky destination in link editor

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11265]
## User Story or Problem Statement

As an editor I would like to see the actual destination of my link when I edit it, and not the linky equivalent so that I may more transparently see and edit my content.

Currently. clicking the edit button for an external link brings up
![image](https://user-images.githubusercontent.com/5752113/196780082-df6c7c56-b2a5-42f4-bcda-03c8aeb94dfe.png)

and the only way to change the link is to delete out the linky reference and put in the link destination.

[Related slack conversation in CMS support](https://dsva.slack.com/archives/CDHBKAL9W/p1666127982707249)
## Acceptance Criteria
- [ ] When editing a wysiwyg link to an external place, I can see the actual destination and not the linky reference.
- [ ] saving the link does not result in two linkies.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@ndouglas this will be pretty high priority for Sprint 70, but not necessarily a sprint goal

**Comment by ndouglas** [comment]
So to be clear, this is editing the existing Linky?  What if someone copies and pastes content and changes the link to point to another destination?
