### ISSUE TITLE
PW - Sprint 70 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11270]
### 1. Harden homepage for prod
- [ ] (stretch; can start after usability study) #11160 ()

### 2. PDF Certificate Expiration Alert
- S70: Align with Dave C and Danielle on content, timeline

### 3. Income Limits web app
- Cindy to resume in ~Sprint 72

### 4. Chatbot 
- No action yet identified

### 5. Benefit Content Model Hardening
- Dependency on Danielle prioritizing

### 6. Cerner API deprecation support
- [ ] (stretch) #9179 (8)

### 7. Table 508 header compliance 
- HOLD, MVP done (template change); awaiting audit by SWContent to see if significant issues remain

###  Other 508
- [ ] #11205 (2)
- [ ] (stretch; requirements pending) #10699
- [ ] #10698 (3)
- [ ] #11271 (points tbd)

---

### Outreach Materials / R&S Taxonomy

- [ ] #11148 (0 - admin work)
- [ ] #11146 (3)
- [ ] #11147 (5)
- [ ] #11149 (1)
- [ ] #11153 (5)

### Injected header post-mortem
- [ ] #11255 (5)

@davidconlon: options to discuss
- The easiest way to prevent issues is to adding the web-components package to the injected header. **Potential tradeoff:** impact on heaviness of Teamsites is unknown (in absolute or relative terms)
  - _If you want to study this perf impact on Teamsites_: study it with #11260 (8)
  - To just go ahead and add it: (stretch) #11313 ()

### Support EDU how-to-apply wizard
- [ ]  (pending stakeholder clarification) (3)  #10916 (pending unblocking)

### Form audit tools
- [ ] #11285 ()
- [ ] #11246 (2)

### Site search
- [ ]  (stretch) ()  #11282  

### Translation support
- [ ] At this point we recommend shifting this to Sitewide-CMS (stretch) (5)  #10631 

### Redirects
- [ ] #11314  (2)
- [ ] #10972  (2)(pending unblocking by stakeholders)
