### ISSUE TITLE
[Platform CMS] Upgrade to php 8.1

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11345]
### User Story or Problem Statement

We need to upgrade to PHP 8.1. Php 7.4 (current version) goes end-of-life on 28 Nov 2022. 

### Affected users and stakeholders

Effects all CMS users and products. 

https://www.php.net/supported-versions.php
![CleanShot 2022-09-26 at 08.37.16.png](https://images.zenhubusercontent.com/62e017d215adbc33b1310f7b/602bdecd-ac81-4e68-9dec-66343622e4e7)

## Tests and areas that need to be checked
- [ ] Test SSO
- [ ] Test Content Build
- [ ] Test API endpoints?
- [ ] Manually test Drupal CMS interface and check for errors.

## Acceptance Criteria
- [ ] php 8.1 is installed on prod before 11/28/22
- [ ] verification that there is no performance degradation between 8.1 and 7.4
- [ ] verification that there aren't any feature regressions and external integrations are functional

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
this is to mirror #10870 but separate between Sitewide CMS team tasks versus Platform CMS team tasks.
