### ISSUE TITLE
Accordion header font size varies on Samsung Galaxy Z3 flip phone

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11353]
## Description
In a recent user test session for homepage, user was using a  Samsung Galaxy Z3 flip phone (a new model released in 2021). Accordion header text on various benefit detail pages presented at wildly different font sizes.  

**So far unable to reproduce.** May have been a combination of user's device + settings + font zoom.

**Tasks before assigning:** 
- [ ] Check Google Analytics for user agent data to see if we can tell how many users may be affected with this device

## To reproduce: 
**Great question.** This does not reproduce with other Samsung devices we've tried or in Chrome inspection emulator for available Samsung user agent strings. Filing the ticket for documentation in case we receive additional reports. 
- [ ] Go to https://www.va.gov/resources/the-pact-act-and-your-va-benefits/ (on a Samsung Galaxy Z3 flip phone?)

## screenshots

![image (21)](https://user-images.githubusercontent.com/85581471/198125534-59859bcb-98ad-4b2f-878a-bf53c9ffc374.png)

<details>
<summary> more screenshots </summary>

![image (20)](https://user-images.githubusercontent.com/85581471/198125540-6965036b-b7ac-4959-b1e5-1ceadce9ee76.png)

![image (19)](https://user-images.githubusercontent.com/85581471/198125544-bb3ad78c-a8cc-4566-a3c9-0dfe1b73fe2f.png)
</details>

## ACs

- [ ] All accordions should have the same font size

**Comment by FranECross** [comment]
Closing old ticket; not reproducible and no new reports filed.
