### ISSUE TITLE
Income Limits: proposed plan, kick off UX design

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11372]
## Background

After [conducting](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11167) the first few Income Limits research sessions, Cindy Merrill flagged that we weren't really getting much information about eligibility or income limits specifically. Wes Rowe, Michelle Middaugh, Dave Pickett and Cindy discussed possible pivots on 10/20 and asked to Dave Conlon for clarification on the research strategy. Wes reported back with clear answers on 10/25. The research & pm team met again on 10/27 to plan next steps.

This ticket outlines those proposed next steps so we can take the plan back to Dave C for sign off before moving ahead.

### Part 1 - Halt current research

**Rationale**
- The research plan, conversation guide, and participant screener are scoped for broad eligibility research. To generate meaningful insights about Income Limits, we'd essentially have to redo them (and related review cycles). 
- Dave C says the research timeline can't be extended.
- The Income Limits app has a well-defined use case and existing data set. Enough information to make a FE prototype to take to usability testing.

**Next Steps**
- [x] Cindy will contact Shane to have Perigean close the study and cancel the participants scheduled for mid-November.
- [x] Cindy will do a mini-synthesis of the sessions that were completed + meta findings about recruitment. This will happen the week of Nov 14, which is when those other sessions are currently scheduled.
- [x] Once research process is officially closed out, Cindy and Michelle have fulfilled their commitment to Public Websites 
- [x] Cindy generously offered to consult on FE designs given her extensive knowledge of Veterans and recent familiarity with this problem space (time and priorities permitting)

**Related tickets to update**
- [x] #11166
- [x] #11167
- [x] #11168

### Part 2 - Begin FE Design ASAP

**Rationale**
- Research synthesis is unlikely to produce actionable insights for the FE design, therefore not technically a blocker

**Next Steps**
- [ ] Wes and Jordan will reestablish contact with Income Limits stakeholders - we will need a tight feedback loop to make sure we are accurately representing the various income criteria
- [ ] Create a task list / flowchart of logic for the 3 income-related priority groups. From the moment a veteran realizes "income may be a factor in my eligibility" to the end goal of "I know my priority group (or subgroup) based on my income"
- [ ] Validate with stakeholders for accuracy of logic / decision tree
- [ ] Make a lofi flow of screens that gather relevant information from users in a intuitive manner consistent with VA.gov design system
- [ ] Internal design critique (Might be the right place for Cindy to weigh in)
- [ ] Collab cycle
- [ ] Mid-fi prototype ready for usability testing

**Related tickets to update**
- [ ] #11098
- [ ] May need to add a couple additional tickets to account for dependencies & review steps

### Part 3 - Refine Recruitment Criteria in anticipation of Usability Testing

**Rationale**
- The criteria we used for this research did not get us the right participants

**Next Steps**
- [ ] Dave P will reach out to other teams who may have had to recruit veterans in specific healthcare priority groups before and see if there are successfully strategies we can borrow
- [ ] @mmiddaugh and @cindymerrill suggested these teams: 
  - 10-10 team (Heather Justice)
  - Eligibility & Enrollment team (Pam Hastings plus Megan Graham, Brittany Iannuzzi, Danielle Oppendike, and Thomas Ferrin). Their recent exploratory research findings on eligibility and enrollment are [here](https://docs.google.com/presentation/d/1vcVIuEUip908oO5vSOmki04_6XeIpSBkdyk__nBvm9U/edit?usp=sharing), which includes a bit about income limits. 
  - Benefits & Debt team
  - Digital Health Modernization (Marci McGuire)
- [ ] Dave P will proactively develop the new recruitment criteria while FE design is in motion

**Related tickets to update**
- [ ] #11099 

## Acceptance Criteria
- [x] Proposed plan is documented
- [ ] Plan is approved by Research & PM Team
- [ ] Plan is approved by PO
- [ ] Subsequent tickets are created or updated

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@davidmpickett, Dave Conlon approved of moving straight to UX design.

**Comment by davidmpickett** [comment]
I'm gonna propose this be the first project for Jordan to tackle once she's onboard

**Comment by wesrowe** [comment]
Ticket has been discussed, leveraged, etc. Closing.
