### ISSUE TITLE
SPIKE: How should we manage Home Page Hub area as content that includes both Benefit Hubs and non-Hubs

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11370]
**BLOCKED pending Sitewide-CMS collab and Dave C sign-off on direction**

Home page Hub list is powered by an entityqueue that displays Benefit Hub Landing Page content: https://prod.cms.va.gov/admin/structure/entityqueue/home_page_hub_list/home_page_hub_list?destination=/admin/structure/entityqueue

In the updated homepage design, we are adding a new item to the hub list that isn't likely to be coming from a Benefit Hub Landing Page, since it will require a link out to an external OPIA controlled resource: 
![Screen Shot 2022-12-12 at 2 05 17 PM](https://user-images.githubusercontent.com/85581471/207165209-aca11656-88cc-4a57-828e-e3d7982c78b7.png)

There appear to be some challenges adding a new item to the home page hub list, in that the ability to add another item tot he queue is missing in the UI. Therefore, we need to understand how to add a new BHLP to the hub list, and the impact of doing so if that item is not a true BHLP (we don't want it appearing elsewhere in the site, like the megamenu).

This spike should address:

How do we add a new item to the existing hubs list?
What impact will there be to other areas of the site, should we add a new BHLP?
How are icons generated?
How could we add a new item to the hub list that isn't a BHLP?

# Spike Results

## How do we add a new item to the hubs list?
<details>
  <summary>Click to expand</summary>
  
Q: How do new items appear in [this entity queue](https://prod.cms.va.gov/admin/structure/entityqueue/home_page_hub_list/home_page_hub_list?destination=/admin/structure/entityqueue)? As Drupal admin on Prod, I don't find an option to add items. to it anywhere.

A: The entityqueue is limiting the number of items to a max of 11 items. To allow for more items, the enityqueue config will need to be updated to allow for at least 1 additional item. At that point, the buttons for doing so appear in the UI.

Q: If I create and publish a new Benefit Hub Landing Page on a tugboat, it doesn't automatically appear in the Hub entityqueue (e.g. https://pr11910-s7zcirucdbwlo6s3v5o3orizx6gf6eod.ci.cms.va.gov/node/51982/edit, vs. https://pr11910-s7zcirucdbwlo6s3v5o3orizx6gf6eod.ci.cms.va.gov/admin/structure/entityqueue/home_page_hub_list/home_page_hub_list?destination=/admin/structure/entityqueue). What is the mechanism for new items in this subqueue to go live? Is it when the Benefit Hub Landing Page is published?

A: Creating a new Benefits Hub Landing Page is alone not enough to add it to the queue. The entityqueue is manual, in that any entries must be added to the queue by someone (or programtically), but there is no automation around populating queues. Once the limit is raised from 11, the ability to add items to the queue will become available.
</details>

## What impact will there be to other areas of the site, should we add a new BHLP?

<details>
  <summary>Click to expand</summary>

Q: Drupal + FE: Would adding a new Benefit Hub in Drupal (just to add this link) have any unintended side effects, such as this new Hub appearing in places where it's not wanted, e.g. the megamenu?

A: Megamenu will be unaffected. The megamenu is driven by a single Drupal menu: header-megamenu. See https://prod.cms.va.gov/admin/structure/menu/manage/header-megamenu

The query:

```graphql
const menuLinkContentQuery = `
  menuLinkContentQuery(limit: 5000, sort: {field: "weight", direction: ASC}, filter: {conditions: [{field: "enabled", value: "1"}, {field: "menu_name", value: "header-megamenu"}]}) {
    entities {
      entityId
      entityLabel
      ${headerQuery}
    }
  }
`;
```

It should be noted however that any new published Benefits Hub Landing Page published in Drupal will create a related detail page in content-build.

Everywhere I could find that Benefit Hub Landing Page is used in GraphQL:

```
13 results - 12 files

src/site/README.md:
  167      entities {
  168:       ... on NodeLandingPage {
  169          entityId

  218  const examplePageFragment = `
  219:   fragment examplePageFragment on NodeLandingPage {
  220      entityId

{this is a readme; no-op}

src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js:
  59      entity {
  60:       ... on NodeLandingPage {
  61          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/homePage.graphql.js:
  41          entity {
  42:           ... on NodeLandingPage {
  43              entityId

{This is the query that results in the hub list items being returned for the homepage; no-op}


src/site/stages/build/drupal/graphql/landingPage.graphql.js:
  21  const landingPageFragment = `
  22:   fragment landingPage on NodeLandingPage {
  23      ${entityElementsFromPages}

{This query returns all landing pages, so any new landing pages will be also be included. This query is used to create the detail pages for each landing page.}


src/site/stages/build/drupal/graphql/nodeChecklist.graphql.js:
  33      entity {
  34:       ... on NodeLandingPage {
  35          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/nodeMediaListImages.graphql.js:
  32      entity {
  33:       ... on NodeLandingPage {
  34          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/nodeMediaListVideos.graphql.js:
  32      entity {
  33:       ... on NodeLandingPage {
  34          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/nodeQa.graphql.js:
  38      entity {
  39:       ... on NodeLandingPage {
  40          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js:
  67      entity {
  68:       ... on NodeLandingPage {
  69          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js:
  53      entity {
  54:       ... on NodeLandingPage {
  55          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/vaFormPage.graphql.js:
  41      entity {
  42:       ... on NodeLandingPage {
  43          fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}


src/site/stages/build/drupal/graphql/paragraph-fragments/contactInformation.paragraph.graphql.js:
  4        entity {
  5:         ... on NodeLandingPage {
  6            fieldHomePageHubLabel

{This is an entity ref field, so only referenced items are returned; no-op}

```
</details>

## How is the icon generated?
<details>
  <summary>Click to expand</summary>

Q: In the Benefit Hub Landing Page form, how is the Hub Icon list generated? We will need a new icon for this design/hub.

A: The icons list is built using a List (Text) field, field_title_icon. See /admin/structure/types/manage/landing_page/fields/node.landing_page.field_title_icon/storage. To accommodate an additional icon, this list will need to be updated (it is just text) to include the new icon machine name and label. See this slack conversation for how to do that: https://dsva.slack.com/archives/CT4GZBM8F/p1671038022450329.

The new option's machine name was created during FE implementation of the new home page: `va-dept-info`. 

Existing machine name|labels are below:

```
health-care|Health care
disability|Disability
education|Education
records|Records
careers|Careers and employment
pension|Pension
housing|Housing
life-insurance|Life insurance
burials|Burials and memorials
family-member|Family member benefits
service-member|Service member benefits
```

Q: Is the new icon in the design system somewhere? Not listed in [approved Design System icons](https://design.va.gov/foundation/icons)
https://design.va.gov/foundation/icons#hub-icons

A: Currently, the icons in the hub are using FontAwesome Free v5, along with some custom css to wire in the machine name (from the field_title_icon field in Drupal) to the FA icon. Design system icons are not being used in the homepage hub list at this time.

Available icons can be found here: https://fontawesome.com/v5/search?o=r&m=free

Technical details:

Icon styles: [vets-website] src/platform/site-wide/sass/iconography.scss
- uses a mixin "make-hub".
- leverages FontAwesome icons from free version 5
- for 'service-memeber':   $icon: $fa-var-flag-usa

Where does the $fa-var-flag-usa var come from?
./node_modules/@department-of-veterans-affairs/formation/node_modules/@fortawesome/fontawesome-free/scss/_variables.scss

</details>

### Replace with menu
<details>
  <summary>Click to expand</summary

This option does away with the exiting method of using an entityqueue. Entityqueue's are limited to a single entity type, so mixing content (BHLP) with blocks is not possible. This was the main reason for proposing an additional block type + entityqueue (see below). However, it also convolutes the system with additional entity bloat and degrades the editorial experience.

1. Add a new menu: Home page - hub list
2. Add fields to the new menu to support icon and teaser
3. Allow OPIA Home Page section users to manage this menu
4. Update the FE to consume the new query
5. Remove the now deprecated entityqueue (fast follow). TBD if icons on BHLP content type still make sense, and if not, remove that field from the BHLP content type, along with the related teaser field.

#### Benefits

1. Single source of truth for hub list items
2. Can add any link of any kind; does not require a BHLP
3. Governance by homepage manager perms + Section -> OPIA Home Page
4. Can still link to BHLP's
5. Menus are provided by core, so not likely to break down the road (defendant on the contrib module menu_item_extras to expose field UX). 
6. Hub list items and non-hub list items can be arranged as needed, rather than bolting on non-hub-list items to the end of the list.

#### Drawbacks
User experience change

</details>

### Append additional items (no longer viable, see drawbacks)
<details>
  <summary>Click to expand</summary

This option allows new items that are not BHLP to be appended to the existing list via a new block type and entityqueue:

1. Create a new Block Type in Drupal (needs name)
    a. Add a new field for the icon, similar to the field_title_icon on BHLP. Move allowed values to a central function for both BHLP field_title_icon and this new field. Update the function to provide values for both fields.
    b. Add CTA paragraph (or unique fields for link + link title, should needs differ from CTA paragraph).
    c. Add 'description' field for the hubs list item text.
    d. Allow Homepage Manager (Drupal role) permission to create and edit these blocks (follow the same permissions model used in the V2 Homepage blocks).
8. Add a new entityqueue (needs name), and allow only the new block type as queue-able items.
    a. Permissions for this entityqueue should match permissions from the other v2 homepage queues. ie: Homepage Manager should be able to add/remove items.
9. Update FE code to include a new query for this new entityqueue.
10. Update FE code to append new entityqueue results to the hubs template variable.

#### Benefits
This allows the most flexibility, should needs change over time. It also doesn't pollute an existing block or entity type with home-page-hub-list only fields.

#### Drawbacks
Not a single source of truth for all hub list items (which is now a requirement).

</details>

## ACs

- [x] desired qualities for future:
  - [x] single source of truth for hubs, potentially for consumption e.g. by another presentation layer
  - [x] managed in one place
- [x] Propose a Drupal method in #11968 for managing the VA Department Info item (which is *not* a Benefits Hub Landing Page), and which will be visually presented in the Hub List space on the Front-end.
  - [ ] Consider change management, if proposed plan includes changing how existing Hub List items are managed  
- [x] File [CMS Collab Cycle intake request](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=ewashb%2Cdawnpruitt&labels=%E2%AD%90%EF%B8%8F+Sitewide+CMS&template=sitewide-cms-collab.yml&title=%5BCMS+COLLAB+CYCLE+INTAKE%5D+%28Team+Name%2C+Product+Name%2C+Feature+Name%29) to review proposed plan (see  [CMS Collab Cycle docs](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1791459333/CMS+Collaboration+Cycle)). Filed. See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12044
  - (Sign-off from Dave C will follow CMS collab)

**Comment by wesrowe** [comment]
@mmiddaugh, the AC says "URL TBD" – do you know it?

**Comment by wesrowe** [comment]
Updating here a complication that came together in a [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1671044240372499):

- We assumed all along that a new Benefit Hub Landing Page was being created. 
  - Nope - We found out on Tues 12/13 that this is not the case: the `VA Departments` website that looks like a Hub in the design is in fact an external website being implemented by OPIA (in WordPress I believe).
- Per Daniel's observation above, we may have a problem: the EntityQueue that renders the homepage Hubs panel assumes that the things listed are `Benefit Hub Landing Pages`. 

@dsasser, do I have this right? Do we need to meet about a solution?

**Comment by jilladams** [comment]
New slack thread with Michelle: https://dsva.slack.com/archives/C03NSH4SLQY/p1671125891943039

Next steps: https://dsva.slack.com/archives/C03NSH4SLQY/p1671127658695379?thread_ts=1671125891.943039&cid=C03NSH4SLQY
From the call:
* VA Dept Info is not a benefit hub, is an external link out to a WP site.
* Not required to be managed in Drupal, per Michelle. Could be a hard coded solution.
* However: if we manage in Drupal:
    * Best idea so far: create a new entityqueue that manages a new custom block type.
    * This eq can be tacked onto the end of the hub list.
    * Prevents having to change Hub editor experience. 
    * That way this item could expand into its own list w/ a different presentation later if we need to. (ala [Homepage round 1 design ](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857)for offramp list).

Michelle to close loop with Dave today.

**Comment by jilladams** [comment]
Per refinement with Dave on 12/15: 
* Site being linked to is a Wordpress site in dev by OPIA
* It is blocked on review / approval by the Secretary
* When it is approved / launched, it will not be a PW fire drill to publish this link out to it. 

Meaning: we have time to work out the correct solution.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C03NSH4SLQY/p1671138379946699

**Comment by jilladams** [comment]
Next steps: 
1. confirm plan re: new block type vs. using existing block type, with new entity queue.
2. work out how to icon
3. cut tickets / estimate

**Comment by dsasser** [comment]
@wesrowe @jill reviewing ACs, I see:

> Understand and document in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11968 how a new item can be added to the Benefit Hubs list on the new homepage using the existing architecture.

I'm not clear on why we would document how do add via the existing architecture into ticket #11968, particularly since we plan to re-architect how all hub list items are added. Can we remove this AC?

**Comment by jilladams** [comment]
I deleted that item, modified the item after, and added a sub-item for CM: 

- [ ] Propose a Drupal method in #11968 for managing the VA Department Info item (which is *not* a Benefits Hub Landing Page), and which will be visually presented in the Hub List space on the Front-end.
  - [ ] Consider change management, if proposed plan includes changing how existing Hub List items are managed

**Comment by dsasser** [comment]
@jilladams @wesrowe CMS collab intake ticket created. I won't be able to meet this AC until the cycle completes, since we don't have approval on the plan yet.

`Capture [decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/decision-log.md) – in product outline (can point back to the epic/tickets)`

Perhaps we move this AC to the implementation ticket?

**Comment by wesrowe** [comment]
That's a good point, @dsasser – maybe we could revisit toward the end of the sprint. If we haven't been able to make a decision, we can punt this AC to the next ticket?

**Comment by dsasser** [comment]
Per this comment, we are striking this AC, as CMS collab, while started, has not completed, and therefore a decision has not been made.

I'll move this AC to the implementation ticket.

- [ ] Capture [decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/home-page/home-page-redesign-initiative/decision-log.md) – in product outline (can point back to the epic/tickets)

**Comment by dsasser** [comment]
Regarding the below AC, we cannot execute on change management until we have an approved approach for using menus as a new source for homepage hub listings, which is currently underway in this [CMS collab intake ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12044).  So in order to not lose the AC entirely, I will move it to the implementation ticket, and we can discuss as a team during refinement where best to execute the CM consideration.

  - [ ] Consider change management, if proposed plan includes changing how existing Hub List items are managed

**Comment by wesrowe** [comment]
Sounds good, thanks for managing those ACs into the implementation ticket.
