### ISSUE TITLE
PW - Sprint 71 Plan 

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11406]
### 1. Harden homepage for prod
- [ ] #11160 (5)
- [ ] #11324 (8)
- [ ] (stretch) #11119  (3)
- [ ] (stretch) #11095  (points TBD pending design update from RyanT)
- [ ] (stretch) #11414 ()
- [ ] **What else?**
  - soft-launch design activities
  - Medallia survey design
  - #11370  - Michelle content entry

### 2. PDF Certificate Expiration Alert
- Stretch, need content (#[48458](https://github.com/department-of-veterans-affairs/va.gov-team/issues/48458) ETA by 11/15 if not earlier)
  - #11021 
  - #11022 
 
### 3. Income Limits web app
- #11168 (Cindy)

### 4. Chatbot 
- No action yet identified

### 5. Benefit Content Model Hardening
- Dependency on Danielle prioritizing

### 6. Cerner API deprecation support
- [ ] #9179 (8)

### 7. Table 508 header compliance 
- HOLD, MVP done (template change); awaiting audit by SWContent to see if significant issues remain

###  Other 508
- [x] (in progress in S70) #11205 (2)
- [ ] #10868 (2)

---

### Outreach Materials / R&S Taxonomy

- [ ] #11149 (1)
- [ ] #11445 (5)
- [ ] #11442 (3)
- [ ] (stretch) #11154 ()

### Support EDU how-to-apply wizard
- [ ]  #10916 (3)  

### Form audit tools
- [ ] #11404 (1)

### Drupalize footer
- [ ] #11438 (3)

### Injected header post-mortem
- Actions waiting on conclusion of post-mortem

### Redirects (~5-10 points total?)
- [ ] Lingering Vet Center redirects (11376, 11382, 11383, 11380, 11379, 11385, 11378)
- [ ] #10972  (2)(pending unblocking by stakeholders)

**Comment by jilladams** [comment]
Other audits not listed in plan yet that we could prob put in stretch if we're light on things: 

#11208  -- login.gov, now refined
#11461  -- Edith not yet refined
