### ISSUE TITLE
Propose strategy for refactoring approach to Featured Stories and Events 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11401]
## Background
We need to clarify the behavior for how stories get featured on Story pages and how it is listed at the top of the Facility page

Related ticket:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11221

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Suggest tackling this in Q1 2023

**Comment by kmariepat-cityfriends** [comment]
Some context:

- [ ] ??? should we fix this approach overall for stories... the 1 and 2 in CMS don't do anything, disconnect bet
- [ ] Featured should be on the place you want to feature it, that lets you select what story you want to feature. Having featured be part of the event is backwards from where the decision is (leadership list is an example of right relationship with items on the list and how it is set)
- [ ] Entity queue is one solution that was proposed

**Comment by kmariepat-cityfriends** [comment]
Some context:

- [ ] ??? should we fix this approach overall for stories... the 1 and 2 in CMS don't do anything, disconnect bet
- [ ] Featured should be on the place you want to feature it, that lets you select what story you want to feature. Having featured be part of the event is backwards from where the decision is (leadership list is an example of right relationship with items on the list and how it is set)
- [ ] Entity queue is one solution that was proposed

**Comment by mmiddaugh** [comment]
As mentioned above, the leadership list may be a good model for this reboot...essentially, the story could be created in a separate workflow from the one in which they are featured and ordered. In this way, the editor would have context and visibility into which and how many stories were selected to be featured and in what order.

**Comment by mmiddaugh** [comment]
**Update 3.9.2024**

This is still high value work which we have not been able to prioritize due to team capacity and other competing priorities, including legislative requirements. May revisit in 2Q or 3Q 2024

**Comment by mmiddaugh** [comment]
Given the need to devote capacity to aligning with USWDS Design system and other competing priorities, I'm deprioritizing this work. We'll revisit in Q324

**Comment by mmiddaugh** [comment]
**Update 6.7.2024**
- Still on hold

**Comment by mmiddaugh** [comment]
**Update 8.8.2024**

- KB articles have been updated to reflect existing functionality
- Adjust misleading Featured stories help text #18819 will be prioritized in the short term
- All other work on hold

**Comment by mmiddaugh** [comment]
**Update 9.3.2024**

- Adjust misleading Featured stories help text https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18819 will be prioritized in the short term
- All other work on hold

**Comment by JonathanKatora** [comment]
**Update**

Still relevant and valuable, but requires prioritization against other initiatives. 
cc: @r-bartlett-gsa
