### ISSUE TITLE
Sprint 71 - Facilities | Nov 7 - Nov 20

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11433]
<details><summary>Quarterly Initiatives</summary>

Major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9655 Lovell 
- #9659 VBA MVP
- #1392 Banners 

**Blocked until LH team moves forward**
- #10798  Lighthouse v1
</details>

<details><summary>OOO</summary>

Tu 11/8 = 🗳️ Election day floating holiday (Agile6 only)
Fri 11/11 = 🪖 Federal Veterans Day

Who | When | Backup 
----- | ------ | ------- 
Dave P | Oct 31- Nov 14 | Aslan & Blake
Dave C | 11/10 _CSW Swap_ | 

</details>

🥅   — Sprint goals (pending Sprint planning)

## Facility COVID status post-launch
- [ ] #11361 COVID status front end **STRECTH**

## Facility Locator

**PM** 

## VBA Facilities

**PM**

**Design**
- [ ] #10196  Veteran research and readout 🥅 **Keep in Sprint 70**
- [ ] #10510 Update VBA MVP after content audit 

_Have to decide plan for PCT research_
- [ ] #10506 PCT research plan review 
- [ ] #10507 Finalize PCT
- [ ] #11210 PCT CMS review cycle 
- [ ] #11452 Conduct PCT research 
- [ ] Recruit and schedule? It's own ticket?

**Engineering**
- [ ] #10914 Update VBA migrations 🥅 
- [x] #11473 Align VBA health services taxonomy for VBA 
- [x] #11468 Services fields should be sentence case 

### Banners
**Engineering** 
- [ ] #11040 Limit alerts per system <- Waiting for the CM
 @dsinla to create CM issues

**PM**
- [ ] #11434 Audit VAMC System Banner Alerts

### Lovell #9655

**Engineering** 
																															 
- [ ] #11422 FE Add TRICARE fallback to service taxonomy 🥅
																						 

Punchlist
- [ ] #11212 Lovell twins not clones
- [ ] #11373 Wrong Lovell switcher
- [ ] #11374 Wrong Lovell switcher path 

**Design**

**PM** 
																				   
- [ ] #11357 Create Lovell roadmap / next steps 🥅
 

## Accessibility 
@maxx1128 What tickets are likely next candidates (as timing allows)
- [x] #11488 CMS? FE? Make 988 in description text clickable

## General Frontend
- [ ] #10656 Execute on [Flippers Audit ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10350)
- [ ] Create individual tickets per Flipper 

## Lighthouse / Facility API data
Mental health phone numbers - in Sprint 71? as Stretch
- [x] #11338 Mental Health number compare

## Blocked
<details><summary>Blocked by V1 release</summary>
The following Lighthouse issues are dependent on the release of Lighthouse V1

- [ ] #8017 Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
- [ ] #4411 Push CAP data 
</details>
