### ISSUE TITLE
Form flag notifications

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11456]
## Background
The VA Forms product in Drupal includes a flagging mechanism. 
* [Forms Managers](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form#forms-managers) and Forms admins make changes to form PDFs and form metadata in the Forms DB
* Forms DB data is migrated nightly to Drupal
* Drupal flags VA Form content in 4 scenarios: 
  * Changed filename
  * Changed Title
  * New form
  * Deleted form

Flagged content can be found in Content audit views at https://prod.cms.va.gov/admin/content/va-forms

However: currently flags have no specific owner, and no established process for being cleared. Ultimately the owners of the PDF and metadata need to be the ones to make changes to fix / revert / update upstream in the Forms DB, but those Forms Managers / Admins are not and probably will never be Drupal users. 

So we need to build: 
1. A process & mechanism for notifying Forms Managers/ Admins of downstream changes that require review
2. A workflow to manage that feedback cycle
3. A workflow for resolving flags on flagged content

### User Story or Problem Statement

As a Forms Manager of a specific administration, I need to be aware when FormsDB data breaks / affects Find a Form, via notification or email.

As a Drupal Admin, I need to understand if changes to Forms were intentional or unintentional. 
As a Drupal Admin, I need a clear workflow for clearing CMS flags on VA Forms.

### Affected users and stakeholders

*[Forms Managers](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form#forms-managers)
* Drupal Admins and Content Admins, with permission to modify Drupal flags

## Acceptance Criteria
- [ ] 
- [ ] Requires KB article update: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10179

### Change management triage
Limited to Drupal Admins and maybe eventually Content Admins. No CM required unless/until we opt to onboard Content Admins to managing these flags.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [X] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
moved open issues to #21109 and now closing this epic
