### ISSUE TITLE
Implement Google Analytics for new homepage

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11467]
## Description
As a stakeholder, I want to capture specific data about user behavior for comparison to determine cutover readiness and to monitor homepage success long term.  

## Tasks

- [ ] Ensure GA is tracking all elements on new homepage with sufficient detail to know which component was used and with which part of the component

Component/area	|	Metric	|	Event suggestion	|	Example	|
---	|	---	|	---	|	---	|
Create an account	|	how often do users click on the the component to create an account	|	Homepage create account CTA	|	Homepage create an account CTA	|
Benefit promo	|	how often do users click through to read more about the benefit promo	|	Homepage benefit promo > [title]	|	Homepage benefit promo > The PACT Act and your VA benefits	|
Search	|	what searches are performed on the homepage using the search field on the body (rather than in the header)	|	Homepage > Search | _We should be able to leverage the pattern used for the search in the header while differentiating the search field on the page rather than in the header_	|		
Other search tools		how often do users click on a specific link from the list of other search tools	|	Other search tools	  > [link label]	| Other search tools  > Find a VA location	
Popular on VA.gov	|	how often do users click on a specific link from the Popular on VA.gov list	|	Popular on VA.gov  > [link label]	|	Popular on VA.gov  > Check your claim or appeal status	|
News promo	|	how often do users click through on the title of the promo	|	Homepage news promo > [title] >title 	| Homepage news promo > Pathfinder	> title |
News promo	|	how often do users click through to read the full article	|	Homepage news promo > [title] > CTA	|	Homepage news promo >  Pathfinder >CTA	|
News promo	|	how often do users click through to "More VA news"	|	Homepage news promo > More VA news	|	Homepage news promo > More VA news	|
Benefit hubs	| 	how often do users click on a specific benefit hub	| 	Benefit hub > [benefit hub name]	| 	Benefit hub > VA department	| 
Email	|	how often do users submit an email to sign up	|	Homepage email sign up	|	Homepage email sign up	|
Mega menu	|	maintain existing event tracking	|||
Header	|	maintain existing event tracking	|||
Footer	|	maintain existing event tracking	|||

## Acceptance Criteria

- [x] Analytics team can help us test these once they are available in staging
- [x] Create an account events are tracked, distinctly from header sign-in events, such as `Homepage create an account CTA`
- [ ] Events on Benefit promo are tracked by title and as initiated on the body of the homepage, such as `Homepage benefit promo > The PACT Act and your VA benefits` 
- [x] Search events are tracked and identifiable as interactions occurring on the body of the page, rather than from the header, such as `Homepage > Search`
- [ ] Events on "Other search tools" are tracked by link label, such as `Other search tools  > Find a VA location`
- [x] Events on "Popular links menu" are tracked by link label, such as `Popular on VA.gov  > Check your claim or appeal status`
- [x] Events initiated via the VA news promo title link are tracked by name and as initiated on the body of the homepage, such as `Homepage news promo > title > Pathfinder`
- [x] Events initiated via the VA news promo CTA are tracked by name and as initiated on the body of the homepage, such as `Homepage news promo > CTA > Pathfinder`
- [ ] Events on the More VA news link are identified as initiated on the body of the homepage, such as `Homepage news promo > More VA News`
- [x] Events on email signup are tracked, such as `Homepage email sign up`
- [x] Benefit hub events are tracked by Hub title, such a `Benefit hub > VA department`
- [x] Mega menu event tracking should be maintained
- [x] Header event tracking should be maintained
- [x] Footer event tracking should be maintained

## QA Steps
- [ ]  Verify in AdSwerve that the events are firing
- [ ]  Analytics team said they can assist via making sure the new event tagging/data layer works. Let @mmiddaugh know when changes are in PR and she'll ping Analytics for review, or can review herself

### CMS Team
Please check the team(s) that will do this work.
- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
