### ISSUE TITLE
CMS: Align VA health services taxonomy VBA services view display with the VAMC and Vet Centers displays

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#11473]
## User Story or Problem Statement

In the VA services taxonomy view display, VBA services names are showing the "Patient friendly names" instead of the "Name" field. This is are out of alignment with VBA and VAMC.

![Screen Shot 2022-11-04 at 4 39 56 PM](https://user-images.githubusercontent.com/766573/200079198-9e65e51a-0e3c-4519-aea3-d528e27d660e.png)

## Acceptance Criteria
- [x] Checking the "Show for VBA facilities" for a given term makes the term name show in the list of available services when creating a VBA Facility Service
![Screen Shot 2022-11-04 at 4 48 02 PM](https://user-images.githubusercontent.com/766573/200080529-8565645a-ad85-4f85-aad9-7ef9f54f4e62.png)

![Screen Shot 2022-11-04 at 4 50 32 PM(2)](https://user-images.githubusercontent.com/766573/200080566-ddf6af3f-8ab6-474a-8f17-5ac2878a9fec.png)

## Implementation steps
Update the view display (/admin/structure/views/view/health_care_service_names_and_descriptions/edit/entity_reference_vba_services) to be like Vet Center or VAMC.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
