### ISSUE TITLE
Create and save a node of every content type in Cypress/behavioral tests.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#11493]
## Description
I thought I'd created this before, but apparently did not 😞 

Our behavioral tests should create and save a node (and verify it was saved correctly) of every content type.

This is an inexpensive way of verifying a lot of the basic (read: embarrassing to break) functionality of the CMS.  And timely, given the upgrades to PHP 8.1 and Drupal 10 we have ahead of us.

## Acceptance Criteria
- [x] Followup issues have been opened to create and save a node of every content type:
  - [x] #12456
  - [x] #12457
  - [x] #12458
  - [x] #12459
  - [x] #12460
  - [x] #12461
  - [x] #12462
  - [x] #12463
  - [x] #12464
  - [x] #12465
  - [x] #12466
  - [x] #12467
  - [x] #12468
  - [x] #12469
  - [x] #12470
  - [x] #12471
  - [x] #12472
  - [x] #12473
  - [x] #12474
  - [x] #12475
  - [x] #12476
  - [x] #12477
  - [x] #12478
  - [x] #12479
  - [x] #12480
  - [x] #12481
  - [x] #12482
  - [x] #12483
  - [x] #12484
  - [x] #12485
  - [x] #12486
  - [x] #12487
  - [x] #12488
  - [x] #12489
  - [x] #12490
  - [x] #12491
  - [x] #12492
  - [x] #12493
  - [x] #12494
  - [x] #12495
  - [x] #12496
  - [x] #12497
  - [x] #12498
  - [x] #12499
- [x] ~The relevant code is created in the right place.~ (see #9277)
- [x] ~A test or documentation is created advising engineers to extend these tests when they add a new content type.~ (see #12611)
- [x] ~Accessibility test is run against node creation form.~ (see #12610)
- [x] ~Accessibility test is run against node view page.~ (see #12610)

**Comment by ndouglas** [comment]
@edmund-dunn I couldn't find the issue, so I created a new one.  (I think I had this in mind with #9277, but maybe I didn't verbalize it.)  Anything to add?

**Comment by ndouglas** [comment]
Changed estimate for this issue to 3 after revising the scope.

**Comment by ndouglas** [comment]
Closed in favor of various followups.
