### ISSUE TITLE
Show VA Services description fields in term:view as rendered

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#11508]
## User Story or Problem Statement

As an editor, I want to see the VA Services description fields rendered as HTML rather than plain text so that I see an approximation of the content on the front-end.

The fields to render:

- field_vet_center_service_descrip
- field_tricare_description
- field_vba_service_descrip

### Manage Display Can't Change This
![va-gov-cms.ddev.site_admin_structure_taxonomy_manage_health_care_service_taxonomy_overview_display.png](https://images.zenhubusercontent.com/62aa0d60f60c1181e8837c67/ff5e5da2-1b1f-41c2-ad5a-1bd08e1ec476)

Whereas the "Description" field comes with the term and has a "Default" format, the other descriptions, do not.

![Screen Shot 2022-11-08 at 12.40.52 PM.png](https://images.zenhubusercontent.com/62aa0d60f60c1181e8837c67/04a20ed5-eb6e-424c-bc39-eddef9a60aca)

## Acceptance Criteria
- [ ] `field_vet_center_service_descrip` displays as rendered HTML in node:view
- [ ] `field_tricare_description displays` as rendered HTML in node:view
- [ ] `field_vba_service_descrip` displays as rendered HTML in node:view

## Implementation steps
Preprocess hook?

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
Low priority given that this page only is used by a select few.

**Comment by EWashb** [comment]
This goes to Dave C, but has been iceboxed.

**Comment by davidmpickett** [comment]
Unless I'm wrong, seems like this is simply a drop-down setting on the VA Services (Taxonomy Term) View
/admin/structure/views/nojs/handler/vha_health_service_taxonomy/default/field/field_vet_center_service_descrip

![Screenshot 2023-10-09 173328](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4643cb7c-aa99-48dd-8ea0-017e6bd0c21a)
