### ISSUE TITLE
CMS: Show Services name and description VBA Facility node:view

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#11516]
## User Story or Problem Statement

As an editor, I want to see the name and description of the services on the VBA Facility node:view so that I can see what services are currently listed and how they are described.

## Acceptance Criteria

- [ ] Under SERVICES: the name of the service <Facility name> - <Service name> is displayed, followed by the description from the "VBA description" in the "VA Services" term.
  - [ ] The term description follows the pattern of other national content, displayed in a greyed out box with a tooltip.
![Screen Shot 2022-11-21 at 2 41 28 PM (2)](https://user-images.githubusercontent.com/766573/203155649-82ad74d7-46fb-401b-8ef6-86fd63a38e79.png)

- [ ] If the "VBA service description" field has content for a facility service, that content displays after the national content.

![Screen Shot 2022-11-08 at 2 33 48 PM](https://user-images.githubusercontent.com/766573/200690203-5d5f1f41-1db1-482f-9f66-8355bdf2930a.png)

## Implementation steps
Create a module for VBA.
Use the code from `appendHealthServiceTermDescriptionToVetCenter` in `va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php` as a model.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
PR is ready to review.
