### ISSUE TITLE
Make Vet Center node:view services listing text the same as the front-end

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#11519]
## User Story or Problem Statement

As an editor, I want the Services listing on the Vet Center node:view to more closely mirror the front-end, so I know that the information I've entered is accurate, complete and not redundant of the national content from the taxonomy term.

## Example of the Current Difference
https://www.va.gov/san-juan-vet-center/
vs
https://prod.cms.va.gov/san-juan-vet-center

![Screen Shot 2022-11-08 at 4 44 33 PM](https://user-images.githubusercontent.com/766573/200694143-dc629976-c233-4db5-b63c-5d2f764fd123.png)

## Acceptance Criteria
- [ ] The text under a service description in the node:view of a Vet Center should be identical (with concessions to theme differences) to the front-end node of the same Vet Center
- [ ] VA Services term field `field_vet_center_service_descrip` data is displayed on node:view under the appropriate service name
- [ ] If `field_vet_center_service_descrip` is empty, the term's `Description` field data should be displayed under the appropriate service name
- [ ] After the term description data, the Vet Center Facility Service `field_body` data should be displayed

## Implementation steps
Edit `appendHealthServiceTermDescriptionToVetCenter` in `va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php`
- append national information from term
	- national information should come from field_vet_center_service_descrip
	- if field_vet_center_service_descrip is empty get the field_service_name_and_descripti description
		- https://api.drupal.org/api/drupal/core%21modules%21taxonomy%21src%21Entity%21Term.php/function/Term%3A%3AgetDescription/8.8.x
	- Display as on the front-end: 
		- national information
		- facility service-specific information

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
This is a defect with current Vet Center behavior. We do NOT want to reproduce this behavior to VBA.  No dependencies, this can just be fixed.

**Comment by EWashb** [comment]
@omahane wanted to put this on the top of your radar. I saw it was still in the "new" column but should have been in to do

**Comment by omahane** [comment]
@davidmpickett @swirtSJW 
Should I try to account for when the national service description itself is blank, as opposed to when the term is removed?
<img width="1840" alt="Screen Shot 2022-12-06 at 11 45 02 AM" src="https://user-images.githubusercontent.com/766573/205989632-d9fc624f-21dc-416c-9eb5-b1f422e90abd.png">


Right now in the PR branch, when the service description is blank, the tooltip still shows, but it’s empty. When the term is removed, we have that handy text that says “Notice: The national service description was not found.”

On the live site in the CMS node:view of Vet Centers shows nothing underneath the term at all if there’s no national service description in the taxonomy term, meaning no visual indication of any sort that there’s nothing there, as the empty tooltip box hints at, though doesn’t say outright.

<img width="1840" alt="Screen Shot 2022-12-06 at 12 12 58 PM" src="https://user-images.githubusercontent.com/766573/205989655-ab11e385-4798-448f-a1c1-cec4c4b6c958.png">

**Comment by omahane** [comment]
If I make a change to account for an empty service description in the taxonomy term for Vet Center, I should also change it for VBA.

**Comment by omahane** [comment]
This is what the code in the PR does at present.
![Screen Shot 2022-12-07 at 8 24 51 AM](https://user-images.githubusercontent.com/766573/206223929-d021ee7b-dbf9-4338-8e85-26484a3c386c.png)

**Comment by omahane** [comment]
We discussed this issue and decided to follow the front-end so that when the Vet Center service description is not available that we use the VAMC description.
