### ISSUE TITLE
Align VBA Facility Service inline entity editor to Vet Center

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#11510]
## User Story or Problem Statement

As an editor, I want the editing of VBA Facilities Services on the VBA Facility content type to mirror the Vet Center experience to make work more consistent and predictable.

## Questions and Suggested changes

- UX: Add instructions to the Services field
- UX question: Should we make the Services table header include the Facility name?
- UX question: Should we remove the Facility name from each service in the table?
- Remove the Facility field as editable (while setting it automatically)
- Remove the Section field as editable (while setting it automatically)
- Winnow the Service names to only those not yet added to the facility
- Review the existing VBA facility service type and services taxonomy to ensure the minimum fields necessary to create the relationship with the VBA facility are present

### Vet Center (possible model)
![Screen Shot 2022-11-08 at 1 38 40 PM](https://user-images.githubusercontent.com/766573/200661787-4ccb04a7-39c1-4dcf-bd0a-d8d323b61900.png)
![Screen Shot 2022-11-08 at 1 36 32 PM](https://user-images.githubusercontent.com/766573/200662133-881c9d31-2eca-4597-bc52-cacedd938b62.png)

### Current VBA Facility (with questions or suggested changes)
![Screen Shot 2022-11-08 at 1 41 01 PM](https://user-images.githubusercontent.com/766573/200661719-0b16e922-9abe-4c3d-bec6-5871971b1014.png)
![Screen Shot 2022-11-08 at 1 36 18 PM](https://user-images.githubusercontent.com/766573/200662185-a9309aa8-390e-4995-84a7-2d7900fd9aa8.png)

## Acceptance Criteria
User ex for adding a VBA Service to a VBA Facility should be identical to the user ex for adding a vet center service to a vet center facility

## Implementation steps
TBD

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by dsinla** [comment]
@BlakeOrgan @EWashb Can you weigh in? Is there any existing research/feedback from Vet Center editors? 
The Dev team is looking for some guidance before executing. Please advise when this might fit in your timeline?

**Comment by EWashb** [comment]
@dsinla we do have Vet Center research! I conducted a large study this time last year. Want to try to meet to chat about it? We also have insights listed in our Airtable Repository

**Comment by xiongjaneg** [comment]
No longer applies, inline editor removed
