### ISSUE TITLE
Redesigned homepage - implement feedback button for launch

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11537]
## Issue description
As the Sitewide Homepage team, we need a way for Veterans and beneficiaries to provide feedback on the redesigned homepage experience. 

Note, this implementation may require some custom work as the position of the feedback button on the current homepage may compete with other page elements or cause confusion given the proximity with the row of Veteran portraits and the email signup field. 

## Tasks
- Work with analytics team as needed to implement feedback button on redesigned homepage

## Pending
- [x] Design from Ryan _(expected by 11/11/2022)_
- [ ] Mobile design from Ryan

## Screenshots

Reference: [Sketch Round 3](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas)

<details> 
<summary> Desktop and Mobile designs </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/c5ba40ea-61ef-441a-a4a4-8a84d790493f)

</details>

## Acceptance criteria
- [ ] Ensure GA click is unique/trackable
- [ ] A Veteran or beneficiary can use the feedback button on the redesigned homepage experience.
- [ ] The feedback button is accessible to all users, regardless of screenreader, keyboard, voice navigation. or other assistive device. 
- [ ] The feedback button is accessible to all users, regardless of mobile, smartphone or desktop device.
- [ ] The feedback button is visible onscreen, even if the page is viewed with zoom. 
- [ ] Feedback provided on the redesigned homepage can be differentiated from feedback provided on existing/current homepage
- [ ] Requires accessibility review
- [ ] Requires design review (Michelle Middaugh or Ryan T)
