### ISSUE TITLE
Redesigned homepage - soft launch modal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11536]
## Issue description
As the Sitewide Homepage team, we need a way to offer the opportunity to use the new redesigned homepage experience to Veteran and beneficiaries visiting VA.gov. 

A similar need occurred during the original launch of VA.gov but was managed using a preview subdomain which is not an option for this launch. 

Two options were evaluated during a design, accessibility and implementation discussion
- a banner, allowing a user to move between the existing and new experiences 
- a pop-up modal allowing a user to "opt in" to the new experience. 

**The modal was determined to be the preferred approach.** 

<details>
<summary> Pros/cons for banners and modals </summary>

Banners
 - (+) avoid the risk of stacking modals
 - (-) could unintentionally introduce user distrust 
 - (-) would create an escape route preventing data and feedback collection
 - (+/-) banners are less prominent 
 - (-) banner blindness
Modal
 - (-) stacking risk presents usability and accessibility concerns 
 - (+) prominent display
 - (+) making it dismissible will manage annoyance factor and various user flows
</details>

## Expected behavior
- The redesigned experience modal is presented **only** on the VA.gov homepage.
- A Veteran or beneficiary can interact with the modal to agree or decline to use the redesigned homepage.
- The modal offering the redesigned homepage experience displays **only once** within a user's session.
- Regardless of previous opt-in or decline, the modal will be presented during the user's next session (which includes the homepage).
- If the Veteran or beneficiary opts-in to the  redesigned homepage experience, the redesigned page opens in the same window and tab.
- The Veteran or beneficiary can return to the current homepage by using the VA logo and/or back button. The breadcrumb may also be an option, depending on the page. 

_Acceptable known risk:
Veterans or beneficiaries who opt-in to the redesigned experience may not be able to easily return to the redesigned page after navigating to deeper content pages. The user_ **may** _be able to return to the redesigned page using the back button. This user will have another opportunity to opt-in from the homepage during the next VA.gov session._

## Pending
- [ ] Design from Ryan _(expected by 11/11)_
- [ ] Content input from Danielle _(meeting scheduled for 11/10)_
- [ ] Resolution for stacking modals

## Tasks
- Implement redesigned experience modal using cookies to govern display within a user's session
- Focus management and experience via keyboard, voice or screenreader should follow patterns established by other modals in use across VA.gov. 

## Acceptance criteria
- [ ] When a Veteran or beneficiary arrives on the VA.gov homepage, the existing homepage is displayed with a modal to opt-in to the redesigned homepage experience.
- [ ] The user can interact with the modal to opt in or out of the redesigned homepage experience. 
- [ ] The redesigned experience modal does not display on any page except the VA.gov homepage. 
- [ ] The redesigned experience modal is displayed only once during a user's session, regardless how many times the user returns to the homepage. 
- [ ] When a Veteran or beneficiary opts-in to the redesigned homepage experience, the redesigned page is displayed in the same window and tab.
- [ ] When a Veteran or beneficiary dismisses the modal, the existing homepage continues to be displayed in the same tab/window.

**Comment by mmiddaugh** [comment]
closing as a duplicate - Zenhub fluke
