### ISSUE TITLE
PW: Deprecate unused feature flags / toggles / flippers in FE and CMS

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#11530]
## Status:
- 2024-01-25: Per Dave C we should start whittling these down and work on them as when possible.

## Background

Request from @RachalCassity:
Console Services Team is evaluating site performance, and identified that feature toggles (Flipper) in vets-api and vets-website repos. 

Feature toggles endpoint is called multiple times per page, and causes Sentry errors / site latency.

Proposed list of Ownership: 
* https://docs.google.com/spreadsheets/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965

Existing flags: 
* [https://api.va.gov/flipper/features](https://www.google.com/url?q=https://api.va.gov/flipper/features&sa=D&source=calendar&ust=1662303611628068&usg=AOvVaw2bP4_CvR8dI3vKbCwf6eRj)
* [https://prod.cms.va.gov/admin/config/system/feature_toggle](https://www.google.com/url?q=https://prod.cms.va.gov/admin/config/system/feature_toggle&sa=D&source=calendar&ust=1662303611628068&usg=AOvVaw0l96tdWhmHqTuDVzq_9fja)

## CMS Feature toggles follow up work
https://prod.cms.va.gov/admin/config/system/feature_toggle
* FEATURE_ALL_HUB_SIDE_NAVS - not enabled, always false. Remove conditional checks in content-build and delete in CMS.
* FEATURE_SINGLE_VALUE_FIELD_LINK - relates to promo blocks. Remove conditional checks in content-build and delete in CMS.
### Complete, no-op 
* FEATURE_HEADER_MEGAMENU - was enabled in CMS, but doesn't show up in content-build. Steve deleted from Prod.
* FEATURE_IMAGE_STYLE_23 - disabled in CMS, doesn't appear in content-build. Steve deleted from Prod.
* FEATURE_FOOTER_MENU - disabled in CMS, doesn't appear in content-build. Steve deleted from Prod.
* FEATURE_CHANGE_LEADERSHIP_LINK- disabled in CMS, doesn't appear in content-build. Steve deleted from Prod.
* FEATURE_RECURRING_EVENTS - disabled in CMS, doesn't appear in content-build. We know this logic was removed during Recurring events 2022Q2 bug bashing. Steve deleted from Prod.

@swirtSJW to follow up with a commit to remove these flags from code if they don't effectively disappear from config based on DB delete, based on #5855

## Feature flippers follow up work
https://api.va.gov/flipper/features
* Audit of PW owned flags or ones we need to verify: https://docs.google.com/spreadsheets/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965 (Public Websites filter view enabled)

## Acceptance criteria
- [X] Schedule sync session with Dave C, Public Websites FE / PM, Facilities FE / PM to audit feature toggles, identify utility / ownership
  - [X] https://api.va.gov/flipper/features
  - [X] https://prod.cms.va.gov/admin/config/system/feature_toggle
  - [x] Confirm ? Flippers with Dave
  - [x] Assess 2 CMS flags for effort to remove content-build code prior to deleting CMS flag
  - [x] Assess PW flags in [Flipper audit sheet](https://docs.google.com/spreadsheets/d/1yQb5oDshNj7y0nvtF3PaZ9OLhtTuZ2aO8t4_n51YBWU/edit#gid=237722104&fvid=1552255965) & determine which flags can be removed (Column F), Notes in Column G
- [ ] If a flipper is not being called from anywhere in code, it can be removed. 
- [ ] If a flipper is being called at all, identify in doc and do not remove. Describe usage, so we can understand whether or not it can be removed.
  - [ ] Summarize tasks, risks, and effort of removing. 
  - [ ] FE team + Product + Dave will review findings to decide 

  
### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Note: new(ish) guidance from Plat on removing flippers: https://depo-platform-documentation.scrollhelp.site/developer-docs/feature-toggles-guide#Featuretogglesguide-Removingold/unusedfeaturetoggles

**Comment by jilladams** [comment]
@FranECross note from Dave that we should start prioritizing the work in this epic into upcoming sprints, to try and burn down this tech debt, out of respect for the platform team ask to get rid of unused flippers.

**Comment by FranECross** [comment]
All stories completed. Closing.
