### ISSUE TITLE
Redesigned homepage - soft launch modal

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11535]
## Issue description
As a Veteran, I want to be given the opportunity to check out the redesigned homepage once per session so that I can know what's coming and offer feedback.

As the Sitewide Homepage team, we need a way to offer the opportunity to use the new redesigned homepage experience to Veteran and beneficiaries visiting VA.gov. so that we can gather feedback to determine readiness for cutover. 

### Technical considerations

- Ensure the modal **only** displays on VA.gov homepage (`/`)
- Ensure the modal doesn't display on injected sites
- Ensure our modal doesn't display if another modal is called on page load
  - The modal we know about is [modal that appears for users redirected from explore.va.gov](https://www.va.gov/?from=explore.va.gov)

<details>
<summary> Background and pros/cons for banners and modals </summary>

A similar need occurred during the original launch of VA.gov but was managed using a preview subdomain which is not an option for this launch. 

Two options were evaluated during a design, accessibility and implementation discussion
- a banner, allowing a user to move between the existing and new experiences 
- a pop-up modal allowing a user to "opt in" to the new experience. 

**The modal was determined to be the preferred approach.** 

Banners
 - (+) avoid the risk of stacking modals
 - (-) could unintentionally introduce user distrust 
 - (-) would create an escape route preventing data and feedback collection
 - (+/-) banners are less prominent 
 - (-) banner blindness
Modal
 - (-) stacking risk presents usability and accessibility concerns 
 - (+) prominent display
 - (+) making it dismissible will manage annoyance factor and various user flows
</details>

## Expected behavior
- The redesigned experience modal is presented **only** on the VA.gov homepage.
- A Veteran or beneficiary can interact with the modal to agree or decline to use the redesigned homepage.
- The modal offering the redesigned homepage experience displays **only once** within a user's session.
- Regardless of previous opt-in or decline, the modal will be presented during the user's next session (which includes the homepage).
- If the Veteran or beneficiary opts-in to the  redesigned homepage experience, the redesigned page opens in the same window and tab.
- The Veteran or beneficiary can return to the current homepage by using the VA logo and/or back button. The breadcrumb may also be an option, depending on the page. 

_Acceptable known risk:
Veterans or beneficiaries who opt-in to the redesigned experience may not be able to easily return to the redesigned page after navigating to deeper content pages. The user_ **may** _be able to return to the redesigned page using the back button. This user will have another opportunity to opt-in from the homepage during the next VA.gov session._

## Pending
- [x] _Final_ Design from Ryan _(expected by 11/11)_
- [ ] _Final_ Content input _(draft content now available)_
- [ ] Resolution for stacking modals

## Example Modal 

Reference Design system modal: https://design.va.gov/components/modal

## Design

<img width="695" alt="image (19)" src="https://user-images.githubusercontent.com/85581471/203634240-c30adba9-f020-4791-abd8-05df784d58f7.png">

* [Slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1669152245109399) with design system about approved ways to handle the 2 CTA links
  * NOTE: use design system components as-is, no special stying should be required. Mockup above was done in Mural so alignments, padding, sizing, etc is not accurate
* ~~[Sketch design](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/a/uuid/EEA4DD2D-B2EA-42D3-B10D-DC5A3EA958B7) (NOT FINAL as of 11/23 -- Sketchwas not caught up with the design system discussion above, so rely on the image here / slack thread for official guidance)~~ _outdated for the modal design_

## Draft content

> [h1] Try our new VA.gov homepage
> 
> We're redesigning the VA.gov homepage to help you get the tools and information you need faster. 

> And we want your feedback to help us make it even better. 
> 
> [cta1] Try the new homepage [semantic link, Primary action link from design system]
> [cta2] Not today, go to the current homepage [semantic button, secondary button from design system] 

## Tasks
- Implement redesigned experience modal using cookies to govern display within a user's session
- Configure modal to report analytics
- Focus management and experience via keyboard, voice or screenreader should follow patterns established by other modals in use across VA.gov. 

## Acceptance criteria
- [x] Modal must sit behind a Flipper for both Staging and Prod -  #11653 tracks creation of the Flipper
- [x] When a Veteran or beneficiary arrives on the VA.gov homepage, a modal to opt-in to the redesigned homepage experience overlays the existing homepage.
- [x] Selecting to opt-in with [cta1] link "Try the new homepage" opens the redesigned homepage URL (`/new-home-page`) in the same window/tab. 
- [x] Selecting to opt-out with [cta2] button "Not today, go to the current homepage" closes the modal, displaying the existing/current homepage URL in the same window/tab. 
- [x] Selecting the "x" will close the modal and the existing/current homepage URL will be displayed in the same window/tab. 
- [x] Pressing the ESC key will close the modal and the existing/current homepage URL will be displayed in the same window/tab. 
- [x] The redesigned experience modal _**only**_ displays VA.gov homepage (`/`)
- [ ] The redesigned experience modal is displayed only once during a user's session, regardless how many times the user returns to the homepage. 
- [ ] ~~This modal IS NOT DISPLAYED if another modal should also be present (e.g., the Explore VA redirect modal)~~
- [x] This modal IS NOT DISPLAYED on injected-header/footer sites

**Analytics**
  - [x] When a user opts in to the new homepage, the modal reports analytics with  `event: new-homepage-modal-click` + `modal-primaryButton-text: try the new homepage`
  - [x] When a user declines the new homepage, the modal reports analytics with `event: new-homepage-modal-click` + `modal-secondary-link: go to current homepage`
  - [x] When a user closes the modal, the modal reports analytics with `event: new-homepage-modal-close`
 
### Accessibility-specific ACs
[See design system](https://design.va.gov/components/modal#accessibility-considerations)

- [x] Modal should have the role=”dialog” attribute.
- [x] Content behind the modal should not scroll while the modal is open.
- [x] The modal and its interactive elements are accessible to all users, regardless of mobile, smartphone or desktop device.
- [x] The modal and its interactive elements are visible onscreen, even if the page is viewed with zoom. 
- [ ] The modal and its interactive elements are accessible to all users, regardless of screenreader, keyboard, voice navigation. or other assistive device.
- [ ] Modal should have an aria-labelledby attribute where the value is the ID of the modal title (you don’t need or want the #).
- [ ] Modal should have an aria-describedby attribute where the value is the ID of a div that contains a description of the modal (you don’t need or want the #).
- [ ] When the modal is closed, focus should go to the skip link at the top of the current/existing or redesigned page, based on user selection. 
- [ ] Pressing the ESC key should close the modal and return the focus to the element that triggered the modal.
- [x] "Try the new homepage" should semantically be a link
- [x] "No Thanks" should semantically be a button
- [ ] Requires accessibility review (Laura Flannery)

**Comment by jilladams** [comment]
Currently blocked on design. Moved to Stretch, as we need to act on this as soon as we have design.

**Comment by jilladams** [comment]
Reassigned to Josh to help with build, so Bryan can focus on session logic when he's back online. Tradeoff: Deprioritizing Drupal footer for now.

**Comment by jilladams** [comment]
- [ ] As soon as deployed & flipper is on: **VERIFY that modal doesn't appear on injected header/footer sites**
