### ISSUE TITLE
Redesigned homepage - update "Create account" area

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11538]
## Issue description
As the Sitewide Homepage team, we need a method to present the value for creating a VA.gov account and information on choosing the type of account.  

**Cross-functional team decision** 
- Create a Resources and Support page to support account creation
- Update language (as needed) in "Create account" area on redesigned homepage 
   _- (note from Danielle, the copy should say "...anytime, `from` anywhere" and use the longer em dash rather than a hyphen)_
- Connect "Create account" area on redesigned homepage with new account creation page in Resources and Support 

## Pending
- [x] Design from Ryan _(expected by 11/11/2022)_
- [x] Content changes from Danielle _(expected by 11/11/2022)_
- [ ] URL for new account creation page in Resources and Support [TBD]
- [ ] Availability of new account creation page in Resources and Support [TBD]

## Screenshots

Reference: [Sketch Round 3](https://www.sketch.com/s/3aa40506-4be2-46cc-876b-93f1a9f3a857/p/EAD305BC-3082-4F81-ADEC-C2486F7B6BEF/canvas)

<details> 
<summary> Desktop and Mobile designs </summary>

![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/bbf85615-a6d1-445d-aea3-88eba32a9298)
![image.png](https://images.zenhubusercontent.com/5d8a47393ac3440001d1a2ed/4bc77942-e878-4ebc-9a47-eea0dff600e1)

</details>

## Tasks

Update "Create account" area on redesigned homepage, including
- [ ] Change "Welcome to VA.gov" to the new look, padding, etc.
- [ ] Update content to "Create an account to manage your VA benefits and care in one place - any time, from anywhere." 
- [ ] Add link label "Learn how an account helps you" which directs to Resources and Support account creation page [_link TBD_]

## Acceptance criteria

- [ ] "Welcome to VA.gov" is bigger and ~doesn't~ _does_ have lines above and below
- [ ] The link to the new account creation page in Resources and Support has the "Learn how an account helps you" label and is styled as a link. 
- [ ] A Veteran or beneficiary can click on the "Learn how an account helps you" label to view the new Resource and Support account creation page [_link TBD_]
- [ ] "Create account" component has updated intro text.

**Comment by wesrowe** [comment]
@mmiddaugh, the H1 changed on the new layout to look more like an H1 also. I'll add that to the ACs. Can you have a second look for any other tweaks in the design?

**Comment by wesrowe** [comment]
@mmiddaugh, this ticket was assigned to @maxx1128 in this sprint, but it shows as blocked, pending Ryan Thurlwell's updates to Sketch. Can you confirm whether that update has been made, or do you have an ETA?

**Comment by jilladams** [comment]
@maxx1128 this work is unblocked and the Sketch file linked in ticket body is up to date / ready to reference for build.
