### ISSUE TITLE
Migrate runtime tasks off of Jenkins to GHA

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11543]
## Description
As part of the migration off of BRD, the first set of tasks we want to move are runtime tasks. This is based on the spike done in #9765 

Tasks that occur outside of a deployment. In the near future these will need a different orchestration/automation tool to trigger and run these actions. So far, Github Actions is the leading candidate. It is free, similar to Jenkins, and has self-hosted runners available. The automation tool choice to replace Jenkins for these tasks will likely be independent of the system to host/deploy the CMS.

## Acceptance Criteria
Each of the runtime tasks identified in the following categories has been migrated from Jenkins to GHA:
- [ ] Determine path forward for CMS every-minute tasks run on prod
- [ ] CMS periodic tasks run on prod
- [ ] CMS daily tasks run, stored in va.gov-cms repo
- [ ] Backup database on prod.cms.va.gov
- [ ] Backup EFS sites/default/files/ on prod.cms.va.gov
- [ ] Sanitize database on prod.cms.va.gov

**Comment by TheBoatyMcBoatFace** [comment]
May no be applicable with projected post-jenkins plan. Will re-open if it becomes applicable #11554
