### ISSUE TITLE
Determination on best workflow tool & Implement

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#11554]
## Description
As part of the migration off of BRD, there was a spike done in #9765 to inventory all CMS tasks that need to be moved.

Before starting any migrations, we need to determine the best workflow tool to leverage. We defaulted to GitHub Actions but have brainstormed multiple potential issues with that.

- Limitation on frequency of job runs
- GHA isn't great to see the output of tasks that run with a high frequency

We'll want to coordinate with the Platform Infrastructure team on their recommendations.

## Acceptance Criteria

- [x] **Research Solutions** - Determine possible alternative solutions and document findings below
- [x] **Decide on Possible Alternative** - Decide on alternative and develop plan to finalize review & decision
- [ ] **Develop & Document Implementation Plan** - Develop plan (issues) to roll out changes and new platform

**Comment by ElijahLynn** [comment]
Slack discussion here > https://dsva.slack.com/archives/CJYRZK2HH/p1668112547807419

**Comment by cmaeng** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/11554?planning-poker) with Zenhub @ElijahLynn @olivereri @timcosgrove

**Comment by olivereri** [comment]
Starting a discussion with Github support to explore what our options are for running workflows on a sub-5-minute schedule: https://dsva.slack.com/archives/CU1E4CX9U/p1668549708262719

**Comment by olivereri** [comment]
Previous exploration of Lagoon as a solution:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6673

**Comment by olivereri** [comment]
## Options
### Take Over Existing Jenkins
### Role Our Own Jenkins in EKS
### Github Actions Worflows
### Lagoon
### Argo Workflows
### Kubernetes CronJob

**Comment by timcosgrove** [comment]
This is a large ticket and will roll over.

**Comment by mchelen-gov** [comment]
Can this be addressed with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8849 ?

**Comment by olivereri** [comment]
@mchelen-gov For the every-minute-job that sends Datadog metrics and content release queues, yes that would be appropriate. However, in the broader context of what we want to achieve, no we can't address this with the Advanced Queue runner in #8849.  

Thinking about it while I type this out, using the Advanced Queue runner for this more difficult to migrate tasks would provide us more flexibility. But I'm hesitant to make a expedient solution decision when we can land on a more comprehensive and long-term solution.

**Comment by TheBoatyMcBoatFace** [comment]
Adding to "Epic" workflow tool

**Comment by TheBoatyMcBoatFace** [comment]
Removed Sprint 72 and Added Sprint 73 Label

Issue larger than anticipated. Converting to Epic

**Comment by TheBoatyMcBoatFace** [comment]
Shifting focus from #11133 to this issue. See #11133 for additional info.

**Comment by TheBoatyMcBoatFace** [comment]
The findings from this issue are transitioning to the [Lagoon Implementation Epic](#11839).
- #11839

## Lagoon Implementation Epics

- #11836
- #11837 
- #11838
