### ISSUE TITLE
PHP 8.1 Testing Errors

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#11577]
## Background
The Sitewide CMS team is working on PHP upgrades heading into the end of life for PHP 7.4, slated for 11/28/22. We are updating to PHP 8.1. Testing is being done on this [tugboat link](https://vacms-10870-upgrade-to-php81-rh7pjindaxvyxvr35alvilr3mqpgaoko.ci.cms.va.gov/) and any bugs/issues/questions should be added as individual, separate issues and attached to this epic to be investigated and ultimately resolved.

## Acceptance Criteria
- [ ] All defects are investigated and/or resolved
- [ ] Determine if issues still exist

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@swirtSJW we discussed this epic in refinement. The investigate/resolve AC was agreed with everyone to be ok for these tickets. If we need more than meets the eye, we will create more tickets. That said, please add anything you'd like to since I'll be bringing it into sprint 75.

**Comment by EWashb** [comment]
looks like all issues have been addressed. closing
