### ISSUE TITLE
PW - Sprint 72 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11570]
### 1. Harden homepage for prod

**Page itself:**
- [ ] #11425 (3)
- [ ] #11654 (2)
- [ ] #11467 (5) 🥅 
- [ ] #11389 (5)
- [ ] #11538 (3)
- [ ] #11537 (2)

**Modal:**
  - [ ] #11587 (5) 🥅 
  - [ ] (stretch) #11682 ()
  - [ ] (stretch) #11653 (3)
  - [ ] (stretch, follows 11587) #11535 ()

**Post-MVP, not launch blocking (and not in Sprint)**
  - #11569 
  - #11568 (2)

**What else?**
  - Medallia survey design - #11414
  - Michelle content entry - #11370
  - How to test & confirm email subscription
  - #11286 (Jill to check, presume no-op)
  - #11586 ()
  - Launch tickets:
    - #11096 
    - #11652 

### 2. PDF Certificate Expiration Alert
- [ ] #11023 (3)
- [ ] #11021 (3) 🥅 
- [ ] #11022 (5)
 
### 3. Income Limits web app
- [x] #11168 (Cindy)
- [ ] (stretch pending Jordan start) #11372 () 
- [ ] What else?
  - FE technical / data strategy #11643, needs refining

### 4. Chatbot 
- No action yet identified

### 5. Benefit Content Model Hardening
- Dependency on Danielle prioritizing

### 6. Cerner API deprecation support
- [X] #9179 (8)
- [ ] (stretch) #11658 

### 7. Table 508 header compliance 
- HOLD, MVP done (template change); awaiting audit by SWContent to see if significant issues remain

###  Other 508
- [ ] (complexity revealed itself in S71) #11205 (2)
- [X] #10868 (2)

---

### Redirects
- [ ] (due ASAP) #11649
- [ ] (due Nov 30) #11677 
- [x] #11680
- [ ] #11662 
- [ ] (stretch) #10972 (2)(pending unblocking by stakeholders)
- [ ] (stretch) #11642
- [ ] (stretch) #11487 

### Content support
- [ ] 11420 (2)

### Outreach Materials / R&S Taxonomy
Later enhancement opportunity:
  - #11154 ()

### Support EDU how-to-apply wizard
- [x]  #10916 (3)  

### Form audit tools
- [ ] #11164 (3)
- [ ] (stretch) #11532 (2)
- [ ] (stretch) #11500 

### Drupalize footer
- [X] #11438 (3)
- [ ] (stretch) #11482

### Injected header post-mortem
- Actions waiting on conclusion of post-mortem

**Comment by jilladams** [comment]
Homepage: Added 3 tickets where Michelle has spelled out punchlist of FE changes from the V3 designs.

**Comment by jilladams** [comment]
Add: 
* #11680 
* #11023 
* #11420
