### ISSUE TITLE
Combine facilities_ppms_suppress_all and facilities_ppms_suppress_pharmacies flippers

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11589]
## Description
We need to retain the functionality to suppress PPMS data, but we can combine our similar PPMS flippers:

- `facilities_ppms_suppress_all`
- `facilities_ppms_suppress_pharmacies`

In any code where `facilities_ppms_suppress_all` is applicable, the Pharmacies suppression code should also apply.

Example: https://github.com/department-of-veterans-affairs/vets-website/blob/87758bcb186617f19dfc15d90eaadf14fa755199/src/applications/facility-locator/components/SearchControls.jsx#L222

```[tasklist]
## Tasks
- [x] Retain `facilities_ppms_suppress_all` flipper in vets-website and vets-api and combine any `facilities_ppms_suppress_pharmacies`-related functionality into the existing logic
- [x] If it's not already off, turn off `facilities_ppms_suppress_pharmacies` in all Flipper Admin environments
- [x] Remove references to `facilities_ppms_suppress_pharmacies` in vets-website and vets-api
- [x] Ask Platform to remove the flipper from the rails console (removing it from Flipper Admin)
```

**Comment by davidconlon** [comment]
This flipper exists so that if there are problems with the Provider Profile Management System (PPMS) we have the ability to disable all the front-end search interfaces that rely (either fully or partially) on data from PPMS.
At this time, the following Facility locator searches rely on data from PPMS:
* Facility Type = Community providers (in VA’s network)
* Facility Type = Community pharmacies (in VA’s network)
* Facility Type = Urgent care + Service type  = All in-network urgent care
* Facility Type = Urgent care + Service type - In-network community urgent care
* Facility Type = Emergency care + Service type  = All in-network emergency care
* Facility Type = Emergency care + Service type - In-network community emergency care

**Comment by Agile6MSkinner** [comment]
@jilladams @FranECross @mmiddaugh This flipper audit was done in late 2022. Would it even still be accurate? Are we realistically going to chase this work at any point?

**Comment by jilladams** [comment]
I don't know how to answer. Does the Platform definitely want us to be removing unused Flippers due to performance overhead on the VA.gov site? Yep. Will we ever choose to prioritize this work? ...I'm not sure. Can we walk away from the tech debt just because we don't intend to prioritize it? ...dunno. If the Platform ever got worked up about Flipper performance again, and put pressure on teams to remove their old flippers: we would definitely have to prioritize this work and the other tickets like it. 🤷‍♀️

**Comment by Agile6MSkinner** [comment]
Makes sense. Backlog seems appropriate.

**Comment by Agile6MSkinner** [comment]
Makes sense. Backlog seems like a good place for it for now.

**Comment by jilladams** [comment]
Will not remove. Will keep for long-term use. Closing as no op and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11591 will track updates on the flipper to document that in the flipper ui.

**Comment by randimays** [comment]
I think I forgot to re-open this when we discussed combining the flippers together. Re-opening.

**Comment by randimays** [comment]
@Agile6MSkinner ^

**Comment by randimays** [comment]
Flipper code has been consolidated and the pharmacies flipper has been removed from all flipper admin environments. Closing as complete!
