### ISSUE TITLE
Remove facility_locator_show_health_connect_number flipper

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11599]
## Description
Remove `facility_locator_show_health_connect_number` from all code where it is used

```[tasklist]
## Tasks
- [x] 1. Remove `facility_locator_show_health_connect_number` flipper and code implementation from vets-website
- [x] 2. Turn off flipper in all Flipper Admin environments
- [x] 3. Remove flipper from vets-api
- [x] 4. Once the vets-api PR has been merged, notify Platform that the feature flipper should be removed from the flipper dashboards in staging and production. ([example](https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549))
```

**Comment by randimays** [comment]
Flipper is removed from all code and the flipper dashboards in all environments. Closing as complete.
