### ISSUE TITLE
Remove facility_locator_rails_engine flipper

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11596]
## Description
Remove `facility_locator_rails_engine` from all its code usage.

```[tasklist]
## Tasks
- [x] 1. Remove `facility_locator_rails_engine` flipper and code implementation from vets-website
- [x] 2. Turn off flipper in all Flipper Admin environments
- [x] 3. Remove flipper from vets-api
- [x] 4. Once the vets-api PR has been merged, notify Platform that the feature flipper should be removed from the flipper dashboards in staging and production. ([example](https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549))
```

**Comment by randimays** [comment]
Based on a Github-wide search for [that flipper](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+facility_locator_rails_engine&type=code) and [its variable in vets-website](https://github.com/search?q=org%3Adepartment-of-veterans-affairs+facilityLocatorRailsEngine&type=code) it is very unlikely this flipper is used, but whomever picks this up should definitely sanity-check.

**Comment by randimays** [comment]
Flipper is removed from all code and the flipper dashboards in all environments. Closing as complete.
