### ISSUE TITLE
Evaluate flipper facility_locator_pull_operating_status_from_lighthouse for removal

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11595]
## Description
Investigate facility_locator_pull_operating_status_from_lighthouse flipper for current use and eligibility for removal.

Refer to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10656

```[tasklist]
## Tasks
- [x] Establish eligibility for removal
- [x] Note outcome in comments
- [x] Remove if eligible
```

**Comment by randimays** [comment]
Pulled into Sprint 19.

**Comment by randimays** [comment]
Flipper was not in use; it has been removed from code in [this PR](https://github.com/department-of-veterans-affairs/vets-api/pull/19889) and the dev, staging and production flipper admins via [this Platform thread](https://dsva.slack.com/archives/CBU0KDSB1/p1734116513770649).
