### ISSUE TITLE
Remove flipper show_expandable_vamc_alert and its implementation                  

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11600]
## Description
Remove the `show_expandable_vamc_alert` and its code usage here:

- https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/platform/site-wide/alerts/showVaAlertExpandable.js
- https://github.com/department-of-veterans-affairs/vets-website/blob/87758bcb186617f19dfc15d90eaadf14fa755199/src/platform/utilities/feature-toggles/featureFlagNames.json#L228

```[tasklist]
## Tasks
- [x] 1. Remove `show_expandable_vamc_alert` and its code usage in vets-website
- [x] 2. Turn off the feature flipper in all Flipper Admin environments
- [x] 3. Remove `show_expandable_vamc_alert` from vets-api
- [x] 4. Once the vets-api PR has been merged, notify Platform that the feature flipper should be removed from the flipper dashboards in staging and production. ([example](https://dsva.slack.com/archives/CBU0KDSB1/p1725555324327549))
```

**Comment by randimays** [comment]
Flipper is removed from all code and the flipper dashboards in all environments. Closing as complete.
