### ISSUE TITLE
Update Drupal GraphQL module to version 4.x

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#11625]
### User Story or Problem Statement

As a CMS, I need all my packages to be on up-to-date & supported versions so I can be sure to get security and bug fixes.

### Affected users and stakeholders

* Developers of CMS teams

## Assumptions
* All entities in the CMS must have schema and data producers created for them, as outlined in the GraphQL 4.x documentation: https://drupal-graphql.gitbook.io/graphql/
* No changes should be made to queries and templates currently in content build
  * A related assumption: the schema and data producers must output data in exactly the same format as GraphQL 3.x currently does
  * Our reasoning is, requiring changes to both content-build and va.gov-cms to accommodate any data structure changes doubles the opportunity for defects

## Acceptance Criteria
- [ ] Drupal GraphQL and its submodules are updated to version 4.x
- [ ] A runbook for creating schema and data producers is established to direct engineers to migrate and then maintain the CMS on GraphQL 4.x
- [ ] Every GraphQL query currently made use has schema and data producers created to handle those queries
  - [ ] Every entity type must be covered
- [ ] Testing reveals no difference in data structure returned by the CMS when using GraphQL 4.x.
- [ ] Testing reveals no difference in the HTML output when querying the CMS via GraphQL 4.x

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [x] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
