### ISSUE TITLE
[EPIC] FE Lovell Testing

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11650]
### User Story or Problem Statement

As a FE developer I want to know if  a change I made to the codebase broke Lovell.

As maintainer of the Lovell ecosystem I want to be alerted if a change in the CMS data broke something about Lovell,

### Affected users and stakeholders
* Developers of CMS and FE teams

<link to any existing research or data supporting this>

### Hypothesis

Testing on Lovell should prevent platastrophy

## Acceptance Criteria

- [ ] Fragile parts of the Lovell FE are covered by tests.

### Change management triage

The change represented by this user story will:
- [x] Noticeable engineering improvements in predictability.
- [x] Confidence
  
## Design principles
- Due to the nature of testing the FE, content will need to be published.
- Failing test should prevent merge
- Tests should be well named so it is clear what they are doing.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
All issues are complete
