### ISSUE TITLE
Sprint 72 - Facilities | Nov 21 - Dec 04

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11666]
<details><summary>Quarterly Initiatives</summary>

Major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9655 Lovell 
- #9659 VBA MVP
- #1392 Banners 

**Blocked until LH team moves forward**
- #10798  Lighthouse v1
</details>

<details><summary>OOO</summary>

Tu 11/24 = 🦃 Thanksgiving day (US)

Who | When | Backup 
----- | ------ | ------- 
Christian | 11/23 | Jay
Blake | 11/25 |
Dawn | 11/25  |
David S | 11/25 |

</details>

🥅   — Sprint goals (pending Sprint planning)

## Facility COVID status post-launch
- [ ] #11361 COVID status front end 
- [ ] #11484 Current Covid-19 safety guidelines not working on php8.1

## Facility Locator

**PM** 

## VBA Facilities
**PM**

**Design**
- [ ] #10510 Update VBA MVP after content audit 
- [ ] 🥅  #11209 Recruit PCT

**Engineering**
- [ ] #11516 Display Service name and description 

### Banners

**PM**
- [ ] #11434  🥅
- [ ] #11479 Recommendations from Banner audit  
- [ ] #11489 Banner CM (removed S72 label - discuss 11/22)

### Lovell #9655

**Engineering** 
																															 
																						 
Punchlist
 - [ ] #11651 SPIKE Identify the Fragile bits of the Lovell FE

**Design**

**PM** 
- [ ] #9967 Lovell CMS collab cycle 
- [ ] #11605 Prep for Lovell training
- [ ] #10027 Create Lovell KB articles 

## Accessibility 
@maxx1128 

## Vet Centers
- [ ] #11519 Make Vet Center node:view services listing text the same as the front-end
## General Frontend

- [ ] Create individual tickets per Flipper 

## Lighthouse / Facility API data
- [ ]  #11634 Next step with Mental Health number with VHADM

## Blocked
<details><summary>Blocked by V1 release</summary>
The following Lighthouse issues are dependent on the release of Lighthouse V1

- [ ] #8017 Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
- [ ] #4411 Push CAP data 
</details>
