### ISSUE TITLE
FE display of Veteran satisfaction with wait time 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11709]
_This ticket has been updated to reflect the extensive history from the comments below_

## Background
Lighthouse reported concerns from field editors about inaccuracies in reporting Veteran Satisfaction scores. The concern is that the "Urgent care appointments" label could lead Veterans to misunderstand that urgent care (using the formal specialty definition) is available at the location when it is not. The language is intended to represent satisfaction with the availability of same day/urgent need appointments for primary care and specialty care services. 

<details>
<summary> More background here </summary>
Excerpt from [slack thread](https://dsva.slack.com/archives/CJ162GDDJ/p1664207051125879):

> Can confirm what [@Joshua Jennings](https://dsva.slack.com/team/UD6M316N5 said. There is no Urgent Care service reported for that facility but there is Primary Care. Satisfaction scores (as shown in the above image) refer to the facility as a whole, not to particular services. The four categories of satisfaction scores are:
> primary_care_urgent
> primary_care_routine
> specialty_care_urgent
> specialty_care_routine
> This facility has both forms of the primary care classifications (urgent and routine). This does not indicate that the facility has urgent care.
> From a data point of view, this is all correct. I agree that the presentation can be confusing. May need to engage with the front end team to either tweak their presentation of this data so it is more clear what is being represented or to add clarity to the editor pages/knowledge base articles.
</details>

The display also has heading level defects which should also be addressed in this issue. 

Veteran Satisfaction scores are reported at the facility level and appear at the bottom of a facility page, between the service accordions and the "Get updates" box. This language is hard coded in the front end. The data is provided by Access to care. 

Recommended language from CAIA has been approved by VHA DM and IVC. 

A related issue on the display of wait times within service accordions will be addressed in #13853

<details>
<summary> Screen shot of current experience </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/9fc3d65d-b54b-4ed2-a2c5-a8857ab2e457)

</details>

This appears at the bottom of VAMC Facility pages, e.g. https://www.va.gov/augusta-health-care/locations/aiken-va-clinic/

## Tasks

- [ ] Replace "Urgent care appointments" label with "Appointments for urgent needs"
- [ ] Replace "Routine care appointments" label with "Appointments for routine care"
- [ ] Update headings and content to establish the following headings (and styling as appropriate) as below (Currently the H4s listed below are just `p` tags)
> H2. Veteran satisfaction with appointment wait times at this location
> H3. Appointments for urgent needs
> H4. Primary care
> H4. Specialty care
> H3. Appointments for routine care
> H4. Primary care
> H4. Specialty care

### AC 
- [x] Current behavior is discussed with Content team and SMEs - new label/content is defined
- [x] Confirm language with VHA - DM
- [x] Labels are updated with approved language
- [x] Headings follow a logical order
- [x] Styling is consistent with design system
- [x] Accessibility check
- [x] Design check for line-wrapping with @thejordanwood 
- [ ] PM/PO review

**Comment by dsinla** [comment]
How to distinguish between primary care urgent appointments - without referring to "urgent care" in a way that can confuse Veterans.

**Comment by dsinla** [comment]
This is the wording on a facility's https://www.accesstocare.va.gov/FacilityPerformanceData/FacilityData?stationNumber=691

Can we reproduce this verbiage? 

![image](https://user-images.githubusercontent.com/62269210/204571503-1d7036f3-a214-4526-9761-537aac840e2d.png)

**Comment by dsinla** [comment]
@dsinla to bring to Sitewide Content

**Comment by JayDarnell** [comment]
@davidconlon @dsinla here is the specific subsection of the facility information within lighthouse for these values:

```
"satisfaction": {
                    "health": {
                        "primary_care_urgent": 0.7200000286102295,
                        "primary_care_routine": 0.8600000143051147
                    },
                    "effective_date": "2022-06-28"
                },
```

**Comment by Dottisea** [comment]
Dotti to follow up w Dave C re: verbiage

**Comment by Dottisea** [comment]
Reached out to Beth Potts for update on whether her team should be doing this work:
https://dsva.slack.com/archives/C01K37HRUAH/p1678301357782579

**Comment by davidconlon** [comment]
@Dottisea I'm confused about the slack thread you link to. It looks like we were asking about Mobile AL Vet Center, not the Primary/urgent care question.

Can you, instead, link to the content request ticket for Primary/Urgent Care?

**Comment by Dottisea** [comment]
Correct link to content request is:
https://github.com/department-of-veterans-affairs/va.gov-team/issues/55227

**Comment by Dottisea** [comment]
@kmariepat-cityfriends  - 
Received this today form Danielle Thiery: Hi @Dottisea. From what I'm understanding the issue here is that the presentation is referring to "urgent care," which is a specific type of care, rather than appointments for urgent needs.

I would recommend changing the headers to these:

Appointments for urgent needs

Appointments for routine care

Let us know if you have questions or need more guidance on this request. Thanks!

**Comment by davidconlon** [comment]
@kmariepat-cityfriends I think we likely want some clarifying guidance/confirmation so that we have sustainability for labelling all four variables. I'm thinking that we get a review from content on:
- "primary_care_urgent" -> "Primary care appointments for urgent needs"
- "primary_care_routine" -> "Primary care appointments for routine care" 
- "specialty_care_urgent" -> "Specialty care appointments for urgent needs"
-  "specialty_care_routine" -> "Specialty care appointments for routine care"

Following on that we may want to review with @laflannery what a good hierarchical structure might be for this content on the front-end. 

I'm thinking we may want to consider:
H2. Veteran satisfaction with appointment wait times at this location
H3. Primary care
H4. Primary care appointments for urgent needs
H4. Primary care appointments for routine care
H3. Specialty care
H4. Specialty care appointments for urgent needs
H4. Specialty care appointments for routine care
Personally, I'm struggling a bit with "what qualifies as 'urgent need' vs. 'urgent care'" but maybe that's not critical.

**Comment by davidconlon** [comment]
Also, not a defect.

**Comment by laflannery** [comment]
I found a page that was showing the current state with both specialty care and primary care: https://www.va.gov/tuscaloosa-health-care/locations/tuscaloosa-va-medical-center/

With this current state in mind, and also to try and limit the repetition of "Primary Care" and "Speciality Care" in the heading structure, we could use the proposed content changes above to alter the headings to look like this:
![image](https://user-images.githubusercontent.com/106678594/235965571-54896ad3-edbd-4bee-ab4c-1b8ee34635a8.png)

The heading structure would be:
H2. Veteran satisfaction with appointment wait times at this location
H3. Appointments for urgent needs
H4. Primary care
H4. Specialty care
H3. Appointments for routine care
H4. Primary care
H4. Specialty care

It also may be a good idea to add additional content in the text below the H3s, just to make this more clear and unique - this can also be seen in the above screenshot.

**Comment by mmiddaugh** [comment]
Made contact with POC for Access to Care and will be getting more information about how this data is derived and the definitions for the types of appointments - let's hold on this until we know more

**Comment by jilladams** [comment]
Slack thread for follow ups to Elizabeth Watson: https://dsva.slack.com/archives/CJ162GDDJ/p1687808842570679?thread_ts=1664211493.324099&cid=CJ162GDDJ

**Comment by mmiddaugh** [comment]
Content input for this issue was provided in Content request from VFS Sitewide Facilities [#55227](https://github.com/department-of-veterans-affairs/va.gov-team/issues/55227). 
From what I'm understanding from ticket #11709, the issue here is that the presentation is referring to "urgent care," which is a specific type of care, rather than appointments for urgent needs.
I would recommend changing the headers to these:

- Appointments for urgent needs
- Appointments for routine care

We will get approval from VHA DM on this on 7/10

**Comment by mmiddaugh** [comment]
Blocked pending VHA DM input

**Comment by mmiddaugh** [comment]
Email from Justin (VHA DM) today: IVC approved the suggested language: 
Appointments for urgent needs 
Appointments for routine care

**Comment by jilladams** [comment]
@eselkin we refined this today and it seems fairly straightforward / is prioritized for you to pick up whenever you're back online!

**Comment by eselkin** [comment]
Just curious what the accessibility checks should be? axe? Anything else? Mac screen reader?

**Comment by laflannery** [comment]
@eselkin When there is an AC for an accessibility check or accessibility review, it generally means to send it to me to double check everything and confirm. However, running axe on issues prior to my review to confirm no other automatic issues have been introduced would be excellent!

**Comment by eselkin** [comment]
@laflannery I ran axe and it came up with issues that I think might be in some other ticket (about repeated id names, but nothing related to my tags/changes). I went over it also with the Mac screen reader and it seemed to announce the sections appropriately. It passed a dev PR review. How would you like to be pulled in to view the changes?

https://github.com/department-of-veterans-affairs/vets-website/pull/25229

**Comment by laflannery** [comment]
@eselkin tagging me in the ticket is absolutely fine to get me to review something - as long as you link the PR so I can easily get to it like you did here. You can also tag me directly in the PR or just ping me in Slack(Randi and Chris often do this!). Whichever option is easiest for you, works for me.

Regarding this ticket -

- Approved from an accessibility standpoint 
- However, I would recommend getting Jordon's (@thejordanwood) design eye on it as well now that Specialty care is wrapping to 2 lines, we might want to make some small adjustments to avoid that but she can make that call

**Comment by mmiddaugh** [comment]
@jilladams @xiongjaneg

**Comment by jilladams** [comment]
Added an AC re: design check with @thejordanwood (who is also typically fine with Github @ mentions or Slack pings, or both, to get her eyes on).

**Comment by thejordanwood** [comment]
We gave Speciality care an h5 styling with normal weight text while keeping an h4 tag. Specialty care is now on one line. This is approved from a design standpoint.

**Comment by jilladams** [comment]
@eselkin in general we have a strong preference for keeping tickets open til they're verified in prod after deploy, because of a history of our environments being strange, and Prod not always reliably exactly mimicking local / Staging envs. 

You can see the state of your deploy here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/frontend-support-dashboard/.  Once it's in prod, if you verify it there, pls just add a note to ticket and then can close. Or, if you prefer 2nd eyes, can ping me / @xiongjaneg to help out as possible.

**Comment by eselkin** [comment]
On prod 
<img width="1112" alt="Screenshot 2023-08-17 at 3 10 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5606931/87225f02-1930-4e7f-ade1-15fdcf491290">
