### ISSUE TITLE
Workflow UX on Homepage blocks

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11779]
## User Story or Problem Statement

As an editor of homepage blocks I would like the workflow display I see on blocks to more closely match what I see on all the other node content types so that I can fall back on familiar patterns.

This could really benefit from a UX review, but if that is not possible due to human capacity it would be good to use the existing patterns.
Her is an example from a node.
![image](https://user-images.githubusercontent.com/5752113/205208209-a71c2e34-68ee-4744-b4d9-c1b82a1fad45.png)

Blocks do not have flags, so no need to include those, and they do not have a right sidebar, so it makes sense to move the section field into the workflow settings.
There are a lot of variations on this layout across the various blocks.  I (swirt) think the one that comes the closest is the pattern on alert blocks
![image](https://user-images.githubusercontent.com/5752113/205208595-75e4cd59-a4b2-4e0e-9d7e-c69951bccb95.png)
Though it has the wrong heading on the field group and is missing several other nicceties from the node version.

The home page block version is way off from either pattern and is non-optimal

![image](https://user-images.githubusercontent.com/5752113/205208803-53ed11a8-1fe9-49ed-958c-3ed7945aaa1f.png)

## Acceptance Criteria
- [ ] Apply design pattern from nodes workflow section to the two homepage block edit. unless UX provides a better one.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@dsasser I think you went ahead and updated this, and it could close, correct?

**Comment by dsasser** [comment]
@jilladams yes this was fixed as part of homepage hardening.
