### ISSUE TITLE
Sprint 73 - Facilities | Dec 05- Dec 18

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#11792]
<details><summary>Quarterly Initiatives</summary>

Major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9655 Lovell 
- #9659 VBA MVP
- #1392 Banners 

**Blocked until LH team moves forward**
- #10798  Lighthouse v1
</details>

<details><summary>OOO</summary>

Who | When | Backup 
----- | ------ | ------- 
Jay | 12/05 | Christian/Swirt 
Dave C | 12/9,12,16

</details>

🥅   — Sprint goals (pending Sprint planning)

## Facility COVID status post-launch
- [x] #11484 Current Covid-19 safety guidelines not working on php8.1 🥅
- [ ] #11794 
Flesh this out more

## Lighthouse / Facility API data

**DEV** 
- [ ] #11627 Determine Provider Core Training flag present 

## VBA Facilities
**PM**

**Design**
- [x] #11453  DSN: Conduct VBA PCT research 🥅
- [x] #11452 DSN: VBA PCT research synthesis 

**Engineering**

### Banners

**PM**

- [x] #11760 PM: Initial banner recommendations

## Vet Centers
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11519

### Lovell 

**Engineering** 
Punchlist
 - [ ] #11651 SPIKE Identify the Fragile bits of the Lovell FE
 - [x] #11557   🥅 
 - [x] #11691 🥅 

- [x] DS>> Schedule 60 min MOB meeting - Repurpose VBA meeting 

**Design**

**PM** 
- [x] #11793 PM Prep for Lovell Training 
- [x] #9967 Lovell CMS collab cycle 
- [ ] Create KB for Listing page behavior 
David create "Launch to dual state" issues blocked by all supporting activities 
DS>> Create ticket **Submit for Platform Staging Review** 
What about Lovell Platform Collab Cycle STAGING review ? Feature complete <- target next Sprint ?  

## Accessibility 
@maxx1128 
- [ ] #11699 No visible focus on Operating Status 

## FLIPPERS?
Merge two tickets that are ready to be retired 

## Blocked
<details><summary>Blocked by V1 release</summary>
The following Lighthouse issues are dependent on the release of Lighthouse V1

- [ ] #8017 Push service data
- [ ] #4769 Push more facility data
- [ ] #4410 Discovery CAP data 
- [ ] #4411 Push CAP data 
</details>
