### ISSUE TITLE
Create Dev|Test Environment for Content Build Github Actions

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11801]
## Background
When building or testing new Github action workflows, all testing and development currently takes place via the production workflows. There is no testing mechanism in place.

### User Story or Problem Statement

In order to optimize Content Build, we need an environment to test new workflows for Github Actions.

### Affected users and stakeholders

- Platform CMS Team
- Platform Infrastructure
- Sitewide CMS
- Any users of Content Build
- Frontend Team

### Hypothesis

By creating a test|dev Github action repo, Content Build workflow issues will be resolved much faster.

## Assumptions
- Content Build error rate will drop
- Improving Content Build will become easier
- Merging changes will become less stressful
- Improved development speeds
- Happier engineers

## Acceptance Criteria
- [ ] Test Content Build Repo Created
- [ ] Platform CMS Team has ADMIN control of New Content Build Repo
- [ ] New Content Build Repo Auto-Updates from Prod Content Build Repo
- [ ] New Repo uses mirror of prod infrastructure
- [ ] **Want, not Need:** Option to utilize full & partial content builds (Example: 10% or 100% of content)

**Comment by TheBoatyMcBoatFace** [comment]
To-Do: Determine where epic lives. Refined epics not in progress

**Comment by EWashb** [comment]
Not within scope
