### ISSUE TITLE
Homepage news promo block: 508: Add screen reader context to CTA on Redesigned homepage 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11823]
## Issue description
The CTA to "Read the full article" under the Pathfinder heading doesn't specify the article. 
This isn't a high severity defect as the information is available contextually, but getting it adds an extra step for a user tapping through the screen. 

It isn't practical to add the specific context into the CTA as this might be difficult to maintain from a CMS editorial perspective, plus this content is expected to change. Using `described by` will support this user while keeping the CTA flexible and accessible despite content changes. 

## Tasks
- [x] Check with Laura F about proper implementation
- [ ] A &lt;span&gt; is added with class="sr-only" that is only available to screen readers (visual users will not see this additional text)
- [ ] This span should dynamically pull in the text of the H3 title above
- [ ] There should all be a hardcoded "about" so the full link would be announced as "Read the full article ABOUT [title of the article]"

## Acceptance criteria 
- [ ] Users who tab to the "Read more link" hear the title of the article or enough information to identify it
- [ ] Accessibility review required

**Comment by mmiddaugh** [comment]
@AngelaFowler82 will you please doublecheck my details and acceptance criteria, editing as needed? Thank you

**Comment by AngelaFowler82** [comment]
Acceptance criteria: users who tab to the read more link hear the title of the article or enough information to identify it.

**Comment by laflannery** [comment]
@apisandipas I would rather we use the same SR-only implementation we are using in other parts of the site to associate titles to links, we do this on the Facility Locator:
![image](https://user-images.githubusercontent.com/106678594/210445949-cfd1e4b3-22c2-4030-baee-e5058ca3832e.png)

I believe this would be more complex than the `aria-describedby` solution so please let me know if it's not feasible

- A `<span>` is added with `class="sr-only"` that is only available to screen readers (visual users will not see this additional text)
- This span should dynamically pull in the text of the H3 title above
- There should all be a hardcoded "about" so the full link would be announced as "Read the full article ABOUT [title of the article]"

The reasons I want to go in this direction are:

- If you use aria-describedby, "visited" will interrupt the announcement of the link if it is a visited link (i.e. "Read the full article, visited, [article title]"
- Also, aria-describedby does not update the text of the link so the link list available to a SR user, this will still just say "Read the full article", the context we are adding has not been added here.
