### ISSUE TITLE
Update background colors in Staging implementation of redesigned VA.gov homepage

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#11831]
## Issue description
**Round 2 version of Sketch**
- Menu of links has white background
- Search block has light blue background

**Round 3 version of Sketch**
- Popular on VA.gov menu of links has light blue background
- Search block has white background

![image](https://user-images.githubusercontent.com/55411834/206761332-527f2a1c-f8a5-429b-b3ca-c8a8b55e0926.png)

Ryan confirmed via email that this switch is intentional and designed to add a little balance. 

## Tasks
- [ ] Update background colors for Search and menu of links blocks

## Acceptance criteria
In both mobile and desktop, 
- [ ] Search block has white background
- [ ] Menu of links has light blue background

**Comment by jtmst** [comment]
staging seems to match this description, is this already done? 

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/61624970/206727314-d30a20e4-0096-4078-bd1e-bd0076b95d6e.png">

**Comment by mmiddaugh** [comment]
Corrected description above - my apologies
