### ISSUE TITLE
Add test coverage for locked down facility api data fields

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#11891]
## User Story or Problem Statement

As a developer on the Facilities product, I want a test(s) to fail if  the facility api data fields are ever editable by an editor.

## Acceptance Criteria
- [x] Testing as a content admin or facility editor
- [x] Facility api data on the following content types should be locked (uneditable)
   - [x] health_care_local_facility
   - [x] vet_center
   - [x] vet_center_mobile_vet_center
   - [x] vet_center_outstation
   - [x] vba_facility
   - [x] nca_facility

## Implementation steps
Cypress.  May need a step definition for looking for disabled fields

**Comment by swirtSJW** [comment]
This gap in coverage was revealed by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11890

**Comment by omahane** [comment]
@swirtSJW So should we be locking down all fields that are in the Facilities API?
Should we be locking them down for all facilities?
Should we show the form elements for editors at all?

Right now, we're not showing the node:view of the facilities API data for NCA or VBA. Should we be doing so?
If so, we should do that before writing these tests.

**Comment by omahane** [comment]
Talked to Steve. We'll make NCA and VBA like the others:
![Screen Shot 2023-05-15 at 4 17 08 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/cc9f4b2b-47fb-47c6-ac1e-1dce36b19383)

And make the cypress tests expect that.

**Comment by omahane** [comment]
@swirtSJW The PR is ready to go, but I just had a thought: do you want tests for content_admin distinct from editor?

**Comment by omahane** [comment]
Never mind, I made them separate scenarios.
