### ISSUE TITLE
Streamline CMS Analytics & Monitoring

### ISSUE THREAD

**Issue by TheBoatyMcBoatFace** [department-of-veterans-affairs/va.gov-cms#11928]
## Background
The Platform CMS Team is responsible for managing and overseeing a complex array of systems and infrastructure. Over time, the team has added new layers and tools, which has made it difficult to maintain a clear, comprehensive view of their operations. As a result, they have struggled to keep track of the various variables, metrics, and insights that are important to their work. This complexity has made it challenging for the team to effectively manage their systems and infrastructure.

### User Story
When the Platform CMS Team needs a comprehensive overview of their area of responsibility, they currently have to check multiple platforms and perform calculations on the spot. This process is time-consuming and hinders their ability to quickly gain insight into their operations. As a result, it has negatively impacted the team's developer experience.

### Affected users and stakeholders

* Platform CMS Team
* Sitewide Crew & Platform Crew needing infrastructure & system insight
* Platform CMS Key Stakeholders

### Hypothesis

We believe that by consolidating the metrics that are currently spread across multiple platforms into a single, streamlined view, the Platform CMS Team will gain a better understanding of the overall status of their systems and infrastructure. This will enable them to more effectively collaborate with other teams within DSVA and make informed decisions about their operations. By streamlining their access to key insights, we believe that the team will be able to improve their developer experience and better manage their area of responsibility.

## Assumptions
* All necessary events/logs/data can be imported into Domo
* No Domo limitations exist
* DevOps team will still utilize platforms such as Sentry & Datadog to trouble shoot or deep-dive into issues

## Acceptance Criteria
- [ ] Developer-Friendly Overview of Platform CMS Operations
- [ ] Monitoring and logs are accessible in current platforms
- [ ] Source of Truth for definitions & variables
- [ ] Defined naming convention for datasets & sources
- [ ] Streamlined Insight and Analysis of Platform CMS Team area of responsibility

**Comment by EWashb** [comment]
Could be worth scoping this ticket more closely to our infrastructure so that it doesn't appear to compete with our other Google Analytics work within the CMS to track editorial experiences.

**Comment by BerniXiongA6** [comment]
Closing this epic since all tasks are done! @maortiz-27-80 @EWashb @ndouglas
