### ISSUE TITLE
Sprint 74 - Public Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#11942]
### 1. Harden homepage for prod - 15+ 2 TBD FE points for 9 open issues; 3+ Drupal points

**Page itself:**
  - [ ] department-of-veterans-affairs/va.gov-cms#11771 (1)
  - [ ] department-of-veterans-affairs/va.gov-cms#11652 (2) - (in PR), merge asap for deploy during week of 12/19 
  - [ ] department-of-veterans-affairs/va.gov-cms#11286 (3) 
  - [ ] (stretch?; AdHoc may have done?) department-of-veterans-affairs/va.gov-cms#11954 (8) 
  - [ ] #12019: engage CMS collab cycle for "Create account" block drupalization
    - ACs: come up with technical design; determine permissions; identify design considerations; create artifact for CMS team's review
  - [ ] (stretch) #11692 
  * **Analytics:**
    - [ ] Tracking Analytics Team dependency in #11965 
    - [ ] GA fix for existing homepage -- Analytics team GTM work required
    - [ ] GA fix for new homepage -- Analytics team GTM work required

**Modal:**
  - [x] department-of-veterans-affairs/va.gov-cms#11535 () 🥅 
  - [ ] department-of-veterans-affairs/va.gov-cms#11975 (1)  
   - [ ] department-of-veterans-affairs/va.gov-cms#11978 () 
   - [ ] #12008 ()

**Drupal**
  - [ ] department-of-veterans-affairs/va.gov-cms#11370 (3) - Dave co-signed going a more holistic route in Drupal. Need to craft the final plan still.
  - [ ] department-of-veterans-affairs/va.gov-cms#11968 () 

**Post-MVP, not launch blocking (and not in Sprint)**
  - department-of-veterans-affairs/va.gov-cms#11569 ()  
  - department-of-veterans-affairs/va.gov-cms#11568 (2)
  - department-of-veterans-affairs/va.gov-cms#11586 ()

### 2. PDF Certificate Expiration Alert - 1-2 FE points
- [ ] (do we do with 1 form still outstanding?) department-of-veterans-affairs/va.gov-cms#11616 (2)
 
### 3. Income Limits web app - 8 Design points
- [ ] (prototype design) department-of-veterans-affairs/va.gov-cms#11098 (8)
- [ ] department-of-veterans-affairs/va.gov-cms#11929 () 

### 4. Chatbot 
- No action yet identified

### 5. Benefit Content Model Hardening
- Meeting w/Danielle set for Sprint 74

### 6. Cerner API deprecation support - 3-5 FE points? 
- [ ] department-of-veterans-affairs/va.gov-cms#9078 () 
- [ ] department-of-veterans-affairs/va.gov-cms#9307 () 

###  Other 508
- department-of-veterans-affairs/va.gov-cms#11205 ()  - tabled for deeper holistic approach later in Q4 / early Q1

---

### Redirects - 7 FE points
- [X] department-of-veterans-affairs/va.gov-cms#11662 () 
- [X] department-of-veterans-affairs/va.gov-cms#10972 (2)(pending unblocking by stakeholders)
- [X] department-of-veterans-affairs/va.gov-cms#11487 ()  
- [ ] department-of-veterans-affairs/va.gov-cms#11745  () 
- [ ] department-of-veterans-affairs/va.gov-cms#11918  (1) 
- [ ] department-of-veterans-affairs/va.gov-cms#11903  (2) 
- [ ] department-of-veterans-affairs/va.gov-cms#11892 (1) 
- [ ] department-of-veterans-affairs/va.gov-cms#11377 (1)
- [ ] #11999 (2)

### Tech debt
- [x] (due Dec 21) department-of-veterans-affairs/va.gov-cms#11358 

### Content support
- [X] department-of-veterans-affairs/va.gov-team#50880  (2) - have proposed moving to GovCIO board, since they're blocking merge
- [ ] Update footer link for new 508 page, by Fri 12/23 if possible: #12012 (2) 

### Drupalize footer - 8 FE points
- [ ] (stretch) department-of-veterans-affairs/va.gov-cms#11482 (8)

### Injected header post-mortem
- Actions waiting on conclusion of post-mortem

## TOTALS: 
FE: 15+, 2, 5, 7, 8 = 37+ FE points
Drupal: 3+ points
Design: 8 points

**Comment by laflannery** [comment]
@jilladams I updated the description because the Drupal Footer also needs to be updated.  I believe this footer is manageable so if you would prefer I do this on my own let me know, I just would like it done the same time this goes live which is why I included it here, so I can track it.

**Comment by wesrowe** [comment]
@laflannery, where did you "update the description"? And... seeing that you're talking about the Drupal footer, is your comment related to #12012, updating the accessibility link?

**Comment by jilladams** [comment]
@wesrowe confirming yes ^ , is re: #12012
