### ISSUE TITLE
Facilities Refinement - 12/15/2022

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11963]
# Refinement 12/15/2022

## COVID Status

- [ ] #10410 - @davidmpickett will look for correct template
- [ ] #10708 - @davidmpickett will tidy

## Lovell

- [x] #11941 - @omahane will refine
- [x] #11832 - @JayDarnell will refine
- [x] #11940 - @ryguyk will refine

## Runbooks

- [ ] #10845 - converted to epic - @davidmpickett will tidy first ticket

**Comment by davidmpickett** [comment]
@omahane @ryguyk @JayDarnell - I just updated this to reflect our discussion in Refinement. Please refine your assigned tickets before sprint planning on Monday. Let @dawnpruitt & I know if you have any questions
