### ISSUE TITLE
Sprint 74 Plan - Facilities

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#11983]
**These are tentative tasks for Sprint 74 pending review.**

## Lovell (#9656) 🎯🎯🎯

**Dev work**
- [x] #11967 🎯
- [ ] #11980 🎯
- [x] #12011 🎯
- [x] #11940
- [x] #11995 
- [x] #11996
- [x] #11989 
- [ ] Manual QA for Lovell

**PM Work**
- [x] #11936 
- [ ] PM: Help Desk Collaboration pre-launch
- [ ] PM: Create Launch review
- [ ] Creation Post-launch Story for after launch tasks/stories

## VBA Regional Office MVP (#9659) 🎯

- [x] #11454

 ## Misc Facility Updates
- [ ] #12000 [Blocked - requires facility services from editors]
- [ ] #11464 [Blocked until Jan 15]
- [ ] #11231 [Ready but blocked]
- [ ] #11952 [Ready but blocked]
- [ ] #11931 [Ready but blocked]

## Pulled into the Sprint
- [x] #12023
 
[edited by @JQuaggles  12/28 at 10:23 EST]

**Comment by JQuaggles** [comment]
I am updating the tentative priorities for Sprint 74.

**Comment by laflannery** [comment]
@davidmpickett I saw you tagged me and just wanted to let you know that I haven't seen or done anything yet for the Lovell pages so do please include me, Thanks!

**Comment by JQuaggles** [comment]
Hi @laflannery, that was me :) 
If you're around this week, will definitely reach out about reviewing Lovell!

**Comment by JayDarnell** [comment]
All misc facility updates are now blocked either waiting for a redirect to be deployed to production, for facility health services to be added, or for a specific go-live date.

**Comment by EWashb** [comment]
Want to move this into the to-do pipeline @JQuaggles?
