### ISSUE TITLE
FE: Rework "Other nearby VA locations" to use CMS data and liquid templates

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12005]
## User Story or Problem Statement

Relates to #11829 
See #12004 for more details regarding the CMS changes this issue builds upon.

## Acceptance Criteria
- [ ] The front end uses graphQL queries and liquid templates to display the new entity reference Other VA Locations field

## Implementation steps

Liquid template: (content-build) src/site/layouts/locations_listing.drupal.liquid

Needs more details... 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
Moved these details into [CONSIDER] Revisit logic governing "Other nearby VA locations" on VAMC pages #13896 and will close this as a duplicate
