### ISSUE TITLE
Audit the Lighthouse Facilities CSV 

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12016]
s## Description
The [Lighthouse CSV](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) should reflect the currently published facilities.

<details>
<summary>List of VHA .asp pages</summary>

```
vha_402HL,https://www.maine.va.gov/locations/Mobile_Medical_Unit.asp
vha_442HK,https://www.cheyenne.va.gov/locations/Wheatland_VA_Mobile_Clinic.asp
vha_442QB,https://www.cheyenne.va.gov/locations/Torrington_VA_Mobile_Clinic.asp
vha_442QD,https://www.cheyenne.va.gov/locations/Laramie.asp
vha_508QH,https://www.atlanta.va.gov/locations/South_Fulton_VA_Clinic.asp
vha_540HK,https://www.clarksburg.va.gov/locations/Rural_Mobile_Clinic.asp
vha_554A4,https://www.denver.va.gov/locations/Pueblo_VA_Community_Living_Center.asp
vha_554BU,https://www.denver.va.gov/locations/Valor_Point_VA_Domiciliary.asp
vha_575QC,https://www.grandjunction.va.gov/locations/Grand_Junction_VA_Mobile_Clinic.asp
vha_589HK,https://www.kansascity.va.gov/locations/MobileMedUnit.asp
vha_663HK,https://www.pugetsound.va.gov/locations/Mobile_Medical_Unit.asp
vha_664BV,https://www.sandiego.va.gov/locations/Aspire_Center.asp
vha_673BV,https://www.tampa.va.gov/locations/Tampa_VA_Domiciliary.asp
```

</summary>
</details>

## Tasks
- [x] Identify .ASP pages that return a 404 
- [x] Identify .ASP pages that redirect to another page

## Final report
Christian checked them on January 3, 2024. All of the VHA .asp pages redirect to their respective VAMC health system in the modernized Drupal-sourced va.gov site. No further action is needed.

## Acceptance Criteria
- [x] Provide a report to Lighthouse of the current state of those URLs and what they resolve to
- [x] Identify which URLs may need to be discussed with VHA Digital Media for resolution

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by Dottisea** [comment]
Lighthouse is in code freeze and so we are blocked till that ends

**Comment by jilladams** [comment]
Lighthouse verified in last sync (7/17) that the CSV cannot publish: https://trello.com/c/rAvktoKO/26-is-there-a-way-to-merge-csv-changes-in-while-other-work-is-being-tested

Doesn’t work in current pipeline setup. As soon as anything is merged to master, it’s in the pipe and can’t ship without shipping everything else merged ahead of it (e.g. Service changes that are not prod-ready).

CMS team made redirects for affected Facilities, and will revert those after CSV merge.

@omahane I think we could call this a dupe of the Revert ticket, and verify the CSV when we get the greenlight and revert? If you agree, go ahead and close this.

**Comment by omahane** [comment]
This is different than the issue we were having with the CSV not getting merged in a timely manner. It's that there are 13 (at this time) .asp pages (outside of the 173 NCA pages) that should be checked to make sure that they are live and correct urls, rather than 404s or incorrectly redirecting to another facility.

**Comment by jilladams** [comment]
Ah, ok! Since LH is no longer in code freeze, marking this unblocked, and FYI @xiongjaneg this is a candidate for upcoming refinements / sprints.

**Comment by omahane** [comment]
I updated the ticket to add the VHA .asp pages, 14 in all. The rest of the ASP pages (173) are NCA.

**Comment by omahane** [comment]
@xiongjaneg @jilladams (cc: @swirtSJW) I added a final report to the issue description. This can be closed with no further action needed.
