### ISSUE TITLE
[EPIC] Discharge Upgrade Wizard: modernize & convert to Subtask pattern

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12043]
# See Project Plan [here](https://agilesix.slack.com/lists/T46Q2J7QV/F07MXUQSHRS?view_id=View07NJ8S8JJU)

## See this other '[Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19592)' to find more tickets associated to this project 
- (GHP only allows 50 associated tickets per epic, so I had to move some)

## Statuses
**[2024-12-13] [Fran]** Releasing Monday, 12/16/2024: All CAIA pre-launch content changes have been addressed; bugs have been fixed; Staging review concluded and the three launch-blocking items completed/approved.
**[2024-9-03] [Michelle]**
  - Still tracking toward move into production by the end of September
  - Final engineering work is queued for Sprint 12, which begins tomorrow
  - QA planning is underway
  - Veteran research plan is in draft
**[2024-07-08] [Fran]** All finished except for the Review screen tickets (see tickets below) and some stakeholder feedback to incorporate.
**[2024-04-01] [Fran]** Chris has completed the first two tickets and is working on the 1st question (ticket 3 of 15). These tickets include the Phase 1 content updates. Fran to create a ticket to implement the text corrections offered via email from Tanekwa, and these will be done after he’s finished with the 15 initial “MVP Phase 1” tickets. 
**[2024-02-22] [Fran]** The V1/V3 Component work has bumped this project; hopefully will be started on 3/13 in Sprint 106.  IA request filed for temporary route 
**[2024-01-22] [Fran]** Tickets have been created by Chris K. and will be prioritized for upcoming sprint(s). 
**[2024-01-16]  [Fran]** Sprint 102 will pull in work breakdown ticket.  
**[2024-01-08]  [Fran]** Tickets for work breakdown for conversion to subtask and Phase 1 content changes are in Next Refinement. 
**[2024-01-04] [Fran]**
  - Ticket created to scope the work it will take to update the DUW to the substack pattern; Chris K and Randi M will then create additional stories.  #16656 
  - Ticket repurposed for Phase 2, which will be comprised of Stakeholder feedback (stakeholders not identified yet). #12801 
**[2023-12-08] [Fran]**
  - This project will consist of two phases for content updates. We were provided updates for Phase 1 this week, and the design ticket will be fleshed out with Katherine's updated provided.
  - Fran has questions out to Dave re; who are stakeholders, and also a content question from Katherine 

**[2023-08-08] [Fran]**
    - Discussed with Dave C. Steps to get this off the ground:
      * Dave: locate stakeholder(s) to validate that existing app is still correct
      * Dave: Verify that Public Websites should own this app, at least during iteration
      * Content team: Validate that content and results meet current standards
      * PW Devs: analyze existing app code and ensure that all possible branches are accounted for in a flow chart or other artifact. ([Existing artifact](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1670355600942/8ebd465060e3c6e404292ab065389458a27160f9?sender=uebde62ceb342c6477fb09406) needs to be replicated at this point.)

## Decision Log
**[2024-09-05] [Fran]** Decision from DUW QA meeting today (Chris/Jordan/Laura/Fran): Chris will implement the new logic wherein if a user clicks Edit for a question on the Review screen, e.g. Year changes their answer, clicks Continue, clicks Back, clicks Back, then forward: the user will see their original edited question again e.g. Year. Chris will have Randi do an engineering pass on the code, and then he will ping Laura/Jordan/Fran to do QA. If any other edge-cases or issues are found, Chris will strip (but save) the Back/Continue button logic and we will go with Option 2 discussed in the meeting yesterday, where: if the user clicks edit on a question on the Review screen, and changes their answer, they will then need to go through all the questions again (although all of their previous answers will have been retained/display as chosen).
**[2024-09-04] [Fran]** Decision from DUW meeting today: If Chris isn't easily able to implement the solution (noted above), then we will decide on one of three options: 1) release an MVP without the Review screen; 2) implement if the user clicks edit on a question on the Review screen, and changes their answer, they will then need to go through all the questions again (although all of their previous answers will have been retained/display as chosen).; 3) ???

## Top-line Description / Goal(s)
The existing discharge upgrade wizard was built in Vets.gov days. It does not use current design or content patterns. It requires a lot of scrolling due to the legacy pattern. We are also unsure if the information within the wizard remains correct.

Based on learnings from the PACT Act wizard, this effort will improve the ability for Veterans to determine their eligibility for a discharge upgrade by re-modernizing the product to align with current VA.gov design and content standards, and convert to a subtask pattern.

[Initiative document](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/initiatives/2024-discharge-upgrade-wizard-subtask/initiative-brief.md)

## Artifacts
_(Links to designs, product brief or initiative, analytics, etc._

- [ Initiative: Discharge Upgrade Wizard: Update to subtask pattern](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/initiatives/2024-discharge-upgrade-wizard-subtask/initiative-brief.md)
- [Mural - DUW Flow](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u71e5a9ded413bfa79dd23932)
- [Mural - Review flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1696352911500/80253b1c7200212cbcbcfb940d2cf4a29fed8417?sender=u71e5a9ded413bfa79dd23932)
- [DUW on Staging](https://staging.va.gov/discharge-upgrade-instructions/introduction)
- [Analytics](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/analytics/Analytics%20-%20Discharge%20Upgrade%20Wizard.md)

## Headlines
**VA stakeholders** - TBD. Stakeholders for product has changed from past.

**OCTO lead** - Dave Conlon

**Is this project tracked to an upcoming event or congressional deadline?** - No

## Details

**Which OCTO team should do this and what is currently on their roadmap?** - Sitewide (Public Websites)

**Which OCTO priority does this work support?** Increase Customer Satisfaction Scores

**What is the user impact and scale of impact?** - 19,000 views/month as of August 2023

**Who would manage this product long term?** - Public Websites

**How much leverage will this create to solve more problems in the future?** -

**How great is the cost of inaction? (e.g., Can it wait? Must it be done by us?)** - 

---

## Background

The wizard pattern has been deprecated by DST in favor of the Subtask pattern. The Discharge Upgrade Wizard needs to be converted to a subtask pattern. Designs for this can be found in [this Sketch file](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e).

### User Story or Problem Statement

As a Veteran, or caregiver of a Veteran, I need the Discharge Upgrade Wizard to be easily understood a navigable SO I can complete it accurately and improve my chances of my discharge upgrade request being approved.

### Affected users and stakeholders
* Veterans and their caregivers
* VA employees who receive and process the Discharge Upgrade Wizard requests/answers.

### Hypothesis

We believe this effort will improve the ability for Veterans to determine their eligibility for a discharge upgrade by re-modernizing the product to align with current VA.gov design and content standards, and convert to a subtask pattern.

## Acceptance Criteria
- [x] Discharge upgrade wizard follows the substack pattern, e.g. one question per page. See this [Sketch ](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e)design.
- [x] The existing logic flow for questions/answers is not degraded/lost.
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [X] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [X] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
Moving this to icebox for now – modernized subtask design is available in design ticket in this epic. We will consider this work in the context of evaluating the whole Public Websites product portfolio for design and tech debt.

**Comment by DanielleThierryUSDSVA** [comment]
**Update 6.3.24:** Expected to ship by end of second quarter.

**Comment by mmiddaugh** [comment]
**Update 7.08.24** 

- Work complete except for updates to Review screen and the incorporation of some stakeholder feedback 
- Planning Veteran research to validate the flow following an edit on the review screen

**Comment by FranECross** [comment]
Some tickets moved from this epic to an organizational epic solely because GH projects limits the number of tickets that can be added as sub-issues to an epic. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19592

**Comment by FranECross** [comment]
Some tickets moved to a new epic just for organization purposes because GH project has a limit on the number of tickets that can be on an epic.

**Comment by mmiddaugh** [comment]
**Update 11.5.2024**

- Usability sessions wrapping up
- Additional content changes expected based on recent DoD action on discharges related to sexual orientation
- Final Collab cycle milestones scheduled

**Comment by mmiddaugh** [comment]
**Update 12.3.2024**
Staging review touchpoint today - addressing launch-blocking QA feedback. Expected to launch by end of year.

**Comment by mmiddaugh** [comment]
**Update 12.16.2024**
this will ship tomorrow, December 17, 2024.
