### ISSUE TITLE
CMS/React content dark launch request: <Sitewide Content and IA>

### ISSUE THREAD

**Issue by RLHecht** [department-of-veterans-affairs/va.gov-cms#12113]
## Description
Use this issue to request dark launch of a CMS page that includes a React widget. 

**Review documentation about the process** prior to submitting your ticket: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#3-publish-a-cms-page-only-to-staging-using-entityqueue-in-order-to-stage-cms--content-build--vets-website-for-viewing-off-of-va-network

The new transfer of entitlement 1990e online form is set to launch in March 2023. We have a static landing page as well as 2 other pages already in production that are connected to this so we would like to be able to look at all of these with the tool in staging as opposed to the separate Drupal previews we normally use.

### Staging/dark launch

* **CMS link to content**: 
http://preview-prod.vfs.va.gov/preview?nodeId=952 This is already on prod, draft
http://preview-prod.vfs.va.gov/preview?nodeId=984 This is already on prod, draft
http://preview-prod.vfs.va.gov/preview?nodeId=44698 This is a brand-new page

* **Target dark launch date**: the authenticated pages are already in staging so would like to add these in as soon as we can. 
* **Is this date flexible?** If not, please explain: 
* **Technical point of contact** for vets-website React code:  n/a, no vets-website code
* **Strategic point of contact** for timing & approval to publish the node to Staging: Randi Hecht

### Production launch
CMS team does not want to get in the habit of having staged nodes that will not publish, so this method should only be used for business cases that have a line of sight on production launch. 

* **Target production launch date:** The actual launch for the tool is currently set for 3/21.
* **What is driving and/or blocking prod launch date?** 1990e online form launch

# For PW use
## Tasks
Please tick the boxes for completed steps as we go, for cross-team visibility.
- N/A - Technical POC has merged vets-website code to main & confirmed deploy to prod
- [x] Add Node ID to [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue)
- [ ] Strategic POC has given approval to publish node to Staging, or has published node
- [ ] Nightly CMS build has run which pushes prod mirror to the staging site, or PW must request an out of band deployment.
- [ ] Content-release has run. 
- [ ] Verify on staging / prod

## Acceptance Criteria
- [ ] Page is verified: Live on Staging
- [ ] Page is **not** live on Prod
- [ ] Ticket is cut for production launch planning, e.g. #10627 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@RLHecht can you confirm: there's no React widgets on these pages, just CMS content?

**Comment by RLHecht** [comment]
Correct, no react widgets on this page.

**Comment by jilladams** [comment]
@RLHecht I've added these 3 nodes to the right place for specifying that once published, they should only be included in the Staging build, and not the Production build. The next step is to publish the pages. After they're published, they should appear on staging after the next content release, however: is there someone who can help us do this step on Tuesday? That way we have more hands around to troubleshoot if anything is weird, rather than risking that today.

**Comment by RLHecht** [comment]
Thanks so much! Looping in @bethpottsVADEPO who will be in and out next week and could publish these pages.

**Comment by jilladams** [comment]
Ok great! Thanks. I'm still working out whether or not the CMS release bits will happen during code freeze or not, so it may be that this all can't get wrapped up til first week of Jan regardless, but we can ping Beth if we find that it can move next week. 

Enjoy your holiday!

**Comment by RLHecht** [comment]
Thank you, you too!

**Comment by mnorthuis** [comment]
@jilladams I apologize for any extra work this created, but we have decided that we are not going to move forward with this on this work effort.  There's not enough benefit to doing this to warrant additional work and risk, as well as the precedent it may set for other projects.   I'll let you close this ticket in case there's other work that needs to be done to forego this effort.  Thank you!

cc @bethpottsVADEPO @RLHecht

**Comment by jilladams** [comment]
Not a problem to remove the items I added, and no problem to abort. Thanks for the heads up!

**Comment by jilladams** [comment]
Going to go ahead and close - feel free to reopen as needed.
