### ISSUE TITLE
Sprint 75 - Public Websites

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12136]
### 1. Harden homepage for prod - 15+ 2 TBD FE points for 9 open issues; 3+ Drupal points

**Page itself:**
  - [ ] (minor 508) #12100 ()
  - [ ] (minor 508) #11823 ()
  - [ ] (minor 508) #11392 ()
  - [ ] #12090 ()
  * **Analytics:**
    - [ ] #12065 (5)
    - [ ] Tracking Analytics Team dependency in #11965 (0)
    - [ ] GA fix for existing homepage -- Analytics team GTM work required (0)
    - [ ] GA fix for new homepage -- Analytics team GTM work required (0)

**Drupal:**
  - [ ] (unlikely stretch; pending CMS Collab Cycle) #11692 ()

### 2. PDF Certificate Expiration Alert 
- [x] (pending SWContent; due Jan 6) #12138 (3)
- [ ] (Wes) #11525 (0)
 
### 3. Income Limits web app
- [ ] #12140 (5)
- [ ] (stretch; Wes) #12141 (0)
- [ ] (stretch; Steve) #12143 (0)
- [ ] (stretch; Steve) #12144 (0)
- [ ] #12158 (8)
- [ ] #12163 (8)

### 4. Chatbot 
- No action yet identified

### 5. Benefit Content Model Hardening
- [ ] (DaveP NOT able to fit in S75) #12058 ()

###  Other 508
- department-of-veterans-affairs/va.gov-cms#11205 ()  - tabled for deeper holistic approach later in Q4 / early Q1

---

### Redirects 
- [ ] (blocked on WebOps) #11662 (3)
- [ ] (target Jan 16) #12022 (1)

### Tech debt
- [ ] #10735 ()
- [ ] (stretch) #10307 

### Drupalize footer - 8 FE points
- [ ] (stretch) department-of-veterans-affairs/va.gov-cms#11482 (8)

### Injected header post-mortem
- Actions waiting on conclusion of post-mortem

## TOTALS: 
FE: 
Drupal: 
Design:
