### ISSUE TITLE
[EPIC] [PW] Implement PACT Act wizard content and logic

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12170]
## Status Updates
- **[2024-08-14] [Jill]** Final content delayed, launch not targeting August. ([Slack](https://dsva.slack.com/archives/C52CL1PKQ/p1723659950217559?thread_ts=1723653129.449249&cid=C52CL1PKQ))
- **[2024-08-08] [Fran]** Asked Danielle about the collab cycle content ticket; she's on top of it and taking it into consideration for the final content updates.
- **[2024-08-08]** Launch plan updated; Privacy, Security, and Readiness Review ticket completed and submitted.
- **[2024-08-05]** Awaiting final content from Danielle T. for the new results page.
- **[2024-02-22]** Launch still delayed; no new date or info. 
- **[2024-02-15]** Stakeholders want to delay launch for additional changes. 
-  **[2024-02-01 Fran]** 
    - Initial content changes from Danielle have been implemented
- **[2024-01-22 Fran]** 
  - IA provided guidance on breadcrumbs; work has been completed and is in Prod Verification. 
  - Security Review documentation will be completed this week and scheduled 
- **[2024-01-16 Jill]** 
  - Staging Review complete 
  - 1 launch blocker, breadcrumb related. Ask out to IA for consult. 
  - Greenlit to move ahead to Security Review 
- **[2024-01-11 Fran]** The team will be working on two text updates in Sprint 102; Fran to let Danielle know; she will then share with Stakeholders et al to get feedback/possible edits.
- **[2023-12-14 Fran]** Staging Collaboration Cycle review scheduled for February 12, 2024 ([ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/60582))
  - [Ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16442)created to update the QA artifact, a requirement to pass the collab staging review 
  - [Ticket ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16443)created to track the foundational testing artifact (Fran to create the actual 

## Product Outline
To be created: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md

## High Level User Story/ies
As a Veteran, I need to understand if I qualify for additional benefits, due to the PACT Act.

## Hypothesis or Bet
**If** we create a wizard to help Veterans understand their benefit status, **then** we will see an uptick in benefit applications for qualifying Veterans.

### Key metrics
TBD

### What must be true in order for you to consider this epic complete? 
* A benefits "wizard" has been designed built, tested, & launched, and metrics for the wizard's use and funnels to benefit applications are being tracked.
* Collab Cycle has reviewed & signed off
  
## Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
From planning: Currently we're figuring out research plan based on what tool we can use for prototyping. The requirement for complex branching logic is hard. 
Options: 
1. CodePen - evaluating on a call with Liz Lantz next week
2. Would we be ahead to just build the wizard and review from lower envs, and just iterate content

Dave would like us to eval the effort diff to help make the call.

**Comment by jilladams** [comment]
From planning: 
* Cindy on PTO 6/28-7/11
* DaveC on PTO 7/21-7/28 (return 7/31)
* Order of ops
    * Determine prototyping tool
    * If build: figure out who's building (Cindy in OW or Eng for CodePen) & timeline (may need tickets)
    * Finalize content
    * Finalize research plan
    * Finalize conversation guide (needs a ticket)
    * Then: schedule research

**Comment by jilladams** [comment]
From UX refinement: For Sprint 94 we will need to create the Research tickets for running sessions, topline, and then for Sprint 95: for synthesis. Cindy can stub, or PM/DM can stub and hand off either way to fill in the rest.

**Comment by jilladams** [comment]
Status notes migrated from Q1 doc: 
**[2024-01-22 Fran]** 

IA provided guidance on breadcrumbs; work has been completed and is in Prod Verification. 

Security Review documentation will be completed this week and scheduled 

**[2024-01-16 Jill]** 

Staging Review complete 

1 launch blocker, breadcrumb related. Ask out to IA for consult. 

Greenlit to move ahead to Security Review 

**[2024-01-08 Fran]**  

Danielle doesn’t have any further updates at this time.  

We have two minor text changes to implement (will be in Sprint 102) 

When those are complete, Fran will notify Danielle, who is working with OPIA to brief VA leadership on this tool before launch. There is a possibility there will be content changes that come from that. 1/12 Staging Review scheduled

**Comment by FranECross** [comment]
Moved to  Blocked. Stakeholders are planning substantiative content & possible flow changes. Pending their feedback.

**Comment by FranECross** [comment]
Added associated tickets as sub-issues so they'll display on the epic on the new board.

**Comment by FranECross** [comment]
Closing as completed; a new [epic ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19874)to track current/future tickets has been created.
