### ISSUE TITLE
Change behavior of My VA Link in header

### ISSUE THREAD

**Issue by davidconlon** [department-of-veterans-affairs/va.gov-cms#12195]
## User Story or Problem Statement

As a Veteran, I need to cancel a "click" into My VA dashboard so I can remain on the page that I am visiting.

The current behavior of the "My VA" login button from the homepage user-flow is that it triggers a react experience to the homepage that then pulls a login modal. The url has the `next` query param, indicating to go to My VA after login: `https://www.va.gov/?next=%2Fmy-va%2F`.

Instead the behavior should be the same as the "Sign in" button in the header that pulls up the sign-in modal. (Assuming that then brings the Veteran to the My VA page). 

### Injected header behavior

Behavior on injected-header sites should remain as-is:  both `Sign in` and `My VA` buttons should continue to redirect to `https://www.va.gov/my-va` (and directs them to log in, if not logged in).

## Acceptance Criteria
- [ ] Clicking My VA in the header triggers the Sign In modal on the page that they are on
- [ ] From that modal as-triggered by the My VA link, completing that flow will bring the Veteran to their My VA dashboard
- [ ] If a Veteran were to close the modal before completing sign-in, the Veteran will stay on whatever page they have been on when they triggered the modal experience
- [ ] On injected-header sites, both `Sign in` and `My VA` buttons continue to redirect to `https://www.va.gov/my-va`

## Implementation steps
<optional>

### Testing considerations

Test in staging using credentials from the Test User Dashboard.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by davidconlon** [comment]
@wesrowe @jilladams Added this issue for your awareness. Likely "low hanging fruit" for an upcoming sprint

**Comment by davidconlon** [comment]
tagging @Samara-Strauss and @ajakabcin for awareness of upcoming re-alignment of MyVA header link experience

**Comment by Samara-Strauss** [comment]
Thanks for this!

I also cleaned up the initial comment by changing "MyVA" to two words -- My VA -- so that's why it says it was edited by me.

**Comment by wesrowe** [comment]
@apisandipas, can you please pre-refine (estimate) when you have downtime?

**Comment by jtmst** [comment]
Both my VA and the login button redirect to the va.gov homepage under these conditions when using the injected header. Are there any desired changes to that flow?

**Comment by Samara-Strauss** [comment]
@jtmst no, please keep the existing redirect flows. Clicking My VA in the header and signing in from the homepage should both continue to redirect to My VA.

**Comment by wesrowe** [comment]
Great question @jtmst, I'm updating the ACs.

**Comment by wesrowe** [comment]
@jtmst, since we didn't get to refine live today – I'm just curious about the rationale for the estimate. I would have guessed, knowing nothing of the code, that the fruit was hanging lower than that. We can discuss in planning also.

**Comment by jtmst** [comment]
> @jtmst, since we didn't get to refine live today – I'm just curious about the rationale for the estimate. I would have guessed, knowing nothing of the code, that the fruit was hanging lower than that. We can discuss in planning also.

I estimated before that last comment, so I assumed there might be some injected header changes and testing in play as well, but that isn't the case.  I also havent done any work in the mega menu so I may just be overestimating because I'm unfamiliar.  Well adjust.

**Comment by jtmst** [comment]
Tested login and redirect to dashboard on staging and is working as intended

**Comment by jtmst** [comment]
> I just tested in staging with user 1, and I am wondering whether this is actually working as intended:
> 
> 1. I click the My VA link in the header. The homepage flashes quickly, then brings up the sign in modal. @davidconlon you were looking to remove the homepage-flashing phenomenon, correct?
> 2. I sign in, and I do get redirected to the My VA dashboard as intended. However, the homepage again flashes first, and then takes me to the My VA dashboard. @davidconlon again, we were looking to remove the homepage-flashing first, correct?

I'm not seeing this behavior.  If you click on 'my-va' from `https://staging.va.gov/health-care/about-va-health-benefits/` you are being redirected to the homepage?

**Comment by Samara-Strauss** [comment]
> I'm not seeing this behavior. If you click on 'my-va' from https://staging.va.gov/health-care/about-va-health-benefits/ you are being redirected to the homepage?

No, I am not being redirected.

**Comment by jtmst** [comment]
Thats the behavior we are trying to fix, users being redirected away from the page that they were on to the homepage.  I fixed that by redirecting to the same page they are currently on with the login page open and a next param that sends them to the va-dashboard when they log in.  This way if they close the login modal they are left on the same page that they were on when they clicked my-va.

**Comment by Samara-Strauss** [comment]
Thanks for the clarification! I'll close this again.
