### ISSUE TITLE
Spike: Understand the process and/or root cause of services still showing after moving

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#12232]
## Description
As described in #12182, it seems that when a health service moves facilities or systems, that the service still shows on the old facility or system. 

## Implementation steps
We either need to understand the reason this happens, to update the runbook describing how to move services to prevent this issue from occurring, or both.

## Acceptance Criteria
- [ ] We can predictably recreate the issue of the services showing on an old facility or system
- [ ] We can predictably move services without the issue recurring
- [ ] We find the responsible code that retains the service in the view of the old facility or system

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ryguyk** [comment]
## Spike Findings

The problem was originally framed with this language:


###
