### ISSUE TITLE
IncLim: Prep Tasks for Research

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12256]
## Description
Tasks to prepare for user research sessions.

## Tasks

- [x] Create item in research repo
- [x] Share research plan and conversation guide with Shane for feedback, approval, and launch recruiting
- [x] Use new form to request recruiting (pilot)
- [x] Make notetaking spreadsheet 
- [x] Make Mural board for observations and synthesis
- [x] Reach out to Perigean for kickoff meeting w/me and Wes to discuss recruiting
- [x] Make notetaking docs in github for Perigean to use--highlight my q's in bold/italics, and then Perigean can type in plain text
- [ ] DOESN'T APPLY: If don't have all participants scheduled before I leave for PTO, ask Perigean which requirement(s) are causing trouble and maybe drop them. Coordinate with Wes, who will cover when I'm away.
- [x] Review recruited participant list for requirements met
- [x] Make sure all research sessions are in my calendar
- [x] Make signup sheet for observers--after sessions are scheduled. Post signup sheet on OneDrive and create a link for Edit access.
- [x] Coordinate with @wesrowe and Dave Conlon to invite VA folks and Sitewide team members to sign up to observe sessions
- [x] Send instructions to observers of sessions (anyone who didn't observe a pilot)
- [x] Schedule team debrief sessions once a day
- [x] Invite observers to attend debrief session on the day of their observing
- [x] Review design prototype, including issues detailed [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12343#issuecomment-1474173549)

## Acceptance Criteria
- [x] All preparation done before the first day of research sessions

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cindymerrill** [comment]
Created a Mural for research session observers to record observations and ideas: https://app.mural.co/invitation/mural/departmentofveteransaffairs9999/1674859150912?sender=uff8fa85716c1796ccf022668&key=dbd99364-9dbc-4051-8ba4-bc31c7c5aad3

**Comment by cindymerrill** [comment]
Started a research session signup sheet that I'll fill in later with the actual session days and times and then share with team members to sign up to observ. Also drafted a message to invite people to the sheet, and observer instructions that I'll send to everyone who signs up.

**Comment by cindymerrill** [comment]
Uploaded observer signup sheet to OneDrive while using CAG, shared a link to edit the sheet with Dave P, and he was able to add his name, so this verifies that it works. I plan to share the spreadsheet with VA folks and team members this way--after I update the sheet with the days/times of scheduled participants.

**Comment by cindymerrill** [comment]
Research BLOCKED because design is BLOCKED by Content

**Comment by cindymerrill** [comment]
Today I launched recruiting and did the prep tasks needed for Monday's pilot: made notetaking spreadsheet, notetaking Mural, printed the conversation guide, and shared observer instructions with Wes and Jordan since they'll be observing.

**Comment by cindymerrill** [comment]
Had a kick-off meeting with Perigean and Wes re recruiting, found out more about how they satisfy recruiting requirements with a survey, and inspired them to change their survey questions from having only 1 option to instead having 2 options. Unfortunately, one of the question options still says “Not qualified” next to it, which I think may confuse and/or bias potential participants. I raised this to Shane Strassberg, who will talk with Perigean about this when he next meets with them.

**Comment by cindymerrill** [comment]
Drafted IncLim research observation communications. Created notetaking template for Perigean in github, and shared with them for feedback.

**Comment by cindymerrill** [comment]
Completed the following tasks today:

- Review recruited participant list for requirements met
-  Make sure all research sessions are in my calendar
-  Schedule team debrief sessions once a day

**Comment by cindymerrill** [comment]
Discussed observer signup process and spreadsheet with @wesrowe today. When I'm away on PTO next week, Wes will work with Dave Conlon to invite a sequence of groups of people to sign up to observe 1-3 sessions each. Draft groups of people and communications template can be found in this document: https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/ETMWRGzfXdNDrO_ceYn2qLoB8z_bznU8kSpg_XoC7LFPhQ?e=ech2JY

When I get back on April 3, I'll see if how the observer signups are going and jump in to help if needed. Then I'll send instructions (in above communications doc) to all observers and invite them to optional debrief meetings.

FYI @jilladams

**Comment by wesrowe** [comment]
@cindymerrill, update on my observer invitation activities:
- I haven't seen any research slots change times
- All the waves are invited – it's Wed now, I got Erika/Tim on Mon, VHA observer email out yesterday, Content/IA just now, and scheduled broader sitewide/CMS slack message for Th afternoon (as I'm checking out for PTO). You weren't copied on the Slack DMs so take my word for it?

**Comment by cindymerrill** [comment]
Thank you, @wesrowe ! Since we still have some observer slots open, I'm going to post again to #proj-vagov-team after one more PW person picks a slot.

**Comment by cindymerrill** [comment]
All ready for research sessions to begin tomorrow!
