### ISSUE TITLE
[SPIKE] Populate internal documentation epic

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12269]
## Description
The epic for moving site and content model documentation and out of Airtable: Spec tool (formerly [acquia spec tool](https://dev.acquia.com/blog/specification-tool-drupal-content-modeling)) is currently empty.  It needs to be fleshed out with issues and some of the issues will become upstream issues on D.o since the module will be contributed

## Acceptance Criteria
- [ ] Epic is fleshed with issues that will result in a module that contains
   - [ ] Content type metadata
   - [ ] field level metadata
   - [ ] displays to surface field instances with view modes.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
[Field Report](https://www.drupal.org/project/field_report) and [Entity report](https://www.drupal.org/project/entity_reports) have some simple but nice reporting.  I like the details on Entity report but do not like the collapsibles, whihc makes it hard to ctrl-f

**Comment by swirtSJW** [comment]
[Field Analytics](https://www.drupal.org/project/field_analytics) is just not far enough along on D8 to consider

**Comment by swirtSJW** [comment]
[Architecture module](https://www.drupal.org/project/architecture) has a great name but never made it out of D7

**Comment by swirtSJW** [comment]
The [original spec tool](https://dev.acquia.com/blog/specification-tool-drupal-content-modeling) did some conversion of the output to uml for making architecture diagrams.  That might be a nice add on post MVP

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/sitedoc has some great ideas.   It has not active code at the moment but I would like to implement
- Node Summary - lists how many of all content types are in the database, along with status information.
- Roles and Permissions - lists all user roles along with their access permissions, blocks that are restricted to the role, and may include all users assigned to the role.

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/projectdocumentation  
Is not D8 but the title is right and the model is right.
I might approach the maintainer and see if we can use the name and port it to D9

It created a content type for project changes mainly around module additions.

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/entities_info is an interesting exporter.  Similar in detail to the Field report module.

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/user_manual is more intended for editors

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/schemadotorg Very promissing if we were starting out now, but probably not so much use this far in.

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/drowl_admin_dashboard has no good explanation of what it actually does, but this phrase is intriguing enough to try it out 
"Get a nice default, configurable Dashboard for your Drupal project and provide a better onboarding experience for your maintainers."

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/field_list_details Neat module but not likely anything to replicate or use.

**Comment by swirtSJW** [comment]
I am going to combine the feature list and onto the epic but will start it here then move the final to the epic.

**Comment by swirtSJW** [comment]
Field level details

Modify or reproduce /admin/report/fields (preferably as a View)
- Pulled from existing data
   - Machine name (this will be the grouping)
   - Field Type (with module that provides it)
   - Entity Type (blocks, nodes, paragraphs, 
      - Used in (link to manage fields)
         - Field name
         - Description
         - target(s) (for entity references)
         - cardinality
         - link to display page
   - also used in (other content types and paragraphs vocabularies)
   - operations (edit) should not delete.. too great a likelihood for bad outcomes)
- Additional data to store  (maybe this becomes a fieldable entity we can add fields too?)




https://prod.cms.va.gov/admin/reports/fields

**Comment by swirtSJW** [comment]
@EWashb and @dawnpruitt  I am calling this done.  I have fleshed out the backlog for the epic and most of the issues have ACs.  The ones that still need refining are not going to be refineable until I get a little farther into this and can see what is possible.
