### ISSUE TITLE
CMS Documentation Updates

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12273]
## Background

After several iterations of various product teams using the CMS, the [Github documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/69833737d9fe22b8990bb987e7c50de13205c5d5/platform/cms) could use updating. The folders do not reflect the current state of the CMS team or the product teams that build on the CMS. There may also be other CMS docs in folders across the various repos. 

This task will likely require some detective work to find all of the pieces of documentation across the various platforms.  As we look to scale out our processes and Drupalize more content, a sound and clear documentation.

Not only are there documents in Github, we also have documents in the team [Confluence](https://vfs.atlassian.net/wiki/spaces/PCMS/overview) space. You will also find some references to the CMS on the [Platform website](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-gov-content-management-system-overview).

### User Story or Problem Statement

As a member of the VA ecosystem, I need clear and up-to-date documentation so I can find information that I need to interact with, build on, or understand the Drupal CMS.

How might we capture the right information about Drupal and the CMS in Github, Confluence and the Platform website so that product teams understand decisions and know how best to interact with the CMS Team?

### Affected users and stakeholders

* CMS Team members
* Various teams in the VA ecosystem
* Product teams that build in Drupal
* The VA product owners

### Hypothesis

We believe that updated and streamlined CMS documentation will achieve a wider understanding of the CMS platform and how to interact with it. We'll know this to be true when users can easily find what they need to answer questions about using the CMS, the history of decisions, and other pertinent information about our processes. 

## Assumptions
* Users currently cannot find the information they need about the Drupal CMS.
* Documents exist in too many places.
* There is no single source of truth for products or processes.
* There is more outdated documentation in Github than there is accurate and up-to-date information.
* There should be a decision point about what lives in Github, Confluence, and on the Platform Website.
* Interested parties are confused when attempting to locate specific product information. 
* The Platform Content team can assist with a large migration to the Platform Website for docs living in Github or Confluence that should be on that website

## Acceptance Criteria
- [ ] All current Github documentation is audited 
- [ ] All documentation in confluence is audited
- [ ] All documentation on the platform website is audited
- [ ] New documentation structure is proposed
- [ ] Documentation needed to add to the Platform Website is identified and meeting with Platform Content team is created to discuss a large migration.
- [ ] CMS team members assist in creating current-state documentation on processes, decisions, and SOPs
- [ ] All cms products have an updated/current product outline

**Comment by EWashb** [comment]
The scope of this ticket needs to be updated to include what stays in Github, what goes to the Platform Documentation website, and what lives in the Platform Confluence.

**Comment by EWashb** [comment]
I'm going to put this back out of "ready for sprint"...it is not anymore

**Comment by EWashb** [comment]
@BerniXiongA6 this is super similar to your #15805. You'll see in the tasks here that we did an audit in #12280 on what lives in Github. That wasn't just product outlines though. This could help us with our plans for product-specific docs.

**Comment by EWashb** [comment]
I would like this work to be a top priority for our new product manager when they begin. This work should include:

- understanding what documentation exists
- understanding where all the documentation exists
- updating and archiving docs as needed
- creating a library of up-to-date product outlines for CMS products
