### ISSUE TITLE
Recurring Events lack "Every 1st of the month" functionality

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12276]
## User Story or Problem Statement

As an Editor, I need to create an Event that happens on the 1st of the month, every month.

As a Public Affairs Officer, I need to create events that recur at arbitrary recurrence such as on the 1st and 3rd Monday of each Month.

However, I can only specify "Repeat every X days/weeks/months"

Given that each month has a different number of calendar days, this is problematic.

**Here are the frequency options when adding a new Event:**
![Screen Shot 2023-01-18 at 5 00 27 PM](https://user-images.githubusercontent.com/9059428/213326189-a3d95208-5d17-4ecc-aafe-27008b4a8a5f.png)

**If you input "Every 30 days" starting on 1/1/2023, the date drifts all over the calendar:**
![Screen Shot 2023-01-18 at 5 38 01 PM](https://user-images.githubusercontent.com/9059428/213328597-78081764-99f1-497d-9758-50789acdc615.png)

**To replicate:**
- Create a new Event: https://staging.cms.va.gov/node/add/event
- Add start and end dates/times such as 1/1/2023 at 8:00 AM until 1/1/2023 at 9:00 AM
- Select "Make recurring"
- Input "Repeat every 30 days" until 1/1/2024
- The list of dates will include the 30th and 31st of several months instead of having the event occur on the 1st of each month

## Acceptance Criteria
- [ ] Editors can add recurring Events in the format "Every X of the day/week/month"
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@jilladams Howdy, please let me know your thoughts on this issue -- thanks!

**Comment by wesrowe** [comment]
@cindymerrill, do you keep your own list of possible research projects? I added a "research" label to this issue for that purpose, might help.

**Comment by wesrowe** [comment]
Idea: this isn't in an epic at all. It should be added to an events one. But we could also have it in a "UX research project ideas" epic. (Wes to do)

**Comment by stefaniefgray** [comment]
@jilladams Thank you!

This ticket originated with Jira ticket [VAHELP-5367](https://va-gov.atlassian.net/browse/VAHELP-5367):

> "I'm trying to do a recurring event with an odd schedule. The event occurs on every first, second and fourth Tuesday at 11-12, and every first, second and fourth Thursday at 1-2, Is there a way to skip one week out of four, and to set specific times for the alternating days?
> 
> I tried to use the edit event series function, but it doesn't seem to save any changes. Has it been enabled yet?"

**Comment by cindymerrill** [comment]
@wesrowe I don't currently have a list of possible research projects, but I have done so before. It's not clear to me that this issue needs user research but rather a design change to the content editor interface that enables the user to specify which weeks of the month will have/not have the event. Were you thinking that we should conduct discovery research or usability test a new design?

**Comment by cindymerrill** [comment]
I believe that our original design for Outreach Events had more options for specifying recurring events, but perhaps they weren't all implemented.

**Comment by cindymerrill** [comment]
If this is a research project, perhaps our new CMS researcher Joann could work on it, perhaps in consultation with me. This isn't one of my priorities for Q1 at the moment.

**Comment by stefaniefgray** [comment]
![Screen Shot 2023-01-27 at 4 00 04 PM](https://user-images.githubusercontent.com/9059428/215223703-f6062f48-ca38-437c-b7db-ed4b3d04dda0.png)

Hey, thank you whoever added this to prod!

Old version from training site, for comparison:

![Screen Shot 2023-01-27 at 4 17 31 PM](https://user-images.githubusercontent.com/9059428/215223730-96389211-fed2-4e1c-92b9-dd8d939e182f.png)

**Comment by wesrowe** [comment]
I suspect that Dave C will not see this as needing Editor research. At least, I have seen him say that before in a situation like this. 

@stefaniefgray, your "thanks for these updates" comment is not meant to imply this is no longr needed, right?

**Comment by jilladams** [comment]
@stefaniefgray Reviewed this request with DaveC today in sprint planning, and he confirmed that it's currently in the "nice to want things" camp until we are able to onboard more editors to creating events, and get more explicit requests / use cases logged.

**Comment by stefaniefgray** [comment]
Past recurring events ticket discovered by @EWashb: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1956

**Comment by stefaniefgray** [comment]
Discussed on 2/7/23 with team -- ticket still in backlog, can be prioritized in future

**Comment by wesrowe** [comment]
To clarify, #1956 turned out to be the epic attached to this current ticket.

**Comment by FranECross** [comment]
Closing; this will be part of Events 2.0 and a new ticket encompassing recurring events will be created.
