### ISSUE TITLE
[cms-ci] Improve the UX for Rebuild/Install/Failed/Verify tasks in DevShop

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1233]
User stories

As a DevShop user:
- I want my environments to build successfully every time. 
- I want to know the progress/status of my build (or rebuild) in real time so that i am not confused about what it's doing. 

Implementation

The number of tasks needed to re/build an environment needs to be reduced, combining when possible.

1. [ ] All CI tasks must run in the correct order every time so that there 
are no errors caused by tasks running out of order.
2. [ ] Tasks must display in the User Interface (UI) in the correct order 
that they ran.
3. [ ] Tasks must reflect real time state in the UI 
    3b. [ ] Tasks say they are processing sometimes in the UI, but 
`ps axf` does not show them running.

**Comment by kevwalsh** [comment]
@jonpugh @ElijahLynn can you add issues from devshop repo to this epic?

**Comment by jonpugh** [comment]
Following. Tomorrow AM I will reserve for grooming "tasks and stability" issues.

**Comment by ElijahLynn** [comment]
I think we are going to keep this iceboxed since we are moving the test runs out of DevShop and into CircleCI which will mitigate this issue for now. 

https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-cms/issues/1231

**Comment by ElijahLynn** [comment]
Closing for now as we may be moving off of DevShop.
