### ISSUE TITLE
Sprint 77 plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12350]
### 1. Harden homepage for prod = 3 BE + 6 FE

**Benefit hub list:**
- [ ] #11968 (3) 🥅 
- [ ] #12351 (3) 🥅 

**Analytics:**
  - [ ] Tracking Analytics Team dependency in #11965 (3) - supporting Michelle Dooley to work out fix.
  - [ ] (may need support this sprint) Support [GTM implementation for new homepage](https://github.com//issues/50835) -- Analytics team GTM work required (0)
  - [ ] (future/NA) GA fix for existing homepage -- Analytics team GTM work required (0)

**"Create Account" block:**
  - [ ] (stretch; needs refinement) #12388 (5)
  - [ ] (stretch; pending design) #12387 (3)
  - [ ] (way stretch; pending CMS Collab Cycle) #11692 (needs refined)

**Other:**
- [ ] (removed from sprint; non-urgent per Dave) #12292 (3)
- [ ] (stretch) #12090 (2)

### 2. Header/footer redesign
- Awaiting info / green light for kickoff

### 3. Income Limits web app = 8 BE + 5 FE
**Design / Research:**
- [ ] (Not ticketed) Midpoint review - Include LauraF
- [ ] #12256  (8, includes launching recruiting)
- [ ] #12341 (8) 🥅 
- [ ] #12248 (5) 🥅 
- [ ] #12340 (8)
- [ ] #12343 (5)
- [ ] (Wes) #12384

**Engineering:**
- [ ] #12348 (5)
- [ ] (stretch) #12402 (8)

### 4. Benefit Content Model Hardening = 0 BE + 0 FE + 8 content/PM
- [ ] #9313 (8, content/PM)

### 5. PACT Act Wizard
- Chatbot leading content & maybe design?
- [ ] (way stretch, pending Dave input) #12171

### 6. Accordion header levels = 10 FE + 8 a11y
- [ ] #12342 (5)
- [ ] #12345 (5)
- [ ] (stretch; Laura F) #12352 (8)
- [ ] (stretch; depends on testing) #12346 (2)

### 7. Cerner API deprecation support
- [ ] (blocked on dependent teams) #9307 (5)

###  Other sprint priorities = 13+ FE
- [ ] (from Samara) #12195 (8)
- [ ] #12338 (5)
- [ ] (stretch) #12339 (needs refining)

### Injections
- [ ] (since Cindy doesn't have alternative projects, work on finding them) #12503 
- [ ] (BCM; broken off from 9313) #12452
---

### Redirects = 3 FE
- [ ] #12288 (2)
- [ ] #12407 (1) 

### Tech debt 3 BE + 4-9 FE
- [X] #10735 (3)
- [X] (in progress) #10307 (4 remain)
- (stretch) department-of-veterans-affairs/va.gov-cms#11843 (5)

### Drupalize footer
- [ ] (stretch) #11482 (8)

### Injected header post-mortem
- Actions waiting on conclusion of post-mortem

**Comment by jilladams** [comment]
Questions for Dave:
* Sprint priorities / goals
* Research / header vs. PACT progress

**Comment by wesrowe** [comment]
The IncLim project hit a rough patch in the first few days of the sprint, as significant questions arose about the IncLim prototype, content, and context. Cindy and Jordan picking up other work as we can find it.

BCM: we got the MVP meeting in on day 2 of sprint. that enabled us to redirect Dave P's work this sprint to auditing How to Apply content. Adjustments were made.

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12530 Pulled in bc Jordan has capacity
