### ISSUE TITLE
Spike - determine how TRICARE taxonomy NAME override can occur

### ISSUE THREAD

**Issue by Dottisea** [department-of-veterans-affairs/va.gov-cms#12356]
## Issue Description
How to make this change as quickly as possible so we can go to feature complete launch?

TRICARE serves many women who are spouses, etc., not veterans and the Phrase "Women Veteran Care" excludes them:

Hello,
Can we receive the documentation provided from the committee for their reasoning behind denying us a name change for “Women Veteran care” to “Women’s health care”?
The decision the committee made is going to have far-reaching implications to anyone visiting the TRICARE version of the site, specifically the spouses of our active-duty service members.
You could possibly get away with an active-duty patient associating “Veteran” with themselves but just labeling it as “Women Veteran care” sends a message that we don’t provide services to spouses and that they need to look for information somewhere else.
Our patient population is roughly broken down as:

18,000 enrolled Veterans
45,000 TRICARE recruits
12,00 TRICARE beneficiaries

As you can see, we have a much larger population of TRICARE patients compared to our Veteran patients.
Please send us the documentation so we can brief our leadership on why this decision was made.
Thank you,
 Katie K. Yearley

See tickets 11422 and 11350 and 11421
---
## Tasks
- [x] Review current tickets related to this task
- [x] Determine additional work required to develop a Service name permutation specific to TRICARE in the service taxonomy to override in the case of a TRICARE Facility
- [ ] ID all the places (Drupal, etc) this change would need to affect

## Acceptance Criteria
- [x] LOE is defined for this work to happen
- [x] additional and Equivalent BE/CMS Tickets are created
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `Console-Services`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by JayDarnell** [comment]
Notes for myself in terms of potential solutions as they pop into my head.

- For VAMC System Health Service changes, item 1: we might be able to update the view to return both the original name and tricare name concatenated together with a dividing character (: or - for example) and then use JS to conditionally hide or show the appropriate portion of the string.

**Comment by davidmpickett** [comment]
> Update the General service description -> Service description to display the TRICARE service description if the TRICARE service description field has a value and the VAMC System is set to Lovell Federal health care - TRICARE

Was this not done as part of the previous work on the TRICARE service description? It makes sense to do, but just calling out that it's not technically part of new work

**Comment by JayDarnell** [comment]
You are correct @davidmpickett that technically the description would be outside of this work but it was something I noticed while testing. I believe we fixed this for the front end but not for the editor experience.

![Screenshot 2023-02-07 at 12 31 37 PM](https://user-images.githubusercontent.com/21045418/217321413-d15864a0-146c-4b83-bddd-432362ecfc77.png)

**Comment by ryguyk** [comment]
@JayDarnell

**Comment by JayDarnell** [comment]
@Dottisea the four tickets above reflect the work needed to the best of my knowledge at this time.

**Comment by Dottisea** [comment]
The follow on work needs to be sized pror to closing this ticket.

**Comment by Dottisea** [comment]
The final work to make this a reality is estimated at 12 to 15 story points, which can be done in Sprint 78.

**Comment by davidmpickett** [comment]
Tickets have been sized and pulled in to sprint 78
