### ISSUE TITLE
Platformizing the Drupal CMS

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12365]
## Background

The CMS teams have combined into one larger team. As we think through how to integrate the larger team into Platform, there are some items that we align both sides of the ecosystem into one unified program and process. Platformizing the CMS will allow our team to scale outside of Sitewide Crew and into other VFS team needs. 

### User Story or Problem Statement
As a VFS Team, I need governance processes to build my product in the CMS that aligns with standards that OCTO will not negotiate on. 

How might we (the CMS Team) migrate documentation and create clear and scalable processes so that teams outside of the Sitewide Crew can use Drupal content for their products? 

## Headlines

**OCTO owner -** Erika Washburn

**Is request tracked to an event or Congressional deadline? -** No

## Details
**Who is the primary user?** 

- this change will impact the VFS-CMS Team, the Platform Crew at large, and any teams building on the Drupal CMS

### Affected users and stakeholders

* Platform Crew
* CMS Team itself
* Sitewide Crew
* Teams interacting with or developing in the Drupal CMS

**What is the business goal?** 
Site reliability and stability are maintained for VA.gov. 

Provide product teams the tools they need to build accessible and usable Veteran and beneficiary-facing experiences.

**How does this map to our North Star?**

1. Increase the availability of self-service tools
2. Decrease time to outcomes
3. Maximize satisfaction, reliability, availability, & security

**How will we measure success?**
- a new product team can be onboarded and building in Drupal following collab cycle and appropriate documentation

**What are the known risks?**
- CMS Team has only ever been a part of the Sitewide Crew as a "mini platform" often operating autonomously outside of the Platform Crew. This move will require large amounts of change management to the way our Sitewide Crew Teams work. This also creates additional workflows in the collaboration cycle that previously did not exist for these VFS Teams. 
- On Platform Crew, there has only been one contract team working with themselves as well. This will be the first time an outside contract and team has assimilated in this way for both he CMS Team and the Platform Team. This reorg will likely result in growing pains.

### Hypothesis

We believe that moving the CMS Team to Platform Crew will allow Drupal to be scaled to other VFS Team products. We'll know that to be true when VFS Teams can follow a complete product lifecycle build using the CMS Team's governance and collab cycle touchpoints.

## Assumptions
* Streamlining logistically with the Platform Crew and the collab cycle will allow the Drupal CMS Team to create sustainable processes and procedures.
* Integrating with the Platform  Crew will allow clearer processes for VFS teams building in the CMS. 
* Platform Crew already has documented best practices that the CMS Team can lean on to build from.
* Platform Crew alignment will allow the CMS to scale

## Acceptance Criteria
- [x] CMS Team has access to Platform Tools
- [x] OKRs to track the success of cutover have been determined and documented
- [x] Expectations of how to best interact with the CMS Team have been established and documented
- [x] Proper change management planning has been completed for VFS Teams
- [x] Documentation lives in the appropriate place (Confluence, Platform Website, etc.), and there is a cadence for updating
- [x] CMS Team has defined their integration with Platform ceremonies (where to integrate, where to remain separate)
- [x] Disciplines have appropriately integrated with their respective CoP
- [ ] CMS orientation has been created and added to Platform onboarding process
- [ ] CMS touchpoints have been added to the Platform collab cycle

References Links:

**Comment by EWashb** [comment]
@BerniXiongA6 @productmike I actually meant to tag that question about fleshing out the epic to THIS one...not the orientation issue. There are a lot of things we are currently doing to support our move to Platform so I'd like to connect all the dots if we can.

**Comment by EWashb** [comment]
Q1 Goal- Integration with Platform Collab Cycle
Q2 Goal- Pilot: New product team in Drupal

**Comment by BerniXiongA6** [comment]
@EWashb thanks for updating this! I'll help keep my eye on this for Product priority.

**Comment by EWashb** [comment]
The new CMS contract was awarded to Oddball. The new team will start work as a Platform Crew Team and integrate into their processes and procedures.

**Comment by EWashb** [comment]
I am due to schedule a meeting with Dave C., Michelle M, Amanda K, and Matt D. to discuss how the CMS Team might become a part of the Platform kickoff.
