### ISSUE TITLE
CMS Team- Sprint 77

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12376]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)

</details>

## Notifications

- [x] #12133 🥅  (Erika + Blake)
- [x] #12381 🥅 
- [ ] #12173 (stretch)

## Translations

- [ ] #12399 (Tim)

## Accessibility
- [x] #12127
- [x] #12396
- [x] #12377 (Stretch)
- [ ] #12378 (Stretch)
- [x] #12397 (Laura)

## Infrastructure

- [ ] #11051 (Elijah)
- [ ] #7667 (Elijah)
- [ ] Post-mortem- the content build failed and was a result of no owner
- [ ] Content & Localization: Testing in Staging Vets-API Server to EKS [#52711](https://github.com/department-of-veterans-affairs/va.gov-team/issues/52711#event-8410609969) request from Platform Tech Team 1

## Lagoon

- [ ] #12291 (Elijah) 🥅

## Drupal Upgrade

- [ ] Dependencies ongoing (Edmund)
- [ ] #12252 (Edmund)
- [ ] #10628 (stretch/blocked by #12252) (Laura)

## Collab Cycle

- [ ] #12272 (Erika)
- [ ] Explore Platform Drupal orientation (Erika + Dawn)

## Documentation

- [ ] #12287 (Swirt)
- [ ] #12309 (stretch) (Swirt)
- [ ] #12362 (Blake- stretch)

## User Support

- [x] #10552 
- [x] #10557 (Just needs review & publishing)
- [x] #10599 (Just needs review & publishing)

## QA Standards
- [x] #12392
- [x] #10579
- [x] #12394
- [x] #11959
- [x] #11895
- [x] #11880
- [x] #11961
- [x] #12501
- [x] #12500
- [x] #12513
- [x] #12551 
- [x] #9416
  - [x] #11841
  - [x] #11842
  - [x] #11845
  - [x] #5087
  - [x] #10713
- [X] #12215

### Stretch/Next Sprint
- [ ] #11493 
- [ ] #11958
- [ ] #9487
- [ ] #12445
- [ ] #12187
- [ ] #12415 (Nightmare -- if I can get to it.)
