### ISSUE TITLE
Events news releases and stories should reference the listing page, not the health care system or office

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1239]
**Describe the defect**

The goal with event listings (and other listing pages) was that events would reference a listing page, not the health care system or office (field_office) that the listing belongs to. 

![VA_gov_High_level_content_model](https://user-images.githubusercontent.com/643678/76647683-a9849f80-6533-11ea-893e-11843b7cf0f8.jpg)

Implementation
* Adding new field field_listing to four content types (cardinality - single)
   * events
   * stories
  * news releases
  * publications
* Removing field_office from four content types (later)
* field_listing should take on the same permission behavior that was added to field_office 
* 4 FE templates
* Update entity_access to look at listing pages for access.

### Implementation steps

1.  Phase 1 (CMS)
    1. Add field_listing to all content types
    1. hide field_listing
    1. Add field_listing to service check array. 
    1. add hook_entity_save to make field_listing populate to match field_office.
2. Phase 2 (CMS)
    1.  hook_update_N to establish new data connection to populate field_listing.
    1. Add descriptive field labels and help text for field_listing on four content types
3. Phase 3 (FE)
   1. Update GraphQL query to include field_listing and remove field_office.
   2. Update FE template to use field_listing and not use field_office
4. Phase 4 (CMS)
   1. fully remove field_office from four content types.
   1. show field_listing

#### Field listing entity reference field AC

- [x] As a user adding value for field_listing, i want the values to make sense so that i know what listing page i am adding to--even when the listing page has the same title as another page on the site.   For example, a user adding an event in Pittsburgh, i should see "**VA Pittsburgh health care: Events**" as an option. As a user adding an event to the Outreach and Events calendar, i should see "**Outreach and Events: Events**".  (eg `"node:field_listing:field_office:title": "node:field_listing:title"`). 
- [x] I should be able to reference unpublished nodes (eg for people building new VAMC sites that are not yet published)
- [x] I should only be able to reference listing nodes that i have permission to edit based on that listing's field_administration
- [x] I should see field label and field help text that concisely explains the purpose of this field

#### Other tech debt clean-up

- [x] remove teaser view modes for all content types
- [x] Event content type workflow UI > set to fieldset instead of fieldgroup

**Comment by oksana-c** [comment]
adding @jordanamello and @rachel-kauff for field label + help text verbiage (Phase 2)

**Comment by rachel-kauff** [comment]
@oksana-c Kev and I discussed the "verbiage"/ potential rework of the helptext and labels (field description and field name). I think for now they don't need a re-write, but that's something we can revisit when we look at some larger design opportunities in this area. cc: @kevwalsh
