### ISSUE TITLE
CMS Team Transition from Sitewide Crew to Platform

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12411]
## Background

Within the next 12 months (approximately and subject to change), the CMS Team will lay the groundwork for transitioning from the Sitewide Crew onto the Platform Team. The Drupal CMS is a stable tool for VFS teams to build on. Therefore, it should be seen as a platform. Currently the VFS-CMS team consists of two merged teams: Platform CMS and Sitewide CMS. This merged team is known as CMS Team as of Q1 2023. The merged CMS Team currently sits under the Sitewide Crew as we prepare for a larger transition to the Platform portfolio.

To ensure success, there are several things that the CMS team should do to ensure a seamless transition. 

### User Story or Problem Statement

As a member of the CMS Team, I need transition plans so I can prepare the proper handoff from Sitewide Crew to the Platform Team.

As an OCTO-DE Product Owner, I need to ensure that all items are documented, and processes accounted for so I can prepare for team transition. 

How might we roadmap and vision the appropriate transition steps so that the CMS Team can integrate with the current Platform Team processes and procedures while also maintaining the CMS's identity?

### Affected users and stakeholders

* CMS Team
* Sitewide Crew/Product Teams
* Platform Team
* OCTO at large

### Hypothesis

We believe that transitioning the CMS Team to the Platform Team will allow for the CMS to be seen as a tool for VFS teams to build on.

We believe that proper planning and roadmapping for a team transition will result in an ecosystem-wide understanding of the why and how this will be done. We'll know this to be true when the CMS Team's processes are integrated with Platform (i.e. collab cycle, design system, orientation). 

## Assumptions
* Roadmapping the team transition plans will allow for better collaboration with platform teams.
* CMS Team transitioning from Sitewide to Platform will allow the Drupal CMS to be utilized holistically and seamlessly for VA.gov.

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Transition roadmap is created
- [ ] Dependencies of this transition are documented 

  
## Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [X] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
Create tickets for:

- Platform collab cycle integration
- Design System integration
- Research Ops integration
- Platform Orientation integration

**Comment by EWashb** [comment]
This is a dupe
