### ISSUE TITLE
Feature Request: Drupal View of "Content Authored by: [Username]" for Help Desk Admins

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#12533]
## User Story or Problem Statement

As a VA Drupal CMS Helpdesk staffer, I would like to view a listing of all content authored by or edited by Firstname.Lastname@va.gov for account administration purposes.

This is not currently possible within Drupal, so if we were asked "Can you pull a list of all content authored by John.Doe@va.gov?" it would take much manual legwork to pull this list. 

We would also be unable to pull all nodes edited by this author, unless we went through the revision histories of all content listed within their section.

## Acceptance Criteria
A View (or a similar sort of dashboard) is created within Drupal that allows admins to view which pieces of content have been authored by or edited by a specific user.

## Implementation steps
Unsure

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ x `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [x] `User support`

**Comment by stefaniefgray** [comment]
@ndouglas @edmund-dunn @ElijahLynn I heard that it's "nice to want things" but @TroyA6 and I would sincerely love to have this View added within prod or a Tugboat instance -- thank you! 🙌 

Troy even said "Yes, I sincerely would" in a Southern accent as I was typing this
