### ISSUE TITLE
Improve Knowledge Base articles

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1254]
### User Story or Problem Statement

We need a common understanding of our existing user guides, their purpose / intention. 

- how they relate to in-CMS help text
- how they relate to Content Style Guide
- how they relate to help desk processes
- high level product documentation

## Relates to

#1266 (UX audit of forms and proofing)
[#4587](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4587)

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Help desk (What do users contact help desk about?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by xiongjaneg** [comment]
Adding help desk representation per Slack thread [#4587 ](https://dsva.slack.com/archives/CT4GZBM8F/p1614974154410700)

**Comment by xiongjaneg** [comment]
See also issue [#4587](https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/4587)

**Comment by stefaniefgray** [comment]
Removing self from ticket, please let me know if I should re-assign

**Comment by stefaniefgray** [comment]
Closing in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10157
