### ISSUE TITLE
Fix smart_date module with respect to modifying date/time for recurring events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12568]
### Engineering notes / background

* #12529 identified a bug affecting the UI while editing a recurrence of a recurring event (500 AJAX error, changes are not saved, no error bubbled to user). This was root caused as:  the SmartDateOverride entity type has a canonical link template, but is missing the corresponding route. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12567 resolves this issue by patching the module to add the missing route. This is a temporary fix to buy time until a more permanent solution (this issue) can be done. The problem was reported in [Drupal contrib](https://www.drupal.org/project/smart_date/issues/3210447), but the module maintainer was unable to reproduce, and so it was closed. When opening a new d.o issue, this originally reported issue should be referenced so others may find it.
** **Drupal upgrade**: When we [upgrade to Drupal 10](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12252), `smart_date` will get updated to 3.7.rc, where the bug will reappear. 
* During PR review of #12529 a [second error](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12567#issuecomment-1426290327) (500 ajax error) was identified where the root cause is the recurrence rule entity (smart_date_rule) doesn't yet have a parent entity, and produces an error: "Cannot load the "node" entity with NULL ID". This was reported in [Drupal contrib](https://www.drupal.org/node/3274881) and fixed in smart_date 3.6-dev.
* #10490 was filed to update `smart_date` to 3.6.x. When this was done previously, 3.5.1 -> 3.6.0 broke things because they changed something in their config schema, so we had to revert it. This upgrade will require its own troubleshooting, and we may want to skip this version in favor of a version of the module where we are able to upstream our fix (3.7-RC).

## Description
Given the above, and noting our use of smart_date 3.7-RC in the upcoming Drupal 10 work, it is suggested to perform all new patches against 3.7-RC rather than our current version of 3.5.1. And in order to avoid regressing the ajax errors back into existence, both the smart_date upgrade and fixes for the above issues need to be accounted for at the same time, either as an epic branch, or a single PR.

## Tasks

1. The extent of the [breakage](https://dsva.slack.com/archives/C02HX4AQZ33/p1661543507320209) caused by the [first attempt to update](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10490) have been determined.
2. Automated tests have been added that cover the broken functionality (i.e. that fail when the package is updated to a problematic version).
3. Update smart_date to ~~3.7-RC~~ 3.7.2 (edited to include latest stable release that was recently cut).
4. Determine if the above automated tests fail, and if so, resolve the issues presented, and open any necessary issues in Drupal contrib. Apply any patches contributed.
5. Create a d.o issue for the missing route issue, and write a patch for resolving this and all other missing routes in the modules (smart_date and smart_date_recur). The patch should include tests to ensure that the routes are working as expected (easiest way is to try to turn the route into a url string).
6. Replace the local patch "Editing event series causes ajax error 500" with the d.o patch created in the previous step.
7. Remove the patch "3274881 - PHP error when creating smart_date_rule entities that are not attached to entities" since this was rolled into 3.7 it will no longer be necessary.
8. Remove the patch "3294350 - Incorrect recurring dates created when using Phoenix timezone" as this was rolled into 3.6.
9. Determine if this patch is still necessary: "3260965 - Undefined index: #value". [A related solution](https://www.drupal.org/project/smart_date/issues/3259088) was rolled into 3.6.
10. Write a test for the [Phoenix timezone issue](https://www.drupal.org/node/3294350).
11. Along with a production ready PR, make a PR against the [Drupal 10 branch](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-12252-drupal-10) so events can be adequately tested there.

### User story
> _Describe the audience/user, enhancement or fix, and value / outcome desired._

* **AS A(N)**: editor
* **I WANT**: to modify the date / time of a recurrence on a recurring event
* **SO THAT**: I can address events that do not follow recurrence patterns. 

## Acceptance criteria

>Consider 
> - Design / Accessibility reviews
> - Collab cycle requirements
> - Device sizes (mobile first)
> - Documentation updates / Change management
> - Testing notes

- [x] As an editor, I can Edit a Recurring event, select a recurrence, modify the date / time, and save changes
- [x] Smart date has been upgraded to ~~3.7-RC~~ 3.7.2 (updated to 3.7.2 as this is the latest stable release)
- [x] [Drupal 10 PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12836) created 

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by dsasser** [comment]
Progress update:

The original upgrade [problem](https://dsva.slack.com/archives/C02HX4AQZ33/p1661543507320209)(s) reported (both reports were for the same root problem) are issues in smart_date versions > 3.5. This was confirmed using a clean/minimal drupal9 install with only the smart_date module as the sole contrib module enabled.

The problem surfaces only when:
- a smart date field is configured to use a the `Date and time range with timezone` form display formatter
- a smart date is restricting allowed/available timezones in the display formatter (see screenshot below)
- during node edit, the user selects any timezone other than the default.

Depending on the above, one of two problems will be revealed:
- A "white screen of death" message such as "The website encountered an unexpected error. Please try again later" (drupal logs reveal the underlying error is `Exception: DateTimeZone::__construct(): Unknown or bad timezone (4)`
- An unexpected form error `1 error has been found: Date and time (value 1)` which prevents saving the form.

Testing for the problems:
There exists an event node cypress test which covers testing that an event node can be created, but it didn't account for the non-default timezone problems. This test was modified to catch these problems by setting the timezone (previously, it was using the default timezone, and this is why the first attempt to upgrade smart_date did not flag any test failures).

![Screenshot 2023-02-24 at 1 11 08 PM](https://user-images.githubusercontent.com/221539/221297014-de63d28f-bdd0-4a2e-abd4-cde52b55cc2e.png)
![Screenshot 2023-02-24 at 1 14 31 PM](https://user-images.githubusercontent.com/221539/221297015-bd88ee69-a797-4675-92c7-06437a9c8405.png)
![Screenshot 2023-02-24 at 1 06 21 PM](https://user-images.githubusercontent.com/221539/221297019-ad52e5b0-f708-404b-9bd6-76dda6f8e3e2.png)

In terms of progress, related to the tasks outlined in this issue description
1. ✅ Done: The extent of the [breakage](https://dsva.slack.com/archives/C02HX4AQZ33/p1661543507320209) caused by the https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10490 have been determined.
2. ⚠️: Partially done: Automated tests have been added that cover the broken functionality (i.e. that fail when the package is updated to a problematic version).
    - As mentioned above, a cypress test was added to cover this issue, but more is needed to contribute this back to the community. A unit test is underway which will prove the existence of the problem, and serve as a springboard for the actual fix.
4.  ✅ Done: Update smart_date to 3.7-RC
5.  ⚠️ Started, not done: Determine if the above automated tests fail, and if so, resolve the issues presented, and open any necessary issues in Drupal contrib. Apply any patches contributed.
    - Working to both write the automated unit test (which will be contributed to d.o) and identifying and writing the fix.
6. ❌ Not started: Create a d.o issue for the missing route issue, and write a patch for resolving this and all other missing routes in the modules (smart_date and smart_date_recur). The patch should include tests to ensure that the routes are working as expected (easiest way is to try to turn the route into a url string).
7. ❌ Not started: Replace the local patch "Editing event series causes ajax error 500" with the d.o patch created in the previous step.
8. ✅ Done: Remove the patch "3274881 - PHP error when creating smart_date_rule entities that are not attached to entities" since this was rolled into 3.7 it will no longer be necessary.
9. ✅ Done. Remove the patch "3294350 - Incorrect recurring dates created when using Phoenix timezone" as this was rolled into 3.6.
10. ❌ Not started: Determine if this patch is still necessary: "3260965 - Undefined index: #value". [A related solution](https://www.drupal.org/project/smart_date/issues/3259088) was rolled into 3.6.
11. ❌ Not started: Write a test for the [Phoenix timezone issue](https://www.drupal.org/node/3294350).
12. ❌ Not started: Along with a production ready PR, make a PR against the [Drupal 10 branch](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-12252-drupal-10) so events can be adequately tested there.

Work is currently focused on task 5: writing the unit tests for the problems. Work is slow going, mainly because there are NO tests for this module at all, so some preliminary scaffolding is necessary. Further, the module is rife with problems (such as missing schema definitions) that make running unit tests impossible without first correcting for these things as I go.

**Comment by jilladams** [comment]
Great progress - thank you so much for the details, Daniel!

**Comment by dsasser** [comment]
Progress update:

1. ✅ Done: The extent of the [breakage](https://dsva.slack.com/archives/C02HX4AQZ33/p1661543507320209) caused by the https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10490 have been determined.
2. ✅  Done: Automated tests have been added that cover the broken functionality (i.e. that fail when the package is updated to a problematic version).
    - Automated test (cypress) has been added to our repo, and a d.o contrib patch (with tests) [has been created](https://www.drupal.org/project/smart_date/issues/3324142#comment-14943529).
3.  ✅ Done: Update smart_date to 3.7-RC
4.  ✅  Done: Determine if the above automated tests fail, and if so, resolve the issues presented, and open any necessary issues in Drupal contrib. Apply any patches contributed.
5. ✅ Done: Create a d.o issue for the missing route issue, and write a patch for resolving this and all other missing routes in the modules (smart_date and smart_date_recur). The patch should include tests to ensure that the routes are working as expected (easiest way is to try to turn the route into a url string).
    - [Issue created](https://www.drupal.org/project/smart_date/issues/3344798) with patch.
6. ✅ Done: Replace the local patch "Editing event series causes ajax error 500" with the d.o patch created in the previous step.
7. ✅ Done: Remove the patch "3274881 - PHP error when creating smart_date_rule entities that are not attached to entities" since this was rolled into 3.7 it will no longer be necessary.
8. ✅ Done. Remove the patch "3294350 - Incorrect recurring dates created when using Phoenix timezone" as this was rolled into 3.6.
9. ✅  Done: Determine if this patch is still necessary: "3260965 - Undefined index: #value". [A related solution](https://www.drupal.org/project/smart_date/issues/3259088) was rolled into 3.6.
10. ⚠️  Started: Write a test for the [Phoenix timezone issue](https://www.drupal.org/node/3294350).
    - I am working to extend the existing cypress test in our repo to check for Phoenix timezone issues.
11. ❌ Not started: Along with a production ready PR, make a PR against the [Drupal 10 branch](https://github.com/department-of-veterans-affairs/va.gov-cms/tree/VACMS-12252-drupal-10) so events can be adequately tested there.

**Comment by jilladams** [comment]
~3 points remaining for S79

**Comment by dsasser** [comment]
When working on task `10. Determine if this patch is still necessary: "3260965 - Undefined index: #value". [A related solution](https://www.drupal.org/project/smart_date/issues/3259088) was rolled into 3.6.` I discovered two things:

1. I wasn't able to re-produce the `Undefined index: #value` error, either with or without the patch. Additionally, the module maintainer was [not able to reproduce the issue](https://www.drupal.org/project/smart_date/issues/3260965#comment-14391604) reported, yet others in the community were having the same or similar issues. There may be certain runtime configurations that were present at the time of the patch, that no longer are present. Given that the patch is innocuous, I suggest we leave it in as a guardrail for these potentially unknown configurations, and seek to further explore this in a future ticket.
2. It is possible, in our VA.gov configuration, to create an event which has an _end_ date which is _earlier_ than the _start_ date. I confirmed that by disabling our custom `va_gov_events` module, this behavior is rectified--pointing to some of our custom code which is interfering with the form validation. In our EntityEventSubscriber we are doing the following (see below), which at first glance appears to be (though not verified) the root cause. I will ticket this bug for future work.

```
    // Set defaults to prevent validation errors.
    $form['field_datetime_range_timezone']['widget'][0]['value']['#value']['object'] = '';
    $form['field_datetime_range_timezone']['widget'][0]['end_value']['#value']['object'] = '';
```

**Comment by dsasser** [comment]
The smart_date module has rolled a new release as of yesterday, March 2, 2023. This update includes patches that I added/created as part of the upgrade work here. Upgrading to 3.7.2 will allow us to remove these patches, so I'm proceeding with doing that now.
