### ISSUE TITLE
CMS: (2) add support for TRICARE service name and service description to VAMC System Health Services

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#12586]
## User Story or Problem Statement

See #12356 

As a TRICARE beneficiary, it would be helpful to see services provided by TRICARE facilities using service names and descriptions as defined by TRICARE. For example, the service "Women Veteran care", as it is called by VAMC Facilities, is not identified by the name "Women Veteran care" at TRICARE facilities and should use a different name when displayed in the TRICARE context.

Problem description: How might we expand on the data we provide within the service taxonomy to support alternate names for services provided by TRICARE facilities? Where should we make updates to CMS nodes and views to be sure this alternate name information is displayed where appropriate?

## Acceptance Criteria

We need to add support for the new TRICARE service name to the VAMC System Health Service content type. When adding or editing a VAMC System Health Service...

- [x] VA services taxonomy: replace **TRICARE service name** field with a checkbox labeled **Show for TRICARE facilities only**
- [x] VAMC System Health Service: update the view responsible for populating the **Service name** drop down so any options with the checkbox **Show for TRICARE facilities only** checked specify they are TRICARE specific with a suffix: (TRICARE)
- [x] VAMC System Health Service: update the available options in the **Service name** drop down: if the selected **VAMC System** if **Lovell federal health care - TRICARE** hide any options containing the word: Veteran
- [x] VAMC System Health Service: update the available options in the **Service name** drop down: if the selected **VAMC System** is NOT **Lovell federal health care - TRICARE** hide any options containing the string: (TRICARE)
- [x] Update the General service description -> Service description to display the TRICARE service description if the TRICARE service description field has a value and the VAMC System is set to Lovell Federal health care - TRICARE
- [ ] ~~Update the **Service name** field to display the TRICARE name for a service when the value for the VAMC System is set to Lovell Federal health care - TRICARE and a given VA Service taxonomy term has a value in the TRICARE service name field.~~
- [ ] ~~On save, the title for the resulting VAMC System Health Service should use the TRICARE name field instead of the regular taxonomy name field.~~
- [ ] ~~On save, the URL for the VAMC System Health Service should use the TRICARE name field instead of the regular taxonomy name field for determining the path~~

![Screenshot 2023-02-02 at 4 17 56 PM](https://user-images.githubusercontent.com/21045418/216452083-89a985b5-ae37-4441-a167-f1203c8b347d.png)

## Implementation steps
This Service name drop down is controlled by a view: 
https://va-gov-cms.ddev.site/admin/structure/views/view/health_care_service_names_and_descriptions/edit/entity_reference_vamc_services

This view will need to be updated.

We also need to update drupalSettings:
`va_gov_backend/src/EventSubscriber/EntityEventSubscriber.php`:
- add TRICARE name
- add TRICARE description
as we do for Vet Centers on lines 203 - 204:
```
'vc_vocabulary_service_description_label' => $vocabulary_definition['field_vet_center_service_descrip']->getLabel(),
'vc_vocabulary_description_help_text' => $vocabulary_definition['field_vet_center_service_descrip']->getDescription(),
```

To populate the appropriate services, we could do one of the following:

1. Perhaps we can update the view to return both values with a separator and then in the JS that restricts content in the Service name field we display the TRICARE portion of the string where appropriate.

2. We could check for TRICARE name in the drupalSetttings array, and use that when populating the dropdown, if it's available.

To consider: A lot of the code is in "va_gov_backend," and we should not add any more to it than we have to. Instead, we should consider moving some or all of this to "va_gov_facilities."

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by JayDarnell** [comment]
Assuming we move forward with the proposed implementation pivot, what should we call this new checkbox?

@davidmpickett @christianmburk @swirtSJW 

- Restrict this service to TRICARE
- Limit this service to TRICARE
- This service is for TRICARE only
- ?

**Comment by omahane** [comment]
I don't know that we need to check for VAMC Facility for TRICARE Facilities. I also don't think we need to have to concern ourselves with a validation function. These are edited by one person, so the issue of data inconsistencies is very circumscribed.

**Comment by swirtSJW** [comment]
I like "Show for TRICARE Facilities only"  It takes all the other assumptions out of it.

**Comment by swirtSJW** [comment]
I would create an issue for the validation.  As  Octode is bringing on more personnel, it may not be that this is a Dave only editorial thing.  The issue may not be prioritized anytime soon, but it is there for someone to make a choice on.

**Comment by JayDarnell** [comment]
If we are not going the checkbox route and want to continue moving forward with the TRICARE service name override field it is safe to say this may not be completed this sprint as the lift becomes much bigger than it was previously estimated. We would need to conditionally override the logic for generating the node title and the node URL.

It looks like the pathauto module (which we use to define our URL patterns) provides a hook for overriding the pattern: https://git.drupalcode.org/project/pathauto/blob/8.x-1.x/pathauto.api.php 

See hook_pathauto_pattern_alter()

Another reference: https://www.mediacurrent.com/blog/pathauto-less-traveled

**Comment by davidmpickett** [comment]
> I would create an issue for the validation. As Octode is bringing on more personnel, it may not be that this is a Dave only editorial thing. The issue may not be prioritized anytime soon, but it is there for someone to make a choice on.

The Sitewide Content Team is actually the team that will be responsible for updating the Service Taxonomy going forward. See comment here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12322#issuecomment-1413837038
