### ISSUE TITLE
VISN websites: Research to validate content assumptions 

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12583]
## Description

**Veterans Integrated Services Network (VISN)**: The U.S. is divided into 18 VISNs, as "regional systems of care working together to better meet local health care needs and provides greater access to care": https://www.va.gov/HEALTH/visns.asp

There is an internal question at VA around migrating VISN websites to the modernized experience and whether that's valuable. Much of the information is: 
* Events / calendar
* Newsletter -- if migrated, content would be added to multiple healthcare systems as syndicated content, rather than living on a VISN site. 
* Leadership

We want to validate content assumptions around these websites / their future: would veterans expect this content on their medical websites vs. a VISN website. This would demand a COPE/seamless content migration. 

We want to know: 
* Do veterans use the VISN page
* Where would they expect this information to appear (on VISN vs. local healthcare center)
* Do Veterans need to know what a VISN is? 

### User story
**DRAFTS:** 

* **AS A** veteran,  **I WANT** to understand the regional health care options available to me **SO THAT** I can efficiently & effectively access my health care. 

* **AS AN** editor **I WANT** to ensure that regional healthcare information provided by VISN websites is available within VA.gov **SO THAT** I can efficiently manage a single source of truth.

### Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [X] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Acceptance criteria

- [ ] TBD

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Action items: 
* @jilladams @wesrowe need to onboard @Dottisea Kamari & @smythe5  to this as a Facilities question, where Cindy may help with research
* Facilities folks to meet with Dave & Cindy & Tim to talk about scope / next steps

**Comment by cindymerrill** [comment]
To facilitate async collaboration, I drafted a Word document of research ideas that others should be able to comment in (if logged into the VA system): [Facilities VISN Research Ideas](https://dvagov-my.sharepoint.com/:w:/g/personal/cynthia_merrill_va_gov/ESSotvi0FO5KlJbWDk8N5loBe7q0sRYrDtilmmMotvzT2w?e=dbpyvY). This was based on the limited information I heard today from [@Dave Conlon(https://dsva.slack.com/team/UNR3WALGZ) in Sprint Planning. 
[@Dorothy Cummings](https://dsva.slack.com/team/U04HQ6RHU5D) [@Kamari Patrick](https://dsva.slack.com/team/U04NVGF8GPQ) [@Jill Adams](https://dsva.slack.com/team/U03A58V9CDT)

**Comment by cindymerrill** [comment]
I assigned myself to this ticket so it will show up on my board, even though we haven't yet had a kickoff about it.

**Comment by cindymerrill** [comment]
Met with Dave C and Dotti, and updated research ideas in my document.

**Comment by mmiddaugh** [comment]
This content is moving to department.va.gov (intended for a primarily non-Veteran audience). 
Closing this issue.
