### ISSUE TITLE
CMS Team- Sprint 78

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12598]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)

</details>

## Notifications

- [x] #12449 🥅  (Steve)
- [x] #12173 (Erika)
- [x] #10430 (Laura) 
- [x] #12391 🥅  
- [x] (Erika: once design is complete from 12391- create tech implementation ticket for dev)

## Translations
- [ ] #10631 (Tim- stretch)
- [ ] #10004 (Tim- stretch)

## Infrastructure and Content Release
- [x] #12053 (Tim)
- [ ] #12435 (Eric)

## Accessibility
- [x] #12600 (laura)
- [ ] #12549 (Edmund- stretch)
- [ ] #12627 (Nate - In Review)
- [ ] #10111 (Edmund- stretch)
- [ ] #10154 (Edmund- stretch)

## Lagoon

- [ ] #12548 (Erik-A, Elijah, Eric-O)

## Drupal Upgrade

- [x] #10628 (laura)

## Editorial Research

- [ ] #12410 (Joann)

## Documentation

- [ ] #12310  (Swirt)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12290 (stretch given Swirt's capacity after revision log work)

## User Support
- [x] #10730 
- [x] #12451 
- [ ] Review and Publish [COVID Status KB](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12360)  Erika to create CMS Team's own tracking ticket

## QA Standards
- [x] #11493
- [x] #12612
- [x] #12614
- [x] #12679
- [x] #12681
- [x] #12610 
- [x] #12713
- [x] #12733
- [x] #12746
- [x] #12456
- [x] #12457
- [x] #12621
- [x] #12458

### QA Stretch
- [ ] #12459 
- [ ] #12460
- [ ] #12461
- [ ] #12462
- [ ] #12463
- [ ] #12464
- [ ] #12465
- [ ] #11958
- [ ] #9487
- [ ] #12445
- [ ] #12187
- [ ] #12734
- [ ] #12415 (Nightmare -- if I can get to it.)
