### ISSUE TITLE
Translation management setup

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12607]
## Background
The CMS needs to be configured to handle translation management - that is, the process by which CMS content is marked for translation, gathered together, sent to translation, imported into the CMS, reviewed, and published. It includes the following:

* Setup of translation management module
* Addition of functionality to support translation system-specific behavior (XLIFF additions to pass additional information)
* Addition of functionality to support providing context to the translators
* Creation of workflow states and transitions to support translation management
* Documentation of the entire translation flow

This epic does not include CMS configuration related to multilingual content itself; that is handled in #12606

### User Story or Problem Statement

As a translation manager, I need to have clear and usable tools for gathering CMS content for translation and for importing it, so that I can manage the translation of large amounts of content with minimum effort.

## Acceptance Criteria
- [ ] Significant amounts of content (up to 100 at a time) can be gathered and submitted for translation
- [ ] The files submitted for translation include meta information to support the translator - URL or image of source page, character limitations, support instructions, etc
- [ ] The content can be imported back into the CMS upon completion
- [ ] The translated content can be reviewed by a language expert prior to being accepted and published as a translation
- [ ] Documentation is created to describe the entire translation management workflow.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [x] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
