### ISSUE TITLE
Multilingual CMS: Language and translation configuration

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12606]
## Background
As part of the multilingual CMS effort, we need to configure the CMS to support translation. This includes:

* enablement of Spanish and Filipino as additional languages in the CMS
* enablement of supporting modules
* configuration of appropriate entities (nodes, pages, taxonomies, etc) for translation
* configuration of permissions and assignment to roles for the above

This epic does *not* include:
* setup of translation management
* any additional work specifically to support the translation management process

### User Story or Problem Statement

As an organization, I need the CMS configured to enable translations, so I can proceed with the translation process.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [x] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
