### ISSUE TITLE
SE: Multilingual Content Management

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#12604]
## Background
We are required to support translations of VA.gov CMS content into other languages. This epic contains all work needed to get the CMS to support translation into Spanish and Filipino, our first two target languages. It includes:

* Setting up languages in the CMS
* Setting up various entities (nodes, paragraphs, taxonomies) to be translatable, in order to meet the needs of our first translation use cases through the Benefits Hub.
* Setting up Translation Management
* Setting up roles and permissions relating to translation viewing, editing, and management
* Specifying and documenting all the operations required to take a piece of source content from English to fully translated into other languages.

This epic's work does *not* include:
* work on publishing multilingual content via content-build or any other mechanism.

## Roadmapping and Strategy
Q1 2023 priority only includes enabling the ability in the CMS to do multilingual content management to support Spanish as Tagalog in the Benefits Hubs and creating user roles for the translation manager. Q2 2023 will focus on working with the Sitewide Content + IA team to walk through the process of supporting translated content in those benefit hubs. We should be prepared to do this work for the Q2 initiative in a demo environment. The demo environment will allow us a low-risk opportunity to confirm this works for the need. After the CMS foundation is built, we will then proceed with the FE support of this work. Most likely, the FE piece of this will be handed off to the Public Websites team for discovery and implementation. 

### User Story or Problem Statement

As a Veteran, family member, or caregiver, I need to read VA.gov content in my native language, so that I have the best understanding of my benefits and how to access them.

As an organization, we need to provide end users content in their native languages so that we can ensure the best understanding and outcomes for those users.

### Affected users and stakeholders

* CMS Editors
* Developers of all teams
* Translation managers

## Acceptance Criteria
- [ ] Content can be translated into Spanish and Tagalog for target content types.
- [ ] Files used for translation of target content types can be requested through the CMS.
- [ ] Completed translations can be imported back into the CMS to create translated content.
- [ ] Viewing, editing, and management of translations is restricted to appropriate users. 
- [ ] The translation process is fully and clearly documented.
  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [x] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by EWashb** [comment]
@productmike if you have a V.2 or next iteration of translation epic, I think we can probably close this one. What do you think?

**Comment by EWashb** [comment]
This MVP work has been completed
