### ISSUE TITLE
Determine approach for handling inline entity forms editing nodes.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12668]
## User Story or Problem Statement

Since revision log messages were made required for all node types there were exceptions made in the case of inline entity forms referencing and allowing to edit other nodes.  (example: editing Vet center Facility service on a Vet Center) 

![image](https://user-images.githubusercontent.com/5752113/219730079-720e29b1-9e80-4cd4-bc86-26ecdf19989b.png)

We have been handling that by bypassing the required validation on nodes if they came through inline entity forms.  Otherwise an editor would not be able to save the update they made inline.  It would fail because there is no log message field to be filled, even though it is required.

**Decision point**:  Should we continue bypassing the requirement for inline entity forms, or should we add the revision log message field to all inline entiity forms for node content types.

## Acceptance Criteria
- [ ] Determined by decision point 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
