### ISSUE TITLE
Design: Update the discharge upgrade wizard to a subtask pattern

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#12698]
## Description
The [Discharge Upgrade Wizard](https://www.va.gov/discharge-upgrade-instructions/questions) needs to be updated to a new design system pattern. 

In the design system, the [wizard pattern](https://design.va.gov/patterns/wizards) has been deprecated. The [subtask pattern](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) should be used for the discharge upgrade questionnaire instead.

- [Discharge Upgrade wizard](https://www.va.gov/discharge-upgrade-instructions/questions)
- [Discharge Upgrade Sketch File](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e)
- [Mural documenting the flow](https://app.mural.co/t/vagov6717/m/vagov6717/1670355600942/8ebd465060e3c6e404292ab065389458a27160f9?sender=u252e7152800e3981889d1910)

## Acceptance Criteria
- [x] Create mockups in Sketch showing the discharge upgrade wizard in a subtask pattern
- [x] Confirm with Platform Design Team that this approach seems appropriate
- [x] Add link to designs to the body of the epic

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Discussed with Jordan. Because the logic for this product is wild, there's no reason to replicate the[ Mural flow](https://app.mural.co/t/vagov6717/m/vagov6717/1670355600942/8ebd465060e3c6e404292ab065389458a27160f9?sender=u252e7152800e3981889d1910) in Sketch. In my opinion, we can have Jordan use one representative pathway through for the design, rather than comprehensively tackle every question. (@wesrowe holler if any objections.)

**Comment by thejordanwood** [comment]
@wesrowe @jilladams The design update for this can be found in [this Sketch file](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e). I took Jill's recommendation and only showed one version of the flow, but believe every type of question example (radio buttons, dropdown) is shown. 

If there is no additional feedback, then I will take this to the Platform design team office hours on Tuesday.

**Comment by jilladams** [comment]
@thejordanwood That Sketch file is telling me it's private & I need a login. Does it live in the same space as the VA Homepage one? Not sure if it's on my end or not.

**Comment by thejordanwood** [comment]
@jilladams I've changed the settings on the Sketch file and you should be able to view it now.

**Comment by jilladams** [comment]
Nice! One note - can we show at least one radio button with a value selected, just to demonstrate the style for the button lines up with the design system?

And making sure I get it that the form changes, but we won't make any design changes to the Results screen, as a part of this update? -- that seems clear in the Sketch file, just making sure.

**Comment by thejordanwood** [comment]
@jilladams I've shown what a radio button looks like selected. 

Yes, the results screen will remain the same. I've made a note of that in the Sketch file too.

**Comment by jilladams** [comment]
Unless @wesrowe has add'l feedback, this seems good to move on in the process.

**Comment by wesrowe** [comment]
@thejordanwood, can you add a start screen? It can be the mobile version of the existing start screen if appropriate. The flow just feels like I'm joining a movie after the beginning.

**Comment by wesrowe** [comment]
(Note: I don't have permission to comment in Sketch)

Also – re the breadcrumbs, you have "< Home". The breadcrumb for the [start page](https://www.va.gov/discharge-upgrade-instructions/) is already "Home > Discharge upgrade". So I wonder if we would at least keep that depth.

**Comment by wesrowe** [comment]
Lastly, I would add a prominent note at the start that these screens are representative – e.g., you have 8 questions, I think there are a few more than that if one follows specific flows. No need to document them all, I just think it would be helpful to add that qualifier in large font. 😄

**Comment by thejordanwood** [comment]
@wesrowe Start screen and qualifier have been added! 

On mobile, only one breadcrumb is ever show. The current experience has "Home" as the only breadcrumb on mobile, but I wonder if it would make more sense to direct back to the start screen?

**Comment by wesrowe** [comment]
Oh I see what you mean, it simplifies to "Home" on mobile. I don't think that would fly with the current Platform design team – there's a rule of thumb out there that either something is useful (for any device format) or it's not. I guess we don't have to solve it now, but I would lean toward a more provocative version of the breadcrumb like your suggestion that it returns to the start (or pre-start) screen.

**Comment by jilladams** [comment]
From scrum: Jordan to take to Design office hours today for next steps.

**Comment by thejordanwood** [comment]
Update from design office hours: It's recommended that we show this to Content and Accessibility, then schedule a Midpoint Review for this work. 

Very optional: There isn't a lot of user research on this subtask pattern, so if we wanted to do some user testing that is an option for us. 

@jilladams @wesrowe

**Comment by jilladams** [comment]
I think we should ticket those things all separately and follow up with iterate prototype tickets. Gonna stub things out in the epic.
