### ISSUE TITLE
Populate database dump with email addresses

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12713]
## User Story or Problem Statement

As an engineer on the system I would like to be able to have users have email addresses in the system on our prod snapshots.

Currently our database dump removes all the email addresses (even though it keeps the user name which is also the email address.

We don't want to use the actual email address in case some lower system accidentally triggers a send, so we want to use @example.com

## Acceptance Criteria
- [x] In the database snapshots, email addresses are populated with userDRUPAL_USER_ID@example.com

## Implementation steps
<optional>

## Design principles

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [X] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
Closed in https://github.com/department-of-veterans-affairs/devops/pull/12586.
