### ISSUE TITLE
CMS Team- Sprint 79

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#12778]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)

</details>

## Notifications

- [x] #12784 (Laura) 🥅
- [x] #12711 (Edmund) 🥅
- [x] Outdated Content CSV fixes #11955 & #11575 (Edmund-immediate stretch)
- [x] #12845
- [x] #12857

## Translations

- [x] #12708 (Tim) 🥅
- [x] #12705 (Tim) 🥅

## Infrastructure and Content Release

- [x] #12774 (In Review)
- [x] #11405
- [x] #12782

## Lagoon

- [x] #12785 (Dawn/Erika/Elijah/Tim/Erika - In Review)
- [x] Schedule meeting with Bryan and team at Amazee

## Editorial Research and Design

- [x] Share CMS Trust Survey with PO (Jo)
- [x] Create Epic to Establish Editorial ResearchOps for CMS (Jo)
- [x] #12362 (Blake possibly stretch since he's OOO)

## Documentation/Erika's Transition Tasks

- [x] #12745 (Elijah)
- [x] #12730 (Steve)
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12816 (steve)
- [x] #12748 (Erika/Jo)
- [x] Erika- Draft tentative Q2 plan
- [x] Erika- Draft Sprint 80 plan
- [x] Erika- more github and collab cycle documentation

## User Support

- [x] #12673 
- [x] #12797
- [x] #12798
- [x] #12799 

### QA/Testing
- [ ] #12734 (In Review)
- [ ] #12459 
- [ ] #12460
- [ ] #12461
- [ ] #12462
- [ ] #12463
- [ ] #12464
- [ ] #12465
- [ ] #11958
- [ ] #9487
- [ ] #12445
- [ ] #12187
- [ ] #12415 (Nightmare -- if I can get to it.)
