### ISSUE TITLE
Content model diagram is not showing Views entity references

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#12816]
## User Story or Problem Statement
In many cases (especially on facilities) we have entity relationships that are made by a View.  In these cases, they are not represented on the diagram.  This is an upstream issue.

## Acceptance Criteria
- [x] Entity references made by a View show as targets in the field list
   - [x] create patch  here https://www.drupal.org/project/content_model_documentation/issues/3343243
- [x] Entity references made by a View show as entity connections in the diagram
   - [x] create patch here https://www.drupal.org/project/content_model_documentation/issues/3343244

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
The diagram part has been fixed https://www.drupal.org/project/content_model_documentation/issues/3343244 upstream

**Comment by swirtSJW** [comment]
Both issues have been resolved upstream and a release has been created.  Dependabot should bring it in shortly
https://www.drupal.org/project/content_model_documentation/releases/1.0.0-alpha13

**Comment by swirtSJW** [comment]
@davidmpickett This update has been fixed upstream and will be arriving on prod in a day or so.  It adds the ability to show Views filter Entity references to both the field list and the entity reference diagrams.
![image](https://user-images.githubusercontent.com/5752113/223525237-1a05ca54-aaba-43eb-8eee-24ea461a5d0b.png)

**Comment by davidmpickett** [comment]
Woohoo! Very exciting
