### ISSUE TITLE
PW Sprint 80

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#12886]
## Q1 Priorities
_Items with [x] are carried over from previous sprint_

### 1. Post-MVP Homepage 
**General:**
- [ ] (stretch) #12814 (5) - Research
- [ ] (stretch) #12980 (needs refining) - FE 

### 2. Header/footer redesign
- Awaiting info / green light for kickoff

### 3. Income Limits web app
**Design / Research:**

- [ ] #12340 (5) - Research
- [ ] #12256 (5) - Research
- [ ] #12343 (3) - Design

**Engineering:**
- [ ] (Stretch, blocked on Plat implementation, may unblock in sprint 79) #12348 (5) - BE

**Future sprints**
- [ ] #12402 (8) - Ruby
- [ ] #12976 (8) - Research

### 4. Benefit Content Model Hardening 
- [ ] #12975 (3) - Content
- [ ] #12735 (needs refining) - Content, include DaveC in internal review but don't block on it

### 5. PACT Act Wizard
- Pending movement from stakeholders; first ticket is ready for Cindy (research) 

### 6. Accordion header levels 
- [ ] (blocked min til Sprint 81 to review data) #12863 (5) - FE 

### 7. Cerner API deprecation support
- [ ] #9307 (5) - [tasks remaining](https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887) - FE

___

### BTSSS widget
- [ ] (blocked on content, 53735) #12591 (~8, tbd content) - FE

##  Other sprint priorities 

- [ ] (stretch) #12339 (5) - FE

### Redirects & Content support
- [ ] #12697 (2) - FE
- [ ] #12841 (1) - FE/BE
- [ ] #12885 (2) - FE/BE
- [ ] #12944 (2) - FE/BE

Epic of upcoming redirects not yet in our board: 
https://github.com//issues/53921

### Tech debt & Defects
- [x] #12800 (5) - BE
- [ ] (carryover from s78) #10307 (~5? remain) - FE
- [ ] #12832 (3) – BE
- [ ] #11937 (8) – FE (maybe BE)
- [ ] #12933 (5) - BE
- [ ] (stretch) #11448 (5) - FE

### User research and UX pipeline development
- [ ] (stretch) #12791 (8) - Research
- [ ] (stretch) #12601 (5) - Research
- [ ] (stretch) #12719 (5) - Research

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
ARs: 
* Create & refine CMS Design for Benefit content model hardening
