### ISSUE TITLE
CMS Name and mission statement

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1289]
## Acceptance Criteria
- [ ] We have a name for our product, and some rules that go along with using that name, added to github va.gov-team repo
- [ ] Bonus: we have a slogan or mission statement for the CMS (separately story probalby?)
- [ ] Validation with POs. 

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [x] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)
