### ISSUE TITLE
Update build tools for theme vagovclaro theme and design_system

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#12927]
### Problem Statement

Based on discovery in #12782 the vagovadmintheme needs to be removed(see #11011) and the build tools for vagovclaro need to be updated to use weback instead of gulp because gulp hasn't been updated since 2019.

This is necessary because of security vulnerabilities that have been introduced by outdated dependencies. Several of these vulnerabilities are introduced by gulp. 

## Acceptance Criteria
- [ ] Removed vagovadmintheme
- [ ] Retool vagovclaro theme to use webpack
- [ ] Update design_system dependencies

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
