### ISSUE TITLE
Top tasks and baseline

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1292]
## Problem statement

Current CMS navigation is designed for engineers/site builders and not for editors. We believe that a more effective navigation can be designed if we understand the top tasks that editors perform in their day to day work as well as their navigation patterns.

## AC

- [ ] a set of top ranked tasks is defined to use as a baseline for improving UX
- [ ] analysis of friction (unnecessary effort) in accomplishing the top tasks is performed to inform UX improvements
- [ ] common language exists to describe tasks across various forms of documentation
- [ ] the [journey map](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/cms-personas-journeys) is updated to include "top tasks"
- [ ] sensors (analytics and/or survey and/or other) for measuring our impact for at least a portion of top tasks are identified
