### ISSUE TITLE
Segmentation Fault and HTTP 502 Status Code when saving CM_Document entities on BRD environments

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#12936]
This is a follow up from the spike https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12745 to identify the issue. The issue was identified as a missing zend_smart_string.h headerfile in the segfaults that we are seeing that correlate to the network timeout. There is a notable amount of debugging already in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12745 so please reference that issue for details. 

```[tasklist]
## Acceptance Criteria
- [ ] Segfaults do not occur anymore on PROD for requests to https://prod.cms.va.gov/admin/structure/cm_document
```

```[tasklist]
## Tasks
- [x] Recreate issue
- [x] Find logs > https://vagov.ddog-gov.com/dashboard/vnk-g4s-fru/cms-prod--staging?from_ts=1680126143382&to_ts=1680730943382&live=true
- [x] Disable one of the memcache servers and see if reproducible
- [ ] Test out a full code and DB revert pre-23rd on TEST.PROD https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/devops/cms-test-sync.md#to-restore-an-older-version-of-the-database-to-cms-test-prod
- [ ] Fix issue
- [ ] Make PR if needed
```

**Comment by ElijahLynn** [comment]
Going off where https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12745 left off to test the hypothesis that maybe it is the remi-safe repo that is not including that file. 

I disabled the remi-safe repo by setting `enabled=1` to `enabled=0` in `/etc/yum.repos.d/remi-safe.repo` and then enabling the normal remi repo by setting `enabled=1`  in `/etc/yum.repos.d/remi-safe.repo`. Then `yum remove php82` which did remove from `remi-safe` then `yum install php82` which did install from `remi` (not safe) repo. Then `systemctl restart httpd` and reloaded https://test.staging.cms.va.gov/admin/structure/cm_document and am still getting the segfault, and I verified that the `/opt/remi/php82/root/usr/include/php/Zend/zend_smart_string.h` is empty and also see that `/opt/remi/php81/root/usr/include/` exists and is empty too. 

I suppose one option that could work although I really don't like it is to install PHP from source, which would maybe need to be done in a base AMI so it doesn't increase our overall Build times on every commit > build > release > deploy. 

I guess I'll try that first, and at least get to a "get it working" state, then move on to "get it right".

**Comment by ElijahLynn** [comment]
Hrm, I've done another segmentation fault/segfault analysis and this time used the `bt` command inside the `(gdb)` prompt to get the call stack, and I'm seeing a callstack of 1,155 calls:

```
#1131 0x00007f4bdc4226ae in datadog_php_profiling::execute_internal () at src/lib.rs:1040                                                      
#1132 0x00007f4beab5a84a in ZEND_DO_FCALL_SPEC_OBSERVER_HANDLER () at /usr/src/debug/php-8.2.3/Zend/zend_vm_execute.h:2063                     
#1133 0x00007f4beab5b163 in execute_ex (ex=0x7f4bc2bda980) at /usr/src/debug/php-8.2.3/Zend/zend_vm_execute.h:56060                            
#1134 0x00007f4beadfe251 in zend_execute (op_array=0x7f4be9c89000, return_value=0x0) at /usr/src/debug/php-8.2.3/Zend/zend_vm_execute.h:60384  
#1135 0x00007f4bead8e020 in zend_execute_scripts () at /usr/src/debug/php-8.2.3/Zend/zend.c:1780                                               
#1136 0x00007f4bead27fbe in php_execute_script () at /usr/src/debug/php-8.2.3/main/main.c:2541                                                 
#1137 0x00007f4beae72ab8 in php_handler () at /usr/src/debug/php-8.2.3/sapi/apache2handler/sapi_apache2.c:712                                  
#1138 0x00005575422494ea in ap_run_handler (r=r@entry=0x55754301cfd8) at config.c:169                                                          
#1139 0x0000557542249a01 in ap_invoke_handler (r=r@entry=0x55754301cfd8) at config.c:443                                                       
#1140 0x000055754225e3be in ap_internal_redirect (new_uri=<optimized out>, r=<optimized out>) at http_request.c:790                            
#1141 0x00007f4bf3b45ff5 in handler_redirect (r=0x557543011c90) at mod_rewrite.c:5293                                                          
#1142 0x00005575422494ea in ap_run_handler (r=r@entry=0x557543011c90) at config.c:169                                                          
#1143 0x0000557542249a01 in ap_invoke_handler (r=r@entry=0x557543011c90) at config.c:443                                                       
#1144 0x000055754225ef8c in ap_process_async_request (r=r@entry=0x557543011c90) at http_request.c:452                                          
#1145 0x000055754225f12e in ap_process_request (r=r@entry=0x557543011c90) at http_request.c:487                                                
#1146 0x000055754225b6ae in ap_process_http_sync_connection (c=0x557542ec0f50) at http_core.c:208                                              
#1147 ap_process_http_connection (c=0x557542ec0f50) at http_core.c:249                                                                         
#1148 0x00005575422527da in ap_run_process_connection (c=c@entry=0x557542ec0f50) at connection.c:42                                            
#1149 0x0000557542252cfb in ap_process_connection (c=c@entry=0x557542ec0f50, csd=<optimized out>) at connection.c:217                          
#1150 0x00007f4bf0d45998 in child_main (child_num_arg=child_num_arg@entry=3, child_bucket=child_bucket@entry=0) at prefork.c:667               
#1151 0x00007f4bf0d45ce8 in make_child (s=0x557542b94dd0, slot=slot@entry=3) at prefork.c:773                                                  
#1152 0x00007f4bf0d45d20 in startup_children (number_to_start=2) at prefork.c:791                                                                                                                              
#1153 0x00007f4bf0d463db in prefork_run (_pconf=<optimized out>, plog=0x557542b98d48, s=0x557542b94dd0) at prefork.c:953                                                                                                                                        
#1154 0x000055754222bfba in ap_run_mpm (pconf=0x557542b69a48, plog=0x557542b98d48, s=0x557542b94dd0) at mpm_common.c:95                        
#1155 0x000055754222443d in main (argc=<optimized out>, argv=<optimized out>) at main.c:841                                                    
(gdb)                                                                                                                                          
```

**Comment by ElijahLynn** [comment]
Hrm:

> This backtrace shows a recurring pattern where multiple calls to mmc_pool_select() and mmc_pool_run() are being made, and the process is repeatedly attempting to unserialize data using php_var_unserialize_destroy() and mmc_unpack_value().

**Comment by ElijahLynn** [comment]
Next step is to disable memcache and see if regular MySQL cache code is able to reproduce this issue.

**Comment by ElijahLynn** [comment]
This is not done yet and was more difficult than I expected. I faced issues of the segfault core dump changing the reasoning behind the segfault and ended up going a different direction. The good thing is that it is still reproduceable. 

I need to carry this into next sprint.

**Comment by ElijahLynn** [comment]
Easier steps to generate the core dumps: https://gitlab.com/-/snippets/2521995

**Comment by ElijahLynn** [comment]
@swirtSJW and I paired on this today and we found that by only using 1 memcache IP in our cluster that the Segfaults stopped happening. I'm experimenting now with different memcache.ini PHP extension settings to see why. This is consistent now with only 1 vs 2 nodes in the cluster, working vs segfaulting.

**Comment by ElijahLynn** [comment]
Looks like the recent batch of segfaults started at March 20 at 5pm PT. 

![image](https://user-images.githubusercontent.com/1504756/229212611-e046ea8c-8357-4f6e-bd5b-e191e99a5c19.png)

**Comment by ElijahLynn** [comment]
Possibly related: Need to read through this more: https://github.com/php/php-src/issues/10737

Worth noting we are on PHP 8.1.17 and it was just released on March 16th, we saw our first segfault with PHPUnit on March 23rd, and then the next day with Apache (MPM) as well.

**Comment by ElijahLynn** [comment]
Looks like the first segfault, upon zooming in further was at 1:06pm PT/3:06PM ET. Just 10-15 minutes after deploy. 

![image](https://user-images.githubusercontent.com/1504756/229234105-f0f6a30c-cf32-4b33-81ec-e682ae733e07.png)

**Comment by ElijahLynn** [comment]
Well, I thought it might have been related to dd-trace/ddtrace 0.86.0 that we were using because that release was causing segfaults on PHPUnit tests (magic methods) and this release introduced support for memcached > https://github.com/DataDog/dd-trace-php/pull/1981

https://github.com/DataDog/dd-trace-php/releases/tag/0.86.0

But, I just downgraded the PHP Extension and the Composer library to 0.85.0 and am still seeing the Segmentation Faults. 

Still investigating.

**Comment by ElijahLynn** [comment]
Reiterating that we first saw these segfaults:
* Staging: Mar 23 11:24am PT
* Prod: Mar 24 1:06pm PT (deploy is at 12:50pm PT)

![image](https://user-images.githubusercontent.com/1504756/229942572-c8687059-8ad4-4e4a-aa79-49d476665f75.png)
![image](https://user-images.githubusercontent.com/1504756/229942715-89f3d2fa-4265-4421-8917-38a27da08566.png)

**Comment by ElijahLynn** [comment]
Rolling back to this commit on test.prod:

March 22nd, 12:35pm PT
Release 0.0.736 ami-067e3b0deb5e0216a == e6891e88f2888749a48f113c8e461188bbebf4ee

![image](https://user-images.githubusercontent.com/1504756/230237125-54e5043a-b0f9-487b-80ea-859b56d2e3fe.png)

**Comment by ElijahLynn** [comment]
This is where I stopped the other night. This is still a good next step. HOWEVER, the Segfaults have largely stopped as of Monday, April 3rd on PROD. Even though I am still able to easily reproduce on STAGING right now as of this moment, April 6th 4pm PT by requesting https://staging.cms.va.gov/admin/structure/cm_document. 

![image](https://user-images.githubusercontent.com/1504756/230508874-bdb8cd7c-58f5-4441-b62c-afffac84f42b.png)

Both STAGING and PROD have the identical commit deployed right now yet I just loaded https://prod.cms.va.gov/admin/structure/cm_document (PROD) 10 times and did not experience a segfault. So the issue is still happening but only on STAGING now. Maybe this means we need to restart an elasticache memcache node?

**Comment by ElijahLynn** [comment]
I just rebooted STAGING Elasticache cluster and still got 3 out of 14 failures on STAGING. 

![image](https://user-images.githubusercontent.com/1504756/230509913-83c7e689-60b4-442a-a3c6-3cbe26582844.png)

But, we aren't seeing them in the logs on PROD since the deploy at 12:38pm PT on Monday, April 3rd. 

![image](https://user-images.githubusercontent.com/1504756/230510083-6e97a422-f8aa-49f6-ab7b-6dc92ecc982a.png)

I don't think we should close this issue but the priority has definitely gone down since we are not seeing on PROD in any significant volume right now. The sole segfault we had in the screenshot above on Tuesday, April 4th was correlated exactly with a Memcache network timeout, fwiw. And this was the only one in 3 days. 

But the fact remains that this is easily reproducible on STAGING and could end up causing test failure flickers which would reduce our test suite confidence.

**Comment by ElijahLynn** [comment]
The odd thing is that STAGING has both the faux php extension of datadog/ddtrace 0.86.1 and the composer library right now, and so does PROD, but yet STAGING has segfaults and PROD does not. The PHP Extension update of 0.86.1 did in fact resolve our PHPUnit test run flickers on STAGING (note that these don't show up in our HTTPD logs in Datadog), see #13134, but not the requests coming in through Apache.

**Comment by swirtSJW** [comment]
On my very first edit of a CM document (just edit and re-save) I am seeing this on prod 
![image](https://user-images.githubusercontent.com/5752113/230646405-4ebe639e-1646-41f0-bb1d-f2b23cfbd976.png)

**Comment by swirtSJW** [comment]
And same thing again on my second save 
![image](https://user-images.githubusercontent.com/5752113/230646556-0a3d0c3d-9737-4f64-8217-f68d48d70000.png)

I am not seeing that this has reduced on prod.

**Comment by ndouglas** [comment]
This was misdiagnosed. The missing `zend_smart_string.h` header file message just means GDB can't provide more information about the symbols in the stack trace because the header file is not available. It does not mean that the header file's absence is in any way connected to the crash. Header files are consulted at compile time, not runtime.

**Comment by swirtSJW** [comment]
Thanks Nate for picking this up.  I do think we were chasing the wrong thing here.  To me it seems like it is definitely tied to mis-caching between the two servers.   I was seeing it toggle back and forth between having new data and old.   And when we disabled one of the two memcache servers, it went away completely.   I do not know why specifically this is tied to CM Documents but they definitely seem to surface this.

**Comment by ndouglas** [comment]
Strongly, strongly suspect that I found the issue today (made the change live and performed a few dozen checks and all succeeded). I'm going to do a clean test on Monday and then I'll open an issue and slightly rewrite another issue to address.

**Comment by ndouglas** [comment]
As discussed on Friday, I performed a test against a relatively clean (only one modification), and I was unable to encounter the 502 error.

![Screenshot 2023-04-21 at 3 39 19 PM](https://user-images.githubusercontent.com/1318579/234011364-8e2219c4-c8f3-47da-82af-1fc1f5c60bdd.png)

(L -> R: DDEV, Tugboat, test.staging)

So as it turns out, we're running three different PHP client Memcache extensions. Switching from the `memcache` extension to the `memcached` extension is sufficient to keep the error from occurring further.

I investigated everything I could think of before stumbling onto this rubber-ducking with Eric Oliver. The question was, why is this happening on BRD but not Tugboat or DDEV? Unfortunately, instead of checking the client extension configuration, I leapt to possibilities like latency, Elasticache configuration, etc. I should have tested easily-tested things first.

I turned on multiple Memcache servers in DDEV, but still could not reproduce the issue. Again, I thought this was due to something more esoteric like network latency or server configuration.

So followups for this issue:

- [ ] #12935: I've simplified this to "Install `memcached`, not `memcache`, on BRD."
- [ ] #13465: A discovery ticket covering preliminary work for unifying PHP across all environments.
