### ISSUE TITLE
Prepare PW products for US Design System 3.0

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#12995]
### User Story or Problem Statement

AS A Veteran
I WANT VA.gov products to change over to USDS 3.0
SO THAT I get to experience its usability and accessibility benefits.

AS A Product Owner
I WANT Public Websites products to be 3.0 ready
SO THAT the Design System Team (DST) can upgrade VAgov in a timely fashion.

## Notes and background
- Wes verified that our react widgets don't have issues as of 3/15/23: [slack thread](https://dsva.slack.com/archives/C01DBGX4P45/p1678990459010609?thread_ts=1678905756.884219&cid=C01DBGX4P45)
- Carol Wong of the DST provided this epic, which breaks the adoption of USWDS v3 into three distinct phases: https://github.com/department-of-veterans-affairs/va.gov-team/issues/52870
  - _Timing estimate: as of 3/17/23, DST will be using Q2 2023 to execute Ph1 of their form demonstration app (so no action for VFS teams)._
- "Foundation" is the name of the existing VA design system

## Acceptance Criteria

**Discovery:**
- [ ] Obtained guidance from DST about types of tech debt that aren't compatible with 3.0
- [ ] Audited all Public Websites products for tech debt that isn't compatible with 3.0
- [ ] Wrote tickets for all instances that need update

**Implementation:**
- [ ] Completed implementation tickets
- [ ] Verified fixes with DST

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by davidconlon** [comment]
@jilladams Is this complete? I'm confused that this is in "Opened/New" but has all closed items?

**Comment by jilladams** [comment]
Right you are - it's complete.
