### ISSUE TITLE
PW Sprint 81

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13038]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626
Design / Research:
- [ ]  #12343 (3) - Design
- [ ]  (carryover on purpose) #12256 (5) – Research
- [ ]  #12976 (8) - Research

Engineering:
- [ ] (ESECC unblocked) #12348 (5) - BE
- [ ]  (prio vs. FE work?) #12402 (8) - Ruby

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628
- [ ]  (DaveP carrying over from s80) #12975 (3) - Content
- [ ]  #12735 (needs refining) - Content, include DaveC in internal review but don't block on it
- [ ]  #12383 () - Design
- [ ]  #13070 () - BE
- [ ]  #13071 () - BE

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170
First ticket is ready for Cindy (research)

@wesrowe TODO: Initial convo in S81, 1hr, Jordan, Wes, DanielleT, Cindy(?), DaveC optional to determine: are the flow chart paths we're creating are the best way. And: best way to map it for testing, given deeper complexity than Discharge wizard.

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. Not yet actionable. (DST building their Ph1 (sample form) in Q2.)

- [ ]  #13098 () – FE

### Other Q2 priorities not in motion

- Translation in R&S, Hubs https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- Header/footer redesign - Awaiting info / green light for kickoff

### Post-MVP Homepage https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11170
- [ ] #12980 - FE
- [ ]  #12161 (1)
- [X]  (not necessary per Analytics team) #13069 ()

### Cerner API deprecation support
- [ ]  (BLOCKED) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

## Other PW Priorities

- [ ]  (before April 4) #13093 () – FE/BE
- [ ]  (stretch) #12339 (5) - FE
- [ ]  (stretch) #13084 () - FE/BE
- [ ]  (stretch) #12932 (8) - FE (Daniel)

Content / IA priorities

- [ ]  #12697 (2) - FE
- [ ]  #13083 () - FE

Epic of upcoming redirects not yet in our board:
https://github.com//issues/53921

Tech debt & Defects

- [ ]  (carryover from s78) #10307 (~5? remain) - FE
- [ ]  (ballooned in s80; bail??) #12832 (3) – BE
- [ ]  (carryover from s80) #12933 (5) - BE
- [ ]  (stretch) #11937 (8) – FE (maybe BE)
- [ ]  (stretch) #11448 (5) - FE

User research and UX pipeline development

- [ ]  (stretch) #12791 (8) - Research
- [ ]  (stretch) #12601 (5) - Research
- [ ]  (stretch) #12719 (5) - Research

**Comment by jilladams** [comment]
- [ ] Need to update ticket for Q2 prioritiies

**Comment by jilladams** [comment]
@wesrowe FYI that your last edit here was out of sync with version control. I can't tell what it was intending to update so we may have lost a couple notes in translation. I re-updated it to Q2 priorities -- take a look and let me know if we need to talk through to work out what we lost.
