### ISSUE TITLE
BTSSS Widget: Use/Investigate Use of CTA react component

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#13061]
## Description
In #12591 we implemented the BTSSS react widget using the <va-alert> web component. However, an existing CTA component exists in vets-website that could possibly be leveraged to reduce tech debt on the BTSSS widget.

The CTA component was not utilized for the following 2 reasons:
- The CTA component has a slightly different design for the authenticated link.
- The CTA component lacks Google Analytics click tracking capabilities.

### Engineering notes
The CTA widget is located [here](https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/components/CallToActionAlert.jsx).

## Tasks
- Determine if the design of the CTA component is acceptable as-is.
- Enhance the CTA component to include GA tracking capabilities.
- Change the BTSSS widget to utilize the CTA component.
- On the CMS page that includes the react widget (/health-care/get-reimbursed-for-travel-pay), set the 'Call To Action Widget' checkbox.

## Acceptance Criteria
- [ ] BTSSS functionality remains
- [ ] GA tracking is functional
- [ ] CMS page has 'Call To Action Widget' checkbox set
- [ ] Requires design review

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
FYI @wesrowe

**Comment by dsasser** [comment]
> @dsasser, re the CTA component we didn't use – is it documented in the design system? I didn't see it on a search. [Action Link](https://design.va.gov/components/link/action) is a flavor of link in the design system though, we've used it several places.

It isn't a design system component, but a React component, and therefore isn't found in the Design System. It is found in the vets-website repository only.

**Comment by wesrowe** [comment]
Just yesterday it clicked for me: "react components" are being generally deprecated because they hold the site back from adopting US Web Design System 3.0. React components are being replaced by web components. So I _think_ this ticket would move us in the wrong direction. Does that track for you, @dsasser?

**Comment by dsasser** [comment]
> Just yesterday it clicked for me: "react components" are being generally deprecated because they hold the site back from adopting US Web Design System 3.0. React components are being replaced by web components. So I _think_ this ticket would move us in the wrong direction. Does that track for you, @dsasser?

Yeah this is a tricky subject, but no that doesn't track for me. Deprecating all React components in vets-website isn't possible. React components are just reusable javascript functions written in React. I think what you are referring to is the eventual deprecation of all React components within the design system itself, which does impact vets-website wherever those components are utilized. For instance the RadioButtons React component _within_ the design system was recently deprecated, and it meant that we needed to upgrade the vets-website React components that utilized the RadioButtons design system component.

In this case, the CTA component I'm referring to is a vets-website owned React component that utilizes design system components to render content on the screen.

**Comment by wesrowe** [comment]
Thanks for the clarification. That helps. In the future maybe we need to be clearer about "Design system react components" versus... I guess "react components" just how you used it. :)

**Comment by randimays** [comment]
@FranECross This might be a good candidate to Refine if we are running low on PE FE work.

**Comment by FranECross** [comment]
Thanks, @randimays ! I moved it to Needs refining and added the label.

**Comment by jilladams** [comment]
Noting: we may need a specific type of Veteran profile in order to see / test this widget. There may be data about that on tix in the BTSSS original epic. (#9157 )

**Comment by randimays** [comment]
I picked this up yesterday, but I'm seeing the movement/discussion on next-build and the lingering code I have over there; I'd like to try to take a little bit of time to freshen that code up.

**Comment by jilladams** [comment]
No objection. Noting that for Sprint 23, this may not move due to next-build priorities taking flight.
