### ISSUE TITLE
Service taxonomy terms should have workflow

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13079]
## User Story or Problem Statement

As a maintainer of the Services Taxonomy, 

- I would like to have the ability to draft changes to a term without making them immediately public (using the same workflow as nodes).
- I would like to be required to add a revision log  message the way I am on all content types.

## Acceptance Criteria
- [x] As an editor I expect the services taxonomy terms to follow node workflow (draft, needs review, published, archived)
- [x] As an editor I expect service terms to require me to enter a revision log message with each save
- [x] I expect to verify that the draft term changes do not make their way to the front end. There is a risk that current GraphQL queries my not be set up to use the the published revision of a term.  If found to be true, this will lead to another ticket
- [x] I expect that any KB is updated appropriately
   - [x]   Updated https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-tricare-specific-service-names 
   - [x] Updated https://prod.cms.va.gov/help/vamc/how-to-add-or-edit-tricare-specific-service-descriptions
   - [x] Updated https://prod.cms.va.gov/help/vamc/editing-facility-supplemental-status-covid-19-term-descriptions

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by kmariepat-cityfriends** [comment]
Next Steps: This may be a CMS ticket, @kmariepat-cityfriends to talk to CMS PMs

**Comment by wesrowe** [comment]
I removed the dependency that had this issue blocking Public Websites' implementation of workflows on the benefits taxonomy since PW will likely go first.

**Comment by swirtSJW** [comment]
I have the workflow enabled for service terms.   Running into some minor trouble with the Revision log field.  Working on it.

**Comment by swirtSJW** [comment]
Revision log field is working on service terms, but not on other terms.   Will kill that bug on Monday.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends The major change this creates is the addition of the Moderation state field and the revision log field for the VA Service vocabulary..
![image](https://user-images.githubusercontent.com/5752113/233229979-57093142-fc28-4696-8b4a-bfeb6a661af3.png)
It did add revision log message fields to all Vocabularies. (something we have been missing)

Testing coverage was expanded to include coverage of  revision logs on all taxonomy vocabularies in the system.
