### ISSUE TITLE
VA Benefits Taxonomy Build Ph 1: Implement structure of fields in new taxonomy

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13070]
### User story

**AS A** PW developer
**I WANT** to stand up the basic implementation
**SO THAT** I and team members can check for surprises in a review instance.

### Engineering notes / background

Source of truth for what should be implemented is the [VA Benefit Taxonomy spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit?usp=share_link) (Google sheet; please request an Excel copy if you need one.)

### Analytics considerations
n/a

### Quality / testing notes
No QA, this is a rough pass.

## Acceptance criteria

***The ACs below apply ~~only to rows 4-17~~ to all rows of the spec spreadsheet (the ones finalized in the meetings on 3/29 and 4/6)***

- [x] All fields implemented per structural details in spec (not design or content), specifically:
  - [x] field label
  - [x] machine name
  - [x] field type
  - [x] required
  - [x] cardinality
  - [x] permissions
- [ ] ~~Taxonomy terms implements existing editorial workflow similar to  node content (draft, in review, approved, published, archived)~~ _moved this AC to [Taxonomy workflow ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13141)_
- [ ] ~~Taxonomy term editing requires revision log message entry in order to save. (similar to node content)~~ _4/6: this AC is also part of the [Taxonomy workflow ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13141)_
- [ ] reviewed by Jill, Daniel, DaveP
- [ ] shared for high-level review (not detailed design & code review) by: Jordan, Tony, Swirt

NOT in scope:
- rename the term label 
- lock down the api field 
- enforce uniqueness
- enforce that terms can’t be linked to themselves

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [X] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
I just updated the ACs to reflect revisions and workflow.

**Comment by wesrowe** [comment]
@swirtSJW, we just discussed internally and decided to punt the workflow ACs to a future ticket so that we can leverage Facilities' work on adding the workflow module to taxonomies. Hopefully that makes sense to you.

**Comment by jilladams** [comment]
Re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12383#issuecomment-1490949417
>The VA Benefit API ID can NOT be modified after a Benefit is published

The Services taxonomy has this paradigm in effect already, with permissions management too. @swirtSJW  is the person to talk to about how that works, I believe.

**Comment by wesrowe** [comment]
Note that I focused the ACs on the fields that we reviewed in yesterday's meeting.

**Comment by chri5tia** [comment]
Dumping my concerns about using taxonomy vs. content type for this here. As I find satisfactory answers in conversations past and present, I'll check them off.
- [ ] Editors can not go to add > content because taxonomy is part of structure, usually closed off to editors except in rare cases of websites that allow ad-hoc creation of taxonomy terms on the content add form (tagging).
- [ ] Taxonomy does not have workflow draft, publish state, etc
- [ ] Taxonomy does not have revision logs; (taxonomy is simply created or destroyed)
- [ ] What problem are we trying to solve by using taxonomy instead of a content type? 
- Content types collect information from editors that will be used as content around the site and is tailored for that purpose with meta data, a title, description, revision history, workbench workflows, etc and is avoided by version controlling
- Taxonomy is a collection of words or phrases to help organize different types of content in different ways as part of architecture and is version controlled instead of revision logging (not version controlled by default)

**Comment by chri5tia** [comment]
Decisions we need to make:

- [ ] Taxonomy or Content, final answer
- [ ] Description of VA Benefit vocabulary
- [ ] Path alias pattern (VA Services uses health-care/[title]); we could use va-benefit/[title]

**Comment by swirtSJW** [comment]
> Editors can not go to add > content because taxonomy is part of structure, usually closed off to editors except in rare cases of websites that allow ad-hoc creation of taxonomy terms on the content add form (tagging).

Yes this is true, but this is not for most editors, this is a very select set.  Also in most of those cases node content translates to actual pages.  Benefits terms would not be FE pages, only ways to connect one thing to another.  

>  Taxonomy does not have workflow draft, publish state, etc

They can, and they will.  This is part of the build, not a blocker.


> What problem are we trying to solve by using taxonomy instead of a content type? What are the pros and cons stress/time/technical-debt-wise of re-engineering Taxonomy to function as a content type?

Mainly, we are not trying to have it serve as a content type.  We are trying to have it make connections to other content types, which is what taxonmy was built to do.

>  How long has the Service taxonomy been in use on our site and what is the editorial workflow for that at the moment? Who creates the terms, (role), how is the content change-logged, how is it used?

Many years.  There is minimal editorial workflow on it currently because Dave C has been the only editor of it.


Notes

> Both types create their own front-facing pages (front-end of the back end). For example: https://va-gov-cms.ddev.site/health-care/adaptive-sports is the page for the Taxonomy Vocabulary "VA Services" and the term "Adaptive Sports"

We have not instances where current taxonomy is creating a front end page.  The page you reference has no front end counterpart.  There is no https://www.va.gov/health-care/adaptive-sports

**Comment by chri5tia** [comment]
@swirtSJW These clarifications are helpful. It sounds like I can come to you with any blockers for building or conceptualizing this direction.

**Comment by chri5tia** [comment]
@swirtSJW Any thoughts on creating this as a module instead of importing field configs? It might be nice to have the module framework to house any special tweaks and hooks, or other features down the road relating to benefits. I don't see any pattern currently used to manage content types and field configs with a custom module, so maybe there's a good reason for that.

I like the idea of being able to look at or write a yaml for field configs for something like this.

**Comment by chri5tia** [comment]
After 4/3 sync, work needed:
- [ ] API key protection
- [ ] Alternate benefit names: allow one
- [ ] Remove Acronyms
- [ ] Build example taxonomy vocabulary for legislation and link to it
- [ ] Add example Benefits to tugboat environment
- [ ] Include character limit countdown

Pertaining to fields not yet reviewed/approved (after line 17 in spec):
- [ ] fix field order
- [ ] related forms should link to nodes
- [ ] fix guidance field, one per related form link

Roadblocks:
- [ ] Need decision from product about linking to related legislation (see 4/3 column notes)

**Comment by chri5tia** [comment]
Things for next check-in, to do, etc.:

- [ ] Form section groupings
- [ ] Select list or autocomplete? Recommend autocomplete for: related legislation, pre-requisite benefits, co-considered benefits, related VA forms, and anything else that has a selection list of options over 5-12

**Comment by chri5tia** [comment]
4/5 checkpoint notes

- working on the API field permissions, which uses an eventsubscriber, which should be in a va_gov_benefits module, which I am creating
- use paragraphs to combine the VA Forms and Form Help sections
- check in with Blake / design system for use of form widget for long lists, use autocomplete for now for pre-req, co-considered, related legislation. Send Jordan examples of each (multiselect, etc.)
- cut ticket to explore enhance multiselect lists, such as with using Daniel's suggestion of Chosen (https://harvesthq.github.io/chosen/) for benefit hub and to make available elsewhere
- Other items discussed on 4/3 progress can be viewed in [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13070#issuecomment-1496671135)

**Comment by jilladams** [comment]
Proposed Taxonomy description to show on the Taxonomy admin page: 
> Single source of truth for VA Benefits including official names, related legislation, related / pre-requisite benefits, application / eligibility notes, and related VA Forms.

This gets saved in code and _cannot_ actually be modified in the Drupal UI (though it makes you think it can). So edits should be made prior to PR merge if at all possible.

**Comment by chri5tia** [comment]
To expand on what @jilladams is saying: It looks like it can be changed in the UI but since it is part of the config sync, any changes made in the UI for this field will be overwritten unless they are committed to config sync. E.g. The UI is where I am putting it initially. I can try to exclude this field from config sync if we want to leave it up to the site admin to control. Let me know if you have any questions about that.

**Comment by chri5tia** [comment]
Pushed API lockdown code and custom va_gov_benefits module code. Also config changes as of the 3/5 checkpoint and most of the changes from the approval meeting today. Going over more finely especially with respect to translation. 

Working on re-labeling the "Name" field to "Official Benefit name" and locking it down.

**Comment by davidmpickett** [comment]
Notes:

- The name of the vocabulary should be "VA Benefits" to match the name "VA Services"

![Screenshot 2023-04-07 095048](https://user-images.githubusercontent.com/51967950/230629856-c096d2ec-ea81-4537-8bac-9157669a5e6c.png)

- When attempting to add a pre-requisite benefit to "runudrifreclenadriwronokulocacrulachadudipanilaj" I got this error message:

![Screenshot 2023-04-07 095343](https://user-images.githubusercontent.com/51967950/230629864-2fef819b-556e-4f46-9e5d-6e0fea9945c7.png)

**Comment by davidmpickett** [comment]
- Logged in as a Content Admin I can't add an Official Benefit name. Per the spec, I should be able to. Maybe that was an intentional change, just noting this discrepancy

![screencapture-cms-i7n92wfzswpe358hivrspihf2ntzshz](https://user-images.githubusercontent.com/51967950/230632244-10bcdcb9-da50-44a5-97e4-9535838f264d.png)

**Comment by davidmpickett** [comment]
Why can't I add wre as a co considered benefit to clatawrir?

![Screenshot 2023-04-07 103218](https://user-images.githubusercontent.com/51967950/230635882-22202f80-227c-4dd9-b9e8-7a78feaad911.png)

**Comment by chri5tia** [comment]
It may either be because I have it preventing circular references, which in this case is probably not a good thing, or a bug with the module I used to generate content. I noticed things with the devel generate being a little weird but I'll double check the entity reference settings.

**Comment by chri5tia** [comment]
> * Logged in as a Content Admin I can't add an Official Benefit name. Per the spec, I should be able to. Maybe that was an intentional change, just noting this discrepancy
> 
> ![screencapture-cms-i7n92wfzswpe358hivrspihf2ntzshz](https://user-images.githubusercontent.com/51967950/230632244-10bcdcb9-da50-44a5-97e4-9535838f264d.png)

Dave C. Mentioned not wanting to allow this name to be changed in favor of archiving and recreating a new term. Let me know your thoughts. I might have gotten lost in translation for the final spec.

**Comment by chri5tia** [comment]
Something I missed is enforcing uniqueness for the taxonomy term e.g. Official benefit name. I noticed that we are also able to create more than one VA Service with the same name as well. It may be worth installing this module:
https://www.drupal.org/project/taxonomy_unique

**Comment by chri5tia** [comment]
@swirtSJW I was trying to figure out how to apply this to the core taxonomy term name field, which isn't managed in the UI. Any ideas?

**Comment by chri5tia** [comment]
Close out notes:

Added field group headers to [the spec](https://docs.google.com/spreadsheets/d/1gP6x-QLFRrJlLWdCEE1COAZXU-kRRmFKSc0sIlc_tyM/edit#gid=0)

Things moved to their own tickets:
- [ ] Unique taxonomy term/Official benefit name entries
- [ ] Explore enhancing multi-select lists using Chosen (https://harvesthq.github.io/chosen/) for benefit hub and to make available elsewhere; will need design system team input
- [ ] Taxonomy editorial workflow with revision history: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13141
- [ ] Change label and help text of Taxonomy name property (Official benefit name)

**Comment by jilladams** [comment]
@chri5tia is "Change label and help text of Taxonomy name property (Official benefit name)" still an open item? I thought I saw during demo that that was handled. 

Otherwise, @wesrowe FYI - open items here we need sign off from you that we are ok to ticket those pieces separately and close this out.

**Comment by chri5tia** [comment]
That is done. If we don't already have a ticket for it, we don't need to. I'll rearrange my notes.

**Comment by chri5tia** [comment]
Demo: https://cms-i7n92wfzswpe358hivrspihf2ntzshzp.ci.cms.va.gov/admin/structure/taxonomy/manage/va_benefits_taxonomy/overview

**Comment by chri5tia** [comment]
In hind-sight, this was an 8 or 13 because it was more than laying the tracks.

**Comment by wesrowe** [comment]
Meets ACs for Ph 1. Closing.

**Comment by swirtSJW** [comment]
> @swirtSJW I was trying to figure out how to apply this to the core taxonomy term name field, which isn't managed in the UI. Any ideas?
> 
> Update: I need to prevent the term name from being duplicated. I am not understanding what this service is doing on the VA Services end. You are still able to create duplicate VA Services.
> 
> ![Screenshot 2023-04-10 at 3 40 05 PM](https://user-images.githubusercontent.com/22764938/231012580-d98222e1-d858-4033-94d6-fdaafad2978a.png)
> 
> Taxonomy Unique module does this:
> 
> ![Screenshot 2023-04-08 at 6 59 34 PM](https://user-images.githubusercontent.com/22764938/231012174-bece2e1a-85f4-406c-82f1-2173da181e8d.png)
> 
> I don't want to add another module if we don't need it so is it possible to use the existing pattern in this way?

This should be covered by 
![image](https://user-images.githubusercontent.com/5752113/234086928-0ef4f59d-c4aa-4576-a8eb-162d17b9a7c5.png)
