### ISSUE TITLE
Support Yellow Ribbon Search Tool

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13099]
### User Story or Problem Statement

AS A Veteran or Beneficiary
I WANT the content and functionality of the Yellow Ribbon tool to be current
SO THAT I both have access to current data and feel confident that it's accurate.

## Acceptance Criteria
- [ ] Data stays current
- [ ] UI is current, e.g., indicates current school year
- [ ] Tool continues to function well
- [ ] Tool has health monitoring in place to prevent silent failures for Veterans

  
### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
IIR team owns Yellow Ribbon tool. These tickets live in their repo now. Closing.
