### ISSUE TITLE
Alt Text Field Prototype

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13103]
### Problem Statement

How might we improve the image upload editorial interface to allow editors to add better, more useful alt text for the images they are uploading?

### Affected users and stakeholders

* CMS editors of all products

<link to any existing research or data supporting this>

### Hypothesis

We believe that by updating the editorial interface and focusing on 3 key areas, we will be able to increase the quality of the alt text for uploaded images. We'll know that to be true when we run the report of alt text metrics and compare statistics against previous statistics. 

We will be focusing on:
- use of filename
- use of redundant phrases (i.e. "image of", "photo of", etc.)
- length of alt text

## Assumptions
- We assume that the use of filename in the alt text field will be reduce to 0%
- We assume 85% of images upload will not use redundant phrases 
- We assume that 90% of images uploaded will have succinct alt text

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by laflannery** [comment]
@maortiz-27-80 I think it makes sense that we close this epic since all the tasks are done and we moved onto [the next epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15785). Does that make sense? CC: @BerniXiongA6

**Comment by maortiz-27-80** [comment]
Yes, and thanks, @laflannery !  Closing this EPIC in favor of [Epic 15785](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15785). cc: @BerniXiongA6
