### ISSUE TITLE
Create Proposed Lagoon Production Architecture Diagram draft

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#13111]
## Description
In preparation of Lagoon implementation we need to create a proposed production architecture.  This will be informed by previous conversations we've had with Amazee.io about how we currently architect our projects around the existing network architecture. Additionally, this will be informed by Lagoon's limitations and verbal agreements to extend Lagoon beyond those limitations. The goal is to use the existing diagram and expand the details to describe the architecture that will be in production.

```[tasklist]
# ACs
- [x] Update existing architecture diagram and update/add necessary details for implementation
- [x] Lagoon Production Architecture diagram is created
```

```[tasklist]
### Tasks
- [x] Decide where diagram will live - Lucidchart
- [x] Create Lucidchart diagram link - https://lucid.app/lucidchart/f73e79e3-a097-4e99-9157-86b18b89847a
- [x] Create high level architecture diagram - Nate MVPd this
- [x] Export PNG and put in our Confluence
- [ ] Review with Team and/or PO
```

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ndouglas** [comment]
Yah, first I thought it was everything, and then I thought "oh crap, maybe they just mean prod bc duplication" and then I thought "well, that leaves out lagoon core" and then I realized it probably meant everything. So yeah, I understood that, but it took me a bit to get there.

I experienced suffering working on the RfC when it came time to draw a diagram. It sucked, again despite having a lot of experience with similar languages. But more than that, there's the problem that any "complete" system diagram, especially for something like this, is going to be an absolute nightmare. It's gonna make that [CNCF landscape image](https://user-images.githubusercontent.com/3083270/34234634-4fb2f894-e5ba-11e7-8515-f9e63548b4ba.png) look like my yard did when I lived in Las Vegas.

Thanks!

**Comment by olivereri** [comment]
Do you mean if we don't break architecture down into multiple diagrams it'll look like the CNCF landscape? Or no using something like draw.io will make super hard to manage? If it's too much of hassle we should reduce the scope. What I'm hoping that we can get to is have a map or guide of what we're going to do if we get this funded.

**Comment by ndouglas** [comment]
I mean that I don't think there's One True Representation. There's one "system" here (in the sense of a set of things), but it's actually multiple systems (in the sense of interacting components) that overlap in time and space. For instance, event flow, CI/CD, editor HTTPS requests, upstream/downstream dependency requests, logging/monitoring, etc. 

We can create a diagram of the Lagoon Core components as deployed, but we can't capture the interactions between the components within a single diagram without creating an incomprehensible mess.

If the scope can/should be reduced, that's fine, but I think there is value in creating multiple diagrams that cover each of these different aspects. For instance, in explaining exactly how HTTPS requests from editors vs. developers on SOCKS are routed into the prod Lagoon Remote instance and how these are handled by the application. I think these would be useful to the customer, to us when we're deploying the thing, people troubleshooting weird issues (e.g. that thing that happens occasionally when DNS issues break CAG/GFE browsing but not SOCKS, or vice-versa), other engineers trying to understand the system, etc.

I'm fine with being talked down, though. I'm probably generating far more work than can reasonably be accomplished.

**Comment by olivereri** [comment]
Ok I see what you mean. I didn't really grasp how complete "complete" would be. I do think eventually we should have all of those diagrams. But what I'm thinking of is: what's the minimum set of diagrams that could get us started when it's time to implement.  A visual roadmap of what we're going to install and where and how they link together. I really think it's a mix of the High-level diagrams with some simple input/output centric information in there.  Shooting for MVP I think is our best bet.

**Comment by ndouglas** [comment]
Yeah, totes.

![cool-doge-doge](https://user-images.githubusercontent.com/1318579/230434448-30282c93-0175-49f8-90d0-2297ce06620f.gif)

I'll do the thing.

**Comment by olivereri** [comment]
Definitely think everything else should be in a Diagram/Documentation epic and this would fit inside it as the first iteration.

**Comment by ElijahLynn** [comment]
Good discussion. I was thinking of an initial high-level overview expanding on Nate's Mermaid diagram in another issue comment. Are either of you working on a Draw.io diagram now? Can you share a link if you are? I was about to start one up, but was thinking Lucidchart since everyone has accounts for that. Do you prefer Draw.io?

**Comment by ElijahLynn** [comment]
I'd also like to propose that we put our docs for this in the Platform-CMS (PCMS) Confluence Space. The cycles are too lengthy for using the repo /READMES. 

I made a starting page here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2590441949/Lagoon+Docs. If we can't use that because not everyone has accounts then we could use this space on the A6-funded Confluence > https://va-gov.atlassian.net/wiki/spaces/VAGOV/overview.

**Comment by ElijahLynn** [comment]
Oh, I see, Draw.io you have to choose a storage backend, e.g. Dropbox, GitHub, local etc. I don't think that will work for ongoing collaboration that well. I'm gonna work on this on Lucidchart, we should all have licenses for that. We can refactor it to Draw.io if that doesn't work.

**Comment by ndouglas** [comment]
I started a Draw.io version of this earlier. Lucidchart might be a better choice longterm, though. I was mostly just thinking about an MVP more-detailed version of the OG mermaid chart with the specific K8s services and which EKS clusters they'll inhabit. I'm not able to access the Lucidchart links (server error), so I don't know how far you've gotten with this.

**Comment by ndouglas** [comment]
As noted above, I can't seem to access Lucidchart. I clicked the link in the OP issue but I can't edit anything - it says I need a Lucid Suite license?  Also, I don't see any shapes - I don't know if that's because there's nothing there or if I don't have permissions to view it or something.

Anyway, in the meantime, I've created the following:

![Screenshot 2023-04-07 at 11 53 25 AM](https://user-images.githubusercontent.com/1318579/230639782-591cc116-c51f-4346-9f15-63b4a3e242de.png)

If you'd like to play with it or finish it up, I threw it in Drive: https://drive.google.com/file/d/1uFBGNZxamMlpMtrFFm22n8Mj8poiwYB4/view?usp=share_link

I don't know if we're using Lagoon to manage other workloads; e.g. if we intend to use it to manage a separate content-build test service, etc. I left some space there just in case.

I'm going to take a break and eat lunch, and I won't change the above diagram without notice.

**Comment by ElijahLynn** [comment]
Thanks Nate, that is a great starting point and I like that you got Nexus in there too. 

I think we just got you added to Lucidchart, and I imported your lagoon.drawio file and here is the link > https://lucid.app/lucidchart/f73e79e3-a097-4e99-9157-86b18b89847a.

**Comment by ndouglas** [comment]
Thanks, @ElijahLynn -- I'm now able to log in and I see that a large amount of stuff is now shared with me 🎉  

However, I'm not able to access the link you posted:

![Screenshot 2023-04-10 at 8 46 18 AM](https://user-images.githubusercontent.com/1318579/230903946-3abd13e6-27bb-4ebc-86fb-53cb4a815a7e.png)

Is it possible that there are some controls on this that are excluding/not including me?

**Comment by ndouglas** [comment]
I imported it (again?) and dragged it in here:

![Screenshot 2023-04-10 at 9 19 45 AM](https://user-images.githubusercontent.com/1318579/230908815-3c878949-8b8c-4f0a-ae53-3922334b3837.png)

Unfortunately, it looks like it loses some granularity of control. It seems like layers are transformed into objects and the internal relationships/arrangements are removed (???). So for instance I can no longer move the individual components within Lagoon Core, etc, and if I try to resize a VPC, it is resized as if it is an image, rather than resizing the outer bounding box.

I'm onboard with using Lucidchart in the future, but I think I should probably finish this up in Draw.io given that the sprint ends tomorrow and this is a sprint commitment. It's comparatively minor to just recreate the graph in Lucidchart if we need to use this work as a foundation for future diagrams.

**Comment by ndouglas** [comment]
Here's where I'm at now -- the thing I haven't really captured, and I know that you really wanted to, Eric, is the complete flow for PRs from merge to deployment.

![Screenshot 2023-04-10 at 3 46 35 PM](https://user-images.githubusercontent.com/1318579/230984947-73099ced-e669-4393-a19a-5f14bb8e3901.png)

https://drive.google.com/file/d/1dKfC3XlEiz1zxE2otRfiZCKczwYqwDnW/view?usp=share_link

I'm struggling to think of how to put that in a way that fits into this diagram. That might be because this sucks or I'm unimaginative 😕

**Comment by olivereri** [comment]
> I'm struggling to think of how to put that in a way that fits into this diagram. That might be because this sucks or I'm unimaginative 😕

It could also be a bad request too. I see how it could get kind of messy but I think it'd kind of resemble the github webhook to Tugboat.  I'll need to look at the Lagoon documentation to make sure, but I think Github via webhook would communicate with Core and it would fire off a deployment to the Staging remote.

**Comment by ndouglas** [comment]
Yeah, I think you're right. It's definitely getting crowded in here.

I probably should've done this up first in `neato`. It'd be even uglier, but I think it would've helped me to lay things out in terms of which things connected to what. As it was, I ended up putting things with the most connections (like the API services) near the centers of the groups, making them much harder to cleanly connect to other things. That'd probably be obvious to anyone else capable of fogging a mirror...

![Screenshot 2023-04-10 at 7 25 21 PM](https://user-images.githubusercontent.com/1318579/231017841-bdef2d27-20d5-4e09-b5f2-1c6dd989b678.png)
