### ISSUE TITLE
Drupal/Accessibility Training

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#13168]
### User Story or Problem Statement

As an new Drupal editor, I need good training materials so I can learn how to use Drupal correctly and efficiently to create accessible content.

### Affected users and stakeholders

* CMS editors of all products

### Hypothesis

We believe that creating more/better training materials will allow editors to use the CMS more efficiently, lessen their confusion with various components and lead to fewer accessibility issues within the content. 

**(How will these assumptions be validated?)**
Unclear right now - this will most likely be determined once we identify exactly the training materials/areas we are going to target and improve upon.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
