### ISSUE TITLE
Facilities: Migrate "phase 2" react components targeted for deprecation

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13174]
**TODO: update after audit with any new items** as of 4/5, this is a partial list, [backstory in Slack](https://dsva.slack.com/archives/C0FQSS30V/p1680722907766189)

### User story
AS A PO for PW
I WANT my products to move from "phase 2" deprecated react components to design system web components
SO THAT VA can stay on the path to upgrade the DS to USWDS 3.0

### Engineering notes / background
- Original slack convo here: https://dsva.slack.com/archives/C03R5SBELQM/p1680033521847529
- Migration docs here:  https://design.va.gov/about/developers/using-web-components#how-to-migrate-to-web-components

### Audit results: 
alertBox:
 These should be covered by migration script and will just need to be run against the script and confirmed confirmed (check corresponding test files as well) (low complexity)

- src/applications/static-pages/facilities/FacilityApiAlert.jsx:

loading-indicator: 

These should be covered by migration script and will just need to be run against the script and confirmed confirmed (check corresponding test files as well) (low complexity)
- src/applications/static-pages/facilities/BasicFacilityListWidget.jsx:
- src/applications/static-pages/facilities/FacilityAppointmentWaitTimesWidget.jsx:
- src/applications/static-pages/facilities/FacilityDetailWidget.jsx:
- src/applications/static-pages/facilities/FacilityListWidget.jsx:
- src/applications/static-pages/facilities/FacilityMapSatelliteMainWidget.jsx:
- src/applications/static-pages/facilities/FacilityMapWidget.jsx:
- src/applications/static-pages/facilities/FacilityMapWidgetDynamic.jsx:
- src/applications/static-pages/facilities/FacilityPatientSatisfactionScoresWidget.jsx:
- src/applications/static-pages/facilities/OtherFacilityListWidget.jsx:
- src/applications/static-pages/facilities/vet-center/NearByVetCenters.jsx:

### Quality / testing notes
These changes will affect over N individual components. Care should be taken to spot check component functionality especially where unit test coverage is not sufficient 

## Acceptance criteria
- [ ] All listed components are cut over to new web components
- [ ] There are no regressions for any component functionality
- [ ] Unit tests are updated where necessary and all tests pass

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [X] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
Cross-reference: Public Websites audit that produced the start of this list: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13098
