### ISSUE TITLE
Deprecate "featured" UX and combined workflow for stories and events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1318]
### User Story or Problem Statement

* The current workflow for featuring content is inconsistent, confusing, ambiguous for FE development. 
* Events do not currently make use of Featuring effectively, and the future of Events won't use the same mechanism for Featuring. 
* Stories do need Featuring, and are primarily used by Facilities.

### Decision point, 5/11/23
Public Websites owns the current functionality and its destiny. @davidconlon 's vision is that Facilities envisions a future for better featuring functionality for Stories, only, and Public Websites then deprecates the old functionality.

Plan of record:
* Facilities devises a shiny new future for Featuring stories.
* Facilities will build that. 
  * Public Websites will own change management of deprecating the old feature, and add a warning to the UI when we're close enough, to warn editors of the upcoming change. This epic will track that work.
* The featuring capability will not be added back to Events. 
* Facilities owns related bug fixes required meantime. (I think I remembered this correctly, @mmiddaugh / @davidconlon , but please correct me if not.)

<details>
Story fieldset, main column
![Create_Story___VA_gov_CMS](https://user-images.githubusercontent.com/643678/103355853-5c030000-4a7d-11eb-9785-58ed3efdc875.jpg)

Event fieldset, right rail
![Create_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/103355962-a4bab900-4a7d-11eb-89f5-4590165a4096.jpg)
</details>

### Affected users and stakeholders

* VAMC editors
* Outreach hub editors

**Comment by jilladams** [comment]
@EWashb Per Dave sync 6/10 to scrub events backlog, this epic (when prioritized) should also address: 
1. Editorial confusion around governance of featured items -- who can feature, who reviews what gets featured, any rules of the road, who can expire a featured item, etc. This is not ticketed. 
2. Editorial confusion around which events to feature -- how to decide what good candidates are, etc. I think #6814 should address that?

**Comment by jilladams** [comment]
FYI to interested parties (@kmariepat-cityfriends @wesrowe @mmiddaugh @EWashb @swirtSJW ): discussed ownership of this epic 

* Events needs to get rid of the Feature capability on the Editor interface. 
* DaveC's vision is: remove the Featuring from both Stories and Events. 
  * Develop the new functionality as a per-product means of featuring Stories vs. Events. 
    * Featuring will not be re-added to Events.
    * If Facilities related products need 
 Facilities will own the future of Featuring Stories. 
  * Update UI to warn re: deprecation. 
  * 
* Therefore: each product that has been using it needs to determine how will we Feature it differently. 
* Blocked by Fac work to devise a new path forward for stories


Tasks: 

- [ ] Close irrelevant tickets in this epic that we'll no longer concerns ourselves with per product
- [ ] Rewrite this epic as a "Deprecation" epic owned by PW for the big picture problem
- [ ] New epic for the Facilities specific work to rethink and

**Comment by swirtSJW** [comment]
Some of those are essentially triaging the current state of brokeness to make it more understandable.   They are likely separate from a "envisions a future for better featuring functionality".   In the past we have hashed out some good ideas for a new path forward on Featured, including the one that both DaveC and @davidmpickett suggested yesterday.  There are others. 

For the most part there is no perfect solution they each have drawbacks but any one of them are better than where we are right now.    I am happy to discuss or enumerate them.

**Comment by swirtSJW** [comment]
I began enumerating them here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13695

**Comment by stefaniefgray** [comment]
Can update editor @ VA Minneapolis in original ticket once complete: https://va-gov.atlassian.net/browse/VAHELP-4738

**Comment by FranECross** [comment]
@jilladams Does the PW team own "Stories"? (I'm unclear what those are). I see that several tickets were moved to a Facilities Epic, and wondered if this epic and associated stories belong to a different team, or if this work is still viable if not? Thanks!

**Comment by davidmpickett** [comment]
> @jilladams Does the PW team own "Stories"? (I'm unclear what those are). I see that several tickets were moved to a Facilities Epic, and wondered if this epic and associated stories belong to a different team, or if this work is still viable if not? Thanks!

According to the [product portfolio mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1646745279937/9a5570c420939d84e875e8334fd73073e3a3971b?wid=0-1705622152348), Facilities owns "Stories." Theses are blog-style articles that VAMCs use. Here's an example: https://www.va.gov/western-colorado-health-care/stories/i-didnt-expect-va-providers-to-get-in-a-van-and-drive-to-my-house/

The reason this epic is a little messy is that Stories and Events both have a "featured" functionality which determines what is shown on [VAMC home pages](https://www.va.gov/western-colorado-health-care/). I guess the question is whether the "Featured" functionality is considered part of "Events" and "Stories" or specific to "VAMCs"?

**Comment by jilladams** [comment]
Making things further messy: the idea here is that: 
1. Facilities is able to prioritize and build a plan for #11401. (in this epic)
    * Facilities will move Stories onto the new mechanism for featuring them
2. When that's done, the owner of Events can fully deprecate everything from the old Featuring workflow, as it pertains to Events. 
    * Events may transition to new IIR ownership before we get there.

**Comment by FranECross** [comment]
Closing ancient ticket

**Comment by jilladams** [comment]
@FranECross we need to keep this open for Facilities' sake, bc featuring on Stories is an active pain point. Reopening.

**Comment by FranECross** [comment]
Closing epic. All linked tickets are closed.

**Comment by jilladams** [comment]
Reopening - there are a few open tix still, and we haven't changed / deprecated the Featured flow yet.
