### ISSUE TITLE
Text field soft character limits

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#13234]
## Background
Some text fields in the CMS have character limits. This is a problem for translations, because when text is translated into many languages, the number of characters in the translation can be 20-30% larger than the English version.

The CMS needs a way to provide character limit guidance for fields for English, while allowing the same fields to contain larger amounts of characters for other languages. Additionally, we need to figure out how to handle existing fields. 

### User Story or Problem Statement
Problem description: How might we maintain character limits on text while allowing translations to expand?

### Affected users and stakeholders
* CMS developers
* Content team

## Acceptance Criteria
- [ ] Text limits are clearly communicated and enforced on text fields for English
- [ ] Text limits are not enforced for non-English versions
- [ ] Existing text fields have been updated so that translations are allowed to be longer than the English source

## Design principles
Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by BerniXiongA6** [comment]
Per @timcosgrove regarding this ticket -- it'll need to be completed before we can continue to make progress on our CMS Translations initiative. cc: @maortiz-27-80 @EWashb @ndouglas
