### ISSUE TITLE
Testing the presence of the FE Lovell menus

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13252]
## User Story or Problem Statement

As a FE engineer I need to know when a menu related change prevents Menus showing up on Lovell VA or Lovell Tricare.

Lovell is like a canary in a coal mine.  If a structural change takes place with menus, Lovell will be the first to die.

Related discussion in slack https://dsva.slack.com/archives/C0FQSS30V/p1681311679298799

## Acceptance Criteria
- [ ] I expect to have test coverage that will prevent PR from passing if the Lovell menu on https://www.va.gov/lovell-federal-health-care-tricare/about-us/ is missing 
- [ ] I expect to have test coverage that will prevent PR from passing if the Lovell menu on https://www.va.gov/lovell-federal-health-care-va/about-us/ is missing 

## Implementation steps
We're almost certainly looking at an end-to-end test. A recent regression in this space was the result of something that a unit test on the content-build side would not have caught. We should implement an end-to-end test that ensures the Lovell main pages have sidebar menus that are populated with at least _some_ content.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by ryguyk** [comment]
I added some notes to the original description around how we can likely approach this:

**Comment by kmariepat-cityfriends** [comment]
@maxx1128 this is in Peer review, is the PR still be reviewed by a dev?

**Comment by maxx1128** [comment]
> @maxx1128 this is in Peer review, is the PR still be reviewed by a dev?

It's currently waiting review by a dev. I messaged Ryan about reviewing it earlier today when I got the tests passing.
