### ISSUE TITLE
Planning Increment #4 2023 Send

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13313]
## Description
As a VA PO, I want consistently measure actionable and behavioral impact of the ongoing CMS enhancements for the breadth of the editor audience, so that I can better determine areas of impact for upcoming planning increments. 

As a UX Researcher and/or Designer, I want to continually know and understand our editor audience, so that I can better apply human-centered design concepts.

## Hypothesis
**HMW** display ongoing editor sentiment as well as a better understand the typical hurdles, wins for the breadth of editors?

## Acceptance Criteria
- [ ] Baseline survey results reviewed
- [ ] Areas of watch identified with PM, PO. 
- [ ] Determine if additional questions or questions removed while retaining question-by-question continuity. Approval by PO.
- [ ] Review with VHA DM. Get approvals.
- [ ] Send and collect feedback.
- [ ] Analyze and communicate findings including comparables from baseline survey.

**Comment by EWashb** [comment]
I'm not sure what the intention of this ticket was
