### ISSUE TITLE
Income Limits Data Export and Import: local and manually to Staging & Prod

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#13320]
## Description

AS A Veteran
I WANT income limits data populated in vets-api going back a number of years
SO THAT I can get the limits I need to utilize benefits.

After creating the database tables in vets-api under #13319, we can move to importing the datasets into them. 

## Engineering Notes
Source .xlxs documents are on Google Drive [here](https://drive.google.com/drive/folders/1iTkVlOdcFum01nZrhaOxkMZSX_GeMRcH).

This [article](https://medium.com/@amanahluwalia/uploading-massive-csvs-into-rails-using-active-record-import-8f382d06cea1) on migrating from .csv to Active Record models may be helpful.

### Tasks
- [x] Work with Joshua Faulker to obtain data dumps from the VES Oracle database
  - Joshua delivered in Excel format (in A6 google drive)

- Blocker: files need to live on S3 #13343
  - convert Excel files to CSV (save as...)
  - ID (and other "integer" columns are comma-separated thousands formatted; need to set correct format before exporting to .csv in Excel file
- build additional models/objects to support tables
- script to parse CSVs into rows of db - Active Record 
  - script needs to be able to interrupt and retry
  - script knows path to S3 bucket
- Test import locally
- sidekiq job to run the script

## Acceptance Criteria
- [x] Local vets-api instance(s) populated with data from data dumps
- [x] Sidekiq job is created to run script to import data to Staging & Prod
- [x] Staging database is populated with data from data dumps - with Platform assistance to run the Sidekiq job
- [x] Production database is populated with data from data dumps via Sidekiq job
- [x] Documented the major steps that will need to be followed periodically (annually/quarterly)

**Comment by olivereri** [comment]
Connection Test Output to VES Oracle Database from, CMS Prod, CMS Staging, and Sandbox:

```
dsva-vagov-staging-vpc
[root@ip- ~]# aws s3 cp s3://dsva-vagov-staging-config-bucket/cms-test/ConnectionTest.jar . --region us-gov-west-1
download: s3://dsva-vagov-staging-config-bucket/cms-test/ConnectionTest.jar to ./ConnectionTest.jar
[root@ip- ~]# yum install java-1.8.0-openjdk
[root@ip- ~]# java -jar ConnectionTest.jar
Oracle JDBC Driver Successfully Registered!
Connection Failed! Check output console
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:858)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at CreateDataExtract.getConnection(CreateDataExtract.java:188)
        at CreateDataExtract.testDBConnections(CreateDataExtract.java:213)
        at CreateDataExtract.run(CreateDataExtract.java:121)
        at CreateDataExtract.main(CreateDataExtract.java:48)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:571)
        at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:548)
        at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:682)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:309)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1600)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:591)
        ... 10 more
Caused by: java.io.IOException: Socket read timed out, socket connect lapse 30003 ms. vessds.cs3zmbhhrp2w.us-gov-east-1.rds.amazonaws.com/10.248.132.238 1521 30000 1 true
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:233)
        at oracle.net.nt.ConnOption.connect(ConnOption.java:174)
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:510)
        ... 15 more
Caused by: oracle.net.nt.TimeoutInterruptHandler$IOReadTimeoutException: Socket read timed out
        at oracle.net.nt.TimeoutSocketChannel.handleInterrupt(TimeoutSocketChannel.java:254)
        at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:103)
        at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:77)
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:192)
        ... 17 more
java.lang.NullPointerException


dsva-vagov-prod-vpc
[root@ip- ~]# java -jar ConnectionTest.jar
Oracle JDBC Driver Successfully Registered!
Connection Failed! Check output console
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:858)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at CreateDataExtract.getConnection(CreateDataExtract.java:188)
        at CreateDataExtract.testDBConnections(CreateDataExtract.java:213)
        at CreateDataExtract.run(CreateDataExtract.java:121)
        at CreateDataExtract.main(CreateDataExtract.java:48)
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:571)
        at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:548)
        at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:682)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:309)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1600)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:591)
        ... 10 more
Caused by: java.io.IOException: Socket read timed out, socket connect lapse 30003 ms. vessds.cs3zmbhhrp2w.us-gov-east-1.rds.amazonaws.com/10.248.132.238 1521 30000 1 true
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:233)
        at oracle.net.nt.ConnOption.connect(ConnOption.java:174)
        at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:510)
        ... 15 more
Caused by: oracle.net.nt.TimeoutInterruptHandler$IOReadTimeoutException: Socket read timed out
        at oracle.net.nt.TimeoutSocketChannel.handleInterrupt(TimeoutSocketChannel.java:254)
        at oracle.net.nt.TimeoutSocketChannel.connect(TimeoutSocketChannel.java:103)
        at oracle.net.nt.TimeoutSocketChannel.<init>(TimeoutSocketChannel.java:77)
        at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:192)
        ... 17 more
java.lang.NullPointerException

dsva-vagov-sandbox-vpc
[root@ip- bin]# java -jar ConnectionTest.jar
Oracle JDBC Driver Successfully Registered!
Connect Success! : vpid: 500007
on rec 0
on rec 1
Completed!
```

**Comment by jtmst** [comment]
In progress,  will need to carry over to next sprint

**Comment by jilladams** [comment]
Updated scope to include Prod, and closing #13382 as a dupe.

**Comment by jtmst** [comment]
Local environment issues with test runners are not allowing me to continue work on this ticket.  I will continue troubleshooting with platform today, and once I am able to resume the ticket will be completed shortly after.

**Comment by jtmst** [comment]
These jobs have been run and verified in all environments: https://dsva.slack.com/archives/CBU0KDSB1/p1684424606834409
