### ISSUE TITLE
PW Sprint 83 plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13344]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626
Design / Research:
- [ ] #11102 () - Design
- [ ] #13380 (5) - Research 🎯 

Engineering:
- [ ] (Eric Oliver dependency ~2hrs) #12348 (5) - BE
- [ ] #13319 (5) - Ruby
- [ ] #13343 (3) - BE
- [ ] #13320 (8) - Ruby
- [ ] (stretch; follow-on to 13320) #13382 (3) - BE

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628
- [ ] #13075 (5) - BE 🎯 
- [ ] (PoC Drupal) #13143 (8) - BE
- [ ] (PoC UX) #13461 (needsrefine) - Design
- [ ] (stretch) #13207 (3) - BE

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170

@wesrowe TODO: Finalize discussion around what survey tool to use for "prototyping" question flow for research. 

- [ ] (blocked on "who" discussion with Danielle) #13233 (needsrefined) - Research

### 4. Expand Q&A Reusability https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780
Not yet prioritized:
- [ ] (stretch) #10936 (3) - BE
- [ ] (stretch) #10937 (needs refining) - FE

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. Not yet actionable. (DST building their Ph1 (sample form) in Q2.)

- [x] #13135 (5) - FE - may need broken up into multiple tickets / sprint sized 
- [x] #13175 (5) - FE 🎯 

### Other Q2 priorities not in motion

- Translation in R&S, Hubs https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- Header/footer redesign - Awaiting info / green light for kickoff

### Post-MVP Homepage 
Future:
- (needs Dave/RyanT input; hard-code okay?) #12292

### Cerner API deprecation support
- [ ]  (BLOCKED) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

## Other PW Priorities

Other priorities
- [ ] #12339 (5) - FE 🎯 
- [ ] #11256 (3) - FE
- [ ]  (stretch) #11260 (needs new estimate from Josh) - FE
- [ ]  (stretch) #13084 (needs refining) - FE/BE
- [ ]  (stretch) #12932 (8) - FE (Daniel)

Forms monitoring/errors:
- Tickets are in stages of refinement; no immediate options to prioritize

### Content / IA priorities
- [x] #13186
- [x] #13460 
- [ ] #11444  - finish the fixing with an option from last comment

Epic of upcoming redirects not yet in our board:
Team repo #53921

### Tech debt & Defects
- [ ]  #11448 (5) - FE
- [ ]  (carryover from s78; blocked on test data from 12932) #10307 (~5? remain) - FE
- [ ] (stretch) #13124 () - UX Design

### User research and UX pipeline development

- [ ]  (stretch) #12791 (8) - Research
- [ ]  (stretch) #12601 (5) - Research
- [ ]  (stretch) #12719 (5) - Research

**Comment by jilladams** [comment]
Updated to remove what's done, note what we _think_ will finish in S82 with a [x], and added the Benefits header thing to Post mvp section.

**Comment by wesrowe** [comment]
Note on IncLim BE work: Dave asked that #13320 be added as a goal. He is aware that this is a 13-point critical path (8 pts dependent on 5 pointer) and indicated making it a goal won't affect sprint acceptance.
