### ISSUE TITLE
Migrate additional NCA fields from Facilities API to CMS

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#13362]
## User Story or Problem Statement

Per #13123 , map the NCA fields from the Facilities API in Lighthouse to the CMS fields created in #13340 

## Acceptance Criteria
- [ ] I expect if a facility is recognized as missing during the migration, it should auto archive
- [x] I expect that the following fields are mapped as shown:

| Drupal field | Facilities API Selector | Notes |
| ------------ | ---------------------- | ----- |
| field_nca_classification | properties/classification | new text (plain) field |
| field_link/uri | properties/website | uri of existing Link field |
| field_link/title | facility name | title of existing Link field |
| field_timezone | properties/time_zone | new text (plain) field |
| field_mailing_address | properties/address/mailing | new Address field |
| field_address | properties/address/physical | new Address field |
| field_fax_number | properties/phone/fax | existing telephone field |
| field_phone_number | properties/phone/main | existing telephone field |
| field_office_hours | properties/hours | existing node field |

### More complex imported fields

<details><summary>field_link</summary>

```
source:
  fields:
    -
      name: field_link
      label: 'Link'

process:
  field_link/uri:
    -
      plugin: str_replace
      source: field_link
      search: 'NULL'
      replace: ''
  field_linkl/title:
    -
      plugin: str_replace
      source: <properties/name> TODO: Clarify this title
      search: 'NULL'
      replace: ''
```

</details>

<details><summary>field_mailing_address</summary>

```
source:
  fields:
    -
      name: city
      label: city
      selector: properties/address/mailing/city
    -
      name: state
      label: state
      selector: properties/address/mailing/state
    -
      name: zip
      label: zip
      selector: properties/address/mailing/zip
    -
      name: address1
      label: address1
      selector: properties/address/mailing/address_1
    -
      name: address2
      label: address2
      selector: properties/address/mailing/address_2
    -
      name: address3
      label: address3
      selector: properties/address/mailing/address_3
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

Combine API lines address_2 & address_3 into Drupal address line 2

</details>

<details><summary>field_address</summary>

```
source:
  fields:
    -
      name: city
      label: city
      selector: properties/address/physical/city
    -
      name: state
      label: state
      selector: properties/address/physical/state
    -
      name: zip
      label: zip
      selector: properties/address/physical/zip
    -
      name: address1
      label: address1
      selector: properties/address/physical/address_1
    -
      name: address2
      label: address2
      selector: properties/address/physical/address_2
    -
      name: address3
      label: address3
      selector: properties/address/physical/address_3
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

Combine API lines address_2 & address_3 into Drupal address line 2

</details>

<details><summary>field_phone_number</summary>

```
source:
  fields:
    -
      name: phone-main
      label: phone-main
      selector: properties/phone/main
process:
  field_phone_number:
    -
      plugin: str_replace
      source: phone-main
      search: Ext.
      replace: x
    -
      plugin: explode
      delimiter: x
    -
      plugin: callback
      callable: trim
    -
      plugin: concat
      delimiter: ' x'
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

</details>

<details><summary>field_office_hours</summary>

```
source:
  fields:
    -
      name: hours
      label: hours
      selector: properties/hours
process:
  field_office_hours:
    plugin: va_field_office_hours
    source: hours
```

Refer to work done in 
va_gov_migrate/config/install/migrate_plus.migration.va_node_facility_vet_centers.yml
for more details

</details>

- [ ] I expect that migration of NCA content results in the CMS fields being correctly populated.
- [ ] I expect that any Facilities product documentation related to NCA data has been updated.

## Implementation steps
See above

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `Facilities`

**Comment by omahane** [comment]
> We also need timezone.

Are you saying we need to do some more processing for timezone? I did put it in the table.
![Screen Shot 2023-04-27 at 10 58 15 AM](https://user-images.githubusercontent.com/766573/234919306-4571edd8-3062-4e67-a1da-367fe2f1de9a.png)

**Comment by omahane** [comment]
Reminder to self:
- Not sure how to auto-archive
- Need to understand what should be done with country (which is being populated by default) if there's no address or one kind or another. Right now, we have country being set by default even if the rest of the address is null.
![Screen Shot 2023-05-25 at 4 58 18 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/f4acd583-2a92-4327-a7ef-4cf63493672f)

**Comment by jilladams** [comment]
From scrum: previous conversation had suggested that we change Facility Status to closed when archiving NCAs. However: we want to confirm that with @mmiddaugh @davidconlon -- we don't _need_ to do that, and it would destroy some data, so want to be sure. @kmariepat-cityfriends let's touch on this in refinement today.

**Comment by kmariepat-cityfriends** [comment]
From Dave P.
- An NCA facility that has been removed from the Facilities API
- action we're taking is auto-archiving the facility in Drupal
- question is should we also clear any text in the "Operating Status: more info" field?

**Comment by kmariepat-cityfriends** [comment]
Next Steps:
- Follow up with @swirtSJW when back from PTO to aligning on next steps regarding operating status. Need to understand the flow of data from an archived facility vs. when `removed from source`

**Comment by davidconlon** [comment]
re: NCA "removed from source"
Removing a cemetery is a bit of a process, so that's the first thing to consider, however, to answer the question re: clear any text in "Operating Status: more info" is irrelevant because that entry has already been removed from Lighthouse - that's how we know it's been "removed from source". So the one place that was publishing that information is no longer accepting that information.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends 
As Dave C mentioned, the data flow is not an issue because by the time we archive the facility, the facility is no longer anyplace to be "flowed".  The remaining issue is more of a human one.  When we have data in the CMS that says conflicting things, it leaves a continual mystery (cognitive overhead) that we try to minimize 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/dd220f3e-23f4-4f8d-b485-092c22c16b03)
