### ISSUE TITLE
Income Limits Data Export and Import: automated to Staging & Prod

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13382]
## Description

AS A Veteran
I WANT income limits data populated in vets-api going back a number of years
SO THAT I can get the limits I need to utilize benefits.

After creating the database tables in vets-api under #13319, we can move to importing the datasets into them. 

## Engineering Notes
blocked by https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13320

### Tasks

- schedule runs for (in all environments)
  - a time soon after merge for initial import
  - a sensible default (annual)

## Acceptance Criteria
- [ ] Sidekiq job is scheduled and has successfully run script to import data to Staging & Prod
- [ ] Staging database is populated with data from data dumps via Sidekiq job
- [ ] Production database is populated with data from data dumps via Sidekiq job

**Comment by jilladams** [comment]
ACs were partially covered in #13320, so included full ACs there and closing this as a dupe.
