### ISSUE TITLE
Update the operating status widget, to account for JSON encoding

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#13499]
## User Story or Problem Statement

As an editor of a field that will be JSON encoded and sent to a character-constrained field, I want to know when my content exceeds the constrained character count with that encoding, so that the data pushes correctly.

## Background
[Research of the field and how it might be changed](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13120#issuecomment-1507059269)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
Patch the contrib [textfield_counter](https://www.drupal.org/project/textfield_counter) module

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
@omahane @productmike this is described as impact to Fac, with VAMC tie. But: this is also tagged as needing a module upgrade that will block D10. Is Facilities the only consumer of this module? Do we need to prioritize this to unblock D10, or will CMS Team maybe take it on in the spirit of that? (In which case: we should add `CMS Team` label.)

**Comment by jilladams** [comment]
+ @edmund-dunn if this is on your radar re: the D10 question, as well.

**Comment by productmike** [comment]
@edmund-dunn It looks as if this module has been updated for D10. Can you confirm it has been and will be included in the d10 upgrade?

**Comment by productmike** [comment]
Temp placing this in the D10 testing epic to confirm with @edmund-dunn @tonytaylor how we should handle and who should own.
