### ISSUE TITLE
Change to how we manage and communicate flagged facility work

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#13508]
## User Story or Problem Statement

As a Facilities or help desk team member, I want to be able to readily see the status of a Flagged facility so that I know what the appropriate action is to take (if any).

### Adding flags
One recommendation could be to add the following flags:
Awaiting editor
Awaiting redirect 
Awaiting CSV 

When these flags are added or removed, a message in the revision log with a link to the appropriate Jira or GitHub ticket would provide anyone looking at either the view of flagged facilities or a specific facility information about its status.

### Parent ticket can move forward without CSV change
Along with these flags, we also think that we should make it clear that URL Change ticket is no longer a blocker to completing CMS work when we are past the URL redirect deploy and are only awaiting the CSV deploy.

From an end-user experience, there will be no noticeable change once the URL redirect has been made.

## Acceptance Criteria
- [ ] The following flags are available on node:edit
  - [ ] Awaiting editor
  - [ ] Awaiting redirect 
  - [ ] Awaiting CSV 
- [ ] The new flags are visible in the Flagged facilities view
- [ ] The URL change runbook has been changed to reflect that the CSV deploy is not a blocker to completing the parent ticket.

## Implementation steps

- Add flags (following the pattern of the current facility flags)
- Edit the flagged facilities view (kind of fiddly)
- Edit one 🤞 runbook

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
@kmariepat-cityfriends I added this ticket, and think that if we are going to make the change to the view anyway (in the form of the revision log), that we should also do this.

**Comment by omahane** [comment]
@thejordanwood @davidmpickett @swirtSJW I have a decision to make about this flagged facility view:
What color should I make the flags we manually set for workflow status:

- Awaiting editor
- Awaiting redirect
- Awaiting CSV

I believe they should all be the same color to distinguish them from the other migration sync assigned flags.

The default is gray, specifically var(--va-gray-lighter) // #e4e2e0

The other option that I think makes sense is var(--va-green-lightest) //#d5e7d9;

I'm showing both in the image below and would like your input. It's not a blocker yet (or really). I can go with gray (the default) for now and add a CSS change if necessary.

![Screen Shot 2023-04-27 at 6 55 51 AM](https://user-images.githubusercontent.com/766573/234856473-cd592336-dbe3-4a4e-9a88-7ffac8140968.png)

**Comment by omahane** [comment]
This is what that would look like: 
<img width="1840" alt="Screen Shot 2023-04-27 at 2 26 02 PM" src="https://user-images.githubusercontent.com/766573/234970693-972bde67-5795-4225-aeae-c70a814ea284.png">
