### ISSUE TITLE
 Enable Event editors to feature an event on the Outreach & Events list (AKA Events Calendar Single Source of Truth)

### ISSUE THREAD

**Issue by kmariepat-cityfriends** [department-of-veterans-affairs/va.gov-cms#13527]
## Status
[2024-03-14] One story remaining (refined) to close out the epic. The training video story will move than likely be transferred to the team taking over events.

## Top-line Description / Goal(s)
Create a single source of truth for event editors so that events can be published to the National Outreach Events calendar. (Allowing VAMC editors to publish an Event to multiple VAMC pages has been split into separate work #15562 , is not a PW Q4 priority.)

#### Monthly project updates:
Simultaneously tracked on DMC board as https://github.com/department-of-veterans-affairs/digital-experience-products/issues/770

---

## Headlines
**VA stakeholders** - 

**OCTO lead** - Dave Conlon

**Is this project tracked to an upcoming event or congressional deadline?** - No

## Details

**Which OCTO team should do this and what is currently on their roadmap?** - Sitewide (Public Websites)

**Which OCTO priority does this work support?** - 

**What is the user impact and scale of impact?** - 

**Who would manage this product long term?** - Public Websites

**How much leverage will this create to solve more problems in the future?** -  

**How great is the cost of inaction? (e.g., Can it wait? Must it be done by us?)** - 

---
## Description
Today, VAMC editors can create VAMC events.
VEO editors can create Outreach & Events events. 

We want a world where a VAMC editor can check a box to allow their event to appear on the Outreach & Events list. 

### User stories

AS AN Outreach Events editor (and only outreach events editor)
I WANT my event to get posted on the Outreach Events calendar by default (without any specific input from me)
SO THAT I don't have any new cognitive load added, & so that so that Veterans are aware of it.

AS AN Editor who can create events for a Facility
I WANT to be given the option of publishing to the Outreach Events calendar (i.e. "national" calendar) in addition to my usual options
SO THAT I can easily expose an event with broad appeal and remote accessibility to all Veterans.

AS A VAMC Editor with access to a VAMC
I WANT the option to publish an event to one of my VAMCs AND the Outreach events calendar
SO THAT I can promote the event where I think most appropriate.

As a VEO Outreach Events or local editor 
I want a single source of truth for local events that should be visible at the national level.

As an events publisher, 
I can specify whether an event publishes to my events calendar OR my events calendar(s) AND the national calendar

As an editor of Lovell, 
how might I say an event is happening at Lovell and I want that event published to Lovell VA AND Lovell TRICARE

As an editor of Lovell, 
how might I say an event is happening at Lovell and I want that event published that only applies to Lovell VA

### Questions to answer: 
* Does O&E need editorial review notifications / approvals to screen promoted events? No, per DaveC: we will not deal with OE review / approval until that emerges as a need from VEO.
* Permissions models for publishing to O&E

## Previous technical notes from Facilities work
Option A - Change "Where should the event be listed?" field
Make the selector field (field_listing) for which listing page an event is connected to be multi-select (cardinality of 2 or more).
image

Exempt the existing winnower from removing the Outreach and Events from the select list. (8)

Pro: Least change to our existing patterns.
Pro: Little to no FE changes needed,
Con: moderate risk of overwhelming Outreach and Events since each event would be opting into displaying there. (would not be an immediate jump.)

## Launch plan

- [X] #15641 completes, pending integration
- [X] #13529 completes
- [X] Both can merge to Prod, with Feature toggle disabled
- [x] #13533 
  - [X] Emails are drafted
  - X]Email in prep of launch is sent
- [X] Soft launch: 
  - [X] Feature flag enabled
  - [X] Comms sent to soft launch Editors that use may begin
  - [X] Editor feedback received / reviewed
- [X] Hard launch
  - [X] CMS is updated to expose feature to all Editors
  
## Post Launch Information
* [12/4/2023] Jill confirmed that there was no discernable change in content release timings 👉🏼 Content release timings vary a bit within a ~4 min range (from 41m - 45mins) with outliers up to an hour. No discernable change in that timing, based on our Events checkbox launch, data attached.

**Comment by jilladams** [comment]
@wesrowe FYI: I didn't realize/remember that Kamari had kicked off an epic for this work under the Facilities label. Since DaveC / Michelle decided Public Websites should own it ([here](https://dsva.slack.com/archives/C03LFSPGV16/p1692055193465039)), our new epic #10088 could absorb these tickets. Worth noting that #13213 is a completed SPIKE on the topic, that @swirtSJW can help our team ramp up on the findings from to think about next steps.

**Comment by jilladams** [comment]
Created a sister epic, #15562 , to track the requirements we are not considering right now, to enable Editors to publish to multiple VAMCs.

**Comment by jilladams** [comment]
@FranECross @dsasser: I drafted a launch plan in the Epic body here. 

Question / potential gap:  We are going to soft launch to a short list of editors, factored into the feature toggle. 
When we are ready to expose this feature to everyone, we may still need the ability to turn the feature off if things get weird. We need to discuss how that works, and I think we'll need a ticket to modify the feature toggle in some way. (Maybe that means it reverts to being binary on / off?)

**Comment by FranECross** [comment]
> @FranECross @dsasser: I drafted a launch plan in the Epic body here.
> 
> Question / potential gap: We are going to soft launch to a short list of editors, factored into the feature toggle. When we are ready to expose this feature to everyone, we may still need the ability to turn the feature off if things get weird. We need to discuss how that works, and I think we'll need a ticket to modify the feature toggle in some way. (Maybe that means it reverts to being binary on / off?)

@jilladams Is there a way to have three options right away? On/Off, short list, everyone? Or maybe that would increase scope?

**Comment by jilladams** [comment]
I had 1:1 with Daniel today and chatted about this - gonna whip up a ticket with those notes and will tag you to review!

**Comment by FranECross** [comment]
Email sent (2023-10-27 @ 0828) to Blake Scates with final email template going to editors, with request that he send it first thing Monday morning 10/30/23, with a requested response from editors of EOD Wednesday 11/1 Eastern Time) cc @jilladams @dsasser 

[2023-10-27_Email to Blake Scates with email template to send to editors.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13190818/2023-10-27_Email.to.Blake.Scates.with.email.template.to.send.to.editors.pdf)

**Comment by davidmpickett** [comment]
@jilladams It looks like this epic hasn't been migrated to GHP yet so I can't see sub-issues. Would be helpful for me to understand this for working on #19563

Is that something you can quickly fix or should I reenable Zenhub?

**Comment by jilladams** [comment]
You've bumped against a weird part of Github projects.
I'll fix it on this epic for you, it's pretty quick, but for reference for
future:

Because we have a finite # of issues allowed in the Project, there's a
motivation to Archive things from the project once they're closed / aged
awhile. Right now by default, anything closed > 3 weeks ago will move to
Archived. And you'll be able to see Archived items here:
https://github.com/orgs/department-of-veterans-affairs/projects/1442/archive
