### ISSUE TITLE
VAgov Claro theme MVP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1352]
## Background
We've determined that implementing Claro is the first step toward surfacing a design system for the CMS. Learn more about the what and why of a CMS design system in the main epic #4000. 
Other important info:
- We're currently using the Drupal 7 admin theme, which is dated and has some accessibility issues.
- Claro theme will soon [replace Seven as a default Drupal theme](https://www.drupal.org/project/ideas/issues/3167121).

## User story
As a CMS user, I can see that the look and feel of the CMS has changed, and on the whole those changes have a neutral or positive impact on my satisfaction and ability to use the cms.

## Scope

1. Adopt the new Drupal 9 design system, Claro, as a sustainable “parent” design system.  ~95% of our interface will simply shift to it.
2. Converting our minimal amount of custom css and html to it, like the tooltip fieldgroup used on so many Facilities forms, Vet Center dashboard, and a few other things like the Knowledge Base. This is the ~5% not already covered by #1.
3. Establish a minimal VA brand on top of it (logo, header, colors, etc) to improve trust with our editors
4. Prioritize a couple specific enhancements to the overall experience, like, say, the login page, the toolbar, etc. Login seems like a real obvious one (first impressions!) but this “enhancement” feature set needs to be kept short for this to be feasible. Updating the direction of our custom tooltip, like we discussed a couple weeks ago, is another example.
5. Addressing some specific problems that we will inherit from the Drupal 9 design system, like the bizarre alerts design (see heuristic analysis done back in Jan 2021). Another concern some have expressed is the information density, many folks find it has too much padding and white space everywhere for the purpose.  I don’t have a strong opinion about that, but we have some prior user research on dashboards (done by Lapedra!) where users expressed higher density.

Must have:
- Port custom theme (Tanner)
- Tokens (colors) (Cindy)
- Change management plan for users (Rachel?)
- Update our design ops Figma (Cindy)

Potential Soft Launch (early Q1?):
- Theme switcher to turn on specific pages:
- Homepage unauth screen enhancement w/ PIV login emphasized
- Knowledge Base updates
- User profile page

Full Launch (mid/end february?):
All of the above plus:
- Parity with existing theme, no regressions functionality-wise
- All CMS admin pages use vagovclaro, including node edit forms & preview pages
- Design tokens

### Q4 2021 

**Sprint 46**

Porting some of the custom theme 

Study MVP opportunities with a couple of screens
- Vet Center form (https://prod.cms.va.gov/node/3756/edit?destination=/section/veterans-health-administration/vet-centers/escanaba-vet-center#prepare-for-your-visit)
- Vet Center dashboard https://prod.cms.va.gov/section/veterans-health-administration/vet-centers/escanaba-vet-center)
- Content listing (/admin/content)
- Toolbar
- Login screen

**Sprint 47 (ends December 17)**
- MVP feature set definition [defined in this ticket/epic]
- Change management plan
- Login screen iteration

**Sprint 48 (ends December 31)**
- Change mgmt plan/roadmap defined
- Porting/refactoring custom theme code
- Design ops foundational work

**Sprint 49 (ends January 14)**
- Design tokens finalized
- Homepage enhancement
- "New Look" alert on certain pages (login, profile, section pages), early change management announcement for editors
- Theme switcher for proposed soft launch
- Mob session with CMS team to find functional or UX regressions
- Knowledge Base design review
- Confirm change management plans w/ wider ecosystem

**Sprint 50 (ends January 28)**
- Potential soft launch this sprint with Homepage and other pages.
- Address issues raised from mob session
- Fully documenting system & content models
- Knowledge base updates

**Sprint 51 (ends February 11)**
- Potential soft launch this sprint with Homepage and other pages.
- Address issues raised from mob session
- Continued documentation & knowledge base update

**Sprint 52 (ends February 25)**
- Proposed full launch, all admin pages
- Address issues raised from mob session
- Cleanup tech debt related to theme switchover

### Affected users and stakeholders

* All CMS users

### Hypothetical Phase 1 AC

- [x] Claro is applied and nothing is broken
- [x] X number of USWDS and/or VADS components are applied to Claro, based on some prioritization calculus driven by research & design process & design principles
- [x] A change management plan is formulated and in place for launch
- [x] Launch rollout

**Comment by EWashb** [comment]
All MVP ACs have been met.
