### ISSUE TITLE
PW Sprint 84 plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13599]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626
🟢 Design / Research:
- [ ] #13596 (5; depends on stakeholder mtgs) - Design
- [ ] #13650 () - Research

🟢 Engineering:
- [x] (Eric Oliver dependency ~2hrs) #12348 (5) - BE
- [x] #13320 (8, 4 remaining) - Ruby 🎯 
- [ ] (Wes) #13582 (3) - BE
- [ ] #13558 (8) - Ruby
- [ ] #13585 (5) - FE
- [ ] (stretch) #12354 (needsrefining) - BE
- [ ] (stretch) #13586 (5) - FE
- [ ] (when API is finalized, after FE build) #13614 (3) - BE
- [ ] #13587 (needs refining) - FE

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628
🟢 
- [ ] (PoC Drupal) #13143 (8) - BE 🎯 
- [ ] (PoC UX) #13461 (3) - Design
- [ ] (stretch) #13572 (2)
- [ ] (stretch) Need a ticket: Making POC production ready (address collab cycle feedback, prep PR) - BE
- [ ] #13207 (3) - BE
- [ ] (stretch; DaveP dependency) #11105 (needs refining) - Content Strategy

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170
🟡 
@wesrowe: TODO: check in with Danielle during Sprint 84 for next steps. 
For "prototyping" question flow for research, will confirm if Optimal Research can be used and who will configure

- [ ] (blocked on content & ownership- Danielle) #13233 (needsrefined) - Research

### 4. Expand Q&A Reusability https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780
🟡 
- [ ] (stretch) #10936 (3) - BE
- [ ] (stretch) #10937 (needs refining) - FE

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. 
🔴 Not yet actionable. (DST building their Ph1 (sample form) in Q2.)

### Other Q2 priorities not in motion
🔴 
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- Header/footer redesign - Awaiting info / green light for kickoff

### Post-MVP Homepage 
- (needs Dave/RyanT to meet post-PTO; hard-code okay?) #12292

### Cerner API deprecation support
🔴 
- [ ]  (BLOCKED) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

# Other PW Priorities

Other priorities
- [x] #11260 (5, 3 remain) - FE
- [ ] (stretch, will only move if we don't add web components) #11256 (3) - FE
- [ ] #11482 (8, ~3 remaining) - FE
- [ ] #13626 (8) - BE
- [ ] (stretch) #13084 (5) - FE/BE
- [ ] (stretch) #13329 (3) - BE
- [ ] (stretch) #12932 (8) - FE (Daniel)
- [ ] (stretch, blocked on design approval) #13222 () - FE

Forms monitoring/errors:
- Tickets are in stages of refinement; no immediate options to prioritize

### Content / IA priorities
- [ ] #13702
- [ ] va.gov-team 58142

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] #13138 (needsrefining) - FE
- [ ] #13148 (needsrefining) - FE
- [ ] #13136 (needsrefining) - FE
- [ ] #13137 (needsrefining) - FE
- [ ] #13147 (needsrefining) - FE

### Tech debt & Defects
- [ ]  (carryover from s78; blocked on test data from 12932) #10307 (~5? remain) - FE
