### ISSUE TITLE
[EPIC] Iterate on Facility Operating Status

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13598]
## Description
Once a facility is made available in the relevant data source (i.e., VAST) and available in LH, it becomes discoverable on the Facility Locator, even if the associated node in Drupal is not published. This means it is possible to find locations which are not yet open or even still under construction in search results. We need a way to clearly represent the status of future locations and to make Veterans aware of locations which will be closing, so that the transition is more gradual. 

We should ensure the label and display - as well as business process - support Veteran understand and clearly differentiate between "closed" due to weather or other temporary situation and "closing" to represent an intended permanent closure of the facility. 

*Take into consideration Accessibility/QA needs as well as Product, Technical, and Design requirements.*

**Additional use cases related to new/closing facility management**
Because the longer term goal is to open or sunset facilities more gracefully than to simply turn them on/off like a light, we need to consider ways to fade in and out, such as the following, at a minimum
- `Closing` (or similar) - a way to indicate the facility is planning a closure or relocation in the future - possibly with a date and way to redirect to new location or website
    - this could be the first status in a runbook for archiving and displayed for a set period of time 
- `Coming soon` (or similar) - a way to make new facilities findable before they are completely open for business - this may need to include a timeframe and may need a different trigger not reliant on a VAST ID number
- `Temporarily closed` - a way to designate a longer period of closure for locations which are under construction, for example, but expected to reopen - this may need to include a timeframe
    - ^ possibly could benefit from a `Coming soon` version to advertise the planned opening

## Existing functionality
**Drupal**
- Drupal is the source for facility operating status for all facility types: VAMC, Vet Centers, VBA, and NCA - even if the facility does not have a modernized published page. The fields have slightly different naming conventions for VA health facilities but the functionality is the same. 
  - `operating status field` = `status` for VA health facilities
  - `operating status - more info` field = `Details` for VA health facilities
- The `operating status` field is required. Four options are available via radio button.
  - Normal services and hours
  - Facility notice
  - Limited services and hours
  - Facility closed
- Normal services and hours is the default.  
- When any other status is selected, a required `Operating status - more info` field is displayed. Editors may enter up to 300 characters to provide additional information about the facility's operating status.

<details>
<summary> Drupal UX </summary>

---

## Designs
https://www.figma.com/design/HcEIBH2fxd147gLK8u2zgt/Facility-Operating-Status?node-id=811-13883&t=WHLiRpOrKuWlWWRp-1

VAMC UX

![Image](https://github.com/user-attachments/assets/1c2a894f-c4ab-4caf-9fb5-b870426a401c)

---
UX for other facility types

![Image](https://github.com/user-attachments/assets/6896feaf-7018-4798-aa85-f4f3e23cd17e)

![Image](https://github.com/user-attachments/assets/f40e297a-bd6d-486c-8908-fa516bf84901)

</details>

**Front end** 

- If the status is anything other than Normal, the `Operating status` is displayed in the Facility Locator search results card. 
- If the status is anything other than Normal, the `Operating status and details` are displayed on the Facility Locator detail page for facilities without a modernized page (i.e., [Jefferson Barracks National Cemetery](https://www.va.gov/find-locations/facility/nca_852)) and in the Location and contact information blocks on modernized pages, including
  - Vet Center main page (i.e., [Guam Vet Center](https://www.va.gov/guam-vet-center/))
  - Vet Center locations page (i.e., [Guam Vet Center - Locations](https://www.va.gov/guam-vet-center/locations/))
  - Regional office modernized main page (i.e.[National Capital Region VA Regional Benefit Office](https://www.va.gov/national-capital-region-va-regional-benefit-office/)) or Facility Locator VBA detail page (i.e., [Veteran Readiness and Employment Office at St. George Vet Center](https://www.va.gov/find-locations/facility/vba_341a)
  - VAMC system home page (i.e., [VA Asheville health care](https://www.va.gov/asheville-health-care/))
  - VAMC facility page (i.e., [Charles George Department of Veterans Affairs Medical Center](https://www.va.gov/asheville-health-care/locations/charles-george-department-of-veterans-affairs-medical-center))
  - VAMC Locations page (i.e., [Asheville health care Locations](https://www.va.gov/asheville-health-care/locations))
  - VAMC operating status page (i.e., [Asheville Operating status page](https://www.va.gov/asheville-health-care/operating-status/))
- Vet Center and Regional office pages use the expandable alert design, allowing Veterans to see the details inline. 
- Facility Locator search results page show the operating status only. Veterans must use the linked name to view the details on the Facility Locator detail page or on the modernized facility page. For VA health facilities only, the operating status has a link to the operating status page, rather than using the expandable alert design. 

<details>
<summary> Facility operating status flow </summary>

![Image](https://github.com/user-attachments/assets/c2ae926d-c892-4b46-a704-24563ecf739d)

</details>

- NCA operating status may not be enforcing the More info requirement (see [Southern Utah](https://www.va.gov/find-locations/facility/nca_942))

## Related items
* Lighthouse sync card discussing data options: https://trello.com/c/rAEpgRjD/86-facility-operating-status-can-we-add-new-values
* [Actionable items from Veteran research](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/research/user-research/facility-status/research-findings.md)

## Product documentation
* **Existing product docs**:  https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers

We don't have great documentation about Operating Statuses there. It would be great to flesh that out during this initiative.

---
### High level work required to complete the epic
- [ ] Analytics review
- [ ] Backlog review
- [x] Content audit --  may be needed, to understand any current facilities with Operating statuses that need to migrate to the new options?
- [ ] FE Design
- [ ] Usability research
- [x] Drupal
  - [x] CMS Design
  - [ ] New config, fields, or entities
  - [x] Revisions to existing config, fields, or entities -- Content modeling _may_ be required, tbd scope
    - [x] Content modeling is required
  - [x] Editor Change management is required in either case
  - [x] Knowledge Base article creation or updates are required in either case
- [ ] Vets-api (Ruby)
  - [ ] New API or endpoints
    - [ ] Datadog monitoring is required 
  - [?] Revisions to existing API / endpoints -- do we need to do work to handle the new statuses in facilities-api, in order to return them to the FE? 
    - [ ] Datadog monitoring updates may be required, tbd the scope of changes 
- [x] Content-build (FE) 
  - [ ] New templates -- try to avoid this and build in Next if possible
  - [x] Revisions to existing templates
- [ ] Next-build (FE)
  - [ ] New template(s)
  - [x] Migration of existing content-build template(s)
  - [ ] Revisions to existing Next templates
- [ ] Vets-website (FE)
  - [ ] New React app or widget
  - [x] Revisions to existing apps, widgets, templates, or styles
- [ ] Collab Cycle - required for any new application, usability research, major architectural change to an existing product. If you're not sure, ask Governance team.

---

## Decision log
* Red goes away in this scope.

**Comment by davidmpickett** [comment]
May be additional lessons learned from COVID-19 Supplemental Status feature to consider

- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10389
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9096

**Comment by mmiddaugh** [comment]
This iteration might also apply to Vet Center CAP communication needs

**Comment by mmiddaugh** [comment]
The following use cases and examples are from a review of status more info text currently in use across facility types

- Available by appointment only
- Virtual options
   - We're not open for in-person service at this time. Our staff are still available by phone and by our online customer service tool.
- Phone number emphasis or correction  
   - To contact Mental health care please dial 901-523-8990 extension 7411.
   - The main phone and Mental Health Care phone lines have temporarily changed to 800-472-1365, ext. 2221. Please make a note of the temporary number. We are experiencing technical issues with our standard 575-exchange lines and this 800-number will temporarily resolve the issue.
- Location corrections 
  - This location is NOT the Fort Worth VA Clinic and does not see patients.
  - This is NOT a VA Clinic. If you wish to contact the Community Resource and Referral Center, please call (843) 789-6500.
  - The North Bend Lab is closed indefinitely at this time. If you have questions or concerns regarding upcoming labs at the North Bend VA Clinic Lab, please contact your PACT team via My VA Health, by phone at 541-756-8002, or in person.
  - December 17 was the last day for operations here. This clinic has moved to the new Terre Haute VA Clinic.  The new clinic is located at 5080 East Bill Farr Drive, Terre Haute, IN 47803-9306  https://www.va.gov/indiana-health-care/locations/terre-haute-va-clinic/
- Upcoming changes to facility
  - The parking garage adjacent to the Baltimore VA Annex at 213 W. Fayette Street will close May 5, 2023. Patients with appointments at the Baltimore VA Annex can park in the garage at the Baltimore VA Medical Center and take a free shuttle to and from the Baltimore VA Annex.
  - Our Primary Care service has expanded to a larger setting and the entrance now faces Hope Avenue, on the opposite side of Summer Street, at the back of the Medical Arts Center. Specialty Care services have moved into the former Primary Care location facing Mill Street.
- TRICARE/Lovell
   - Services for ACTIVE DUTY ONLY at this location.
- Vet Center CAP service details
  - Group and Individual Counseling is available at this location on Thursdays. Please call our main Vet Center at 570327-5281 before joining us for the first time.
  - Veterans connect with horses each week and progress together through basic groundwork skills. Services are available at this location by appointment only from 8 a.m. to 10 p.m. on Wednesday. Veteran or service member are required to participate in the program here to receive counseling services.
  - The Vet Court is a specialized program to serve Veterans with trauma from serving in a war zone. Services are available at this location by appointment only 8 a.m. to 9 p.m. on Wednesday. Please Veteran or service member are required to participate in the program here to receive counseling services.
  - This site is only for inmates. Services are available to inmates by referral.
  - Access point location to open in early 2022.
- Special campus access info 
  - Access to Fairchild AFB required.

**Comment by kmariepat-cityfriends** [comment]
Note: this may be considered for VBA fast follow

**Comment by davidmpickett** [comment]
See also: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14546

**Comment by xiongjaneg** [comment]
@xiongjaneg
To discuss with Dave, is this the same as the supplemental status issue.

**Comment by jilladams** [comment]
@Agile6MSkinner I added the new checklist of discipline area work, and took a stab / added my notes for what might potentially be involved in this. The team will need to review / cosign that, and we'll need to scrub through the tickets already in this epic, to make sure they're still relevant, given today's scope.

**Comment by mmiddaugh** [comment]
@Agile6MSkinner 
**Scope for 4Q2024**
- The primary goal is to support Veteran understanding about facilities/cemeteries which are available in the API/Facility Locator but which are not yet open to provide benefits and services or which have been archived in Drupal but are still discoverable in search results. The requested changes are needed as the number of scenarios documenting Veteran confusion and misunderstanding about facility availability and stakeholder complaint has increased over the last few months, 
- This work should expand **existing** functionality by adding several new operating statuses, i.e.
   - Planned
   - Under construction
   - Coming soon
- Existing operating status options should be maintained.
- More info/details field should be required for all status except Normal. Character limit should remain at 300 characters. 
- Existing functionality to push operating status to Lighthouse should be retained and should encompass new statuses. 
- Amanda is working on design, in context of the necessary changes needed to replace the expandable alert - error variant (red) which has been removed from guidance and is no longer recommended. (see #18225)
- Although the flow for VAMC operating status should be revisited, it is not necessary within this iteration. 
- The sub-issues associated with this issue today are not in scope.

**Comment by jilladams** [comment]
That's great help! Moving those sub-issues out of this epic prior to today's meeting, to keep us focused, and we can focus on story mapping instead for what _is_ in scope per Michelle's comment, @Agile6MSkinner.

**Comment by jilladams** [comment]
Noting from story mapping discussion: 
We have talked to Lighthouse about this: https://trello.com/c/rAEpgRjD/86-facility-operating-status-can-we-add-new-values

> LH can add new values but need to add a code change to support receiving the new value.

> In LH API: accepted values is set up right to accept 1 of 4 values, and if they got an unexpected value, would throw the whole message away.

> LH LOE to add new values = probably relatively small.

> From Joe: theoretically VAST could flag as Inactive / Planned, etc. so they don’t show up in LH. But: that’s not always happening. Only 2 VAST statuses get pulled into LH: Active, & Temporarily Deactivated. They don’t get Planned or Permanently Deactivated.

> We can ask Editors to request a status update with their VAST coordinator to ask to move back to Planned. But until those updates are made in VAST, a planned but “Active” facility would show up in Facility Locator searches.

**Comment by jilladams** [comment]
@mmiddaugh if you used Mural to generate the FLow in [this image](https://private-user-images.githubusercontent.com/55411834/381189113-c2ae926d-c892-4b46-a704-24563ecf739d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzU3MzAsIm5iZiI6MTczMDkzNTQzMCwicGF0aCI6Ii81NTQxMTgzNC8zODExODkxMTMtYzJhZTkyNmQtYzg5Mi00YjQ2LWE3MDQtMjQ1NjNlY2Y3MzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDIzMjM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzcwODE3MmY4ZTU2YTBlYTRhMDQ4YzkwYzhmODgwYTMxMDJmMjMyNzI0NWVlNjZmOWIyMDQ5YjRkY2E5MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X5SyCJP5ZG6Ufn8AjAOazInXeIiDe_wDh0A3jVsZjMw), could you either share the Mural link, or download that image and share it in Slack? It's being treated as private content, and we can't view it bigger than a thumbnail.

**Comment by jilladams** [comment]
Added #18410 to this epic. That's one additional location where Operating Statuses can be found in the front-end, and shouldn't be. if we just kill that debt, it makes this epic smaller.

**Comment by jilladams** [comment]
@Agile6MSkinner can this epic close?

**Comment by Agile6MSkinner** [comment]
@jilladams Sure can!
