### ISSUE TITLE
Create automation for putting site in Site Alert Mode, then backup files directory and restore to new servers during deploy

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1360]
Strategy has been [updated](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1360#issuecomment-621378961):

1. Put site in alert mode (disables activity by editors and admins)
2. On existing server, backup sites/default/files directory to S3
3. Deploy new server
4. On new server, restore sites/default/files directory from S3
5. Remove site alert mode

Task List (**bold = in progress**):
- [x] Ansible tasks to upload files archive to S3 from pre-deploy instance 
- [x] Ansible tasks to restore files archive to new deploy instance
- [x] Create Jenkins Job and Ansible migration playbook for automated steps to swap out the files directory on the EFS volume, one time run only, in preparation for the new deployment modifications 
    - http://jenkins.vfs.va.gov/job/cms/job/cms-efs-to-ssd-migration-2020-04-31/
- [x] Make PR
    - https://github.com/department-of-veterans-affairs/devops/pull/6857
- [x] Test migration job on CMS-TEST PROD Deploy
- [x] Update PROD files backup job to go into server, archive and upload to S3 (because the current job mounts EFS on Jenkins, which will be gone, and we would have no files backups anymore)
- [x] Test new Backup job
    - [x] Fix IAM permissions
        - https://github.com/department-of-veterans-affairs/devops/pull/6870
- [x] Test new deploy steps on CMS-TEST PROD Deploy
- [x] Update PR to have the meta backup wrapper job use the assets job instead of the efs backup job
- [x] Deploy this faster filesystem improvement to CMS-PROD
- [x] Until S3FS - Increase frequency of pipeline backups to 15 minutes for disaster recovery on ASG failure/instance termination (has never happened yet outside of deploys but could) - https://github.com/department-of-veterans-affairs/devops/pull/6876
- [x] **Create follow up post-mvp launch tasks that arise** (a checkbox here _only_ means the task was created, not completed)
    - [x] Remove all EFS infra in Terraform/Jenkins/Ansible - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1516
    - [x] Restore assets/files transfer before new instance goes into rotation so that CSS/JS is present and not broken. - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1713
       -  See https://dsva.slack.com/archives/CT4GZBM8F/p1588621716492800?thread_ts=1588621065.492500&cid=CT4GZBM8F
    - [x] Reevaluate using tome-syncs file export feature because we already have this data, and it doubles the size of the archives. We can dynamically generate this very quickly with tar.~ Discussed with @indytechcook and have Tome SYnc not export files at all (Neil is currently aware of the limitation) - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1714
    - [x] High Priority - S3FS - Solve multiple instance deployment and ASG termination issue - must be done soon after - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1716
    - [x] Resolve "The file public://cms-asset-export-latest.tar was not deleted because it does not exist." in logs when requesting http://localhost/cms-export/asset - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1717
    - [x] Zippy Drupal module contribution - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1718
    - [x] Create issue for lifecycle hook broken CONTINUE - https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-cms/issues/1719
    - [x] Create issue to add the wait: 2000 back for Build AMI task - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1720
    - [x] Update PR environments to get asset files (might be an open PR), currently broken, demo envs work - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1721
        - Consider use stage file proxy in URL replace mode - This won't work with the web build
    - [x] Add restoration of most recent files backup (not deploy state transfer) to init tasks (BRD has support for this) so when an instance goes down and the ASG brings it back up it has the latest files there, we would have to increase the backup frequency to once every 5 minutes for this to possibly be effective.  - **Not doing right now, will solve in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1713 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1716**
    - [x] Resolve "URL not supported for path_alias" when visiting https://prod.cms.va.gov/node/add/health_care_region_detail_page - Log type 'VA-EXPORT' - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1722
    - [x] Configure /cms-export/assets|content endpoint to not 302 in maintenance mode, so that incoming requests are still served while the asset state is being transferred - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1723
    - [x] Rename redirected file archives to match endpoint and internal contents, e.g. cms-content-export-latest.tar > cms-export-content-latest.tar (same for asset). Also should it be assets? Content is plural and singular at the same time. :man_shrugging: - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1724
    - [x] Fix "Source image at public://video_thumbnails/d8M13QVgOqk.jpg not found while trying to generate derivative image at public://styles/large/public/video_thumbnails/d8M13QVgOqk.jpg." by moving asset state restoration to the beginning of the post-deploy tasks.  - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1713

======================= 

((partially) outdated, see above)

    
<details>
<summary>**WIP - Wanted to get it out of my notepad and public, still working on this, copying it here, will format when done.** </summary>

**Swap EFS for EBS IO1 SSD for sites/default/files mount**
This story is basically changing the deployment system to swap out a very slow EFS mount for a high performance EBS SSD Volume so that we can quickly archive (TAR) the content and asset files and make them available in the Tome Sync story. 

**Why?**
EFS is too slow for the speed we need to archive these and make available for download. In a PoC of FS-CACHE that interfaces with EFS performance was better but not enough for our needs of archiving all content immediately upon publish (hook_insert/update) with a background process launching another PHP process to TAR the files (not GZIP, too slow) in 2 seconds (17,000 files/~1GB), which the IO1 can do. The times of FS-CACHE brought the times from 10 minutes down to 5 minutes for a `tar --create` and 1.5 minutes for an `tar --update`. 

@todo 
This will only work with one server as one cannot attach an EBS volume to more than one instance in GovCloud (multi-attach is available for other regions but not GovCloud yet, and all instances have to be in the same Availability Zone). So look into solving this by using D8 S3FS to keep the changes in sync. 

**How?**
We create a dedicated file assets EBS IO1 SSD for each environment: DEV, STAGING, PROD. The volumes have a 60GB EXT4 filesystem with 3,000 dedicated provisioned IOPS. 

We modify the deployment jobs to first unmount and detach from the old instance and then immediately attach and mount to sites/default/files. 

List of tasks below that should roughly be what is needed:

Prerequisite:
Site Alert Deploy Triggers/Maintenance Mode - is it a blocker for real?
We kinda want the site to not be used when the mount is missing for a few seconds
IO1 root volume deployment - testing now
Tasks
Measure Performance

Create a file assets `io1` volume with an ext4 filesystem that can be attached and detached to deploys for DEV, STAGING & PROD
mkfs ext4
Remove EFS volumes
AWS Console
Remove EFS mount code
deploy configs
Unmount file system on old instance
Detach volume of old instance
Attach volume to new instance
Mount filesystem on new instance at sites/default/files
Before the sync-files.sh
do we need chown/chmod?
Create run book
Last, create story to track and use multi-attach when it is in GovCloud, even with the S3FS, this should make the time it is unmounted between deploys zero. 
</details>

**Comment by indytechcook** [comment]
I'm adding a comment here that in discussion with @swirtSJW  and @ElijahLynn we agreed that adding a new endpoint `/content-export/tar`, or something similar, which will tar the files on demand is the best approach.

* The tar update command takes less then a second to occur
* We do not have to worry about race conditions as we would if a cron or background job was used.

**Comment by ElijahLynn** [comment]
Strategy has changed: Latest strategy for this work is now going to be:
1. Put site in alert mode (disables activity by editors and admins)
1. On existing server, backup sites/default/files directory to S3 
1. Deploy new server
1. On new server, restore sites/default/files directory from S3
1. Remove site alert mode
