### ISSUE TITLE
Facility editors should not be able to publish facilities without services

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13670]
## User Story or Problem Statement

As a a facility editor I should be prevented from publishing a facility that requires services, when it has no services assigned so that I do not create a bad Veteran experience.

This applies to 
* VAMC Facilities
* Vet Centers 
* (soon) VBA facilities.

Approaches:

- **Entity validation on save**: Entity validation is the safest as it will stop it at the time of save and be able to handle  a nice error message.  It would safely account for any services that were saved in other tabs after the facility form was opened.
- **Removing the "publish" transition on node edit**: This is the less jarring experience as there are no error messages, however it would incorrectly fail if services were added after the form was open.  It would also not create an opportune UX spot for a message describing why publishing is not available.

Neither of these approaches will remove the risk of a Bulk operation of publish.  Bulk operations do not follow entity validation.

## Acceptance Criteria
- [ ] When a VAMC facility has no services assigned, the "publish" transition should either be hidden, or entity validation should prevent the save with a nice helpful error message.
- [ ] Same for Vet Center (the fields are different so the check will need adjusting)
- [ ] Same for VBA if that product is far enough along, if not, it will need its own ticket.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by timcosgrove** [comment]
Very much in favor of the first approach:
> Entity validation on save: Entity validation is the safest as it will stop it at the time of save and be able to handle a nice error message. It would safely account for any services that were saved in other tabs after the facility form was opened.

I do not think this should be solved via Content Moderation.

**Comment by mmiddaugh** [comment]
Use case: As a Veteran, I want to be able to discover facilities which will soon be opening in my area. 

Because of this use case (and potentially others) we will want to consider whether or not associated services should be a requirement for publishing.
