### ISSUE TITLE
Content Model: VBA, NCA, Veterans Centers

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1367]
## Description

3 new content types: 
- [x] VBA facility
- [x] NCA facility
- [x] Veterans Center

Fields for all 3 content types, reusing existing fields already on “VAMC facility” content type
   - [x] Facility name (node title)
   - [x] Facility Locator API ID (Use existing field field_facility_locator_api_id) 
   - [x] Operating status (required) Use existing field_operating_status_facility
   - [x] Operating status - more info (not required) Use existing field_operating_status_more_info
   - [x] Owner (field_administration) 
   - [x] Title and facility field_facility_locator_api_id should be located inside  field group group-facility-api  (see implementation on /node/add/health_care_local_facility

Other considerations
- [x] Enable editorial workflow. Default to Draft instead of just Unpublished
- [x] Path alias pattern `[node:field_administration:entity:name]/locations/[node:title]`

### TODO:

- default owners for field_administration will be set in #1375 

## Acceptance Criteria
- [ ] 3 new content types with specified fields exist:
   - [ ]  VBA facility
   - [ ] NCA facility
   - [ ] Veterans Center
- [ ] editorial workflow is enabled for all 3 new content types
- [ ] 3 new content types have defined path alias patterns

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)
