### ISSUE TITLE
Facility Locator form system conversion feature flag

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13675]
## Issue Description
So that the Facility Locator can fall into line with the design system and use accessible error messages, we need to convert to the form system. 

## Tasks
Create feature flag to allow testing

## Acceptance Criteria
- [ ] New search components created with form system do not move to Production until ready

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
Closing this as no longer needed
