### ISSUE TITLE
Remove Featured field order from featured fieldset.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13688]
## User Story or Problem Statement

The editorial experience for the Featured aspect of Stories and Events is confusing.  We offer the ability to pick an order but it seemingly has no effect on the FE.

## Acceptance Criteria
- [ ] Before beginning other work, validate that 'field_order' is not used on the FE system template, story list page, or event list page templates.
- [ ] I expect the 'field_order' field is removed from the story content type
- [ ] I expect the 'field_order' field is removed from the event content type
- [ ] I expect the field guidance on featured related fields on story and event content types no longer addresses order or a limit of 2, and reflects that there can be only one featured.
- [ ] I expect a FE PR is created to remove the field_order from the template and queries.
- [ ] Requires KB article updated
- [ ] Updates made to CM Documents related to the behavior of the featured field.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
content-build references

- https://github.com/department-of-veterans-affairs/content-build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/graphql/facilities-fragments/healthCareRegionEvents.node.graphql.js#L22
- https://github.com/department-of-veterans-affairs/content-build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js#L144
- https://github.com/department-of-veterans-affairs/content-build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js#L144
- https://github.com/department-of-veterans-affairs/content-build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/va/events.json#L217
- https://github.com/department-of-veterans-affairs/content-build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/federal/events.json#L253
- https://github.com/department-of-veterans-affairs/content--build/blob/95eba2ce55b9396f18ada2a00a9e6193ded0cc4b/src/site/stages/build/drupal/tests/lovell/fixtures/listing-pages/tricare/events.json#L228

There seem to be no instances of it showing in tempates.

**Comment by jilladams** [comment]
We need to explicitly identify which KB articles require updates and add links to ACs

**Comment by davidmpickett** [comment]
The Order fields were hidden as part of #18819

That ticket also addressed UI and KB updates, so all that remains for this ticket is an update hook to fully remove the fields.
