### ISSUE TITLE
Implement epic text-field migration core logic.

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#13699]
## Description

Building on the discovery and planning stages outlined in [issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14995), this ticket aims to implement the core logic required for migrating text fields to accommodate longer translations without compromising data integrity.

## Pseudocode

- given a field name and entity type:
  - extract data from that field across all entities of that type
  - safely delete the identified field (without compromising associated nodes or content)
  - recreate the field with the new form
  - populate the new field values with the extracted data

## Tasks
- [ ] Flesh out the algorithm as necessary.
- [ ] Keep in mind the following questions:
  - [ ] Are all steps atomic? How do we roll back from each one?
  - [ ] How are errors propagated in each step? What happens then?
  - [ ] What's the disaster recovery strategy for each step?
  - [ ] What risks do we face? How do we guard against them?

## Acceptance Criteria

- [ ] Core logic has been implemented in a class or system of classes.
- [ ] Detailed unit tests exist for every aspect of the process.
- [ ] Detailed integration tests cover as much of the functionality as possible.
- [ ] Detailed existing-site-base tests exist that will actually perform the migration as envisioned. E.g. we should be able to run the full collection of CI/CD tests, then run this specific test suite, then run the full collection of CI/CD tests again and there should be no errors or failures anywhere.
- [ ] Manual testing procedure has been crafted in the abstract, e.g. whenever we run this process on a specific field, we should follow these steps to verify that the related data is safe and not changed in an undesirable way.

**Comment by ndouglas** [comment]
## Addressing Acceptance Criteria from #14995

### Recommendations on general strategy, rollout, etc have been used to inform implementation ticket.

As mentioned in #13699, I've shifted my idea of how to attack this on the broadest scale. I think I want to be _guaranteed_ the ability to use all Drupal services, particularly during the verification phase. I also want to be able to roll back my changes if there is an issue, get better feedback about what is currently happening in the system, etc. That seems to imply to me that I should avoid the update hook system, as clean and obvious as that would be. 

The goal is for this to be transparent, and I believe based on an extensive code review that this is possible, so I don't think doing this on a deployed instance is problematic _except_ in that I obviously want to prevent people from accessing the system during the operation. Putting Drupal in maintenance mode should suffice for that.

### Process for testing and verifying reliability

I'll divide this into two sections: lower environments and production.

#### Lower Environments

- Cypress tests (if available, else manual) for CRUD operations per affected entity type and bundle.
- Cypress tests for character limits on each limited field, similar to existing `translations.feature` test.
- Cypress tests for verifying continuity and consistency of form display for modified content types.
- PHPUnit functional tests for verifying continuity and consistency of form display in config.
- Cypress tests for verifying translatable fields are indeed accessible in the interface.
- PHPUnit functional tests for verifying consistency of field data before and after change.
- Cypress tests for verifying that updating a node creates revisions and that the node can be reverted back to a previous revision.
- Cypress tests for a content type using Centralized Content, just to verify that it has the expected data, etc.
- PHPUnit functional tests for verifying that rollbacks operate correctly from each step in the process.
- Integrated tests for verifying that the data is consistent and coherent.

#### Production

- Integrated tests for verifying that the data is consistent and coherent.
- Manual spot-checking individual entities to see if anything strange has happened.

### Rollback strategy in case of unforeseen issues



### Process for verifying data integrity during/after completion



### Process for spot-checking individual entities



### Schedule (vague) for phased rollout given tentative benchmarks and safety margins for deployment
