### ISSUE TITLE
Creating a Lovell umbrella page that overwrites a single page is possible.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13704]
## User Story or Problem Statement

As an editor I would like to know if the Lovell page I am creating is occupying / blocking/overwriting another Lovell page that already exists so that I can fix the problem

example1 :
  - Lovell umbrella page "apple" exists
  - While creating a new Lovell tricare "apple" page warns me that umbrella "apple" is already exists and  suggests a way to fix this.

example2 :
  - Lovell VA page "pear" exists
  - While creating a new Lovell umbrella "pear" page a warning tells me that VA "pear" already exists and  suggests a way to fix this.

## Acceptance Criteria
- [ ] I expect an editor is notified if a page they are creating/editing collides with an existing page.
- [ ] I expect the notification does NOT prevent saving the page.
- [ ] I expect the notification to provide a link to the existing page and describes how to resolve the problem.
- [ ] Requires design review for the helpful phrases.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.
