### ISSUE TITLE
Prevent James A Lovell TRICARE facility drift

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13706]
## User Story or Problem Statement

As a Lovell site maintainer I expect that any data that is changed by the nightly VAMC facility migration is propagated from the VA James A Lovell facility (vha_556 in Facility API) to the TRICARE James A Lovell facility (tricare_556)  that is not in Facility API 

As it is now, Changes to James A Lovell VA will track the facility API data, but James A Lovell TRICARE is not updated, and can become out of sync.

## Acceptance Criteria
- [ ] I expect that when Facility API sourced data in https://prod.cms.va.gov/node/1480 is changed, that https://prod.cms.va.gov/node/49055 is updated to match.

## Implementation steps
This could be done as a post save hook, or it could be done with a post migration task that just syncs VA to TRICAE no matter if data changed or not.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

**Comment by kmariepat-cityfriends** [comment]
Next Steps: Is VAST the canonical information for the TRICARE half of Lovell, ask VHA DM about this in 5/19 sync session

**Comment by jilladams** [comment]
Per Steve: there is an implementation difference between matching the data on migration, vs. on node save. Answers from office hours will determine best path forward, in order to finalize plan and estimate.

**Comment by kmariepat-cityfriends** [comment]
the information in VAST to their knowledge is the canonical information for the TRICARE half of Lovell
