### ISSUE TITLE
Benefit Detail page hardening using VA Benefit Taxonomy

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13752]
### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

**Comment by jilladams** [comment]
CAIA feedback was shared via SharePoint doc today: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZi5OJA1om9Fj_fl3IXmwYQBKKmKbkUhAXQuYyQFcG_Gjw?email=JILL.ADAMS1%40VA.GOV&e=31dcA4

**Comment by jilladams** [comment]
CAIA feedback was shared via SharePoint doc today: https://dvagov-my.sharepoint.com/:w:/g/personal/danielle_thierry_va_gov/EZi5OJA1om9Fj_fl3IXmwYQBKKmKbkUhAXQuYyQFcG_Gjw?email=JILL.ADAMS1%40VA.GOV&e=31dcA4

Next step: 
* Review the feedback doc within the team
  - [ ] @FranECross 
  - [ ] @jilladams 
  - [ ] @davidconlon 
  - [ ] Daniel / Michael, tbd prioritization discussion with Dave 
- [ ] Schedule review meeting with Danielle / Randi H on CAIA to talk through the feedback, including Fran / Dave and whomever else is required

**Comment by davidmpickett** [comment]
Notes following review of the feedback. 

1. Some of what they are asking for are things that were intentionally cut from MVP scope ([see decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/structured-content/benefits-content-model/decision-log.md#329--330--46-mvp-spec-finalization-meeting-with-dave--danielle)). For instance, while "How to Apply" was an area I audited with the hopes of hardening, pretty much all of that was removed from the scope because it was determined that those details might better be part of the Forms Content Model.


2. The question of how does this relate to the Benefit Detail Page (Drupal Content Type) and the corresponding VA.gov Benefit Hub pages (FE pages) is very much an open one. [This diagram](https://app.mural.co/t/departmentofveteransaffairs9999/m/vagov6717/1660845137501/6eadf59a3f4d8dcd29da572a68115a22d6114fe4?fromVisitorModal=true&sender=u9c899abc4fe36c9a698b1647) gestures towards a path forward, but we'd need to do work to actually connect the Benefit Taxonomy in any meaningful way to the front end.

From a Product standpoint, want to make sure we're distinguishing between 1) Adding features to the Benefit Taxonomy vs 2) Wiring up the Benefit Taxonomy (as is) to power portions of the Front End.

3. More of a side note, but one of the ways we framed this last year was that there would be other consumers of the Benefit Taxonomy. How much should we keeping that perspective in mind when reviewing feedback / deciding on direction?

**Comment by FranECross** [comment]
Added associated tickets as sub-issues so they'll display on the epic on the new board.
