### ISSUE TITLE
PW Sprint 85 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13754]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626
🟢 Design / Research:
- [x] #13596 (5; depends on stakeholder mtgs) - Design
- [x] #13723 (depends) - Design
- [x] #13703 (2) - Research

🟢 Engineering:
- [x] #13558 (8) - Ruby 🎯 
- [ ] #13586 (5) - FE 🎯 
- [x] #12354 (3) - BE
- [x] #13738 (5) - FE
- [x] #13587 (3) - FE

Stretch for Randi to continue as sprint allows:
- [x] #13590 () - FE
- [ ] #13588 () - FE
- [ ] #13750 () - FE

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628
🟢 
- [x] #13802 () - BE
- [x] #13572 (2) 🎯 
- [ ] #13755 () - Design
- [x] (stretch) #13756 (5) - BE
- [ ] #13207 (3) - BE

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170
🔴 
- [ ] (stretch; Cindy dependency) #13722 () - Research
- [ ] (blocked on content & ownership - Danielle) #13233 (needsrefined) - Research

### 4. Expand Q&A Reusability https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780
🟡 
- [x] (stretch) #10936 (3) - BE
- [ ] (stretch) #10941 (5) - BE
- [ ] (stretch) #10937 (3) - FE
- [ ] (stretch) #13725 (needsrefining) - Design

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. 
🔴 Not yet actionable. (DST building their Ph1 (sample form) in Q2.)

### Other Q2 priorities not in motion
🔴 
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- Header/footer redesign - Awaiting info / green light for kickoff

### Post-MVP Homepage 
🟢 
- (RyanT design dependency) #12292
- #12772 (5) - 5/30-6/1 launch timeframe (Mid-sprint) 🎯 
- #11921 () - FE

### Cerner API deprecation support
🔴 
- [ ]  (BLOCKED) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

# Other PW Priorities

Cross-repo dependencies post-mortem
- [ ] (stretch) #13730 (needsrefining) - FE/BE
- [ ] (stretch) #13731 (needsrefining) - FE/BE

Other priorities
- [x] #11313 () - FE
- [ ] (stretch; blocks missing-event defect 10307) #12932 (8) - FE (Daniel)
- [ ] (stretch) #10307 (8, partially done) - FE 
- [ ] (stretch) #13329 (3) - BE
- [ ] (stretch) #13222 (8) - FE
- [ ] (hold off; purpose of flag was identified, asked CAIA to comment) #13732 (5) - BE
- [ ] (stretch) #13062 (3) - FE

Forms monitoring/errors:
- Tickets are in stages of refinement; no immediate options to prioritize

### Content / IA priorities
- [ ] #13702
- [ ] (blocked; CLP-related) va.gov-team 58142

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [x] #13138 (needsrefining) - FE
- [ ] (stretch) #13136 (3) - FE
- [ ] (stretch) #13137 (needsrefining) - FE
- [ ] (stretch) #13147 (needsrefining) - FE

### Tech debt & Defects
- [ ]  (carryover from s78; blocked on test data from 12932) #10307 (~5? remain) - FE

**Comment by wesrowe** [comment]
Tickets to refine in Planning 1st hour:
- [ ] #11313
- [ ] (stretch) #13730 (needsrefining) - FE/BE
- [ ] (stretch) #13731 (needsrefining) - FE/BE
- [ ] #13481 
- [ ] #13590 
- [ ] #13802

**Comment by jilladams** [comment]
For 86+: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11921
