### ISSUE TITLE
Spike: Use constants in cypress tests?

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13765]
## User Story or Problem Statement

As an engineer I would like a single file in cypress to conrol all our references to specific nodes, paths, etc so that I can easilly **see** where tests are going and **fix** any risky data hard coding in one spot. 

As an engineer I want clean names so the test is easier to read.

Instead of having a test like 
```And my workbench access sections are set to "2,12,"
  # 2 = NCA (Louisiana National Cemetery)
  # 12 = VA Pittsburgh health care (H. John Heinz III Department of Veterans Affairs Medical Center)
```
I can say  in one the constants  file  (env file?)
SectionIDNCA = 2
SectionVAMC= 12

And the test located in a different file can read
```
And my workbench access sections are set to SectionIDNCA, SectionVAMC
```

In the constants  file I can say 
```
  # Vet Center Outstation (Clarksville Vet Center Outstation)
  NodeVetCenterOutstation =  "/node/17533"
```

Then in the test, instead of saying 
```
  # Vet Center Outstation (Clarksville Vet Center Outstation)
  Then I am at "/node/17533/edit"
```
I can say 
```
Then I am at NodeVetCenterOutstation . /edit
```

The examples above are just sudo code-ish.   The 
## Acceptance Criteria
- [ ] Establish if it feasible
- [ ] If it is feasible, propose an achitecture for it.
- [ ] Stand up one example / convert one existing test to use it

## Implementation steps
<optional>

**Comment by swirtSJW** [comment]
@ndouglas this was something that @omahane and I were kicking around a bit.  It was mainly an idea I wanted to get down in writing before I forgot about it.

I did some really quick searching on this and it sounds like it might be doable https://stackoverflow.com/questions/49700479/cypress-how-to-store-global-constants-in-a-file-that-can-be-used-across-all-spec

Give it some thought.  Let me know if you think it has merit.

**Comment by ndouglas** [comment]
Yeah, that looks like a great improvement @swirtSJW!

**Comment by swirtSJW** [comment]
@ndouglas The other possible gain I see coming out of this could be leveraging node titles in the tests where you are creating one of each content type.

Instead of creating node titles like
`[Test Data] Dolorem ut autem saepe animi accusantium atque omnis nesciunt.`


we could use them as vars like
```
NodeVetCenterOutstationTitle =  "[Test Data] Node VetCenter Outstation A"
```
so that other tests could leverage their existence by title and we would not have to keep creating other nodes for tests.

Maybe that is not a gain though if tests are parallelized and we can't gurantee those nodes exist at any given time??
