### ISSUE TITLE
Update VAMC secure messaging links to MHV

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13796]
## Problem to solve
As MyHealtheVet functionality is brought into va.gov, we will need to update existing top task links from VAMC pages to the new corresponding location. 

## Other things to consider
- Difference in endpoint for Cerner vs non-Cerner facilities - will the check still be needed?
  - as of 9/6/2023, our changes are slated for Phase 2 and Cerner is expected to be integrated so fork in experience should no longer be needed
- Lovell bifurcation 
- Can we use a deeper login vs directing the Veteran to an interstitial landing page? 
- How might we clearly indicate login will be needed before the Veteran clicks the action link?
- Updating these links on our side should not be critical path for the MVH roll-out as redirects will be in place to ensure Veteran is directed to the correct endpoint, even if our links are not yet updated

## Current behavior
Veteran clicks link from "Manage your health online" box > directed to va.gov/health-care/secure-messaging/ page > Sign in to send secure messages widget
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3R4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49ad7c35f3245bb604cabc509bc559e1c2e8dd57/image.png)

## Tasks
- [ ] in the Manage your health online box on VAMC system level pages, update link text from `Send a secure message to your health care team` to [TBD - will come from CAIA team)
- [ ] update the secure messaging link to [TBD - will come from Comms team) 
- [ ] coordinate change management with VHA DM for editor-entered links to secure messaging

**Comment by mmiddaugh** [comment]
Blocked pending availability/readiness of feature

**Comment by mmiddaugh** [comment]
Today we direct traffic based on a "Is Cerner" type of flag at the facility level. 
What if this was based on the task?
- Is this task in the modernized space? 
   - If yes -> this modernized link
   - If no, then is this a Cerner facility?
      - If yes -> Cerner link
      - If not -> Vista link
