### ISSUE TITLE
Update VAMC links to make an appointment to MHV

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13797]
## Problem to solve
As MyHealtheVet functionality is brought into va.gov, we will need to update existing top task links from VAMC pages to the new corresponding location. 

Appointments are already part of va.gov but will be migrating from Healthcare Hub to MyHeatheVet and URLs will be changing so we'll want those to land before prioritizing this work. Appointments will be in phase 0 (access via email invite only) tentatively in Aug/Sept so we can target 4Q. 

## Other things to consider
- Difference in endpoint for Cerner vs non-Cerner facilities - will the check still be needed? 
   -  as of 9/6/2023, our changes are slated for Phase 2 and Cerner is expected to be integrated so fork in experience should no longer be needed
- Lovell bifurcation 
- Can we use a deeper login vs directing the Veteran to an interstitial landing page?
   - _MyHealtheVet team will supply link into 1st page of scheduling._
- Can we pass the facility ID to prepopulate that in appointment screen? 
- How might we clearly indicate login will be needed before the Veteran clicks the action link?
- Where are all of the links to make appointments?
   - _MyHealtheVet team should be able to provide referral source data for pages to identify all relevant pages and to monitor after changes are done in case one is missed (or added by an editor)_
- Updating these links on our side should not be critical path for the MVH roll-out as redirects will be in place to ensure Veteran is directed to the correct endpoint, even if our links are not yet updated

## Current behavior
Veteran clicks on top task button or link from "Manage your health online" box > directed to -health-care/make-an-appointment/ page > Make an appointment online widget (login)
<details>
<summary> Screenshots </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3R4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49ad7c35f3245bb604cabc509bc559e1c2e8dd57/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHB4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0477458f1163ea6cc81e9662db3bd6fdcd35d683/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHR4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f2a0c34c4f88dc49eae0962e36e2fc995f7a2da7/image.png)

</details>

## Tasks
in the Manage your health online box on VAMC system level pages
- [ ] update link text from `Schedule and manage health appointments` to [TBD - will come from CAIA team)
- [ ] update the appointments link to [TBD - will come from Comms team) 

for top task (blue `Make an appointment` button
- [ ] update label to [TBD - will come from CAIA team)
- [ ] update the appointments link to [TBD - will come from Comms team) 

for blue `Schedule appointment online` button inside health service accordions
- [ ] update label to [TBD - will come from CAIA team)
- [ ] update the appointments link to [TBD - will come from Comms team) 

- [ ] coordinate change management with VHA DM for editor-entered links to appointments

**Comment by mmiddaugh** [comment]
Per Mikki today, this will probably be first functionality to support since it is already part of VA.gov - targeting 4Q

**Comment by mmiddaugh** [comment]
Blocked pending availability/readiness of feature

**Comment by mmiddaugh** [comment]
Our work is part of Phase 2 and expected by 5/2024

**Comment by mmiddaugh** [comment]
Today we direct traffic based on a "Is Cerner" type of flag at the facility level. 
What if this was based on the task?
- Is this task in the modernized space? 
   - If yes -> this modernized link
   - If no, then is this a Cerner facility?
      - If yes -> Cerner link
      - If not -> Vista link
