### ISSUE TITLE
Cant't flag new VACM facilities for editor contacted

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#13842]
## User Story or Problem Statement

As a first responder to a new facility being flagged, I need to be able to update the revision log with notes and a flag so that I can perform the workflow and accurately reflect what is happening.

The problem is that the facility can not be saved until its system is known and and a menu assigned.

Proposed solution.  New facilties already get the "VAMC facilities" section when migrated in.  We just need to have a menu that matches that "system" so it essentially becomes the isle of lost ~toys~ facilities

## Acceptance Criteria
- [ ] I expect that I can assign a new facility to the VACM facilities menu so that I can save the node when I initiate contact with an editor.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
The benefit of the proposed solution is that there are times when we have an archived facility that creates confusion for editors and have in the past been forced to delete them.    This gives us a better place to park them.

**Comment by davidmpickett** [comment]
From refinement - due to capacity and prioritization, this will likely not be picked up until sprint 89

**Comment by Agile6MSkinner** [comment]
@omahane Swirt was leading this, do you still want to pursue it?
