### ISSUE TITLE
VAMC Clinics: Primary Care health service accordion: Generic text includes reference to walk-ins, but clinics don't offer walk-ins

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#13853]
## Background
There are two related concepts which appear on VAMC facility pages 

- **Average number of days to get an appointment based on a specialty** - _this issue will deal with this part_
   - shown at a service level and appears within the relevant service accordion
- **Veteran satisfaction with appointment wait times at this location** - _handled separately in [#11709](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/11709)_
   - location-level data  which appears below the service accordions
   
VAMC: Display of appointment wait times when data is not available [#14277](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14277) documents a defect in the display in a separate issue
  
## Description

Stakeholders report that "For urgent health issues, we offer same-day appointments, telehealth visits, or walk-in express care." creates confusion when the facility does not have urgent care services. 

**Links to additional relevant information**
- https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-5595
- https://dsva.slack.com/archives/C0FQSS30V/p1685032218916549

<details>
<summary> Screenshot </summary>

![image (12)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/9646141f-c561-4807-9e68-e93ac5bb18ee)

</details>

### Code
Code where the hard coded copy is: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/facilities/FacilityAppointmentWaitTimesWidget.jsx#L56

### Examples
* Clinic FE: https://www.va.gov/new-mexico-health-care/locations/truth-or-consequences-va-clinic/
* Clinic CMS: https://prod.cms.va.gov/new-mexico-health-care/locations/truth-or-consequences-va-clinic
* Primary care health service: https://prod.cms.va.gov/node/30120/edit?destination=/node/1154

## Tasks
- [ ] Add the sentence `Check with your local VA medical center to confirm availability of these services.` to the end of the text under the "Average number of days to get an appointment" heading 

## Acceptance Criteria
- [x] Confirm language with VHA - DM - _done_
- [x] Text below the  "Average number of days to get an appointment" heading reads "We’ll work with you to schedule an appointment with the shortest wait time. In some cases, we may schedule your appointment at another VA medical center or clinic, or refer you to a non-VA medical provider in your community. For urgent health issues, we offer same-day appointments, telehealth visits, or walk-in express care. Check with your local VA medical center to confirm availability of these services."
- [x] All other functionality is maintained
- [x] Accessibility reviewer has been added to the PR

**Comment by jilladams** [comment]
This will be a topic in the VHA DM sync with Fac on 6/13.

**Comment by jilladams** [comment]
@kmariepat-cityfriends I missed the VHA DM sync this week - any update we can give back to support on this one?

**Comment by kmariepat-cityfriends** [comment]
This content will have to run through the content team...
Proposed updated language to come from...VHA DM with program office

**Comment by kmariepat-cityfriends** [comment]
Does this language appear for other service entries as well? We think yes, do a content audit (discuss approach for audit in refinement)

**Comment by mmiddaugh** [comment]
Blocked pending VHA DM input

**Comment by mmiddaugh** [comment]
Language received from Office of Integrated Veteran Care, forwarded by VHA DM

**Comment by xiongjaneg** [comment]
@laflannery The final AC on this is an accessibility review. Would you please let Eli know if you have any questions? Thank you!

**Comment by xiongjaneg** [comment]
Laura was added as a reviewer to the PR. That completes the final AC.
