### ISSUE TITLE
Accordion audit: identify heading level defects

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13880]
## Issue Description
Headings on the page should increase by one in a logical order. A Defect 2 was identified due to the absence of headings within the accordion elements in the "Prepare for your visit" section. The Facilities team is resolving that defect (#18913)and the CMS team will restrict content editorials from creating new defects (#18986). 

We also need to audit the site to understand where else these issues might be hiding. 

---
## Tasks
- [ ] Audit VAMC accordions for heading level defects. 

## Acceptance Criteria
- [ ] _What will be created or happen as a result of this story?_
---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by laflannery** [comment]
Decided I'm closing this now, we do have other tickets noting issues and where we need to make changes
