### ISSUE TITLE
Push facility operating status data to Lighthouse

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1389]
## User Story or Problem Statement

As a veteran, i want the latest facility status available via facility locator tool.

As an editor of a facility's operating status, i want my content to go immediately to the services that display facility status to veterans, so that i know they are get 

## Acceptance Criteria
- [ ] Lighthouse API receives the data within X seconds of saving new operating status info
- [ ] Success is logged in drupal log
- [ ] CMS-team slack is notified with certain problems -- TBD. 
- [ ] Possible next steps documented in a github issue 

## Assumptions
If Drupal has a facility that Lighthouse doesn't?

## Implementation steps
1. A queuer that will queue items on node_save if `field_operating_status_facility` or `field_operating_status_more_info` has been changed, which could be changed manually or by migration
1. Queue trigger to process the queue
1. Call the Lighthouse write/post API
1. Notification if the queue is stalled
1. Slack admin to work on getting a custom slack webhook notification

**Comment by oksana-c** [comment]
push workflow - https://www.lucidchart.com/documents/edit/3b19f443-8d0a-4cd7-ac77-c1c6addda4fd/OdhJVqF-g3cm
