### ISSUE TITLE
Improve operating status editorial experience 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1392]
### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by ContentBrewmaster** [comment]
Added epic template sections including change management.

**Comment by ContentBrewmaster** [comment]
@jilladams are you now the lead on this epic? I had tagged it in my notes as a Q3 priority: is that still true?

**Comment by jilladams** [comment]
No - is a Facilities epic, so likely @dsinla

**Comment by RWEagans** [comment]
Having a discussion with Dave C tomorrow

**Comment by dsinla** [comment]
In convo with Dave C this morning -Ideating on next steps:

Reduce scope - for next Q4
1. Number of alerts you can have 
2. How to limit content - character limit
3. How to assess compliance as editors create alerts (may involve a notification to Facilities team  or VHADM to be aware of new alerts and reach out if not in compliance )

Plan would be to cutover in November - will force editors to recreate banner alerts in their system, 

### Tasks
- [ ] On healthcare product, audit the purpose of all current alerts - Alerts are being used in a way we did not intend in a way that is detrimental.  We want to hear how we can improve this for you, but first we need to fix the poor experience 

Intention is to limit to 1 alert for most important thing.  This is more How to website, not how to technology

**Comment by davidmpickett** [comment]
@dawnpruitt @dsinla Might be good to tidy up this epic before the mid-Q4 check in tomorrow. There's a lot of old tickets in here and it's not clear how this maps to the q4 mural.

**Comment by dsinla** [comment]
@davidmpickett @dawnpruitt  Agree that this Epic has changed in scope and strategy. Not gonna get to this before tomorrow, but can outline my current understanding:

1. Dev work to implement allow_only_one VAMCBA if an editor attempts to create a 2nd <- **DONE** and waiting in the wings
2. Dev work to enforce character limit <- Trivial to do when we're ready to flip the switch 
4. Audit - Understand how VAMCBA are being used and misused <- Happening in this sprint 71
5. Initial recommendations proposed: For all the misuses, provide editors the recommended way to accomplish the same goal
6. Coordinate with Content Team for input and guidance on how best to communicate to editors, provide them our recommendations as initial input 
7. CM - how to roll out, coordinate with VHADM, provide lead time, instructions for "What happens to my existing banners", etc,

**Comment by kmariepat-cityfriends** [comment]
- content audit started (Dave P. to share over materials)
- unmerged PR out there (needs testing)

**Comment by kmariepat-cityfriends** [comment]
- Last ticket completed - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11760
- Next ticket that has been in limbo - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11489
