### ISSUE TITLE
[Facility Locator] Sentry issue: error undefined is not an object

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13929]
# Issue Description
Between 10/6 and 10/16, Sentry logged 56 occurrences for: `TypeError?(src/applications/facility-locator/api/LocatorApi)
error undefined is not an object (evaluating 'e.data.map')` 

## Tasks
- [ ] Determine the root cause for [error](http://sentry10.vfs.va.gov/share/issue/06f77c46deb04f668ab9d3ca1ddc97d3/) and which team needs to resolve

## Acceptance Criteria

For errors **within** Facilities team responsibility
- [ ] Error is no longer thrown

For errors **outside** Facilities team responsibility
- [ ] Issue is created and assigned to the appropriate team

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)

**Comment by mmiddaugh** [comment]
@eselkin based on your investigation into FL alerting and monitoring, do you have any idea if this is still relevant?

**Comment by eselkin** [comment]
I think this is _not_ connected to the other error I was seeing that it was trying to process using `map` of undefined in NearbyVetCenters (when there are no nearby Vet Centers) https://sentry.vfs.va.gov/organizations/vsp/issues/202546/events/b951d3d46c98470ea45c7d7b482ab9ee/events/?project=4.

I don't see this particular error in the logs anymore.

**Comment by mmiddaugh** [comment]
closing because of age, Eli's comment above and in light of upcoming sentry deprecation
