### ISSUE TITLE
VAMC health service "Available at these locations" list sort order

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#13941]
## Issue Description
The "Available at these locations" list in a health service accordion doesn't seem to have a logical order - likely due to a bug and/or oversight.

<details>
<summary> screenshot </summary> 

![image](https://user-images.githubusercontent.com/55411834/130649944-529e59eb-be75-4a06-8c95-851d42c23b32.png)

</details>

### Expected behavior
The list should be ordered using the same logic as the Locations page
- Main clinics
- Alpha list of health clinics
- Doms/CLCs
- Mobile

## Dev note
- preferred method is to add a filter rather than addressing in the template

---
## Tasks
- [x] Implement sort order logic from Locations page for  "Available at these locations" list in a health service accordion

## Acceptance Criteria
- [x] Sort order within health services accordions is consistent with Locations page sort order logic
- [x] VA clinic locations are listed first, beginning with the main location, followed by Doms and CLCs, followed by Mobile clinics 
- [x] Facilities are listed alphabetically within a facility subtype 
- [x] Changes communicated to CMS Team Support

**Comment by eselkin** [comment]
This seems to still be happening.
the liquid file `health_service.drupal.liquid` seems to just take `healthService.fieldLocalHealthCareService` and iterate over it without a any filter or sort.

**Comment by swirtSJW** [comment]
These are the two sources of data in the CMS

Bubble to the top field_main_location (fieldMainLocation)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/fb8fa458-7c99-4ee4-8d70-ca483ae63b8e)

Possible for other sort field_facility_classification (fieldFacilityClassification)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/c9c32422-9b7d-4c91-af4a-09f6aee61f1d)

**Comment by maxx1128** [comment]
This is an example data object from one of the locations in the example.

```json
{
    "entityId": "26895",
    "entityType": "node",
    "entityUrl": {
        "path": "/houston-health-care/health-services/gastroenterology-at-va-houston-health-care"
    },
    "fieldBody": {
        "processed": "<html><head></head><body><p><strong>Care we provide at VA Houston&#xA0; health care</strong></p>\n<p>Staff in our gastroenterology department can provide the following treatments:</p>\n<ul><li>Colonoscopy</li>\n<li>Endoscopic services</li>\n<li>Treatments for complex gastrointestinal conditions</li>\n<li>Services for patients with liver diseases</li>\n<li>Early screening and cancer detection</li>\n</ul><p><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"2f3c9623-bd71-4002-b423-f8ad74e77841\" href=\"/houston-health-care/programs/gastroenterology-and-hepatology\" title=\"Gastroenterology and hepatology\">Learn more about gastroenterology at VA Houston.</a></p>\n</body></html>"
    },
    "fieldLocalHealthCareService": [
        {
            "entity": {
                "status": true,
                "entityUrl": {
                    "path": "/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center/gastroenterology"
                },
                "fieldFacilityLocation": {
                    "entity": {
                        "entityUrl": {
                            "path": "/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center"
                        },
                        "title": "Michael E. DeBakey Department of Veterans Affairs Medical Center"
                    }
                },
                "fieldAdministration": {
                    "entity": {
                        "entityId": "228"
                    }
                }
            }
        }
    ],
    "fieldServiceNameAndDescripti": {
        "entity": {
            "weight": 0,
            "entityId": "86",
            "entityBundle": "health_care_service_taxonomy",
            "fieldAlsoKnownAs": "Digestive care, GI",
            "fieldCommonlyTreatedCondition": "reflux, GERD, Barrett's esophagus, endoscopy, colonoscopy",
            "name": "Gastroenterology",
            "description": {
                "processed": "<html><head></head><body>Our gastrointestinal (GI) specialists offer screening and treatment for conditions affecting your GI tract, gallbladder, liver&#xA0;and pancreas&#x2014;like reflux, Crohn&#x2019;s disease, hepatitis and pancreatitis.</body></html>"
            },
            "fieldTricareDescription": null,
            "fieldServiceTypeOfCare": "Specialty care"
        }
    }
}
```

Like Eli noted above, `healthService.fieldLocalHealthCareService` is being passed into the template, but we could also pass `healthService.fieldServiceNameAndDescripti` into the template as well for the additional info. However, I don't see any info there that can help with the needed sorting either. The closest I see is `fieldServiceTypeOfCare`, but it only has the following different values: `"Specialty care", "Mental health care", "Social programs and services", "Primary care", "Other services"`.

Are there any extra fields we can add to the GraphQL queries to get in the needed data?

**Comment by eselkin** [comment]
@maxx1128 and I met to look for where we might pull the data from for this sort. However, we were not able to find where the data could be pulled from. We investigated similar queries, CMS data (specifically health care location pages:
https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/houston-health-care/locations/michael-e-debakey-department-of-veterans-affairs-medical-center
and
https://cms-txcrk8bym4a0ivw3xfr8xvdhezmls36f.demo.cms.va.gov/houston-health-care/locations
) and find no identifying information to query for that sort. We need someone familiar with the data structures here, perhaps @omahane who has worked in these data structures to help us find what to add to the query.

**Comment by swirtSJW** [comment]
Sorry I mislead you when I said this data comes from the Facility API.  I was mistaken about which ticket we were talking about.

Main clinics -> detectable by the field field_main_location == 1 though this is only used when there are more than one medical center in a system
Alpha list of health clinics ->  (anything that is not a Main, Dom, Mobile or CLC.   If you extract all the others, this is what you have left)
Doms/CLCs  -> detectable by field_facility_classification
Mobile  -> detectable by  field_mobile == 1

These are the values present in field_facility_classification
value| label
1|VA Medical Center (VAMC)
2|Health Care Center (HCC)
3|Multi-Specialty CBOC
4|Primary Care CBOC
5|MCS
6|Other Outpatient Services (OOS)
7|Extended Care Site (Community Living Center) (Stand-Alone)
8|Residential Care Site (MH RRTP/DRRTP) (Stand-Alone)

**Comment by swirtSJW** [comment]
field_facility_classification
field_mobile
field_main_location

are all fields on the Facility, not the individual services.

**Comment by maxx1128** [comment]
Per the end of Sprint 91, there's a pull request open for this ticket, and should be starting to undergo some review soon. For Sprint 92, it just needs any needed review and modifications before being merged, and then it can get closed.

**Comment by xiongjaneg** [comment]
@maxx1128 This looks merged but no updates since then. Would you please update this and mark off completed ACs? For the last AC, I can submit a summary to CMS Team for review.

**Comment by maxx1128** [comment]
@xiongjaneg I confirmed this change has occurred on Prod (see screenshot below). I updated the tasks and ACs.

<img width="1225" alt="Screen Shot 2023-09-12 at 2 31 36 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/10790736/7587de10-3743-4fd9-9424-9b83ad97e5ac">

**Comment by xiongjaneg** [comment]
Shared in [CMS Support slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1694544855896359)
