### ISSUE TITLE
PW Sprint 86 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#13967]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626 🟢 
Design: 

Engineering:
- [x] (carryover) #13558 (8) - Ruby
- [ ] #13586 (5) - FE 🎯 
- [ ] #13968 (5) - Ruby
- [ ] #13969 (3) - FE  
- [ ] #14021 () - FE
- [x] #12354 (3) - BE
- [ ] (stretch; blocked) #13750 () - FE

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628 🟢 
- [x] #13802 () - BE
- [ ] (note: CMS team dependency) #13755 (3) - Design
- [ ] #13756 (5) - BE
- [ ] NEXT tickets generated by 13756
- [ ] (stretch) #13207 (3) - BE

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170 🟢  
- [ ] (stretch; Cindy dependency) #13965 (3)
- [x] (stretch) #13327 - PM

### 4. Expand Q&A Reusability https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780 🟡 
- [ ] (stretch) #10936 (3) - BE
- [ ] (stretch) #10941 (5) - BE
- [ ] (stretch) #10937 (3) - FE
- [ ] (stretch) #13725 (5) - Design

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. 
🔴 Not yet actionable. (DST building their Ph1 (sample form) in Q2.)

### Other Q2 priorities not in motion 🔴 
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- Header/footer redesign - Awaiting info / green light for kickoff

### Post-MVP Homepage 🟢 
- [ ] #12292 (5) - BE
- [ ] (stretch; dep on 13955) #11921 (5) - BE
- [ ] (stretch; dep. Jordan capacity) #14002 - Design

### Cerner API deprecation support 🔴 
- [ ]  (unblocked? Need FE eng to confirm) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

# Other PW Priorities

Cross-repo dependencies post-mortem 🟡 
- [ ] (stretch) #13730 (needsrefining) - FE/BE
- [ ] (stretch) #13731 (needsrefining) - FE/BE

Other priorities 🟡 
- [x] #11313 (5) - FE
- [ ] (stretch; blocks missing-event defect 10307) #12932 (8) - FE (Daniel)
- [ ] (stretch) #10307 (8, partially done) - FE 
- [ ] (stretch) #13222 (8) - FE
- [ ] (s87 most likely) #13990 - BE
- [ ] #11354 

Forms monitoring/errors: 🔴 
- Tickets are in stages of refinement; no immediate options to prioritize

### Content / IA priorities 🔴 
- [ ] #14104 
- [ ] (blocked; CLP-related) va.gov-team 58142
- [ ] (blocked on 58142) #13603 () - FE

Epic of upcoming redirects not yet in our board: 🔴 
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] (stretch) #13136 (3) - FE
- (later) #13137 (needsrefining) - FE
- (later) #13147 (needsrefining) - FE

### Tech debt & Defects

**Comment by jilladams** [comment]
Refine in planning: 

- [ ] #14021 
- [ ] #13755 design
- [ ] #13725 design
- [ ] stretch #14002 design
- [ ] stretch/blocked #13750 
Could punt to refinement:
- [ ] #13730 
- [ ] #13731 


Suggested Goals: 

- #13586 
- #13756 or #13755 
- #13227
