### ISSUE TITLE
Migrate hours to Vet Center Community Access Point

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14001]
## User Story or Problem Statement

As a Veteran, I want the timezone of a Vet Center CAP to be accurate, based on the location.

## Acceptance Criteria
- [ ] Venter Center CAP timezone field is populated with data from the Facilities API.

## Implementation steps
- Timezone is added to the migration configuration for Vet Center CAP.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
