### ISSUE TITLE
[EPIC] CMS Collab Cycle Improvements

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14013]
## Background

As the CMS product matures and engrains itself in the VA.gov eco, there is fast developing other products and teams that want to collaborate, update and conform it for assimilation into their products. The CMS team needs to begin putting governance around it -- thinking of it as the platform is truly is -- so that the controls to maintain quality and consistency are normalized which in turn will also better enable other products to understand and plan around those enhancements they may desire to make.

## User Story / Problem Space
As a **CMS discipline/function owner**, I want to be able to clearly articulate when and how I'd like other teams to inform/collab with me, so that I can appropriate direct them with a singular voice.

As a **product utilizing the CMS**, I want as much clarity around new development in the CMS, so that I know how to plan and communicate those changes for speed-to-market purposes.  

**HMW** create a cyclical workflow that continues/furthers (a) high quality standards for the CMS platform and (b) isn't overly cumbersome for external teams to interact with?

### Priority and OKRs
We will be measuring success by creating an ongoing survey for other products to give feedback. For 3Q our goal is to achieve a 6/10 each for thoroughness, clarity and user-centeredness.

### Definition of Done
 

- [ ] Scope of governance for each discipline has been explicitly defined and stated.
- [ ]  Starter documentation added to the CMS confluence space.
- [ ]  Visual workflow -- at least loosely based on updated platform workflow -- has been developed and expanded for CMS team.
- [ ]  Associated documentation for where in the workflow and how each discipline/function wants to be notified and included in the collab cycle.
- [ ]  CMS team internal approvals have been received and logged. Including PO.
- [ ]  Potential collab cycle consumer(s) approvals have been received and logged. Including sitewide POs.
- [ ]  Measurement system in place and has scored at least 6/10 each for governance thoroughness, clarity and user-centeredness has been reached.

### Things this will include (TBD)

- [ ] Governance for editor journeys: Access; Content Management/CRUD; Publishing; Support/KB
- [ ]  PR reviews
- [ ]  Defect discovery
- [ ]  New enhancement requests
- [ ] 

### Things this will not include
TBD
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17442
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17563
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17813
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17942
```

**Comment by EWashb** [comment]
We may be at a point now where we should regroup with the Platform Governance team on how we might align/attach ourselves to their touchpoint checklist. I talked about this work with @naomimarcussen, and we have some ideas about properly aligning our efforts through integration with existing touchpoints rather than creating a separate process.

**Comment by EWashb** [comment]
@gracekretschmer-metrostar I cleaned up the tasks within this epic. Since you are currently doing a lot of discovery on this then we will go with whatever tickets you create as the best path forward. I would be glad to help you work through refining this epic, though, because I know a lot of the description above is not the current state or accounting for our integration with Platform Crew.

**Comment by gracekretschmer-metrostar** [comment]
Will be reaching out to Shira later this week and we will be shadowing design intent sessions.

**Comment by EWashb** [comment]
@gracekretschmer-metrostar is this ready to be closed?
