### ISSUE TITLE
Auto archiving VC Outstations and Mobiles when removed from source.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#14032]
## User Story or Problem Statement

As a CMS data maintainer, I would like to have VC Outstations and Mobiles automatically archived when they are removed from the Facility API source.

Neither VetCenter Outstations nor Mobile VetCenters have services attached to them AND they do not have pages of their own, so the assumption here is that they could be autoarchived without needing human followup.

## Acceptance Criteria
- [ ] When a NCA Facilities, VC Outstation or Mobile VetCenter is removed from the Facility API (source) these facilities will
   - [x] Have there moderation state set to archived
   - [x] Have it facility status set to closed
   - [x] Have its facility  status moreinfo blanked out.
   - [x] Revision log entry is made and attributed to CMS migrator.
   - [x] Not get flagged.
   

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
I updated the related documentation here.
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/flagged-facilities.md

**Comment by swirtSJW** [comment]
I updated the runbooks for 
* [Vet center Mobile and outstation](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-closed.md) 
* Validate that [NCA Facility close](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-nca-facility-closed.md) already covers this

**Comment by jilladams** [comment]
@swirtSJW if PO review is the only step here, we can close. If that's the case, will
