### ISSUE TITLE
Set up codeowners notifications for Public Websites in CMS repo

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14061]
## User story
AS A: CMS contributing team
I WANT: a clear indicator when changes are made that might affect my team's products
SO THAT: I can ensure operational stability

## Description
In the spirit of the CMS as a platform where many product teams can be contributing: we want to support a clear definition of ownership where possible. Meaning: which teams own which files and features, and should be notified to code review any changes being made to those files. 

The .github/codeowners file is a mechanism that can help with this. Codeowners files articulate: 
* filepath
* User group(s) who "own" that file path

When Pull Requests make changes to files with listed owners, owners will be automatically added as Reviewers.

In vets-website & content build, this is used to help ensure that if another team modifies your team's file(s), you'll be notified and can vet the changes: https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS

In CMS, the codeowners file is not set up this way to notify PW / Fac teams yet. We should do that: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/CODEOWNERS

### **Issues/concerns**
- CMS code could be optimized to make structure more amenable to shared ownership. 
    - To what extent does the existing codebase structure limit this effort? Ideally, shouldn't block us doing what we can now. Is that realistic?
    - Would ideally be prioritized / owned on CMS team
    - Will be limited in some cases by Drupal native code structures / behaviors like the /config directory (one big slush pile folder, and spread across db tables
- Things that will probably be easy to articulate as code paths for product teams to own: 
    - Custom modules for product team features / functionality
    - Contrib modules that are used / added specifically by product teams for product features
    - Template files for product features
- How do we avoid being required reviewers for maintenance work from CMS team that doesn't affect product behavior?

### **PW ownership:**
Drupal elements to consider 
  - Benefits Hub Landing Page
  - Benefits Detail Page
  - Campaign Landing Pages
  - Dark launch staging-only entity queue
  - Events List
  - Event
  - FAQ Page
  - Footer & Header menus
  - Homepage: menus, custom blocks, custom module, entityqueues
        - has its own module, PW can own that
  - VA Forms migrations
        - Find-a-form
  - Full-width Alert
  - Promo Banner
  - Outreach Materials Library (Publication listing & page)
  - Q&A - single
  - Resources & Support detail page
- Need an epic?

**Tasks:**

- [ ] Evaluate what portions of CMS code the Public Websites engineers should be notified about, if changes are initiated by other teams
- [x] Figure out if we already have user groups that we can use for this, or need to make them.
     * No - we have CMS teams: https://github.com/orgs/department-of-veterans-affairs/teams/?query=cms
     * We have PW frontend team: https://github.com/orgs/department-of-veterans-affairs/teams/?query=public
     * We'll need to decide a team name and make the team, notes in comment
- [x] If we need to make them, make them.
- [ ] Add those lines to the codeowners file with the appropriate user group

## Acceptance Criteria
- [ ] Identified custom PHP code that PW has written that could be isolated for code ownership – i.e., modules or files within other modules that PW wholly owns.
- [ ] Added file paths to file above to make PW code owners of those files/modules/etc.
- [ ] Documented any additional findings that need follow-up or would be useful to CMS team for later restructuring

**Comment by jilladams** [comment]
I can set up the codeowner team for this in VA (or anyone may be able to). Existing CMS teams: https://github.com/orgs/department-of-veterans-affairs/teams/?query=cms

I would suggest calling this codeowner team `public-websites-cms` and limiting this to Drupal changes. But: if it makes more sense to make it a `public-websites-backend`, we could use that for other Income Limits API related things as well, if that's relevant in the CMS repo, but I don't think it is. @dsasser @jtmst  can opine on that when we refine.

**Comment by jilladams** [comment]
Hrm. I accidentally submitted the form and now we have https://github.com/orgs/department-of-veterans-affairs/teams/public-websites-cms . It doesn't appear that I have perms to change the team name, but: if we opt for a different name, I prob could figure that out with Github admins as needed.

**Comment by jilladams** [comment]
Sister ticket for Facilities: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14060
I've also chatted with @swirtSJW as FYI of the flags we brought up (in ticket body) in BE refinement yesterday, for reference.

**Comment by wesrowe** [comment]
refinement 6/15: leave this in Needs refining until Dave has had convo in PO sync.

**Comment by wesrowe** [comment]
Update: this will likely be on the agenda at the next Scrum of Scrums in a couple weeks

**Comment by jilladams** [comment]
Nate did do a bunch of work on codeowners: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14342, and @dsasser was a reviewer of that PR. I'd defer to Daniel re: whether everything that _could_ be attributed to us as owners already is, or if we could spend a littlet ime and help fine tune.

**Comment by FranECross** [comment]
Moved to next refinement to discuss with Daniel and decide if more review is needed.

**Comment by dsasser** [comment]
## Status Update 2/8/24

Discovery for PW owned code has been done. Findings attached below:

[VACMS-14601_ PW Codeowners.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/14213302/VACMS-14601_.PW.Codeowners.xlsx)

CODEOWNERS file has been updated to reflect findings. [PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17168) is is currently pending review.

**Comment by dsasser** [comment]
## Status Update 2/12/24

Changes to CODEOWNERS was merged 2/9/24 and confirmed on main.
