### ISSUE TITLE
Knowledge-base (KB) Enhancements

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14069]
## Background

The Knowledge Base was launched in 2020 to support the editors through self-help articles and training materials. We have not large-scale iterated on the product since the launch. The CMS Team has received feedback that the KB articles are not always plain language, make sense for the task, can be hard to find, are not organized in a coherent way, etc. These are all datapoints that should be confirmed through proper analysis and research. 

Erika notes: The current left Nav in the Knowledge Base isn't correct. The items listed are not product guides and we have received feedback from high-profile editors that it doesn't make sense. At the very least, can we change those links without doing a large facelift on the KB?

### User Story or Problem Statement
As an editor, I want to be able to quickly find accurate support content so that I can confidently complete my task in accordance to VA standards and requirements. 

As a user support team member, I want to be able to confidently direct users to the knowledge base to encourage self-help more efficiently. 

### Affected users and stakeholders

* CMS editors of all products
* Helpdesk personnel
* New Drupal teammates

## Helpful Links
- [Understanding Drupal CMS Editors' Knowledge Base Needs: Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/research/knowledge-base/kb-research-findings.md)
- [Knowledge Base Worksheet](https://app.mural.co/t/mdominguezoddball1033/m/mdominguezoddball1033/1707934939645/a27aa48f0275c7797c35ee3d76c860cbf6d773b7?sender=22108dd9-dbd8-4462-8c25-114e74f0e8d1)

### Hypothesis
- Editors would prefer a Knowledge Base more tailored to their needs.
- Editors currently experience pain when searching for articles to complete their tasks.

## Assumptions
* We assume that the KB should be redesigned.
* We assume the search within the KB is not intuitive.
* We assume that the nav and menus are not intuitive.
* We assume that the current structure does not meet requirements for scalability. 
* We assume that training is outdated or missing elements. 

## Acceptance Criteria
- [ ] KB Landing page redesigned with a product-specific focus.
- [ ] Search is updated to reflect appropriate taxonomy
- [ ] Analytics (either Datadog or GA4) is implemented to measure success. 

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [X] `Purpose-driven`: Create an opportunity to involve the editor community in VA?s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [X] `Approachable`: Offer friendly guidance over authoritative instruction.
- [X] `Consistent`: Reduce user?s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

```[tasklist]
### Tasks
- [x] Knowledge Base Study: Synthesis and Reporting #17099
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17909
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17940
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18113
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17383
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18116
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18115
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18805
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19069
```

**Comment by EWashb** [comment]
Adding a note for myself to come back and refine this epic.

**Comment by EWashb** [comment]
@gracekretschmer-metrostar here is the epic for the KB project. More than likely it need to be refined and updated for current state.

**Comment by gracekretschmer-metrostar** [comment]
@MDomngz Could you help me in refining the hypothesis, assumptions, and acceptance criteria for this epic? I would like it to better reflect what we decided on as next steps during our meeting earlier today.

**Comment by MDomngz** [comment]
[Mural board link](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1709667164024/6cb8bb5a493ae9f4b91d843205f56a83d53dd90e?sender=u4c8b6076357da42993941037) with KB research synthesized and ready for action. 

I conducted an audit of the in-place CMS Design System and determined that the current state is below the bar and is therefore unsupportive of not only my immediate UX task with redesigning the KB Landing but in addition, the design system does not support any teams building editor functionality into the Drupal CMS system. A deeper audit for understanding is underway to discover our options for team planning.

**Comment by smarithaponnala** [comment]
Closing as this hasnt been updated in 4 month
