### ISSUE TITLE
PW Sprint 87 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14079]
## Q2 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626
🔴  Design / Research:

🟡 Product: 
- (carryover from s86, waiting on Plat Analytics implementation) #13480 - Product
- (when ready) #14106 () - Product

🟢 Engineering:
- [x] #13586 (5) - FE  🎯 
- [x] #14049 (3) - FE
- [x] #13968 (5) - Ruby 🎯 
- [x] #14050 (3) - FE
- [ ] #14044 (5) - FE
- [x] #13969 (3) - FE

Stretch for team to continue as sprint allows:
- [ ] #13593 (3) - FE
- [ ] #14047 (3) - FE
- [ ] (blocked on final content & stakeholder review) #13750 () - FE
- [ ] (blocked on final decision whether to drupalize the start screen) #13751 () - FE

Post-mvp:
- #14046 (8) - FE

### 2. Benefit Content Model Hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628 🟢 
- [x] #14085 () - BE
- [x] #14086 () - Design
- [ ] (stretch) #14095 () - Research/Design/Product
- [ ] #13207 (3) - BE

### 3. PACT Act Wizard https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170 🟡 
- [x] #13324 (5) - Research
- [x] #13722 () - Research

### 4. Expand Q&A Reusability https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780 🟡 
- [x] #10936 (3) - BE
- [ ] (stretch) #10941 (5) - BE
- [x] #10937 (3) - FE
- [ ] (stretch) #13725 (needsrefining) - Design

### 5. Public WebsitesUS Design System 3.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12995  🔴 
Updating any design system components to be compliant with USWDS 3.0, downstream from VA Design System work. 

### Other Q2 priorities not in motion 🔴 
- **Translation in R&S, Hubs** (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- **Public Websites supporting MHV on VA.gov** – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
- **Header/footer redesign** - Awaiting info / green light for kickoff
    - DaveC to schedule a design context kickoff sometime during S87 (after AndyL meeting) & record for Cindy's later reference
- **Mobile promotional banners** - Want to kick off Collab Cycle, based on product brief. 

### Post-MVP Homepage 🟢 
- [ ] #11921 (5) - BE

### Cerner API deprecation support 🔴 
- [ ]  (BLOCKED) #9307 (5) - https://github.com/department-of-veterans-affairs/vets-website/pull/23036#issuecomment-1448615887 - FE

# Other PW Priorities

Cross-repo dependencies post-mortem
- [ ] (stretch) #13730 (needsrefining) - FE/BE
- [ ] (stretch) #13731 (needsrefining) - FE/BE

Other priorities
- [x] (in progress s86) #11313 (5) - FE
- [x] #10307 (8, partially done) - FE 
- [ ] (stretch) #14071 (3) - FE
- [ ] (stretch) #13329 (3) - BE
- [ ] (stretch) #13222 (8) - FE
- [ ] (stretch) #13062 (3) - FE

Forms monitoring/errors:
- Tickets are in stages of refinement; no immediate options to prioritize

### Content / IA priorities
- [ ] #14119 
- [x] #14104 
- [ ] (blocked; CLP-related) va.gov-team 58142

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] (stretch) #13137 (needsrefining) - FE
- [ ] (stretch) #13147 (needsrefining) - FE

**Comment by wesrowe** [comment]
@cindymerrill, could use an estimate on this when you have a moment

**Comment by cindymerrill** [comment]
@wesrowe An estimate on what?

**Comment by wesrowe** [comment]
ugh, sorry, I put that comment on the wrong ticket. disregard

**Comment by jilladams** [comment]
for refining: 
- [ ] #14085
