### ISSUE TITLE
CMS Team Sprint 87 Plan

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14080]
<summary>**CMS Team Sprint 87 Goals & Notes**</summary>
<br>

- [x] #13387  🥅
- [x] #13592  🥅
- [x] #13951  🥅

<br>

**Notes:** 
<details><summary>Capacity assumptions: attempted to limit to 6 story points for each person-sprint. July 4th holiday and extra capacity for maintenance, 3Q alignment.</summary>
Current plan:</br>
- Jo --> 8 (BX: re-refined ticket with Jo and increased the estimate from 5pts to 8pts)</br>
- Blake --> 5 </br>
- Tim --> N/a </br>
- Nate --> 8</br>
- Eric --> 8</br>
- Edmund --> 5</br>
- Tony --> 5</br>
- Tolashe --> 8</br>
- Laura --> 5</br>
  
</details>

- [ ] Editor Trust Survey is pending VIEWS approval process. All work has been put on pause -- this will live on under Objective: Strengthen the CMS ecosystem of users and partners for 3Q.
- [ ] Lagoon continues to be on hold until funding clears. Will be working under the assumption this likely won't be workable until closer to 4Q.
- [ ] Translations MVP has completed. Documentation loose ends and ongoing feedback will continued to be prioritized.

<details><summary>S86: 2Q Goals Plan</summary>

## Alt Text Enhancements [2QG: Finalize Prototype] 
- [x] #13387 

## Drupal 10 Upgrade Pathway [2QG: TBD/Reassessing]
- [x] #14066 
- [ ] #12453

## Editor Notifications [2QG: Send VAMC, Vet Center; Identify and Send New] 
- [x] #13592 

## Editor Trust Survey [2QG: Communicate Baseline Editor Trust in CMS]
- [ ] N/a - VIEWS process.

## Lagoon Implementation Planning [2QG: Supporting BRD for CMS; funding]
- [ ] ON HOLD

## Permissions Schema Update [2QG: Communicate Proposal]
- [ ] Quarterly goal reached. Paused until further digging.

## Multilingual Content [2QG: Deliver Working MVP]
- [ ] #13540 

</details>

<details><summary>S86: Functional Area Needs</summary>

## DevSecOps 
- [ ] #14075 (blocked)
- [x] #13844 
- [ ] #13771 (blocked)
- [x] #14126 

## a11y
- [x] #13951 
- [x] #10368 
- [ ] #10111

## UXD
- [x] #13350

## Milestone Items: 
- [ ] #14081 

## Defect: 
- [ ] #14129 (stretch)

</details>

**Comment by BerniXiongA6** [comment]
Note for @EWashb and @productmike : I met with @joagnitti today to re-refine her remaining tickets for the Alt Text Creation study. Here's what came out of that discussion:

Sprint 87: 
- Jo can work on Ticket #13387 (complete synthesis - 8 pts)

_FYI for future sprints: Jo and I pre-refined the following tickets that can start after she completes synthesis_
- #14103 (complete topline summary - 5 pts)
- #14101 (complete research findings report - not sized yet)
-  #13787 (present findings - 5 pts)

Hope this helps us to better understand the breakdown of what's left to do for this usability research initiative.

**Comment by EWashb** [comment]
I would like to remove #12963 from the sprint goals. I hesitate to bring it in with folks out and I'm not clear what the ACs are @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Hi @EWashb -- yes with Mike gone this current and most of this coming sprint, I think you can move #12963 to the following sprint.
