### ISSUE TITLE
[DevSecOps P1] CMS TLS Certificate Expires July 30 2023 For All Environments

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14140]
## Description
As a DevOps engineer, I need to renew the CMS TLS certificate that secures all environments and coordinate the change with Identity and Access Management SSOi IdP, so that we can maintain the CMS's federated authentication and HTTP security posture.

* Certificate expires July 30, 2023.

## Acceptance Criteria
- [x] Use Venafi to renew CMS TLS Certificate
- [x] Coordinate with IAM SSOi Team to implement the certificate:
  - [x] Provide Public Cert to IAM SSOi Team
  - [ ] Update the certificate private key on the CMS severs at the same time IAM Team updates.

## Implementation Details
- [Renew Certificate with Venafi](https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi+Create+and+download+TLS+certificates)
- [Coordinate certificate update with IAM team.](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/coordinate-cert-update-with-iam-team.md)
https://dsva.slack.com/archives/C02HX4AQZ33/p1657135877991339
- [Previous Ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9728)
- [Previous Devops PR](https://github.com/department-of-veterans-affairs/devops/pull/11527)

## Task List
- [x]  [Create Pull Request](#devops-pull-request) to update Dev/Staging certificate in DevOps Repo.
- [x]  [Create IAM Lower Environment Trouble Ticket (LETT)](#creating-an-identity-access-management-lower-environment-trouble-ticket-lett)
- [x]  Coordinate with IAM Team to join their AcS Non-prod Release Window. [See schedule](#external-team-schedules)
- [x]  [Install New Certificate During Maintenance Window](#install-new-certificate-during-maintenance-window)
- [x]  Merge Dev/Staging certificate change PR after login tested.
- [x] Update SSM Parameter `/devops/certificates/cms-nonprod-va-gov.key` immediately after merge
- [x] Delete SSM Parameter `/devops/certificates/non-prod-cms-va-gov.key` no longer necessary
- [x]  [Create Pull Request](https://github.com/department-of-veterans-affairs/devops/pull/13209) to update Production certificate in DevOps Repo.
- [ ] ~~Create a Change Request Ticket (SNOW)~~
- [ ] ~~Receive Fed Lead Approval on created CR.~~
- [ ] ~~Fill in CR fields under "Customer Impact tab:"~~
- [ ] ~~Attend and speak at Enterprise Change Advisory Board (CAB) @ [Date TBD]~~
 - [ ] ~~Attain CAB approval.~~
- [x] Coordinate with IAM team to update CMS Signing Certificate:
  - [ ] First Window **July 20th**
  - [ ] Second Window **July 27th**
- [ ] On the CMS Prod Server manually update certs: 
  - [ ] /certs/cms.va.gov.private.key with 
  - [ ] /certs/cms.va.gov.public.crt with 
  - [ ] Restart HTTPd service
- [ ] Test PIV login
- [ ] Update SSM Parameter /devops/certificates/cms-va-gov.key
- [ ] Update SSM Parameter /devops/certificates/cms-va-gov.crt
- [ ] Merge [Prod DevOps PR](https://github.com/department-of-veterans-affairs/devops/pull/13209)
- [ ] Update certificate in AWS Certificate Manager

**Comment by EWashb** [comment]
@productmike @BerniXiongA6 this will need to be high priority in the next sprint. @olivereri may also find that he should start the process earlier and I am ok with that if he needs to. We are racing against a 7/30/23 expiration of our current certificate.

**Comment by EWashb** [comment]
@olivereri Do you know what level TLS the CMS will be on once this certification is complete?

**Comment by productmike** [comment]
@olivereri Since this is a technical task and it was authored by you :) , I'm working under the assumption that this is refined and can be prioritized for the next sprint -- let me know if you don't agree. If so, can you also story point the effort for this as well so we can plan against capacity?

Removing the refinement label and moving into READY FOR SPRINT.

cc @EWashb @BerniXiongA6

**Comment by EWashb** [comment]
It looks ready to me @productmike @BerniXiongA6, but Eric can weigh in to be certain

**Comment by olivereri** [comment]
Staging environment update status:
DevOps PR created
[ ] - Merge PR after IAM maintenance window https://github.com/department-of-veterans-affairs/devops/pull/13208
[ ] - Update SSM Key `/devops/certificates/cms-nonprod-va-gov.key` immediately after merge
[ ] - Delete SSM Key `/devops/certificates/non-prod-cms-va-gov.key` no longer necessary

**Comment by olivereri** [comment]
# Production Environment Certificate Update Status:

- [ ] Merge PR after IAM maintenance window https://github.com/department-of-veterans-affairs/devops/pull/13209

**Comment by olivereri** [comment]
We are on for July 20th Prod TLS certificate update:

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/31904439/8da37072-3036-45fb-bc87-21acf6c876ae)

**Comment by olivereri** [comment]
Remaining work will be completed in this ticket;
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14435
