### ISSUE TITLE
PW Sprint 88 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14142]
## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)
🔴  Design / Research:

🟡 Product: 
- (carryover from s86, waiting on Plat Analytics implementation) #13480 - Product
- (when ready) #14106 () - Product

🟢 Engineering:
- [ ] #14200 (needs) - FE
- [ ] #13751 (needs) - FE
- [ ] #13737 (3) - FE
- [ ] (blocked on content review) #13750 () - FE
- [ ] #13614 (3) - FE/BE

### 2. PACT Act Wizard [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢  
- [ ] (stretch) (started s87, continue when Cindy is avail post-PTO #13324 (5) - Research
- [ ] (stretch) #14072 (5) - FE

### 4. Expand Q&A Reusability [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡 
- [ ] (carryover from s87) #10936 (3) - BE
- [ ] #10941 (5) - BE
- [ ] (s89; blocked on BE) #10944 () - FE

### 5. Benefit Content Model Hardening [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢 
- [ ] (may carryover from s87) #14085 (5; underestimated) - BE
- [ ] (may carryover from s87) #14086 (5) - Design
- [ ] #14095 (0) - Product

### Mobile App Promotional Banners [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482)
- [ ] (stretch) #13481 (5) - FE
- [ ] (stretch) #14179 (0) - Product

### Post-MVP Homepage 🟢 
- [ ] #14002 (3) - Design 
- [ ] (stretch; blocked on design/14002) #13863 (3) - BE

### Cerner API deprecation support 🟡 
- [ ] (stretch)  (no longer blocked - PR is ready) #9307 (5) - FE

# Other PW Priorities
## Prioritized for this sprint
- [ ] #14185 (3) - BE
- [ ] #14274 (3) - BE
- [ ] (stretch; CMS team promised D10 env for 7/10) #13990 () - BE

## Backlog of non-quarter priorities (for easy access)
Tech debt, Defects, Drupal 10 upgrade
- [ ] (stretch) #14071 (3) - FE

Cross-repo dependencies post-mortem
- [ ] (stretch) #13730 (3) - FE/BE

Other priorities
- [ ] #13736 (8) - FE
- [ ] #12325 (2) - BE
- [ ] (stretch) #13329 (3) - BE
- [ ] (stretch) #13222 (8) - FE
- [ ] (stretch) #13062 (3) - FE

### Content / IA priorities
- [ ] (blocked; CLP-related) va.gov-team 58142

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [x] (stretch) #13136 (3) - FE
- [ ] (stretch) #13147 (needsrefining) - FE
- [ ] (stretch) #13137 (needsrefining) - FE
- [ ] (blocked on Appointment team's design work) #14219 (needs) - FE

### Other priorities not in motion 🔴 
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.

**Comment by wesrowe** [comment]
Priorities for BE and non-top-5 effort s88:

- [ ] (D10) #14185 
- [ ] (D10) #13990 
- [ ] #13481 
- [ ] #13863 
- [ ] #13736 
- [ ] #12325 
- [ ] #13730

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13481 = stretch
