### ISSUE TITLE
I.L. FE: Use Subtask code pattern for application

### ISSUE THREAD

**Issue by randimays** [department-of-veterans-affairs/va.gov-cms#14177]
## Description
The SubTask pattern has [design guidance](https://design.va.gov/patterns/help-users-to/complete-a-sub-task) as well as a [code implementation](https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-sub-tasks). We need to implement the code solution so the application is consistent with other subtask applications across VA.gov.

### User story
**AS A** veteran
**I WANT** all subtask forms to use the subtask coding pattern
**SO THAT** all subtask forms will behave identically and create a consistent navigation experience across VA.gov

### Engineering notes / background
- Engineering implementation guidance: https://depo-platform-documentation.scrollhelp.site/developer-docs/va-forms-library-sub-tasks
- Design library guidance: https://design.va.gov/patterns/help-users-to/complete-a-sub-task

### Quality / testing notes
- [ ] Update unit tests if necessary
- [ ] Ensure all Cypress e2e tests still pass

## Acceptance criteria
- [ ] Current year flow still correctly navigates (Home > Zip > Dependents > Review > Results)
- [ ] Past year flow still correctly navigates (Home > Year > Zip > Dependents > Review > Results)
- [ ] API results for current year flow are correct
- [ ] API results for past year flow are correct

**Comment by randimays** [comment]
Some progress notes:

I looked through the documentation for the code implementation. It seems overly complex for a small app with simple routing. I doubt making the code changes is worth it - the cognitive load to understand routing and setup is kind of high, and the effort may not be worth any benefits we'll get out of it.

I [asked for @jilladams and @wesrowe's opinion](https://dsva.slack.com/archives/C52CL1PKQ/p1688154881545459) to see if the juice is worth the squeeze here. Jill suggested I follow up with a Platform ticket, [so I did](https://dsva.slack.com/archives/CBU0KDSB1/p1688396310472949). Wes weighed in about Collab Cycle and said they likely won't check the code. So at this point I'm just following through with trying to get a Platform direction before trying to refactor anything.

**Comment by randimays** [comment]
Got some guidance from the Platform here: https://dsva.slack.com/archives/C52CL1PKQ/p1688402806242329?thread_ts=1688154881.545459&cid=C52CL1PKQ. Seems like the Design System forms library is more for traditional forms like this:

<img width="671" alt="Screenshot 2023-07-03 at 11 46 22 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/58e15f0c-1c69-4c95-a549-7a1d4ae36c85">

And not necessarily wizards. I'll dig a bit deeper before we start on the PACT Act wizard to see if this might be applicable for it, but I'm thinking it's not.

Meanwhile, closing this ticket as a no-op.
