### ISSUE TITLE
D10 Test Plan

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14176]
## User Story
As clients of the CMS, I want to ensure that are able to aptly test and provide feedback to the CMS team during final e2e testing, so that I can set expectations and socialize accordingly. 

As the CMS team, I want to have as many folks as possible test Drupal 10 in a lower environment prior to release, so that bugs have been detected, decided upon and/or fixed to decrease risk and interruption of services.

## Acceptance Criteria
- [x] Testing has begun.
- [x] PO, PM, DM and CMS team hold 1st review on entered defects. 
- [x] Track and enforce process improvements.

## Todos
- [x] Determine mob testing window.
- [x] Circulate start and ending dates, materials and and rules of engagement for mob testing with PW and Facilities.
- [x] Receive PW and Facilities approvals of the start and ending dates, materials and and rules of engagement for mob testing.
- [x] Track all logged defects in master spreadsheet here: https://docs.google.com/spreadsheets/d/1R4g9jSZJvGRCAWWoslnxlC2hv5A2kHKMMxabbct3bI4/edit#gid=0

**Comment by productmike** [comment]
Rules of engagement for mob testing:
(1) CMS team will not be responsible for testing modules and functionalities specific to PW and/or Facilities. That is up to those specific products to own.
(2) Each of the columns/criteria in the spreadsheet should be answered as fully as possible. If not, more than likely a decision made based on the information entered. (CMS team will do our best to track and nudge you).
(3) Once a decision is made on if a defect is blocking (or not) to D10 release, the CMS team will not re-evaluate without the associated VA PO written justification.
(4) The testing open date is Monday 7/10. The link and master spreadsheet will be posted in the #sitewide-program slack channel.
(5) If a screenshot is useful, please send along to your DM or PM for sending along. Or request access to #d10-upgrade-testing slack channel. Rename the image to match the corresponding line # in the xls (e.g. if my issue is line #5 on the xls, then any associated materials should be saved and sent as Line5-[artifact].
(6) Closing date is Friday 7/28. ALL defects and/or associated information needs to be entered by then. No exceptions as the CMS team needs time to review and plan accordingly for Sprint 90.

Also tracked here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2693726361/Drupal+Upgrade+--+Test+Rules+of+Engagement

cc: @EWashb @BerniXiongA6 @edmund-dunn @tonytaylor

**Comment by productmike** [comment]
@EWashb Sure thing. As we're working through those access issues, I think it'll be beneficial for our team to use the confluence space as a shaping mechanism even though they won't live exclusively in that space. Shaping the light policy for our confluence here: https://vfs.atlassian.net/wiki/spaces/PCMS/overview?homepageId=1917845659. Definitely room to grow there, but if we admit that it's an ideating space for now (and it should always result in cross-posting in another VA-approved space) -- I think it makes using it a bit easier.

Re: mob testing, what's you thoughts on the ACs and Todos in this ticket based on our convo during planning today? Adjustments needed from your perspective?

**Comment by EWashb** [comment]
I like that approach to the documentation. And those ACs look good to me as well @productmike. This is approved as a sprint goal.

**Comment by productmike** [comment]
This will be a running async test from 7//10 to 7/28. See announcement to products teams here: https://dsva.slack.com/archives/C03LFSPGV16/p1688749304944389

Also for internal CMS team, the confluence link here: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2693726361/Drupal+Upgrade+--+Test+Rules+of+Engagement

**Comment by productmike** [comment]
Currently in blocked state until sitewide discussion on 7/13 to further determine plan approach and timing.

**Comment by productmike** [comment]
Meeting on 7/18 clarified several items. Here were the decisions and action items:

Outcomes desired by POs:
- Annual process/runbook developed in parallel with D10 deploy.
- Roadmap coordination/learning/sharing
- Timetables/sprints for testing

Decisions:
- PW began testing in sprint 88; nearly completed. 
- Facilities to begin in sprint 89. Expected to complete in sprint, pending results of CMS team's dissection of core vs. product responsibilities (w/ product team's acceptance)
- CMS team will meet to discuss ownership along with other considerations such as: (1) manual vs. automated testing; (2) cascading impacts product should test; (3) other core items that are owned by CMS but product may have impacted customizations
- Prioritization rubric to be further defined. Investigate Neutral or better criteria previously used (Claro; in airtable). 
- Include CMS UX team in these conversations.
- Go/no go meet will be held.

Action Items: 
- CMS team to hold session to dissect CMS components. 
- CMS Team to review outcome of that meeting with PW, Facilities for their acceptance/feedback.
- Prioritization rubric to be further developed and accepted by all teams. 
- CMS team to meet weekly to review defects entered.
- Mike to update in Rules of Engagement. Transfer to github for runbook real-time development.
- Mike to develop a test plan illustrated timeline artifact.

This has been posted here for further development as well: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2693726361/Drupal+Upgrade+--+Test+Rules+of+Engagement

cc: @EWashb @BerniXiongA6
