### ISSUE TITLE
Upgrade to Tugboat v2.23.16

### ISSUE THREAD

**Issue by rabbitlair** [department-of-veterans-affairs/va.gov-cms#14190]
## Tasks:

- [ ] Change directories to the Tugboat root: `cd /opt/tugboat`
- [ ] Fetch the latest tags: `git fetch --tags`
- [ ] Checkout the tag (e.g. `git checkout v2.23.16`)
- [ ] Build: `make && make install`
- [ ] Restart Tugboat: `tbctl restart`
- [ ] Wait for Tugboat to start up successfully. For the lazy: 
```
wget --quiet -O- --tries=100 --retry-on-http-error=404,502,503 --retry-connrefused https://[tugboat-dashboard-host]/_status
```

## Team

Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

#### v2.23.16 - 15 June, 2023

```
#3907 fix: Suspend child previews when rebuilding or refreshing base preview
#4899 feat: add a robots.txt to assets
#4954 fix: update preview object in redux before creating jobs
#5003 fix: increase mongoose serverSelection timeout
chore: bump @fastify/static from 6.9.0 to 6.10.2
chore: bump chart.js from 3.8.0 to 3.9.1
chore: bump postcss from 8.3.11 to 8.4.24
```

#### v2.23.15 - 02 June, 2023

```
#4424 docs: Add readme to server service
#4730 feat: Obfscate react and redux dev tool in production mode
#4968 fix: Make tbctl graceful restart replicated services properly
#4995 fix: Allow name arg when creating preview from tugboat cli
```

#### v2.23.14 - 23 May, 2023

```
#4976 fix: cache agent resources
#4977 fix: resolve project when it already exists in redux store
#4988 fix: handle recurly expired subscription webhook payloads
chore: bump @fastify/view from 7.1.0 to 7.4.1
chore: bump engine.io from 6.4.1 to 6.4.2
```

#### v2.23.13 - 15 May, 2023

```
#4917 fix: Remove signal listener if socket connection occurs
#4957 fix: Avoid dispatching multiple calls to project list
chore: bump fs-extra from 10.0.0 to 10.1.0
```

#### v2.23.12 - 04 May, 2023

```
#3595 fix: Enforce case in user emails
```

#### v2.23.11 - 03 May, 2023

```
#3594 chore: Ugprade traefik and use error middleware
#4054 feat: Sort visualdiffs by status
#4096 fix: Log container start timeout message
#4427 fix: Merge duplicate users
#4561 feat: Expose server resources to Premium customers
#4622 feat: Change webhooks server to fastify
#4753 feat: Add a tbctl graceful command
#4754 feat: Introduce service dependencies in various tbctl commands
#4815 feat: Rebuild visualdiffs and lighthouse reports by status
#4886 fix: Increase significant digits for visual diffs
#4902 fix: Add handling around proxying errors
#4932 fix: Graceful command should restart agents in worker servers
chore: Bump babel-jest from 27.3.1 to 27.5.1
chore: Bump core-js from 3.26.1 to 3.30.1
chore: Bump loglevel from 1.8.0 to 1.8.1
chore: Ensure latest Docker version is running on local environments
```

#### v2.23.10 - 01 April, 2023

```
#4414 docs: document agent service 
#4635 fix: serve static assets from apache
#4835 fix: Prevent proxy crash when preview container is not available
#4857 fix: handle errors thrown for stdout and stderr
#4861 chore: bump socket.io from 4.5.2 to 4.6.1
#4862 chore: bump @babel/preset-env from 7.17.10 to 7.20.2
#4863 chore: bump query-string from 7.1.1 to 7.1.3
#4864 chore: bump open from 8.4.0 to 8.4.2
#4868 chore: bump redux from 4.1.2 to 4.2.1
#4875 fix: handle errors thrown by previews.updateById
#4889 feat: allow custom agent to be passed to clean-agent.sh
```

#### v2.23.9 - 20 March, 2023

```
#4847 chore: bump react-redux from 7.2.6 to 7.2.9
#4846 chore: bump jest-environment-jsdom from 29.2.1 to 29.5.0
#4843 chore: bump @fastify/static from 6.5.0 to 6.9.0
#4865 fix: handle unhandled rejections in agent requests
#4853 fix: bind log method to logger class 
#4810 fix: handle errors thrown in scheduler refresh
#4869 fix: resolve log.error to a promise 
#4872 chore: use NODE_ENV directly
```

#### v2.23.8 - 11 March, 2023

```
#4760 fix: use MemFree from /proc/meminfo for agent memory calcs
#4810 fix: catch errors made by scheduler request
#4824 fix: catch and log errors made by agents.request
#4828 fix: call process.exit() if start throws on agent
#4837 fix: chain catch on unawaited startProxy call
#4848 fix: send 500 when container cannot attach to preview network
chore: bump @babel/preset-react from 7.14.5 to 7.18.6
chore: bump fastify from 4.6.0 to 4.14.1
chore: bump postcss-scss from 4.0.4 to 4.0.6
chore: bump qs from 6.5.2 to 6.5.3
chore: bump redux-thunk from 2.3.0 to 2.4.2
chore: bump undici from 5.10.0 to 5.20.0
```

#### v2.23.7 - 07 March, 2023

```
#4824 fix: pass callback to second parameter of exec inspect call
#4809 fix: handle google analytics errors on the agent-proxy
```

#### v2.23.6 - 03 March, 2023

```
#4806 fix: handle deployment status update for deleted previews
#4807 fix: check for screenshot before sending event update to server
#4819 fix: default force to false with empty request body
#4822 fix: revert back to sending the error just on the agent mqueue
```

#### v2.23.5 - 01 March, 2023

```
#4783 fix: log errors thrown in unawaited exec call
#4785 fix: apply fast-proxy strip only leading double slash fix from fork
#4802 fix: pass agent in when starting interrupted jobs
```

#### v2.23.4 - 28 February, 2023

```
#4631 fix: make an explicit tugboat error code for econnrefused 
#4653 feat: log uncaught and unhandled errors 
#4692 fix: create requestBody section for force attribute in deleting preview doc 
#4764 fix: log url instead of path in mqueue error handlers 
#4766 fix: make network request to job/start on agent 
#4782 fix: add leading slash to github comment delete endpoint 
#4786 fix: do not pass provider API query along to paged requests
```

#### v2.23.3 - 22 February, 2023

```
#4310 chore: replace request-promise-native with undici 
#4350 chore: miscellaneous performance improvements; nodejs 16 upgrade 
#4458 feat: change server and agent mqueue to fastify 
#4466 feat: change express to fastify in public api 
#4467 chore: replace request-promise-native with undici for GitHub API 
#4468 chore: switch to undici for GitLab provider 
#4469 chore: switch to undici for bitbucket api 
#4470 chore: refactor recurly API to use undici 
#4473 chore: add config options to use nsolid containers 
#4475 fix: add AbortSignal to promises to avoid memory leaks 
#4476 chore: upgrade to nodejs 16 
#4479 feat: change express to fastify on api messaging queue 
#4481 feat: change express to fastify on logs service message queue 
#4483 feat: change express to fastify for puppeteer message queue 
#4508 feat: proxy in download routes with fast-proxy 
#4510 fix: strictly check for logging turned off 
#4512 fix: inherit emit from MQueue api class 
#4515 fix: upgrade pkg to 5.8.0 to support node16; remove win32
#4524 fix: handle job load error elegantly with 404 
#4525 fix: handle image tagging errors gracefully 
#4531 chore: bump to jest29
#4537 fix: relieve asynchronous saturation mixing 
#4566 fix: update dequeuing in fastify agent mqueue 
#4576 fix: handle and log errors to setting service state
#4602 chore: use undici for Bitbucket Server API 
#4608 chore: switch to undici in api tests 
#4620 feat: implement write-through cache for preview hits 
#4628 refactor: remove opentelemetry and cleanup nsolid monitoring 
#4630 fix: await results to catch exceptions appropriately
#4650 feat: use fastify to serve profiler 
#4656 #4636 feat: cache preview state and optimize findService 
#4660 fix: set headersTimeout to 0 to unset option 
#4681 fix: check that provider params are passed before checking its attributes 
#4683 fix: parse error details in github tags request 
#4687 fix: move render queues up to job start method 
#4699 fix: implement tests
#4715 docs: update issue templates 
#4729 fix: Handle Chromium crashes in Puppeteer 
#4731 fix: send err.message as mqueues' payload 
docs: document events and listeners
fix: add findOne to job controller
tb-2213 fix: correct variable id routes in mail routes 
tb-2214 fix: update visualdiff if error is thrown 
tb-2220 fix: Handle Chromium crashes in Puppeteer 
tb-2225 fix: consume the error on the subscription form in order to control submission state 
tb-2226 fix: remove /terminate from terminate endpoint 
tb-2231 fix: update destructured number property off of invoice
```

#### v2.23.2 - 10 February, 2023

```
tb-2222 fix: send only error message payload in mqueue responses and revert concurrency 
```

#### v2.23.1 - 09 February, 2023

```
#4697 fix: renew locks using lock ID; use Promise.allSettled on interrupted jobs
#4698 fix: delete jobs that cannot load in jobs/end
#4702 feat: increase concurrency for screenshots/visualdiffs
#4703 chore: add logging for render queue status
```

**Comment by ndouglas** [comment]
we good now
