### ISSUE TITLE
Review of new or updated KB articles: VAMC health services in support of v1

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#14207]
## Background
VAMC editors understand that they maintain their websites but likely do not think of it as maintaining the source of truth for services available at their facilities. This has been a separate workstream with different parties responsible.
Currently, PAOs/editors are instructed to contact Lighthouse to update their service information.
With v1, we’ll need to help editors understand that

- the information they enter into Drupal will be the source of truth and
- it is important to keep service information up to date and accurate for Veterans viewing their website and 
- it is important to keep service information up to date and accurate because the information can be used across the entire ecosystem.

## Which article(s) need review?

Separate issues have been created to handle each set 

- [x] VAMC facility health service KB articles #14688 
- [x] VAMC system health service KB articles #14689
- [x] Health Services List KB articles #14690
- [x] How do I update my VAMC Facility's Basic Location Data? #14691 

## Goal(s) 
We have an opportunity to 
- consolidate overlapping/duplicate KB articles
- update appropriate articles by adding content which emphasizes the importance of maintaining an accurate list of health services and associated information about the method, delivery location, hours, etc.  (Michelle will work with VHA Digital Media on the language to be added) 
  
## Priority or deadline for request
Choose either Deadline or a priority:

- [x] Deadline: August 24, 2023 - in support of Lighthouse V1
- [ ] Priority:
  - [ ] Critical
  - [ ] High
  - [ ] Medium
  - [ ] Low

**Comment by mmiddaugh** [comment]
closing as all associated issues are complete
