### ISSUE TITLE
Facility Locator iteration: Provider core training / PPMS data

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14225]
### Provider Core Training
Design was handled during #11542 .  Figma file: https://www.figma.com/file/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?type=design&node-id=172-16230&mode=design

All of the following user stories in this group are related to using facility locator to search for `community providers in VA's network` the other facility types are not in the MVP scope for this effort. 
1. As a Veteran, I want to see what Providers have completed Provider Core Training
2. As a Veteran, I want to learn about Provider Core Training and what it means 
3. As a Veteran, I want to filter my search in the Facility Locator to return only providers who have received the Provider Core Training

**Implementation Notes:**
- the area for Veterans to learn about Provider core training will not be housed in facility locator, you should design a link/call to action etc. for Veterans to click or otherwise engage that links them out to this information that is housed elsewhere

For background, here is a blurb on Provider Core Training: 
Department of Veterans Affairs (VA) has created the Provider Core Training so that Veterans can be offered care from the highest quality providers available. Referring Veterans to Providers who have completed the Provider Core Training ensures that Veterans are receiving high-quality care in the community.

### **User Stories**
- [ ] As a Veteran, I want to see what Providers have completed Provider Core Training
- [ ] As a Veteran, I want to learn about Provider Core Training and what it means 
- [ ] As a Veteran, I want to filter my search in the Facility Locator to return only providers who have received the Provider Core Training

<link to any existing research or data supporting this>

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

**Comment by mmiddaugh** [comment]
per Keri Kinyon, as of 9/27,2023  barely .02% of total providers in PPMS (estimating current providers at around 1.3M) have completed training – specific to the 8 courses they are tracking for this program.
