### ISSUE TITLE
Implement colors from the design system.

### ISSUE THREAD

**Issue by BlakeOrgan** [department-of-veterans-affairs/va.gov-cms#14268]
## Description

- As a designer, I want the HEX codes and names of colors in Storybook to match what is in the Figma Design system, so that designers using the CMS design system are on the same page as developers about color usage.
- As a developer, I want to blank, so that blank.
- As a CMS Editor, I want to be able to view all colors used in the CMS without any color contrast issues, so that I can use the CMS without any accessibility issues.

## Atomic Level

These levels match the levels in [VA.gov Design System Documentation](https://design.va.gov/)

- [x] **Foundation** - The Foundation section provides information about the visual language and styles used in the CMS.
- [ ] **Component** - Components are interactive and non-interactive UI elements that can be grouped together or presented individually. They are independent, reusable chunks of a user interface.
- [ ] **Pattern** - Patterns are solutions and researched best practices for solving user-focused tasks and recurring user interface design problems.
- [ ] **Template** - Templates, or page layouts, compose components within a single page. A layout can contain multiple variations of a component depending on the context.

## Acceptance Criteria
**Implement design system updates**
- [x] Update the CSS variables per the color map. 
- [x] Ensure that Storybook is updated to reflect the changes listed above.
- [x] Audit existing CSS for any colors using hexcodes and not CSS variables.
- [x] Change hexcodes to CSS variables that align with new color system.

**Collab with Design**
- [ ] Set up a meeting to collaborate with the designer who made the updates in the design system.
- [x] Add the designer who made the updates in the design system as a reviewer on the pull request.
- [x] Add the A11y (Laura) as a reviewer on the pull request.
- [ ] Tag the designer who made the updates in the design system in a Slack message in the #sitewide-cms-platform channel letting them know that the pull request is ready for their review.
```[tasklist]
### Tasks
```

**Comment by BlakeOrgan** [comment]
This is a dev implementation ticket for the colors edited in the design system as part of ticket #12949.

**Comment by BlakeOrgan** [comment]
@edmund-dunn @tonytaylor   
  
[Here is the color map](https://www.figma.com/file/dLiV79QpWrpdwsTDC2veJW/Design-System-Playground?type=design&node-id=658%3A2957&mode=dev) that explains which colors need to change to what to align with the new colors that have been finalized as part of the [new simplified design system colors](https://www.figma.com/file/LAlrfgqFJgCV9EIq7eyDcw/Simplified-Design-System?type=design&node-id=547%3A580&mode=design&t=PtYBkWq39Im0tw4I-1). Please leave comments in Figma for anywhere that you have specific questions and I can get back to you with answers when I'm back from PTO. Thanks!

**Comment by productmike** [comment]
Refinement 7/26: 
- @edmund-dunn @tonytaylor confirm this is still a 5 based on the color map @BlakeOrgan  attached.

**Comment by productmike** [comment]
Removed AC: "- [ ] Add an automated test with Cypress (if doesn't already exist) to prevent regressions." and created visual regression epic (#14750) and color ticket (#14751) to capture for future reference.

cc: @tonytaylor @BerniXiongA6 @BlakeOrgan @edmund-dunn

**Comment by BerniXiongA6** [comment]
Hey @tonytaylor -- how close are we to completing this ticket?

**Comment by tonytaylor** [comment]
@BerniXiongA6 -- Sorry for the delay.  This will be closed once the tests pass (~30 minutes).

**Comment by BerniXiongA6** [comment]
Sounds good @tonytaylor -- hope you don't mind me moving the ticket to Review pipeline. cc: @BlakeOrgan @edmund-dunn cc: @productmike

**Comment by tonytaylor** [comment]
No problem @BerniXiongA6.

**Comment by BerniXiongA6** [comment]
@tonytaylor -- what is going on with this ticket? Did it ever get reviewed, can we close it?

**Comment by tonytaylor** [comment]
@BerniXiongA6 this was completed by @edmund-dunn in referenced ticket #15308
