### ISSUE TITLE
PW Sprint 89 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14296]
## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)

🟢 Product:
- (carryover from s86, waiting on Plat Analytics implementation) #13480 - Product
- #14106 (0) - Product

🟡 Engineering:
- [ ] (any carryover to s89?) #13750 () - FE
- [ ] #13614 (3) - FE/BE
- [ ] (post-Staging Review) #14294

### 2. PACT Act Wizard [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢  
- [ ] #14072 (5) - FE
- [ ] (blocked on prototype tool, content) (started s87, continue when Cindy is avail post-PTO #13324 (5) - Research
- [ ] #14408 () - Research
- [ ] (reopened) #12791 () - Research
- [ ] WES TICKET: PACT results screen mock-ups for Jordan

### 3. USA Header/Footer [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14078) 🔴
- (Laura/CMS Team) #14339

### 4. Expand Q&A Reusability [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡
- [ ] (stretch) #10941 (5) - BE
- [ ] (stretch) #10944 (needs) - FE

### 5. Benefit Content Model Hardening [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
- [ ] (may carryover from s87) #14086 (5) - Design
- [ ] #14095 (0) - Product
- [ ] (stretch; needs refining for plausibility) #14289 (needs)- BE
- [ ] (stretch; needs refining for plausibility) #14290 (needs)- BE

### Mobile App Promotional Banners [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482) 🟢
- [x] #13481 (5) - FE
- [ ] #14179 (0) - Product
- [ ] #14288 (0) - Product

### Post-MVP Homepage 🟡  
- [ ] (stretch; 14002 done?) #13863 (3) - BE

### Cerner API deprecation support 🔴  
- [ ] (stretch; wait for Chris to settle) (no longer blocked - PR is ready) #9307 (5) - FE

# Other PW Priorities
## Prioritized for this sprint
- [ ] (in motion from s88) #14185 (3) - BE
- [ ] (in motion from s88) #13990 (13) - BE
- [ ] #14442 (needs) - BE

## Backlog of non-quarter priorities (for easy access)

Cross-repo dependencies post-mortem
- [ ] (stretch) #13730 (3) - FE/BE

Other priorities
- [ ] #13736 (8) - FE
- [ ] (stretch) #13329 (3) - BE
- [ ] (stretch) #13222 (8) - FE
- [ ] (stretch) #13062 (3) - FE

### Content / IA priorities
- [ ] (blocked; CLP-related) va.gov-team 58142

### Portfolio and pipeline - [epic](#7599)
- [ ] (awaiting Cindy update on status) #12601 (needs) - Design
- [ ] (awaiting Cindy update on status) #12791 (needs) - Design

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] (stretch) #13147 (needsrefining) - FE
- [ ] (stretch) #13137 (needsrefining) - FE
- [ ] (blocked on Appointment team's design work) #14219 (needs) - FE

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.

**Comment by wesrowe** [comment]
Priorities for BE and non-top-5 effort – s89:

- [x] (D10) #14185 
- [x] (D10) #13990 
- [ ] #13614 
- [ ] #13481 
- [ ] #13736 
- [ ] #13863 
- [ ] #12325 
- [ ] #13730

**Comment by jilladams** [comment]
Dave suggested considering deprecating the Office product, upcoming. Not urgent, just noting if for refinement purposes, in case there are easy wins here with any capacity: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14404

**Comment by jilladams** [comment]
Mobile apps: separate tix for collab cycle touchpoints? Close original ticket or keep it open?

**Comment by jilladams** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14408

**Comment by jilladams** [comment]
From planning notes: 

- [ ] Need a ticket for addl Drupal test coverage audit: not forms/events.
- [ ] Need a ticket for PACT results screen mockups to use in research
- [ ]

**Comment by jilladams** [comment]
Judgment call: Income Limits takes priority for Staging Review, over mobile banners.

**Comment by jilladams** [comment]
Goals
[I.L. FE: Add real content to app #13750](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13750)
[BE: Support Drupal 10 testing/bug bash #13990](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13990)
[Document the logic of PACT Act Wizard's user flow v1.2 #14408](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14408)
