### ISSUE TITLE
Eric Oliver Extended Leave Planning - CMS DevOps Engineer On-boarding

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#14297]
## Background
I, Eric Oliver, will be starting (pending approval) extended leave. My leave will last 12 weeks starting August 10, 2023 and ends with my return November 2nd, 2023. This epic is meant to ensure:
- A smooth transition of my responsibilities.
- Existing DevOps team members have system(s) access and documentation to cover those responsibilities.
- New DevOps team members have system(s) access and documentation to cover those responsibilities.

Generally, what current work needs to be handed off. Additionally, what specific CMS DevOps Engineer related on-boarding needs documenting and completing (e.g. AWS Access, Venafi Certificate Portal Access, CMS Server Access, etc.)

### User Story or Problem Statement

As a CMS DevOps team member, I need to ensure my team has the proper tools, system access, and documentation that are used to complete my duties, so I can take extended leave without degrading or preventing the CMS DevOps team's ability to complete planned and unplanned work.

### Affected users and stakeholders

* CMS DevOps Team

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that planning for extended leave will achieve an interrupted continuation of excellent service to CMS platform engineers and users. We'll know that to be true when planned or unplanned work is completed without undue difficulty.

## Assumptions
* TBD

## Acceptance Criteria
- [x] Eric's Existing tickets and responsibilities are documented.
- [x] CMS DevOps Engineers tools, system access, and documentation to successfully complete work is documented.
- [ ] CMS DevOps Engineers have the tools, system access, and documentation to successfully complete work.

  
## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by olivereri** [comment]
Rough list of what I can access and other DevOps engineers should have;
- [ ] Github CMS-bot login access via Security Key.
- [ ] Identity and Access Management PreProd Identity Provider membership. Allows Staging CMS PIV logon.
- [ ] Service Now Change Management Group Membership.
- [ ] Venafi Certificate Management Portal. Access is controlled by ePAS.
- [ ] AWS Systems Manager access to CMS Servers.
- [ ] General AWS access.
- [ ] cmsadmin distribution group membership and associated documentation.
