### ISSUE TITLE
CMS DevSecOps Onboarding Artifacts Review and Diagramming

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#14298]
## User Story / Description

Given that Tolase is kinda sorta new to the CMS team, I'd like to be able to use that superpower to review, improve and illustrate DevSecOps documentation where needed. There is existing documentation -- I'd like us to use that as a starting point.

CMS readmes: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/READMES
CMS DevOps readmes: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/READMES/devops
CMS DevOps Local Environment: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14024#issuecomment-1591783971

## TODOS
- [ ] Review the readmes here: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/main/READMES/devops
- [ ] Select a component to dig into. 
- [ ] If a system diagram exists, evaluate the reciprocation between the documentation and the diagram.
- [ ] If no system diagram exists, start one based on the diagram. Questions expected, so don't feel bad!
- [ ] Create/edit a business process diagram that illustrates top use cases for that component.

**Comment by teeshe** [comment]
I have reviewed the ACM certificate import README and I have updated the ACM certificate documentation with a process diagram that illustrates the steps to complete the task [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/devops/acm-certificate-import.md). Documentation listed platform steps to create/renew internal certificates on Venafi and also import it to AWS certificate manager.
