### ISSUE TITLE
[SPIKE] Approach to Satisfaction for DevSecOps

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14321]
As part of #14012, we should draft functional questions for the satisfaction survey. It'd be good to be able to associate these with KPIs and metrics, new and existing, and use what we learn from the satisfaction survey to improve processes, e.g.  interaction guidelines discussed in #14320.

## Tasks
- Review current (existing, newly added, proposed) DevSecOps metrics, discuss how they relate to customer satisfaction, identify gaps, etc.
- Identify satisfaction indicators for each group:
  - Editors
  - Veterans
  - Product Team(s)
  - Platform Security team and other institutional voices from up on high
- Draft survey questions: create specific questions that can capture some of these satisfaction indicators.
- Figure out how to integrate the satisfaction survey into our workflow and how to track and analyze the collected data.
- Explore how scores can tie into existing KPIs/metrics/whatever and create a fuller performance overview.

## Acceptance Criteria
- [ ] Followup issue(s) for any identified gaps in current metrics that might relate to customer satisfaction
- [ ] Identified satisfaction indicators, e.g. responsiveness, resolution time, stability/availability, communication, etc.
- [ ] Drafted survey questions that try to capture customer satisfaction
- [ ] Plan and/or followup issue(s) or something for how we're incorporating outcomes from satisfaction survey into our work going forward **NEEDS REFINING**
- [ ] How we integrate satisfaction survey feedback with existing metrics. If people say reliability is down but our metrics have never looked better, what does this mean? How do we respond? How do we manage discrepancies in perception and measurement?

**Comment by productmike** [comment]
Refinement 7/26: 
- This one may need to wait until more defined survey plan is created.

**Comment by EWashb** [comment]
Platform does a similar thing and we can likely tack on any questions we might have with their existing effort as we roll into that new Crew. We can work with Naomi Marcussen on this.
