### ISSUE TITLE
[SPIKE] Consider/plan adoption of merge queues.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14343]
## Description
Merge queues are generally available! 

https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

## Tasks

- [ ] Read details, familiarize ourselves if we're not already familiar
- [ ] Determine what changes might need to be made to Tugboat to support this. This might be a problem.
- [ ] Consider potential downsides, e.g. if my tests fail because I'm a fool, does that cause all downstream PR tests to fail as well?

## Acceptance Criteria
- [ ] DevOps Squad™ has discussed whether this is worth bothering with or if this will be a nightmare.
- [ ] Followup issue(s) opened to address specifics, if it's a good idea.
