### ISSUE TITLE
layout: node--support_service

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14366]
## Description
We need a layout to display Support Services
Example:

## Acceptance Criteria
- [ ] Support Services content renders correctly
- [ ] The layout output is consistent with the existing output of content-build (visually and functionally)

```[tasklist]
### Tasks
- [ ] type definitions - Drupal node type, Next Build page type
- [ ] query definition - query drupal data, map to next bulid type
- [ ] tests for query/formatter
- [ ] layout component
```

## Supporting detail
**This is not an individual page.**
**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/support_service/fields

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/support_service.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/supportService.graphql.js

**API query for individual node:** https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec?include=field_office,field_administration

**Includes:**
```
    [
    'field_office',
    'field_administration',
    ]
```

<details><summary>Example normalized data</summary>

```
{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": {
    "type": "node--support_service",
    "id": "c82ccd0e-c6e1-44da-ba14-01398d1005ec",
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec?resourceVersion=id%3A18482"
      }
    },
    "attributes": {
      "drupal_internal__nid": 57,
      "drupal_internal__vid": 18482,
      "langcode": "en",
      "revision_timestamp": "2019-06-03T18:39:41+00:00",
      "revision_log": "Bulk operation publish revision",
      "status": true,
      "title": "Ask a question online",
      "created": "2019-01-28T20:48:52+00:00",
      "changed": "2019-06-03T18:39:41+00:00",
      "promote": false,
      "sticky": false,
      "default_langcode": true,
      "revision_translation_affected": true,
      "breadcrumbs": [
        {
          "uri": "https://prod.cms.va.gov/",
          "title": "Home",
          "options": []
        },
        {
          "uri": "https://prod.cms.va.gov/va-central-office",
          "title": "VA Central Office",
          "options": []
        },
        {
          "uri": "https://prod.cms.va.gov/va-central-office/ask-a-question-online-0",
          "title": "Ask a question online",
          "options": []
        }
      ],
      "moderation_state": "published",
      "expiration_date": null,
      "warning_date": null,
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "Ask a question online | Veterans Affairs"
          }
        },
        {
          "tag": "link",
          "attributes": {
            "rel": "image_src",
            "href": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:site_name",
            "content": "Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:title",
            "content": "Ask a question online | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:site",
            "content": "@DeptVetAffairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:title",
            "content": "Ask a question online | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        }
      ],
      "path": {
        "alias": "/va-central-office/ask-a-question-online-0",
        "pid": 195,
        "langcode": "en"
      },
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "field_last_saved_by_an_editor": "2019-06-03T18:39:40+00:00",
      "field_link": {
        "uri": "https://iris.custhelp.va.gov/app/ask",
        "title": "",
        "options": [],
        "url": "https://iris.custhelp.va.gov/app/ask"
      },
      "field_phone_number": null
    },
    "relationships": {
      "node_type": {
        "data": {
          "type": "node_type--node_type",
          "id": "27533ffc-851f-4edc-8465-518ea2414b27",
          "meta": {
            "drupal_internal__target_id": "support_service"
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/node_type?resourceVersion=id%3A18482"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/relationships/node_type?resourceVersion=id%3A18482"
          }
        }
      },
      "revision_uid": {
        "data": {
          "type": "user--user",
          "id": "e62ded06-1de9-4617-bd70-595036edc7ee",
          "meta": {
            "drupal_internal__target_id": 89
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/revision_uid?resourceVersion=id%3A18482"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/relationships/revision_uid?resourceVersion=id%3A18482"
          }
        }
      },
      "uid": {
        "data": {
          "type": "user--user",
          "id": "b02c2ff5-dfe1-4542-beec-3fd410a3f267",
          "meta": {
            "drupal_internal__target_id": 1
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/uid?resourceVersion=id%3A18482"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/relationships/uid?resourceVersion=id%3A18482"
          }
        }
      },
      "field_administration": {
        "data": {
          "type": "taxonomy_term--administration",
          "id": "2c331a6d-b525-4f0c-8bea-4ecde41c7ef0",
          "meta": {
            "drupal_internal__target_id": 1
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/field_administration?resourceVersion=id%3A18482"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/relationships/field_administration?resourceVersion=id%3A18482"
          }
        }
      },
      "field_office": {
        "data": {
          "type": "node--office",
          "id": "c715d441-b6cb-4067-92eb-0650e97b7d62",
          "meta": {
            "drupal_internal__target_id": 126
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/field_office?resourceVersion=id%3A18482"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec/relationships/field_office?resourceVersion=id%3A18482"
          }
        }
      }
    }
  },
  "included": [
    {
      "type": "node--office",
      "id": "c715d441-b6cb-4067-92eb-0650e97b7d62",
      "links": {
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62?resourceVersion=id%3A10606"
        }
      },
      "attributes": {
        "drupal_internal__nid": 126,
        "drupal_internal__vid": 10606,
        "langcode": "en",
        "revision_timestamp": "2019-09-04T19:14:37+00:00",
        "revision_log": null,
        "status": false,
        "title": "VA Central Office",
        "created": "2019-03-04T14:12:28+00:00",
        "changed": "2019-09-04T19:14:37+00:00",
        "promote": false,
        "sticky": false,
        "default_langcode": true,
        "revision_translation_affected": true,
        "breadcrumbs": [
          {
            "uri": "https://prod.cms.va.gov/",
            "title": "Home",
            "options": []
          },
          {
            "uri": "https://prod.cms.va.gov/va-central-office",
            "title": "VA Central Office",
            "options": []
          }
        ],
        "moderation_state": "archived",
        "expiration_date": null,
        "warning_date": null,
        "metatag": [
          {
            "tag": "meta",
            "attributes": {
              "name": "title",
              "content": "VA Central Office | Veterans Affairs"
            }
          },
          {
            "tag": "link",
            "attributes": {
              "rel": "image_src",
              "href": "https://www.va.gov/img/design/logo/va-og-image.png"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:site_name",
              "content": "Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:title",
              "content": "VA Central Office | Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:image",
              "content": "https://www.va.gov/img/design/logo/va-og-image.png"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:image:alt",
              "content": "U.S. Department of Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:card",
              "content": "summary_large_image"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:site",
              "content": "@DeptVetAffairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:title",
              "content": "VA Central Office | Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:image",
              "content": "https://www.va.gov/img/design/logo/va-og-image.png"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:image:alt",
              "content": "U.S. Department of Veterans Affairs"
            }
          }
        ],
        "path": {
          "alias": "/va-central-office",
          "pid": 192,
          "langcode": "en"
        },
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "field_body": null,
        "field_description": null,
        "field_email_updates_link": null,
        "field_external_link": null,
        "field_last_saved_by_an_editor": null,
        "field_meta_tags": null,
        "field_office_id": null,
        "field_social_media_links": null
      },
      "relationships": {
        "node_type": {
          "data": {
            "type": "node_type--node_type",
            "id": "60cde818-b36c-4c05-a3c9-4c045a14787a",
            "meta": {
              "drupal_internal__target_id": "office"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/node_type?resourceVersion=id%3A10606"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/node_type?resourceVersion=id%3A10606"
            }
          }
        },
        "revision_uid": {
          "data": {
            "type": "user--user",
            "id": "8bea8773-6a06-4afd-99b5-1dfa7a2192ea",
            "meta": {
              "drupal_internal__target_id": 197
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/revision_uid?resourceVersion=id%3A10606"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/revision_uid?resourceVersion=id%3A10606"
            }
          }
        },
        "uid": {
          "data": {
            "type": "user--user",
            "id": "b02c2ff5-dfe1-4542-beec-3fd410a3f267",
            "meta": {
              "drupal_internal__target_id": 1
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/uid?resourceVersion=id%3A10606"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/uid?resourceVersion=id%3A10606"
            }
          }
        },
        "field_administration": {
          "data": {
            "type": "taxonomy_term--administration",
            "id": "c20f3989-e93e-49bd-8c95-ad3821042a02",
            "meta": {
              "drupal_internal__target_id": 5
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/field_administration?resourceVersion=id%3A10606"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/field_administration?resourceVersion=id%3A10606"
            }
          }
        },
        "field_parent_office": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/field_parent_office?resourceVersion=id%3A10606"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/field_parent_office?resourceVersion=id%3A10606"
            }
          }
        }
      }
    },
    {
      "type": "taxonomy_term--administration",
      "id": "2c331a6d-b525-4f0c-8bea-4ecde41c7ef0",
      "links": {
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0?resourceVersion=id%3A1"
        }
      },
      "attributes": {
        "drupal_internal__tid": 1,
        "drupal_internal__revision_id": 1,
        "langcode": "en",
        "revision_created": "2022-01-06T20:39:49+00:00",
        "revision_log_message": null,
        "status": true,
        "name": "VBA",
        "description": null,
        "weight": 11,
        "changed": "2022-01-06T20:39:49+00:00",
        "default_langcode": true,
        "revision_translation_affected": true,
        "moderation_state": null,
        "metatag": [
          {
            "tag": "meta",
            "attributes": {
              "name": "title",
              "content": "VBA | VA.gov CMS"
            }
          },
          {
            "tag": "link",
            "attributes": {
              "rel": "canonical",
              "href": "https://prod.cms.va.gov/section/vba"
            }
          }
        ],
        "path": {
          "alias": "/section/vba",
          "pid": 71,
          "langcode": "en"
        },
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "content_translation_created": null,
        "field_description": "Veterans Benefits Administration"
      },
      "relationships": {
        "vid": {
          "data": {
            "type": "taxonomy_vocabulary--taxonomy_vocabulary",
            "id": "645055c5-e567-4683-b6db-459ce04522ce",
            "meta": {
              "drupal_internal__target_id": "administration"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/vid?resourceVersion=id%3A1"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/relationships/vid?resourceVersion=id%3A1"
            }
          }
        },
        "revision_user": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/revision_user?resourceVersion=id%3A1"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/relationships/revision_user?resourceVersion=id%3A1"
            }
          }
        },
        "parent": {
          "data": [
            {
              "type": "taxonomy_term--administration",
              "id": "virtual",
              "meta": {
                "links": {
                  "help": {
                    "href": "https://www.drupal.org/docs/8/modules/json-api/core-concepts#virtual",
                    "meta": {
                      "about": "Usage and meaning of the 'virtual' resource identifier."
                    }
                  }
                }
              }
            }
          ],
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/parent?resourceVersion=id%3A1"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/relationships/parent?resourceVersion=id%3A1"
            }
          }
        },
        "content_translation_uid": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/content_translation_uid?resourceVersion=id%3A1"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/relationships/content_translation_uid?resourceVersion=id%3A1"
            }
          }
        },
        "field_product": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/field_product?resourceVersion=id%3A1"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/2c331a6d-b525-4f0c-8bea-4ecde41c7ef0/relationships/field_product?resourceVersion=id%3A1"
            }
          }
        }
      }
    }
  ],
  "links": {
    "self": {
      "href": "https://prod.cms.va.gov/jsonapi/node/support_service/c82ccd0e-c6e1-44da-ba14-01398d1005ec?include=field_office%2Cfield_administration"
    }
  }
}
```

</details>

**Comment by mreed101** [comment]
Needs to be refined. Add screenshots

**Comment by laflannery** [comment]
Duplicate since we have layout tickets in the next-build board now
