### ISSUE TITLE
component: block--alert

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14363]
```[tasklist]
### Tasks
- [ ] types: block--alert
- [ ] queries: block--alert
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8642
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8615
- [ ] build component
```

**Comment by timcosgrove** [comment]
Dupe: #8688
