### ISSUE TITLE
layout: node--office

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14367]
## Description
We need the ability render an office page. The goal is to take the preexisting page from content-build and migrate it over to next-build
Example:
https://www.va.gov/outreach-and-events/

## Screenshot
<img width="1122" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/13966636/e6110fb4-7552-4242-883e-8c82931bf6ca">

## Acceptance Criteria
- [ ] Office content renders successfully
- [ ] The layout output is consistent with the existing output of content-build (visually and functionally)

```[tasklist]
### Tasks
- [ ] type definitions - Drupal node type, Next Build page type
- [ ] query definition - query drupal data, map to next bulid type
- [ ] tests for query/formatter
- [ ] layout component
```

## Supporting detail
**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/office/fields

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/office.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/nodeOffice.graphql.js

**API query for individual node:** https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62?include=field_parent_office,field_administration

**Includes:**
```
    [
    'field_parent_office',
    'field_administration',
    ]
```

<details><summary>Example normalized data</summary>

```
 {
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": {
    "type": "node--office",
    "id": "c715d441-b6cb-4067-92eb-0650e97b7d62",
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62?resourceVersion=id%3A10606"
      }
    },
    "attributes": {
      "drupal_internal__nid": 126,
      "drupal_internal__vid": 10606,
      "langcode": "en",
      "revision_timestamp": "2019-09-04T19:14:37+00:00",
      "revision_log": null,
      "status": false,
      "title": "VA Central Office",
      "created": "2019-03-04T14:12:28+00:00",
      "changed": "2019-09-04T19:14:37+00:00",
      "promote": false,
      "sticky": false,
      "default_langcode": true,
      "revision_translation_affected": true,
      "breadcrumbs": [
        {
          "uri": "https://prod.cms.va.gov/",
          "title": "Home",
          "options": []
        },
        {
          "uri": "https://prod.cms.va.gov/va-central-office",
          "title": "VA Central Office",
          "options": []
        }
      ],
      "moderation_state": "archived",
      "expiration_date": null,
      "warning_date": null,
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "VA Central Office | Veterans Affairs"
          }
        },
        {
          "tag": "link",
          "attributes": {
            "rel": "image_src",
            "href": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:site_name",
            "content": "Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:title",
            "content": "VA Central Office | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:site",
            "content": "@DeptVetAffairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:title",
            "content": "VA Central Office | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        }
      ],
      "path": {
        "alias": "/va-central-office",
        "pid": 192,
        "langcode": "en"
      },
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "field_body": null,
      "field_description": null,
      "field_email_updates_link": null,
      "field_external_link": null,
      "field_last_saved_by_an_editor": null,
      "field_meta_tags": null,
      "field_office_id": null,
      "field_social_media_links": null
    },
    "relationships": {
      "node_type": {
        "data": {
          "type": "node_type--node_type",
          "id": "60cde818-b36c-4c05-a3c9-4c045a14787a",
          "meta": {
            "drupal_internal__target_id": "office"
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/node_type?resourceVersion=id%3A10606"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/node_type?resourceVersion=id%3A10606"
          }
        }
      },
      "revision_uid": {
        "data": {
          "type": "user--user",
          "id": "8bea8773-6a06-4afd-99b5-1dfa7a2192ea",
          "meta": {
            "drupal_internal__target_id": 197
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/revision_uid?resourceVersion=id%3A10606"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/revision_uid?resourceVersion=id%3A10606"
          }
        }
      },
      "uid": {
        "data": {
          "type": "user--user",
          "id": "b02c2ff5-dfe1-4542-beec-3fd410a3f267",
          "meta": {
            "drupal_internal__target_id": 1
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/uid?resourceVersion=id%3A10606"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/uid?resourceVersion=id%3A10606"
          }
        }
      },
      "field_administration": {
        "data": {
          "type": "taxonomy_term--administration",
          "id": "c20f3989-e93e-49bd-8c95-ad3821042a02",
          "meta": {
            "drupal_internal__target_id": 5
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/field_administration?resourceVersion=id%3A10606"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/field_administration?resourceVersion=id%3A10606"
          }
        }
      },
      "field_parent_office": {
        "data": null,
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/field_parent_office?resourceVersion=id%3A10606"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62/relationships/field_parent_office?resourceVersion=id%3A10606"
          }
        }
      }
    }
  },
  "included": [
    {
      "type": "taxonomy_term--administration",
      "id": "c20f3989-e93e-49bd-8c95-ad3821042a02",
      "links": {
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02?resourceVersion=id%3A5"
        }
      },
      "attributes": {
        "drupal_internal__tid": 5,
        "drupal_internal__revision_id": 5,
        "langcode": "en",
        "revision_created": "2022-01-06T20:39:49+00:00",
        "revision_log_message": null,
        "status": true,
        "name": "VACO",
        "description": null,
        "weight": 0,
        "changed": "2022-01-06T20:39:49+00:00",
        "default_langcode": true,
        "revision_translation_affected": true,
        "moderation_state": null,
        "metatag": [
          {
            "tag": "meta",
            "attributes": {
              "name": "title",
              "content": "VACO | VA.gov CMS"
            }
          },
          {
            "tag": "link",
            "attributes": {
              "rel": "canonical",
              "href": "https://prod.cms.va.gov/section/vaco"
            }
          }
        ],
        "path": {
          "alias": "/section/vaco",
          "pid": 75,
          "langcode": "en"
        },
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "content_translation_created": null,
        "field_description": "VA Central Office"
      },
      "relationships": {
        "vid": {
          "data": {
            "type": "taxonomy_vocabulary--taxonomy_vocabulary",
            "id": "645055c5-e567-4683-b6db-459ce04522ce",
            "meta": {
              "drupal_internal__target_id": "administration"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/vid?resourceVersion=id%3A5"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/relationships/vid?resourceVersion=id%3A5"
            }
          }
        },
        "revision_user": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/revision_user?resourceVersion=id%3A5"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/relationships/revision_user?resourceVersion=id%3A5"
            }
          }
        },
        "parent": {
          "data": [
            {
              "type": "taxonomy_term--administration",
              "id": "virtual",
              "meta": {
                "links": {
                  "help": {
                    "href": "https://www.drupal.org/docs/8/modules/json-api/core-concepts#virtual",
                    "meta": {
                      "about": "Usage and meaning of the 'virtual' resource identifier."
                    }
                  }
                }
              }
            }
          ],
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/parent?resourceVersion=id%3A5"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/relationships/parent?resourceVersion=id%3A5"
            }
          }
        },
        "content_translation_uid": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/content_translation_uid?resourceVersion=id%3A5"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/relationships/content_translation_uid?resourceVersion=id%3A5"
            }
          }
        },
        "field_product": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/field_product?resourceVersion=id%3A5"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/c20f3989-e93e-49bd-8c95-ad3821042a02/relationships/field_product?resourceVersion=id%3A5"
            }
          }
        }
      }
    }
  ],
  "links": {
    "self": {
      "href": "https://prod.cms.va.gov/jsonapi/node/office/c715d441-b6cb-4067-92eb-0650e97b7d62?include=field_parent_office%2Cfield_administration"
    }
  }
}
```

</details>
