### ISSUE TITLE
layout: node--page (Benefits Detail Page)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14368]
```[tasklist]
### Tasks
- [ ] types: node--page
- [ ] queries: node--page
- [ ] build component
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14365
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14369
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16598
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16599
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16600
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16747
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14370
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8636
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8607
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14372
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14371
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8612
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8629
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16601
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8688
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8605
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8642
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "node--page",
    "id": "27aaaef6-0c67-4639-b7d7-84cb3c124cff",
    "drupal_internal__nid": 298,
    "drupal_internal__vid": 304204,
    "langcode": "en",
    "revision_timestamp": "2020-04-30T20:11:16+00:00",
    "status": false,
    "title": "Check Your VA Claim or Appeal Status",
    "created": "2019-04-24T19:05:07+00:00",
    "changed": "2020-04-30T20:11:16+00:00",
    "promote": false,
    "sticky": false,
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [
      {
        "uri": "https://prod.cms.va.gov/",
        "title": "Home",
        "options": []
      },
      {
        "uri": "https://prod.cms.va.gov/check-your-va-claim-or-appeal-status",
        "title": "Check Your VA Claim or Appeal Status",
        "options": []
      }
    ],
    "moderation_state": "archived",
    "expiration_date": null,
    "warning_date": null,
    "metatag": [
      {
        "tag": "meta",
        "attributes": {
          "name": "title",
          "content": "Check Your VA Claim or Appeal Status | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "description",
          "content": "Find out how to check the status of a VA claim or appeal online."
        }
      },
      {
        "tag": "link",
        "attributes": {
          "rel": "image_src",
          "href": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:site_name",
          "content": "Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:title",
          "content": "Check Your VA Claim or Appeal Status | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:description",
          "content": "Find out how to check the status of a VA claim or appeal online."
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:image",
          "content": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:image:alt",
          "content": "U.S. Department of Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:card",
          "content": "summary_large_image"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:description",
          "content": "Find out how to check the status of a VA claim or appeal online."
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:site",
          "content": "@DeptVetAffairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:title",
          "content": "Check Your VA Claim or Appeal Status | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:image",
          "content": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:image:alt",
          "content": "U.S. Department of Veterans Affairs"
        }
      }
    ],
    "path": {
      "alias": "/check-your-va-claim-or-appeal-status",
      "pid": 479,
      "langcode": "en"
    },
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "field_description": "Find out how to check the status of a VA claim or appeal online.",
    "field_intro_text_limited_html": {
      "value": "Find out how to check the status of a VA claim or appeal online.",
      "format": "rich_text_limited",
      "processed": "<p>Find out how to check the status of a VA claim or appeal online.</p>\n"
    },
    "field_last_saved_by_an_editor": null,
    "field_meta_tags": null,
    "field_plainlanguage_date": null,
    "field_table_of_contents_boolean": null,
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/node/page/27aaaef6-0c67-4639-b7d7-84cb3c124cff?resourceVersion=id%3A304204"
      }
    },
    "node_type": {
      "type": "node_type--node_type",
      "id": "d4860e9e-588d-474c-8d59-550fb61c5c8c",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "page"
      }
    },
    "revision_uid": {
      "type": "user--user",
      "id": "c564bd69-e8da-4ac3-905c-dd94f4bf7b35",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 1317
      }
    },
    "uid": {
      "type": "user--user",
      "id": "c564bd69-e8da-4ac3-905c-dd94f4bf7b35",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 1317
      }
    },
    "field_administration": {
      "type": "taxonomy_term--administration",
      "id": "2c331a6d-b525-4f0c-8bea-4ecde41c7ef0",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 1
      }
    },
    "field_alert": null,
    "field_content_block": [
      {
        "type": "paragraph--wysiwyg",
        "id": "b871d67e-44a1-45d7-a3c9-948795c0b10d",
        "resourceIdObjMeta": {
          "target_revision_id": 78497,
          "drupal_internal__target_id": 3885
        }
      }
    ],
    "field_featured_content": [
      {
        "type": "paragraph--wysiwyg",
        "id": "07b2ad1b-9b94-464a-8961-3ca73e84c8aa",
        "resourceIdObjMeta": {
          "target_revision_id": 78498,
          "drupal_internal__target_id": 3886
        }
      }
    ],
    "field_related_links": null,
    "relationshipNames": [
      "node_type",
      "revision_uid",
      "uid",
      "field_administration",
      "field_alert",
      "field_content_block",
      "field_featured_content",
      "field_related_links"
    ]
  }
```

## Acceptance Criteria

- [ ] Benefits detail page created

**Comment by laflannery** [comment]
Duplicate since we have layout tickets in the next-build board now
