### ISSUE TITLE
[Epic][AP] Build all necessary pages when content is added or saved (ISR)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14360]
### User Story or Problem Statement

As a CMS user, when I save content, I want all pages using that content to be rebuilt, so that all information using that content is up-to-date.

### Affected users and stakeholders

* CMS Editors

### Hypothesis

We believe that correctly configured cache invalidation will allow all pages related to a piece of content to be rebuilt when needed. We'll know that to be true when the CMS reliably generates a list of content to be invalidated when something is saved.

## Assumptions
* The CMS will be able to provide a mechanism for identifying all pieces of content related to an individual piece of content.
* The CMS is able to clearly identify how all pieces of content relate to each other to facilitate this cache invalidation.

These assumptions will be validated early on in the epic with proof of concept efforts.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

```[tasklist]
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14399
- [ ] Spike: Verify cache invalidation correctly identifies all cached items for purging
- [ ] Inform Next.js server of invalidated cached items
```

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by timcosgrove** [comment]
I am closing this epic. We are going to use an initial caching strategy of a short TTL to handle content getting refreshed, rather than this mechanism.
