### ISSUE TITLE
component: block_content--promo

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14364]
```[tasklist]
### Tasks
- [ ] types: block--promo
- [ ] queries: block--promo
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8676
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] build component
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "block_content--promo",
    "id": "4a9807dc-7656-4792-b5f9-1a0a80eb2424",
    "drupal_internal__id": 14,
    "drupal_internal__revision_id": 166,
    "langcode": "en",
    "revision_created": "2019-06-04T20:02:48+00:00",
    "status": true,
    "info": "Confirm your VA benefit status",
    "changed": "2019-06-04T20:02:48+00:00",
    "reusable": true,
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [
      {
        "uri": "https://prod.cms.va.gov/",
        "title": "Home",
        "options": []
      },
      {
        "uri": "https://prod.cms.va.gov/system/403",
        "title": "Access Denied",
        "options": []
      }
    ],
    "moderation_state": "published",
    "expiration_date": null,
    "warning_date": null,
    "metatag": [
      {
        "tag": "meta",
        "attributes": {
          "name": "title",
          "content": "| Veterans Affairs"
        }
      }
    ],
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/block_content/promo/4a9807dc-7656-4792-b5f9-1a0a80eb2424?resourceVersion=id%3A166"
      }
    },
    "block_content_type": {
      "type": "block_content_type--block_content_type",
      "id": "0a87c177-4b3c-4cf5-bcae-1f0c432da52b",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "promo"
      }
    },
    "revision_user": {
      "type": "user--user",
      "id": "c0745381-8e20-40da-9540-5a7d2eee1b35",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 86
      }
    },
    "field_image": {
      "type": "media--image",
      "id": "84efa2f5-9d94-4d54-8fc7-9c9d43021e76",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 9
      }
    },
    "field_owner": {
      "type": "taxonomy_term--administration",
      "id": "cf0807aa-0b82-45cb-9c66-6bedae9555f2",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 76
      }
    },
    "field_promo_link": {
      "type": "paragraph--link_teaser",
      "id": "69620159-bb03-45bc-915e-35147050d1d8",
      "resourceIdObjMeta": {
        "target_revision_id": 14619,
        "drupal_internal__target_id": 3546
      }
    },
    "relationshipNames": [
      "block_content_type",
      "revision_user",
      "field_image",
      "field_owner",
      "field_promo_link"
    ]
  }
```

## Acceptance Criteria

- [ ] Block content created
