### ISSUE TITLE
component: paragraph--q_a_section (Page-Specific Q&A Group)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14369]
```[tasklist]
### Tasks
- [ ] types: paragraph--q_a_section
- [ ] queries: paragraph--q_a_section
- [ ] build component
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8636
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14370
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "paragraph--q_a_section",
    "id": "5d52e032-b77c-48fb-bae1-4449f242484f",
    "drupal_internal__id": 2758,
    "drupal_internal__revision_id": 3015,
    "langcode": "en",
    "status": true,
    "created": "2019-03-04T22:24:09+00:00",
    "parent_id": "127",
    "parent_type": "node",
    "parent_field_name": "field_content_block",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [],
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "content_translation_changed": null,
    "field_accordion_display": true,
    "field_section_header": "Frequently asked quesitons about thing",
    "field_section_intro": "asdfasdf",
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/paragraph/q_a_section/5d52e032-b77c-48fb-bae1-4449f242484f?resourceVersion=id%3A3015"
      }
    },
    "paragraph_type": {
      "type": "paragraphs_type--paragraphs_type",
      "id": "f7351783-e298-425f-9b27-ac95be2ed069",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "q_a_section"
      }
    },
    "field_questions": [
      {
        "type": "paragraph--q_a",
        "id": "66125704-adec-474c-a47c-be2968a1f84a",
        "resourceIdObjMeta": {
          "target_revision_id": 3012,
          "drupal_internal__target_id": 2755
        }
      },
      {
        "type": "paragraph--q_a",
        "id": "71df0e11-b6fa-482f-9c6f-8f16449d6f3a",
        "resourceIdObjMeta": {
          "target_revision_id": 3014,
          "drupal_internal__target_id": 2757
        }
      }
    ],
    "relationshipNames": [
      "paragraph_type",
      "field_questions"
    ]
  }
```

## Acceptance Criteria

- [ ] Q&A section created
