### ISSUE TITLE
component: paragraph--list_of_link_teasers (List of link teasers)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14365]
```[tasklist]
### Tasks
- [ ] types: paragraph--list_of_link_teasers
- [ ] queries: paragraph--list_of_link_teasers
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] build component
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "paragraph--list_of_link_teasers",
    "id": "fd090f35-1c89-4bc6-9525-3e8c8221a87e",
    "drupal_internal__id": 471,
    "drupal_internal__revision_id": 500,
    "langcode": "en",
    "status": true,
    "created": "2019-01-15T16:13:36+00:00",
    "parent_id": "43",
    "parent_type": "node",
    "parent_field_name": "field_related_links",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [],
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "content_translation_changed": null,
    "field_title": "Other VA Benefits and Services",
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/paragraph/list_of_link_teasers/fd090f35-1c89-4bc6-9525-3e8c8221a87e?resourceVersion=id%3A500"
      }
    },
    "paragraph_type": {
      "type": "paragraphs_type--paragraphs_type",
      "id": "17be725c-343b-4050-a3c0-4e953226233e",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "list_of_link_teasers"
      }
    },
    "field_va_paragraphs": [
      {
        "type": "paragraph--link_teaser",
        "id": "d411fda3-dd79-4f47-91ca-f0f983b9663e",
        "resourceIdObjMeta": {
          "target_revision_id": 501,
          "drupal_internal__target_id": 472
        }
      },
      {
        "type": "paragraph--link_teaser",
        "id": "cbe8f193-a813-403e-92bf-a2c0f1fd05a2",
        "resourceIdObjMeta": {
          "target_revision_id": 502,
          "drupal_internal__target_id": 473
        }
      },
      {
        "type": "paragraph--link_teaser",
        "id": "a56015fb-7ac9-437e-851b-d64761cb2da2",
        "resourceIdObjMeta": {
          "target_revision_id": 503,
          "drupal_internal__target_id": 474
        }
      },
      {
        "type": "paragraph--link_teaser",
        "id": "119f5afd-9cf4-43f8-9e8d-dd1d77a3d173",
        "resourceIdObjMeta": {
          "target_revision_id": 504,
          "drupal_internal__target_id": 475
        }
      }
    ],
    "relationshipNames": [
      "paragraph_type",
      "field_va_paragraphs"
    ]
  }
```

## Acceptance Criteria

- [ ] List of link teasers created

**Comment by laflannery** [comment]
Based on developments I think we can reclose
