### ISSUE TITLE
Create new form classes for content release UI.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14386]
## Description

We currently have the following forms in `va_gov_build_trigger`:
- `BrdBuildTriggerForm`
- `BuildTriggerForm` (base class)
- `LocalBuildTriggerForm`
- `TugboatBuildTriggerForm`

These are tightly coupled to the environment concept and cannot really be tested in an environment-independent way.

## Tasks
- Create new versions of the forms, using current language and appearance, but environment-independent
- Redirect `va_gov_content_release` form route subscriber to point to these forms
- Redirect `va_gov_content_release` routes to point to these forms
- Find a way of injecting stub services for the test routes
- Add behavioral tests for testing these forms on every environment

## Acceptance Criteria
- [x] New forms exist
- [x] Old forms continue to exist
- [x] Existing functional and unit tests continue to pass
- [x] Behavioral tests have been added for new classes
- [x] `va_gov_content_release` and its services only refer to the new forms
