### ISSUE TITLE
Revert redirects for facilities after the CSV change is deployed

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#14400]
## Description
While Lighthouse can't merge code that's already in their staging environment (such as the services push work), they are unable to merge our CSV changes for facilities. Thus, we are going to use the redirect method to get Facility Locator to direct visitors to the full facility pages, rather than the Facility Locator pages.

When Lighthouse is able to merge their CSV changes, we should _revert_ any redirects that were created during this window. This ticket will track all the added redirects, for reversion. 

## Acceptance Criteria
- [x] Revert https://github.com/department-of-veterans-affairs/devops/pull/13240/commits
    - [x] Reverts [Fort Yates redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13403)
    - [x] Reverts [Knox West redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13378)
    - [x] Reverts [Bartlesville VA Clinic redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13399)
    - [x] Reverts [Johnson Air Force Base VA Clinic redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13405)
    - [x] Reverts [Cedar Crest Boulevard VA Clinic redirect](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13711)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
Now that [Lighthouse has deployed CSV changes](https://github.com/department-of-veterans-affairs/lighthouse-facilities/pull/479) for 
  - [Fort Yates](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13403)
  - [Knox West](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13378)
  - [Bartlesville VA Clinic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13399)

I can remove those from the devops redirects.

**Comment by omahane** [comment]
This has been completed and will be deployed tomorrow morning, Sept 13, 2023.
