### ISSUE TITLE
Deprecate the Office product

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14404]
### User Story or Problem Statement
As a CMS Product Owner and DRUPAL ENGINEER I want the codebase to be clean of cruft SO THAT upgrades and maintenance are simplified.

## Description
The Offices product was in development Q3 2021 - Q1 2022. It was eventually blocked on a Salesforce integration that has not since moved forward. @davidconlon identified that we should consider deprecating this product, since it has not moved or shipped, and is no longer a VA priority (due to the ship of https://department.va.gov/?)

## Acceptance criteria

- [x] Office tagged tickets are closed as no-op: https://github.com/department-of-veterans-affairs/va.gov-cms/labels/Office
- [ ] Office Collab Cycle tickets are closed in va.gov-team
- [ ] Office code is removed:
    - [ ] in va.gov-cms
    - [ ] in vets-api
    - [ ] in vets-website
    - [ ] in content-build

**Comment by jilladams** [comment]
FYI @wesrowe

**Comment by wesrowe** [comment]
Duplicate, closing

**Comment by jilladams** [comment]
@wesrowe can you link to the dupe ticket? It captures all the same ACs?

**Comment by FranECross** [comment]
Closing older iceboxed ticket.

**Comment by jilladams** [comment]
@FranECross totally ok to do that, just flagging: this is tech debt within our code that it would be nice to remove. While it's still around, it may require periodic maintenance / cause tests to fail, etc. But: that's also a bridge we can cross if/when it happens.

**Comment by jilladams** [comment]
Random notes since Offices are a hot topic this week: 

## Offices power the "Connect with Us" sidebar on Benefit Hub Landing Pages: 
1. In this view, `/admin/structure/views/view/content_entity_reference_source/edit/entity_reference_7`, there's a filter that explicitly only pulls in the Offices (by node ID) for VHA, NCA, VACO, and VBA.
2. On Benefit Hub Landing Page nodes, the Right Rail section, "Add a "Connect with us" block" field is powered by that view / the node options in its filter:
![Image](https://github.com/user-attachments/assets/8d9b83ee-6878-4342-9e4a-52ce9906cba4)
5. FE appearance:  
![Image](https://github.com/user-attachments/assets/56ce8482-3573-4f9b-8f19-b5f5143aa452)

## Offices power the "Connect with Us" section on Campaign Landing Pages
https://prod.cms.va.gov//node/add/campaign_landing_page
Connect with Us section > "Add a Connect with us panel:"
![Image](https://github.com/user-attachments/assets/7ae63aeb-6e22-430e-b1ad-63484694bf2a)


## Offices power the "Office" portion of select lists in the "Related Office or Healthcare System" selector 

on 
* VAMC Detail pages : https://prod.cms.va.gov/node/add/health_care_region_detail_page
* Publication Listings: https://prod.cms.va.gov/node/add/publication_listing
* News Release listings: https://prod.cms.va.gov/node/add/press_releases_listing
* Leadership listings: https://prod.cms.va.gov/node/add/leadership_listing
* Health Services listings: https://prod.cms.va.gov//node/add/health_services_listing
* Event Listings: https://prod.cms.va.gov//node/add/event_listing
* Staff Profile: https://prod.cms.va.gov//node/add/person_profile
![Image](https://github.com/user-attachments/assets/44e8fa73-b22b-4dea-9db2-07891820510e)

(For Publication Listings, only 1 was ever created, for Outreach Materials: https://prod.cms.va.gov/outreach-and-events/outreach-materials )

## `fieldOffice` provides Healthcare system name on various pages
e.g. a `fieldOffice` value does this: 
![Image](https://github.com/user-attachments/assets/aaf480fb-97bf-4d98-b57c-aabe58cde686)

~/code/content-build/src/site/layouts/vamc_system_billing_insurance.drupal.liquid:
   17            <div class="va-introtext">
   18              <p>
   19:               You can pay your {{ fieldOffice.entity.entityLabel }} bill online, by phone, mail, or in person.
   20              </p>
   21            </div>

And similar things exist on other Top Task pages. 

I suspect this is getting drawn from the same list as the Offices + VAMC Systems list, somewhere, but would need someone to prove that in the code (that Offices is actually still a part of this invocation of `fieldOffice` or would need to be removed from it.

## Offices are somehow implicated in VAMC situation updates
~/code/content-build/src/site/components/fullwidth_banner_alerts.drupal.liquid:

```
   13    {% assign statusUrl = "" %}
   14    {% for vamc in entity.fieldBannerAlertVamcs %}
   15:     {% if region == vamc.entity.fieldOffice.entity.entityUrl.path %}
   16        {% assign outputStatus = true %}
   17        {% if hideOnSubpages == true and lastArg != region and lastArg != "/operating-status" %}
   18          {% assign outputStatus = false %}
   19        {% endif %}
   20:       {% assign emailUpdates = vamc.entity.fieldOffice.entity.fieldLinkFacilityEmergList.uri %}
   21        {% assign statusUrl = vamc.entity.entityUrl.path %}
   22      {% endif %}
```
## Other code references still around
~/code/content-build/src/applications/registry.json:
```
    "appName": "All VA offices",
    "entryName": "office-directory",
    "rootUrl": "/office-directory",
    "template": {
      "vagovprod": false,
      "layout": "page-react.html"
    }
```
https://www.va.gov/office-directory/ 404s in prod
but if you publish Office content in a Tugboat, you can see the page appear: https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/office-directory/

~/code/content-build/src/site/README.md:
  213: - **fieldOffice**: needed for VAMC pages that need a side nav menu

~/code/content-build/src/site/layouts/office.drupal.liquid: - does have its own template


There are probably more. Suffice to say that before we take on deprecating the Office content type, we need to audit and get very confident about how to go about it. :D 

cc @mmiddaugh

**Comment by jilladams** [comment]
Via #17326, identified 2 addl uses of Offices, to tie Support Service content to Benefit Hub Landing Pages, and Resources & Support pages.
