### ISSUE TITLE
Allow CMS product stakeholders to view draft KB revisions

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14448]
## User Story or Problem Statement

As a national stakeholder for a CMS product, I need to view draft revisions to Knowledge Base articles so I can plan change management efforts for the user base of my CMS product.

e.g. As a member of VHA Digital Media, I need to review the [draft revisions to KB articles about VAMC System Banner Alert with Situation Updates](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14009), so I can draft an email to all VAMC CMS users explaining the changes that will be coming to the product 1 week before [those changes merge](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14117). 

or

Problem description. How might we _____________ ?

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
