### ISSUE TITLE
[Epic][AP] Analytics

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14455]
## Requirements & Goals
The VA.gov uses various Analytics tools to analyze user behavior so that the VA.gov ecosystem can provide better service to Veterans. The front end is responsible for including various analytics scripts and tools for VA.gov.

```[tasklist]
### How will we know we've achieved our goal?
- [x] All identified analytics libraries and scripts are included in the Next Build header, as directed by the Analytics team.
- [x] Analytics events can be sent from Next Build components, as directed by the Analytics team.
```

## Work and Supporting Info

```[tasklist]
### Tickets and ideas
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16501
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16105
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16106
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16382
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15515
```

**Comment by timcosgrove** [comment]
All designated work for this epic is complete.
