### ISSUE TITLE
[Epic] [AP]: Next Build ongoing build and deployment

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14464]
## Requirements & Goals
The core requirement of Next Build is that it build pages with CMS content data and deploy those pages to VA.gov. 

This epic does not encompass incremental build.

```[tasklist]
### How will we know we've achieved our goal?
- [ ] Next Build new and changed pages are built and deployed and accessible to the public.
```

## Work

```[tasklist]
### Issues or tasks to be turned into issues
- [ ] Trigger Next Build on a periodic basis
- [ ] Built output is moved to the production file store.
```

**Comment by timcosgrove** [comment]
This epic is not sufficiently defined to be actionable. Closing.
