### ISSUE TITLE
[Epic][AP] Documentation and Developer support

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14467]
## Requirements & Goals
Next Build development processes need to be documented so that teams understand how to create new products in Next Build and migrate existing Content Build products to Next Build.

## Work

```[tasklist]
### Issues or tasks to be turned into issues
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17588
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17706
```

## Supporting material

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9137
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10354
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15314
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15322
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9135
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16400
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16456
```
