### ISSUE TITLE
[Epic] [AP] Stories and story listings

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14465]
## Requirements & Goals
Stories and Story Listing pages are used by Facilities to publish human interest stories about their facility. This is our first use case for the AP effort.

We will deliver templates for these two page types as well as any templates required for the content interior of those page types (paragraphs etc). 

This epic does not include front-end global elements; see #14739 for those.

```[tasklist]
### How will we know we've achieved our goals?
- [x] All Story and Story Listing pages can be output with visual and functional consistency to Content Build's rendering of those pages (content area)
```

## Work and Supporting Info
```[tasklist]
### Tickets
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15056
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15061
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14745
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15825
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15826
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15055
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15566
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14744
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15062
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14779
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14741
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14829
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14830
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14824
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15122
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14742
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14802
```

## Supporting material
Example Story Listing: https://www.va.gov/san-francisco-health-care/stories/
Example News Story: https://www.va.gov/san-francisco-health-care/stories/leading-with-empathy-a-master-sergeants-story/

**Comment by timcosgrove** [comment]
Quarterly goal possibly?

**Comment by tjheffner** [comment]
Feedback button widget will also need added to all pages. The markup looks like it opens a medallia form

![Image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/11279744/af7c5b8b-6d02-42dc-9df5-552ceefa03c0)

https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/above-footer-elements.drupal.liquid
https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/medallia-feedback-button.drupal.liquid
