### ISSUE TITLE
VAMC product dashboard

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1447]
### User Story or Problem Statement

See [thread on #vsa-vamc-upgrade slack](https://dsva.slack.com/archives/CPQFCQKEH/p1586524258189600)

"The Health Services was  the biggest time suck, then facilities, it's a toss up for the remaining one but they were much less time consuming"

### Affected users and stakeholders

* VAMC upgrade team
* Possibly VHA staff and Facilities team.

### Hypothesis

We believe that dashboards specific to the needs of 

## Acceptance Criteria

For each of the following dashboards
- [ ] Table view
- [ ] "Displaying @number of @total " near the top
- [ ] Who last updated, and when
- [ ] Owner field
- [ ] Whatever fields are relevant 
- [ ] A menu item that lives at /admin/content/vamc-systems or below

VAMC systems
- [ ] At /admin/content/vamc-systems, there's a listing of all VAMC systems, with their most relevant content and administrative fields. 

VAMC facility health services
- [ ] On a given VAMC /health-services page, there's a listing of health services that shows the 
- [ ] at /admin/content/vamc-systems/vamc-health-services, there's a listing of all health services that shows all VAMC facility health services, with their most relevant content and administrative fields.

VAMC facilities
- [ ] On a given VAMC /locations, there's a listing of vamc-facilities for that VAMC system that shows 
- [ ] at /admin/content/vamc-systems/facilities, there's a listing of all health services that shows all VAMC facility health services, with their most relevant content and administrative fields.

**Comment by EWashb** [comment]
Deprioritized as of Q3 2022

**Comment by mmiddaugh** [comment]
Some artifacts are available related to this work: 

- [Prototype](https://xd.adobe.com/view/4837c11c-b5b4-4439-84d7-5867919f9c42-1d64/?fullscreen) with associated [user stories](https://docs.google.com/spreadsheets/d/1KFQyA5JtoTSXJDogVwJDsqPvgBtkwCzXAflGTIKUHYs/edit#gid=0) - both found in [#2786](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/2786) 
- [VAMC Dashboard tech plan.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5585011/VAMC.Dashboard.tech.plan.pdf)
- The dashboard created for Vet Centers was intended to inform this work and was designed with the following goals 
   - to provide access to everything a Vet Center editor might need to do in one place, and use the Vet Center page to do so
   - to help Vet Center editors orient to their top tasks through cards that use icons and descriptions
   - to bridge the gap between the content model and users' mental model through action links in cards that jump link to relevant parts of a form
   - to allow editors to review satellite locations and their operating statuses at a glance so they can make see what might need updating
