### ISSUE TITLE
Facilities Team Sprint 90

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14499]
# Initiatives

## VAMC Banners with Situation Updates ([#1392](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1392))
**State of the union** 
- Launched
- Post-launch follow up only 

### **NOW**
- #13543 - need to refine before adding to sprint

---

## VBA Regional Office Modernization MVP ([#10514](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514))
State of the union: 
- Consult epic "Flow" accordions for pulling in next steps for sprint planning / future sprints
- Midpoint Review 8/1
- Integrate feedback, start prototype (sprint priority)
- Prototype blocks usability testing

### **NOW**
- [x] #14351 - Content - was in S89, complete any rollover work on final reviews in S90
- 8/1 Midpoint Review (https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)
    - Follow up with CAIA re: service accordion content: https://github.com/department-of-veterans-affairs/va.gov-team/issues/58511
- 🎯 #13960 - Design
    - Include draft Service accordion content  
- #14524 - Research - when prototype is available
- #13338 - Research - when prototype is available
- 🎯 #13811 - Content
- #14528 - Research - Stretch / if blocked on other projects
- #14088 - Drupal admin
- #14529 - Content - pre-refine so we can pull it into 91?

<details><summary>Blocked by research</summary>

- #11267 - Content

</details>
---

## Lighthouse V1 ([#12921](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12921))
State of the Union: 
- LH v1 expecting to launch early August
- TODO: LH to verify V0 deprecation timeline ([trello card](https://trello.com/c/X7RMCnnf/30-v0-retirement-timeline))
- TODO: Create tickets for V1 adoption, when launch timeline / V0/V1 diff documentation has been provided by Lighthouse

---

## Facility Locator  ([#11542](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11542))
State of the union: 
- Implementing changes from Design Intent
- Will need Midpoint Review after

**This sprint**
- [x] #13359 - Ruby - S89, hopefully complete / no rollover. Complete in S90 if not.
- [x] #14533 - Design - double check Jordan's capacity relative to CLP / Q&A work
- TODO: ticket: Tech: Think about order of ops / whether we can start any architectural process now
- TODO: Think about implementing LH V1 in FL: what's there / close the gap / how do we handle launching V1 with the old designs

---
### 1. Mental Health phone numbers ([#9717](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9717))
- #14578 - Content - Needs refined, how does priority stack against VBA content work?

### 2. Lovell TRICARE switch link
- 🎯 #14479 

---

# Product Maintenance 

## Drupal 10 upgrade Testing ([#13112](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13112))
Should be largely complete from S89.
- 🎯 #14388

## Other
- #13679 - Drupal
- #14586 - FE - Needs to be refined
- #13980 - Drupal
- #14238 - Drupal
- #14277 - FE
- #13331 - FE

# Continuous Work streams 

## Flagged Facilities ([board](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13546#workspaces/flagged-facilities-64b47ffcd5bea6bc6ba82ddc/board))
- #13624  - Drupal
- #13842 - Drupal
- #14400 - need to clarify status / what action can be taken

Facility status changes:
- #13714 
- #13546 
- #13545 
- #14588
- #14589
- #14560 
- #14561 
- #14510 
- #14511 
- #14614 
- #14509

**Comment by jilladams** [comment]
Removing COVID backend: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13676

**Comment by jilladams** [comment]
VBA-specific refinement questions: 
* Centralized content to ship hard coded or to Drupalize (effort): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13799#issuecomment-1654461264

**Comment by jilladams** [comment]
Updated body with Flagged facility tickets that Helpdesk has indicated are "Ready to go"

**Comment by mmiddaugh** [comment]
@jilladams for space and other considerations,  I'd suggest removing the VHA DM priorities which are not in progress from the sprint planning template and just listing those in progress as team priority items

**Comment by jilladams** [comment]
Topics for team refinement toward S91:    
* Drupal - operating status for VBA - need to write a ticket
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11848
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13543

**Comment by mmiddaugh** [comment]
Suggest that we refine these accessibility issues this week or next:
- Add heading for Facility map #12905
- 
VAMC Templates - On this page links must set focus correctly in iOS Safari + VoiceOver #13946 (ally defect-2)
