### ISSUE TITLE
SE: Lighthouse V1 adoption before V0 EOL

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14507]
## Background

Lighthouse Facilities V1 shipped August 24, 2023. When shipped, any Facilities products that use Lighthouse Facilities API V0 will need to be updated to use the V1 API. This will involve: 
* Assessment of each product for V0 usage
* Identifying V1 endpoints to be used instead, if not already done
* Ticketing each piece of effort separately, per product, including testing expectations. 
* Testing V0 > V1 cutover per product. 

Known impacts: 
* Facility Locator front-end

## V0 sunset
As of Dec 2023:  June 1, 2024 is now estimated V0 EOL date.
https://trello.com/c/X7RMCnnf/30-facilites-v1-adoption-v0-retirement-timeline
* May 20, 2024: https://dsva.slack.com/archives/C02BTJTDFTN/p1716217882889939 - extension to 6/14

### User Story or Problem Statement

As a consumer of the Facilities API, I want access to new features exposed in Lighthouse Facilities V1.

As a consumer of the Facilities API, I need support for V0 features until V0 is formally deactivated.

### Affected users and stakeholders

Users: 
* Facilities API consumers

Stakeholders: 
* Lighthouse Facilities team

### Scope
Throughout this effort, we found several unexpected uses of the Lighthouse V0 endpoint in Facilities and Public Websites code. Those invocations are documented here, and can be used to scope the next migration / next time Lighthouse releases a new endpoint: 
* [Lighthouse Facilities API calls through facilities API in vets-api](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facilities-api/README.md#productsfeatures-using-facilities-api-calls-with-lh-facilities-api-data)
* [Direct LH Facilities API calls from CMS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facilities-api/README.md#productsfeatures-integrated-directly-with-lh-facilities-api-data-not-via-facilities-api)
* [LH uses of the legacy Facilities API client in vets-api](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facilities-api/README.md#legacy-facilities-api-client)

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

**Comment by jilladams** [comment]
Noting: V0 sunset date updated to June 1, 2024: https://trello.com/c/X7RMCnnf/30-facilites-v1-adoption-v0-retirement-timeline.  Updated in ticket body.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C02BTJTDFTN/p1716217882889939

Lighthouse have agreed to extend V0 deprecation deadline to 6/14.

**Comment by jilladams** [comment]
Our LH Fac API dependencies now documented for future LH API revs: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facilities-api/README.md#lighthouse-facilities-api-product-dependencies--scope

cc @mmiddaugh

**Comment by jilladams** [comment]
Final step here is resolving the legacy API client ownership questions. Notes / updates in that ticket (#18351 )
