### ISSUE TITLE
Update Facility Locator to point to modernized VBA RO pages

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#14531]
## Description
Once VBA RO sites are launched into Dual-state, update Facility Locator to point to them rather than the existing Facility detail pages ([example](https://www.va.gov/find-locations/facility/vba_459))

Note: Largely the code to do this already exists, it is just not being applied to VBAs.   It is really the second piece of the acceptance criteria (not pushing an address if not published) that is an alteration to the existing logic.

## Acceptance Criteria
- [x] Assess risk of doing this before FE launch
- [x] When a VBA facility is published, it should push its new url to Lighthouse. 
- [x] When a VBA facility is not published (remains unpublished) it should not push a url ~~so that the facility API will still use what remains in the CSV that Lighthouse maintains~~ (Note: The CSV determines the website URL, regardless of what is pushed to Lighthouse, until such time that Lighthouse changes their source for the website URL).

## Implementation steps
- [x] Determine the mechanism for VBA pages to be correctly linked from the Facility Locator.

## Context on VBA links
In the Facility Locator at present, a [search for a benefit office](https://www.va.gov/find-locations/?address=Philadelphia&bounds%5B%5D%5B%5D=-76.56401000000001&bounds%5B%5D%5B%5D=38.550886&bounds%5B%5D%5B%5D=-73.76401&bounds%5B%5D%5B%5D=41.350885999999996&context=Philadelphia%2C%20Pennsylvania%2C%20United%20States&facilityType=benefits&latitude=39.950886&longitude=-75.16401&page=1&radius=25&serviceType&bounds%5B%5D=-76.56401000000001&bounds%5B%5D=38.550886&bounds%5B%5D=-73.76401&bounds%5B%5D=41.350885999999996) leads to a Facility Locator detail page, such as  Philadelphia's page: https://www.va.gov/find-locations/facility/vba_310

This is despite the fact that the [websites.csv](https://github.com/department-of-veterans-affairs/lighthouse-facilities/blob/master/facilities/src/main/resources/websites.csv) in lighthouse-facilities has this entry:
`vba_310,http://www.benefits.va.gov/philadelphia`

Similarly, the API itself has the same url for that facility:
```
 "id": "vba_310",
            "type": "va_facilities",
            "attributes": {
                "name": "Philadelphia VA Regional Benefit Office",
                "facilityType": "va_benefits_facility",
                "classification": "Regional Benefit Office",
                "website": "https://www.benefits.va.gov/philadelphia/",
```
With other facilities, it is the URL in the csv that determines what URL Facility Locator uses, but this does not seem to be the case with VBA. 

Is there some mechanism either in `vets-website` or `vets-api` that determines whether to show the link provided in the API or a Facility Locator detail page?

**Comment by jilladams** [comment]
@swirtSJW @omahane @maxx1128 is this FE or Drupal work? (I tagged with both for now.)

**Comment by davidmpickett** [comment]
This won't happen until after Staging Review, so can safely float into National Epic

**Comment by jilladams** [comment]
Noting: I don't think we'll declare success on Prod launch til this work is done, so we should consider it the last mile of the pilot, which now captures prod launch. (Unless I've missed a beat somewhere.)

**Comment by davidmpickett** [comment]
> Noting: I don't think we'll declare success on Prod launch till this work is done, so we should consider it the last mile of the pilot, which now captures prod launch. (Unless I've missed a beat somewhere.)

You are right, I was conflating this with the redirects. It seems like this conditional logic could be in place for Staging Review.

**Comment by mmiddaugh** [comment]
Related: [CONSIDER] Disable VBA service type dropdown in Facility Locator #17781

**Comment by jilladams** [comment]
Are there risks to having this change merged before Staging Review? thinking: Inadvertent VBA publishing, etc.

**Comment by mmiddaugh** [comment]
@omahane, new web editors for VBA Regional Office pages only get content creator/editor permissions. Only VNBA leadership will have publishing rights. As the modernized pages begin rolling out, these editors will maintain facility operating status for facilities which have modernized/published pages and for facilities which still have legacy TeamSite pages. They will need to remember to save any status changes according to the previous moderation state and may easily make mistakes when saving. Does this present an additional risk or will the csv still be the source of truth for LH?

**Comment by omahane** [comment]
TODO: Look into the editor experience when they don't have the "Content publisher" role.

**Comment by omahane** [comment]
# Primacy of CSV for Facility Locator (for all but VBA)
The CSV determines what get's put in the "websites" property for a given facility in the Facilities API, per [Adam](https://dsva.slack.com/archives/C02BTJTDFTN/p1719489850971679). Until Lighthouse cuts over to using Drupal as the source for this data, the CSV is the single source of truth. The Facility Locator (FL) uses this website url for the link in search results. Should there be no website url, the FL uses a link to the FL detail page, such as for a new facility like Brownsville VA Clinic: https://www.va.gov/find-locations/facility/vha_740GK.

Normally, that's where the story would end, but VBA is spinning its own little yarn, because there exists URLs in the Facilities API for our VBA ROs, that come from the CSV, such as this line: `vba_340,http://www.benefits.va.gov/albuquerque`. Nevertheless, when searching for a VA benefits location, you are presented with a FL detail page. 

I think there must be something in the FL code that is determining not to show the TeamSite pages for VBA, but I don't know what it is. If it triggering off of the URL pattern `www.benefits.va.gov`, then a change to the CSV should work. However, if it is triggering off of the type of facility from the Facility type dropdown on the FL page, then a CSV change will be necessary but not sufficient to present the correct URL.

![Screenshot 2024-06-27 at 9 56 51 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/05a1ba7a-4e5f-4b5c-90c2-4a926dcf45e0)

**Comment by omahane** [comment]
# Editing an unpublished facility as a Content editor (without the Content publisher role)
When editing a facility that has never been published, an editor can change the status of a facility. Should they save that facility, they will only have the option save it as Draft or In Review. Any save will post the facility's status to the Post API queue, which is consumed by Lighthouse and will be shown on the front end.

# Editing a published facility as a Content editor (without the Content publisher role)
When editing a facility that has been published, an editor can change the status of a facility. Should they save that facility, they will only have the option save it as Draft (if editing the default revision) or either as Draft or In Review (if it's a forward revision). No save, however, will result in the status being added to the Post API queue, meaning that Lighthouse will not know of the status change.

This ability to draft content that is not sent to Lighthouse allows an editor to draft a facility status of a published facility without publishing the language or type of status, should they desire a review of that language or status type before publishing. 

This also means, though, that should our VBA editors wish to change the status of a published facility before they have been granted the Content publisher role, they will need to have another person publish their change to make the status change live.

# Can an editor inadvertently publish a page?
- No
- Neither can they somehow upon save send a URL to Lighthouse that will be used by the Facility Locator (see comment above bout CSV primacy).

**Comment by eselkin** [comment]
I'll look into whether FL uses some different URL presentation for VBA since that Albuquerque one should folllw the CSV but isn't.

**Comment by omahane** [comment]
> I'll look into whether FL uses some different URL presentation for VBA since that Albuquerque one should follow the CSV but isn't.

I'll make a ticket for this.

**Comment by mmiddaugh** [comment]
For the benefit of our future selves: the desired behavior for VBA is that FL search results point to FL detail pages (which link to the website) so that the service information is reliably available to Veterans and other beneficiaries. 
So while the behavior shouldn't change, we do need to understand what might be overriding the LH csv data for VBA so that as new RO modernized pages are published, FL search results can point directly to the new page.

**Comment by omahane** [comment]
> For the benefit of our future selves: the desired behavior for VBA is that FL search results point to FL detail pages (which link to the website) so that the service information is reliably available to Veterans and other beneficiaries. So while the behavior shouldn't change, we do need to understand what might be overriding the LH csv data for VBA so that as new RO modernized pages are published, FL search results can point directly to the new page.

It seems like we want the current behavior until such time as we add a Drupal-sourced facility URL to the websites.csv. At that point, we'd want that link in the search results. If so, then the URL string determines whether we want a FL detail page or the Drupal-sourced page. Correct?

**Comment by mmiddaugh** [comment]
> It seems like we want the current behavior until such time as we add a Drupal-sourced facility URL to the websites.csv. At that point, we'd want that link in the search results. If so, then the URL string determines whether we want a FL detail page or the Drupal-sourced page. Correct?

Correct!

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner #17977 is a blocker for this ticket, so we should bring that into the sprint.

**Comment by omahane** [comment]
Also #18413 is also a blocker to this ticket.

**Comment by Agile6MSkinner** [comment]
@omahane Does that mean we can close 18413 or just that it's not a blocker?

**Comment by omahane** [comment]
> @omahane Does that mean we can close 18413 or just that it's not a blocker?

Could someone on the product side document Eli's findings [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator)? Then, I'd say we can close it.

**Comment by omahane** [comment]
@jilladams Until such time as a VBA facility is published, we have given Lighthouse the CSV changes, and they have been deployed, this is blocked.

**Comment by jilladams** [comment]
Eli's findings on #18413 are documented: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18413#issuecomment-2214641216

I am closing this ticket. Code has been merged, and when we have a Facility ready to publish (after we clear Security review) we can ticket any specific work required for that particular publishing process.
