### ISSUE TITLE
PW Sprint 90 Plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14547]
Google doc for actual editing: https://docs.google.com/document/d/1MDBNok_-v0ze0ZOA4iG_FYd6zlHURfLug5mFhueVPcU/edit?usp=sharing

## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)

🟢 Product:
- [ ] #14106 (0) - Product - carryover from s89 🎯
- [ ] (Analytics team delay: several more sprints from 8/1) #13480 - Product - **blocked** on Plat Analytics implementation

🟡 Engineering:
- [ ] #14593 (3) - FE 🎯
- [ ] #14613 (5) - FE
- [ ] (post C.C.) #14294 - **blocked** on C.C. Staging Review & Security Review

### 2. PACT Act Wizard [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢  
- [ ] #13324 (5) - Research 🎯
- [ ] (stretch; pending SM decision) #14447 (8) - Research - carryover from s89; Survey Monkey dependency
- [ ] (tbd) #14444 - Design - Need / priority is TBD on survey tool decision
- [ ] (tbd; may not need) #14446 - Design - Need / priority is TBD on survey tool decision 
TODO: Assess lift for OW design needs (Cindy)

### 4. Expand Q&A Reusability [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡
- [ ] #14541 (5) - FE - fix R&S Q&As - good first task
- [ ] #10944 (8) - FE - good first task
- [ ] #14443 (8) - Design - paused in progress, bumped from s89 due to VBA
- [ ] (defect) #14604 (3) - BE
- [ ] (defect; can we reproduce?) #14605 (5) - BE

### 5. Benefit Content Model Hardening [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
- [ ] #14577 (5) - BE 🎯goal?
- [ ] #14290 (8) - BE
- [ ] #14289 (3) - BE
- [ ] #14582 (0) - Product (synthesize hallway)

Post-MVP
- [ ] (post-MVP) #14532 (3) - BE
- [ ] (post-MVP) #14534 (needs) - BE
- [ ] (post-MVP) #13142 (5) - BE

### Mobile App Promotional Banners [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482) 🟢
- [ ] (stretch) #14179 (0) - Product
- [ ] (later) NEED Launch ticket
- [ ] #14288 (0) - Product

### Post-MVP Homepage 🟡  
- [ ] (stretch) #13863 (3) - BE - Need to review ACs collectively re: CTAs (save draft/publish)

### Cerner API deprecation support 🔴  
- [ ] #9307 (5) - FE - **blocked** on Appointments team code change

# Other PW Priorities
## Prioritized for this sprint
(Note: may be duplicated in sections below)
- [x] (carryover from s89) #13736 (8) - FE 
- [ ] (carryover from s89) #11354 (5) - FE - good first issue
- [ ] (stretch) #13147 (2) - FE
- [ ] (stretch) #13222 (8) - FE
- [ ] (stretch) #14150 (5) - FE
- [ ] (stretch) #11854 (5) - FE
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #12933 (5) - BE

## Backlog of non-quarter priorities (for easy access)
Tech debt, Defects, Drupal 10 upgrade

Cross-repo dependencies post-mortem

Other priorities
- [ ] (stretch) #13329 (3) - Design - Jordan dependency
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #11230 (3) - BE

### Content / IA priorities (CAIA)
- [ ] va.gov-team 58142 - **blocked**; CLP-related

### Portfolio and pipeline - [epic](#7599)
- [ ] #12791 (needs) - Design
- [ ] (awaiting Cindy update on status) #12601 (needs) - Design

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] (stretch) #13147 (needs_refining) - FE
- [ ] (stretch) #13137 (needs_refining) - FE
- [ ] (stretch) #14219 (need_refining) - FE - mtg w/Appointment team 8/3

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.
