### ISSUE TITLE
Data map of current state vs. future state for Mental Health phone number data sources

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14578]
## Background
Context: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9717#issuecomment-1659077902

Mental Health phone numbers in the CMS has some open questions: 
1. Where in the CMS should the numbers live? (System? Facility?)
2. How should they be governed? Legislative requirement to update every 90 days, so we need to understand who is responsible / will be responsible for those updates. 

The source data situation is also complex, currently, and being able to demonstrate where the data comes from / how it's managed today, vs.where we are trying to go, may help with the governance conversation. 

## Task
Articulate visually the current and future states of Mental Health phone number data.

## ACs

- [x] An artifact is created to help clarify current data flow vs. desired future state
- [ ] Artifact is brought to/shared with Michelle, Justin (VHA DM), Blake Scates (VHA DM) for review to determine next steps re: governance
- [x] Create a ticket for Governance for adding a new kind of notification

**Comment by davidmpickett** [comment]
Places where mental health phone number currently show up:

- 0-? Per system on [Mental health care detail pages](https://www.va.gov/north-texas-health-care/health-services/mental-health-care/) 
- 0-1 Per facility in [FL results](https://www.va.gov/find-locations/?page=1&address=76119&facilityType=health&serviceType&latitude=32.685791&longitude=-97.279635&radius=10&bounds%5B%5D=-98.029635&bounds%5B%5D=31.935791000000002&bounds%5B%5D=-96.529635&bounds%5B%5D=33.435791&context=Fort%20Worth%2C%20Texas%2076119%2C%20United%20States) 
- 0-1 Per facility on [VAMC facility page](https://www.va.gov/north-texas-health-care/locations/fort-worth-va-clinic/) 
- 0-? Per facility on [Mental health care service accordion](https://www.va.gov/north-texas-health-care/locations/tyler-centennial-va-clinic/#health-care-offered-here) on facilities that have that service

**Comment by davidmpickett** [comment]
Look at how this may potentially connect with the Mental health care effort of https://github.com/department-of-veterans-affairs/va.gov-team/issues/13881

**Comment by mmiddaugh** [comment]
I have this [mural on data sources and flows](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?sender=u3fcece2648da0fcf15d81890) which has helped to clarify my understanding it might be helpful

**Comment by davidmpickett** [comment]
Working in a [new section](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1693242058396) of Michelle's existing mural

**Comment by davidmpickett** [comment]
Shared links to current and existing state with Michelle for review https://dsva.slack.com/archives/C0FQSS30V/p1693246922119459

**Comment by davidmpickett** [comment]
@xiongjaneg @jilladams @mmiddaugh For AC #2, do you want to add me to the invite / agenda for an upcoming VHA DM sync?

**Comment by davidmpickett** [comment]
Ticket for notification https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14730

**Comment by xiongjaneg** [comment]
@davidmpickett We've been discussing regularly at VHA DM sync. I'll add your most recent notes to the ongoing topic in that meeting so that we can close this ticket. Thank you!

**Comment by jilladams** [comment]
Based on the 3 comments above, closing.

**Comment by jilladams** [comment]
@davidmpickett also forwarded invite to the Tues 9/5 occurrence of VHA DM sync so you can join to discuss.

**Comment by mmiddaugh** [comment]
I'd like to discuss this internally before reviewing with VHA DM @davidmpickett @xiongjaneg @jilladams

**Comment by davidmpickett** [comment]
Updated future diagram based on meeting today: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1690837066198/79f3d0e816f12daaf9a9ede96f4cf14ab6932cb7?wid=0-1693263650243

**Comment by xiongjaneg** [comment]
Potential future paths:
Option 1: make an editable field for editors and explain what it represents, for places it's blank have a default or editable number
Option 2: have a default fallback number, either MH or System main, that is automated or a choice is given to editors

**Comment by xiongjaneg** [comment]
@mmiddaugh @xiongjaneg check with VHA DM: do they want a fall back number?

**Comment by xiongjaneg** [comment]
Adding a default fallback number would likely be simpler on the front end. In Drupal, it would be more complicated. 

There is a possibility of a contraction, such as the custom number entered by the editor matches the System main number. This could be detected by Drupal.
