### ISSUE TITLE
SE: VHA DM Priorities for Facilities, Q3 2023

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14581]
## Background
https://trello.com/c/GYAKSooC/24-vha-dm-priorities-for-facilities-projects-within-drupal-justin

Narrative dumped from Trello. **TODO**: Migrate details into each epic / ticket , as appropriate.

### Order
1. Mental Health phone numbers [#9717 ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9717)(#1 as of 7/31)
2. Lovell issue TRICARE patients: [#14479](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14479) refined an issue to change alert color, will satisfy this. Should go into Sprint 90.
3. Police transparency/ metadata (Facilities) [#14327](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14327) - Will jump the line when we have the necessary data. Similar to Access to Care, likely an external API, Michelle has created a stub ticket.
4. VAMC Hardening: Maps – start in Q3, tbd bandwidth. - **TODO**: Find the existing epic(s) / ticket(s). Organize into a subepic. We know some exist.
5. VAMC Hardening: Required health services - **TODO**: Find the existing epic(s) / ticket(s). Organize into a subepic. We know some exist.
6. VA Services proposed new terms 

## Maps specifics
Michelle has started an audit to see what exists.

Some locations link to a lovely interactive map already. That could make this project light lift: we get that link. If not, we’ll have to support 2 sorts of experiences.

Steps to hardening:

Audit / figure out VAMC access to interactive maps.
Content modeling for new reality
Drupal / CMS Design – hand in hand
Editor UX research: TBD
FE design
FE Research: TBD
FE build

### VAMC Hardening: Required health services
 hardening effort for 7 pages, e.g. minority veteran care, returning service member, caregiver, etc. Smaller lift than Map. We may suggest flipping priority.

Currently VAMC detail pages being used in a variety of ways. These 7 pages, specifically, are correlated to VA Services taxonomy terms, but we do not think the data is pulled from the Taxonomy in any way.

e.g.    and https://prod.cms.va.gov/pittsburgh-health-care/health-services/women-veteran-care

Paragraph under H1 should become a ~centralized content sort of model

Connect with a (named person) is local

Care we provide section might come from the taxonomy, TBD

Other Resources to be standardized

## VA Services proposed new terms (in this order)
 Doesn’t require much work from the team, just input from Taxonomy Council to create new terms.

Each of these new terms has existing content that could be tied in Drupal content. Michelle to decide when / what to coordinate with Facilities team vs. Content team and direct entry in Drupal / Taxonomy.

New terms:

Veteran Canteen Service (VCS) (will also get a CLP) --VCS is retail / physical store per campus. It has benefits that tie into existing VA Services / benefits – e.g. we can tie existing optometry benefits available to existing VA Services, as a content addition in the Taxonomy term itself.

There are easy wins here, even if we don’t take the Taxonomy new term approach right now. No research / no eng effort.

Chaplain

Library

Home-Based Primary Care (HBPC) – adding these items as new services

# Epic template

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`
