### ISSUE TITLE
Catalogue functional requirements based on current codebase.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14661]
## Description

In order to determine effective test coverage of our functional requirements, we first have to create some sort of list of those functional requirements. Unfortunately, we do not have a comprehensive suite of tests that would, by their existence, firmly establish our functional requirements.

So it is necessary to go through our codebase and reverse-engineer this, to the extent possible.

## Tasks
- [ ] Derive a list of functional requirements from studying the following resources:
  - [ ] Custom content types
  - [ ] Custom modules
  - [ ] Custom themes
  - [ ] Custom blocks
  - [ ] Custom taxonomy vocabularies
  - [ ] Contributed modules
  - [ ] Core functionality
  - [ ] Views
  - [ ] Other Configuration
  - [ ] Upstream dependencies
  - [ ] Downstream dependencies
  - [ ] Content Build
  - [ ] DevOps functionality
    - [ ] Supporting DDEV
    - [ ] Supporting Tugboat
    - [ ] Supporting BRD
- [ ] Create a document with the list of functional requirements. Not a spreadsheet, not a Mural, not a PNG. Just a document. It's going to get outdated quickly, but that doesn't matter, it's just for an initial estimate.
- [ ] Open up followup tickets to address specifics of each of these areas.

## Acceptance Criteria
- [ ] A document containing a raw list of functional requirements has been generated.
- [ ] Followup ticket(s) opened to address or respond to individual issues raised by this process.

**Comment by ndouglas** [comment]
This leads to a number of questions, which I'm developing approaches to at this time.

1. What custom content types do we have? Which of these have some degree of behavioral test coverage (see #14662)?
2. What custom modules do we have? Which of these have some degree of unit or functional test coverage (see #14663)?
3. What custom classes do we have? Which of these have some degree of unit or functional test coverage (see #14665)?
4. In what ways can we test our `vagovclaro` custom theme most effectively?
