### ISSUE TITLE
Facilities Team Sprint 91

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14673]
# Schedule Notes
- Alexis out Aug. 16
- Cindy out Aug. 16-18
- Max out Aug. 16-18
- Jill at DC onsite Aug. 22-24
- Michelle at DC onsite Aug. 23-24

# Sprint Priorities
At the end of this sprint, what do we want to have accomplished/delivered?

- [x] 🎯 #14524 
- [x] 🎯 #14525 (both Sprint 91 and 92)
- [x] 🎯 #14798 
- [x] 🎯 #14705  

# Initiatives

## VBA Regional Office Modernization MVP #10514
- [ ] #14529 continuing
- [ ] #14702

## VAMC
- [x] #14277 
- [ ] #13941 
- [x] #14578 

### VA Police Transparency #14327
- [x] scheduled for next week, will need an Drupal engineer, which will depend on availability when meeting is set

## Vet Centers
- [ ] #11789 

## Lighthouse V1
- [x] launch next week, may be unplanned work to support
- [x] #14813 

## Unplanned Work
- [x] #14867 

### Flagged Facilities #13716
- [Ready tickets](https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=is%3Aopen+is%3Aissue+label%3A%22Flagged+Facilities%22+label%3AReady)

### Tech Debt
- [x] #13331

**Comment by xiongjaneg** [comment]
copied from 90, need updates

**Comment by jilladams** [comment]
8/14 from Michelle: Priority for refinement: Vet Center Notifications (intended to begin at the beginning of October)
