### ISSUE TITLE
PW Sprint Plan 91

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14679]
Google doc for actual editing: https://docs.google.com/document/d/1Loi1UKmaSkr7cl2r2yKq1kbS_8R-s6UmJZkmX4rDTVE/edit?usp=sharing

## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic #9626](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)

🟢 Product:
- [ ] TICKET: Security and readiness review (0) - Product
- [ ] (Analytics team delay: several more sprints from 8/1) #13480 - Product - **blocked** on Plat Analytics implementation

🟡 Engineering:
- [ ] #14046 (3) - FE
- [ ] (injection?) #14854 - FE (a11y thing just enabled by DST)
- [ ] (injection?) #14858 - FE
- [ ] (post C.C.) #14294 - **blocked** on C.C. Contact Center & Security Review
- [ ] (stretch) #14818 (needs) - BE
- [ ] (stretch; blocked on 14818) #13759 (8) - BE
- [ ] (stretch) #13760 () - BE
- [ ] (stretch) #13761 () - BE

### 2. PACT Act Wizard [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢  
- [ ] (carryover from S90) #14447 (8) - Research
- [ ] (carryover; paused in s91) #13324 () - Research
- [ ] (supports 14729) #14444 - Design 🎯
- [ ] #14729 - FE 🎯
- [ ] (stretch) #14749 (5) - Research
- [ ] ~~(tbd; may not need) #14446 - Design - Need / priority is TBD on survey tool decision~~

### 4. Expand Q&A Reusability [epic #10780](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡
- [ ] #14814 (5) - FE (accordions)
- [ ] #14790 (8) - Design
- [ ] #14442 (latest est.?) - BE
- [ ] (stretch; KB) #14633 (needs) - BE/PM/DM

### 5. Benefit Content Model Hardening [epic #9628](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
- [ ] #14289 (3) - BE
- [x] #14582 (0) - Product (synthesize hallway)
- [ ] (stretch; Drupal debt) #14777 (2) - BE
- [ ] (stretch; Drupal debt) #14778 (5) - BE
- [ ] (stretch) #14817 (needs) - BE (dotted border)
- [ ] (stretch) #14860 (needs) - BE (View screen enhancements)
- [ ] #14532 (3) - BE
- [ ] #14534 (needs) - BE
- [ ] #13142 (5) - BE

### Mobile App Promotional Banners [epic #13482](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482) 🟢
- [ ] (stretch) #14179 (0) - Product
- [ ] (later) NEED Launch ticket
- [ ] #14288 (0) - Product

### Post-MVP Homepage 🟡  
- [ ] (rollover from s90?) #13863 (3) - BE
- [ ] (stretch; worth the effort?) #14800 (5) - BE 🎯

### Cerner API deprecation support 🔴  
- [ ] #9307 (5) - FE 

# Other PW Priorities
## Prioritized for this sprint
(Note: may be duplicated in sections below)
- [ ] (stretch) #14788 (8) - Design
- [ ] #14819 (5) - FE - search.gov error triage
- [ ] #13222 (8) - FE
- [ ] (stretch; events, needs Dave buy-in) #14904 (2) - BE
- [ ] (stretch) #13099 (needs) - FE
- [ ] (stretch) #14793 (needs) - BE
- [ ] (stretch) #14150 (5) - FE
- [ ] (stretch) #13137 (3) - FE
- [ ] (stretch) #11854 (5) - FE
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #12933 (5) - BE
- [ ] DEPRECATE OFFICES product and close loop on documentation - #11233? - BE

## Backlog of non-quarter priorities (for easy access)
Tech debt, Defects, Drupal 10 upgrade
- [ ] (stretch) #14767 (needs) - FE

Cross-repo dependencies post-mortem

Other priorities
- [ ] (stretch) #13329 (3) - Design - Jordan dependency
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #11230 (3) - BE

### Content / IA priorities (CAIA)
- [ ] va.gov-team 58142 - **blocked**; CLP-related

### Portfolio and pipeline - [epic](#7599)
- [ ] #12791 (needs) - Design
- [ ] (awaiting Cindy update on status) #12601 (needs) - Design

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [x] (stretch) #13147 (needs_refining) - FE
- [ ] (stretch) #13137 (needs_refining) - FE
- [ ] (stretch) #14219 (need_refining) - FE - mtg w/Appointment team 8/3

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.

**Comment by jilladams** [comment]
@wesrowe Note: Facilities doesn't have design tickets for Jordan in Sprint 91, so PW can use Jordan's full capacity, if we have runway for that.

**Comment by jilladams** [comment]
Cindy - every research
Jordan - PW only: 
* #14790 
* #14788 

Daniel - #13759, burning down Magichead bugs (drupal debt first)
Christia - *14442, 13863, other Drupal config work

Randi / Chris - Prioritized in this sprint list

Top priorities for refinement: 
FE: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14294

**Comment by jilladams** [comment]
From planning: Dave may need us to review / prioritize Search issues from https://dsva.slack.com/archives/CBU0KDSB1/p1690239844318679

**Comment by wesrowe** [comment]
Today we created two new I.L. FE tickets – both are launch-blocking, so I recommend that we pick them up and displace other work from the sprint plan as needed.
