### ISSUE TITLE
Vet Center notifications

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14694]
## Description

- The goal of VA Directive 6102 is to present information and services to Veterans, caregivers and their families in a consistent and accessible way. To achieve this goal, the directive provides policies and standards that must be followed by all websites within the VA ecosystem.
- CMS has implemented CMS notifications to help editors comply with VA Directive 6102 via reminders to review and update content based on a new "Outdated content" view. 
- Currently notifications are being sent to VAMC editors.
- We need to implement notifications to Vet Center editors. This roll-out is intended to begin on October 1, following a return of office hours, and communication to editors by RCS. 
- This will be the first time that CMS has a product team implement notifications - some knowledge transfer may be necessary. 

## Background
- Notifications use flags as triggers
- The Outdated content report is based on the last touched by an editor date, using one year as the definition for "outdated"
- Editors receive an email which links to the [outdated content report](https://prod.cms.va.gov/admin/content/outdated_content) and the [Outdated content audit report KB article](https://prod.cms.va.gov/help/cms-basics/outdated-content-audit-tool)
- Product documentation is available in the platform repo: [CMS Notifications for VA Directive 6102](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/VA-Directive-6102-Notifications.md#cms-notifications-for-va-directive-6102)
- [Notification product outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-outlines/VA-Directive-6102-Notifications.md)
- [Figma design for email](https://www.figma.com/file/fQl2Y2k9MDA2dc0xViC645/6102-Notification-Email?node-id=510%3A7202&t=fNO1WcUptIYDq7d6-1) 
- [Directive 6102 KB article](https://prod.cms.va.gov/help/va-directive-6102)
- #10139 Triggers for CMS notifications

<details>
<summary> Screenshots of outdated report </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcmtUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--187f1ace47381680e6458545f7022955e8861f01/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcndUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a10258e17fce2d08022066f8bf66bcef1447ecd4/image.png)

</details>

## Vet Center specifics 
Vet Center notifications will follow the VAMC implementation with a few modifications, including
- Vet Center notifications will leverage Vet Center specific email language and KB article (draft in progress)
- Vet Center notifications will have a different cadence than VAMC notifications (twice monthly, beginning in October)

## Problems to solve
Spotlights are an important content type for Vet Center editors to review because they are frequently used to advertise events and can become outdated quickly. 
- They are not a content type which is specifically surfaced on the outdated content audit report. 
- How might we support Vet Center editors in reviewing spotlight content more often? 

## Tasks

- [x] Finalize language in email (drafted and waiting for approval by Vet Centers)
- [ ] Finalize language in KB article (including getting Vet Center content out of existing article, Vet Center article is drafted)

CMS initially framed out the following issues, which are attached to their epic #10477
- [ ] Manual queue of Vet Center editor notifications email #13045
- [ ] Add Vet Centers editor emails to existing tasks.yml #13044

**Comment by xiongjaneg** [comment]
spotlights, in particular, are used for events and get outdated fast

**Comment by xiongjaneg** [comment]
Spotlights get outdated fast because they're used for events, how can we monitor these easilty? (unlike content types, which we can view)

**Comment by xiongjaneg** [comment]
potentially two links in the same email or separate emails with each, may be consistent with national's desire for biweekly notifications:
- report on what's outdated
- section view that's filtered for Facilities

**Comment by xiongjaneg** [comment]
Oct. 1 is a Sunday. And Facilities Team members have adjacent company offsite responsibilities.

**Comment by mmiddaugh** [comment]
Updates based on my most recent conversation with RCS - fyi @xiongjaneg 

- monthly notification timing
- email will point to KB article rather than to the outdated tool, because of the definition of "outdated" and the ability to identify featured content/spotlight content separately.

**Comment by xiongjaneg** [comment]
moved future iteration ideas to #16593 and closing completed work
