### ISSUE TITLE
Retire va.gov-content repo

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14712]
### User Story or Problem Statement

Problem: How can we retire the [va.gov-content](https://github.com/department-of-veterans-affairs/vagov-content/tree/main) repo while maintaining its currently used functionality?

### Affected users and stakeholders

* Editor(s) of existing content pages in va.gov-content
* Analytics team
* Content/IA team (404 strategy, potentially)

## Acceptance Criteria
- [ ] All currently used pages in va.gov-content are identified
- [ ] All functionality in the above pages is moved to other systems

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`
