### ISSUE TITLE
User/Access request form MVP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1472]
### Affected users and stakeholders

* New users
* People who are requesting accounts for others

## Acceptance Criteria

- [ ] This form implementation should not preclude the possibility of using these form submissions to automate the assignment of users, roles, and sections
- [ ] Identify an MVP user group and announce to them (eg various POs and PMs from product teams)
- [ ] Redirect people who create their own CMS account with PIV to this form  
- [ ] Sensor for form success identified 

Not in scope
- [ ] Link added to homepage (possibly in #1269)
- [ ] People with PIVs who log in to CMS, without already having an account. 
- [ ] Enterprise user governance long term strategy and service design

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by EWashb** [comment]
This is no longer needed. We have a process for requesting access for both those with PIV and without
