### ISSUE TITLE
[Epic] [AP] Global front-end elements

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14739]
## Requirements & Goals
All VA.gov pages have a header and footer that provide menus and other info for the page. These need to be implemented in Next Build to be visually and functionally equivalent to what currently exists.

The header and footer are largely the same on all pages, with some exceptions. This epic contains the work necessary to implement these components.

In addition to the menus and visual aspect of the header/footer, the header in particular is responsible for loading a page's Javascript and CSS. This 'hidden' functionality is considered part of this epic with the following exceptions:

* Implementation of analytics will be its own epic: #14455 

```[tasklist]
### How will we know we've achieved our goals?
- [x] The header and footer contained in pages generated by Next.js is functionally and visually equivalent to what is currently generated by Content Build
```

## Work and Supporting Info
```[tasklist]
### Tickets
```

```[tasklist]
### Related work (not epic work)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15491
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15510
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15512
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15511
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14996
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14875
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15489
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14779
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15063
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14802
```
