### ISSUE TITLE
[Epic] [AP] Next Build & Lovell

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#14743]
## Description
VA.gov has a lot of functionality to handle the special case of Lovell, which is both a VA and Tricare (active military personnel) medical center.

This epic is intended to capture all functionality needed to correctly render pages for the Lovell cases.

Note that the epic does not require *implementing* all Lovell-specific functionality, only that it is identified and that what is needed for our first Milestone (News Stories) is in place.

## Acceptance Criteria
- [x] Lovell-specific logic throughout Content Build is identified and documented
- [x] Rethink this TIM: Any Lovell-specific data provided by GraphQL is also available via JSON:API
- [x] Functionality needed to complete the News Stories pages is in place

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [x] `Accelerated Publishing`

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14745
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15825
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15826
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14746
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14744
```

**Comment by timcosgrove** [comment]
In practice it is working better to work on Lovell issues as they arise for particular content types or situations. Closing this epic.
