### ISSUE TITLE
Merge Lighthouse V1 related work, after Lighthouse V1 launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14813]
## Description

Prep work for Lighthouse V1 is in an integration branch -- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/13464. This should merge after Lighthouse V1 launch, estimated 8/24.

## Tasks

- [x] Integration branch is merged to main
- [x] Force push is complete
- [x] Data is verified in prod
- [x] Defects are filed for any follow up work required

## ACs

- [ ] Services are being sent to Lighthouse V1

**Comment by omahane** [comment]
I'm in the middle of doing the "force push" now:
https://dsva.slack.com/archives/C02BTJTDFTN/p1692208312102169

**Comment by omahane** [comment]
Per the meeting with Lighthouse and Facilities on 28 Aug 2023. This work is complete.
