### ISSUE TITLE
Deprecate Outreach Hub / Outreach Materials, preserve Outreach Events only

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#14835]
## Background
Outreach Materials are being migrated to a new OPIA / VEO platform (tentative name: Discover). 

### User Story or Problem Statement

Need these.

### Outcomes
We will deprecate: 
* Outreach Materials: https://www.va.gov/outreach-and-events/outreach-materials 
     * Publications content - https://prod.cms.va.gov/admin/content?title=&type=outreach_asset&moderation_state=All&owner=All
       * Data migration?
     * Publications content type
       * BE code, any Drupal config
       * FE templates
* Outreach and Events path: https://www.va.gov/outreach-and-events/

### IA concerns
* Outreach Events path will change from https://www.va.gov/outreach-and-events/events/ to https://www.va.gov/events/
    * Requires IA review 
* Outreach materials – Redirect (destination?) - either choose.va.gov top-level, or deep-link to video gallery or “Outreach materials” tab

### Tasks / Steps
- **Product:** 
  - Audit
  - Look at traffic/GA to see if detailed redirects will be needed
  - Content IA intake ticket for review / approval
  - Change Management (KB article audit for changes / archiving, review / plan any comms required for Editors with OPIA / VEO and Dave)
- **FE**
  - Change outreach-and-events path to /events, including breadcrumbs
  - Outreach hub / landing (Publication listing): archive - https://prod.cms.va.gov/outreach-and-events/outreach-materials
  - Move /outreach-and-events/events template / content to /events
  - Footer: change “VA outreach materials” to point to new subdomain on Choose
  - Footer: “VA outreach events” point to /events, and change copy to Events
- **Drupal** 
  - Publication content within Outreach Hub Section: Archive nodes  - https://prod.cms.va.gov/admin/content?title=&type=outreach_asset&moderation_state=All&owner=7 

### Status 8/17/23
- Keeping the hub til end of August (probably later)
- Outreach will stay on VA.gov until that ships.
- Bronwyn to participate in usability session re: how effective the docs are for the current product. 
- May result in KB article updates for PW.

### Affected users and stakeholders

* CMS editors of Outreach Materials
* Developers of Public Websites team

## Assumptions
* Outreach Materials do not drive meaningful traffic to other areas of VA.gov, and deprecation will not impact metrics for other products.
* Redirects to new OPIA / VEO "Discover" product will be sufficient for Veteran purposes to access Outreach Materials information.

(How will these assumptions be validated?)

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [x] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by jilladams** [comment]
Discover is not a thing, has been replaced by "Choose VA" (a WP site for OPIA). Still not sure what the destiny is for Outreach materials or status of that project build.

**Comment by FranECross** [comment]
Moving into Admin column and assigning to me so that I can ask Michelle M about this.

**Comment by jilladams** [comment]
@FranECross timely! this just came up on the VHA Digital Media call this week. My comment above was from that discussion: basically, the platform we expected to take the Outreach Materials functionality has morphed, and we don't know the next steps here until Michelle can talk to OPIA about whether or not they've accounted for OM in their product / build.

**Comment by FranECross** [comment]
Ticket transferred to CMS.
