### ISSUE TITLE
UX review of VBA Service Region content type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14845]
## Description or Additional Context 
Review VBA [Service Region implementation](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14705)

Refer to [VBA Content Specs XLS in Sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideFacilitiesTeam/EVVWpQp091ZEvI2n-9iyvTQBGYFZjxlVPN3Zfyz-Eh6Oyg?e=NVvsCc) -- Legend tab explains color highlighting

## Tasks
- [x] Review editorial interface components for usability and compliance with CMS design system
- [x] Review all text (help text, field labels, tool tips, error messages) for UX writing best practices
- [x] Consider broader user flow(s) for the task(s) and make sure this logically integrates/references other Drupal entities
- [x] Consult with Engineering to understand what technical limitations may prevent updating interface
- [x] Document any recommendations for improving the interface via Figma

## Acceptance Criteria
- [x] Recommendations are documented [in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)
- [x] Recommendations are shared with PM/PO for review and taking to CMS collab cycle

**Comment by laflannery** [comment]
@thejordanwood can you ping me when you are done with this so I can add [my notes from my ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14856#issuecomment-1702868021) into your Figma?

**Comment by thejordanwood** [comment]
@laflannery I've created [a Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1) for this and commented some of my recommendations in there if you want to review. I looked at your ticket and made some updates you suggested as well.

**Comment by laflannery** [comment]
Thanks @thejordanwood! I just added all my comments. I have one that is off to the left with no real connection to the mockup because you can't see what I'm commenting on in your designs. I also don't think I can add stuff to Figma so here is a screen shot of what I'm talking about and maybe you can add that in there?
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/67e4a885-6dd8-4d2c-b5d1-f0b85d810738)

Let me know if you have no idea what I'm referring to.

**Comment by thejordanwood** [comment]
@laflannery I added that screenshot into the Figma file!

**Comment by thejordanwood** [comment]
**End of sprint update:** 

@xiongjaneg For the most part, the design work is finished for this and is show in [this Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=puNAatVKdroxMF0y-1). This is what's still outstanding:

1. Street address label - In the "Service location" section of the design, there's a checkbox with a "Street address" label over it. There's been some discussion on removing this label, but the content for the checkbox may need to be made clearer. 
2. Regional service description field - This was left out of the original implementation in the CMS because there had been conflicting guidance of being a plain text field, but the help text recommends bullets. We'll need to discuss this with Dave P. whenever he gets back. 
3. Add address button - This is in the "Service location" section and currently allows editors to add different content blocks to this section, which shouldn't be allowed. @swirtSJW is looking into this behavior.

**Comment by thejordanwood** [comment]
> Street address label - In the "Service location" section of the design, there's a checkbox with a "Street address" label over it. There's been some discussion on removing this label, but the content for the checkbox may need to be made clearer.

We're going to remove the label on this. I've made this change to the Figma file. @xiongjaneg

**Comment by xiongjaneg** [comment]
Recommendations reviewed, closing
