### ISSUE TITLE
UX review of VBA menu

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14843]
## Description or Additional Context 
Review implementation for VBA menu in #14696 
Refer to [VBA Content Specs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13096)

### Design

[Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)

## Tasks
- [ ] Review editorial interface components for usability and compliance with CMS design system
- [ ] Review all text (help text, field labels, tool tips, error messages) for UX writing best practices
- [ ] Consider broader user flow(s) for the task(s) and make sure this logically integrates/references other Drupal entities
- [ ] Consult with Engineering to understand what technical limitations may prevent updating interface
- [ ] Document any recommendations for improving the interface

## Acceptance Criteria

- [ ] Recommendations are documented [in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)
- [ ] Recommendations are shared with PM/PO for review and taken to CMS collab cycle

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by davidmpickett** [comment]
Closing as not planned since we discussed that UX work should precede development work in the future
