### ISSUE TITLE
UX Review of VBA Centralized Content implementation

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14889]
## User Story or Problem Statement
Review implementation in #14699 -- this is Centralized Content, as it pertains to VBA. 
* Centralized Content content type -- not a candidate for this review
* The Centralized Content node instance where Natl editors will edit info -- https://prod.cms.va.gov/centralized-content/national-vba-facilities-content
* The VBA Facility content type where that node content is pulled in -- e.g. https://prod.cms.va.gov/vba-facilities/locations/fort-harrison-va-regional-benefit-satellite-office-at-david-j-thatcher-va-clinic

Refer to:
-  [VBA Content Specs](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13096)
- #13799 
- #14978 

### Design

[Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)

[Sketch annotations](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/23336061-721C-400F-BEAD-0DED48F3A8EF/canvas) showing the spec

## Tasks
- [x] Review editorial interface components for usability and compliance with CMS design system
- [x] Review all text (help text, field labels, tool tips, error messages) for UX writing best practices
- [x] Consider broader user flow(s) for the task(s) and make sure this logically integrates/references other Drupal entities
- [ ] Consult with Engineering to understand what technical limitations may prevent updating interface
- [ ] Document any recommendations for improving the interface

## Acceptance Criteria

- [x] Recommendations are documented [in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)
- [x] Recommendations are shared with PM/PO for review and taken to CMS collab cycle

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by jilladams** [comment]
@thejordanwood This ticket is now unblocked, and we are inclined to pull it into S95. Can you confirm if the 5 estimate was based on something specific about this issue?

**Comment by thejordanwood** [comment]
@jilladams I'm not sure how past Jordan came up with the 5 estimate. 

I just asked @davidmpickett about the spec for this and he pointed me to the annotations he did in [the Sketch file](https://www.sketch.com/s/891d33ae-152d-471c-ab5d-9aedf89cf6ff/p/23336061-721C-400F-BEAD-0DED48F3A8EF/canvas) and [a comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14699#issuecomment-1743679540) with more detail in the #14699 ticket. After looking those over, I still feel comfortable with pointing this at a 5. 

I've been pointing most of the content spec tickets at a 5 to allow time for feedback and revisions. I suspect we'll need this time for the centralized content because it can get a bit confusing.

**Comment by laflannery** [comment]
@thejordanwood I have a rather large comment in my [accessibility ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14899#issuecomment-1759734404). I'm not sure if any of this applies to you or helps you in any way because honestly I was pretty confused about this scope of this but I at least wanted to make you aware of it.

**Comment by thejordanwood** [comment]
I started the UX review on the _VBA Centralized Content_ page in [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=166%3A798&mode=design&t=st3bxMjN7F3wdPqa-1). This review is split between the admin view and the national editor view. 

**Note:** Since this review didn't require any design changes, I didn't create a current/new artboard comparison like I have in past UX reviews. Instead, I took screenshots of the current experience and left comments next to the text I think should change.

**Comment by thejordanwood** [comment]
@xiongjaneg Here are the 2 changes that we may need CMS collab cycle tickets for:

1. How we display characters remaining on text fields - For consistency, these should say "xx characters remaining." This is how it's displayed in the CMS design system. This can be seen [next to this comment](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh?node-id=167:819&mode=design#590435939) in the Figma file. 
2. Phone number fields - Help text changes would impact multiple places. This applies to the Type, Phone number, Extension number, and Label fields. Suggested changes can be seen starting [with this comment.](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh?node-id=180:806&mode=design#590436716)

**Comment by xiongjaneg** [comment]
scheduled meeting with CMS Team and Facilities product folks to discuss ^ on Oct. 30
