### ISSUE TITLE
UX Review of updated Service Location paragraph type

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#14890]
## User Story or Problem Statement

Review updated Service Location paragraph type for VBA in #14704 

To create a VBA Facility service in the integration branch: https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/node/add/vba_facility_service
- This is used in the following content types:
    - VAMC non-clinical service
    - VAMC facility service
    - VBA service region
    - VBA facility service
- Use the content editor role

### Design

[Design System link](https://www.figma.com/files/920496649063276587/project/53099542/CMS-Design-System-Library?fuid=1118989037713679864)

[Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)

## Tasks
- [x] Review editorial interface components for usability and compliance with CMS design system
- [x] Review all text (help text, field labels, tool tips, error messages) for UX writing best practices
- [x] Consider broader user flow(s) for the task(s) and make sure this logically integrates/references other Drupal entities
- [x] Consult with Engineering to understand what technical limitations may prevent updating interface
- [x] Document any recommendations for improving the interface

## Acceptance Criteria

- [x] Recommendations are documented and updated [in Figma](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=0%3A1&mode=design&t=HMbWiEC8fQQTUEiu-1)
- [x] Recommendations are shared with PM/PO for review and taken to CMS collab cycle

## Team
Please check the team(s) that will do this work.

- [ ] CMS Team
- [ ] Public Websites
- [X] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by xiongjaneg** [comment]
Copy ACs from Service Region

**Comment by davidmpickett** [comment]
Note that some recommendations for Service Location have already been made in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14845

**Comment by thejordanwood** [comment]
@davidmpickett Thanks for pointing this out. I do have the Service Location section mocked up in [the Figma file](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=100%3A481&mode=design&t=j3jWKWMmhqxHzgOG-1), but it looks like I'm missing some of the suggestions [in your spreadsheet](https://docs.google.com/spreadsheets/d/1kulQsfmJP_qVrb-MRkKsEVYkdwkNxNEa/edit?usp=sharing&ouid=109515556316253843471&rtpof=true&sd=true). Specifically the suggestion for better help text to describe what Service Locations are and the addition of the delivery method field. 

I'm now realizing that perhaps I should have completed this ticket first, before completing work for Service Regions and other content types that contain the Service Location section.

**Comment by davidmpickett** [comment]
> I'm now realizing that perhaps I should have completed this ticket first, before completing work for Service Regions and other content types that contain the Service Location section.

This is what I wanted to apologize for today in UX refinement. I realize I didn't set you and @laflannery up for success by pointing that y'all should essentially ignore the Service Location part of the other content types when reviewing them because we were gonna have to look at it again after dev team made the changes I already suggested.

Looking forward to having lots on hard conversations about Service Location in the next couple sprints 😅

**Comment by thejordanwood** [comment]
@davidmpickett No need to apologize! We've suggested some improvements to it already and I now have it as a design I can reuse in my Figma file when we make it to this ticket.

**Comment by jilladams** [comment]
Since we expect Alexis to have some capacity in S95, proposing she and Jordan pair on this ticket as an intro to Drupal spec business.

**Comment by thejordanwood** [comment]
A note for later: We need to decide how many service locations to allow (3, unlimited, etc.).

Here's a [relevant Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1696542532134509) referencing this.

**Comment by ALogsdon3** [comment]
I've made comments and help text suggestions in the Figma file and alerted @thejordanwood in Slack.

**Comment by davidmpickett** [comment]
Uploading a slice of the VBA Services sheet from sharepoint for conversation about Service Delivery Options 
[Service Delivery Options.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13244663/Service.Delivery.Options.xlsx)

**Comment by thejordanwood** [comment]
**Pre Out of Office Update:**

There are still some questions [in this slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1698959066016179) about how best to show VBA service options. I've updated [the Figma mockup](https://www.figma.com/file/aKdT4weNNthDxb3r6MolEh/VBA-Content-Specs?type=design&node-id=208%3A714&mode=design&t=5fQb7ZvIuaXiLhvg-1) with the latest suggestion. 

cc: @jilladams @xiongjaneg

**Comment by xiongjaneg** [comment]
rolling over to sprint 97 for CMS collab cycle meeting

**Comment by thejordanwood** [comment]
@xiongjaneg Since the CMS collab cycle meeting was last week, is this ready to close?

**Comment by xiongjaneg** [comment]
@thejordanwood Yes, thank you, please close. If you have any questions about collab cycle meeting, please async or meet with Dave or me.
