### ISSUE TITLE
Create a PagerDuty Incident Trigger workflow in Slack for general CMS issues

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14920]
## Description

Last night (08/22), there was an issue where saves of facility statuses and services content led to exceptions for exceeding the lock timeout. This interfered at least somewhat with normal editor operations but caused substantial issues synchronizing facility information to Lighthouse.

I was not on-call for PagerDuty last night, but Swirt tagged me. Since I don't have alerts on my phone for Slack tags (otherwise it'd be even harder to get out of the office and stay out), I was unaware that I was being summoned 🧞‍♂️ until later.  

An appropriate course of action in this case would have been to trigger a PagerDuty incident. Unfortunately, none of the personnel responding to the issue had PagerDuty licenses, and consequently they would not be able to trigger an incident. Even if they had licenses, the process is sufficiently complex that it probably would have required documentation and resulted in further delays resolving the issue.

The best thing we can do is likely to create an Incident Trigger Slack Workflow, as documented [here](https://support.pagerduty.com/docs/slack-user-guide#create-an-incident-trigger-slack-workflow). This will allow engineers and other personnel without PagerDuty licenses to trigger CMS incidents.

## Tasks

- [ ] Who controls our ability to create workflows in DSVA Slack?
- [ ] Do we need to ask for permission before we can do this?
- [ ] How complicated is this process?

## Acceptance Criteria

- [ ] Engineers without PagerDuty licenses can trigger CMS incidents from within Slack.
- [ ] Process for triggering CMS incidents from within Slack is documented in READMES.

**Comment by ndouglas** [comment]
The documentation for this is completely outdated and does not match the current Slack workflow UI.

I was able to create a workflow, but it only seems to work for users with PagerDuty accounts 😩 

I've reached out via PD forums, PD documentation, and PD technical support to try to figure out why this is the case.

**Comment by EWashb** [comment]
We have completed this exact thing on Platform for PD Incident Triggers for Platform support. Are you able to see that/use that existing workflow now? FYSA, I am a Slack admin and can work with you to either create or approve what you create.

**Comment by ndouglas** [comment]
@EWashb Using `/support`? That could work. Unfortunately, [it doesn't seem like the official integration will](https://community.pagerduty.com/forum/t/how-to-trigger-an-incident-workflow-from-slack/4648/3) 😩

**Comment by EWashb** [comment]
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/90111970/d813aa02-4fc5-4f42-a6db-36eec7435326)

These are the ones I was thinking of. Are any of these available to you? @ndouglas

**Comment by ndouglas** [comment]
@EWashb Unfortunately, those require a linked PD seat to trigger an incident.

**Comment by EWashb** [comment]
Darn. We also are working on declaring incidents through `/datadog incident` for the reasons you stated about the limits on PD seats. Either way, when you start this I can approve any workflows you create, just give me a head's up they are coming through.

**Comment by ndouglas** [comment]
I can create workflows, they just don't do anything useful 😂
