### ISSUE TITLE
Create general incident response document for CMS issues.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14923]
## Description

Last night (08/22), there was an issue on production that required active response from available engineers.

It occurred to me that there is not actually any suitable documentation for initial incident response with a production CMS instance. I should create this.

## Things to Document
- [ ] Trigger a PagerDuty incident (see #14920).
- [ ] Until #14920 is resolved, or if it needs to be escalated further, just call or text me, my phone number is in my Slack profile.
- [ ] Notify Helpdesk to make sure they feel safe and equipped to handle tickets from users.
- [ ] Notify POs/PMs/DMs if the issue affects users. Recommend OOB deploy if appropriate.
- [ ] Useful documents for reference (see #14921, #14922, OOB deploy documentation, etc).
- [ ] Progress notifications to Helpdesk.
- [ ] Cautions, e.g. "don't restart Apache willy-nilly, this can cause it to fail healthchecks and be marked unhealthy" and what to do if such issues arise.
- [ ] Post-resolution notifications to Helpdesk.
- [ ] Post-resolution notifications to POs/PMs/DMs.
- [ ] Postmortem process.

## Acceptance Criteria
- [ ] An incident response document containing the information above is created within the repository.
- [ ] The existence of this document is socialized and linked where appropriate.
- [ ] Socialize the difference between an incident and a defect.

**Comment by EWashb** [comment]
@ndouglas, you probably don't know this, but user support created some documentation around major incident response. I wonder if you might find some of that useful in your documentation efforts. @TroyA6 has a lot of context and can likely point you in the right direction if you wanna check out what they have! I would prefer whatever we do for our MIM to live in the repo anyway.
