### ISSUE TITLE
PW Sprint Plan 92

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#14930]
Google doc for actual editing: https://docs.google.com/document/d/1S70Em6MC2LTS0MCDsUXnneJxfrJ0vaTin7kf2zqufA4/edit?usp=sharing

## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic #9626](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626)

🟢 Product:
- [ ] #14965 (0) - Product
- [ ] (Analytics team delay: several more sprints from 8/1) #13480 - Product - **blocked** on Plat Analytics implementation

🟡 Engineering:
- [ ] #14964 (1) - FE
- [ ] #13759 (8) - BE
- [ ] (stretch) #13760 () - BE
- [ ] (stretch) #13761 () - BE

### 2. PACT Act Wizard [epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢  
- [ ] (carryover from S90) #14447 (8) - Research 🎯
- [ ] (carryover; paused in s91) #13324 () - Research
- [ ] (stretch) #14749 (5) - Research
- [ ] #14951 (5) - Design

Engineering:
- [ ] (stretch) #15001 (needs) - FE
- [ ] (stretch) #14931 (8) - FE
- [ ] (stretch) #14932 (5) - FE
- [ ] (stretch) #14939 (5) - FE

### 4. Expand Q&A Reusability [epic #10780](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡
- [ ] (carryover from s91?) #14790 (8) - Design
- [ ] (stretch, blocked on 14790; KB) #14633 (needs) - BE/PM/DM

### 5. Benefit Content Model Hardening [epic #9628](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
- [ ] (waiting to delete zoom recordings) #14582 (0) - Product (hallway)
- [ ] #14817 (5) - BE+FE
- [ ] #14815 (3) - Design
- [ ] (blocked on 14815) #14860 (needs) - BE (View screen enhancements)
- [ ] (stretch) #13142 (5) - BE
- [ ] (stretch) #14534 (needs) - BE

### Mobile App Promotional Banners [epic #13482](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482) 🟢
- [ ] (carryover from s91) #14179 (0) - Product
- [ ] #14967 (needs) - FE - launch 🎯
- [ ] (stretch) #14288 (0) - Product

### Post-MVP Homepage 🟡  
- [x] #14960 (1) - FE

### Cerner API deprecation support 🔴  
- [x] (carryover from s91?) #9307 (5) - FE 

# Other PW Priorities
## Prioritized for this sprint
(Note: may be duplicated in sections below)
- [ ] (carryover from s91) #14788 (8) - Design 🎯
- [x] #14819 (5) - FE - search.gov error triage
- [x] #13222 (8) - FE
- [x] (stretch) #13137 (3) - FE
- [ ] #14861 (1) - FE
- [ ] (do when greenlit by CAIA) #15002 (1) - TIME SENSITIVE blocked on greenlight, timing tbd input on ticket
- [ ] (awaiting greenlight) #15012 -  TIME SENSITIVE blocked on greenlight, timing tbd input on ticket
- [ ] (stretch) #14793 (2) - BE
- [ ] (stretch) #11233 - BE
- [ ] (stretch) #14767 (3) - FE
- [ ] (stretch) #11854 (5) - FE
- [ ] (stretch; small item if it doesn’t slow other stuff down)  #14904 (2) - BE
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #12933 (5) - BE

## Backlog of non-quarter priorities (for easy access)
Tech debt, Defects, Drupal 10 upgrade
- [ ] (stretch) #14767 (needs) - FE

Cross-repo dependencies post-mortem

Other priorities
- [ ] (stretch) #13329 (3) - Design - Jordan dependency
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #11230 (3) - BE

### Content / IA priorities (CAIA)
- [ ] #15002 - TIME SENSITIVE blocked on greenlight, timing tbd input on ticket
- [ ] #15012 -  TIME SENSITIVE blocked on greenlight, timing tbd input on ticket
- [ ] va.gov-team 58142 - **blocked**; CLP-related

### Portfolio and pipeline - [epic](#7599)
- [ ] #12791 (needs) - Design
- [ ] (stretch, low-prio) #12601 (needs) - Design

Epic of upcoming redirects not yet in our board:
Team repo # 53921

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
- [ ] (stretch) #13137 (needs_refining) - FE
- [ ] (stretch) #14219 (need_refining) - FE - mtg w/Appointment team 8/3

### Product health/dashboard backlog
- [ ] #15003 (0) - Product

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
- Public Websites supporting MHV on VA.gov – Update the secure messaging widget to point to MHVonVAgov rather than Cerner / VistA. Not yet actionable. Sitewide Content input: There will also be content tweaks within the widget. Timing unknown but won't be sudden.

**Comment by wesrowe** [comment]
Candidates for refining in planning:
FE: 
- #15001 
BE: 
- #11233

**Comment by jilladams** [comment]
Randi / Chris
* PACT test plan
* PACT front-end work - alongside 
* Redirects - blocked on approval

Christia
* KB article for Q&A

Daniel
* Oracle DB - VES
* CSVs - VES

Jordan - 
[CMS Design: Enable Facility Editors to publish events to the National Outreach Calendar #14788](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14788) - 5pts left in S92
[CMS Design: Assess how CLP design impacts other content types from UX and Engineering perspectives and recommend new state #14790](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14790) - 2pts for S92

[PAW: Design checkbox and radio button validation experiences for multi-select questions #14951](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14951) - 5pts
[Design: Magichead help text and labels in View and Edit modes #14815](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14815) - 3pts

Cindy - PACT Act
