### ISSUE TITLE
Implement epic text-field migration Drush commands.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#14997]
## Description

If I'm going to do this thing, I'm going to want better control than just running `drush updb` repeatedly.

## Goals

- [x] Report time usage accurately, regardless of failure.
- [x] Report peak memory usage accurately, regardless of failure.
- [x] Give good progress updates, whether with batching or not.

## Tasks

- [x] Drush command to migrate a specific field on a specific content type.
- [x] Drush command to rollback the migration of that specific field on that specific content type.
- [x] Drush command to verify a migration completed successfully (how?).
- [x] Drush command to find (if possible) fields that haven't been migrated yet.

## Acceptance Criteria

- [x] Drush commands exist in a stub form, ready to be hooked up to whatever contains the core logic (see #13699).
