### ISSUE TITLE
Post API release 2.0.0

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1499]
[Post API](https://www.drupal.org/project/issues/post_api) is ready for a stable release.

### Affected users and stakeholders

* CMS administrators who monitor and maintain Facility data sync to Lighthouse API in Drupal.

## Acceptance Criteria

- [x] The following features and their dependencies are implemented:
   - [x]  https://www.drupal.org/project/post_api/issues/3127941
   - [x]  https://www.drupal.org/project/post_api/issues/3127328
   - [x]  https://www.drupal.org/project/post_api/issues/3127573
   - [x] https://www.drupal.org/project/post_api/issues/3126954
   - [x] https://www.drupal.org/project/post_api/issues/3127173
   
- [x]  Post API has stable release 2.0.0
- [x]  Post API version in https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/composer.json is updated to ^2.0.0

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)
