### ISSUE TITLE
KB: Migrate CLP "product guide" content from PDF to KB article

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15003]
**STATUS: CONVERTED TO EPIC**
- Don't want to lift-and-shift content – 
- Instead, come up with approach, break into issues 

The PDF in question: https://prod.cms.va.gov/sites/default/files/2021-12/VA.gov_.Campaign.Landing.Page_Governance_Product_Guide_11302021.pdf

### User story

**AS A** CLP Editor
**I WANT** to find CLP documentation in the KB
**SO THAT** it's easier to find and accessible.

**AS A** Content Editor
**I WANT** the knowledge base (KB) article on Campaign Landing Pages (CLPs) to be updated for reusable Q&As
**SO THAT** I have accurate documentation to follow.

### Engineering notes / background

Product guide location – go to CMS help/KB area, product guide PDFs are linked at bottom of page.
- https://prod.cms.va.gov/help - reach by clicking "Knowledge Base" at top of UI
- <img width="508" alt="Screenshot 2023-08-28 at 4 58 10 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/4054752/94734cea-69cd-4bc0-8b7a-c2ef556e7d64">

Can we find the source file for the original PDF? No. 

### Other relevant info
Most important article to begin with is "How do I get a CLP created?". We have a Public Websites runbook here: 
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#runbook-for-clp-creation, that we can use as a start for the narrative for explaining this to editors.

## Acceptance criteria

- **Anticipate multiple KB articles**

https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages
- [ ] ??? What exactly needs to make it into the KB? 
- [ ] [Reusable Q&As KB](https://prod.cms.va.gov/help/cms-basics/how-to-create-and-reuse-qas) (draft as of 9/11) is linked to from CLP KB 
  - [ ] FAQs language in existing KB is revised to make sense with new Q&A structure
- [ ] New KB content is drafted for "How do I request a Campaign Landing Page?" ([#808791](https://prod.cms.va.gov/node/15138/revisions) is created)
- [ ] BE: draft a revision to change the content
- [ ] [open a ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/new?assignees=&labels=Knowledge+Base%2C+Needs+refining&projects=&template=knowledge-base-article-review.md&title=Review+of+new+or+updated+KB+article+%3A+%3Cinsert+topic+here%3E) for Help Desk to review

**Comment by jilladams** [comment]
Some newer thoughts from DaveC via DM with me & Wes: https://dsva.slack.com/archives/C03ES2LMNTH/p1694467019674749?thread_ts=1694466542.940769&cid=C03ES2LMNTH

**Comment by mmiddaugh** [comment]
@FranECross we may want to handle this with future enhancement work

**Comment by mmiddaugh** [comment]
This is not needed - there are KB articles for the CLP:

- [How to request a campaign landing page](https://prod.cms.va.gov/how-to-request-a-campaign-landing-page)
- [How to create a new Campaign Landing Page](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-create-a-new-campaign-landing-page)
- [How to edit and maintain a Campaign Landing Page](https://prod.cms.va.gov/help/campaign-landing-pages/how-to-edit-and-maintain-a-campaign-landing-page)
- [Campaign Landing Pages](https://prod.cms.va.gov/help/campaign-landing-pages)
