### ISSUE TITLE
Review and respond to questions from Lighthouse regarding sandbox data

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15027]
## Description

To support the ongoing conversation with Lighthouse team regarding sandbox data, our team has been asked to review and respond to questions below. 

**Sandbox Data for CMS team**

CMS needs to be able to see a push of data from lower environments, revealed in lower environments
- The CMS uses it to pull and push data on lower environments 

> Question from Andrew: Can you provide examples to illustrate? Do you mean making data available to CMS from data sources on the lowers, which CMS then stores locally?

The lower environments of va.gov  pull data from Sandbox
> Question from Andrew: Does Va.gov=facility locater?

The behavior of Facility Locator pulls data and points to pages generated by the CMS
- For the CMS team, it is important for testing that there is parity between sandbox FAPI, CMS and FE. 
> Question from Andrew: Are CMS and FE (assuming this means front-end/va.gov) both consumers of the Facilities API? If so, what's causing the lack of parity between CMS and FE, if they both use the API to get facility data?

If CMS team is pushing data from CMS lower environments to staging FAPI, they need to be able to see it on FE lower environments. 
- This is needed for new feature development, debugging, and demonstration purposes.
> Question from Andrew: FAPI is a read-only API. Not clear what is meant by CMS pushing data to FAPI.

If the data is synthetic, then CMS team lower environments will be using synthetic data, which makes it hard for them to test or develop against an ongoing issue. Example:
- When CMS was rolling out Covid statuses, they needed the ability to test that when a facility in the local/dev environment pushed the first of any Covid status ever pushed, they could see it and act on it on the consumer of the API (the facility locator).  
- As it was, the data CMS pushed to sandbox was so far out of sync timewise with what was on prod that we were unable to test some cases and ended up with a very broken FE needing an out of band deployment to fix.

Unlike most consumers of the Facility API, CMS is both a provider and a consumer and need to be able to test full cycle of new data push to new data read on lower environments.

For the CMS team, a synthetic data source is also a good thing to have but is not a replacement for a production-like interactive data source.

## Tasks
- [x] Review Lighthouse sandbox data above
- [x] Respond to indicated questions
- [x] Provide any additional corrections/feedback 

## ACs

- [x] Review is provided in comments in this issue and made available to Lighthouse

**Comment by swirtSJW** [comment]
> CMS needs to be able to see a push of data from lower environments, revealed in lower environments
> 
> The CMS uses it to pull and push data on lower environments
> Question from Andrew: Can you provide examples to illustrate? Do you mean making data available to CMS from data sources on the lowers, which CMS then stores locally?

Example from recent history:
The CMS had to push new data related to Covid protection levels.  We had added the code on CMS lower environments and **pushed** it to Lighthouse sandbox.  Developers on the lower environments of the facility locator (VA.gov FE) needed to build and test the new feature by **pulling** from lighthouse sandbox.  For complete development we needed to be able to push and pull the same data from lighthouse sandbox. If we were not able to both push and pull from the same location, this effort would have been much more difficult.  

During that time, lighthouse sandbox was rebuilt, which meant the developers of the Facility locator lost the ability to get the data they needed. It was also a problem that appeared during this example that lighthouse prod data could not be synced down to lighthouse sandbox, and the only way the data sourced from the cms  could only be restored to sandbox by pushing all the entries again.

**Comment by swirtSJW** [comment]
> The lower environments of va.gov pull data from Sandbox
> Question from Andrew: Does Va.gov=facility locater?

VA.gov pulls from the facilty API for the facility locator AND several other pages on the site. (facility statuses on operating status pages for example)

**Comment by swirtSJW** [comment]
> For the CMS team, it is important for testing that there is parity between sandbox FAPI, CMS and FE.
>> Question from Andrew: Are CMS and FE (assuming this means front-end/va.gov) both consumers of the Facilities API? If so, what's causing the lack of parity between CMS and FE, if they both use the API to get facility data?

The lack of parity usually comes from Lighthouse sandbox not having the same data as production.  My understanding is that when sandbox is rebuilt, it pulls data from all of its sources in one shot.  The problem is it never pulls from the CMS.  All CMS data is push only and we are now to a set of data payload that takes hours for us to push it all if/when sandbox is rebuilt.
Also when sandbox is set up to support new code or data, it blocks any other development from happening.  So we get a development logjam because there are no other lower environments to use.

**Comment by swirtSJW** [comment]
> f CMS team is pushing data from CMS lower environments to staging FAPI, they need to be able to see it on FE lower environments.
This is needed for new feature development, debugging, and demonstration purposes.
>>Question from Andrew: FAPI is a read-only API. Not clear what is meant by CMS pushing data to FAPI.

The cms provides data to two different overlays that feed the FAPI
1. CMS pushes facility operating statuses for 2,100+ facilities (Health care facilities, Vet Centers, VBAs, and cemetaries)
2. CMS pushes ~18,000 facility service descriptions.

These are dynamic pushes that typically push when something changes in the CMS on a facility by facility or service by service basis.

**Comment by jilladams** [comment]
@swirtSJW @xiongjaneg per the ACs, this ticket can be considered complete, and we just need to follow up with Lighthouse for next steps. Steve, I think you can prob feel free to close this.

I added a note to the LH Trello board in this card, pointing back to these comments: https://trello.com/c/OhbJPLp6/7-data-sync-for-lower-environments-and-synthetics
