### ISSUE TITLE
PW Sprint 93 plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15078]
Google doc for actual editing: https://docs.google.com/document/d/104Di4WcUAR8EtXbyZvmNrZ8d20RiE7ZLlwJ66jG_ohM/edit?usp=sharing

## Q3 Priorities
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic #9626](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9626) 🟢
[I.L. Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3ODcwMQ,Z2lkOi8vcmFwdG9yL0VwaWMvOTU0NTg5&filterLogic=any&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzE3)

### 2. PACT Act Wizard [epic #12170](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170) 🟢 
[PAW Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAyOTA1Mw&filterLogic=all&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzE4) 

### 3. USA Header/Footer [epic #14078](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14078) 🟡
[FedHeadFoot Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3NzMzMg&filterLogic=all&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zNDgx)
TODO: Create Research ticket backlog

### 4. Expand Q&A Reusability [epic #10780](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟡
[Q&A Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvOTk0MTkz&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzIw)

### 5. Benefit Taxonomy / Content Model Hardening [epic #9628](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
[Benefit Taxonomy / Magichead Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3MDczOQ,Z2lkOi8vcmFwdG9yL0VwaWMvOTU0NjA0&filterLogic=any&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzIx)

### Mobile App Promotional Banners [epic #13482](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13482) 🟢
- [ ] (stretch) #14288 (0) - Product

## Q2 Finish-up

# Other PW Priorities
## Prioritized for this sprint
(Note: may be duplicated in sections below)
- [ ] #15195 (needs) - FE/BE - High prio for 9/30 PACT deadline 🎯
- [ ] (stretch) #12978 (needs) - also monitoring of Forms, needed in addition?
- [ ] (carryover from s92) #14819 (5) - FE (Randi)
- [ ] (carryover from s92) #14788 (5) - Design
- [ ] (carryover from s92) #11230 (3) - BE
- [ ] (carryover from s92) #14793 (3) - BE
- [ ] (carryover from s92) #14870 (1) - FE (Chris)
- [ ] #11255 (needs) - FE - priority for monitoring: injected head/foot
- [ ] #13329 (3) - Design
- [ ] #15242 () - BE
- [ ] #15219 () - FE
- [ ] #15147 () - FE

XXX APPROX CUT LINE for Sprint 93 XXX
- [ ] (stretch) #11233 - BE
- [ ] (stretch) #11854 (5) - FE
- [ ] (stretch; small item if it doesn’t slow other stuff down)  #14904 (2) - BE
- [ ] (stretch) #15205 (needs) - FE
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #12933 (5) - BE

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
[A11y Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?labels=accessibility&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zNDgy)

### Other priorities
- [ ] (stretch) #13062 (3) - FE
- [ ] (stretch) #11230 (3) - BE

### Content / IA priorities (CAIA)
- [ ] #15219
- [ ] va.gov-team 58142 - **blocked**; CLP-related

### Portfolio and pipeline - [epic](#7599)
- [ ] #12791 (needs) - Design
- [ ] (stretch, low-prio) #12601 (needs) - Design

### Epic of upcoming redirects not yet in our board:
Team repo # 53921

### Product health/dashboard backlog
- [ ] #15003 (0) - Product

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
