### ISSUE TITLE
Remove COVID vaccine URL from facility api data

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15088]
## User Story or Problem Statement

The COVID Vaccine URL is no longer necessary to have in our Facilities API pushes and should be removed.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/9e63ee3e-e735-4d52-9187-b06e82354215)

### Background
@mmiddaugh on removing it:
https://dsva.slack.com/archives/C0FQSS30V/p1692903074898259?thread_ts=1692887713.139779&cid=C0FQSS30V

Adam from Lighthouse saying that it can be safely removed:
https://dsva.slack.com/archives/C02BTJTDFTN/p1692976600056399?thread_ts=1692974257.103199&cid=C02BTJTDFTN

## Acceptance Criteria
- [x] Confirmed with Lighthouse
- [x] The facility operating status data in the queue does not have the `covid_url` property.

## Implementation steps
The relevant code is in
file: `va_gov_post_api/src/Service/PostFacilityStatus.php`
method: `getRelatedSystemInfo`

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`
