### ISSUE TITLE
Support sidewide_alert feature request to get it across the d.o finish line

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#15103]
## User Story or Problem Statement

Back in June 2022 we made a [feature request on the sitewide_alert module](https://www.drupal.org/project/sitewide_alert/issues/3290964) to make it use Drush commands that we need for CMS deployments.  On behalf of the CMS team, Swirt made the feature request, and Tanner contributed the patch.   The modules's maintainer asked a lot of questions that went unanswered (due to people rolling off the team) and made some updates to the patch.  Edmund has had to re-roll it a couple of times to make it exist as a static (more secure) patch we could use in our site.

The patch is now in "Needs review" and we could/should help move it along by having someone review the patch, show that we are using it, and show that it does what it is supposed to without error. (testing out the drush commands.  Then change its status to "Reviewed and tested by the community".   This will help the module maintainer get it merged in so we do not have to keep spending time re-rolling patches.

## Acceptance Criteria
- [x] Patch is reviewed by someone not already on the issue (not swirt, tanner, or edmund)
- [x] Testing procedure of testing the drush commands is described in a comment on the issue and shown to be successful. (There are test cases that swirt added early on in the issue, they would be a good place to start.)
- [x] Link to our repo showing the line where we are using the patch is added in the comment.
- [x] If testing and review is successful, status is change to "Reviewed and tested by the community.
- [ ] If testing is not successful, the problem is described and status of the issue is changed to "Needs work"

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Websites
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by BerniXiongA6** [comment]
Hey @ndouglas -- could you preview this request to find out whether we have enough info before bringing it into pre-refinement? Appreciate the assist! cc: @productmike @swirtSJW @xiongjaneg

**Comment by BerniXiongA6** [comment]
Thanks @ndouglas ! Let's plan on having you all bring this into the next pre-refinement sync. Let me know if you need anything. Thank you!!

**Comment by tonytaylor** [comment]
Running late on this one. Completion targeted for Thurs.
