### ISSUE TITLE
Update VAMC links to Order hearing aid batteries and accessories to MHV

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15111]
## Problem to solve
As MyHealtheVet functionality is brought into va.gov, we will need to update existing top task links from VAMC pages to the new corresponding location. 

## Other things to consider
- Difference in endpoint for Cerner vs non-Cerner facilities - will the check still be needed? 
   -  as of 9/6/2023, our changes are slated for Phase 2 and Cerner is expected to be integrated so fork in experience should no longer be needed
- Lovell bifurcation 
- Can we use a deeper login vs directing the Veteran to an interstitial landing page?
   - _MyHealtheVet team will supply link 
- Can we pass the facility ID to prepopulate that in appointment screen? 
- How might we clearly indicate login will be needed before the Veteran clicks the action link?
- Where are all of the links?
   - _MyHealtheVet team should be able to provide referral source data for pages to identify all relevant pages and to monitor after changes are done in case one is missed (or added by an editor)_
- Updating these links on our side should not be critical path for the MVH roll-out as redirects will be in place to ensure Veteran is directed to the correct endpoint, even if our links are not yet updated

## Current behavior
Veteran clicks on top task button or link from "Manage your health online" box > directed to health-care/order-hearing-aid-batteries-and-accessories/  page > Sign in to order hearing aid supplies widget (login)
<details>
<summary> Screenshots </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3R4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--49ad7c35f3245bb604cabc509bc559e1c2e8dd57/image.png)
</details>

## Tasks
in the Manage your health online box on VAMC system level pages
- [ ] update link text from `Order hearing aid batteries and accessories` to [TBD - will come from CAIA team)
- [ ] update the link to order to [TBD - will come from Comms team)

- [ ] coordinate change management with VHA DM for editor-entered links (if any)

**Comment by mmiddaugh** [comment]
Our work is part of Phase 2 and expected by 5/2024

**Comment by mmiddaugh** [comment]
Today we direct traffic based on a "Is Cerner" type of flag at the facility level. 
What if this was based on the task?
- Is this task in the modernized space? 
   - If yes -> this modernized link
   - If no, then is this a Cerner facility?
      - If yes -> Cerner link
      - If not -> Vista link

**Comment by jilladams** [comment]
Per Mikki, this is not part of March 12 MHV of VA.gov transition due to staffing changes. Closing as not planned, we can reopen when it revives.
