### ISSUE TITLE
Addiction and substance abuse care should be a required Vet Center service

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15118]
## Description
A set of services were determined to be required for Vet Center pages. This meant they were automatically added to new Vet Center pages and could not be removed by editors. 

Addiction and substance abuse care was previously considered a required service for Vet Centers but editors have access to the "Remove" button in the CMS interface today. (I am logged in as an admin rather than an individual editor but I don't think this is the reason I can see the remove button because other required services such as Couples and family counseling and Mental health care do not have the "Remove" option. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDF5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f874f2528ebfc421689488b8922ee75360584021/image.png)

The following services are required for Vet Centers

- Addiction and substance abuse care 
- Community engagement 
- Couples and family counseling 
- Grief and bereavement  
- Mental health 
- Military sexual trauma care 
- PTSD 
- Returning service member care 
- Suicide prevention 
- Veteran connections 

## Tasks
- [ ] TBD

## Acceptance Criteria
- [ ] Vet Center editors do not visually or functionally have the option to remove required Vet Center services. 
- [ ] Required services appear automatically on Vet Center pages
- [ ] Required Vet Center services do not appear in the list of optional services

**Comment by xiongjaneg** [comment]
@swirtSJW @omahane Please review and add any comments, questions, blockers. Please let me know if a sync is needed to discuss.

**Comment by swirtSJW** [comment]
I validated that it is not just a bad setting in the data 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1J6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5e0793e8fecdf7e4ade3d7561f450ce5f7fe35bb/image.png)

**Comment by swirtSJW** [comment]
I just tried using the remove button and then publishing the node revision.  It did not stick.   The addiction service is still present and attached to the node.
[Uploading... image.png]

**Comment by swirtSJW** [comment]
Some odd behavior popping up.
If I edit the Fort Myers Vet Clinic.  addiction service shows as optional.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc3h6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0fe83717bc366863a9d824f09d90929a86ec4fbc/image.png)


Then if I make a change to the service by using the edit button, and save it, the service is now correctly classified as required
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczV6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b928bb3af78dddb19dee548ec5f7eda968a79a67/image.png)

**Comment by swirtSJW** [comment]
I think there was a problem with the automated saves that were done by the CMS team to create Linkies.  It saved every node, but somehow the revisions on the entity references got messed up.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHB6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--665e59e4e17e5d45eb986b39d645cd17edb6bbe8/image.png)
Saving an edit to the node fixes the entity reference.

Laura Flannery had called out another place where automated saves had created a disconnect in KB articles.  This may be a similar problem

**Comment by xiongjaneg** [comment]
Per Steve in Slack: We might want to time box it to a 5.   Or we we don't bother trying to see what went wrong and we just try to fix it for the future.  The investigation may take a while.  My hunch was that it comes down to the automated processing we did for Linkies..... but that does not explain why it only affected one of the 10 required services... so I do not have much confidence in that hunch.

**Comment by mmiddaugh** [comment]
Recording these observations from my reminder self-tour this afternoon
- The only path by which the revision log message workflow is presented for changes to Vet Center services is if the editor clicked  edit from the content list for the service. (Note: none of our training materials, roll-out materials, or live presentations during 1:1 help sessions or office hours showed this path.)
- Clicking "Go to services" from the card on the dashboard drops the editor into the services section of the main page, where the only revision log message workflow is at the bottom of the main page (not inline for the service edits). 
- This is true for all other content on the main page. 
-  However, changes to the Locations page content will have a revision log message whether the editor arrives from the Content view or via the "Edit" button on the Dashboard.

**Comment by omahane** [comment]
I ran bulk edit in a Tugboat environment, bulk saving the "Addiction and substance use care" service, which made it once again required, as Steve suggested it might in his research.

I then deleted a Vet Center and its services.

I ran a migration, which made the facility show up.

I then ran cron, which caused all the required facilities to be created.

**Comment by swirtSJW** [comment]
Nice test @omahane Sounds like a great plan.

**Comment by omahane** [comment]
@xiongjaneg @jilladams I ran bulk update on the following "Addiction and Substance use care" services
- Vet Center Facility service
- VAMC System Health service
- VAMC Facility Health service

Vet Centers should now all show "Addiction and Substance use care" as required when being edited.

Additionally, no service of any kind has the term "abuse" in the title any longer (as it was replaced by "use" in the term a while ago).

This was testing in a PR branch, then staging and now run in Prod, so it's complete.
