### ISSUE TITLE
CMS Team Sprint 93 Plan (9.13.2023 - 9.26.2023)

### ISSUE THREAD

**Issue by productmike** [department-of-veterans-affairs/va.gov-cms#15156]
## Sprint 93 Goals & Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_

- [x] 1. #15246 
- [x] 2. #15241  
- [x] 3. #15119

<br>

**Notes:** 
<details><summary>**Sprint 93 Prioritization Notes**</summary>

- [ ] Editor Trust Survey is pending VIEWS approval process. All work has been put on pause.
- [ ] Capacity: All Points CMS Team Can Take On in S93 = 56.7 points
> All Eng = 36.9 pts
> All UX = 16 pts
> All Support = 3.8 pts

  
</details>

## Sprint 93 Committed Work

[How does this work impact our OKRs?](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2703720521/Current+Priorities#3Q)

### 1. D10 Test Readiness and Deploy #14410
Drupal
- [ ] (3 completed) #15103 (2pts to carry over to S94)
- [x] (5) #15119 
- (0) Carry over 2 pts from In Progress to S94/95 #14725 

Product
- [ ] #15297 (Product to carry over into S95)

### 2. Alt Text Field Prototype #13103
UX
- [x] (3) #15241 (Sprint Goal)

### 3. Knowledge-base Enhancements #14069 
UX
- [x] (5) #15246 (Sprint Goal)
  

### 5. CMS Governance by Discipline/Function #14012 

UX Design
- [x] (3) #12952

DevOps
**- (DevOps could bring in about 4 additional points this sprint if sprint commitments are completed) Per Erika, DevOps can pull in tickets at the top of Ready for Sprint pipeline. Let Berni know if you pull in tickets into Sprint 93.)**

### 7. Improvements to content release system #14016
- Not planned

### 8. CMS Collab Cycle #14013
- Not planned

### Help clients, stakeholders hit their objectives.
Drupal / A11y
- [x] (1) #15135 
- [ ] (1 completed) #9919 (carry over 1 point to S94)

Product
- [x] (1) #14908

### Defects, Hurdles
DevOps
- [x] (5) #10220 

### Keep the lights on (KTLO)
Drupal
- [ ] (0) #15163 -- none in S93

DevOps
- (0) #14350 (carrying over 8pts to S95, was blocked in S94)
- [x] (5) #8669  (This is a carry-over issue, if DevOps has bandwidth)

Unplanned
- [x] (1) Drupal #15272 
- [x] (3) Drupal #15332 
- [x] (5) DevOps #15183 
- [x] (5) DevOps #15184  
- [x] (3) Defect #15298 
- [x] (8) Enhancement #8849 
- [x] (5) Helpdesk and user support #12669

**Comment by BerniXiongA6** [comment]
Partially and fully completed sprint work = 60 pts in Sprint 94.
