### ISSUE TITLE
Income Limits Automation: Test Network Connectivity from Self-Hosted Runners to VES

### ISSUE THREAD

**Issue by dsasser** [department-of-veterans-affairs/va.gov-cms#15202]
## Description
As [noted](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13759#issuecomment-1711960509) in #13759, our next steps for Income Limits automated data export involves testing access to VES within Github self-hosted runners.

Create a new self-hosted runner likely using the method described in [Tim's comment](https://dsva.slack.com/archives/CT4GZBM8F/p1693941770594819?thread_ts=1693936884.434949&cid=CT4GZBM8F).

The runner should execute a java test script (created by Johnathan Falkner) for the purposes of testing network connectivity to the VES network. The runner will execute inside a new workflow.

The test should execute the following commands:

```bash
aws s3 cp s3://dsva-vagov-staging-config-bucket/cms-test/ConnectionTest.jar . --region us-gov-west-1 #copies the test script from s3 where it already exists.
yum install java-1.8.0-openjdk # installs java
java -jar ConnectionTest.jar # executes the test. Get the test file from Daniel Sasser via Slack.
```

The test output will clearly indicate if it succeeds or fails. Should the test prove unsuccessful, we will need to work with ESECC/Gateway Operations to establish the connectivity before we can begin an implementation ticket.

### User story
**AS A** PW Engineer
**I WANT** to test connectivity to VES in a github self-hosted runner
**SO THAT** we can ensure it is viable for VES data export

## eng notes
The DB at VES that holds the data is not accessible from everywhere on the network, including local. IT helped us configure access from 3 subnets.

Re: which repo to use for the Github workflow: 
* We own va.gov-cms and can test there, and move the Action to a more logical repo later if it works
* If we move it later, we'll need to make sure it will still work / repos dont' have different network access. CMS Devops can probably help understand that.

### Tasks
- Build an action within Github's self-hosted runner
  - Test action with 2 lines or so, just to demonstrate it worked

## Acceptance criteria
- [x] Implemented test Github workflow that demonstrates connection to VES
- [x] Results of experiment (script, implementation notes, etc) documented in ticket
- [x] Next step ticketed
  - [x] Decide the long-term repo home for the Github action

**Comment by dsasser** [comment]
## Status Update

The test was a [success](https://github.com/department-of-veterans-affairs/va.gov-cms/actions/runs/6748590584/job/18347231797).

![Screenshot 2023-11-03 at 10 47 15 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/2b188ed0-26ce-448b-93b1-b856210f97fa)

We can now proceed with ticketing automation.

cc @FranECross @jilladams 

Regarding this AC:

> Decide the long-term repo home for the Github action

We don't need the test workflow to remain in place, but we do need to figure out where the actual, final workflow that performs the automated export should live, be that in vets-api or vets-website.

**Comment by dsasser** [comment]
I'm going to remove the test workflow branch; preserving the .yml below for posterity in case we need to run the test elsewhere:


```yaml
name: Income Limits VES DB Test
on:
  push:
  workflow_dispatch: null

env:
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt

jobs:
  # Testing
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install Java
        uses: actions/setup-java@0ab4596768b603586c0de567f2430c30f5b0d2b0 #v3.13.0
        with:
          distribution: 'zulu'
          java-version: '8'

      - run: java -version

      - run: java -jar ./scripts/income_limits/ConnectionTest.jar

```

**Comment by dsasser** [comment]
[Slack thread ](https://dsva.slack.com/archives/CT4GZBM8F/p1699034571641739)on s3 and access to resources.

**Comment by jilladams** [comment]
@dsasser WOO! Re: long-term home, it makes most sense to me to put it in vets-api, since we're importing data that we interact with through that API. Thoughts? Maybe we ask Platform in a support ticket to confirm if that's ok, since they own most of the other github workflows in both those repos?

**Comment by dsasser** [comment]
> @dsasser WOO! Re: long-term home, it makes most sense to me to put it in vets-api, since we're importing data that we interact with through that API. Thoughts? Maybe we ask Platform in a support ticket to confirm if that's ok, since they own most of the other github workflows in both those repos?

Platform will have to review the PR anyway, so we can get their approval at that time. We can fall back to vets-website, and finally va.gov-cms, if the other two repo's end up being a no go for whatever reason.

**Comment by dsasser** [comment]
This is the next likely ticket for automation: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15203
