### ISSUE TITLE
Draft outline of engineering portion of SOP/Runbook for Drupal upgrades

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15237]
## What You Need to Know
- Part of #12238.
- This is the engineering-specific "review of outline" of the runbook for how we work on Drupal upgrades.

## Acceptance Criteria
- [x] Outline of the Engineering-specific portion of a runbook has been drafted.
- [x] PM/DM/PO have reviewed the outline and approved it.
- [x] Outline has been saved in Confluence.

## Tasks
- [x] Review the runbook outline drafted in #12238.
- [x] Refine outline as appropriate.
- [x] House the outline content in Confluence ([link](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2739175693/Runbook+Draft+Drupal+Upgrades))

**Comment by edmund-dunn** [comment]
@ndouglas I think I have it in good shape. Can't think of anything I missed. Feel free to hack it apart. I did make sure to get info from @tjheffner on AP so we can make sure anything we need to include for AP in the next (D11) upgrade is accounted for.

**Comment by edmund-dunn** [comment]
@BerniXiongA6 @EWashb this is ready for you to review/approve. :)

**Comment by EWashb** [comment]
@edmund-dunn @BerniXiongA6 this looks go so far from the engineering perspective. Good list to start!

For Product to consider- The final doc will need more narrative. Looking at the list doesn't give the reader the context necessary to act on the steps listed. However, I know there will be more input on this doc from other other disciplines. I would like it to be plan language and actionable.

**Comment by BerniXiongA6** [comment]
Forgot to mentioned that this outline has been reviewed, @edmund-dunn @ndouglas . @EWashb and I will be fleshing out more details soon in terms of how Product would like the final deliverable to read. In the meantime, thanks for getting us started!
