### ISSUE TITLE
Create an onboarding-centric document for DevSecOps and Drupal roles on the CMS team

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15234]
## Description

In our visioning workshop, we determined the following:

>- We lack simplified, beginner-friendly documentation for our ecosystem. We need materials that are engaging, utilizing elements like diagrams and cartoons to make it more accessible and easier to understand.
>- There is a lack of clear documentation for our major CMS components, and it’s unknown how well our onboarding process helps people understand these different parts and how they work together. 
>- We lack a list of tasks for new team members to work on as they wait to complete their onboarding process.
>- We don’t have a shared understanding of how our work aligns with and contributes to the broader ecosystem.

We can partially address these issues by creating an onboarding-centric document for DevSecOps roles.

This document should be brief, no more than a couple pages as a PDF, but should provide the "10,000-foot view" of the ecosystem, the CMS, our work process and good first tickets, and a summary of how we contribute to the ecosystem.

## Tasks

- [ ] Create a Markdown document containing:
  - [ ] brief, highly simplified, beginner-friendly documentation for the ecosystem, including diagrams, etc to make it less taxing to consume.
  - [ ] brief, highly simplified, beginner-friendly documentation for major CMS components.
  - [ ] brief summary of "how we work", including a link to where an engineer can find good first tickets to work on.
  - [ ] brief summary of how our work aligns with and contributes to the broader ecosystem.
- [ ] Add the document to the READMEs directory.
- [ ] Add a link to the document in the onboarding ticket template.
- [ ] Add a link to the document in the root README.
