### ISSUE TITLE
Monitoring for Facility Locator

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15261]
## Description
As the Facilities team, we want to be the first to know when connections with Facility Locator are disrupted.

## Tasks
Related to #15224 analysis of test coverage
- Review existing documentation, such as this [Facility Locator Technical documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/technical-documentation.md#facility-locator-technical-documentation) and [this table of error states](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/error_states.md) and validate for accuracy
- Determine what is known related to the following 
   - What are the connections responsible for VA facility searches?
   - What are the connections responsible for community care data searches?
   - Who owns each connection?
   - Will we know if the connection fails?
     - If so, how will we know? What test or system will tell us? Do we currently monitor this test or system? 
   - If we identify an issue, how do we notify the owning team? Who is the POC?
   - If this connection fails, what happens in the Veteran experience? (is there a graceful error message?)
   - Do other teams depend on our connection?
     - If so, which teams and how will we notify them? 
- Identify missing knowledge and processes

## Considerations
Datadog could tell us more, but requires access. 
We can request, and if Platform isn't responsive, can request help from DaveC to get response.

## Acceptance criteria
- [x] Existing documentation has been updated and validated for accuracy
- [x] It has been determined whether or not Datadog provides what is needed to monitor any disruption in Facility Locator data.
  - [ ] If not, is there another source? Create a new ticket to identify a different source.
  - [x] If yes, set up a schedule or process for monitoring and sending alerts.

**Comment by xiongjaneg** [comment]
From Adrian Rollett about access to tools for monitoring, visit this Slack thread https://github.com/department-of-veterans-affairs/va.gov-team/issues/65206#issuecomment-1712130625

**Comment by jilladams** [comment]
From sprint planning: this ticket needs updated with ACs notes / takeaways to do the steps identified in #15224  (@xiongjaneg )

**Comment by eselkin** [comment]
@maxx1128 and I started creating alerting from Datadog for `vets-api /v1/facilities/va`
We chose the similar alert that PW chose for the forms content. Though we haven't been made aware of any different cap on requests. We already have a rack_attack restriction on the path so it's unlikely given the current history that this level will be triggered (>400 warn,>450 alert). We will also add 429 alerting for people abusing that endpoint.

**Comment by jilladams** [comment]
Asked Lighthouse about how our API consumer / limits work here: https://dsva.slack.com/archives/CJ162GDDJ/p1696019631707519. tl;dr: 

* Our Lighthouse Facilities API consumer is `VADOTGOV_FacilityLocator`
  * There are known cases where multiple products / teams are using a single API key, or multiple API keys, through the same API consumer. Don't currently know how to know if that's the case for us.
* Lighthouse sets API rate limiting by consumer, and _can_ set specific limits per consumer+per API. 
* According to Adam, the rate limit on this key set to ~2000/min, to ensure a bulk push of all the service data coming from the CMS will not fail. Lighthouse has confirmed they can receive bulk services coming in as fast as the CMS queue could send them on top of the steady state traffic coming from the rest of the system so there should be no issues with that rate limit on this key.

**Comment by eselkin** [comment]
@jilladams added a question there. Wanted to make sure we checked that the CMS push was using the key we are using with our indirect vets-api endpoint. The configs are not visible to us I think, so we can't see if the config YAML for vets-api facility locator is using that VADOTGOV_FacilityLocator key.

**Comment by eselkin** [comment]
Created Monitor (and warning/alerting) for rate limiting: https://vagov.ddog-gov.com/monitors/161751
Created Monitor (and warning/alerting) for abnormally high error levels: https://vagov.ddog-gov.com/monitors/164800 
Created Dashboard for facilties: https://vagov.ddog-gov.com/dashboard/3vy-h6h-4ek/sitewide-facilities

We can add more monitors to the dashboard, but the two above are added. To add an alerting monitor to the dashboard, add a panel, select alert value, select the alert (only alerts, not warnings are viewable).

I did not update the threshold of the warning to 2000 as the consumer `VADOTGOV_FacilityLocator` can't be verified by us. We are assuming it's true that it's higher than the other groups and does have a vets-api key that is separate than all other lighthouse vets-api keys, so it's probably in a different group.

**Comment by jilladams** [comment]
Monitors look good, dashboard makes sense. 
RE: getting notified, #facilities-monitoring was created in DSVA slack, and is getting pings from Datadog with monitoring status. 

Last AC here is re: updating the existing Github docs to tell future generations what exists as far as monitoring. @eselkin can you please update here re: status on that / if this is now closeable? 

Also: In DDog, can this one be deleted if we won't be using it? https://vagov.ddog-gov.com/monitors/164800

**Comment by eselkin** [comment]
We are using that one (164800), it has NO DATA because nothing has crossed its threshold. So far, today, only 1 500 error happened on vets-api. So it hasn't crossed to the warning zone of 5 and nowhere near the alerting of 15. I can bring the warning down to 1 and it'll "have data" or just wait till something like the 28th happened where there were like 35 errors.

**Comment by jilladams** [comment]
Ok. Can you confirm if the documentation AC is complete / ticket can close?

**Comment by eselkin** [comment]
Updated: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator/technical-documentation.md

Can close

**Comment by eselkin** [comment]
I added a separate monitor for CCP 500 errors as well to the dashboard (also documented)

**Comment by jilladams** [comment]
Woo! Closing.
