### ISSUE TITLE
Each new VBA facility needs a regional office and operating status

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15299]
## User Story or Problem Statement

New VBA facilities need to be assigned to the appropriate regional office and have an operating status updated or confirmed.

## Acceptance Criteria
The the following [new VBA facilities](https://prod.cms.va.gov/admin/content/facilities/flagged?type=vba_facility&workbench_access_section__section=All) haver been updated:
- [x] Fort Harrison VA Regional Benefit Satellite Office at Benjamin Charles Steele VA Clinic
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VetSuccess on Campus at Santa Monica City College
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VetSuccess on Campus at University of California, Los Angeles
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] Veteran Readiness and Employment Office at Raleigh, North Carolina
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VA Regional Benefit Satellite Office at Providence Vet Center
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VA Regional Benefit Satellite Office at New Bedford VA Clinic
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VA Regional Benefit Satellite Office at Cape Cod Vet Center
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag
- [x] VA Regional Benefit Satellite Office at Middletown VA Clinic
  - [x] Assign the facility to the proper Regional Office section
  - [x] Update or confirm the operating status
  - [x] Remove the `New Facility` flag

When 
## Implementation steps
See acceptance criteria

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by mmiddaugh** [comment]
Done! @omahane
