### ISSUE TITLE
Update colors in CSS

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#15310]
## User Story or Problem Statement
This follows #15309 
Make any updates that are needed. 

## Description or Additional Context 
Document needed changes here:

- [ ] Dropdown arrow icons on home pages should be `--va-blue-dark` `#004795` [View image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN212QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0c7c951bca20e43a7bf50d03fa601b43388fff9e/Screenshot%202023-11-07%20at%2011.23.46%20AM.png)
- [ ] Black text on [pager components](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#pager) should be `--va-gray-darkest` `#212121`
- [ ] Upon hover, the circle indicating the page currently being viewed on [pager components](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#pager) should darken to `--va-blue-darkest` `#112E51` with text remaining `--va-white` `#FFFFFF`
- [ ] Expand and collapse arrows on [forms-details components](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#form-details) should turn the same color as the associated text upon hover. `--va-blue-dark` `#004795`
- [ ] Text for secondary buttons in [confirm form components](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#confirm_form) should remain `--va-blue-dark` `#004795` upon hover.
- [ ] Fly out menu arrows should be `--va-blue-dark` `#004795` [View image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTJ2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a38d1f85dbd3010efe013a6489fe04d956f0908e/Screenshot%202023-11-06%20at%203.42.57%20PM.png)
- [ ] Fly out menu arrows should not disappear upon hover. They should stay `--va-blue-dark` `#004795`
- [ ] On pages with lists of links such as the [add content page](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/node/add) the description text under links should be `--va-gray-darkest` `#212121`
- [ ] On pages with lists of links such as the [add content page](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/node/add) the arrows next to links should be `--va-blue-dark` `#004795` and behave the same as their associated link upon hover.
- [ ] When clicking a menu item, the background of the menu item should remain `--va-blue-lightest` `#F0F6FB` [View image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeSt3QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c39a5be81d7ea7fae5639029acefca450570d39/Screenshot%202023-11-06%20at%203.30.41%20PM.png)
- [ ] Icons for the [status, warning, and error messages](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#status-message) should be `--va-gray-darkest` `#212121` to align with similar components in the VA Design System.
- [ ]  [Status message](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#status-message) background should be `--va-green-lightest` `#E7F4E4`
- [ ]  [Warning message](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#warning-message) background should be `--va-gold-lightest` `#FFF1D2`
- [ ]  [Error message](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#error-message) background should be `--va-red-lightest` `#F9DEDE`
- [ ]  [Forms, action](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#form-actions) danger button should darken by 10% upon hover
- [ ] [Progress bar](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#progress_bar) blue indicator should be `--va-blue-dark` `#004795`
- [ ] [Progress bar](https://pr15560-ab9nzwp4bqjzcsp9aaggnxolxezeet0j.ci.cms.va.gov/admin/appearance/styleguide/vagovclaro#progress_bar) grey indicator should be `--va-gray-lightest` `#F1F1F1`

## Acceptance Criteria
- [ ] All colors have been updated. 
- [ ] Requires design review
- [ ] Requires accessibility review

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [ ] Public Website
- [ ] Facilities
- [ ] User support
- [ ] Accelerated Publishing

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 @edmund-dunn 
This ticket has been updated with color updates needed and is ready to be worked when there is capacity.
