### ISSUE TITLE
Cross-platform mobile banner: remaining iOS browsers / Android

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15331]
## Top-line Description / Goal(s)
Promote the existence/use of the VA.gov Mobile App. As the mobile team rolls out functions, the Sitewide Crew can elevate the capabilities of the Mobile App through the use of a cross-platform solution that is an extension of/continues to use/parallels the Apple smart-banners solution.

Initiative brief: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/benefit-hubs/initiatives/2023Q3-mobile-promotion/README.md

#### Monthly project updates:
- 

## Headlines
**VA stakeholders** - 

**OCTO lead** - Dave Conlon

**Is this project tracked to an upcoming event or congressional deadline?** - No

## Details

**Which OCTO team should do this and what is currently on their roadmap?** - Sitewide

**Which OCTO priority does this work support?** - Self-service

**What is the user impact and scale of impact?** - 

**Who would manage this product long term?** - Public Websites

**How much leverage will this create to solve more problems in the future?** -  TBD. Hypothesis is that it will drive increased adoption of the mobile app.

**How great is the cost of inaction? (e.g., Can it wait? Must it be done by us?)** - 

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by EricaRobbins** [comment]
- Changed target start from Oct 1 to Nov 1
- Waiting to get analytics on effectiveness of smart banner

**Comment by davidconlon** [comment]
This is in-flight as of end of November.

**Comment by davidconlon** [comment]
Launched during sprint ending 1/17/2024

**Comment by jilladams** [comment]
Re: remaining tickets in epic: 
* #16969 - post-launch defect Identified today
* #15345 - final tech debt removal, we identified today this is blocked on a content step from CAIA. They'll ticket their work so we can follow along and merge our changes once unblocked

**Comment by jilladams** [comment]
Tech debt is complete, closing!
