### ISSUE TITLE
PW Sprint 94 plan

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15338]
Google doc for actual editing: 
https://docs.google.com/document/d/1l7kUk1U9IgxzgXYA3MQFt8aB_jYEHHGinrwYE_wVE4I/edit

### 1. PACT Act Wizard [epic #12170](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170)  🟢
[PAW Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTAyOTA1Mw&filterLogic=all&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzE4) 

### 2. USA Header/Footer [epic #14078](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14078)   🟢
[FedHeadFoot Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3NzMzMg&filterLogic=all&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zNDgx)

### 3. Cross-platform Mobile banner [epic #15331](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15331) 🟢
- [ ] #15348 (0) - Product
- [ ] #14288 (0) - Product
(blocked on analytics) #15339 - mobile app banner FE architecture
(blocked on analytics) #15317 - mobile app banner design

### 4. Outreach Events improvements (National Calendar) [epic #13527](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13527) 🟢
- [ ] #10089 (8) - add Natl Calendar checkbox
- [ ] #15350 (needs) - FE - event image ratio
- [ ] (stretch) #15168 () - BE
- [ ] (stretch; small item if it doesn’t slow other stuff down)  #14904 (2) - BE
- [ ] #15385 (needs) - BE
  - [ ] (blocked on 15385) #15411 (needs) - FE

### 5. Support log-in widgets for health apps
- [ ] (stretch) #15205 (needs) - FE
- [ ] (stretch) #13062 (3) - FE

### 6. Discharge upgrade wizard [epic #12043](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12043) 🟢
- [ ] #15216 - flow/content audit against prod code
- [ ] (stretch) #11854 (5) - FE

### 12. Benefit content model  [epic #9628](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628) 🟢
[Benefit Taxonomy / Magichead Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3MDczOQ,Z2lkOi8vcmFwdG9yL0VwaWMvOTU0NjA0&filterLogic=any&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzIx)
- [ ] #15397 
- [ ] (stretch) #15398

### 13. Re-usable QA support [epic #10780](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10780) 🟢
[Q&A Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvOTk0MTkz&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzIw)
- [x] #10938

### 14. Monitoring and Alerts [epic #15262](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15262) 🟢
- [ ] #15377 - 5xx errors on forms
- [ ] #15414 - flaky tests audit
- [ ] #11255 (8) - FE - priority for monitoring: injected head/foot

### 15. Campaign Landing Page [epic #4642](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4642) 🟢
- [ ] #15351 (3) - Design - formalize plan for getting CLPs to 1:1 aspect ratio
- [ ] Epic for CLP KB articles (to replace pdf) #15003 (0) - Product
  - [ ] #15384 (needs) - BE (KB for CLP)

## Q3 Remainders
Items with [x] are carried over from previous sprint

### 1. Income Limits web app [epic #14113](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14113) 🟢
[I.L. Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTA3ODcwMQ,Z2lkOi8vcmFwdG9yL0VwaWMvOTU0NTg5&filterLogic=any&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zMzE3)
- [x] #15202
- [x] #15330

# Other PW Priorities 🟢
## Prioritized for this sprint
(Note: may be duplicated in sections below)
- [ ] (carryover from s93?) #14819 (5) - FE (Randi)
- [ ] #15337 (3) - BE - D10 upgrade
- [ ] (stretch) #12933 (5) - BE

### A11y backlog
Stretch tasks as needed, unless we prefer to prioritize 1 per sprint to burn down the list.
[A11y Zenhub View](https://github.com/department-of-veterans-affairs/va.gov-cms#workspaces/public-websites-6171bf4bf43742001af18cc5/board?labels=accessibility&repos=48004036,33202667,133843125,154174777,zh-Z2lkOi8vcmFwdG9yL1JlcG9zaXRvcnkvMTMzODI5MTI2&view=Z2lkOi8vcmFwdG9yL1NhdmVkVmlldy8zNDgy)

### Content / IA priorities (CAIA) 🟢
- [x] #15352
- [ ] va.gov-team 58142 - **blocked**; Secure sign in CLP

### Portfolio and pipeline - [epic](#7599)
- [ ] #12791 (needs) - Design
- [ ] (stretch, low-prio) #12601 (needs) - Design

### Epic of upcoming redirects not yet in our board:
Team repo # 53921

### Other priorities not in motion 🔴
- Translation in R&S, Hubs (epic) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12996 – FE templating to make CMS-entered translations visible. Possible dependencies on BCM hardening and fast publishing (because translation is field-by-field).
