### ISSUE TITLE
Vanity URL/Redirect: WH event for a CLP 

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15358]
## User Story or Problem Statement

http://va.gov/VSAFE
to
https://www.va.gov/initiatives/protecting-veterans-from-fraud/

per https://dsva.slack.com/archives/C52CL1PKQ/p1695386739021879
## Acceptance Criteria
- [ ] URL redirects successfully

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [x] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by FranECross** [comment]
Confirmed that the URL is redirecting correctly to https://www.va.gov/initiatives/protecting-veterans-from-fraud/..  Closing.
