### ISSUE TITLE
CMS Team Sprint 95 Plan (Oct 11, 2023 - Oct 24, 2023)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15364]
# Sprint 95 Goals & Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
- [x] Presentation has been completed at 10/11/2023 Drupal CMS Office Hours for VAMC editors #15642 
- [x] Outline has been drafted by UX for Drupal runbook deliverable #15432
- [x] Made progress on Datadog monitoring expansion #15539

**Notes:** 
<details><summary>**Sprint 95 Prioritization Notes**</summary>

- [ ] Capacity: All Points CMS Team Can Take On in S95 = 50.9
> All Eng = 31.5 
> All UX = 13.4
> All Support = 4
> a11y = 2

</details>

# Sprint 95 Committed Work

### D10 readiness (Q4 Goal)
Drupal
- [x] (1 partial point) - Unblocked and ready to test! #14725 (will keep ticket open for 11/2 test.prod deploy w/ IAM team)

UX/Training/a11y
- [x] (3) #15579 

Training
- [x] (1) #15642 (Sprint Goal)

### D10 Runbook Deliverable (Q4 Goal)
UX
- [x] (3) #15432 (Sprint Goal)

### Datadog Monitoring Expansion (Q4 Goal)
DevOps
- [ ] (5) Pulled over from S94 #15307 -- carryover to S97
- [x] (3) #15539 (Sprint Goal)
- [x] (3) #15540
- [ ] (8) #15542 -- carry over to S96

Helpdesk
- [ ] (5) #15470 -- carry over to S96

### Alt Text and Image Upload Enhancements (Q4 Goal) 
Drupal
- [x] (8) #15435 

### Defects, Hurdles
- [X] (8) #13639 (Tony) 

### Keep the Lights On
DevOps
- none assigned to S95

Drupal
- [ ] (1) #15428 -- none in sprint 95

### Collab Cycle / CMS Governance

UX Research
- [x] (2) #15481 (refined)

### Knowledge-base Enhancements
UX
- [x] (5) #15247

### Improvements to Content Release System
- none assigned to S95

### Help clients and stakeholders hit their objectives
Product / Delivery
- [x] (1) #15257 (will carryover and finish at the beginning of S95 - BX 10/10)
- ~~#15328 (will carryover and finish at the beginning of S96 - BX 10/23)~~
- ~~#15657 (Deadline 10/23) - Per Jill, removed CMS Team from this ticket as it's being revamped by PW team. Remove from Sprint 95.~~
- [x] (1) #15051
- [ ] (1) #15643 (partially completed, will carryover and finish in S96 - BX 10/25)

### New Team Member Onboarding
- [ ] (0) #15590 -- making progress, almost done onbaording

### Added Post-Sprint-Planning
- [x] (8) #14971 (Ari)
- [x] (2) #15711 
- [x] (3) #15846
- [x] (3) #15433

# REFINED AND READY - candidates for Sprint 95 if Top and Medium Priority tickets have been completed 

**Rolling these over to Sprint 96 epic since we didn't get to these!**
### Open DevSecOps Tickets
- [ ] (5) #14492
- [ ] (8) #13834
- [ ] (5) #15301
- [ ] (5) #15307
- [ ] (5) #13975
- [ ] (3) #11632
- [ ] (8) #7674
- [ ] (5) #7673
- [ ] (5) #11629

### Open Drupal Engineering Tickets
- [ ] (2) #14765 
- [ ] (3) #12674

# CANDIDATES FOR S95 BACKLOG REFINEMENT -- Do NOT work on these until they've been refined. See Berni if you need to prioritize an async refinement on any one of these before pulling it into the sprint.

**Rolling these over to Sprint 96 epic since we didn't get to these!**

### Drupal Engineering Tickets 
- [ ] #12522 (needs refining)
- [ ] #10119 (needs refining)
- [ ] #13982 (needs refining)
- [ ] #13697 (needs refining)
- [ ] #10356 (needs refining)
- [ ] #15419 (needs refining)
- [ ] #15410 (needs refining)

**Comment by BerniXiongA6** [comment]
Hi All! @ndouglas @edmund-dunn @ariperez @tonytaylor @teeshe @stefaniefgray @TroyA6 @laflannery @joagnitti @BlakeOrgan 

As a reminder, the "Top Priority" and "Medium Priority" tickets should be worked on first before all others. I've ordered these tickets from highest priority on top of the "To Do (Current Sprint)" pipeline. 

(Note: If you've completed your Top and Medium priority sprint work, you can start pulling in refined tickets from the top of the "Ready for Sprint" pipeline.)

**Comment by BerniXiongA6** [comment]
Closing out Sprint 95 at 55pts completed (108% of sprint capacity plan)!
