### ISSUE TITLE
PAW: Post-research tasks

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#15370]
### User story

**AS A** researcher
**I WANT** to wrap up my research study
**SO THAT** I can share it with others and then move on

## Tasks
- [x] Share research report with Amanda for review prior to sharing with team
- [x] Work with @jilladams and @FranECross to schedule readout
- [x] Incorporate Amanda's feedback into report
- [x] Share research report with team, stakeholders for feedback/prep for readout
- [x] Present readout to team
- [x] Revise report per read out 
  - [x] Incorporate any additional async revisions from Danielle
  - [x] Incorporate any additional suggestions from @aklausmeier (including comment about "R1 results")
  - [x] Talk with @aklausmeier re how to share specific recommendations that will be removed from the report
- [x] When done making changes, tell Danielle so she can share report w/526-EZ team
- [x] Message Naomi Marcussen to schedule presentation for VA weekly design sync meeting
- [x] Make longer readout presentation for VA weekly design sync meeting
- [x] Remove PII from notes and post on Github, along with any other synthesis documents
- [x] Get readout presentation reviewed by Amanda, and incorporate feedback
- [x] Make short readout presentation for Sprint Demo
- [x] Copy findings into card in research repo and move to Completed column 
- [x] Delete recordings -- WAIT until after recommendations discussions w/teams
- [x] Close out ticket once once completed

## Acceptance criteria
- [ ] All above tasks completed

**Comment by cindymerrill** [comment]
Shared draft research report with @aklausmeier for review: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/pact-act-wizard/research/research-findings.md

**Comment by cindymerrill** [comment]
Updated tasks in ticket FYI @jilladams @FranECross

**Comment by cindymerrill** [comment]
After I hear back from @aklausmeier re her timing for giving me feedback, I'll work with @jilladams and @FranECross to schedule the readout.

**Comment by aklausmeier** [comment]
@cindymerrill In general, the insights are written well and like seeing participant quotes. 

A few areas that need revisions:

1. The recommendations are long and detailed and get too far into solutions. I know this is a fine line and can be difficult. Should be vague and open ended for the writer or designer (possibly in collab with SME) to make a decision on **how** to solve for the confusion/problem area.

- [ ] Example: "Consider adding more information to provide clarity around... _confusion area description here_." (might be helpful to think of this as 1-2 sentences)

2. Key Findings - we should not include any that only impacted 1-2 people

- [ ] Better suited for the "Additional Findings" section and opportunity to share quotes 

3. These research reports can be referenced years down the road by researchers and SMEs in other departments so we need to be careful about the level of detail in recommendations.

**Comment by jilladams** [comment]
@aklausmeier  - @FranECross and I have connected with Cindy about feedback / timing. Fran has gone ahead to schedule readout, Cindy will work on revisions. If we need to further iterate, let's discuss with you, me, Fran, Cindy and @DanielleThierryUSDSVA (and Dave?) after or at the end of readout to figure out how to get aligned on expectations. That'll help for this project, and Sitewide research projects in general.

**Comment by cindymerrill** [comment]
Thank you for your feedback, @aklausmeier ! 

Re your comment on the recommendations, I will work on rewriting them to be less solution-oriented. 

Re your comment about findings that impacted only 1-2 people, I normally do avoid including the feedback of small numbers of people in key findings when I'm doing a regular usability test focused on user interaction, but I've found that usability testing _content_ results in less consensus in the feedback from research participants. I'm reporting all the results because they seem valid and relevant to the research goals, and I want to document as much user feedback as possible on the content. Many of the findings and beliefs were from small numbers of participants, and if I were to move them all to the "Additional Insights" section, there wouldn't be many key findings and "Additional Insights" would be super long.

More importantly, in the case of the questions that were confusing to some participants, some were seen only by small numbers of participants, and so the 1 or 2 people might be a sizable percentage of the few who saw a specific question. In the table below, you can see in yellow highlighting how the _only_ participant who saw question S2.1.1 was confused, and 2 of 5 participants who saw question S2.2.2 were confused. I'll add into my report the total number of participants who saw each question that was confusing to some people because it wasn't everyone.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/69914583/97840146-da97-4517-9438-ca9c478219a6)

FYI @jilladams @FranECross

**Comment by aklausmeier** [comment]
@cindymerrill Seeing that chart above and understanding how many folks saw each question is insightful and a good reminder that there were several paths through content. Would be helpful to have that chart in the research folder if it's not already.

**Comment by cindymerrill** [comment]
@aklausmeier I just created that chart in my notes/analysis spreadsheet yesterday, and I was already planning to upload the new version to github.

**Comment by cindymerrill** [comment]
@aklausmeier I just finished revising the recommendations per your feedback, and now I'm going to share the report with everyone in preparation for Monday's readout. 
FYI @jilladams @FranECross

**Comment by aklausmeier** [comment]
@cindymerrill on adding screenshots inline... not sure this is the solution. I was pointing out that additional clarity might be helpful in providing context for what "R1 results pages" are. Other teams will be reading this report who may not understand how results screen differed. You can decide on best solution but additional clarity in first mention and for each listed in bulleted list in Methodology section would be beneficial for those outside our team who need the additional context.

**Comment by cindymerrill** [comment]
@aklausmeier I will clarify my use of "R1 results pages" or might go back to using "You may be eligible" results page instead.

**Comment by cindymerrill** [comment]
I revised report per feedback received during the readout and from Amanda afterwards. Only revisions left are if Danielle requests any more, as she said she might.

Now I'll start making slides to present at the VA UX Design Sync meeting...

**Comment by cindymerrill** [comment]
Revised report again with additional feedback from Amanda, which takes the place of Danielle's feedback. Shared out to both Amanda and Danielle.

**Comment by cindymerrill** [comment]
Finished drafting readout presentation for Monday's VA UX Design meeting and shared it with @aklausmeier and an Ad Hoc researcher for feedback. Will practice it tomorrow to see if it's an appropriate length.

**Comment by aklausmeier** [comment]
reviewed readout presentation and provided minor revisions to @cindymerrill

**Comment by cindymerrill** [comment]
Incorporated feedback from @aklausmeier and also from an Ad Hoc researcher.

**Comment by cindymerrill** [comment]
Made short readout presentation for Sprint Demo, copied findings into card in research repo and move to Completed column, and deleted recordings. I just need to run through my presentation slides for Demo tomorrow after I find out how much time I can have to present.

**Comment by cindymerrill** [comment]
FYI @jilladams @FranECross Finished in this sprint!
