### ISSUE TITLE
Update twitter logo on VAMC pages

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15390]
## Description
The "Get updates from >system> health care" box includes a link to Twitter. Twitter's logo recently changed and we need to update the icon.

## Current experience
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbURWIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e036fdca0f13591fef40754512fcdd97de88c067/image.png)

## Resources
- [Twitter branding toolkit](https://about.twitter.com/en/who-we-are/brand-toolkit)

## Tasks
- [x] Find instances of existing Twitter bird icon on VAMC pages
- [ ] Replace with new X icon consistent with design system
- [ ] ~~Update Twitter field label to X on VAMC System~~ Moved to a separate Drupal ticket #17323 
- [x] Updated references to Twitter in [KB: How to edit a VAMC System homepage](https://prod.cms.va.gov/help/vamc/how-to-edit-a-vamc-system-homepage)

## Acceptance criteria
- [ ] The "Get updates from >system> health care" box with a link to Twitter has the new updated X logo

**Comment by davidmpickett** [comment]
Leaving a note to say that current CAIA guidance is to style references to X as "X (formerly Twitter)"

**Comment by xiongjaneg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/15390?planning-poker) with Zenhub @eselkin @maxx1128

**Comment by xiongjaneg** [comment]
Dave got guidance from CAIA to use the language X (formerly known as Twitter)

**Comment by xiongjaneg** [comment]
@aklausmeier Apply icon USWDS v3. All logos may need a change. Need to know if all v1 icons will automatically change.

**Comment by xiongjaneg** [comment]
Fontawesome will deprecate end of May. Pending more info about VA icons from Design System.

**Comment by davidmpickett** [comment]
Complimentary ticket for standardizing the wording of link text on VAMC social links https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17509

**Comment by aklausmeier** [comment]
New va-icon component will replace current Font Awesome icons. New guidance from design team is in progress.

**Comment by laflannery** [comment]
This ticket doesn't talk about the Twitter text but [the comments do](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15390#issuecomment-1994756162) and implies this is an engineering thing but this is not hardcoded content - it's editor manageable content

**Comment by davidmpickett** [comment]
> This ticket doesn't talk about the Twitter text but [the comments do](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15390#issuecomment-1994756162) and implies this is an engineering thing but this is not hardcoded content - it's editor manageable content

Correct, it came up in conversation while refining this ticket, but I spun up a separate ticket with a way to address the wording (by removing it from editor control) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17509

**Comment by mmiddaugh** [comment]
Logo has been updated as part of font awesome component replacement

 ![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/b9b7fac5-9e1c-44b3-9d7d-931f826f376d)
