### ISSUE TITLE
FE: Events: Adapt FE Event template to handle both URL and email-address CTAs

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#15411]
### User story

**AS A** Veteran
**I WANT** to be able to respond to an Event using the method (email or URL) requested by the Editor
**SO THAT** I can ensure I'm able to join the event.

### Tasks
- [ ] updated gql
- [ ] use logic to select the one that's populated

## Acceptance criteria

- [ ] For an Event with a URL CTA, the FE renders the same as before
- [ ] For an Event with an email CTA, the FE CTA has "mailto" link that opens the user's email client with the appropriate address
- [ ] Design review
- [ ] PM review
- [ ] a11y review

**Comment by wesrowe** [comment]
@thejordanwood, do the draft ACs in this ticket seem consistent with the experience you designed?

**Comment by thejordanwood** [comment]
@wesrowe Yes, this looks good to me!

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C52CL1PKQ/p1702579365675189?thread_ts=1702578052.529349&cid=C52CL1PKQ

From light QA on the PR for this, I'd like to expand scope to cover some changes to the generated email. This is scope creep, but I don't think we'd want to ship without considering. 

As a FE user, you click "register" and there's a slight delay while your email client opens. 
When the email opens, it contains only the email address in To line. Thinking about the VA folks who will receive this email, and need to know exactly which event it's in response to, in order to process the registration, and how Veterans likely won't provide enough info on their own: I think we need to add some data to that mailto link.  Ideally: 

To: `How to sign up email value from CMS`
Subject: RSVP for `Event title`, `Event date & time`
Body: I would like to Register for `Event title` on `Event date & time`.  (`VA.gov event URL`)

We can iterate this, but @FranECross I think we should take a couple mins in refinement today to run this past Dave to see if he feels we should check with VHA DM re: minimum contents this email should include for Editors' sakes.

**Comment by FranECross** [comment]
Dave agrees to go ahead and ship per Jill's requirements above, and then get feedback.

**Comment by jilladams** [comment]
Drupal PR merged after today's daily deploy, so will be live on Prod tomorrow. FYI @chriskim2311

**Comment by chriskim2311** [comment]
FE work has been completed, currently waiting on CMS prod deploy to be able to merge FE changes. Will carry over but close early into next sprint.

**Comment by jilladams** [comment]
@chriskim2311 verified the CMS changes are live in prod, and you're 🟢 to merge!

**Comment by dsasser** [comment]
## Update 12/20/23

PR has merged, and deployed to dev and staging ONLY at this time. It should go out today during the afternoon release.

![Screenshot 2023-12-20 at 10 42 14 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/221539/623f4b68-d381-4808-848a-e3422458afe3)

**Comment by chriskim2311** [comment]
@jilladams This has merged and is out on prod. Not sure we can test it without an event. But we can let stakeholders know now.

**Comment by jilladams** [comment]
Done! We won't be able to verify til we get Editors in there to use it, so closing, and we can address any feedback in new tickets.
