### ISSUE TITLE
Draft outline of UX portion of SOP/Runbook for Drupal upgrades

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15432]
## What You Need to Know
- Part of #12238.
- This is the UX-specific "review of outline" of the runbook for how we work on Drupal upgrades.

## Acceptance Criteria
- [x] Outline of the UX-specific portion of a runbook has been drafted.
- [ ] PM/DM/PO have reviewed the outline and approved it.
- [x] Outline has been saved in Confluence.

## Tasks
- [x] Review the runbook outline drafted in #12238.
- [x] Refine outline as appropriate.
- [x] House the outline content in Confluence ([link](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2739175693/Runbook+Draft+Drupal+Upgrades))

**Comment by BerniXiongA6** [comment]
Can move to S95

**Comment by BerniXiongA6** [comment]
hi @BlakeOrgan how's it going? As this is one of our sprint goals, let us know if you'll need help with anything or if this seems to still be on track to finish this sprint?

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 Yes, this is still good to be finished this sprint!

**Comment by BlakeOrgan** [comment]
@BerniXiongA6 @EWashb 

The [UX portion of the runbook for Drupal upgrades](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2806874180/Runbook+Draft+-+UI+UX+Testing+for+Drupal+Upgrades) is in a good spot for review and can be accessed in Confluence. It's more of the whole runbook than just an outline, so I still need to make a couple of small tweaks like linking to sections referenced throughout the runbook and flushing out the two questions in the"Where" section, but it's in a good enough spot for review.

**Comment by EWashb** [comment]
This is great, @BlakeOrgan. I also appreciate you working ahead, so thank you for starting the section narratives. I have nothing to add, and I think this is precisely the kind of style, structure, and plain language we need for all of our other disciplines @BerniXiongA6

**Comment by BerniXiongA6** [comment]
Excellent work @BlakeOrgan -- we can considered this closed! Love that you got in front of this and now have a headstart for the next steps. Thank you! cc: @EWashb

**Comment by BlakeOrgan** [comment]
The runbook for [UI/UX Testing for Drupal Upgrades](https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2806874180/UI+UX+Testing+for+Drupal+Upgrades) is complete.
