### ISSUE TITLE
Spike: Review Police data available for use on VAMC police page

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15446]
## Description 
The data available from Axon needs to be made available so that we can display it on a VAMC page. For the near term, this is likely a manual CSV. The vendor API is likely not available until next spring, March or April. Lighthouse likely would not be involved until that time.

## Details received from vendor
- Directed to [Axon Records DataStore Field Mappings](https://my.axon.com/s/article/Axon-Records-DataStore-Field-Mappings?language=en_US) for data details
  - _Michelle's note: based on my quick review, there is clearly more data available in the full SQL select statement than will be needed/appropriate for our needs. We need to ensure we do not pull in PII._
- Confirmed that data will be mapped to VISN > health care system > facility > location within facility (i.e. department) 
  - _Michelle's note: Facility level should be sufficient level of granularity -  location within facility is not necessary_
- the vendor recommended we reference the [Tucson Police data and Analysis](https://policeanalysis.tucsonaz.gov/) site, which is where data shared [in this comment on #15376](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15376#issuecomment-1739863748) was found

## Additional context
- the data uses codes from two crime reporting systems:  Uniform Crime Reporting (UCR) and National Incident-Based Reporting System (NIBRS) 
   - [NIBRS User manual](https://bjs.ojp.gov/sites/g/files/xyckuh236/files/sarble/data_common/nibrs-user-manual-2021-1041521.pdf)

## Income Limits example
Income Limits also uses a CSV and a vets-api API implementation to pull / display data. 
* Josh Mills built the API in Ruby
* Daniel Sasser managed the backend data store stories

## Pending
how to identify data for the following (_Michelle's note: I've already asked if this data is expected to be in the same database or separate data source_)
- use of force and weapons discharge by Department police officers
- complaints, investigations, and disciplinary actions regarding Department police officers.
- contact information 

## Data elements 

**Required** _(based on understanding of legislature)_
- Date 
- Facility 
- number of arrests made
- number of  of tickets issued 
- number of  of prosecutions, ticketing, and other actions relating to such arrests
- number of incidents with Officer use of force 
- number of  incidents with Officer weapons discharge 
- number of Complaints again officers 
- number of Investigations against officers
- number of Disciplinary actions against officers 
- Department/Officer name/title
- Department contact info 

**Nice to have elements** _(for context)_
- total number of incidents by source (calls for service vs officer initiated)
- broad category of incident (event type)

## Tasks
- review mapping resources
- document mapping for most relevant required fields 

## Acceptance Criteria
- [x] Design developed by Jordan in #15376 is reviewed
- [x] Recommendation is made on process for translating CSV to usable format for static pages
- [x] A skeleton is started for the general file structure pending any missing information. (e.g., if the output has to be JSON, the Ruby requirements are documented)
- [x] Subsequent tickets are stubbed out as needed

## Team
- Facilities

**Comment by jilladams** [comment]
Tagged as Sprint 96 since pushed out of Sprint 95 plan, and got new info that we may be able to pull this in.

**Comment by mmiddaugh** [comment]
Additional info from the data software vendor:

regarding an API: Our plan for facilitating access to this data leverages the Axon DataStore, which is not an API endpoint but rather a Microsoft Azure SQL Database to which your team can connect using ODBC-compliant tools. This Axon DataStore Introduction article (https://my.axon.com/s/article/Axon-DataStore-Introduction?language=en_US) provides some additional details on this architecture. That article and the DataStore Field Mapping article are the best resources for seeing examples of how the data is returned when queries are run against the database. Once your team has finalized what will be displayed on the dashboards and the specific data points needed to support that display, a custom database view could be created to make it more efficient to query those specific points using a tool such as PowerBI.

As a reminder, direct access to the Axon DataStore will not be available until the completion of Phase 2 of this project.

Regarding different sources for the data, there is a separate DataStore for the Axon Records and Axon Standards products. As the RMS system, Records houses the day-to-day forms, incident reports, and investigations completed by VA police. Axon Standards is usually the source for use of force and sometimes disciplinary information/internal investigations. I would have to defer to the VA team for specific details on the data points that they are capturing in each system.

**Comment by jilladams** [comment]
If we go the vets-api route, we know we will need to: 
* Write the API
* Do backend work to sort out the datastorage in S3
* Hook up the front-end to the API

**Comment by jilladams** [comment]
From planning: so far, we believe the contact info will be a (maybe one of many) CSV, and CMS does not need to be involved.

**Comment by eselkin** [comment]
- I reviewed the sketch and comments on the [design issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15376)
- From the conversation in our last Scrum meeting, it seemed like content-build should be where we focus the effort for processing the CSV as other file formations happen here (i.e. the KISS JSON documents). We can then handle the processed data from a JSON similar to other KISS documents within react elements or wherever.
- The static portion of the file should definitely be in content-build. But have to figure out how to add a page that would be linked off the side-nav. Will ask @maxx1128 and others if necessary. The page needs to be linked off the side-nav of a facility but will not be created in pages.json because the page content does not originate from drupal. We might need to intercede between the steps of `getContentViaGraphQL` or `loadDrupal`

**Comment by jilladams** [comment]
@eselkin in scrum today, we discussed that due to the tight timing on this project, we should meet to review SPIKE findings and figure out what we still need from the data vendor, so we can get them moving. @xiongjaneg volunteered to schedule that sync, so if we are ready for it sooner than end of sprint, please let her know? The main points to understand for that purpose are: 
* Do we have a clear read on whether we will be receiving all the data we need from the vendor, to satisfy the design? 
  * If not, what's missing.
* What's our plan for how we'll access that data? In order to understand how we're going to build / dependencies, etc.

(I know you're still working through things, just FYI-ing the scrum convo.)

**Comment by eselkin** [comment]
A little clarification on the data would be nice, like:
1. Is the CSV row cumulative data for a period or is it 1 row per event that needs to be summarized/bucketed for display?
2. Do all facilities have some data?
3. What key/identifier are they using for a VAMC location?

**Comment by eselkin** [comment]
We need a ticket for 
1. Determine how to create a content-build page when no graphql is being used to generate data. We need a VA Police Page built for each VAMC facility.
2. Create a Vets-Website component for loading in JSON data for a facility Id and displaying sections and boxes within each section for the important data.
3. Complete the code to add VA Police to the Facility Sidebar (see comment above)
4. IS there possibly special code for Lovell? Does the sidebar get generated differently? Does the main page need two separate pages?

**Comment by jilladams** [comment]
Eli has reviewed:
- data we want
- Data the vendor has said they’ll provide
- the Tucson data sample - is behind PowerBI, so all we see is how the raw data has been piped into a front end, not the raw data itself.

So we will need: an example of raw data. We have some questions: 

- Is it one row per event or
- one row per facility
- or one row per month, etc. 
- have they already summarized the data into buckets. etc

Next step: @eselkin  to let @xiongjaneg  know when he's ready to review (tomorrow?) so we can move the meeting currently scheduled for 10/23.

**Comment by eselkin** [comment]
Will stop working on determining how to place the sidenav links and build pages. Will work on:
1. Creating skeleton structure for loading in a CSV and processing the unknown content into JSON
2. Adding step 1 into metalsmith
3. Skeleton structure for loading content from processed data in 1 & 2 and loading into redux (similar to KISS -- adding selectors for Facility ID to retrieve data).

Need tickets for 
1. Finalizing structure of CSV -> JSON
2. Finalizing component reading data from redux

**Comment by xiongjaneg** [comment]
Ticket 1: #15722 CSV -> JSON

**Comment by xiongjaneg** [comment]
Data questions:

Required (based on understanding of legislature)

Could be a separate file:
Date
Facility - should match the facility ID provided by facility api, otherwise would possibly need Drupal data matching

number of arrests made - should be a column of a row (each row should have all of the columns for all the data needed per date range)
number of of tickets issued - should be a column of a row
number of of prosecutions, ticketing, and other actions relating to such arrests - should be a column of a row
number of incidents with Officer use of force - should be a column of a row
number of incidents with Officer weapons discharge - should be a column of a row
number of Complaints again officers - should be a column of a row
number of Investigations against officers - should be a column of a row
number of Disciplinary actions against officers - should be a column of a row
(possibly additional columns for the nice to have elements below)

Could be separate file:
Department/Officer name/title
Department contact info

Nice to have elements (for context):
- total number of incidents by source (calls for service vs officer initiated) - ideally: one row per year with calls for service, office initiated; needs more data than summary of the required elements, might need a whole table of each event and statistics per event
- broad category of incident (event type) - ideally: a column of each event type with the number of each type

**Comment by xiongjaneg** [comment]
the example of Tuscon police data was not helpful because it was just a summary of the stats not access to the raw data

**Comment by xiongjaneg** [comment]
For Drupal, need facility ID and it should match what's in VAST, otherwise there would have to be some effort to map them

**Comment by eselkin** [comment]
If the rows are per event, in a worst-case-scenario, making sure we don't have PII in the data is best. It's likely that we just want true or false for columns. The Columns would still be the similar
datetime_utc   | system_id | facility_id | arrest_made | ticket_issued | prosecution_ticket  | officer_used_force | weapon_discharged | complaint | investigation_of_officer | disciplinary_action_against_officer | call_for_service | officer_initiated | category_of_incident
---------------|-------------|-------------|-------------|---------------|---------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|--------------------|
2023-01-01T10:00:00Z| va_10101 | vha_605 | true | true | false | NULL or empty | false | false | true |

**Comment by mmiddaugh** [comment]
> Not sure where disciplinary action is held.

Hi @eselkin, it seems there are two separate DataStores:
- Axon Records houses the day-to-day forms, incident reports, and investigations completed by VA police
- Axon Standards is usually the source for use of force and sometimes disciplinary information/internal investigations

**Comment by eselkin** [comment]
If they are different stores, that's fine. I was just being optimistic above, I'll take out the contact information from the select.

**Comment by eselkin** [comment]
Added some ACs on [finalize CSV->JSON](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15722)

**Comment by davidmpickett** [comment]
> - Q: Should we expect police data and contact information for every facility? Or at the system level only?
>    - A: _Believed to be at facility level but will confirm_

Have we received any further detail on this? Do we have an example of the raw contact data is stored?

**Comment by eselkin** [comment]
> > * Q: Should we expect police data and contact information for every facility? Or at the system level only?
> >   
> >   * A: _Believed to be at facility level but will confirm_
> 
> Have we received any further detail on this? Do we have an example of the raw contact data is stored?

Not as far as I know.

**Comment by xiongjaneg** [comment]
From Michelle and Jane conversation:
We will want the police data at the facility level. The vendor said they can provided it down to even the department level, but for our purposes, we will want it displayed at the facility level.

**Comment by davidmpickett** [comment]
Should have clarified, I'm specifically asking about the Contact Information, which seems like it's stored in an entirely different system than the other data. Do we know if the Contact Information has a facility level of granularity? Looking at the Tuscon example, there are geographical subdivisions (Wards, Divisions, etc) for incident data, but there is no Contact Information per these subdivisions. It is only displayed at the home page level in the footer

**Comment by eselkin** [comment]
> Will stop working on determining how to place the sidenav links and build pages. Will work on:
> 
> 1. Creating skeleton structure for loading in a CSV and processing the unknown content into JSON
> 2. Adding step 1 into metalsmith
> 3. Skeleton structure for loading content from processed data in 1 & 2 and loading into redux (similar to KISS -- adding selectors for Facility ID to retrieve data).
> 
> Need tickets for
> 
> 1. Finalizing structure of CSV -> JSON
> 2. Finalizing component reading data from redux

1,2 are in PR and QA
3 is not really technically possible until 1,2 passes so that the files are accessible to vets-website. So it's probably best to put this with [#15723](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15723)

**Comment by mmiddaugh** [comment]
Thank you for this @eselkin 
I'll email our list of requested data and ask for a meeting to discuss and view raw data

**Comment by jilladams** [comment]
@eselkin @xiongjaneg should this ticket stay open? Not sure if we need it to track the next steps re: the data call with Axon or not.

**Comment by xiongjaneg** [comment]
@jilladams @eselkin Our ACs are covered. Whatever comes out of the Axon call can be added to a subsequent ticket or stub out a new one. I'll close this.
