### ISSUE TITLE
Front-end: Show YouTube link on VAMC facility page

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15465]
# DO NOT MERGE until CMS PR has been merged. 
* CMS work is not in prod, so you'll need to reference the Tugboat that's built on this PR - https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15450

## User Story or Problem Statement

The "Get Updates" section on a VAMC facility should show a YouTube link when an editor has added that information in the CMS


## Acceptance Criteria
- [ ] In the Tugboat on #15450 , create YouTube links on some VAMCs, for testing content.
- [ ] An external link to a YouTube channel shows in a VAMC facility's "Get Updates" section
- [ ] Link text says, [VAMC system] YouTube similar to the other social media link text
- [ ] The link opens in a new tab attribute is noreferrer
- [ ] The link is preceded by a YouTube icon in keeping with the other social media links
- [ ] The link that is added in Drupal goes to the right page for at least three sites (testing).
- [ ] **DO NOT MERGE** until Drupal PR is merged. Let Drupal engineers know #15450 is unblocked
- [ ] Ticket is moved to "Complete Pending Integration" column for sprint close until CMS 

**Launch plan:** 
1. FE completes the work, Draft PR
2. Notify CMS to merge their PR
3. CMS merges their PR
4. FE merges
5. Notify Jane & Michelle that VHA DM can start use

## Screenshot
<img width="2168" alt="Screenshot 2023-09-29 at 8 19 34 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/22503009-00c0-46cb-9162-5fc5cf9fddd1">


## Implementation steps
It appears the changes will be needed here
- content-build/src/site/facilities/facility_social_links.drupal.liquid
- content-build/src/site/facilities/facility_social_links.drupal.liquid
- content-build/src/site/stages/build/drupal/graphql/facilities-fragments/healthCareSocialMedia.fields.graphql.js
                                                                                                                                                                                                                                                                                                              

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by jilladams** [comment]
@maxx1128 Reminder to step through the ACs here and verify what's addressed, and to notify the CMS team when your PR is ready to go, so they can merge theirs first.

**Comment by jilladams** [comment]
@maxx1128  I know we have a draft PR up failing some tests currently -- could you add a comment for end of sprint, summarizing status / blockers?

**Comment by maxx1128** [comment]
@jilladams It looks like when the pull request got rebased off of `main`, it started failing a few tests...either that or it's some carryover bugs from the recent CMS failures. Either way, I'll look into it more tomorrow. Once it's done, the CMS side can be notified and then the CMS PR can be merged before the front-end PR is.

**Comment by jilladams** [comment]
Mid-sprint: CMS has to merge for tests to pass. Michelle approved to merge.

**Comment by jilladams** [comment]
This has been merged and deployed to Prod. We won't have FE content to verify until an editor tries to use it, so: closing and we can reopen or file follow up tickets as needed.
