### ISSUE TITLE
Facilities Sprint Plan 95

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15467]
## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
- [x] 🎯 UX: #14981 (needs refining, Alexis and Jordan to meet Friday or Tuesday)
- [ ] 🎯 FE: #13359 
- [ ] 🎯 Drupal: #15503  

### VA Police Transparency #14327

- [ ] #15446 -- vendor info added, might be actionable now?

### VBA Regional Office Modernization MVP #10514

- [x] #14889  
- [x] #14899 
- [ ] UX: #11267 (potential for Dave and Alexis co-work)
- [ ] UX: #14528 
- [ ] UX: #14978 
- [x] UX: #15490 
- [ ] FE & a11y: #14940 (note: 3 of the 8 estimated points are for Laura's accessibility review)
- [ ] Drupal: #15503 
  - [ ]  STRETCH: Drupal: #11334 - blocked by 15503
- [ ] Drupal: #11628 

Now blocked on #15649 : 
- [ ] UX: #14890 (may still be blocked, need to check with Dave and Jordan)
- [ ] A11y: #14893 Optional pending Laura's Capacity

### Facility Locator
- Drupal: #14847
- A11y: #15543 

### VAMC
- [ ] UX: #14837
- [ ] FE: #15465 

### Vet Centers
- [ ] Drupal: #15422 

#### Flagged Facilities #13716
- Drupal: #15524 
- Drupal: #13842 
- [Flagged Facilities tickets](https://github.com/department-of-veterans-affairs/va.gov-cms/labels#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?labels=flagged%20facilities) for coordination with CMS Support

#### Accessibility Debt
- [ ] Drupal: #12666 
- [ ] FE: #12882

**Comment by mmiddaugh** [comment]
@xiongjaneg @jilladams 

There are a few issues still in the Current Sprint, not started column. #14528 is going to roll - will any others? 

---

Sprint priority suggestions
- FE: #13359 since it's already been in limbo for too long. We should assess whether our query is functional as is or if it will need additional work while it's on the radar
   - otherwise #14940 
- UX: #14981 (this isn't defined yet but it seems like it can be ready before the sprint begins)
  - otherwise UX: synthesize previous editorial research / make recommendations #14528 - will rolls from this sprint 
- Drupal: #14699 may have already been started. We need to pull in #14978 as its buddy (I'll pitch hit if needed)

---

- This 2-pointer isn't on the draft plan but looks like a leftover from the Services push -> TIC intercepts of api push should put item back in queue #14847 (2)
- May want to grab this one as part of Flagged Facilities queue-> [Manchester Vet Center - Portsmouth-Newington Vet Center Outstation URL change #15524 (?)

---

I'm inclined to hold these until the next Sprint
- #15446 until we have more information, otherwise it feels like we'll just have to revisit it later
- #15424 because it is blocked by the Drupal work in #15422
- #14700 as it needs additional refinement 
- #14957 because it is blocked by 14704

**Comment by jilladams** [comment]
@mmiddaugh Yes, I forgot we killed the live meeting for mid-sprint, and don't have Scrum on Thurs with refinements. So: I'm behind on getting Facilities mid-sprint updates this sprint. It's queued as a topic in scrum tomorrow am to confirm what's at risk for end of sprint.

**Comment by davidmpickett** [comment]
#11334 says it is blocked by #15503 - so I don't think #11334 can be a sprint priority. Does seem to indicate that 15503 should be refined and pulled into this sprint though

**Comment by jilladams** [comment]
^ Confirmed: https://dsva.slack.com/archives/C0FQSS30V/p1696954412127839

Updated plan. We'll need to get #11503 refined, in order to prioritize. Have asked Drupal folk to take a look, and we'll refine live in planning first half if necessary.

**Comment by jilladams** [comment]
Mental Health numbers news: Office of Mental Health feedback led to new tickets: 
* #15647  -- important for this sprint
* #14215 -- blocked by #15647, but should move in this sprint, so pulled in (tbd confirming load)
* #15648 -- should fast follow, either in this sprint or in S96. Needs refining.
