### ISSUE TITLE
CMS Sprint 96 Plan (10.25.2023 - 11.7.2023)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15477]
# Sprint 96 Goals & Priorities
_At the end of this sprint, what do we want to have accomplished/delivered?_
- [x] Goal 1: Create plan for D10 Announcement using Sitewide Alerts #15862
- [x] Goal 2: KB experience enhancement: #15859 

**Notes:** 
<details><summary>**Sprint 96 Prioritization Notes**</summary>

- [ ] Capacity: All Points CMS Team Can Take On in S96 = currently 57.1 pts
> All Eng = currently 31.1 pts
> All UX = currently 13.6 points
> All Support = currently 3.4 pts
> A11y = currently 2 pts

</details>

# Sprint 96 Committed Work

### D10 readiness (Q4 Goal)
Eng
- [x] (3) #14640 (blocked by 14639) -- support from IAM to deploy for test.prod will occur on 11/2
- [x] (1) carry over from S95 to finish work with IAM #14725

UX
- [x] (5) #15862 (Sprint Goal)

Eng/a11y
- [x] (2) #15923

### D10 Runbook Deliverable (Q4 Goal)
a11y
- [ ] (5) #15857 -- Laura can start on it in S96, but can finish in S97 if needed (Carry over to S97)

### Datadog Monitoring Expansion (Q4 Goal)
DevOps
- [ ] (8) #15542 (carry over to S97)

Support
- [ ] (5) #15470 (carry over to S97)

### Alt Text and Image Upload Enhancements (Q4 Goal) 
Drupal
- [x] (8) #15436 
- [x] (5) #15962

Research
- [x] (2) #15861 (BX note for Jo: only need to complete step 1 of this ticket in Sprint 96. Can finish the rest in Sprint 97. We just want to make sure Step 1 is completed ahead of Engineering-related work)

a11y
- [x] (5) #15549 (BX note for Laura: only expectation is 2-2.5 pts partially completed this sprint and can carry over rest into S97 if need be)

Product
- Once ticket # 15549 is complete, product can create a rollout strategy (be sure to time things with other product teams' deadlines too)

### Knowledge-base Enhancements
UX
- [x] (3) #15859 (Sprint Goal)
- [ ] (5) #15824 (Jo can start working on this if it coincides with ticket 15859 work, but can be finished in Sprint 97) (carry over to S97)

### Improvements to Content Release
- [ ] (8) #6434 (carry over to S97)
- [ ] (5) #15301 (carry over to S97?)

### Defects, hurdles
- [x] (2) #15882 (resolves #15099 and #15201)

### Keep the Lights On
DevOps
- [ ] (2) #15854 (carry over to S97)
- [x] (8) #15852 

Drupal
- [x] (1) #15840 

### Dependencies (dependabot)
Eng
- [X] (9) Dependabot PRs merged

### Collab Cycle / CMS Governance
- #12961 -- note to berni: talk to erika about when to bring this in / need to chat with Amanda K. (need to know cms touchpoints for all practice areas)

### CMS Design System Improvement
- [X] (5) #15309 

### Help clients and stakeholders hit their objectives
Product/Delivery
- [x] (1) #15683 (High Priority for Facilities)
- [ ] (1) #15050 - low (carryover to S97)
- [ ] (1) #15692 - low (carryover to S97)
- [ ] (1) #15643 (carryover from S95 and finish reviewing in S96) - low

Drupal
- [x] (2) #15721
- [x] (5) #15804

Product/Delivery owns (need UX and a11y review)
- [ ] (1) Carry over from S95 #15328 

### General
Product
- [ ] (0) #15805 (carry over to S97)
UX
- [x] (3) #15819 

Eng
- [ ] (0) #15590 -- continue making progress, almost done onboarding (carry over to S97)

### Unplanned Work Completed
- [x] #16036 Content-Build (DevOps, Content-build, Unplanned work)
- [x] #16024 Change image list export to batch (Drupal, unplanned)
- [x] #16017 Fix D10 incompatibility (Drupal, unplanned)
- [x] #15984 Duplicate users appearing in Drupal admin "people" view (Drupal, Defect, Unplanned)
- [x] #15979 Reusable checkbox missing from add doc form (drupal, defect, unplanned)
- [x] #15898 Tugboat Database Backup Job Fails Due to Upgrade Changes (devops, unplanned)
- [x] #14342 Update codeowners for va.gov-cms repo (unplanned)
- [x] #15903 Check for the presence of the `alert type` option and try to scroll to it in the VAMC operating-status-and-alerts Cypress test. (unplann ed, QA)
- [x] #15883 Content-Build file download log too verbose. (DevOps, unplanned)

**Comment by EWashb** [comment]
There are some KB enhancement things that will likely need to be ticketed coming out of @joagnitti work in Sprint 95. Some of that will be design-dependent and will need @BlakeOrgan's assistance. Not sure if that's doable within this sprint cc: @BerniXiongA6

**Comment by EWashb** [comment]
For everyone's awareness on the Siteimprove mention above:  we will need to determine a date to start month-long trial with the pre-publishing token. So there is a fair amount of technical feasibility that will need to be determined. Then, if the technical portion goes right, is there a demo environment that we can set up to allow folks to see how the deep linking would work within current state of the CMS. It doesn't have to be a rush to start this right now, we just need to create a plan at some point soon and share that timeline/plan with VHA DM. See inside the epic ticket for more notes/context.

**Comment by EWashb** [comment]
Remember that the runbook does not have to be delivered at the same time as the upgrade. This can be an item that we can continue working on after retro-ing the overall D10 process as long as it is delivered by Q4 end.

**Comment by BerniXiongA6** [comment]
@EWashb with the exception of some Product tickets I still need to write up to be refined this sprint, this is where Sprint 96 is landing. Let me know if this meets your approval to proceed with the sprint goals and committed work? Don't worry about the total points calculated in this epic above; we'll likely be closer to a Sprint 96 commitment of 60-65 total pts given the known reduced capacity of All CMS Team at 85% due to expected time off.

**Comment by EWashb** [comment]
@BerniXiongA6 apologies...I missed this. I wanted to commit here for the record, this sprint plan was approved

**Comment by BerniXiongA6** [comment]
Closing Sprint 96 -- we ended at 96 points closed, met all our Sprint Goals, and finished at 168% of sprint capacity plan! Incredible job to the team! cc: @EWashb
