### ISSUE TITLE
CMS Sprint Plan 97 (11.8.2023 - 11.21.2023)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15478]
# Sprint 97 Capacity
_All Points CMS Team Can Take On in S97 = 58.1_
> All Eng = 38.6
> All UX = 14.2
> All Support = 3.6
> A11y = 1.8

# Sprint 97 Goals & Priorities

## SPRINT 97 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [x] Goal 1: Supported final round of testing for D10 issues #16047 - Edmund will close this out but 8 points were completed in S97.
- [x] Goal 2: Created D10 banner alert for CMS users #16051 
- [x] Goal 3: (3) Completed 11/16 meeting to update VA IAM Prod SAML Public Certificate for D10 readiness #16038

## SPRINT 97 PRIORITIES
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY2024 goal, 3) the rest of the tickets in this section:_
#### D10 Readiness and Launch (CY2024 Q4 Goal) (Epic #14410)

Eng
- [ ] (8) #16047 - SPRINT GOAL - Edmund will close this out but 8 points were completed in S97.
- [x] (3) #16038 - SPRINT GOAL
UX
- [x] (2) #16051 - SPRINT GOAL

#### D10 Runbook Deliverable (CY2024 Q4 Goal) (Epic #12238)
a11y
- [x] (3) #15857 (Laura started this in S96 and will finish in S97 -- full points can count in S97)

#### Datadog Monitoring Expansion (CY2024 Q4 Goal)
DevOps
- (5) #15307 (we can carry over to S98)
- [x] (4) #15542 (carryover from S97 - 4 pts left to complete in S97)

UX
- [x] (5) #15548

Support
- [x] (5) #15470

#### Alt Text Validation (CY2024 Q4 Goal) (Epic #15785) 
Drupal
- [x] (5) #15783

#### Knowledge Base Enhancements (Epic #14069)
UX
- [x] (5) #15824

#### Collab Cycle (#14013) / CMS Governance (#14012)
UX
- [x] (3) #15705
- [x] (3) #15706
- [x] (5) #16026

#### CMS DesignOps (Epic #12843)
- None at this time

#### Improvements to Content Release (Epic #14016)
- [x] (8) #6434
- [ ] (5) #15301 (carry over from S97)

#### Dependencies / Dependabot PRs
- [X] (average 4 pts per Dev) - Actual PRs (1 point each) will vary by sprint -- In S97, there were 15 pts completed 

#### Help Partners, Clients and Stakeholders Hit Objectives
DevOps (Eric)
- [x] (5) CMS Infrastructure (AP) #16052

Product
- [ ] (1) Finish reviewing #15643 (carryover from S96) - carryover to S98
- [ ] (1) #15050 - low - carryover to S98
- [ ] (1) #15692 - low - carryover to S98

#### General
- [ ] (0) #15974
- [ ] (0) #15805
- [x] (0) #15590 -- continue making progress, almost done onboarding (carryover from previous sprint/s)

## SPRINT97 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed

DevSecOps
- [x] (1) #15953 
- [x] (2) #15954

Drupal testing
- [x] (5) #10356

Defects
- [x] (5) #13550 
- [x] #16119 
- [x] #16123 
- [x] #16126 #16134 
- [x] #16098 
- [x] #14643 
- [x] #16061 
- [x] #15955 
- [x] #15554 
- [x] #15813

Dependabot
- [x] #16193
- [x] #16179  
- [x] #16180 
- [x] #16166 
- [x] #16168 
- [x] #16092 
- [x] #16131 
- [x] #1750 
- [x] #15878 
- [x] #16113 
- [x] #16115 
- [x] #15914 
- [x] #16096 
- [x] #16091 
- [x] #16097 

## REFINED AND READY
_These are candidates for Sprint 97 if Sprint Goals and Priority tickets have been completed and you have the bandwidth to take on work:_
 
#### Open DevSecOps Tickets (carryover these tickets to S98)
- [ ] (5) #14492
- [ ] (8) #13834
- [ ] (5) #13975
- [ ] (3) #11632
- [ ] (8) #7674
- [ ] (5) #7673
- [ ] (5) #11629
 
#### Open Drupal Engineering Tickets (carryover these tickets to S98)
- [ ] (8) #10119 
- [ ] (3) #14765 
- [ ] (3) #12674

**Comment by olivereri** [comment]
I'd like to get this issue refined and prioritized in Sprint 97's plan:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16038

This is high priority and includes a scheduled date.
