### ISSUE TITLE
CMS Sprint Plan 99 (12.6.2023 - 12.19.2023)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#15480]
# Sprint 99 Capacity
_All Points CMS Team Can Take On in S99 = 63.4_
> All Eng = 44.6
> All UX = 14.3
> All Support = 3
> A11y = 1.5

# Sprint 99 Goals & Priorities
## SPRINT 99 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [x] Goal 1:  #16317
- [x] Goal 2: #7673

## SPRINT 99 PRIORITIES - not yet finalized
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:_

### D10 Runbook Deliverable (Epic #12238)
- [ ] Slotting for Sprint 100

#### Post D10 Launch (CY2023 Q4 Goal) (Epic #16048)
- [x] (5) #16241
- [x] #16262
- [x] (2) #16265 
- [x] (5) #16317

Defect
- [ ] BLOCKED but keep an eye on this (from D10 testing) #16107 -- BX: carry over to the next sprint OR keep it on the roadmap to keep an eye on

#### Datadog Monitoring Expansion (CY2023 Q4 Goal) - (Epic #11928)

- [ ] (3) #11281
- [x] (5) #7673 - Sprint Goal (S99)
- [ ] (5) #13975 

UX
- [x] #16334

#### Alt Text Validation (CY2023 Q4 Goal) (Epic #15785) 
- [ ] Product #15944
- [ ] Product to meet with Edmund to discuss unrefined Alt Text tickets (need to understand what is critical for launch)

#### Knowledge Base Enhancements (Epic #14069)
UX
- [x] (3) #16163
- [x] (2) #16175
- [x] (3) #16286 
- [x] (3) #16285 

#### Collab Cycle (#14013) / CMS Governance (#14012)
- [x] (3) #16320 
- [ ] (3) #16321 

#### CMS DesignOps (Epic #12843)
- None for this sprint

#### Improvements to Content Release (Epic #14016)
- None for CMS this sprint, AP working on

#### ATO Documenttion (CY2023 Q4 Goal) (Epic #12122) 
- [x] Marcia and Nate beginning recurring meetings, beginning this Thursday, Dec 7

#### Dependencies / Dependabot PRs
- [ ] (average 4 pts taken on per Dev) - Dependabot PRs = 1 point each. Total points completed will vary by sprint. Berni to update actual numbers at end of sprint.

#### Help Team, Partners, Clients and Stakeholders Hit Objectives
DevOps
- [x] (5) #16207
- [ ] (5) #16342 
- [ ] (5 pts left) #13834 (In Progress w/ John) -- 3 pts completed in S98

Product
- [x] (1) Finish reviewing Review of new or updated KB article : VA Benefits taxonomy #15643 (carryover from S96) - carryover to S98
- [ ] (1) Create new KB article or update existing article : Outreach Hub: How to archive Outreach Materials #15050 - low - Berni assigned self to ticket in S99, will carry over to S100
- [x] (1) Update existing KB article : VA Health Connect phone number change requests  #15692 - low - carryover to S98

#### General
- [ ] (0) Onboarding Marcia Ortiz #15974
- [ ] (0) [Product] CMS product documentation needs updating #15805 
- [x] (4) #15580

## SPRINT 99 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. It's hard to predict what will actually come in, but we're averaging about 20-30 points of unplanned yet necessary Dev work each sprint. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed
- [x] #15940 
- [x] (5) #7673
- [x] #16228 (John)

## REFINED AND READY
_These are candidates for Sprint 99 if Sprint Goals and Priority tickets have been completed and you have the bandwidth to take on work:_ 

#### Open a11y Tickets
- [ ] (5) #2428
 
#### Open DevSecOps Tickets 
- [ ] (5) #13975
- [ ] (8) #7674
- [ ] (5) #11629
 Datadog
- [ ] (5) #8866
- [ ] (5) #10462
- [ ] (5) #7674
- [ ] (5) #11629
- [ ] (5) #15307 

#### Open Drupal Engineering Tickets 
- [ ] (3) #14765 
- [ ] (3) #12674

### Engineering Tickets that Need Refining
DevOps:
- [ ] #15646 
- [ ] #15941 (could be an async pre-refinement w/ DevOps)
- [ ] #16136  (could be a good one John)

Drupal:
- [ ] #14666 (Nate meeting w/ Blake and Laura to nail down what we should cover for testing. Could be a good pair programming w/ Edmund and John)
- [ ] #16333
- [ ] #15146 
- [ ] #10113 
- [ ] #12522
- [ ] #15555
- [ ] #15942 
- [ ] #14851
