### ISSUE TITLE
Allow Content Admins to view Content Model Documentation reports

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#15492]
## User Story or Problem Statement

As a Content Designer overseeing implementation of Drupal entities on a VFS Product team , I need to visualize connections between Drupal entities and search for instances of fields across Drupal entities so I can ensure my product is implemented correctly and follows established best practices.

Currently viewing these reports requires me to puppet an Admin account on Staging or Training which may be out of sync with Prod. Puppeting an admin also introduces a ton of other menu items compared to what I'm used to as a Content Admin. It would be nice to have access to these reports in Prod. Now that Drupal is the source of truth for the Content Model, access to these reports is vital for the work of Content Designers.

## Acceptance Criteria
- [ ] A user with the role Content Admin can view admin/reports/content-model

## Implementation steps

![Screenshot 2023-10-02 140136](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/ab6a97b2-3c40-4668-969d-1ee591f15893)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by jilladams** [comment]
I have updates here from Scrum of Scrums today that I'll share back to @davidmpickett and @swirtSJW in 1:1s this week. This ticket is likely iceboxed until further notice, as CMS team migrates to Platform and envisions the future of content model documentation.
