### ISSUE TITLE
[Aging Content] Drupal: Implement Aging Content Notifications for Home Page Promo and Home Page News Spotlight Blocks

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15507]
## Status

**[2024-07-08]** Per Michelle M, we're holding on this for now. We may decide to close this in the near future. Also, converted to an Epic and if we resurrect, we can create associated tickets.
**[2024-03-27]** Will be in Stretch/Next Sprint as a candidate for Sprint 108. Daniel will pull into 107 toward the end of the sprint if he's able to, but it's not formally planned for that sprint.

## Description

Using the new Framework developed in Initiative 1, wire up Home Page News Spotlight Block and Home Page Benefit Promo Block to the new framework, and implement:
- a 30-day expiration for each block content type
- a 3 days prior to the expiration date warning notification email 
- an expiration date warning notification email

```[tasklist]
### ACs
- [ ] Configure Home Page Benefit Promo blocks with a 30 day expiration
- [ ] Configure Home Page News Spotlight blocks with a 30 day expiration
- [ ] "Expired" email message is sent on the content's expiration date, and then daily to all editors of published, expired Home Page Benefit Promo Blocks and Home Page News Spotlight blocks 
- [ ] "Expiring" email message is sent three days prior to expiration date, and then daily to all editors of published, expiring Home Page Benefit Promo Blocks and Home Page News Spotlight blocks 
- [ ] Recipient for both email notification types is editor in the the last saved by an editor  field (the user who last saved the node), rather than the original node author.
- [ ] Enter a list (TBD) of allowed recipients such that the notifications can be delivered to hand-picked users only, allowing for a staged roll out to early adopters
```

## User Stories

**AC1: Editor receives notification email warning of upcoming expiration date 3 days prior to expiration**
**AS A** PM/PO
**I WANT** editors who have published a Home Page News Spotlight Block and/or a Home Page Benefit Promo Block to receive a warning notification email 3 days prior to the content's expiration date
**SO THAT** Veterans, their caregivers, family and survivors see only up-to-date, relevant information in VA.gov

**AC1: Editor receives notification email warning of upcoming expiration on the actual expiration date (day 30)**
**AS A** PM/PO
**I WANT** editors who have published a Home Page News Spotlight Block and/or a Home Page Benefit Promo Block to receive a warning notification email on the content's expiration date - in this instance, day 30
**SO THAT** Veterans, their caregivers, family and survivors see only up-to-date, relevant information in VA.gov

#### Expiring Email Notification aka 3 days prior to expiration

Subject: Please update or archive your Home Page Benefit Promo Block by [Day 30 Date]

Please plan to archive, or edit to extend display of, your published Home Page Benefit Promo Block titled [content title / link] by [Expiration Date aka Day 30].

As a reminder, Home Page Benefit Promo Blocks are used to help Veterans learn about new or changed benefits and services that may affect them. The intent here is to provide just enough information to help Veterans decide if they want to read more on another page and should display for 30-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the content, simply edit with a comment to that effect, and the 30-day countdown window will reset.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

**Coming Soon:**

In the near future, Home Page Benefit Promo Blocks will be permanently auto-archived at the end of Day 30, unless edited to reset the 30-day timeframe. We will give ample notice before this auto-archival feature is released.

**Need help?**

If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.

If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

#### Expired Notification Email aka sent on day 30 / expiration date

Subject: Action Needed: Your Home Page Benefit Promo Block has displayed for thirty (30) days

Your Home Page Benefit Promo Block has displayed for thirty (30) days. In order to meet the purpose of this type of content——please plan to archive, or edit to extend display of, your published Home Page Benefit Promo Block titled [content title / link] by [date].

As a reminder, Home Page Benefit Promo Blocks are to be used to help Veterans learn about new or changed benefits and services that may affect them. The intent here is to provide just enough information to help Veterans decide if they want to read more on another page, and should display for 30-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 30-day countdown window will reset.

**Coming Soon:**

Home Page Benefit Promo Blocks will be permanently auto-archived at the end of Day 30, unless edited to reset the 30-day timeframe. We will give ample notice before this functionality is implemented.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

**Need help?**

If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.

If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).
__________________________________________________________________________________________________________________________________

#### Expiring Email Notification aka 3 days prior to expiration

Subject: Please update or archive your Home Page News Spotlight Block by [Day 30 Date]

Please plan to archive, or edit to extend display of, your published Home Page News Spotlight Block titled [content title / link] by [Expiration Date aka Day 30].

As a reminder, Home Page News Spotlight Blocks are to be used as a space for curated news article ‘teasers’ from news.va.gov, and should display for 30-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the content, simply edit with a comment to that effect, and the 30-day countdown window will reset.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

**Coming Soon:**

In the near future, Home Page News Spotlight Blocks will be permanently auto-archived at the end of Day 30, unless edited to reset the 30-day timeframe. We will give ample notice before this auto-archival feature is released.

**Need help?**

If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.

If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

#### Expired Notification Email aka sent on day 30 / expiration date

Subject: Action Needed: Your Home Page News Spotlight Block has displayed for thirty (30) days

Your Home Page News Spotlight Block has displayed for thirty (30) days. In order to meet the purpose of this type of content, please plan to archive, or edit to extend display of, your published Home Page News Spotlight Block titled [content title / link] by [date].

As a reminder, Home Page News Spotlight Blocks As a reminder, Home Page News Spotlight Blocks are to be used as a space for curated news article ‘teasers’ from news.va.gov, and should display for 30-days, unless there’s a compelling reason to extend display of the content.

If you do need to extend the display of the banner, simply edit with a comment to that effect, and the 30-day countdown window will reset.

**Coming Soon:**

Home Page News Spotlight Blocks will be permanently auto-archived at the end of Day 30, unless edited to reset the 30-day timeframe. We will give ample notice before this functionality is implemented.

For more information, you can read this [Knowledge Base article](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review) for tips and best practices to manage compliance.

**Need help?**

If you are a Vet Center Director or Outreach Specialist who needs assistance accessing Drupal CMS, please email the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).

If you want to refresh your skills, need ideas, or have questions about creating content for your webpages, you can find How to Guides and Training videos in the [Drupal CMS Knowledge Base](https://prod.cms.va.gov/help/vet-centers) or drop in during office hours.

If you received this email and no longer have a role at a Vet Center, please inform us by emailing the CMS Support Team at [support@va-gov.atlassian.net](mailto:support@va-gov.atlassian.net).
```

**Comment by jilladams** [comment]
@FranECross can you clarify on this ticket -- it's in sprint 2, but assigned to you. Should we have in sprint yet? I forget what was happening with this one.

**Comment by FranECross** [comment]
@jilladams Thanks for pinging me on this one! We shouldn't have it in Sprint 2 because it's been deprioritized due to the design work. I should have scooted it back to Ready, at the bottom of the pile and will do that now.

**Comment by FranECross** [comment]
@dsasser Just an FYI - per Michelle M., at this time we're not going to move forward with wiring up these blocks to Aging Content Notifications. Not sure if/when we'll resurrect.

**Comment by FranECross** [comment]
Closing per note above. We will resurrect or create a new ticket if this comes up in future.
