### ISSUE TITLE
[BLOCKED] [EPIC] [Events v3 - Future State] Publish Events to multiple Facilities + Outreach Events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15562]
## Top-line Description / Goal(s)
Expand Events to allow selection of multiple VAMCs where Event should appear.

By the time we prioritize this, VAMCs may no longer be the only Events type. We may also need to consider Vet Centers, VBA facilities / Regional Offices, or NCA, which will expand scope and stakeholders.

#### Monthly project updates:

---

## Headlines
**VA stakeholders** - VHA DM

**OCTO lead** - Michelle Middaugh

**Is this project tracked to an upcoming event or congressional deadline?** - No.

## Details

**Which OCTO team should do this and what is currently on their roadmap?** - Sitewide

**Which OCTO priority does this work support?** - 

**What is the user impact and scale of impact?** - 

**Who would manage this product long term?** - Public Websites

**How much leverage will this create to solve more problems in the future?** -  

**How great is the cost of inaction? (e.g., Can it wait? Must it be done by us?)** - 

---
## Business Case
Epic #13527 implemented single VAMC + Outreach Events selection on Events, including breadcrumbs / URL paths. 

We now want to expand this functionality to allow VAMC editors to select multiple VAMCs, in addition to Outreach Events calendar, for a single event. This should include: 
* CMS work to update the Events form to handle multi-VAMC selection, including GraphQL query updates
* UX / IA / Drupal work to figure out how URL paths can / should work for a single Event that appears in multiple listings, which will affect breadcrumbs
* FE work to account for breadcrumbs
* Change management: Coordination with VHA DM (on behalf of VAMCs), KB article updates, and coordinated launch planning.
### CONSIDERATIONS
* Lovell
* Breadcrumbs
* IA
  
### User Story or Problem Statement

AS A VAMC editor, 
I WANT the ability to publish an event to multiple VAMCs in my System, and to the Outreach Events calendar
SO THAT we have a single source of truth for Events. 

### Affected users and stakeholders

* VAMC Events editors 
* Public Websites team, owners of Events 

## Acceptance Criteria
- [ ] Events may be published to a single VAMC or multiple VAMCs, as well as the National Outreach Events calendar
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by FranECross** [comment]
@jilladams do you know if Dave/Michelle have made a decision on whether this is facilities or PW work? I can always add to the next Prod Sync if not. Thanks!

**Comment by jilladams** [comment]
As far as I know, it's not an urgent priority, and Dave's idea is that whichever team it becomes important for first could carry it out.

**Comment by mmiddaugh** [comment]
Noting that this work should be able to facilitate cross-facility posting, regardless of facility type (i.e., a VAMC can add a Vet Center event to their page, or VBA could post event which is co-promoted with VBA)
