### ISSUE TITLE
VAMC "Learn more" CTAs should be styled as links, not buttons

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15598]
## Issue Description
The Facilities team recently became aware of the button/link design shift which will impact various CTAs throughout the VAMC product. 

## Current behavior: 
![image](https://user-images.githubusercontent.com/55411834/113603223-e9b43580-9600-11eb-8fb9-68c6c6fa6f6b.png)

## Expected behavior
This issue will address VAMC "Learn more..." CTAs which behave as links and should be styled accordingly: 
![image](https://user-images.githubusercontent.com/55411834/113603271-fafd4200-9600-11eb-97f0-737675171198.png)

## Tasks

- [ ] Replace the "Learn how to request chaplain services during your stay at VA Pittsburgh." CTA as seen on the "Chaplain services and chapels" accordion under "Prepare for your visit" with an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, department-of-veterans-affairs/va.gov-team#4795
- [ ] Replace the "Learn more about the history of Veterans Affairs" CTA as seen on the [History page](https://www.va.gov/pittsburgh-health-care/history/) with an active link styled according to the  [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, department-of-veterans-affairs/va.gov-team#4795
- [ ] Replace the "Find out more about volunteering to participate in research" CTA as seen inside the "Volunteer for medical research studies" accordion on the [Volunteer or donate page](https://www.va.gov/pittsburgh-health-care/work-with-us/volunteer-or-donate/) with an active link styled according to the [Design system](https://design.va.gov/components/action-links#how-to-use-other-links), using Source Sans Pro (Bold), underlined, 16px, department-of-veterans-affairs/va.gov-team#4795

## Acceptance Criteria
- [ ] The "Learn how to request chaplain services during your stay at VA Pittsburgh." CTA as seen on the "Chaplain services and chapels" accordion under "Prepare for your visit" is styled as an active link 
- [ ] The "Learn more about the history of Veterans Affairs" CTA as seen on the [History page](https://www.va.gov/pittsburgh-health-care/history/) is styled as an active link
- [ ] The "Find out more about volunteering to participate in research" CTA as seen inside the "Volunteer for medical research studies" accordion on the [Volunteer or donate page](https://www.va.gov/pittsburgh-health-care/work-with-us/volunteer-or-donate/) is styled as an active link
- [ ] The "See all locations" CTA as seen on a [VAMC System Page](https://www.va.gov/northern-california-health-care/#locations)
- [ ] The "See all stories " CTA as seen on a [VAMC System Page](https://www.va.gov/northern-california-health-care/#stories)
- [ ] The "See all events" CTA as seen on a [VAMC System Page(https://www.va.gov/lovell-federal-health-care-va/#events)
- [ ] The active links listed above are styled according to the [Design system](https://design.va.gov/components/action-links#how-to-use-other-links) and use Source Sans Pro (Bold), underlined, 16px, department-of-veterans-affairs/va.gov-team#4795

**Comment by davidmpickett** [comment]
Removed section about user-input instances that will be handled by #15068

## Places to double-check after #15068
- [ ] "Learn how to request chaplain services during your stay at VA Pittsburgh." CTA as seen on the ["Chaplain services and chapels" accordion under "Prepare for your visit" ](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#chaplain-services-and-chapels)
- [ ] "Learn more about the history of Veterans Affairs" CTA as seen on the [History page](https://www.va.gov/pittsburgh-health-care/history/) 
- [ ] "Find out more about volunteering to participate in research" CTA as seen inside the "Volunteer for medical research studies" accordion on the [Volunteer or donate page](https://www.va.gov/pittsburgh-health-care/work-with-us/volunteer-or-donate/#volunteer-for-medical-research-studies-4079)

**Comment by eselkin** [comment]
Pointed a 2, but it takes about a 2 away from the [VAMC icon ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17855)

**Comment by randimays** [comment]
@thejordanwood These "See all" links in prod currently take up full width and are centered on smaller screens.

<img width="679" alt="Screenshot 2024-05-17 at 2 08 16 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/fdd90544-06a7-4c57-92e6-465896c453d8">

Since we're changing to an active link instead, should it be centered on smaller screens or left-aligned?
<img width="646" alt="Screenshot 2024-05-17 at 2 08 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/422268d3-5120-40c2-8262-8799d3879feb">
<img width="647" alt="Screenshot 2024-05-17 at 2 08 25 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/87c131a2-b57b-4ded-9f6e-dc4493415e32">

**Comment by thejordanwood** [comment]
@randimays Let's left align it to keep it consistent with how we handle other links, like the top task links on these pages.

**Comment by randimays** [comment]
Successfully validated in production. Closing!
