### ISSUE TITLE
Resolve content model tentacles on 10089 Events checkbox

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15641]
## Description
#10089 added an Events checkbox to the Events form. 
This change shipped and broke the content model in the front end in 2 known places: 

1. [Outreach Materials](https://www.va.gov/outreach-and-events/outreach-materials/) -- not displaying Publications in [VA.gov](http://va.gov/) frontend
2. VAMC Stories ([example](https://www.va.gov/alaska-health-care/stories/learn-how-to-cook-with-healthy-teaching-kitchen/)) -- "See all stories" link is missing at the foot of the page.
3. We also need to re-verify Lovell, per Tim, though still no smoking gun for what that might mean

## Slack threads
[Topline for DaveC](https://dsva.slack.com/archives/C52CL1PKQ/p1696976116933149)

## Engineering notes

<details>
<summary>Feature Toggle may still be "ON" in prod, despite the revert of our code which created it.</summary>

We need to be careful about the `FEATURE_EVENT_OUTREACH_CHECKBOX` feature toggle being deployed as "enabled". The latest CMS mirror is showing it as enabled, but unsure if this was because the snapshot was taken before the revert was deployed.

</details>

<details>
<summary>Everywhere field_listing is used in templates/queries</summary>

```
10 results - 6 files

src/site/layouts/news_story.drupal.liquid:
  45                      </div>
  46:                     {% if fieldListing.entity.entityUrl.path %}
  47:                         <a onClick="recordEvent({ event: 'nav-secondary-button-click' });" class="vads-u-display--block vads-u-margin-bottom--7" href="{{ fieldListing.entity.entityUrl.path }}" id="news-stories-listing-link">See all stories</a>
  48                      {% endif %}

src/site/layouts/publication_listing.drupal.liquid:
  87                {% for entity in outreachAssetsDataArray.entities %}
  88                {% for entity in outreachAssetsDataArray.entities %}
  89:               {% if entity.fieldListing.targetId == entityId %}
  89                {% assign topicsString = entity.fieldLcCategories | buildTopicsString %}
  90                {% assign topicsString = entity.fieldLcCategories | buildTopicsString %}

src/site/stages/build/drupal/process-lovell-pages.js:
  69  
  70  
  71:   if (page?.fieldListing?.entity?.entityUrl) {
  72:     page.fieldListing.entity.entityUrl.path = getLovellVariantOfUrl(
  73:       page.fieldListing.entity.entityUrl.path,
  73        variant,
  74        variant,

src/site/stages/build/drupal/graphql/newStoryPage.graphql.js:
  33      }
  34:     fieldListing {
  35        entity {

src/site/stages/build/drupal/graphql/nodeEvent.graphql.js:
  114      }
  115      }
  116:     fieldListing {

  116        entity {
  117        entity {

  284      }
  285      }
  286:     fieldListing {
  286        entity {
  287        entity {

src/site/stages/build/drupal/graphql/file-fragments/outreachAssets.graphql.js:
  13          fieldDescription
  14:         fieldListing {
  15            targetId

```

</details>

## ACs.

- [x] #10089 changes are present and 
  - [x] Outreach materials present Publications correctly at /outreach-and-events/outreach-materials/
  - [x] Stories display a link at page footer to "See all stories"
  - [x] Lovell is verified. Talk to Tim and maybe Ryan to clarify what needs verified.
- [x] Ensure the feature toggle `FEATURE_EVENT_OUTREACH_CHECKBOX` does not deploy as 'enabled'.
- [x] AP are added as code reviewers on any related PRs (CMS, or FE)
- [x] Deployment plan is in place, as FE changes will be required this time.
- [x] A11y review completed

## Deployment Plan

- [x] Test changes in both this PR, and the related content-build together in a tugboat environment. [Completed by Jill](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15641#issuecomment-1773419429) October 20, 2023 on [this tugboat](https://tugboat.vfs.va.gov/6532ce3435265df0bbd091fd).
- [x] A11y confirmation/testing by @laflannery in tugboat
- [ ] PRs ([BE 15761](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15761), [FE c-b 1752](https://github.com/department-of-veterans-affairs/content-build/pull/1752)) approved by PW and AP teams
- [ ] Merge the [BE PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15761).
- [ ] Wait for deployment of the BE PR and test success.
- [ ] Merge the FE PR.

**Comment by jilladams** [comment]
Estimate doesn't factor Lovell complexity. Daniel to talk to AP folks and update as needed with Lovell in mind.

**Comment by dsasser** [comment]
## Mid-sprint Update 10/19/23

When taking on this ticket, we were planning no architectural changes on the backend, and instead making the frontend (content-build) robust enough to handle both a single value and an array of values. However, this approach had a lot of technical debt built in, and little risk mitigation was possible.

Because of this, we are pivoting to a different architecture:

Backend Changes
- We will create a new field on the Event content type on the BE. 
- This field will hold 'additional listings' (it is an entity reference field, just like field_listing)
- It will be hidden from view, and only populated with the correct Outreach calendar Event Listing reference if the checkbox is set.

Frontend (content-build) Changes
- An additional Graphql reverse entity query will be added to the existing nodeEventListing query, in the same way that the field_listing data is done.
- We will combine the event data from the two queries prior to piping into the event listing template. This will allow us to inject the data in a single location, without affecting vets-website's related React widget (we won't need to worry about combining, sorting, or other tasks beyond what we are doing in content-build).

Overall this approach is much safer, since we aren't touching the structure of an existing field, but adding another field which is brand new to the ecosystem.

**Comment by jilladams** [comment]
@dsasser I like this and also: it smells like we may get questions at code review time. Would it be worth bouncing this off any other Drupal folks for smell testing before we fully commit? Or feels very safe / uncontroversial as a fix?

**Comment by dsasser** [comment]
> @dsasser I like this and also: it smells like we may get questions at code review time. Would it be worth bouncing this off any other Drupal folks for smell testing before we fully commit? Or feels very safe / uncontroversial as a fix?

Getting feedback during review time is adequate in this case.

**Comment by jilladams** [comment]
**Testing notes:**
Will update this as we get a FE built to verify there. Right now, busted, thread WIP: https://dsva.slack.com/archives/C52CL1PKQ/p1697837268281799?thread_ts=1697835404.910689&cid=C52CL1PKQ

Tugboat with feature toggle enabled: https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/admin/config/system/feature_toggle

| Editor login, roles, section  | Event type |  Expected behavior | Pass/fail in CMS | Pass/fail in FE |
| ------------- | ------------- | --- | --- | --- |
| Timothy.Chavis@va.gov, Content creator - VAMC / Content publisher | [event](https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/alaska-health-care/events/62493) VAMC event, recurring | Shoudn't see national checkbox | 🟢 checkbox does not appear | |
| edward.mcevoy@va.gov] Content creator - outreach hub, Content publisher | [event](https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/outreach-and-events/events/62492) Outreach event, recurring  | Shouldn't see the checkbox  | 🟢 checkbox does not appear | |
| Winfield.DanielsonIII@va.gov - shortlisted beta editor, Content creator - VAMC Bedford & Boston / Content publisher | [event](https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/boston-health-care/events/62494) VAMC event, Boston, not recurring. National. | Should see / select National checkbox. Event should publish to Natl calendar  | 🟢 checkbox appears, is selected /s aved. | |
| Winfield.DanielsonIII@va.gov - shortlisted beta editor, Content creator - VAMC Bedford & Boston / Content publisher | [event](https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/bedford-health-care/events/62495) VAMC event, Bedford, not recurring. National. | Should see / select National checkbox. Event should publish to Natl calendar  | 🟢 checkbox appears, is selected /s aved.| |

## Other FE tests: 
Listings: 
* Stories - see all link
* Outreach materials - lists publications 
* Outreach events cal - displays events correctly in order, when national checkbox ones interleaved
* Outreach events cal - Filters work for 
  * Date range
  * Specific date
  * past

**Comment by dsasser** [comment]
## Deployment Plan

- [x] Test changes in both this PR, and the related content-build together in a tugboat environment. [Completed by Jill](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15641#issuecomment-1773419429) October 20, 2023 on [this tugboat](https://tugboat.vfs.va.gov/6532ce3435265df0bbd091fd).
- [ ] A11y confirmation/testing by @laflannery in tugboat
- [ ] PRs ([BE](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15761), [FE](https://github.com/department-of-veterans-affairs/content-build/pull/1752)) approved by PW and AP teams
- [ ] Merge the [BE PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15761).
- [ ] Wait for deployment of the BE PR and test success.
- [ ] Merge the FE PR.

**Comment by laflannery** [comment]
@dsasser I got in for a bit but wasn't able to test everything yet. However I do have one general QA item I wanted to mention - I saw this issue that I has flagged as a D10 issue and thought had been resolved in a [previous ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12634). Is it a problem that it's here in this tugboat?
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/ff83dc92-1963-493e-9d4a-16d804b61bd0)

**Comment by jilladams** [comment]
@dsasser @laflanner  I see what Laura is seeing here: https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62493/edit

I tried to repro that, using this new event: https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62522/edit
* Created a new recurring event - don't see the 2nd set of date fields, in the Add form
* Saved as draft - don't see 2nd set of fields when editing after draft save
* Published - still don't see 2nd set of fields
* Modified recurrence from days to weeks = this change weirdly allowed me to save, but when I review, it removed my date data from the original event date settings (GAH, new bug, need to file it). https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62522/revisions/view/817739/817740/visual_inline

Then got a 502. 😂 but will check when it's back up, re: whether the 2nd date fields appear.

**Comment by dsasser** [comment]
> @dsasser @laflanner I see what Laura is seeing here: https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62493/edit
> 
> I tried to repro that, using this new event: https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62522/edit
> 
> * Created a new recurring event - don't see the 2nd set of date fields, in the Add form
> * Saved as draft - don't see 2nd set of fields when editing after draft save
> * Published - still don't see 2nd set of fields
> * Modified recurrence from days to weeks = this change weirdly allowed me to save, but when I review, it removed my date data from the original event date settings (GAH, new bug, need to file it). https://cms-ytipldihujdcko41uemzx3w18e31hyof.ci.cms.va.gov/node/62522/revisions/view/817739/817740/visual_inline
> 
> Then got a 502. 😂 but will check when it's back up, re: whether the 2nd date fields appear.

I'm still not clear how to reproduce what you and @laflannery are seeing w/ the 2nd set of date fields. Noting that this would be an unexpected change, since we didn't change those fields in any way intentionally.

**Comment by laflannery** [comment]
@dsasser and @jilladams some notes:
- I think that extra fieldset is only showing on recurring events
  - I can see it on the 3 recurring events you have in the table above but NOT in the one non-recurring event and not in the new non-recurring event you made
- In the previous ticket, the D10 one, the issue was the combination of the version of the events module and D10 that caused that extra fieldset to show. Daniel and Edmund worked on it together to resolved that. 
  - This Tugboat is not on D10 but I'm wondering if this is a new version of the module that is not not working with our current version of Drupal?

**Comment by dsasser** [comment]
@laflannery what is the behavior on staging/prod?

**Comment by laflannery** [comment]
Staging has this same behavior and shows me the extra fieldset:
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/bfec972f-2085-48ca-8150-ffa16cc7d0f4)

So that being said I feel like I (or someone?) should just ignore this entirely here and ticket this separately right?

**Comment by laflannery** [comment]
So back to what I was actually supposed to be reviewing, using the table from Jill above:

**_Will finish when Tugboat is back up_**

**Scenario 1**
- FE breadcrumbs look good (it has the VAMC breadcrumbs as expected)
- FE accessibility approved
- 
**Scenario 2**
- FE breadcrumbs look good (it has the Outreach breadcrumbs as expected)
- FE accessibility approved
- 
**Scenario 3**
- FE breadcrumbs look good (it has the VAMC breadcrumbs coming from both listings as expected)
- FE accessibility approved
- 
**Scenario 4**
(Note this IS a recurring event, in Jill's table is says that it is not)

**Comment by jilladams** [comment]
( Noting: all test data at tugboat links i comments above got blown away by Tugboat refresh. )

**Comment by laflannery** [comment]
@jilladams and @dsasser Updated my comment above with the testing of the last scenario. The only thing of note was that this event did not show in the national outreach calendar even though it should have. I feel this may have been because of all the rebuilding and tugboating but wanted to make sure I noted it just in case.
