### ISSUE TITLE
Write a test to confirm Tablefield's field values adhere to the expected format.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#15663]
## Description

In July of 2022, Tablefield added functionality to support draggable table rows. This was done by quietly injecting an additional column into the data. This has made a lot of people using Tablefield in their APIs very angry, and has been widely regarded within this project as a bad move. 

While the negative effects have been eliminated with a patch, the fact remains that we have some very loose, unstructured data in some fields that we send over the wire to API consumers. We should have some test or tests in place to make sure that this data is coherent and consistent with our expectations.

## Tasks

- [ ] Create a PHPUnit test, likely a kernel or existingsitebase test, that validates that the number of columns (and other general formatting) remain consistent when a field is retrieved via GraphQL and via JSON:API.
- [ ] Remove the patch we have working around this issue and confirm that the test fails, i.e. that it is an accurate indicator for this kind of mischief.
- [ ] Replace the patch and verify that the test passes.

## Acceptance Criteria

- [ ] A test is in place that accurately indicates when Tablefield field values get deformed or manipulated or otherwise isn't matching what the API expects.

**Comment by gracekretschmer-metrostar** [comment]
@anantais what's your progress on this?

**Comment by anantais** [comment]
I don't know why my name is on this. I do not write PHPUnit tests.
