### ISSUE TITLE
Confirm analytics implementation for VAMC "In the spotlight" links 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15693]
## Problem to be solved

There are two "In the spotlight at VA <name> health care" areas on VAMC pages
- on the system home page, such as [VA Pittsburgh health care](https://www.va.gov/pittsburgh-health-care/)
- on the system health services page, such as [Health services](https://www.va.gov/pittsburgh-health-care/health-services/)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWMrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53ee9a957040dc90ada4e75f9f317baa1940099b/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2srQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--668b1fad00550646aee1a52a8dcab3da0e3366a5/image.png)

Although DOMO reports data on the number of clicks on links within the "In the spotlight at VA <name> health care" on the system home page, it is reported in aggregate for the entire group of eight links. There is no data reported for interactions on the "Flu shots" link vs the "Chat with VISN 4 Clinical Contact Center Nurse" link. 

I am currently unable to find data for interactions with the Spotlight links on the Health services page, even when I've restricted the DOMO dashboard to those particular URLs but still do not see interaction data. 

This makes it difficult to 
- make recommendations for the best place to add links to new content or content which needs elevated visibility 
- evaluate the success of our recommendations or individual editor experiments

## Tasks
- Determine current analytics implementation for "In the spotlight" areas on VAMC system home page
- Determine current analytics implementation for "In the spotlight" areas on VAMC system health services page
- Add event tracking as needed based on existing implementation

## Acceptance criteria
When a Veteran clicks a link in one of the "In the spotlight" areas on a VAMC system site, data with the following details is collected 
- [ ] in which "In the spotlight" area the interaction occurred (system home page or health services page) 
- [ ] which specific link (or label) was clicked 
- [ ] on which health care system the area exists
