### ISSUE TITLE
Upgrade to Tugboat v2.23.24

### ISSUE THREAD

**Issue by rabbitlair** [department-of-veterans-affairs/va.gov-cms#15711]
## Tasks:

- [x] Change directories to the Tugboat root: `cd /opt/tugboat`
- [x] Fetch the latest tags: `git fetch --tags`
- [x] Checkout the tag (e.g. `git checkout v2.23.24`)
- [x] Build: `make && make install`
- [x] Restart Tugboat: `tbctl restart`
- [x] Wait for Tugboat to start up successfully: 
```
wget --quiet -O- --tries=100 --retry-on-http-error=404,502,503 --retry-connrefused https://[tugboat-dashboard-host]/_status
```

## Team

Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

#### v2.23.24 - 16 October, 2023

```
#3908 fix: rely on job queue to build children
#4621 feat: switch UI from Express to Fastify
#5128 feat: resolve session handling socket issues
chore: bump @babel/core from 7.22.19 to 7.23.0
chore: bump @babel/preset-env from 7.22.15 to 7.22.20
chore: bump fastify from 4.22.2 to 4.23.2
chore: bump redoc from 2.1.1 to 2.1.2
chore: bump undici from 5.23.0 to 5.25.2
feat: add util script to connect to mongosh from any tugboat server
feat: update local development environment for arm64
```

#### v2.23.23 - 20 September, 2023

```
#5064 tests: add e2e tests for vrt pass / fail
#5086 chore: Implement ZFS as storage driver in local envs
#5139 feat: upgrade to node 18
#5157 fix: pass io to route manager to expose to routes
#5161 feat: enable eslint for typescript files
chore: bump @babel/core from 7.22.15 to 7.22.19
chore: bump core-js from 3.32.1 to 3.32.2
chore: bump html-webpack-plugin from 5.5.0 to 5.5.3
chore: bump mongoose from 6.11.5 to 6.12.0
chore: bump postcss-scss from 4.0.7 to 4.0.8
fix: use e2e prefixed branches on tugboat-test repo
```

#### v2.23.22 - 06 September, 2023

```
#4958 fix: Update DEV and DASHBOARD Google Analytics to GA4
#5082 fix: only update a job still exists
#5141 feat: allow refreshing previews when project is over quota
chore: bump @adobe/css-tools from 4.0.1 to 4.3.1
chore: bump @babel/core from 7.19.3 to 7.22.15
chore: bump eslint-plugin-import from 2.26.0 to 2.28.1
chore: bump ioredis from 5.2.3 to 5.3.2
chore: bump mongodb from 4.16.0 to 4.17.1
chore: bump redis-semaphore from 5.3.0 to 5.5.0
chore: bump undici from 5.22.1 to 5.23.0
```

#### v2.23.21 - 23 August, 2023

```
chore: add hint to RepoSelectorForm.jsx
chore: bump fastify from 4.14.1 to 4.21.0
chore: bump mongoose from 6.7.2 to 6.11.5
chore: bump prettier from 2.7.1 to 2.8.8
chore: bump socket.io-client from 4.3.2 to 4.7.2
```

#### v2.23.20 - 16 August, 2023

```
#4910 fix: implement width indicators on VRT pages.
#4911 feat: add links to visualdiff dashboard to base and preview pages
#5069 feat: add *_IS_DRAFT env variables for GitHub and GitLab
#5079 fix: ensure E2E tests are able to run in Jenkins
#5119 fix: sanitize only if lighthouse report exists
chore: Implement new backup strategy
```

#### v2.23.19 - 20 July, 2023

```
chore: bump sharp from 0.30.5 to 0.30.7
chore: bump word-wrap from 1.2.3 to 1.2.4
hotfix: check if pub client is connected before return io server
```

#### v2.23.18 - 19 July, 2023

```
#4727 fix: create better error messaging around docker disk availability
#4745 refactor: change render queueing process by type
#4750 feat: implement e2e tests with playwright
#4816 feat: rebuild visualdiffs by status on UI
#4946 fix: prevent connection reset errors for redis service
#5030 fix: log server error events
#5042 fix: log response string on bitbucket getYml errors
#5053 fix: add handler for proxied socket errors
chore: bump inspector-api from 1.4.5 to 1.4.6
chore: bump semver from 7.3.7 to 7.5.2
chore: bump socket.io from 4.6.1 to 4.6.2
```

#### v2.23.17 - 19 June, 2023

```
#5021 fix: log errors thrown by suspendPreview when preview is deleted
chore: bump @babel/plugin-transform-runtime from 7.17.0 to 7.22.5
chore: bump moment-timezone from 0.5.37 to 0.5.43
chore: bump mongodb from 4.11.0 to 4.16.0
chore: bump undici from 5.20.0 to 5.22.1
```

**Comment by ndouglas** [comment]
Completed while fighting with other things.
