### ISSUE TITLE
Archived CAPs are no longer visible to editors on dashboard

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15724]
## Description
Vet Center editors can add, edit, and archive Community Access Point which are affiliated with their Vet Center. 

However, CAPs still look actionable to editors even after they have been archived (although they are correctly no longer made visible to Veterans on Prod) - this causes confusion about whether or not the location actually has been removed. 
- An archived CAP still appears on the Satellite Locations list below the Vet Center Dashboard
- An archived CAP can still be edited by editors
- An archived CAP still appears on the Locations page in Preview 

For example, 
View the [Facility list for Scranton.](https://prod.cms.va.gov/admin/content/facilities?title=scranton&type_op=in&type%5B%5D=nca_facility&type%5B%5D=health_care_local_facility&type%5B%5D=vba_facility&type%5B%5D=vet_center&type%5B%5D=vet_center_cap&type%5B%5D=vet_center_mobile_vet_center&type%5B%5D=vet_center_outstation&moderation_state=All&workbench_access_section__section=All) 
- Notice that Scranton Vet Center - SCI Dallas and Scranton Vet Center - Waymart locations are both archived. 

<details>
<summary> Screenshot of content view for Scranton </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGhPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df4950b6fd4ae9a6c3877dde37422f965b91cb4d/image.png)

</details>

---

Now view the [Satellite Locations list for Scranton Vet Center](https://prod.cms.va.gov/section/vha/vet-centers/scranton-vet-center). 
- Notice the archived Scranton Vet Center - SCI Dallas and Scranton Vet Center - Waymart locations are present. 
- Observe that an editor can click Edit, open the node, and make changes to a location which has been archived. 
<details>
<summary> Screenshot of Scranton's Satellite locations </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzlPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef1a1260f6655363bd5638fbb57564b3015f00c3/image.png)

</details>

---

[Preview the Scranton Vet Center Locations page](http://preview-prod.vfs.va.gov/preview?nodeId=28124). 
- Observe that both archived location are still present in Preview. 
<details>
<summary> Scranton Locations page preview </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDlPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2715ce5c633728f753265cc4bf05eb68f2d7ec49/image.png)

</details>

---

View [Scranton's Locations page in prod](https://www.va.gov/scranton-vet-center/locations/). 
- Observe the archived locations are not displayed to Veterans. 

## Tasks
TBD

## Acceptance criteria
- [x] An archived CAP is not displayed to Vet Center editors as an active location
- [x] Archived locations are not displayed to Veterans
- [x] UX review
- [x] Accessibility review
- [x] Subsequent tickets are stubbed as needed.

**Comment by omahane** [comment]
When I advocated for adding this, I thought I'd pick it up. Sorry, @swirtSJW .

**Comment by jilladams** [comment]
Was gonna verify while working on sprint report, but not 100% on what I'm seeing, so logging here and others can close based on whether this is 🟢 for meeting ACs: 

* [Facility list for Scranton.](https://prod.cms.va.gov/admin/content/facilities?title=scranton&type_op=in&type%5B%5D=nca_facility&type%5B%5D=health_care_local_facility&type%5B%5D=vba_facility&type%5B%5D=vet_center&type%5B%5D=vet_center_cap&type%5B%5D=vet_center_mobile_vet_center&type%5B%5D=vet_center_outstation&moderation_state=All&workbench_access_section__section=All) - SCI Dallas, Waymart listed as Archived
* [Satellite Locations list for Scranton Vet Center](https://prod.cms.va.gov/section/vha/vet-centers/scranton-vet-center) -- SCI Dallas / Waymart not listed
* http://preview-prod.vfs.va.gov/preview?nodeId=28124 -- SCI Dallas / Waymart listed as "Facility closed"
* [Scranton's Locations page in prod](https://www.va.gov/scranton-vet-center/locations/) - SCI Dallas / Waymart not listed

**Comment by mmiddaugh** [comment]
Confirming behavior in CMS:
🟢 Facility list: SCI Dallas and Waymart CAPs correctly show as archived on the Facility List
🟢 Satellite Locations list for Scranton Vet Center: Archived CAPs SCI Dallas and Waymart do not appear as Satellite locations
🟢Preview page: SCI Dallas / Waymart are listed as "Facility closed" (noting that this is because the editor marked them this way - may not always be the case)
🟢 Scranton Vet Center page in prod: Archived CAPs SCI Dallas / Waymart do not appear

All good to go, @jilladams 
Thanks for your work on this @swirtSJW
