### ISSUE TITLE
Change management: Event email CTA

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15729]
## description
We are updating the Events UI to: 
* Add an option for RSVP: Email or URL
* Add an Email field that will validate email addresses
* Update the URL field to disallow entering email addresses

## STakeholders
VHA Digital Media (Justin Warren, Blake Scates)

## Tasks

- [x] Reachout to VHA DM for awareness, ask about communicating the change
- [x] Craft a communications plan
- [ ] Update KB articles that speak to Event RSVPs
  - [ ] https://prod.cms.va.gov/help/cms-basics/how-to-edit-an-event - doesn't mention RSVP options. Should it?
  - [x] https://prod.cms.va.gov/help/vamc/about-events-content-for-vamcs - high level, does not require changes for this project
- [x] Send comms before the feature ships
- [x] Send comms when the feature ships

**Comment by jilladams** [comment]
This is way lower priority than the Events national calendar change management, so let's get that settled first, and leave this til after.

**Comment by jilladams** [comment]
@FranECross I went ahead and cued up an agenda Item to talk about this with VHA DM on 11/14, and forwarded that meeting invite to you. (They have a sync next week during our Product sync with Dave, and this can wait til after the holiday anyway.)

In the agenda card, I drafted an Editor facing email. Please feel free to revise and post updates to that card: https://trello.com/c/qGwFtMkx/90-events-email-as-rsvp-option Again: not urgent at all.
