### ISSUE TITLE
Email call to action for Events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15725]
## User story
As an editor on https://prod.cms.va.gov/ creating a new Event, I would like attendees to RSVP by emailing an address such as VANJHCSCommsTeam [at] va.gov, so that I can manage RSVPs without a website.

### Helpdesk description
Unfortunately, if an email address is added as the "Call to Action" URL without the `mailto:` prefix, it saves as `/VANJHCSCommsTeam%40va.gov`

**Note:** The help text for adding an Event "Call to Action" URL does not advise editors to add `mailto:` before email addresses.

This issue is inconvenient for site visitors who may wish to click the link to RSVP.

This issue also creates broken link alerts that are reported every 30-60 minutes in #content-broken-links until they are resolved by the editor or by a member of the VA Drupal CMS Help Desk team.

## Tasks required
* Design
* Drupal
* Front-end
* Change management

### Design
https://www.figma.com/file/8ZT1nnu8r2twbOlEhysnNp/Events?type=design&node-id=133-575&mode=design&t=GLTPkEbfBgSTUJDB-0

## Launch plan
We don't want to expose the new Email field until FE can display that data in the template, and Editor communications have gone out to explain the new field.
- [x] Drupal changes are made but not merged
- [x] FE changes are made but not merged
- [x] Product works with VHA Digital Media (Justin Warren & Blake Scates) to: 
  - [x] Develop a communications plan (which might include an email to all VAMC editors)
  - [x] Update existing Knowledge Base articles to explain the change
  - [x] Comms are delivered with advance notice before the feature ships
- [x] Drupal changes can deploy
- [ ] Any existing Events that include mailto: in URL are updated to use Email field instead.
- [x] FE changes can deploy
- [x] Change Management notice is sent that the feature is live

**Comment by jilladams** [comment]
Doing an epic for this because of change management / launch steps are complex. 

We need: 
* Change management ticket
* Launch plan added
