### ISSUE TITLE
(PW) Sprint 96

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#15742]
# Sprint Priorities #

```[tasklist]
## 🥅 Sprint Goals 🥅
- [ ] 📣UX: Present PACT Act Wizard research study to determine next steps ([PAW: Post-research tasks ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15370))
- [ ] 📣 FE: Fix screen reader issues so Veteran's are able to navigate from headers to their nested text/items. Tickets [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15268) 
- [ ] 📣Drupal: Discovery work on notifications framework and Q4 plan for such ([ticket here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15533))
```

# Candidates for Sprint #96
```[tasklist]
##  PACT Act Wizard [(Epic #12170)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12170)
- [ ] **Value Prop**: _Present research study results in order to determine next steps in delivering PACT Act Wizard changes_
   - [ ]  #15370 
- [ ] **Value Prop**: _Fix screen reader issues where navigating from a header doesn't then take the Veteran/user to the logical nested questions/information_
   - [ ]  #15268 
   ```

```[tasklist]
## Outreach Events Improvements [(Epic #13527)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13527)
- [ ] **Value Prop**: _Complete the FE work to handle breadcrumbs & URLS so that veterans have a consistent, intuitive content experience without errors_
  - [ ] &#x20;\#15627
- [ ] **Value Prop**: _Addition of an email field for Veteran responses to provide a more complete experience in gathering their feedback and/or registration for events._
  - [ ] \#15385
```

```[tasklist]
## Cross-Platform Mobile Banner ([Epic #15331](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15331))
- [ ] **Value Prop:** _Support the Mobile team by increasing adoption of the Mobile App"._
- [ ] #15317
- [ ] #15694
```

```[tasklist]
## Benefit Content Model [(Epic #9628)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9628)
- [ ] **Value Prop:** _Drupal work to provide collapse functionality during editing content, which will speed up an editor's work, benefiting Veterans in the long run by providing more timely information to them._
-  [ ] #15397
-  [ ] **Research:** _To determine true scope of adding the ability to add multiple Beneficiary types to a Resources & Support article so we can determine whether or not to do the work._
-  [ ] #15743 
```

```[tasklist]
## Income Limits App
- [ ] **Value Prop:** _This is the next step in achieving automated data export for Income Limits_
   - [ ] #15202 
```

```[tasklist]
## Medalia Survey Data (encompasses 1st-time Visitor & other Q4 Priorities)
- [ ] **Value Prop:** _Analyze the qualitative survey data for the remaining PW portfolio in order to determine future projects to benefit Veteran's experience in the website and tools_
  - [ ] \#12791
```

```[tasklist]
## Campaign Landing Page
- [ ] **Value Prop:** _Provide Veteran's a more professional visual experience when rendering images on this page_
   - [ ] #15632 
```

**Comment by jilladams** [comment]
ADDED: 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15835 - new, pulling in
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15856
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15839

DONE: 
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15694
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15317
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15363

TO REFINE / STRETCH:
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15316
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15318
