### ISSUE TITLE
VA Police data page content model

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15756]
## User story
- As a Veteran, I want to know police activity that has occurred at my VA Medical Center facility.
- As a VAMC editor, I want to add information to the police data provided for my VA Medical Center facility.

## Background
Legislation passed in 2022 requires VAMC websites to include data about VA police activity.
Deadline: One year after the enactment (December 29, 2022), the Secretary shall report to Congress on the implementation of all provisions of amendments to 38 USC 902, which includes the publishing of arrest and ticketing data.

[Initiative Brief: VA police transparency (WIP)](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/police/readme.md#initiative-brief-va-police-transparency-wip)

## Assumption
The Police Transparency MVP page will be built in Drupal with police data provided by a vendor added by the front end. The Drupal page may consider future uses by VAMC editors, but for the MVP editors will not be editing the page.

## Working document
https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?sender=u9c899abc4fe36c9a698b1647

## Acceptance Criteria
- [x] Review and respond to [CAIA's questions](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67055#issuecomment-1772970982) 
- [x] Content models that covers external data sources, Facilities backend products, and VA.gov front displays are sketched out in Mural
- [x] Address Police vs Policies [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68315) via menu order
- [x] Address granularity [feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68315) via split of system page and facility data pages
- [x] The models are reviewed with product & engineering to evaluate pros and cons
- [x] Possible iteration within Mural
- [ ] ~~After a decision is made about overall approach, modeling can move into more detailed specification of content fields~~ Moved to subsequent ticket

**Comment by swirtSJW** [comment]
The mural helps a lot.  Nice work.   The only variant I wasn't seeing is this possibility 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/1981a4a8-297e-484a-b4e3-550f009cd145)

Which might solve the menu problem (not just the code.. but how the menu would look).

**Comment by xiongjaneg** [comment]
From Michelle and Jane conversation: Our preference is for the page at the facility level - on the Mural, VA Police (page per facility). This would need to be linked from elsewhere in the Facility, for example a service accordion. This would eliminate the link from the left navigation that only exists at the system level.

**Comment by davidmpickett** [comment]
> From Michelle and Jane conversation: Our preference is for the page at the facility level - on the Mural, VA Police (page per facility). This would need to be linked from elsewhere in the Facility, for example a service accordion. This would eliminate the possibility of a link from the left navigation that only exists at the system level.

I do want to flag a risk to this approach. Having a page that is not reflected in the sidenav is in violation of Platform's URL standards. They already have an outstanding ticket about our Billing and payment and Medical Records Office pages violating this principal. https://github.com/department-of-veterans-affairs/va.gov-team/issues/54291

**Comment by davidmpickett** [comment]
Noting that L4 pages are not supposed to show the sidenav at all, so that might be part of the solution here

**Comment by mmiddaugh** [comment]
Thank you for flagging the risk (and the related outstanding ticket). 
We should be covered under the L4 guidance.

**Comment by jilladams** [comment]
From planning: 
* @mmiddaugh wants to put something in front of the Office of Security, and CAIA, to review. 
* @davidmpickett  to think about that during this ticket, and get review from Michelle & @xiongjaneg , sync or async, early in Sprint 96.

**Comment by davidmpickett** [comment]
-  ABOUT [VAMC SYSTEM]
  - About us
  - Work with us
  - Contact us
  - Policies
  - VA Police
  - Programs (if enabled)
  - Research (if enabled)

**Comment by davidmpickett** [comment]
Summary from conversations with @swirtSJW and @eselkin about possible paths forward for creating pages per facility. There is still some more work to do to fully understand these options (Eli has some digging to do), but wanted to document them for the rest of the team to start absorbing.

## Option 1 - Single Page App - SPA (ala Income Limits)
- Each facility page has it's own URL path 
  - (system)/va_police/(facility)
- Each police page has full unique breadcrumbs for MVP
- No side navigation displayed while on Police pages (system or facility) for MVP
- May have additional accessibility review compared to widget 
- Facility pages don't have link in sidenav, just system page

## Option 2 - Embedded widget (ala Access to Care data)
- Each facility page is actually a query parameter, not a true URL path 
  - (system)/va_police?=(facilityid)
- No breadcrumbs on facility pages for MVP
- Side nav could be displayed, but it would just always show the system-level page selected, would not update per facility page
- Facility pages don't have link in sidenav, just system page

## Option 3 - Drupal creates page per facility 
- This would mean adding not 1, but 2 new content types
- 1400 new nodes instead of 140
- This would be the only way to have both system and facility pages in the side nav
- This is only included here as a last resort in case Eli find that options 1/2 couldn't reliably create pages per facility (after Drupal creates System page)

**Comment by davidmpickett** [comment]
Snapshot of [content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698094046232). I've taken this about as far as I can with existing information 


![VA Police data - content model_2023-10-27_21-50-50](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/26c37a01-8d91-4160-9f44-0d19f2ef2824)

**Comment by jilladams** [comment]
We will need a new CAIA IA review to inform the decision here?

**Comment by davidmpickett** [comment]
@jilladams Our meeting with CAIA isn't until next week, I will walk them through our proposal at that time. I have been responding to their questions and updating them on our progress on [their ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/67055)

**Comment by jilladams** [comment]
Ugh, sorry, I keep getting mental wires crossed on IA state of affairs between VBA and Police. Thank you for clarifying for probably the 3rd time this week.

**Comment by laflannery** [comment]
FWIW my initial thoughts:
**Option 1**
- Overall I don't mind this
- Each page will need a unique `<title>`. it should follow the same pattern that the other pages within the VAMCs follow `H1 | VAMC System Name | Veterans Affairs`
  - Randi is doing this dynamically on Income limits and PACT because of where things come from (vets-website vs content-build I believe). This solution was fine for IL but I think would cause some issues for Police because it loads just a second or 2 after the page does. So if we do build this the same way, yes it will definitely need to be tested
- I like that the subnav will not have duplicate facility links now, so that's a Pro as far as I'm concerned
- IL hasn't been an issue with the way it's built, I have seen some things occasionally with loading but because of how we are forcing focus and the fact that it's not a "browsing" page, it's generally not an issue.
  - These pages are definitely pages where the user is going to be going between different areas more frequently so I can see that potentially being an issue

**Option 2**
- I don't particularly like this
- I don't like that there isn't a clear indicator of where the user is in the page hierarchy, no breadcrumbs and no accurate subnav

**Option 3**
- I know this is a last resort
- Obviously the accessibility would be a non-issue
- I still have weird feelings about duplicative links in the subnav (I know they are hierachical but it's still hard to understand I feel like)

**Comment by swirtSJW** [comment]
Related to option 2.   The in-page widget could alter breadcrumbs and menus if it had to.  We just are not suggesting that possibility for MVP as time is a limited commodity.

**Comment by swirtSJW** [comment]
Also for Option 2
> (system)/va_police?facility=(facilityid)
This could be more human readable by using the facility common name instead of the id.
(system)/va_police?facility=bellmont-county-va-clinic

**Comment by jilladams** [comment]
From scrum: 
Digging = whether it’s possible for left nav to exist in a single page application. So far: no.  (SPA = vets-website) We cannot initiate a React single page app within an existing page, so far as we can tell. 

CMS view can be created that has System IDs with nested IDs of Facility pages? This would provide the necessary data to the FE. 

KISS that can curl a file = we could set up a view that could be pulled, to associate Facility with System. This would happen at content-build time.

Are there any requirements that force Option 3? No.

The nested sidenav showing all Facilities is only possible in Option 3.

Option 2 could have System level with Facilities below it in the sidenav, but might not be worth doing for MVP. Could be done with Menu items + self-contained widget. Was a CONSIDER from design intent.

**Comment by mmiddaugh** [comment]
Are the only objections to Option 2 related to side nav and breadcrumbs?
-> If so, [Steve commented](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15756#issuecomment-1785432244) that the in-page widget could alter breadcrumbs and menus if it had to (post-MVP)

**Comment by davidmpickett** [comment]
> Are the only objections to Option 2 related to side nav and breadcrumbs? -> If so, [Steve commented](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15756#issuecomment-1785432244) that the in-page widget could alter breadcrumbs and menus if it had to (post-MVP)

@swirtSJW @eselkin To make a final call on Option 1 vs Option 2, it might be helpful to have a clearer articulation of which aspects of each approach are permanent vs just for MVP. 

Most of the downsides of Option 2 are in the "Just for MVP" category but that doesn't mean that Option 1 necessarily has downsides that are permanent. What long-term structural decisions are we making with SPA vs Widget that can't be addressed via iteration?

**Comment by laflannery** [comment]
I am also very wary of the lack of breadcrumbs/sidenav - I believe this is going to get flagged as launch-blocking at Collab Cycle, in which case it couldn't be omitted from the MVP and would have to be resolved. [Examples of tickets](https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue+label%3Alaunch-blocking+label%3ACCIssue04.01+is%3Aclosed) where something like this was labelled as launch-blocking.

I do think that if this is being considered, we need to run this be IA sooner rather than later

**Comment by davidmpickett** [comment]
Added a little more detail to the [content model](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1698094046232) to reflect discussion about content drafting from meeting today
![Screenshot 2023-11-01 181058](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/f1da0a54-3276-4bc6-8e67-6de6f042a826)

**Comment by mmiddaugh** [comment]
Recording @eselkin's feedback about the level of effort here 
Both the SPA and the widget require about the same amount of work. The additional feature available in the SPA of having the breadcrumbs makes it a little more effort, but probably not much more. But the SPA is more navigable because it has those breadcrumbs and in MVP the widget would not (nor would the widget have working facility links in the side nav).

In terms of total length of effort to produce the system page, probably less than 1 sprint (though some of that is dependent on a CMS view being produced first to provide system/id/url/name and nested facility/id/name). This CMS view will also help in producing the breadcrumbs. The individual facility pages would probably take 1 sprint or 2 if problems arise. There is a 1 sprint before any of this of converting whatever they give us on the 9th to whatever we need for the facility pages.

**Comment by jilladams** [comment]
https://dsva.slack.com/archives/C0FQSS30V/p1698966435539929
> Summary of conversation just now with Mikki and Dave P - we're going with a version of **Option 2 - single app page using a query to dynamically present facility level data** (preferably by passing a query so the page can default to data for the facility the user has come from). This allows us to avoid blowing out the node count and creating duplicate high level police content while leveraging left nav, breadcrumbs, and URLs. We'll need to think through the accessibility points Laura made earlier related to page title and live regions.

**Comment by davidmpickett** [comment]
@mmiddaugh @xiongjaneg One lingering question here. For MVP do we need to add a link on each VAMC facility page that points to the associated facility query on the System Police data page? 

If so, here's a quick mock-up of what that might look like: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1698092447003/c969debf289d4e43e3cdd293d90053c2c137c338?wid=0-1699292283883

Previous conversations around this involved trying to add that via a Prepare for your visit / Security accordion, but that is not a viable approach for MVP since those accordions are blobby.

**Comment by davidmpickett** [comment]
@jilladams @xiongjaneg Moving this to PO review. This ended up being larger than a 5 so the last AC was out of scope for this sprint:

- [ ] After a decision is made about overall approach, modeling can move into more detailed specification of content fields

Rather than leaving this ticket open, I'd suggest just updating the Drupal tickets with time for me to assist with spec ala https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15710

**Comment by xiongjaneg** [comment]
#15710 updated with the last AC, that can be struck out from this ticket

**Comment by jilladams** [comment]
Sounds like this is officially wrapped -- closing based on the notes, but please reopen if we missed anything here.
