### ISSUE TITLE
Facilities Sprint 96 Plan

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15753]
## Schedule Notes
- Alexis OOO 10/26, partially unavailable next week
- Steve OOO 11/1 - 11/3 (partially unavailable on 11/3)
- Max OOO 11/2 - 11/9 (4 days in sprint 96)
- Jordan OOO 11/6 - 11/10 (2 days in sprint 96)

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
- [ ] 🎯 UX:  #15631 needs refining after 10/24 collab cycle mtg feedback is received
- [ ] 🎯 FE: #14940 carryover from previous sprint
- [ ] 🎯 Drupal: #11334 

### VBA Regional Office Modernization MVP #10514
- [ ] UX: #14890 if unblocked
- [ ] Accessibility: #14893

### VA Police Transparency #14327
- [ ] UX: #15756 

### VAMC
- [ ] UX: #14837 carryover from previous sprint
- [ ] UX: #15704 
- [ ] Drupal: #14214 

### Vet Centers
- [ ] Drupal: #15724 
- [ ] Drupal: #15702 in progress
- [ ] FE: #15424 

#### Flagged Facilities #13716
- [Flagged Facilities tickets](https://github.com/department-of-veterans-affairs/va.gov-cms/labels#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?labels=flagged%20facilities) for coordination with CMS Support

#### Accessibility Debt
- [ ] FE: #11848 

#### Process Improvement
- [ ] UX: #15829

**Comment by mmiddaugh** [comment]
Suggested Sprint Priorities 🎯

- UX: [Updates to VAMC Police data page after Design Intent #15631](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15631)
- Drupal: [CMS: Implement VBA Editor permission stories #11334](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11334)
- FE: [Front End template skeleton for Facility content type for VBA #14940](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14940) _carryover from previous sprint_
