### ISSUE TITLE
Initiative - CLP: Update hero image aspect ratio

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15807]
#10075 documented a disconnect between the guidance in the CMS and the real-world behavior of CLP hero images. 
CLP hero images historically have gone full screen as background images. 
This initiative is to update the CMS implementation, guidance, and Front-end to make hero images more useful to veterans. 

## Launch plan
- [x] Change management prep complete
  - [x] Published CLPs: Editors have been provided with an updated 1:1 image and signed off on the change
  - [x] Stakeholder administrations have been made aware of the upcoming change and have responded
  - [x] https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages - Draft revision to update mention of "large full-width image" is ready to publish (but not yet published)
- [x] CMS changes are shipped, including: updated hero instructional image
- [x] https://prod.cms.va.gov/help/campaign-landing-pages/how-to-manage-campaign-landing-pages draft revision is published
- [x] Published CLPs revised to use modified 1:1 image ratio
- [x] FE changes are shipped to use 1:1 ratio
- [ ] Change management follow up communications are sent, confirming the change is live

**Comment by jilladams** [comment]
I added a draft launch plan to ticket body. We'll review and update it under the CM ticket: #15806

**Comment by jilladams** [comment]
Launched! https://dsva.slack.com/archives/C52CL1PKQ/p1702071118044789?thread_ts=1701979898.379149&cid=C52CL1PKQ
