### ISSUE TITLE
CMS/React content dark launch request: <Static page for 1010EZR online form testing>

### ISSUE THREAD

**Issue by aliyahblackmore** [department-of-veterans-affairs/va.gov-cms#15802]
## Description
In preparation for the MVP launch of the online 1010-EZR form in mid November, sitewide worked with the 1010 team on adjusting content to [this static page ](https://www.va.gov/health-care/update-health-information/)ahead their testing in early November.  Their testing will be with authenticated users and will include wayfinding.

We'd like to create a new node in Drupal and place it behind a feature flag that will only be used for usability testing. After testing, we'd need to take the test page down and publish the updates on the "real" page.

**Review documentation about the process** prior to submitting your ticket: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/public-websites#3-publish-a-cms-page-only-to-staging-using-entityqueue-in-order-to-stage-cms--content-build--vets-website-for-viewing-off-of-va-network
  
  
### Staging/dark launch
* **CMS link to content**: https://prod.cms.va.gov/node/62530 
  * Preview link: **http://preview-prod.vfs.va.gov/preview?nodeId=62530**
* **Target dark launch date**: November 1, 2023
* **Is this date flexible?** If not, please explain: The 1010 team is planning to have their research repo submitted by November 1.
* **Technical point of contact** for vets-website React code: @longmd 
* **Strategic point of contact** for timing & approval to publish the node to Staging: @alexseelig @hdjustice 
### Production launch
CMS team does not want to get in the habit of having staged nodes that will not publish, so this method should only be used for business cases that have a line of sight on production launch. 

* **Target production launch date:** 12/1/23
* **What is driving and/or blocking prod launch date?** We want to give Veterans the ability to update some of their information online
  
# For PW use
## Tasks
Please tick the boxes for completed steps as we go, for cross-team visibility.
- [x] Technical POC has merged vets-website code to main & confirmed deploy to prod
- [x] PW team: Add Node ID to [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue)
- [x] Strategic POC: has given approval to publish node, or has published node
- [x] Nightly CMS build has run which pushes prod mirror to the staging site, or PW must request an out of band deployment.
- [x] Content-release has run. 
- [ ] Verify on staging / prod

## Acceptance Criteria
- [x] _**Note: this needs to be done in the first half of the sprint, with the goal of meeting the Target dark launch date**: November 1, 2023**_
- [ ] Page is verified: Live on Staging
- [x] Page is **not** live on Prod
- [ ] Ticket is cut to follow up post-research, including: 
  - Remove the node from staged content queue
  - Unpublish node
  - Eventually delete the node (this might need to be a 2nd later ticket, unless 1010-ezr team is ready for this right away)

**Comment by jilladams** [comment]
@aliyahblackmore & @ alexseelig - DaveC signed off on this use of the dark launch. Noting for our future selves:
* No redirect needed
* This page will be archived when testing is complete and the current live page is updated
* We would also like to eventually delete this temporary page, after an appropriate amount of time. Proposing: 30 days after the Prod page has been updated, if not before with your approval, but let us know if you need to revise that timing for some reason.

**Comment by aliyahblackmore** [comment]
Hi @jilladams great - thanks so much for confirming!

I'll reach out if I have any other questions as I'm getting this set up. And I'll update the above issue when the 1010 team confirms some of the questions.

**Comment by alexseelig** [comment]
@jilladams I don't think I can edit, so here's the info:
Technical PoC: Matt Long 
Strategic PoC: Myself and Heather Justice
Target launch date: 12/1/23 
Driving/Blocking: We want to give Veterans the ability to update some of their information online

**Comment by aliyahblackmore** [comment]
@alexseelig I just updated the top of the ticket this information. Thanks so much!

**Comment by jilladams** [comment]
@aliyahblackmore for this project, is there no vets-website React widget implicated? The page you want is solely a content page? 

If no vets-website widget, we don't need to worry about technical POC. But if there is a vets-website widget on the page we are dark launching, we need to know who Technical POC will be for confirming state of that deploy.

**Comment by aliyahblackmore** [comment]
Hi @jilladams there is a react widget for this page. I pinged Matt about this last week so it's on his radar! 
 
@longmd do you know when the code for the react widget (to sign in) will be ready? 

And @jilladams I'll create the duplicate page later today and link that above.

**Comment by longmd** [comment]
> @longmd do you know when the code for the react widget (to sign in) will be ready?

@aliyahblackmore , I plan on getting to this next week.

**Comment by jilladams** [comment]
Timing flags: ticket lists a November 1 dark launch date (next Wednesday). In order to achieve that, we'll need to hit the following targets: 
* vets-website code merged / deployed by daily deploy on Tues Oct 31 - @longmd 
* CMS content drafted by east coast COB Tues Oct 31 - @alexseelig / @hdjustice 
* CMS subqueue change will be made by Tues Oct 31 EOD, to publish in nightly CMS build, to be available by am Wed 11/1 - my team

Timing will slip accordingly if any of those mileposts move. Holler with any questions or concerns!

**Comment by aliyahblackmore** [comment]
Thanks for these timeline flags @jilladams! 

I just updated the descriptions with the CMS duplicate page we'll use for the dark launch (node 62530). 

When Matt passes along the react widget code (to sign in), I'll add that to the page.

**Comment by aliyahblackmore** [comment]
Hi @jilladams a question for you:

We'd like to add this ticket to our epic of the 1010 EZR work so that we can track this task. 
There's no project listed above. Should the project be assigned to your team?

Looping in @strelichl FYSA

**Comment by jilladams** [comment]
Bc we manage our tickets in the va.gov-cms repo, sometimes that makes things weird for people who mostly operate in va.gov-team. If you can send me your epic link, I can likely get it added to your epic. 

I don't know about the "Project" - we don't tend to use that Github/ Zenhub feature.

**Comment by jilladams** [comment]
Added!

**Comment by aliyahblackmore** [comment]
**Just an update here:**

We're still waiting for feedback/a review from HEC stakeholders on some adjustments to the static page. 

I'll make updates on the duplicate page once we get feedback from them.

**Comment by longmd** [comment]
@aliyahblackmore / @jilladams , the CTA widget has been added and is in prod with the key for use being: `update-health-benefits-info`.

**Comment by jilladams** [comment]
@chri5tia FYI that ^ this note means you are unblocked for the next "PW team" task, under "Tasks" in the ticket body.

**Comment by aliyahblackmore** [comment]
Hi @longmd - I just added the code from above to the original static page (I'll add it to the duplicate dark launch page as well) and I'm getting this message. 

Anything for me to do on my end? 

These are two screen captures: 

![Screenshot (22)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/102090263/71bb100a-40fd-4326-9123-01aab75391d2)
![Screenshot (23)](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/102090263/cb40ed09-aaa0-4edc-a6f4-6c6584196a09)

**Comment by longmd** [comment]
@aliyahblackmore , just want to confirm that there is no specific `Call to Action` widget that you may need to use in Drupal that may be different from the traditional React widgets that are standalone apps in their own right? I'm not sure what your options for that are, but I'm wondering if they are different modules for you?

**Comment by aliyahblackmore** [comment]
This is a good question! I just asked Randi (OCTO-content) if she has any context on this. I took a look at another page in the healthcare hub with a react widget, and the "Call to Action Widget" option in Drupal isn't checked and it's showing as it should. I'll circle back here when I have more information.

**Comment by chri5tia** [comment]
Ready to verify on prod after content build process.

**Comment by aliyahblackmore** [comment]
@longmd back with some info! 

In the past, when there have been issues with widget rendering we've asked the product team/engineers to look at other widgets from other product teams. It's not clear to us, from the content side, whether the widget should be a specific `Call to Action `widget. So this isn't a question that content would have the answer to, but it seems to be an engineering question. 

This is a widget code example from the Review and pay your VA copay bill page. The Call to Action check box isn't checked in Drupal, and it appears as it should on the preview page/on the live page

`medical-copays-cta`

**Comment by chri5tia** [comment]
Ready to verify in staging after next content build

**Comment by aliyahblackmore** [comment]
@jilladams / @chri5tia FYSA - We got additional feedback that we need to add to the duplicate page linked above.
I'm in Drupal now and will make those updates! Just adding here in case this impacts the work that you all are doing at all.

**Comment by longmd** [comment]
@aliyahblackmore , yup... so the `medical-copays-cta` is a standalone widget, whereas ours is utilziing the call to action widget. You should be able to set it up identical to 'manage-va-debt`, for example, or changing direct deposit info (`direct-deposit`).

**Comment by aliyahblackmore** [comment]
@longmd this worked! Thanks so much for clarifying.

@jilladams / @chri5tia I've made the last updates to the dark launch duplicate page in Drupal. This is the preview link that's also linked above:

http://preview-prod.vfs.va.gov/preview?nodeId=62530

**Comment by chri5tia** [comment]
@longmd This is ready to publish or we need permission to publish before the next content build runs. This should have been ready to go today but it apparently didn't save correctly in the staged content entity queue.

**Comment by longmd** [comment]
@hdjustice or @alexseelig , can you provide sign off for @chri5tia for this request?

**Comment by alexseelig** [comment]
11/1/23 18:04 ET - We do not need an OOB release for this. Our research doesn't start for another ~week. We will need it for research prep, so please just keep in touch with myself, Jessica Stump, Hieu Vo, and Katelyn Caillouet

**Comment by chri5tia** [comment]
@alexseelig Thank you. May I go ahead and publish so that it's ready or are you saying you want to wait?

**Comment by alexseelig** [comment]
@chri5tia you may publish!

**Comment by jilladams** [comment]
Took a look this morning, just to see where we're at: 

- 🟢 Node is added to [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue)
- 🟢 Node = published: https://prod.cms.va.gov/health-care/update-health-information-1
- 🟢 Prod va.gov: page does not exist, as desired (404): https://www.va.gov/health-care/update-health-information-1
- 🔴 Staging va.gov: page does not load, doesn't 404 but gives a different error page I'm not sure what it means / implies: https://staging.va.gov/health-care/update-health-information-1

So unfortunately this is something it looks like we'll need to debug. I'm not sure, but it may be a problem at the build step or something?  

## Other debug info
1. Content release _has_ run today, several times since the nightly CMS release: https://github.com/department-of-veterans-affairs/content-build/actions/workflows/content-release.yml
2. Other staging pages _do_ load fine. Seems to be isolated to just our dark launch page having the problem. 

I checked the other node that is dark launched to see how it's behaving: 
- 🟢 Node is added to [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue)
- 🟢 Node is published: https://prod.cms.va.gov/download-your-irs-1095-b-tax-form
- 🟢 404 in prod: https://va.gov/download-your-irs-1095-b-tax-form/
- 🟢 Loads in staging: https://staging.va.gov/download-your-irs-1095-b-tax-form/

FYI @chri5tia

**Comment by chri5tia** [comment]
I need to find and look at the build logs to see what went wrong during the build process.

**Comment by jilladams** [comment]
It's a 504 error -- updated my note above.
![Screenshot 2023-11-02 at 9 25 38 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/85581471/571093ca-f701-470d-9e38-026de8ecba49)

**Comment by chri5tia** [comment]
504 is a gateway timeout. 
Do you think that the content differs from https://staging.va.gov/health-care/update-health-information/ or do we just have the URL wrong with the `-1`? Is this a new version of that?

**Comment by chri5tia** [comment]
Makes sense. Just wanted to be sure.

**Comment by chri5tia** [comment]
## Status Update: 11/02/2023

Staging is failing to serve the page, 504 error.
We believe that when the content build runs again, it should be fixed and will check in tomorrow.
https://staging.va.gov/health-care/update-health-information-1

Content is not coming up on prod. Both are still published in the CMS backend.

**Comment by jilladams** [comment]
@hdjustice @alexseelig @aliyahblackmore @longmd  https://staging.va.gov/health-care/update-health-information-1/ is now live in Staging! (And not in Prod.) 

Filed https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15994 to track next steps we'll need to do when usability testing is complete and you're ready to retire this temporary page. Please let us know when you're done with it.

Closing this ticket.
