### ISSUE TITLE
FE Provider training design implementation 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15823]
## Background
a blurb on Provider Core Training:
> Department of Veterans Affairs (VA) has created the Provider Core Training so that Veterans can be offered care from the highest quality providers available. Referring Veterans to Providers who have completed the Provider Core Training ensures that Veterans are receiving high-quality care in the community.

## User Story
As a Veteran, I want to see what Community care providers have completed Provider Core Training so that I can select the most appropriate provider for my care. 

Design was handled during #11542 and is available in the [Facility Locator Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=0-1&t=hiN4vHJDfdU4dNTb-1)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXhvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a441d7e11eee0fefbe7aa2b3f904bf2b58a56edb/image.png)

## Notes
- Currently there is no page where Veterans can learn more about Provider Core training so the link shown in the design will not be needed
- We may not want to use the word "complete" in the label as the data indicates when a provider has completed at least one of a group of eight (to date) defined Community Provider Core Training (CPCT) Courses - rather than completing all eight. 

## Tasks
- Implement icon and label for Provider core training 
- Use a feature flag so that this will be ready to turn on when there are enough providers with this training

## Acceptance criteria
- [x] Recommend the label reads "Provider core training" (no "complete"), no link out
- [x] When facility type = "Community providers in VA's network", community providers with training data display the training icon and label. 
- [x] When facility type = "Urgent care" and service type = "All in network urgent care" or "In network community urgent care", community providers with training data display the training icon and label. 
- [x] When facility type = "Emergency care" and service type = "All in network emergency care" or "In network community emergency care", community providers with training data display the training icon and label. 
- [x] Icon and label display consistent with design
  - [x] icon uses aria-hidden = true
- [x] Only providers with training data display the icon and label
- [ ] Design review and signoff
- [ ] Accessibility review and signoff
- [ ] Po/PM review and signoff

**Comment by xiongjaneg** [comment]
From pre-refinement, this is likely not a small sized ticket and would take time and attention away from current higher priority work given the low numbers of providers that may have this training currently

**Comment by xiongjaneg** [comment]
@xiongjaneg discuss with FE just enabling the icon and label and potentially turning on but not working on the filter part of it, low risk

**Comment by aklausmeier** [comment]
updated provided icon in Figma design, screenshot updated in ticket to reflect USWDS icon "how to reg"

**Comment by eselkin** [comment]
@mmiddaugh
Do we know what the course code is for the Provider Core Training?
Is the title of the course (courseName): "Provider Core Training"? Are we certain of that?
I'm only finding a somewhat relevant training of:"A Perspective for Veteran Care" course code: 1085488

**Comment by eselkin** [comment]
The icon in the image is: #2e8540 but that doesn't exist in our color palate. Do we want to use this color or like #00a91c (which is vads-color-success) or a darker color like #008817 which is the darker version?

**Comment by thejordanwood** [comment]
@eselkin Let's use #00a91c, which is the vads-color-success. I just added the link to the latest mockups in the ticket so that it doesn't link to the Sketch file anymore. 

[Facility Locator Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=0-1&t=hiN4vHJDfdU4dNTb-1)

**Comment by jilladams** [comment]
@mmiddaugh FYI that this work on the Provider core training merged today, and should be in prod when you're back from CWS!

**Comment by davidmpickett** [comment]
Verified on Prod: https://www.va.gov/find-locations/?address=1005%20White%20Willow%20Way%2C%20Morgantown%2C%20WV%2026505&bounds%5B%5D%5B%5D=-80.705935&bounds%5B%5D%5B%5D=38.879782&bounds%5B%5D%5B%5D=-79.205935&bounds%5B%5D%5B%5D=40.379782&bounds%5B%5D%5B%5D%5B%5D=-80.705935&bounds%5B%5D%5B%5D%5B%5D=38.879782&bounds%5B%5D%5B%5D%5B%5D=-79.205935&bounds%5B%5D%5B%5D%5B%5D=40.379782&context=Morgantown%2C%20West%20Virginia%2026505%2C%20United%20States&facilityType=provider&latitude=39.629782&longitude=-79.955935&page=1&radius=10&serviceType=101YP2500X&bounds%5B%5D=-80.705935&bounds%5B%5D=38.879782&bounds%5B%5D=-79.205935&bounds%5B%5D=40.379782

<img width="330" alt="Screenshot 2024-07-22 at 11 05 34 AM" src="https://github.com/user-attachments/assets/5e7f1823-d471-4878-96c6-dc67eab8cee1">
