### ISSUE TITLE
Update VR&E name in Facility Locator 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#15837]
## Description
`Vocational Rehabilitation and Employment` was renamed `Veteran Readiness and Employment` but this change has not been reflected in the Facility Locator.

This is likely hardcoded in vets-website and possibly content build

<details>
<summary> Screenshots </summary>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnhxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--405e77654d86d3008727d24ffc1d7af126068f91/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5e207c8e9c57cf933082ba3d52b82895e2c8bce5/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjlxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4ccb42d82dee0e92871c9d04059ffef86db344ad/image.png)

</details>

## Tasks
- Update the dropdown list of VBA services by replacing `Vocational Rehabilitation and Employment` with `Veteran Readiness and Employment`
- Update the displayed name when it appears on detail pages, such as [VetSuccess on Campus at Middle Tennessee State University](https://www.va.gov/find-locations/facility/vba_320f)
- Update the search parameters heading displayed above search results

## Acceptance criteria
- [x] When facility type = "VA benefits", the drop down list includes `Veteran Readiness and Employment help` and does not include `Vocational Rehabilitation and Employment help`
- [x] When a search is performed for facility type = "VA benefits", the search parameter heading reads "Showing x - y results for "VA benefits", "`Veteran Readiness and Employment help`" near "(geographic parameter)" 
- [x] When a Veteran clicks through to a detail page for a facility offering `Vocational Rehabilitation and Employment help` , the name is displayed as `Veteran Readiness and Employment help`
- [x] `Veteran Readiness and Employment help` is only displayed as a service for locations which have indicated they offer it

**Comment by davidmpickett** [comment]
@mmiddaugh Relatedly, we should probably also look at updating the name in the Service Taxonomy. It's showing up with the old name for VAMCs 
![Screenshot 2023-11-08 105001](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/631f9c54-4a37-4829-be49-c5a515785fd4)
https://prod.cms.va.gov/health-care/vocational-rehabilitation-and-employment-programs
