### ISSUE TITLE
component: node--event

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#15908]
## Requirements

```[tasklist]
### Tasks
- [x] type definitions - Drupal node type, Next Build page type
- [x] query definition - query drupal data, map to next bulid type
- [x] tests for query/formatter
- [x] layout component
- [x] Google maps component
- [x] Facility location reference
- [x] Storybook
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16190
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8676
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9118
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14744
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15313
```

## Background & implementation details

**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/event/fields

**API query for individual node:** https://prod.cms.va.gov/jsonapi/node/event/31269b5d-da18-497b-9fd4-42b77104ecd1?include=field_listing,field_additional_listings,field_media,field_media.image,field_administration

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/event.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/nodeEvent.graphql.js

**Events-specific filters:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/filters/events.js
**Some filters used by events:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/filters/liquid.js

Note: there is additional logic in Content Build for dealing with Event Listing pages. These are not handled here.

**Comment by timcosgrove** [comment]
This is complete.
