### ISSUE TITLE
Spotlight/Featured Content improvements across Facilities products

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#15931]
### User Story or Problem Statement
Featured content (spotlight) is used across Facilities products. They currently have some accessibility issues or inconsistencies between Drupal and Front End that need improvements

### Affected users and stakeholders

* CMS editors of VAMCs, Vet Centers, and soon to be VBA Regional Offices

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by jilladams** [comment]
When #13804 is complete and we're ready for next step ticketing, note to PM selves: 
* Drupal ticket: align UI, add conditional formatting in CTA section
    * address state of #13801, whether/how that ticket definition changes
* FE ticket for VAMC update to adopt the paradigm
    * update #5731 or close it as dupe of implementation ticket
    * same for #12080 
* Change management issue
    * VHA DM comms
    * KB article updates as needed
