### ISSUE TITLE
[Design - Search] Need text and design for >> Errors occurring when search string is too long

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#15983]
### User story

**AS A Veteran or other user of VA.gov
**I WANT to be limited as to the length of my search text
**SO THAT I don't encounter an error when I kick off the search
**AND** if I exceed the length allowed, I will see a user-friendly error message telling me about the field length restriction

### Design
[Search UI Sketch file](https://sketch.com/s/433403fb-b16c-4c98-867e-181d86208ba2)

## Acceptance criteria

Check to see if there is an existing design element for search restrictions/errors so that may be used if possible.

**AC1: Unauthenticated user is searching on VA.gov**

**GIVEN**: I'm utilizing one of the Search fields on one of VA.gov's UNAUTHENTICATED pages
**WHEN**: I enter attempt to enter a string of text in the Search field that exceeds the point where an error will occur
**THEN**: the search is not successful 
**AND** I see a user friend error message

**AC1: Authenticated user is searching on VA.gov**
**GIVEN**: I'm utilizing one of the Search fields on one of VA.gov's on an AUTHENTICATED pages
**WHEN**: I enter attempt to enter a string of text in the Search field that exceeds the point where an error will occur
**THEN**: the too long text isn't actually submitted (to alleviate the monitoring noise in the error logs) search is not successful
**AND** I see a user friend error message

Notes:
* any solution should encompass both the search bar in the header and on the search results page (and anywhere else it might live).
* this particular error only displays when the text-length limit is reached, and doesn't affect any existing errors for other scenarios.

```[tasklist]
### Tasks
- [x] Create design in Sketch and write help text for error
- [x] Review final design with Fran, Amanda, and Dave (and Jill)
- [x] Add final design to the original engineering ticket
- [ ] Prioritize the original engineering ticket when it's ready (Fran task)
```

**Comment by randimays** [comment]
There is also a full site search available at va.gov/resources when you select `All VA.gov`

**Comment by thejordanwood** [comment]
I created a mockup in [this Sketch file](https://sketch.com/s/433403fb-b16c-4c98-867e-181d86208ba2) that shows the error message we want to use.

**Comment by thejordanwood** [comment]
End of sprint update:

I started [a slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1700511025900389) to get feedback for this. Amanda has approved, but I'm not sure who else needs to sign off on this. 

cc: @FranECross @jilladams

**Comment by FranECross** [comment]
@thejordanwood Thanks, Jordan! Jill and I discussed with Dave in a recent product sync, so I believe we're good on sign-offs since you have Amanda's. I'll add an explanation in the description for our/anyone's future selves to be aware this only displays when the text-length limit is reached, and doesn't affect any existing errors for other scenarios.

**Comment by thejordanwood** [comment]
Thanks @FranECross! I've added the design to the original engineering ticket. You can close this whenever you're ready to.

**Comment by FranECross** [comment]
Acknowledging and closing the ticket. Thanks!
