### ISSUE TITLE
(PW) Sprint 97 Priorities & Candidates

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#15992]
# Sprint Priorities #

```[tasklist]
## 🥅 Goals 🥅
- [ ] 📣UX: Provide a meaningful error message to the Veteran and their caregivers if they enter a search string that's too long and the search fails.  department-of-veterans-affairs/va.gov-cms#15983 
- [ ] 📣 FE:  Translation Front-end: Ensure a better experience for Spanish-speaking Veterans & their caregivers by ensuring pages displayed in Espanol also display translated breadcrumbs and left navigation department-of-veterans-affairs/va.gov-cms#15759 
- [ ] 📣Drupal:  Drupal 10 Testing department-of-veterans-affairs/va.gov-cms#16013 
```

# Candidates for Sprint 97 (Nov 08 to Nov 21)
```[tasklist]
##  Campaign Landing Page department-of-veterans-affairs/va.gov-cms#15807  
- [ ] **Value Prop**: Ensure a more professional visual user experience for Veteran's, their caregivers, etc. when they visit VA.gov, thus garnering more Veteran confidence in the VA.gov site
   - [ ]  department-of-veterans-affairs/va.gov-cms#15632 
  - [ ] The Change Management ticket below is for Fran/Jill
   - [ ] department-of-veterans-affairs/va.gov-cms#15806 
   ```

```[tasklist]
## Income Limits App
- [ ] **Value Prop**: Ensure Veterans and their caregivers aren't adversely impacted by issues if they occur by clearly defining vfs-public-websites-frontend in vets-api as a codeowner
   - [ ] department-of-veterans-affairs/va.gov-cms#15868 
```

```[tasklist]
##  Monitoring & Alerts
- [ ] **Value Prop**: Ensure a better Veteran & caregiver experience by providing a meaningful error message to the Veteran, and also by reducing the number of 'false' errors being logged so that the VA.gov support folks can address actual errors
   - [ ] department-of-veterans-affairs/va.gov-cms#15983 
```

```[tasklist]
##  VA Benefits Taxonomy
- [ ] **Value Prop**: Ensure Veterans and their caregivers receive current information quickly by providing the means for content editors to quickly and efficiently add content to VA.gov.
   - [ ] department-of-veterans-affairs/va.gov-cms#15397 
   - [ ] Note that this will be a stretch goal....
```

```[tasklist]
##  Outreach (and other) Events Improvements [(Epic department-of-veterans-affairs/va.gov-cms#13527)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13527)
- [ ] **Value Prop**: Ensure a better Veteran & caregiver experience by allowing Content Editors to provide an email address as an alternative for Veteran/caregivers to RSVP to event with
   - [ ]  department-of-veterans-affairs/va.gov-cms#15385 
- [ ] **Value Prop**: Provide a broader range of event information for Veterans, their caregivers and other users of VA.gov by providing Content Editors the ability to publish events not onto to their VAMC, but to the National Outreach Calendar as well as the same time. (The ticket below is the actual "make it live" action by removing the feature flags and making the feature available to all editors. 
   - [ ]  department-of-veterans-affairs/va.gov-cms#15968 
- [ ] **Value Prop**: Ensure Veterans, their caregivers, and other VA.gov users are aware of events happening in the future, not being limited to near-future events, so they can plan accordingly when wanting to attend.
   - [ ]   department-of-veterans-affairs/va.gov-cms#10716 
```

```[tasklist]
##  Translation Front End 
- [ ] **Value Prop**: Ensure a better experience for Spanish-speaking Veterans, their caregivers, and other Spanish speaking users' by having the proper breadcrumb and left nav translations in place. _(Six pages were identified as having translation issues, detailed in the ticket below)_
   - [ ]  department-of-veterans-affairs/va.gov-cms#15759 
```

```[tasklist]
##  VETS.api Infrastructure Research department-of-veterans-affairs/va.gov-cms#10767 
- [ ] **Value Prop**: Ensure Veterans, their caregivers, and other VA.gov users have a fast, accurate search experience when they're trying to find information on VA.gov. _(The ticket below is to finish the research and documentation of site search infrastructure so that the PW team can not only maintain it, but also consider ways to improve and possibly change the number calls to Vets-.api.)_
   - [ ]  department-of-veterans-affairs/va.gov-cms#10768 
```

```[tasklist]
##   Ongoing Analytics Analysis & Usage Research 
- [ ] **Value Prop**: Ensure a better experience for Veterans, their caregivers, and other VA.gov users by understanding their usage of VA.gov to ensure we enhance/build/fix the most impactful features in the site. _(Note that the ticket below is for Fran)_
   - [ ]  department-of-veterans-affairs/va.gov-team#69474 
```

```[tasklist]
## Medalia Survey Data (encompasses 1st-time Visitor & other Q4 Priorities)
- [ ] **Value Prop:** _Analyze the qualitative survey data for the remaining PW portfolio in order to determine future projects to benefit Veteran's experience in the website and tools_
  - [ ] department-of-veterans-affairs/va.gov-cms#12791
```
```[tasklist]
## Drupal 10 Launch Testing
- [ ] **Value Prop:** _Provide ongoing value to Veterans and their caregivers by ensuring that the Drupal 10 upcoming launch doesn't introduce bugs or cause issues in what is presented to them in VA.gov._
  - [ ] department-of-veterans-affairs/va.gov-cms#16013 
```

D10: Updated testing toward launch department-of-veterans-affairs/va.gov-cms#16013

**Comment by jilladams** [comment]
New topics: 
* D10 testing: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16013 - [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1699287512488959)
* Income limits downtime 11/18-11/19 (needs a ticket) - [Slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1699290324722839)

**Comment by jilladams** [comment]
@FranECross Notes from review: 
* We may want Drupal 10 testing to be the Drupal sprint goal, now that we know updated timing for that launch.
* #15397 (magichead collapse feature) may not fit or could be stretch - Daniel's sprint will be pretty full with D10 added

Otherwise looks good to me!
