### ISSUE TITLE
Shadow launch: 1010EZR finish when prod launched

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#15994]
## Statuses
[2024-09-12] [Fran] Message sent to Heather J asking for status on this item.

**BLOCKED by greenlight from 1010EZR team**

## Description
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15802 we dark launched a page that duplicates production content: 
* Staging page: https://staging.va.gov/health-care/update-health-information-1/
* Node: https://prod.cms.va.gov/node/62530

When 1010EZR completes user acceptance testing, their team will update the production version of the CMS page to its new content. The dark launched page will be deprecated. 

* **Technical point of contact** for vets-website React code: @longmd 
* **Strategic point of contact** for timing & approval to publish the node to Staging: @alexseelig @hdjustice 

**Tasks:**

- Archive/unpublish the node: https://prod.cms.va.gov/node/62530
- Remove the node ID from [Staged Content entity subqueue](https://prod.cms.va.gov/admin/structure/entityqueue/staged_content/staged_content?destination=/admin/structure/entityqueue) config - (node id == 62530)
- Run content release
- Staging page should no longer appear, and page will not be live on prod

## Acceptance Criteria
- [ ] 1010EZR provides greenlight to deprecate the Staging only page
- [ ] https://prod.cms.va.gov/node/62530 is archived / unpublished
- [ ] Staging entity queue no longer contains node 62530

**Comment by hdjustice** [comment]
Hi @FranECross - the form went into production in April, I believe we can close this ticket.  Thank you!
@alexseelig

**Comment by jilladams** [comment]
Thanks Heather. @FranECross I can confirm that the Staging shadow launch queue is empty, but we need to verify the state of node 62530 before we close this. (The deploy shield is up for the CMS right now, so can't do that at the moment, but can later after daily deploy.)

**Comment by jilladams** [comment]
Verified via the revision log on the relevant node that we worked with RandiH to archive it back in March: https://dsva.slack.com/archives/C52CL1PKQ/p1709565637160509

Closing.
