### ISSUE TITLE
Add VA Services taxonomy term information to Service Region node:edit

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#15990]
## User Story or Problem Statement

As a VBA national editor, I want to see the nationalized service related information when creating or editing a service region so that I have a better understanding of how a service region will be rendered on the front end.

### Service Region node:edit
![Screenshot 2023-11-03 at 11 13 42 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/2346d352-7e4d-4689-9243-564e0232a6fc)

### VBA Facility Service node:edit (for comparison)
<img width="1840" alt="Screenshot 2023-10-17 at 7 24 54 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/f89ae296-d33b-4ed9-9fb1-ef2dec232e84">

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
@xiongjaneg Here's that ticket I created about Service Region.
