### ISSUE TITLE
Disable workflow participants module

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1600]
## Description
Remove the Workflow Participants module and related custom code.

## Acceptance Criteria
- [ ] Workflow participants module is disabled.

## Implementation Steps
- [ ] Disable `workflow_participants` and `va_gov_notifications`. PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1987
- [ ] Remove `workflow_participants` from composer and `va_gov_notifications` from code base

**Comment by indytechcook** [comment]
PR for disabling the `workflow_participants` module and removing the related views.  The `va_gov_notificaitons` module was already disabled.

https://github.com/department-of-veterans-affairs/va.gov-cms/pull/1987

**Comment by swirtSJW** [comment]
1987 has been merged.  It is ok to proceed with a PR to remove the module from composer.

**Comment by indytechcook** [comment]
Send PR is in: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2000
