### ISSUE TITLE
Enhance the editorial experience for creating VAMC system health services DUPE

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1601]
## User Story or Problem Statement

When editing a VAMC system health service: 
* i can't see the content in the VHA managed health care service taxonomy
* the Governance box sometimes overlaps with the WYSIWYG if my window is too narrow, because of a Google Chrome bug related to select lists that get very wide. 

## Acceptance Criteria
- [ ] The select list for VHA health service has been replaced with an Entity browser that shows all 

## Implementation steps
- [ ] Create a an entity browser for VHA health services
- [ ] Apply to the VAMC system health service content type, replacing the

**Comment by kevwalsh** [comment]
Dupe of #1608
