### ISSUE TITLE
Implement Long-term Fix to Address Outdated Software Causing Test Failures

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#16067]
## Background
This is a follow-on from #16036 which was closed when #16046 was merged. During Staging tests CMS builds the site from the Content-Build repository. A change to the included project packages `node-libcurl` was compiled with a higher version of GCC than our servers in BRD come installed with.

There are limited to no options to update to a newer version of GCC from Amazon's package manager. They do provide GCC v10, but the system I believe is built on GCC v7.X.Y and that mis-match can be problematic.

Amazon does have an AMI newer than AL2, AL2023 which comes with GCC 11.X. The challenge being the current build and deploy infrastructure's software packages are out-of-date and fail to build AL2023. We'd need to update or otherwise run ansible build tasks elsewhere with up-to-date packages.

Far field would be to migrate Staging and Production to containers and reap the rewards of faster more responsive image changes versus server changes.

### User Story or Problem Statement
As a DevOps engineer I need to determine and implement a longer-term solution than #16036 provides, so that I can unblock other teams making improvements to content-build.

### Affected users and stakeholders

* CMS Platform Engineers
* Developers of Content-Build

https://dsva.slack.com/archives/CJT90C0UT/p1699300432617899

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
- Implement Amazon Linux 2023. It comes with GCC 11.2 installed which will meet our needs
- Install a more recent version of GCC and use linux LD_* environment variables to run yarn commands

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Team has defined tickets required to determine path forward and implementation.
- [ ] Developers in Content-build are free to use packages built with newer versions of GCC without breaking Staging tests.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`
