### ISSUE TITLE
Improve editorial experience for facility and local health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1608]
## User Story or Problem Statement

Forms: 

* As a member of VAMC upgrade team adding or editing VAMC system health services, i want to see the Nat'l health service taxonomy content inside the form. 

Content review: 
* As a member of VAMC upgrade team reviewing my VAMC system and facility health service nodes in Drupal, i want a decent content proofing experience. (eg at `/va-erie-health-care/system-health-services/pharmacy` and `/facility-health-services/extended-care-and-rehabilitation-at-butler-va-medical-center`)
* As a member of VAMC upgrade team working on hundreds of VAMC system health service and facility health service nodes, i want good node titles so that i can find my content more easily. 

## Acceptance Criteria
- [ ] New VAMC system nodes contain the name of the health service and the VAMC system in the node title (not a value visible to end users). 
- [ ] The VAMC system health service form contains an entity browser for health services, not just the term name in a select list. 
- [ ] The order of the fields on the default VHA health service taxonomy term, within the above entity browsers, displays the order of the fields on va.gov (Name, Patient-friendly name, Common conditions, Description)
- [ ] The VAMC system health service view (eg /va-erie-health-care/system-health-services/pharmacy ) has three field groups: 1) the VHA health service 2) the VAMC system health service description 3) the health services from all facilities offering that service. Field group labels are intuitive and there are no unnecessary/redundant field labels. 
- [ ] The VAMC facility health service view (eg /facility-health-services/extended-care-and-rehabilitation-at-butler-va-medical-center ) has the same three field groups, but only shows that facility's description--not all facilities in the VAMC system. 

## Implementation steps
- Create entity browser for health services
- Various form and node display configuration
