### ISSUE TITLE
Facilities Sprint 98

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16103]
## Schedule Notes
- Christian OOO 11/20 - 11/24 (3 days in sprint 98)
- Thanksgiving holiday 11/23
- Friday after Thanksgiving 11/24
  - A1M holiday
  - Agile Six not a holiday
  - Civic Actions holiday
- Steve OOO 11/27

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
- 🎯 Drupal: #15869
- 🎯FE: #15957
- 🎯UX: #14888 
- 🎯UX: #15929 

### VA Police Transparency #14327
- [ ] Drupal: #16015 
- [ ] Drupal: #15715 
- [ ] FE: #16208 
- [ ] UX: #15631 carried over, in progress

### VBA Regional Office Modernization MVP #10514
- [ ] Drupal: #16153
- [ ] FE: #15956 carryover
- [ ] FE: #14942 
- [ ] FE: #14947 
- [ ] FE: #14937 
- [ ] UX: #15748 
- [ ] Accessibility: #14898 

### Facility Locator
- [ ] FE: #16195 
- [ ] UX: #14515

### VAMC
- [ ] Drupal: #16152 also related to VBA
- [ ] UX: #16156 Dave working on first AC

### Vet Centers
- [ ] FE: #15424 (related 15660 review at UX sync 11/29)

**Comment by mmiddaugh** [comment]
Based on discussion this morning, we can likely replace [Draft VA health chat research plan #16012](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16012) with [Draft Facility Locator mobile map research plan & conversation guide #14515](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/14515) (or at least the research plan)

---

The following VA police issues may be blocked since they are all pending vendor data input - if anything can be done in the meanwhile, let's identify and prioritize those tasks 
  - [FE: Finalize structure of CSV -> JSON for Police data #15722](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15622)
  - [FE: Finalize component reading data from redux for Police Transparency data #15723](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15623)
  - [Updates to VAMC Police data page after collab cycle feedback #15631](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/15631)

---

If https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15660 is complete, will it be possible to pull in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15424 and complete the front end work?

---

Priority candidates
- 🎯 Drupal: [Apply and test workflows for VBA Facility content type](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15869#top)
- 🎯FE: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15957 and/or https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15956 as they were previously carryovers
- 🎯UX: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14888) and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14515
