### ISSUE TITLE
Migrate Github Actions to use AWS OIDC instead of AWS Access Keys.

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#16151]
### Summary
Use OIDC instead of AWS secrets in VFS-CMS owned repositories. This gets us away from storing these sensitive values in GH secrets. Ask @ph-One for pointers, if necessary. But first, read through [this Slack thread](https://dsva.slack.com/archives/C04CYC4LMU6/p1699970664394349).

### Acceptance Criteria

- [ ] All repositories we're responsible for are identified.
  - [ ] Identify all workflows leveraging the AWS API.
- [ ] Setup and configuration is complete for all repos.
- [ ] All repos no longer use AWS Access Keys so that GHA can auth with AWS.
- [ ] All repos use OIDC to auth with AWS.

### Implementation Tasks
- [ ] configure IAM Role to allow a repo to use OIDC to authenticate and use the role
- [ ] add that Role's ARN to the repo's Action Variables
- [ ] Update the workflows in all repositories that use `${{ secrets.AWS_SECRET_ACCESS_KEY }}` and `${{ secrets.AWS_ACCESS_KEY_ID }}`. (Similar to what is done in https://github.com/department-of-veterans-affairs/devops/pull/13615 and https://github.com/department-of-veterans-affairs/devops/pull/13718.)
- [ ] Delete secrets that were removed in above step from here: https://github.com/department-of-veterans-affairs/vets-api/settings/secrets/actions (and the equivalent in the manifests repo).

## Follow-on Tickets:
 - [SPIKE] To determine repos and technical requirements
 - For each repository identified configure it to use OIDC
 - For each repository identified update workflows to use OIDC instead of secrets
 - Determine feasibility of removing Access Keys. Map their usage out.
