### ISSUE TITLE
Prep for Federal Header/Footer research

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16210]
### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up Federal Header/Footer research
**SO THAT** the research will happen successfully

### Tasks for Sprint 98 -- 5 points
**Finalize research deliverables**
- [x] Update research plan and conversation guide with any timeline or protocol tweaks

### Tasks for Sprint 99 -- 8 points
**Finalize research deliverables**
- [x] Update conversation guide with any protocol tweaks based on revised prototypes
- [x] Add new full and bitl.ly links for both prototypes info convo guide
- [x] Recopy into EnjoyHQ

**Coordinate with Research-Ops and Perigean**
- [x] Create recruiting request and submit to VA Research-Ops. Use *Easy Recruitment Request* (for moderated research) or *Easy Recruitment Request for Unmoderated Cohorts* (for unmoderated research) on [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
- [x] Create *New Research Intake* request from [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - [x] In description, add links to github research folder and (from previous step) recruiting request form
  - [x] Make yourself the assignee
  - [x] Add labels for the project's product, research methodology, audience, etc. from [this list](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)
- [x] Make agenda for kickoff meeting w/Perigean
- [x] Review Perigean's recruitment survey before kickoff meeting
- [x] Attend kickoff meeting with Perigean and Sitewide UX Lead and/or PM
- [x] Test Zoom login from Perigean 
- [x] Change display name of Perigean Zoom account to "*<Moderator's first name>* (Moderator)" from "Perigean"

**Notetaking prep**
- [x] Make note-taking spreadsheet/Mural
- [x] Create a Mural board for research debrief sessions and/or data synthesis
- [x] Learn how to take notes/synthesis in EnjoyHQ--get something to read from Amanda, then discuss with her

**Pilots** 
[Guidance here](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-4-Run-a-pilot-session4.Runapilotsession)
- [x] Recruit pilot participant(s) from your company or another one
- [x] Schedule pilot(s) 
- [x] Slack your Perigean lead with the date, time, and participant for your pilot(s)
- [x] Schedule team debrief sessions after each pilot 
- [x] Schedule prep time before and debrief time after each pilot 
- [x] Confirm the day before with pilot participant(s) 
- [x] Run pilot(s) 
- [x] Debrief pilot(s) with team
- [x] Make any revisions needed to conversation guide and prototype
- [x] Send thank you slack message to pilot participant(s) 

**Recruitment / scheduling sessions** (for moderated research only)
- [x] Review recruited participant list from Perigean for requirements met
~- [ ] Follow-up with Perigean re participant list, if needed~--NO CHANGES NEEDED
- [x] Make sure all research sessions scheduled by Perigean are in your calendar
- [x] Make signup sheet for observers -- in github (email Cindy to sign up) and SharePoint (self-service)
- [x] Share signup sheet with team, stakeholders to sign up
  - [x] Invite anyone interested from Auth team, including Liz Lantz
- [x] Invite signed up observers to each session and optional debrief session, per signup sheet
- [x] Add participant numbers, dates, and times into recruitment intake ticket Participant Tracker (to check off later after each session) 
- [x] Make notetaking doc in github for each session to share with Perigean right before each session starts -- make all prompts in italics
- [x] Schedule 30-minute team debrief sessions once a day, and invite all observers signed up to observe in the previous 24 hours
- [x] Schedule prep and debrief time for each session
- [x] Slack/email all observers with instructions

## Acceptance Criteria
- [x] The target number(s) of participants have been recruited and scheduled (for overall & primary criteria)
- [x] The moderator(s), notetaker(s), and observer(s) have been invited to research sessions and daily debriefs
- [x] Pilot session(s) have been conducted
- [x] All preparation done before the first day of research sessions

**Comment by jilladams** [comment]
@cindymerrill can you add an end of sprint update for SPrint 98?

**Comment by cindymerrill** [comment]
Finished task for Sprint 98. The rest of the task will move into Sprint 99.

**Comment by cindymerrill** [comment]
Created new recruiting request and research intake request, thus submitting research to Shane for review and approval to send onto Perigean for recruiting.

**Comment by cindymerrill** [comment]
Plugging along on doing research prep tasks...
