### ISSUE TITLE
VBA RO Pilot Staging Review

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16268]
## User Story or Problem Statement
Staging review for VBA Regional Office Pilot MVP is scheduled for March 21. This is to prep any materials in advance by 5 days prior (longer due to using Tugboat). 

This is for product and content artifacts. QA artifacts are covered in #17318 

Per [Shira in Slack](https://dsva.slack.com/archives/CBU0KDSB1/p1702934828958529?thread_ts=1699289451.944039&cid=CBU0KDSB1):
Please be very clear within the Staging Review artifacts section what the scope of work is and which pages should be included for review. Not knowing this information can increase the amount of time we spend reviewing, and can lead to us reviewing pages outside of the scope of the changes the VFS team is making. I imagine this could also be a challenge with a new tool.

## Imposter components
[Amanda verified with Matt Dingee ](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17505#issuecomment-2010603117)that current Spotlight pattern will not be a blocker for staging review, but we should continue to replace it with a va-card component.

Imposter Components and V1 Design System Components will be flagged at Staging Reviews
Starting March 18th, 2024, Governance Team will flag as violations of the [VA.gov](http://va.gov/) Experience Standards any imposter components in VFS products. An imposter component is one that emulates the look and function of a Design System web component. In addition, Governance Team will flag the use of most V1 Design System components.

Impact: VFS teams should replace imposter components with the corresponding Design System web component absent a legitimate technical reason why the Design System web component is inadequate. V1 components should be replaced with the V3 counterpart if it exists.

[Documentation](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/change-history)

## Prerequisites / Blocking issues 
- [x] #17598
- [x] #17599
- [x] #17710
- [x] #15223
- [x] #16369 
- [x] #15155
- [x] #18159
- [x] #17999 

## Not launch blocking, but good to fix
Moved to parent epic - #10514

## Artifact prep

Required artifacts are linked in the [collab cycle ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/46029)

- Product artifacts
  - [x] Staging URL - N/A, we are going to provide a Tugboat
  - [ ] Tugboat URL 
  - [ ] Specify which pages are included in the review
  - [x] Staging test user information - N/A, unauthed experience
- Content artifacts
  - [x] Please include a link to any Sitewide CAIA feedback you received, including a content source of truth, any relevant static content page and entry point updates, and the intake form.
- IA artifacts
  - [x] Please include a link to any Sitewide CAIA feedback you received, including an IA review document or intake form.
- QA artifacts
  - [x] An artifact that corresponds to each standard in the [QA Standards](https://depo-platform-documentation.scrollhelp.site/developer-docs/quality-assurance-standards). (Created by Eli, but not linked yet in Collab Cycle ticket yet)
- Accessibility artifacts
    - [x] [Completed accessibility testing artifact](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=briandeconinck&labels=a11y-testing&template=a11y-testing.yaml&title=Accessibility+Testing+for+%5BTeam+Name%2C+Product+Name%2C+Feature+Name%5D). For details, see [Prepare for an accessibility staging review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/prepare-for-an-accessibility-staging-review).

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/16268?planning-poker) with Zenhub @davidmpickett

**Comment by davidmpickett** [comment]
IA artifacts added

**Comment by davidmpickett** [comment]
Content Artifacts section added as well. @xiongjaneg let me know if there's anything else I can do to support you on this

**Comment by xiongjaneg** [comment]
@davidmpickett You are the awesomest. Thank you!

**Comment by xiongjaneg** [comment]
Staging review postponed, moving issue to backlog for when review is rescheduled

**Comment by davidmpickett** [comment]
Adding #17095 as a blocker since imposter components will no longer pass staging review.

**Comment by mmiddaugh** [comment]
I'm not sure ["Additional Hours Options" content shows in Italics #17686](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17686) should be considered launch blocking since it's the existing behavior on VAMC pages in Prod (although we do need to fix it)

**Comment by jilladams** [comment]
@davidmpickett to line up approach, I converted this to an epic and pulled the blocking issues into this epic, so it acts like the Service Locations launch plan.

**Comment by mmiddaugh** [comment]
@davidmpickett if at all possible, we should improve the editor UX slightly by adding more support via navigation to the VBA Facility Service workflow from the VBA facility node before staging review
- i.e., Replace "Facility services are created on a different page." with "Add or edit Facility services [here](VBA service link)"
<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEpoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ce89ff462bf0a195fd92ae264b9e6f38ee20daf1/image.png" alt="image.png" />

**Comment by jilladams** [comment]
@davidmpickett  Can we move "Not launch blocking" list out of this epic into the parent Pilot epic?

**Comment by davidmpickett** [comment]
> @davidmpickett Can we move "Not launch blocking" list out of this epic into the parent Pilot epic?

Great idea. I'll move those now

**Comment by davidmpickett** [comment]
@Agile6MSkinner @jilladams @mmiddaugh I'm closing this Epic since it reflected the work to get TO Staging Review. Any work that comes FROM Staging Review tomorrow can sit in the [Pilot Epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514)
