### ISSUE TITLE
<Summary of enhancement>

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#16273]
## User Story or Problem Statement

As a n editor of any kind, I need a way to be able to add a revision log message to archived content, without needing to convert the node back to draft and then again move it to archived.  This is critically important to Facilities where there closure status it tracked in revision log messages.

This requires adding the transition of archived from the archived state to the archived state.

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/8d0a92e0-5f47-41b1-b32e-3884121cd9b5)

[Related slack conversation](https://dsva.slack.com/archives/C0FQSS30V/p1701464409940849)

There is not a great reason to have it limited the way we currently do.

## Acceptance Criteria
- [ ] "editorial" workflow allows transition from archived to archived.
- [ ] "archive_restricted" workflow allows transition from archived to archived.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by swirtSJW** [comment]
This would impact all workflows so will likely need buy-in from CMS team and Public websites.

**Comment by xiongjaneg** [comment]
@BerniXiongA6 @maortiz-27-80 This was discovered by our team but isn't specific to Facilities, so this might deserves a look to see which team is appropriate to put in their backlog. Thanks!
