### ISSUE TITLE
[Epic][AP] Events

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16307]
## Requirements & Goals
 
The goal is to implement all Events front-end functionality in Next Build and migrate it away from Content Build.

```[tasklist]
### How will we know we've achieved our goal?
```

## Work

```[tasklist]
### Issues or tasks to be turned into issues
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16290
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15908
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16473
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16399
```
