### ISSUE TITLE
Vets-website applications in Next Build

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16308]
## Requirements & Goals
This ticket is about hosting vets-website applications in Next Build pages. Currently Content Build generates an entry HTML page which houses vets-website applications. This functionality will need to be created in Next Build.

**From Chris:**

We should really not use that registry.json thing in Next Build. We should just have pages as TSX files at the appropriate route in src/pages/. We can have a shared <AppPage /> component that we can pass the appropriate information to so they all are the same (unless they have a reason to not be).

**From Brian:**
- there are other things to figure out there too, like the system to launch an app in stage but not prod
- And the header/footer settings

### How will we know we've achieved our goal?
- [ ] All vets-website applications' entry HTML can be created by Next Build
- [ ] Clear documentation is created to show how to add new applications and manage existing ones
- [ ] Change management for the move to Next Build is complete

### Issues or tasks to be turned into issues
- [ ] Spike: explore different options for vets-website apps in Next Build

## Supporting detail
To mimic the behavior of content-build, next-build will need the ability to build static pages that inject react applications inside of a template.

Currently this is achieved in content-build by adding the application to content-builds [registry.json](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/applications/registry.json) file.
Content-build will inject applications into a file called page-react.html which is the template for all applications.
Page-react has a loader called react-loader that checks to see if there is a loading message to give the user. It also checks to see if the application is _in_maintenance_. Once the application has loaded successfully the loading message is removed from the page. 

The following is the current makeup of an application
`{
    "appName": "COVID-19 screener",
    "entryName": "covid19screen",
    "rootUrl": "/covid19screen",
    "template": {
      "title": "COVID-19 screening tool",
      "layout": "page-react.html",
      "private": true,
      "vagovprod": true
    }
  },`

The meaning of the fields can be found inside of the new [application documentation](https://depo-platform-documentation.scrollhelp.site/developer-docs/creating-a-new-application).

As a note, all applications use the layout of "page-react.html". This field may not be needed moving forward.

Some form of linking will need to be done with the vets-website repo that will allow a developer to test changes to their applications.
[This page](https://depo-platform-documentation.scrollhelp.site/developer-docs/setting-up-your-local-frontend-environment) shows how this scenario is handled in CB.
