### ISSUE TITLE
Add Childcare to VA service taxonomy

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#16312]
## Description 
[H.R. 840 (116th): Veterans’ Access to Child Care Act](https://www.congress.gov/bill/116th-congress/house-bill/840) directs the Department of Veterans Affairs (VA) to provide child care assistance to an eligible veteran who is actively participating in treatment, including mental health and health care services. 

The bill requires the VA to inform eligible veterans of the available child care assistance.

I've connected VHA DM to CAIA for program page and health hub needs. This team will support the request to add childcare to the VA service taxonomy so that PAOs can indicate services are available and to help the service become discoverable on the Facility Locator once Lighthouse v1 has been implemented. 

## Tasks
- [ ] Michelle to work with Justin on taxonomy content
- [ ] Editor announcement/change management
- [ ] We will need to inform Lighthouse when the taxonomy is added so they are prepared to accept data from CMS

**Comment by mmiddaugh** [comment]
per Justin in email 1/24/24, the first child care site at Fresno probably will not launch until April, so we can put on hold for now.
The name of the service may also change.

Type of care = Social programs and services
Service description = If you are a Veteran in need of childcare during your appointment, we offer VA Kids Care—a free, safe, and secure drop-in childcare facility you can use while attending a qualifying VA appointment at a VA facility.

**Comment by mmiddaugh** [comment]
Update January 14, 2025: still on hold
