### ISSUE TITLE
CMS Sprint Plan 100 (12.20.23 - 01.02.24)

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#16313]
**BX note: This sprint plan draft is in progress, this is not yet finalized.**

# Sprint 100 Capacity
All Eng: 21.5 pts
All UX: 7.4 pts
All Support: 1.6 pts
A11y: 1.1 pts
All CMS Team: 31.6 pts
(43.9% sprint capacity for team in Sprint 100)

# Sprint 100 Goals & Priorities
## SPRINT 100 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [ ] Goal 1:  D10 Runbook (#15538)
- [x] Goal 2: Working session b/t UX and DevOps for Datadog collab (#16541)

## SPRINT 100 PRIORITIES - not yet finalized
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:_

### D10 Runbook Deliverable (Epic #12238)
- [ ] #15538

### Siteimprove (Epic #10201)
DevOps
- [x] #16521
A11y
- [x] #16021
-- BX to MO: Siteimprove should be monitored by Product but we won't make it a sprint goal for hte team for S100.

Defect
- [ ] BLOCKED but keep an eye on this (from D10 testing) #16107 -- BX: carry over to the next sprint OR keep it on the roadmap to keep an eye on

#### Datadog Monitoring Expansion (CY2023 Q4 Goal) - (Epic #11928)
Both
- [x] #16541

DevOps
- [x] (3) #11281
- [x] (5) #13975 

UX
- [x] #16518

#### Alt Text Validation (CY2023 Q4 Goal) (Epic #15785) 
- [ ] Product #15944
- [ ] Product to meet with Edmund to discuss unrefined Alt Text tickets (need to understand what is critical for launch)

#### Knowledge Base Enhancements (Epic #14069)
UX
- [x] #16487 
- [x] #16489 
- [x] #16488

#### Collab Cycle (#14013) / CMS Governance (#14012)
- 

#### CMS DesignOps (Epic #12843)
- [x] #16518

#### Improvements to Content Release (Epic #14016)
- None for CMS this sprint, AP working on - Ask Nate

#### ATO Documentation (CY2023 Q4 Goal) 
- [x] #16427

#### Dependencies / Dependabot PRs
- [ ] (average 4 pts taken on per Dev) - Dependabot PRs = 1 point each. Total points completed will vary by sprint. Berni to update actual numbers at end of sprint.

#### Help Team, Partners, Clients and Stakeholders Hit Objectives
DevOps
- [x] (5 pts left) #13834 (BLOCKED) -- 3 pts completed in S98
- [x] #13632- Note: Unsure if this is the correct heading
- [x] (5) #16532

Drupal
- [ ] #16449
- [x] (3) #16538
Support
- [ ] #16508

QA
- [x] #16358 - Note: team to point at sprint planning 

Product
- [ ] (1) Create new KB article or update existing article : Outreach Hub: How to archive Outreach Materials #15050 - low - Berni assigned self to ticket in S99, will carry over to S100

#### General
- [ ] (0) Onboarding Marcia Ortiz #15974
- [ ] (0) [Product] CMS product documentation needs updating #15805 

## SPRINT 100 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. It's hard to predict what will actually come in, but we're averaging about 20-30 points of unplanned yet necessary Dev work each sprint. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed

### Engineering Tickets that Need Refining
DevOps:
- [ ] #15646 
- [ ] #15941 (could be an async pre-refinement w/ DevOps)
- [ ] #16136  (could be a good one John)

Drupal:
- [x] #13632

**Comment by BerniXiongA6** [comment]
Closing Sprint 100 at 155% (49 points) of planned team capacity.
