### ISSUE TITLE
[EPIC] Migrate Sketch files to Figma & clean up

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16337]
## Description

This EPIC will be used to organize the tickets for the individual designs that needs to be moved to Figma.

The reason for the move is that the Sketch license ends on February 16th, 2024, and at that point out team should have downloaded any Sketch files they still need to Figma.

Public Websites and Facilities files that are in the CMS Figma account will need to be migrated the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024.

### Statuses

**2024-02-28 Status**
- All files have been moved from Agile Six Figma to VA Platform Figma ahead of the March 29, 2024 deadline
- Next step is to convert components in design files to Figma VA design system components. This will be done whenever time permits. 

**2024-02-05 Status**
- All files have been moved from Sketch to Figma, including working files. 
- Next step is to start moving files form Agile Six Figma to VA Platform Figma by March 29, 2024

**2024-01-04 Status**
- Converted this ticket to an Epic
- Amanda reported that she spoke to Ericka W, and Public Websites and Facilities files that are in the Agile Six Figma account will need to be migrated the VA Platform Figma no later than March 29, 2024.

### User story

**AS A** PW and Facilities team member
**I WANT** to have all Sketch files that will continue to be needed going forward moved into Figma
**SO THAT** when the Sketch license expires, we can continue business as usual

### Additional Info from Platform
[How to move your work from Sketch to Figma](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma)
[Designing with Figma at VA](https://depo-platform-documentation.scrollhelp.site/research-design/designing-with-figma-at-va)
[Figma accounts and role permissions at VA](https://depo-platform-documentation.scrollhelp.site/research-design/figma-accounts-at-va)

### Quality / testing notes
Review each file after import to ensure fonts, colors, and styling imported accurately. 

#### Facilities Sketch files

<details>
  <summary>Do not move until February 1, 2024 AND all comments are resolved</summary>

- [x] Police Transparency
- [x] VBA Regional Office
- [x] Facility Locator

</details>

<details>
  <summary>High Priority</summary>

- [x] VAMC CMS Master
- [x] Vet Centers

</details>

<details>
  <summary>Low Priority</summary>

- [x] Lovell VA tricare VAMC CMS

</details>

#### Public Websites Sketch files

<details>
  <summary>High Priority</summary>

- [x] Outreach and events
- [x] Discharge Wizard
- [x] OCTO Brand Design (full file migration complete)
- [x] PACT Act
- [x] Home page presentation
- [x] VA-home-updates-2022

</details>

<details>
  <summary>Low Priority</summary>

- [x] Search UI
- [x] VA CLP Template
- [x] Software factory tool (full file migration complete)
- [x] O&E Wireframes W2
- [x] VA Resources support template
- [x] Income limits
- [x] VA form search
- [x] Yellow ribbon map
- [x] VA form redesign
- [x] VA learning center template v2
- [x] Harassment reporting tool prototype
- [x] FAF Download PDF
- [x] Yellow ribbon search results
- [x] VA learning center template v3
- [x] Learning center map
- [x] Campaign landing page template v1
- [x] Contact center journeys
- [x] Yellow ribbon map 2
- [x] Harassment reporting tool
- [x] FAF 10EZ
- [x] CLP tweaks 2021
- [x] Page rating
- [x] VA tier3
- [x] VA footer language

</details>

#### Design System Sketch files

<details>
  <summary>Do not move until February 1, 2024 AND all comments are resolved</summary>

- [x] USA Header Footer

</details>

### Agile Six Figma to VA Platform Figma (must be moved by March 29, 2024)

<details>
<summary>Current Working Files</summary>

- [x] VBA Content Specs

</details>

#### Facilities Figma files

<details>
  <summary>High Priority</summary>

- [x] VAMC facilities

</details>

<details>
  <summary>Low Priority</summary>

- [x] VBA Regional Office Prototype
- [x] Covid/Facility Status
- [x] VA medical Centers forms
- [x] Vet Centers forms

</details>

#### Public Websites Figma files

<details>
  <summary>High Priority</summary>

- [x] Header/footer prototype copy from A6's Figma account
- [x] Events
- [x] Full width banner alerts
- [x] Q&As

</details>

<details>
  <summary>Low Priority</summary>

- [x] Income limits prototype
- [x] Campaign Landing Pages
- [x] CTA with links content block
- [x] Magic Headers and Paragraphs
- [x] Benefit Content Model
- [x] News Promo Block
- [x] HUB List Menu
- [x] Tableview Patch UI
- [x] Events near me: Editor UX for testing

</details>

### Sketch to Figma

**All files need to be moved from Sketch to Figma by February 16, 2024.**

- [x] Make a list of Sketch files that need to be moved to Figma
     - [x] Public Websites
     - [x] Facilities
- [x] Move top priority files
- [x] Move low priority files
- [x] Move current working files by February 16, 2024

### Agile Six Figma to VA Platform Figma

**All files need to be moved from Agile Six Figma to VA Platform Figma by March 29, 2024.**

- [x] Make a list of Agile Six Figma files that need to be moved to VA Platform Figma
     - [x] Public Websites 
     - [x] Facilities 
     - [x] Mark current working files (This only applies to 1 file)
- [x] Move top priority files
- [x] Move low priority files
- [x] Move current working files by March 29, 2024

**Comment by FranECross** [comment]
@thejordanwood @jilladams I created a ticket for the work to migrate Sketch files to Figma, so we can plan accordingly. The Sketch license doesn't expire until Feb 24, 2024, but I thought perhaps a list could be made, and then separate tickets created to be weaved into sprints so we aren't caught at the last minute next year.

**Comment by thejordanwood** [comment]
@jilladams @FranECross I can list these out sometime, but for now will put the overview here. 

- There are 28 files in [the Public Websites folder](/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/8663f01a-b54e-40ed-b4f2-ac939905c6e3) in the Sketch workspace. 
- There are 6 files in [the Facility folder](https://www.sketch.com/workspace/c99d3e96-7c23-4210-b173-92a2b73a8788/p/40ca7f51-9176-44f3-8104-19514e340955) in the Sketch workspace. 
- Some of these files were created before my time on the project. Others have been created while I've been here, but not by me. My assumption is that I'm in charge of moving all of these files into Figma.

**Comment by FranECross** [comment]
@thejordanwood Thanks so much for this information. I believe you're correct about the ask falling on your shoulders. When you're not so bogged down, I can collaborate with you to get stories created to accommodate small chunks of work in a way that makes sense to you. cc @jilladams

**Comment by aklausmeier** [comment]
@thejordanwood We also need to import the Drupal UI files that were created for PW and Facilities products.

**Comment by jilladams** [comment]
@thejordanwood @aklausmeier I know we'll discuss today in Fac UX Sync, but noting: we'll want to think about points here.

**Comment by thejordanwood** [comment]
@aklausmeier I've added a list of the files in Sketch and the Drupal UI files that currently live in the Agile Six workspace. I grouped these by high and low priority, but please feel free to rearrange!

**Comment by jilladams** [comment]
Noting: Amanda intends to work on this during the break, so reflecting it will make some progress in Sprint 100.

**Comment by jilladams** [comment]
@aklausmeier @thejordanwood I know y'all plan to sync about status / plans here. Could you update notes on ticket for my / Jane / Fran's reference once you do? Thanks!

**Comment by jilladams** [comment]
Amanda noted in planning: She has migrated almost all the files and we don't expect to need more help. More details coming when there's time to spell it out.

**Comment by aklausmeier** [comment]
@thejordanwood All high and low priority files for PW and FAC have been imported to the VA Figma space. We will need to relink all design components including any necessary text styles to the Figma design system components  ([step 7 in migration process](https://depo-platform-documentation.scrollhelp.site/research-design/how-to-move-your-work-from-sketch-to-figma)) when our team has capacity or needs to do so because the product is being pulled in for iteration. Since these have been migrated, these files are not bound by the FEB 16 deadline.

In our Figma space, I have added a file "cover" to indicate current status. Link to [Figma status legend](https://www.figma.com/file/UlOytC2YfdmvajwlJtvqbB/File-Legend-for-Sketch-Import?type=design&node-id=0%3A1&mode=design&t=EZJulF1nXEdP5Y1C-1) for reference. 

Cover example indicating components still need to be updated:
![Screenshot 2024-01-03 at 11 37 35 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/137226108/cbb344c1-d7db-4c5b-ad09-1879acfe5235)

Current working files still need to be migrated by FEB 16. @thejordanwood this can be done anytime while you are working in the files. Comments will not migrate over so ideally these are resolved before migration or migrated before comments begin on a file. 

@jilladams @FranECross After sharing current status with Dave C., we will need to track each design file as it's own ticket possibly making this effort an epic rather than this one ticket. I can make a note above to a few of the design files that do not need this tracking w/in an epic because they are completed.

**Comment by aklausmeier** [comment]
In regards to moving our PW and Facilities files out of the CMS Figma space, this is on hold until we get confirmation from @EWashb on whether they will continue to stay in the separate CMS Figma space or they will move to the VA Figma account. This is dependent on a decision of where the CMS design component library will live. Some of these files are currently in progress and we wouldn't want to move them until comments are resolved.

**Comment by aklausmeier** [comment]
Public Websites and Facilities files that are in the CMS Figma account will need to be migrated the VA Figma folder "CMS Editor Experiences" no later than March 29, 2024. 

@FranECross @jilladams In an upcoming UX refinement, let's discuss how we can turn this ticket into an epic with tickets to track the work. @thejordanwood and I will most likely need your assistance.

**Comment by FranECross** [comment]
@aklausmeier Sounds great! If you have a simple list of items that need individual tickets, I can take care of converting this to an epic and then creating the associated individual tickets. Thanks! cc @jilladams @thejordanwood

**Comment by aklausmeier** [comment]
@FranECross Thanks! Every file listed in this ticket description will need it's own ticket w/in the epic unless it has "full file migration complete" next to it's name. This applies to file names with and without the checkmark. 

The AC's should be :

- Sketch file imported to VA Figma
- File Cleanup: Design components and styles relinked to Figma VADS

**Comment by FranECross** [comment]
@aklausmeier and @thejordanwood 😁I've created tickets for each files, and labeled accordingly (Facilities/Public Websites).

**Comment by aklausmeier** [comment]
@thejordanwood and @davidmpickett I changed the VA Figma folder from "CMS - Editor Experiences" to 2 distinct folders, "CMS - Public Websites Editor Experiences" and "CMS - Facilities Editor Experiences" to keep files organized by team.

**Comment by thejordanwood** [comment]
@aklausmeier All files have been moved from the Agile Six Figma to VA Platform Figma. 

We no longer need to worry about deadlines! Next step is to convert components in design files to Figma VA design system components, which will be done whenever time permits.

**Comment by FranECross** [comment]
Closing; some tickets completed, and some closed as no op with comments. Epic is completed.
