### ISSUE TITLE
Front end: Vet Center unpublished services should not be showing on VA.gov

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16362]
## User Story or Problem Statement
As a Veteran, I want to know which services are available at my Vet Center and should not see services that aren't available.

As a Vet Center editor, I want to show only services that are available at my Vet Center and my Vet Center page shouldn't show services that aren't available that I've unpublished.

Per [Slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1701387808889179), unpublished Vet Center services should not be showing on VA.gov.

Per Steve in [Slack](https://dsva.slack.com/archives/C0FQSS30V/p1702070337791989?thread_ts=1702069084.753339&cid=C0FQSS30V), The Vet Center services query is not filtering for Published (status)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/a0f3a56b-1198-43fb-9f85-11e963db134a)

## Sequencing for launch
August 15 change management will unblock Drupal #18003 to merge the Drupal PR.
This ticket should follow #18003 merge and use the Graph QL from that branch / PR.

## Acceptance Criteria
- [x] The Vet Center services query filters for Published status.
  - [x] If the service isn't Published, it doesn't show on VA.gov.
```[tasklist]
### Tasks
- [x] Verify "Draft", "Archives," "In Review," and "Approved" don't show on the front end
- [x] Verify that "published" services show on front end
```

**Comment by davidmpickett** [comment]
IMO there are a few different phases here:
- [ ] Content model / UX / Drupal -> SPIKE proposed path(s) for Vet Center editors to publish services 
  - There are a lot of gnarly implications to changing this, so I don't think we'll be able to hash all of them out via refinement alone, will need some dedicated time to exploring/documenting/conferring
- [ ] Product approves/chooses path
- [ ] Drupal implementation 
- [ ] Updates to FE query to filter by Published

**Comment by mmiddaugh** [comment]
Re: option to add a View Block of services to the Dashboard which would direct editors to admin/content filtered properly for services and their vet section 

**Notable differences in editorial experience**
- current admin/content workflow does not distinguish required services (which cannot be removed by editor) from optional services (which editors can remove)
- the method for adding a service in the current admin/content workflow takes the editor to ["Add content" menu](https://prod.cms.va.gov/node/add) which adds risk for confusion, at a minimum 
- current admin/content workflow does not display the national description, which could introduce risk for editors to duplicate the description 
<details>
<summary> existing service edit view </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/43f5c33e-a36a-4830-890f-eaba756cc7df)
</details>

<details>
<summary> admin/content service edit view </summary>

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/55411834/a2195dc2-eaa6-4d49-bbe0-9dcbcc56b4bb)
</details>

**Comment by mmiddaugh** [comment]
If we get into Dashboard changes related to this, #7269 [Improve Vet Center editor experience - dashboard and other](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/7269) may be relevant

**Comment by davidmpickett** [comment]
Historical ticket noting the ambiguity of Vet Center service moderation state: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7144

**Comment by davidmpickett** [comment]
> Re: option to add a View Block of services to the Dashboard which would direct editors to admin/content filtered properly for services and their vet section
> 
> **Notable differences in editorial experience**
> 
> * current admin/content workflow does not distinguish required services (which cannot be removed by editor) from optional services (which editors can remove)

It might be important to note that the only thing currently preventing Vet Center editors from Archiving Required Services is the fact that they are unlikely to ever go to admin/content. Required services aren't actually structurally different than non-required services in a content moderation workflow sense.

On Staging as a Vet Center editor, I was able to Archive a required service in my section

![screencapture-staging-cms-va-gov-st-louis-vet-center-service-st-louis-vet-center-addiction-and-substance-abuse-care-2023-12-11-19_15_34](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/086fb128-3294-48a7-9799-33d6a0ed1e73)

Although give that unpublished services are currently showing up on VA.gov, even archiving a service wouldn't necessarily remove it. 🤯

**Comment by xiongjaneg** [comment]
@xiongjaneg There is an accompanying Drupal ticket. This is not blocked by Drupal.

When we do this on front end, there will be change management with editors who have what they thought were published services but with this fix, these services will not be published.

**Comment by xiongjaneg** [comment]
This fix may also have the advantage of making it apparent to editors when they've only saved in Draft and never Published, because when they check their published page, draft content won't show.

**Comment by xiongjaneg** [comment]
Some of these issues may be impacted by the inline editor epic. Should this wait? Likely no, there is risk in publishing content not intended for publishing.

**Comment by mmiddaugh** [comment]
@xiongjaneg depending on level of effort, [Vet Center service editorial UX does not show national description #17177](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17177) may need to ride along with this work

**Comment by xiongjaneg** [comment]
blocked by IEF removal ticket

**Comment by swirtSJW** [comment]
This is blocked because currently if an editor edits a VetCenter Service, due to IEF, they do not have the option to publish their change.  So if we stop showing draft content, they have no way to get new edits out to the FE.

**Comment by jilladams** [comment]
This change would mean that the 30 draft services that currently appear in the front-end need to be published in order to continue appearing on the FE. 

We need to do CM for editors before we make this change.

**Comment by Agile6MSkinner** [comment]
@mmiddaugh is working with VetCenters with draft services to get them addressed. @mmiddaugh should we consider this one unblocked per our conversation?

**Comment by mmiddaugh** [comment]
@eselkin 
For validation purposes, here are a [few Vet Center services in draft](https://prod.cms.va.gov/admin/content?title=&type=vet_center_facility_health_servi&moderation_state=draft&owner=All) as of this morning

- [Ponce Vet Center](https://www.va.gov/ponce-vet-center/)
  - Whole health	
  - LGBTQ+ Veteran care
  - Intimate partner violence support	
- [Kona Vet Center](https://www.va.gov/kona-vet-center/)
   - Workshops and classes	
- [Seattle Vet Center](https://www.va.gov/seattle-vet-center/)
  -  Women Veteran care		
  -  Minority Veteran care	
  -  LGBTQ+ Veteran care
  
I did not see any of these services displayed on the relevant pages in Prod

**Comment by jilladams** [comment]
That's a verification in prod! Closing.
