### ISSUE TITLE
[Income Limits] Upload of 2023 data

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16371]
## Description
[2023IncomeThreshold.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13653178/2023IncomeThreshold.xlsx)

[2023GMTThresholds.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/13653180/2023GMTThresholds.xlsx)

Upload of 2023 data to S3.

Note: We need to coordinate with having an info alert TBD what that is.

The PW team is currently working on automating the upload of the data, however this upload needs to occur before that work will be completed.

Note: We want to provide Veterans with some type of alert, letting them know that there's new data available.

### Tasks for Fran to unblock this story:
- [X] Check with CAIA to determine what type of alert they prefer
- [X] Create an FE story if necessary, or arrange for timeboxed content if a full-width banner is used.

### User story

**AS A** Veteran, caregiver or other user of the Income Limits app
**I WANT** to see the most up-to-date information when I use the app
**AND** I want to see an in-page info alert letting me know the data has been updated
**SO THAT** my results are as accurate as possible

### Engineering notes / background
- Won't be imported into the dataset until the automated script runs to import into Postgres.. next run is midnight Jan 1, 2024.

## Acceptance criteria
- [x] Review the exported excel file to ensure fields match expected data schema
- [x] Review the exported excel file to ensure it's 2023 data
- [x] Coordinate with FE folks to ensure the info-alert in ticket [#16458](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16458) is released in lock-step with the upload
- [x] Upload to S3
- [ ] QA the Income Limits app to ensure it's returning the 2023 data
- [x] If possible, should be uploaded to S3 before code freeze starting on 12/22 so the next automated run picks it up
- [ ] Randi's change shouldn't be released until after the automated run.

**Comment by FranECross** [comment]
I emailed Joshua today regarding obtaining the exported excel file, and his response > Yes, we do not have next year's thresholds loaded yet but I will send them soon as they are done. 

Adding Blocked label.

**Comment by FranECross** [comment]
@dsasser @Becapa Just an FYI that Joshua provided the income limits data for 2024, and I've attached. Moving this out of blocked.

**Comment by FranECross** [comment]
@dsasser Will you please point this?

**Comment by FranECross** [comment]
@FranECross Check with CAIA on what they prefer for the type of info alert, and how long it will be in place.

**Comment by dsasser** [comment]
@FranECross pointed at a 2. However, I have some thoughts/questions:

1. What is meant by this AC? ` Info-alert displays`
2. Insofar as QA'ing this work, it helps to know that the data is automatically imported only once every 3 months (Jan,Apr,Jul and Oct) into the database. So unless we get Platform's help to run the 5 import scripts manually, we would need to wait until January to test.
3. Is it worth doing this if we are very close to automating the import in #16217?

**Comment by FranECross** [comment]
@dsasser If we're close to automating the import, I agree it may not be worth the effort. I'll touch base with Dave/Jill to confirm.

**Comment by FranECross** [comment]
@dsasser Regarding your question below, Dave mentioned that we want to alert Veterans that new content is available. I'll remove the AC from this ticket, because I need to collaborate with CAIA to get their take on what they prefer for an alert e.g. full width banner, etc. Thanks!

What is meant by this AC?  Info-alert displays

**Comment by FranECross** [comment]
After checking with Dave regarding his and stakeholder wishes, and with Daniel on timing of moving forward with the upload, we'll be targeting getting it up loaded next week before the code freeze. I'll also check with CAIA today to see if we can also move forward with a banner alert in the interest of providing info regarding new data to the Veterans when it's uploaded. cc @jilladams @dsasser

**Comment by FranECross** [comment]
CAIA Team member Laura Willwerth says that a Full-width banner isn't needed for this, but that we can add an in-page info alert after the intro paragraph on the first page of the tool with the following verbiage. Dave indicates we will need to update the React app with your provided content. I'll create a front-end ticket and link to this one.

We've updated this tool to check 2024 income limits
You can check your income limits for 2024 now.



https://dsva.slack.com/archives/C01K37HRUAH/p1702666933423939?thread_ts=1702655838.690279&cid=C01K37HRUAH

**Comment by randimays** [comment]
@FranECross To confirm, we're using this banner style?

<img width="700" alt="Screenshot 2023-12-15 at 2 28 30 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/19175324/8dd47278-932c-4d9e-aaa9-38c702d7eafe">

This is a pretty small change to the Income Limits homepage. Either Chris or I can tackle this next week, and hold the PR from merging until we're ready.

**Comment by FranECross** [comment]
@randimays I believe so.... @jilladams are you able to confirm the the banner Randi shared above the one suggested by CAIA? I haven't seen the various alerts or banners available (but will come up to speed on them). Thanks!

**Comment by jilladams** [comment]
This should be a UX decision, I think. @thejordanwood could you confirm -- UX typically decides which style of banner to use on a page? In this case, we're talking about: 

On Income Limits, adding an in-page Alert to notify Veterans that the app is now vetting for 2023 data starting in Jan, vs. 2022 data. Will use the [Alert component from the DS](https://design.va.gov/storybook/?path=/docs/components-va-alert--default), and the default is in Randi's screenshot above. I _think_ that's correct, rather than a Warning style, but could you confirm if you think a different style should be used, or if this is typically a Content and not a UX call?

**Comment by thejordanwood** [comment]
@jilladams My thinking would be that UX determines the style of alert and content approves the copy we suggest. 

I do believe Randi is currently using the right banner. This is [an informational alert](https://design.va.gov/components/alert), which the design systems says are "Used to provide helpful information or something that warrants a user’s attention. Not used for negative consequences."

**Comment by jilladams** [comment]
Lovely thanks! @randimays holler if you have any other questions.

**Comment by jilladams** [comment]
I just realized that outcome should go onto #16458 - noting it there.

**Comment by jilladams** [comment]
From planning: 
* Will upload the data to S3
* Won't be used by the API until scripts run that pull the data into postgres. That happens once every 3 months, and that happens in January. 
  * We can ask for that to run early. 
* FE should ship after the data takes effect in postgres

**Comment by dsasser** [comment]
## Status Update

The new data has been uploaded to:

- https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_gmtthresholds_temp.csv
- https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_incomethreshold_temp.csv

I archived the entire 2023 year (2022 income year) in a new s3 folder to `s3://sitewide-public-websites-income-limits-data/archived/2022/`

### Testing Performed

The newly exported 2023 income year files were not comprehensive, as expected (they didn't contain previous years, only 2023). I needed to combine existing csv data with the incoming exported data. To do this I:

Prep CSVs
- Uploaded the new .xls files to Google Drive.
- Normalized the field formats as described in [the documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/income-limits-app/data#converting-xlsx-to-csv).
- Exported these as new CSVs to my local desktop

Backup
- Uploaded these 2023-only CSVs to S3 for posterity [here](https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/archived/std_gmtthresholds_2023.csv) and [here](https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/archived/std_incomethreshold_2023.csv).

Create new CSVs
- Downloaded existing CSVs
- Appended exported CSV values in existing CSVs
- Saved CSVs, appending _2023 to the filenames.

Upload to S3
- Uploaded the new CSVs to S3, overwriting existing files

Test Import Scripts Locally
- Ran Sidekiq import scripts on my local vets-api instance against the new CSVs, which succeeded in adding 2023 records
- Verified row count between CSV and rows in database

Test API Locally
- Made API calls to the Income Limits API, passing in valid zip codes and dependents, using '2024' as the year.
- Validated the returned data matched the CSV data

Example API call: `http://localhost:3000/income_limits/v1/limitsByZipCode/97086/2024/1`

Example response:

```json
{"data":{"pension_threshold":21674,"national_threshold":49349,"gmt_threshold":72200}}
```

**Comment by jilladams** [comment]
For end of sprint: need to: 
* Verify midnight of Jan 1 scripts ran successfully, and that new data got pulled into postgres. 
* If so, this can close. If not, need to troubleshoot with (Platform?)
  * If so: FE is unblocked to merge https://github.com/department-of-veterans-affairs/vets-website/pull/27232

**Comment by randimays** [comment]
Validated this data was populated correctly in [a comment on #16458](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16458#issuecomment-1874312264). Nice work, @dsasser!

Closing!
