### ISSUE TITLE
Conduct Federal Header/Footer research readout and complete post-research tasks

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16375]
### User story

**AS A** researcher
**I WANT** to wrap up my research study
**SO THAT** I can share insights with others and protect participants' private information

## Tasks

**Collaborate**
- [ ] ~~Discuss draft recommendations with team~~ -- NOT NEEDED since this research report is being handed off to OFCIO
- [x] Discuss w/Amanda whether research readout(s) are needed. -- NONE, except that I am permitted to **present on research methodology**, such as what I learned about conducting research with accessibility tech users

**Research Readout(s)**
- [x] Draft readout presentation slides
- [x] Share readout slides with Sitewide UX Lead for feedback
- [x] Incorporate feedback from Sitewide UX Lead
- [x] *(optional)* Consider doing a practice runthrough to gauge flow and length
- [x] Present readout(s) to team and/or stakeholders
- [x] Revise report and/or readout slides per feedback from readout(s)
- [ ] *(optional)* Consider presenting at Sprint Demo; make a *very short* version of your readout slides -- WON'T DO because there aren't any more Sprint Demos for me on the contract
- [x] *(optional)* Consider presenting at Veteran Digital User Experience Weekly Design Sync meeting; slack Naomi Marcussen to schedule a date; [presentation template here](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)

**Add Findings to Research Repository**
- Once your report is final, link to the relevant research repository:
  - Veteran-facing research: [How to add research to Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70) > *What to do when you complete your research*
  
**Delete and Archive Research Materials**
- Review your notes and synthesis materials to make sure they don't contain any PII ([Personally Identifiable Information](https://depo-platform-documentation.scrollhelp.site/research-design/what-is-pii)). Then add them to your github research folder, and link to them in your research report.
- Once your readouts are complete, you should delete [session recordings](https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions) and transcripts from your computer and empty the trash folder.

## Acceptance Criteria - Sprint 105 (8 points)
- [x] After report revised and approved, findings added to Research Repo
- [x] Research methods readout slides started

## Acceptance Criteria - Sprint 106 (8 points)
- [x] Research methods readout slides drafted 
- [x] Incorporated all feedback on readout slides from Laura Flannery and Liz Lantz
- [x] Readout slides shared with Amanda for review
- [x] Incorporated feedback on readout slides from Amanda
- [x] Readout(s) conducted
- [x] Session recordings and transcripts deleted from your computer

**Comment by jilladams** [comment]
Acknowledged in planning: after research sessions conclude, Cindy will only have 1 day, maaaaybe 2, of work in sprint. So we're pulling this into Sprint 100 with the understanding that it will start but not finish until Sprint 101.

**Comment by cindymerrill** [comment]
@jilladams @FranECross This isn't the ticket I'd work on with my 1 day in the sprint. It's the data synthesis and reporting ticket instead. This ticket will wait until after the synthesis and reporting ticket is done.

**Comment by jilladams** [comment]
Updated both to reflect that!

**Comment by cindymerrill** [comment]
This ticket will likely wait until _after Phase 2 research has been completed_, at which point I will do a combined readout for Phases 1 and 2 together. @jilladams @FranECross @aklausmeier

**Comment by FranECross** [comment]
@cindymerrill @jilladams I'm going to move this ticket out of Stretch/Next Sprint into Refined since it's not going to be worked on until after completion of Phase 2 research.

**Comment by aklausmeier** [comment]
@cindymerrill Dave and I came to an agreement that no research shareout slide presentation is required. 

OPTIONAL: If time allows, an abbreviated presentation around AT/CodePen research methodology could be shared in the weekly design meeting in collaboration with @laflannery's insights. There would be no mention of the Federal H/F work. If questions were to come up around Fed H/F during any presentation Amanda would be point to respond. 

cc @FranECross @jilladams

**Comment by cindymerrill** [comment]
@aklausmeier I'm going to copy your comment into my readout and post-research tasks ticket, which is where it's relevant... 

cc @FranECross @jilladams

**Comment by cindymerrill** [comment]
@FranECross I updated this ticket for sprint 105 
FYI @jilladams

**Comment by cindymerrill** [comment]
I specified which AC's I'm aiming to do in this sprint @FranECross @jilladams

**Comment by cindymerrill** [comment]
Starting to work on research methodology readout slides.

**Comment by cindymerrill** [comment]
Finished drafting my research methodology slides and shared them with @laflannery and 2 others for feedback. Also reached out to @aklausmeier to ask when and how she wants to review them.

**Comment by cindymerrill** [comment]
Added findings to VA Research Repo and moved the study cards for phase 1 and phase 2 from Current to Complete. Already drafted readout slides on research methodology, so done with AC's for this sprint. @FranECross

**Comment by cindymerrill** [comment]
Revised AC's for next sprint. @FranECross

**Comment by cindymerrill** [comment]
Today I finished incorporating all feedback from Laura Flannery and Liz Lantz on the readout slides, and I shared them with @aklausmeier, Martha Wilkes, and some Ad Hoc folks for review. 

I'm trying to schedule a time to present next week to VA, which Martha Wilkes is helping with since the Monday VA UX Design meeting probably won't be possible on this short notice.

FYI @FranECross

**Comment by cindymerrill** [comment]
I incorporated feedback from an Ad Hoc researcher on the readout slides, and re-shared them with @aklausmeier and Martha Wilkes. 

I will be presenting my readout at this coming Monday's **VA UX Design Sync meeting (10 am PT on March 18)**, and also at an Ad Hoc UX meeting on Wednesday. 
FYI @FranECross @jilladams

**Comment by cindymerrill** [comment]
Amanda had no feedback on my readout presentation. Tomorrow I'll practice my presentation and time it so I'll be ready to present on Monday and Tuesday.

**Comment by cindymerrill** [comment]
@FranECross @jilladams Where would be a good place on github to post a PDF of my slides? I don't think they belong in the Public Websites header/footer folder. Is there a general research folder where you'd like me to put them?

**Comment by FranECross** [comment]
@cindymerrill I'll take a look. If I don't find anything obvious, we may need to wait for Jill to return to get a location. Thanks!

**Comment by aklausmeier** [comment]
@cindymerrill The accessibility slides can be added to the Public Websites Teams sharepoint site. I just created a [UX Research folder](https://dvagov.sharepoint.com/:f:/s/SitewidePublicWebsites/EjHVekCdkoRDkYHdI644Tn8BBjDZyhB2zELwXVIJph7lZw?email=Cynthia.Merrill%40va.gov&e=e53BLa) for you.

**Comment by cindymerrill** [comment]
I presented to the VA OCTO UX Design weekly sync meeting this morning, and it went well. Tomorrow I will be presenting to an Ad Hoc UX audience. After tomorrow's presentation, I will copy my slides into the Sharepoint folder that Amanda created.

**Comment by cindymerrill** [comment]
@aklausmeier Just wanted to check with you that it's OK for me to delete all of my header/footer research session recordings, which I normally do at the end of every research study. I don't know whether OFCIO or USWDS might want to see some of them, or whether my written report is sufficient.

**Comment by aklausmeier** [comment]
@cindymerrill written report is sufficient and I can pull from transcripts in EnjoyHQ if needed in the future

**Comment by cindymerrill** [comment]
@aklausmeier I copied my readout slides from today into the Sharepoint folder that you created.

**Comment by cindymerrill** [comment]
> @cindymerrill written report is sufficient and I can pull from transcripts in EnjoyHQ if needed in the future

OK, so I will delete the recordings. @aklausmeier Just a note that the transcripts are really bad, in that Zoom misinterpreted a LOT of the words so much doesn't make sense on their own. For many of the quotes I put into my report, I watched the video and edited the transcript to match what was said (and straighten out who said it--the participant, the participant's screen reader, or me). I did **not** do this throughout each transcript, which I don't think is worth the huge time investment this would take. I want you to know this before I delete all the recordings, Amanda.

**Comment by cindymerrill** [comment]
Recordings have been deleted.

**Comment by cindymerrill** [comment]
I've completed all required tasks and AC's.

**Comment by FranECross** [comment]
@cindymerrill Thanks so much for all your hard work on these tasks! 🎉
