### ISSUE TITLE
Facilities Sprint 100 Plan

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16391]
## Schedule Notes
Code freeze Dec. 22 to Jan. 2
Christmas holiday Dec. 25
New Year's holiday Jan. 1
Alexis out Dec. 18 to Dec. 27
Dave out Dec. 25 to Jan. 1
Jordan out Dec. 25 to Jan. 1
Steve out Dec. 22 to Jan. 1
Max out Dec. 25 to Jan. 5
Christian out Dec. 25 to 27, Dec. 29 to Jan. 2

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?

Tickets for top priority:
- [ ] 🎯 UX Design: #15631 ACs on FAQs, updates, CAIA
- [ ] 🎯 UX Research: #16293 AC for plan drafted
- [ ] 🎯 Drupal: #14238 
- [ ] 🎯 FE: #16243

### UX
- [ ] Police: #16415 reviews will carry over to 101
- [ ] VBA RO: #14888 ACs on review/feedback
- [ ] VBA RO: #14515 
- [x] VAMC: #16154 ACs on review/feedback

### Drupal
- [ ] Defect: #14238 
- [x] Defect: #16481
- [x] Defect: #16465
- [x] Vet Centers: #7563 
- [x] Flagged Facilities: #15456 
- [x] Flagged Facilities: #15457 

### Front End
- [x] Vet Center: #15424 pending feedback
- [ ] Police: #14942 pending unit test success
- [ ] Police: #16303 pending prod access for cypress
- [ ] Police: #16019 
- [ ] VBA: #16243 ideal for code freeze
- [ ] VBA: #14947 
- [ ] VBA: #14937 

## VA Police MMVP launch #16370!
