### ISSUE TITLE
Front End: Add data layer to VA Police page

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16407]
## Description
We need to ensure that we are able to capture data about the visits and interactions on VA Police pages, whether automatically through the use of design components or addition of custom code. 

## Tasks
- [ ] Determine coverage by components
- [ ] Determine if custom code is needed
  - [ ] If custom code is needed, tag PM to discuss with Michelle Dooley and the Platform Analytics Team before adding
- [ ] Add code
- [ ] Request the addition of Regional offices as a product to the existing VA.gov Content KPI DOMO Dashboard
- [ ] Request the addition of Medallia/Foresee

## Acceptance criteria
The following data can be collected from VA Police pages
- [ ] Number of pageviews (total and unique)
- [ ] Number of users (total and unique, new and returning)
- [ ] Click interactions by accordion
- [ ] Click interactions by button
- [ ] Click interactions by phone number (and from which accordion)
- [ ] Click interactions by link (and from which accordion)
- [ ] Scroll depth
