### ISSUE TITLE
Create a collaboration cycle for work with FE engineers on product teams

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#1643]
## Description
The VSP-Platform team has a mature collaboration cycle and [tracker](https://docs.google.com/spreadsheets/d/1d219oL1zCvCvnv1Bx-dI-GMzwgbarLv9_bzMSa3ULjA/edit?pli=1#gid=1341642809) that they use for teams to manage touchpoints with Platform and other teams. We had some initial discussions in February on how the CMS team might integrate with that but pivoted towards an embedded Drupal engineer model. That model is being revisited and the need for fleshed out collaboration protocol with our team has resurfaced.

## Acceptance Criteria
- [ ] How teams ought to interact with our team is documented and available in GitHub (expectations on regular meetings, epic/story identification, backlog grooming, prioritization, escalation process)
- [ ] An orientation framework is documented and available in GitHub
- [ ] These processes have been approved by DEPO and socialized at Team of Teams
