### ISSUE TITLE
FE meta tags for VBA facility for SEO

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16437]
## User Story or Problem Statement

As a Google, I want to display meta description when people search for a VBA facility.

## Acceptance Criteria
- [ ] `<meta name="description">` shows on the front-end of a VBA facility
- [ ] `<meta name="og:description">` shows on the front-end of a VBA facility

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by omahane** [comment]
Closing as this is a dupe of #16254
