### ISSUE TITLE
VBA Regional Offices: VA.gov production launch plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16445]
Launch plan for VBA RO Pilot MVP editor launch (precedes national rollout, which won't be until later quarters)

# VA Services taxonomy
- [x] Assessed & itemized if any Services terms are outstanding for VBA / CAIA final review, from #15748#issuecomment-1850961454
- [x] VAMC Service location changes are launched

## Launch Order of operations
- [x] VA Services taxonomy updated: Terms are saved as Published and then become available in the **Service name** drop-down on [VBA Facility Service](https://prod.cms.va.gov/node/add/vba_facility_service)

# FE launch

## Prerequisites / blockers
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16268 is complete
  - [x] Staging Review MUST feedback is resolved
- [x] Security Review is complete
- ~~[ ] #17966~~ (Moved to National Rollout Epic)
- ~~[ ] #16349~~ (Moved to National Rollout Epic)
- [x] Assessed for blocker status
  - [x] #17686
  - [x] #17925
  - ~~[ ] #17852~~ (Moved to National Rollout Epic)
  - [x] #14531
  - [x] #16906
  - [x] #18219
  - [x] Any remaining open tickets in #10514 : should either be launch blocking, or moved to #17782 
- [x] VBA change management 
   - [x] Comms are prepared - to who, saying what? (@mmiddaugh / @Agile6MSkinner )
   - [x] [VBA RO KBs](https://prod.cms.va.gov/help/veterans-benefits-administration-vba) are reviewed for any additional KBs needed (@Agile6MSkinner @laflannery @mmiddaugh based on recent editor trainings
   - [x] New KB article drafts are created & published
   - [x] VBA leadership has reviewed and determined which ROs are approved for publish
       - [x] list is provided so Sitewide can publish --OR--
       - [x] VBA is on deck to publish on launch day
   - [x] CMS Helpdesk has been notified of upcoming launch timing
- [x] Complete the [analytics request process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html)
  - [x] Draft started here: https://github.com/department-of-veterans-affairs/va.gov-team/issues/76780 
- [x] Complete the [Contact Center review process](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Contact-center-review.1782317061.html)

## Launch Order of operations
**For Approved list of Facilities ready to publish ONLY**
- [x] VBA Facility Health Services for those locations are PUBLISHED. ([full list of all VBA FHS](https://prod.cms.va.gov/admin/content?title=&type=vba_facility_service&moderation_state=All&owner=All))
- [x] VBA leadership-approved ROs are published (by either VBA leadership or Sitewide Drupal admin, tbd decisions above)
- [x] Content release runs / completes successfully 
- [x] Request is sent to LIghthouse in #cms-lighthouse, to redirect published Regional offices from the API ID facility locator detail page, to the published / modernized page. **This may take several days for LH to complete.**
- [x] VBA leadership are notified, with CMS Helpdesk in cc, of completed launch, including: link to live Regional Office page(s), [VBA KB landing page](https://prod.cms.va.gov/help/veterans-benefits-administration-vba), and estimated timing from LH for the CSV updates

## Follow up tasks
- [x] #17977
- [x] #18433

**Comment by davidmpickett** [comment]
I think title should be -> VBA: CMS **Pilot** Editor launch plan?

**Comment by jilladams** [comment]
Roll out plan: 
* When we are able to deliver CMS to Editors, Jane / Michelle will hold ~weekly trainings with these new editors to train them on conceptual pieces of the CMS. They will gradually begin content entry. 
* The FE will roll out when FE code is ready for Staging Review, we will do that and then ship the FE. 
* National roll out to all Editors will be later / separate: #16446 
  * After Pilot rollout
  * After Editor research
  * Probable iteration to improve before we roll out to all Editors

**Comment by jilladams** [comment]
This is drafted. Open action items are to follow up re: FE tasks remaining that block launch (Jane has scheduled a meeting next week for this), and to review this plan with the team. 

Right now I've written the FE launch to state we'll ship behind a feature toggle. However: we've asked Plat Governance if we could use Tugboat for our Staging Review: https://dsva.slack.com/archives/CBU0KDSB1/p1699289451944039.  If they say yes, we can revise the launch plan to account for that. (CC @mmiddaugh )

**Comment by davidmpickett** [comment]
@mmiddaugh @jilladams - I will take a pass at getting this ticket updated to our current state/understanding of launch steps and blockers for VBA

**Comment by omahane** [comment]
This has been published:
https://www.va.gov/portland-va-regional-benefit-office

**Comment by omahane** [comment]
@jilladams @Agile6MSkinner Update: the CSV with the URL change has been deployed: https://dsva.slack.com/archives/C02BTJTDFTN/p1721421342650609

**Comment by jilladams** [comment]
Verified: 
* Go to [FL search for Benefits in OR](https://www.va.gov/find-locations/?page=1&address=97206&facilityType=benefits&serviceType&latitude=45.464262&longitude=-122.579052&radius=10&bounds%5B%5D=-123.97905200000001&bounds%5B%5D=44.064262&bounds%5B%5D=-121.179052&bounds%5B%5D=46.864262&context=Portland%2C%20Oregon%2097206%2C%20United%20States)
* Scroll down to Portland VA Regional Benefits Office
* Click title
* Land on https://www.va.gov/portland-va-regional-benefit-office/

WOO

**Comment by jilladams** [comment]
Noting outstanding items to call this closed: 
* Contact Center process
* Analytics process
* 508 request (also has its own ticket, #18433 )

**Comment by jilladams** [comment]
Pinged analytics folks about whether the analytics ticket (https://github.com/department-of-veterans-affairs/va.gov-team/issues/76780) is ok or needs work: https://dsva.slack.com/archives/C1Q4294JJ/p1723140748378569

**Comment by Agile6MSkinner** [comment]
Just checked off the last item and I'm closing this. VBA RO page modernization in launched.
