### ISSUE TITLE
Audit view of service location data 

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#16451]
## User Story or Problem Statement

As a developer, I need a view to be able to verify that service location data has been successfully migrated over from VAMC Facility services.

## Acceptance Criteria
- [ ] Each row is an individual service location
- [ ] The columns in the view include the following
  - From Parent **VAMC Facility Health Service** 
     - [ ] Title (e.g. Polytrauma and traumatic brain injury - Bakersfield VA Clinic)
     - [ ] Appointment introduction text list selection
     - [ ] Appointment introduction text (when "Customize text" is selected)
     - [ ] Are walkins accepted?
     - [ ] Is online scheduling available for this service?
     - [ ] Phone number for appointments
  - From **Service Location**
    - [ ] Office visits
    - [ ] Virtual support
    - [ ] Appointment introduction text list selection
    - [ ] Appointment introduction text (when "Customize text" is selected)
    - [ ] Phone number for appointments
- [ ] Ticket is created to remove soon to be dead fields

## Implementation steps
[Need fields migrating from]

**Comment by xiongjaneg** [comment]
@davidmpickett Update more fields

**Comment by davidmpickett** [comment]
Adding my face since there's work I need to do to refine this before it's ready to pick up

**Comment by davidmpickett** [comment]
@omahane I updated the ACs to reflect the fact that the View should include both the deprecated fields from the parent VAMC Facility Health Service and the new fields you're adding to Service Location in #16348.

I grouped them by entity source for clarity here, but in the actual view it might make sense to put the old field and corresponding new field side by side for auditing purposes. Let me know if you want to chat

**Comment by omahane** [comment]
@swirtSJW Which do you prefer:

1. Fields from VAMC Facility health service which we are mapping to Service location
2. Fields from Service location which we're mapping to
3. The rest of the Service location fields

I am building this to capture both 1 and 2, but do you also want 3?

**Comment by swirtSJW** [comment]
@omahane For migration needs, I don't think 3 is needed.  However for useful longevity, 3 would probably be more helpful to the team long term.

We are going to need to alter the View in order to remove the fields that are going away, so it might make sense to just add the number 3 related fields at the same time we remove the old fields.

**Comment by omahane** [comment]
> add the number 3 related fields at the same time we remove the old fields

Yes, that makes sense, so I'll do 1 & 2 for this ticket.

**Comment by jilladams** [comment]
PR merged to integration branch: complete pending integration.

**Comment by jilladams** [comment]
Integration branch: https://github.com/department-of-veterans-affairs/va.gov-cms/tree/integration-service-location
