### ISSUE TITLE
[Epic][AP] Front-end work for launch

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16497]
## Requirements & Goals
 
Collecting any front-end work that does not align neatly with an existing epic. 

## Work

```[tasklist]
### Issues or tasks to be turned into issues
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17583
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17779
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18492
```

## Supporting material

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16432
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17551
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16379
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16499
```
