### ISSUE TITLE
[Epic][AP] Application logging, monitoring, and metrics collecting

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16490]
## Goals, requirements, and work
 
The Next Build application should have a centralized and clear of collecting logs and metrics and sending those to VA.gov's chosen logging and metrics analysis tools. 

```[tasklist]
### Acceptance criteria
- [ ] Next Build is set up to send logging information to common logging file locations rather than STDOUT
- [ ] Next Build Prod & Staging server logs are forwarded to log collection
- [ ] Preview server health is monitored and alerts are set up
- [ ] Next Build content deployment is monitored and alerts are set up
```

```[tasklist]
### Work to be done
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16954
```

```[tasklist]
### Completed work
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16491
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16956
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16955
```
