### ISSUE TITLE
IL Vets-api: update for new date format and data cutover to automated csvs

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16512]
## Description

**This is a RUBY ticket.** Other discipline labels are added temporarily so we don't lose this during discipline filtering in refinements.

Follow up from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16217. 

Goal: Complete Income Limits automation of data import by leveraging the new CSVs generated by the Income Limits Data Sync GHA.

## Engineering Notes
We have VES data exporting and writing to S3, via [a GHA](https://github.com/department-of-veterans-affairs/vets-api/blob/master/.github/workflows/income-limits-data-sync.yml) (Github Action).  The action is creating the following CSVs:

```
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_county_temp.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_gmtthresholds_temp.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_incomethreshold_temp.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_state_temp.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_zipcode_temp.csv
```

In the Income Limits API, the following CSVs are being used (note the lack of "_temp" in the filenames being the only difference) as of today. These files are manually uploaded and formatted, but we want to cutover to use the ones generated by the GHA.
```
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_county.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_gmtthresholds.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_incomethreshold.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_state.csv
https://sitewide-public-websites-income-limits-data.s3.us-gov-west-1.amazonaws.com/std_zipcode.csv
```

The new CSVs (with _temp) in the filename have a slight variation to the date format . The new date format (seen in 'created' fields for example) is `YYYY-MM-DD HH:MM:SS z` (where z is the timezone offset), eg:  2004-06-23 09:43:48 +0000. Formerly, the format was `M/DD/YYYY H:MM:SS.N p`, eg 6/23/2004 9:43:48.000000 AM. See [strftime](https://apidock.com/ruby/Time/strftime) for an explanation of the format tokens.

In the [Sidekiq import scripts](https://github.com/department-of-veterans-affairs/vets-api/tree/master/app/sidekiq/income_limits), the 'created' and 'updated' fields are `DateTime` objects and are expecting the data to have the _former_ date format. These scripts will need to be updated to accommodate the new format.

From IncomeLimits::StdZipCodeImport.perform:
```ruby
created = DateTime.strptime(row['CREATED'], '%m/%d/%Y %l:%M:%S.%N %p').to_s
updated = DateTime.strptime(row['UPDATED'], '%m/%d/%Y %l:%M:%S.%N %p').to_s if row['UPDATED']
```

## Tasks

- Setup local vets-api, if not already done
- Run the Sidekiq import scripts to populate your local postgres with content from the "old" CSVs
- Update Sidekiq import scripts to handle the new date formats
- Change Sidekiq import scripts to point to the new CSVs (with _temp) in the filename
- Re-run the Sidekiq import scripts, ensuring that they succeed on your local system
- Confirm row counts match from new CSVs and postgres tables
- If row counts match, proceed. If not, we may need to consider truncating the tables and re-importing from scratch. This would need to be delicately handled to avoid API downtime.
- Update the GHA to no longer use _temp in the filenames
- Update the GHA to set the ACL to "public read", eg `aws s3 sync ${{ env.TEMP_FOLDER }} s3://${{ env.BUCKET_NAME }} --acl public-read` (the last step of the Action. See [this Slack post](https://dsva.slack.com/archives/C52CL1PKQ/p1703023956176079?thread_ts=1703023031.148489&cid=C52CL1PKQ).
- Make a copy of the old CSVs and store them in S3 (for fallback/historical purposes)

## ACs
- [x] Automated import scripts import successfully with new format.
- [ ] A release plan that includes cutting over to use the new github action
- [x] Create ticket to update Income Limits documentation

**Comment by dsasser** [comment]
@FranECross do we want to include updating documentation in this ticket? It seems like a good time to do so since we will be fully automated once this goes in, and current documentation would be out of sync with the new automation process.

**Comment by FranECross** [comment]
@dsasser Yes, that's an excellent idea and catch! I'll update the AC, and appreciate you thinking of it.

**Comment by dsasser** [comment]
## Release Plan

To cutover to full data automation:

1. Merge this PR request.
2. Wait for the next vets-api deploy.
3. Run the GHA
4. Wait for the next auto import (March 1, 2024), OR
5. Ask Platform to run the Sidekiq import scripts on staging
6. Decide if we want to run the scripts on production, or wait for the next auto import in March.

**Comment by dsasser** [comment]
I created a new ticket for updating documentation [here](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17260).

**Comment by jilladams** [comment]
Launch plan now lives in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17250. Closing!
