### ISSUE TITLE
Transition Events product to IIR team

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16563]
# BLOCKED: On IIR verification that they're ready to transition Events.
1/25/24: Dave Conlon confirmed that if IIR confirms they're ready to take over Events, handoff can proceed.

## Background

Dave Conlon has a vision of transferring the Events product to the IIR team. This Epic tracks administrative work required to complete that move. 

## Tasks

- [ ] Make contact with new owners to confirm who will own the below tasks
- [ ] Update codeowner lines for Events to IIR team
  - [ ] [va.gov-cms](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/CODEOWNERS#L66)
  - [ ] [content-build](https://github.com/department-of-veterans-affairs/content-build/blob/main/.github/CODEOWNERS#L64)
  - [ ] [vets-websites](https://github.com/department-of-veterans-affairs/vets-website/blob/main/.github/CODEOWNERS#L117)
- [ ] Remove Public Websites label from [Events tickets](https://github.com/department-of-veterans-affairs/va.gov-cms/labels/Events) _that do not affect other PW products_ , and add IIR team label.    
  - Some tickets with the Events label have a bigger scope for Public Websites work, e.g. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16864. In this case, a ticket like that shouldn't transition to IIR. Instead: IIR should have their own backlog ticket to track the Events-specific work.
- [ ] Transition issues from va.gov-cms repo to IIR repo?  
  - Epics will lose their issue associations. Maybe better to have IIR update their workspace to show the va.gov-cms repo issues with their team label.
- [ ] Update Atlas / [Plat Product directory](https://depo-platform-documentation.scrollhelp.site/getting-started/vfs-product-directory-user-guide) with new ownership
- [ ] Update Events [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/outreach-events/product-outline.md) with new team contact info
- [ ] Schedule & hold meeting with IIR engineers, for technical handoff / context setting on Events risk space, technical quirks, stakeholders, and other questions / topics of note for POs.

**Comment by FranECross** [comment]
Decision was made not to transition to IIR team. Closing as no op
