### ISSUE TITLE
CMS Sprint Plan 101 (1.3.24 - 1.16.24)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#16596]
# Sprint 101 Capacity
All Eng: 32.1 pts
All UX: 9.1 pts
All Support: 0.7 pts
All CMS Team: 42 pts

# Sprint 101 Goals & Priorities
## SPRINT 101 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [x] Goal 1: Alt Text #16583 
- [x] Goal 2: Knowledge Base Enhancements #16292 

## SPRINT 101 PRIORITIES - not yet finalized
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:_

### D10 Runbook Deliverable (Epic #12238)
- [ ] Product and Delivery - start runbook edits in S101, finish final draft hopefully by S102

### Siteimprove (Epic #10201)
- None at this time for CMS Team (waiting VHA DM to take action)

#### Datadog Monitoring Expansion (CY2023 Q4 Goal) - (Epic #11928)
- NONE ZILCH

#### Alt Text Validation (CY2023 Q4 Goal) (Epic #15785) 
- [x] (2) #16583

#### Knowledge Base Enhancements (Epic #14069)
- [x] (3) #16292

#### Collab Cycle (#14013) / CMS Governance (#14012)
- Ask Blake (returns 1/4) if any collab/gov tickets to bring in)

#### CMS DesignOps (Epic #12843)
- [x] #16637 (Blake to refine / size)
- [ ] (5) #15655

#### Improvements to Content Release (Epic #14016)
- None at this time

#### ATO Documentation (CY2023 Q4 Goal) 
- Product / Tech Lead: Collab sesh w/ Paul Walker's team - CMS waiting to discuss the PTA (more info refer to #16427)

#### Dependencies / Dependabot PRs
- [ ] (average 4 pts taken on per Dev) - Dependabot PRs = 1 point each. Total points completed will vary by sprint. Berni to update actual numbers at end of sprint.

#### Help Team, Partners, Clients and Stakeholders Hit Objectives
Product / Delivery
- [ ] (1) Create new KB article or update existing article : Outreach Hub: How to archive Outreach Materials #15050 - low - Berni assigned self to ticket in S99, will carry over to S101
- [ ] #16170 (Berni to review/edit for Facilities)

DevOps
- [x]  (5) CMS Infrastructure ticket for Eric #16770

Drupal
- [ ] #16452 (Edmund to pre-refine)
- [x] #16591 (In progress, Edmund to size)
- [x] #16542 (In progress, Edmund to size)
- [x] (5) #16457 (In progress in S100)

#### General
- [ ] (0) Onboarding Marcia Ortiz #15974 - MARCIA VERIFY

## SPRINT 101 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. It's hard to predict what will actually come in, but we're averaging about 20-30 points of unplanned yet necessary Dev work each sprint. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed

### DevOps
- [ ] (8) #15646
- [x] (5) #16136

### Drupal
- [ ] (8) #15615
- [ ] (5) #14851
- [ ] (3) #16449

**Comment by BerniXiongA6** [comment]
CMS team closed Sprint 101 at 117% of actual vs. capacity plan (49 closed points vs. 42 capacity points -- which includes manual calculation of dependabot PRs).
