### ISSUE TITLE
component: node--landing_page (Benefits Hub Landing Page), Related Benefits

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16607]
## Description
Build out a component for 'Benefits Hub Links',  node--landing_page component. This is not a layout, but rather a component.

```[tasklist]
### Tasks
- [ ] All child tasks are complete
- [ ] Drupal type definition
- [ ] Next/component type definition
- [ ] Component QueryFormatter created
- [ ] Component & tests created
- [ ] Component in storybook
```

### CMS Info
**Paragraph/Node**: `node--landing_page`
**CMS structure**: [`types/landing_page/fields`](https://prod.cms.va.gov/admin/structure/types/manage/landing_page/fields)
**JSON:API query**:  [`jsonapi/node/landing_page`](https://prod.cms.va.gov/jsonapi/node/landing_page)

### Content Build info
**Existing template(s)**:[`benefit-hubs-links.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/includes/benefit-hubs-links.drupal.liquid)
**Existing/example existing GraphQL**:[fragment in several node types](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js#L52-L67)
**Logic notes**:
n/a

### Next Build info
**Example next-drupal query**:

```javascript
  const params = queries
    .getParams()
    .addPageLimit(10)
    .addInclude([

    ])

  const data = await drupalClient.getResourceCollection('node--landing_page', {
    params: params.getQueryObject(),
    withAuth: {
      clientId: process.env.DRUPAL_CLIENT_ID,
      clientSecret: process.env.DRUPAL_CLIENT_SECRET,
    }
  })
```
Required properties off the entity are simple strings.
