### ISSUE TITLE
component: paragraph--link_teaser_with_image (Link teaser with image)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16605]
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16626
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "paragraph--link_teaser_with_image",
    "id": "06af0fa3-bf08-4dad-bd1a-fb050737635d",
    "drupal_internal__id": 43281,
    "drupal_internal__revision_id": 309147,
    "langcode": "en",
    "status": true,
    "created": "2021-05-26T16:08:29+00:00",
    "parent_id": "19951",
    "parent_type": "node",
    "parent_field_name": "field_clp_stories_teasers",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [],
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "content_translation_changed": null,
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/paragraph/link_teaser_with_image/06af0fa3-bf08-4dad-bd1a-fb050737635d?resourceVersion=id%3A309147"
      }
    },
    "paragraph_type": {
      "type": "paragraphs_type--paragraphs_type",
      "id": "3b2c944c-742e-462a-b163-9aa0568de0c9",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "link_teaser_with_image"
      }
    },
    "field_link_teaser": {
      "type": "paragraph--link_teaser",
      "id": "036037a6-9376-403f-a666-5975392902c9",
      "resourceIdObjMeta": {
        "target_revision_id": 309146,
        "drupal_internal__target_id": 43280
      }
    },
    "field_media": {
      "type": "media--image",
      "id": "45f26cac-1d3a-4259-b395-9508057b7034",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 4047
      }
    },
    "relationshipNames": [
      "paragraph_type",
      "field_link_teaser",
      "field_media"
    ]
  }
```

## Acceptance Criteria

- [ ] Link teaser with image created
