### ISSUE TITLE
Prep for Federal Header Footer Phase 2 research

### ISSUE THREAD

**Issue by cindymerrill** [department-of-veterans-affairs/va.gov-cms#16614]
### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up Federal Header Footer Phase 2 research
**SO THAT** the research will happen successfully

### Tasks for Sprint 102 -- 13 points
**Finalize research deliverables**
- [x] Update research plan and conversation guide with any timeline or protocol tweaks
- [x] Upload research plan and convo guide to EnjoyHQ

**Coordinate with Research-Ops and Perigean**
- [x] Create recruiting request and submit to VA Research-Ops. Use *Easy Recruitment Request* (for moderated research) on [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
- [x] Create *New Research Intake* request from [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - [x] In description, add links to github research folder and (from previous step) recruiting request form
  - [x] Make yourself the assignee
  - [x] Add labels for the project's product, research methodology, audience, etc. from [this list](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)
- [x] Make agenda for kickoff meeting w/Perigean
- [x] Review Perigean's recruitment survey before kickoff meeting
- [x] Attend kickoff meeting with Perigean and Sitewide UX Lead and/or PM
- [x] Test Zoom login from Perigean 
- [x] Change display name of Perigean Zoom account to "*<Moderator's first name>* (Moderator)" 

**Notetaking prep**
- [x] Make note-taking spreadsheet
- [x] Create a new Mural board for research debrief sessions

**Pilot** 
- [x] Schedule pilot -- with a CAIA Accessibility Specialist
- [x] Slack your Perigean lead with the date, time, and participant for your pilot
- [x] Schedule team debrief sessions after pilot 
- [x] Schedule prep time before and debrief time after pilot 
- [x] Confirm the day before with pilot participant
- [x] Run pilot
- [x] Debrief pilot with team
- [x] Make any revisions needed to conversation guide and prototype
- [x] Send thank you slack message to pilot participant

**Recruitment / scheduling sessions** 
- [x] Review recruited participant list from Perigean for requirements met
- [x] Follow-up with Perigean re participant list, if needed
- [x] Make sure all research sessions scheduled by Perigean are in your calendar
- [x] Make signup sheet for observers, and share with team, stakeholders to sign up ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/observer_schedule_template.xlsx))
- [x] Make github version of signup sheet so OFCIO and USWDS folks can see the current schedule and open slots
- [x] Reserve one of the observer slots for an accessibility specialist
- [x] Get accessibility specialists signed up for each session
- [x] Share accessibility tech info for each participant with the accessibility specialists who will be supporting sessions
- [x] Invite signed up observers (+ Sara Smith from CAIA) to each session and optional debrief session, per signup sheet
- [x] Make notetaking doc in github for each session to share with Perigean right before each session starts (or all at once ahead of time if Perigean contact is OK with this)
- [x] Schedule 30-minute team debrief sessions once a day, and invite all observers signed up to observe in the previous 24 hours
- [x] Schedule prep and debrief time for each session
- [x] Slack/email all observers with instructions

## Acceptance Criteria
- [x] The target number(s) of participants has been recruited and scheduled (for overall & primary criteria)
- [x] The moderator(s), notetaker(s), and observer(s) have been invited to research sessions and daily debriefs
- [x] Pilot session has been conducted
- [x] All preparation done before the first day of research sessions

### Tasks for Sprint 103 -- 2 points
- [x] Handle 11th participant: observers, a11y specialist
- [x] Add participant numbers, dates, and times into recruitment intake ticket Participant Tracker (to check off later after each session)

**Comment by cindymerrill** [comment]
Launched participant recruiting today!

**Comment by cindymerrill** [comment]
Today Amanda and I reviewed Perigean's recruitment survey and provided feedback during a kickoff call with Perigean. All set now for recruitment to begin!

**Comment by cindymerrill** [comment]
Also got pilot test dates and participants confirmed by CAIA, so passed these along to Perigean to create calendar invites for.

**Comment by cindymerrill** [comment]
Observer invite planning, created github table to match Sharepoint spreadsheet. Created Mural board and spreadsheet for notetaking, confirmed both pilot participants and found out that they'll both be on desktop (not mobile).

**Comment by cindymerrill** [comment]
Conducted second pilot today--this time with a screen magnifier. Got good feedback, and we decided to find a better quality color image of the VA seal because the original one didn't magnify well. Now all pilots are done.

**Comment by cindymerrill** [comment]
Still waiting for Perigean to recruit the 11th participant, which will continue while research sessions get started. If Perigean succeeds in recruiting one more participant, then I'll need to repeat some of the above tasks for that new session.

**Comment by cindymerrill** [comment]
Perigean just scheduled the 11th participant, but I don't have all the details on that person yet, nor do I have any observers or accessibility specialist for that session. I also need to add all the sessions to the recruitment intake ticket Participant Tracker. I should be able to finish these tasks in the next couple days...
FYI @jilladams

**Comment by jilladams** [comment]
Thanks Cindy - updated ACs to reflect the sprint 103 work remaining, and guessed at a 3, but feel free to update that if it's off

**Comment by cindymerrill** [comment]
@jilladams I reduced the estimate to 2 points.

**Comment by cindymerrill** [comment]
Finished last prep tasks! Should hear from Perigean tomorrow to confirm new 11th participant.

**Comment by cindymerrill** [comment]
FYI @jilladams
