### ISSUE TITLE
layout: node--press_release (News Release)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16625]
## Description
We need a layout to render Press Release content. Examples:
https://www.va.gov/detroit-health-care/news-releases/attend-the-usa-wheelchair-football-league-veterans-all-star-game-2024/
https://www.va.gov/saginaw-health-care/news-releases/pact-act-expanded-veteran-town-hall-claims-clinic-and-toxic-exposure-screenings-event/

## Acceptance Criteria
- [x] Press release page content renders correctly
- [x] The layout output is consistent with the existing output of content-build (visually and functionally)

```[tasklist]
### Tasks
- [x] type definitions - Drupal node type, Next Build page type
- [x] query definition - query drupal data, map to next bulid type
- [x] tests for query/formatter
- [x] layout component
```

## Supporting detail
**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/press_release/fields

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/press_release.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/pressReleasePage.graphql.js

**API query for individual node:** https://prod.cms.va.gov/jsonapi/node/press_release/9736d655-5987-4d78-abf9-9e5fadde15ae?include=field_listing,field_pdf_version,field_press_release_contact,field_press_release_downloads

**Includes:**
```
    [
    'field_listing',
    'field_pdf_version',
    'field_press_release_contact',
    'field_press_release_downloads',
    ]
```

<details><summary>Example normalized data</summary>

```
 {
    "type": "node--press_release",
    "id": "6153ed5b-85c2-4ead-9893-3d656ad5d758",
    "drupal_internal__nid": 18141,
    "drupal_internal__vid": 398575,
    "langcode": "en",
    "revision_timestamp": "2021-04-12T14:27:39+00:00",
    "status": false,
    "title": "Wilmington VAMC 2019 Annual Report",
    "created": "2021-04-12T14:25:27+00:00",
    "changed": "2021-04-12T14:27:39+00:00",
    "promote": false,
    "sticky": false,
    "default_langcode": true,
    "revision_translation_affected": true,
    "breadcrumbs": [
      {
        "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/",
        "title": "Home",
        "options": []
      },
      {
        "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/wilmington-health-care",
        "title": "VA Wilmington health care",
        "options": []
      },
      {
        "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/wilmington-health-care/news-releases",
        "title": "News releases",
        "options": []
      },
      {
        "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/wilmington-health-care/news-releases/wilmington-vamc-2019-annual-report",
        "title": "Wilmington VAMC 2019 Annual Report",
        "options": []
      }
    ],
    "moderation_state": "draft",
    "metatag": [
      {
        "tag": "meta",
        "attributes": {
          "name": "title",
          "content": "Wilmington VAMC 2019 Annual Report | VA Wilmington health care | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "description",
          "content": "We invite you to come and read our 2019 Annual Report."
        }
      },
      {
        "tag": "link",
        "attributes": {
          "rel": "image_src",
          "href": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:site_name",
          "content": "Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:title",
          "content": "Wilmington VAMC 2019 Annual Report | VA Wilmington health care | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:description",
          "content": "We invite you to come and read our 2019 Annual Report."
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:image",
          "content": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "property": "og:image:alt",
          "content": "U.S. Department of Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:card",
          "content": "summary_large_image"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:description",
          "content": "We invite you to come and read our 2019 Annual Report."
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:site",
          "content": "@DeptVetAffairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:title",
          "content": "Wilmington VAMC 2019 Annual Report | VA Wilmington health care | Veterans Affairs"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:image",
          "content": "https://www.va.gov/img/design/logo/va-og-image.png"
        }
      },
      {
        "tag": "meta",
        "attributes": {
          "name": "twitter:image:alt",
          "content": "U.S. Department of Veterans Affairs"
        }
      }
    ],
    "path": {
      "alias": "/wilmington-health-care/news-releases/wilmington-vamc-2019-annual-report",
      "pid": 22184,
      "langcode": "en"
    },
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "field_address": {
      "langcode": null,
      "country_code": "US",
      "administrative_area": "DE",
      "locality": "Wilmington"
    },
    "field_intro_text": "We invite you to come and read our 2019 Annual Report. ",
    "field_last_saved_by_an_editor": null,
    "field_meta_tags": null,
    "field_press_release_fulltext": {
      "value": "<p>We invite you to come and read our 2019 Annual Report.<em> </em></p>\r\n",
      "format": "rich_text",
      "processed": "<p>We invite you to come and read our 2019 Annual Report. </p>"
    },
    "field_release_date": "2020-06-19T10:25:28-04:00",
    "links": {
      "self": {
        "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/node/press_release/6153ed5b-85c2-4ead-9893-3d656ad5d758?resourceVersion=id%3A398575"
      }
    },
    "node_type": {
      "type": "node_type--node_type",
      "id": "46fab8b2-83ee-448c-86e5-09151964e5c0",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "press_release"
      }
    },
    "revision_uid": {
      "type": "user--user",
      "id": "412272ee-6e47-4d26-9e46-b424d1d390d8",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 1486
      }
    },
    "uid": {
      "type": "user--user",
      "id": "412272ee-6e47-4d26-9e46-b424d1d390d8",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 1486
      }
    },
    "field_press_release_contact": [],
    "field_press_release_downloads": [],
    "field_administration": {
      "type": "taxonomy_term--administration",
      "id": "f55a34b8-f0cc-41f1-a6a3-8375160003ab",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 188
      }
    },
    "field_listing": {
      "type": "node--press_releases_listing",
      "id": "e3227296-c490-424c-abe7-42d80d0364cc",
      "drupal_internal__nid": 3047,
      "drupal_internal__vid": 859557,
      "langcode": "en",
      "revision_timestamp": "2024-04-02T13:36:41+00:00",
      "status": true,
      "title": "News releases",
      "created": "2020-03-02T21:29:22+00:00",
      "changed": "2024-04-02T13:36:41+00:00",
      "promote": false,
      "sticky": false,
      "default_langcode": true,
      "revision_translation_affected": true,
      "breadcrumbs": [
        {
          "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/",
          "title": "Home",
          "options": []
        },
        {
          "uri": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/wilmington-health-care",
          "title": "VA Wilmington health care",
          "options": []
        },
        {
          "uri": "internal:#",
          "title": "News and events",
          "options": []
        },
        {
          "uri": "internal:#",
          "title": "News releases",
          "options": []
        }
      ],
      "moderation_state": "published",
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "News releases | VA Wilmington health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "description",
            "content": "Get the latest news from Wilmington-area medical centers and clinics. For further information, contact our Public Affairs Office at 302-994-2511, ext. 5389."
          }
        },
        {
          "tag": "link",
          "attributes": {
            "rel": "image_src",
            "href": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:site_name",
            "content": "Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:title",
            "content": "News releases | VA Wilmington health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:description",
            "content": "Get the latest news from Wilmington-area medical centers and clinics. For further information, contact our Public Affairs Office at 302-994-2511, ext. 5389."
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:description",
            "content": "Get the latest news from Wilmington-area medical centers and clinics. For further information, contact our Public Affairs Office at 302-994-2511, ext. 5389."
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:site",
            "content": "@DeptVetAffairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:title",
            "content": "News releases | VA Wilmington health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        }
      ],
      "path": {
        "alias": "/wilmington-health-care/news-releases",
        "pid": 3891,
        "langcode": "en"
      },
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "field_description": "Get the latest news from Wilmington-area medical centers and clinics. For further information, contact our Public Affairs Office at 302-994-2511, ext. 5389.",
      "field_enforce_unique_combo": false,
      "field_intro_text": "For more information about Wilmington health care, contact our Public Affairs Office at 302-994-2511, ext. 5389. You can also visit us online, like us on Facebook, or follow us on Twitter. ",
      "field_last_saved_by_an_editor": "2024-04-02T13:36:47+00:00",
      "field_meta_tags": null,
      "field_press_release_blurb": {
        "value": "<p>For more information about Wilmington health care, contact our Public Affairs Office at <a href=\"tel:+13029942511\" aria-label=\"3 0 2. 9 9 4. 2 5 1 1.\">302-994-2511</a>, ext. 5389.</p><p>You can also visit us <a href=\"/node/2362\" data-entity-type=\"node\" data-entity-uuid=\"56fc04f4-46c8-4e20-8c4a-09aba2229894\" data-entity-substitution=\"canonical\">online</a>, like us on<a href=\"/admin/content/linky/1582\"> Facebook</a>, or follow us on <a href=\"/admin/content/linky/1583\">Twitter</a>.&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>",
        "format": "rich_text",
        "processed": "<p>For more information about Wilmington health care, contact our Public Affairs Office at <a href=\"tel:+13029942511\" aria-label=\"3 0 2. 9 9 4. 2 5 1 1.\">302-994-2511</a>, ext. 5389.</p><p>You can also visit us <a href=\"/wilmington-health-care\" data-entity-type=\"node\" data-entity-uuid=\"56fc04f4-46c8-4e20-8c4a-09aba2229894\" data-entity-substitution=\"canonical\" title=\"VA Wilmington health care\">online</a>, like us on<a href=\"https://www.facebook.com/WilmingtonVAMC\"> Facebook</a>, or follow us on <a href=\"https://twitter.com/WilmingtonVAMC\">Twitter</a>.&nbsp;</p><p>&nbsp;</p><p>&nbsp;</p>"
      },
      "links": {
        "self": {
          "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/node/press_releases_listing/e3227296-c490-424c-abe7-42d80d0364cc?resourceVersion=id%3A859557"
        }
      },
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 3047
      },
      "node_type": {
        "type": "node_type--node_type",
        "id": "4dd9e832-53d6-4587-a9f7-5040ac950e0a",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": "press_releases_listing"
        }
      },
      "revision_uid": {
        "type": "user--user",
        "id": "412272ee-6e47-4d26-9e46-b424d1d390d8",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 1486
        }
      },
      "uid": {
        "type": "user--user",
        "id": "8bea8773-6a06-4afd-99b5-1dfa7a2192ea",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 197
        }
      },
      "field_administration": {
        "type": "taxonomy_term--administration",
        "id": "f55a34b8-f0cc-41f1-a6a3-8375160003ab",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 188
        }
      },
      "field_office": {
        "type": "node--health_care_region_page",
        "id": "56fc04f4-46c8-4e20-8c4a-09aba2229894",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 2362
        }
      },
      "relationshipNames": [
        "node_type",
        "revision_uid",
        "uid",
        "field_administration",
        "field_office"
      ]
    },
    "field_pdf_version": {
      "type": "media--document",
      "id": "523bbd93-436a-4d36-83b4-810caa7bd7a3",
      "drupal_internal__mid": 3208,
      "drupal_internal__vid": 3410,
      "langcode": "en",
      "revision_created": "2021-04-12T14:27:34+00:00",
      "status": true,
      "name": "WilmingtonVAMC_Annual_Report_2019_web.pdf",
      "created": "2021-04-12T14:27:28+00:00",
      "changed": "2021-04-12T14:27:28+00:00",
      "default_langcode": true,
      "revision_translation_affected": true,
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "| Veterans Affairs"
          }
        }
      ],
      "path": {
        "alias": null,
        "pid": null,
        "langcode": "en"
      },
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "field_media_in_library": true,
      "field_media_submission_guideline": null,
      "links": {
        "self": {
          "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/media/document/523bbd93-436a-4d36-83b4-810caa7bd7a3?resourceVersion=id%3A3410"
        }
      },
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 3208
      },
      "bundle": {
        "type": "media_type--media_type",
        "id": "584b28c1-b73f-43c8-b1e9-02c86ac63d49",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": "document"
        }
      },
      "revision_user": null,
      "uid": {
        "type": "user--user",
        "id": "412272ee-6e47-4d26-9e46-b424d1d390d8",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 1486
        }
      },
      "thumbnail": {
        "type": "file--file",
        "id": "bd3b1fc6-cb65-4def-9c2e-21cca6aa48d1",
        "resourceIdObjMeta": {
          "alt": "",
          "title": null,
          "width": null,
          "height": null,
          "drupal_internal__target_id": 11
        }
      },
      "field_document": {
        "type": "file--file",
        "id": "649c7052-f0b4-4772-a047-5344dad2e6b5",
        "resourceIdObjMeta": {
          "display": true,
          "description": "",
          "drupal_internal__target_id": 3519
        }
      },
      "field_owner": {
        "type": "taxonomy_term--administration",
        "id": "c20f3989-e93e-49bd-8c95-ad3821042a02",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 5
        }
      },
      "relationshipNames": [
        "bundle",
        "revision_user",
        "uid",
        "thumbnail",
        "field_document",
        "field_owner"
      ]
    },
    "relationshipNames": [
      "node_type",
      "revision_uid",
      "uid",
      "field_press_release_contact",
      "field_press_release_downloads",
      "field_administration",
      "field_listing",
      "field_pdf_version"
    ]
  }
```

</details>

## Notes
There is at least one field in the Content Build template that is not actually in the data, and currently renders as empty: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/press_release.drupal.liquid#L83

There is a div apparently containing the characters `###`: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/press_release.drupal.liquid#L80

These should most likely be dropped.

**Comment by ttran-Therisa** [comment]
Currently need to have a successful build with Tugboat and SOCks connection, which I believed are linked. I am trying to understand rebuilding in tugboat for my branch and main. I am using previous DSVA threads as reference which I obtain the rebuilding ideaa

**Comment by ttran-Therisa** [comment]
Runs with SOCKs now. No changes made. Need to recheck Tugboat
