### ISSUE TITLE
layout: node--press_releases_listing (News Releases List)

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#16629]
## Description
We need a layout to render Press Release Listings.
Examples:
https://www.va.gov/milwaukee-health-care/news-releases/
https://www.va.gov/bronx-health-care/news-releases/

## Screenshot
<img width="249" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/13966636/b5dc19d4-aa06-4a3a-b562-cf11ad79f981">

## Acceptance Criteria
- [x] Press releases listings renders correctly
- [x] The layout output is consistent with the existing output of content-build (visually and functionally)

```[tasklist]
### Tasks
- [x] type definitions - Drupal node type, Next Build page type
- [x] query definition - query drupal data, map to next bulid type
- [x] tests for query/formatter
- [x] layout component
```

## Supporting detail
**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/press_releases_listing/fields

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/press_releases_listing.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/pressReleasesListingPage.graphql.js

**API query for individual node:** 
https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307?include=field_administration,field_office

**Includes:**
```
    [
    'field_administration',
    'field_office',
    ]
```

<details><summary>Example normalized data</summary>

```
{
  "jsonapi": {
    "version": "1.0",
    "meta": {
      "links": {
        "self": {
          "href": "http://jsonapi.org/format/1.0/"
        }
      }
    }
  },
  "data": {
    "type": "node--press_releases_listing",
    "id": "1c5ef865-2d04-4167-ac3c-46cfc7063307",
    "links": {
      "self": {
        "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307?resourceVersion=id%3A697188"
      }
    },
    "attributes": {
      "drupal_internal__nid": 15159,
      "drupal_internal__vid": 697188,
      "langcode": "en",
      "revision_timestamp": "2022-10-13T00:39:33+00:00",
      "status": true,
      "title": "News and Press Releases",
      "created": "2020-10-06T05:44:25+00:00",
      "changed": "2022-10-13T00:39:33+00:00",
      "promote": false,
      "sticky": false,
      "default_langcode": true,
      "revision_translation_affected": true,
      "breadcrumbs": [
        {
          "uri": "https://prod.cms.va.gov/",
          "title": "Home",
          "options": []
        },
        {
          "uri": "https://prod.cms.va.gov/durham-health-care",
          "title": "VA Durham health care",
          "options": []
        },
        {
          "uri": "internal:#",
          "title": "NEWS AND EVENTS",
          "options": []
        },
        {
          "uri": "internal:#",
          "title": "News releases",
          "options": []
        }
      ],
      "moderation_state": "published",
      "expiration_date": null,
      "warning_date": null,
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "News and Press Releases | VA Durham health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "description",
            "content": "Durham VA Health Care System news and press releases; information for the Veterans, their families, and caregivers"
          }
        },
        {
          "tag": "link",
          "attributes": {
            "rel": "image_src",
            "href": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:site_name",
            "content": "Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:title",
            "content": "News and Press Releases | VA Durham health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:description",
            "content": "Durham VA Health Care System news and press releases; information for the Veterans, their families, and caregivers"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "property": "og:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:card",
            "content": "summary_large_image"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:description",
            "content": "Durham VA Health Care System news and press releases; information for the Veterans, their families, and caregivers"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:site",
            "content": "@DeptVetAffairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:title",
            "content": "News and Press Releases | VA Durham health care | Veterans Affairs"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image",
            "content": "https://www.va.gov/img/design/logo/va-og-image.png"
          }
        },
        {
          "tag": "meta",
          "attributes": {
            "name": "twitter:image:alt",
            "content": "U.S. Department of Veterans Affairs"
          }
        }
      ],
      "path": {
        "alias": "/durham-health-care/news-releases",
        "pid": 17465,
        "langcode": "en"
      },
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "field_description": "Durham VA Health Care System news and press releases; information for the Veterans, their families, and caregivers",
      "field_enforce_unique_combo": false,
      "field_intro_text": "News and Press Releases for the Durham VA Health Care System ",
      "field_last_saved_by_an_editor": "2021-09-01T18:47:23+00:00",
      "field_meta_tags": null,
      "field_press_release_blurb": null
    },
    "relationships": {
      "node_type": {
        "data": {
          "type": "node_type--node_type",
          "id": "4dd9e832-53d6-4587-a9f7-5040ac950e0a",
          "meta": {
            "drupal_internal__target_id": "press_releases_listing"
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/node_type?resourceVersion=id%3A697188"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/relationships/node_type?resourceVersion=id%3A697188"
          }
        }
      },
      "revision_uid": {
        "data": {
          "type": "user--user",
          "id": "c564bd69-e8da-4ac3-905c-dd94f4bf7b35",
          "meta": {
            "drupal_internal__target_id": 1317
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/revision_uid?resourceVersion=id%3A697188"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/relationships/revision_uid?resourceVersion=id%3A697188"
          }
        }
      },
      "uid": {
        "data": {
          "type": "user--user",
          "id": "42b77c61-aabd-4182-8a0e-2d19f0267eff",
          "meta": {
            "drupal_internal__target_id": 1270
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/uid?resourceVersion=id%3A697188"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/relationships/uid?resourceVersion=id%3A697188"
          }
        }
      },
      "field_administration": {
        "data": {
          "type": "taxonomy_term--administration",
          "id": "ddfadf16-7428-4c17-abaa-53bb96492dd7",
          "meta": {
            "drupal_internal__target_id": 218
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/field_administration?resourceVersion=id%3A697188"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/relationships/field_administration?resourceVersion=id%3A697188"
          }
        }
      },
      "field_office": {
        "data": {
          "type": "node--health_care_region_page",
          "id": "d86e1929-2284-47ce-8da8-a4e02610d7c8",
          "meta": {
            "drupal_internal__target_id": 6928
          }
        },
        "links": {
          "related": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/field_office?resourceVersion=id%3A697188"
          },
          "self": {
            "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307/relationships/field_office?resourceVersion=id%3A697188"
          }
        }
      }
    }
  },
  "included": [
    {
      "type": "taxonomy_term--administration",
      "id": "ddfadf16-7428-4c17-abaa-53bb96492dd7",
      "links": {
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7?resourceVersion=id%3A1584"
        }
      },
      "attributes": {
        "drupal_internal__tid": 218,
        "drupal_internal__revision_id": 1584,
        "langcode": "en",
        "revision_created": "2023-04-03T19:41:40+00:00",
        "status": true,
        "name": "VA Durham health care",
        "description": null,
        "weight": 0,
        "changed": "2023-04-03T19:41:40+00:00",
        "default_langcode": true,
        "revision_translation_affected": true,
        "moderation_state": null,
        "metatag": [
          {
            "tag": "meta",
            "attributes": {
              "name": "title",
              "content": "VA Durham health care | VA.gov CMS"
            }
          },
          {
            "tag": "link",
            "attributes": {
              "rel": "canonical",
              "href": "https://prod.cms.va.gov/section/vha/vamc-facilities/va-durham-health-care"
            }
          }
        ],
        "path": {
          "alias": "/section/vha/vamc-facilities/va-durham-health-care",
          "pid": 7756,
          "langcode": "en"
        },
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "content_translation_created": null,
        "field_description": null
      },
      "relationships": {
        "vid": {
          "data": {
            "type": "taxonomy_vocabulary--taxonomy_vocabulary",
            "id": "645055c5-e567-4683-b6db-459ce04522ce",
            "meta": {
              "drupal_internal__target_id": "administration"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/vid?resourceVersion=id%3A1584"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/relationships/vid?resourceVersion=id%3A1584"
            }
          }
        },
        "revision_user": {
          "data": {
            "type": "user--user",
            "id": "20b2bc97-2210-4def-9a0f-46c22d250eb7",
            "meta": {
              "drupal_internal__target_id": 0
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/revision_user?resourceVersion=id%3A1584"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/relationships/revision_user?resourceVersion=id%3A1584"
            }
          }
        },
        "parent": {
          "data": [
            {
              "type": "taxonomy_term--administration",
              "id": "10d71348-6091-4a73-a3d7-4bf993414166",
              "meta": {
                "drupal_internal__target_id": 165
              }
            }
          ],
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/parent?resourceVersion=id%3A1584"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/relationships/parent?resourceVersion=id%3A1584"
            }
          }
        },
        "content_translation_uid": {
          "data": null,
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/content_translation_uid?resourceVersion=id%3A1584"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/relationships/content_translation_uid?resourceVersion=id%3A1584"
            }
          }
        },
        "field_product": {
          "data": {
            "type": "taxonomy_term--products",
            "id": "2fe1cb98-c03e-49fe-bb09-d73b66b99c8d",
            "meta": {
              "drupal_internal__target_id": 284
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/field_product?resourceVersion=id%3A1584"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/taxonomy_term/administration/ddfadf16-7428-4c17-abaa-53bb96492dd7/relationships/field_product?resourceVersion=id%3A1584"
            }
          }
        }
      }
    },
    {
      "type": "node--health_care_region_page",
      "id": "d86e1929-2284-47ce-8da8-a4e02610d7c8",
      "links": {
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8?resourceVersion=id%3A802280"
        }
      },
      "attributes": {
        "drupal_internal__nid": 6928,
        "drupal_internal__vid": 802280,
        "langcode": "en",
        "revision_timestamp": "2023-07-12T15:20:54+00:00",
        "status": true,
        "title": "VA Durham health care",
        "created": "2020-08-28T04:48:32+00:00",
        "changed": "2023-08-14T16:18:41+00:00",
        "promote": false,
        "sticky": false,
        "default_langcode": true,
        "revision_translation_affected": true,
        "breadcrumbs": [
          {
            "uri": "https://prod.cms.va.gov/",
            "title": "Home",
            "options": []
          },
          {
            "uri": "internal:#",
            "title": "VA Durham health care",
            "options": []
          }
        ],
        "moderation_state": "published",
        "expiration_date": null,
        "warning_date": null,
        "metatag": [
          {
            "tag": "meta",
            "attributes": {
              "name": "title",
              "content": "VA Durham health care | Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "description",
              "content": "At the Durham VA Health Care System, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates."
            }
          },
          {
            "tag": "link",
            "attributes": {
              "rel": "image_src",
              "href": "https://www.va.gov/img/design/logo/va-og-image.png"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:site_name",
              "content": "Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:title",
              "content": "VA Durham health care | Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:description",
              "content": "At the Durham VA Health Care System, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates."
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:image",
              "content": "https://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2021-04/DURHAM_%20Front_FB_DSC_0321_1.jpg"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "property": "og:image:alt",
              "content": "Durham VA"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:card",
              "content": "summary_large_image"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:description",
              "content": "At the Durham VA Health Care System, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates."
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:site",
              "content": "@DeptVetAffairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:title",
              "content": "VA Durham health care | Veterans Affairs"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:image",
              "content": "https://prod.cms.va.gov/sites/default/files/styles/3_2_medium_thumbnail/public/2021-04/DURHAM_%20Front_FB_DSC_0321_1.jpg"
            }
          },
          {
            "tag": "meta",
            "attributes": {
              "name": "twitter:image:alt",
              "content": "Durham VA"
            }
          }
        ],
        "path": {
          "alias": "/durham-health-care",
          "pid": 8244,
          "langcode": "en"
        },
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "field_appointments_online": false,
        "field_description": "At the Durham VA Health Care System, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you, and manage your health online. Sign up for community events and updates.",
        "field_facebook": {
          "uri": "https://www.facebook.com/VADurham",
          "title": "Durham VA Health Care System Facebook",
          "options": {
            "href": "https://www.facebook.com/VADurham",
            "data-entity-type": "",
            "data-entity-uuid": "",
            "data-entity-substitution": ""
          },
          "url": "https://www.facebook.com/VADurham"
        },
        "field_flickr": null,
        "field_govdelivery_id_emerg": "USVHA_404",
        "field_govdelivery_id_news": "USVHA_100",
        "field_instagram": {
          "uri": "https://www.instagram.com/vadurham/",
          "title": "Durham VA Health Care System Instagram",
          "options": {
            "href": "https://www.instagram.com/vadurham/",
            "data-entity-type": "",
            "data-entity-uuid": "",
            "data-entity-substitution": ""
          },
          "url": "https://www.instagram.com/vadurham/"
        },
        "field_intro_text": "At the Durham VA Health Care System, our health care teams are deeply experienced and guided by the needs of Veterans, their families, and caregivers. Find a health facility near you and manage your health online. Sign up for community events and updates.\r\n",
        "field_last_saved_by_an_editor": "2023-07-12T15:20:55+00:00",
        "field_meta_tags": null,
        "field_operating_status": {
          "uri": "entity:node/15817",
          "title": "Operating status - Durham VA Health Care System",
          "options": {
            "href": "entity:node/15817",
            "data-entity-type": "node",
            "data-entity-uuid": "1fab7755-6f59-4bb5-a4aa-931cf1d73cd3",
            "data-entity-substitution": "canonical"
          },
          "url": "/durham-health-care/operating-status"
        },
        "field_other_va_locations": [
          "vc_0328V",
          "558GI"
        ],
        "field_twitter": {
          "uri": "https://twitter.com/vadurham",
          "title": "Durham VA Health Care System Twitter",
          "options": {
            "href": "https://twitter.com/vadurham",
            "data-entity-type": "",
            "data-entity-uuid": "",
            "data-entity-substitution": ""
          },
          "url": "https://twitter.com/vadurham"
        },
        "field_vamc_ehr_system": "vista",
        "field_vamc_system_official_name": "Durham VA Health Care System",
        "field_va_health_connect_phone": null,
        "field_youtube": null
      },
      "relationships": {
        "node_type": {
          "data": {
            "type": "node_type--node_type",
            "id": "d611ade3-cc27-4359-8af1-6fba3384200f",
            "meta": {
              "drupal_internal__target_id": "health_care_region_page"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/node_type?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/node_type?resourceVersion=id%3A802280"
            }
          }
        },
        "revision_uid": {
          "data": {
            "type": "user--user",
            "id": "de1f741d-0292-4f3b-9999-aa707b3a5007",
            "meta": {
              "drupal_internal__target_id": 1921
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/revision_uid?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/revision_uid?resourceVersion=id%3A802280"
            }
          }
        },
        "uid": {
          "data": {
            "type": "user--user",
            "id": "42b77c61-aabd-4182-8a0e-2d19f0267eff",
            "meta": {
              "drupal_internal__target_id": 1270
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/uid?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/uid?resourceVersion=id%3A802280"
            }
          }
        },
        "field_administration": {
          "data": {
            "type": "taxonomy_term--administration",
            "id": "ddfadf16-7428-4c17-abaa-53bb96492dd7",
            "meta": {
              "drupal_internal__target_id": 218
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/field_administration?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/field_administration?resourceVersion=id%3A802280"
            }
          }
        },
        "field_clinical_health_services": {
          "data": [
            {
              "type": "node--regional_health_care_service_des",
              "id": "ea19c7d0-5ed3-4219-a817-dd565b63e351",
              "meta": {
                "drupal_internal__target_id": 10071
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "0163fd94-8d15-48b7-a781-1c06ae509a4b",
              "meta": {
                "drupal_internal__target_id": 10072
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "bbda6698-8e3f-4a3e-9576-9050671fbdf9",
              "meta": {
                "drupal_internal__target_id": 10073
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "4885c850-c85c-40cd-b17e-cf355d6f0a81",
              "meta": {
                "drupal_internal__target_id": 10074
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "1069b7a9-69dc-408a-96dd-b402d9df9e54",
              "meta": {
                "drupal_internal__target_id": 10075
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "fbc98267-d078-468b-a07f-ec91e044d122",
              "meta": {
                "drupal_internal__target_id": 10076
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "bdc05eb1-e991-480f-9b65-7705ba9b4cb9",
              "meta": {
                "drupal_internal__target_id": 10077
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "8c5c544e-9ce1-4951-a607-7f15d2384831",
              "meta": {
                "drupal_internal__target_id": 10078
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "d743b464-5dc7-42bd-9047-9eeba26a0e9c",
              "meta": {
                "drupal_internal__target_id": 10079
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "6b1d6114-4ce5-4f7f-baf8-f7e710f011dc",
              "meta": {
                "drupal_internal__target_id": 10080
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "5b2f4436-6993-4ce3-a74f-90717c490437",
              "meta": {
                "drupal_internal__target_id": 10081
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "a4bd2921-d7c6-4c95-a466-bf26642277b1",
              "meta": {
                "drupal_internal__target_id": 10082
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "8ec51145-d543-410e-8e9f-9393a6446b93",
              "meta": {
                "drupal_internal__target_id": 10083
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "955bbdda-fac6-41d5-9fdd-48111cbdbd8a",
              "meta": {
                "drupal_internal__target_id": 10084
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "bbc9f5e9-b2c2-4be7-8c62-f195970d73ca",
              "meta": {
                "drupal_internal__target_id": 10085
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "3fd47b2e-88c8-469d-b4b4-de427a952a29",
              "meta": {
                "drupal_internal__target_id": 10086
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "3d0365c7-0a46-4e8c-a10e-aec4ae492e05",
              "meta": {
                "drupal_internal__target_id": 10087
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "bd9afd3a-b2c4-4cdd-9e24-b29777044c7c",
              "meta": {
                "drupal_internal__target_id": 10088
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "20d40216-6e43-4af4-9f88-eb7c0c6179ce",
              "meta": {
                "drupal_internal__target_id": 10089
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "2d1c3067-b158-4b82-988f-4e0113c5412e",
              "meta": {
                "drupal_internal__target_id": 10090
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "41d4769b-9fde-4512-9013-12d22b2f5379",
              "meta": {
                "drupal_internal__target_id": 10091
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "abed9f38-b5fa-43c3-ac3a-f2115a2038c4",
              "meta": {
                "drupal_internal__target_id": 10092
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "069a4356-2391-44cd-b760-99a31e59c253",
              "meta": {
                "drupal_internal__target_id": 10093
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "fc3c0006-93e1-4da8-82e3-85917c0b1fb6",
              "meta": {
                "drupal_internal__target_id": 10094
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "0e3b7766-f134-4d1e-b83e-cca24cae007f",
              "meta": {
                "drupal_internal__target_id": 10095
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "a0240708-b075-4a3a-bb2f-140a78210a61",
              "meta": {
                "drupal_internal__target_id": 10096
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "7d628d83-0232-45a9-958d-a1a220b9ae6e",
              "meta": {
                "drupal_internal__target_id": 10097
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "5a1a9e93-2b49-485c-bc0e-fda8c13a50d8",
              "meta": {
                "drupal_internal__target_id": 10098
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "7d064d52-6fba-4322-880f-ae462d70d63d",
              "meta": {
                "drupal_internal__target_id": 15218
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "c41485a9-bbfa-4fff-b7a9-132ae6c1425c",
              "meta": {
                "drupal_internal__target_id": 32880
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "28e6dc65-0913-4f4e-9020-134f554e3f90",
              "meta": {
                "drupal_internal__target_id": 34842
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "1b8389dc-91a6-4479-8dbc-d80a824b7d9b",
              "meta": {
                "drupal_internal__target_id": 39971
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "8f206209-7120-4e9d-96a8-00981d171a25",
              "meta": {
                "drupal_internal__target_id": 60155
              }
            },
            {
              "type": "node--regional_health_care_service_des",
              "id": "3084f21d-a1fc-4852-87c7-434a2eaea679",
              "meta": {
                "drupal_internal__target_id": 60157
              }
            }
          ],
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/field_clinical_health_services?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/field_clinical_health_services?resourceVersion=id%3A802280"
            }
          }
        },
        "field_media": {
          "data": {
            "type": "media--image",
            "id": "254f998a-ecb4-471c-bd3a-6980f9817fa1",
            "meta": {
              "drupal_internal__target_id": 2777
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/field_media?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/field_media?resourceVersion=id%3A802280"
            }
          }
        },
        "field_related_links": {
          "data": {
            "type": "paragraph--list_of_link_teasers",
            "id": "1562ea8f-8bf8-4316-a93e-5d0460b2a139",
            "meta": {
              "target_revision_id": 1000459,
              "drupal_internal__target_id": 12858
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/field_related_links?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/field_related_links?resourceVersion=id%3A802280"
            }
          }
        },
        "field_system_menu": {
          "data": {
            "type": "menu--menu",
            "id": "1b4fa231-d59b-41de-aee0-72e0a7c3e0ae",
            "meta": {
              "drupal_internal__target_id": "va-durham-health-care"
            }
          },
          "links": {
            "related": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/field_system_menu?resourceVersion=id%3A802280"
            },
            "self": {
              "href": "https://prod.cms.va.gov/jsonapi/node/health_care_region_page/d86e1929-2284-47ce-8da8-a4e02610d7c8/relationships/field_system_menu?resourceVersion=id%3A802280"
            }
          }
        }
      }
    }
  ],
  "links": {
    "self": {
      "href": "https://prod.cms.va.gov/jsonapi/node/press_releases_listing/1c5ef865-2d04-4167-ac3c-46cfc7063307?include=field_administration%2Cfield_office"
    }
  }
}
```

</details>

**Comment by ttran-Therisa** [comment]
Generated files; working on the formatter and updating relevant files for the formatter to work

**Comment by ttran-Therisa** [comment]
Generated PressReleaseTeaser to be used in PressReleaseListing
