### ISSUE TITLE
[Discharge Wizard] Scope FE work to update the wizard to the subtask pattern

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#16656]
## Note
Randi & Chris will collaborate to break up/edit this story into manageable chunks of work.

## Description
The wizard pattern has been deprecated by DST in favor of the Subtask pattern. The Discharge Upgrade Wizard needs to be converted to a subtask pattern, e.g. one question per page. See link to design below.

There will be a subsequent story for text edits.

### User story

**AS A** As a Veteran, or caregiver of a Veteran
**I WANT** the Discharge Upgrade Wizard to be easily understood and navigable
**SO THAT** I can complete it accurately and improve my chances of my discharge upgrade request being approved.

### Design(s)
- Designs for this can be found in [this Sketch file](https://www.sketch.com/s/20ea8818-8846-4f47-b341-7dc0ee6fc57e).

## Acceptance criteria
- [ ] FE tickets have been created for migration of the existing Discharge Upgrade Wizard to follow the subtask pattern, and added to the #12043 epic
- [ ] Plans are mindful that the existing logic flow for questions/answers is not degraded/lost.
- [ ] Testing is considered and accounted for in ticketing

Final goal:
**GIVEN** I'm a Veteran or caregiver of a Veteran using the Discharge Upgrade Wizard
**WHEN** I proceed through the various screens of the wizard answering questions
**THEN** I see that there is one question per page

**Comment by FranECross** [comment]
@chriskim2311 Here is the 1st Discharge Upgrade Wizard story where it should be changed to the substack pattern. I'll create a second story to handle the text changes. cc @jilladams @randimays

**Comment by randimays** [comment]
@FranECross I did not pick up on this yesterday when we mentioned "changing to the subtask pattern" in planning.

Platform has a plug-and-play solution for subtask forms (example: applications for benefits where authentication is required). But when it comes to wizards (unauthed forms for determining actions to take), the subtask pattern is more conceptual and does not have a plug-and-play code implementation.

This means the conversion to subtask is not a single ticket; rather it's the epic. @chriskim2311 and I planned to break down the work required based on how the PACT Act wizard is constructed. That should lend itself to bite-sized chunks as we work to converting this over time.

**Comment by jilladams** [comment]
Thanks Randi. That in mind: maybe we make this ticket the FE work to carve out the tickets /plan the work into the epic?

**Comment by randimays** [comment]
@jilladams That makes sense to me

**Comment by jilladams** [comment]
updated ticket title / body (FYI @FranECross ) to reflect that change. We can tweak ACs as needed in refinement.

**Comment by FranECross** [comment]
@jilladams and @randimays Thanks so much for taking care of this! Apologies, Randi. I now remember you mentioning Chris and you would break it down. For some reason that was in one ear and out the other yesterday. 😁

**Comment by randimays** [comment]
No worries @FranECross! Simple misunderstanding. Thank you!

**Comment by FranECross** [comment]
@chriskim2311 Here's the story I mentioned in stand up this morning, where you and Randi will collaborate to create stories for the actual work off of this 'Scope' story. cc @randimays

**Comment by randimays** [comment]
@FranECross Should we pull this in when ready? Where does it fall in our current priorities?

**Comment by FranECross** [comment]
@randimays Thanks for checking! This falls just after PAW and Federal Header/Footer work. It's one of our Q1 initiatives, but third in that lineup. Thanks! cc @jilladams

**Comment by randimays** [comment]
@FranECross @jilladams: @chriskim2311 and I will be collaborating on this tomorrow morning. We pointed it at a 3

**Comment by FranECross** [comment]
I found this ticket in the backlog and wanted to reference it here in case you'd like to repurpose it. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14796

**Comment by chriskim2311** [comment]
@FranECross @jilladams 
I have created the tickets required for the FE work. Can you review them when you get a chance and we can close this ticket thanks!

**Comment by FranECross** [comment]
@chriskim2311 Thank you, and will do!

**Comment by randimays** [comment]
@FranECross Would you say this ticket is complete? I believe we got everything created and refined.

**Comment by FranECross** [comment]
@randimays Yes, thanks for the reminder! Closing now.
