### ISSUE TITLE
Code review & QA for Events transition to NextJS / Accelerated Publishing

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#16660]
~Blocked: on Accelerated Publishing devops work to standup servers for dev, staging, prod. Once complete (~ETA March 2024~), Events Next templates could ship to prod~
* **[2024-09-19]** AP expects to be ready for 2nd round QA week of 9/23
* **[2024-08-21]** AP team will have Events and Event listings builds ready for testing by August 28. 

## Tasks

- [ ] Clarify with AP what steps are required to ship
- [x] Ensure parity between content-build Events and Next Events at the time we're clear to ship
- [x] For code review: complete #16865 to understand the code setup

## ACs

- [x] Events AP build is verified for parity with production, including
  - [x] Recurring events presentation
  - [x] Events appearing on both Outreach Events calendar and VAMC calendar if checkbox is selected in Drupal
  - [x] Basic events metadata all presents / is correct 
    - [ ] ~On Event listing page~ [RM] Event Listings are moving to Sitewide post-release
    - [x] On Event detail page
  - [x] Conditionals are correct
  - [ ] ~Feedback is provided to AP team in pull request~ [RM] Code is being verified on dev.va.gov

ACs related to Event Listings have been moved to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19436

**Comment by jilladams** [comment]
Created this ticket to track the state of the conversation. Not clear yet if there is actual development work or any other work for Public Websites to do here. 

1/4/2024 meeting notes from Public Websites / AP sync, with @davidconlon @EWashb @tjheffner @timcosgrove @jtmst @randimays @chriskim2311 .

**Steps to go to prod for Next are on the Devops side.** 
* Next is in place on Tugboat
* Not in place on dev, staging, prod yet
* Devops needs to get servers stood up parallel to BRD deployment infrastructure
* Timeline is targeting March for production
* Contract transition for VFS-CMS introduces some potential points of failure. To be worked out along the way, as contract transitions.

**Can we code freeze Events, to prevent drift?** 
* Only work that is planned for Q1 is #15766 
* Yes, unless we find outages / major defects that need to be resolved, let's plan to put Events on ice.
* AP team has been added as codeowner to content-build Events files, so they'll be proactively notified of any work in these files. 

cc @FranECross

**Comment by jilladams** [comment]
@Agile6MSkinner to follow up with @mreed101  on AP team about expected timing for Events work to be ready for Sitewide final review.

**Comment by jilladams** [comment]
From AP team, this work should be ready to re-review next week: 
https://dsva.slack.com/archives/C07B86KV4P4/p1726761960245289?thread_ts=1726761861.279299&cid=C07B86KV4P4
> Right now we have pulled next-build out of dev as we are doing reverse proxy changes. It will be back online by next week and I will alert your team. I’d love for you to give us another pass of the changes

Week of 9/23 LauraF will be OOO, so we will need to work with AmandaK to close loop, and may need to pull in other folks to help test. I've asked JR to ping Fran + me + Amanda when the work is ready to test (since this is really on behalf of Events in Fran's portfolio, to ensure no prod breakage when they ship). 

This will probably become a sprint 13 injection, when it's ready to test, since they're trying to ship before their end of contract Oct 9. FYI @FranECross (and @Agile6MSkinner )

**Comment by jilladams** [comment]
Previous ticket for testing: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18493
QA spreadsheet that Laura & Amanda used for the first round: https://docs.google.com/spreadsheets/d/1Bt_vR8jOST2kzOiSoAvNgzcdyIsI1byhjwCsmyhhjyQ/edit?gid=675750633#gid=675750633

**Comment by jilladams** [comment]
This is unblocked and we need to inject in sprint 14: https://dsva.slack.com/archives/C07B86KV4P4/p1727972073479989

I've pulled it in, and Randi is already looking at the build, so I went ahead and assigned it. @randimays if you have concerns and are not prepared to take on the full scope, please wave a red flag and let's discuss with Fran.

**Comment by randimays** [comment]
@jilladams I think the events data is a bit different in dev vs. prod - verifying events parity with the filters might be a bit tricky.

**Comment by randimays** [comment]
A new spreadsheet was made (presumably by AP?) for QA items here: https://docs.google.com/spreadsheets/d/1czCFV4d4rQXcxoxVYoWtVyfSNGTDChhYchLLsxmp3OY/edit?gid=675750633#gid=675750633

**Comment by randimays** [comment]
@jilladams Are we ok to make some scope adjustments here? As I understand, AP is only shipping event detail pages (https://dsva.slack.com/archives/C07B86KV4P4/p1728318556408759?thread_ts=1728062069.765979&cid=C07B86KV4P4).

I haven't found any more issues than the ones that are reported in [the QA spreadsheet](https://docs.google.com/spreadsheets/d/1czCFV4d4rQXcxoxVYoWtVyfSNGTDChhYchLLsxmp3OY/edit?gid=675750633#gid=675750633); I think we might be good to call this "done" until AP makes fixes and we need to re-verify.

**Comment by jilladams** [comment]
That makes sense - I do think we need to track the Event Listing ACs, since we are taking over that work. So: 
1. Epic: #19435.  (The "events in progress not in upcoming" defect is also in this epic now)
2. QA ticket added to that epic, where the Event LIsting-related ACs now live: #19436

**Comment by randimays** [comment]
@jilladams @FranECross Not sure what should happen with this ticket re: sprint boundary. I understand Tim is still hard at work trying to get Events to prod; should we roll this to next sprint in anticipation of a final round of testing pre-deploy?

**Comment by jilladams** [comment]
Yes, per planning discussion: ok to keep it in sprint, and hoping that in cross-team sync today we'll figure out some of Tim's time to assist.

**Comment by randimays** [comment]
I reviewed [Tim's PR](https://github.com/department-of-veterans-affairs/next-build/pull/795) for the fix for events in progress and approved it. He will work on getting it merged and then we can do one last testing pass before shipping events & event listings to prod.

**Comment by randimays** [comment]
I re-tested events today and verified that all the issues marked as launch-blocking in [the spreadsheet](https://docs.google.com/spreadsheets/d/1czCFV4d4rQXcxoxVYoWtVyfSNGTDChhYchLLsxmp3OY/edit?gid=675750633#gid=675750633) have been addressed. I'm closing this as complete; I think we are ready to ship events to production.
