### ISSUE TITLE
Launch plan for VBA/VAMC Service Locations enhancements

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#16825]
## Description
Launch plan for VBA/VAMC service locations/appointments. This is new for VBA but changes VAMC current experience. 

Note this change is needed to roll out VBA, but the actual changes are for VAMC since they already have data in the older format.

## Prerequisites / blockers
- [x] #16451 complete pending integration
- [x] #15559 complete pending integration
- [x] #16348 complete pending integration
- [x] #16144 complete pending integration
- [x] #15959 complete pending integration
- [x] #17114 peer review
- [x] #17142 complete pending integration
- [x] #17241 
- [x] #17363 error can't be replicated
- [x] #16156 Existing KB articles are updated and reviewed by VHA DM, saved as draft
- [x] Synchronous team testing #17453 
- [x] Launch-blocking issues identified during testing
  - [x] #17511
  - [x] #17513
  - [x] #17516
  - [x] #17518
  - [x] #17605
  - [x] #17414
  - [x] #17600
  - [x] #17632
  - [x] #17843
  - [x] #17844
  - [x] #17956
  - [x]  #18069

## Big ol' chart of examples for testing / verification

[Service locations audit](https://pr15622-xptmfsnjoodldn85nzgkrgljqtfbz24b.ci.cms.va.gov/admin/content/audit/service-locations-detailed)

Page | Prod condition 
-- | -- 
VAMC Medical Records | [Basic](https://www.va.gov/northeast-ohio-health-care/medical-records-office/#get-your-records-in-person) |
VAMC Billing & Insurance |  [Basic](https://www.va.gov/northeast-ohio-health-care/billing-and-insurance/#pay-in-person) 
VAMC Register for Care | [Basic](https://www.va.gov/northeast-ohio-health-care/register-for-care/#patient-registration-admission)
VAMC Facility Health Service | [Basic](https://www.va.gov/northeast-ohio-health-care/locations/louis-stokes-cleveland-department-of-veterans-affairs-medical-center/#ophthalmology) 
VBA Facility Service  | NA 

Service Location Component | Previous condition | New condition | Drupal 
-- | -- | -- | --
Walk-ins -> Office Visits | [Walk-ins = No](https://www.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/#dentaloral-surgery) | ✅  Office Visits = Yes, by appointment only | ✅ [Prod](https://prod.cms.va.gov/pittsburgh-health-care/locations/h-john-heinz-iii-department-of-veterans-affairs-medical-center/dentaloral-surgery)
Walk-ins -> Office Visits | [Walk-ins = Yes](https://www.va.gov/new-york-harbor-health-care/locations/brooklyn-va-medical-center/#ophthalmology) | ✅  Office Visits = Yes, with or without an appointment | ✅ [Prod](https://prod.cms.va.gov/new-york-harbor-health-care/locations/brooklyn-va-medical-center/ophthalmology) 
Walk-ins -> Office Visits | [Walk-ins = Unspecified ](https://www.va.gov/greater-los-angeles-health-care/locations/santa-maria-va-clinic/#optometry) | ✅  Office Visits = NULL | ✅ [Prod](https://prod.cms.va.gov/greater-los-angeles-health-care/locations/santa-maria-va-clinic/optometry)
Walk-ins -> Office Visits | [Walk-ins = 2 ](https://www.va.gov/dublin-health-care/locations/perry-va-clinic/#cardiology) | ✅  Office Visits = NULL | ✅ [Prod](https://prod.cms.va.gov/maryland-health-care/locations/perry-point-va-medical-center/cardiology) 
Referral  | [Referral = No](https://www.va.gov/maine-health-care/locations/calais-va-clinic/#addiction-and-substance-use-care) | ✅  Referral = No | ✅ [Prod](https://prod.cms.va.gov/maine-health-care/locations/calais-va-clinic/addiction-and-substance-use-care)
Referral  | [Referral = Yes](https://www.va.gov/maine-health-care/locations/calais-va-clinic/#ptsd-care) | ✅  Referral = Yes | ✅ [Prod](https://prod.cms.va.gov/node/64620)
Referral  | [Referral = Unspecified](https://www.va.gov/maine-health-care/locations/calais-va-clinic/#laboratory-and-pathology) | ✅   Referral = Unspecified | ✅ [Prod](https://prod.cms.va.gov/maine-health-care/locations/calais-va-clinic/laboratory-and-pathology) 
Online Scheduling | [Online Scheduling = No](https://www.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/#mental-health-care) |  ✅ Online Scheduling = No | ✅ [Prod](https://prod.cms.va.gov/pittsburgh-health-care/locations/pittsburgh-va-medical-center-university-drive/mental-health-care)
Online Scheduling  | [Online Scheduling = Yes](https://www.va.gov/battle-creek-health-care/locations/battle-creek-va-medical-center/#physical-therapy-occupational-therapy-and-kinesiotherapy) |  ✅ Online Scheduling = Yes | ✅ [Prod](https://prod.cms.va.gov/battle-creek-health-care/locations/battle-creek-va-medical-center/physical-therapy-occupational-therapy-and-kinesiotherapy)
Online Scheduling  | [Online Scheduling = Unspecified](https://www.va.gov/tampa-health-care/locations/temple-terrace-va-clinic/#mental-health-care) |  ✅ Online Scheduling = NULL | ✅ [Prod](https://prod.cms.va.gov/tampa-health-care/locations/temple-terrace-va-clinic/mental-health-care)
Online Scheduling | [Online Scheduling = 2](https://www.va.gov/charleston-health-care/locations/beaufort-va-clinic/#physical-therapy-occupational-therapy-and-kinesiotherapy) |  ✅ Online Scheduling = NULL | ✅ [Prod](https://prod.cms.va.gov/charleston-health-care/locations/beaufort-va-clinic/physical-therapy-occupational-therapy-and-kinesiotherapy)
Appointment Intro Text | [Appointment Intro Text = Remove text](https://www.va.gov/butler-health-care/locations/butler-va-medical-center/#palliative-and-hospice-care) | ✅ Appointment Introduction Text = Remove text | ✅ [Prod](https://prod.cms.va.gov/butler-health-care/locations/butler-va-medical-center/palliative-and-hospice-care) 
Appointment Intro Text | [Appointment Intro Text = Use default text](https://www.va.gov/syracuse-health-care/locations/binghamton-va-clinic/#smoking-and-tobacco-cessation) | ✅ Appointment Introduction Text = Use default text | ✅  [Prod](https://prod.cms.va.gov/syracuse-health-care/locations/binghamton-va-clinic/smoking-and-tobacco-cessation)
Appointment Intro Text | [Appointment Intro Text = Customize text](https://www.va.gov/greater-los-angeles-health-care/locations/los-angeles-va-clinic/#pain-management) | ✅ Appointment Introduction Text = Customize text | ✅  [Prod](https://prod.cms.va.gov/greater-los-angeles-health-care/locations/los-angeles-va-clinic/pain-management) 
Appointment Intro Text | [Appointment Intro Text = NULL](https://www.va.gov/gulf-coast-health-care/locations/biloxi-va-medical-center/#critical-care) | ✅ Appointment Intro Text = Use default text | ✅ [Prod](https://prod.cms.va.gov/gulf-coast-health-care/locations/biloxi-va-medical-center/critical-care) 
Additional phone numbers for appointments | [0 phone numbers](https://www.va.gov/houston-health-care/locations/tomball-va-clinic/#patient-advocates) | ✅  0 phone numbers | ✅ [Prod](https://prod.cms.va.gov/houston-health-care/locations/tomball-va-clinic/patient-advocates) 
Additional phone numbers for appointments | [1 phone number](https://www.va.gov/north-texas-health-care/locations/dallas-va-medical-center/#homeless-veteran-care) | ✅  1 phone number | ✅ [Prod](https://prod.cms.va.gov/north-texas-health-care/locations/dallas-va-medical-center/homeless-veteran-care) 
Additional phone numbers for appointments | [2 phone numbers](https://www.va.gov/greater-los-angeles-health-care/locations/antelope-valley-va-clinic/#geriatrics) | ✅  2 phone numbers | ✅ [Prod](https://prod.cms.va.gov/greater-los-angeles-health-care/locations/antelope-valley-va-clinic/geriatrics)
Use the facility phone number (for Appointments) |  [Use the facility phone number = On](https://www.va.gov/houston-health-care/locations/tomball-va-clinic/#patient-advocates) |  ✅  Use the facility phone number = On | ✅ [Prod](https://prod.cms.va.gov/houston-health-care/locations/tomball-va-clinic/patient-advocates) 
Use the facility phone number (for Appointments) |   [Use the facility phone number = Off](https://www.va.gov/greater-los-angeles-health-care/locations/antelope-valley-va-clinic/#geriatrics) |  ✅  Use the facility phone number = Off | ✅  [Prod](https://prod.cms.va.gov/greater-los-angeles-health-care/locations/antelope-valley-va-clinic/geriatrics)
Multiple Service Locations | [1 service location](https://www.va.gov/coatesville-health-care/locations/coatesville-va-medical-center/#prosthetics-and-rehabilitation) | ✅ 1 service location | ✅ [Prod](https://prod.cms.va.gov/coatesville-health-care/locations/coatesville-va-medical-center/prosthetics-and-rehabilitation) 
Multiple Service Locations | [2 service locations](https://www.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic/#intimate-partner-violence-support) | ✅ 2 service locations | ✅ [Prod](https://prod.cms.va.gov/pittsburgh-health-care/locations/westmoreland-county-va-clinic/intimate-partner-violence-support) 
Multiple Service Locations | [3 service locations](https://www.va.gov/lovell-federal-health-care-va/locations/captain-james-a-lovell-federal-health-care-center/#addiction-and-substance-use-care) | ✅ 3 service locations | ✅ [Prod](https://prod.cms.va.gov/lovell-federal-health-care-va/locations/captain-james-a-lovell-federal-health-care-center/addiction-and-substance-use-care) 

### Pre-launch comms
- [x] VHA DM and VAMC editors are notified the changes are coming in the future
- [x] VHA DM is notified about imminent timing of changes to share with editors - @davidmpickett has copy prepped to send
- [x] CMS Team is notified to ensure they have capacity to support - 1 week advance notice required, min
- [x] CMS Helpdesk is notified of upcoming changes
- [x] Ask CMS Platform if they agree that we don’t need to have a in-system message to Editors during the maintenance window - @jilladams 

### Pre-launch code prep

- [x] content-build -  [Content-build Integration branch PR](https://github.com/department-of-veterans-affairs/content-build/pull/1912)
    - [x] Prep PR / set ready to review
    - [x] Code review complete
    - [x] What about this ticket? #18069
- [x] CMS -  [CMS integration branch PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15622) (this will alter the visible fields and perform the migration when deployed.) 
    - [x] Prep PR / set ready to review
    - [x] https://github.com/department-of-veterans-affairs/content-build/pull/2070 Must merge to main prior to SL int branch merge
    - [x] Code review complete

### Day one (May 13th) - Drupal Launch Day
- [x] CMS: Before CMS daily deploy cutoff  @ 10:30a CT: @omahane merges [CMS integration branch PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15622) (this will alter the visible fields and perform the migration when deployed.) 
- [x] PM: @laflannery or Jill or Michael notifies VHA DM when the code from above is deployed (so that VAMC editors will know to not edit services during that window)
- [x] CMS: CMS code deploys to prod (3:30 ET) - takes ~45mins if deploy succeeds
- [x] CMS: Spot check that everything looks as expected, before migration: New fields appear in Drupal, Service Audit view exists, etc. If so: cue CMS to run migration.
- [x] CMS: Devops (@7hunderbird)  runs migration script  - making note of start time `drush scr ./scripts/content/VACMS-15559-migrate-service-location-from-node-to-paragraph.php`
- [x] CMS: ~4 hours pass for migration to run
- [x] CMS: Devops (@7hunderbird) notifies @omahane when the script is complete - making note of end time
- [x] CMS: @davidmpickett publishes [updated KB articles](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16156)
- [x] CMS: @omahane and @davidmpickett examine the CMS service location audit is to see what services were edited during the migration window
   - [x] Any nodes edited during the window have their revisions examined to see if any data needs to be re-entered (it may have been overwritten by the migration.
   - [x] DUPLICATE PHONE NUMBER CHECK INFO GOES HERE
   - [x] Spot checking examples 
- [x] CMS: Confirm that no critical issues have occurred that would prevent FE launch. Notify @laflannery & @mmiddaugh that CMS deploy is successful, in light of Tues 3pm ET VBA training.

### Day two (May 14th) - FE Day
- [x] FE:  [Content-build Integration branch PR](https://github.com/department-of-veterans-affairs/content-build/pull/1912) - rerun CI tests. Takes hours.
- [x] FE: @eselkin merges the [Content-build Integration branch PR](https://github.com/department-of-veterans-affairs/content-build/pull/1912)
- [x] ~Out of band deploy?~ Will allow to daily deploy on 5/15
- [x] Drupal clean up work by @omahane 
  - [x] #18112
  - [x] [Service location buttons config change](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18119)

### Day three (May 15th) - FE Day part two (assuming no OOBD)
- [x] FE: Verify that commit passed CI in main. 
  - [x] If so: Code deploys at (12p ET)
    - [x] FE: ~1 -2 hours till next content release completes
    - [x] FE: @davidmpickett @maxx1128 @eselkin Verify FE on Prod
  - [x] If not: (make a call re: OOB deploy vs. pushing FE by a day)
    - [x] If we delay to Wed: let VHA DM and Helpdesk know that it'll be 1 day lag til CMS changes appear in the FE. 
- [x] PM: On successful deploy: @laflannery / Jill / Michael notify VHA DM when the FE changes are visible on Prod
- [x] PM: VBA Editor checklist is updated (This is for Laura to do) 

### Mitigation if snafus
* Old fields / data still exist, so we can roll back either FE or Drupal as needed. Would need a revert PR to roll forward a revert. 

## Follow up tasks - tracked in #17350
- FE confirms none of the fields being removed appear in the GraphQL query(s) for VAMC Facility Service.
-  CMS merges [PR to Remove the hidden fields](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17479) from audits
    - Remove the removed fields from the audit view.
- #17137 
- #17514

**Comment by xiongjaneg** [comment]
Target date of Feb. 26 and need ticket from Steve's integration branch

**Comment by gracekretschmer-metrostar** [comment]
@edmund-dunn

**Comment by jilladams** [comment]
From refinement: we'll swarm to test next week. @xiongjaneg  & Jill to collaborate this week on: 
* setting up a time for team to swarm
* a Slack channel for the swarm
* a punch list ticket ala #11026 to capture the details

**Comment by jilladams** [comment]
@davidmpickett note to selves: Michelle noted it would be wise to do a last big picture check that everything is working as expected when our tickets close / pre-launch. Might warrant a ticket (that I won't get cut today, but maybe tomorrow.)

**Comment by gracekretschmer-metrostar** [comment]
@7hunderbird Facilities team will likely need our support (you can see the CMS steps outlined above) next sprint and I'd like you to be that support for the CMS team. Jill is anticipating that this work will begin in the first week of May.

**Comment by jilladams** [comment]
@mmiddaugh FYI that DrupalCon is the week of 5/6 and Christian will be away. So we are planning to launch on week of 5/13. Coordinating with CMS on that.

**Comment by jilladams** [comment]
Noting: New SL ticket, we haven't worked out yet what must happen here re: launch or what our options are exactly so haven't added to this epic yet: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17967.

**Comment by davidmpickett** [comment]
@omahane One small thing I noticed in the interface. The "add another service location" button has different formatting on different content types

### VAMC Facility Non-clinical Service

![Screenshot 2024-05-13 at 5 27 11 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/49f359ee-baa3-4dfa-9cab-137fae8b5f59)

### VAMC Facility Health Service
![Screenshot 2024-05-13 at 3 26 49 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d87429c2-fa45-446e-9f8d-5f357acc8778)

### VBA Facility Service & Service Region

![Screenshot 2024-05-13 at 5 29 55 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/932866c3-9cc5-4f20-b49b-315af655f9d5)

I've done multiple refreshes so I don't think this is a local browser issue, but can you confirm?

**Comment by davidmpickett** [comment]
@omahane Superficial issue number 2:

The word Order is showing up in the Address accordion header bar
![Screenshot 2024-05-13 at 3 20 23 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/9db79001-a0c9-4637-a132-e87a8753a31b)

**Comment by omahane** [comment]
> @omahane One small thing I noticed in the interface. The "add another service location" button has different formatting on different content types
> 
It has to do with the Add mode in the widget.
## VAMC Facility Health vs Non-clinical Services
![Screenshot 2024-05-14 at 9 09 53 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/b249c645-75bf-4c3c-9617-ac995810bbf6)

## VBA
![Screenshot 2024-05-14 at 9 16 30 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/c8db6fe4-9d88-4d51-81f9-86f3a19a9781)

I can align these with a config change.

**Comment by omahane** [comment]
> @omahane Superficial issue number 2:
> 
> The word Order is showing up in the Address accordion header bar

[This issue](https://www.drupal.org/project/paragraphs/issues/3418303) has to do with a [Drupal core change](https://www.drupal.org/project/drupal/issues/1038316) that introduced a regression in the Paragraphs module. 

It doesn't look like the patch is ready for production yet, but I am looking at a CSS fix in the meantime.

**Comment by omahane** [comment]
@davidmpickett This PR should straighten out those buttons: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18119

**Comment by davidmpickett** [comment]
Launch is successful. I have moved any items that are fast follows to #17350

IMO final steps before this epic is closable:
- https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18119
  - Verify on prod later today
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18112
  - Verify cardinality change on prod later today
  - Communication to editors is sent (either as a CTA in lieu of us making updates or as a FYI after we make changes)

**Comment by davidmpickett** [comment]
@laflannery There's a check box on here for you to update the VBA Editor checklist. I don't think we need to block closing this epic on that task, but wanted to make sure you have either done that or are otherwise tracking that to do item.

**Comment by laflannery** [comment]
I just updated it, thanks!

**Comment by davidmpickett** [comment]
CLOSING THE EPIC 😭🥳

**Comment by jilladams** [comment]
SO EPIC. 🎉 🚀

**Comment by jilladams** [comment]
This ticket is still so horrifying and so beautiful. Good job us.
