### ISSUE TITLE
CMS Sprint Plan 102 (1.16.2024 - 1.30.2024)

### ISSUE THREAD

**Issue by BerniXiongA6** [department-of-veterans-affairs/va.gov-cms#16859]
# Sprint 102 Capacity
All Eng: 32.1 pts
All UX: 11.4 pts
All Support: 1.4 pts
All CMS Team: 44.9 pts

# Sprint 102 Goals & Priorities
## SPRINT 102 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [x] Goal 1: #16821 

## SPRINT 102 PRIORITIES 
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:_

### Documentation / Knowledge Transfer
Continue these tickets through the end of the contract
- [ ] #16650 
- [ ] #16872 
- [ ] #16649 
- [ ] #16874 
- [ ] #16648 
- [ ] #16875 
- [ ] #16646 
- [ ] #16876 
- [ ] #16644 
- [ ] #16877 
- [ ] #16643 
- [ ] #16878 
- [x] #16645 
- [ ] #16879 
- [x] #16870 
- [x] #16880 
- [x] #16647 
- [x] #16881 

### D10 Runbook Deliverable (Epic #12238)
- [ ] Product and Delivery - start runbook edits in S101, finish final draft hopefully by S102

### Siteimprove (Epic #10201)
- None at this time for CMS Team (waiting VHA DM to take action)

### Datadog Monitoring Expansion (CY2023 Q4 Goal) - (Epic #11928)
- None

### Alt Text Validation (CY2023 Q4 Goal) (Epic #15785) 
- None

### Knowledge Base Enhancements (Epic #14069)
- [x] (8) #16612

### Collab Cycle (#14013) / CMS Governance (#14012)
- None

### CMS DesignOps (Epic #12843)
- [x] #16637 (Erika to check with Amanda K. on this effort)

### Improvements to Content Release (Epic #14016)
- None

### ATO Documentation (CY2023 Q4 Goal) 
- [x] #16821 Product / Tech Lead: Paul Walker's team to submit form w/ help from CMS (more info refer to #16427)

### Dependencies / Dependabot PRs
- [ ] (average 4 pts taken on per Dev) - Dependabot PRs = 1 point each. Total points completed will vary by sprint. Berni to update actual numbers at end of sprint.

### Help Team, Partners, Clients and Stakeholders Hit Objectives
Product / Delivery
- [ ] (1) Create new KB article or update existing article : Outreach Hub: How to archive Outreach Materials #15050 - low - Berni assigned self to ticket in S99, will carry over to S102
- [x] #16170 (Berni to review/edit for Facilities)
- [x] #15692 (Berni to review updated edits from Facilities)

DevOps
- [x] (3) #16887
- [x] #16734 

Drupal
- [x] #16591 - Edmund, please point

## SPRINT 102 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. It's hard to predict what will actually come in, but we're averaging about 20-30 points of unplanned yet necessary Dev work each sprint. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed

### DevOps
- [ ] (8) #15646
- [x] (5) #16136

### Drupal
- [ ] (8) #15615
- [ ] (5) #14851 - Blocked by Facilities (not blocked by Engineering work)
- [x] (3) #16449

### Engineering Tickets that Need Refining
- n/a

**Comment by BerniXiongA6** [comment]
FYI @michelle-dooley

**Comment by BerniXiongA6** [comment]
Sprint 102 closed at 151% of actual to planned capacity (68points total completed by all team, which includes manually counted dependabot PRs).
