### ISSUE TITLE
Capture 87 config items to clean up config export

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17019]
## User Story or Problem Statement

As a developer, I would like to only have the config I have changed exported during a config export, instead of 87 configuration files unrelated to my changes.

## Acceptance Criteria
- [ ] Configuration exported after a configuration change only produces files related to the change.

## Implementation steps
- Run a config export from the `main` branch
- Capture the exported config to the code base

## Screenshot
![Screenshot 2024-01-24 at 3 11 59 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/28997e14-41e2-4fb4-89b9-4ad64df18b54)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

**Comment by gracekretschmer-metrostar** [comment]
@anantais what is your progress on this work?
