### ISSUE TITLE
CMS Sprint Plan 103 (1.31.2024 - 2.13.2024)

### ISSUE THREAD

**Issue by maortiz-27-80** [department-of-veterans-affairs/va.gov-cms#17104]
# Sprint 103 Capacity
All Eng: 28.6 pts
All UX: 11.4 pts
All Support: 1.6 pts
All CMS Team: 41.6 pts

# Sprint 103 Goals & Priorities
## SPRINT 103 GOALS
_By the end of this sprint, this is what we're committing to have accomplished and delivered:_
- [x] Goal 1: #17099 

## SPRINT 103 PRIORITIES 
_These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:_

### Documentation / Knowledge Transfer
Continue these tickets through the end of the contract
- [ ] #16650 
- [x] #16872 
- [x] #16649 
- [x] #16874 
- [x] #16648 
- [x] #16875 
- [x] #16646 
- [x] #16876 
- [x] #16644 
- [x] #16877 
- [x] #16643 
- [x] #16878 
- [x] #16645 
- [x] #16879 
- [x] #16870 
- [x] #16880 
- [x] #16647 
- [x] #16881 

### D10 Runbook Deliverable (Epic #12238)
- [ ] Product and Delivery - Berni is working on edits and proofing. Will work with Marcia to get it into markdown before end of Sprint 103.

### Siteimprove (Epic #10201)
- None at this time for CMS Team (waiting VHA DM to take action)

### Datadog Monitoring Expansion (CY2023 Q4 Goal) - (Epic #11928)
- None

### Alt Text Validation (CY2023 Q4 Goal) (Epic #15785) 
- None

### Knowledge Base Enhancements (Epic #14069)
- [x] (8) #17099 

### Collab Cycle (#14013) / CMS Governance (#14012)
- None

### CMS DesignOps (Epic #12843)
- None

### Improvements to Content Release (Epic #14016)
- None

### ATO Documentation (CY2023 Q4 Goal) 
- None

### Dependencies / Dependabot PRs
- [ ] (average 4 pts taken on per Dev) - Dependabot PRs = 1 point each. Total points completed will vary by sprint. Berni to update actual numbers at end of sprint.

### Help Team, Partners, Clients and Stakeholders Hit Objectives
Product / Delivery
- None

DevOps
- [x] (3) #17113

Drupal
- [ ] #17073  - Edmund discussed with Amanda on 01/31.  The new team will take on this work and the current team will not work on this in Sprint 103 (MO)
- [x] #17117 - Nate will work on this per PO/PM/DM discussion 01/31

## SPRINT 103 UNPLANNED WORK (Post Sprint Planning)
_These tickets have been added after Sprint Planning event. It's hard to predict what will actually come in, but we're averaging about 20-30 points of unplanned yet necessary Dev work each sprint. Please let your Delivery Manager know if you're needing to pull in a critical ticket that didn't make it to the Sprint Plan:_
- Defects and hurdles work can come in, as needed
- Keep the Lights On work can come in, as needed

### DevOps
- [ ] (8) #15646
- [x] (8) #16884 

### Drupal
- [ ] (8) #15615
- [ ] (5) #14851 - Blocked by Facilities (not blocked by Engineering work)

### Engineering Tickets that Need Refining
- n/a

**Comment by BerniXiongA6** [comment]
Closed Sprint 103 at 156% (65 pts) of team capacity plan.
