### ISSUE TITLE
Add text validation to appointment custom test in Service Location

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17124]
## User Story or Problem Statement

As an editor, I would like to have validation on the Custom text field of the Appointment information in the Service Location so that I can ensure that I have filled out that field before I save the page.

## Context
Prior to the Service Location being the source of truth for Appointment text type and custom text, the VAMC Facility Health Service had these fields and validated the presence of text in the Custom text field if "Custom text" was chosen for the Appointment text type. 

## Acceptance Criteria
- [ ] When saving a service of any of the 4 applicable content types, should the **Appointment introduction text** field be set to "Customize text" and **Custom text** textbox should show as required.
- [ ] Should the **Customize text** be selected and the **Custom text** be empty, the node should not save.
- [ ] Should Javascript be disabled, server-side validation should prevent the node from being saved.
- [ ] The above should be true for the following content types:
  - [ ] Service Region
  - [ ] VAMC Facility Health Service
  - [ ] VAMC Facility Non-Clinical Service
  - [ ] VBA Facility Service 

## Implementation steps
The likely area to add this code would be `va_gov_facilities_field_widget_single_element_paragraphs_form_alter` in `va_gov_facilities.module`.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [x] `Facilities`
- [ ] `User support`

**Comment by davidmpickett** [comment]
Unlikely that this will get pulled in to Sprint 2 given that this is hefty and there's a good chunk of higher priority tickets on the docket, but will leave it here until Sprint Planning next week for official call

**Comment by JonathanKatora** [comment]
@r-bartlett-gsa I think this work is better suited in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16905
