### ISSUE TITLE
Add Product documentation for React widgets owned by Sitewide

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17145]
## User Story or Problem Statement
As Sitewide product owner & team
we want to have accurate product documentation for React widgets used on VA.gov
for the sake of long-term ownership and maintenance. 

## Description or Additional Context 
During USWDS V3 component migration, we identified that over the years Public Websites & Facilities have created many React widgets that aren't listed in our product portfolio as products we own, and don't have top level product docs in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products. 

We need to get those documented, with 2 intentions: 
1. In case of contract transition, make sure existing product docs are comprehensive about what might need maintenance or iteration, in our portfolio
2. Make docs available in case products need to be retired or moved to other teams

## Question for FE Team members
We need a gut check from FE re: whether Jill's guesses in comments are spot-on, and if there are more widget sources to review, in order to determine what all Fran and Jill need to help get documented.

## Tasks
1. Audit https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/widgetTypes.js for widgets owned by PW
2. For any widgets owned but not documented, create docs

## Acceptance Criteria
- [ ] All Sitewide owned React widgets are documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products, as noted in the [Jan 2025 comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17145#issuecomment-2590885725)

**Comment by jilladams** [comment]
Full list from https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/widgetTypes.js.  Box checked for anything I'm pretty sure we own: 

- [ ]   DOWNLOAD_1095B_CTA: 'download-1095b',
- [ ]   ASK_VA: 'ask-va',
- [ ]   BANNER: 'banner',
- [ ]   BASIC_FACILITY_LOCATIONS_LIST: 'basic-facility-locations-list',
- [ ]   BURIALS_APP_STATUS: 'burials-app-status',
- [ ]   BURIAL_HOW_DO_I_APPLY_WIDGET: 'burial-how-do-i-apply-widget',
- [ ]   BTSSS_LOGIN: 'btsss-login',
- [ ]   CHAPTER_31_CTA: 'chapter-31-cta',
- [ ]   CHAPTER_31_WIZARD: 'chapter-31-Wizard',
- [ ]   CHAPTER_36_CTA: 'chapter-36-cta',
- [ ]   COE_ACCESS: 'coe_access',
- [ ]   COVID_VACCINE_UPDATES_CTA: 'va-covid-vaccine-updates-cta',
- [ ]   CTA: 'cta',
- [ ]   DEPENDENCY_VERIFICATION: 'dependency-verification',
- [ ]   DISABILITY_APP_STATUS: 'disability-app-status',
- [ ]   DISABILITY_RATING_CALCULATOR: 'disability-rating-calculator',
- [ ]   EDUCATION_APP_STATUS: 'education-app-status',
- [ ]   EVENTS: 'events',
- [ ]   EZR_SUBMISSION_OPTIONS: 'ezr-submission-options',
- [ ]   FACILITY_APPOINTMENT_WAIT_TIMES_WIDGET:
- [ ]     'facility-appointment-wait-times-widget',
- [ ]   FACILITY_DETAIL: 'facility-detail',
- [ ]   FACILITY_DETAIL_SATELLITE_LOCATIONS: 'facility-detail-satellite-locations',
- [ ]   FACILITY_LOCATIONS_LIST: 'facility-locations-list',
- [ ]   FACILITY_MAP: 'facility-map',
- [ ]   FACILITY_MAP_SATELLITE_MAIN_OFFICE: 'facility-map-satellite-main-office',
- [ ]   FACILITY_MAP_SATELLITE_LOCATIONS: 'facility-map-satellite-locations',
- [ ]   FACILITY_PATIENT_SATISFACTION_SCORES: 'facility-patient-satisfaction-scores',
- [ ]   FACILITY_PATIENT_SATISFACTION_SCORES_SATELLITE_LOCATIONS:
- [ ]     'facility-patient-satisfaction-scores-satellite-locations',
- [ ]   FIND_A_REP_LANDING_CONTENT: 'find-a-rep-landing-content',
- [ ]   FIND_VA_FORMS: 'find-va-forms',
- [ ]   FIND_VA_FORMS_INVALID_PDF_ALERT: 'find-va-forms-pdf-download-helper',
- [ ]   FORM_10182_CTA: 'form-10182-cta',
- [ ]   FORM_686_CTA: 'form-686-CTA',
- [ ]   FORM_2010206_CTA: 'form2010206',
- [ ]   FORM_210845_CTA: 'form210845',
- [ ]   FORM_210966_CTA: 'form210966',
- [ ]   FORM_210972_CTA: 'form210972',
- [ ]   FORM_2110210_CTA: 'form2110210',
- [ ]   FORM_214142_CTA: 'form214142',
- [ ]   FORM_21P0847_CTA: 'form21p-0847',
- [ ]   FORM_264555_CTA: 'form264555',
- [ ]   FORM_400247_CTA: 'form400247',
- [ ]   GET_MEDICAL_RECORDS_PAGE: 'get-medical-records-page',
- [ ]   HCA_PERFORMANCE_WARNING: 'hca-performance-warning',
- [ ]   HEALTH_CARE_APP_STATUS: 'health-care-app-status',
- [ ]   HIGHER_LEVEL_REVIEW_APP_STATUS: 'higher-level-review-status',
- [ ]   HOMEPAGE_BANNER: 'homepage-banner',
- [ ]   HOMEPAGE_HERO_RANDOMIZER: 'homepage-hero-randomizer',
- [ ]   HOMEPAGE_SEARCH: 'homepage-search',
- [ ]   I_18_SELECT: 'i18-select',
- [ ]   MAINTENANCE_BANNER: 'maintenance-banner',
- [ ]   MANAGE_VA_DEBT_CTA: 'manage-va-debt-cta',
- [ ]   MEDICAL_COPAYS_CTA: 'medical-copays-cta',
- [ ]   OPT_OUT_APP_STATUS: 'opt-out-app-status',
- [ ]   OTHER_FACILITY_LOCATIONS_LIST: 'other-facility-locations-list',
- [ ]   PENSION_APP_STATUS: 'pension-app-status',
- [ ]   PENSION_HOW_DO_I_APPLY_WIDGET: 'pension-how-do-i-apply-widget',
- [ ]   POST_911_GI_BILL_STATUS_WIDGET: 'post-9-11-gi-bill-status',
- [ ]   REFILL_TRACK_PRESCRIPTIONS_PAGE: 'refill-track-prescriptions-page',
- [ ]   RESOURCES_AND_SUPPORT_SEARCH: 'resources-and-support-search',
- [ ]   SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE: 'schedule-view-va-appointments-page',
- [ ]   SCO_ANNOUNCEMENTS: 'sco-announcements',
- [ ]   SCO_EVENTS: 'sco-events',
- [ ]   SECURE_MESSAGING_PAGE: 'secure-messaging-page',
- [ ]   SHIFTED_VETS_BANNER: 'shifted-vets-banner',
- [ ]   SIDE_NAV: 'side-nav',
- [ ]   SUPPLEMENTAL_CLAIM: 'supplemental_claim',
- [ ]   THIRD_PARTY_APP_DIRECTORY: 'third-party-app-directory',
- [ ]   VET_CENTER_HOURS: 'vet-center-hours',
- [ ]   VET_CENTER_HOURS_SATELLITE_LOCATIONS: 'vet-center-hours-satellite-locations',
- [ ]   VET_CENTER_NEARBY: 'vet-center-nearby',
- [ ]   VIEW_DEPENDENTS_CTA: 'view-dependents-CTA',
- [ ]   VIEW_PAYMENT_HISTORY: 'view-payment-history',
- [ ]   VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page',
- [ ]   VIEW_ENROLLMENT_VERIFICATION_LOGIN: 'view-enrollment-verification-login',
- [ ]   VIEW_EDUCATION_LETTERS_LOGIN: 'view-education-letters-login',

**Comment by jilladams** [comment]
Re: 
> There's another list here we may need to review? https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/cta-widget/ctaWidgets.js#L16

Took a pass at that here: https://dsva.slack.com/archives/C07BVDGCY8H/p1723481918242219?thread_ts=1723213627.592759&cid=C07BVDGCY8H.  That'll roll up into the bigger convo of CTA widget ownership.

**Comment by FranECross** [comment]
@jilladams Is this something that needs to be finished prior to us handing over ownership of the widgets to the team taking them on?

**Comment by jilladams** [comment]
I honestly am not sure. Thinking out loud: 

* **CTA Widget app ownership**: Sitewide owns the CTA Widget, globally, as an app. The app is documented: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/cta-widget 
* **Healthcare Apps CTA widgets:** There are 5 invocations of the CTA Widget that the Healthcare apps team will end up owning: 
  * HEALTH_RECORDS
  * LAB_AND_TEST_RESULTS
  * MESSAGING	
  * RX	
  * SCHEDULE_APPOINTMENT
* **How much is moving?**: We don't know yet if we are handing off ownership of the entire CTA Widget App to the Healthcare Apps team, or just those 5 invocations 
* **Other Sitewide CTA widgets:** Beyond those 5 listed above, Sitewide owns many other invocations of the CTA Widget, checked off in the list in [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17145#issuecomment-1928446684). We'll still own those, even if the global app transitions to new owners, and should confirm my guesses are right and document them at some point.

So I guess my conclusion is: this ticket stands, and is work we should do at some point, but isn't urgent or related to the handoff to the Healthcare Apps team.

**Comment by jilladams** [comment]
As of today: Identity owns the core cta-widget app, and the MHV cartography team are stakeholders in the content that appears in the widgets listed above as Healthcare Apps. So: those cases are now covered and not on our team to handle documentation around. 

Update list below, that in mind: 

Full list from https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/static-pages/widgetTypes.js.  Box checked for anything I'm pretty sure we own: 

- [ ]   DOWNLOAD_1095B_CTA: 'download-1095b',
- [ ]   ASK_VA: 'ask-va',
- [x]   BANNER: 'banner', (What is this one doing? Does it belong in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/full-width-alert? )
- [x]   BASIC_FACILITY_LOCATIONS_LIST: 'basic-facility-locations-list', docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-locator
- [ ]   BURIALS_APP_STATUS: 'burials-app-status',
- [ ]   BURIAL_HOW_DO_I_APPLY_WIDGET: 'burial-how-do-i-apply-widget',
- [x]   BTSSS_LOGIN: 'btsss-login', - document in https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/travel-reimbursement-btsss
- [ ]   CHAPTER_31_CTA: 'chapter-31-cta',
- [ ]   CHAPTER_31_WIZARD: 'chapter-31-Wizard',
- [ ]   CHAPTER_36_CTA: 'chapter-36-cta',
- [x]   COE_ACCESS: 'coe_access', -- https://github.com/department-of-veterans-affairs/va.gov-team/issues/28848
- [ ]   COVID_VACCINE_UPDATES_CTA: 'va-covid-vaccine-updates-cta',
- [ ]   CTA: 'cta', - if Healthcare apps ends up owning the entire CTA widget app, we won't need to document this
- [ ]   DEPENDENCY_VERIFICATION: 'dependency-verification',
- [ ]   DISABILITY_APP_STATUS: 'disability-app-status',
- [ ]   DISABILITY_RATING_CALCULATOR: 'disability-rating-calculator',
- [ ]   EDUCATION_APP_STATUS: 'education-app-status',
- [x]   EVENTS: 'events', -- doesn't need it's own docs, but should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/outreach-events
- [ ]   EZR_SUBMISSION_OPTIONS: 'ezr-submission-options',
- [x]   FACILITY_APPOINTMENT_WAIT_TIMES_WIDGET: 'facility-appointment-wait-times-widget', docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_DETAIL: 'facility-detail', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_DETAIL_SATELLITE_LOCATIONS: 'facility-detail-satellite-locations', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_LOCATIONS_LIST: 'facility-locations-list', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_MAP: 'facility-map', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages 
- [x]   FACILITY_MAP_SATELLITE_MAIN_OFFICE: 'facility-map-satellite-main-office', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_MAP_SATELLITE_LOCATIONS: 'facility-map-satellite-locations', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_PATIENT_SATISFACTION_SCORES: 'facility-patient-satisfaction-scores', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [x]   FACILITY_PATIENT_SATISFACTION_SCORES_SATELLITE_LOCATIONS: 'facility-patient-satisfaction-scores-satellite-locations', , docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/facility-pages
- [ ]   FIND_A_REP_LANDING_CONTENT: 'find-a-rep-landing-content',
- [x]   FIND_VA_FORMS: 'find-va-forms', -- doesn't need it's own docs, but should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form
- [x]   FIND_VA_FORMS_INVALID_PDF_ALERT: 'find-va-forms-pdf-download-helper', -- doesn't need it's own docs, but should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form
- [ ]   FORM_10182_CTA: 'form-10182-cta',
- [ ]   FORM_686_CTA: 'form-686-CTA',
- [ ]   FORM_2010206_CTA: 'form2010206',
- [ ]   FORM_210845_CTA: 'form210845',
- [ ]   FORM_210966_CTA: 'form210966',
- [ ]   FORM_210972_CTA: 'form210972',
- [ ]   FORM_2110210_CTA: 'form2110210',
- [ ]   FORM_214142_CTA: 'form214142',
- [ ]   FORM_21P0847_CTA: 'form21p-0847',
- [ ]   FORM_264555_CTA: 'form264555',
- [ ]   FORM_400247_CTA: 'form400247',
- [ ]   GET_MEDICAL_RECORDS_PAGE: 'get-medical-records-page',
- [ ]   HCA_PERFORMANCE_WARNING: 'hca-performance-warning',
- [ ]   HEALTH_CARE_APP_STATUS: 'health-care-app-status',
- [ ]   HEALTH RECORDS - Will transition to Healthcare apps team in Q1 2025.
- [ ]   HIGHER_LEVEL_REVIEW_APP_STATUS: 'higher-level-review-status',
- [x]   HOMEPAGE_BANNER: 'homepage-banner', -- doesn't need it's own docs, but should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/home-page
- [x]   HOMEPAGE_HERO_RANDOMIZER: 'homepage-hero-randomizer', -- same
- [x]   HOMEPAGE_SEARCH: 'homepage-search', -- doesn't need it's own docs, but should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/on-site-search
- [x]   I_18_SELECT: 'i18-select', -- should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/README.md
- [ ] LAB_AND_TEST_RESULTS  -- transitioned to Identity / Healthcare apps team in Q1 2025.
- [x] MAINTENANCE_BANNER: 'maintenance-banner', -- should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/full-width-alert
- [ ]   MANAGE_VA_DEBT_CTA: 'manage-va-debt-cta',
- [ ]   MEDICAL_COPAYS_CTA: 'medical-copays-cta',
- [x]  MESSAGING -- Will transition to Healthcare apps team in Q1 2025.
- [ ]   OPT_OUT_APP_STATUS: 'opt-out-app-status',
- [ ]   OTHER_FACILITY_LOCATIONS_LIST: 'other-facility-locations-list',
- [ ]   PENSION_APP_STATUS: 'pension-app-status',
- [ ]   PENSION_HOW_DO_I_APPLY_WIDGET: 'pension-how-do-i-apply-widget',
- [ ]   POST_911_GI_BILL_STATUS_WIDGET: 'post-9-11-gi-bill-status',
- [ ]   REFILL_TRACK_PRESCRIPTIONS_PAGE: -- transitioned to Identity / Healthcare apps team in Q1 2025.
- [x]   RESOURCES_AND_SUPPORT_SEARCH: 'resources-and-support-search',  -- should be documented within https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support
- [ ] RX: tx -- transitioned to Identity / Healthcare apps team in Q1 2025.
- [ ]   SCHEDULE_VIEW_VA_APPOINTMENTS_PAGE: 'schedule-view-va-appointments-page'-- transitioned to Identity / Healthcare apps team in Q1 2025.
- [ ]   SCO_ANNOUNCEMENTS: 'sco-announcements',
- [ ]   SCO_EVENTS: 'sco-events',
- [ ]   SECURE_MESSAGING_PAGE: 'secure-messaging-page'-- transitioned to Identity / Healthcare apps team in Q1 2025.
- [x]   SHIFTED_VETS_BANNER: 'shifted-vets-banner', -- this is old for the old version of the homepage. If it's no longer in use / we've replaced it with different veteran image shuffler, it could be archived: https://github.com/department-of-veterans-affairs/vets-website/pull/20621
- [ ]   SIDE_NAV: 'side-nav', -- is this ours? 😬 
- [ ]   SUPPLEMENTAL_CLAIM: 'supplemental_claim',
- [ ]   THIRD_PARTY_APP_DIRECTORY: 'third-party-app-directory',
- [x]   VET_CENTER_HOURS: 'vet-center-hours', docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers
- [x]   VET_CENTER_HOURS_SATELLITE_LOCATIONS: 'vet-center-hours-satellite-locations', docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers
- [x]   VET_CENTER_NEARBY: 'vet-center-nearby', docs go into https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers
- [ ]   VIEW_DEPENDENTS_CTA: 'view-dependents-CTA',
- [ ]   VIEW_PAYMENT_HISTORY: 'view-payment-history',
- [ ]   VIEW_TEST_AND_LAB_RESULTS_PAGE: 'view-test-and-lab-results-page',
- [ ]   VIEW_ENROLLMENT_VERIFICATION_LOGIN: 'view-enrollment-verification-login',
- [ ]   VIEW_EDUCATION_LETTERS_LOGIN: 'view-education-letters-login',

**Comment by mmiddaugh** [comment]
[Add the list of Sitewide owned widgets to product folder and will close this issue. ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/sitewide-widgets.md)
