### ISSUE TITLE
[Consider] Support custom Help Text on Link fields controlled by Linkit Module

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17201]
## User Story or Problem Statement

As a UXer designing editorial interfaces in the Drupal CMS, I need to customize help text so I can make it relevant to the user's context.

Right now if I try to provide custom link text on a Link field that is using the LinkIt widget it won't show up on the interface. The default help text from the LinkIt module is shown instead.

The Facilities Team discovered this while working on [#16327](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16327#issuecomment-1930670785). @omahane created an [upstream issue](https://www.drupal.org/project/linkit/issues/3420280) on the Drupal Module.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

**Comment by omahane** [comment]
@davidmpickett I created a [merge request on the upstream issue](https://www.drupal.org/project/linkit/issues/3420280#comment-15436315). I would like to get your feedback there, if possible.

**Comment by omahane** [comment]
If we decide we want this and use a patch, we'll need to check for any links that may be overridden currently, such as `field_url_of_an_online_event`, which is currently overridden in EntityEventSubscriber: `va_gov_events/src/EventSubscriber/EntityEventSubscriber.php`

**Comment by davidmpickett** [comment]
> @davidmpickett I created a [merge request on the upstream issue](https://www.drupal.org/project/linkit/issues/3420280#comment-15436315). I would like to get your feedback there, if possible.

Feedback added!
