### ISSUE TITLE
Platform CMS Sprint Plan 4 (2/19/2024 - 3/27/2024) 

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17244]
### 2024 Q1 Vision
Keep the lights on and build a foundation of excellence. 

### Sprint 4 Goals & Priorities

**SPRINT 4 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- No goals this sprint, but continue to prioritize onboarding and gaining access to the needed VA systems for your discipline.

### SPRINT 4 PRIORITIES
These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:

**Offboard Previous Team**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17312 

**Onboarding New Team**
Onboarding and gaining access to the needed VA systems.
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17013
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17010
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17011
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17009
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17014
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17016
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17015
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17012
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17218
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17219
- [ ] Grace and Michelle build sprint and communication structures.

**Prod Offline Incident Post Mortem (Epic [#17242](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17242))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17255
- [x] Grace will organize and facilitate a  post mortem meeting. 
- [ ] Grace will synthesize findings into a post mortem report in GitHub. 

**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [ ] Take Knowledge Base Study and translate into an implementation plan.
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136

**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] Discovery work in collaboration with Platform governance team to understand where CMS should plug into the existing collaboration cycle. 

**Dependencies / Dependabot PRs**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [ ] Blocked?

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [ ] Technical discovery work about PDF deletion bug in Drupal

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825
- [ ] [Run menu re-org script on prod and fix Lovell · Issue #17202 · department-of-veterans-affairs/va.gov-cms (github.com)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17202)

### SPRINT 4 UNPLANNED WORK (Post Sprint Planning)
