### ISSUE TITLE
Design: Add VA health connect and VA health chat to VAMC page

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17308]
## Description
We need to find a centralized way to promote the availability of alternate ways which Veterans can communicate with their health care teams, specifically VA health chat and VA health connect. 

Veterans can use these tools to compete the following tasks
- schedule, confirm, or cancel primary care appointments
- Ask a nurse medical or health-related questions
- Talk to a medical provider about an urgent or developing medical issue via phone or video
- Refill, request medication renewals, or check on the status of medication 

**How might we add these communication options to VAMC pages in a centralized way?**
- Options: 
   - `Manage your health online` box, found on health care system main pages 
       - because VA health chat and VA health connect can be used to complete tasks similar to those included in this area 
       - the `Manage your health online` box is hard coded on the front end, rather than powered by Drupal
   - Location and contact information block found on system level page , locations page, and facility level pages - this may be difficult to manage for facilities which already include the VA health connect phone numbers (and label change will also impact this area)
   - Top task action buttons - these tools are methods for completing top tasks, not top tasks in themselves
<details>
<summary> screenshots </summary>

<img width="783" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWw5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--697cd895e90e7b9e613833b121c2f27e35ad2a00/image.png" alt="image.png" />

<img width="470" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk45QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e5f8db822c7285f71378efca6228acf0c16a583/image.png" alt="image.png" />

<img width="304" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjZBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cdb5f3d33bf651d6a485671242ece2d914be2f8/image.png" alt="image.png" />

</details

## Tasks
Determine the best location to add the following links and update the relevant design 
- Learn more about VA Health Connect (will link to campaign landing page) - if icon is needed, it should communicate this option as telephone-based
- Get the VA Health Chat app (will link to VA Health Chat | VA Mobile) - if icon is needed, it should represent the messaging/app/mobile nature of this method
- Evaluate the feasibility of a label change from `VA health connect` to V`A Health Connect Clinical Contact Center` to improve Veteran understanding of the purpose and use (in the Locations and contact information block on VAMC pages and in Facility Locator search results

## Acceptance Criteria

- [x] Design mockups with Health Connect and Health Chat are added to contextually relevant points on VAMC pages
- [x] CAIA review (close loop [in existing ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/68030))
- [x] PO review
- [x] Link locations shared with Alexis for related research 
- [x] follow up tickets created

**Comment by thejordanwood** [comment]
Some content feedback that may be relevant:

https://github.com/department-of-veterans-affairs/va.gov-team/issues/68030#issuecomment-1807251225

**Comment by xiongjaneg** [comment]
@thejordanwood Please refine and point. When it's in a good spot, we can put it in the Ready column as a stretch. Thanks for your flexibility!

**Comment by aklausmeier** [comment]
@xiongjaneg I'll be taking this one.

**Comment by aklausmeier** [comment]
@mmiddaugh Do you want me to address updating the phone label for VA Health Connect in the design I am doing for this ticket? 

> proposal to increase telephone label for VA health connect found in two places (Facility Locator search results and VAMC Locations and contact information block)

https://dsva.slack.com/archives/C0FQSS30V/p1708550599669129

**Comment by aklausmeier** [comment]
@mmiddaugh 

Considering a broad approach, we have two phases of adding VA Health Chat and VA Health Connect to VAMCs for Veteran sense making. 

1. Top-level presence (immediate placement for campaign landing page)
2. Contextually relevant linking (post [upcoming research](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/16011))
    - placements informed by Veteran research
    - considers the capabilities each system or facility offers and placement is within context such as within an accordion like Nurse Advice or Pharmacy

**Immediate top-level placement recommendations:**

- Add **VA Health Connect** to
    - main contact info with proposed link label "VA Health Connect, 24/7 virtual care"
       - Facility Locator listing
       - Systems level landing page, main contact info blocks
       - Facility level landing page, main contact info block
    - VA Health Connect page under Programs, systems level
        - OR a combined VA Health Chat / Health Connect campaign landing page
 
- Add **VA Health Chat** 
    - In the spotlight, system level (preferred)
    - or to the “Manage your health online” block (alternative, centralized)
        - some concern Veterans might be confused seeing it next to Secure messaging and may want to wait for research insights to see if this assumption is true
     - VA Health Chat page under Programs, systems level
        - OR a combined VA Health Chat / Health Connect campaign landing page



Options annotated and shown in [design mockups](https://www.figma.com/file/ikCp2eOubIgbN1TwyEYIrN/VAMC-CMS-Master?type=design&node-id=63%3A5796&mode=design&t=0wSfxTabmHnqbKVK-1)

**Comment by mmiddaugh** [comment]
Moved FE task into #17436 FE: Add VA health chat and VA health connect to the Manage your health online box
