### ISSUE TITLE
Platform CMS Sprint Plan 48 (2/29/2024 - 3/12/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17331]
### 2024 Q1 Vision
Keep the lights on and build a foundation of excellence. 

### Sprint 48 Capacity
All Eng: 
All UX: 
All Support: 
All CMS Team:

### Sprint 48 Goals & Priorities

**SPRINT 48 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [ ] ?

### SPRINT 48 PRIORITIES
These are candidates for projected sprint work. Prioritize tickets in this order: 1) Sprint goal, 2) CY23Q4 goal, 3) the rest of the tickets in this section:

**Onboarding New Team**
Onboarding and gaining access to the needed VA systems.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17013
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17010
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17011
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17009
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17014
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17016
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17015
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17012
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17218
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17219
- [ ] Grace and Michelle build sprint and communication structures.

**Prod Offline Incident Post Mortem (Epic [#17242](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17242))**
- [ ] Grace will synthesize findings into a post mortem report in GitHub. 

**Tugboat Discovery**
- [ ] DevOps team investigate Tugboat to understand how to best support the application and make recommendations to improve Tugboat's uptime and sustainably scale the application. 

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646
 
**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [ ] Take Knowledge Base Study and translate into an implementation plan.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136

**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] Pivot collab cycle work to include moving CMS from site-wide to platform. 
- [ ] Discovery work in collaboration with Platform governance team to understand where CMS should plug into the existing collaboration cycle. 

**Dependencies / Dependabot PRs**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15663gov-cms/issues/17102

**Parking Lot**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17073
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17019
- [ ] https://github.com/orgs/department-of-veterans-affairs/projects/1194/views/1?pane=issue&itemId=54015742

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [ ] Technical discovery work about PDF deletion bug in Drupal

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825
- [ ] [Run menu re-org script on prod and fix Lovell · Issue #17202 · department-of-veterans-affairs/va.gov-cms (github.com)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17202)

### SPRINT 48 UNPLANNED WORK (Post Sprint Planning)

**Comment by gracekretschmer-metrostar** [comment]
Capacity direction: each team member is going to start creating their own tasks for each assigned epic and start tracking their capacity through hours. We will work together on a team norms session to establish standards around capacity. 

Onboarding next steps: historically, the onboarding tickets have been timeboxed to a limited number of sprints. Right now, there's a challenge of just getting through the videos and readings is a big lift. Jon: could we mark specific tasks a required and optional?

ATO: Need to work with platform team to resolve AL2 harden and need register CMS as a minor application. 

KB: Knowledge base search will be assigned to Jay and he will look to see what search improvements could be. Jay will rely on Edmund and Amanda for any access support he needs. 

Collab Cycle: Marisa will move forward with a working session for the platform team/collab cycle and how we want to define success and opportunities to move forward. Steve will work on accessibility standards for collab cycle. Need to focus on accessibility only for Drupal. Should talk to Laura Flannery. Need to address the question about custom code question and when to use it. This relates to the design system. Steve: there's an opportunity to do an audit for all of the custom code. Erika: there is a place where we can see all the custom code, mostly related to facilities products. 

Drupal PDF: Jay will research possible solutions to delete PDFs.
