### ISSUE TITLE
Make Drupal the source of truth for VBA shared location fields

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17353]
## User Story or Problem Statement

The fields `Shared VHA location` and `Non-VA location official name` on the VBA Facility Content type currently have Sandy's Database as the source of truth. They are migrated into Drupal as part of a periodic migration.

These two fields will be used to power the "Located at" text associated with the H1 on VBA regional office pages.

![Screenshot 2024-02-27 at 10 30 29 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/d2d4368f-bbd0-4af3-b5e6-8077ed0e199b)

In #15752, I originally proposed doing a data clean up in Sandy's DB and then running that migration. But @mmiddaugh pointed out we could instead deprecate Sandy's DB as the source of truth and do the data clean up in Drupal.

### Current Migration
- [VBA Facilities VBA Database Migration](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-facility.md#vba-facilities-vba-database-migration)
- Run this one more time to catch any updates since it was last run?
- Edit migration to not pull these in from Sandy's DB
- Any other fields we want to start having Drupal be Source of Truth for at the same time?
- Remove them from Sandy's DB? Or just leave them there?
- Start conversation with Lighthouse about supporting these fields (may also come up in #17351)

### DB clean up
- **Product** / **Content**
- [initial quick findings](https://dsva.slack.com/archives/C0FQSS30V/p1707955907018829?thread_ts=1707949354.658559&cid=C0FQSS30V) in slack
- [Additional findings](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15752#issuecomment-1959742070)
- Audit the fields `Non-VA location official name`, `Shared VHA location`, and `Official name`
- Update the fields `Non-VA location official name` and `Shared VHA location` to match reality / official name
  - Only one of these two fields should be populated
- Do not update `official name` unless it contains _ontologically_ inaccurate information. This is primarily an additive audit, so we shouldn't be removing any information.
  - Shared VHA facility has a new name not reflected in official name = don't change `official name`
  - "Shared location" in official name  is actually a geographic region (e.g. Sacramento) = don't change `official name`
  - There is data in either `Non-VA location official name`, `Shared VHA location` that is not reflected in official name = don't change `official name`
  - We learn that a facility that currently says it has a shared location is actually a standalone building = _maybe_ change `official name`, but it's not vital for the sake of this ticket

## Description or Additional Context 

![Screenshot 2024-02-27 at 11 55 28 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/1d1e246d-4073-4284-9b8e-50f9ae9390be)

## Tasks

- [ ] Run the migration as currently done
- [ ] Change configuration of migration to remove shared location from it
- [ ] update [this knowledge base article](https://prod.cms.va.gov/help/veterans-benefits-administration-vba/location-and-contact-information)

## ACs

- [ ] Shared location fields updated from Sandy's DB
- [ ] Subsequent migrations from Sandy's DB do not not update the fields named above in Drupal
- [ ] Content model and product documentation is updated

**Comment by omahane** [comment]
# Points of clarification
- The db extract migration from Sandy's db was last run on 2022-11-21 15:09:21.
- Per @mmiddaugh, we do have an instance of the `Non-VA location official name` and `Shared VHA location` are both different and meaningful: [in Manila](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351#issuecomment-2037907154)

**Comment by omahane** [comment]
I propose that that we deprecate these shared location fields (along with District), here: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351#issuecomment-2327090762

**Comment by davidmpickett** [comment]
@mmiddaugh @jilladams @Agile6MSkinner - This came up today when @omahane and I were discussing the related ticket about cutting VBA names. 

While we won't be able to **fully** remove our dependence on Sandy's DB until Lighthouse is ready to update their API to make Drupal the source of truth of VBA data, this ticket is an instance of where we are unblocked and could begin to reduce our reliance on Sandy's DB.
