### ISSUE TITLE
Improve services accordions and service locations across Facilities products

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17350]
### User Story or Problem Statement
As a Veteran, I need to easily understand who and how to contact to get the services I need.
As an editor, I need to easily be able to provide accurate and timely information about services contact information.

This epic is to improve how services accordions and service locations are used by editors across Facilities products. Human-centered and accessible design considerations will ensure that the Drupal user interface provides editors with helpful, easy-to-understand guidance as the point of services entry. Consistent design and processes across products allows engineers to maintain products more efficiently and with less context-switching between products.

### Affected users and stakeholders

* VAMC editors
* VBA editors
* Vet Center editors

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by aklausmeier** [comment]
Deep understanding of issues and context can be found in #13932

**Comment by jilladams** [comment]
@omahane to create a new ticket to cover pushing the `Virtual support` field to Lighthouse. Not launch blocking. Likely a 3.
