### ISSUE TITLE
[Components] Future: V1 components without V3 equivalents

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17379]
## Description

This epic lists Public Websites products which have V1 components with no V3 equivalents (provided by Laura Flannery) so that we may then refer to it and write stories as V3 components become available.

- Global Search Results: Loading Indicator: Currently using v1, which is the most up to date component
- Campaign Landing Pages: Back to top: Currently using v1, which is the most up to date component
- Benefits Hub Landing Page: 
  - On this page: Currently using v1, which is the most up to date component
  - Banner: Currently using v1, which is the most up to date component
- Benefits Detail Page
  - Back to top: Currently using v1, which is the most up to date component
  - On this page: Currently using v1, which is the most up to date component
  - Table: Currently using v1, which is the most up to date component
- Find a Form
  - Back to top: Currently using v1, which is the most up to date component
  - Loading Indicator: Currently using v1, which is the most up to date component
- FAQ Page
  - On this page: Currently using v1, which is the most up to date component
- Resources & Support Detail Page  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16987 (need a new epic for this/these)
  - Back to top: Currently using v1, which is the most up to date component
  - On this page: Currently using v1, which is the most up to date component
  - Table: Currently using v1, which is the most up to date component

### User story

**AS A** PO/PM managing certain VA.gov products and features
**I WANT** to ensure the PW team updates V1 components when the Design team creates and makes available V3 components
**SO THAT** the VA.gov experience for  Veterans, their family members, caregivers, or survivors is not degraded when the Design team updates to V3.

## Acceptance criteria

- [ ] Global Search Results: Loading Indicator ticket is created
  - [ ]  Global Search Results: Loading Indicator is refined and prioritized
- [ ] Campaign Landing Pages: Back to top ticket is created
  - [ ]  Campaign Landing Pages: Back to top ticket is refined and prioritized
- [ ]  Benefits Hub Landing Page: On this page ticket is created
  - [ ] Benefits Hub Landing Page: On this page ticket is refined and prioritized
- [ ]  Benefits Hub Landing Page: Banner ticket is created
  - [ ] Benefits Hub Landing Page: Banner ticket is refined and prioritized
- [ ] Benefits Detail Page: Back to top ticket is created
  - [ ] Benefits Detail Page: Back to top ticket is refined and prioritized
- [ ] Benefits Detail Page: On this page ticket is created
  - [ ] Benefits Detail Page: On this page ticket is refined and prioritized
- [ ] Benefits Detail Page: Table ticket is created
  - [ ] Benefits Detail Page: Table ticket is refined and prioritized
- [ ] Find a Form: Back to top ticket is created
  - [ ] Find a Form: Back to top ticket is refined and prioritized
- [ ] Find a Form: Loading indicator ticket is created
  - [ ] Find a Form: Loading indicator ticket is refined and prioritized
- [ ] FAQ Page: On this page ticket is created
  - [ ] FAQ Page: On this page ticket is refined and prioritized
- [ ] Resources & Support Detail Page: Back to top ticket is created
  - [ ] Resources & Support Detail Page: Back to top ticket is refined and prioritized
- [ ] Resources & Support Detail Page: On this page ticket is created
  - [ ] Resources & Support Detail Page: On this page ticket is refined and prioritized
- [ ] Resources & Support Detail Page: Table ticket is created
  - [ ] Resources & Support Detail Page: Table   ticket is refined and prioritized

**Comment by FranECross** [comment]
@laflannery I've created the epic for the future component work that you captured in your original audit. The AC is for me to create tickets and prioritize as components become available. I'm happy to edit as needed! cc @jilladams
