### ISSUE TITLE
Review and Adjust PHP Settings Across Environments

### ISSUE THREAD

**Issue by alexfinnarn** [department-of-veterans-affairs/va.gov-cms#17378]
While working on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17021 I noticed that the `max_input_vars` setting on my local DDEV environment was different than what is on Tugboat and also different than what is on production. This caused issues with the approach I was taking to solve an issue, and I thought it would be a good idea to open an issue to review PHP settings across environments so that devs don't write code and push it up only to find out server configuration prevents the code from working as expected during development. 

Example differences in `max_input_vars` setting:
- DDEV - 5000
- Tugboat - 1000
- Staging - Unkown (currently down)
- Production - 10,000

### Tasks:
- [ ] Review `phpinfo()` output from "/admin/reports/status/php" across DDEV/local, Tugboat, staging, and production
- [ ] List out differences in settings that diverge
- [ ] Look for best practices in PHP server configuration for those settings
- [ ] Commit updated PHP settings to respective configuration files
- [ ] Try to draw the PHP ini overrides from a centralized file, if possible
- [ ] More things a PM knows are needed...and/or rework initial set of task acceptance criteria from whoever takes this over.

### Team
Please check the team(s) that will do this work.

- [ ] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
