### ISSUE TITLE
Document Facilities research processes

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#17413]
## Purpose
This is to document the current state of Facilities research in light of potential contract transition.

# Tasks
- Review current Facilities projects in the [research roadmap Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1699650112593/672d59e5ac915c73c1dfd8d6326fcff277bc28db?sender=u3f35bedf61955cb051f44770)
- Locate all documentation for current work 
- Create a Word doc in Sharepoint for documentation

# Acceptance criteria
- [x] Current Facilities research projects are documented in Facilities team Sharepoint's [UX Folder](https://dvagov.sharepoint.com/:f:/s/SitewideFacilitiesTeam/Es-NKHca2vFNl28Vu6Kr-h4BEEWdgejYO3RmA1BBe7V9Jw?e=SVwsi2)
- [x] Sharepoint doc reviewed by Facilities team, PO, and UX lead for omissions or clarifications
- [x] Updates to document based on team feedback
- [x] Slack team with link to final document

**Comment by xiongjaneg** [comment]
@ALogsdon3 Would you please refine and point this ticket if you end up using it next sprint? Thank you!

**Comment by aklausmeier** [comment]
@ALogsdon3 and I met and discussed:

All Murals and Sharepoint docs should be in Facilities **team** folders.

**Comment by aklausmeier** [comment]
Created a [UX folder](https://dvagov.sharepoint.com/:f:/s/SitewideFacilitiesTeam/Es-NKHca2vFNl28Vu6Kr-h4BEEWdgejYO3RmA1BBe7V9Jw?e=SVwsi2) in Facilities team Sharepoint, updated ticket with link

**Comment by ALogsdon3** [comment]
All ACs complete, closing this ticket.
