### ISSUE TITLE
Discovery: Content Build's Failures and Delays

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17423]
## Background
When a VA editor updates or adds new content in Drupal, they are advised that their content will not show up to VA.gov for two hours because of the content build progress. On 3/4/2024, the content build progress failed twice and then became delayed (1-2hrs added to the process). 

### User Story or Problem Statement
How can we understand these failures and delays to address the root cause and plan for a more stable content build? 

### Affected users and stakeholders

*VA Editors
* Veterans

### Hypothesis
There's been instability with the runners during the content build process that could be impacting the failures and delays. By addressing the runner issues, we believe that content build will stabilize and reduce the time delays. 

(How will these assumptions be validated?)

## Acceptance Criteria
- [x] The root cause of 3/4/2024 failures is understood and how to resolve the failures in the future.
- [x] The root cause of 3/5/2024 of delays is understood and how to resolve the failures in the future. 
- [x] A path forward of how to sustainably address the failures and delays documented in Confluence.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17422
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17431
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17441
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17384
```

**Comment by Hassantariq-MetroStar** [comment]
As per our investigation with Hector, we found that the issue with runners is disk space is not getting cleaned up after the completion of the job i.e, after uploading the .tar folder to s3 bucket and in that period of time, its reaching upto 78% of the disk space.
And we are not cleaning the .tar file after uploading to the S3 bucket in the pipeline. This is the reason that another runner dont have much space to run on the server and its getting stuck.
I'm assuming if we upload the .tar file to s3 bucket, so we already have a backup and we dont need that .tar to be on runner everytime.
As of now there is **no issue with github runners except the time of completion** which is a low priority and involves  other teams to work collaboratively to re-define the setup of these runners to decrease the delay in job completion.

**Comment by gracekretschmer-metrostar** [comment]
@Hassantariq-MetroStar based upon our conversation in sprint planning, I am to pull this up into Sprint 6. Can you update the epic to describe the next steps needed for this discovery work?

**Comment by gracekretschmer-metrostar** [comment]
@edmund-dunn and @7hunderbird can y'all refine to content build work doing for sprint 6?
