### ISSUE TITLE
Alt Text field upgrades

### ISSUE THREAD

**Issue by srancour** [department-of-veterans-affairs/va.gov-cms#17443]
### Problem Statement

How might we further improve the alt text validation to allow editors to add better, more useful alt text for the images they are uploading?

### Affected users and stakeholders

* CMS editors of all products

<link to any existing research or data supporting this>

### Hypothesis

We believe that users are still not understanding how to use alt-text for images. By increasing their knowledge and improving the alt-text field we can improve the quality of the alt-text submitted.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Team
Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`
- [ ] `Accelerated Publishing`

**Comment by aklausmeier** [comment]
@srancour @MDomngz In Facilities recent VBA regional office editor research a related insights were uncovered. 

- Description and Alt text were confusing to user, he assumed they were the same thing
- Alt text was very clear to him, more help text is needed for description to better understand alt text best practices

Historical context, when the [alt text work](https://www.figma.com/file/KAY52TczGiRksfayWkMr2c/CMS-Media-Alt-Tags?type=design&node-id=529%3A11615&mode=design&t=MfyrSb0s6cl10kyO-1) was done last year (research and full ux flow), the description field was not addressed. Is this necessary? 

Question to you both, do you feel the above insights can be addressed within the scope of this epic?

**Comment by srancour** [comment]
@aklausmeier I actually chatted with @edmund-dunn about the description field for the images a couple weeks ago as I was digging into the alt-text work and thought that it probably confused editors with alt-text. We did come to the agreement that the description field is an unnecessary field, since the only place where that field is used is in the storage of the file, and we should look at getting rid of it.

I do think those insights can absolutely be addressed in this epic as it shows that editors are directly being confused about the alt-text field because the description field exists.

**Comment by aklausmeier** [comment]
> the description field is an unnecessary field, since the only place where that field is used is in the storage of the file, and we should look at getting rid of it.

I would support this.

**Comment by michelle-dooley** [comment]
We will pick this back up after accessibility audit to see what we learn from that and how that may apply here.
