### ISSUE TITLE
update packages for content-build

### ISSUE THREAD

**Issue by edmund-dunn** [department-of-veterans-affairs/va.gov-cms#17456]
## User Story or Problem Statement
We need to update some dependencies within content-build. 

## Description or Additional Context 
These tickets contain the specifics for the required updates:
#17100 
#17101 
#17102 

## Steps for Implementation
Update dependencies including deprecated `babel` dependencies.

## Acceptance Criteria
- [x] Dependencies updated to the required versions. 
- [x] All critical errors have been resolved.
- [x] No failures during the build process.
- [ ] The sitewide public websites team confirms that the webpages are operating as expected. 

## Team
Please check the team(s) that will do this work.

- [x] CMS Team
- [x] Public Websites
- [ ] Facilities
- [ ] Accelerated Publishing

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102
```

**Comment by gracekretschmer-metrostar** [comment]
Erika's feedback: if public websites is the dependency, then remove as goal for this sprint.

**Comment by jilladams** [comment]
Added @dsasser as a reviewer on the PR. However, per discussion with @FranECross and @davidconlon , we can't inject this into current sprint, so we'll take a look in our next sprint and get feedback to you by the 4/15 deadline.

**Comment by jilladams** [comment]
(Public Websites will create our own ticket to track the review. We will link it here when it's available.)

**Comment by gracekretschmer-metrostar** [comment]
PW team will have review completed by the end of their next sprint (~4/14).
