### ISSUE TITLE
Prep for VA Health Chat and VA Health Connect tree test

### ISSUE THREAD

**Issue by ALogsdon3** [department-of-veterans-affairs/va.gov-cms#17498]
### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up VA health chat link placement research
**SO THAT** the research will happen successfully

## Tasks for Sprint 106 -- 13 points
Use [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies) as a guide

**Finalize research deliverables**
- [x] Update [research plan and conversation guide](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/research/VA-health-chat/research-plan.md) with any timeline or protocol tweaks
- [x] Update [sitemap in Treejack](https://app.optimalworkshop.com/a/dj540s05/treejack/surveys/3bc8b181-47f3-42db-9bde-ce02002ef587/edit#/t/setup/tree) to reflect all potential correct paths
- [x] Update settings in Optimal Workhop based on guidance from [Planning Unmoderated Studies](https://depo-platform-documentation.scrollhelp.site/research-design/planning-unmoderated-studies)

**Pilots** 
These can be with people on our team--15 minute sessions where they complete tree test and talk through it.
- [x] Recruit, schedule, run pilots with 1-2 volunteers
- [x] Make any revisions needed to conversation guide and prototype

**Coordinate with Research-Ops and Perigean**
- [x] Create recruiting request and submit to VA Research-Ops. Use [Easy Recruitment Request for Unmoderated Cohorts](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose)
  - [x] In description, add links to github research folder and (from previous step) recruiting request form
  - [x] Make Amanda the assignee
  - [x] Add labels for the project's product, research methodology, audience, etc. using [this list](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)
  - [x] Submit [Research review](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/research-review) ticket ("1-2 weeks before you plan to conduct user research")

## Acceptance criteria
- [x] Tree test is ready for testing in OW
- [x] UX lead feedback incorporated into tree test / research plan
- [x] Pilots completed
- [x] Project submitted for research review
- [x] Recruitment request completed
- [x] Follow-up tickets created as needed

**Comment by aklausmeier** [comment]
@ALogsdon3 reminder to add your and my contact info at bottom of research plan

Research plan and task development: Alexis Logsdon (your email)
VA UX Lead & Project point of contact: Amanda Klausmeier (amanda.klausmeier@va.gov)

**Comment by mmiddaugh** [comment]
@ALogsdon3 @aklausmeier - thank you for the opportunity to review the research plan. A few thoughts: 
- Research goals
   - Suggest adding VA health connect to Research goal 2 (secondary goal) - both methods are otherwise mentioned throughout 
- OCTO priorities
   - Suggest adding: "Number of transactions processed using our products have increased by 25%" as we hope that promoting these communication methods in logical places on VAMC pages will increase Veterans awareness and use of the tools 
- Tasks
  - VA health chat and VA health connect were created as an alternative to calling a medical center's main phone number so that Veterans can connect with someone who can help them more quickly and without a lengthy time on hold. VA health connect is also available 24/7. Both provide real-time/live support. 
     - Given those features, I wonder if the tasks (particularly for VA health connect) should more clearly separate this task from simply calling the main facility phone number or leaving a message. Such as, "It's after hours and you'd like to ask someone about a health concern..." or "You need to change your appointment and don't know which extension to call..."
    - Task 6. Suggest replacing "someone on your your health care team" with something more general such as "a health professional" or "VA health care staff" because the tools connect Veterans with someone who can help, but not necessarily someone who knows them or is at their facility (This is different than secure messaging, which goes direct to their provider or team). 
- Recruitment
  - Both tools are only available to Veterans who are enrolled in VA health care. VA health chat also requires the Veteran to have login credentials. 
     - Should these be included in the recruitment criteria? 
     - Is familiarity with VA health facility webpages important?

**Comment by xiongjaneg** [comment]
From Michelle: Do we need Veterans to test this?
From Alexis: This could probably be done internally with team members or other team members (PW, CMS, etc.)

**Comment by xiongjaneg** [comment]
Given limited time and priorities, documentation on this may be lower priority. Amanda and Dave may be able to assist with that aspect of this ticket.

**Comment by aklausmeier** [comment]
@ALogsdon3 The distinction between secure messaging and nurse advice line/VA Health Connect would be secure messaging is direct with their medical provider and Health Chat or Health Connect is they can speak with on call health professionals not necessarily the patient's direct provider team. 

> Suggest replacing "someone on your your health care team" with something more general such as "a health professional" or "VA health care staff"

> I was operating under the assumption that they could speak to someone from their team if they identified Nurse advice line as their answer. I was basing that on your Mural, and I made a little chart for myself to track paths to each service. I will attach that as another comment below.

**Comment by ALogsdon3** [comment]
Current status: 
- Tree test is ready for piloting and feedback. Link shared in facilities channel. 
- Scheduled message for Thursday AM in public websites channel to get pilot participants.
- Once I've gotten feedback on the tree test from PW participants, will submit to research review (hoping to do this by Friday, 3/20)

**Comment by ALogsdon3** [comment]
Research has been submitted for review! Now we wait. :) 
cc: @aklausmeier @jilladams @xiongjaneg @mmiddaugh

**Comment by jilladams** [comment]
In the spirit of @xiongjaneg and @ALogsdon3 leaving next week: the last AC here is for tickets created as needed for next steps. If someone's able to share what the next steps probably look like (synthesis?) I can help make those, or Alexis, if you're able to spell out tickets for what comes next, holler.

**Comment by aklausmeier** [comment]
You can create a ticket and assign to me for Research Synthesis.

**Comment by ALogsdon3** [comment]
Research review is complete; recruitment kickoff has begun, with estimated start date of study April 1, 2024. Closing this ticket as completed.
