### ISSUE TITLE
Platform CMS Sprint Plan 06 (3/14/2024 - 3/27/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17502]
### 2024 Q1 Vision
Keep the lights on and build a foundation of excellence. 

### Sprint 06 Capacity
All Eng: 
All UX: 
All Support: 
All CMS Team:

### Sprint 06 Goals & Priorities

**SPRINT 06 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17383

### SPRINT 06 PRIORITIES
Priorities are listed from highest priority to lowest priority, starting at the top of the list. 

**Onboarding New Team**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17010
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17014
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17218
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17527
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17288

**Plan for Redis Upgrade**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17504

**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17383
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136

**Onboarding of Accelerated Publishing Team (Epic [#17506](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17506))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17461
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17507

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15136
- [ ] Technical discovery work about PDF deletion bug in Drupal
- [ ] Bring in PDF audit and look at how we can correct the deletion issue. 

**DevOps Discovery**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17423
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17387

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [x] Schedule meeting with ATO PM to understand next steps.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17316
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646
 
**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] Pivot collab cycle work to include moving CMS from site-wide to platform. 
- [ ] Discovery work in collaboration with Platform governance team to understand where CMS should plug into the existing collaboration cycle. 

**Dependencies / Dependabot PRs ([#17456] (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17456))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102

**Drupal Maintenance**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17073
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17019
- [ ] https://github.com/orgs/department-of-veterans-affairs/projects/1194/views/1?pane=issue&itemId=54015742
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15663

**Cyress Testing Discovery**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17465
- [ ] Get Jon to create an epic. 
- [ ] Hypothesis: use the cucumber framework for writing user stories for engineers. 

### Stretch Goals (only work on after completing your pre-defined sprint work)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17384
- [ ] Q2 planning

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825

### SPRINT 06 UNPLANNED WORK (Post Sprint Planning)
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17641
