### ISSUE TITLE
Update VA service taxonomy view with VBA service details 

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#17545]
## Description
As a Drupal Admin, I would like the VA service taxonomy view to include the details for VBA services and be able to filter using VBA as a content type so that my work can be more efficient. 

## Current functionality
The VA service taxonomy displays descriptions, type of care, and number of uses for each VAMC and Vet Center service. The taxonomy can be filtered for VAMC and Vet Center content types. Now that VBA services are included, the details should be included and the content type should be available as a filter. 

<details>
<summary> VA Service taxonomy content type filter  </summary>

<img width="593" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1ByQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3d21b731df7e2cd47e598506d5a42e79f8ab744/image.png" alt="image.png" />
</details>

---

<details>
<summary> Notice the row for the VBA Home Loans service compared to the row for Homeless Veteran care, used by VAMC and Vet Centers </summary>

<img width="1839" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzNyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e067fb606385cda5477afe98b210da360674ce93/image.png" alt="image.png" />
</details>

```[tasklist]
### Tasks
- [ ] VBA Facility service is selectable from the Content type drop down
- [ ] The Description column displays the VBA description if available
- [ ] The Type of Care column displays VBA Service Type if available
- [ ] Remove the Stop Code column (it is totally empty)
- [ ] Tighten up formatting
- [ ] No regressions to VBA and VAMC functionality
```

**Comment by davidmpickett** [comment]
Formatting consideration. For the fields where the value may differ between VAMC, Vet Center and VBA, do we need to repeat the column labels in each entry? Or could we just list the Product prefix

- VAMC Patient-friendly Name: -> VAMC:
- Vet Center Patient-friendly Name: -> Vet Center:
- etc.

![Screenshot 2024-09-11 at 2 56 19 PM](https://github.com/user-attachments/assets/c06742ad-e0c4-4960-b661-07764b4730f2)

![Screenshot 2024-09-11 at 2 56 19 PM copy](https://github.com/user-attachments/assets/c37d3090-769f-4028-8d25-a8ebd62b8c45)

**Comment by davidmpickett** [comment]
Currently stuck on trying to strip the p tag that seems to come from the term description property without destroying special characters in the process

![Screenshot 2024-09-11 at 6 32 09 PM](https://github.com/user-attachments/assets/9d109fd8-e1af-437c-8f3c-91bd070c6e05)

![Screenshot 2024-09-11 at 6 32 15 PM](https://github.com/user-attachments/assets/4fef1a37-d771-4891-b085-1f5fa5c60f26)

**Comment by davidmpickett** [comment]
Verified in prod https://prod.cms.va.gov/va-services
![Screenshot 2024-09-17 at 3 20 33 PM](https://github.com/user-attachments/assets/20541c94-54cd-4ce0-9523-53055da12602)
