### ISSUE TITLE
[PR Review] Review PR for three CMS Team tickets

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17558]
## Description

The CMS team has PRs for three tickets (see below) which need review by the PW Team's Drupal expert. Targeting Sprint 107.

Tickets:
- #17100 
- #17101 
- #17102 

### User story

**AS THE** CMS Team
**I WANT** to have the PW Team's Drupal expert review the PRs for three of our tickets
**SO THAT** we can receive suggested changes or approvals, thus increasing the confidence in the code not presenting issues to editors or Veterans, et al.

## Acceptance criteria

- [ ] PR Review for ticket #[17100](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100)
  - [ ] Questions / suggestions given, if applicable
  - [ ] Signed-off
- [ ] PR Review for ticket #[17101](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101)
  - [ ] Questions / suggestions given, if applicable
  - [ ] Signed-off
- [ ] PR Review for ticket #[17102](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102)
  - [ ] Questions / suggestions given, if applicable
  - [ ] Signed-off

**Comment by FranECross** [comment]
@dsasser will you please provide @gracekretschmer-metrostar an update on this ticket's progress? She's asked: Is there any way this could get completed in the next few days? I connected the dots that if PW does their review at the end of your current sprint and finds issues, that doesn't give the CMS team much time to fix those issues before 4/15 (when [we are required](https://github.com/orgs/department-of-veterans-affairs/discussions/5) to have the critical issues resolved).

Thanks in advance!

**Comment by dsasser** [comment]
@FranECross @gracekretschmer-metrostar 

I have reviewed and [approved](https://github.com/department-of-veterans-affairs/content-build/pull/1949#pullrequestreview-1992490998) the PR related to all of the affected tickets.

**Comment by jilladams** [comment]
PR merged, closing.
