### ISSUE TITLE
Platform CMS Sprint Plan 07 (3/28/2024 - 4/10/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17564]
### 2024 Vision
Keep the lights on and build a foundation of excellence. 

### Sprint 07 Capacity
All Eng: 
All UX: 
All Support: 
All CMS Team:

### Sprint 06 Goals & Priorities

**SPRINT 07 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17640

### SPRINT 07 PRIORITIES
Priorities are listed from highest priority to lowest priority, starting at the top of the list. 

**Onboarding New CMS Team**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17010
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17527

**Onboarding of Accelerated Publishing Team (Epic [#17506](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17506))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17461
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17507
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17679

**2024 Roadmapping and Q2 Planning**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17640
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17288

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17604
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15136
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17648

**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17563
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17442

**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17383
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136

**DevOps Discovery**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17423
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17387
- [ ] To do: add Tugboat discovery and assign to Robbie

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17316
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646
 
**Dependencies / Dependabot PRs ([#17456](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17456))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102

**Team Norms and Charter**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17565

**Drupal Maintenance**
- [ ] https://github.com/orgs/department-of-veterans-affairs/projects/1194/views/1?pane=issue&itemId=54015742
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15663

**Code Scanning Fixes for WASA ([#17647](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17647))**
- [ ] https://vfs.atlassian.net/wiki/spaces/PRT/pages/2942369846/Code+Scanning+Fixes+Required+for+WASA

### Stretch Goals (only work on after completing your pre-defined sprint work)
- [ ] PDF discovery work

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825

### SPRINT 07 UNPLANNED WORK (Post Sprint Planning)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17774

- [ ]
