### ISSUE TITLE
[EPIC] Forms migration: nodes with changed Title should get the Changed Title flag

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17574]
## Description

On 3/6/2024, VA Form 21-0307 was updated in the Forms DB with a new title. Drupal migration ran at midnight 3/7/2024, and data was successfully migrated to Drupal.  After migration, the form node reflects the new `Form name` from Forms DB, but: https://prod.cms.va.gov/find-forms/about-form-21-0307 
* No revision on 3/7/2024 from CMS Migrator to reflect the changed title [defect]
* Change Title flag was not added to the node: https://prod.cms.va.gov/admin/content/va-forms/changed-title [defect]
* `Form title` (Drupal field) was not updated to match the `Form name`from the Forms DB. [not sure if this is a defect or intended behavior]

This epic organizes the  research Spike and subsequent tickets.

### Migration Context & docs
* Migration: https://prod.cms.va.gov/admin/structure/migrate/manage/forms/migrations
    * Nightly CSV artifact will appear here: https://prod.cms.va.gov/sites/default/files/migrate_source/va_forms_data.csv
* Forms Migration docs: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md
* Product docs: Forms > engineering > data: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md -- has some specific context around how we handle dates, for reference
* https://dsva.slack.com/archives/C52CL1PKQ/p1709821062708819

## AC / Expected behavior
- [ ] After nightly forms migration, any form node with a changed title should get the Changed Title flag and appear in the Changed Title va-forms view
- [ ] Any node modified by the migration should get a revision log from the CMS Migrator
- [ ] ~Migration logic for how `Form name` is or isn't set up to modify the `Form title` Drupal field is documented in either [Forms Migration](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-forms.md)  or [forms > engineering > data](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/find-a-va-form/engineering/data/data.md), to help determine if the existing logic should be modified~
- [ ] Summary notes are added to ticket comments, for PO / PM review re: whether follow up tickets are needed
- [ ] New tickets are created to track any changes required

**Comment by FranECross** [comment]
All tickets in this epic are closed/done. Closing.
