### ISSUE TITLE
[EPIC] Audit of GA Custom Events in PW products 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17608]
## Description

 When companies update to G4 (Google Analytics 4), any custom events aren't automatically ported over/migrated. Because of this, the Analytics team has asked for an audit of our custom events, and then for us to provide them information on the events we need them to manually move/add to G4

To that end, Randi has conducted a thorough audit of all custom events on Public Websites product features and created a [spreadsheet](https://docs.google.com/spreadsheets/d/1fDsRQct_QMJ5nd3bTRDgwrfbFo_PqzdFQqYecJouic8/edit#gid=0). Fran needs to review to determine which we can rely on the baked in analytics that web components provide.

## Acceptance criteria

- [ ] Audit of all custom events in PW products/features
- [ ] PM (Fran Cross) to review and determine which should be retained
- [ ] Analytic Team audit form completed (by Fran) 
  - [ ] Audit form provided to Analytics Team (Fran)
  - [ ] Ticket for Analytics Team created (Fran)

**Comment by FranECross** [comment]
All work completed
