### ISSUE TITLE
Code Scanning Fixes Required for WASA

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17647]
## Background
The platform reliability team is working on what is called Preview Environments - It allows teams to take their new code and combine it with isolated snapshots of the FE/BE repositories, so they can test their code in an isolated and low risk environment. The team's intent (and project requirements) includes making these Preview Environments publicly accessible, so teams can use these environments to test with real veteran end users.

In order to get anything publicly accessible, the team need to navigate through various stages of an approval process, which they've been working on and towards for quite some time to meet the various requirements that we become aware of. One of these requirements included having code scanning done on our repositories - which surfaced a number of critical & high issues for vets-website, vets-api, and content-build. In order to continue proceeding, we need to resolve the issues on that code scanning report, however it involves fixing a number of items in content-build, which we're not super familiar with.

In the WASA scan, three critical issues were identified within the content-build repo that the CMS team will own getting resolved. 

### Relevant Links
- https://vfs.atlassian.net/wiki/spaces/PRT/pages/2942369846/Code+Scanning+Fixes+Required+for+WASA

### User Story or Problem Statement
As user researcher, I wanted to be able to make preview environments publicly accessible so that I can more meaningful run usability tests with members of the public. To make preview environments publicly available, the preview environments need to resolve all critical issues identified in the WASA scan.

## Acceptance Criteria
- [ ] Critical issue: Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code as been resolved (https://github.com/department-of-veterans-affairs/content-build/security/dependabot/83) has been resolved
- [ ] Critical issue: [Cross-realm object access in Webpack 5](https://github.com/department-of-veterans-affairs/content-build/security/dependabot/67) has been resolved 
- [ ] Critical issue: [json-schema is vulnerable to Prototype Pollution](https://github.com/department-of-veterans-affairs/content-build/security/dependabot/13) has been resolved

**Comment by gracekretschmer-metrostar** [comment]
This ticket is duplicative of the update packages for content build ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17456

Therefore, closing this ticket.

**Comment by gracekretschmer-metrostar** [comment]
@anantais and @JakeBapple, there is a backlog of security issues attached to this epic (see under the task list). When each of you have completed your sprint tasks, you can pick up work in this task list.
