### ISSUE TITLE
Example design ticket that is secretly an epic in disguise

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17643]
## Background
All the real meat of a single large design ticket that might run across sprint boundaries. 

## ACs
- [ ] Actual AC for final acceptance
- [ ] Actual AC for final acceptance
- [ ] Actual AC for final acceptance - 
- [ ] Actual AC for final acceptance
