### ISSUE TITLE
Make required services unable to be removed or archived

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17676]
## User Story or Problem Statement

As a user with privilege to edit facility services, I want to be assured that I cannot "remove" or archive a facility service that is required. 

## Acceptance Criteria
- [x] A user with permissions to edit the service should be able to see on node:edit whether the service is required or optional.
- [x] Non-admin user is unable to archive a required service
- [x] Non-admin user is unable to "remove" a required service from a facility
- [ ] Admin user is able to archive a required service, if currently true in production
- [ ] Admin user is able to "remove" a required service from a facility, if currently true in production

## Implementation steps
1. ~~The most certain way is to add some server-side validation, like a constraint, that checks whether a service is required and throws an error when the user submits a form that would archive a service. Of course, we'd need to not throw it if the user is a content admin or admin, as it may actually be necessary to do this.~~
2. Another way would be to disable the Archive option in Moderation state for people for whom `hasAdminRole()` is not true. 

![333667772-50d05616-25b9-4cf8-8738-739b414a3814](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/3d9f06d2-b0d5-49d5-8271-e77e30abd9d6)

**Comment by jilladams** [comment]
This ticket doesn't yet account for archiving / removing optional services as an editor. The same proces/mechanism should apply to Editors handling optional services.

**Comment by omahane** [comment]
I was looking at your comment on #17929 and was thinking that this box about required or optional services could be clearer, something like the following:

## Required services
![Screenshot 2024-05-28 at 10 54 04 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/bc7202eb-bd14-4201-801d-f82edd0b504b)

## Optional services
![Screenshot 2024-05-28 at 11 10 14 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/766573/c9dd3f2d-5146-4827-a75e-643cbf306e35)

**Comment by davidmpickett** [comment]
Great edits! I was going to say, "won't it be hard to have the header change?" but then I realized it won't be any harder than changing the sentence that says "This is an optional service." You'll be doing conditional form alters no matter what and this makes it much clearer at a glance.

**Comment by davidmpickett** [comment]
@omahane I went ahead and pointed this at a 3 based on your LOE estimate from #17929. We can still discuss it in a refinement, but it think this is more or less Ready.

**Comment by omahane** [comment]
In reviewing the PR, I found something we'll want to add to the IEF removal work: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18321

**Comment by davidmpickett** [comment]
Confirmed on Staging as a Vet Center editor 

![Screenshot 2024-06-24 at 3 11 02 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/a9dbe0ff-2f98-42f2-9bb7-7ef1aaa1cbb0)

![Screenshot 2024-06-24 at 3 11 27 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/728691a6-a85f-4137-be42-b847bf529bfc)

And as Admin

![Screenshot 2024-06-24 at 3 15 51 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/4a8da604-531c-402a-b02c-92d2bb56c46f)
