### ISSUE TITLE
Cross-product: Remove already created services from the options when adding a new service

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17674]
## Glossary for new people
* **Facility** - a Drupal node for a physical VA location. Might be VAMC, VBA, or Vet Center, in the context of this ticket
* **Service** - a Drupal taxonomy that lists available services as terms. It's a fielded entity that can be used for VAMC, Vet Centers, or VBA facility types. Not all services are available at all facility types.
* **Facility Service** - a content type that acts as a "join" and indicates that a specific Service is available at a specific Facility, with specifics about the physical location, hours, etc. for how that service is provided at the facility.

## Problem Statement
On the Create <facility type> Service content form, Editors first select their facility, then select a Service name from a dropdown, for the type of Service they would like to create for their facility.  (Services map to VA Service taxonomy terms for the Facility type.)

Currently, the "Service name" dropdown displays all Services for the facility type, regardless of whether a Facility Service for that Service+Facility combination has already been created. This means an editor may select a Facility, Service, populate the entire Create Service form (which is time consuming), and then receive a validation error on save saying that the given Facility Service already exists & cannot be saved.

<details><summary>**Example screenshot**</summary>

![Screenshot 2024-08-16 at 1 33 16 PM](https://github.com/user-attachments/assets/e694776e-2f47-465b-bcaa-701c0450c76a)
</details> 

We should only show options in the "Service name" dropdown for Services that do not exist as a Facility Service for the given Facility. 

## Question
Do we need to handle this for [VAMC System Health Service](https://prod.cms.va.gov/node/add/regional_health_care_service_des) as well? That one acts differently, and you don't select a Facillity, you select a VAMC System section. Should it have its own ticket, or does it make sense to roll up into this ticket?

## User story
As an editor, when creating a new Facility Service, I want to choose from Services that are not already in use on a Facility Service for my Facility.

#### Using a hook in the IEF (This is for reference only. Remove before closing ticket.)
As of 2024-03-28 (commit 4e254ffd1492344e12d422e8577609772bdbef95), the inline entity form (IEF) on Vet Centers reduces the options on services by the following code in `va_gov_vet_center/va_gov_vet_center.module`:
```
 /**
   * Implements hook_inline_entity_form_alter().
   */
  function va_gov_vet_center_inline_entity_form_entity_form_alter(&$entity_form, FormStateInterface $form_state) {
    // Disable service name field for existing Vet Center Facility Services.
    $node_id = $entity_form['#entity']->id();
    if ($entity_form['#bundle'] === 'vet_center_facility_health_servi' && isset($node_id)) {
      $entity_form['field_service_name_and_descripti']['#disabled'] = TRUE;
    }
  }
```

We need to be able to do the same when the list of possible services is being shown on the form regardless of IEF. Ideally, this would happen for VAMC, Vet Center and VBA.

- [ ] Refactor code introduced in [VACMS-11367: editors should not rename vet center facility services #12512](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/12512)

#### Using a PHP service
As of 2024-07-24, there's a `hasService` function in `va_gov_vet_center/src/Service/RequiredServices.php`. This is the sort of thing we would like to know for any facility type, again, ideally.

If so, we'd need to create a new service that accounts for the differences in the facility services.

## Acceptance Criteria
- [ ] On create Facility Service forms, the Service Name field list excludes Service options that are already in use on a Facility Service for the selected Facility. 
- [ ] Remove obsolete code introduced in [VACMS-5888: Hide existing VC services from option list to prevent duplicates. #5915](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5915) and [VACMS-4936: Add setter logic to vc ief selects. #5681](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5681).
- [ ] Tested and verified on:
  - [ ] [Vet Center - Facility Service](https://prod.cms.va.gov/node/add/vet_center_facility_health_servi)
  - [ ] [VBA Facility Service](https://prod.cms.va.gov/node/add/vba_facility_service)
  - [ ] ~[VAMC Facility Non-clinical Service](https://prod.cms.va.gov/node/add/vha_facility_nonclinical_service)~
  - [ ] ~[VAMC Facility Health Service](https://prod.cms.va.gov/node/add/health_care_local_health_service)~ now covered in #19075

**Comment by davidmpickett** [comment]
@omahane This is one that we weren't able to get to in refinement this week but is on the list of potential tickets for next sprint. Can you take a look and see if async refinement if feasible?

**Comment by omahane** [comment]
The size of this issue depends on the following:
- whether all three content types in the ACs are using the same method for adding services to a facility
- whether we decide it makes sense to tackle each of these separately
- whether the implementation for adding new services is Views or Entity Browser - Table

**Comment by davidmpickett** [comment]
This doesn't TRULY block #18003. The Allow Only One functionality works correctly for Vet Center Editors when they try to add a duplicate service via Add Content. 
![Services](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/94310deb-2efe-4edc-898a-5570a0a4dde7)

However, in order to replicate the existing functionality of the IEF, this has been included in scope, so makes sense to do before the final step.

**Comment by davidmpickett** [comment]
Removed this as a blocker to #18003 as this is a nice to have and not critical to achieving the functionality

**Comment by davidmpickett** [comment]
@omahane estimate on LOE here?

**Comment by omahane** [comment]
I would like to refine this before estimating. I put that we should consider all facility services when doing this, but we can also just do Vet Center. The effort required would differ.

**Comment by Agile6MSkinner** [comment]
@jilladams will split out VAMC health services into a separate ticket

I will change epics.

**Comment by jilladams** [comment]
Vet Center Facility service: https://prod.cms.va.gov/node/add/vet_center_facility_health_servi
* Service name field is handled so that existing service options won't appear.

VBA Facility service: https://prod.cms.va.gov/node/add/vba_facility_service
* Also handled, uses the same field

 VAMC Facility non-clinical service: https://prod.cms.va.gov/node/add/vha_facility_nonclinical_service
* Uses a different field that lists 3 options for Service. We don't think the juice is worth the squeeze to prevent options from appearing in this list, if the Service has already been created. 

VAMC System health Service: https://prod.cms.va.gov/node/add/regional_health_care_service_des
* Handles things at the System level, not facility level. Would require additional separate lift to handle this. We don't know if this is worth it and would like a product call. @Agile6MSkinner @mmiddaugh

**Comment by jilladams** [comment]
From scrum review with Michael: 
* Vet Center Facility service ✅ ship it
* VBA Facility service: ✅ ship it
* VAMC Facility non-clinical service:  🔴  not doing it, not worth the squeeze
* VAMC System health Service:  🔴  not doing it. If it becomes a priority for System editors later, we'll ticket it then.

**Comment by jilladams** [comment]
Verified in prod.
