### ISSUE TITLE
Dependabot is dependable

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1770]
## Acceptance criteria
- [ ] dependabot is dependable
   - [ ] Prioritize updates in vets-website and security updates
   - [ ] Deprioritize non-security updates

**Comment by acrollet** [comment]
dependabot has been working well since updating composer to v2.
