### ISSUE TITLE
[Epic][AP] Migrate all page layouts

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17701]
## Requirements & Goals
 This epic captures all page layouts that will be necessary to retire Content Build. Our goals are both to retire Content Build and to publish all page types more quickly, and page layout migration will need to be completed for that.

### How will we know we've achieved our goal?
- [ ] All Drupal page types with VA.gov pages have been implemented in Next Build
- [ ] All Drupal page types with VA.gov pages are being published to production by Content Build

### Layouts to migrate
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8644
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8645
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8650
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8651
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14362
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14367
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14366
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14368
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16603
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16622
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16630
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16632
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16633
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16618
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16722
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16758
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16759
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16760
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16761
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16762
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16763
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16764
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16765
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16766
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16768
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16624

### Migration work in some state of completion
Feb 2025: The tickets below were closed in an earlier era, but does NOT reflect that the current state of template build has parity with production content-build or that all these templates are launched to production using Next-build.
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15908
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16290
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8649
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8652
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8653
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16767
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16625
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16629

**Comment by laflannery** [comment]
Closing in favor of the new next-build board
