### ISSUE TITLE
Discovery: Usage Tab

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17714]
## User Story or Problem Statement
As a drupal editor, the usage tab could be helpful for my day to day work, but right now, the usage tab is only available for admin users. 

## Description or Additional Context 
Look into opening up the usage tab to all editors to address the outdated content that goes out to editors. Right now, the usage tab is only available to admin and help desk have to support the editors. There may be opportunity to bring in the knowledge base. 

This could help support the broken links process too. 

## Steps for Implementation
- [x] Evaluate how and where the usage tab could be better use for supporting editors 
- [x] Investigate the risk of opening feature to VA editors
- [x] UX and technical review to ensure the feature is usable and useful for VA editors
- [ ] Using a decision tree, meet with VA CMS product owner to determine path forward. 

## Acceptance Criteria
- [ ] A plan of action on how to open the usage tab to editors. 
- [ ] An understanding of the level of effort to open up the usage tab. 

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18441
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19012
```

**Comment by ian-sears** [comment]
Use case: Editors needing to Archive a node, currently do not have a Broken Links mitigation tool.
IF an Editor can be KB instructed to first remove Inbound links, less long-tail broken links are needed.

**Comment by MDomngz** [comment]
[Drupal's background on the Usage Report tab - ](https://www.drupal.org/project/usage_report)

**Comment by gracekretschmer-metrostar** [comment]
Before implementation, @MDomngz wants to better understand the use case,

**Comment by EWashb** [comment]
I have spoken with @RLHecht regarding this functionality and she is interested in getting the usage tab opened up to more people on her CAIA teams. This has been very helpful to her at an admin level, but it would be the most helpful if the editors in her team could access it as well. They use it to fix links. Can we bring this into refinement next time @gracekretschmer-metrostar ?

**Comment by gracekretschmer-metrostar** [comment]
Tim's feedback: It would be a trivial change to give access to the Usage tab to whichever roles we want. We just need to know which ones. 

I think it would be a balance between people needing the information vs being confused by it, i.e. VAMC editors may not need/want it.

**Comment by RLHecht** [comment]
Thanks @gracekretschmer-metrostar For CAIA content editors, this tab would be really useful in avoiding broken links when we set up redirects. While we do content searches to find pages we may need to update, being able to find each page a specific link is on will make it much easier and more thorough.

**Comment by gracekretschmer-metrostar** [comment]
The specific use case that really needs it is for CAIA team. The challenge right now is that only admin users can have access to the usage tab.

**Comment by EWashb** [comment]
@skirkman16 so it sounds like this would be easy enough to not just limit to our CAIA editors?

**Comment by skirkman16** [comment]
@EWashb Correct. Technically we could find a way to limit this to CAIA Editors but it would require custom code. Worst thing that could happen is there is no behavior change and Editors don't use the usage tab, so to me there is only a positive benefit. We would provide some education on the usage tab to encourage Editors to refer to it when archiving.

**Comment by EWashb** [comment]
@gracekretschmer-metrostar see Randi's comment above

**Comment by skirkman16** [comment]
[Mural link with user flow](https://depo-platform-documentation.scrollhelp.site/)
