### ISSUE TITLE
Remove simplesamlphp salt and admin password from va.gov-cms and changes values

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#17774]
The VA.gov-cms repo contains secrets related to simplesamlphp functionality. These secrets need to have their values cycled, and a secure mechanism put in place to source the secrets for use.

Salt: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/simplesamlphp-config-metadata/config/config.php#L191
Simplesamlphp admin password: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/simplesamlphp-config-metadata/config/config.php#L199

### Tasks:
- [x] #17783
- [x] Copy params in PHP env variables using BRD build/deploy processes
- [x] read env variables form values in `simplesamlphp-config-metadata/config/config.php`
- [x] Test on test infrastructure
- [x] Deploy to regular infrastructure
- [x] Rotate the secret immediately, by ensuring that the secret can no longer be used
