### ISSUE TITLE
Platform CMS Sprint Plan 08 (4/11/2024 - 4/24/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17771]
### 2024 Vision Roadmap
- [Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710770110435/815417c164d347d6720309063a146709685712f5?sender=u68176db99729f92d17379835)

### Sprint 08 Capacity
All Eng: 
All UX: 
All Support: 
All CMS Team:

### Sprint 08 Goals & Priorities

**SPRINT 08 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17648
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17813

### SPRINT 08 PRIORITIES
Priorities are listed from highest priority to lowest priority, starting at the top of the list. 

**Onboarding New CMS Team**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17527

**Onboarding of Accelerated Publishing Team (Epic [#17506](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17506))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17461
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17507
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17679
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17849

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17604
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15136
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17648
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17718

**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17563
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17442
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17813

**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136

**DevOps Discovery**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17387
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17774

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17316
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646
 
**Dependencies / Dependabot PRs ([#17456] (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17456))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17100
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17101
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17102

**Team Norms and Charter**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17565

**Drupal Maintenance**
- [ ] https://github.com/orgs/department-of-veterans-affairs/projects/1194/views/1?pane=issue&itemId=54015742
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15663

### Stretch Goals (only work on after completing your pre-defined sprint work)
- [ ] 

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825
- [ ] ^^^ notes, CMS will likely need to support for sprint 9, should start thinking about who needs to get pulled in
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17845

### SPRINT 08 UNPLANNED WORK (Post Sprint Planning)
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17838
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/1624
