### ISSUE TITLE
Upgrade to Tugboat v2.24.8

### ISSUE THREAD

**Issue by rabbitlair** [department-of-veterans-affairs/va.gov-cms#17770]
## Tasks:

- [x] Change directories to the Tugboat root: `cd /opt/tugboat`
- [x] Fetch the latest tags: `git fetch --tags`
- [x] Checkout the tag (e.g. `git checkout v2.24.8`)
- [x] Build: `make && make install`
- [x] Restart Tugboat: `tbctl restart`
- [x] Wait for Tugboat to start up successfully: 
```
wget --quiet -O- --tries=100 --retry-on-http-error=404,502,503 --retry-connrefused https://[tugboat-dashboard-host]/_status
```

## Team

Please check the team(s) that will do this work.

- [x] `CMS Team`
- [ ] `Public Websites`
- [ ] `Facilities`
- [ ] `User support`

#### v2.24.8 - 02 April, 2024

```
* #5516 fix: replace non-latin1 characters with a `?`  (#5524)
* #4935 fix: log a warning for not found routes on webhooks service (#5515)
```

#### v2.24.7 - 25 March, 2024

```
* #5442 fix: encode special characters in agent proxy response headers (#5509)
* chore: bump chokidar from 3.5.3 to 3.6.0 (#5487)
* chore: bump eslint from 8.56.0 to 8.57.0 (#5486)
* chore: bump follow-redirects from 1.15.5 to 1.15.6 (#5483)
* chore: bump mongoose from 6.12.6 to 6.12.7 (#5488)
* chore: bump socket.io from 4.7.4 to 4.7.5 (#5485)
```

#### v2.24.6 - 14 March, 2024

```
* #4965 fix: reattempt to start a locked preview during /container/start failures (#5466)
* #5065 test: add regenerating visualdiff e2e tests (#5436)
* #5420 refactor: replace remaining fast-proxy proxying with @fastify/reply-all (#5462)
```

#### v2.24.5 - 12 March, 2024

```
* #3838 feat: show creator of a preview (#5423)
* #5029 fix: proxy websocket requests with fastify/http-proxy (#5415)
* #4762 fix: recreate missing container on start and suspend (#5443)
* #5428 fix: fix uncaught exception on screenshot update (#5439)
* #5275 fix: pass a state to gitlab commit pipeline status api call for all refs (#5437)
* #5463 fix: pass after option to rebuildVisualdiff handler  (#5464)
* #5468 fix: patch ZFS for compiling on arm64 locally (#5469)
* fix: prefix port 80 websocket traffic(#5474)
* chore: bump fastify from 4.24.3 to 4.26.2 (#5460)
* chore: bump socket.io-client from 4.7.2 to 4.7.4 (#5400)
* chore: bump moment from 2.29.4 to 2.30.1 (#5402)
* chore: bump undici from 5.28.2 to 5.28.3 (#5426)
* chore: bump ip from 1.1.8 to 1.1.9 (#5429)
* chore: bump mailparser from 3.6.5 to 3.6.9 (#5456)
* chore: bump moment-timezone from 0.5.44 to 0.5.45 (#5403)
```

**Comment by 7hunderbird** [comment]
Starting upgrade.

**Comment by 7hunderbird** [comment]
Done with upgrade.

```
$ tbctl status

Checking Tugboat...

  Network: tugboat                                                      [  OK  ]
  Service: agent                                                        [  OK  ]
  Service: apache                                                       [  OK  ]
  Service: api                                                          [  OK  ]
  Service: logs                                                         [  OK  ]
  Service: mail                                                         [  OK  ]
  Service: mongo                                                        [  OK  ]
  Service: proxy                                                        [  OK  ]
  Service: puppeteer                                                    [  OK  ]
  Service: redis                                                        [  OK  ]
  Service: registry                                                     [  OK  ]
  Service: scheduler                                                    [  OK  ]
  Service: server                                                       [  OK  ]
  Service: traefik                                                      [  OK  ]
  Service: ui                                                           [  OK  ]
  Service: webhooks                                                     [  OK  ]
  
$ tbctl -V
2.24.8
```
