### ISSUE TITLE
Change management for Vet Center IEF / allow only one changes

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#17840]
Behavior of the Vet Centers services selection is going to change. 
We need to do change management with/for editors. 

## Tasks 
- [ ] Prepare timeline for delivery and comms
- Relevant KB articles: draft edits
  - [x] Definitely [How to add, edit or remove a Vet Center service](https://prod.cms.va.gov/help/vet-centers/how-to-edit-a-vet-center-service) 
  - [x] Maybe the Add services section of [Create a new Vet Center page](https://prod.cms.va.gov/help/vet-centers/create-a-new-vet-center-page#add-services)
  - [x] Maybe [Vet Center content review](https://prod.cms.va.gov/help/vet-centers/vet-center-content-review)
- Materials we may need to provide to Vet Centers for awareness, besides KB?
  - [x] Email message to VC editors about change to method for editing/creating services
  - [ ] Email outreach to editors with services in draft so that the FE work does not impact services that they want displayed
- [x] Notify CMS helpdesk of the change, and invite them to attend Vet Center office hours when we present
- Vet Center office hours handling
  - [x] Advertise in advance that there is a change to improve attendance
  - [x] Present in office hours
- [x] 8/15 After #18003 successfully deploy, publish KB article draft revisions. 
  - [x] https://prod.cms.va.gov/node/23222/revisions
  - [x] https://prod.cms.va.gov/node/65338/revisions
  - [x] https://prod.cms.va.gov/node/61424/revisions

**Comment by davidmpickett** [comment]
Added links to related KB articles and moving to Next Refinement column

**Comment by davidmpickett** [comment]
@Agile6MSkinner Would it be helpful for me to draft the KB article revisions? Not sure what your level of familiarity is with that part of Drupal yet. Happy to sync and show you around as well.

**Comment by davidmpickett** [comment]
Draft versions of updated KBs have been saved on Prod and sent to @Agile6MSkinner and @mmiddaugh [in slack](https://dsva.slack.com/archives/C0FQSS30V/p1721924764735299) for review
- https://prod.cms.va.gov/node/23222/latest
- https://prod.cms.va.gov/node/65338/latest
- https://prod.cms.va.gov/node/61424/latest

I'm gonna let Michael use it as a learning opportunity to log in to Drupal & Publish when deemed ready (and/or make additional small tweaks to drafts)

**Comment by Agile6MSkinner** [comment]
@davidmpickett @dsasser Can either of you explain this item or tell me who might be able to?

"Call out the Draft services as an important factor to check BECAUSE right now Draft services show up on the FE and after this they won't so editors might have services vanish."

**Comment by davidmpickett** [comment]
> @davidmpickett @dsasser Can either of you explain this item or tell me who might be able to?
> 
> "Call out the Draft services as an important factor to check BECAUSE right now Draft services show up on the FE and after this they won't so editors might have services vanish."

Right now, Vet Center services will display on a Vet Center regardless of editorial workflow status. So Draft, In Review, Approved, Published, and Archived are all currently displayed on the FE.

There are for instance [32 Vet Center services currently in Draft](https://prod.cms.va.gov/admin/content?title=&type=vet_center_facility_health_servi&moderation_state=draft&owner=All)

Vet Center editors have not necessarily had to pay close attention to the Workflow State of their services, because they all show up on Front End. Once we do this [follow up FE ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16362) that will change.

**Comment by davidmpickett** [comment]
There will be some gap between the CMS changes that remove IEF and the FE changes that prevent draft services from displaying on FE. Just need to make sure the timing of the tickets and comms to Vet Center editors is intentional about this

**Comment by Agile6MSkinner** [comment]
- @Agile6MSkinner to draft email communication on Services change of process.
- @mmiddaugh to draft email to editors with services in "draft"
- Announce in Teams that there will be a change presented at next office hours 
- Publish KBs at time of shipping

Target date Aug 15

**Comment by jilladams** [comment]
Got the email into Helpdesk hands for sending (finally): https://dsva.slack.com/archives/C02730UEZPS/p1723588809735889

Michelle and Michael were cc'ed on the handoff email. Ian will do a test send to me to verify.

**Comment by jilladams** [comment]
Email was sent yesterday. #18003 PR is merged and will ship tomorrow. 

KB article drafts will need to be published after we verify in prod.
