### ISSUE TITLE
cms-notifications channel audit

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17853]
## User Story or Problem Statement
As a member of the CMS team, I want to know what each notification that is sent to the CMS notification channel means. 

## Description or Additional Context 
The error log and notifications being pushed to the cms-notifications channel within Slack. 

## Steps for Implementation
- An audit of the cms-notifications channel. 
- When possible, a definition of what the notification means and if that is not possible, identification that the notification still needs research and possible removal from the channel. 
- When possible, fix errors that are triggering the notification getting pushed to the cms-notifications channel.

## Acceptance Criteria
- [ ] A list of errors and notifications getting sent to the cms-notifications channel. 
- [ ] A comprehensive understanding of notifications getting pushed to the cms-notifications channel within Slack. 
- [ ] A list of notifications flagged that could be removed from the channel.

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17839
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17881
```

**Comment by anantais** [comment]
Currently two tickets created, as well as a confluence page to document errors and decide if they warrant tickets. https://vfs.atlassian.net/wiki/spaces/PCMS/pages/3092054060/CMS-Notifications+channel+audit

I decided that one of the errors related to GraphQL is intermittent and may not need a ticket unless it keeps happening. There are currently two other tickets that may or may not need tickets in the future.

**Comment by smarithaponnala** [comment]
Closing as this hasnt been updated in 4 month
