### ISSUE TITLE
[Events v2] Create an API mirroring and expanding upon what is currently in Drupal

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#17871]
## Background

@FranECross TBD description, etc.

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

**Comment by FranECross** [comment]
@FranECross Find any past research, content models or mural boards.

**Comment by FranECross** [comment]
@dsasser Since this is a Super-Epic, would it be appropriate for me to create three regular Epics for: 
- Create an API for Events to mirror what's currently in Drupal and accommodate lat/long, etc.
- Create a Content Model for Events v2
- Create endpoints for Events v2

Separate from this endeavor is getting all facility types to be selectable. I'll create an Epic for that, and will find out which aren't yet selectable, and we can create stories for that. 

Do you prefer a meeting where you can talk through which stories are needed and I can create them during the meeting, or do you prefer to mull and create the stories yourself? Either works for me.

**Comment by davidmpickett** [comment]
Some relevant Facilities events epics you may want to cross reference/list under here
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17665
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12926

**Comment by mmiddaugh** [comment]
**Update 6.7.24**

- Data model in progress
- Will need to implement lat/long forward lookup to support editor selection of non-VA event locations and "events near me" functionality

**Comment by mmiddaugh** [comment]
**Update 8.8.24**
No update

**Comment by mmiddaugh** [comment]
**Update 9.3.2024**
This is on hold pending conversations with VEO
