### ISSUE TITLE
DRAFT Sprint 3 Plan - Facilities

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#17895]
## Schedule Notes
Sprint 3 = 5/1 - 5/14
- Michelle OOO Wed 4/24-Fri 5/3
- Christian: OOO Drupalcon, week of 5/6
- Eli OOO: Th 5/9
- OCTO offsite: 5/8-5/9 + travel days (5/7, 5/10) for DaveC, Michelle, Amanda

FYSA: DaveC PTO this week; Chris Kim on leave for May; Josh Mills backfill

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?

* WHOLE TEAM:
  * #16825
* UX: 
    * #17891
* FE: 
  * ~~#17855~~ 
* Drupal: 
  * #17929

#  CY Q2 Priorities

<details><summary>Numbered list </summary>

1. department-of-veterans-affairs/va.gov-cms#17653
2. department-of-veterans-affairs/va.gov-cms#17722
3. department-of-veterans-affairs/va-iir/issues/553
4. department-of-veterans-affairs/va.gov-cms#14507
   4a. department-of-veterans-affairs/va.gov-cms#15344
   4b. department-of-veterans-affairs/va.gov-cms#12907
5. department-of-veterans-affairs/va.gov-cms#16825
6. #10514 
   6b. department-of-veterans-affairs/va.gov-cms#16268 
7. department-of-veterans-affairs/va.gov-cms#15037
8. department-of-veterans-affairs/va.gov-cms#14225
9. department-of-veterans-affairs/va.gov-cms#17655
10. department-of-veterans-affairs/va.gov-cms#17708
    10b. department-of-veterans-affairs/va.gov-cms#7818
11. department-of-veterans-affairs/va.gov-cms#17661
12. Removed
13. department-of-veterans-affairs/va.gov-cms#12923
14. department-of-veterans-affairs/va.gov-cms#14477
15. Removed
16. department-of-veterans-affairs/va.gov-cms#12942
17. department-of-veterans-affairs/va.gov-cms#14327
18. department-of-veterans-affairs/va.gov-cms#15541
19. Removed
20. department-of-veterans-affairs/va.gov-cms#17350 
</details>

## Non-quarterly prio injections
- FE department-of-veterans-affairs/va.gov-cms#17547 -- Outreach to PPMS starting week of 4/29
- FE department-of-veterans-affairs/va.gov-cms#15664
- FE #17904 

## 2) va-icon adoption - end of May deadline - department-of-veterans-affairs/va.gov-cms#17722
- FE department-of-veterans-affairs/va.gov-cms#17855 - 5 pts
- FE #17874
- FE #17884
- FE #17886 
- FE #15598 
- FE #17887  
- FE #16952
- FE #17892  

## 3) Security / PII issue (IIR) - https://github.com/department-of-veterans-affairs/va-iir/issues/553
- FE - May need some capacity to review work done by IIR

## 4) Lighthouse v1 (IIR) - department-of-veterans-affairs/va.gov-cms#14507
- FE - May need some capacity to review work done by IIR
  - Draft PR: https://github.com/department-of-veterans-affairs/vets-api/pull/16463

## 5) VBA/VAMC Service Location enhancements - department-of-veterans-affairs/va.gov-cms#16825?

- S2 injection rolling over - Drupal #17956
- Product capacity for inter-team coordination on #16825

### Not Launch Blocking
- FE #17514

## 6) VBA Staging review blockers - department-of-veterans-affairs/va.gov-cms#16268
- S2 roll over - FE #15223
- S2 roll over - FE #17598
- FE department-of-veterans-affairs/va.gov-cms#17566 

### 6b) VBA Pilot MVP: other launch-related - #10514
- FE department-of-veterans-affairs/va.gov-cms#17601

## 8) Facility Locator iteration: Provider core training / PPMS data - #14225
- FE #15823 

## 9) Adopt V1 & V3 components to replace custom code implementations department-of-veterans-affairs/va.gov-cms#17655
- S2 roll over #16148

## 10) Vet Centers remove IEF - department-of-veterans-affairs/va.gov-cms#17708
- Drupal #17929

## 11) Initiative - Vet Center design 2.0 #17661 
Child epic: Veterans can distinguish Vet Centers from VA medical facilities #17893
- UX #17891 -- double check state of refinement and points here

## 18) Facility Locator: "Service type" field iterations #15541
- ~~UX #17835~~ Jordan capacity tradeoff

## 20) Improve services accordions & locations across products - department-of-veterans-affairs/va.gov-cms#17350
- FE department-of-veterans-affairs/va.gov-cms#17415 

# Other Work (Not Q2 Prioritized)
- department-of-veterans-affairs/va.gov-cms#17848 
- https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17762 - Design assessment of the env Randi will stand up - might be an opportunity to have Carissa shadow some of Jordan's work and gain familiarity with portfolio? 

# Sprint 4 Holding spot
- Drupal #17137 
- UX department-of-veterans-affairs/va.gov-cms#17806 

# Priority updates
## 7) Link to Health chat from VAMC pages - #15037 
Paused due to VHA DM communications planning.

**Comment by jilladams** [comment]
* Updated PTO from cal as of today
* Added Sprint 3 tickets to epic
* Updated list of initiatives / tentative tickets in sprint, based on top-down Q2 prios + injections

## TO DO prior to planning: 
- [ ] Remove Sprint 2 tickets that have closed
- [ ] Cross walk Ready column for any high priority items that get refined and are not included
- [ ] Double check load: 
     - [ ]  [Proposed FE load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzODU5Nw&labels=va.gov%20frontend)
     - [ ] [Proposed Drupal load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzODU5Nw&labels=drupal%20engineering)
     - [ ] [Proposed UX load](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10514#workspaces/sitewide-facilities-639f5253e4b702a32376339e/board?epics=Z2lkOi8vcmFwdG9yL0VwaWMvMTEzODU5Nw&labels=ux)
- [ ] Review with Michelle
    - [ ] Update changes from review

**Comment by jilladams** [comment]
Note to selves: @laflannery is scheduled for a Service Locations demo to VAMC editors on 5/8. We need to flag if that will not work, at the beginning of this sprint.

**Comment by mmiddaugh** [comment]
@jilladams @davidmpickett 
Under Non-quarterly prio injections, I see the suggestion to do #17646 and #17649 before #17547 but I'd suggest starting with a query to confirm if the provider is in the data set rec'd in response. This would allow us to give feedback to the PPMS team if that's the issue. I've located the provider on a completely separate map and then zoomed into the same area on the FL and the provider is not in the results list. I'm not sure pagination is in play here.

**Comment by davidmpickett** [comment]
> @jilladams @davidmpickett Under Non-quarterly prio injections, I see the suggestion to do #17646 and #17649 before #17547 but I'd suggest starting with a query to confirm if the provider is in the data set rec'd in response. This would allow us to give feedback to the PPMS team if that's the issue. I've located the provider on a completely separate map and then zoomed into the same area on the FL and the provider is not in the results list. I'm not sure pagination is in play here.

I confirmed that this is not pagination related. Pulled 17547 up to discuss at top of Team Refinement tomorrow

**Comment by davidmpickett** [comment]
@jilladams to confirm what I think you said in demo today. 2) **va-icon adoption** is partially blocked by DST, so we should prioritize FE tickets from **9) Adopt V1 & V3 components** instead?

**Comment by davidmpickett** [comment]
@jilladams Also I just updated the ticket body to include tickets that seem likely to roll over from S2 given current state

**Comment by jilladams** [comment]
From planning: 
* We will hold on DS icon work until the alignment / padding work is fixed on the component. Main idea here is that it's not worth double review if we do the work now and merge to an integration branch that must be checked again when we merge. 
* Noting: With DS deadline changes, we may want to review our priorities in order to help plan next few sprints. @jilladams or @davidmpickett to bring this to product sync.
