### ISSUE TITLE
Create "Recurring Security Epic" template

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#1790]
Goal: Sprint goal = Have an epic that all security work is logged against each sprint. 

AC:
- [ ] Assigned to current sprint
- [ ] Assigned to Clarence to start with so he can delegate accordingly
- [ ] Develop template with language around the process
  - [ ] Checkboxes on it... 
- [ ] Link to the Security Alerts page https://github.com/department-of-veterans-affairs/va.gov-cms/network/alerts
- [ ] When: First day of Sprint/Monday morning

**Comment by acrollet** [comment]
ACs moved to #1791
