### ISSUE TITLE
Platform CMS Sprint Plan 09 (4/25/2024 - 5/8/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#17926]
### 2024 Vision Roadmap
- [Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710770110435/815417c164d347d6720309063a146709685712f5?sender=u68176db99729f92d17379835)

### Sprint 09 Capacity
Accessibility: 50%
Drupal Engineering: 75%

### Sprint 09 Goals & Priorities

**SPRINT 09 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17604

### SPRINT 09 PRIORITIES
Priorities are listed from highest priority to lowest priority, starting at the top of the list. 

**Onboarding New CMS Team**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17527

**Onboarding of Accelerated Publishing Team (Epic [#17506](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17506))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17461
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17679
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17849
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17938

**PDF Deletion and Retention ([#15958](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15958))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17604
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15136
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17718
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17939

**Tech Debt**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17889
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17881
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17872
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17936

**Collab Cycle ([#14013](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14013)) / CMS Governance ([#14012](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14012))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17563
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17442
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17941
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17942

**Knowledge Base Enhancements (Epic [#14069](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14069))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17940
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17909
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17943

**BRD**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17387

**CMS Notifications Audit (Epic [17853] (https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17853))**
- [ ] 

**ATO Documentation ([#15646](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17316
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15646
 
**Team Norms and Charter**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17565

### Stretch Goals (only work on after completing your pre-defined sprint work)
- [ ] 

### Help Team, Partners, Clients and Stakeholders Hit Objectives
**Facilities**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16825

### SPRINT 09 UNPLANNED WORK (Post Sprint Planning)
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18022
- [ ] https://github.com/department-of-veterans-affairs/content-build/pull/2069
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18080
