### ISSUE TITLE
<Summary of enhancement>

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#17956]
## User Story or Problem Statement

As an Editor,
I would like Virtual support information to be added to the Facilities API v1
so that Veterans could search for virtual support options in the Facility Locator.

## Acceptance Criteria
- [ ] Virtual support data is correctly coded in the services data push to Lighthouse (LH)
- [ ] LH confirms that they received and can ingest the new field

## Implementation steps
Update the `va_gov_post_api/src/Service/PostFacilityServiceVamc.php` service to include "Virtual support"

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by omahane** [comment]
I'm trying to determine the work necessary to get this closed by asking [Adam at Lighthouse](https://dsva.slack.com/archives/C02BTJTDFTN/p1714393251052789).

**Comment by davidmpickett** [comment]
@omahane Is there anything we can do to verify this is working as intended on the SL tugboat? Or will this need to wait until launch day for final verification?

Put another way. Is there anything else to do before launch?

**Comment by omahane** [comment]
This is done for now. [Someone in Lighthouse will be making a ticket](https://dsva.slack.com/archives/C02BTJTDFTN/p1714587648663199?thread_ts=1714393251.052789&cid=C02BTJTDFTN) to allow for processing the `virtual_support` field, but that will not be happening immediately. As a result, we may end of needing to do a force push of all services at some point when that functionality is added to Lighthouse.
