### ISSUE TITLE
My Education Benefits: Edu Non-Chapter 33 Benefit Updates

### ISSUE THREAD

**Issue by alexander-ferzola** [department-of-veterans-affairs/va.gov-cms#17960]
## Background
The Digital GI Bill team (Partnership of VA Education + Accenture Federal Services) is gearing up for a Release 7 deployment (December 2024) which includes updates to 2 existing benefit application forms (22-1990 and 22-5490) as well as the long-awaited "How to Apply Wizard." Additional details for each of those efforts are included below:

**1. The Case for Updating the 22-1990**
Today, the Chapter30/Chapter1606 education benefits exist on a separate form from the Chapter 33 Post-9/11 GI Bill application form. This is not aligned with the paper 22-1990 (which has all three forms on the same application). Ch33 was split from the 1990 as part of our MVP approach to automating application decisions and improving the overall user experience for the Ch33 prospective applicants. We are now at a point, where we would like to re-incorporate Ch30 + Ch1606 back into the authenticated online 22-1990 and offer those prospective applicants the same streamlined experience as Ch33 enjoy now.

Informed by user research conducted through the collaboration cycle and your input in 2021, EDU Product Owners have consensus on a revamped flow that keeps the future 22-1990 "lean," asking only the questions necessary for processing and have identified places where information can be pre-populated for the Vet. While we're not entirely sure the full scope of our updates, we believe we can remain adherent to the Va.Gov Design System and will not need to introduce any new tools.

**2. The Case for Updating the 22-5490**
Today, the 22-5490 education application - which includes Chapter 35 and the Fry Scholarship options - exists as an online application with a sub-optimal authenticated experience + a paper form version. As part of our larger effort to improve and standardize the education applications offered to Veterans and their family members, we plan to update the authenticated online flow for 22-5490 to include features present on My Education Benefits products today (pre-filled information, streamlined questioning, and automation elements).

Informed by user research conducted through the collaboration cycle and your input in 2021, EDU Product Owners have consensus on a revamped flow that keeps the future 22-5490 "lean," asking only the questions necessary for processing and have identified places where information can be pre-populated for the dependent. While we're not entirely sure the full scope of our updates, we believe we can remain adherent to the Va.Gov Design System and will not need to introduce any new tools.

**3. The Case for Updating the How to Apply Wizard**
While there are many potential entry points to education application forms (i.e. Google, Find a Form tool, the eligibility page within the edu hub) - We are specifically looking to improve the "How to Apply" wizard which has been well-documented as a pain point in the Veteran education journey.

At this time, EDU Product Owners have consensus on a new 'tool' that would live as a component on existing How to Apply and Eligibility pages. While we're not entirely sure the full scope of our updates, we believe it will impact the look and feel of those pages on Va.Gov and likely introduce a new-ish tool to the design system.

### User Story or Problem Statement

For application updates, how might we improve the self-entitled Veteran application experience for a faster, easier, and more accessible application workflow?

For the how to apply updates, how might we improve the Veteran and Veteran family member experience for more easily finding the correct education application they should apply for and starting that application faster?

### Affected users and stakeholders

Having trouble finding the research repo, but we've done research on these updates multiple times. A few links:

Collaboration Kickoff, Design Intent, Midpoint Reviews, Content team requests for 22-5490 updates
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41556
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41556
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41090
https://github.com/department-of-veterans-affairs/va.gov-team/issues/41338

How to Apply entry points - Content team request, et. al.
https://github.com/department-of-veterans-affairs/va.gov-team/issues/38853

### Hypothesis

Given the successful in-take of Veteran applications for My Education Benefits Post-9/11 GI Bill Application metrics and qualitative feedback to date, we believe that our MEB updates will achieve an overall improvement in the Veteran and Veteran family members' quality of life. We will measure QoL and process improvement using sentiment & analytics metrics post-deployment. 

## Assumptions
* Va.Gov Information Architecture remains relatively stable over the next 8 months. 

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, use the [Change Management Runbook](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/change-management) to create a CM epic and associated tickets.

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [X] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [X] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [X] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [X] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [X] `Approachable`: Offer friendly guidance over authoritative instruction.
- [X] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>
