### ISSUE TITLE
[Epic] Deliver Drupal Events Data as JSON file to OPIA Team

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18001]
## User Story or Problem Statement
OPIA team needs Drupal event data delivered to their team for their team do to discovery work on the events data. 

## Description or Additional Context
Noelle Sweeney and Timothy Hudock from the OPIA Team are requesting drupal events data to help support their solution to centralize VA events. 

Per Noelle, they need:
_If this is a manually transferred JSON for the short term, we can definitely receive that while discussing more sustainable solutions.

When I spoke with Tim Cosgrove, we discussed some of the fields that we would want to retrieve from the query:_

<img width="455" alt="image" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/156952452/ad0ab17b-fdce-463c-bdef-f62422fcd6b4">

_These are also listed in the data connection request form.

Additionally, here is the documentation on the types of data connections that Foundry supports: https://www.palantir.com/docs/foundry/data-integration/source-type-overview/_

## Steps for Implementation

- [x] Construct a REST API query that gives them the data they've asked for; data to be added here
- [x] Write a script that pulls all the data
- [x] The data is paged, so the script will need to go through each page and consolidate the data.
- [x] Data provided to the team as single large JSON file.
- [x] An explainer on how to interpret the event data. 

### Potential follow-ups after the team digests the data:

- [ ] adjustments to what data is and isn't included, and script run again and new data provided to them
- [ ] discussions of an ongoing daily delivery. 

## Acceptance Criteria
- [x] A query is created to extract the data needed for the OPIA team 
- [x] Event data is delivered to the OPIA team in a format that is needed 
- [x] A quick explainer is created for the OPIA team to use to understand the events data

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18064
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18194
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18309
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18357
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18352
```

**Comment by gracekretschmer-metrostar** [comment]
Tim: I think they want a one time JSON file. We tried to set them up with access to regular Drupal API (using also for Next Build). Granting them access was difficult for governance reasons, which is why we are now leaning toward GraphQL. At this stage, they want a one time dump of existing events. 

Erika: OPIA contract team, Palantir. They are the team that does the marketing of the team. What we need is an estimation of effort to get that data and steps to do it.

**Comment by gracekretschmer-metrostar** [comment]
Longer term: we should look at the security concerns to see if we can resolve to have a more sustainable solution.

**Comment by gracekretschmer-metrostar** [comment]
Future state: wait until Next Build is in production to move forward.

**Comment by gracekretschmer-metrostar** [comment]
For reference for the team: https://www.va.gov/outreach-and-events/events/

**Comment by gracekretschmer-metrostar** [comment]
Next steps: clean up and getting future state ticket in the backlog. Amanda will own creating the query and script for deliver data. TBD on who will own the data explainer.

**Comment by anantais** [comment]
Currently working on a solution that provides this data using Views on the backend.

I was troubleshooting adding to the vets-api module vs building a new module when I came across this solution that seems to be a newer ability that Drupal 10 has.

Using this method I can restrict the data output to certain roles in Drupal as well as provide csv or xml format if needed (in addition to a json feed). I am currently making sure the feed provides all the data we need and looks good.

**Comment by anantais** [comment]
@gracekretschmer-metrostar I did just realize something about this ticket. Who should I be giving access to? And is this something I can create a role for? Using Drupal is very efficient but I am not sure what the procedure is for controlling access. This is the first ticket I have really worked on where I have to consider access.

**Comment by gracekretschmer-metrostar** [comment]
Feedback from @EWashb: As a side note- this is worth keeping in mind as we explore the long-term solution for events data for Noelle and the Palantir team. We will likely need to hand that off to the Sitewide team after that MVP file.

**Comment by gracekretschmer-metrostar** [comment]
Demo of MVP feature here: https://drive.google.com/file/d/1TzmQjUvHXUfyrmrnpBi0iImNemDk2sF7/view?usp=sharing

**Comment by jilladams** [comment]
Added Public Websites so our team can find this work in our sprint board, after it transitions to us.

**Comment by gracekretschmer-metrostar** [comment]
@gracekretschmer-metrostar met with OPIA team (Dan and Noelle) on 6/18 and this was their feedback for ideal state:
- A centralized location for PAOs to be able to see all the VA events from the national calendar and their event details happening so that they can better support comms around the events. 
- An events data API that their system can have a continuous pull of data.

**Comment by gracekretschmer-metrostar** [comment]
@EWashb do you think we can close this ticket or do you want to hold off until you've spoken to the OPIA team? It's been sitting in limbo because we are unsure how to hand it over to sitewide.

**Comment by EWashb** [comment]
@gracekretschmer-metrostar i think we can close. You can also feel free to make a recurring ticket within the sprint for transmitting  the file in the meantime. I meet with their PO on 7/8
