### ISSUE TITLE
DRAFT Facilities Sprint 4 plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#18036]
## Schedule Notes
Sprint 4 = 5/15 - 5/30
* Jordan OOO 5/28-6/5

## Sprint Priorities 🎯 
At the end of this sprint, what do we want to have accomplished/delivered?
* UX: #18100 
* FE: LH V0 anything (then PPMS pagination if no LH, or icons)
* Drupal: #18108 -- needs refined

#  CY Q2 Priorities

<details><summary>Numbered list </summary>

1. department-of-veterans-affairs/va.gov-cms#17653
2. department-of-veterans-affairs/va.gov-cms#17722
3. department-of-veterans-affairs/va-iir/issues/553
4. department-of-veterans-affairs/va.gov-cms#14507
   4a. department-of-veterans-affairs/va.gov-cms#15344
   4b. department-of-veterans-affairs/va.gov-cms#12907
5. department-of-veterans-affairs/va.gov-cms#16825
6. #10514 
   6b. department-of-veterans-affairs/va.gov-cms#16268 
7. department-of-veterans-affairs/va.gov-cms#15037
8. department-of-veterans-affairs/va.gov-cms#14225
9. department-of-veterans-affairs/va.gov-cms#17655
10. department-of-veterans-affairs/va.gov-cms#17708
    10b. department-of-veterans-affairs/va.gov-cms#7818
11. department-of-veterans-affairs/va.gov-cms#17661
12. Removed
13. department-of-veterans-affairs/va.gov-cms#12923
14. department-of-veterans-affairs/va.gov-cms#14477
15. Removed
16. department-of-veterans-affairs/va.gov-cms#12942
17. department-of-veterans-affairs/va.gov-cms#14327
18. department-of-veterans-affairs/va.gov-cms#15541
19. Removed
20. department-of-veterans-affairs/va.gov-cms#17350 
</details>

## Non-quarterly prio injections
- FE: #17646 - can we make headway on this without API connection to PPMS from dev box?
- FE: #17649 

## 2) Typography audit - June 5
- #18100

## 3) Security / PII issue (IIR) - https://github.com/department-of-veterans-affairs/va-iir/issues/553
- Wed 5/15 meeting scheduled to close loop with IIR re: whether more work is needed or not.

## 4) Lighthouse v1 before v0 deprecation **June 1** - department-of-veterans-affairs/va.gov-cms#14507
- **June 1 deadline** Vets-api work complete, shipped, notified.
* Drupal: #18108 -- needs refined
- FE changes will be ready for review / testing during Sprint 5. (finishing #18014 )
  - Jill owes regression test plan for Eli review
- FE: #12909 - we need to know with confidence if we owe any work on this
- FE: #12908 - we need to know with confidence if we owe any work on this

## 2) va-icon adoption - **June 19** deadline - department-of-veterans-affairs/va.gov-cms#17722
- FE department-of-veterans-affairs/va.gov-cms#17855 - 5 pts
- FE #17874
- FE #17884
- FE #17886 
- FE #15598 
- FE #17887  
- FE #16952
- FE #17892  

## 6) VBA Staging review blockers - department-of-veterans-affairs/va.gov-cms#16268
- FE department-of-veterans-affairs/va.gov-cms#17566 

## 9) Adopt V1 & V3 components to replace custom code implementations department-of-veterans-affairs/va.gov-cms#17655
- FE: #18103
- Public Websites FE contributing.

## 10) Vet Centers remove IEF - department-of-veterans-affairs/va.gov-cms#17708
- Drupal #17929

## 11) Initiative - Vet Center design 2.0 #17661 
Child epic: Veterans can distinguish Vet Centers from VA medical facilities #17893
- UX #17891
- UX #18121 
- Content strat: #17195 

# CUT LINE 
## 5) VBA/VAMC Service Location enhancements - non-launch-blocking follow ups - department-of-veterans-affairs/va.gov-cms#16825?
- FE #17514
- Drupal: #17515
- Drupal: #17137 
- Any additional launch follow up

### 6b) VBA Pilot MVP: other launch-related - #10514
- FE department-of-veterans-affairs/va.gov-cms#17601

## 8) Facility Locator iteration: Provider core training / PPMS data - #14225
n/a

## 18) Facility Locator: "Service type" field iterations #15541
- UX #17835

## 20) Improve services accordions & locations across products - department-of-veterans-affairs/va.gov-cms#17350
- FE department-of-veterans-affairs/va.gov-cms#17415 

# Other Work (Not Q2 Prioritized)
- department-of-veterans-affairs/va.gov-cms#17848 
- FE #17904

**Comment by jilladams** [comment]
@davidmpickett @Agile6MSkinner FYI: started a Sprint 4 plan epic, just a straight copy of Sprint 3 at this point

**Comment by davidmpickett** [comment]
@jilladams @Agile6MSkinner  Consider adding this under 5) Service Locations as fast follow 
- [ ] Drupal: #17515

IMO this is a much higher priority for improved Editor experience than 17137

**Comment by jilladams** [comment]
- [ ] Identify the LH V0 tix that need refined
- [ ]  Dave pickett's content strategy tix
- [ ] Find Michelle's PPMS pagination tix and figure out wt
- [ ] Get Jordan's design tix from the A6 thread 
- [ ] Pick goals for FE / UX
- [ ] Icons: either PW has to help or we have to do or we have to ask deadline to move
