### ISSUE TITLE
Develop a UX Decision/Change Log

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-cms#18116]
### Problem Statement

As a UX designer, I must document the changing areas of the UI, including their location and the rationale behind the change, emphasizing its positive impact.

### Description

Create a document for the CMS product team to utilize as a reference for UI changes within the Knowledge Base. 

### Acceptance Criteria

- [x] Creation of a sharable document
- [x] Document the state of design upon joining
- [ ] Document the ideas, conversations, and meetings surrounding the work to be done
```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18118
```
