### ISSUE TITLE
PDF Delete: Six Hats Persona Mapping [UX Artifact]

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-cms#18124]
### Problem Statement

As a product team, we need a better understanding of the Editor's ability to delete documents from the Drupal environment.

### Description

Using the Six Hats framework, we will outline six areas of consideration regarding the editor's experience in posting content and using PDFs. Areas include: 

1. Positivity (yellow) - what opportunities open up?
2. Downside (black) - what are the worst-case scenarios?
3. Data (white) - what does the data tell us?
4. Emotions (red) - how would others react to this decision?
5. Creativity (green) - what is possible?
6. Process (blue) - how can you shift the perspective?

### Acceptance Criteria

- [x] visual map depicting the thought process for the different areas
- [x] spreadsheet or table with synthesized thoughts for team consideration

### Artifacts
[Six Hats Mural Board](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1712587869604/fead5bc2ac0915af1ada1f01053f68dfe403b90e?wid=0-1715619314041)

**Comment by MDomngz** [comment]
### First round of Exercise

Hat | Positivity | Downside | Data | Emotions | Creativity | Process
-- | -- | -- | -- | -- | -- | --
Color | yellow | black | white | red | green | blue
  | Benefits of the decisionWhat opportunities open up? | Take a defensive approach, imagine any potentially negative outcomes, see what might not workWhat are the worst-case scenarios? | Analyzing available data and trendsWhat is the rational approach? | Using your intuition and gut feelingsHow would others react to this decision? | Let your mind run free and generate ideas without censoring them.What is possible? | Controlling the process by shifting the thinking or discussion to a different hat/perspectiveHow can you shift the perspective?
Notecards | Self-governance | Accidental deletion of files | # of in-use PDFs | User empowerment | Write a daily script that ‘removes’ duplicates un-attached | (Editor)Approval process to confirm delete action
tighter management process | Abuse of feature | # of duplicate PDFs | Confidence building | Incorporate AI to assist the editor with what they need to action | (Veteran)Give them the ability to “flag” inaccessible PDFs
smaller pdf file count stored | Influx of HelpDesk tickets | # of un-used PDFs | Usefulness in being able to clean up messes | Rollout a new manual workflow that incorporates the ability to delete | (Admin)Review a log of files uploaded per week by each user
removal of duplicates | Confusion caused by changes to the process | # of editors on the system | Frustration over new processes |   | (Product)Automated review for duplicates, flagging for removal
removal of error file uploads | Deleting a PDF that is tied to content | # of PDFs uploaded by section |   |   |  
reduction in user confusion | Revert deletion requests | Avg years of experience by role |   |   |  
streamlining new workflows |   |   |   |   |  

### Next steps

Dig into the data to see what it tells us about the unmet needs of the user along with the depth of the problem

**Comment by MDomngz** [comment]
### Data findings

**Todo**
- [ ] need to find the number of duplicates

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/156954219/acc5d9a2-bbe2-4dfc-8a00-f64daa91531d)

**Comment by gracekretschmer-metrostar** [comment]
@MDomngz this work has been completed, correct?

**Comment by MDomngz** [comment]
@gracekretschmer-metrostar yes, this work has been completed. I will close.
