### ISSUE TITLE
Add tests for core updates

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#1812]
## Description

This is a follow up on #1797 to create tests instead of doing them manually:

As admin
1. Review core patches (perhaps this should be included in the core update procedure, not tests, but leaving it here)
   - [x] confirm all patches applied correctly
   - [x] if any patches failed - verify if they are still relevant and re-roll those that must stay **composer already fails the build when any patch failed to apply**
1. Login and visit /admin/reports/status
   - [x] Validate that site is running 8.8.6 **not essential**
1. Bounce around on the site to several content pages then visit /admin/reports/dblog
   - [ ] Validate that there are not a bunch of new errors or notices tied to the update - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2797 
1. Edit a node with a WYSWIG: visit /node/2450/edit
1.  Edit one of the WYSIWYG paragraphs in the main content section. then save the node.
1. Validate that the change worked.
1. Edit a node with draggable paragrapsh: visit /node/2450/edit
1. Drag the the bottom paragraph in the main content section to the top of the section and save the node.  **not going to test automatically atm**
   - [ ] validate that the bottom content now appears as the top of the section.
1. Create a site_alert here /admin/config/system/site-alerts and set an expiry time a minute or two in the future - **https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3707**
   - [ ] validate that the alert appears. 
   - [ ] stay on the page and validate that the alert disappears when the time has past. (polls every 30 seconds)
1. Visit a node edit page /node/716/edit
   - [ ] Open your browser console and validate there are no js errors. **https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3708**

**Comment by oksana-c** [comment]
made comments inline for related stories. closing
