### ISSUE TITLE
Update facilities runbooks

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18136]
## User Story or Problem Statement

As someone supporting facility status changes, I want to be able to quickly create accurate issues related to these changes so that veterans are able to find the information they need quickly.

## Changes

- [x] Runbook ISSUETEMPLATES use the Flagged Facilities label
- [x] VA.gov frontend label is removed
- [x] URL change ticket accurately reflects modern steps
- [x] Steps that are no longer required are removed
- [x] Context is added about API IDs

## Acceptance Criteria
- [x] Runbooks are clarified for Help Desk and facilities team.

## Implementation steps
<optional>

**Comment by omahane** [comment]
I updated https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vamc-facility-new.md on Friday.

**Comment by jilladams** [comment]
@omahane FYI that Michelle had put this PR up awhile ago and I just merged it today, to udpate Vet Center new runbook. May need to pull that change in before you do more on this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/17689

**Comment by omahane** [comment]
[Vet Center new](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-vet-center-new.md) has been updated.

**Comment by omahane** [comment]
The [URL change runbook](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/runbook-facility-url-change.md) has now been updated, too. 

I believe these changes are complete (for now).

**Comment by jilladams** [comment]
@omahane You're clear to close this ticket when changes are done, and we'll iterate as needed once the Helpdesk starts using the updated templates.
