### ISSUE TITLE
Discovery: User Journey Flow > Editor PDF Usage [Research]

### ISSUE THREAD

**Issue by MDomngz** [department-of-veterans-affairs/va.gov-cms#18143]
### Problem Statement

As the UX designer for the CMS team, I need to understand how future feature iterations will affect each role type. Understanding this information will help guide a more holistic design approach to solutions.

### Description
I aim to utilize GitHub and other VA documentation to find the necessary information for a better understanding of the various editor roles and their interactions with the Drupal environment.

```[tasklist]
### Tasks
- [x] Locate archived persona documentation
- [x] Contact other teams for suggested resources
- [ ] Develop the content for a journey map
- [ ] Illustrate the editor paths that encounter the need to delete an uploaded PDF document
```

**Comment by MDomngz** [comment]
Steve suggested the following link 
- https://prod.cms.va.gov/user/4943/roles * once loaded it provides the birds-eye for all editor roles available within Drupal

Dave Pickett provided his well-diagramed resources -

- This readme explains how Content Moderation roles work. This is one of the main ways access is determined
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-governance/content-moderation-roles 

- This folder talks about the various types of roles and permissions
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/content-governance
  
- I also did a presentation on this a year ago that might be helpful [https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/sitewide/topic-dives/README.md#51523---cms-user-[…]rkflows--sections](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/sitewide/topic-dives/README.md#51523---cms-user-permission-model-roles-permissions-workflows--sections)

**Comment by MDomngz** [comment]
Archived documentation done by the previous team
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research/cms-personas-journeys
[VFS-CMS Personas V1.0.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/15339225/VFS-CMS.Personas.V1.0.pdf)
