### ISSUE TITLE
Design system tooling

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1816]
## Hypothesis

Once the CMS team has determined that it is feasible to maintain a Design System, we will need to identify tools and methods for building, maintaining, scaling a Design System.

We'll know that the decision made in regards to tooling is effective, once we assess the level of effort to implement, collaborate, maintain and scale a Design System powered by these tools short and long-term.

## Acceptance criteria

- [ ] Design System tools landscape is analyzed for design and technical feasibility and compatibility with Drupal
- [ ] A short list of recommendations that includes pros/cons summary around selected tools is generated for validation with the team
- [ ] backlog is formed based on team's findings and preferences for tooling
