### ISSUE TITLE
VBA: Contact info phone # not showing on front end

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18220]
## Bug Description
**WHEN** - Viewing VBA facilities service location
**IF** - Additional phone numbers have been added in Drupal
**THEN** - Other phone numbers do not appear in service location accordion

### Drupal View:
![342447097-a9f35f18-6955-4b78-9f61-bf9dea133319](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/dfc25235-40b4-4374-8d10-4830f792f0e2)

### Front-End View:
![342447074-944e8cfb-1ba3-4823-954e-e18e957b02a4](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/4e853238-76cc-435f-90bb-5e532458c068)

## End state Mockup
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/167716994/848893fd-9979-48de-a85b-9410fd366c60)

```[tasklist]
### Tasks
- [x] Root Cause Analysis
- [x] Develop Fix
- [x] Apply Fix
- [ ] QA
- [ ] Accessibility Review
```

```[tasklist]
### Acceptance Criteria
- [ ] "Other phone numbers" entered by editors in Drupal appear in service location detail after main phone number
- [ ] Uses design system components and correct props
```

**Comment by Agile6MSkinner** [comment]
@laflannery @Agile6MSkinner Will look at this to update description and ACs

**Comment by davidmpickett** [comment]
I just initiated a Content Release on my Tugboat to verify this and 17925

**Comment by davidmpickett** [comment]
Confirmed on tugboat https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/

![Screenshot 2024-07-05 at 1 50 39 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/20dc82f5-c70d-4a69-8ab4-9a78ba06a819)
