### ISSUE TITLE
VBA QA: Meta description has placeholder content

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18226]
## Description
The current meta description of the VBA Facilities says:

> "Placeholder text: Veterans benefits offices provide services to Veterans ... "

![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/106678594/92811f8f-3c18-4945-9436-445dbe1ff8ad)

[Example facility](https://web-shoowipgxumevd9gysmbhgkv2catpzm1.demo.cms.va.gov/portland-va-regional-benefit-office/)

What should this say? Where should this be coming from? We should resolve this.

## Acceptance Criteria
- [ ] Determine what the meta description for the facilities should say
- [ ] Determine where the eta description should be coming from (dynamic, hardcoded, etc.)
- [ ] Update the meta description based on the above 2 items
- [ ] Requires accessibility review

```[tasklist]
### Tasks
- [ ] Verify what they text should be
```

**Comment by davidmpickett** [comment]
Suggest as Staging Review blocking as this is likely to get flagged there

**Comment by jilladams** [comment]
(On the other hand: we could go to Staging Review with this as a known issue, if we were otherwise ready, which we are not yet.)

**Comment by Agile6MSkinner** [comment]
This is content work that @mmiddaugh will handle by working with VBA leadership and will enter into Drupal.

Closing as not planned since there is no eng lift.

**Comment by mmiddaugh** [comment]
Input from Tanekwa today during Office hours: we can follow VAMC lead and leverage intro text:

“We help Veterans, service members, and their families access VA benefits and services. Benefits we can help with include disability compensation, education benefits, life insurance, pensions, and home loans. Find a benefit office near you or sign up for updates."

**Comment by mmiddaugh** [comment]
This has been updated in Drupal
