### ISSUE TITLE
Vet Center - Facility Service create form needs service descriptions

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18321]
## User Story or Problem Statement

As an editor creating a new Vet Center - Facility Service from the /node/add form, I want to see that national description of the service I'm creating.

## Acceptance Criteria
- [ ] Selecting a service from the **Service name** dropdown populates a box with national description information (as it currently does when creating a service via IEF on the Facility page
- [ ] When changing the selected service in the **Service name** dropdown, the populated information changes to match the selected service

## Implementation steps
There's already code here to do this on the Facility page in the `appendHealthServiceTermDescriptionToVetCenter` function in the `va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php` file. It should be refactored so that the retrieval of the national description is its own function, allowing it to be called on both the node/add form for the service and the facility IEF (for now).

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by davidmpickett** [comment]
Great catch @omahane!

IMO - I would not consider this as blocking #18003. This is a small enhancement that could happen before or after. The service description box is present on the Node Edit UI, so this ticket is really just about creating a net new service.

![screencapture-main-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-node-69524-edit-2024-06-13-17_30_24](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/6cc5af95-77ab-437e-947f-f897af1e11e7)

**Comment by davidmpickett** [comment]
And for sake of completeness, here's screenshot of the Create UI missing the Service Description box

![screencapture-main-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-node-add-vet-center-facility-health-servi-2024-06-13-17_37_19](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5453aa74-8db5-4880-a953-6c9e8a5aca56)

**Comment by Agile6MSkinner** [comment]
Not blocking. Will add to editor experience enhancements epic after I create it.

**Comment by davidmpickett** [comment]
@omahane went above & beyond in resolving #18003 and also addressed this ticket in the same PR!
![Screenshot 2024-07-18 at 5 38 13 PM](https://github.com/user-attachments/assets/a1f2e14b-d5e2-4ee6-8e14-693896974196)

**Comment by jilladams** [comment]
This ticket is complete pending integration but didn't have an assignee. I assigned @davidmpickett but rereading comments, seems like this was actually an @omahane PR that covered it?

**Comment by davidmpickett** [comment]
Verified in prod
![Screenshot 2024-08-19 at 4 04 06 PM](https://github.com/user-attachments/assets/0b6e554b-320f-409f-874c-2f82ef10b373)
