### ISSUE TITLE
Make required/optional services text editable by site builders.

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#18325]
## User Story or Problem Statement

As a site builder, I want to edit the text that is used on Vet Center services to distinguish between required and optional services.

## Background
This idea stems from a [comment](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/18318#discussion_r1639895329) by @davidmpickett during the review of work to create the box with this information on the Vet Center services form.

## Acceptance Criteria
- [ ] A field is presented in a place where a site admin can edit the text that shows to editors (this may need to be more than one field).

## Implementation steps
The current implementation is in `va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php`. If this work is done to expand the types of services that can be designated as required or optional (and to show that to editors), we should consider refactoring `va_gov_vet_center/src/Service/RequiredServices.php` so that it accounts for all services with required fields, rather than Vet Centers only. At that time, it would be wise to move the code out of `va_gov_vet_center`, too. 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.
