### ISSUE TITLE
Multiple email addresses entered in Drupal should display on FE

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#18383]
## User Story or Problem Statement
When multiple email addresses have been added to a Service Location under Contact information, only the first email is displaying.

Something here might also be impacting Service Hours not displaying?

## Description or Additional Context 

- https://main-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/node/69894
- https://web-jdujzwgvp8kmj36hcfonqejlgtq5b6st.demo.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1169-

### Front End on Tugboat
![screencapture-web-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-philadelphia-va-regional-benefit-office-2024-06-24-12_13_29](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/7fad1906-534c-4b19-8bfd-5317204656f9)

### Data in drupal
![screencapture-main-jdujzwgvp8kmj36hcfonqejlgtq5b6st-demo-cms-va-gov-node-69894-2024-06-24-12_13_40](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/5f366e8d-9e05-4033-ba63-236f3acb4d2d)

### WAVE testing reveals hidden email addresses

![Screenshot 2024-06-18 at 12 34 42 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/428e001a-b06b-4f4f-9e2c-a4d9a5cd6c1c)

![Screenshot 2024-06-18 at 12 38 34 PM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/b7db21bd-aa83-474a-b1bb-8b02e621aec4)

```[tasklist]
### Tasks
- [ ] Find the root cause of the issue
- [ ] Fix the issue OR
- [ ] Create a bug fix ticket and link it here
```

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/18383?planning-poker) with Zenhub @davidmpickett @dsasser @eselkin

**Comment by eselkin** [comment]
Probably all frontend: Something is probably breaking in the email loop and causing the rest to be ignored/hidden by an incorrect ending div or something like that. We see this occasionally happen in liquid.

**Comment by jilladams** [comment]
@Agile6MSkinner this ticket is the last fix ticket in the VBA Pilot ticket that wasn't in Ready or in current sprint. Is it a launch blocker? I pulled it over to Ready assuming yes, but am I wrong?

**Comment by Agile6MSkinner** [comment]
Interesting... it was removed via sprint automation. I don't like that at all.

**Comment by jilladams** [comment]
Ohhhh that must've happened while I was updating the Flagged Facilities board automation. Wow -- good catch, thank you!

**Comment by eselkin** [comment]
I think @randimays fixed this when she fixed the hours one. I see multiple contact emails 
<img width="653" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d09f54a949ca0f3285c536a756fddf58153b08dd/Screenshot%202024-07-15%20at%204.49.46%E2%80%AFPM.png" alt="Screenshot 2024-07-15 at 4.49.46 PM.png" />

**Comment by randimays** [comment]
@eselkin Yes, I fixed this when I fixed the hours display. They were both broken due to the same syntax error.

**Comment by davidmpickett** [comment]
Was resolved in #18393
