### ISSUE TITLE
BUG: Hours on VBA service locations do not display consistently on the FE

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18393]
## Description
Christian developed a script that allows us to quickly add and view test content for VBA. By using this script we found an issue with VBA Service location specific hours displaying on the Front end, sometimes they show, sometimes they don't. Christian and I spent time trying to find a pattern in what may be causing this an unfortunately we weren't able to find anything that really stood out to us. Here are some examples at the [Philadelphia VBA on tugboat](https://web-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/philadelphia-va-regional-benefit-office/):

**[Education benefits for Family members
](https://web-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1145-)**
- 3 service locations were added
- All have "Provide specific hours for this service" chosen
- All have the exact same hours added for the service
- Hours only show for the second location added

**[VetSuccess on Campus
](https://web-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1173-)**
- 3 service locations were added
- All have "Provide specific hours for this service" chosen
- All have the exact same hours added for the service
- Hours only show for the first location added

**[Transition assistance
](https://web-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1177-)**
- 1 service location was added
- It has "Provide specific hours for this service" chosen
- It has the exact same hours added for the service that the other above example have
- Hours do not show on the front end

**[Benefit letters and decision letters
](https://web-8xlwvjaivaajom82pgmuy8h3n3fzt65g.ci.cms.va.gov/philadelphia-va-regional-benefit-office/#vba-service-item-1142-)**
- 1 service location was added
- It has "Provide specific hours for this service" chosen
- It has the exact same hours added for the service that the other above example have
- Hours do show on the front end

## Notes
1. Christian and I are pretty sure this is a frontend ticket not Drupal because all the hours do show in the View screen properly so it seems the disconnect is after the Drupal piece.
2. I have added hours without the script on my own tugboat and doing my own testing and hadn't noticed anything off except this (possibly?) [related issue with service regions](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18221)

```[tasklist]
### Tasks
- [ ] Find the root cause of the issue
- [ ] Fix the issue OR
- [ ] Create a bug fix ticket and link it here
```

**Comment by jilladams** [comment]
@Agile6MSkinner @mmiddaugh this one seems like a launch blocker to me. Added to the VBA Pilot epic and queued for refinement in case you agree. If not, feel free to punt to Icebox. 

(@laflannery I also added the Sitewide label. )

**Comment by jilladams** [comment]
Noting: Christian put up a couple PRs that are linked above in comments, trying to figure out what is going on here, when it seemed like it was part of the test script ticket, #17969. But; it's likely that it's properly FE work and doesn't have anything to do with the test script. More that the test script revealed a FE problem.

**Comment by Agile6MSkinner** [comment]
This seems like a troubleshooting ticket (spike) to me. Anyone disagree?

**Comment by omahane** [comment]
I made one PR with ONLY "Use facility hours" selected for all service locations. When I released content, the [front end](https://web-ilyejayfize9avs66bwidqtsayldw4u9.ci.cms.va.gov/philadelphia-va-regional-benefit-office/) only the following had "The service hours are the same as our facility hours.":
- Careers and employment
- Disability compensation
- VetSuccess on Campus
- Benefit letters and decision letters
- Military records

When I did the same with only using specified hours, it was this group:
- Vet Success on Campus
- Education benefits for family members
- Returning service member care
- Benefit letters and decision letters
- Military records

**Comment by Agile6MSkinner** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-Sitewide-Product-Team-6645154188a81a1f7a0a9464/issues/department-of-veterans-affairs/va.gov-cms/18393?planning-poker) with Zenhub @eselkin @dsasser @davidmpickett

**Comment by eselkin** [comment]
May be related to the contact email loop issue.
