### ISSUE TITLE
[Epic][AP] Sitemap for CMS and other VA.gov content

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#18488]
## Requirements & Goals
 We want sitemaps that are well-constructed and complete, so that search engines can accurately index our content and therefore allow Veterans to use search to find the content they need.

Sitemaps should be well-organized such that they are human-readable, for awareness and troubleshooting purposes.

Sitemaps should be able to be broken up semantically into categories, to allow for better troubleshooting and also to allow prioritization of some sitemap for more frequent or higher priority indexing. 

```[tasklist]
### How will we know we've achieved our goal?
- [ ] We can produce sitemaps that are organized according to the needs of VA.gov IA
- [ ] The total collective sitemap can be broken up into multiple sitemaps for semantic organization purposes and to keep the number of URLs being indexed in an individual sitemap reasonable
- [ ] Sitemaps can be produced on-demand which reflect the current state of VA.gov content
- [ ] Sitemaps accurately reflect content age (`lastmod` property)
```

## Work

```[tasklist]
### Issues or tasks to be turned into issues
- [ ] Link issues here
- [ ] Or enter ideas for the PM to convert to issues
```

**Comment by laflannery** [comment]
- sitemap-index.xml
  - content-build.xml
  - next-build.xml
    - facilities.xml
    - everything-else.xml
    - etc.xml
- Probably not children within children, just can have one level, so the facilities and everything site maps would go one level up
- There is also standard naming we must follow
- Could we also add the ability to flag something to NOT be indexed and not show in the sitemap
  - Example use case: Keep something hidden from search because it's a quiet launch, non of the auth pages should be there but they do find their way, usually it's temporary but it still does need to happen

**Comment by laflannery** [comment]
Regarding any sitemap updates and Search.gov:

Michelle checked with the [Search.gov](http://search.gov/) folks and they replied:
> This change won't have an impact on indexing. Also, there's no need for redirects. We recommend to keep the sitemap URLs up-to-date in both the sitemap index and the individual sitemaps. There's no need for you to let us know prior making this change, but please feel free to do so if you want us to double check the structure.

**Comment by laflannery** [comment]
Resources:
- https://www.sitemaps.org/protocol.html#index
- https://search.gov/indexing/sitemaps.html
- https://developers.google.com/search/blog/2005/08/using-sitemap-index-files
- https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps

**Comment by laflannery** [comment]
1. We have a content-build sitemap
2. We could turn the next-build sitemap on
   3. Make sure last mod date is there and accurate
4. We need to create a sitemap_index
5. Splitting facilities into it's own sitemap will probably be done when we move to On Demand
