### ISSUE TITLE
FE: Add "Mission Explainer" /  "Our commitment" Box to VetCenter Facility Pages

### ISSUE THREAD

**Issue by Agile6MSkinner** [department-of-veterans-affairs/va.gov-cms#18724]
## **DO NOT MERGE** until @Agile6MSkinner is notified for change management purposes

**FINAL CONTENT FROM CAIA: https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961** Drupal functionality was created using Draft content. We do not want to publish that to the FE. Could build this and hold merge until final content is received, or opt not to work it yet.

### User Story
As a veteran, beneficiary or caretaker, I would like to have a summary box displayed at the top of VetCenter facility pages so that I am quickly able to understand the mission and services offered for the facility I am looking at.

### Description
Implement a GraphQL query to fetch VetCenter mission explainer content and use the existing "Summary Box" component from the design system to display it on the Vet Center pages.

[Figma Designs](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=906-9587&t=01z24AaG2OXhFbTw-1)
[GraphQL recommendations from Eli](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18724#issuecomment-2374658111)

### ACs:
1. Blue Summary Box exists at the top all VetCenter facility pages
2. Includes content from Mission Explainer content block created in #18723 
3. The blue summary box must use the existing "Summary Box" design component and follow all applicable annotations [indicated here in Figma](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=930-13596&m=dev).

```[tasklist]
### Tasks
- [x] Write a GraphQL query to fetch the blue information box content, with Drupal support.
- [x] Integrate the ["Summary Box" component](https://design.va.gov/components/summary-box) to into the template
- [x] Communicate change to VetCenter
```

```[tasklist]
### QA
- [ ] Verify that the "Summary Box" component is used for the mission explainer summary box.
- [ ] Verify that the content is correct in the front-end and matches Drupal data
- [ ] Verify that the blue information box is displayed correctly and consistently across all Vet Center pages.
- [ ] Accessibility Review
- [ ] Design Review
- [ ] **DO NOT MERGE** until @Agile6MSkinner is notified for change management purposes
```

**Comment by davidmpickett** [comment]
Noting that we have a [request out to the Design System team](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2956) to update their guidance on On This Page component so we could exclude the blue box from having a jump link

**Comment by aklausmeier** [comment]
Noting that we do not have final content from CAIA.

**Comment by jilladams** [comment]
Added details on the CAIA blocker in ticket body. I bumped https://github.com/department-of-veterans-affairs/va.gov-team/issues/83961 as well to see if they have updates, since we haven't heard anything this week. 

We are also blocked on product decision around timing / priority for building out Vet Centers 2.0 in content-build (and creating more drift for the AP template to catch up) vs. waiting for AP to ship, and building it all out in AP instead. 

FYI @mmiddaugh @Agile6MSkinner

**Comment by jilladams** [comment]
I think we could do a quick estimate in refinement re: pulling fields through to FE in content-build, just to understand the lift, if we have time.

**Comment by Agile6MSkinner** [comment]
@aklausmeier @laflannery Let's look at the DST ticket for exclude the explainer box from "One This Page"

**Comment by Agile6MSkinner** [comment]
@eselkin Will do a bit of exploration on Graph QL and add to ticket.

**Comment by aklausmeier** [comment]
@Agile6MSkinner I have pinged the DST team for an update on an ETA for a fix to [allowing exclusion of H2's from the On this page/ToC component](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/2956)

**Comment by eselkin** [comment]
A simple GraphQL query for vet centers is:
```
query GetVetCenters {
  nodeQuery(
    limit: 1
    offset: 100
    filter: {conditions: [{field: "status", value: ["1"], enabled: true}, {field: "type", value: ["vet_center"]}]}
  ) {
    entities {
      ... on NodeVetCenter {
        entityId
        title
        fieldMissionExplainer {
          fetched
        }
      }
    }
  }
}
```
Returns something that looks like:

```
{
  "data": {
    "nodeQuery": {
      "entities": [
        {
          "entityId": "3711",
          "title": "Pasco County Vet Center",
          "fieldMissionExplainer": {
            "fetched": {
              "fieldMagicheadBody": [
                {
                  "value": "<ul><li>Our team will work with you to identify your goals and make a plan to meet them. We'll help you and your family build meaningful connections to improve your quality of life.</li><li>Our counseling is confidential. We won’t share any information about you or the services you receive without your permission—except in a life-threatening situation. And our records can't be accessed by other VA offices, the Defense Department, military units, or community providers.</li><li>We encourage you to contact us, even if you're not sure you're eligible. We'll find a way to connect you with the help you need—at VA and your community.</li></ul>",
                  "format": "rich_text_limited",
                  "processed": "<ul>\n<li>Our team will work with you to identify your goals and make a plan to meet them. We'll help you and your family build meaningful connections to improve your quality of life.</li>\n<li>Our counseling is confidential. We won’t share any information about you or the services you receive without your permission—except in a life-threatening situation. And our records can't be accessed by other VA offices, the Defense Department, military units, or community providers.</li>\n<li>We encourage you to contact us, even if you're not sure you're eligible. We'll find a way to connect you with the help you need—at VA and your community.</li>\n</ul>\n"
                }
              ],
              "fieldMagicheadHeading": [
                {
                  "value": "Our commitment"
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

The `fieldMissionExplainer` is a magic head array with one element (it's been limited to 1)... Not all Vet Centers (unpublished? or something else, not sure) have the `fieldMissionExplainer`

**Comment by laflannery** [comment]
@Agile6MSkinner There should be an AC/Task, (I'am not clear on the distinction tbh) to indicate that the summary box should follow all applicable annotations [indicated here in Figma](https://www.figma.com/design/EVd3q06ukAbVS61Q8MwRAT/Vet-Centers?node-id=930-13596&m=dev). Are you able to add that to the correct list above?

**Comment by aklausmeier** [comment]
@Agile6MSkinner The DST is expecting to allow the exclusion of H2s by December so we will need to pull that AC into it's own ticket as a follow-up when that is revised in the design system component.

**Comment by davidmpickett** [comment]
> Not all Vet Centers (unpublished? or something else, not sure) have the fieldMissionExplainer

@omahane - Could this be related to the default value thing for Entity Fetch Fields?

**Comment by eselkin** [comment]
@davidmpickett Not sure, but if you go to the node's page on my tugboat or prod the mission explainer is in fact missing:
https://main-gypmlk8q1dooxvfrxv2hfyasml9oalln.demo.cms.va.gov/alexandria-va-vet-center
https://prod.cms.va.gov/alexandria-va-vet-center

**Comment by jilladams** [comment]
@Agile6MSkinner could you add latest status here? OK for Eli to merge?

**Comment by Agile6MSkinner** [comment]
Apologies, I thought I put the go-ahead here too. We can merge this @eselkin

**Comment by jilladams** [comment]
![Image](https://github.com/user-attachments/assets/e7206961-61ed-4f0a-b064-fa772a42307b)
