### ISSUE TITLE
No-Op: Lovell Programs page split into two separate Programs pages

### ISSUE THREAD

**Issue by ian-sears** [department-of-veterans-affairs/va.gov-cms#18725]
## User Story or Problem Statement

As a Lovell Editor, I need to separate the Programs page into the two since they have different program offerings.
Original JIRA CMS Help Desk ticket: [VAHELP-7771](https://va-gov.atlassian.net/browse/VAHELP-7771)

[https://www.va.gov/lovell-federal-health-care-va/programs/](https://www.va.gov/lovell-federal-health-care-va/programs/)

We only have one possible editable Programs section for both the TRICARE and VA site - I’m not able to make my own but we need to be able to separate them since they have different program offerings:

[Programs | Lovell Federal Health Care | Veterans Affairs (va.gov) (note: this is VA)](https://www.va.gov/lovell-federal-health-care-va/programs/)

[Programs | Lovell Federal Health Care | Veterans Affairs (va.gov) (note: this is Tricare)](https://www.va.gov/lovell-federal-health-care-tricare/programs/)

#facilities-support [Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1721751062452559)

## Acceptance Criteria
- [ ] Existing feature functionality of the Lovell Programs page(s) is/are preserved (toggling)
- [ ] Editor able to add unique information (or) content to each Programs page
- [ ] Existing side(bar) Menus functionality is preserved
- [ ] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
Alter the exisitng Programs page to no longer serve "both" TRICARE and VA
Alter the existing Programs page to serve the VA side of the Lovell health care system
Add a duplicate of this Programs page that serves the TRICARE side of the Lovell health care system

[VAHELP-7771]: https://va-gov.atlassian.net/browse/VAHELP-7771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ian-sears** [comment]
dsva discussion https://dsva.slack.com/archives/C02730UEZPS/p1721751062452559

**Comment by ian-sears** [comment]
@TroyCMSSupport and @ian-sears discussed this in depth. We found the Lovell [Contact Us](https://www.va.gov/lovell-federal-health-care-tricare/contact-us/) pages have been separated like this, and see that the Editor updated these today as well. It may help to notice the 3 Blue Chevrons (look closely as they are unique to each Contact Us page) to see what may be motivating the Editor to need this Programs page separation.

**Comment by ian-sears** [comment]
Today, the Editor attempted to do this and mistakenly (temporarily) Archived the [Programs page on the va side](https://www.va.gov/lovell-federal-health-care-va/programs/). CMS Help Desk revisioned the page to the previous Published revision and the page is now functioning as it was.

**Comment by ian-sears** [comment]
While we (CMS HD) can likely create the two new Programs pages (from the existing), we recommend this first be examined and possibly tested on the development sites (or) assist the CMS Help Desk in a decisive response to the Editor for this request.
CMS HD asked the Editor to please hold off making changes (to the Prod site) for this until Engineering can consider the best resolution to this request.
CMS Help Desk ticket is Awaiting Developers (consideration and decision) currently.

**Comment by jilladams** [comment]
Per [Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1721758458094149?thread_ts=1721751062.452559&cid=C02730UEZPS), assigned this ticket to Michelle for follow up with the requester (Rowan) to understand the need / priority better.

**Comment by ian-sears** [comment]
@mmiddaugh  - We are following up on this ticket in hopes of closing this issue with the Editor.

To refresh memory on this ticket, the Editor originally reported the following to our VA CMS Help Desk, and as we understand it -  you are following up with the Editor. This is Lovell.

Rowan Yearley asked:
"We only have one possible editable Programs section for both the TRICARE and VA site - I’m not able to make my own but we need to be able to separate them since they have different program offerings:

[Programs | Lovell Federal Health Care | Veterans Affairs (va.gov)](https://www.va.gov/lovell-federal-health-care-va/programs/)

[Programs | Lovell Federal Health Care | Veterans Affairs (va.gov)](https://www.va.gov/lovell-federal-health-care-tricare/programs/) 

They look different on the site but it is the same link in Drupal edit mode. I can’t provide different descriptions- I attempted to make another detail page this morning to separate them and it didn’t work, it wouldn’t allow me to assign it. It was functioning as a combined page - we need separate ones to provide different details."

**Comment by ian-sears** [comment]
@mmiddaugh 
Lovell Tricare
Lovell Federal
Both need separate "Programs" menus. Their programs are unique in each.
Is there any progress we can convey to the Editor for this open CMS Help Desk support ticket?
Editor is Rowan Yearley

**Comment by mmiddaugh** [comment]
Thank you for bringing attention to this request - apologies for the delay. I understand the business need, similar to the Contact us pages. I agree we should put some engineering eyes on it to look for possible consequences. 
@Agile6MSkinner - Christian or Bryan might be able to advise.

**Comment by laflannery** [comment]
@Agile6MSkinner I'm following up on this as I've been going through Helpdesk requests. Based on the conversation, I will be replying to the editor today that this request has been reviewed and will be raised to the engineering team to be evaluated but just pinging you for awareness and making sure it doesn't get lost. Thanks!

**Comment by jilladams** [comment]
Created a content strategy SPIKE : https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20284

**Comment by jilladams** [comment]
Consensus from refinement: the technical lift to fork the Programs page is not worth the effort, given the user need. We would like to propose to the Lovell editor(s) that they can just list their available programs in the main page as 2 lists, if they would like. Especially given that Editors can already create separate program pages per audience, and the menu handles that correctly. 

Next steps: 
* Product follow up with Rowan
* Product follow up with VHA

**Comment by laflannery** [comment]
@jilladams Based on this update, there are no steps that Helpdesk needs to take at this time correct? And if that becomes the case you will ping us directly?

**Comment by jilladams** [comment]
Correct!

**Comment by Agile6MSkinner** [comment]
Waiting for VHA to follow up with editors. Tracked in Trello: https://trello.com/c/6BYIDzao/276-lovell-programs-page
