### ISSUE TITLE
EWA: Revision meta block [content]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1878]
## User Story

As a Content Editor I want to see revision information at the top of the content I'm viewing.

See [Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1590696725037/2c23eff492dd1997307579bfb6560fb0e74aa7da)

## AC 

- [x] labels finalized for the "revision meta block"
  - [x] Revision ID (users should have a way of referencing a revision)
![image](https://user-images.githubusercontent.com/16477724/83794675-93323f80-a65b-11ea-8969-f6c262296741.png)
  - [x] "latest revision" label
  - [x] “See preview” option
  - [x] “Copy preview link” option

## Implementation

- suggested Revision ID format `You’re looking at revision 5011/32 12/21/20 2:33pm ET`, where `5011/32` is composed of Node ID / Revision ID numbers.

**Comment by rachel-kauff** [comment]
Documented my [recommendations in this mural](https://app.mural.co/t/vagov6717/m/vagov6717/1591028145892/1ef11c627afd3437fe97a46cc57640eb9603328c). Jordana will update the prototype to match!
