### ISSUE TITLE
EWA: Entity meta data block

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#1883]
## User Story

As a content editor, I need quick access to node's meta data information when I'm viewing node's latest or older revisions. 

## Acceptance criteria

- [ ] an entity meta data block is displayed in the right sidebar on the node view page per [prototype](https://xd.adobe.com/view/62bb878c-565e-4120-6449-3ea443b6064f-148a/?fullscreen)
<img width="440" alt="Screen Shot 2020-06-04 at 12 29 05 PM" src="https://user-images.githubusercontent.com/16477724/83801003-9cc0a500-a665-11ea-9496-85e8e33eb426.png">

## Implementation

- block's content is proprietary to the VACMS and will live in a custom module
- the following information should be included:
    - [ ] Owner: contextual to currently viewed revision
    - [ ] content type
    - [ ] Va.gov URL: taken from latest published revision or N/A [TBD in #1900]
