### ISSUE TITLE
Update Regional office content type with new embedded service view

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#18857]
## Description

In #17708, the problematic inline entity form (IEF) was removed from the Vet Center node and replaced with a new services view. We can now improve the Regional office editorial experience by adopting this new paradigm 

Note additional changes are pending and should be considered for this effort, such as [Remove already created services from the options when adding a new service #17674](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17674) 

## Tasks
TBD

## Acceptance criteria

- [ ] Editors can see the existing Facility Services for their VBA facility while editing the page
- [ ] Editors can see the moderation state of a listed VBA facility service
- [ ] Editors can click out to a facility service to add or edit
- [ ] A token is passed to pre-populate the facility on the service 
- [ ] Relevant KB articles are reviewed and updated as needed
