### ISSUE TITLE
Display issues with Checklist type in resources and support

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#18876]
## Background
The checklist content type in Drupal is not a content type that is often used (possibly ever?). However, a new node was created a couple weeks ago to support the rollout of the Login changes that are coming this year. This page is displayed on the front end here: https://www.va.gov/resources/what-to-bring-to-create-your-online-sign-in-account/

## Description
While doing a separate audit I noticed 2 issues with the front end display:
1. Breadcrumbs: The second and third crumb are reversed.
   
![image](https://github.com/user-attachments/assets/c8ceb67e-b725-4180-b190-9279d2bf09bd)

   - The second crumb should be "Resources and support" and link to the Resources and support landing page
   - The third/last crumb should be "What to bring to create your online sign-in account"
     - This should also be sentence case and not title case which is is currently but this also may be a larger issue than just this one article
2. Bottom section:
   -  Last Updated is way off to the left when it should be in line with the left edge of content
   - The feedback button is missing
![image](https://github.com/user-attachments/assets/687fb5f5-0bf0-4f16-bc83-991aaee3ce85)

## Acceptance Criteria
- [ ] Breadcrumbs match the actual URL path of the article
- [ ] Casing of crumbs is updated if possible (if within scope)
- [ ] Article footer is updated to include feedback button and display Last updated correctly
- [ ] Requires design review
- [ ] Requires accessibility review

**Comment by jilladams** [comment]
@randimays I just noticed that this ticket was in last sprint and rolled over, but we didn't talk about it in planning yesterday. Is this one we could assign to you?

**Comment by randimays** [comment]
This has been validated successfully in production. Closing as complete!
