### ISSUE TITLE
Pressure Test AP Frontend Documentation

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#18906]
## User Story or Problem Statement
The AP frontend documentation needs to be reviewed and pressure tested ahead of handing it over to a new team that will take over the template migration work.

## Description or Additional Context 
the Accelerated Publishing team's task order will be ending in early October and will need to hand over the frontend template migration to another team. @ttran-Therisa, the AP frontend engineer, has created documentation to hand over to the next team that will take over this work, so to help improve the documentation and coverage within the team, we want to pull in a CMS engineer and pressure test the documentation. 

## Steps for Implementation
- CMS developer review the documentation and try to complete tasks listed within it
- Provide feedback to AP frontend engineer 
- Complete task attached to this ticket

## Acceptance Criteria
- [ ] CMS team better understands what is needed for the AP template migration work, ahead of AP team rolling off the project.
- [ ] AP frontend documentation is ready to be handed off to the sitewide and/or platform teams. 

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/next-build/issues/661
```

**Comment by ttran-Therisa** [comment]
Here is the starting markdown format that I wanted to make a GitHub README for this; however, I need to compress my videos to be smaller than 100 mb and my premiere pro expired. (looking into safe alternatives or if someone else has premier pro). There is also intentions to put the documentation on confluence.

#Next-Build Walkthrough

## Next-Build Local Setup

If you already have `next-build` setup on your local-machine, you can skip to the next step on creating layouts. 
Link for [next-build README](https://github.com/department-of-veterans-affairs/next-build/blob/documentation/README.md)

If there are some issue being able to preview `next-build`, it is recommended to look at [preview.md](https://github.com/department-of-veterans-affairs/next-build/blob/documentation/READMEs/preview.md)

(embed howToSetUpNextBuild.m4 here; should be the first one)

## Walkthrough on creating layouts

When creating layouts, most of your efforts will be dedicated to manipulating and connecting data to their intended area. This video is here to familiarize the user what the development process is like and encourage users to dive into the many layers of connecting files for a better understanding.

Link to [layout reference sheet](https://docs.google.com/document/d/1yQJDqJKp-Ixd9KicKfiIzqmWH27UVij-h_LJJpmJ9h8/edit?pli=1)

(embed walkthroughOnLayouts.mp4; should be the second one)

**Comment by JakeBapple** [comment]
I've done a walkthrough of the document and provided suggested changes.
