### ISSUE TITLE
Add official name to the VBA facility

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19212]
Direction for this issue was decided in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351 SPIKE.

## User Story or Problem Statement

As a Veteran, I want to be able to find a VBA facility based on a name that is easy to read and which I would recognize.

## Acceptance Criteria
- [ ] An "Official name" field is visible in node:view
- [ ] An "Official name" field is visible in node:edit
- [ ] A new VBA facility has its "Official name" field filled in during migration
- [ ] An existing VBA facility has its "Official name" field changed during migration when the name changes upstream
- [ ] A new VBA facility has its "Title" set to the "Official name" during migration
- [ ] An existing VBA facility has its "Title" unchanged during migration when the name changes
- [ ] The VBA regional benefit offices that need a condensed name have a condensed name as their title
- [ ] Requires Content Model Documentation
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps

- A field called "Official name" `field_official_name` is added to VBA facility.
- The VBA facility migration is changed to set the `field_official_name` to the `name` property in the API.
- Copy `field_official_name` to the` title` (if the title is empty [as we do with Vet Center in the `va_gov_migrate.module`]).
- Manually change the `title` for the Regional benefit offices that need to have a condensed name

## Additional context
Product agreed to do this during the 12 Sept 2024 Sitewide UX sync, as documented in [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17351#issuecomment-2349117334).

## Definition of done
- [ ] Code completed; PR created
- [ ] Review instance created/available; internal team notified to start reviews
- [ ] Automated tests passed 
- [ ] Code review (meets established quality and security standards)
- [ ] PR approved
- [ ] Design review (meets design & UX requirements)
- [ ] A11y review (meets accessibility standards)
- [ ] Functional/feature review (meets acceptance criteria)
- [ ] Testing completed; dev team notified to deploy
- [ ] PO/PM/external verify in prod
- [ ] Documentation updated
