### ISSUE TITLE
Establish metric tracker for number of support requests on a monthly basis, and count for January-June

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1924]
## AC
- [x] Definition of a support request
- [x] Sensor in place that helps us measure number of support requests
- [x] Place to track this data

## Not included
- [ ] Automated way of counting support requests. 

## What constitutes a support requests?
1. vacmssupport@va.gov email thread 
2. slack #cms-support workflow 
3. @mentions on slack in #cms-support

## Artefact 

See https://docs.google.com/spreadsheets/d/1XRQYWCacMIpf14sZr6kVQ7uq0iF-RfoDzdfv_EwsDVc/edit#gid=1200406817
