### ISSUE TITLE
STUB: Manila overflow

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19270]
### User set up [CMS helpdesk / Drupal admin]
- [x] Create users if needed / assign users to the appropriate section - Manila editor: https://prod.cms.va.gov/user/2199
- [x] Communicate to user that they can start editing (and explain what they shouldn't do)

### VAMC editor tasks
- [ ] Complete training if they haven't already
- [ ] Do all the things listed [here](https://prod.cms.va.gov/help/vamc)
- [ ] Do we have a checklist like we do for VBA?
- [ ] Confirm when ready to publish

### Launch tasks (not Editor blocking, but are launch blocking)
- [ ] ~DRUPAL Enable the menu in Menu Breadcrumbs module~ - now in #19199
- [ ] ~FE Update CONTENT BUILD FILE with the menu~ - now in #19273
- [ ] DRUPAL Ensure URL aliases are functioning properly - Maybe can verify in #19199 
- [ ] Lighthouse coordination for service push?
- [ ] Redirects?  From the now-dead VISN 21 page to the modernized page?
- [ ] Comms, change management?

**Comment by jilladams** [comment]
Closing. We nailed all this down in #19271 and other launch blocking tickets.
