### ISSUE TITLE
New VAMC System: VA Manila, and launch plan

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19271]
### Information needed from Product / VHA DM
- [x] The plain language name for the VAMC system. This should follow [the pattern](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/naming-schema): Manila VA Clinic
- [x] Which VISN is this system in? 21

### Create a new menu through config PR [Drupal Engineer]
- [x] [Add a new Menu](https://staging.cms.va.gov/admin/structure/menu/add) in a non-prod environment - https://prod.cms.va.gov/admin/structure/menu/manage/manila-va-clinic
   - [x] Title = VAMC system plain language name
   - [x] Administrative summary = VISN 21 | va.gov/plain-language-name
- [x] Enable the new menu in the Menu Settings for these Content types
   - [x] event
   - [x] event_listing 
   - [x] health service listing
   - [x] leadership listing 
   - [x] locations listing
   - [x] news release - no menu settings available as Manila content creator / publisher 
   - [x] news release listing
   - [x] publication listing
   - [x] staff profile - no menu settings available as Manila content creator / publisher
   - [x] story - no menu settings available as Manila content creator / publisher
   - [x] story listing
   - [x] VAMC operating status
   - [x] VAMC billing and insurance
   - [x] VAMC facility
   - [x] VAMC system
   - [x] VAMC medical records office
   - [x] VAMC system policies page
   - [x] VAMC register for care - 
   - [x] VAMC VA police
   - [x] VAMC detail page - as Manila editor in Tugboat, Manila VA Clinic is not present in the list of menu options - should be resolved by #19199 
- [x] Export the config file and create a PR to merge it into the va.gov-cms repo https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19193

### Create initial VAMC System Drupal entities [CMS helpdesk or Sitewide team]
- [x] Add a new Term in the [Sections taxonomy](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview) - https://prod.cms.va.gov/section/vha/vamc-facilities/manila-va-clinic
   - [x] Nest the term under VHA > VAMC Facilities > VISN ##
   - [x] Name = VAMC system plain language name
   - [x] As you create all the subsequent Drupal entities, assign them to this Section
- [x] [Add a VAMC System](https://prod.cms.va.gov/node/add/health_care_region_page) - https://prod.cms.va.gov/manila-va-system
   - x ] Fill out all required fields
      - [x] Meta description = placeholder?
      - [x] Banner image = placeholder?
      - [x] GovDelivery ID(s) = placeholder?
      - [x] Menu settings > Menu link title = VAMC system plain language name
      - [x] Menu settings > Parent link = `<VAMC system plain language name>`
      - [x] System menu = VAMC system plain language name

### Create one copy of each of these hardened VAMC content types [CMS helpdesk or Sitewide team]

**URLS BELOW HAVE ALL BEEN UPDATED TO USE /manila-va-clinic/ as the root**

 - [x] Parent link = `<VAMC system plain language name>` -- **In the sitemap, Dave has called out:** we don't know if Manila can use these as-is, , if not all the required fields & Centralized Content don't apply to Manila. They may want to archive these 4 hardened pages, and instead: make a stand-in page from a VAMC Detail Page template. (This is what Lovell tricare does)
    - [x] VAMC System Billing and Insurance - https://prod.cms.va.gov/manila-va-clinic/billing-and-insurance
    - [x] VAMC System Medical Records Office - https://prod.cms.va.gov/manila-va-clinic-system-node/medical-records-office
    - [x] VAMC System Operating Status - https://prod.cms.va.gov/manila-va-clinic-system-node/operating-status
    - [x] VAMC System Register for Care - https://prod.cms.va.gov/manila-va-clinic-system-node/register-for-care
 - [x] ~Parent link = SERVICES AND LOCATIONS~ - N/A bc a11y is advocating to stop using the fake headings that aren't links in the sidenav
    - [x] Health Services List - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services
    - [x] VAMC System Locations List - N/A for Manila
 - [x] ~Parent link = NEWS AND EVENTS~ - N/A bc a11y is advocating to stop using the fake headings that aren't links in the sidenav
    - [x] Events List - https://prod.cms.va.gov/manila-va-clinic-system-node/events
    - [x] News Releases List - https://prod.cms.va.gov/manila-va-clinic-system-node/news-releases
    - [x] Stories List - https://prod.cms.va.gov/manila-va-clinic-system-node/stories
 - [x] ~Parent link = ABOUT VA [REGION NAME]~ - N/A bc a11y is advocating to stop using the fake headings that aren't links in the sidenav
    - [x] Leadership List (will need to be moved later) = https://prod.cms.va.gov/leadership
    - [x] VAMC System Policies Page - https://prod.cms.va.gov/manila-va-clinic-system-node/policies
    - [x] VAMC System VA Police page - https://prod.cms.va.gov/manila-va-clinic-system-node/va-police

### Clone (from where?) these semi-hardened VAMC detail pages [CMS helpdesk or Sitewide team]
- [x] Parent link = `<VAMC system plain language name>`
  - [x] Make an appointment  - https://prod.cms.va.gov/make-an-appointment
  - [x] Pharmacy - https://prod.cms.va.gov/pharmacy
- [x] Parent link = SERVICES AND LOCATIONS / Health Services List - **N/A for Manila**
  - [x] Caregiver support - N/A for Manila they do not want this
  - [x] Homeless Veteran care - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/homeless-veteran-care
  - [x] LGBT Veteran care - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/lgbtq-veteran-care
  - [x] Mental health care - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/mental-health-care
  - [x] Minority Veteran care - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/minority-veteran-care
  - [x] Patient advocates - https://prod.cms.va.gov/patient-advocates
  - [x] Returning service members - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/returning-service-member-care
  - [x] Suicide prevention - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/suicide-prevention
  - [x] Women Veteran care - https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/women-veteran-care
- [x] Parent link = ABOUT VA [REGION NAME] - **N/A for Manila**
  - [x] About us - https://prod.cms.va.gov/manila-va-system/about-us
  - [x] Programs - https://prod.cms.va.gov/manila-va-system/programs
  - [x] Research - https://prod.cms.va.gov/research
  - [x] Work with us - https://prod.cms.va.gov/work-with-us
  - [x] Contact us - https://prod.cms.va.gov/contact-us-0
- [x] Parent link = ABOUT VA [REGION NAME] / About us
  - [x] Mission and vision - https://prod.cms.va.gov/about-us/mission-and-vision
  - [x] History - https://prod.cms.va.gov/about-us/history
  - [x] Performance - https://prod.cms.va.gov/performance
- [x] Parent link = ABOUT VA [REGION NAME] / Work with us
  - [x] Jobs and careers - https://prod.cms.va.gov/work-with-us/jobs-and-careers
  - [x] Internships and fellowships - https://prod.cms.va.gov/work-with-us/internships-and-fellowships
  - [x] Volunteer or donate. - https://prod.cms.va.gov/work-with-us/volunteer-or-donate
  - [x] Doing business with us - https://prod.cms.va.gov/work-with-us/doing-business-with-us

### Find any existing VAMC facilities that belong to this system [CMS helpdesk or Sitewide team]
- [x] Set them to the appropriate Section - https://prod.cms.va.gov/manila-va-clinic
- [ ] Set their Parent link settings to SERVICES AND LOCATIONS / Locations -- **N/A for Manila**

### Menu configuration and clean up [CMS helpdesk or Sitewide team]
- [x] Go to [Content / Menus](https://prod.cms.va.gov/admin/structure/menu)
- [x] Find the relevant menu and select edit menu
- [x] Ensure all menu links are nested in the proper place
- [x] Set some menu links to disabled 
- [x] Consult [VAMC sitemap in sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EblgAS21OUtHloKK3a8ZvNIBHzV1S6uO2l4hj4dqYG0avQ?e=J8UVZh) for menu settings --- **MANILA IS DIFFERENT** and has its own [sitemap](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EdEKl_6X5vRDs7uTjg5tMNUBfXEsWuK834vmp7Hs4FZXZQ?e=b7juyL). Dave verified the menu is correct for Manila.
- [x] Enable the menu in [Menu Breadcrumbs](https://prod.cms.va.gov/admin/config/user-interface/menu-breadcrumb) module - will happen via #19199 
- [x] Update CONTENT BUILD FILE with the menu - will happen via #19273 

### User set up [CMS helpdesk]
- [x] Create users if need / assign users to the appropriate section [link to KB article] - https://cms-efaris8nl6pxlah9ngsycnqtlqfhe99t.ci.cms.va.gov/user/2199?check_logged_in=1

### VAMC editor tasks
- [x] Complete training if they haven't already
- [x] Do all the things listed [VA Medical Centers (VAMCs) KB](https://prod.cms.va.gov/help/vamc)
- [x] Do we have an editor facing checklist for content entry / tasks that gate publishing like we do for VBA?
- [x] Confirm when ready to publish

### VHA DM 
- [x] Clarify gates for publishing: VHA DM (Justin) is comfortable letting Editor publish as soon as Facilities team clears blocking issues and Editor is ready
- [x] Verify any necessary redirects - right now https://www.visn21.va.gov/locations/manila.asp redirects to https://department.va.gov/integrated-service-networks/visn-21/. We will want to re-redirect to the modernized page when it's published. We need a ticket to track changing that redirect and implementing about 

### Engineering team
- [x] Complete blocking tickets
  - [x] #19273 
  - [x] #19199 
  - [x] #19280
- [x] Publish in Tugboat
- [x] Verify all pages, paths, IA, menus, menu links. 

#### Do we need?
- [x] Lighthouse coordination for service push? Asked here: https://dsva.slack.com/archives/C02BTJTDFTN/p1729873924890329

### LAUNCH
- [x] Tell Editor they can publish and notify VHA DM
- [x] Complete #19282 
- [x] Complete #19570 
- [ ] Working & can notify Editor: none show left sidenav til #19762 resolves, but breadcrumbs work:
  - [ ] Story pages
  - [ ] News release pages
  - [ ] Events
- [ ] Needs more work
  - [ ] Staff profile pages - Leadership left sidenav link is incorrect, #19992 
    - [ ] New Staff profile does not appear on Leadership listing. Can include in #19992 or needs a new ticket?
  - [ ] #19762 (CMS AP team)

**Comment by jilladams** [comment]
Manila section & content in it: https://prod.cms.va.gov/admin/content?title=Manila&type=All&moderation_state=All&owner=1187

**Comment by jilladams** [comment]
Questions that may affect Manila or may be bigger picture for the runbook template itself: 

1. Menus: there are content types shown where the menu should be added, but if I'm a Content creator / publisher for the Manila section, I don't see menu options on those content types at all. Do we need to make the menu / content type relationship if the relevant editors can expose things to the menu anyway? Or is that bc Admin should be doing the menu pieces?

**Comment by davidmpickett** [comment]
> 1 Menus: there are content types shown where the menu should be added, but if I'm a Content creator / publisher for the Manila section, I don't see menu options on those content types at all. Do we need to make the menu / content type relationship if the relevant editors can expose things to the menu anyway? Or is that bc Admin should be doing the menu pieces? This may need a runbook edit as well.

I was also confused why we enabled have Menu settings on these content types. However, all other VAMC system menus are enabled. In lieu of strong evidence that it is a problem, I opted for consistency with previous systems. If it ain't broke, don't fix it mentality.

- [ ] news release - no menu settings available as Manila content creator / publisher 
- [ ] staff profile - no menu settings available as Manila content creator / publisher
- [ ] story - no menu settings available as Manila content creator / publisher

**Comment by davidmpickett** [comment]
> 2. Other Programs pages use the path /system/programs. This one was set to auto, /programs. I updated it to https://prod.cms.va.gov/manila-va-system/programs, but we need to change if that's not right.

Good catch! I wasn't sure if the Programs page should automatically get the correct alias, but wasn't because of other things not being fully configured. But looking at some other Program pages, they do seem to be manually over-riden, so the runbook should relfect that step.

**Comment by davidmpickett** [comment]
> - [ ] VAMC detail page - as Manila editor in Tugboat, Manila VA Clinic is not present in the list of menu options

I think that will be resolved by this ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19199

**Comment by davidmpickett** [comment]
> 4. Can @davidmpickett help confirm the IA for the menu, based on content strategy? https://prod.cms.va.gov/admin/structure/menu/manage/manila-va-clinic - it seems to have been strategically built the way it is , but I have questions about why some things are where they are, so not 100% sure on status of that part of the checklist

The source of truth for this is the [Manila sitemap in sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EdEKl_6X5vRDs7uTjg5tMNUBfXEsWuK834vmp7Hs4FZXZQ?e=b7juyL). Happy to explain why this differs from the general [Sitemap of a VAMC system in sharepoint](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EblgAS21OUtHloKK3a8ZvNIBHzV1S6uO2l4hj4dqYG0avQ?e=J8UVZh).

**Comment by davidmpickett** [comment]
> 3. I noted the links that were in use for many of these pages. Should the runbook include updating them to use the correct system slug? Or we expect the editor to do that?

I think by this you mean things like how the [Women Veteran Care](https://prod.cms.va.gov/manila-va-clinic-system-node/health-services/women-veteran-care) page has links to the Mental health care and Patient Advocate pages? And those links are still pointing to the Pacific Islands system I copied the pages from?

Even if we expect the editor to do it, might be good to add to editor steps in the runbook. At very least, a good thing for the change management

**Comment by davidmpickett** [comment]
> 6. " Enable the menu in [Menu Breadcrumbs](https://prod.cms.va.gov/admin/config/user-interface/menu-breadcrumb) module - 9/19: not done in prod yet for Manila. should it be?

Yup, it's listed in the overflowticket https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19270

**Comment by davidmpickett** [comment]
> 7. "Update CONTENT BUILD FILE with the menu" -- ??
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19273

**Comment by jilladams** [comment]
Under normal circumstances, it would be: 
System = /PLACE-health-care
Facility =  /PLACE-health-care/FACILITY-NAME

Manila is weird because the Facility IS the root of the system. So:
System = will not publish, does not get a FE page. How? There's a FE ticket to figure this out. #19272 
Facility =  /manila-va-clinic

SO: all paths for all the Manila pages should include /manila-va-clinic/ as the root.

**Comment by jilladams** [comment]
Next steps: 
1. Jill to fixup paths and check for content references to Pacific Healthcare in node bodies, since that's what we copied.
2. Need to port the bigger picture Runbook changes back to the runbook ticket. - @davidmpickett 
3. Need to share the Manila content link to Justin, Michelle to pass on to the Editor. cc Helpdesk. BE SURE TO INCLUDE: 
     4. **Do not publish** until content is complete. Please reach out to (?) 

Link of Manila VA content that the Editor will need.
https://prod.cms.va.gov/admin/content?title=&type=All&moderation_state=draft&owner=1187

Emailed Justin to clarify how we get things to the Editor. (Via VHA DM or Helpdesk.)

**Comment by davidmpickett** [comment]
@Agile6MSkinner @jilladams FYI - I moved all notes here about updates to make/consider to the runbook over to the runbook ticket
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/15264 Gonna unassign myself from this ticket now

**Comment by jilladams** [comment]
Content updates are done, to fix path and remove Pacific Island info, where it was sensible to do so. 

## Pages where I cannot modify path as admin
Billing/Insu - https://prod.cms.va.gov/node/72610/edit
Med records - https://prod.cms.va.gov/node/72697/edit 
Operating status - https://prod.cms.va.gov/node/72699/edit 
Register for care - https://prod.cms.va.gov/node/72706/edit
Top task - https://prod.cms.va.gov/node/72703/edit 
Police - https://prod.cms.va.gov/node/72704/edit 

Before those get published, if they do, we need to figure out whether we can modify the path. I suspect the paths are supposed to be autobuilt for these based on section, using system node path, but that's not gonna work for Manila. I'll stub a ticket.  (FYI @Agile6MSkinner )

**Comment by jilladams** [comment]
We decided https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19227 is not launch blocking.

**Comment by jilladams** [comment]
Today I yolo'ed and Published > Archived the production System node, since that had not yet been done and is a requirement for everything else to work.

**Comment by jilladams** [comment]
Doing Tugboat content review 
after launch blocking changes are done, we think: https://dsva.slack.com/archives/C0FQSS30V/p1729611500413259

# Takeaways for follow up: 

## Performance page: appears as a not clickable link in the left sidenav, with current IA / menu setup: 
![Image](https://github.com/user-attachments/assets/e8a38ff2-9dc0-4188-b0ae-120dcb01d648)

## Register for care 404s
* CMS register for care node:
published, seems ok, using Manila VA Clinic system in <> as menu parent: https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/node/72706/edit
* Register for care page 404s in the FE: https://web-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-clinic/register-for-care

Make an appointment is set up the same way, but works: 
* CMS Make an appt: https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/node/72716/edit
* FE: https://web-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-clinic/make-an-appointment/

![Image](https://github.com/user-attachments/assets/9f7a34e5-85f5-4a35-b255-a354e524da22)

**Comment by davidmpickett** [comment]
- Stories
- Events
- Staff Profiles
- New releases

All of these might need a fix similar to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19280

**Comment by davidmpickett** [comment]
> ## Register for care 404s
> * CMS register for care node:
>   published, seems ok, using Manila VA Clinic system in <> as menu parent: https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/node/72706/edit
> * Register for care page 404s in the FE: https://web-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-clinic/register-for-care
> 

@jilladams This may be specific to your environment. I'm not sure if the work @omahane did in #19280 works on lower environments. On Prod the Register for Care page in Drupal has the correct path https://prod.cms.va.gov/manila-va-clinic/register-for-care

Your tugboat still has it with the system URL path. [/manila-va-system/register-for-care](https://main-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-system/register-for-care)

**Comment by jilladams** [comment]
Hm, good catch. I thought I built my Tugboat after Prod content changes had all shipped, so it should have had all the same settings / paths as prod, with the only difference being what was published / not published. But clearly not so. I'm gonna rebuild it in order to make that true, and rebuild the FE, to confirm.

**Comment by davidmpickett** [comment]
@jilladams That was my initial thought too, that if you rebuilt Tugboat it would start working, but actually I think that the way @omahane made these updates means they will not port to lower environments. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19280#issuecomment-2430012608

**Comment by davidmpickett** [comment]
@jilladams MEA CULPA. It was just a Tugboat issue. I forgot about the lag between deploys and base previews rebuilding etc. etc. @omahane and I just looked at your Tugboat and it's fine now

**Comment by jilladams** [comment]
## TUGBOAT TESTING ITEMS 
Testing against Sitemap in Sharepoint, testing notes are documented there as well. 


1. Manila VA Clinic page: Title metatag is `Manila VA Clinic | Manila VA Clinic | Veterans Affairs`. Need to assess if launch blocking. -- @mmiddaugh @Agile6MSkinner @davidmpickett 
2. Operating Status: has `| Manila VA Clinic` tacked to the end of the otherwise correct breadcrumbs. Not launch blocking / will get ticketed (matches other VAMCs in prod, e.g. https://www.va.gov/augusta-health-care/operating-status/ , [related slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1729809509395989))
3. Performance & Leadership: don't appear under About Us in menu / path. Rebuilding tugboat to verify if still broken after path updates. If so: is launch blocking to fix but I think they'll be ok after rebuild.

### Changes I made to the menu
Reordered menu items to match the sitemap order, including nesting Leadership and Performance under About Us.
Tugboat menu: https://cms-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/admin/structure/menu/manage/manila-va-clinic
Prod menu: https://prod.cms.va.gov/admin/structure/menu/manage/manila-va-clinic

### Changes I made to the sitemap
* Policies / VA Police pages: marked Menu items disabled and updated in the Sitemap, since Editor said they will not be needed
* Updated "Returning service members" to "returning service member care" [to match other VAMCs](https://prod.cms.va.gov/admin/content?title=Returning+service+member&type=All&moderation_state=All&owner=All). (This was already true in the content on prod for Manila, just not in the sitemap)

**Comment by jilladams** [comment]
#1 page title is not launch blocking per Michelle. 

#3 is now working: pages appear correctly in the About Us section with correct crumbs, Title, and path.
https://web-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-clinic/about-us/performance/
https://web-xwykohumwbnvcp90arpvpzfkcilh2ngo.demo.cms.va.gov/manila-va-clinic/about-us/leadership/

Letting Justin know that editor is clear to make / publish everything with the exception of Stories / Staff / Events / News Releases.

**Comment by jilladams** [comment]
Since https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19762 is the last item remaining here, and CMS team has said they'll own that, I'm closing this.
