### ISSUE TITLE
Bug: Drupal: Events can be saved without date / time

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19284]
## Description 

On Sept 19, 2024 content release broke due to an Event that was saved without a date or time: 
* Node: https://prod.cms.va.gov/west-palm-beach-health-care/events/72882
  * Was published on creation / had never been edited
* Slack thread where CMS team found the faulty node: https://dsva.slack.com/archives/CT4GZBM8F/p1726766076344879?thread_ts=1726762852.899099&cid=CT4GZBM8F

CMS team just archived the node. We do not know how this came about, and the editor told Helpdesk they did not have any trouble while creating the event: https://va-gov.atlassian.net/issues/VAHELP-8035. 

### Repro
We need to figure out if we can repro the issue

- @dsasser says "The only way I know of to save an Event without a date is by editing the repeating occurrences of a repeating event and removing/disabling the first one. There might be other ways that we haven't discovered."

### Maybe related, maybe not
You can also save an Event without required location information
* We made a fix: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17426
* The fix won't work bc of the client-side validation settings, which CMS now does not intend to change from being globally enabled but we _do_ need to help redefine the work to include a black list for forms that can be excluded from global enablement (?): https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17896#issuecomment-2297315760

### Tasks

- [ ] Try to repro
- [ ] Figure out if its the same clientside validation root cause or not (am I off base here?)
- [ ] If it is, then what? 
- [ ] If it's not, fix it.

## ACs

- [ ] Events can't be saved without date and time

**Comment by jilladams** [comment]
I tried everything I could think of in a Tugboat to cause this to happen before a 1st successful save, as this editor (who doesn't have Clone permissions). 

I couldn't repro so far.

**Comment by TroyCMSSupport** [comment]
@jilladams I have heard back from the Editor who created the Event - "If I am placing in events that repeat, I do get a prompt if I forget to add something in."

**Comment by mmiddaugh** [comment]
If this can't be reproduced - let's close it as a no-op
