### ISSUE TITLE
[EPIC] VAMC real-time banners that do not use content-build

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19302]
## Background
https://dsva.slack.com/archives/C0FQSS30V/p1727108182414679

VA would urgently like to pursue methods for getting critical content out to production faster, for things that should not / cannot wait for content-build when it's having problems.

This was introduced at the end of Q3 2024, and will be a Q4 priority.

## Scope
MVP: VAMC banners, not including situation updates

Additional phases can be scoped when we arrive at a methodology to achieve MVP.

MVP is _not_ for full-width banners first, but for VAMC banners _without_ situation updates. They are similar, but different. 

* Live VAMC banner with situation update: https://prod.cms.va.gov/va-north-floridasouth-georgia-health-care/vamc-banner-alert/2024-10-08/hurricane-milton-operational-status-update-for-nfsgvhs
* Example where it appears on the FE: https://www.va.gov/north-florida-health-care/ - by default, the situation update appears on any VAMC system page, for the System checked on the VAMCBwSU (?) node

These ride along with the header: 

![Image](https://github.com/user-attachments/assets/9428ae26-bed3-42bb-97fd-110aa1f20fd2)

---
### High level work required to complete the epic
- [ ] Analytics review
- [ ] Backlog review
- [ ] Content audit
- [ ] FE Design
- [ ] Usability research
- [ ] Drupal
  - [ ] CMS Design
  - [ ] New config, fields, or entities
    - [ ] Content modeling is required
  - [ ] Revisions to existing config, fields, or entities -- Content modeling _may_ be required, tbd scope
  - [ ] Editor Change management is required in either case
  - [ ] Knowledge Base article creation or updates are required in either case
- [x] Vets-api (Ruby)
  - [x] New API or endpoints
    - [x] Datadog monitoring is required 
  - [ ] Revisions to existing API / endpoints
    - [ ] Datadog monitoring updates may be required, tbd the scope of changes 
- [x] Content-build (FE) 
  - [ ] New templates -- try to avoid this and build in Next if possible
  - [x] Revisions to existing templates
- [ ] Next-build (FE)
  - [ ] New template(s)
  - [ ] Migration of existing content-build template(s)
  - [ ] Revisions to existing Next templates
- [x] Vets-website (FE)
  - [x] New React app or widget
  - [ ] Revisions to existing apps, widgets, templates, or styles
- [ ] Collab Cycle - required for any new application, usability research, major architectural change to an existing product. If you're not sure, ask Governance team.

---
## Decision log
* **[2024-10-09]** We will start with banners. This content type also supports "Situation updates" which push emails to GovDelivery. We will not include this functionality in MVP. _ONLY_ banners will publish with the new API endpoint functionality.

**Comment by timcosgrove** [comment]
Just to put it out there: we have a lot of the pieces of a solution for this in Next Build / CMS already, and **it would not require using Next Build**:
- There is an API endpoint that returns all the banner data the CMS knows about for an individual path: https://prod.cms.va.gov/api/v1/banner-alerts?path=/asheville-health-care/locations/charles-george-department-of-veterans-affairs-medical-center
  - This could be connected up to vets-api to provide realtime banner data for an individual page
- There are banners components currently in Next Build to render this data: https://github.com/department-of-veterans-affairs/next-build/tree/main/src/templates/common/banners
  - These could be moved to vets-website for more general use; they do not need to remain in Next Build

The basic work would be:
- wire up the existing CMS endpoint to vets-api so that it data can be retrieved in realtime
- move the banner components to vets-website
- set up both Content Build and Next Build to use these components and endpoints

Or, use parts of this. At a minimum, it feels like the API endpoint already exists in CMS and replicating it would be wasteful, unless there are requirements for this effort that are fundamentally incompatible with the existing endpoint.

**Comment by dsasser** [comment]
> Just to put it out there: we have a lot of the pieces of a solution for this in Next Build / CMS already, and **it would not require using Next Build**:
> 
> * There is an API endpoint that returns all the banner data the CMS knows about for an individual path: https://prod.cms.va.gov/api/v1/banner-alerts?path=/asheville-health-care/locations/charles-george-department-of-veterans-affairs-medical-center
>   
>   * This could be connected up to vets-api to provide realtime banner data for an individual page
> * There are banners components currently in Next Build to render this data: https://github.com/department-of-veterans-affairs/next-build/tree/main/src/templates/common/banners
>   
>   * These could be moved to vets-website for more general use; they do not need to remain in Next Build
> 
> The basic work would be:
> 
> * wire up the existing CMS endpoint to vets-api so that it data can be retrieved in realtime
> * move the banner components to vets-website
> * set up both Content Build and Next Build to use these components and endpoints
> 
> Or, use parts of this. At a minimum, it feels like the API endpoint already exists in CMS and replicating it would be wasteful, unless there are requirements for this effort that are fundamentally incompatible with the existing endpoint.

A Slack conversation around this can be found [here](https://dsva.slack.com/archives/C52CL1PKQ/p1729182302225659).

**Comment by jilladams** [comment]
Meeting with Bryan, Eli, Christian and Laura / Michael / me. 

## UX concern
The banners code in FE lives in content-build completely. 
We originally planned to introduce a static content-build element that vets-website could hook into to pre-load content. 
But: everything in VAMC views is only content-build in the static pages. We don't have a means to inject vets-website. 
This would require the client's browser to send a call for the JS to get the banner. That means: lag time for the user while the browser fetches data.  The entire page has to render first, then the JS call to return the banner.
Time required to make that call depends on the user's browser and internet connection, so timing may vary. Could be up to 5 seconds on bad wifi / mobile. UX for the banner snapping in will be a jump. (Sort of like what we see on TeamSites with the injected header showing up, when it's slow.)

### Might be ok though
Per Eli: in our current structure, this UX flash after JS loading is not out of the ordinary. 
In content-build: create a data element that React looks for from vets-website and loads itself into. Those asynchronous calls are unavoidable within our structure. So: this UX issue might be par for the course / not be the worst thing, given the reasons for this project. 

Also: when vets-website does load in async, it will bring with it all of the DST components / dependencies.

Per Michael: migration to AP will affect this once we move VAMCs to AP. 
Alternative is a near-term fix to honor the needs, so we can think of it as stop-gap. And then it's probably ok if it's not perfect. (Next Build will still be making an asynchronous call but it’ll be to Drupal as opposed to vets-api and that still has flashiness.)

### UX question to confirm: skeleton spaces
Should we create a "skeleton space" to hold space for this banner, to prevent the jump down when it loads. 
No, we think, and need to confirm with @thejordanwood . So far: that's an antipattern for VA. Also: it would be more frequent to hold space for a banner that doesn't exist / have to disappear it, than it would be to _not_ hold space, and have the page jump down when banner loads. (Also the jumping down works in favor of the banner intention, to get user's attention.)

## Facts of deploy
Content release: builds main every hour or on certain types of content changes, including VAMC BwSU. (Content-build rebuilds what _is_ main from code, daily. SO: templates daily; data hourly or more.)

**Comment by thejordanwood** [comment]
I agree that we don't need to create a skeleton space for this banner. Having the page jump down when the banner loads is currently the existing behavior for VA banners and can be seen with the natural disaster banner that's on the homepage right now ([example](https://www.va.gov/)).

cc: @jilladams @davidmpickett

**Comment by mmiddaugh** [comment]
**Update 11.5.2024**
- this work has been urgently prioritized to allow banner content to move more quickly to production outside of content build
- work is tracking toward completion by the end of the month

**Comment by mmiddaugh** [comment]
**Update 12.16.2024**
This work was approved during Staging review on Friday, December 13 and is expected to ship this Wednesday, the 18th

**Comment by Agile6MSkinner** [comment]
Work complete
