### ISSUE TITLE
[ZSF] Send a Slack notification when the TIC blocks facilities data pushes

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#19369]
## User Story or Problem Statement

As a provider of data to the Lighthouse API, the CMS should notify the Facilities team when the Trusted Internet Connection (TIC) is not allowing our requests through. 

In the case of a failure to push data from the CMS to Lighthouse due to the TIC, we should send a message to Slack as described in [this analysis of possible failure points](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19250#issuecomment-2383935878).

## Acceptance Criteria
- [ ] When the TIC is responsible for blocking requests from the Post API Queue push, a Slack notification is generated.
- [ ] Alerts sent to Slack channel #facilities-monitoring
- [ ] Add notes here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-pages/technical-documentation.md#alerting-and-monitoring

## Implementation steps
Update lines 117 ff. of `va_gov_post_api/src/EventSubscriber/QueueItemProcessedEventSubscriber.php` to add Slack notification when the following is true:
```
 if ($response_code === 200) {
      if ($response_phrase !== 'OK' || $size > 0) {
```

## Testing steps
- [ ] I outlined testing steps in an earlier PR: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/15667
- [ ] Test POST API queue data push

**Comment by jilladams** [comment]
@omahane is Drupal capable of generating these notices to Slack? Or does that need to happen somewhere else? 

FYI @Agile6MSkinner : queued this for Next Refinement, as it's ZSF work

**Comment by jilladams** [comment]
@omahane  I just noticed on the PR that the notifications will go to the #cms-notifications channel, but ACs specify `Alerts sent to Slack channel #facilities-monitoring`.  The idea there being: who's gonna notice it in the mud of the CMS channel, vs. our team watching for our own issues in the Facilities channel. 

But: are there limitations on notices coming out of CMS that they can't go to other channels?

**Comment by omahane** [comment]
I'm using the Slack webhook that's in the ENV, to which I don't have access. In fact, Tim gave me the URL. It's currently the one we use for this module, anyway. If we have to move one, we'll have to move both. But for now . . . let's leave well enough alone.

**Comment by omahane** [comment]
If we want to use a different Slack URL to send to a different channel, I think CMS will have to set that up.

**Comment by jilladams** [comment]
Christian confirmed he and the CMS team both watch the cms-notifications channel, so we'll leave it. 

Re: documentation, everything about the migration lives in the migration readme, so I added a note about this monitor there: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/migrations-facility.md#monitoring

Closing.
