### ISSUE TITLE
EPIC: Support facility migration iteration for new facilities that are not in VAST

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1939]
### Scenario 1

DoD (Tricare) facilities at Lovell

There are 3-4 facilities at Lovell that are not in VAST. 
   - [ ] https://www.lovell.fhcc.va.gov/locations/USSOsborne.asp
   - [ ] https://www.lovell.fhcc.va.gov/locations/USSRedRover.asp
   - [ ] https://www.lovell.fhcc.va.gov/locations/USS_Tranquillity.asp
   - [ ] https://www.lovell.fhcc.va.gov/locations/FisherMedicalDentalClinic.asp (need to check to see about this one)

### Scenario 2 (not in scope)

<details><summary>VAMC facilities that take months to get into VAST (not in scope for this epic)</summary>

Facilities don’t get into VAST for months, sometimes, so we have a number of facilities with ID like “0000”. The facilities team needs a governance, migration, and editorial experience plan for the facilities that 

[Slack thread]( https://dsva.slack.com/archives/C02686M6K6X/p1646921537414249)

![Teams chat about adding a facility not in VAST](https://user-images.githubusercontent.com/643678/157693773-523f6d81-3f97-458a-9bc3-38c078494a00.png)

</details>

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
@EWashb think CM will be needed this quarter?

**Comment by EWashb** [comment]
@ContentBrewmaster this one would be on the facilities team, not Sitewide CMS. @dsinla?

**Comment by ContentBrewmaster** [comment]
Sorry @EWashb linking the Collab cycle note incorrectly.

**Comment by JayDarnell** [comment]
@dsinla @swirtSJW all subtasks for this epic are complete and the facilities in question were manually added to production in October. Can we close this epic?

**Comment by dsinla** [comment]
@JayDarnell I'm going to say YES as far as I'm concerned.

**Comment by JayDarnell** [comment]
Closing as discussed.
