### ISSUE TITLE
Manila: Programmatically prevent the Manila VAMC system node from building a FE page

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19406]
## Description 
For Manila: 
* System must exist, for menus and Operating status to work, as well as some pages.
* VAMC System should never build in the FE. The VAMC Facility node acts as the system level page, for Manila. 

## Implementation plan
* We have short term Published > Archived the VAMC system node
* This ticket will then prevent the system from being able to build to the FE. 
* We think this should happen in content-build as a pre-publishing step, to prevent the System node from creating a page.

## ACs
- [x] Manila VAMC System node is published in Drupal, but no FE page generated
- [x] Manila VAMC System page can't make it through content-build to the FE
- [x] Regression test FE in a tugboat and ensure that all URLs match the [IA document in SharePoint.](https://dvagov.sharepoint.com/:x:/s/SitewideContract/EblgAS21OUtHloKK3a8ZvNIBHzV1S6uO2l4hj4dqYG0avQ?e=J8UVZh)AMC
- [ ] The Manila VAMC Facility content displays as intended at https://www.va.gov/manila-va-clinic/

**Comment by jilladams** [comment]
I don't know if this will be a Drupal solve or a content-build solve, so I tagged both for now, til we get a chance to refine it with the team.

**Comment by jilladams** [comment]
@Agile6MSkinner I'd love for us to get this into Sprint 16 if we can. It's a risk for making Manila weird in prod, until we programmatically make it impossible to screw up (via this ticket).

**Comment by jilladams** [comment]
We might need to extend scope to also disallow System health services publishing. Tagged to discuss in scrum here: https://dsva.slack.com/lists/T03FECE8V/F079GFKN50D?record_id=Rec07S4SRP5JB. Depending on that convo, scope of this ticket might need an update.

**Comment by davidmpickett** [comment]
Noting that the [Lovell solution to this this problem](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12776) seems to be intrinsically tied to the Lovell cloning logic, so the Manila solution will be different and looking at what is done for Lovell may end up be more confusing

**Comment by SnowboardTechie** [comment]
This has yet to be started but I expect will move smoother than #19992 has now that I've gotten the chance to get familiar with the content-build for Manila/Lovell

**Comment by SnowboardTechie** [comment]
@jilladams in Sprint 20 I have gotten some code prepared that I believe will handle this [here](https://github.com/department-of-veterans-affairs/content-build/pull/2410). However, the content modeling language does not line up with a "VAMC System page" so I am not certain that the `HEALTH_CARE_REGION_PAGE` I have this trying to eliminate is the correct one. 
Unfortunately CI is failing to build ATT. So for Sprint 21, Once tugboat starts working again and can successfully build me a review instance to test this work, I will be able to follow up with either some automated testing and cleanup, or adjusting this code to focus on a different page content model.

**Comment by SnowboardTechie** [comment]
@davidmpickett thank you for the confirmation and the helpful screenshot! Now I've got an idea of how I can identify the machine names from the CMS for next time 😺

**Comment by SnowboardTechie** [comment]
@jilladams the work is now live to prevent content-build from creating a FE page for Manila's VAMC system nodes. Would you like me to do a production test of this prior to closing or is the tugboat testing that was done enough to consider this complete?

**Comment by davidmpickett** [comment]
@SnowboardTechie Definitely should verify on Prod before closing ticket

**Comment by SnowboardTechie** [comment]
@davidmpickett is there a channel I should be notifying editors/folks prior to publishing incase something goes awry?

**Comment by davidmpickett** [comment]
> [@davidmpickett](https://github.com/davidmpickett) is there a channel I should be notifying editors/folks prior to publishing incase something goes awry?

I'd would suggest giving a heads up in #sitewide-cms-platform in the off chance that this would have a bad interaction with Next Build, but I also see you had Tim Cosgrove approve the PR, so that probably covers that. Editor comms can be after the fact

**Comment by jilladams** [comment]
I'd vote: let's wait til tomorrow (fri) or Monday. CMS team is running an OOB deploy this afternoon, and I'd like to stay out of their way. If we publish early tomorrow, or on Monday, there'll be more support available for anything that might go awry.

**Comment by SnowboardTechie** [comment]
Sounds good. I'll plan on doing the publishing this afternoon once CMS team confirms the OOB deploy completed without issue and will post about it in #sitewide-cms-platform at that time.

Thank you both!

**Comment by SnowboardTechie** [comment]
Actually going to hold off till Monday for testing this. It sounds like the OOB deploy went okay, but they are expecting a quiet successful deploy tomorrow morning so I am going to hold off so that we can be sure all is going smooth there before adding another test into the mix.

**Comment by jilladams** [comment]
We tried to publish, things broke, including the path of the system. 
Christian submitted a PR to fix that, which has not yet deployed.
Once that deploys, we can/should try publishing again with CMS team notice.

**Comment by jilladams** [comment]
@SnowboardTechie path fix successfully deployed last night. We can retry publishing the System next week.

**Comment by davidmpickett** [comment]
@SnowboardTechie Correct! The previous situation where it had to be archived was a workaround rather than a desired state. 

@jilladams @Agile6MSkinner Will you make sure the editor is informed that they no longer need to save it as Archived if they make changes to the System?

**Comment by jilladams** [comment]
Go team!!

**Comment by jilladams** [comment]
Man, we thought we had it.

**Comment by jilladams** [comment]
we published, nothing broke in the build, however: the FE got weird, so reopening. [Slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1739302566107249)

What is happening: 

Entity | Drupal path | FE behavior
--- | --- | --- 
System | https://prod.cms.va.gov/manila-va-system | https://www.va.gov/manila-va-system 404s, expected behavior
Clinic | https://prod.cms.va.gov/manila-va-clinic | https://www.va.gov/manila-va-clinic loads but displays content from the Manila VA system node

![Image](https://github.com/user-attachments/assets/60eeac50-3874-464a-bb3d-5678b38902fc)

**Comment by SnowboardTechie** [comment]
For engineers: It appears the `fieldIntroText` we're receiving for the clinic may be changing when the system node is published. Is it possible that CMS is changing the `fieldIntroText` based on system node status?

**Comment by davidmpickett** [comment]
Hey @SnowboardTechie sticking my nose in to the code here to see if I notice anything strange that might help you debug. Feel free to ignore if this is wildly off base.

In the `processManilaPages` function, there's an IF / ELSE statement that seems to be where the Region page is being excluded from the build. 

```
      if (isManilaVAClinicPage(page)) {
        acc.manilaVAClinicPages.push(page);
      } else {
        // Federal Region Homepage should not be created for Manila VA Clinic
        if (isManillaVaRegionHomepage(page)) {
          return acc;
        }
        acc.otherPages.push(page);
      }
```

But I'm not clear how the ELSE condition would ever be met because `isManillaVaRegionHomepage` function shows that the Region page is, by definition in the IF scope of  `isManilaVAClinicPage`

```
function isManillaVaRegionHomepage(page) {
  return (
    isManilaVAClinicPage(page) &&
    page?.entityBundle === ENTITY_BUNDLES.HEALTH_CARE_REGION_PAGE
  );
}
```

**Comment by davidmpickett** [comment]
> For engineers: It appears the `fieldIntroText` we're receiving for the clinic may be changing when the system node is published. Is it possible that CMS is changing the `fieldIntroText` based on system node status?

I'm not sure I see what you mean here. You seem to be implying that the `fieldIntroText` associated with the System `health-care-region-page` is being published in the template for a VAMC Facilty `health_care_local_facility`. But what I see happening is a `health-care-region-page` template filled with `health-care-region-page`

## Current error state 
![Image](https://github.com/user-attachments/assets/60bca5a4-9ab2-42ac-b6ab-b89ea2d21dad)

## Previous state via wayback
![Image](https://github.com/user-attachments/assets/09ad039c-14a9-4bbd-9029-c0ac937e994e)

**Comment by SnowboardTechie** [comment]
@davidmpickett after seeing your first comment around placement of the blocker, I am pretty sure I was going down the wrong rabbit hole and you're onto something. I'm spinning up tugboat for some testing there

**Comment by davidmpickett** [comment]
FYI I added an AC that I think we missed when originally refining:

- [ ] The Manila VAMC Facility content displays as intended at https://www.va.gov/manila-va-clinic/

**Comment by jilladams** [comment]
From refinement: what we've learned: 
* We cannot reproduce what happened in prod yesterday on a Tugboat, so far. Oy.
* Systems are pervasive. It's harder than we thought to make this setup work with the System published. 
* Content-build's native brittleness is a piece of the puzzle.
* However in next-build: it also was built with the expectation of a published System that has a FE page, and managing things without that will require ongoing artisanal work to support the Manila case. 

So: we are inclined to: 
1. Not change anything else for Manila right now. Let it be a one-off archived system, to keep the FE clinic info stable for now.
    2. Closing this ticket, in that spirit. This was the last ticket from the original Manila Epic, and the epic is closed.
3. Regroup on a plan to convert Manila to be a standard System with facilities in it. @Agile6MSkinner and I can follow up with Michelle for priority of timing.

Go team.
