### ISSUE TITLE
Events listings: QA for production cutover

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19436]
## Tasks

- [ ] Clarify what steps are required to ship
- [ ] Ensure parity between content-build Events listings and Next Event listings at the time we're clear to ship, including: 
    - [ ] VAMC events listings
    - [ ] Outreach and Events listing

## ACs

- [ ] Event listings AP build is verified for parity with production, including
  - [ ] Events filters: Past
  - [ ] Events filters: Upcoming
  - [ ] Events filters: Specific date
  - [ ] Events filters: Date range
  - [ ] Events in progress appearing in Upcoming until event time is complete (EOD or right after, tbd)
  - [ ] Basic event listing metadata presents / is correct on Event listing page
