### ISSUE TITLE
[EPIC] Campaign Landing Page V2 Enhancements 

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#19447]
## Overview

**Initiative brief:** https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/campaign-landing-page/initiatives/2024-v2-clp-enhancements/initiative-brief.md

The Campaign Landing Page MVP was launched in 2021, and a review needs to be conducted to determine whether the MVP was successful, and if not not, what next steps if any should be prioritized.

## Outcome Summary
The opportunity is to validate or disprove effectiveness of the MVP Campaign Landing Page, which will provide insight into possible improvements or enhancements in order to provide the best possible experience for both our Veterans (their caregivers and other users), as well as Content Editors the best experience possible.

**Related/Associated product(s)**
- [Campaign landing page template - product outline](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/campaign-landing-page#campaign-landing-page-template---product-outline)

## Problem
The CLP template does not meet all the original KPIs - especially:
- the capabilities of the CLP template (the various content components) meet the minimum needs of the business stakeholders
- the CMS functionality of the template builder is bug-free and user/author-friendly

### Evidence
* the template is underutilized - 21 CLPs have been created since 9/2021
  * 4 are still in draft, having never been published 
  * 5 have been archived
* expressed editor frustration about the inflexibility of the template
* some CLPs have been created but did not meet stakeholder requirements and were never published 
* a few highly visible CLPs have recently been delayed at the time of launch because of bugs, unexpected behavior, and/or confusion editorial UX

## Product documentation
* **Existing product docs**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/campaign-landing-page

---
### High level work required to complete the epic
- [ ] Analytics review
- [ ] Backlog review
- [ ] Content audit
- [ ] FE Design
- [ ] Usability research
- [x] Drupal
  - [x] CMS Design
  - [ ] New config, fields, or entities
    - [ ] Content modeling is required
  - [x] Revisions to existing config, fields, or entities -- Content modeling _may_ be required, tbd scope
  - [ ] Editor Change management is required in either case
  - [ ] Knowledge Base article creation or updates are required in either case
- [ ] Vets-api (Ruby)
  - [ ] New API or endpoints
    - [ ] Datadog monitoring is required 
  - [ ] Revisions to existing API / endpoints
    - [ ] Datadog monitoring updates may be required, tbd the scope of changes 
- [x] Content-build (FE) 
  - [ ] New templates -- try to avoid this and build in Next if possible
  - [x] Revisions to existing templates
- [x] Next-build (FE)
  - [ ] New template(s)
  - [x] Migration of existing content-build template(s)
  - [ ] Revisions to existing Next templates
- [ ] Vets-website (FE)
  - [ ] New React app or widget
  - [ ] Revisions to existing apps, widgets, templates, or styles
- [ ] Collab Cycle - required for any new application, usability research, major architectural change to an existing product. If you're not sure, ask Governance team.

---

## Decision log
* **[yyyy-mm-dd]**

**Comment by jilladams** [comment]
@mmiddaugh @FranECross @davidmpickett as I'm poking through the repo in prep for migrating to Github Projects, I found an older epic about CLP iteration candidates: #4642 . I know this project has an intentionally limited scope. But while we are talking priorities, it might be a good opportunity to close out that other epic or clean it up for things we still care about / might do someday, vs. things that don't meet the bar and we'll probably never do / could be closed.

**Comment by jilladams** [comment]
Oh - this epic might be a straight dupe at this point? That one says: 

> This issue was updated in September 2024 by Michelle following a few editor conversations and a series of problematic launches
the inflexibility of the template has led to underutilization.
> a few highly visible CLPs have recently been delayed at the time of launch because of bugs, unexpected behavior, and/or confusion editorial UX

This epic contains some more recent narrative, but that one contains tickets. If the tickets are valid, may be easiest to close this as a dupe and update that one where the tickets live. @FranECross holler if I am just confusing things.

**Comment by FranECross** [comment]
@jilladams I added info from this epic to the one that Michelle edited, and added the ticket from this one to that one. Closing. Thanks for noticing the dupe!
