### ISSUE TITLE
[EPIC] Facility Locator progressive disclosure

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19489]
## Top-line Description / Goal(s)
We want to follow existing VA design paradigms, and only display fields that users can interact with, rather than the current Facility Locator behavior of displaying inactive fields.

In addition, the page layout on desktop will change to better align with the look on mobile. This involves switching to a vertical alignment where the map and the user entry fields are side by side.

### User Story or Problem Statement
As a user, I want to see only fields I can interact with, to reduce noise in the UI. 

### Affected users and stakeholders
Veterans using the Facility locator and filtering by services.

### In scope
FE Filter updates per Figma designs

### Out of scope
Facility Locator migration to Next Build
Usability research

## Product documentation
*  [**Designs**](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=963-5630&t=dhwXbmG2v5DZCGxR-4)
* **Existing product docs**: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/facility-locator

---
### High level work required to complete the epic
- [ ] Analytics review
- [ ] Backlog review
- [ ] Content audit
- [x] FE Design - complete: [Layout Revisions page in Facility Locator Figma file](https://www.figma.com/design/GvNVeG9GAXZaBpny7vNxZP/Facility-Locator?node-id=806-27055&node-type=canvas&t=y96mpmvlRg7HEZ9i-0)
- [ ] Usability research - [Amanda K decision: no](https://dsva.slack.com/archives/C06EK4NLGDQ/p1728667051689409?thread_ts=1728601487.426879&cid=C06EK4NLGDQ) 
- [ ] Drupal
  - [ ] CMS Design
  - [ ] New config, fields, or entities
    - [ ] Content modeling is required
  - [ ] Revisions to existing config, fields, or entities -- Content modeling _may_ be required, tbd scope
  - [ ] Editor Change management is required in either case
  - [ ] Knowledge Base article creation or updates are required in either case
- [ ] Vets-api (Ruby)
  - [ ] New API or endpoints
    - [ ] Datadog monitoring is required 
  - [ ] Revisions to existing API / endpoints
    - [ ] Datadog monitoring updates may be required, tbd the scope of changes 
- [x] Content-build (FE) 
  - [ ] New templates -- try to avoid this and build in Next if possible
  - [x] Revisions to existing templates
- [ ] Next-build (FE)
  - [ ] New template(s)
  - [ ] Migration of existing content-build template(s)
  - [ ] Revisions to existing Next templates
- [ ] Vets-website (FE)
  - [ ] New React app or widget
  - [ ] Revisions to existing apps, widgets, templates, or styles
- [ ] Collab Cycle - required for any new application, usability research, major architectural change to an existing product. If you're not sure, ask Governance team.

---

## Decision log
* **[2024-10-11]** No usability research for the updated FL design / progressive disclosure ([Slack](https://dsva.slack.com/archives/C06EK4NLGDQ/p1728667051689409?thread_ts=1728601487.426879&cid=C06EK4NLGDQ))

**Comment by Agile6MSkinner** [comment]
@mmiddaugh We have run into enough UX questions while building this that I am recommending that we include this in staging for user research with services autosuggest.

**Comment by mmiddaugh** [comment]
[Remove progressive disclosure tech debt #20875](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20875) removed from epic which can now be closed
