### ISSUE TITLE
Sitewide: migrate from ZH to Github Projects

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19485]
# Migration
Brain dump: 
## Project

- [x] Create project: https://github.com/orgs/department-of-veterans-affairs/projects/1442/views/1
- [x] Config custom fields
  - [x] sprints
  - [x] points
  - [x] ~Teams?~  Only can have single value, so leaving as Labels
  - [x] Status (sprint board columns
- [x] Config workflows
  - [x] auto add new cms sitewide label issues
  - [x] auto add new team sitewide label issues
- [x] Make a Priority custom field
  - [x] Ask PMs what levels should be
  - [x] Add it to the board card visibility

### Q4 priorities
- [x] Make sure we have a list of tickets within each epic 
  - Used labels to put Epic issue ID on the epic + children (including sub-epics/sub-children): https://github.com/department-of-veterans-affairs/va.gov-team/labels?q=ghp- 
- [x] Import relevant issues into project (Issues tab, check all, select Project from dropdown, 25 per page)
- [x] Build parent/child relationships for each epic
- [x] Map points from GH issue to GHP card
- [x] Map everything to sprint columns

### Remaining va.gov-team tix
Epics: https://github.com/department-of-veterans-affairs/va.gov-team/issues?q=is%3Aissue%20state%3Aopen%20label%3Asitewide%20label%3AEpic
- [x] Make sure we have a list of tickets within each epic 
- [x] Import relevant issues into project (Issues tab, check all, select Project from dropdown, 25 per page)
- [ ] Build parent/child relationships for each epic
- [ ] Map points from GH issue to GHP card

### Remaining va.gov-cms tix
Epics: https://github.com/department-of-veterans-affairs/va.gov-cms/issues?q=is%3Aissue%20state%3Aopen%20label%3Asitewide%20label%3AEpic
- [ ] Make sure we have a list of tickets within each epic
- [x] Import relevant issues into project (Issues tab, check all, select Project from dropdown, 25 per page)
- [ ] Build parent/child relationships for each epic
- [ ] Map points from GH issue to GHP card

### Flagged Facilities
FIgure out: 
- [x] Can we make a board for them?  YES: https://github.com/orgs/department-of-veterans-affairs/projects/1461
- [x] Can tickets live in 2 boards? YES. Done.
- [x] Can boards sync lanes? No, or oly sort of. Only for Closed, and for when ticket is created. Status moves within the sprint board will not sync.

### Left behinds
We have 1131 open sitewide tix across CMS / team repos, and GHP project issue cap = 1200. We can't bring in all our tickets. This is the list of things we are leaving behind: 

- 

## Sprint board
- [x] Confirm lane name revisions with the team
- [ ] Config the sprint card view - which fields to show / hide
- [ ] Config the slices
- [ ] If we did Discipline as a field, we could make Discipline lanes in the board, but: lots of our tix have 2+ disciplines. Talk to team about it.

## Monthly reporting

# Opportunities
## Roadmap
How can we use this for quarterly priorities? 

## Planning
Can we use a view to deal with sprint planning? Look at Oddball template "Planning" view

**Comment by jilladams** [comment]
@FranECross @Agile6MSkinner we have an Opp to add a JIRA-like "priority" field in Github Projects. 
1. Do you want that? 
2. If so, what levels of priority are most useful for planning purposes?

**Comment by Agile6MSkinner** [comment]
@jilladams Yes please. On what to use there, I haven't felt like we've had the most success with MoSCoW, and I'm wondering if we shouldn't move to something with less semantic baggage, like "Critical, High, Medium, Low" or even more simple: "P0, P1, P2, P3"

**Comment by jilladams** [comment]
I was also pondering "Emergent" - a la COVID, or this alternative banners thing. Do you think that's the same as "Critical"?

**Comment by Agile6MSkinner** [comment]
I think "Emergent" is the same thing as "Critical," although the fact that there's even some semantic noise there does lend credence to the idea of P0 - P3, with P1 being the default high priority and P0 being outside-the-norm issues

**Comment by FranECross** [comment]
I like the P0 to P3, but am good with whatever is decided.

**Comment by jilladams** [comment]
- Updated [Epics sheet](https://docs.google.com/spreadsheets/d/1ER9HKSHBS_49xD5idkSMO-x1EncV_sTe4ziw9DHtr4g/edit?gid=1719736890#gid=1719736890) with all PW / Fac epics
 - Tags are aligned with Github
 - There may be other epics that don't have the EPic tag (if it started as an Issue). Think I caught them all
- Applied `ghp-` labels to 
  -  Sitewide backlog by sprint board lane
  - Q4 / Q1tagged epics by issue number

Flagged facilities: started a project: https://github.com/orgs/department-of-veterans-affairs/projects/1461/views/1

**Comment by jilladams** [comment]
@mmiddaugh @Agile6MSkinner @FranECross The automation team has determined they will not have time to write a script to help migrate issues onto Epics in Github Projects. 

I've gathered some information from other engineers at VA and A6 to demonstrate proof of concept on Zenhub side, and on Github side, that it will be possible to automate, but it's beyond my scripting skills. I've attempted to start manual migration, but I truly feel that the hours spent on my part will A) give me carpal tunnel of clicking (for real), and B) it would take an engineer a matter of a few hours to put together a script that would eliminate days of manual migration. 

I am requesting some engineering time in Sprint 18 (before Zenhub license expires during Sprint 19) to assist with this script. If FE folks fiinish their Sprint 17 work before end of sprint, we could pull it into current sprint. Please let me know if you have concerns or objections.

**Comment by FranECross** [comment]
@jilladams Thanks for the valiant attempt, and I heartily approve engineering time. Passing the mic to @Agile6MSkinner @mmiddaugh

**Comment by Agile6MSkinner** [comment]
I agree. I think it's a good use of capacity.

**Comment by FranECross** [comment]
Approved to work on.
