### ISSUE TITLE
[EPIC] [Resources & Support] Phase 1 Drupal updates in support of tags for the new filter

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19492]
### Business Case
Resources and support has expanded to include 137 articles (as of September 2024). As much as 50% of the content from the Benefit Hubs is expected to be moved into Resources and Support as part of that streamlining effort. We expect the number of articles will continue to grow via the ongoing migration of content to VA.gov from legacy sites. Other major content areas are being evaluated, such as health education and materials for non-beneficiary audiences. 

This anticipated growth accelerated the prioritization of this effort to ensure the experience adequately supports discoverability and Veteran understanding.

**Initiative brief:** https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support/initiatives/2024-search-experience-enhancements-Phase-1
    
### Current Veteran experience
- The Resources and Support search component is custom built and allows the Veteran to search resources and support articles _or_ all of VA.gov 
- "Tags" for benefit category, topic, and Audience _might_ appear on articles but aren't consistent, interactive, or use to filter or sort search results.
- The landing page does not adequately support browsing - topic lists are incomplete and manually organized by benefit hub, rather than based on Veteran mental models. 
- The experience contains a number of accessibility defects, as discovered by an [audit performed in May 2024](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17365#issuecomment-2116090937) 

### Current Drupal editorial experience
- Tags representing topic and/or audience group (i.e. beneficiary or non-beneficiary) are not required.
- Options for topic tags are not comprehensive
- Methods to organize content and support findability rely on manual editorial processes, making them inconsistent and/or absent.

### In scope
Phase 1 focus
- addressing accessibility defects - either through design iteration or engineering implementation
- increasing findability 
  - taxonomy enhancements to support functional tagging and which can be extended to other parts of the VA.gov experience
- landing page redesign
- detail page template improvements
- remove tech debt: While digging around in Drupal to update R&S tags, Dave P stumbled across a feature that was built, but seemingly never used. There is code to show a Browse by audience list of links on the R&S homepage.
[Original implementation ticket from 2020](https://github.com/department-of-veterans-affairs/va.gov-team/issues/17276)
[Feature Documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/LC-homepage-requirements.md#browse-by-audience-section) from when R&S was called Learning Center
  - Randi has confirmed: to my knowledge we never used it. When we first launched R&S we were only using the "all Veterans" tag and didn't distinguish between other audiences. So we never used that functionality.

### Out of scope
- The Unified Search team will be implementing the search FE and BE, as well as the new filter
- No silent failures

## Artifacts
* **Existing product docs**: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support
* [R&S Search and Filtering - Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/resources-and-support/research/2024-search-filters/research-report.md)

---
### High level work required to complete the epic
- [ ] Analytics review
- [ ] Backlog review
- [x] Content audit
- [x] Design - Amanda K completed design during Q3 2024, no tracking ticket
- [x] Usability research
- [x] Drupal -- may be required in a separate epic, to complete implementation
  - [x] New config, fields, or entities
  - [x] Revisions to existing config, fields, or entities
  - [x] Editor Change management is required in either case
  - [x] Knowledge Base article creation or updates are required in either case
- [x] Collab Cycle - required for any new application, usability research, major architectural change to an existing product. If you're not sure, ask Governance team.
     
---

## Decision log
- **[2026-01-29] [Fran]** After discussion with Randi, it was decided to update the Initiative document and project tickets to remove tagging/searching, since the Unified Search Team will be performing that work.
* **[2024-10-1]** [R&S Tagging Content Model Review Mtg] 
  - [Veterans Audience (beneficiaries)] [Mikki]: The level of granularity (in mural) she doesn't feel is necessary for what we are doing, e.g., Vietnam War Veterans, WWII Veterans, and Korean Veterans - this detailed breakdown is more like service eras not veteran types. We'll need to do a migration if anything is tagged with these.
  - [Family members & caregivers - Audience non-beneficiaries] [Mikki] Family member and caregivers non beneficiaries - caregivers can also be not family members; especially once we get into the general caregiver services. Danielle agrees with the granularity here.
  - [Multiple names for the same tag] [Mikki] They are aiming to keep it as simple as possible; not going to be able to solve for every single use case they could potentially need. They aren't going to seven variations of housing assistance.
  - [Benefits Taxonomy] [Mikki] Manage the VA benefits taxonomy (it's labeling and nomenclature) separate from the additional content and attributes of the details of the benefit.
- **[2025-10-08] [Jeanna Clark, Veteran Facing Forms]** From [Slack](https://dsva.slack.com/archives/C044AGZFG2W/p1759958467984869?thread_ts=1759859996.650389&cid=C044AGZFG2W) > The mobile order should follow the desktop order. 
* **[2024-10-1]** Research for this effort is a 2024 Q4 priority

**Comment by jilladams** [comment]
Amanda K did design for this initiative, and considered https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18147 Accessibility findings for R&S while updating designs.

**Comment by FranECross** [comment]
Epic's tickets add as sub-issues.

**Comment by mmiddaugh** [comment]
**Update 11.5.2024**

- Content strategy decisions made for landing page
- Designs being finalized to support planned Veteran usability sessions during 4Q2024(CY)
- Drupal engineering following usability expected in 1Q2025(CY)

**Comment by mmiddaugh** [comment]
**Update 2.14.2025**

- Prototype complete
- Veteran research sessions begin the week of Feb 17th

**Comment by davidmpickett** [comment]
@FranECross I moved the Collab Cycle ticket out of this Phase 1 Epic into the new super epic and transferred a lingering sub-issue over to Phase 2. I'll let you do the honor of officially marking this Epic as closed ;)
