### ISSUE TITLE
Drupal 9 upgrade preparation and implementation

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#1950]
### User Story or Problem Statement

Drupal 9 will get new features and bug fixes. 

### Affected users and stakeholders

* All users, and developers. 

### Acceptance criteria

- [ ] the CMS is 100% compatible with Drupal - both infrastructure and code base
- [ ] the CMS has a list of functional tests w/ outlined steps that need to be run manually or matching automated testing
- [ ] the CMS is upgraded to Drupal 9 and has no visual or functional regressions

### Implementation notes

Install Upgrade Status contrib locally/Tugboat to confirm compatibility of code/infra: 
`composer require drupal/upgrade_status`
`drush en upgrade_status -y`
find report at `/admin/reports/upgrade-status`
