### ISSUE TITLE
[EPIC] Benefit hub & Campaign landing pages are showing unpublished "Connect With Us" content

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#19544]
## The Problem
The **Office** content type is being used in two fundamentally opposed ways.
1. It is being used to create a front end page for [Outreach and Events](https://www.va.gov/outreach-and-events/). This way requires having Office content types Published.
2. It is being used to populate content for **Connect With Us** panels that are used on Campaign Landing Pages and Benefit Hub Landing Pages. 
   - https://www.va.gov/pension/
   - https://www.va.gov/initiatives/protecting-veterans-from-fraud/

<details><summary>Example Connect With Us panels</summary>

![Image](https://github.com/user-attachments/assets/53301859-e449-4576-bca3-e5b662c4e433)

![Image](https://github.com/user-attachments/assets/5d5b2ac5-9ad9-48cc-9fbd-c33fcf7fb000)

</details>

- This would be fine if we also wanted those offices (NCA, VBA, etc) with "Connect With Us" panel content to have published front end pages like Outreach and Events.
- However, since we don't want those FE pages, we are keeping all those Office nodes unpublished and circumventing the normal expectations about published vs unpublished content.

## The Proposed solution - Create a "Connect with us" Block Type
- Office is a Content Type - means by default it gets a URL
- The Connect with Us fields are only used on Offices that we don't want to have published URLS
- The only Office that is published doesn't have content in the Connect with Us fields
- Lean into the default way Drupal is supposed to work. 
   - Nodes get URLs, meant for full pages
   - Blocks don't, meant are for reusable components on multiple pages
- Will require building new block type (change to Content Model), updating CLPs to reference this block type (Drupal), and updating FE query slightly
- Dave already built a proof of concept
- Only 4 nodes to migrate

## The alternative - Create a bunch of tech debt 
Trying to support the two use cases of Office is basically us fighting upstream against Drupal. Discussion in scrum we agreed this is a bad idea.

## Rough cut story mapping:

- [x] **Build QA test plan** that covers both Drupal and FE
- [x] **Content audit:** Where do Connect With Us blocks appear (Dave addressed in [comment below](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19544#issuecomment-2452693379))
- [x] **Drupal:** 
   - [x] build the new Block type: Connect with us, reusing existing fields as much as possible. - Dave has [in PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19770)
   - [x] Associate it with all the content types that use Connect With us content now. Can merge to prod after QA. - Dave has [in PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19770)
   - [x] ~~create a CMS feature toggle, off by default, that can be used for content-build changes.~~ per UX sync we are not going to do this
- [x] **Data entry:** CAIA can do this, or we can do it: create blocks using the new block type, for VHA, VACO, VBA, NCA Connect with us content, and publish. - [19764](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19764)
- [x] **Data association:** On any content that displays Connect With Us content now, add the new Connect with Us block. (This will be on many Benefit Detail Pages, and on some CLPs.) - [19764](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19764)
- [x]  **FE:** Where it appears on entities other than Offices pages, convert the existing Connect With Us build to use the new Connect with Us Block content. Hide this behind a CMS feature toggle. (We should verify that with FE.) Can merge to prod after QA. - [19649](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19649)
- [x] **Run the QA test plan**
- [x] **Launch:** 
   - [x] FE PR deploys to prod
   - [x] Verify on prod
   - [x] Notify CAIA that today is the day fix goes live, on https://dsva.slack.com/archives/C07SFHRM745/p1729702094028749 
- [ ] **Tech debt removal & change management**      
   - [x] #19794

## Original defect report
<details><summary>Initial defect report and investigation notes</summary>

## Describe the defect
On Benefits Hub Landing Pages, there is a reference to the Office content type for the "Add a "Connect with us" block" field. This field information is not respecting moderation state and is showing content that is unpublished.

## To Reproduce
1. Go to https://prod.cms.va.gov/burials-memorials, a Benefits Hub Landing Page.
2. Scroll down to the bottom of the page, and observe the 'Add a "Connect with us" block' content.
3. Visit the source for the 'Add a "Connect with us" block' , which is the NCA Office node: https://prod.cms.va.gov/nca.
4. Observe that there are no published revisions for the NCA Office node. The content should not be visible at all on Benefit Hub Landing Pages. 

## Warning
- Race condition exists when deploying to ensure prod isn't broken. 

 ## Additional context
We are fairly certain that the problem originates with the view used to select the 'Add a "Connect with us" block', which locally is accessible here: https://va-gov-cms.ddev.site/admin/structure/views/view/content_entity_reference_source/edit/entity_reference_7

This view uses a filter which does not check Moderation State, and so it will return content for any node regardless of its status:
![Image](https://github.com/user-attachments/assets/148a1ced-470e-4d2a-94c2-ae951f28df6c)

We do not know everywhere that Office content is used on the site, nor how this view is used to provide content, so we recommend finding every place it may be used to ensure content is not inadvertently removed with the fixes here. 

**We also recommend reviewing all the other versions of this view for similar problem. Only one of them (System references) is filtering for moderation state.**

</details>

**Comment by omahane** [comment]
@gracekretschmer-metrostar @jilladams @mmiddaugh 
I made a Tugboat environment to investigate this.

The issue I see is that none of the Office nodes returned in [this view](https://main-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/admin/structure/views/view/content_entity_reference_source/edit/entity_reference_7) are currently in a [Published state](https://main-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/admin/content?title=&type=office&moderation_state=All&owner=All&order=title&sort=asc):
![Image](https://github.com/user-attachments/assets/77af2be2-9623-4f8b-ad0e-01e2a9c5699d)

I am not sure if whether we want to publish these offices or not, as they have not been published since the beginning of the site. Perhaps we do, but before we change the reference field to only return published Offices we should confirm that we want the offices published.

**Comment by jilladams** [comment]
In this view, /admin/structure/views/view/content_entity_reference_source/edit/entity_reference_7, there's a filter that explicitly only pulls in the Offices (by node ID) for VHA, NCA, VACO, and VBA. 

We are gonna try publishing those in Tugboat to see if that's a starting point for saying: don't publish draft content to FE.

**Comment by jilladams** [comment]
If that works, we will need to: 

- [ ] Publish those 4 nodes in prod
- [ ] Update the FE to make sure it only shows Published content.

**Comment by jilladams** [comment]
# On Tugboat, with Offices published:

## Connect with Us content
 it appears to make no difference on the Hub pages where Connect with us is powered by the content. Side by sides of tugboat (left) vs. prod (right), for each administration represented by an office:

https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/burials-memorials/
<details><summary>Screenshot burials / NCA</summary>
![Image](https://github.com/user-attachments/assets/a26f89ac-1dda-4176-87d5-776955fbbe51)
</details>


https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/health-care/
<details><summary>Screenshot healthcare / VHA</summary>
![Image](https://github.com/user-attachments/assets/68000294-dbe6-44e3-9f60-9fd27f51e7ba)
</details>


https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/disability/
<details><summary>Screenshot disability / VBA</summary>
![Image](https://github.com/user-attachments/assets/21aa5bd7-e639-4e78-b4bb-e6a2f78aae30)
</details>


https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/records/
<details><summary>Screenshot records / VHA</summary>
![Image](https://github.com/user-attachments/assets/fc0ceeb8-72f6-47bc-a558-bad4fec3bb36)
</details>


https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/service-member-benefits/
<details><summary>Screenshot service member / VACO</summary>
![Image](https://github.com/user-attachments/assets/c8cd1808-f397-4538-a17c-0a214f4fcf3f)
</details>

## Office directory
* Office directory has a URL that 404s in prod: https://www.va.gov/office-directory/ 
* But is live in lower environments, regardless of whether Offices content is published or not: 
  * Benefits demo tugboat (where Offices are now published): https://web-tgr2ytyynpiadf2hn9evwblpfhs4ohg7.demo.cms.va.gov/office-directory/
  * Laura's demo tugboat (where they're not): https://web-cqo9f8ujqskzfigy3roxk5eqqdkad6vp.demo.cms.va.gov/office-directory/

The search on that page doesn't work.

<details><summary>Screenshot of console errors preventing search from working</summary>
![Image](https://github.com/user-attachments/assets/6f80e2f1-ee04-4807-823f-bd176631c810)
</details>

## Single office pages
Offices do have a template: https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/office.drupal.liquid

 I can't find a way to get to a single Office page but that doesn't mean there isn't one. We probably need someone on FE to help confirm whether or not there are routes.

**Comment by davidmpickett** [comment]
# Proposal wip

## Option 1 - Create a "Connect with us" Block Type
- Office is a Content Type - means by default it gets a URL
- The Connect with Us fields are only used on Offices that we don't want to have published URLS
- The only Office that is published doesn't have content in the Connect with Us fields
- Lean into the default way Drupal is supposed to work. 
   - Nodes get URLs, meant for full pages
   - Blocks don't, meant are for reusable components on multiple pages
- Will require building new block type (change to Content Model), updating CLPs to reference this block type (Drupal), and updating FE query slightly

## Option 2

**Comment by jilladams** [comment]
**Rough cut story mapping:** 
1. Drupal: build the new Block type: Connect with us, reusing existing fields as much as possible, & create a CMS feature toggle, off by default, that can be used for content-build changes. Can merge to prod.
2. Data entry: CAIA can do this, or we can do it: create blocks using the new block type, for VHA, VACO, VBA, NCA Connect with us content
3. Content audit: Where do Connect With Us blocks appear
4. Data association: On any content that displays Connect With Us content now, add the new Connect with Us block. (This will be on many Benefit Detail Pages, and on some CLPs.) 
6. FE: Where it appears on entities other than Offices pages, convert the existing Connect With Us build to use the new Connect with Us Block content. Hide this behind a CMS feature toggle. (We should verify that with FE.) Can merge to prod.
7. QA test plan
8. Launch: flip the CMS feature toggle > content release > verify on content that uses Connect with Us.
9. Tech debt removal:   * FE: remove the old Offices version of connect with us, keep the new Block build, and remove Feature toggle conditional logic
  * Drupal: Remove the CMS feature toggle
  * Drupal content: Archive the VHA, VACO, NCA, VBA Offices nodes 
  * FE: Remove the Offices directory

Folks who can contest this before or after we make tickets (might be easier before / save some ticket-making time): 
* Drupal: @omahane @jv-agile6 or @dsasser 
* FE: @chriskim2311 @randimays 
* Overarching: @laflannery @davidmpickett

**Comment by davidmpickett** [comment]
> 2. Content audit: Where do Connect With Us blocks appear

- CLPs and BHLPs are only two Drupal nodes use the field_related_office Entity Reference
- Content build only seems to reference "connect with us" in CLPs and BHLPs https://github.com/search?q=repo%3Adepartment-of-veterans-affairs%2Fcontent-build+%22Connect+with+us%22&type=code
- Should double check other entities that reference Office to make sure none of them are relying on these fields
- ![Image](https://github.com/user-attachments/assets/c304a3d7-26db-4e51-810d-5422d5938a0a)

> 3. Drupal:>    
>    * build the new Block type: Connect with us, reusing existing fields as much as possible.
>    * Associate it with all the content types that use Connect With us content now. Can merge to prod after QA.

I have a draft PR that does these first two items: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/19666

**Comment by jilladams** [comment]
QA test plan: https://docs.google.com/spreadsheets/d/1YUa8ujmnniU8E5VzqnSn8aG9iyOjypzrRazR0nKAVbE/edit?gid=0#gid=0 @laflannery @davidmpickett @FranECross it's pretty basic about presentation of BHLPs / CLPs Connect with Us pieces so far. Holler if you have questions/ objections to how I set that up 

This did bring up one interesting question / note: It appears in production that the social media links in the FE are being built using the External link field - link title. That's the only place I see the text like "Veterans Health Administration" being set in Drupal on Office nodes, e.g. https://prod.cms.va.gov/node/38440/edit -- unless the VHA > Veterans Health Administration text is being established somewhere in the FE code. If it's the link title, that's a little obscure. If that poses any issues during the FE build, we could think about a more obvious way to get that done (add a field, or use the Block title and make block title be the full administration text, but that might have other consequences in the node view that generates the Drupal field list items, etc).  (I wrote the test plan assuming it's the link title being used. If not, we need to update the test plan.)

@davidmpickett flagging for your consideration as you work the FE ticket or need help with it from @chriskim2311 .

**Comment by davidmpickett** [comment]
> This did bring up one interesting question / note: It appears in production that the social media links in the FE are being built using the External link field - link title. That's the only place I see the text like "Veterans Health Administration" being set in Drupal on Office nodes, e.g. https://prod.cms.va.gov/node/38440/edit -- unless the VHA > Veterans Health Administration text is being established somewhere in the FE code. If it's the link title, that's a little obscure. If that poses any issues during the FE build, we could think about a more obvious way to get that done (add a field, or use the Block title and make block title be the full administration text, but that might have other consequences in the node view that generates the Drupal field list items, etc). (I wrote the test plan assuming it's the link title being used. If not, we need to update the test plan.)
> 
> [@davidmpickett](https://github.com/davidmpickett) flagging for your consideration as you work the FE ticket or need help with it from [@chriskim2311](https://github.com/chriskim2311) .

Good question. It's not obvious that one field in Drupal is being used in multiple link titles on the FE. I do think this is an elegant enough solution (since it's the current solution with Offices as the data source), but would be good to note in KBs or Content Model Documentation

![Image](https://github.com/user-attachments/assets/bd726f56-1a34-4c67-9864-627dc4b10135)

![Image](https://github.com/user-attachments/assets/adb77705-59e5-4cfc-8171-7ab626efe4aa)
