### ISSUE TITLE
DUW usability research readout and report

### ISSUE THREAD

**Issue by thejordanwood** [department-of-veterans-affairs/va.gov-cms#19561]
### User story

**AS A** researcher
**I WANT** to wrap up my research study
**SO THAT** I can share insights with others and protect participants' private information

## Tasks

**Collaborate**

- [x] Share draft research report with team and ask for feedback
- [x] Incorporate feedback into report
- [x] Discuss draft recommendations with team 

  - Recommendations are key outputs of the research process. They connect your findings back to the product roadmap(s) and shape the experience of future users. Depending on the type of research conducted, recommendations might be narrowly focused on improving a specific interface component of your team's product, or they might have broad implications for multiple parts of the VA.gov ecosystem. Work with the Sitewide UX Lead, UX team, Product Manager, and Product Owner to generate, refine, and categorize recommendations. PMs and POs also play a key role in socializing recommendations to other teams.

- [x] Work with Sitewide UX Lead, PM, and/or PO to discuss whether research readout(s) are needed. If so, determine audience and meeting length (e.g., 30-min meeting with 20-min presentation and 10-min discussion).
- [x] Work with PM to schedule research readout(s)

**Research Readout(s)**
- [x] Draft readout presentation slides
- [x] Share readout slides with UX Lead for feedback
- [x] Incorporate feedback from UX Lead
- [ ] *(optional)* Consider doing a practice runthrough to gauge flow and length
- [x] Present readout(s) to team and/or stakeholders
- [x] Revise report and/or readout slides per feedback from readout(s)
- [x] *(optional)* Consider presenting at Sprint Demo; make a *very short* version of your readout slides
- [ ] *(optional)* Consider presenting at Veteran Digital User Experience Weekly Design Sync meeting; slack Naomi Marcussen to schedule a date; [presentation template here](https://docs.google.com/presentation/d/13G80avWGdY7tHU40PbP_l05W1yRpDr-opOk0u_AAhzQ/edit#slide=id.g892adcb623_0_141)

**Add Findings to Research Repository**
- Once your report is final, link to the relevant research repository:
  - Veteran-facing research: [How to add research to Research Repo](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/70) > *What to do when you complete your research*
  - Editor-facing research: [CMS Research Repository](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/research)

**Delete and Archive Research Materials**
- Review your notes and synthesis materials to make sure they don't contain any PII ([Personally Identifiable Information](https://depo-platform-documentation.scrollhelp.site/research-design/what-is-pii)). Then add them to your github research folder, and link to them in your research report.
- Once your readouts are complete, you should delete [session recordings](https://depo-platform-documentation.scrollhelp.site/research-design/recording-user-research-sessions) and transcripts from your computer and empty the trash folder.

## Acceptance Criteria
- [x] Feedback incorporated into research report
- [ ] Readout(s) conducted
- [x] Findings added to [Research Repo ticket](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/704)
- [x] Notes and synthesis materials scrubbed of PII, posted to github, and linked to report
- [x] Session recordings and transcripts deleted from your computer

**Comment by jilladams** [comment]
Per [Slack](https://dsva.slack.com/archives/C06S9DADEUB/p1730135000224049?thread_ts=1730134947.607349&cid=C06S9DADEUB), we'll plan to pull this into Sprint 16, but it's likely to start at the tail end of sprint and roll into SPrint 17.

**Comment by thejordanwood** [comment]
End of sprint update: 

I have some readout slides drafted, but want to give everyone more time to give feedback on the research report. This ticket will roll over to leave time for feedback, any updates that need to be made to the report, and finalizing the readout.

**Comment by thejordanwood** [comment]
@FranECross @davidmpickett Please let me know if you have any feedback on the [DUW research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/research-findings.md). You can post that feedback in this ticket or in [this Slack thread](https://dsva.slack.com/archives/C06S9DADEUB/p1732046985303089).

**Comment by FranECross** [comment]
> [@FranECross](https://github.com/FranECross) [@davidmpickett](https://github.com/davidmpickett) Please let me know if you have any feedback on the [DUW research report](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/research-findings.md). You can post that feedback in this ticket or in [this Slack thread](https://dsva.slack.com/archives/C06S9DADEUB/p1732046985303089).

@thejordanwood The research report is amazing. Great job, and I don't have any suggested changes.

**Comment by thejordanwood** [comment]
I've made updates to the report based on feedback, the [research readout](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/veteran-military-records/discharge-upgrade-wizard/research/2024-Review-Flow/DUW%20usability%20research%20readout.pdf) is complete, and I plan to show a condensed version of the readout in demo on 12/10. 

I'm going to go ahead and close this ticket since the readout is planned.
