### ISSUE TITLE
Meta title for Events is incorrect - the parts are reversed

### ISSUE THREAD

**Issue by laflannery** [department-of-veterans-affairs/va.gov-cms#19698]
## Description
While doing QA for next-build Events I found an existing bug with the `<title>` tag on Events where the parts are swapped which makes the tag not very helpful.

Currently 3 parts make up the title tag:

1. H1 of the event
2. Section the event belongs to (VAMC System name or Outreach)
3. Website name (Veterans Affairs)

However, on both VAMC Events and National events, Part 1 and 2 are swapped so that the section is coming first. This means that in the browser Tab, I am seeing the Section for all events which is very confusing when I have many open and am trying to find the correct tab to get back to. Notice what my tabs look like currently, I have 4 different events open but I can't use the `<title>` tag to figure out which one is which:

![Image](https://github.com/user-attachments/assets/02c44878-4269-4e93-b694-29d523829286)

This is what it should look like:
![Image](https://github.com/user-attachments/assets/3dbe8342-424d-4a4b-a7ca-2b8875e2be5b)

### Scope / Impact analysis
_What, if anything, could break as a result of this change?_
_Engineer should assess this when approaching PR._

### Roles / assignments
_After functional testing, code review, accessibility review, and design review can happen in parallel._
- [ ] **Functional testing:** 
- [ ] **Code review:** 
- [ ] **Design review:** 
- [ ] **Accessibility review:** 
- [ ] **Product acceptance:** 

## Acceptance criteria
_ACs should capture expected behavior, to inform test plans. Consider devices, documentation updates including KBs, change management, and [content model](https://prod.cms.va.gov/admin/structure/cm_document) when applicable._

- [ ] 
- [ ] Impact analysis is filled out and QA test plan is updated accordingly
- [ ] Does this product have an existing regression test plan?
	- [ ] Yes, link: 
	- [ ] No, regression test plan will be created as part of the work / points in this ticket

**Comment by FranECross** [comment]
Blocked so we don't introduce changes before the Staging review of NB Events on 11/15.

**Comment by jilladams** [comment]
Events are shipped to prod in the next-build template, so this is now unblocked. Updating ticket / tags.

**Comment by chriskim2311** [comment]
@FranECross @laflannery This has made it to prod can you review and close if everything looks good thanks!

**Comment by chriskim2311** [comment]
@laflannery Took a look and got some insights from Tim about where the data is coming from and this only needed a CMS change. I am going to revert the changes made in Next-Build

**Comment by chriskim2311** [comment]
@laflannery CMS change has made it to prod. Let me know if you find any issues thanks!

**Comment by laflannery** [comment]
Looks good, thanks Chris!

**Comment by jilladams** [comment]
Revert pr in next-build: https://github.com/department-of-veterans-affairs/next-build/pull/841. Closing.
