### ISSUE TITLE
Prep for R&S search filters research

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#19703]
## Dependencies

**This ticket is blocked by:**
- [x] #19706
- [x] #19000

**This ticket blocks**
- [ ] #19701

### User story
**AS A** Researcher
**I WANT** to complete all the details for setting up R&S search filters research
**SO THAT** the research will happen successfully

### Tasks for Sprint X -- Y points
**Finalize research deliverables**
- [x] CM 1 Update research plan and conversation guide with any timeline or protocol tweaks

**Coordinate with Research-Ops and Perigean**
- [x] CM 2 Create recruiting request and submit to VA Research-Ops. Use *Easy Recruitment Request* (for moderated research) or *Easy Recruitment Request for Unmoderated Cohorts* (for unmoderated research) on [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose) @mention Rodney
  - Schedule 20-25% more sessions than the desired # of participants to account for no-shows & cancellations 
- [x] CM 3 Create *New Research Intake* request from [this page](https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/new/choose) @mention Rodney
  - [x] In description, add links to github research folder and (from previous step) recruiting request form
  - [x] Make yourself the assignee
  - [x] Add labels for the project's product, research methodology, audience, etc. from [this list](https://github.com/department-of-veterans-affairs/va.gov-research-repository/labels?page=1&sort=name-asc)
- [x] CM 6 (document as a comment in this ticket) Make agenda for kickoff meeting w/Perigean

- [x] Review Perigean's recruitment survey before kickoff meeting
- [x] Attend kickoff meeting with Perigean and Sitewide UX Lead and/or PM
- [x] Test Zoom login from Perigean -- Cindy did; Rodney needs to
- [x] Change display name of Perigean Zoom account to "*<Moderator's first name>* (Moderator)"  -- Cindy did; Rodney needs to

**Notetaking prep**
- [x] Make note-taking spreadsheet/Mural
- [x] Create a Mural board for research debrief sessions and/or data synthesis

**Pilots** -- Cindy run first, Rodney run second
[Guidance here](https://depo-platform-documentation.scrollhelp.site/research-design/research-checklist#Researchchecklist-4-Run-a-pilot-session4.Runapilotsession)
- [x] CM 4 Recruit pilot participant(s) from your company or another one
- [x] CM 5 Schedule pilot(s) -- 2  for 2/6 or 2/7
- [x] CM Schedule pilot -- 1-2 for Feb 10-14
- [x] Slack your Perigean lead with the date, time, and participant for your pilot(s)
- [x] Run pilot(s) 
- [x] Debrief pilot(s) with team
- [x] Schedule team debrief sessions after each pilot 
- [x] Schedule prep time before and debrief time after each pilot 
- [x] Confirm the day before with pilot participant(s) -- Cindy did for the 1st 2 pilots
- [x] Make any revisions needed to conversation guide and prototype
- [x] Send thank you slack message to pilot participant(s) -- Cindy did for the 1st 2 pilots

**Recruitment / scheduling sessions** (for moderated research only)
- [x] Review recruited participant list from Perigean for requirements met
- [x] Follow-up with Perigean re participant list, if needed
- [x] Make sure all research sessions scheduled by Perigean are in your calendar
- [x] Make signup sheet for observers, and share with team, stakeholders to sign up ([template](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/regional-offices/research/observer_schedule_template.xlsx)) -- Slack canvas instead of SharePoint
  - [x] Invite Laura Flannery, Shamia, Dave, Michelle, Fran, Jill, Amanda Klausmeier, Mikki Northuis, Danielle Thierry
  - [x] Thursday Feb 13 - Invite the rest of the Megateam
- [x] Invite signed up observers to each session and optional debrief session, per signup sheet
- [x] Add participant numbers, dates, and times into recruitment intake ticket Participant Tracker (to check off later after each session) 
- [x] CM (if time) Make notetaking doc in github for each session to share with Perigean right before each session starts (or all at once ahead of time if Perigean contact is OK with this). [transcripts folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support/research/2024-search-filters/transcripts)
  - [x] Need to rename files so they include the 2-digit date of each session
- [x] Schedule 30-minute team debrief sessions once a day, and invite all observers signed up to observe in the previous 24 hours
- [x] Schedule prep and debrief time for each session
- [x] Slack/email all observers with instructions

## Acceptance Criteria
- [x] The target number(s) of participants have been recruited and scheduled (for overall & primary criteria)
- [x] The moderator(s), notetaker(s), and observer(s) have been invited to research sessions and daily debriefs
- [x] Pilot session(s) have been conducted
- [x] All preparation done before the first day of research sessions

**Comment by cindymerrill** [comment]
Could this ticket be pulled into the current sprint? Rodney and I won't finish it, but we will want to get started on it and then continue working on it into the next sprint. @FranECross @davidmpickett @jilladams

**Comment by FranECross** [comment]
@cindymerrill @rlittleCivicActions Done!

**Comment by cindymerrill** [comment]
@FranECross This ticket appears in the **Sprint Commitment** column of the ticket board. Should it instead be in **Refined & Ready**? It's definitely not going to be completed in this sprint. Is it OK if I move it there?

FYI @jilladams

**Comment by jilladams** [comment]
@cindymerrill Fran / I added to sprint in response to your note yesterday that it will start in this sprint. It's ok to have it in the Sprint column, even if it won't close within sprint boundary. I've noted in reporting that we pulled it in as stretch.

**Comment by cindymerrill** [comment]
Ready to submit research plan and convo guide for research review and launch recruiting, which I'll do tomorrow...

**Comment by FranECross** [comment]
Wonderful! Thanks, @cindymerrill !!

**Comment by cindymerrill** [comment]
I just submitted this research for review and to launch recruiting! 

However, I was unable to @mention @rlittleCivicActions because he doesn't have access to the research repo yet, but I @mentioned @davidmpickett instead. FYI @mmiddaugh @FranECross @jilladams

**Comment by davidmpickett** [comment]
Adding links to the Research Repository tickets for @rlittleCivicActions in the future
- https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/793
- https://github.com/department-of-veterans-affairs/va.gov-research-repository/issues/794

**Comment by cindymerrill** [comment]
@davidmpickett @rlittleCivicActions As promised, here's my draft agenda and prep for the kickoff meeting with Perigean...

### Kickoff meeting w/Perigean

#### PREP for the meeting
1. Receive Perigean's recruitment survey (link or screenshot)
2. Review survey for usability and for coverage of recruitment criteria

#### Draft agenda for the kickoff meeting
- Introductions
- Any questions from Perigean about recruiting
- Any feedback from Dave and Rodney on Perigean's recruitment survey
- Discuss relative priorities of recruitment criteria (mobile device usage is most important, then secondary criteria as listed in decreasing order of importance in the research plan) 
- Request that Perigean walk each participant through downloading the Zoom mobile app before entering the session and enabling settings for screen sharing on their mobile device
- Request that Perigean calls each participant to remind them about the session, in addition to emailing them. And please include the session time in each participant's own time zone (from their address) in both emails and calls.

**Comment by cindymerrill** [comment]
I'm trying to schedule 3 pilot sessions: 
- I plan to run the first pilot this week (Thu or Fri)
- Rodney plans to run the second pilot this week (Thu or Fri)
- Rodney plans to run a third pilot next week (Tue or Wed) when the prototype is finished

Below are the times that work for Rodney, Dave, and me this week and for Rodney and Dave next week:

- Thu Feb 6 from 4-5 pm ET
- Fri Feb 7 anytime during 12:30 - 3:30 pm ET
- Tue Feb 11 anytime during 2:30-5 pm ET
- Wed Feb 12 from 4-5 pm ET

I have reached out to 4 people so far, and 1 person is willing to participate on Friday. I'm waiting to schedule them until tomorrow to see if I hear back from anyone else. I have 3 more people I could ask if needed.

**Comment by cindymerrill** [comment]
@davidmpickett @rlittleCivicActions @FranECross @mmiddaugh @jilladams I just recruited 3 pilot participants and scheduled them as follows:

Thu Feb 6 from 4-5 pm ET – Rocio De Santiago (Cindy runs; Dave, Rodney, and Michelle observe)
Fri Feb 7 from 2-3 pm ET – Steven Strailly (Rodney runs; Dave and Cindy observe)
Wed Feb 12 from 4-5 pm ET – Lee DeIarm (Rodney runs; Dave and Michelle observe)

Next I'll schedule a debrief meeting after each pilot...

**Comment by cindymerrill** [comment]
FYI @davidmpickett @rlittleCivicActions I just added one more item to the end of my [draft agenda for the kickoff meeting with Perigean](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19703#issuecomment-2635478459)

**Comment by cindymerrill** [comment]
@davidmpickett I still don't have access to Mural, so could you please create a new Mural for notetaking? You should be able to use the template that I and others have used in the past, which has many bunches of different colored stickies--one for each pilot or regular session. Ideally you'd have it before tomorrow afternoon's first pilot.

**Comment by cindymerrill** [comment]
All 3 of our pilot participants plan to join the session from a mobile device, so we can ask them to if they forget and show up on a computer.

**Comment by cindymerrill** [comment]
@davidmpickett created a Mural board for observers to take notes, and I modified it a bit: https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1738793109607/9003012168cc00d3673c9babe90d7435ece613cf
It should be shared in the #feedback-backchannel thread before every session, @rlittleCivicActions .

**Comment by cindymerrill** [comment]
The participant for pilot 1 today just canceled but is available tomorrow, so I've rescheduled for Fri Feb 7 from 12:30-1:30 pm ET. That leaves 30 minutes between the end of pilot 1 (which I'm running) and the beginning of pilot 2 (which Rodney is running), which should be OK.

**Comment by cindymerrill** [comment]
Research prep activities that I completed today:

- Confirmed with both pilot 1 and pilot 2 participants for tomorrow
- Reviewed Perigean's recruitment email and survey, and gave my revision requests to Perigean
- Checked settings in Perigean's zoom account 
- Talked through more research tasks with Rodney and answered his questions
- Created a notetaking doc template for Perigean and duplicated it for each participant 
  - Files are [in this folder](products/resources-and-support/research/2024-search-filters/transcripts)
  - Filenames will need to be edited to add in the 2-digit date for each participant's session

FYI @davidmpickett @rlittleCivicActions @FranECross @jilladams

**Comment by davidmpickett** [comment]
@cindymerrill and @rlittleCivicActions, I just made a small pull request with some suggested changes to the conversation guide based on what we observed in the pilots today https://github.com/department-of-veterans-affairs/va.gov-team/pull/102743

**Comment by cindymerrill** [comment]
Those changes look great to me, @davidmpickett ! (I approve)

**Comment by cindymerrill** [comment]
I moderated the first pilot today, and @rlittleCivicActions moderated the second. We debriefed together and with @davidmpickett . I checked off all the tasks at the top of this ticket that are completely done, and am leaving the rest of them and the research study in @rlittleCivicActions 's capable hands with @davidmpickett supporting as needed. 

Please keep me posted on the results! And feel free to reach out if you have any questions :).

**Comment by cindymerrill** [comment]
FYI Here is a google doc that contains the blurbs I used for pilot participant recruiting: https://docs.google.com/document/d/1W43hQXhNmxQMdqd_pMMbstaDcTtg-HOayk2GcBTlFj0/edit?usp=drive_link 

It's in the Research folder for Resources and Support on the Sitewide shared google drive.

**Comment by jilladams** [comment]
@rlittleCivicActions could you help out next week and update the checklist in ticket body to indicate where we're at overall on progress here? Thanks!

**Comment by davidmpickett** [comment]
Sessions begin tomorrow morning. Closing this ticket. Any additional logistics can be tracked in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19701
