### ISSUE TITLE
Operating Status expansion: Launch plan & change management

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19823]
## Pre-launch comms
Facility closed goes from red to yellow.
Facility limited status goes from yellow to blue.

- [x] Complete KB drafts ticket #19904 - Michelle
- [x] Publish KB draft revisions created in #19904 - Michelle 
- [ ] PM: Provide draft content to all facility stakeholders to share with Editors, including KB links and time estimate for launch 
  - [x] VHA
  - [x] Vet Centers
  - [x] VBA
  - [x] NCA
- [x] Reach out to people using "closed" and start a migration effort.

## FE
- [x] FE changes are tested per #19809 
- [x] Changes merge to production

## Drupal
- [x] Changes merge to production
- [x] Changes deploy and are editor visible

## Post launch Comms

- [ ] Continue working "closed" facilities

**Comment by Agile6MSkinner** [comment]
All KBs published

**Comment by jilladams** [comment]
@Agile6MSkinner List of all facilities using the Closed status: https://prod.cms.va.gov/admin/content/facilities/facility-status?Title=&field_facility_locator_api_id_value=&field_operating_status_facility_value=closed&field_operating_status_more_info_value=&field_supplemental_status_target_id_op=or&field_supplemental_status_target_id=All&type=All&moderation_state=All&workbench_access_section__section=All

**Comment by Agile6MSkinner** [comment]
Making a spinoff ticket for addressing "closed" and removing.
