### ISSUE TITLE
Zenhub migration: script to associate Epic children from Zenhub with Github issues as sub-issues

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#19876]
## Business logic
* Address every epic in the in the `va.gov-cms` and `va.gov-team` repositories that has the `sitewide` label and has child issues
* For each of these epics: the parent/children relationship in Zenhub is re-created in Github as parent issue / sub-issues. 
* DO NOT CHANGE EXISTING PARENTS in Github Projects. We do not want to overwrite recent Product work to assign parents/ children. Only if a child has no parent, assign the parent.

We don't care what language is used to script, or what API tooling we use (Github REST API vs. GraphQL). There are some related code examples below, in case they're helpful. 

## Zenhub documentation / notes
Zenhub has a GraphQL interface we can use. 
**We use legacy `epics`,** (now deprecated), not Zenhub Epics.

* Get a GraphQL API token here: https://app.zenhub.com/settings/tokens
* [GraphQL explorer here](https://developers.zenhub.com/explorer
* workspace ID = 6645154188a81a1f7a0a9464

### What's working
Working GraphQL example that pulls all workspace epics and their child issues and labels: 
```
query epicsFromWorkspace($workspaceId: ID!) {
  workspace(id: $workspaceId) {
    epics { # required for legacy epics
      nodes {
        issue {
          repository {
            name
          }
          number
          title
          labels {
            nodes {
              name
            }
          }
        }
        childIssues {
          nodes {
            number
            title
          }
}}}}}
```

### What's not working so far
* Filter by only epics with the `sitewide` label. Right now it returns any / all epics, even though they don't actually show up in the workspace.
* It only returns a small set of epics -- can't get the full list through the Explorer with that query.

## Github GraohQL documentation
In Github, we are using the parent issue / sub-issue setup to build "epics." **Sub-issues are in beta.**

From the **sub-issues beta**:  Sub-issues can be managed via the GraphQL API. **Note that these requests will need to include the GraphQL-Features header with a value of sub_issues.**

**Github GraphQL docs:**
* [Parent issues](https://github.com/github/github/blob/41b61c795e2cea379903d6ab4fa8f13f10f894f3/config/schema.public.graphql#L22531)  
* [Sub-issues summary](https://github.com/github/github/blob/41b61c795e2cea379903d6ab4fa8f13f10f894f3/config/schema.public.graphql#L22836)   
* [List of sub-issues](https://github.com/github/github/blob/41b61c795e2cea379903d6ab4fa8f13f10f894f3/config/schema.public.graphql#L22811)  
* [Add sub-issue](https://github.com/github/github/blob/41b61c795e2cea379903d6ab4fa8f13f10f894f3/config/schema.public.graphql#L30660) 

### Python app example using GraphQL
Another A6 team uses the GraphQL CLI to manage sub-issues:
- [GitHub CLI call to the graphql API that includes headers for beta features](https://github.com/HHS/simpler-grants-gov/blob/4fb6e45f4af1faa30a1b10e2bb3c0b9d18aa527a/analytics/src/analytics/integrations/github/make-graphql-query.sh#L63-L68) - "The first example uses the GitHub CLI -- which is a fantastic tool, but you can easily replicate that using JS fetch"
- [GraphQL query with issue types and sub-issues](https://github.com/HHS/simpler-grants-gov/blob/4fb6e45f4af1faa30a1b10e2bb3c0b9d18aa527a/analytics/src/analytics/integrations/github/getSprintData.graphql#L42-L69)

### Github projects migration script
From Eric Boehs: 
> https://github.com/ericboehs/z2g-ui is the migration tool hosted [here](https://z2g-ui.fly.dev/). You could have someone from your team add an "Epics" step. The code is MIT so anyone can use/modify. It's a bit messy though as I wrote it in 2-3 days... mostly AI.

Again: this is not a requirement, but if it's useful, we can go this route.

## Acceptance criteria

- [ ] Script is developed that can be run to migrate Epic child issues from Zenhub to Github sub-issues of a parent issue
- [ ] After script runs, child issues appear on Sitewide parent issues in Github projects
- [ ] Script can be shared to the Github projects COP channel in DSVA slack

**Comment by eselkin** [comment]
Unfortunately epics under our workspace returns ALL epics across the system.
We need to specify the epics with a `epics(query: "[EPIC]"){...` (gets us about 40% of the way to filtering) and then filter the results for exact matches of the substring "[EPIC]" (all caps and brackets) to capture the ids of the epics we want to search through for the children issues.
To go through all epics we need the 
```
pageInfo {
        endCursor
        startCursor
}
```
of the query. And reference them with start and end.

**Comment by jilladams** [comment]
In case helpful, I have a spreadsheet of all Epics for Faciliites / Public Websites: https://docs.google.com/spreadsheets/d/1ER9HKSHBS_49xD5idkSMO-x1EncV_sTe4ziw9DHtr4g/edit?gid=1109999405#gid=1109999405

(I got this from a Node script that Ryan Koch built for me awhile back that pulls issues from the Github APi that have the label Epic. I can share that app if useful, but am not allowed to upload it to Github as a .js file.)

**Comment by jilladams** [comment]
Some help from Billy Daly: 

> I had some extra time this weekend, and put together a lightweight [CLI tool](https://github.com/agilesix/zh-to-gh/tree/main) that should get you to 90% of the way to the final step, i.e. adding task-level issues to their parent epic-level ticket in GitHub, assuming you’ve already filtered the ZenHub data down to something like this:
```
{
  # epic level issue URL
  "https://github.com/agilesix/simpler-grants-sandbox/issues/29": [
    # task-level tickets under that epic
    "https://github.com/agilesix/simpler-grants-sandbox/issues/33",
    "https://github.com/agilesix/simpler-grants-sandbox/issues/15"
  ],
  "https://github.com/agilesix/simpler-grants-sandbox/issues/30": [
    "https://github.com/agilesix/simpler-grants-sandbox/issues/13",
    "https://github.com/agilesix/simpler-grants-sandbox/issues/12"
  ]
}
```

> If you’re able to share snippets of:
> * The ZenHub graphql query
> * What you get out of the ZenHub graphql explorer
> I should be able to get the second step set up pretty easily too (i.e. transforming that output to a format that would work with this tool), and get part of the way to the first step (i.e. actually exporting the data from ZenHub)

**Comment by randimays** [comment]
The migrations are complete and I am now going through all of our epics in the va.gov-cms and va.gov-team repos to ensure everything is picked up correctly. Some of our epics will require manual changes because:

1. Some issues do not have the `sitewide` label
2. Github Projects has a max of 50 sub-issues and some epics have more than that

This folder in the Public Websites Google Drive has all of our documentation / code from this effort: https://drive.google.com/drive/folders/1x9fZV1HKtkFD1CVhczLhDBUomTOZNLR_

I'll be working through [this spreadsheet](https://docs.google.com/spreadsheets/d/1jfMQzpLZtUXrfyygvrxG0RA_-UIRH93_5tIWWKKDrGo/edit?usp=drive_link) specifically and will flag here when I'm finished.

**Comment by jilladams** [comment]
@randimays could you add that Google drive folder to the Team folder somewhere, for access purposes. (I think it's not there yet, but if it already is, lemme know -- I got a 404 error on the link, so could be something else going on.)

Re: validating: if the Gdrive folder includes the export from ZH so we can cross compare later, I don't think you're obligated to validate each and every epic.

**Comment by randimays** [comment]
@jilladams Whoops, the link had gotten chopped off. Updated it in the post above and also here: https://drive.google.com/drive/folders/1x9fZV1HKtkFD1CVhczLhDBUomTOZNLR_?usp=drive_link

**Comment by randimays** [comment]
@jilladams Re: validating. Some tickets attached to our epics via Zenhub (both from our team pre-mega-team and other teams' tickets) did not get linked to those Zenhub epics via the script I wrote because they did not have the `sitewide` label. That means we won't have any record of them belonging to the epics with the export I have. I'm working through epics fairly quickly, but I think we will definitely lose a significant amount of data if I don't check them all, unfortunately.

**Comment by randimays** [comment]
Update here.

As I'm validating, I'm noticing that even though I have now run the migration for both repositories three times that there are still missing connections when I look at the epics. I'm asking Billy if he knows what might be happening, because I'm not seeing errors in the migrations when I run them in a batch.

To elaborate a bit, as an example:

1. The va.gov-cms repo has about 500 epics that need migration
2. There is a JSON file that has all 500 of these epics tied to their child issues
3. I take batches of 6-8 of those epics and run them through Billy's script (to avoid rate limiting and so I can see if errors crop up)
4. Once I'm finished running all 500 epics through the script, I run all the epics in va.gov-team (there are about 32) through the script
5. Then I go through each epic individually to verify issues have been added, and some are missing. These issues have the `sitewide` label and are tied to the epic in the JSON file I was using to migrate originally, so I run that epic's data again through the migration script, and the issues are added

I'm not sure why there are issues, but it is happening with nearly every epic I am validating so it is really slowing me down. I'm hoping Billy has some insights, because as I noted above, we need to validate every epic or we're going to lose relationships for the ones that simply aren't working for whatever reason or are missing the `sitewide` label.

**Comment by randimays** [comment]
I just caught up with Billy Daly and we determined that the problem with the migration was that Zenhub allows issues to have multiple parent epics, and Github Projects does not. I didn't know this until today. So I had a quick huddle with Fran and we agreed that I should do the migration for all of the issues that only have a single Zenhub parent, and gather the ones that have multiple epic parents. She and Michael will work to choose only a single epic those issues should belong to, and then we can run the migration again and get those assigned as well.

After that is finished, we can do the final pass through and validate all the epics with their sub-issues (which may be a PM task at that point).

**Comment by randimays** [comment]
@FranECross @Agile6MSkinner [Here is a spreadsheet](https://docs.google.com/spreadsheets/d/1PGgLjpVPtBWXVq1hQvlcL8wmEmxGfFmFtyK8kzOomFA/edit?usp=sharing) of all of the issues in our repositories that have multiple epic parents in Zenhub. In order for me to migrate these properly, they need to have only ONE epic parent in Zenhub. Could you please go through this list and remove epics until there is only one assigned?

For instance: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9399

This issue has two epics assigned: 
![Image](https://github.com/user-attachments/assets/7d28d827-efc1-4cd8-a7d0-404b5275b6e9)

We need to choose one and remove the other so my script will pick it up and assign it to a single parent without any problems.

❗ Since we have an EOY deadline for this migration, it would be really helpful to have this done ASAP. Please let me know if you have any questions.

**Comment by Agile6MSkinner** [comment]
@randimays Understood. We'll get on it.

cc: @FranECross

**Comment by davidmpickett** [comment]
FYI - I have been slowly working through the spreadsheet in the background during meetings where I am primarily listening. 

One thing I noticed is that a good chuck of the Facilities tickets were assigned to Sprint Planning Epics which were a way previous PMs planned sprints. As I encounter those I have been converting them from Epics back to Issues which sometimes fixes a lot of tickets at once.

**Comment by randimays** [comment]
Discussed with the team that we will close this ticket even though the spreadsheet audit work is still happening. We have all the code written to get the data and migrate what we can, and that was the end goal of this ticket.

Closing as complete.
