### ISSUE TITLE
Updates to R&S design (based on Midpoint feedback & prototype needs)

### ISSUE THREAD

**Issue by davidmpickett** [department-of-veterans-affairs/va.gov-cms#20002]
## Changes to make

- [x] Mobile layout of Detail page
- [x] Color contrast for the filter chips [98001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98001)
   - This is fixed in the component and in the R3 designs
   - This is **not fixed** in the mobile prototype
- [x] Must: revisit order of "Show filters" button and "Showing 1 - X of Y results" [98001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98001)
  - Alternative explorations were added to [R3 page](https://www.figma.com/design/cg8VNnxFOxw7lb10FVHpi5/Resources-support?node-id=1044-9517)
  - Additional changes will wait until after Research
- [x] Must: update the "Showing 1 - X of Y results" message to "Showing 1 - X of Y results for 'term' with 3 filters applied" [98001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98001)
- [x] Must: "Clear all" button must be styled to look like a button [98001](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98001)
- [x] Should: Reword intro paragraph on landing page: "Search or filter for information related to VA benefits and services, including step-by-step instructions for using VA.gov tools." [97939](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97939)
- [x] Adjust vertical alignment of "close" icon and text in filter chip
   - This is fixed in the component and in the R3 designs
   - This is **not fixed** in the mobile prototype

Before | After
-- | --
![Image](https://github.com/user-attachments/assets/74eee889-5f5b-4f03-90a3-ac9c6e3cb23e) | ![Image](https://github.com/user-attachments/assets/1d229b9d-b246-43d7-a4b8-e596a862f3d1)

### Detail Page
- [x] For first round of research, what word do we want to use to describe the group of tags? 
  - "Topics" was too broad via [Midpoint feedback](https://github.com/department-of-veterans-affairs/va.gov-team/issues/97991)
  - "Tags" is in current design
  - "Filters" and "Categories" were also suggested
  - ![Image](https://github.com/user-attachments/assets/3f7d62b8-ec67-4c43-9df9-7ba6e96d1c48)

## Revisit in future design iteration (after research)
[Ticket created](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20355) 
- [ ] Language toggle to match new experimental design component [3564](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3564)
- [ ] Fix spacing issues Jordan noted in Figma comments before final annotations
- [ ] Filter chip character limit?
- [ ] Full width button on mobile when embedded in another element with background? 
- [ ] Other notes from midpoint feedback

## Acceptance criteria
- [x] Review with Product, A11y, Engineering
- [x] Review with UX team
- [x] Design is updated for R&S, to reflect collab cycle feedback

**Comment by aklausmeier** [comment]
Show filter behavior is different on desktop vs mobile, important to include desktop in research

**Comment by aklausmeier** [comment]
cc @davidmpickett @thejordanwood @laflannery 


**Revisions made so far** in Figma 🟡 WIP - R3 search filters (revisions):

- Intro copy revised to include "search or filter" in the first few words so AT users know both options are available. @laflannery to discuss with Bryan on governance to see if this passes. If not, @thejordanwood can explore a design iteration. I started in this [Figma frame](https://www.figma.com/design/cg8VNnxFOxw7lb10FVHpi5/Resources-support?node-id=1156-8688&t=HKx66tqtf2RzZfJG-1).
- Included search term in: Showing 1–4 of 4 results for “appeal”  
- Included # of filters applied in: Showing 1–4 of 4 results for “appeal” with 4 filters applied  
- Clear all button styling to match icon button with minor revisions that will need to be added to experimental design ticket if tests well in research. This button has a white background, lower case for better readability, shares red X icon. The current icon buttons are currently only allowed when paired with a primary link and we do not have that use case.
- On detail page, updated "Topics" in front of filter chips to "Tags" which is currently used today. We can stick with this OR choose another term that encompasses all.

**Comment by aklausmeier** [comment]
Also left comment on accessibility [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/98001#issuecomment-2521701629):

>> Must: When viewing [a details page linked from the results](https://www.figma.com/design/cg8VNnxFOxw7lb10FVHpi5/Resources-support?node-id=332-15206&t=FnhfSl1AdHoSH96D-4), the filter chips are present again to show the taxonomical labels for the page. But the chips play a different role here when clicked (navigational rather than action), and those differences need to be reflected in both the semantics and the visual presentation. Is there a reason why they couldn't just be ordinary links here?

>@briandeconinck This was discussed during the [experimental design ticket notes](https://docs.google.com/document/d/1H8B989-PbHIqdrNZppsEGE-Oyxriuou3jryD0YRpJzA/edit?pli=1&tab=t.0) to some extent. It's also how it behaves today. I would prefer these stay consistent in design as filter options. Would love for you and @laflannery to discuss this a bit more. It seems like a grey area to me. It does take them to a new page but clicking on the filter chip in this scenario creates a new search results list like a search button might.

**Comment by davidmpickett** [comment]
Updated the Filter Chip component to 1) fix alignment of label text and X icon 2) make the three version true variants of one base component. I also updated instances of the chip in R3 to use new sub variants where applicable

![Image](https://github.com/user-attachments/assets/04985dea-9306-43f8-9a4e-4ce5934853d4)
![Image](https://github.com/user-attachments/assets/b9aac86d-fe0d-49ae-8d28-c4fca3c77a3c)

![Image](https://github.com/user-attachments/assets/b30933a2-9c71-4f52-88d1-83a00b76d1a2)

**Comment by davidmpickett** [comment]
@jilladams @FranECross - FYI that while this ticket isn't fully refined, it is technically in progress. In addition to @aklausmeier's work, I am starting to pick away at it. This is one I will be continuing in Sprint 19

**Comment by davidmpickett** [comment]
**End of sprint update**
- Moving this back to "To Refine" as we still haven't fully parsed all the midpoint feedback and ensured all necessary changes are accounted for in the ACs of this ticket

**Comment by jilladams** [comment]
@davidmpickett@FranECross is the remainder of that refinement work blocked on having Amanda present to discuss? This'll be a topic in UX sync next time? Wondering if we can get it into sprint 19, or if it'll sit til after the convo guide / research plan advance.

**Comment by davidmpickett** [comment]
I don't think we need Amanda to refine it, we have a lot of notes that @FranECross took about Amanda's opinions on various aspects and what we should or shouldn't implement. Mostly this ticket just needs someone who to spend the time parsing what feedback has already been implemented, what feedback we won't be implementing and what's left to implement.

**Comment by davidmpickett** [comment]
Added border color exploration to address color contrast feedback. Tagged @thejordanwood and @Shamiaalam on [slack](https://dsva.slack.com/archives/C06S9DADEUB/p1737147460776659) for review

https://www.figma.com/design/cg8VNnxFOxw7lb10FVHpi5/Resources-support?node-id=67-6621

![Image](https://github.com/user-attachments/assets/ccb28957-3ae3-4e1b-8ae3-89238708d7f8)

**Comment by davidmpickett** [comment]
**End of sprint update:**

- This will roll into next sprint, hope to have full draft by EOD
- Mitigating factors: sickness, short sprint, split priorities

**Comment by davidmpickett** [comment]
Shared with Fran and Michelle on Slack to close out https://dsva.slack.com/archives/C52CL1PKQ/p1738028713439139

**Comment by FranECross** [comment]
@davidmpickett Looks great. I created a [ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20355) to revisit the items you listed, as well as the balance of the Midpoint review feedback.
