### ISSUE TITLE
Platform CMS Sprint Plan 25 (12/5/2024 - 12/18/2024)

### ISSUE THREAD

**Issue by gracekretschmer-metrostar** [department-of-veterans-affairs/va.gov-cms#20017]
### 2024 Vision Roadmap
- [Roadmap](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1710770110435/815417c164d347d6720309063a146709685712f5?sender=u68176db99729f92d17379835)

### Sprint 25 Goals & Priorities

**SPRINT 25 GOALS**
By the end of this sprint, this is what we're committing to have accomplished and delivered:
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19569
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19811
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20024

### SPRINT 25 PRIORITIES 
Priorities are listed from highest priority to lowest priority, starting at the top of the list. 

**CMS Current Scope of Work ([#20018](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20018))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19569

**Next Build's Events and Event Listing Launch [#19869](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19869)**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19811

**Tech Debt and Maintenance**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19772
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19814
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20024
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20034

**Monitoring and Alerting for Content Build ([#9396](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19396))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19639 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20020

**Improve Editor Support ([#19398](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19398))** 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19982
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20022

**Q4 Editor Survey and Quick Wins ([#19461](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19461))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20019
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19983
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19883

**2025 CMS Roadmap ([#19954](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19954))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19646
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19297
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19296
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19900

**Stabilize Uptime of Editor Experience ([#19397](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19397))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19586
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19894
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19910

**Accessibility Backlog ([#18503](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18503))**
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19368
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19375
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19562

**CMS Comprehensive Test Plan ([#18396](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18396))**
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19746
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/19753

### Help Team, Partners, Clients and Stakeholders Hit Objectives
- [ ] 

### Stretch Goals (only work on after completing your pre-defined sprint work)
- [ ] 

### SPRINT 25 UNPLANNED WORK (Post Sprint Planning)
- [ ] https://dsva.slack.com/archives/CBU0KDSB1/p1733518765120689
- [ ] https://github.com/department-of-veterans-affairs/content-build/pull/2368
- [ ] https://dsva.slack.com/archives/CE4304QPK/p1733875074632889
- [ ] https://github.com/department-of-veterans-affairs/next-build/pull/840
- [ ] https://dsva.slack.com/archives/CBU0KDSB1/p1734148735107309
- [x] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/20092

**Comment by gracekretschmer-metrostar** [comment]
Note: the CMS team had a number of illnesses this sprint that has slowed down our progress.
