### ISSUE TITLE
[SPIKE] [Resources & Support] Explore Search.gov options to replace 'bespoke' search features in VA.gov products

### ISSUE THREAD

**Issue by FranECross** [department-of-veterans-affairs/va.gov-cms#20145]
## Description

The new search requirements is using facets/tags/filtering, which the current search can not do. We need to explore alternatives. Also, Resources & Support search feature is custom and very limited in what is returned (only searches titles, not content) and we need the content searched too.

This supports the [Resources and Support search experience enhancements](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/resources-and-support/initiatives/2024-search-experience-enhancements-Phase-1#scope), Phase 1 initiative.

This spike is to take a holistic look at the various products in VA.gov that have a search feature and create a white paper listing and outlining:

- Products which have a search feature
- What search engine/code/? is used for that feature
- Do any features share code or use the same search feature; what API if any is being used
- Each search features limitations
- Options for updating to a different search engine/feature/API e.g. Elasticsearch, Solr, MeiliSearch, etc., keeping in mind that we want not only titles but body of content searched and results returned.
- High level estimates for each option
- Is there additional cost associated with any of the options

### Information to Consider
- More content will be added to Resources & Support, which is one of the drivers to improving its search feature by returning more content (title/body of content included in searches), as well as speed and accuracy.

### User story

**AS A** Veteran, their caregiver, family member or survivor using the various search features across VA.gov
**I WANT** to have accurate, fast search results when I search for information or forms
**SO THAT** I can achieve my research and needs faster and with a minimum of frustration and angst.

## Acceptance criteria

- [ ]  create a white paper listing and outlining:
- Products which have a search feature
- What search engine/code/? is used for that feature
- Do any features share code or use the same search feature; what API if any is being used
- Each search features limitations
-  Options for updating to a different search engine/feature/API e.g. Elasticsearch, Solr, MeiliSearch, etc. keeping in mind that we want not only titles but body of content searched and results returned.
- High level estimates for each option
- High level estimates for each option
- Is there additional cost associated with any of the options
- [x] Ping Fran so she can review results with Michelle to determine next steps. 
- [x] Okay to close ticket

**Comment by mnorthuis** [comment]
Both Search.gov and AI should be considered as potential services.

**Comment by FranECross** [comment]
@FranECross Pull any analytics available.

**Comment by FranECross** [comment]
For this ticket, AI won't be part of the research, and we can explore that at a later date.

**Comment by jilladams** [comment]
Flag from planning: there's an analytics piece here to help understand cost, meaning: current traffic will help determine cost.

**Comment by jilladams** [comment]
From product sync: 
* Daniel described to Michelle the concept that we can achieve the R&S facets with search.gov as a free solution (vs. Aquia, Solr, or other search server options that would have increased cost)
* This ticket will now assume Search.gov is the solution, and provide details on how to go about that, rather than researching alternatives. 
* Forms search isn't implicated. It uses Lighthouse.
* Outreach Materials search is, as it uses the custom search implementation. That's a separate piece of work we can decide to do later, but aren't going to wrangle right now, given that OM has an uncertain destiny.

@FranECross we recorded that discussion so you can get the context, if you'd like: 
https://us06web.zoom.us/rec/share/zp4Jnj3rdPOBeTzatskKqdtbGEGib1jdw2yoAISUqErUYfakSSyc-VozyfiV8Lk.wp7wKrje1U0iFyx6
Passcode: guKF6h.M

**Comment by dsasser** [comment]
The first area I'm looking into for a Search.gov solution is to determine the best way to index R&S content. There are three options:

1. An RSS feed
2. A "collection"
3. Meta tags

To determine this, I'm going to "clone" the existing site in Search.gov as to avoid making any production changes to the way our search works currently. The clone option exists to do this type of testing. I'll then test out the various options against the cloned site.

**Comment by dsasser** [comment]
> The first area I'm looking into for a Search.gov solution is to determine the best way to index R&S content. There are three options:
> 
> 1. An RSS feed
> 2. A "collection"
> 3. Meta tags
> 
> To determine this, I'm going to "clone" the existing site in Search.gov as to avoid making any production changes to the way our search works currently. The clone option exists to do this type of testing. I'll then test out the various options against the cloned site.

I've learned that testing these scenarios against test data is not possible since a .gov domain is required for the source site. I've reached out to Search.gov for solutions to this but have not heard back yet.

However in my research I've found the best path forward is likely using meta tags. VA.gov is not currently using many meta tags save for title and a few others, but we could leverage more to categorize the R&S pages (or all pages if we desire).  Content-build is setup to provide them if they exist in the Drupal data, though a small bit of wiring is required to get them named appropraiately.

Going with meta tags has the following benefits:
  - An additional API would _not_ be needed in vets-api. We can leverage the existing search API and pass in additional parameters (eg: `content_type`) to limit results to R&S pages.
  - Facets will work out of the box by passing in an additional parameter, `include_facets`, to the existing API
  - We should be able to roll out meta tags safely without affecting the existing search (this was going to be part of my testing, but I'm unable to confirm with 100% accuracy the affect of adding meta tags on existing search restuls). However, we can stage the roll out in staging by setting up a staging site in Search.gov to confirm this.
  - It should be a relatively small lift to get the meta tags implemented
  - We can avoid complicated roll outs that require changes be coordinated among vets-api, content-build, vets-website, and the CMS. Meta tags can be rolled out first (to staging only if we desire) and we can push those out to production safely (once we verify it doesn't affect main site search results negatively). This will get the data indexed and categorized as we need, and we can then work solely in vets-website (for the R&S search results page) and content-build (for the landing page).
 
[Search.gov meta tags](https://search.gov/indexing/metadata.html) we need to implement:

- Content type (`<meta name="dc.type" content="example">`). This should be the same content type for all R&S pages (the 7 Drupal content types that are currently searched)
- Audience (`<meta name="dcterms.audience" content="example">`). From the Drupal audience field (once it is created)
- Benefit: (`<meta name="searchgov_custom1" content="..., ..., ...">`). There is no Dublic Core or OG field category for benefits, so we will leverage a custom tag.
- Topic: (`<meta name="searchgov_custom2" content="..., ..., ...">` or `<meta name="article:tag" content="example" />`). We could probably use the "keyword" meta tag here if we think it fills the need or we can use the custom tag. Both will function with facets.

Until and unless I hear back differently from Search.gov, I will start laying out basic story mapping for this scenario.

**Comment by dsasser** [comment]
Here are the basic tasks to move to a Search.gov powered R&S search experience with a new design. Story mapping for this work has been scheduled.

## Tasks for R&S Search Powered by Search.gov

### Drupal
#### Adding new Drupal fields for Audience, Topic, Benefits
- These fields don't yet exist in Drupal [per Dave](https://dsva.slack.com/archives/C52CL1PKQ/p1736983377947279?thread_ts=1736978610.453809&cid=C52CL1PKQ).
- Size = Small

#### Populating new Drupal fields
- Will need to determine how this will need to happen be that manually or as some kind of data migration.
- Size if manual by content editors = N/A (no dev work), if automated Medium to Large (N/A to L)

#### Add Custom Meta Tags
- Tags needed: [Audience](https://search.gov/indexing/metadata.html#audience), [Benefit](https://search.gov/indexing/metadata.html#searchgov-custom-fields), [Topic](https://search.gov/indexing/metadata.html#searchgov-custom-fields), [Content Type](https://search.gov/indexing/metadata.html#content-type)
- Drupal content types to add tags to: Resources and Support Detail Page, Step by Step, FAQ Page, Q&A, Checklist, Media List Images, Media List Video
- May require custom code to replace underscores (_) with periods (.) or colons (:) as needed since the Drupal metatag modules only support underscores in tag names
- Size = Small to Medium (S-M)

### Content Build
#### Add Meta Tags to Templates
- Add tags to graphQL queries for all 7 content types
- Tag name normalization if not done in Drupal (Replacing _ with : or .)
- Size = Small (S)

#### Landing Page Redesign
- Design the landing page per [Figma design](https://www.figma.com/design/cg8VNnxFOxw7lb10FVHpi5/Resources-support?node-id=1044-9517&p=f&t=nlw5KXFssmRpHSg7-0)
- If deployed in place of current design, we will need to decide how to deal with the new filter button/side drawer
- Size = Medium (M)

#### Post Deploy Cleanup
- Remove any feature toggles or environment conditionals if used

### Vets Website
#### Search Results Page Redesign
- In the ResourcesAndSupportSearchApp React app
- Filter button
- Filter side drawer
- Filter "pills"/"chips"
- Filter accordions
- Design changes
- Utilize Search.gov as backend (via vets-api current Search API)
- Tests
Size = Extra Large (XL)

#### Post Launch Cleanup
- Remove flipper or environment conditional logic

### Vets API
- Flippers if needed
- Size = Small (S)

**Comment by mnorthuis** [comment]
@dsasser Is there an option to bring Search.gov into R&S in phases where phase one would be powering the existing search with search.gov (likely includes the search redesign work) but with no facets/filtering?  Phase two would be implementing the facets/filtering once the tags are finalized and the process for implementing and maintaining them is in place?

**Comment by dsasser** [comment]
> [@dsasser](https://github.com/dsasser) Is there an option to bring Search.gov into R&S in phases where phase one would be powering the existing search with search.gov (likely includes the search redesign work) but with no facets/filtering? Phase two would be implementing the facets/filtering once the tags are finalized and the process for implementing and maintaining them is in place?

Yes we could do this. We can add facet filtering after doing the initial design and search backend work.

**Comment by jilladams** [comment]
@FranECross do you feel comfortable with us closing this / that ACs are met with Daniel's notes above? I speculated in scrum that the original proposed meeting with Mikki/Danielle, etc. was based on possibly needing to explore solutions outside of Search.gov, but not sure if that's needed now that we aren't doing that?

**Comment by FranECross** [comment]
@jilladams I agree that we can close the ticket. I changed the AC to be that I'm pinged so I can review results with Michelle to determine next steps; and then last AC is to close the ticket (closing now). Thanks!

**Comment by jilladams** [comment]
From product sync: 
* Fran noted: @dsasser to create the tickets that arose from this spike
* Michelle would still like to close loop with @mnorthuis , so she can be aware of how Search.gov can be used for this and other potential use cases. @FranECross to schedule a meeting wtih Mikki, Daniel, MIchelle, and Jill / Danielle optional.

**Comment by FranECross** [comment]
Meeting scheduled for Monday, Feb 3rd at 1:35PT. Invited Mikki, Michelle, Fran, Daniel and Dave P, with Jill and Danielle T as optional.
