### ISSUE TITLE
Refactor hub landing page "Connect with us" block 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2045]
## Problem statement

Currently, the "Connect with us" block at the bottom of the right rail on hub landing pages contains data from the Section taxonomy terms. 

There are several problems with this content architecture:
1) Not all roles can edit Sections terms, and therefore content governance for these Connect with us blocks is associated with a role, instead of a section.  
2) In order to display the right content, hub landing pages are owned by top level terms in Sections (Disability hub landing page and other VBA related benefits is owned by VBA, Health care hub landing page is owned by VHA, Burials and memorials by NCA, and "Veterans Affairs" is the owner for the three "VA generic" hub landing pages: [Records](https://www.va.gov/records/), [Family member benefits](https://www.va.gov/family-member-benefits/), and [Service member benefits](https://www.va.gov/service-member-benefits/)). Instead, each of these hub landing pages should be owned by the same section as their child Benefits detail pages, such as "Health care benefits hub".
3) The section that should be called VACO (or VA Central Office) is called "Veterans Affairs" because it shows up as a front end label on the latter three hub landing pages. Section term names shouldn't be ever used as front ende labels.  
4) All six VBA-owned benefits hub landing must share identical "Connect with us" blocks. The same is true for the three VACO owned hubs. This is possibly an acceptable outcome, but @jenniferlee-dsva has mentioned certain use cases where slight differences between blocks would be ideal, such as adding LinkedIn on Careers, but not other VBA hubs. 

## Background

This architecture is probably the oldest technical debt in the VA CMS content model. 

We made an early, incorrect bet that Section taxonomy terms (then known as "Administration" terms) could be used to house "Office" content. 

Fixing it will be necessary to scale the Sections governance system.  

## Solutions

- [ ] Add social media fields to office nodes
- [ ] create Office nodes for each of these 4 "administrations"
- [ ] add an optional (cause of Records) entity reference to Office from Benefits Hub Landing page
- [ ] refactor FE template and query to pull the social media media fields out of the Office entity ref
- [ ] Delete fields from the Section vocabulary

Possible scenarios
* a flexible "connect with us" block type that can be used by multiple business units / offices at VA

Similar existing or future components from other products
* VAMC system "Get updates from" block

![VA_Pittsburgh_Health_Care___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/3536177c-34c4-49e0-b8ff-cdb57dc11eed)

* Campaign Landing Page social media links (incoming in Q3 2020)

![campaign-lp-content-requirements-022420_pdf.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/ca7f1aaa-a231-4d81-80f8-38426672a0a7)

## Acceptance Criteria
- [ ] When editing a Section, there are no extraneous content fields, just what's needed for content governance

**Comment by jenniferlee-dsva** [comment]
hello @kevwalsh - there are several nuanced but important details I'd like to correct/clarify ^. Will write it up here, but feel free to grab some time with me and John for a quick call. Sorry - wall o' text. 

> 2/ In order to display the right content, hub landing pages are owned by top level terms in Sections (Disability hub landing page and other VBA related benefits is owned by VBA, Health care hub landing page is owned by VHA, Burials and memorials by NCA, and "Veterans Affairs" is the owner for the three "VA generic" hub landing pages: Records, Family member benefits, and Service member benefits). Instead, each of these hub landing pages should be owned by the same section as their child Benefits detail pages, such as "Health care benefits hub".

This sounds accurate to what it is in the benefit hubs today. "Veterans Affairs" is today used more like 'VA.gov root level content' but it's always been a little off/wrong. Because root level content like Records, family member hub, Change your address, etc. should really have been treated like a Global UX owned content. That's because "Veterans Affairs" permission today seems synonymous with OIPIA-vaco owner role; and most root level content is not OPIA owned. 

> 3/ The section that should be called VACO (or VA Central Office) is called "Veterans Affairs" because it shows up as a front end label on the latter three hub landing pages. Section term names shouldn't be ever used as front ende labels.

Not sure what this means (section names vs. front end label). :-)  But see comment on # 2 - 'Veterans Affairs' today conflates OPIA owner with Global UX access, and they are actually 2 different things with 2 different access/permissions. 

> 4/ All six VBA-owned benefits hub landing must share identical "Connect with us" blocks. 

This is not true actually. MOST of the things are and should be the same; however, the Follow us social media links do vary - at least it used to until a bug during migration which I think never got fixed. 

> Continued 4/ The same is true for the three VACO owned hubs. This is possibly an acceptable outcome, but @jenniferlee-dsva has mentioned certain use cases where slight differences between blocks would be ideal, such as adding LinkedIn on Careers, but not other VBA hubs.

TBH, I think this is one of those bugs that are so unnoticeable to the business (no one has noticed or complained), I think we can simply change the rule/guidance for these SM links to be the same for all VBA hubs; but if we do, I'd like to formalize it, instead of unconsciously merging into it, and make sure we get VBA VACO's A-Okay.  

WRT the  `Connect `panel on the campaign templates:  The 'Veterans Affairs' owner is really intended to mean 'VA generic' on these campaign templates -- sometimes that could be OPIA, but sometimes literally just VA generic, as in... the Office of Construction and Blah Blah doesn't sit under VHA, VBA, NCA, or OPIA. Jenny HL mentioned there are some programs/offices like that -- they are sort of true VA-wide. 

So, in some cases, OPIA publishing a campaign page (like for MISSION Act) would use the "Veterans Affairs" `Connect `; but if the Construction office published one, they would also need to use the "Veterans Affairs" Connect panel.  I can't remember super well now, but I believe the items inside the Connect panel allows some but not total customization of contact info/links.

**Comment by msbtterswrth** [comment]
adding our notes here: 

We think it's best to move the social links field (field_social_media_links) into the 'office' content type and create pages for each of the 4 main offices. We can then potentially assign the offices to a section and those links will pull in dynamically to the connect block.
