### ISSUE TITLE
MVP for notifying all users with incident status

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2051]
## Acceptance Criteria
- [x] All CMS users have information about system outages, such as challenges to content release, or inability to access Drupal itself, to include specific messaging. 
  - [x] PAOs at VAMCs, web managers at VISN and Outreach hub content editors are updated when there are status issues
  - [x] Slack is updated for members product teams and DEPO folks
  - [x] Trigger, sensor, something that starts the process, actual process all developed
  - [x] UX Writing has reviewed and accepted
 
## Implementation steps
- [x] Email?
- [x] Site alert in Drupal?
- [x] Slack?

**Comment by oksana-c** [comment]
https://docs.google.com/document/d/1F_5wOgZ5Ie1suaFn-blHh83sgTe0pv3P_2ykxILNi2c/edit#heading=h.5owt68f9gak7
