### ISSUE TITLE
Improve access to CMS status & outages information, including content release 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2052]
## User Story or Problem Statement

CMS  users have unequal access to information about system status, outages. Not all CMS users are on slack. 

## Acceptance Criteria
- [ ] All CMS users have information about system outages, such as challenges to content release, or inability to access Drupal itself, to include specific messaging. 
  - [ ] PAOs at VAMCs, web managers at VISN and Outreach hub content editors are updated when there are status issues
  - [ ] Slack is updated for members product teams and DEPO folks
  - [ ] Trigger, sensor, something that starts the process, actual process all developed
  - [ ] UX Writing has reviewed and accepted
 
## Implementation steps
- [ ] Email?
- [ ] Site alert in Drupal?
- [ ] Slack?

MVP process for notifying all users of incident status https://docs.google.com/document/d/1F_5wOgZ5Ie1suaFn-blHh83sgTe0pv3P_2ykxILNi2c/edit#heading=h.5owt68f9gak7

**Comment by cmaeng** [comment]
@kevwalsh is this epic complete?

**Comment by sandyisland1** [comment]
@kevwalsh : Can we resolve this? I see its been added two weeks ago.
