### ISSUE TITLE
Finish proofing for Benefits detail pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2181]
## Acceptance Criteria
- [ ] Finish the POC
- [ ] https://app.zenhub.com/workspace/o/department-of-veterans-affairs/va.gov-cms/issues/936

## Implementation steps
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)
