### ISSUE TITLE
CLP: Change management (onboarding, training) for beta users

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2275]
### User Story 
As a VA.gov editor, I need to have access to training and support materials to create, edit, publish, and maintain campaign landing pages.

### Acceptance Criteria
- [ ] Three groups of Beta users are onboarded and trained
   - [ ] VEO (Tim Hudak and team)
   - [ ] VBA (Sandy Tadeo and team)
   - [ ] VHA (JHL and team)
- [ ] MVP collateral is produced (TBD)

**Comment by xiongjaneg** [comment]
TBD CMS team's role in this, discuss 2/24/21

**Comment by kevwalsh** [comment]
@xiongjaneg i just updated the title and ACs of this epic and moved it to "Epics in Progress", but also added the Needs refining label.
