### ISSUE TITLE
[LC] "Checklist" component

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2315]
## AC

- [x] "Checklist" component /paragraph fields:
    - `field_section_header` - required
    - `field_checklist_sections` | entity reference to paragraph type "Checklist item" | unlimited cardinality
    - [x]  "Checklist section" component/paragraph fields:
          - `field_section_header` | optional
          - `field_checklist_items` | plain text | unlimited cardinality
- [x] spec tool is updated w/ new content model
