### ISSUE TITLE
[LC] "Checklist" content type

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2316]
# Description

Create "Checklist" content type

## Acceptance criteria

- [x] content type "Checklist" with machine name `checklist` exists and contains the following fields:
   - [x]  **Intro text** – `field_intro_text_html_limited` – 1,000 characters max including spaces
   - [x] meta tag fields - see other content types.
   - [x]  **CTA component** -  `field_button`:
       - [x] at least 1 required
       - [x] up to 2 max
   - [x] **Checklist component** - `field_checklist` - required - single cardinality - allows for "Checklist" paragraph type only
   - [x] "Repeat CTA buttons" checkbox – boolean field `field_repeat_buttons` Example: User can omit repeat if page is short as in a single FAQ page
   - [x] Owner field is displayed in sidebar - `field_administration`
- [x] editorial experience does not suffer regressions. Any existing patterns are used. E.g. help text, widget config, etc.
- [x] Checklist content type is included in Editorial workflow
- [x] Add Content > Checklist menu item is position in the menu in the alphabetical order
- [x] spec tool is updated with new content model
