### ISSUE TITLE
VA forms need two layers of deleted tracking

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#2359]
## User Story or Problem Statement

As a lighthouse API consumer I need a deleted flag that is separate from the va_form detail page status to be able to track the status of forms and their detail pages separately.

We need to add two fields to the ve_form content type.

It would be used like this
**New form added:**
   - status = 0   (detail page not published)
   - va_form_deleted = 0 (pdf available)

**Forms detail page published:**
   - status = 1 (detail page published)
   - va_form_deleted = 0 (pdf available)

**Forms deleted:**
   - status = 0 (detail page unpublished)
   - va_form_deleted = 1 (pdf not available)
   - va_form_deleted_date  = 10/23/2019

## Acceptance Criteria
- [ ] Boolean field `va_form_deleted` exists on va_form
- [ ] Date field `va_form_deleted_date` exists on va_form
- [ ] both of these fields are in the api data grouping
- [ ] migration is updated to have the va_form_deleted come in with 0 as a default and get 1 only when 1 in "Deleted" source column from csv.
- [ ] migration is updated to have the va_form_deleted_date come get populated with a date only when 1 in "DeletedDate" source column from csv.
