### ISSUE TITLE
Maintain Drupal average planned uptime at > 99.9%

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#2368]
Our uptime percentage for Q2 was 99.85%. We want to increase that to 99.9% of planned uptime, with our eyes on trying to hit 99.99% for Q4.

AC:
- [ ] Be able to distinguish between planned and unplanned uptime
- [ ] Leverage the Grafana chart to track uptime percentages for the quarter
- [ ] Measure 99.9% uptime for the quarter on 9/30/20
