### ISSUE TITLE
CLP: Menu, breadcrumb, URL alias implementation (blocked by IA Design)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2383]
## User Story or Problem Statement

Per @johnhashva on [Slack](https://dsva.slack.com/archives/C01DS1XDEQ0/p1620047277096800?thread_ts=1619701487.087900&cid=C01DS1XDEQ0), May 3 2021

> All CLPs will sit in a new sub-directory, with a name like initiatives — e.g. va.gov/initiatives/<tbd>.  Final word on the name of this sub-directory has not been determined.
> All CLPs will derive their canonical URLs from the H1 with hyphens of the CLP -- e.g. increasing-access-to-health-care-with-the-mission-act

## Acceptance Criteria
- [ ] New CLPs automatically receive the URL alias /initiatives/[campaign-title] (where [campaign-title] is the same as the h1)
- [ ] Existing CLPs receive new URL aliases, with the exception of  va.gov/veteran-trust-in-va (node 18299)

## Implementation steps
- [ ] Update pathauto settings for CLP node type to match spec. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
This is potentially dependent on the Public Websites team's governance design for this product, because the way URL aliases get added may be done by a privileged group in an "IA governance" group. (See also #1915)

**Comment by kevwalsh** [comment]
For MVP of CLP, Content Admins can create breadcrumbs, URLs and menu items on a case-by-case basis. We'll wait to establish any other patterns until the Content & IA team has planned a medium/long-term implementation pattern.
