### ISSUE TITLE
Text format constraints for rich text fields

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2397]
## Description

All rich text/WYSIWYG fields currently offer an option to switch between preconfigured text formats. See below
<img width="1046" alt="Screen Shot 2020-07-23 at 1 19 11 PM" src="https://user-images.githubusercontent.com/16477724/88329487-4677f600-cce7-11ea-8996-802fe9254a7f.png">

Each rich text field should be configured to support only one text format option in order to prevent text format/markup options overuse and potentially abuse and also to support desired content rigidity.

## Acceptance Criteria

- [ ] rich text fields allow "Rich Text" format only and do not offer an option to switch formats:
    - list of fields TBD
- [ ] rich text fields allow "Rich Text Limited" format only and do not offer an option to switch formats:
   - list of fields TBD

## todo

- [ ] research contrib space for this problem

**Comment by oksana-c** [comment]
check for duplicates

**Comment by oksana-c** [comment]
closing in favor of #2539
