### ISSUE TITLE
Limit URL alias by role, to certain content types. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2405]
## User Story or Problem Statement

TBD

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Implementation steps
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)
