### ISSUE TITLE
Hide "plain language certified date" field from Benefits Detail Page (page) form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2407]
## User Story or Problem Statement

The Plain Language Certified date was migrated from the original vagov-content front matter. But it is out of date and not used at all. It should be hidden for now on the form, and possibly brought back later. 

This can be done at the same time as #2406 

## Acceptance Criteria
- [ ] PLC field is no longer visible on the right sidebar of /node/add/page
- [ ] verify if `page` is the only content type that has PLC field and disable (hide) it if it's found on any other forms

## Implementation steps
- [ ] Change form display for `page` content type to remove PLC date field 

![Create_Benefits_detail_page___VA_gov_CMS.jpg](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/b320c1ca-f77b-48d7-93ba-e24060e1f262)
