### ISSUE TITLE
Enforce IA design for VAMC system editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2427]
# Runbook 

## Proof of concept

- [x] #4311 SPIKE: technical implementation of VAMC system menu IA governance 

## Pre-menu lockdown

- [x] #5135 Prepare VAMC menu user guide and announcement from VHA HQ 
- [x] #5397 Remove ability for content_publishers to reorder their VAMC menus (only allow for content_admins) (Sprint 33) 
- [x] #5415 Delete old /forms landing page built with `health_care_region_page` (CMS with a headsup to Decision Tools) 
- [x] #1268 Make menu items mandatory for future VAMC detail pages #1268 (Sprint 33, @kevwalsh ) 
- [x] #5437 Reset detail page custom URL aliases before running pathauto 
- [x] #4773 Update pathauto / PR #5329 (Sprint 33, @ethanteague) (depends on #5437)
- [x] Run the bulk "Update URL alias from #4773 at `admin/content/audit/detail-pages-urls`

### Stretch: Minor menu/IA UX improvements (CMS)

- [x] #5399 Hide description and weight field (Sprint 33, @ethanteague)
- [x] #4932 Show VAMC menu on VAMC proofing pages. (Sprint 33)
- [x] #5120 Rename Detail Page content type to "VAMC Detail Page" (Sprint 33, @ethanteague)
- [x] #5470 Remove disable_node_menu_link (needs IA/product design approval)

Not yet approved/prioritized
- [ ] #5469 Prevent rewriting menu link title on VAMC Detail page (needs IA/product design approval)

### Dual State menu fixes
- [x] **CMS** #5400 Include report of all Detail pages that don’t include `-health-care`, which VAMC team can use to repair existing menu items (Sprint 33, @kevwalsh ) 
- [x]  **VAMC upgrade team** #24106 adds 4 draft parent pages to all VAMCs   (VAMC Sprint 48)
- [x] **VAMC upgrade team** #24991 Address missing and incorrect menu items (VAMC sprint 48?) based on #5400
- [x] **VAMC upgrade team** #24991 Fix malstructured menus (VAMC sprint 48?) based on #5400 (done?)

### Pittsburgh
- [x] **IA** #25044 Mikki reviews [URL spec for pittsburgh changes](https://airtable.com/shrf9O0nAUavSJjI7) (week of May 24)
- [x] **PW**  #25044 redirects PR   (CMS Sprint 33 / Mikki / Public Websites 49) - June 1
- [x] **PW/DevOps** tests redirects on staging June 2
- [x] **CMS** #5132 June 3 - Update Pittsburgh URLs on prod.cms.va.gov, then request DevOps to merge redirects to prod
- [x] ~**VHA Digital Media** Change management with Pittsburgh, TBD @davidconlon~ Decision May 27: no change management. 

## Lockdown

- [ ] #4988 Implement VAMC menu governance (Sprint 34)
- [ ] Work with VHA Digital Comms to publish announcement from #5135 

## Other

- [ ] Post-mortem for lessons learned on the Spike / Discovery / Runbook approach. (Sprint 33, @ethanteague @swirtSJW @kevwalsh @cmaeng) 

#### Later epics
   
* Pregenerated, required content, comes in with all the right menu items in the right place
* Design VAMC system IA governance for longer term, eg when the product IA changes, how is that implemented?

# Problem statement

## Current status

Editors with VA Pittsburgh health care section (and other VAMC systems) can edit their VAMC Pittsburgh menu. 

That menu should be locked down, and they should only be able to manipulate parts of it. 

To reproduce: 

*   log in as user/34  a Content publisher with Section access to VA Pittsburgh Health Care
*   Go to /admin/structure/menu/manage/pittsburgh-health-care?destination=/admin/structure/menu
*   Drag and drop 
*   Save. 

## IA / Design artifacts

*   This [IA (Moqups) doc](https://app.moqups.com/Rnc4BDEKrA/view/page/a9e1a59e9) managed by Mikki (VSP IA team) shows the required content that should not be changed. 
*   This [IA doc (spreadsheet)](https://docs.google.com/spreadsheets/d/14Mp6KpBB2wLM-xU4ypf9ZRJlYTjdufFI1drP4ygo_xo/edit#gid=1432610448) shows what should be locked down, vs what should be editable, as well as content types, and what is pre-loaded vs what is added on the fly. 

## Additional background information

*   Current menu access to it is governed by Workbench menu access. Each menu in the site is associated with 
*   When a keys to a VAMC site are handed over, the site is already generated, by VAMC upgrade team, a team with trusted editors that can have “content admin” users. 
*   There’s a possibility of automating the generation of some of this content and menu items, but that’s not currently in scope

## Research questions (for Facilities and/or VAMC upgrade team)

*  Do we have the “pre-loaded” and “required” content correct in our spreadsheet?
* For now, is it sufficient to lock down menus to “content admin”, while we 

## Governance design decisions 

1. Remove menu administration permissions from all VAMC users
2. Continue to rely on workbench access to determine section-based editing. Eg a PAO should still be able edit all content in that section(without changing menu items)
3. Make sure that VAMC upgrade team has all the right permissions to pregenerate content with menus
4. **Allow VAMC editors to add to their menus in very constrained ways**
    1. Detail pages can only go in About us section? 
    2. How to handle the existing current detail pages that are “outside” About us? 
        1. Content model changes
    3. Can we Use URL aliases to determine permissions for menu items? 
        2. Form validation based on the URL alias created according to menu item placement? 
        3. EG: create a list of url alias patterns for eligible parent menu items, based on role
            1. /[health-care-system]/programs/
            2. /[health-care-system]/research/
            3. /[health-care-system]/etc
        4. VAMC editors still need to be able edit detail pages that don’t have these patterns (eg Facility maps)
        5. Roles vs section permissions
            4. Menu item administration (reordering etc) based on role
            5. Menu item from nodes could be based on section
5. Design an editorial experience to support this
    4. Should we render smaller parts of menu that are eligible?
6. Update user guides and training to explain menu editing, including these constraints and the why

**Comment by davidconlon** [comment]
@kevwalsh Can't read the spreadsheet b/c it's in google docs.
How do you want me to go about answering some of the above questions?

**Comment by kevwalsh** [comment]
Hi @davidconlon , sorry i missed this comment above. Sometimes github notifications go unseen. 

I'll add this to Friday's 10:30am agenda, and we can aim to complete the plan (probably with an accompany technical spike in our next Sprint). 

Here's the XLSX version of that file. 

[VAMC IA governance analysis.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5871323/VAMC.IA.governance.analysis.xlsx)

and here's my latest thinking about how to approach this (no input yet from @swirtSJW , but that's coming soon)

**Comment by kevwalsh** [comment]
Results of update to URL paths, after running "Update URL alias" on prod this morning. 

[Prod June 9 - URL update-1632 updated paths, 1373 unchanged.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6624580/Prod.June.9.-.URL.update-1632.updated.paths.1373.unchanged.csv)

**Comment by kevwalsh** [comment]
I moved out two issues to other epics so we can close this.
