### ISSUE TITLE
Improve CMS user guide content model part 2

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2438]
## User Story or Problem Statement

User guides need additional content design tools to improve page hierarchy and flow

## Acceptance Criteria
- [ ] I can add a 3 column layout to a user guide page
- [ ] i can add link teasers or list of links to 3 columns

## Implementation steps
- [ ] Two new paragraph types, with appropriate form and view mode displays
- [ ] Enable on user guides, with paragraph browser experience.
