### ISSUE TITLE
Refactor post-deployment-tasks to run before ASG removal

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#2494]
See EPIC #1713. 

AC:

1. Before the new instance(s) go into rotation, the post-deploy-tasks should have run already so that the code state matches the DB state

Implementation Notes:
This will require a refactor of the `deploy-asg` role as the that role also has e.g. `cleanup-asg` types of tasks that need to run after the deploy tasks and the way that Ansible works you can only have one `hosts` target per Play so we need to move the cleanup ASG task afterwards and "sandwich" the deploy with that.

**Comment by ElijahLynn** [comment]
- [ ] Figure out how to do this
- [ ] Make PR
- [ ] Test on CMS-TEST environment
- [ ] Make sure it doesn't break other apps
- [ ] Merge and Deploy

**Comment by ElijahLynn** [comment]
K, so our testing worked partially, but we ran into an issue that is a blocker. The issue that the new instance go into the InService state immediately after launching because their is no lifecycle hook because we dynamically create a new ASG on every deployment. Which is problematic because ASGs are supposed to static resources that have pre-existing lifecycle hooks that are there before any instances launch. When a lifecycle hook doesn't exist the default behavior is to just put it into InService and if did exist then the default behavior is to put it into the Pending state, then we could mark instances properly after config operations have run and it is ready. SO....

New plan: Turns out we are not using ASGs with lifecycle hooks correctly and need to fork the deploy-asg role and modify the entire deployment type to use static ASGs with proper lifecycle hooks so that we can run post-deployment-tasks and then run a complete-lifecycle action hook on the instance(s) after that is done to move them from pending to InService.

1. Use static ASGs on deploys (Terraform) - This will have a pre-defined lifecycle hook we can use properly
1. Consider using Ansible Async task for ec2_asg update with the instance refresh option, so we can run deployment hooks while that task is running so that we can transition them from Pending to InService. 
1. OR
1. Change max instances and desired instances temporarily for deployment only, they will launch in pending state, run post deploy tasks, then run a complete-lifecycle-action to transition them, then change max and desired instances back to ideal state.

**Task List**
- [ ] Create ASGs in Terraform (separate PR)
- [ ] Move cleanup-asg back to deploy-asg
- [ ] Update ASG Names to not have the date in it in Ansible tasks (e.g. dsva-vagov-staging-deployment-vagov-staging-cms-test-20200730-221334-asg)
- [ ] Create new deployment target role in BRD, deploy-asg-lifecyle (Demian consulted with us already on this)
- [ ] Rip out the stuff that won't be used (if we copy/fork the deploy-asg role)
- [ ] Create task to update ASG max/desired instances
- [ ] Modify launch template update (e.g. date won't be in ASG name anymore etc)
- [ ] Run post-deploy-tasks (run_once: true)
- [ ] Create a lifecycle complete Play or Task to update on all instance

**Comment by ElijahLynn** [comment]
Opened upstream issue to support Template Tags for the https://docs.ansible.com/ansible/latest/modules/ec2_launch_template_module.html here https://github.com/ansible/ansible/issues/71101.

**Comment by olivereri** [comment]
https://github.com/ansible/ansible/issues/71169
Currently seeing an issue with refresh_inventory not working as intended. Opened an upstream issue here.

**Comment by ElijahLynn** [comment]
> [ansible/ansible#71169](https://github.com/ansible/ansible/issues/71169)
> Currently seeing an issue with refresh_inventory not working as intended. Opened an upstream issue here.

We got refresh_inventory inventory working with the suggestion in https://github.com/ansible/ansible/issues/71169 to use the aws_ec2 inventory plugin!

**Comment by ElijahLynn** [comment]
We also discussed and are implementing now moving the test run out of our post-deploy-tasks and into its own Jenkins job so that it is easier to distinguish deploy failures from test failures, which will consist of the following tasks. 

- [ ] Create new testing job entry in the seed job
- [ ] Create new groovy "CMS-TESTING" job that is triggered as a downstream job from a successful deployment job, may have to update the DEV/STAGING deploy jobs to trigger this new. (figure out naming as we already have a job in the "testing" folder which is confusing anyways because it doesn't actually test anything, but is a wrapper around the build and then deploy process). 
- [ ] Create a new Ansible playbook that the new groovy job runs the `composer yaml-tests` tasks in it and move out those tasks from the post-deploy-tasks file. 
- [ ]  Configure to notify Slack, #cms-notifications on testing failure.

**Comment by ElijahLynn** [comment]
Updated the runbook in comment above https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2494#issuecomment-666844645.

**Comment by olivereri** [comment]
Working Run book here:
https://docs.google.com/document/d/1ibi_NlH8_GJnK-TesIxGNzJDprgHl3AwScQB4aX5qWM/edit?usp=sharing

**Comment by ElijahLynn** [comment]
W00t! This was just deployed and our deploy times went from 12 minutes to 6 minutes! Our testing on cms-test showed closer to 4 minutes and I haven't looked into _why_ yet. 

![image](https://user-images.githubusercontent.com/1504756/91249884-9265f280-e70c-11ea-9b30-9d96e17a7678.png)

**Comment by ElijahLynn** [comment]
Here is the output of the final working run book here, for the record:

![image](https://user-images.githubusercontent.com/1504756/91250113-18823900-e70d-11ea-88b8-324103323b3b.png)
