### ISSUE TITLE
"Hold my draft" research

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2501]
## User Story or Problem Statement

From https://www.drupal.org/project/hold_my_draft: 
> With core revisions, you cannot easily edit a published revision state without losing work or publishing work in progress.
> The common use case:
> Published revision
> Many forward drafts with a new page section being written. Waiting on approval.
> And then... a typo is discovered on the published page! What is a content editor to do? Hold my draft...

## Acceptance Criteria
* We determine whether "Hold My Draft" offers a viable solution to Public Websites teams needs, with our current use case. 

## Implementation steps
- [ ] Install Hold My Draft on a PR environment
- [ ] consider the following constraints
   * permissions by role
   * ability to remove this solution without consequences to content when we're ready to switch to a new solution
   * UX/UI/workflow should not provide more mental overhead to the user than current workaround solution
   * ability to extend this module (UI/features)
   * hold_my_draft solution does not introduce regressions into current workflow and is compatible with `workflow`, `content_moderation` and `content_export` module
- [ ] Initial review and POC share w/ @jordanamello @indytechcook @oksana-c

**Comment by indytechcook** [comment]
Included in the evaluation criteria should be how it works with core `workflow` and `content_moderation` module.

**Comment by oksana-c** [comment]
Team discussion takeaways:

* hold_my_draft solution:
   *  introduces too much risk into editorial workflow
   * needs significant amount of UX/UI overrides
* needs in depth review and prioritization as a Product Support team initiative

Conclusion: Icebox until further requests come from users.

**Comment by kevwalsh** [comment]
Some screenshots of UI 

![Revisions_for_VA_health_care_and_other_insurance___VA_gov_CMS](https://user-images.githubusercontent.com/643678/97618799-dff52900-19f5-11eb-8aff-a527ca6ee662.jpg)

![Are_you_sure_you_want_to_start_a_draft-hold____VA_gov_CMS](https://user-images.githubusercontent.com/643678/97618915-fdc28e00-19f5-11eb-891c-3850916c1052.jpg)

![Edit_Benefits_detail_page_VA_health_care_and_other_insurance___VA_gov_CMS](https://user-images.githubusercontent.com/643678/97626143-ceb11a00-19ff-11eb-9738-6fd17831a810.jpg)


![Revisions_for_VA_health_care_and_other_insurance___VA_gov_CMS](https://user-images.githubusercontent.com/643678/97626214-e4beda80-19ff-11eb-821a-668007e8d1cc.jpg)

**Comment by EWashb** [comment]
we can revisit if needed
