### ISSUE TITLE
[LC] Automated Meta Title

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2547]
## Acceptance Criteria
- [ ] Meta title is auto generated for LC content types using H1 with appended `| Veterans Affairs`.  E.g. `How to change your VA address online | Veterans Affairs` - this should be done using the metatag module config
- [ ] The Meta title field should be completely removed from the LC content types.
- [ ] Existing tests should be appropriately updated
- [ ] A test to confirm the correct meta title generation for LC types should be added

LC content types: 
* Checklist
* Step-by-step
* Media list -Images
* Media list - Videos
* Q&A
* FAQ - multiple Q&As
* Learning Center Detail Page
