### ISSUE TITLE
CMS Design System tokens -old epic

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2650]
## Description

The VACMS Design System should be based on consistent palettes of typography, spacing units, color, and other discrete elements of style.

@DanielMiller-agile6 compiled [resources related to various aspects of the upcoming Design System work](https://drive.google.com/drive/folders/1AtB5qmWroaRNtmOVDAdQYIIuQWZB0MWH?usp=sharing).

A set of VACMS Design System tokens will allow for efficient prototyping and front-end/theming work while the rest of the Design System is being established.

## Acceptance Criteria
- [ ] compiled Design System resources are reviewed. Special attention on [Gap Analysis: Theme (Palette, Typography, Spacing, Icons)](https://docs.google.com/document/d/1-VGT2syRIif1vr3Zrr3jLh2LCKUyQoAHzzUkhDgJVsI/edit?usp=sharing)
- [ ] a minimal set of Design System tokens is established
    - [ ] color tokens
    - [ ] typography & rhythm 
    - [ ] spacing & grid system
    - [ ] icons (define whether the OS set from Font awesome is sufficient; if not - connect w/ someone in VA design channel to explore possibilities for using paid version of fontawesome; alternatively - keep expanding our own svg icon set)
- [ ] established tokens exist in a format that is easy to reference by the CMS design and engineering team

**Comment by oksana-c** [comment]
linking slack thread where we discussed ACs https://dsva.slack.com/archives/CDKB88PS8/p1598373066001900
