### ISSUE TITLE
Remove git branch info from admin menu for all users except admin

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2739]
## User Story or Problem Statement

As a _____, I need _____ so I can _____.

or

Problem description. How might we _____________ ?

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Implementation steps
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)
