### ISSUE TITLE
Favicons for prod and lower environments

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2746]
## User Story or Problem Statement

As a site user, i want a favicon so i know what's in my browser tab!

## Acceptance Criteria
- [ ] Prod has a favicon
- [ ] Lower environments have a favicon (or several)

## Implementation steps
- [ ] Pick a favicon 
- [ ] Create a variant (or variants) of it for non-prod environments.
- [ ] Implement

**Comment by kevwalsh** [comment]
Dupe of #5373

**Comment by kevwalsh** [comment]
This was not a dupe. #5373 is the PR.

**Comment by kevwalsh** [comment]
This was a dupe of #5372.
