### ISSUE TITLE
[LC] Field updates in Checklist component

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2814]
per request in https://github.com/department-of-veterans-affairs/va.gov-team/issues/12537#issuecomment-681086670

### New fields
- [x] New `Checklist` paragraph field `/admin/structure/paragraphs_type/checklist/fields`: "Section intro" `field_section_intro` | optional | Text (Plain, long) | max chars - 300 | positioned under Section Header in form and preview modes.
- [x] New `Checklist section` paragraph field `/admin/structure/paragraphs_type/checklist_item/fields`: "Section intro" `field_section_intro` | optional | Text (Plain, long) | max chars - 300 | positioned under Section Header in form and preview modes.

### Field updates

- [x] `Checklist` and `Checklist section` paragraph fields "Section Header" `field_section_header` have character limit 70.
