### ISSUE TITLE
Enable EWA content moderation transitions

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2853]
## User Story or Problem Statement

For the health services data cull, VAMC editors could use an "Approved" moderation state to show that they have completed the data call for a given service. 

This is already on the roadmap for EWA in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2078, but we only want to implement the Approve transition for now, not the "Assign" transition. 

![ZoomAnnotationMsgWnd](https://user-images.githubusercontent.com/643678/92268146-dba60700-eeaf-11ea-98e6-15787cd6a9f9.jpg)

## Acceptance Criteria
- [x] All permissions for transitions highlighted in green are implemented
- [x] "Approved" moderation state appears in dropdowns on content listing filters (such as /admin/content and sections pages)
- [ ] Release note has been written for all users. 

## Implementation steps
- [x] Update permissions for transitions

**Comment by kaise-lafrai** [comment]
@kevwalsh 

Changes made:

- Content Admin:
  - **Added**:   - 'use editorial transition approve'

- Content Editor:
  - **Removed**:    - 'use editorial transition archived_published'

- Content Publisher:
  - **Added**:     - 'use editorial transition approve'

**Comment by kaise-lafrai** [comment]
@kevwalsh Updated comment above.

**Comment by kevwalsh** [comment]
@kaise-lafrai that looks right to me!

**Comment by kaise-lafrai** [comment]
@kevwalsh Okay then -- Gonna push out a PR so it can be officially tested.
