### ISSUE TITLE
EWA: Entity meta block follow-up

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2861]
##  Acceptance Criteria

- [ ] "Entity Meta Display" block is displayed on node revision pages, e.g. /node/2/revisions/23101/view
- [ ] "Entity Meta Display" block displays "Va.gov URL" data based on the following rules
   - [ ] Va.gov URL is taken from latest published revision. Otherwise not displayed at all
       - [ ] logic for VA.gov URL display - if  ~env = prod and~ node has a published revision and node doesn't have an archived revision (archived rev ID is higher than latest published rev ID) -> display the URL
      - [ ] ~if latest published revision ID is greater than currently viewed revision ID AND URL alias of currently viewed revision is equal to latest published revision URL alias value, then Va.gov URL should be displayed using latest published revision alias. Otherwise, VA.gov URL should not be displayed, because it's no longer accurate.~ 
      - [ ] use the alias we have (since it's not revisionable)
      - [ ] if there's any published revision, check if URL exists on prod [200 OK], if it doesn't - gray it out and add "pending" label to it. Colors used to style inactive link are passing contrast test 

## Implementation

* `docroot/modules/custom/va_gov_workflow_assignments/src/Plugin/Block/EntityMetaDisplay.php`

**Comment by kevwalsh** [comment]
AC moved to a separate issue, #3100,  in the icebox

- [ ]  "Entity Meta Display" block displays "Owner" data based on currently viewed revision.

**Comment by kevwalsh** [comment]
Splitting this out because it's higher priority (actually, becoming a defect) in #3131

- [ ] "Entity Meta Display" block is not displayed on the CMS Help Page content type nodes (currently displayed on all)

**Comment by acrollet** [comment]
@oksana-c regarding this AC:

>  if latest published revision ID is greater than currently viewed revision ID AND URL alias of currently viewed revision is equal to latest published revision URL alias value, then Va.gov URL should be displayed using latest published revision alias. Otherwise, VA.gov URL should not be displayed, because it's no longer accurate.

In my testing as of now, only one path alias is stored for a given node and all its revisions, whether using automatically generated or manually created alias. We could work around this for automatically aliased nodes by manually generating the alias for the revision in question and comparing against the live alias, but this wouldn't catch the case when the alias pattern has been updated. I'd suggest that we not display the va.gov URL when viewing any revision older than the currently published revision?

**Comment by acrollet** [comment]
UX/UI in issue mini-spike:

As things stand now, we can't always know the correct va.gov URL for a piece of content if its URL in Drupal has been updated and a content deploy hasn't yet happened. We're checking if the va.gov URL we have is live, and if not, we:

- gray out the URL
- make it not clickable
- add the text (pending) after it

Screenshot:

<img width="414" alt="Screen Shot 2020-10-21 at 3 21 45 PM" src="https://user-images.githubusercontent.com/101649/96788749-34265a80-13b1-11eb-971c-a1a50a551c23.png">

@rachel-kauff @jordanamello @nataliedunbarCS Please feel free to add any feedback/suggestions here or add a follow-on for improvements if this has already been closed. :-)

**Comment by rachel-kauff** [comment]
@jordanamello What do you think? Is the (pending) label enough? I think so.
