### ISSUE TITLE
Resources and support MVP 1.1 [PW]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#2915]
## Background

[MVP 1.0](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1975) - October 2020
MVP 1.1 - December 18/21, 2020
IRIS content migrated into the CMS
IRIS content editors team will be onboarded after release 1.1 - current ETA end of Q1 2021

* [Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1588167553516/2773c854e8ff3a725a5e3ee03272b78e8519f78b)
* [PW/CMS standing agenda with notes and action items](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/cms/readme.md)
* [Learning Center template requirements](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/template-requirements.md#about)

### Affected users and stakeholders

* CMS editors of R&S product
* Engineers on the CMS and PW team

### Assumptions

* content in R&S MVP 1.1 is managed by Public websites team. ~Other SMEs / call center authors onboarding ETA end of Q1 2021~

## Acceptance Criteria

- [ ] R&S MVP 1.1 CMS content model is ready for content intake and publishing workflow on production
    - [ ] Content types include: Media list- Images, Media list- Videos
- [ ] ~governance of the Resources and support product is defined based on PW team research findings about SME/call center author workflows~ Postponed
- [ ] ~the CMS team started to develop training materials / user guides to support onboarding of R&S SMEs/call center authors at the end of Q1 2021~ Postponed
