### ISSUE TITLE
Improve editorial experience and governance of React Widgets

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#2919]
### User Story or Problem Statement

There are dozens of react widgets placed on detail pages across the CMS, primarily in Benefits Hubs pages and VAMC detail pages. The current implementation supports the `widgetTypes` defined [here in vets-website](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/platform/site-wide/cta-widget/helpers.js)

The current experience for adding and editing these in the CMS is sub-optimal, prone to user error. [See relevant slack thread](https://dsva.slack.com/archives/C01H29ERVJ7/p1621270321259200)

<details><summary>Screenshots 
</summary>

![VA_Pittsburgh_Health_Care___Medical_Records_Office___Veterans_Affairs.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/f79c98b3-bc3e-4ab5-9072-7e5982eeab66)

![Edit_Detail_Page_Medical_records_office___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/10637535-907a-4098-b57f-350c125e3700)

</details>

How might we improve the governance and editorial experience of react widgets in the VA.gov CMS?

### Affected users and stakeholders

* Product teams who design and manage react widgets
* Editors who place react widgets into content

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public

### Hypothesis

We believe that a React widget block library will make it easier to manage, add, and govern react widgets across the site. 

### Assumptions

- [ ] We can identify a React widget library owner (eg Public Websites?)

## Acceptance Criteria
- [ ] All CMS-eligible react widgets are cataloged in a library
- [ ] Editors with the right permissions can add react widgets in certain parts of the CMS, based on the content model
- [ ] We have documentation in va.gov-team repo about governance for these react widgets, and how product teams can let CMS known about a new react widget. 
- [ ] Existing widgets are migrated from legacy content model to new content model. 

## Runbook  (order TBD)
1. Design content model and editorial experience for library of react widgets
1. Determine runbook details (backwards compatibility etc)
1. Implement content model to support backwards compatibility
1. Write migration (or create manual migration plan) to move existing react widgets to new widgets. 
1. Adjust front end templates to support both new and old content model
1. Run migration if necessary
1. Remove support in FE for old conent model
1. Remove old content model

**Comment by ContentBrewmaster** [comment]
Added change management triage. Need to validate choices in this section.

**Comment by wesrowe** [comment]
@kevwalsh, I see you added the PW label in April – can you confirm whether this stil belongs in the icebox?

**Comment by wesrowe** [comment]
cc @jilladams

**Comment by FranECross** [comment]
All tickets in this epic are closed; closing epic
