### ISSUE TITLE
VAMC top task content model and governance discovery

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3025]
### User Story or Problem Statement

- Governance problem space
  - Engineering
  - Content strategy
- Content audit and design

### Affected users and stakeholders

* CMS product support team
* Facilities Product Owner

## Acceptance Criteria
- [x] We have selected one or two top task pages for initial implementation 
- [ ] We have selected a technical solution to achieve this
- [ ] We have designed sufficient editorial experience patterns to support the diversity of these pages (or, the first two or three pages)
- [ ] We have updated the ACs for the Top task pages that are the first to be implemented (eg #3046 for Policies)

**Comment by cmaeng** [comment]
reporting this closure in sprint 19.
