### ISSUE TITLE
R&S Support & Editor Training

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3028]
### Problem Statement

Learning Center is a new product. LC content for MVP 1.0 (Oct 2020) and MVP 1.1 (Dec 2020) will be managed by Public Websites team.

Even though all PW team editors are experienced CMS users, there will be a need to include LC training material in the CMS user guides and provide some level of user training and support.

### User Story

As a LC content author/editor, who is starting to use Learning Center editing tools, I need to have access to related training materials and human support to answer any quick questions, so I can perform my tasks efficiently.

### Affected users and stakeholders

* CMS editors of Learning Center product
* The CMS Helpdesk team

## Acceptance Criteria

- [ ] LC training materials exist
- [ ] LC training module exists
- [ ] CMS Helpdesk is onboarded on the LC product to carry out daily user support requests

**Comment by stefaniefgray** [comment]
@cmaeng Troy and I are in the process of cleaning up older tickets -- are we still going to be working on this? Thanks!

**Comment by cmaeng** [comment]
@stefaniefgray i don't have a good sense for where this all landed. best to reach out to @davidconlon to verify if this might be resuscitated.
