### ISSUE TITLE
R&S Homepage Iteration

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3031]
## Background

Resources and support (R&S) MVP 1.0 Homepage is manually curated using "Landing Page" content type. 
R&S Homepage MVP 1.0 contains buckets of content grouped by 2 R&S Category terms.
In MVP 1.1, content grouped by Audience terms will be added.

As the number of content and content categories in R&S grows, the R&S homepage will become more difficult to curate manually.

### Affected users and stakeholders

* PW team editors who manage R&S Homepage

### Hypothesis

We believe that automation of R&S homepage content grouping will simplify R&S Homepage curation.

### Assumptions

* R&S Homepage may be partially or fully automated. We will know the level of automation required after a deeper dive into the R&S homepage needs with the PW team.

## Acceptance Criteria

- [ ] The CMS team explored the needs of PW team for curating R&S Homepage content
- [ ] R&S homepage automation strategy has been defined
- [ ] Runbook for rolling out the new R&S homepage is defined and includes
    - [ ] change management strategy
    - [ ] user training for the updated homepage curation process
    

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

**Comment by EWashb** [comment]
@jilladams wanted to flag this backlog item for you. I think I heard you're working on R&S so this might be helpful or need to move to your backlog?

**Comment by FranECross** [comment]
Old ticket; closing.
