### ISSUE TITLE
VAMC system "Policies" page content type and governance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3046]
These ACs may evolve based on the discovery performed in #3025 

- [x] VAMC team will create a VAMC policies new one and clone for all new VAMC systems.
- [x] Choose a VAMC to launch first: Butler
- [x] Timing for making this change Butler 
- [x] Draft communication about centralized Policies content should come from JHL/VHA HQ, eg:

```
Because policies are much the same across all VA Health Care systems, we are adding a new standardized VAMC System Policies Page to every VAMC website. These pages contain newly standardized content, but also opportunities for each VAMC to add additional policies specific to their system. 

You can find this page at prod.cms.va.gov/[system-health-care]/policies (example:  prod.cms.va.gov/butler-health-care/policies.  For each health care system with content managed in Drupal, we have migrated any local content that had been added, so you can start using this new one immediately. 

To learn more about managing your new VAMC System Policies Page, watch this [training video](link to video).

This the first of a half-dozen pages that will be launching throughout 2021 to help standardize, and to reduce the overall content maintenance burden. 

Please let me know if you have any questions.

[JHL]
VHA Digital  Comms
```

- [ ] Next steps to get alignment around announcement.

**ACs**
- [x] Every VAMC system has a single Policies page 
- [x] Content model is implemented according to specs determined 
- [x] Governance is implemented according to specs determined 
- [ ] User guide is created, or "top task" parent page is updated
- [x] Editorial experience has been designed and implemented
- [ ] Content has been migrated or otherwise populated 
- [ ] VHA Digital Comms team have been trained in editing nationally-governed content
- [ ] PAOs have received training or other guidance on this change
- [ ] Only one Policies page can be added, per VAMC system.

**Comment by kevwalsh** [comment]
This was completed in Q3 2020
