### ISSUE TITLE
Product taxonomy

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3074]
## Background

We need to have a canonical list of Products with information about them that is easily accessible by all team members.

### User Story or Problem Statement

As a CMS team member, I need to be able to find information about a specific Product without searching multiple GitHub issues.

### Affected users and stakeholders

* CMS editors
* CMS engineers / designers / content strategists 

### Hypothesis

We believe that a full-fledged product taxonomy in the CMS will assist with building Product dashboards and any Product-related UI required to improve Authoring Experience within the CMS.

We believe that having a full-fledged product taxonomy in the CMS will allow us to structure a more granular access to certain products than Sections taxonomy/user roles currently allow.

###  Opportunities:
* Dashboard / section tagging
* User Guide tagging
* CMS Announcement tagging
* Canonical source of the following info:
    - [ ] Product label
    - [ ]  Product machine name
        * for use in field name in various content types, etc
        * Users may have permissions/ roles that are named using label / machine names of products
    - [ ]  Description - Mission / vision - for use in user guide, possibly dashboards, CMS homepage can pull this info
    - [ ]  Product Owner - user profile entity ref
    - [ ] Stakeholder info
    - [ ] Content success metrics. E.g. moderation state - this product is 80% published / 20% draft. Plain language certified - 50% of content if plain lang certified, etc.
* User dashboards - Products I work on. Having related role would be a good way to manage this
    
Mikki Northuis organized github dir of all existing product. Connect to get more information.

## Acceptance Criteria
- [ ] canonical list of Products managed in the CMS
- [ ] strategy for introducing Product-based access permissions
- [ ] other TBD

**Comment by EWashb** [comment]
We have outgrown the scope of this ticket since many product teams are building in Drupal. however, all of the associated tickets in this epic are complete
