### ISSUE TITLE
User communication standards and process

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3114]
### Problem Statement

The CMS application needs to have a defined process and patterns for alert messages released to the CMS users in various scenarios.

The scope of this process definition are alerts initiated by the system/CMS team and it’s not a result of the user’s actions.

Example - https://design.va.gov/patterns/messaging-dictionary 

We do have Slack/email messaging templates for certain situations, such as outages, publishing delays, and release notes. There’s plenty to expand on here, but for those who are sending out comms to our users, it’s helpful to get a sense of our current language patterns. :point_right: [Check it out](https://docs.google.com/document/d/1AbGy4OIzm_RjPEIIhS8MZfhDbJBzCo6pKUKbEGnfcl8/edit).

### Affected users and stakeholders

* CMS users
* the CMS team

### Hypothesis

Having clearly outlined process for releasing important system-related issues or status alerts to the CMS users will improve both user experience and the CMS team workflows when unexpected issues arise.

## Acceptance Criteria

- [ ] Current user communication processes are audited and documented in an inventory
- [ ] Develop design system components for: site alerts, error messages, etc. 
- [ ] Messaging guidelines are developed in an alert message matrix 
- [ ] alert message matrix is available in the CMS Design system documentation
- [ ] Messaging guidelines are incorporated into styleguide so that others know how to approach writing new messages.

**Comment by stefaniefgray** [comment]
@cmaeng @TroyA6 and I are doing ticket refinement and think that this one could likely be closed -- what do you think?

**Comment by cmaeng** [comment]
@stefaniefgray this effort never really got off the ground. i would touch base with @EWashb to see if she wants to keep this as a thing or just close and revisit if needed.

**Comment by EWashb** [comment]
@stefaniefgray if you and Troy feel good about the templated responses you have already in place we can close this one

**Comment by stefaniefgray** [comment]
We already have sitewide alert language documented on Confluence; closing
