### ISSUE TITLE
Register for care, Billing and insurance, Medical records top task pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3151]
## Background 

Each of the 140 VAMCs has one of each 
* Billing and insurance
* Medical records
* Register for care 

These pages have been created as unstructured "VAMC detail pages", and are being standardized, each with their own content type, and leveraging "Centralized content" nodes for the bit sof content that are standardized, to ensure consistency, quality, and semantic content across VAMCs.

### User story
As a VAMC editor, I need to reflect accurate hours and locations for my facility/ies billing and insurance, medical records and registration services so that Veterans can easily find and access those services.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [x] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public

### High level content model 

<details><summary>Screenshot</summary>

From https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8 

<img width="716" alt="VA_gov_High_level_content_model" src="https://user-images.githubusercontent.com/643678/140074006-cc8d5bf0-6fbd-4c99-aaa6-b59769a65821.png">

</details>

### Resources

For each of the three top task content types and the new VHA facility nonclinical service content type, there are various artifacts/resources cataloged [in this google spreadsheet](https://docs.google.com/spreadsheets/d/18amXr7dMIFnf5axyJwDbTAW5xEI2M1zXrn8FvGIKcHc/edit?usp=drive_open&ouid=114216740278804672394).

**Comment by kevwalsh** [comment]
Closing this, remaining tasks are in VHA DM's hands, and user support.
