### ISSUE TITLE
Discovery on recurring events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3252]
## Description

As a Product Support Team, i want a hypothesis for solving the commonly requested feature of recurring events, so that i can begin design and implementation. 

## Acceptance Criteria
- [ ] Understanding of user stories for various users of Event content type
- [ ] Understanding of open source landscape (drupal contrib) for supporting recurring events
- [ ] Roadmap for first iteration on recurring events. 
- [ ] identify what other Events user stories (#1605) may align with this roadmap, to include within this iteration
- [ ] What if any FE development will be required
- [ ] What if any Content API changes may be needed.

**Comment by kevwalsh** [comment]
Closing this, design and implementation approach still being determined via individual issues.
