### ISSUE TITLE
Research: Notification Preferences

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3268]
Series of interviews to gauge user habits about email preferences (MVP for notifications is email as of June 2022)

## Acceptance Criteria

- [ ] We identified what we want to know from our users (e.g. how people handle the various notifications they receive, what catches their attention etc.)
- [ ] We identified who we'd like to interview and what questions we want to ask
    * posted in va.gov-team repo cms research space and linked to this issue
- [ ] Interviews are scheduled ~5.
- [ ] Interviews are concluded.
- [ ] Data from the interviews is synthesized and opportunities for the CMS notification framework are mapped out.
- [ ] Information is shared with Spike group
    * lightweight written summary (github)
    * 30 mins zoom call discussion w/ team

**Comment by EWashb** [comment]
This may not be accurate for current state as of 2nd Q 2022, but reassigning this ticket to the correct epic for later refinement

**Comment by EWashb** [comment]
@swirtSJW Wanted your insight here. Once we get the email and slack technical parts of this out, would this be the next step in your opinion? Or maybe this is a concurrent step with some other tech effort.

**Comment by EWashb** [comment]
We need current state refinement. This should be broken down into possibly at least 3 tickets.

**Comment by EWashb** [comment]
closing in favor of current state tickets like #9552
