### ISSUE TITLE
Accelerate software delivery

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3304]
### User Story or Problem Statement

**As a team, we should optimize our software delivery process.**

### Affected users and stakeholders

* engineers of the CMS team

### Hypothesis

We can accelerate our software delivery process by reducing cycle time from PR open to PR deploy.

We will know that our process is optimized when our average cycle time is less than 48 hrs.

### Assumptions

* the team is willing to redefine our code review/release processes
* we are moving to a new CI infrastructure
* we are making an effort to parallelize our tests

## Acceptance Criteria

- [ ] code review/release processes are redefined
- [ ] code quality standards are reviewed and redefined
- [ ] Core Application and Product Support teams are in alignment on the established processes

**Comment by cmaeng** [comment]
Closing this epic in favor of quarterly timeboxed ones
