### ISSUE TITLE
Upgrade simplesaml php 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3323]
**Describe the defect**
There are several critical issues related to our outdated version of simplesamlphp  

1. https://github.com/department-of-veterans-affairs/va.gov-cms/network/alert/simplesamlphp-1.17.2/composer.lock/symfony%2Fhttp-foundation/open
2. https://github.com/department-of-veterans-affairs/va.gov-cms/network/alert/simplesamlphp-1.17.2/composer.lock/symfony%2Fdependency-injection/open
3. https://github.com/department-of-veterans-affairs/va.gov-cms/network/alert/simplesamlphp-1.17.2/composer.lock/robrichards%2Fxmlseclibs/open

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information if relevant, or delete):**

**Additional context**
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

**Tasks**
- [x] Update dependency
- [x] Update Drupal module
- [x] Add/remove/update any patches
- [x] Copy vendor folder over simplesamlphp-1.17 and re-apply any changes (diff the old version and folder) 
- [x] Update any post-install scripts in composer.json
- [ ] QA on DEV

**Comment by ElijahLynn** [comment]
We are currently on 1.17.2 and 1.17.8 has some of the updates needed but not all, so we need to jump up a minor release to 1.18.8. This requires our drupal/simplesamlphp_auth to be updated as well as there was a dependency update just for this library update here https://www.drupal.org/node/3097283. 

I am making a PR for this now and testing on DEV. 

Related links for me:
https://github.com/simplesamlphp/simplesamlphp/releases
https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.19/docs/simplesamlphp-changelog.md
https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-1.18
https://www.drupal.org/project/simplesamlphp_auth/releases/8.x-3.2

**Comment by ElijahLynn** [comment]
Here is the PR for this change, https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3336. However, I cannot test on DEV right now as even without this PR, I am getting a 403 Forbidden error so I will need to get that working first. 

![image](https://user-images.githubusercontent.com/1504756/97524957-fc945100-1962-11eb-8e83-36d5deb11c2f.png)

**Comment by ElijahLynn** [comment]
Deploying to DEV now (internal) http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-dev/838/console. Will test in the AM.

**Comment by ElijahLynn** [comment]
The deploy failed due to config that didn't lay down right because of the name change. Need to make a devops repo change for this, in progress.
