### ISSUE TITLE
Upload multiple PDFs at once

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3427]
## User Story or Problem Statement

As a CMS editor with a lot of PDFs i want to post, i want to be able to bulk upload and management these in sets, so that i don't have to upload each one individually. 

Requires a spike to think through a bulk upload solution and/or a "set of downloads" content model solutino.  

## Acceptance Criteria
- [ ] TBD based on spike

## Implementation steps
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)

**Comment by erogray** [comment]
Relates to https://va-gov.atlassian.net/browse/VAHELP-58 and https://va-gov.atlassian.net/browse/VAHELP-70
