### ISSUE TITLE
Paragraphs implementation for CLP 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3469]
## User Story or Problem Statement

Possible future scenario: As a CLP editor, i want to be able to sort panels on a page. 

## Acceptance Criteria
- [ ] Certain panels are potentially reorder-able in 
- [ ] None are reorder-able for MVP (the system sorts them automatically)
- [ ] Editors cannot add more than one of each panel

![Create_Benefits_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/98982293-287c0e80-24ed-11eb-8ecf-2dabe45d4c6a.jpg)

## Implementation steps
- Needs writing
