### ISSUE TITLE
Make it possible for content publishers to archive 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3480]
## User Story or Problem Statement

It's difficult to archive (unpublish) published content. Currently, only content admins can do this, and must do it with bulk actions on Sections pages. 

## Background

It was previously possible to archive content while editing it. We removed content moderation from edit forms. You can't archive from the View page, or Latest version node

## Acceptance Criteria
- [x] CMS editors with publisher rights can easily unpublish content.

## Implementation steps
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to Enhancement)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS Objective (orange)
- [ ] CMS-supported product (black)

**Comment by oksana-c** [comment]
this is an issue of transition config. 

Archive transition should be modified like this 
<img width="1468" alt="Screen Shot 2020-11-13 at 2 26 39 PM" src="https://user-images.githubusercontent.com/16477724/99122977-862b5c00-25bc-11eb-8589-5ec2bc901689.png">

then users will be able to archive the node regardless of current state.
