### ISSUE TITLE
[EPIC] Tugboat Migration Runbook

### ISSUE THREAD

**Issue by daddison48** [department-of-veterans-affairs/va.gov-cms#3502]
## Roadmap

[Visual timeline to coordinate cross-functional effort](https://app.lucidchart.com/lucidchart/b5323cb6-a454-4a11-8acb-713a9dae8c8f/view)

### Sprint 23 

- [x] Announce the DevShop is EoL and in maintenance only mode in cms-team channel

### Sprint 24

- [x] #3973 + #3975 Create Demo project on Tugboat and create all required Demo environments
- [x] #3902 + #3986 Design/ Help text iteration on Release Content page [UX Writing / Engineering]
- [x] (?) Final technical checklist for tugboat readiness
- [x] Training Development
   - [x] #3988 Final list of User Stories to inform training narrative [@oksana-c]
   - [x] #3989 Walk-thru w/ Elijah/Neil/Oksana - should be recorded [@xiongjaneg @ElijahLynn @indytechcook @oksana-c @rachel-kauff(optional to get context for User Guides review)]
   - [x] #3901 Training Materials
      - [x] Training outline ready for review [@xiongjaneg]
         - [x] Peer review [@oksana-c @indytechcook ]
      - [x] Draft slidedeck [@xiongjaneg ]
         - [x] Review [@oksana-c ]
      - [x] Final draft of live presentation [@xiongjaneg ]
- [x] #3992 + #3993 user guides available
- [x] #3990 Official transition from DevShop to Tugboat - Announcement prep [@rachel-kauff / @xiongjaneg]

### Sprint 25

- [x] #3991 Live Training product  - end of first week of Feb [@ElijahLynn / @olivereri to support]
- [x] #3994 On-demand video recording available in CMS
- [x] Official transition announced (slack / email / record in CMS) - tentative February 5th [@rachel-kauff ]

### Sprint 25/26
- [x] #3987 Trained help desk on how to create Demo environment on Tugboat

### Sprint 27
#3503 DevShop stays on as a backup for another sprint, then taken offline
