### ISSUE TITLE
Checklist process for field removal

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3550]
## Background

The CMS team is often working on refactoring the content model where there's a need to remove obsolete fields.

The fields may be used in various places within the application and very often the action of removing fields from their primary place of origin (e.g. content types) is not followed by a removal from other secondary places of usage (e.g views, custom codebase, form display settings). This causes stray instances of removed fields in configuration files and sometimes codebase that are identified only after views or form display modes are intentionally saved, etc.

The CMS team needs to review the current process of field removal, improve and document it so as to provide engineers w/ a checklist that should be followed when obsolete fields are removed.

This Checklist should also include a process of collaboration w/ FE engineers that are responsible for maintaining FE templates for Product in which obsolete fields were used.

## Acceptance Criteria
- [x] A comprehensive Checklist that describes the process for obsolete fields removal is documented [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/remove-depracated-fields.md)
- [x] Checklist reviewed w/ 1-2 engineers on the CMS team, preferably someone who is also familiar w/ FE templating process
- [x] Checklist is socialized w/ the team

**Comment by ethanteague** [comment]
Here's the method that I have landed on:
1) PR to remove field from config - looking at the corresponding tables, the data associated with the field is removed from the db table (however, the empty table remains).
2) After 1 is released to prod, second pr to remove the empty tables from the db, ala:
```
/**
 * Remove nickname tables from db.
 */
function va_gov_backend_update_8010() {
  $tables = [
    'node__field_nickname_for_this_facility',
    'node_revision__field_nickname_for_this_facility',
  ];
  $schema = Database::getConnection()->schema();
  foreach ($tables as $table) {
    $schema->dropTable($table);
    Drupal::logger('va_gov_backend')->log(LogLevel::INFO, 'Deleted "%table" from db', [
      '%table' => $table,
    ]);
  }
}
```
cc: @oksana-c

**Comment by kevwalsh** [comment]
@oksana-c Product support team will try to get this done in Sprint 25, it's a good follow-up as you noted to the Content model change documentation.
