### ISSUE TITLE
Helpdesk requests retroactive import into JSD

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3559]
## User story 

As a Helpdesk manager, I need to have retroactive information available in JIRA Service Desk (JSD) so that I can run reports between January 2020 to present and analyze patterns where users are having issues.

## Acceptance criteria

- [x] Import of [Google Tracking sheet](https://docs.google.com/spreadsheets/d/1VHHnVF7Aj_OvOcJ74d79-cNZnjCRNr12V4-fFRwjjs4) history to JSD
- [ ] import of Slack channel requests into JSD starting on January 2020 until now
- [ ] incorporate any synthesis previously done of support requests by the UX team

## Description
In our initial estimation we determined it takes roughly an hour to analyze and input each ticket. There were approximately 50 tickets from mid October to mid November which extrapolates to 500 tickets, and 500 hours.

**Comment by oksana-c** [comment]
@VanessaLuxen , I'm closing this epic as I think you and Ero didnt plan on going beyond July 2020. Please reopen if you're planning to go further than July 2020. Thanks,

**Comment by VanessaLuxen** [comment]
Yes thank you.
