### ISSUE TITLE
[SUPEREPIC] V3-Phase2 of CI/PR/Automation Testing/Demo/Local Environments

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#3578]
Post-MVP of Tugboat, follow up epic of #2680 ([SUPEREPIC] V3-Phase1 of CI/PR/Automation Testing/Demo/Local Environments). 

This is catching the items that were not included in the MVP of Tugboat. 

## Acceptance criteria

- [x] Tugboat is ready for prime-time on Demo environments
- [x] Training and Change management for VFS Product team members
- [x] DevShop is discontinued

**Comment by acrollet** [comment]
@ElijahLynn can this epic be closed?
