### ISSUE TITLE
Notifications framework MVP roadmap

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3643]
## Description

The CMS notifications framework roadmapping w/ a focus group: @indytechcook @acrollet @ndouglas @oksana-c 

## Acceptance Criteria
- [x] focus group discussed the implementation in depth based on the Notifications Framework Architecture definition in #1905 
- [x] the CMS notifications framework MVP roadmap is defined
- [x] backlog for the next 2-3 sprints is refined

**Comment by oksana-c** [comment]
CMS Notifications Framework Roadmap - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-ops/editorial-workflow/notifications/roadmap.md 

Epic for Release 1.0 https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3736
