### ISSUE TITLE
Write migration for remaining VAMC systems and sections

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3685]
## User Story or Problem Statement

As a VAMC upgrade team, i can start building out VAMC system content

As a COVID content manager or migrator, i can create COVID-19 vaccination content that's dependent on it.

## Acceptance Criteria
- [x] CMS team is ready to migrate all VAMC systems into Drupal, when data is ready.
- [x] CMS team is ready to migrate a Section for each VAMC system, wh data is ready.

Stretch (mainly pending data)
- [x] All VAMC systems are in Drupal
- [x] Each VAMC system nodes has a Section, and that Section lives under the appropriate VISN (not required for COVID-19, but required for general scaffolding). 
- [x] Other VAMC system node fields are migrated
- [ ] ~All VAMC facilities are associated to a system~ (this can come later)

## Implementation steps
- [ ] Create new migration for VAMC System nodes
  - location: docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.health_care_region_page.yml
(shortcut, copy facility_health_care_service_2.yml)
   - id: health_care_region_page
  - label: 'Node - VAMC Health System.'
  - path: modules/custom/va_gov_migrate/data/health-care-region-page.csv
 - update revision_log default value to `Imported by health_care_region_page migration.`
- fields
   - Title
  - field_administration  (entity lookup sections taxonomy)  (either needs to be a stub migration or separate migration that this one depends on).
  - field_vamc_system_official_name
 - ? field_intro_text ?  
- field_vamc_system_official_name ?
- field_nickname_for_this_facility ?  
- field_meta_title (generate from concat of title and pattern) ?
- field_description?
 - field_meta_tags?

CSV Format

 id | system name | visn name | meta description 
--- | ------------------- | ------- | ----- 
     |   |   |

**Comment by swirtSJW** [comment]
Check on seemingly missing VISNS in section taxonomy
-  3 
- 11
- 13
- 14
- 18

These are missing  and can be created by hand if they are intentionally missing.

**Comment by swirtSJW** [comment]
@kaise-lafrai   The CSV for this migration is in this thread.
https://dsva.slack.com/archives/CPQFCQKEH/p1607718604135200

**Comment by kaise-lafrai** [comment]
@swirtSJW Thanks Steve. Yes I pulled it into a google sheet earlier and gave it a quick review. I am now into the process section of the script.
