### ISSUE TITLE
Automated test for enabling entity reference and linkit connections to new content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3735]
Related/spurred by #3731 
## User Story or Problem Statement

As a CMS user, i want all to be able to link to or reference all content with valid FE URLs from a variety of tools. 

As an engineer, i want a test to make sure i've enabled content content types in various configuration areas  including Linkit, and the Scope field of the Alert custom block type. 

## Acceptance Criteria
- [ ] New content types with planned support for FE URLs (eg a node that is visible on the FE at that node's alias), which have not been added to Linkit config fail an automated test. 
- [ ] Node types with do not have FE URLs, eg VAMC facility health services and VAMC system health services, are excluded. 

## Implementation steps
- [ ] consider adding a list of node types that do not have a valid FE URL, so that that these can be excluded from automated tests.
