### ISSUE TITLE
The CMS Notifications framework [Release 1.0]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3736]
## MVP 1.0 Scope

* CMS is generating notification records in log for workflow state transitions per user, but doesn't send the actual email
* CMS does not provide UI for users to opt-in into notifications

Logging emails in MVP 1.0 instead of sending will provide us with the following advantage and information:
* volume of emails to predict CMS usage under GovDelivery (or other) providers
* quantitative data:
   * to optimize email content and delivery options
   * to support user research before we offer opt-in/out UI to the CMS users

### User Story or Problem Statement

As a CMS Engineer, I need to have a stable notifications framework that reacts to basic editorial workflow events, so I can track the volume of outgoing notifications in log and have sufficient structure for building more sophisticated delivery options.

### Affected users and stakeholders

* CMS engineers
* CMS researchers and designers

### Hypothesis

We believe that launching the CMS notifications framework with initial set of trigger-events and logging notifications instead of sending them to real users, will provide the CMS team sufficient time to test out the framework without using GovDelivery resources or spamming the CMS users with email. This approach will also provide the research and design team with sufficient data to start optimizing the notifications delivery system.

### Assumptions

* We are supporting the most basic event triggers: transitions between editorial states, e.g. new draft, publish, archive.
* We are automatically subscribing users to nodes they ever created / edited + retroactive sub
* We are not sending emails, only recording triggered notifications in a dedicated log (DANSE entities)
* We are not building email templates
* We are not integrating w/ VA Notify yet

## Acceptance Criteria
- [ ] Notifications framework plugins for the editorial workflow events are functional
- [ ] Users are subscribed to all content that they have ever created/edited retroactively + ongoing (match revision users)
- [ ] Notifications log tracks all editorial workflow events and logs each individual notification

## Roadmap 
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-ops/editorial-workflow/notifications/roadmap.md

**Comment by indytechcook** [comment]
Until our code is updated to 7.2+, us this PR/branch as a base: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/3870

**Comment by indytechcook** [comment]
Tugboat demo branch: https://tugboat.vfs.va.gov/5fff0dafdb72fa7bf1d056cb
