### ISSUE TITLE
Onboard more users to facility status editing

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3804]
Once merged, will this work cause changes that CMS users will notice?
  - [ ] Y: Add the annoucements label to this issue for the PM and UX writer to review and include a design review in the ACs.
  - [ ] N: No futher action needed

### User Story or Problem Statement

*Veterans* need access to up to date Facility status  (via  Facility Locator [search](https://www.va.gov/find-locations/?zoomLevel=4&page=1&address=10001&facilityType=vet_center&serviceType&location=40.75%2C-73.99&context=New%20York%2C%20New%20York%2010001%2C%20United%20States) and [facility pages](https://www.va.gov/find-locations/facility/vc_0106V), for now). 

@davidconlon and @mmiddaugh spend too much time editing facility status for Vet Centers, using the process and content detailed in [this mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1595276505275/42814b6e8bf09ad6f70ab41626b03fcbaf6eafca ) 

This work can be done directly by the people who have the data.  

Facility editors should still be able to bulk edit, but the training should explain to ask for support from CMS team

### Affected users and stakeholders

* Facilities team
* Vet Center staff and vendors (and lower priority: VBA staff and vendors)

### ACs
- [x] Vet Center editors should be able to edit Vet Center status
- [ ] VBA Facility editors should be able to edit VBA Facility status. 

For now, the only VBA facility editor will be Sandy Tadeo, who already has Content publisher role. Other editors (for Vet Centers) may only have Content Editor at first.
