### ISSUE TITLE
Improve CMS user account unlock and password reset process

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#3851]
### User Story
As a CMS Team member providing help desk support, I want to be able to help users who have locked themselves out of their CMS accounts due to entering too many wrong passwords.

### Acceptance Criteria
- [ ] Process map or workflow showing steps from failed user login attempt to successful user login
- [ ] All users can reset their own passwords
- [ ] User admins can unblock IP addresses through UI
- [ ] User guide is written for user admins so they know how to unblock people
- [ ] User guide is written for "what to do if you are blocked"

### Current state
- Only a few CMS Team members know how to unblock a locked account and this doesn't include help desk members
- Default lockout time is long (6 to 10 hours?)
- CMS-generated email messages, including password reset, do not go to non-VA.gov addresses, which is a system standard

**Comment by stefaniefgray** [comment]
@cmaeng Is this ticket still necessary if users don't have passwords and they just have PIV cards?

**Comment by cmaeng** [comment]
@stefaniefgray it looks like the bulk of this work has been completed and updates just need to be made to existing guidance. still needed = yes because it would still apply for folks on our team.

**Comment by stefaniefgray** [comment]
Closing because editors log in through PIV card login, and our teammates can reach out via #cms-support if they have login trouble
