### ISSUE TITLE
Upgrade to Drush 10

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3868]
## User Story or Problem Statement

As a developer I would like to run a modern version of Drush so that our Drush matches our codebase's requirements.

or

Problem description. We are currently running Drush 8 because Devshop prevented us from upgrading.  When Devshop is no longer in our pipeline, we should upgrade to Drush 10.

## Acceptance Criteria

- [ ] Drush 10 exists in all environments
- [ ] Existing Drush commands used in yaml-tests execute as expected.
- [ ] common developer commands execute as expected.
   - [ ] drush cex
   - [ ] drush cim
   - [ ] drush cr
   - [ ] drush ms regional_health_care_service_covid
   - [ ] drush mim regional_health_care_service_covid

## Tasks
- [ ] Update BRD
- [ ] Update Tugboat
- [ ] Update Lando

**Comment by indytechcook** [comment]
I wanted to use a drush 10 command locally so I attempted to upgrade but this error occurred:

```

  Problem 1
    - Conclusion: remove drupal/migrate_tools 4.5.0
    - Conclusion: don't install drupal/migrate_tools 4.5.0
    - drush/drush 10.4.0 conflicts with drupal/migrate_tools[4.5.0].
    - drush/drush 10.4.0-rc1 conflicts with drupal/migrate_tools[4.5.0].
    - drush/drush 10.x-dev conflicts with drupal/migrate_tools[4.5.0].
    - Installation request for drupal/migrate_tools (locked at 4.5.0, required as ^4.0) -> satisfiable by drupal/migrate_tools[4.5.0].
    - Installation request for drush/drush ^10.4 -> satisfiable by drush/drush[10.4.0, 10.4.0-rc1, 10.x-dev].
   ```

**Comment by acrollet** [comment]
Ah, I added this issue as a blocker for #4281 but am now seeing that they're cross-dependent. I'll update that PR to upgrade to drush 10.

**Comment by ElijahLynn** [comment]
On BRD, we use the Drush launcher installed in `/usr/local/bin/drush` which is in the PATH, so I think it should still work with Drush 10. This means that we may not have to update BRD and this will mostly just be a Composer dependency update.

**Comment by acrollet** [comment]
Resolved in #4590
