### ISSUE TITLE
BigPipe Placeholders

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3871]
Once merged, will this work cause changes that CMS users will notice?
  - [ ] Y: Add the announcements label to this issue for the PM and UX writer to review and include a design review in the ACs.
  - [x] N: No further action needed

## Background

Industry research has indicated that informing users of the current working state will make the process more tolerable to the user by reducing uncertainty.

> Wait animations, such as percent-done bars and spinners, inform users of the current working state and make the process more tolerable to the user by reducing uncertainty. Users experience higher satisfaction with a site and are willing to wait longer when the site uses a dynamic progress indicator.
> https://www.nngroup.com/articles/progress-indicators/

https://www.drupal.org/docs/8/core/modules/big-pipe/overview

### User Story or Problem Statement

As a **CMS user**, I want to see main node content first while other page elements may still be loading, so that I can start working on content without delays.

As a **CMS user**, I want to see a clue that some elements on the page are still loading, so that I am not surprised when they finally loaded.

As a **CMS designer**, I want to ensure that all placeholders that are used for asynchronous loading of page elements in the CMS are visually consistent, closely represent the layout of the content that's been loaded and are compliant with the Section 508 standards.

As a **CMC engineer**, I want to have placeholder options available when I determine whether or not page elements should be loaded asynchronously, so that I can select a placeholder that is the most fitting to the application instead of having to create it from scratch.

### Affected users and stakeholders

* CMS editors
* Engineers on the CMS team

#### 1
We believe that developing a library of placeholders for asynchronous loading of page elements will improve UI consistency
and front-end/perceived performance of the application.

#### 2
We believe that the implementation of asynchronous loading for certain page components within the application will improve CMS user satisfaction with the application, because users will be able to see/access most important content on the page faster while other less important content is loaded shortly after.

#### 3
We believe that developing a library of placeholders for asynchronous loading of page elements will increase engineering efficiency while developing a multitude of various CMS components that should be loaded asynchronously.

### Assumptions

* When viewing node content, users want to see the content of node fields first and the content of informational sidebars or related menus last.
* When viewing content dashboards with a variety of blocks on the page, users would rather see some blocks loading faster while waiting for other blocks that are more information intensive to load later.

These assumptions _may_ be validated in a focused user research before we begin design / implementation phase.

## Acceptance Criteria
- [ ] Use cases for asynchronous loading of page components are reviewed and documented
- [ ] Accessibility requirements for asynchronously loaded components are well understood and incorporated in implementation phase
- [ ] Research phase for load placeholders
- [ ] Design phase for load placeholders
- [ ] Placeholder component is incorporated in the CMS Design System documentation along with usage guidance
- [ ] BigPipe Placeholders technical architecture
- [ ] BigPipe Placeholders implementation
- [ ] Open Source contribution to Drupal.org
