### ISSUE TITLE
Improve Deployment Alerts

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3885]
Once merged, will this work cause changes that CMS users will notice?
  - [ ] Y: Add the announcements label to this issue for the PM and UX writer to review and include a design review in the ACs.
  - [x] N: No further action needed

### User Story or Problem Statement

As a CMS User, I want the deployment alert to be accurate, so that I know when to stop/restart my work.

As a CMS Engineer, I want to have deployment alerts that work on all BRD environments.
 
### Affected users and stakeholders

* CMS users
* CMS Engineers

### Hypothesis

We believe that improving the accuracy of deployment alert, will improve the CMS user experience. 

### Assumptions
* User dont want to spend more time than necessary awaiting the deployment to finish
* Engineers want to have deployment alerts working on BRD environments

### Acceptance criteria

- [ ] deployment alert functionality and experience is improved

**Related epic** https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3119
