### ISSUE TITLE
Standardize display of non-editable content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3913]
### User Story or Problem Statement

There are a number of forms where non-editable content appears (or we want to display it), inline in the form, or on proofing pages. For example:

* VAST data on facility forms (migrated content that should not be edited)
* Migrated form data on VA forms (migrated content that should not be edited)
* Nationally controlled content on Top task pages like VAMC Policies (entity referenced content) (see https://balsamiq.cloud/s21kwcm/py46j7t/r1717)
* Default Appointments intro text on Facility health services (see https://balsamiq.cloud/s21kwcm/py46j7t/rCC1D)
* National Health service taxonomy content on VAMC System Health Service and VAMC Facility Health Service nodes (no design or implementation yet)

We need some consistent patterns for displaying this content inline. The Policies page design shows grey background and some nice tooltips to explain what this content is.

This will require a more full inventory than the list of examples above, and noting various attributes of each situation to represent the diversity of variants. 

### Affected users and stakeholders

* All CMS editors

### Hypothesis

We believe that standards for displaying non-editable content in a content form will help editors write better content for Veterans. We'll know that to be true from user feedback on a variety of forms

## Acceptance Criteria
- [ ] a pattern for non-editable content display is
   - [ ]  designed
   - [ ] implemented on content types that should use it
- [ ] new pattern is documented in the CMS design system

Once merged, will this work cause changes that CMS users will notice?
  - [x] Y: Add the annoucements label to this issue for the PM and UX writer to review and include a design review in the ACs.
  - [ ] N: No futher action needed

**Comment by kevwalsh** [comment]
This was accomplished via various patterns developed within the Centralized Content epic
