### ISSUE TITLE
Add "Type of care" field to health_care_service_taxonomy

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#3915]
## Background

The parent terms at admin/structure/taxonomy/manage/health_care_service_taxonomy/overview will be deprecated and become attributes of all the terms. 

In other words, this will become a flat taxonomy--for now--and the parents should be changed into attributes of their children. 

## ACs

- [x] New field: `field_service_type_of_care`
   Label: "Type of care" 
   Type: "List (text)"
   Possible values: "Primary care, Mental health care, Specialty care, Social programs and services, Other services"
   Cardinality: 1 (single value) 
- [x] Form display: 
   Widget: Select list. 
   Weight: Right below the Name field (above Health Service API ID)
- [x] Display
   Label: Above

====   

- [x] Update the VHA health service taxonomy view at admin/structure/views/view/vha_health_service_taxonomy
  - [x] Change the Format from `Tree (table)` to `Table of fields`. 
  - [x] Remove all the fields that use the Parent relationship, and then remove the Parent relationship.
  - [x] Add the new `field_service_type_of_care` field  so that it can be seen at vha-health-services
  - [x] Reset the Data export display (`data_export_1`) Fields data to use the same Fields as the Page view (`page_1`).

====
- [x] Once this gets field is released to prod, we should populate this field for child taxonomy terms at health_care_service_taxonomy. There are only ~90 terms, so this should probably be done manually, it would take about 30 minutes. 

- [x] Do not delete the parent terms yet, the FE depends on them. That will happen later. 

====         
- [x] Export the CSV, or send the export link to @davidconlon

**Comment by kaise-lafrai** [comment]
@kevwalsh Do we send the CSV after everything goes to prod and data has been populated?

**Comment by kevwalsh** [comment]
@kaise-lafrai i went ahead and updated the data on prod.

**Comment by kevwalsh** [comment]
@davidconlon All Parent terms now co-exist as "Type of care" attributes. See attached CSV (saved as .txt because github doesn't like csv's here apparently), and/or review at https://prod.cms.va.gov/vha-health-services 
[vha-health-services.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/5810989/vha-health-services.txt)

**Comment by kaise-lafrai** [comment]
Thank you Kevin!
