### ISSUE TITLE
"Learn more" help text pattern module

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#3932]
Once merged, will this work cause changes that CMS users will notice?
  - [ ] Y: Add the announcements label to this issue for the PM and UX writer to review and include a design review in the ACs.
  - [x] N: No further action needed

## Background

Inability to assign a custom position and/or format to help text per field is becoming an impediment to improving UX throughout CMS forms. "Learn more" pattern was reviewed as a POC #1777 and consensus is that we should make it available to our Content Strategists, so that they can improve CMS UX.

### User Story or Problem Statement

- As a CMS Editor, I need to be able to easily find contextualized help content, so that I can enter content without going to a separate page to learn now.
- As a CMS UX Writer, I need to be able to easily enter help content in the CMS, so that I can quickly iterate on the editorial experience.
- As a CMS UX Writer, I need to be able to easily enter help content in the CMS, so that I do not need to wait for a developer's help to add & update help content for CMS editors.
- As a CMS UX Writer, I can enter help content in a field or WYSIWYG, so that I do not need specialized HTML knowledge to create help content for CMS editors.
- As a CMS UX Writer, I need to be able to upload images within help content, so that I can provide relevant and useful guidance to CMS editors.

### Affected users and stakeholders

- CMS editors
- CMS UX writers

### Hypothesis

We believe that an open source Drupal module that provides field UI for adding "Learn more" help text will provide UX Writers with tools to improve UX for long forms.

Prototype: https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957?sender=3f0a3abd-9276-4f57-9dd1-a239b50d783f

### Assumptions
- the "Learn more" help text pattern may not be the only help text pattern that lives in this new contrib module. UX Writers also need an ability to control help text position, etc as discovered in Spike #3333

## Acceptance Criteria
- [ ] spike for various help text patterns that we may want to implement within this contrib
- [ ] help text pattern design is documented by UX Writer / Designer and understood by engineers
- [ ] help text patterns are prioritized
- [ ] implementation strategy developed
- [ ] Drupal module developed and contributed to Drupal.org
- [ ] new UX pattern is implemented based on current form design needs

**Comment by rachel-kauff** [comment]
FE patterns for this to inform final implementation: **https://design.va.gov/experimental-design/hint-text**

**Comment by EWashb** [comment]
Help text will be revisited in a new "extended help text" epic instead of this module-centric approach. We will also do discovery on the accessibility of the "learn more" pattern
