### ISSUE TITLE
Remove closed facilities periodically

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3981]
## User Story or Problem Statement

As a facility manager I would like the facilities that have been removed from VAST to be archived in the CMS.

As a veteran I prefer not to see facilities listed that no longer exist.

or

**Problem description:**  Our nightly migration from api.va.gov/services/va_facilities/v0/facilities/all  within the migration defined here /docroot/modules/custom/va_gov_migrate/config/install/migrate_plus.migration.va_node_health_care_local_facility.yml  there is no accounting for facilities that are permanently closed.   When a facility closes it disappears from the facilities/all query so it disappears from any handling that the migration is capable of.

## Proposal: 
A yml task is added to our daily tasks that would pull the facility nodes (vha, vba, nca and vet centers) and compares them to 
the results of api.va.gov/services/va_facilities/v0/facilities/all and archives any that do not appear (and perhaps un-archives them if they reappear.).  
A summary of the actions taken should be logged to watchdog.

## Acceptance Criteria
- [x ] 🙈 Can be implemented without consulting design team members
- [ ] When a facility is removed from the facility API, the facilitiy is archived in the CMS within 24 hrs.
- [ ] When a facility re-appears in the facility API, the facility is unarchived in the CMS within 24 hrs.  
    - [ ] If the facility was ever published, it should be re-published.
    - [ ] if the facility was never published it should be put in draft. 

## Implementation steps
* should be run through yml task on the 'daily' tasks and should run after the related daily migrations.

**Comment by davidmpickett** [comment]
@swirtSJW to review if still relevant

**Comment by jilladams** [comment]
Tossing this in an epic for later visibility.

**Comment by swirtSJW** [comment]
This is not still relevant.  This is essentially complete.  We apply flags to any facility that is no longer in the migration source Facility API.
