### ISSUE TITLE
Display last content release build time in CMS

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#3984]
## User Story or Problem Statement

As a content publisher, I want to see when the content was released last, so that I know if my content went out to production.

As an engineer, I want to see the time of the last content release, so that I have more context when troubleshooting content builds.

## Acceptance Criteria
- [x] Design mock is available for displaying the time of last content release [Design / UX Writing] 
- [x] We've identified which roles needs to see this information [Design]
- [x] Design is tested w/ users [lite testing]
- [ ] Content release time is implemented in a non-render blocking fashion [Engineering]
- [ ] Tooltip styling on "VAMC Policy Pages" is updated to match new design spec

## Implementation steps

- potential tooltip that provides sufficient context: content published within the last 15 mins will not be in this release, etc.
- we can deduct the timestamp by looking to the /BUILD.txt file  (ex: https://www.va.gov/BUILD.txt)

![image](https://user-images.githubusercontent.com/5752113/104350652-663bea00-54d2-11eb-8d91-f11ce539fe92.png)

**Comment by acrollet** [comment]
This will need some word-smithing as well, looking at the current text on https://prod.cms.va.gov/admin/content/deploy, we have:

> This is a decoupled Drupal website. Content will not be visible on the Front End until a "Content Release" is made to an environment.

I think this can be made substantially more clear and helpful. I'd suggest something like the following as a starting point:

> The Veterans Affairs website is generated intermittently from content entered on this website. Content that has been created or updated since Jan 12 at 08:54 EST will not be visible on [www.va.gov](www.va.gov) until the next content release has been completed.

cc @rachel-kauff @nataliedunbarCS

**Comment by acrollet** [comment]
Linking the [Figma spec](https://www.figma.com/file/JlemfRZ31tbawkSzCV0CoP/General?node-id=0%3A1)

Detail:
<img width="580" alt="Screen Shot 2021-02-03 at 3 40 01 PM" src="https://user-images.githubusercontent.com/101649/106818829-1619f880-6636-11eb-9b96-508a10ccdd42.png">

**Comment by acrollet** [comment]
I've researched the available solutions for tooltips and compared them with our internal requirements and the [USWDS Guidelines](https://designsystem.digital.gov/components/tooltip/). After doing so, I recommend that we move forward with [tippy.js](https://atomiks.github.io/tippyjs/), for the following reasons:

### Internal requirements
* well-supported (steady commits, 8k+ stars on github)
* also [used by webform](https://www.drupal.org/project/webform/issues/3170593)
* supports AJAX content
* supports popovers and tooltips
* themable
* accessible
* smart positioning

### USWDS requirements
* supports progressive enhancement
* supports keyboard accessibility

I recommend using tippy.js over the USWDS component for the following reasons:
* we don't plan on directly consuming USWDS, so we can push tech debt into the library vs maintaining a copy of the USWDS component
* allows complete flexibility over look/feel
* ease of universal implementation if we choose to do so

**Comment by jordanamello** [comment]
Lite testing phase has begun and will be over today. We have 4 users giving us feedback. 
Reference environment: https://pr4210-hq8l38fdcrdjdi54ztaenomozmumznbp.ci.cms.va.gov/

**Comment by oksana-c** [comment]
@acrollet , I reviewed the summary you posted and 💯 agree with your assessment.

tagging the team FYSA: @indytechcook @ndouglas @swirtSJW @kaise-lafrai @ethanteague @kevwalsh

**Comment by acrollet** [comment]
I've marked this issue as blocked by #3861 , as that will let us rely on the `webform/libraries.tippyjs` library. This way we don't duplicate dependencies, and the needed update to tippy 6.x will be automatically handled when we go to D9.

**Comment by jordanamello** [comment]
[Here's the doc](https://docs.google.com/document/d/1rkzKPsYgTypO1spfBO8tNkG6hYaNbQ9fwNza9aYSVyE/edit#) with lite test results and recommendations.

@acrollet @ndouglas @oksana-c @rachel-kauff and I discussed what we learned during testing phase and decided that:
- The tooltip phrase will be adjusted for the short term solution. @rachel-kauff 
- A spike will be created to tackle related issues: how to communicate the decoupled concept from content release, wait time to content going live; moderation state verbiage; and explore the use cases identified during testing. @jordanamello
