### ISSUE TITLE
Improve UX for "Link to file or video" paragraph

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4031]
## Problem statement

The scope of "Link to file or video" paragraph is too broad. User can add image, file or a link to video using this paragraph. This presents challenges when composing contextual guidance for the "link to file or video" paragraph form elements.

Content blocks (paragraph types) should present a menu of different formats to choose from, and there should be roughly a 1:1 relationship where there's a separate paragraph for each kind of content design that the Content editor might want to use. Download a file or image is quite different than link to a video, in terms of both the FE appearance, and the reason the user might want to use that content block, so we should explore splitting.

## Hypothesis

By splitting the "Link to file or video" paragraph into three distinct paragraphs and adding focused guidance for each media type, we will improve user experience and the quality of resulting content.

## Acceptance Criteria
- [ ] paragraph design is proposed and validated with users
- [ ] new paragraphs are implemented
      - [ ] content model changes are coordinated with FE team(s)
      - [ ] any new transformers are coordinated with FE team(s)
      - [ ] existing content using current paragraph is identified and refactored
- [ ] announcement of the updated UI is released
- [ ] updated UI is reflected in existing training materials
