### ISSUE TITLE
Tugboat deployment performance enhancement

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#4058]
## User Story or Problem Statement

The [file permissions update](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/80b14a1673d4917df59eda847017539f58e577a5/.tugboat/config.yml#L97) run on `sites/default/files` during the update phase is fairly lengthy and could probably be improved. More background and potential solutions are available in [this slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1611274228093100).

## Acceptance Criteria
- [ ] File permissions step takes as little time as possible
- [ ] Alternatives for improvement have been tested for functionality and speed
- [ ] Determine if the [file permission updates for /vendor/va-gov/web](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/80b14a1673d4917df59eda847017539f58e577a5/.tugboat/config.yml#L132) also should be updated(?) 

## Implementation steps
<optional>

**Comment by ElijahLynn** [comment]
explode([source_thread](https://dsva.slack.com/archives/CT4GZBM8F/p1611274228093100))

Adrian Rollett  1 hour ago
I noticed that the file permission update /bin/sh -c find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \; is fairly slow, perhaps close to a minute

Adrian Rollett  1 hour ago
could we get the same effect with setting a umask before the untar of the files and passing --no-same-permissions to tar?

Adrian Rollett  1 hour ago
Could shave some build time

Adrian Rollett  1 hour ago
I think we’d still have to run the directory permissions update, but that completes quickly

Elijah Lynn  32 minutes ago
thx, interesting idea.

Elijah Lynn  32 minutes ago
Have you tried that yet? (edited) 

Elijah Lynn  31 minutes ago
Depending on the part that takes longer, the ls from find, or the chmod . GNU Parallel could be used for a speedup too.

Adrian Rollett  31 minutes ago
I didn’t try it, we’d need to validate the idea. The one issue might be that umask is restrictive rather than prescriptive, so if that’s there to make sure that files are readable, (rather than to ensure they’re not executable) I don’t think it could do that (edited) 

Elijah Lynn  30 minutes ago
k, I think parallel would still be a big speedup if that didn't work.

Adrian Rollett  29 minutes ago
cool

Adrian Rollett  29 minutes ago
you want me to throw a placeholder issue up?

Adrian Rollett  26 minutes ago
actually a little more digging brought this up: https://stackoverflow.com/questions/1163294/changing-chmod-for-files-but-not-directories
Stack OverflowStack Overflow
changing chmod for files but not directories
I need to use chmod to change all files recursivly to 664. I would like to skip the folders. I was thinking of doing something like this ls -lR | grep ^-r | chmod 664 This doesn't work, I'm assum...

Adrian Rollett  26 minutes ago
looks like using xargs rather than -exec might speed things up a good bit

Adrian Rollett  26 minutes ago
so the chmod commands are batched rather than one per file

Elijah Lynn  26 minutes ago
yes please https://dsva.slack.com/archives/CT4GZBM8F/p1611275427100800?thread_ts=1611274228.093100&cid=CT4GZBM8F

Adrian Rollett
you want me to throw a placeholder issue up?
From a thread in #cms-team | Today at 4:30 PM | View reply

Elijah Lynn  21 minutes ago
oh interesting, the default batch size is based on the argument length limit of the shell!
xargs already batches up files so that they don't exceed the argument length limit

Adrian Rollett  19 minutes ago
nice :slightly_smiling_face:

Adrian Rollett  19 minutes ago
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4058

**Comment by indytechcook** [comment]
A few notes about the joy of file permissions.

The directory/file mask is also set by Drupal.  We had to override it on devshop: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/80b14a1673d4917df59eda847017539f58e577a5/docroot/sites/default/settings.devshop.php#L32. If Drupal does not have the to change the file permissions our logs will be filled up with the message complain it can not update files permissions.

Regarding the vets-website code.

* The root user does the initial composer install.  The vets-website is built using this same user in the build steps. 
* The background job uses www-data user to re-run the vets-website build.
* The permission of the `vendor` directory (where the `vets-website` and build code lives) is set as `drwxr-xr-x` by composer.  We will fight against this every time composer does anything.

**Comment by acrollet** [comment]
Some back of the napkin benchmarking:

```
root@php:/var/lib/tugboat# time find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

real    1m12.283s
user    0m46.851s
sys     0m24.135s
root@php:/var/lib/tugboat# time find "${DOCROOT}/sites/default/files" -type f -exec chmod 0664 {} \;

real    1m9.996s
user    0m45.860s
sys     0m24.264s
```

```
root@php:/var/lib/tugboat# time find "${DOCROOT}/sites/default/files" -type f -print0 | xargs -0 chmod 0664

real    0m0.367s
user    0m0.110s
sys     0m0.315s
root@php:/var/lib/tugboat# time find "${DOCROOT}/sites/default/files" -type f -print0 | xargs -0 chmod 0664

real    0m0.363s
user    0m0.091s
sys     0m0.331s
```

Confirming effectiveness:
```
root@php:/var/lib/tugboat# chmod a-rwx ${DOCROOT}/sites/default/files/secva2019vetsdaymessage.jpg 
root@php:/var/lib/tugboat# ls -la ${DOCROOT}/sites/default/files/secva2019vetsdaymessage.jpg 
---------- 1 48 www-data 43754 May  3  2020 /var/www/html/sites/default/files/secva2019vetsdaymessage.jpg
root@php:/var/lib/tugboat# time find "${DOCROOT}/sites/default/files" -type f -print0 | xargs -0 chmod 0664

real    0m0.350s
user    0m0.077s
sys     0m0.330s
root@php:/var/lib/tugboat# ls -la ${DOCROOT}/sites/default/files/secva2019vetsdaymessage.jpg 
-rw-rw-r-- 1 48 www-data 43754 May  3  2020 /var/www/html/sites/default/files/secva2019vetsdaymessage.jpg
```

The `xargs` approach feels like a pretty easy quick win :-)

**Comment by ElijahLynn** [comment]
Wow, I never would have thunk that it would be sub-second with just using xargs! Over 1 minute off the file-sync operation, fantastic work @acrollet!
