### ISSUE TITLE
Refactor GTM/GA build into a service.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#4100]
## User Story

As a developer, I should refactor the code that builds Google Tag Manager's `dataLayer` so that it can be extended and tested better and to improve the accuracy of our reporting.

## Grievances
While working on the tests for #4001, I encountered a caching issue.  Most of the dataLayer is constructed from the user object, and the cache contexts and tags tend to support accurate reporting gracefully.  However, user section associations are unrelated entities, their changes don't necessarily correlate with user updates, and so I think we need to bubble up the cache tags for the user section associations.

This is doable as-is, but the `_va_gov_backend_gtm_settings()` is expanding rapidly with recent changes.  It's about 60 lines in my current working branch, uses seven services explicitly and probably a good deal more implicitly, and is therefore quite difficult to test.  Adding some ad-hoc `#cache` stuff to the return value isn't ideal, to say the least.

## Implementation steps
I think, tentatively, that this might take the form of a plugin manager with each plugin providing both the value and the cache metadata associated with that value and a simple service that aggregates the values and cache metadata to bubble up to the cache metadata for the page attachments.  This would allow testing of the values and their cacheability individually and severally.

## Acceptance Criteria
- [ ] `_va_gov_backend_gtm_settings()` no longer exists
- [ ] Generation of current and future dataLayer values can be tested efficiently
- [ ] Appropriate cacheability metadata is bubbled up to pages for each value
