### ISSUE TITLE
Placeholder to address Tugboat functionality gaps

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4122]
## Description

To work on outcomes from #4121 

## Acceptance Criteria
- [x] any Tugboat functionality gaps or defects are resolved in prep for Demo env prime-time

## Summary of issues identified after beta testing

- [x] 502 Bad Gateway errors on FE build in demo envs - GraphQL fails #4179
- [x] Disable caching on content release logs view #4177
- [x] Intermittent connection issues to multiple services through SOCKS #4178
- [x] Increase suspension timeout for Tugboat/CI environments #4172
- [x] Update demo environment creation documentation to include creating and disseminating human-friendly URLs #4161

**Comment by oksana-c** [comment]
1. [Engineering] Create view to show content release build logs #4158 
2. [UX] Show the human-readable demo/PR tugboat environment name to the user #4159
3. [Engineering] Implement environment name display #4160
4. [HelpDesk / Training] Update demo environment creation documentation to include creating and disseminating human-friendly URLs #4161
5. [DevOps] Tugboat preview URLs can contain human-readable identifiers #4162
