### ISSUE TITLE
Sprint 25 Product support team priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4143]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

## Core team collaboration

- [ ] Transformer support #4142 @swirtSJW 

Core UX debt (from VAMC product)

- [ ] Remove entity embed #3292 (not critical, could be moved to Sprint 26) 
  - [ ] Audit and fix detail pages that have used Entity Embed within rich text fields #3293 
  - [ ] Remove Entity embed tool from Rich text editor #3294 

## Develop collaboration cycle with VFS Product teams #1643 
- [x] Content model documentation 
  - [x] Request and incorporate feedback on content model documentation #4131 @kevwalsh 👥
  - [x] Checklist process for field removal #3550 @ethanteague 
- [ ] Content strategy service blueprint #4132 @nataliedunbarCS 👥

### Demo environments
- [x] Develop demo environment training and documentation #3901 (in review, beta test with VAMC upgrade team)
- [x] Deliver training to Product teams #3991 @xiongjaneg
- [x] On demand recording #3994 @xiongjaneg

### VAMC System

**Launch support #4092 @swirtSJW  @kevwalsh**
- [ ] Launch Lebanon, 
- [x] Launch Wilkes-barre 

**VAMC System Policies Page #3046**
- [ ] Minor defects / enhancements
  - [x] Accessible tooltips fieldgroup #4049 @kaise-lafrai 
  - [x] Remove field labels #4077 @kaise-lafrai 
  - [x] Order of fields on VAMC System Policies Page #4139 @kaise-lafrai 
  - [x] Developer data should not show on proofing page #4138 @kaise-lafrai 
- [ ] Document Policies content model for FE devs, and Centralized content content model for CMS team #4145 @swirtSJW _(moved to sprint 26)_

**Centralized content national editing experience** _moved to sprint 26_
- [ ] Prevent deletion of centralized content #4056 *needs refining* 
- [ ] Modify cc_documentor paragraph to have special form view #4016 @swirtSJW *needs refining*

**Facility health services cutover #1729**
- [x] Remove the first remove button on Facility health services service locations #4104 @ethanteague 
- [x] Hide blobby content 

**COVID-19 vaccine data #3684**
- [x] [spike] more data to Lighthouse about facility health services? #4089 @swirtSJW 👥

**Governance & editorial experience**
- [ ] Enforce IA design for VAMC editors #2427 
  - [ ] Identify opportunities and build roadmap for improved IA governance in VAMC system #4144 @swirtSJW @kevwalsh @ethanteague 👥  🥅  
- [ ] Spike: Unique content validation approach #4074  (will span more than one sprint)
  
**Technical debt**
- [ ] Change prod to use prod endpoint for govdelivery #1498 @cmaeng 👥

### Vet Center #4080 
- [ ] Build CMS roadmap @kevwalsh   👥  🥅 

### VHA health service #1981
- [ ] Change "Type of care" label to "Type of care (VAMC)" and add a new matching select list "Type of care (Vet Center)" #4147  (sprint 26) 

### Campaign Landing Page MVP

- [x] Support FE devs with CLP  #3785 @kevwalsh (ongoing)

Requirements 
- [x] Form validation errors with closed fieldsets #4137 @kaise-lafrai  🥅  
- [x] Support "Publication date" for videos. #4156 🥅  

Enhancements
- [ ] Improve help text text for image alt text  #3444 @rachel-kauff (core team, but spurred by CLP)
- [ ] Spike of crop ratios for media browser form #3969 @ethanteague (may go to 26) 
- [ ] Evaluate possibility of improving hero image cropping help text, as an alternative to #3969 **needs issue**
 
### Resources and Support
- [ ] Defect: Related information field should be required on Q&A nodes #4090  

### VA Forms 
- [ ] Migration defect: Forms flagged as deleted not being archived by nightly forms migration #4083  @swirtSJW 

## Discussion Topics / Refining 👥

Core
- [ ] HTML5 form validation #4040 @kaise-lafrai 
- [ ] Disable HTML5 validation Proof of Concept #4051 @kaise-lafrai

VAMC system product design
- [ ] Enforce IA design for VAMC, epic #2427 
- [ ] Editorial experience for national editors, epic #4028

Training
- [ ] Develop VAMC Policies page training materials #3278 
- [ ] CLP training 
 
### Links to product team sync agendas
* [Public websites](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)
* [Facilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)
* [VAMC upgrade](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/vamc-upgrade-cms-weekly-sync.md)
