### ISSUE TITLE
Fix Tugboat backup job

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#4175]
## Tasks
- [x] Ansible: Remove stopping docker and tbctl tasks
- [x] Ansible: Remove AMI creation
- [x] Terraform: new S3 Bucket (`dsva-vetsgov-utility-tugboat`)
- [x] Ansible: Backup the nightly Mongo Tugboat to S3
- [x] Remove any other code
- [x] Docs: Add documentation for how the backups work and how to restore a backup 
  - In READMES/devops/tugboat-on-prem-install.md via https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5409
