### ISSUE TITLE
Tugboat Feature Enhancements

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4183]
### User Story or Problem Statement

As a CMS DevOps engineer, I want to continuously improve existing functionality of our CI tooling, so that it better serves the needs of the stakeholders that use it: VFS teams, CMS team.

### Hypothesis

We believe that improving Tugboat features will increase team efficiency and improve external stakeholders experience when they use Demo environments.

### Assumptions
* Tugboat support team is willing to discuss and implement new feature requests
* CMS team can customize certain CI features without dependencies on the Tugboat team

## Acceptance Criteria
- [ ] Human-friendly URLs are available for Tugboat environments
- [ ] Improved 403 page
- [ ] Improved content release log visibility
- [ ] Improved broken link report on demo envronments
