### ISSUE TITLE
Upgrade + Upscale RDS BRD Servers

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4226]
While testing https://github.com/department-of-veterans-affairs/vets-website/pull/15974 with Nick, I was monitoring Grafna for cms-test prod.  I noticed that the RDS instance had 70% - 80% CPU usage while the build job was running while the EC2 instance didn't go above 25%.  Currently, we are using a `db.m4.large` instance type.  This is the smallest instance type and we would do good to upgrade.   

## Questions

* Do we setup a read replica now?  We could greatly benefit from it as we scale.
* Transfer to Aurora?

This needs coordination since the DB does down during the upgrade.

## Tasks

- [x] Determine best instance type: https://aws.amazon.com/rds/instance-types/: 10.5.8
- [x] Upgrade MariaDB version
- [x] Verify new export from 10.5 works in Tugboat envs on Mysql 5-* etc, until #4240 is done and propgated
- [x] Upgrade DB instance is compatible with Drupal 9 https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of#comment-13741116 
- [x] Terraform updated
- [x] Deploy
- [x] Make sure cms-test works fine, sync DB to cms-test - https://github.com/department-of-veterans-affairs/devops/pull/8519
- [x] Remove old servers (TF) - https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/18
- [x] Remove old param groups (were not in TF)
- [x] Fix cms-test again (cleanup had to delete because of the way Terraform works, and I had to change a name on the last apply)

**Comment by ElijahLynn** [comment]
I think it makes sense to do the Aurora and scale up as two separate tasks so there is less risk and also a timeline point where we can see in Grafana to see if anything goes odd.

**Comment by indytechcook** [comment]
The run book for the upgrade is as follows.  

 _I am currently running this on `dev.cms.va.gov` and [monitored grafana for login failures](http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&var-datasource=Prometheus%20(Utility)&var-environment=dev&var-app_name=cms&var-region=us-gov-west-1&from=now-1h&to=now%2B3h)._

The process will be in two steps.  First we upgrade MariaDB.  Second, we upgrade the instance size.  

On a call with @micahchiang and @ElijahLynn we decided on an instanced size of `db.m5.2xlarge` and upgrade MariaDB to the newest version which is `10.5.x`. 

According to Drupal.org documentation version `10.3.7` is required for Drupal 9](https://www.drupal.org/docs/understanding-drupal/how-drupal-9-was-made-and-what-is-included/environment-requirements-of#comment-13741116).

For the new Parameter Groups the following properties are modified from the default:

| Name                            | Value          |
|---------------------------------|----------------|
| innodb_deadlock_detect          | 1              |
| log_bin_trust_function_creators | 1              |
| max_allowed_packet              | 268435456      |
| slave_max_allowed_packet        | 268435456      |
| tx_isolation                    | READ-COMMITTED |

1. MariaDB requires a minor version upgrade:
* Create new Paramager Group for MariaDB 10.3 name `cms-test-mariadb10-3`
* Upgrade MariaDB from version from `10.2.12` to `10.3.x`
* Create new Paramager Group for MariaDB 10.4 name `cms-test-mariadb10-4`
* Upgrade MariaDB from version from `10.2.12` to `10.4.x`
* Create new Paramager Group for MariaDB 10.5 name `cms-test-mariadb10-5`
* Upgrade MariaDB from version from `10.2.12` to `10.5.x`

1. Upgrade the db instance size to `db.m5.2xlarge`

**Comment by ElijahLynn** [comment]
For the rollout of this, I wonder if we should spin up a new instance and do a mysql import on it so it is a faster upgrade.

**Comment by ElijahLynn** [comment]
WIP Runbook (will copy here when ready) > https://docs.google.com/document/d/1LN9iHWIS5QrOK3S-e16sU7TGLgVlwSFv6sL839aegJw/edit#

**Comment by ElijahLynn** [comment]
This is done!

![image](https://user-images.githubusercontent.com/1504756/107837157-87ebf380-6d54-11eb-810d-93fd68033037.png)

**Comment by ElijahLynn** [comment]
Runbook used to deploy:

DEV/STAGING/PROD RUNBOOK:

- [ ] Login `ssm-session vagov-dev|staging|prod cms` # Do this twice, 2nd is root for opcache reload 

- [ ] `sudo su -`
- [ ] `sudo -u apache -s` 

- [ ] `cd /var/www/cms; source /etc/sysconfig/httpd; PATH=$PATH:/usr/local/bin`

- [ ] Login and open [https://prod.cms.va.gov/node/6900](https://prod.cms.va.gov/node/6900) # to verify site alert functionality 

- [ ] Alert users of upcoming downtime:  
    `drush site_alert:create 'deploy-alert' 'Around 6pm ET today we will be running a system update. &lt;br>The CMS will be temporarily unavailable for up to 15 minutes. You should plan to save ahead of time, or take a break during the update to avoid losing work.' --severity=medium` 

- [ ] Wait <N> minutes 

- [ ] `drush site_alert:create 'deploy-alert' '&lt;strong>System update in progress&lt;/strong>&lt;br>&lt;br>Sit tight! Stay on this page to avoid losing unsaved changes. &lt;br>This update will be up to 15 minutes.  We will let you know when it is ok to resume working again.' --severity=high`

- [ ] ENABLE deploy mode  
    `drush va-gov-enable-deploy-mode  
    cp docroot/sites/default/settings/settings.deploy.inactive.php docroot/sites/default/settings/settings.deploy.active.php`
  
- [ ] DUMP current DB: (30 seconds)  
    `mysqldump --default-character-set=utf8mb4 --single-transaction -h dsva-cms-prod.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com -u drupal -p dsva_cms_prod > cms-prod.sql`
  
- [ ] IMPORT to new HOST: (3m23s)  
    `mysql -h dsva-cms-prod-db.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com -u drupal -p --database=dsva_cms_prod &lt; cms-prod.sql`
  
- [ ] Manually set instance to use new DB host  
  - [ ] `vim /var/www/cms/docroot/sites/default/settings.php +22` # Next deploy will have this in it
  - [ ] `'dsva-cms-prod-db.cdqbofmbcmtd.us-gov-west-1.rds.amazonaws.com'`
  - [ ] sudo service httpd reload # In 2nd session, to reload opache to pickup PHP change
  
- [ ] VERIFY new host connection with  
  - [ ] `drush status`
  - [ ] This doesn’t mean the site is using new opcache for certain
  
- [ ] Rebuild cache for good measure 
    `drush cache:rebuild`
  
- [ ] Delete site alert 
    `drush site_alert:delete 'deploy-alert'`
  
- [ ] DISABLE Deploy mode 
    `drush va-gov-disable-deploy-mode`
    `rm docroot/sites/default/settings/settings.deploy.active.php` 

- [ ] VERIFY Unicode characters survived the export/import 
    [https://prod.cms.va.gov/node/6900](https://prod.cms.va.gov/node/6900)  
    A long load after site alert drops will verify new DB as cache is being primed. 

- [ ] Check dblog 
    [https://prod.cms.va.gov/admin/reports/dblog](https://prod.cms.va.gov/admin/reports/dblog)  

- [ ] Check status report 
    [https://prod.cms.va.gov/admin/reports/status](https://prod.cms.va.gov/admin/reports/status) 

- [ ] Merge devops PR with new hostname changes 

- [ ] Run a deploy on DEV to ensure the new settings are good.
  
- [ ] Perf Test
  - [ ] time composer yaml-tests
  - [ ] CMS Export / Post Live job
  - [ ] database backup, run manually, timing, and charts
    - [ ] 60 > 50s
  - [ ] post screenshots to issue
  - [ ] sanitize job 

- [ ] Monitor performance 

- [ ] Update Grafana dashboard to use new host

**Comment by ElijahLynn** [comment]
Other PRs for this:

* https://github.com/department-of-veterans-affairs/devops/pull/8513
* https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/15
* https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/16
* https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/17

**Comment by ElijahLynn** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4240 (Tugboat upgrade)
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4345 (Lando upgrade)

**Comment by ElijahLynn** [comment]
Alrighty! All the old DB instances deleted as well as param groups, and the Param Groups are all managed in Terraform now too!

![image](https://user-images.githubusercontent.com/1504756/108449182-e6fbad80-7217-11eb-8522-e6b3db603039.png)
![image](https://user-images.githubusercontent.com/1504756/108449187-e82cda80-7217-11eb-80bb-bcc1f4b8a572.png)

**Comment by ElijahLynn** [comment]
K, I finally have automated the database user creation! This will be helpful for our disaster recovery docs and also future upscales or instance replacements. 

I also just got all our CMS-TEST infra working again. 

Once https://github.com/department-of-veterans-affairs/devops/pull/8571 is merged tomorrow (I already effectively deployed, tested and ran the job) we can call this story closed.

**Comment by ElijahLynn** [comment]
> Once [department-of-veterans-affairs/devops#8571](https://github.com/department-of-veterans-affairs/devops/pull/8571) is merged tomorrow (I already effectively deployed, tested and ran the job) we can call this story closed.

This is merged. 

I think the last outstanding merge is for Lando, which we are doing on Friday after Demo.

**Comment by ndouglas** [comment]
Was this PR merged or does it need to be reopened?

**Comment by ElijahLynn** [comment]
> Was this PR merged or does it need to be reopened?

It was just merged > https://github.com/department-of-veterans-affairs/va.gov-cms/pull/4304
