### ISSUE TITLE
VA.gov Virtual Agent (Chatbot) product onboarding to CMS

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4242]
## Background

The VA.gov Virtual Agent (chatbot) team is looking to use Drupal CMS as the single source of truth, and intend to consume the content directly. 
The team is interested is any API services available today that they can leverage.

Informal conversations took place and several team members received access to the CMS via role "Content API Consumer".

The team is seeking formal onboarding to thee CMS and an overview of Content API capabilities.

Initial intent - query FAQ nodes every ~24 hrs.

Related Slack Threads:
1. https://dsva.slack.com/archives/CBU0KDSB1/p1612218123120800
2. https://dsva.slack.com/archives/CDHBKAL9W/p1612475699083400

### User Story or Problem Statement

As a VA.gov Virtual Agent (chatbot) team member, I need to have access to Drupal Content API, so that I can run FAQ / Q&A queries to train the chatbot.

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria (TBD)
- [ ] Va.gov Virtual Agent (Chatbot) Team  users have production CMS accounts - tracked in https://va-gov.atlassian.net/browse/VAHELP-404 
- [ ] the CMS team has information on the use case / expectations and end goals and has enough technical details to support the Chatbot team
- [ ] the Chatbot team can use GraphQL endpoint & query / explore in production and/or Demo environment
- [ ] TBD
