### ISSUE TITLE
Critical Alerts and Monitoring for CMS Application, Infrastructure, User and Content 

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4268]
### User Story or Problem Statement

As a CMS Engineer, I need access to granular reporting on various system performance indicators, so that I have enough data to make informed decisions for maintenance / scaling / enhancements to the CMS application and infrastructure.

### Hypothesis

We believe that having granular monitoring and easily accessible reporting for all system services, including data about active users and published content, will enable the CMS team to identify/predict and fix any performance / scaling issues sooner and more effectively.

## Acceptance Criteria
- [x] we've identified application and infrastructure monitoring gaps
- [x] we've added appropriate tools to cover identified gaps in monitoring / reporting
- [x] we've setup alerts for high-priority metrics

**Comment by mchelen-gov** [comment]
per convo the other day, we can scope this to "critical" alerting and split out non-critical system monitoring and alerts

**Comment by acrollet** [comment]
> per convo the other day, we can scope this to "critical" alerting and split out non-critical system monitoring and alerts

Created #5404 for non-critical system monitoring/alerts.

**Comment by acrollet** [comment]
> per convo the other day, we can scope this to "critical" alerting and split out non-critical system monitoring and alerts

✅
