### ISSUE TITLE
Site alert for training environments

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4271]
## User Story or Problem Statement

This is a followup to #4249 

As a trainee, i want to know about how long i may be able to access any content i've created in a training environment, so that i can plan my training activities accordingly.

As a training environment manager, i can activate a training site alert after i refresh the environment. 

## Acceptance Criteria
- Alter sanitization script to do:
  - [x] Remove "site_alerts" from [tables to truncate](https://github.com/department-of-veterans-affairs/devops/blob/186f8b8c4b307ef36efa6d431b59b6e1cc867bff/ansible/cms/roles/cms-db-sanitize/tasks/sanitize-db.sh.j2#L78)
  - [x] Add command to  remove all site alert with a label of 'deploy-alert' from the table 'site_alerts'.   All other labeled alerts should survive the sanitization.
- [x] New site alert has been added to prod
  - [x] Alert label: "Training environment refresh"
  - [x] Severity: Medium
  - [x] Active: FALSE
  - [x] Message: `This Drupal CMS training environment is temporary. It will be refreshed every Monday at 9:00 a.m. ET. Any content changes will be lost.`
  - [x] Scheduling: None
  - [x] @xiongjaneg has QAd this on a PR environment (by activating the alert).

## Implementation steps

Add this to config: 

![Edit_training_refresh_alert___VA_gov_CMS](https://user-images.githubusercontent.com/643678/107646251-c2b43580-6c47-11eb-95a6-16c53c448dd4.png)

**Comment by swirtSJW** [comment]
This could be added as a drush command. that gets run after install.  But probably a better approach is have the sanitiation job only remove site alerts that have the label "site_deploy"

**Comment by indytechcook** [comment]
The sanitation job wouldn't matter since this isn't data that originates in production.  I agree drush job is the best path.  There isn't a way to automate this yet as the `clone` step doesn't have access to drupal and the `build` step is only run after refresh.  Let's try to talk through a solution if we want to automate it.

**Comment by xiongjaneg** [comment]
My two cents (maybe 1 and a half with my lack to technical knowledge), probably not worth spending a lot of time on since it's really only for training unless there's another use case. Also, I have to go in and activate it after every refresh anyway, I might as well just copy and paste a new one.

**Comment by indytechcook** [comment]
Steve's sanitation solution will work the best if this is content that's already in prod and just needs to be manually activated on training.  We can easily have this run on every refresh.  If it's for training and not demo then that makes sense to me.

**Comment by swirtSJW** [comment]
I can see a case where we will want some saved inactive alerts to persist.  The only reason the sanitization job was removing them was to get rid of the the misleading active site_deploy alerts.   So I think it makes sense just to remove those in the sanitization rather than removing all site alerts as happens currently.

**Comment by ElijahLynn** [comment]
fwiw, currently we drop the entire site_alerts table in the sanitize job here > https://github.com/department-of-veterans-affairs/devops/blob/186f8b8c4b307ef36efa6d431b59b6e1cc867bff/ansible/cms/roles/cms-db-sanitize/tasks/sanitize-db.sh.j2#L72-L80.

**Comment by cmaeng** [comment]
Looks to be DevOps dependent. @ElijahLynn could you chime in when you get a chance?

**Comment by cmaeng** [comment]
No immediate urgency from a training standpoint. cc: @xiongjaneg

**Comment by swirtSJW** [comment]
Relavant discussion here https://dsva.slack.com/archives/CT4GZBM8F/p1614197797249800

**Comment by swirtSJW** [comment]
The remainder of this ticket falls to a devops task.  Not urgent, to be prioritized accordingly  @ElijahLynn @oksana-c

**Comment by ElijahLynn** [comment]
> The remainder of this ticket falls to a devops task. Not urgent, to be prioritized accordingly @ElijahLynn @oksana-c

Got it, so:
```
- [ ] Remove "site_alerts" from tables to truncate
- [ ] Add command to remove all site alert with a label of 'deploy-alert' from the table 'site_alerts'. All other labeled alerts should survive the sanitization.
 ```

**Comment by ElijahLynn** [comment]
This is done :heavy_check_mark:. 

PR is https://github.com/department-of-veterans-affairs/devops/pull/8610 and I just tested on the cms sanitize job (cms-test is already too far sanitized), then refreshed a Tugboat [environment](https://tugboat.vfs.va.gov/603ee57ce6599bf6b48f2485), visited https://master-zwklduwzwsyq0kht24ijzxlgzhw8z2nv.ci.cms.va.gov/admin/config/system/site-alerts, works,  merged. 
![image](https://user-images.githubusercontent.com/1504756/109741910-ed2c4b00-7b82-11eb-9635-197d2c9cae6d.png)

**Comment by xiongjaneg** [comment]
@ElijahLynn Looks good. Thanks!
