### ISSUE TITLE
Sprint 26 priorities - Product Support team

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4310]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

#### #4332 Discovery 🥅 

- [x] #4332 Discovery 
   - [x] User journey 
   - [x] Top tasks
   - [x] Change management
   - [x] User research
   - [ ] 

#### #4318 Content model to 80%+  🥅  

*Locations*
  - [x] #4323 Create "Vet Center Locations List" content type
  - [x] #4327 Should Outstations and Mobile Vet Centers be their own content types? 
  - [x] #4335 “Vet Center Community Access Point” content type

*Main location* 
  - [x] #4332 Add known fields to Vet Center content type
  - [x] #4340 issue: "Update URL alias for vet centers to use Vet Center name, nothing else. Eg “nashville-vet-center”, “rochester-vet-center”.
  - [x] #4330 Distinguish 3 "Springfield Vet Center"

*Services*
  - [x] #4355 Vet Center Facility Health Service content type 
  - [x] #4147 VHA health service taxonomy

*Moved to icebox*
  - [ ] #4320 Hours field for Vet Center
 
Added mid-sprint 

### VAMC System

**Facility status migrations**

- [x] #4305 Endpoint problems (Certs, non-existent Facility Ids, and merged VAMC systems).

**#4309 VAMC Upgrade Dual State Launch support  @swirtSJW  @kevwalsh**
- [x] Launch Lebanon Feb 17 
- [x] Launch Butler Feb 18
- [x] Launch VISN 4 VAMC Week of Feb 22 
- [x] Launch VISN 4 VAMC Week of Feb 22 
- [ ] Launch VISN 4 VAMC Week of Feb 22 (delayed by VAMC upgrade to sprint 27)

**VAMC System Policies Page #3046**
- [ ] #4145  Document Policies content model for FE devs, and Centralized content content model for CMS team @swirtSJW 🥅  

#### Governance & editorial experience** (all stretch goals)

**Epic Centralized content national editing experience**  
- [ ] #4195 Support tokens in EFF for inserting local values into nationally managed content 
- [ ] #4056 Prevent deletion of centralized content  *needs refining* 
- [ ] #4016 Modify cc_documentor paragraph to have special form view  @swirtSJW *needs refining*

**Epic: Enforce IA design for VAMC editors**
- [ ] #4311 SPIKE: technical implementation of VAMC system menu IA governance @ethanteague 

**Epic: Unique content validation**
- [ ] #4074 Spike: Unique content validation approach   (will span more than one sprint) @kaise-lafrai 
  

### Campaign Landing Page MVP

- [ ] #4317 Attend CLP beta user onboarding @nataliedunbarCS @xiongjaneg  (moved to sprint 27)
- [x] Figure out next steps for issues arising through alpha testing 

### Resources and Support

n/a

### VA Forms 

- [x] #4083 Migration defect: Forms flagged as deleted not being archived by nightly forms migration @swirtSJW 

## Core team collaboration

Drupal 9 update
- [ ] #4283 Update Migration Tools module @swirtSJW 

Core UX debt (from VAMC product)
- [ ] #3292  Remove entity embed (not critical, could be moved to Sprint 27) 
  - [ ] #3293  Audit and fix detail pages that have used Entity Embed within rich text fields @kevwalsh 
  - [ ] #3294  Remove Entity embed tool from Rich text editor 

## Candidates for Discussion Topics / Refining 👥

Core
- [ ] #4040 HTML5 form validation  @kaise-lafrai 
- [ ] #4051 Disable HTML5 validation Proof of Concept  @kaise-lafrai

VAMC system product design
- [ ] #2427  Enforce IA design for VAMC, epic 
- [ ] #4028 Editorial experience for national editors, epic 

Training
- [ ] #3278  Develop VAMC Policies page training materials 
- [ ] CLP training 
 
### Links to product team sync agendas
* [Public websites](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)
* [Facilities](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)
* [VAMC upgrade](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/vamc-upgrade-cms-weekly-sync.md)
