### ISSUE TITLE
Clarify SLA requirements on federal holidays

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#4334]
### User Story or Problem Statement
The CMS needs clarity on SLA requirements and expectations around support of our system during federal holidays. There is often work and activity (deployments, content releases) occurring that we are not sure if we ought to be supporting or not.

## Tasks
- [x] @cmaeng to clarify with @JeffBarnesUSDS and @Jeff-Hayter 
- [x] Helpdesk team to draft language on expectations for slack and email communication
- [x] Helpdesk team to communicate internally to our team

## Acceptance Criteria
- [x] The CMS team has a clear understanding of our SLA commitments and support expectations on Federal holidays
- [x] These expectations have been clarified with and agreed upon by our OCTO-DE POs
- [x] These expectations are documented in GitHub and pinned in our #cms-support channel

List of federal holidays here: 
![image.png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/57d1a87f-eb13-4d5a-a9a0-5e73fdc51afc)

**Comment by cmaeng** [comment]
![image.png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/0b44cac7-2f6c-44ee-83f3-031869c2bae9)

**Comment by mchelen-gov** [comment]
for context: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/working-with-vsp/policies-work-norms/deployment-policy.md#exceptions-to-automated-deploys

helpdesk SLA decision should be documented here: https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/service_level_agreement.md

**Comment by erogray** [comment]
See updated version of https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/service_level_agreement.md

and pinned note in https://dsva.slack.com/archives/CDHBKAL9W/p1617965866155000

this looks like it's now complete?
