### ISSUE TITLE
Update URL alias for vet centers to use Vet Center name, nothing else. Eg “nashville-vet-center”, “rochester-vet-center”

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4340]
## User Story or Problem Statement

Per [slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1613489907063200) 

## Acceptance Criteria
- [ ]  Vet Center URL aliases should be simply `[node:title]` 
- [ ] Orlando Vet Center (node 3690) should have the alias `orlando-vet-center`

## Implementation steps
- [ ] Update pathauto settings for Vet Center
