### ISSUE TITLE
Vet Center Migrations

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4370]
The Vet Center content model has evolved, and some changes are required to migrate Vet Center content from VAST to CMS

### Sprint 27
- [x]  National Vet Center staff continue to update MVCs and OS in the main "Vet Center" content type 
- [x]  CMS team updates VAST migration to start distinguishing MVCs, OS, and Vet Centers #4325 
- [x]  ~CMS team writes to sync `field_operating_status_facility` and `field_operating_status_more_info` from Vet Center nodes to MVC and OS, using `field_facility_locator_api_id` as key, (Save hook)~ Decision is taken to handle this via business process... (#4479) 

### Sprint 28 

[needs adding: CAP identifier?]

- [x]  National Vet Center staff continue to update MVCs and OS in the main "Vet Center" content type 
- [x]  CMS team updates VAST migration to start distinguishing MVCs, OS, and Vet Centers #4325 
- [x] CMS team updates Facility Status dashboard updated to include new Vet Center content types (OS, MVC, CAP) #4820
- [ ] Cutover to new content types on 3/26/21 
  - National Vet Center and Local Vet Center staff start updating Facility Status for OS, (& CAP if desired)
  - [x] CMS team stops migrating OS, MVC into `vet_center` content type
- [x] CMS team deletes `vet_center` nodes that end in `MVC` and `OS`

### Sprint 29
- [ ] CMS->Lighthouse CAP discovery #4410 

### Sprint 30
- [ ] CMS team updates Lighthouse push migration #4411 to include CAP
