### ISSUE TITLE
Define technical ownership boundaries: build pipelines

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#4381]
AC:
- [ ] Define and document ownership of build pipeline results
- [ ] Update alerts to match build pipeline result ownership
- [ ] Define and document ownership of build pipeline steps

**Comment by jkalexander7** [comment]
Boundaries outlined in Team Roles doc: https://vfs.atlassian.net/wiki/spaces/LEAD/pages/2071330836/Team+roles+for+Content+Build+performance
