### ISSUE TITLE
Change management for Vet Center MVP editors - local

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4400]
## User story

As a Vet Center editor, i want my onboarding and adoption of the CMS to be streamlined, including training, user accounts and permissions, user guides, help desk support.  

## Sprint 30: 

- [x] #4404 User guides
- [x] #4401 Draft training materials
- [x] #3801 User onboarding policy

Training materials can be created using static screenshots of UXPin, but training will not be delivered until the coded front end is done (As of March 26, this is anticipated by April 21). 

## Sprint 31
- [ ] #4402 Deliver training

## Sprint 31 or 32

- [ ] #4837 Create self-service videos

This will unblock content gathering for the next ~50 Vet Centers (Q2 goal)

### Affected users and stakeholders

* CMS Vet Center editors

<link to any existing research or data supporting this>
