### ISSUE TITLE
Product Support Team Sprint 27 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4424]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

#### #4374 Local editor experience

**Design**
- [x] #4386 Dashboard design
- [x] #4423 Form design
- [x] #4421 Usability testing - Local experience
- [ ] #4482 UX labels and form design for other Vet Center forms. 

**Engineering**
- [ ] #4481  Spike: Dashboard architecture   👥 
- [ ] #4477 Spike: modals for entity reference forms (forms within a form). [wait until usability testing is complete]

Stretch: 
- [ ] #4422 Implement form design 👥  
  - [ ] Implement TOCs and Fieldgroups for Vet Center form (needs refining)
  - [ ] Implement dialog approach from #4477 if possible. 

#### #4370 Migration

- [ ] #4369 Spike: How to handle changes to facility names in VAST? @swirtSJW (could be moved to Sprint 27) 
- [ ] #4445 Plan cutover for MVC and OS Vet Center Facility Status @kevwalsh 
- [ ] #4325 Update VAST migration for Vet Center nodes  @kaise-lafrai  🥅  
- [ ] #4410 Lighthouse discovery: Vet Center CAP data @swirtSJW 
- [x] #4479 Sync Vet Center operating status fields to MVC and OS content types @kaise-lafrai 

#### #4318 Content model   ("100% complete") 🥅

Our goal is to facility the entry of content by Facilities team by the end of Sprint 27, for one node (Escanaba MI, node 3756).

- [x] #4385 Featured content blocks (pending design spec)
- [x] #4420 Vet Center FAQ 
- [x] #4419 Nearby Vet Center field(s) 
- [x] #4428 Locations page intro text
- [x] #4442 Vet Center Prepare for your visit
- [x] #4446 Refactor field_address on Vet Center CAP to include "Located at" 
- [x] #4510 Updates to Vet Center MVC content model and governance (needs some refining)
- [x] Another 8 unplanned issues arose during the sprint

#### #4414 Governance and permissions

- [x] #4418 "Content creator - Vet Center" role 

#### #4373 National editor experience

- [ ] #4415 Add Vet Center specific fields to /vha-health-services view (can go to 28)

#### #4400 Change management

- [ ] Refine the plan for MVP and beyond

#### #4407 FE support

- [ ] #4408 Document Vet Center content model for Facilities team

### VAMC System

**#4309 VAMC Upgrade Dual State Launch support  @swirtSJW  @kevwalsh**
- [x] #4475 Launch 5-8 VAMCs in VISN 4 and 19

**VAMC System Policies Page #3046**
- [x] #4145  Document Policies content model for FE devs, and Centralized content content model for CMS team @swirtSJW 

**COVID Vaccine data to Lighthouse**
- [ ] #4484  Modify data sending of COVID 19 vaccine service date to lighthouse

#### Governance & editorial experience (all stretch goals)

**Epic Centralized content national editing experience**  
- [ ] #4195 Support tokens in EFF for inserting local values into nationally managed content 
- [ ] #4056 Prevent deletion of centralized content  *needs refining* 
- [ ] #4016 Modify cc_documentor paragraph to have special form view  @swirtSJW *needs refining*

**Epic: Enforce IA design for VAMC editors**
- [ ] #4311 SPIKE: technical implementation of VAMC system menu IA governance @ethanteague 

**Epic: Unique content validation**
- [ ] #4074 Spike: Unique content validation approach   (will span more than one sprint) @kaise-lafrai 
  

### Campaign Landing Page MVP

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

**#2275 Change management for beta users**  👥

- [ ] #4472 Facilitate CLP beta test with VBA @nataliedunbarCS @xiongjaneg 👥
- [ ] #4317 Attend CLP beta user onboarding @nataliedunbarCS @xiongjaneg  
- [ ] #2270 Draft training materials (dependent on John's input) 🥅 

**#2274 CLP Editorial experience**

Minor editorial experience and content rigidity issues.

- [ ] #4389 Require CLP hero image
- [ ] #4390 Remove editorial workflow widget (defect)
- [ ] #4392 Require or guide consistent use of of images in Story Panel
- [ ] #4393 Title character limit for Downloadable resource
- [ ] #4368 Document - External is missing workbench access setting (defect)

### Resources and Support

N/A

### VA Forms 

N/A

## Core team collaboration

**Drupal 9 update**
- [ ] #4283 Update Migration Tools module @swirtSJW 

**Core UX debt (from VAMC product)**
- [ ] #3292  Remove entity embed (not critical, could be moved to Sprint 27) 
  - [ ] #3293  Audit and fix detail pages that have used Entity Embed within rich text fields @kevwalsh 
  - [ ] #3294  Remove Entity embed tool from Rich text editor
