### ISSUE TITLE
Tugboat Deploy/Pre-deploy message [Design]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4431]
## User Story

As a Tugboat or Demo Environment user, I want to see a warning before Tugboat goes offline for maintenance and I want to understand how my work will be affected and the time I should wait for my pages / environments to come back online.

## Current message displayed to users

<img width="574" alt="Screen Shot 2021-02-24 at 10 30 57 AM" src="https://user-images.githubusercontent.com/16477724/109042788-d1f6a280-768d-11eb-9316-649e0eb60dc7.png">

## Acceptance Criteria
- [ ] Tugboat Dashboard pages, CMS and WEB UI display a pre-deploy warning message is designed
- [ ] Tugboat Dashboard pages, CMS and WEB UI display a full-screen "deployment in progress" message is designed

## Tasks

- [ ] DevOps and @rachel-kauff @jordana discuss technical details of the process
- [ ] @rachel-kauff @jordanamello propose messaging / design for warning and full-screen messages
- [ ] DevOps review for technical feasibility
