### ISSUE TITLE
Use Memcache for Drupal Cache - [Devops]

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#4458]
## Acceptance Criteria

- [x] Memcache is ready for consumption by the application on CMS-TEST (all environments)
- [x] ElastiCache infrastructure is in code
- [x] ElastiCache cluster is configured for High Availability (2 nodes)
- [x] Configuration/etc. is documented

## Tasks 
- [x] Terraform config for the ElastiCache cluster

whatever we understand from setting this up, will influence approach in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4817 

note: auto-discovery out of scope

**Comment by ElijahLynn** [comment]
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_cluster

**Comment by olivereri** [comment]
Hack-a-thon settings:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/39863b05-d617-4913-8bc4-b1dba49b9d99)

**Comment by olivereri** [comment]
# Connectivity Tests:
Only bare minimum network connectivity to test AWS Security Group rules:

## Dev
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/b199d73a-3654-4fdb-a068-45ea7009d0ac)
## Staging
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/59134661-d88c-45b5-989a-53b834e68995)
## Prod
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/9168c369-3bb1-4ae1-9580-9fb3afc12843)

**Comment by olivereri** [comment]
# Technical Documentation Draft:

## Purpose:
Provide an overview and detailed technical information regarding the implementation of AWS Elasticache using the Memcache engine.
## Motivation:
(va.gov Front-end content releases ?) and GraphQL increases load on Drupal backed VA.GOV-CMS database. By implementing a layer of the most frequently accessed data those queries will remove be much faster and shift load away from the CMS database. In-memory caching is an effective way to solve this problem
## Research Findings:

Team tested build times<sup>[[4]](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4461#issuecomment-806146870)</sup> and resource consumption of a PoC for Elasticache Memcache and found that a full build request was faster and consumed fewer resources<sup>[[5]](http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&from=1616614756221&to=1616615896576&var-datasource=Prometheus%20(Utility)&var-environment=dev&var-app_name=cms-test)</sup> on the database server and only slightly more CPU on the app server. It is suspected that it is so much faster on a cold cache because the cache writes are faster with Memcache than RDS. 
Cold cache (over 50% decrease)

- GraphQL Request time
  - wo/Memcache: 1m06s
  - w/Memcache: 0m32s	
- RDS Load
  - wo/Memcache: 33% max
  - w/Memcache: 21%
- RDS Write IOPS (read was negligible)
  - wo/Memcache: 657/second
  - w/Memcache: 13/second
- EC2 Load
  - wo/Memcache: 24.0% max
  - w/Memcache: 47.1% max
- Warm cache
  - GraphQL Request time
    - wo/Memcache: 5.365s
    - w/Memcache: 4.788s
  - RDS Load - N/A
  - EC2 Load - N/A

The 50% decrease in response times for a vets-website GraphQL Build with our current node count of 5K+ justifies the replacement of AWS Relational Database Service (RDS) with AWS Elasticache Memcache for the Drupal Cache Layer. The decrease in response time also justifies the increased complexity of adding Memcache to our entire stack, including CI and Local environments.

- Redis
  - Pros
    - Advanced Data Structure
    - Clustering
    - “Fastest”
    - Sharding
  - Cons
    - Single Threading
    - Blocking
- Memcache
  - Pros:
    - Simple
    - Multi Thread out of the box
    - Fast
  - Cons:
    - Simple data structure
    - Old hotness?

## Implementation Details:

AWS Elasticache using Memcache is implemented in Terraform<sup>[[2]](https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/21)</sup>

Continue here...

## References
1. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4458
1. https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/21
1. https://github.com/department-of-veterans-affairs/devops/pull/8895

1. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4461#issuecomment-806146870
1. http://grafana.vfs.va.gov/d/dxf8a-6Zz/cms-dashboard?orgId=1&from=1616614756221&to=1616615896576&var-datasource=Prometheus%20(Utility)&var-environment=dev&var-app_name=cms-test

**Comment by jefflbrauer** [comment]
@olivereri Awesome work - can you please find a good spot in our code repo read.me for this documentation and link to it from this ticket?
