### ISSUE TITLE
Document image derivatives (image styles) available through Content API

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4464]
## User Story or Problem Statement

As a product team, i know what image derivates are supported by the Content API.

## Acceptance Criteria
- [ ] Documentation is available on va.gov-team repo about image derivatives (aka image styles in drupal-speak) available via Content API
  - [ ] Aspect ratio
  - [ ] Resolution
  - [ ] Crop-based or not
  - [ ] Stretch: example uses in various products (@kevwalsh could fill this in)
  - [ ] drupal machine names (snake case)
  - [ ] stretch: liquid template names (camel case)

## Implementation steps
<optional>
