### ISSUE TITLE
Comms for increased frequency of Content Releases

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4474]
## Background

Week of March 03/01 - Content Releases will run twice a day: 11am ET and at 2pm ET daily full website deploy.

A week of two after - 4x/day:  3 content releases + during the daily deploy

Shortly after - hourly Content Releases.

## User Story

As a CMS user, I need to understand the changes in the content release schedule and how they affect my work.

## Acceptance Criteria
- [x] Communication strategy is formed to facilitate change management up to hourly content releases
- [x] Comms strategy reviewed and confirmed w/ @davidconlon @johnhashva 
- [ ] Comms are sent to all CMS users (slack and email)
   - [x] Week of 03/01 - communication about 2x/day content releases
   - [ ] ~Communication about 4x/day content releases~ https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4630
   - [ ] ~Communication about 8x/day content releases~ #4631 
   - [ ] ~Communication about hourly content releases~ #4632 
- [x] Existing documentation updated
   - [ ] ~Diagram in GitHub [here](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/product-release-notes/screenshots/CMS-and-VAGOV-deployments.png)~ https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4651
   - [ ] ~Source Whimsical [here](https://whimsical.com/va-gov-cms-deployments-14gDq8UJ61yYx4cD4kHFKQ)~ https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4651
   - [ ] ~Training slides~ https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/3583 , also see thread https://dsva.slack.com/archives/CT4GZBM8F/p1615501894479000
   - [x] CMS help center

**Comment by oksana-c** [comment]
linking comms - Email 1-4 https://docs.google.com/document/d/16XaK_iIagT18WxH9D1SOEgn82D4u4vS7BappbrmTS2k/edit#

new user guide about Content Release to VA.gov - https://prod.cms.va.gov/help/content-release-to-vagov
