### ISSUE TITLE
Add governance to field_vet_center field so that editors can only select vet centers they have access to

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4478]
## User Story or Problem Statement

Vet Center editors should not able to add content to Vet Centers via `field_vet_center` they do not have access to (per `field_administration`.)

We've built a service in VAMC system that we can reuse here.  

## Acceptance Criteria
- [ ] Vet Center editors should not able to add content to Vet Centers they do not have access to. 

## Implementation steps
- [ ] Remove all `field_vet_center` fields and replace with `field_office`. 
- [ ] Add content type to service array in docroot/modules/custom/va_gov_user/src/Service/UserPermsService.php.

**Comment by kevwalsh** [comment]
Closing this in favour of #4541
