### ISSUE TITLE
Spike: Vet Center dashboard architecture 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4481]
## User Story or Problem Statement

In sprint 28 we will be implementing a Vet Center dashboard on Vet Center sections. We want an architecture that can also be used for other product such as VAMC. 

## Acceptance Criteria

We have answers to the following q's

- [ ] We have an implementation path that can be launched for Vet Center MVP but also refactored for use with a new design.
- [ ] do we use `field_office` or `field_administration` to filter content? ideally they are in sync but if not, which one is the source of truth. probably `field_office` bec
- [ ] Twig template approach (a product field on the Section taxonomy term? some other approach?) 
- [ ] Page layout approach
- [ ] Components
  - [ ] FE URL (can we include "pending" from the proofing page?)
  - [ ] "Cards" (as blocks?) 

 

## Implementation steps
<optional>

**Comment by kevwalsh** [comment]
Per [slack](https://dsva.slack.com/archives/CT4GZBM8F/p1616605964364300?thread_ts=1616603201.355800&cid=CT4GZBM8F)

**Kevin Walsh  5 days ago**
1. Create a view mode for Vocabularies for each product that needs a dashboard attached to a Section (“Vet Center dashboard”, “VAMC dashboard”, in the future “Office” … there may be a dozen of these eventually, but not likely more than 10 view modes)
2. Add a product (or dashboard) field to the Section taxonomy as we discussed
3. Use hook_entity_view_mode_alter()  (found this on https://www.drupal.org/project/view_mode_switch but i don’t think a contrib module is needed) to change what view mode is used to display the section terms, based on the product/dashboard field used in the section (or in a parent/ancestor section)
4. Use layout builder on each Vocabulary dashboard view mode to govern layout and block placement

What is not accounted for in the above:
1. “Subdashboards” like Health services on VAMC dashboard. Steve can speak better to the “painting us into corner” problem associated with that!

**Nathan Douglas:house_with_garden:  5 days ago**
That's very similar to what I did to implement a newsletter generator at my previous employer.

**Steve Wirt  5 days ago**
subdashboards as long as we are ok with them being Views, which is how they are all defined currently, this would work fine.

**Steve Wirt  5 days ago**
Mainly the only custom code this would require is something to traverse the parents and find the first parent with an assigned product (which was going to be needed for the model pitched yesterday)

**Steve Wirt  5 days ago**
Then we just use hook_entity_view_mode_alter() to set the view mode based on the product.

**Steve Wirt  5 days ago**
Bing bam boom and Ethan's Aunt Bob is your Uncle  :wink:
