### ISSUE TITLE
Fieldgroups and TOC for Vet Center node form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4531]
## User Story or Problem Statement

As a Vet Center editor, i want quick access to the content i am trying to edit, so that i can quickly complete my editing task. 

## Designs

[Pending usability testing and some accessibility review week of March 1]

https://www.figma.com/file/885DMraAi9V2DLJnrIN7Wv/Vet-Centers?node-id=2%3A183

## Acceptance Criteria
- [ ] we have a shared plan for how to implement each id
- [ ] Fieldgroups are created with appropriate `id`'s , or IDs are added to other elements, and fields are nested appropriately.
- [ ] Fields and fieldsets are accessible 
- [ ] Table of contents is visible at top of page, linking to appropriate id's, and other guidelines at the top of the page.
- [ ] Tooltip content is in place in fieldgroups
 

## Implementation steps
- [ ]

**Comment by kaise-lafrai** [comment]
5f582f12-b72f-4a35-a9df-411485c8e446

**Comment by kaise-lafrai** [comment]
This ticket combines ACs for #4739 and #4747.
