### ISSUE TITLE
Group  "Vet Center" sections into Districts and update menu toolbar

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4582]
## User Story or Problem Statement

Vet Centers will add 300 sections to the Sections taxonomy

This will kill performance of the toolbar menu. We'll need to follow the approach used for VAMC. But as of now, we have no way of grouping these, and we probably want to avoid a list of 300 Vet Centers on the [VHA > Vet Centers](https://prod.cms.va.gov/section/vet-centers) section.

## Acceptance Criteria
- [x] 5 districts sections have been created as children of Vet Centers
- [ ] Every Vet Center section has been added to a parent District
- [ ] No children of "Veterans Health Administration" > "Vet Centers > District N" are visible in the toolbar menu.

## Implementation steps
- [ ] ~Automated migration~
- [ ] Install and enable hierachy_manager but don't enable any config, and create PR with just that, and test on Tugboat, then after release:
- [ ] As admin, go to prod.cms.va.gov/admin/config/user-interface/hierarchy_manager/config
  - [ ] Check the Taxonomy hierarchy setup plugin checkbox and save
  - [ ] Go to prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview and drag and drop the Vet Centers according to the groupings specced in https://docs.google.com/spreadsheets/d/1AHnEMOFD7Fge7wetPE972E4Mne6j1_x1/edit#gid=484827806
- [ ] Disable some District 1-5 menu items at https://prod.cms.va.gov/admin/structure/menu/manage/sections
