### ISSUE TITLE
Drupal Logs Monitoring & Alerts [Sentry]

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4693]
### User Story or Problem Statement

As a CMS Engineer, I need to have efficient access to a log of application errors that affect CMS users, so that I can diagnose and fix errors.

As a CMS Engineer, I need to have alerting of application errors that affect CMS users, so that I can address issues before the impact is too great.

### Affected users and stakeholders

* CMS Engineers

### Assumptions

Internal: https://dsva.slack.com/archives/CE4304QPK/p1600896861002300

## Acceptance Criteria
- [x] the CMS team is tracking Drupal system performance and has access to the following KPIs at a glance:
   - [ ] Drupal system errors 
   - [ ] PHP errors
   - [ ] PHP Exceptions
   - [ ] Error logging events
   - [ ] SQL Deadlocks
- [x] Sentry is configured and provides details reporting for the CMS application
- [x] CMS Engineers receive alerts for important Drupal events related to KPIs described above

**Comment by mchelen-gov** [comment]
spot check for AC: confirm that facility status migration errors are showing up in Sentry and sending Slack alerts with the appropriate severity level
