### ISSUE TITLE
CMS Testing Best Practices and Training

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4724]
### User Story

As a CMS Engineer, I need to have efficient and intuitive testing tools and processes that aid feature development and testing instead of hindering velocity.

### Problem statement

The CMS team needs the most comprehensive testing possible with the least amount of configuration required.

The CMS team needs easily accessible and up-to-date documentation and training on best practices in application testing.

### Affected users and stakeholders

* CMS Engineers

### Hypothesis

We believe that clear standards around testing CMS features and efficient testing toolkit will align CMS engineers in a concerted effort to ensure that mission-critical CMS functionality is well tested and no regressions are deployed to production.

## Acceptance Criteria
- [ ] CMS testing standards and process are defined
- [ ] Clear guidance on the CMS testing standards and process is available to CMS engineers
- [ ] Up-to-date documentation for each testing tool that CMS uses is available in the CMS repository
- [ ] CMS Engineers are trained on CMS testing standards and process
