### ISSUE TITLE
CMS Content and User Monitoring

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4726]
### User Story or Problem Statement

As a CMS DevOps or Application Engineer, I need to have quick access to CMS Content and User metrics overtime, so I can effectively troubleshoot any infrastructure or application issues and anticipate scaling needs.

### Affected users and stakeholders

* CMS DevOps and Application Engineers

### Hypothesis

We believe that having quick access to CMS Content and User metrics will help the CMS team to:
* troubleshoot any infrastructure or application issues
* observe trends overtime and anticipate scaling needs

## Acceptance Criteria
- [ ] Drupal sends metrics data to Prometheus
- [ ] the following CMS Content and User metrics are available in Grafana dashboard including trends overtime
   - [ ] Total Node Count
   - [ ] Published Node Count
   - [ ] Number of Active Users (not blocked)
   - [ ] Number of user accounts logged in per minute
