### ISSUE TITLE
RDS Monitoring & Alerts

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4727]
### Hypothesis

We believe that having quick access to CMS RDS metrics & alerts will help the CMS team to:
* troubleshoot any infrastructure or application issues
* observe trends over time and anticipate scaling needs
* react to high resource consumption in a timely manner

### Affected users and stakeholders

* CMS DevOps Engineers

## Acceptance Criteria
- [ ] alert thresholds are defined and agreed upon
- [ ] RDS logs are sent to Loki
- [ ] RDS monitoring is configured for the following metrics:
   - [x] DB Connections
   - [x] CPU
   - [ ] Slow queries
   - [ ] Error Logs	
- [x] RDS alerts (via prometheus alert manager) are configured for the following criteria:
   - [x] CPU 
      - [x] 70% over 3 minutes
      - [x] 100% over 1 minute

**Comment by acrollet** [comment]
Monitoring spike doc: https://docs.google.com/document/d/1LlxH026S1OPny-FtpokuxHv30v9AuMt2aoWTUUct_lw/edit#

**Comment by mchelen-gov** [comment]
@ElijahLynn @indytechcook it sounds like there is an existing alert for RDS CPU sustained spike?

**Comment by mchelen-gov** [comment]
@acrollet it sounds like we can monitor & alert on RDS CPU and connection count using Cloudwatch + Prometheus/Grafana? if so let's remove Loki AC so this isn't blocked

**Comment by acrollet** [comment]
> @ElijahLynn @indytechcook it sounds like there is an existing alert for RDS CPU sustained spike?

I believe so, e.g. https://dsva.slack.com/archives/C24RH0W11/p1620829122117000

@ElijahLynn do the existing alerts need to be modified to meet these ACs?

**Comment by acrollet** [comment]
DB connection alert AC split out into #5405
