### ISSUE TITLE
Initial Discovery: Accelerated Publishing

### ISSUE THREAD

**Issue by oksana-c** [department-of-veterans-affairs/va.gov-cms#4748]
# Discovery: Accelerated Publishing 

The purpose of this discovery is to understand the challenges faced by editors when publishing content to VA.gov and identify ways to improve this process.

## Headlines
**Business stakeholder -**
All VA business units currently using the Drupal CMS or considering migrating from another system, all teams publishing content to www.va.gov including:
- Facilities
- Public Websites
- VFS teams

**DEPO owner -**
@mchelen-gov 

**Approvals**
- [x] @rroueche 
- [x] @mchelen-gov 

## Details
**Who is the primary user?**
CMS Editors

**What are the user goals for the project/page/product?**
- _As a CMS Editor, I would like to publish content to VA.gov as quickly and easily as possible, and no longer than 5 minutes, so that I can most effectively deliver content to Veterans and the public._
- _As a DEPO product owner, I would like to understand CMS Editor content publication use cases and paint points affected by publishing speed so that I can plan improvements and features to most effectively support them._ 
- _As a VSP engineer, I would like to understand the content build architecture so that I can best apply technical solutions._ 

**What is the business goal?**
- Research and document existing CMS and content build architecture.
- Understand CMS Editor objectives and pain points when publishing content.
- Propose approaches improvements to content publishing
- Describe architecture, implementation, team structure, target milestones, and risks for proposed methods.

**How does this map to our North Star?**
- Decrease time to outcomes
- Maximize satisfaction, reliability, availability, & security

**How will we measure success?**
- When we have accurately described options for improving content publication including goals, architecture, team, target milestones, and risk register. 

**How well do we understand the problem?**
- We are aware of many pain points including publishing speed and content scaling limits. This discovery is intended to understand how editor use cases are affected, and determine the technical approaches required to address them.

**What is DEPO's role in this work?**
- Allocate resources for discovery
- Identify stakeholders and facilitate communication
- Review findings with stakeholders 
- Provide guidance around prioritization of use cases and technical roadmap

**What are the known risks?**
- Legacy build system requires substantial time to understand
- Coordination is required from multiple DEPO teams and VA stakeholders 
- Availability of engineering capacity
- Regulatory (ATO) implications affect technical options
- Business requirements for feature compatibility or timeline may restrict architecture implementation options

**Reference links:**
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4748

The Discovery phase is outlined as follows:
* Sprint 29 - 30 (3/29 - 4/23) - Problem space definition; Knowledge gap analysis and closure; POCs and Technical Architecture Draft
* Sprint 31 (4/26 - 5/7) - Approval from OCTO-DE; ATO reviews; Final team structure; Backlog; Risk Register

### User Stories 

As an "Accelerated Publishing" team member, I need to understand the problem space in depth before attempting to recommend solutions, so that I can avoid risks and miscommunication down the road.

As an "Accelerated Publishing" team member, I need to perform research into the problem space, so that I can recommend solutions and generate POCs.

As an "Accelerated Publishing" team member, I need to outline technical architecture of the recommended approach, so that it can be shared and approved by OCTO-DE.

As an "Accelerated Publishing" team member, I need to contribute to the development of the initiative roadmap and flag any risks to the timeline, so that the team is set up for success given available resources.

### Hypothesis

We believe that a solid problem space definition that encompasses current and desired [user, engineer, stakeholder] experience will serve as a guiding light for the Accelerated Publishing effort.

We believe that exploring the current content build ecosystem in depth will help us close knowledge gaps and identify areas of value, areas of high-risk and areas of improvement.

We believe that generating Proof-of-concept prototypes will help us validate hypothesis during the discovery phase.

## Acceptance Criteria

- [x] [Problem space definition](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition.md) is available for stakeholder reference
- [x] [Success criteria are defined](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition.md#what-does-success-look-like)
- [x] [Current content build ecosystem](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/content-build) has been documented in detail to close knowledge gaps
- [x] [Research into the problem space](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/problem_space_definition.md)is performed and any POCs are generated
- [x] [User Experience research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/ux_research) has provided an understanding of publishing pain points and this understanding is socialized with stakeholders
- [x] [POCs](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/single_page_publish_poc.md) are validated against success criteria
- [x] [Solution Option Matrix](https://docs.google.com/spreadsheets/d/1qrXyjnED4aaJuQ0AgqHHFK2RMjjqeAP1GL1hw5lo0tU/edit#gid=0) is complete
- [x] CMS team has reviewed and [proposed an implementation initiative ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/findings_recommendations.md)for review by OCTO-DE

---

**Reference links:**
https://github.com/department-of-veterans-affairs/digital-experience-products/issues/323

**Comment by mchelen-gov** [comment]
is this complete? all the tickets look closed
