### ISSUE TITLE
Change pathauto for Detail Pages to use the full menu hierarchy.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4773]
## User Story or Problem Statement

Currently URL aliases are set to [node:field_office:entity:url:path]/[node:title] 

URL aliases for detail pages should include the menu hierarchy. Eg if a detail page is saved with salt-lake-city-health-care/work-with-us as the parent menu item, it should have the salt-lake-city-health-care/work-with-us/[title]

## Acceptance Criteria
- [x] ~health_care_region_detail_page has been added to the "Menu-based" pattern, and "Detail page" pattern has been deleted.~  **Update March 24:** This needs some more thinking. Because detail pages do not require menu items, we can't count on menu tokens to build the URL. **Update mid-May:** Detail pages will require menu items, based on #1268
- [x] [node:menu-link:parents:join-path] should be updated to meet two needs
  - [x] 1. parent menu items with `<nolink>`are ignored 
  - [x] 2. parent menu items that have path aliases set manually (in this case, all VAMC systems, which have `va-` stripped from their first URL path... like `VA Altoona health care` becomes `altoona-health-care). 
- [x] this pattern should be applied to all VAMC Detail Pages

## Implementation steps

![Patterns___VA_gov_CMS](https://user-images.githubusercontent.com/643678/112166807-57ef0600-8bc6-11eb-9200-28252a8fc0a2.png)

**Comment by kevwalsh** [comment]
This is turning out to be more complicated. 

I updated the pathauto pattern `[node:menu-link:parents:join-path]/[node:title] for `health_care_region_detail_page`. 

i created an audit/bulk operations view to help test this, and see the before and after, which can be found at https://pr5329-hlvekp16ivk1elzkftnv0vc65wvkaizj.ci.cms.va.gov/admin/content/audit/detail-pages-urls

Running "update URL alias" using bulk update leads to a bunch of undesired URL segments that contain the URL sections when one of the parent menu items contain `<nolink>`  (in particular, "Services and Locations", and "About [Health care system])" have been added to the URL alias. Here's a screenshot showing before and  after. 

![detail-pages-urls_csv__Imported_table_-_Airtable.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/de29165f-23a8-407d-bd60-e5746dc824b2)

This [comment in the pathauto issue queue](https://www.drupal.org/project/pathauto/issues/1496582#comment-13134944 
) seems to speak to this problem. I also found folks [reporting the same problem having been fixed in D7](https://www.drupal.org/project/special_menu_items/issues/1485784), when `<nolink>` was a feature of the `special_menu_links` contrib module (but which has since been added to core).
