### ISSUE TITLE
Care we provide h3s in VAMC system health service

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4799]
## User Story or Problem Statement

* Care we provide h3s can be "hardened". 
* Semantic headings in VAMC system health service are not structured properly in all displays. 

![Edit_VAMC_System_Health_Service_Surgery_at_VA_Salisbury_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/112336802-c6e66080-8c93-11eb-8406-f8d5a6e7af49.png)

## Acceptance Criteria

Rich text editor
- [ ] VAMC system description field is "rich text limited" moving forward
- [ ] All existing VAMC system nodes have been set to use rich text limited only.

Remove existing content
- [ ] All headings in VAMC system health services are deleted (not converted to the allowed `<p>`)

## Implementation steps

- [ ] Add feature flag in Drupal
- [ ] FE can start targeting this 
- [ ] Write script to update blobs (remove all heading tags)
- [ ] Update field
  - [ ] Set field's to only allow "rich text limited"
  - [ ] Change field label to "Care we provide"
- [ ] Feature flag removal

**Comment by ContentBrewmaster** [comment]
Added CM triage text

**Comment by JayDarnell** [comment]
Counts:

h2 (21 items) - [vamc-system-service-audit-h2.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8612303/vamc-system-service-audit-h2.csv)

Post care we provide cleanup script: h3 ( items) - 

h4 (57 items) - [vamc-system-service-audit-h4.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8612294/vamc-system-service-audit-h4.csv)

h5 (7 items) - [vamc-system-service-audit-h5.csv](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8612307/vamc-system-service-audit-h5.csv)

**Comment by swirtSJW** [comment]
Do we have to do anything more with these counts or can we call this epic done?

**Comment by JayDarnell** [comment]
PR to remove the feature flag now that it is no longer needed: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9040
