### ISSUE TITLE
Disable password_policy on lower environments

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4802]
## User Story or Problem Statement

We often need to edit users in PR, demo, or training environments. Password policy doesn't like the `drupal8` password that we set for all users in lower environments. 

See [this Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1616417231174900) which references [this slack thread](https://dsva.slack.com/archives/C01FMRGRAGY/p1616095133023000)

## Acceptance Criteria
- [ ] it's possible to edit any user (eg user/197/edit), change the roles, hit save,  and not have to add a complex password.

## Implementation steps
- [ ] Configure Config split to only enable password_policy on prod. 
- [ ] In-place tests are executed against the Production behavior, not non-prod behavior (i.e. production behavior is enabled before and disabled after the test, or some similar way of testing desired production behavior is accomplished)
