### ISSUE TITLE
Prevent editors from saving content with unsavory links 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4806]
## User Story or Problem Statement

As an editor, i want good feedback if i try to include bad links, such as Outlook safelinks or other links recreated by an application. 

Examples: 
```
https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fda.gov%2Femergency-preparedness-and-response%2Fcoronavirus-disease-2019-covid-19%2Fmoderna-covid-19-vaccine%23additional&amp;data=04%7C01%7C%7Cae4b13d851d04f5bdd4908d8a5e18c0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637441735414140146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=7%2BSIjDj2S3y85ZedTnWAG34O%2FO8J7akY2aKJ5WfKdN8%3D&amp;reserved=0
``` 

## Acceptance Criteria
- [ ] We have a place in the codebase to maintain a list of bad URL patterns, including Outlook safe links, links generated by google search result links, etc. 
- [ ] Editors get feedback if they include a link that matches that pattern in rich text (and/or in a link field?)
- [ ] TBD: feedback is a warning? or does the form not validate?

## Implementation steps
TBD

**Comment by 1Copenut** [comment]
Related issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/22139

**Comment by kevwalsh** [comment]
![jenkins___testing_content-build-integration-testing___content-build-integration-testing____102.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/05afcfd8-f344-446d-878e-496d17ad47eb)

```
 - sitemap 1/4 (24m 24s)

[2021-05-26T16:22:24.032Z]    Failed [fail]: (

[2021-05-26T16:22:24.032Z]              Description:  Links must have discernible text

[2021-05-26T16:22:24.032Z]              Impact:       serious

[2021-05-26T16:22:24.032Z]              Rule ID:      link-name

[2021-05-26T16:22:24.032Z]              URL:          http://content-build:3001/hudson-valley-health-care/nurse-residency-programs/

[2021-05-26T16:22:24.032Z]              DOM node:     

[2021-05-26T16:22:24.032Z]    <a href="mailto:judith.brown2@va.gov" target="_blank"> </a>

[2021-05-26T16:22:24.032Z]    a[href="mailto\:judith\.brown2\@va\.gov"][target="_blank"]:nth-child(2)

[2021-05-26T16:22:24.032Z]              More help:    https://dequeuniversity.com/rules/axe/4.1/link-name?application=axeAPI

[2021-05-26T16:22:24.032Z]            )

[2021-05-26T16:22:24.032Z]              Description:  Links must have discernible text

[2021-05-26T16:22:24.032Z]              Impact:       serious

[2021-05-26T16:22:24.032Z]              Rule ID:      link-name

[2021-05-26T16:22:24.032Z]              URL:          http://content-build:3001/hudson-valley-health-care/nurse-residency-programs/

[2021-05-26T16:22:24.032Z]              DOM node:     

[2021-05-26T16:22:24.032Z]    <a href="mailto:judith.brown2@va.gov" target="_blank"> </a>

[2021-05-26T16:22:24.032Z]    a[href="mailto\:judith\.brown2\@va\.gov"][target="_blank"]:nth-child(2)

[2021-05-26T16:22:24.032Z]              More help:    https://dequeuniversity.com/rules/axe/4.1/link-name?application=axeAPI

[2021-05-26T16:22:24.032Z]            ): Failed [fail]: (

[2021-05-26T16:22:24.032Z]              Description:  Links must have discernible text

[2021-05-26T16:22:24.032Z]              Impact:       serious

[2021-05-26T16:22:24.032Z]              Rule ID:      link-name

[2021-05-26T16:22:24.032Z]              URL:          http://content-build:3001/hudson-valley-health-care/nurse-residency-programs/

[2021-05-26T16:22:24.032Z]              DOM node:     

[2021-05-26T16:22:24.032Z]    <a href="mailto:judith.brown2@va.gov" target="_blank"> </a>

[2021-05-26T16:22:24.032Z]    a[href="mailto\:judith\.brown2\@va\.gov"][target="_blank"]:nth-child(2)

[2021-05-26T16:22:24.032Z]              More help:    https://dequeuniversity.com/rules/axe/4.1/link-name?application=axeAPI

[2021-05-26T16:22:24.032Z]            ) - Expected "undefined" but got: "undefined"

[2021-05-26T16:22:24.032Z]        at forEach (/application/content-build/src/platform/testing/e2e/nightwatch-commands/axeCheck.js:85:21)

[2021-05-26T16:22:24.032Z]        at Array.forEach (<anonymous>)

[2021-05-26T16:22:24.032Z]        at Object.<anonymous> (/application/content-build/src/platform/testing/e2e/nightwatch-commands/axeCheck.js:72:18)
```

**Comment by swirtSJW** [comment]
AS of this pr we are warning in the broken link report.  It does not prevent saving, but does call it out. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5442

**Comment by EWashb** [comment]
Although an old ticket, I'm going to add it to the requirements definition pipeline since Laura added the appropriate accessibility label recently

**Comment by srancour** [comment]
@gracekretschmer-metrostar this could be a good opportunity with helping editors to make their content more accessible along with the PDF and alt-text work.
