### ISSUE TITLE
Design system documentation review

### ISSUE THREAD

**Issue by gujacq** [department-of-veterans-affairs/va.gov-cms#4840]
## Description
As a UX researcher, I want to understand what has been done with the design system so far, so I can define a strategy for structuring a design system for the CMS.

## Tasks
- [x] Review existing documentation for design system
- [x] Review existing documentation for brand
- [x] Meet with Rachel to review upcoming work 
- [x] Debrief with Oksana on what’s been done on the tech architecture side

## AC
- [x] Jacqueline understands the landscape of existing tools and their components and how a design system may affect change enough to start working on a strategy

## Resources 
- [Design System Inventory Key Information](https://docs.google.com/document/d/1S7qFGjbbgO0qj8g6SJEyHUYZqfvJXUq--6UHZBWTYR8/edit)
- [Previous gap analysis](https://drive.google.com/drive/u/1/folders/1n6Ro-1a7E-AfvMPJSZ5fGfAAgy_V1Ekt)
- [Previous Design System roadmap](https://lucid.app/lucidchart/4dd0105e-f2bc-4703-bf1c-c843eedec706/edit?page=0_0#)
