### ISSUE TITLE
Sprint 29 Product support team priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4843]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

### Campaign Landing Page MVP

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

**#2275 Change management for beta users**  👥

- [x] #4838 Facilitate CLP beta tests with VHA editor
- [x] #4848 CLP beta user synthesis

### Outreach Hub

- [x] #4844 Fix events administration page (defect)
- [ ] #4213 Archive past Outreach hub events, and let editors know (content)
- [ ] Review feature requests with Public Websites team (product)

### Resources and Support

- [ ] #4633 Removing Benefit Hubs is not possible when parent form fails validation (defect) (_stretch_)

### VA Forms 

N/A

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

### Cross-product (VAMC Policies, Vet Center)

- [ ] #4822 Provide fetched data directly in EntityFieldFetched fields (Improve GraphQl support for Centralized Content) **NEEDS ESTIMATE**  🥅  
- [ ] #4857 Create shared understanding of Lighthouse / CMS facility migrations 

#### #4374 Local editor experience

- [ ] #4850 Vet Center MVP Dashboard implementation **NEEDS ESTIMATE**   🥅  
- [x] #4541 Extend field_office entity reference permissions to Vet Center content types 
- [x] #4808 Vet Center form implementation: Outstations, CAPs, Mobile Vet Center content types
- [ ] #4807 Add content type descriptions for all Vet Center content types (stretch)

#### #4370 Migration @kaise-lafrai, @swirtSJW

- [ ] Generate one "Vet Center Locations List" node for each Vet Center (see #4324 below) (stretch)

####  Lighthouse push
- [x] #4854 Facility status for 18 Outstations is failing on push
- [ ] #4410 Lighthouse discovery: Vet Center CAP and Outstation data @swirtSJW

Stretch
- [ ] #4411 Push Vet Center CAP data to Lighthouse (*stretch*, can go to Sprint 30)

#### #4318 Content model and governance

- [ ] #4582 Hide children of "Vet Centers" section in the toolbar menu and add groupings (dependent on grouping from @davidconlon ) (*stretch*)
- [x] #4628 Make revision log mandatory for all vet_center_* content types

#### Product team collaboration

FE support
- [x] #4324 Create 10 Vet Center Locations List nodes (should this be migration?)
- [ ] Setting Section and field_office for 18 Outstations
- [x] Recreate Escanaba Facility Health Service nodes, to fix CER?
- [ ] #4409 Support Facilities team FE devs with content model 

Documentation
- [ ] VAST migration
- [ ] Lighthouse push
- [ ] Content admin tasks

#### #4373 National editor experience

TBD

### VAMC System

- [ ] #4849 Make it possible to archive a facility **Needs refining**
- [ ] #3292  **Remove entity embed** 
  - [ ] #3294  Remove Entity embed tool from Rich text editor 
- [ ] #4743 **Distinguish mobile VAMC clinics from non-mobile clinics** (needs estimates) (_stretch_)
  - [ ] #4744 Content model: Mobile flag for VAMC facilities
  - [ ] #4745 Add mobile flag to VAST facility migration
- [ ] #4842 Launch 8-10 VAMCs in VISN 6 and beyond @swirtSJW  @kevwalsh
- [ ] Debug Eastern Colorado.

Training
- [x] #3278 Training for Policies page
- [ ] #3277 User guide for Policies Page
- [x] #4836 Update VAMC session 3 training videos for new navigation, training link, and help desk link

### Governance & editorial experience 

**Epic: Enforce IA design for VAMC editors**
- [x] #4311 SPIKE: technical implementation of VAMC system menu IA governance @ethanteague  🥅  
- [ ] #4773 Change pathauto for Detail Pages to use the full menu hierarchy.

**Epic Centralized content national editing experience**   (stretch)
- [ ] #4195 Support tokens in EFF for inserting local values into nationally managed content 
- [ ] #4056 Prevent deletion of centralized content  *needs refining* 
- [ ] #4016 Modify cc_documentor paragraph to have special form view  @swirtSJW *needs refining*

**Epic: Unique content validation**  (stretch)
- [ ] #4074 Spike: Unique content validation approach   (will span more than one sprint) @kaise-lafrai 

## #4019 User administration service  

- [ ] #4115 Workbench access (Sections) training, documentation, and purging of redundant Section access
- [ ] #3801 User administration policy for Vet Center MVP editors
- [ ] Document Outreach Hub user administration policy
- [ ] Document VAMC user administration policy

## Core team collaboration

**Drupal 9 update**
- [x] #4283 Update Migration Tools module @swirtSJW
