### ISSUE TITLE
Setup Layout builder for sections taxonomy

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4855]
## User Story or Problem Statement

- [x] Add `field_product` entity reference field added to Sections taxonomy (`administration`). 
- [x] View mode created for taxonomy "Vet Center Dashboard" and enabled on Sections taxonomy 
- [x] Vet Center facility listing view enabled on Vet Center Dashboard

Content needed on prod (or for development of the dashboard switch below), dependent on `field_product` above (@kevwalsh) 
- [ ] Vet Centers Section tagged with "Vet Center"
- [ ] VAMC Facilities section tagged with "VAMC System"

As a _____, I need _____ so I can _____.

or

Problem description. How might we _____________ ?

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Implementation steps
<optional>

**Comment by kevwalsh** [comment]
Moving this to done, the commits in PR #4870 are being incorporated within the next issue in this epic, #4850
