### ISSUE TITLE
Migrate CMS initiatives from Lucidchart to DEPO board

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#4874]
## Description
source: https://lucid.app/lucidchart/9b3d2f36-2e90-4b2a-9676-8edb96e9dd42/edit?shared=true&page=I9Ok25vTgODC#

destination: https://github.com/department-of-veterans-affairs/digital-experience-products/projects/1

template: https://github.com/department-of-veterans-affairs/digital-experience-products/issues/new?assignees=&labels=&template=product-board.md&title=

## Acceptance Criteria
- [ ] CMS initiatives added to DEPO board
- [ ] DEPO board issues are correctly filled out in accordance with template
- [ ] DEPO board issues are linked to appropriate CMS issues in GH

**Comment by TheBoatyMcBoatFace** [comment]
Closing out - Roadmap functionality handled by Zenhub.

If this is is still a priority, please reopen.
