### ISSUE TITLE
Improve UX for Hours widget 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4888]
## User Story or Problem Statement

Relates to #8861 

As an editor of a CAP, facility service, or top task page, i want to add and edit opening hours with an intuitive tool. 

The core Office Hours module's widget leaves a lot of room for improvement

- [ ] ~SO MANY dropdowns, all with empty values~
- [ ] ~Long rows that exceed the parent divs~
- [ ] Nonintuitive "Comment" ~and "Operations"~ column labels
- [ ] ~24 hour time~
- [ ] ~Not enough time selectors (00 or 30)~

<details><summary>Screenshot</summary>

![Create_Vet_Center_Community_Access_Point___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/27402a46-f7c0-4392-ae92-61f2a4d2894a)

</details>

Some design work was done in the scope of the Vet Center form, suggesting a modal dialog approach where the content is previewed and edited only when an editor interacts with it (such as by clicking on the pencil)

<details><summary>Screenshot</summary>

![Vet_Centers_–_Figma.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/159f3b45-6fae-4d87-9f46-2331d4691390)
![Vet_Centers_–_Figma.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e1f592c7-956e-4e88-97af-73da8ad183a6)

</details>

See also this "simple" UI from google calendar

<details><summary>Screenshot</summary>

![image.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/e8079814-fef0-42a1-92f5-dfa8f4696192)

</details>

We need an approach that works for multiple use cases, from Facility hours (various node types) to Service Locations hours (paragraph type) inside a facility health service. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

```[tasklist]
### Tasks
```

**Comment by msbtterswrth** [comment]
possible sandbox widget we could look at for improving this - https://www.drupal.org/sandbox/phoehne/2329615

**Comment by xiongjaneg** [comment]
See also #8368

**Comment by xiongjaneg** [comment]
See also #8368

**Comment by xiongjaneg** [comment]
@kevwalsh Will there be some communication to editors on hours changes? An alert on login page or something?

**Comment by kevwalsh** [comment]
I just came across this in Google Calendar. I like the plus symbol for supporting multiple sets of opening hours per day. And the Copy to all is intuitive and functions well. 


<img width="633" alt="Cursor_and_CivicActions_-_Calendar_-_General_settings" src="https://user-images.githubusercontent.com/643678/163224134-7f383add-9a3e-44ec-886e-77dfea58ba01.png">

**Comment by EWashb** [comment]
@jilladams @mmiddaugh @kmariepat-cityfriends This was one that doesn't have a set clear owner for the reasons you mentioned. This has been in the CMS backlog because hours widget is a design-heavy item that is either already reflected in the CMS Design System or at some point will/should be addressed.

If you all are working on something and need it soon, Facilities is welcome to formulate an experimental design system component and go through the collab cycle. But I will let @BlakeOrgan weigh in here to see if this is work he is planning to do in relation to other design system governance. cc: @productmike @BerniXiongA6

**Comment by jilladams** [comment]
Thanks Erika. I came across this in a big scrub of Facilities epics, where this ticket is mentioned but doesn't show in our board. No problem leaving as is for now, and if we ever _do_ need to iterate how hours are handled, we can treat it that way. Thank you!

**Comment by davidmpickett** [comment]
Closing this epic as all tickets have been completed or relocated to the more modern epic of #17350
