### ISSUE TITLE
Sprint 30 Product support team priorities [WIP]

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4892]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

### Campaign Landing Page MVP

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### Outreach Hub

Nothing expected, possibly refining Events epic stories for VAMC and Outreach Hub.

### Resources and Support

Nothing expected. 

### VA Forms 

Nothing expected. 

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

#### #4374 Local editor experience

Finish implementation of dashboard. 

Bug fixes.

####  Lighthouse push

- [ ] #4411 Push Vet Center CAP data to Lighthouse 

#### #4318 Content model and governance

- [ ] #4582 Hide children of "Vet Centers" section in the toolbar menu and add groupings (dependent on grouping from @davidconlon ) (*stretch*)

#### Product team collaboration

FE support
- [ ] #4409 Support Facilities team FE devs with content model 

Documentation
- [ ] VAST migration
- [ ] Lighthouse push
- [ ] Content admin tasks

#### #4373 National editor experience

- [ ] 

### VAMC System

- [ ] #4849 Make it possible to archive a facility **Needs refining**
- [ ] #4743 **Distinguish mobile VAMC clinics from non-mobile clinics** (needs estimates) (_stretch_)
  - [ ] #4744 Content model: Mobile flag for VAMC facilities
  - [ ] #4745 Add mobile flag to VAST facility migration
- [ ] [Needs issue] Launch 8-10 VAMCs @swirtSJW  @kevwalsh

Training
- [ ] Training materials for Vet Center

### Governance & editorial experience 

**Epic: Enforce IA design for VAMC editors**
- [ ] #4311 SPIKE: technical implementation of VAMC system menu IA governance @ethanteague  🥅  
- Anything that comes out of this spike, TBD
- [ ] #4773 Change pathauto for Detail Pages to use the full menu hierarchy.

**Epic Centralized content national editing experience**   (stretch)
- [ ] #4195 Support tokens in EFF for inserting local values into nationally managed content 
- [ ] #4056 Prevent deletion of centralized content  *needs refining* 
- [ ] #4016 Modify cc_documentor paragraph to have special form view  @swirtSJW *needs refining*

**Epic: Unique content validation**  (stretch)
- [ ] #4074 Spike: Unique content validation approach   (will span more than one sprint) @kaise-lafrai 

## #4019 User administration service  

- [ ] #4115 Workbench access (Sections) training, documentation, and purging of redundant Section access
- [ ] #3801 User administration policy for Vet Center MVP editors
- [ ] Document Outreach Hub user administration policy
- [ ] Document VAMC user administration policy

## Core team collaboration

TBD.
