### ISSUE TITLE
Style the date on EFF form displays per design (but without link)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4897]
## User Story or Problem Statement

As an editor of a page with centralized content, i want to know when the centralized content was last updated

![Screenshot_2021-04-01__1_45_PM](https://user-images.githubusercontent.com/643678/113333914-0b57a900-92f1-11eb-8a5f-345e61c449c6.png)

## Acceptance Criteria
- [ ] See screenshot
- [ ] Set "Show source updated date" to yes on all Vet Center EFF field widgets (check with @rachel-kauff on this)

## Implementation steps
- [ ] Theme the EFF form widget

## Not in scope
- [ ] Linking the last updated metadata to the source. (That's in #4054)

**Comment by rachel-kauff** [comment]
Would it be able to show a last updated timestamp for VAST data too, or is this for CMS-manage content only?

**Comment by rachel-kauff** [comment]
That's a YES to showing Last updated timestamps on all the national content for Vet Centers forms.

**Comment by swirtSJW** [comment]
> Would it be able to show a last updated timestamp for VAST data too, or is this for CMS-manage content only?

@rachel-kauff Not really.  The data is updated at midnight every night, but individual nodes are only updated in the CMS when there is actually a change.   So any date we display would be confusing and need lots of explanation.

**Comment by swirtSJW** [comment]
Since this has been updated in contrib and we can now more closely hit the spec, I am going to close this in favor of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4054
