### ISSUE TITLE
Add method to bullk push VHA facility service data to Lighthouse.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#4901]
## User Story or Problem Statement

As a CMS engineer I need a way to bulk push VHA facility service data to Lighthouse in the UI so that Lighthouse can be kept in sync with CMS data.

This approach should just add on to what is here /admin/config/va-gov-post-api/facility-force-queue

## Acceptance Criteria
- [ ] 👀 **Needs design review** because the work involves changes to labels or other design elements.
- [x] 🙈 Can be implemented without consulting design team members
- [x] Facility service appears as an option to select on the Force Queue page. /admin/config/va-gov-post-api/facility-force-queue
- [x] Choosing to force queue facility health services results in ~204 Covid vaccine services being added to the queue here /admin/config/post-api/queue

## Implementation steps
<optional>

**Comment by swirtSJW** [comment]
This is covered in t PR #4889.

**Comment by swirtSJW** [comment]
![image](https://user-images.githubusercontent.com/5752113/113372818-7e840e00-9337-11eb-8e40-96bd7e66ba5e.png)

![image](https://user-images.githubusercontent.com/5752113/113372827-85128580-9337-11eb-83d7-5f0a182fafdb.png)

**Comment by swirtSJW** [comment]
Lighthouse code has been merged so after CMS deploy today, we can run the bulk push from here https://prod.cms.va.gov/admin/config/va-gov-post-api/facility-force-queue
