### ISSUE TITLE
Facility health service should have limited options for Facility and System Service, based on Section

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4923]
## User Story or Problem Statement

As a VAMC editor creating a facility healths service, i should only see VAMC Facilities and VAMC systems that i have access to based on my Section membership. 

![Screenshot_2021-04-05__12_33_PM](https://user-images.githubusercontent.com/643678/113598475-2edd6500-960b-11eb-8c9e-3db8b8a75e8d.png)
 
## Acceptance Criteria
- [ ] As a member of Pittsburgh Health Care, i should only see 7 facilities in the and ~50 System services.
- [ ] Upon editing a facility health service, the selected service should remain as the existing selection. (Saving should not cause the systems service or facility to change)

## Implementation steps
- [ ] User string matching to reduce options.

**Comment by swirtSJW** [comment]
Re-opening this since the code was reverted.   The issue is that it was overridding existing setting on editing a facility health service.

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5392 has been merged
