### ISSUE TITLE
Services should not be moved from one facility to another

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4924]
## User Story or Problem Statement

As a VAMC editor, i should be able to create facility health services in any of my facilities, but i should not be able move them between facilities after they are created. 

Currently, Lighthouse may get orphaned data. 

If this happens again, we have to manually archive one, then create a new one (happened first week of April 2021). 

See also #4923

## Acceptance Criteria
- [ ] As a non-content admin or non-admin, i see these two fields represented as "External content", in a tooltip fieldgroup that explains: "These settings cannot be changed after the content has been created." 
- [ ] The fieldgroup should have no label. 

![Screenshot_2021-04-05__12_33_PM](https://user-images.githubusercontent.com/643678/113598992-f68a5680-960b-11eb-923c-8c5e7b2c8692.png)

- [ ] Outdated help text on these fields is removed. 

## Implementation steps

- [ ] Update Facility Health Service form.

**Comment by EWashb** [comment]
@mmiddaugh @jilladams cleaning up tickets from our backlog that didn't have a current team label, only "sitewide crew." Adding facilities so that you can have eyes on it
