### ISSUE TITLE
Update IEF for Vet Center services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4935]
## User Story or Problem Statement

As a manager of Vet Center facility health services, 
- i want to be able to create revisions on each edit when editing services via the main Vet Center form, so that i can keep a history of my changes.
- i want to be able set the Section so that i can edit it later.

## Acceptance Criteria
- [x] Form should loook like this, for now 

<img width="1223" alt="Edit_Vet_Center_Escanaba_Vet_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113629352-54cb2f80-9634-11eb-87ae-0b16dda7f763.png">

  

## Implementation steps
- [x] Enable IEF form mode for Facility health service 
  - [x] "Enable" Owner field by moving it out of the Details sidebar, and hide needless fields

<img width="1155" alt="Manage_form_display___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113629582-9f4cac00-9634-11eb-814b-91753c3fc7d0.png">

- [x] Change the form mode on Vet Center for the services field to use the IEF form
  - [x] Enable revisions within IEF on Vet Center Services field.

<img width="1342" alt="Manage_form_display___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/113629516-83e1a100-9634-11eb-8a74-123be4d2afd1.png">
