### ISSUE TITLE
Replace "Audience (tags)" open-ended field with a reference to two existing audience vocabularies

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4989]
## User Story or Problem Statement

Usability testing with editors showed that existing user-generated audience vocabulary was confusing and difficult. 

Decision was to replace this with a reference to two other existing controlled Audience vocabularies.

## Acceptance Criteria

- [ ] `field_clp_audience` is updated
  - [ ] Allows "Audience - Beneficiaries" or "Audience - Non-beneficiaries" (see screenshot below for config)
  - [ ] Widget is updated to use a Select list instead of autcomplete
- [ ] Audience (tags) vocabulary is removed, along with all of its content

## Implementation steps

at /admin/structure/types/manage/campaign_landing_page/fields/node.campaign_landing_page.field_clp_audience :

![Add_between_1_and_3_audiences_settings_for_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114133163-9b8a8500-98d3-11eb-95d4-fff38001586a.png)

at admin/structure/types/manage/campaign_landing_page/form-display

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114133293-d2f93180-98d3-11eb-811b-aff7c2eceac7.png)

**Comment by johnhashva** [comment]
@kevwalsh I'd like to include the option to make the "This Page is For" audience component optional in Panel 1.  Seems to me the Share links would just move up from there.   Does this increase scope by a significant amount?

**Comment by kevwalsh** [comment]
@johnhashva just saw your last comment today, sorry i missed it!

Making the field optional is trivial. 

Are you also suggesting the field get moved from the second panel to the first panel?

**Comment by johnhashva** [comment]
@kevwalsh Nope.  What I was referring to (and this may be a front end thing) -- if the Editor elects not to show __This Page is For_ component, the Share component -- if effect -- replaces it by moving up -- correct?  Would that require any FE work to make that if/then work elegantly?

<img width="608" alt="CLP-Audiences_Share" src="https://user-images.githubusercontent.com/63107147/116092995-4d67d680-a674-11eb-8066-db5a35d713b1.png">

Question #2: Do you know if there are any plans to add to the Audience taxonomy (adding @brianalloyd in case he knows), which I am putting here for posterity.

<img width="311" alt="Audience Tags" src="https://user-images.githubusercontent.com/63107147/116093585-cebf6900-a674-11eb-9e4b-e7256cd08434.png">

<img width="208" alt="Audience Tags - Non" src="https://user-images.githubusercontent.com/63107147/116093597-d252f000-a674-11eb-9c12-56d3fbce794f.png">

**Comment by kevwalsh** [comment]
@johnhashva 

> 1. What I was referring to (and this may be a front end thing) -- if the Editor elects not to show _This Page is For component, the Share component -- in effect -- replaces it by moving up -- correct? Would that require any FE work to make that if/then work elegantly?

Looks like the FE doesn't fail gracefully here, and expects content.  
<img width="1175" alt="Veteran_Trust_in_VA___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/116343307-2d3e3180-a7b2-11eb-954c-fa2e555370e3.png">


> 2. Do you know if there are any plans to add to the Audience taxonomy (adding @brianalloyd in case he knows), which I am putting here for posterity.

I am not aware of any plans. The governance of this taxonomy (or the rest of the R&S product, which triggered the creation of this taxonomy) has not been fully documented. 

> 3. Lastly - can I add a few more Audience tags -- e.g. Lawmakers (or member of Congress) -- or does that go through some sort of approval process with the Content team?

The "Audience (tags)" vocabulary will be deprecated, leaving only the two other vocabularies (Beneficiaries and non-beneficiaries) above. Content team seems like a good place to ask!

**Comment by johnhashva** [comment]
@brianalloyd looks we will need to add a ticket to ensure the This Page is For component fails gracefully in event the optional component is de-selected by the CLP editor via CMS.  @kevwalsh we would want to make This Page is For active by default and the editor needs to actively disable it.

**Comment by brianalloyd** [comment]
@johnhashva I'll include this into our "Conditional Rendering" ticket based on a discussion with Kelson this AM and reference this ticket as supporting ticket.
