### ISSUE TITLE
Improve VHA health service taxonomy form to accommodate both VAMC and Vet Center

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#4993]
## User Story or Problem Statement

The VHA health service taxon form now supports two "sets" of data, one for VAMC (the "default" VHA values) and one for VAMC. 

![Edit_term___VA_gov_CMS](https://user-images.githubusercontent.com/643678/114183878-24c0ac80-9912-11eb-9593-a4843b541365.png)

## Acceptance Criteria
- [x] Create a VAMC fieldgroup in the form and add 4 fields indicated in the screenshot
- [x] VAMC fieldgroup should have the help text: "These values act as the default values for VHA health services, but can be overridden for Vet Centers, below."
- [x] VAMC and Vet Center fieldgroups should follow the same order of fields (use the order from Vet Center)
- [x] Both VAMC and Vet Center fieldgroups should be collapsible, but open by default
- [ ] Get design review

## Implementation steps
<optional>
