### ISSUE TITLE
AP Research study: Editorial experience for publishing

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#4995]
## User story
As a CMS Editor, I would like to publish content to VA.gov as quickly and easily as possible so that I can most effectively deliver content to Veterans and the public.

## Business goal
Identify CMS editor objectives and pain points when publishing content in order to understand the implications of a technical solution for AP.

## Research objectives
- Gather user expectations for publishing times without leading questions
- Understand publishing requirements for various users and products 
   - [ ] TBD number of users from each product 
- Identify pain points in the user publishing workflow
- Understand how proofing page, preview and scheduling features impact/augment users' publishing workflow.

## ACs
- [ ] 2-3 study participants from each user segment recruited for the study and scheduled.
- [ ] Conversation guide is prepared
- [ ] ((2-3) * (number of user segments)) users interviewed
- [ ] Study data is synthesized
- [ ] Research readout + PO review
