### ISSUE TITLE
Understand and articulate the limitations of current helpdesk infrastructure

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5034]
## Description
With the CMS user base growing close to 1,000 by the end of 2021, we want to understand when the tipping point is where our current helpdesk infrastructure and staff would need to be increased and by how much.

## Acceptance Criteria
- [ ] OCTO-DE has a clear understanding of the limitations of our current helpdesk infrastructure and staff
- [ ] OCTO-DE has a clear timeline as to when we project to hit limitations

## Possible Tasks / Stories
- [ ] Communicate limitations in reference to number of users
- [ ] Define incoming users by product, persona, potential LOE on support needed
- [ ] Trend current support tickets and extrapolate out based on projections through December, 2021
