### ISSUE TITLE
Drupal content dependency graph management PoC

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5037]
## Description

In order to incrementally update the published content on www.va.gov, some system needs to know what content should be refreshed when a specific piece of content is published in Drupal. This might take one of several forms:

1. a system that queries Drupal's caching system to discover what other node, view and menu cache items have been invalidated and maps this data to content paths to rebuild (note: with the centralized content model in place, this might be the only practical option)
2. a system that records node UUID -> path mappings and dependencies during the full content build process and can then map from invalidated UUIDs to content paths to rebuild

## Acceptance Criteria
The work done for this issue should allow us to determine the practicality of obtaining these data and an order of magnitude estimate for LoE. It's possible that this cannot be determined solely within Drupal, as the front end build may assemble pages from multiple Drupal nodes in some instances.

- [x] Create documentation on how to determine which content types do and don't map to pages on the front end is added to this issue
- [x] Discover and document how sidebar menus are built, and document under what conditions a rebuild should be triggered for all pages referenced from a given sidebar menu
- [x] Discover and document whether related entities may be retrieved from Drupal's cache tags system

## Follow up Tasks
- [ ] Finalize "Is node a page" logic: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5068
- [ ] Source of truth for non-front-end pages has lost its data: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3954
- [ ] Create FrontEndPage service which holds all the business logic to know if the current node represents a page on the front end. (#5069)
- [ ] Update preview button code at `va_gov_backend_preprocess_page` and `EntityMetaDisplay` to use new service. (#5070)
- [ ] Create API endpoint to expose list of bundles and the ability to check if a `nid` represents a page.
- [ ] Update front end to pull bundles from CMS instead of hard coding.

**Comment by acrollet** [comment]
Notes: @indytechcook says that drupal's caching system may provide an event when cache keys are invalidated.

The menu system needs to be taken into account.

Tome sync may have additional helper code that we can pull in.

CER (Corresponding Entity References) will need to be taken into account.

**Comment by indytechcook** [comment]
Looking at possible contrib modules which provide any assistance: 

**https://www.drupal.org/project/entity_dependency_visualizer**

* the logic is buried in https://git.drupalcode.org/project/entity_dependency_visualizer/-/blob/8.x-1.x/src/Controller/EntityDependencies.php#L127.
* Limitations for what support references and entries are supported

```
  /**
   * @var array List of supported entity reference types.
   */
  protected $supported_entity_reference_types = [
    'entity_reference',
    'entity_reference_revisions',
  ];

  /**
   * @var array List of supported entity types.
   */
  protected $supported_entity_types = [
    'user',
    'node',
    'paragraph',
    'taxonomy_term',
  ];
```

**https://www.drupal.org/project/tome**

We can pull out the sync logic:  https://git.drupalcode.org/project/tome/-/blob/8.x-1.x/modules/tome_sync/src/ContentIndexerTrait.php#L27

### Other random questions
* Is there a way to use `ConfigDependencyManager`
*

**Comment by indytechcook** [comment]
Conversation with @swirtSJW confirms what I have above:

![image](https://user-images.githubusercontent.com/121603/115297880-b7d7be80-a12a-11eb-9c3c-901712296e27.png)

**Comment by indytechcook** [comment]
> Discover and document whether related entities may be retrieved from Drupal's cache tags system

I spent some time working through the Cache API and here are my findings in relation to using them as a Dependency mgmt.

Verdict: Using the Drupal Cache API is impracticable to find dependcies.

There currently isn't an existing API to query cache tags and get the related items.  There is a path to build a new contrib module that could provide this service but it's mostly like a 5 point story as there is complication using different query backend (database vs memecache).

The current cache system uses a checksum pattern to invalidate tags.  This means it stores which tags are invalidated and when a cache item is loaded, it checked if it contains a tag that has been invlidated.  It's quite complex and very fast but it means there isn't an easy way to query which cache items contain which tags.

Even if we could query the cache item by cache tags, the list would be incomplete because there isn't always a cache item for every entity

**Comment by indytechcook** [comment]
_Work still in progress_

> Discover and document how sidebar menus are built, and document under what conditions a rebuild should be triggered for all pages referenced from a given sidebar menu

The "mega menu" is built from the pages.json data extracted from Drupal.   The data which drives the menu is extracted from the large pages.json here: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/menus.js#L267

* Menu links and hierarchy are pulled from GraphQL: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/navigation-fragments/menuLinks.nav.graphql.js#L9

_Work still in progress_

**Comment by indytechcook** [comment]
Assets created:

* https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/dependency_graph
* https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/dependency_graph
* https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/accelerated_publishing/dependency_graph
