### ISSUE TITLE
Export users from CMS by product / section / role or other grouping

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5040]
## User Story or Problem Statement

As a user admin, product manager, product owner, or other stakeholder, i can export a filtered list of users by CSV, like the CSV export on /vha-health-services

#3263 will also add a lot of value to this, but can be done independently. 

## Assumption

CSV export functionality respects filters added by user.

## Acceptance Criteria
- [ ] Export to CSV functionality has been added to /admin/people, that shares its filters
- [ ] Button label TBD with @rachel-kauff 

## Implementation steps
- [ ] update view config
