### ISSUE TITLE
Sprint 31 priorities for Product Support Team

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5042]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

## Context

1. This remains the Product support team but in Sprint 31 we're going to start feeling the shift in priority towards Accelerated publishing 
2. This will take product support team engineer and design energy from Product development. Ethan will be jumping into the discovery effort net sprint. 
3. This scrum team has taken on some critical Core initiatives and responsibilities, specifically help desk, CMS design system, and user admin, and all of which dilutes our focus a bit. Kaise in particular will start 
4. We are also going to be needed to contribute to the Drupal 9 upgrade 

What will not change

1. Customer service and change management initiatives (help desk, training, etc)
2. Ongoing support for Product epics already in progress (Vet Center, VAMC Policies Page, CLP)
3. Maintenance and Tier 2 support for products (Tier 2) 

## ~#1950 Drupal 9 upgrade~

~- [ ] #4944 Mob testing session~ - deprioritized by Core team

## #4019 User administration service  

- [x] #4997 Design Improved Role delegation UI 
- [x] #5088 Improve Section UI in PR environment and get feedback

## Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### CLP

#4989 Replace "Audience (tags)" open-ended field with a reference to two existing audience vocabularies 🥅 

Not in sprint: CLP request form

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

#### #4374 Local editor experience

- [x] Bug fixes to forms and governance, if any. 
- [ ] #5110 Vet Center dashboard edit links are missing the destination parameter 
- [x] #5089 Include current page in breadcrumbs on all section taxonomy pages

#### #4400 Change management for local editors 👥  

- [x] #5133  Finalize Vet Center training materials and user guides 

#### #4373 National editor experience

Centralized content editorial experience has been deprioritized.

### VAMC System

- [x] #5134 Launch 8-10 VAMCs @swirtSJW  @kevwalsh

Policies Page 
- [x] #5099 Tools to analyze top task page revision histories
- [x] #5053 Collaborate with VAMC upgrade team on VAMC System Policies page runbook and launch one Policies page 🥅  
  - [x] Write Release note that could be sent by VHA Digital Comms about this change, including link to training. 

## #2427 Epic: Enforce IA design for VAMC editors**

- [ ] Finish implementation #4988 / PR #4894 🥅   
- [ ] #5135 Change management for new IA / menu governance 
- [ ] #5132 Collaborate with VAMC upgrade team, Facilities team on Pittsburgh IA changes 

Stretch
- [ ] Document how to update URLs for content admins for VAMC product 👥  
- [ ] How to make the CMS force the correct URLs for VAMCs for new pages 👥  
  - [ ] #4773 Update pathauto for Detail pages to use [VAMC system homepage]/[menu-hierarchy]/[h1]
- [ ] Programatically re-align dual-state sites to the correct IA 👥  

## Help desk 

- [ ] Broken link analysis - Editor vs CMS vs Front end template vs Front end build issues.
- [ ] VAMC help request analysis

## Lighthouse collaboration

[Link to agenda](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/lighthouse-cms-weekly-sync.md)

- [x] If a Vet Center or VAMC staff finds an issue with the data coming through Facilities API, what should they do? Multiple data sets... Access to care, Mental health care contacts, VAST.
