### ISSUE TITLE
helpdesk planning for VAMC Upgrade transitions

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5073]
## Description
VAMC Upgrade Team will be completing VAMC website transitions from Teamsite to Drupal end of calendar year 2021 and shifting focus away from upgrade support. As a helpdesk team member, I need to know how that transition will affect helpdesk processes, editor support, broken links, etc.

## Acceptance Criteria
- [ ] Identify existing processes and workflows that involve VAMC Upgrade team
- [ ] Analyze ticket data that involve VAMC Upgrade Team
- [ ] Who will we talk to when they are not here?
- [ ] We need to create a tracking system (Google Sheets?) to track all of the recent Stan/Lisa escalations, why we escalated it, what we needed from them, and what the outcome was.
- [ ] Should we plan direct trainings with Stan and Lisa? TBD.

**Comment by xiongjaneg** [comment]
Will want to revisit current process in Q4 as VAMC Upgrade Team transitions

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5073?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
@stefaniefgray @chriscraiga6 is this work being tracked elsewhere? Maybe we can close it as done?

**Comment by chriscraiga6** [comment]
@kevwalsh Yes, this can be closed. We completed this work with #6807 and #6808
