### ISSUE TITLE
[CAPI] FE Discovery using React component

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5104]
## Background

Currently, the technical architecture that supports CMS content being pushed to VA.gov causes a publishing delay. Ideally, after a user navigates to a page on the website, the user lands on the React application, which then fetches data from the CMS and uses the response data to render the page. The JSON response between Drupal and the React App will flow through an API Gateway. The API Gateway will provide a single entry point for any React applications and external systems integrating with the CMS. We are exploring using either Lighthouse or AWS Gateway as the API Gateway to expose Drupal to the internet.

### User Story or Problem Statement

As a CMS editor, I wish to be able to publish changes to a single page within the shortest possible time-frame.

As a CMS engineer, I want CMS content to be publicly available, so that I can create client-side applications that can access the latest CMS data.

### Acceptance Criteria

- [ ] Followup tickets have been completed for the following items:
   - Solution overview & description documentation
   - Architectural diagram
   - Relevant PoCs
   - Estimate of LoE
- [ ] The Content API can be reached from the open internet and data retrieved from it
- [ ] The Content API gateway is approved by Platform governance, and this approval is documented
- [ ] The Content API schema changes are not hindered by processes of the team which manages the gateway

### Implementation

https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/accelerated_publishing/proof-of-concepts-summaries/RealTimeCMS.md

**Comment by timcosgrove** [comment]
This epic was written from the perspective of a public content API, and is not relevant to the current direction. Tickets that were part of this epic have been moved to other epics or else closed. Closing.
