### ISSUE TITLE
Some final touches to Vet Center dashboard theming

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5115]
## Acceptance Criteria
- [ ] List of cards should be in one group so that they can be responsive (3x2, 2x3, 1x6)
- [ ] Grey/White backgrounds on first four cards, white-only background on last two cards, to distinguish their type. 
- [ ] Alignment of h3s on cards 

## Implementation steps
- Layout builder config change to cards
- HTML & CSS

**Comment by msbtterswrth** [comment]
@kevwalsh i think we could close this as duplicative of the more recent dashboard work we've done?

**Comment by EWashb** [comment]
This is done/not currently within scope
