### ISSUE TITLE
Address root causes of consistent High RDS CPU Usage

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5183]
### Problem Statement

<img width="771" alt="Screen Shot 2021-04-29 at 11 18 24 AM" src="https://user-images.githubusercontent.com/101649/116591913-a0dc5d80-a8dc-11eb-944b-b09df40c3eec.png">

CPU load on RDS is consistently unacceptably high during working hours, leading to the following crucial issues:

- Occasional brief CMS downtime
- Very long total GraphQL query times (10+ minutes, when a fully cached query can complete in 10s of seconds or less)
- Negative impacts on CMS Editors (slow page loads)

### Affected users and stakeholders

- All CMS Editors
- CMS devops team
- `vets-website` developers

### Hypothesis

We believe that addressing the epic's issues in this order will efficiently resolve this problem and meet the epic's ACs:

1. #4570 ~~(Prevent `vets-website` development builds from querying prod, resolved)~~
2. #5207 ~~(Use tugboat for all non-production content builds)~~
4. #5184 (Rate limit requests to the GraphQL endpoint)
2. #5177 (Allow temporarily disabling the automatic content build trigger)
5. #5131 (Fix inefficient path alias database queries. Improving cache invalidation in #5177 may substantially mitigate this issue)

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
- GraphQL requests are the main cause of high RDS CPU usage

## Acceptance Criteria
- [ ] Proposed: CMS team is alerted when RDS CPU usage remains above 75% for 10 minutes
- [ ] This alert has not been triggered for a 2 week period

**Comment by indytechcook** [comment]
@acrollet do we want to add an issue for updating the front end Review servers to use tugboat?

**Comment by acrollet** [comment]
> @acrollet do we want to add an issue for updating the front end Review servers to use tugboat?

Added #5263, thanks @indytechcook!
