### ISSUE TITLE
Apply external data form treatment to VAMC facility form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5185]
## User Story or Problem Statement

Old design pattern

![Screenshot_2021-04-29__12_52_PM](https://user-images.githubusercontent.com/643678/116588633-c7ed5c00-a8e9-11eb-9134-e6e30529285c.png)

New design pattern

![Screenshot_2021-04-29__12_51_PM](https://user-images.githubusercontent.com/643678/116588566-b60bb900-a8e9-11eb-8770-779147865816.png)

## Acceptance Criteria
- [ ] New design patterns have been applied
- [ ] Full redesign of this area including Field labels and help text, including Mobile checkbox

## Not included 

Move to a separate issue: Tooltips go to the right by default, but remain 
- content model refactor to field_office_hours
- 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.
