### ISSUE TITLE
Scaffolding for 18 VAMCs in VISN 10 and VISN 15 (Menus etc)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5221]
## User Story or Problem Statement

As a member of VAMC upgrade team, i need to add menu items for 11 VAMC Systems in VISN 10. 

## Acceptance Criteria
- [ ] Each of the 11 VAMC systems in VISN 10 have "scaffolding"
  - [ ] VA Ann Arbor health care
  - [ ] VA Central Ohio health care
  - [ ] VA Chillicothe health care
  - [ ] VA Cincinnati health care
  - [ ] VA Dayton health care
  - [ ] VA Northeast Ohio health care
  - [ ] VA Battle Creek health care
  - [ ] VA Detroit health care 
  - [ ] VA Indiana health care 
  - [ ] VA Northern Indiana health care
  - [ ] VA Saginaw health care
- [ ] Each of the following VISN 15 
  - [ ] VA Columbia Missouri health care
  - [ ] VA Eastern Kansas health care
  - [ ] VA Kansas City health care
  - [ ] VA Marion health care
  - [ ] VA Poplar Bluff health care
  - [ ] VA St Louis health care
  - [ ] VA Wichita health care
- [x] Menus are eligible for various VAMC content types.
- [ ] `menuByName` is updated vets-website 
- [x] Menu entities have descriptions that include URL and VISN (following existing pattern)

## Implementation steps
See https://docs.google.com/document/d/1fz-m_4Eo4Ib7g4s_3pk7Hz4N3uaNnCD1lAppp6KDMrk/edit?usp=drive_web&ouid=114216740278804672394

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
