### ISSUE TITLE
Sprint 32 Product team priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5222]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

## Core team collaboration

#1950 Drupal 9 upgrade
- [x] #4944 Mob testing session (pending prioritization by Core team)

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

#### VAMC upgrade team

- [ ] #5273 Migrate Facility services for VISN 7 and 8 (moved to 33)
- [x] #5274 VAMC Launch Support
- [x] #5221 Scaffolding for VISN 10 and 15 menus. 🥅

Policies page

- [ ] #5238 VAMC Policies page video 

### #2427 Epic: Enforce IA design for VAMC editors

- [ ] #4988 Implement VAMC menu governance  🥅 (updated to the runbook from #2427)
- [x] #5135 Change management for new IA / menu governance 

Stretch
- [ ] #5132 Collaborate with VAMC upgrade team, Facilities team on Pittsburgh IA changes 
- [ ] #4773 Update pathauto for Detail pages to use [VAMC system homepage]/[menu-hierarchy]/[h1]
- [ ] Programatically re-align dual-state sites to the correct IA 👥  

#### #4374 Local editor experience

- [x] #5110 Vet Center dashboard edit links are missing the destination parameter 
- [ ] Basic clean up of proofing pages (new fields added, etc)

#### #4400 Change management for local editors 👥  

- [x] #4402 Deliver local training to national Vet Center staff   🥅
- [ ] Stretch: deliver local editor training to Vet Center staff (issue coming) (33)
- [ ] #4837 Post Vet Center training videos on CMS help center  (33)

## Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### CLP

- [x] #2383 Set up URL generation for campaign landing page (tiny but not urgent, can be handled manually) 

## #4019 User administration service  

- [x] #5265 Research plan for user admin stakeholder interview 
- [ ] #5264 Granular documentation of current state user admin process for existing products 
- [ ] Refine Role Delegation user stories 

## Governance UX

- [x] #5250 Improve Section settings on all content forms and views
- [x] #5251 CMS Announcement and user guides about new "Sections" and "Section Settings" 

## Help desk 
- [x] Broken link analysis - Editor vs CMS vs Front end template vs Front end build issues.
- [ ] #5004 VAMC help request analysis
- [x] #5282 Replace "contact help desk" with link to help center for non-logged in users 🥅
