### ISSUE TITLE
PROD Previews Slow and Timing Out

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5228]
@ElijahLynn commented on [Wed Feb 10 2021](https://github.com/department-of-veterans-affairs/va.gov-team/issues/19787)

The CMS team received a report on Jan. 28th from Lisa Trombley on VAMC Upgrade team that previews were very slow and sometimes timing out. 

To temporarily unblock the VAMC Upgrade team, @tskinn increased the timeout on the PROD Preview server from 60 to 300 seconds. 

I was able to reproduce consistently in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4151 and the GQL cache is getting invalidated on any node save, not just the node that is being requested by the query. @ncksllvn said he may have an idea on how to reasonably improve this slowness. 

Related internal threads:
* https://dsva.slack.com/archives/CDHBKAL9W/p1611856292037400 (support request on Jan 28th)
* https://dsva.slack.com/archives/CBU0KDSB1/p1611857007368600 (increased ELB timeout for temporary unblocking)
* https://dsva.slack.com/archives/C01512KN35G/p1612984982200600 (technical discussion with @ncksllvn and I)
* https://dsva.slack.com/archives/C52CL1PKQ/p1612986446391700 (triage to this ticket)

## Tasks
- [ ] Improve preview speed (@ncksllvn)
- [ ] Revert ELB timeout (@tskinn)

## Acceptance Criteria
- [ ] Preview server has been updated to use the split GraphQL queries in [content-build](https://github.com/department-of-veterans-affairs/content-build)
- [ ] Follow-on tickets have been created for any remaining performance issues

**Comment by acrollet** [comment]
@ncksllvn can you add an estimate to this issue when you have a chance? thanks!

**Comment by acrollet** [comment]
@jefflbrauer FYSA we decided with @mchelen to pull this into our sprint for two reasons:

1. It's an active bug that's impacting the editor experience
2. It will reduce the uncertainty for #5098

**Comment by mchelen-gov** [comment]
i'm ok with swapping out https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5080 for this if we can clarify the AC and size it
