### ISSUE TITLE
Improve Section Settings on all content forms

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5250]
### Background

In #5088 we tested a new UI for the `field_administration` on all content types, using the PR environment for #5151.  

Insights from that testing were incorporated into this iteration on what is currently the "Governance" fieldgroup on  all content types. 

![▶_Page_1_-_Sections_menu](https://user-images.githubusercontent.com/643678/117306067-5d8a6d80-ae4d-11eb-888f-f79f1289c195.png)

## Acceptance Criteria
- [ ] New field label, field help text and fieldgroup label has been applied across all bundles
- [ ] Column header "Owner" has been replaced with "Section" in various views (already done in #5151)
- [ ] Merged alongside an [announcement of this change](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5251). 

## Implementation steps
- [ ] Update config

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
@rachel-kauff I'm going with "Section settings" sentence casing, to match up with "Menu settings", which is what's happening underneath the CSS `text-transform: uppercase;` on these field group labels.

**Comment by rachel-kauff** [comment]
Announcement + associated help guide ready to go out.
