### ISSUE TITLE
Replace "contact help desk" with link to help center for non-logged in users

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5282]
## User Story or Problem Statement

As a CMS user, i can easily access self service documentation to review, when not logged in. 

No current way to easily access the Help Center from the log in page without knowing the url.

![Screenshot_2021-05-10__11_49_AM](https://user-images.githubusercontent.com/643678/117687632-fab71000-b185-11eb-80c4-df1f459457c9.png)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
- [ ] Replace existing button with a different label and destination = CMS Help Center 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
