### ISSUE TITLE
Reduce nbsp; characters in rich text editor

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5291]
## User Story or Problem Statement

Rich text fields contain a lot of `nbsp;`. 

We need to understand how they are being generated (copy/paste from a different program?)

## Acceptance Criteria
- [ ] We have identified the cause of this
- [ ] We have taken some measure to reduce their rate of occurence

## Implementation steps
- [ ] Create a view of field_wysiwyg with various content attributes that will help us find some patterns of where this is occurring (including editor, content type, etc)
- [ ] TBD 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
