### ISSUE TITLE
Sections select lists can be misleading in certain situations

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5297]
## User Story or Problem Statement

In certain situations (possibly very rare, definitely edge-casey) an editor may see the hierarchy represented in a misleading way, where a nibling may appear like a child. This occurs where a user who has access to one section, and its parent's siblings section. 

![Create_Event___VA_gov_CMS](https://user-images.githubusercontent.com/643678/117860160-f9591680-b25d-11eb-906c-92ab96d3c186.png)

A solution should be researched/designed, but could be similar to the solution used in Menu settings, where ineligible parents appear as disabled. 

## How to reproduce

1. Edit the workbench settings for any user who only has access to one VAMC
2. Add a VISN that is not the parent of their VAMC, with a lower VISN number than the the parent of their VAMC.
3. Log in as that user, go to /node/add/event note that the their VAMC appears inside the wrong VISN in the Sections menu. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
