### ISSUE TITLE
Allow only Vet Center services on Vet Center service forms, show only VAMC services in VAMC forms.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5301]
## User Story or Problem Statement

As a Vet Center service editor, i only want to see options for adding Vet Center eligible services, not VAMC or other services.

As a VAMC service editor, i only want to see options for adding VAMC eligible services, not Vet Center or other services.

## Acceptance Criteria
- [x] On the /node/add/vet_center_facility_health_service form, the only services available are those where "Vet Center Type of care" has a value.
- [x] On /node/add/health_care_local_health_service, the only services available are those where "VAMC Type of care" has a value.

## Implementation steps
Update health_care_service_names_and_descriptions view. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
