### ISSUE TITLE
Better support for portrait images that have orientation set only in EXIF

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5305]
## User Story or Problem Statement

As an editor, i want to add a photo to the media library where the EXIF orientation "conflicts" with the image size values, so that it can show up with the right orientation.  

[slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1620751238358600)

Possible approaches

1. `exif_orientation` module
2. Better help text
3. Something else.

## Acceptance Criteria
- [ ] Viable path for uploading photos where correct orientation is set only with EXIF metadata.

## Implementation steps
TBD

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by acrollet** [comment]
Just noting that I've reviewed the `exif_orientation` module and the code looks reasonable to me and shouldn't raise performance concerns. cc @indytechcook if you'd like to give it a glance as well.

**Comment by kevwalsh** [comment]
Unfortunately, it doesn't seem to "just work" in our application.


![Add_Image___VA_gov_CMS](https://user-images.githubusercontent.com/643678/118019344-e52d1c00-b326-11eb-8c05-985e151777e5.png)


I did a quick read of the [issue queue](https://www.drupal.org/project/issues/exif_orientation?status=All&categories=1), nothing jumped out at me.

**Comment by indytechcook** [comment]
No immediate concern though a few thoughts.

The only possible concern would be with bulk updating since it [ possible to touch every file](https://git.drupalcode.org/project/exif_orientation/-/blob/8.x-1.x/exif_orientation.module#L58) which could to lead to IO issues.  The file IO would become an issue more when we move back to EFS.  We have seen performance issues when dealing with lots of small files. 

This module uses a custom form_alter to add a upload validator and uses `hook_file_presave` to perform the rotation.  This might actually do the operation twice but I'm not sure.   Custom the custom validation instead of `hook_file_validate` also goes around the `File::validate()` method.  Other modules (life dropzone;f use this method to make sure the file can be upload.  So you actually won't see the changes until after the File is saved.

**Comment by kevwalsh** [comment]
This came up in https://va-gov.atlassian.net/browse/VAHELP-956
