### ISSUE TITLE
Adjust GraphQL fetched to match unfetched

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5312]
## User Story or Problem Statement

As a front end consumer of graphQL data I need what appears in fetched data to be as GraphQL-like as possible so we do not need to transform in on the Front End.

[Upstream issue on drupal.org](https://www.drupal.org/project/entity_field_fetch/issues/3213821)

Relevant discussions:
https://dsva.slack.com/archives/C0FQSS30V/p1620849612431600
https://dsva.slack.com/archives/C0FQSS30V/p1620858691452200

## Acceptance Criteria
- [x] field names are converted from drupal snake case to GraphQL camelCase.
![image](https://user-images.githubusercontent.com/5752113/118130926-e5cbbe00-b3cb-11eb-915e-6f58ed8291a5.png)
- [x] type is converted to entityType
![image](https://user-images.githubusercontent.com/5752113/118130830-cc2a7680-b3cb-11eb-8bb9-ab54ec79ee05.png)
- [x] bundle is converted to entityBundle
![image](https://user-images.githubusercontent.com/5752113/118130714-af8e3e80-b3cb-11eb-98c3-0c5d001c0ca3.png)

- [x] entities adjoined to `entity:`
![image](https://user-images.githubusercontent.com/5752113/118131028-03008c80-b3cc-11eb-9fa1-71f87dec0579.png)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
I just merged this upstream https://www.drupal.org/project/entity_field_fetch/issues/3213821 and created a release alpha8.
I am waiting for dependabot to bring in the PR and then I can mark it as do not merge.

**Comment by swirtSJW** [comment]
The PR is created and on-hold until the Facilities front end team gets the checks in place to have it work both ways.  Once that is in place we should get passing tests on this PR and can merge it.

**Comment by swirtSJW** [comment]
This is blocked by https://github.com/department-of-veterans-affairs/va.gov-team/issues/24700
