### ISSUE TITLE
Double CMS RDS instance size

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5318]
## Description

RDS CPU usage is consistently hitting close to 100% during content deploys.

## Acceptance Criteria
- [x] Existing instance CPU capacity is doubled (from `db.m5.2xlarge` to `db.m5.4xlarge`)
- [x] Grafana query/graph is updated (if applicable) and checked for accuracy

## Tasks
- [x] Test procedure on `cms-test` and add runbook to this issue 
- [x] Perform deployment during daily deploy downtime window
- [x] Confirm reduced CPU usage on Grafana
- [x] Add Grafana Annotation marker

## Runbook
- [x] Pre-deploy, adjust site alert that was set by the auto-deploy job to notify users there will be 30 minutes of downtime today
- [x] Pre-deploy, disable http://jenkins.vfs.va.gov/job/cms/job/deploy-live-prod/ (this will cause the deploy job to fail at the end when it tries to trigger this job, but that is okay)
- [x] During deploy, just after the new instance comes up, `mv settings.deploy.inactive.php settings.deploy.active.php` to put up a static "system update in progress" page
- [x] Wait until the [deploy job](http://jenkins.vfs.va.gov/job/deploys/job/cms-vagov-prod/) is done so database updates have been applied, config imported.
- [x] Go to RDS, modify `dsva-cms-prod-db`, change DB instance class to `db.m5.4xlarge, click "Continue", then "Apply immediately" radio button at bottom, then finally submit with "Modify DB Instance"
- [x] Wait 10-15 minutes for change to take effect
- [x] mv settings.deploy.active.php settings.deploy.inactive.php
- [x] Re-enable http://jenkins.vfs.va.gov/job/cms/job/deploy-live-prod/ and run this job
- [x] Ensure PR is created
- [x] From devops repo, `cd terraform/environments/dsva-vagov-prod` 
- [x] `terraform apply` # this just queues the change and the only reason we are running, we might consider running it afterwards as we just want to make sure the state matches.

**Comment by ElijahLynn** [comment]
Going to up the instance size now. The last spike we had to 100% was on May 13, 2021. Max since then has been 53%. I know we are planning for more capacity though so let's get this done. 

![image](https://user-images.githubusercontent.com/1504756/119583897-6e5b3e80-bd7c-11eb-9041-4904efe8da07.png)

**Comment by ElijahLynn** [comment]
Terraform applies the changes in under a minute, but they aren't actually applied and are queued for the maintenance window. And a reboot doesn't work to apply the change. So, we have to "modify" the instance, then manually select the new size, then save changes, then "apply immediately". OR we can just wait until the maintenance window hits which currently is 10-10:30 GMT/UTC / 6-6:30pm ET, which is too early. I think the manual steps are fine, Terraform stays in sync this way. 

![image](https://user-images.githubusercontent.com/1504756/119584847-5be20480-bd7e-11eb-851d-ce4ce680d3e8.png)

![image](https://user-images.githubusercontent.com/1504756/119585291-43261e80-bd7f-11eb-944d-47f990445ee9.png)

**Comment by ElijahLynn** [comment]
Upsize complete on PROD, here is a Grafana chart showing the decrease in CPU utilization: 
![image](https://user-images.githubusercontent.com/1504756/119907986-6929fb00-bf06-11eb-9315-a7173df741b5.png)

**Comment by ElijahLynn** [comment]
All instances have been upsized, lastly, I need to merge PR and update TF state here > https://github.com/department-of-veterans-affairs/terraform-aws-vsp-cms/pull/23.
