### ISSUE TITLE
Improve Leadership team field widget on Leadership nodes

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5335]
## User Story or Problem Statement

When editing a Leadership List, and selecting Staff Profiles to appear there, the existing multivalue autcomplete widget has a number of issues

- Firehose of content to choose from (all staff profiles are eligible)
- ~Removing a value and resaving leads to a form validation error~
- It's impossible to know if the content is published, draft, or archived from the current widget

![image](https://user-images.githubusercontent.com/643678/118305469-02442500-b4b6-11eb-9214-ab4df9b1372d.png)

See also defects documented in #5331 (Deleting a staff profile does not remove the empty slot in field_leadership on listing pages) and #5334 (closed)

## Acceptance Criteria
- [ ] PEOs can find staff profiles to link to more easily, including whether Staff profiles are published, draft, or archived. (Ideally, archived should not appear.)

## Implementation steps
TBD

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
@jilladams @BerniXiongA6 I'm not sure where this belongs, but we don't have a team label on it.

**Comment by Agile6MSkinner** [comment]
This is the last ticket standing on an abandoned epic. Going to close it and the epic since it's not seen action in a long time.
