### ISSUE TITLE
Refactor metags on VAMC product to pull directly from node titles (h1s)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5339]
## User Story or Problem Statement

As a PAO, i don't want to have to specify metatags manually, they should be auto generated

## Acceptance Criteria
- [ ] For each VAMC content type (`Detail Page, Event, Event listing, VAMC system operating status, VAMC system health service, VAMC system banner alert with situation updates, VAMC system, VAMC facility health service, Story listing, Story, Staff profile, News releases listing, News release, Locations listing, Leadership listing, Health services listing, VAMC facility`)
  - [ ] "Meta title tag" (`field_meta_title`) has been removed, if it exists
  - [ ] field_meta_tags settings has been update to use the following pattern [from the style guide](https://design.va.gov/content-style-guide/seo#meta-properties): `H1 Page Title | VAMC Plain Language System Name | Veterans Affairs` eg `[node:title] | [node:field_office] | Veterans Affairs`.   Drupal will not have the Initial Casing, that will be applied in the FE. 
  - [ ] Requires design review

## Implementation steps
- [ ] Update config
- [ ] This can be merged before FE has transformed the metatag into initial case (issue forthcoming)

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
Facilities team work for adding capitalization filter - https://github.com/department-of-veterans-affairs/va.gov-team/issues/24796
