### ISSUE TITLE
CMS Product Support Team Sprint 33 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5340]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

#### VAMC upgrade team

- [x] #5275 VAMC Launch Support
- [ ] #5273 Migrate Facility services for VISN 7 and 8 and adding Service Location to migration for moving forward. 🥅

### #2427 Epic: Enforce IA design for VAMC editors

See epic #2427 for full list

- [x] #5329 Update pathauto #4773 / PR (Sprint 33, @ethanteague) 🥅
- [x] #5400 Include report of all Detail pages that don’t include -health-care, which VAMC team can use to repair existing menu items (Sprint 33, @kevwalsh ) 🥅

#### #4374 Local editor experience

- [ ] #5426 Review and enhance proofing pages for Vet Center content types 
- [ ] #5425 Standardize Operating status fields for Vet Center CAP (stretch)

#### #4400 Change management for local editors 👥  

- [x] #5281 Deliver training to Vet Center Outreach coordinators
- [x] #4837 Post Vet Center training videos on CMS help center

#### Enforce unique content

Not prioritized for this sprint, we will continue to lean on help desk here (accessibility tests -> help desk -> VAMC upgrade team / editors.) 

## Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### CLP

- [ ] Support for launches

## #4019 ~User~ _CMS account_ administration service  

- [x] #5423 Moderation guide
- [x] #5267 User admin stakeholder interviews 1/2 complete
- [ ] #4999 Update documentation with standardized terms

Stretch:
- [ ] #4790 Update CMS account admin role permissions 
- [ ] Refine Role Delegation user stories 

## Training

- [ ] #5288 Establish scope and draft "What is the VA.gov CMS" video(s)

## Translation 

- [ ] Discovery conversations with #localization-mvp team
