### ISSUE TITLE
Provide feedback opportunity in broken link report to report false positives

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5342]
## User Story or Problem Statement

There are several ways in which the broken link can have "false positives"
1. Site is down temporarily 
2. Can't be crawled by a user agent
3. Not available from VA network. 

As an editor who thinks my "broken link" is not bad, i want to know that it's not a perfect tool. 

As a editor that sees what i think is a false positive in the broken link report, i want to report it so that it can be added to a whitelist.

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
