### ISSUE TITLE
Add a VA favicon to VA.gov CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5372]
## User Story or Problem Statement

The internet is not a series of tubes, it's a series of tabs. And favicons are critical to distinguish between tabs. 

Can/should the favicon match the environment indicator? 

## Acceptance Criteria
- [ ] VA icon appears on VA.gov CMS pages
- [ ] No environment indicator overlaid on top.

## Implementation steps
Update theme and environment indicator settings 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

**Comment by kevwalsh** [comment]
This was done via #7368
