### ISSUE TITLE
Update all facility health service ensure each one has a Service Location

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5387]
## User Story or Problem Statement

All facility health services (health_care_local_health_service) need service locations. Existing facility health services are missing them. Future health services will get them via #5273. 

## Acceptance Criteria
- [ ] All existing facility health services have at least one Service Location
![image](https://user-images.githubusercontent.com/5752113/140197645-1716ae91-d894-4aae-b841-99a3d2efa730.png)
Within server_location paragraph there are 3 other paragraphs that need to be created as well.
- node: health_care_local_health_service
   - field: field_service_location
      - paragraph: service_location
         - field_hours should be set to `0` for `Use the facility's hours`
         - field_use_main_facility_phone should be TRUE
         - field_service_location_address -> paragraph: service_location_address
            - field field_use_facility_address should be TRUE
         - field_email_contacts -> paragraph: email_contact  (all field values should be empty)
         - field_phone -> paragraph: phone_number   (all field values should be empty)

## Implementation steps
- ~Update hook or~ drush script.   There are currrently ~5100 facility health services, but we won't know until we craft the query how many are actually missing location parargraphs.   ~More than 500, do it as a drush script.  Less than 500 do it as a hook_update_N()~
- Model this script after `scripts/content/VACMS-2975-update-vamc-service-nodes-2020-10.php`  (just copy and rename it)
-  process all facility health service nodes that have an empty value for field_service_location
- Create a new paragraph of "Service location" to connect to by entity revision.   It should have the sub-paragraphs and field values as defined in the outline above 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
Facilities team issue to remove fallback logic: [#24899](https://github.com/department-of-veterans-affairs/va.gov-team/issues/24899)

**Comment by swirtSJW** [comment]
field_values  would contain the checkbox value for use default address.

```
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\paragraphs\Entity\ParagraphsType;


$paragraph = Paragraph::create($field_values);
$paragraph->save();
```

**Comment by swirtSJW** [comment]
@netboss I just updated the specifics related to the paragraph, fields and sub-paragraphs.    In order to do this, you have to actually create the subparagraphs first so that they can be saved with the paragraph, which can be then saved with the node.

**Comment by swirtSJW** [comment]
I strongly recommend creating functions that each handle part.   
createParagraphServiceLocationAddress()  (returns the created  paragraph or its revision ID)
createParagraphEmailContact()  (returns the created  paragraph or its revision ID)
createParagraphPhoneNumber()  (returns the created  paragraph or its revision ID)  

Then  createServiceLocation() will call each of the functions above and return the paragrapph or revision id that will be needed to save with the node.
