### ISSUE TITLE
Hide Description and weight field on Menu settings

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5399]
## User Story or Problem Statement

The menu item descriptions are not currently used by va.gov, and add unnecessary cognitive load to editors when adding menu items. 

![Create_Benefits_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/118857170-bcb49d00-b8a5-11eb-955e-c84a6fa9d88c.png)

## Acceptance Criteria
- [ ] Description field and weight field is removed from Menu Settings on all content types. 
- [ ] We have validated that no users use the Weight field. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
