### ISSUE TITLE
Single page publishing MVP

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5401]
## Background

The team has been exploring the concept (#5080) of using the preview server code to create publishable faithful renderings of single pages from the CMS. Having proven the content fidelity and feasibility of the concept, the next iterative step is to produce a working prototype. This MVP prototype will allow publishing single pages of a selected content type, in order to demonstrate the following items:

- Proof of Concept feasibility
- single page publishing speed
- single page content fidelity (with respect to the full content build)

## Proposed Implementation

The following will be done for a single selected content type (TBD):

- Add a “Publish Now” button next to the “Preview” button
   - only shown to site admins
   - only shown on non-production environments
   - disabled if the alias is not the same as current production (see: [vaGovFrontEndUrlForEntityIsLive](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/docroot/modules/custom/va_gov_backend/src/Service/VaGovUrlInterface.php))
- The published button will direct the user to an AWS API Gateway endpoint, giving the current node ID as a parameter
   - e.g. https://{apigateway}/publish-cms-page?nodeId=123
- This gateway will call a Lambda function that:
   - retrieves the page HTML from the preview server for that environment
   - writes the page content to S3 at the correct path
   - displays text to the end user: “Page published to https://staging.va.gov/path/to/page”

### Content Type Candidates

- Benefits Detail Page
- FAQ - multiple Q&As

## Notes

This is an iterative MVP, rather than the first step towards a final architecture. Any final architecture will need to include consideration for the following concerns:

- audit trail for content publishing
- queuing and/or de-duping of publishing requests
- simultaneous publishing of multiple interdependent pages

## Acceptance Criteria
- [ ] “Publish Now” button is visible for users with the "Administrator" role on "FAQ - Multiple Q&A" pages on non-production BRD environments
- [ ] When pressed, the current node is built and published to a S3 bucket at a path matching production
- [ ] After publishing, an editor is able to navigate to the page and verify that their changes have been published
- [ ] Page content visually matches production content for all published "FAQ - Multiple Q&A" nodes
- [ ] HTML diffs against production content for all published pages of the "FAQ - Multiple Q&A" have been reviewed and do not introduce functional changes
- [ ] Technical diagram and basic architecture documentation for the solution has been created and linked from this issue
