### ISSUE TITLE
Implement new content type names and descriptions from #5411

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5412]
## User Story or Problem Statement

See #5411 for context. 

## Acceptance Criteria
- [ ] Changes designed in #5411 are implemented 

## Implementation steps
- [ ] Update content names and descriptions per #5411
- [ ] Search codebase for places in the UI we may want to update
- [ ] Changes are added to a VAMC training backlog, and User guides are updated

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by Agile6MSkinner** [comment]
This effort was abandoned years ago. Closing.
