### ISSUE TITLE
Review and enhance proofing pages for Vet Center content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5426]
## User Story or Problem Statement

As a manager of Vet Center content, i should be able to proof content on the View tab for nodes, and use the revisions history to compare content.

## Acceptance Criteria
- [ ] All node _content_ is visible on View and revision pages in a way that reflects the node form 

## Implementation steps
- Review proofing page (View tab) for content complete proofing pages for all vet center content types, using escanaba content as an example
- Standardize (reorder, add fieldgroups, etc) appropriately

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
Closing as no longer relevant
