### ISSUE TITLE
Reset detail page custom URL aliases before running pathauto 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5437]
## User Story or Problem Statement

Pathauto "Update URL alias" does not run on nodes that have aliases that are different from their past pathauto pattern, and that have "Generate automatic URL alias" unchecked. Before we run the pathauto change from #4773, we need to ensure that it affects all "detail page" nodes. 

We think there are only a few detail pages, like the three under pittsburgh-health-care/about/, that are potentially affected, but we aren't yet sure. 

## Acceptance Criteria
- [ ] Updating URL aliases based on change in #4773 updates URL aliases for _all_ Detail pages that don't match the new spec, including those that had been previously customized away from the old spec. eg
  - [ ] /pittsburgh-health-care/about/history is rewritten to /pittsburgh-health-care/about-us/history (although worth noting that Pittsburgh will have its URL aliases hand-updated, not with "Update URL alias" action.

We could also establish that no existing detail page nodes (outside of pittsburgh) have this non-default url alias, or so few that we can fix these by hand. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
