### ISSUE TITLE
VAMC system (and benefit hub landing page?) URL alias should be automated on h1 (plain language system name), but strip out the va-

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5440]
## User Story or Problem Statement

VAMC systems URLs are autogenerated based on their node title, but must have `va-` stripped out, so they end up being having their alias set manually. 

This is low priority because over 80 of these are already created and have had their URL alias overridden manually. 

## Acceptance Criteria
- [ ] "VAMC system" content type pathauto pattern has been updated to strip out `va-`, so eg `va-altoona-health-care` becomes `altoona-health-care`
- [ ] Consider "resetting" Existing VAMC systems to this new pathauto default
- [ ] Consider applying this to Benefits Hub landing pages, which often contain "VA in them.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
@jilladams @mmiddaugh another one I found
