### ISSUE TITLE
Additional info on content administration page

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#5444]
## User Story or Problem Statement
As a VAMC editor I need to be able to easily tell who has last modified a page from the [content administration page](https://prod.cms.va.gov/admin/content). Particularly when a site is in dual-state, it's hard to know which pages I've edited and which ones still need editing without having to drill into each page.

On a VAMC open hours call, several users requested a new column with `last modified by` but they are open to any solution that works.

![image (5).png](https://images.zenhubusercontent.com/5e3ad9b2c4b3070f908bf89c/a92655e6-ec6e-4b11-99fe-e86cb6c80695)

## Acceptance Criteria
- [ ] A user is able to easily identify who last modified a page from the content administration page

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by TheBoatyMcBoatFace** [comment]
Removing Platform CMS label. If applicable to us, please re-add

**Comment by EWashb** [comment]
This has been done
