### ISSUE TITLE
Not all staff profiles need stand-alone pages on va.gov

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5450]
Corresponding Facilities team issue: https://github.com/department-of-veterans-affairs/va.gov-team/issues/17116 (some overlap)

## User Story or Problem Statement

Currently, all staff profiles produce a URL on www.va.gov, in the [sitemap.xml](https://www.va.gov/sitemap.xml)

The only staff profiles that currently _need_ a profile are those linked on the VAMC leadership page, such as 
https://www.va.gov/wilmington-health-care/staff-profiles/vince-kane/

<details><summary>Examples wtih screenshots</summary>

## Sitemap

![https___www_va_gov_sitemap_xml_and_Slack___Threads___Digital_Service___VA___2_new_items_and_New_Issue_·_department-of-veterans-affairs_va_gov-cms](https://user-images.githubusercontent.com/643678/119692882-ca27d500-be19-11eb-970d-68d221624a61.png)

## Care coordinator pages with "mini staff profiles" 

These staff profiles may not need stand-alone pages, because their content is included on the Care coordinator page.

![VA_Wilmington_health_care___Chaplain_Services___Veterans_Affairs](https://user-images.githubusercontent.com/643678/119693264-1d018c80-be1a-11eb-8956-88f17c6542c4.png)

Example Staff profile that doesn't need a front end URL.
Note the left nav takes the user back to leadership, which is not appropriate.

https://www.va.gov/wilmington-health-care/staff-profiles/peter-igwilo/

![Peter_Igwilo___VA_Wilmington_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/119693131-ff342780-be19-11eb-873f-c3dafd514a33.png)

</details>

There are several overlapping issues that may need to be solved together
1. Determine which staff profiles "deserve" pages. Is it the presence of a certain field, like bio? Is it a boolean? Is it the fact that it's linked from the Leadership page? 
2. Consider implications for left nav and breadcrumbs. Depending on the rules for what determines the front. The current navigation pattern assumes they are leadership profiles.
3. Consider future staff profiles on other websites, particularly organization websites that often contain bios. 

## Acceptance Criteria
- [ ] TBD on discovery

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
