### ISSUE TITLE
Sprint 34 - Product support team priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5460]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

Sprint 34 pressure points
- Closing in on end of quarter, on track for hitting [our 1.0 priorities](https://docs.google.com/spreadsheets/d/1aH4vtnZDdhjXXNJjaYYlUPMrxRvJqQgBa3MgRSqjrlQ/edit#gid=326448684) but not our 1.1 priorities, with the exception of "Enforce unique / Prevent duplicate content". Have made additional progress in other areas 
- Need to start planning Q3
- Drupal 9 issues may need to be prioritized alongside product team user stories (backfiling for Core team) 
- Vet Center MVP launches happening, prepping to double our CMS user base by end of June with 70 new Vet Centers from west coast
- 55+ of 139 VAMCs in dual state, questions about content strategy are increasing
  - More VAMC issues to triage coming through via support / help desk and office hours 
- Tier 2 support for help desk increasing, we need to strike balance between incidence response and prevention/systemic issues.
- Vacation: Kev 4 days in Sprint 34, Steve will be out for Sprint 35. 

## Core

Drupal 9 issues TBD

## Cross-product issues posing risk to governance, accessibility, help desk, etc 

- [x] #5447 Content publishers should not be able to trigger content release
- [ ] #5436 Sections field on media doesn't respect workbench access limitations in the media widget version of form 
- [x] #5442 Include 501 and 503 responses in re-scan logic 
- [x] #5180 Incorrect guidance for editors about how to fix facility data. 🥅 
- [x] #5419 Remove "cloning" from content_creator roles 
- [x] #5536 Node link report reporting image links as non-discernable text 
- [ ] #4806 Spike: Prevent editors from saving links with no discernible text  (stretch)

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

### Vet Center 

- [x] #5025 Reproduce field_office caching defect (may be only affecting content admins that use both VAMC and Vet Center product)

#### #4400 Change management for local editors 

- [x] #5453 Vet Center training for 10 MVP Vet Center Directors (6/11)
- [x] #5454 Iterate on Vet Center training materials (videos) for the next batch
- [x] #5494 Vet Center District 5 users added to training/prod (awaiting dump)
- [ ] MVP launch support (Tier 1 and 2)

### VAMC

- [ ] #5004 Deep dive on VAMC help desk data
- [x] #5339 Refactor metatags on VAMC product to pull directly from node titles (h1s) (stretch)
- [x] #5508 User guide for adding Other locations on the VAMC System page #5508

### #2427 Epic: Enforce IA design for VAMC editors

UX issues
- [x] #5489 Merge integration branch for Sprint 33's #4773 #5437 #5399 #1268 #5470 (awaiting menu items, maybe done)
- [ ] #4932 Show VAMC menu on VAMC proofing pages (in review but not merged)

Parent item lockdown
- [ ] #4988 Implement VAMC menu governance  🥅  

#### VAMC upgrade team

- [x] #5273 Finalize migration for 7/8 
- [x] VAMC Launch Support for VISN 7/8
- [x] Migration process for whatever's after VISN 7/8.  Discuss with VAMC how to keep them unblocked. -- timing of A-Z mapping and data cleaning. 9 VISNs to go after 7 and 8. (Friday June 11 sync)

## Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### CLP

- [ ] Support for launches

## #4019 ~User~ _CMS account_ administration service  

- [x] #5267 CMS account admin interviews 🥅 
- [ ] #4999 Define standard language each step of CMS account service 

Stretch:
- [ ] #4790 Update CMS account admin role permissions 
- [ ] Refine Role Delegation user stories 

## Training

- [ ] Followup to #5288 Establish scope and draft "What is the VA.gov CMS" video(s)
