### ISSUE TITLE
Prevent editors from saving content with links using undesired patterns, such as Outlook safelinks.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5462]
## User Story or Problem Statement

* Outlook safelinks or other links recreated by an application. 

Undesired href value
```
https://gcc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.fda.gov%2Femergency-preparedness-and-response%2Fcoronavirus-disease-2019-covid-19%2Fmoderna-covid-19-vaccine%23additional&amp;data=04%7C01%7C%7Cae4b13d851d04f5bdd4908d8a5e18c0c%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637441735414140146%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=7%2BSIjDj2S3y85ZedTnWAG34O%2FO8J7akY2aKJ5WfKdN8%3D&amp;reserved=0
``` 

## Acceptance Criteria

- [ ] We have a place in the codebase to maintain a list of bad URL patterns, including Outlook safe links, links generated within google search results, etc. 
- [ ] Editors get feedback if they include a link that matches that pattern in rich text (and/or in a link field?)
- [ ] TBD: feedback is a warning? or does the form not validate?

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Here's a node to test with https://prod.cms.va.gov/node/5047 

![Erie_VAMC_Launches_New_ATLAS_Site__Bringing_VA_Care_Closer_to_Home___VA_Erie_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/134713675-c6644bbc-5e19-459e-9c93-31a49505128d.png)

**Comment by kevwalsh** [comment]
We may want to merge this into #6837
