### ISSUE TITLE
SPIKE: Help center iteration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5467]
## User Story or Problem Statement

The current help center IA and content design was done on a shoestring in early 2020. Since then, we've developed modular training videos for Vet Center and VAMC users, and developed a number of user guides for products and features. 

How might we continue to improve CMS users access to
* product specific guides
* cross-product issues (editorial workflow, common editing tasks like rich text editing, accessibility, account issues, etc) 

How might we incorporate new types of content, such as
* lists of known product issues (and feature requests?)
* modular training videos
* gifs
* content strategy docs
* etc

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
[CMS Knowledge Base iteration recommendations.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6841101/CMS.Knowledge.Base.aka.Help.Center.iteration.pdf)
