### ISSUE TITLE
Prevent rewriting menu link title on VAMC Detail page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5469]
## User Story or Problem Statement

Drupal core's menu system autopopulates the Menu link title with the node title. 

On VAMC detail pages, do we want to allow editors the option to change the menu link title? 

We already enforce parity between the h1 and the last part of the URL alias. Do we want to enforce parity to the menu link title too? 

If so, should this field just be hidden on this content type? 

![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/119925676-e889ef80-bf43-11eb-9109-0f6a039ad474.png)

## Acceptance Criteria
- [ ] Menu link title field is set to `disabled` on health_care_region_detail_page
- [ ] OR Menu link title field has been hidden on health_care_region_detail_page

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
I changed the PR for this to draft while the AC's get worked out.  Still under "needs refining"
