### ISSUE TITLE
Remove disable_node_menu_link

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5470]
## User Story or Problem Statement

There are certain situations where we want to disable a menu item from the left nav, but still place a node in a menu hierarchy for breadcrumb purposes. Examples: Care coordinator pages under Health Services in the VAMC product. 

At one point, we installed [Disable Node Menu Item](https://www.drupal.org/sandbox/pcranston/2920832) to allow editors to opt out of a left nav menu item inside the node form, instead of having to go to /admin/structure/menu menu administration page. 

![Create_Detail_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/119927057-a57d4b80-bf46-11eb-8d16-958c987ca041.png)

But we don't want this option in the hands of editors in the field, because it's confusing. Content admins who can access menu admin pages can still disable menu items from there. 

Confirmed with Randi (sitewide content) and Lisa (VAMC upgrade) that the menu admin screens are a viable alternative, and that having this option inline in the form is not necessary. So we can proceed!

## Acceptance Criteria
- [ ] The ability to disable menu items has been removed from node add and edit forms.
- [ ] Change management with VAMC upgrade team and other content admins

## Implementation steps
- Uninstall module
- investigate and remove dependencies

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
