### ISSUE TITLE
Reduce menu item selection based on field_administration

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5471]
## User Story or Problem Statement

As a content admin, i only want to see "eligible" menus in the section dropdown. 

As a content editor who has access to 2 or more sections, I also only want to see "eligible" menus in the section dropdown, so that I don't accidentally add a page to the wrong menu. 

Currently, content admins can see 139 menus when adding a menu item to a VAMC system. 

We can use string matching, much like [was done for facility health services](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5328/files). When a content admin picks a section, a matching menu parent item could be selected (and everything else filtered?).

<details><summary>Screenshot</summary>

![Edit_VAMC_Facility_Savannah_VA_Clinic___VA_gov_CMS](https://user-images.githubusercontent.com/643678/119990137-fa947e00-bf95-11eb-9bee-31f1862b1544.png)

</details>

[Related slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1639428399274400), with this quote from a content admin: 

> "I'm in scroll city"

## Acceptance Criteria
- [ ] The list of available menus items is reduced based on selection of a VAMC system in the Section field.
- [ ] No regressions for other limits that have already been put on Parent menu item for content_publishers

## Implementation steps
String matching, like what was done for facility services in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5328/files

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by davidmpickett** [comment]
Closing as dupe of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/11790
