### ISSUE TITLE
Apply menu_force to enforce menu items for other content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5488]
## User Story or Problem Statement

In #1268 we [enforced menu items for VAMC detail pages](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/5441/files#diff-2e75997abb77a562973fc6cbf99d923339d16fb797c93400fcff1e4e8fb294a1).  We can extend that governance to other content types, and possibly simplify the pathauto settings once menu items can be taken as a given 

Possible followup: Update pathauto settings for these content types to leverage menu item placement. 

## Acceptance Criteria
The following content types are enabled with menu_force 

- [ ] ~Benefits Detail Page~
- [ ] ~Benefits Hub Landing Page~
- [x] CMS Help Page
- [x] Events List
- [x] Health Services List
- [x] Leadership List
- [x] News Releases List
- [x] Stories List
- [x] VAMC Detail Page
- [x] VAMC Facility
- [x] VAMC System
- [x] VAMC System Locations List
- [x] VAMC System Operating Status
- [x] VAMC System Policies Page

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
