### ISSUE TITLE
Spike: Investigate standardizing of URL alias patterns (pathauto) for all content types with required menu items

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5490]
## User Story or Problem Statement

In #5488 we will start enforcing menu items for a dozen content types. Given that enforcement, pathauto can be updated to leverage the menu item placement. But this may require some careful change management and possibly adding some redirects. 

See #4773 for an example of how this was done in the context of the messy Detail Page content type. 

## Acceptance Criteria
- [ ] Create one (or standardize around an existing) pathauto pattern that uses the parent hierarchy
- [ ] Apply to the content types specified in #5488 
- [ ] Run "Update URL alias" on nodes with these content types to determine how many URLs will change
- [ ] Work with appropriate product teams to sort through URL diffs. 
- [ ] Create followup issues to finish implementation. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
