### ISSUE TITLE
Disable or hide the cost field on events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5492]
## User Story or Problem Statement

<details><summary>Background</summary>

Jane:
> Jean has expressed some concerns/risks that would be better addressed in the content model/form design than by training, such as not allowing people to include a cost for events (because VEO doesn’t ever want events with a cost to go into the calendar).
> She and Doug seemed keen to talk about it further, I told them I’d convey that back to the team.

Kev's response
> This has come up before. i think it’s a problem where the content strategy didn’t make it into the CMS UI. Research with Veterans showed that they still wanted to be told that an event was free.  There’s a form design question about whether or not to provide a default value “Free” and then disable the field, or just hide the field altogether. I can imagine a situation in the future  where a fundraiser event will happen and we’ll want to be able to make this field editable. In any case, i’ll document this as a problem that needs solving and add to the Event form UX epic.

</details>

<details><summary>Screenshot</summary>

![Edit_Event_Bunker_Bingo___VA_gov_CMS](https://user-images.githubusercontent.com/643678/120522186-1f785f00-c3a3-11eb-9eda-bdf2035272a0.png)

</details>

## Acceptance Criteria
- [ ] Make "Free" the default value
- [ ] Disable the field for non-content Admins
- [ ] Remove textcounter
- [ ] Help text should read "All VA events are free"

## Implementation steps
Drupal config and form theming.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
From @davidconlon 

**Cost:** Free

_All VA events are free_
