### ISSUE TITLE
Add a boolean to staff profile that FE can use to determine when to build a URL

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5498]
## User Story or Problem Statement

Not all staff profiles need URLs on www.va.gov. 

A product decision was made June 2 2021 to generate a page for a staff profile only when they have a bio. @davidconlon  

Instead of the FE querying "all staff profiles that do not have content in the bio field", a recommendation was made by @swirtSJW to add a boolean field that 
1. the FE could use to determine when to build a page
2. the CMS could use to show/hide the fields that are not relevant, including the two text fields used in the bio, as well possibly some other fields, like the "Download profile photo as high res"

## Acceptance Criteria
- [ ] The staff profile form has been designed according to CMS Design principles
- [ ] GraphQL can determine when to build a www.va.gov web page based on the value of a new boolean field.
- [ ] Pages with pages on FE should have menu items required (TBD)
- [ ] A new URL alias pattern has been determined and implemented (TBD) (current pattern is `[node:field_office:entity:url:path]/staff-profiles/[node:title]`, which is bad because `[node:field_office:entity:url:path]/staff-profiles/` does not exist. Sometimes alias should have `/leadership/`, and sometimes it shouldn't....

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
