### ISSUE TITLE
MVP Small Batch Publishing

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5499]
### User Story or Problem Statement

As a CMS content editor, I need to publish my content quickly, so that I can _fill in based on user research findings_.

### Affected users and stakeholders

- Primary:
   - All CMS Editors
- Others:
   - OCTO-DE leadership
   - Developers
      - FE Tools
      - Facilities
      - Public Websites
   - CMS Help Desk & Training

### Hypothesis

We believe that rapid Single Page Publishing will drastically improve user experience for CMS editors and organizational confidence in the CMS. We'll know that to be true when the average publication time* for new and updated content is under five minutes.

* As defined as the time between the 'Publish' button being pressed in the CMS and those changes being live on VA.gov.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions

- Many changes critical to Veterans are content-only and can therefore be resolved with this solution

(How will these assumptions be validated?)

## Definition of Done

An editor sees published changes to any Drupal content live on VA.gov within _X_ minutes. (TBD based on User Research)

## Acceptance Criteria
- [ ] CMS Editors see published changes to at least 1 Drupal content type live on VA.gov within 1 minute
- [ ] Editors have clear feedback within the CMS and know when the content they have just published will go live
- [ ] User documentation has been created & incorporated in training materials

Sub Epics/Issues:
- Implement monitoring of content build time

**Comment by acrollet** [comment]
Closed in favor of #5502
