### ISSUE TITLE
Update URL aliases for leadership list pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5500]
### User Story or Problem Statement

Existing leadership list pages are all at `*-health-care/leadership`, but they should be at `-health-care/about-us/leadership`. 

The `*-health-care/leadership` is hardcoded in [the person_profile liquid template](https://github.com/department-of-veterans-affairs/content-build/blob/589ad40646f57eeda4824b51b24bdb745d41bc5d/src/site/layouts/person_profile.drupal.liquid#L11) as part of the this effect in the left nav:

<details><summary>Screenshot</summary>

![Martha_Smith____VA_Shreveport_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/120680177-05548480-c468-11eb-9c9b-9219847e469f.png)

</details>

## Runbook
- [x] Facilities https://github.com/department-of-veterans-affairs/va.gov-team/issues/25606 PR (https://github.com/department-of-veterans-affairs/content-build/pull/276)
- [x] CMS #5671: Export the FEATURE_CHANGE_LEADERSHIP_LINK feature flag  created in Tugboat to code, and release to CMS prod 
- [x] Facilities:  Re-test  https://github.com/department-of-veterans-affairs/content-build/pull/276#issue-674971212 in Tugboat then merge
- [x] CMS #5669: Create PR to update Leadership List URL alias pattern.
- [x] VAMC Upgrade team: Content freeze on creating new Leadership List URLs
- [x] Public Websites https://github.com/department-of-veterans-affairs/va.gov-team/issues/26475: Work with Mikki to prepare a redirect PR(s) for Pittsburgh leadership page, and any leadership pages that get launched before this gets released. **Decision July 1: no redirects needed**.
- [x] CMS #5670: Update URLs on Prod for all existing leadership pages, to use ~health-care/about-us/leadership instead of  ~health-care/about/leadership  AND remove feature flag, and then trigger content release
- [x] ~CMS: Trigger devops team to merge redirect PR(s)~ **Decision July 1: no redirects needed**.
- [x] VAMC Upgrade team: Resume Leadership List page creation
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/27056 Facilities remove dependency on FEATURE_CHANGE_LEADERSHIP_LINK feature flag
- [x] #5855

### Affected users and stakeholders

Various teams. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
