### ISSUE TITLE
Expose Drupal Content API via Lighthouse

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5502]
### User Story or Problem Statement

As a VA.gov web or mobile developer, I need access to a dynamically updated public read-only content API, so that I can create pages & applications with real-time content updates.

### Affected users and stakeholders

* VA.gov developers

### Hypothesis

We believe that exposing Drupal Content via Lighthouse will allow developers to build dynamic, instantly updated pages & applications. We'll know that to be true when all Drupal page content is queryable via a public read-only API.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
* Tk
* Tk

## Acceptance Criteria
- [ ] Drupal content is accessible via a public API served by Lighthouse
- [ ] The process for accessing the public API is documented and socialized to VA.gov developers

## Possible tickets to create for this epic

- [ ] Development PoC
- [ ] Create API specification
- [ ] Implement API endpoints
- [ ] Scalability
- [ ] High Availability
- [ ] Zero-downtime deployments

**Comment by chrisj-usds** [comment]
@mchelen I don't think this card belongs on this board -- seems like a work item. Can it be moved back to the board it came from?

**Comment by chrisj-usds** [comment]
@mchelen Can we please move this card off this board?

**Comment by cmaeng** [comment]
With the AP effort paused, this initiative will be moved into the backlog

**Comment by TheBoatyMcBoatFace** [comment]
Public content API is not an initiative we are moving forward with at this time.

**Comment by davidconlon** [comment]
@mchelen I'm confused as to why this issue was put onto the Digital Experience Board with the thread from the A6 team. Thoughts? Unsure what you and Chris discussed last Jan.

My understanding is that we should have Public Content API should be "On Hold" but not killed off because this is one of the things we have been working with @JeffBarnesUSDS to try to secure funding for? So perhaps we need a new card to outline that?

**Comment by EricaRobbins** [comment]
Did we determine the status of this card? If so, please let me know and I will align it to the appropriate column. Thanks!
@mchelen, @davidconlon
