### ISSUE TITLE
Improve UX for enforcing duplicate content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5513]
## User Story or Problem Statement

When attempting to create duplicate content, the form validation messaging could be improved

![image](https://user-images.githubusercontent.com/643678/120816517-d1886600-c51e-11eb-98c6-b2ea16745f99.png)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
This message can be improved by just changing the name of the Field label.  
![image](https://user-images.githubusercontent.com/5752113/120844870-048e2200-c53e-11eb-8aee-0279cb3320a6.png)

The "1 error has been found" comes from Drupal core.

For the localized message, only what is in highlighted in green can be altered.
![image](https://user-images.githubusercontent.com/5752113/120845226-83835a80-c53e-11eb-90f0-9f8dd4ef30b1.png)
