### ISSUE TITLE
Create analytics dashboard for CMS help center

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5520]
## User Story or Problem Statement

As a CMS team member, i want data about how the CMS help center is being used to help guide decisions on content, IA, and help center features. 

## Acceptance Criteria
- [x] We have brainstormed and prioritized a list of help center metrics we want to track
- [x] We have created a shared analytics dashboard on GA with a subset of those prioritized metrics

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
https://analytics.google.com/analytics/web/#/dashboard/8OLPIasZQzq-dNGgglR9eQ/a50123418w196569434p211458524/
