### ISSUE TITLE
Improve the Content lock UX

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5543]
### User Story or Problem Statement

As an editor, i want more clarity about content locks:
1. How to understand if and when content is locked by another editor
2. How and when to break the lock

We regularly see editors see forms "greyed out" and report issues with broken forms, when the the content is actually locked by another editor

The current UX is very much OOTB drupal contrib, including the alert messaging. The only customization is what can be seen on content listing pages in the last column of /admin/content. 

How might we improve this overall experience? 

What training or documentation might help? 

### Affected users and stakeholders

* All CMS users

Example Slack threads and help desk tickets
* [Vet Center form](https://dsva.slack.com/archives/CDHBKAL9W/p1623162370095400)

![Slack___vsa-vamc-upgrade___Digital_Service___VA___6_new_items](https://user-images.githubusercontent.com/643678/121209172-a072a300-c848-11eb-8ed2-1e50fe855b7b.png)

A VISN 5 editor,  jorge.cardich-fuster@va.gov,  reported on Nov 16 2021 that everything always seem like it got locked. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] 👀 Needs design review because the work involves changes to labels or other design elements
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Runbook
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by davidmpickett** [comment]
Re: the last column of admin/content, the header doesn't always show up. There is a <th> tag and it has a class, but there's no header content. 
![unlabeled column](https://user-images.githubusercontent.com/51967950/194939253-e4947715-c307-48ed-b6f7-ecb2f733196a.png)
![Screen Shot 2022-10-10 at 2 21 02 PM](https://user-images.githubusercontent.com/51967950/194939683-6ae8bf56-e2d0-4e97-b457-b071bf395444.png)

**Comment by laflannery** [comment]
After looking at this, it seems like if the editor goes to this page by clicking on "Content" in the main nav, the table header will have content and be correct. However, if the editor clicks on a section from the homepage to get here, this is when the table header will be empty, the <th> element is also missing an ID - if this is being filled in with JS that may be why it's empty?

**Comment by laflannery** [comment]
After some investigation - this looks like if the editor goes to this page using the "content link" in the main nav, the <th> element will have the "Is Locked" content and be correct.  However, if the editor chooses a section from the homepage once logged in, that is when they will be taken to this page with the empty <th> element.  This element is also missing an ID - and if this is controlled by JS at all that might be why the content is missing
