### ISSUE TITLE
Sprint 35 priorities - Product Support Team

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5554]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

Sprint 35 pressure points
- last sprint of Q2
- Q3 planning
- Swirt out entire sprint

## Core

- [x] #5560 Drupal 9 issues TBD - possible 5 point issue for release support.

## Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

### Vet Center 

- [x] #4582 Group "Vet Center" sections into Districts and update menu toolbar (stretch, critical for 37)
- [x] Any critical issues arising from  MVP test group, including possibly
  - [x] #4936 Prepopulate (and hide?) field_administration and field_owner on IEF for Facility Health Service  (stretch, critical before 37 when next batch is in the system)

#### #4400 Change management for local editors 

- [ ] MVP launch support (Tier 1 and 2)

### VAMC governance

- [x] #5180 Update guidance for facility editors for how to correct Lighthouse-managed data (in PR)
- [x] #5339 Refactor metatags on VAMC product to pull directly from node titles (h1s) (in PR, FE side)
- [ ] #4369 **Refine:** how to handle changes in VAST facility data (needs refining) Move back to 36

### VAMC Content model hardening - Epic refinement

- [ ] #5686 
- [ ] Schedule Retro for Policies/cross-team planning for rollout - first week of July (36)
- [ ] Draft roadmap that leaves open who will launch the new pages (could be VHA, could be VAMC) (stretch)

### #2427 Epic: Enforce IA design for VAMC editors

- [ ] #4988 Implement VAMC menu governance, Parent item lockdown (on hold until 36, for Steve) 
- [ ] Interim process for dealing with Detail pages placed where they shouldn't be (VAMC upgrade)
- [ ] Identify other items, risk space (stretch)

#### VAMC upgrade team

- [x] #5615 Migrate health service data for VISN  17, 20, 10 🥅 
- [x] #5634  Remove endpoint for ~4~ 3 VAMCs going live June 30  🥅 
- [x] VISN 7 launches.

## Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

### CLP

- [x] #5625 Add a "viewport width" image style / derivative for CLP banners 🥅  
  - [x] Required followup: #5694 

## CMS Help desk

- [ ] [Needs new issue] Continue to refine labels and reporting from help desk about product priorities 

## CMS Help Center

- [ ] **Refine:** #5650 Iterate on CMS help center epic
- [x] Stub: #5668 How to create CMS Help Center documentation for product teams
  
## Cross-product governance

- [x] #5320 Remove bulk operations from Sections listings
- [x] #5644 Remove access to taxonomy overview for non content admins (PR already exists)
- [ ] #5248 **Refine:** Non content admins should not be able to archive certain content (stretch)
- [x] #5488 Enforce menu items for other content types (stretch)

### Centralized content

- [x] #4056 
- [ ] #4204 

## #4019 CMS account administration service  

- [ ] #5268 CMS account admin stakeholder interview synthesis
- [ ] Generate Backlog for Q3:  Refine Role Delegation user stories, etc.

## Training

- [ ] #5562 Create product agnostic orientation and editorial training videos
- [x] #5473 Listening sessions for VAMC training feedback and synthesis

**Comment by xiongjaneg** [comment]
added issue number for 5668
