### ISSUE TITLE
Create long term solution for memcache container memory limit for CI and local

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5578]
In #5491 we solved an "out of memory" memcache issue with a short term fix of extending the Tugboat Memcached container and bumping the runtime memory allocated to it from 256MB to 1024MB. We had to push a container image to Docker Hub for this and it isn't ideal that we maintain this container long term. 

## Acceptance Criteria
- [ ] Work with Tugboat to make the memory limit configurable in the config.yml
- [ ] Implement solution in comment below 
- [ ] Clean up previous docker hub image 

## Tasks
- [x] Update Lando config
- [x] Update Tugboat config
- [x] Test
- [ ] Merge
- [ ] Rebuild Tugboat base images
- [ ] Delete image from DockerHub after this PR

**Comment by ElijahLynn** [comment]
Solution here from @q0rban https://dsva.slack.com/archives/C01A35JDH88/p1623360886023100?thread_ts=1622563487.013300&cid=C01A35JDH88

```
services:
  ...
  memcache:
    image: tugboatqa/memcached:1.6
    commands:
      init:
        - sed -e 's/256/1024/' -i /etc/service/memcached/run
        - sv restart memcached
```

**Comment by ElijahLynn** [comment]
Fixed in #6083 by updating Tugboat (ci) and Lando (local) configs. One remaining task that I've added is to remove the container image from DockerHub after we merge and rebuild all the Tugboat environments, when it will be safe to delete. 

## Memcache memory limits with the code in this PR applied to both Tugboat and Lando:

**Tugboat After**
![image](https://user-images.githubusercontent.com/1504756/128965286-383b1971-af1b-4381-8d49-dabf7170c091.png)

**Lando Before**
![image](https://user-images.githubusercontent.com/1504756/128965306-9ba71686-fad2-4a41-9c76-de51f796dd95.png)

**Lando After**
![image](https://user-images.githubusercontent.com/1504756/128965402-99fb902f-a9dd-494f-8846-e66e4ac4fd17.png)

**Comment by ElijahLynn** [comment]
Waiting to delete image until I see the last "pulled" timestamp be at least 24 hours: 
![image](https://user-images.githubusercontent.com/1504756/129143552-f0fd0c36-89f9-4508-b65c-dc0da66a4d00.png)
