### ISSUE TITLE
Critical External System Monitoring

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5605]
## Background
CMS integrates with multiple external systems. The operation and behavior of these systems can negatively affect CMS functionality.

### User Story or Problem Statement

As a CMS engineer, I need to keep track of and monitor systems that affect CMS functionality so that I can effectively maintain operation of the CMS system.

### Affected users and stakeholders

* All CMS editors
* All CMS developers

### Hypothesis

We believe that documenting and monitoring external dependencies will allow CMS team to be more aware of and respond more effectively to issues that affect the functionality of the CMS . We'll know that to be true when more systems that affect CMS are monitored and the time to resolution is decreased.

### Assumptions
* CMS team does not have direct control over all systems that it depends on
* Monitoring external systems allows the team to more effectively escalate issues
* Some external systems have existing monitoring in place by CMS or other teams

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] 👀 Needs design review because the work involves changes to labels or other design elements
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Runbook
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by mchelen-gov** [comment]
@cmaeng The scope here was specifically around monitoring of critical external systems, which did not have monitoring implemented. It looks like the remaining issues here are around documentation, so those should get completed.
