### ISSUE TITLE
Show Vet Center service content inline - POC

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5607]
## User Story or Problem Statement

As an editor I need to see the nationalized service description so I know I am not repeating it.
![image](https://user-images.githubusercontent.com/5752113/121960117-acbc9b80-cd33-11eb-98ae-ebdd510cb26f.png)

Currently as an editor editing a vet center service I am not able to see the national content for that service.  All I see is a link to the service term.  This makes  it difficult to see if I am repeating what is already present in the national description.
The CMS should render the content from the service term instead of just a link to that term.  
It will need to default to suing A, then fall back to B if A is not available.
![image](https://user-images.githubusercontent.com/5752113/121961403-636d4b80-cd35-11eb-9e9f-254255527861.png)

## Acceptance Criteria
- [ ] All national service content is visible to the editor after (or even before?) selecting the service 
- [ ] Maintain the functionality where editors cannot select existing services. 
- [ ] Work with design 
- [ ] Stretch: reusable for VAMC system services (but not implementation for now)

## Implementation 
- [ ] View mode for Health care service taxonomy
  - [ ] VAMC: Display term name and 4 VAMC specific fields
  - [ ] Vet Center: Display term name 4 Vet Center specific fields

## Ajax approach

As an editor, i want to to select my service using the existing selector, and see the national service content immediately

There may be something useful here in this contrib widget, which piggypacks on the ajax call in the autocomplete widget. https://www.drupal.org/project/entityreference_live_preview

Another idea: Load a json file of all services and their fields on the form's page load, and then pull in the relevant bits when a service is selectd. 

## Entity browser approach

Downsides: Adds a lot of UI that will need design love, and moves us away from a simple selector that we believe is already working well. 

- [ ] Create one taxonomy entity browser view (see if we have one already?) with two displays, 
  - [ ] one display for VAMC services. Filter by whether "VAMC Type of Care" is not empty. 
  - [ ] one display Vet Center services.  Filter by whether "Vet Center Type of Care" is not empty. 
  - [ ] both displays should show the corresponding view mode as an entity dislay. 
- [ ]  Create "Health service" entity browser(s? Possibly one for Vet Center, one for VAMC). 
  - [ ] Change the form widget for the health service reference field on the VAMC System Health Service to the entity browser
  - [ ] Change the form widget on the Vet Center content type to use Health Service entity browser.
  - [ ] Selecting the service should show the taxonomy term's entity display, using the respective view mode for each case. 
- [ ] Consider how we might leverage the taxonomy view modes on Node view
- [ ]   

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
This was originated from:
 

1. this ticket: https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-1004 
2. this slack https://dsva.slack.com/archives/C01H29ERVJ7/p1623699929070000
