### ISSUE TITLE
Migrate tables from benefits hubs to Resources and support 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5612]
## User Story or Problem Statement

Background: [see slack thread](https://dsva.slack.com/archives/CDHBKAL9W/p1623769214163900)

A number of Benefits Hubs detail pages are being migrated to Resources and support. 

Some data is going to be time-consuming to migrate manually. 

Is there a programmatic solution to this? 

@RLHecht will provide a list of tables that will be migrated

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by RLHecht** [comment]
@kevwalsh Here's the list of all our rates pages with the number of tables on each. The biggest one is the DIC rates for parents: 36 tables on the page and there are also 3 past rates pages that go with it, which will also need to be moved over. Let me know if you think the pages that have more tables can be done and we can work on doing the rest manually.

[Rates tables to migrate.docx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6688586/Rates.tables.to.migrate.docx)

**Comment by RLHecht** [comment]
@kevwalsh Giving you a heads up that we may be holding off on moving these rates pages into R&S. We'll know more in a week or two but wanted to let you know before you started assessing whether your team could do this work.

**Comment by FranECross** [comment]
@RLHecht Is this ticket still viable, or may I close it? Thanks!
