### ISSUE TITLE
Add a "viewport width" image style / derivative for CLP banners

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5625]
## User Story or Problem Statement

As a CLP user, i want a big image that looks great but is also performant 

## Acceptance Criteria
- [ ] new `viewport_width` image style is created, set to 2500px wide (no upscaling)
- [ ] @kelsonic / Public Websites team is updated once this is on prod

## Implementation steps
- Configure an image style and update behat tests

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
