### ISSUE TITLE
VAMC facilities listed on Operating Status pages should be populated by their VAMC System relationship

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5632]
## User Story or Problem Statement

Currently, facilities listed on each VAMC operating status page must be added manually by an editor. 

Instead, they should be listed based on their `field_office`, which has a value that is shared with each Operating Status page, and should automatically be connected and not editable. 

<img width="950" alt="Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Pittsburgh_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/122402832-d8b26980-cf4b-11eb-938d-2779fcc406ec.png">

## Acceptance Criteria
- [ ] All Operating Status pages are pre-populated with the facilities that are associated with the VAMC system specified in field_office
- [ ] We maintain as much of the experience where editors can edit multiple facilities at once. 
- [ ] Removing a published facility from a VAMC system removes it from the associated Operating Status page

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
This has already been done on the FE. Issue #6849 takes care of it in the CMS experience.

**Comment by davidmpickett** [comment]
Would be resolved by #6849

**Comment by Agile6MSkinner** [comment]
Per @davidmpickett 's comment, closing this in lieu of fixing Operating Status IEF
