### ISSUE TITLE
Improve the editorial experience for VAMC system "plain language" vs "official" names  

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5641]
## User Story or Problem Statement

VHA has adopted plain language VAMC system names, using the format "VA [geographic region or city] health care" for anything Veteran facing, but the "official name" is maintained for legacy purposes. 

Various editors and stakeholders have asked to use the official name instead of the plain language name. The application could do a better job explaining the intent of this decision, and referring editors or stakehodlers to VHA or to written documentation about this design decision. 

Also, since the plain language names were "locked down" for non-content-admins, we have developed the new "tooltip fieldgroup" pattern for these use cases. 

![Edit_VAMC_System_VA_Pittsburgh_health_care___VA_gov_CMS_and_Edit_VAMC_System_VA_Pittsburgh_health_care___VA_gov_CMS](https://user-images.githubusercontent.com/643678/122464734-31eabf00-cf85-11eb-9cc5-8f0ff027e532.png)

## Acceptance Criteria
- [ ] VAMC system plain language name has been added to a tooltip fieldgroup with appropriate help text, explaining the intent of this naming convention and linking out to appropriate documentation (or just referring to VHA) 
- [ ] older code disabling the field for non-content-admins has been removed, and plain language name appears in "view" rather than edit mode for non-content-admins. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
