### ISSUE TITLE
Remove access to taxonomy overview for non content admins

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5644]
## User Story or Problem Statement

Currently, all editors can see Structure > Taxonomy in the toolbar. That's needless noise in the UI, because they don't need access to the Taxonomy Overview pages. 

![Witt_Cook_va_gov___VA_gov_CMS](https://user-images.githubusercontent.com/643678/122567939-35c72180-d017-11eb-9605-bd25e35d547b.png)

## Acceptance Criteria
- [x] Access to Taxonomy overview has been revoked for all but content admins
- [x] "Structure" is gone in the admin toolbar for all but content admins

## Implementation steps
- Update permissions

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
