### ISSUE TITLE
Extend menu-item-based paths to more content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5647]
## User Story or Problem Statement

In #5488 we enforced menu items for >10 menu items.  With menu items guaranteed, we can align URL aliases with their menu items/breadcrumbs, by applying the `[node:menu-link:parents:menu-path-use-parent-url]/[node:title]` token. 

This can greatly reduce the number of pathauto patterns. 

But we need to be careful about this because this could cause some URL aliases to change.  

## ACs

- [ ] https://prod.cms.va.gov/admin/content/audit/detail-pages-urls has been adjusted to:
 - [ ] allow all content types
 - [ ] filterable by multiple content types at once
 - [ ] URL moved to https://prod.cms.va.gov/admin/content/audit/urls
- [ ] [menu_based](https://prod.cms.va.gov/admin/config/search/path/patterns/menu_based) pathauto pattern is updated to use the new token, and is extended to all bundles affected where menu_force is enabled
  - [ ] Pathauto patterns made redundant by this change are removed
- [ ] Nodes with menu_force have been reset to use their auto-generated URL aliases
- [ ] URL aliases updated on a PR environment
  - [ ] First, use the admin/content/audit/urls to download existing URLs
  - [ ] Run update URL aliases 
  - [ ] Download updated URL aliases 
  - [ ] Analyze the delta between aliases before/after, and consider the needs for redirects or unintended consequences. 
  - [ ] Update config as needed based on findings
- [ ] Coordinate with other teams for redirects 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by jilladams** [comment]
This ticket needs to be revisited in the new world of breadcrumbs, since:
1. the 2023 AP change that made Drupal the source of truth for breadcrumbs using 2 modules, and 
2. Updated content guidance that the final breadcrumb should always match content H1 (rather than menu item)

High level summary available in #16902
