### ISSUE TITLE
Iterate on CMS help center  / relaunch as Knowledge Base

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5650]
[this is out of date]

### User Story or Problem Statement

The existing help center at /help is barebones has already outgrown its current structure

Opportunities abound to improve the help center experience
* Update existing IA and add better navigation
* Improve current landing page
* Add search functionality
* Standardize and improve content design and add new editing/content design tools
  * templates for different use cases
    * videos
    * how-tos
    * known issues
    * announcements
  * such as accordions for certain FAQ content
  * gifs
* Add "known issues" pages
* Smarter release notes
* Better support for training curriculum pages
* Add links from editorial experience to relevant help pages
* Add product metadata to content to increase content relationships and open search opportunities
* Supporting new audiences
  * Support content admins  
  * Support api users
  * CMS account admins
* Improved help center analytics to guide various decisions about product or documentation enhancements
  * Add "Was this helpful" widgets
  * Improved Google Analytics 
* Rebranding as "knowledge base"?

Big questions
* What are key features
* What's the right platform for these features? 

### Affected users and stakeholders

* All CMS editor

<link to any existing research or data supporting this>

### Hypothesis

Improvements to the documentation, including IA, content design, searchability, would increase number of self-service events and reduce help desk.
Increased inline links from editorial experience to documentation (also measurable as a KPI) will increases self-service events

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by mchelen-gov** [comment]
removing Platform CMS label

**Comment by EWashb** [comment]
We've already launch the Knowledge Base. Should have been closed a while ago
