### ISSUE TITLE
Tracking for Test Coverage

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5661]
## Background
Related to Q3 Objective 4: "VFS testing suite is comprehensive, on par with industry leaders", we should be able to easily evaluate and track our test coverage and how that evolves over time.

### User Story or Problem Statement
As anyone involved in the project, I need to be able to track test coverage of our custom code in order to make educated decisions concerning development, maintenance, and testing.

### Affected users and stakeholders
* All CMS editors
* All CMS developers

### Hypothesis
We believe that being able to measure test coverage and track changes in coverage over time will provide value in a number of ways, allowing us to:
- visualize the custom code that exists and its degree of test coverage
- ascertain risk posed by a given element of code as a combination of:
  - the degree of coverage of the code
  - the requirements addressed by that code
  - the criticality of those requirements
  - the interactions between that code and upstream code and mutations from updates, etc
- make evidence-based decisions on how to address:
  - backlog issues for adding tests to existing uncovered code 
  - coverage requirements for newly added code
  - major version updates of upstream dependencies

A testable hypothesis should probably be generated in a spike; these are just some things I came up with off the top of my head.

## Acceptance Criteria
- [ ] A testable hypothesis describing how this epic can provide a key result for the objective has been defined.
- [ ] Suitable baselines and goal figures have been determined for testing this hypothesis. 
- [ ] Some resilient and future-proof method for determining test coverage has been decided upon
  - [ ] with sufficient granularity to encompass and allow distinguishing between code that:
    - [ ] exists in different custom modules
    - [ ] is written in different languages (JS, PHP)
    - [ ] may correspond to different functional requirements
  - [ ] that persists recorded metrics in an accessible and comparable format so that an engineer or other party may compare the codebase in its present form to that in a past or alternate form

## Possible tickets to create for this epic
- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

### CMS Team
- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by EWashb** [comment]
Why was this put in the icebox? I'm putting back into unrefined.
