### ISSUE TITLE
Enable revision history for blocks

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5672]
## User Story or Problem Statement

As a block editor, i want to see block revisions and revert if needed to older versions, just like nodes. 

See also 
* #830 (Taxonomy revisions)
* #5102 (Media revisions)

## Acceptance Criteria
- [ ] Revisions tab

## Implementation steps
- [ ] Install and enable https://www.drupal.org/project/block_content_revision_ui

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by msbtterswrth** [comment]
Potential module solutions: 
https://www.drupal.org/project/block_content_revision_ui
