### ISSUE TITLE
Improve content moderation for blocks

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5673]
## User Story or Problem Statement

As an editor, i want to edit blocks with confidence, knowing what changes will be immediately pubilshed vs intiially in draft, regardless of whether i'm editing them on their own (eg https://prod.cms.va.gov/block/39) or inline in another content form. 

[Slack thread with some background](https://dsva.slack.com/archives/CDHBKAL9W/p1624370125200800)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by FranECross** [comment]
Old ticket; closing.
