### ISSUE TITLE
Build help desk self help resources

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5687]
## Description
As a CMS Users, I need to be able to find answers to common questions or issues that block me from publishing content without having to contact the help desk.

As help desk support I need to reduce the strain on the help desk by creating a self help solution for CMS users.  

[ ] Every how-to ticket or ticket that involves a CMS related question about usage, should have a corresponding self-help resource created too (ongoing)
[ ] Every historical ticket should be reviewed for inclusion as a self help resource
[ ] Find location for self help resource (JIRA, CMS?)
[ ] measure visitor traffic for the self help resource
[ ] measure help desk volume
[ ] report on the impact of self help resources on the help desk
[ ] establish method for identifying KB opportunities from helpdesk tickets

## Acceptance Criteria
- [ ] a decrease in help desk volume by x% (to be defined)
- [ ] sustained usage of self help resources by CMS users (30% of active users is the initial target)
- [ ] all June and future tickets have a corresponding self help resource created

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Core Application Team`
- [x] `Product Support Team`

**Comment by xiongjaneg** [comment]
include canned answers, documentation that helps team members respond more efficiently to tickets
