### ISSUE TITLE
Send updated TLS Public Key Certificate to IAM Team

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5698]
## User Story or Problem Statement

As a drupal team member, I need to update my SSOi certificate with the IAM team so I can continue enabling ssoi login for Drupal.

## Acceptance Criteria
- [x] A new certificate for Drupal's SSOi integration is sent to Timi 
- [x] Confirmation is received on **7/8** (9pm) that the cert is installed by the IAM team
- [x] Users can continue to login to Drupal successfully using SSO in all environments

Original email from [Timi.Anlembom@va.gov](mailto: Timi.Anlembom@va.gov)
This email is a reminder that your **cert on our systems is expiring  on 07/13/2021**. Please see the details below

Serial number = 3D0000003E9BB0                            
Subject line: E=cms-admin@va.gov,CN=cms.va.gov,OU=VACO IT,O=Department of Veterans' Affairs,L=Washington,ST=DC,C=US          
Issuer: CN=VA-Internal-S2-ICA1-v1,DC=va,DC=gov

Please make arrangement to provide a new cert so we can replace this as soon as possible before expiration.  **We only make cert production changes on Thursdays at 9pm ET.**

## Tasks
- [x] Send cert to IAM team
- [x] Coordinate deployment to lower environments and test
- [x] Coordinate deployment to PROD and test

**Comment by ElijahLynn** [comment]
This is DONE!!!

I tested after they deployed the new cert and confirmed SSOi was in fact down, and the changes were real. I got a 500 response. Then deployed the new cert to PROD and SSOi PIV login worked again!

Total SSOi/PIV login downtime was 10 minutes - 6:10-6:20pm PT/9:10-9:20pm ET.
