### ISSUE TITLE
Renew PROD TLS certificate

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#5699]
As a CMS user, I need to have an TLS certificate on the Drupal CMS URLs so I can be confident information is being transmitted securely.

## Acceptance Criteria
- [x] TLS certificates are updated for ```cms.va.gov.chain.crt``` and ```cms.va.gov.public.crt``` **before 7/13**
- [x] Production Drupal CMS environment loads with valid TLS certificate displayed in URL bar 
- [ ] Documentation has been added to the `va.gov-team-sensitive` repo 
  - MOVED to #4496 

## Tasks
- [x] Get new certificate in Venafi
- [x] Import in ACS
- [x] Make PR in devops repo https://github.com/department-of-veterans-affairs/devops/pull/9540
- [x] Deploy and Test on DEV/STAGING
- [x] Deploy and test on PROD
- [ ] Get PR approved and merged (I used a branch override in the Jenkins config for deploy)
- [ ] Reset branch back to master for deploy jobs.

**Comment by ElijahLynn** [comment]
Been working on this throughout the day and got my EPAS account fixed, which was indeed broken. It was a deactivated NMEA account and is now an MEA account again. It was deactivated because I didn't complete the NMEA process with a USB Token, which turns out the NMEA account is not needed for regular UI CRUD operations of certificates.  

I then waited for the permissions to propogate to our Venafi service and it never worked, so I contacted the PKI team and they suggested to wait until morning. I did create a SNOW ticket to track all of this: INC18685253.

**Comment by cmaeng** [comment]
Request through VA email from OIT DevSecOps for the new cert by noon ET on 7/8/21.

**Comment by ElijahLynn** [comment]
This is done and deployed to DEV and PROD, STAGING will go out next merge. 

New cert was created with self-service portal Venafi and I installed/imported on the ALB 443 listener and it expires August 1, 2022. Worth noting, and I am still working on docs for this, that we don't have ACM in Terraform so it is a manual operation in the UI of ACM.
