### ISSUE TITLE
Enable “Spotlight” component on VAMC detail pages (and possibly Benefits Hubs pages) as content blocks

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5731]
## User Story or Problem Statement

As a CMS editor I want to place a set of "Spotlight" blocks on a VAMC detail page.

![Health_services___VA_Houston_health_care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/123664393-4e002300-d805-11eb-8f91-64fce220a848.png)

From this user's ticket https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/11/VAHELP-1002

## Acceptance Criteria
- [ ] TBD 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
This work will be informed by an audit reviewing available spotlight patterns and a recommendation to standardize those from Laura (more info available in a [comment on #12801](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-cms/12081#issuecomment-1544376062)

**Comment by xiongjaneg** [comment]
@xiongjaneg Look for related accessibility ticket. Time along with VBA CC Drupal implementation ticket

**Comment by Agile6MSkinner** [comment]
Obsolete
