### ISSUE TITLE
Sort Vet Center Sections alphabetically within their Districts

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5739]
## User Story or Problem Statement

The "reset to alphabetical" button is broken in Drupal core. Even if we could use it, we would have to reset existing non-alphabetical sections to alphabetical. 

## Acceptance Criteria
- [ ] All descendants of VHA > Vet Centers  and VHA > VAMC facilities are sorted alphabetically
- [ ] Sretch:  kept that way in an ongoing basis. 

## Implementation steps
Update hook?

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
