### ISSUE TITLE
Sprint 36 Product team priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5741]
🥅   — Sprint goals (pending Sprint planning)
👥   — Needs discussion, meetings and/or refining 

**Sprint 36** 
- First sprint of Q3
- Swirt needs focus on #4988 from Q2
- Core team
  - Drupal 9 launch
  - Some code review and QA support from Core team
  - Neil out Friday July 9 through Wed July 14
  - Adrian Tier 2 
  - Performance evaluation of #4932 
- Kev out Friday July 9 and Monday July 12

# Customer service

## CMS Help desk

- [ ] #5767  (follow-up to #5004) 
- [ ] #5656 

## CMS Help Center

- [x] **Refine:** #5650 
  - [x] Thursday July 8: Recommendations (backlog refinement) 🥅 
  - [ ] Rest of sprint: iteration and refine next steps
- [x] Specific user guides
  - [x] #5759 
  - [x] #5768 

## #4019 CMS account administration service  

- [x] #5771 

## Training

- [x] #5562 
- [x] #5768 
- [ ] #4940 

# Facilities 

[Agenda for weekly sync with Facilities team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/facilities-cms-weekly-sync.md)

### #2427 Epic: Enforce IA design for VAMC editors

- [ ] #4988 🥅 
- [ ] #5500 (epic)
  - [x] #5669 (ready to merge once Facilities has done QA)
  - [x] #5670 (coordination and post-release) 🥅

### VAMC governance

- [ ] #5248 (in review, needs PO attention)
- [ ] **Refine:**  #4369 (threat to steve's focus on #4988) 
  - [ ] Oakwood VA clinic in Georgia’s number has changed

### VAMC Content model hardening - Epic refinement

- [ ] #5686 🥅  
- [ ] Schedule Retro for Policies/cross-team planning for rollout - first week of July (36)
- [ ] Draft roadmap that leaves open who will launch the new pages (could be VHA, could be VAMC) (stretch)

#### VAMC upgrade team

- [ ] #5781
- [ ] Support dual state launches 

## Vet Centers

- [ ] Discover/Refine: District-level editors with permissions to all Vet Centers in a district.

### Vet Center editorial experience

- [x] #5774 
- [x] #5776 

### #4028 Centralized content editorial experience and governance

- [x] #4056 (done in Sprint 35)
- [ ] #4204 (in Review)

# Public Websites

[Agenda for weekly sync with Public Websites team](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/product-team-support/product-team-weekly-syncs/public-websites-cms-weekly-sync.md)

## CLP 

- [x] #5775
