### ISSUE TITLE
Remove User admin (administrator_users) role and add "CMS Account admin" (cms_account_admin)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5742]
## User Story or Problem Statement

`administrator_users` is not in use. it has a bad machine name and label and we have an opportunity to fix this before adding people to it. 

## Acceptance Criteria
- [ ] `administrator_users`  is removed
- [ ] `cms_account_admin` is 
- [ ] All permissions associated with the former are moved to the latter. 
- [ ] Codebase is reviewed for any references to `administrator_users` and updates are made. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
