### ISSUE TITLE
Possible data integrity issue with paragraphs and owner nodes.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#5744]
## Describe the defect

[Full thread for context](https://dsva.slack.com/archives/CT4GZBM8F/p1624996827137200)

It appears that we have a data integrity issue:

```
mysql> SELECT id,revision_id,parent_id,parent_type,parent_field_name FROM paragraphs_item_revision_field_data WHERE parent_id=8106;
+-------+-------------+-----------+-------------+---------------------+
| id    | revision_id | parent_id | parent_type | parent_field_name   |
+-------+-------------+-----------+-------------+---------------------+
|  5344 |      142710 | 8106      | node        | field_content_block |
| 12663 |      142711 | 8106      | node        | field_content_block |
|  5353 |      142712 | 8106      | node        | field_content_block |
|  5354 |      142713 | 8106      | node        | field_content_block |
| 18826 |      176557 | 8106      | node        | field_content_block |
| 18958 |      176689 | 8106      | node        | field_content_block |
| 19013 |      176744 | 8106      | node        | field_content_block |
| 19173 |      176904 | 8106      | node        | field_content_block |
| 18826 |      215554 | 8106      | node        | field_content_block |
| 19173 |      215555 | 8106      | node        | field_content_block |
| 18958 |      215556 | 8106      | node        | field_content_block |
| 18826 |      265702 | 8106      | node        | field_content_block |
| 19173 |      265703 | 8106      | node        | field_content_block |
| 18958 |      265704 | 8106      | node        | field_content_block |
| 19013 |      265705 | 8106      | node        | field_content_block |
| 18826 |      273152 | 8106      | node        | field_content_block |
| 19173 |      273153 | 8106      | node        | field_content_block |
| 18958 |      273154 | 8106      | node        | field_content_block |
| 19013 |      273155 | 8106      | node        | field_content_block |
| 18826 |      273192 | 8106      | node        | field_content_block |
| 19173 |      273193 | 8106      | node        | field_content_block |
| 18958 |      273194 | 8106      | node        | field_content_block |
| 19013 |      273195 | 8106      | node        | field_content_block |
+-------+-------------+-----------+-------------+---------------------+
23 rows in set (0.09 sec)

mysql> SELECT * FROM paragraphs_item_field_data WHERE parent_id=8106;
Empty set (0.04 sec)

mysql> SELECT * FROM paragraphs_item_field_data WHERE id=19013;
+-------+-------------+---------+----------+--------+------------+-----------+-------------+---------------------+-------------------+------------------+-------------------------------+
| id    | revision_id | type    | langcode | status | created    | parent_id | parent_type | parent_field_name   | behavior_settings | default_langcode | revision_translation_affected |
+-------+-------------+---------+----------+--------+------------+-----------+-------------+---------------------+-------------------+------------------+-------------------------------+
| 19013 |      273222 | wysiwyg | en       |      1 | 1565734343 | 18376     | node        | field_content_block | a:0:{}            |                1 |                             1 |
+-------+-------------+---------+----------+--------+------------+-----------+-------------+---------------------+-------------------+------------------+-------------------------------+
1 row in set (0.00 sec)
```

There are at least a few paragraph <-> node relationships that are broken.  In this case, the broken relationship appears to be affecting how editing permissions are calculated for paragraphs.  

My hypothesis is that:
1.  A node was created and pointed to a paragraph.
2. That node was cloned and the clone received a new reference to a new revision of the original paragraph.
3. Whichever node has the latest default revision will determine which is the default revision of the paragraph.
4. When an editor attempts to edit one of the nodes, `workplace_access` checks permission to edit the paragraph based on the node referred to by the paragraph's default revision's `parent_id`, _not_ the node referred to by the paragraph's current revision's `parent_id`.  In other words, I think the section will be come from the node with the latest default revision pointing to that paragraph, rather than the node currently being edited.
5. Correspondingly, the node and its paragraphs may have mismatched section information.

### Tasks:
- [x] Write script to:
   - [x] add site alert to let editors know some nodes may not be edited
   - [x] lock affected parent nodes
   - [x] clone paragraphs incorrectly referenced from multiple nodes
   - [x] correct references on cloned paragraphs
   - [x] update references on parent nodes and re-save
   - [x] unlock parent nodes
   - [x] remove site alert
- [x] test script on `cms-test` or `dev` and confirm data integrity
- [ ] run script on `prod`

## Acceptance Criteria
- [ ] An editor with access to the "VA Sierra Nevada health care" section may edit the paragraphs under "Main Content" on the DAV Vans detail page for VA Sierra Nevada (`/node/8106/edit`)

**Comment by ndouglas** [comment]
```
mysql> SELECT entity_id,field_content_block_target_id,field_content_block_target_revision_id,parent_id FROM node__field_content_block AS parent INNER JOIN paragraphs_item_field_data AS paragraph ON parent.field_content_block_target_id=paragraph.id AND parent.entity_id <> paragraph.parent_id;
+-----------+-------------------------------+----------------------------------------+-----------+
| entity_id | field_content_block_target_id | field_content_block_target_revision_id | parent_id |
+-----------+-------------------------------+----------------------------------------+-----------+
|       746 |                          4787 |                                  42186 | 18262     |
...
1316 rows in set (0.02 sec)
```

```
mysql> SELECT DISTINCT(entity_id) FROM node__field_content_block AS parent INNER JOIN paragraphs_item_field_data AS paragraph ON parent.field_content_block_target_id=paragraph.id AND parent.entity_id <> paragraph.parent_id; 
+-----------+
| entity_id |
+-----------+
|      8175 |
...
504 rows in set (0.02 sec)
```

**Comment by ndouglas** [comment]
Looking at another node, Node 23396:

```
mysql> SELECT id,revision_id,parent_id,parent_type,parent_field_name FROM paragraphs_item_revision_field_data WHERE parent_id=23396;
+-------+-------------+-----------+-------------+--------------------------------+
| id    | revision_id | parent_id | parent_type | parent_field_name              |
+-------+-------------+-----------+-------------+--------------------------------+
| 23394 |      192658 | 23396     | paragraph   | field_phone                    |
| 23395 |      192660 | 23396     | paragraph   | field_service_location_address |
| 23394 |      219136 | 23396     | paragraph   | field_phone                    |
| 23395 |      219137 | 23396     | paragraph   | field_service_location_address |
| 50276 |      330462 | 23396     | node        | field_content_block            |
+-------+-------------+-----------+-------------+--------------------------------+
5 rows in set (0.09 sec)
```

And to where do the default revisions of Node 23396's paragraphs point?

mysql> SELECT id,revision_id,parent_id,parent_type,parent_field_name FROM paragraphs_item_field_data WHERE id IN (SELECT id FROM paragraphs_item_revision_field_data WHERE parent_id=23396);
+-------+-------------+-----------+-------------+--------------------------------+
| id    | revision_id | parent_id | parent_type | parent_field_name              |
+-------+-------------+-----------+-------------+--------------------------------+
| 23394 |      219136 | 23396     | paragraph   | field_phone                    |
| 23395 |      219137 | 23396     | paragraph   | field_service_location_address |
| 50276 |      330495 | 26900     | node        | field_content_block            |
+-------+-------------+-----------+-------------+--------------------------------+
3 rows in set (0.10 sec)

Paragraph 50276 points to Node 26900.

And to which section does Node 23396 belong?

```
mysql> SELECT entity_id,revision_id,field_administration_target_id FROM node_revision__field_administration WHERE entity_id=23396;
+-----------+-------------+--------------------------------+
| entity_id | revision_id | field_administration_target_id |
+-----------+-------------+--------------------------------+
|     23396 |      447167 |                            322 |
|     23396 |      447168 |                            322 |
|     23396 |      447199 |                            372 |
|     23396 |      450704 |                            372 |
+-----------+-------------+--------------------------------+
4 rows in set (0.00 sec)
```

So 322, then 372.

And Node 26900?

```
mysql> SELECT entity_id,revision_id,field_administration_target_id FROM node_revision__field_administration WHERE entity_id=26900;
+-----------+-------------+--------------------------------+
| entity_id | revision_id | field_administration_target_id |
+-----------+-------------+--------------------------------+
|     26900 |      462769 |                            372 |
|     26900 |      462770 |                            372 |
|     26900 |      462795 |                            376 |
|     26900 |      462872 |                            376 |
+-----------+-------------+--------------------------------+
4 rows in set (0.00 sec)
```

372, then 376.

And to which sections do these nodes refer?

```
mysql> SELECT tid,name FROM taxonomy_term_field_data WHERE vid="administration" AND tid=322;
+-----+------------------------+
| tid | name                   |
+-----+------------------------+
| 322 | VA Atlanta health care |
+-----+------------------------+
1 row in set (0.00 sec)

mysql> SELECT tid,name FROM taxonomy_term_field_data WHERE vid="administration" AND tid=372;
+-----+-----------------------+
| tid | name                  |
+-----+-----------------------+
| 372 | VA Alaska health care |
+-----+-----------------------+
1 row in set (0.00 sec)

mysql> SELECT tid,name FROM taxonomy_term_field_data WHERE vid="administration" AND tid=376;
+-----+-------------------------+
| tid | name                    |
+-----+-------------------------+
| 376 | VA Roseburg health care |
+-----+-------------------------+
1 row in set (0.00 sec)
```

So according to this, Node 23396 belongs to VA Alaska health care, Node 26900 to VA Roseburg health care, and Node 23396's field_content_block paragraph belongs to VA Roseburg health care.  

So if we attempt to edit Node 23396 with a user with access to VA Alaska health care, they should be prevented from editing the field_content_block paragraph.

And indeed, this is what we see:

<img width="1157" alt="Screen Shot 2021-06-30 at 10 12 56 AM" src="https://user-images.githubusercontent.com/1318579/123976149-eb855f00-d98b-11eb-8a0e-fe08a03d0d38.png">

**Comment by ndouglas** [comment]
Going by the created dates of the paragraphs of the newest node showing this issue:

```
mysql> SELECT id,revision_id,parent_id,parent_type,parent_field_name,DATE_FORMAT(FROM_UNIXTIME(created), '%e %b %Y') FROM paragraphs_item_revision_field_data WHERE id IN (SELECT id FROM paragraphs_item_revision_field_data WHERE parent_id=23406); 
+-------+-------------+-----------+-------------+---------------------+-------------------------------------------------+
| id    | revision_id | parent_id | parent_type | parent_field_name   | DATE_FORMAT(FROM_UNIXTIME(created), '%e %b %Y') |
+-------+-------------+-----------+-------------+---------------------+-------------------------------------------------+
| 50312 |      330593 | 23406     | node        | field_content_block | 19 Feb 2020                                     |
| 50312 |      330635 | 26909     | node        | field_content_block | 19 Feb 2020                                     |
+-------+-------------+-----------+-------------+---------------------+-------------------------------------------------+
2 rows in set (0.20 sec)
```

It appears that the patch to `entity_clone` did indeed have the desired effect.  Or at least, there's nothing to indicate that further corruption is still occurring.  Rather, we're just still dealing with data issues that had not been addressed.

cc @kevwalsh

**Comment by ndouglas** [comment]
See [here](https://gist.github.com/ndouglas/941d70bd69c787a0a21a0d450b5a2c1d) for the output of the script run on production.

Two nodes were in use when the script was run and I'll need to follow up and repair them individually before I can really close out this issue.

```
The following nodes could not be locked: [6475,8457]

 [warning] Message: This content is being edited by the user james.hoehn2@va.gov and is therefore 
locked to prevent other users changes. This lock is in place since 2 hours 2 
min.

 [warning] Message: This content is being edited by the user Jackie.Stevenson@va.gov and is 
therefore locked to prevent other users changes. This lock is in place since 
41 min 49 sec.
```

**Comment by ndouglas** [comment]
<img width="854" alt="Screen Shot 2021-07-15 at 4 31 53 PM" src="https://user-images.githubusercontent.com/1318579/125853616-d0b88d62-aef3-419f-a314-2bba93f82f24.png">
<img width="852" alt="Screen Shot 2021-07-15 at 4 31 45 PM" src="https://user-images.githubusercontent.com/1318579/125853620-f8dee0f4-e9dd-4545-8321-7e80482668d0.png">

No unexpected resource utilization or service disruption AFAICT, although the DB was definitely in use 😃
<img width="857" alt="Screen Shot 2021-07-15 at 4 33 27 PM" src="https://user-images.githubusercontent.com/1318579/125853805-39353657-bc9a-4d0c-9a9d-1b1365eabfab.png">

**Comment by ndouglas** [comment]
Ended up re-running this script on production today (see [log](https://gist.githubusercontent.com/ndouglas/8d8121f3b831e5cb585321eb0afbad72/raw/7e2b9b98f1e1e2be1d4611897321344a1720044d/log.txt)).  Some nodes had to be repaired _again_ -- this is because they had been cloned since July 15, as far as I can tell.
