### ISSUE TITLE
SSOi login is not working on {staging,dev}.cms.va.gov

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#5753]
**Describe the defect**
SSO is not working on {staging,dev}.cms.va.gov.

`Exception: Unable to validate Signature`

**To Reproduce**
1. Attempt to sign on using SSO

**Expected behavior**
Signon completes successfully.

### Tasks:
- [x] Get new cert
- [x] Test manually on DEV
- [x] Make PR
- [ ] Merge
- [ ] Deploy to DEV/STAGING
- [ ] Ensure SSO login works now

**Comment by ElijahLynn** [comment]
W00t! I found an email from the IAM team saying they replaced the lower ENV certs on April 20th and they gave us a new cert. I'll get this updated and deployed.

**Comment by ElijahLynn** [comment]
Tested on DEV (works) and PR is here > https://github.com/department-of-veterans-affairs/devops/pull/9516/.

**Comment by ElijahLynn** [comment]
I also added some more documentation to https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md.

**Comment by acrollet** [comment]
Nice work @ElijahLynn!

**Comment by jefflbrauer** [comment]
I tried on staging and got this, but it could be because I'm not whitelisted?

Debug information
The debug information below may be of interest to the administrator / help desk:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SAML2\Exception\InvalidArgumentException: Invalid Argument type: "non-empty string" expected, "string" given
Backtrace:
5 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/Exception/InvalidArgumentException.php:21 (SAML2\Exception\InvalidArgumentException::invalidType)
4 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php:28 (SAML2\DOMDocumentFactory::fromString)
3 /var/www/cms/docroot/vendor/simplesamlphp/saml2/src/SAML2/HTTPPost.php:74 (SAML2\HTTPPost::receive)
2 modules/saml/www/sp/saml2-acs.php:35 (require)
1 lib/SimpleSAML/Module.php:260 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

**Comment by acrollet** [comment]
@ElijahLynn confirmed that SSOi is now working on dev:

![image (1)](https://user-images.githubusercontent.com/101649/124801947-aa092c80-df14-11eb-8750-a09cc2daf75c.png)

**Comment by ElijahLynn** [comment]
> I tried on staging and got this, but it could be because I'm not ~white~ allow listed?

yes, you need to be added to the allow list, per instructions in https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-tools, however, Adrian did that, was added and still cannot log in, which is the same issue we had last time trying to add Howie and I eventually gave up spending cycles on it as we didn't get anywhere. 

We need to open a ticket as per https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#for-issues-in-your-lower-environments-dev-idev-sqa-preprod.
