### ISSUE TITLE
Remove the node link report ignorelist from configuration management

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5757]
## User Story or Problem Statement

As Tier 1 help desk or other team member triaging an issue about a bad node link report, i want to to be able to add a domain to an ignore list quickly, so that i don't need to involve a developer in fixing a bad node link report.

![Node_Link_Report_Admin___VA_gov_CMS_and_New_tab](https://user-images.githubusercontent.com/643678/124159509-3b862380-da69-11eb-8607-d9ebc882d678.png)

## Acceptance Criteria
- [ ] Ignore list can be managed on prod at https://prod.cms.va.gov/admin/config/content/node_link_report (or in separate config form)

## Implementation steps

We may want to wait for Steve to chime in. And this should have an issue on the node_link_report page https://www.drupal.org/project/issues/node_link_report?status=All&categories=All 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
SOrry for chmining on on this late, but this should be handled via config ignore.  /admin/config/development/configuration/ignore not through any change to the module itself.

**Comment by swirtSJW** [comment]
Something like `node_link_report.settings:domains_to_skip` ought to do it.
