### ISSUE TITLE
Prototype standardized CMS account admin policy for VAMC and Vet Center and CLP

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5771]
## User Story or Problem Statement

- “As CMS help desk processing a new account request, I need to know who can verify permissions for the requested user so I can proceed with giving them an account.”
- “As a cms-supported product owner, I need to know who I can contact when I have questions about cms users for my product.”
- “As a cms-supported product owner, I need to know what the process is for user account management and who is responsible for which piece.”
- “As a CMS user, I want to be able to know who makes the decisions for my account access.”

[Draft policy](https://docs.google.com/document/d/1ZrbMsek8GGeJanKKuGSQjOMCb5ILFywb-mGuydF7B9g/edit#) (Google Docs) 

## Acceptance Criteria
- [x] Template is validated
- [x] Policies are complete (for today's world) for two products: VAMC and Vet Center
- [x] Policies are added to Help Center

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by cmaeng** [comment]
VAMC policies in Help Center **[here](https://prod.cms.va.gov/help/vamc-cms-account-administration-policy)**.

Vet Center policies in Help Center **[here](https://prod.cms.va.gov/vc-cms-account-administration-policy)**.
