### ISSUE TITLE
Improve metatag for titles and images

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5775]
## User Story or Problem Statement

<details>
<summary>Screenshot</summary>

![metatag_config](https://user-images.githubusercontent.com/643678/124545555-3fae9a00-ddf7-11eb-8078-3ac812fc05a4.png)

</details>

## Acceptance Criteria

- [ ] The default Content title (and any other meta title fields like twitter_cards_title should be `[node:title] |  Veterans Affairs` not `[node:title] | [node:field_office] | Veterans Affairs`. 
  - This is causing a FE Defect: Go to https://www.va.gov/initiatives/recognizing-lgbtq-veterans-during-pride-month/ , https://www.va.gov/resources/can-i-be-buried-in-arlington-national-cemetery/, or any page based on a content type that doesn't have a field_office value (which is required on some content types). See that there is a double pipe in the meta title. 
  - [ ]  Any content type that has a required field_office should be `[node:title] | [node:field_office] | Veterans Affairs`
- [ ]  Every content type that has a "primary" image field should have an og:image specified, using the 2:1 medium image style. This includes:
  - [ ] Event
  - [ ] All VAMC and Vet Center facility types
  - [ ] VAMC system 
  - [ ] Story
  - [ ] Staff profile
  - [ ] Campaign Landing Page **priority**
  - [ ] Benefit Hub Landing Page
  - [ ] Any others with an image field. 

## Implementation steps
- [ ] Update metatag config.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ethanteague** [comment]
@kevwalsh is the `2:1 medium image style` token a thing? Not seeing it in the available list. Do you want me to create one? If so, what info would it include?
![image.png](https://images.zenhubusercontent.com/5e2b1d8b2f4d80671f879681/f61e0179-b993-43b7-b98a-d421c1170db7)
