### ISSUE TITLE
Character count on Featured content 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5776]
## User Story or Problem Statement

As a Vet Center editor, i should have helpful guardrails to keep my Featured content to an appriopraite length for the content design. 

## Acceptance Criteria
- [ ] A text counter has been added to Featured Content description. 

![Edit_Vet_Center_Nashville_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124606748-2cbdb900-de3b-11eb-98f1-04f75d884bfe.png)

![Edit_Vet_Center_Nashville_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124607283-afdf0f00-de3b-11eb-9e64-3d32cb2cbea9.png)

## Implementation steps

At admin/structure/paragraphs_type/featured_content/form-display 

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/124606885-537bef80-de3b-11eb-90c6-51f9729152df.png)

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
