### ISSUE TITLE
Show national taxonomy service content inline on Vet Center and VAMC system health service forms

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5800]
## User Story or Problem Statement

As an editor of service content at a Vet Center, i want to be able to see the national content inline within my form (and on prooing screens), so that i can write my content in relation to it, and not duplicate any of it. 

As an editor of VAMC system health services, I want clear guidance on how to edit existing VAMC system health services, and create new ones, including, in particular, what to put  in the "VAMC system description of service" field (label subject to change), so that the content i manage flows well with the national content (from the health care taxonomy) and the facility-specific content. Currently, there is next to no guidance in the UI. VAMC upgrade team pre-populates this content for most VAMCs, and then they can update it. But VAMCs also create new system healths services. We will soon be moving the h3s "Care we provide at [Health care system]" out of this content. 

### Stretch user story

As an editor of health service content at a VAMC or Vet Center, i want to be know who controls this content, in case i wan't to request a change to it. 

As a manager of national health service content, i want to be able to collect feedback about the health service taxonomy in a standardized way, so that i can respond to it. 
  * For example: https://va-gov.atlassian.net/browse/VAHELP-1138

<details><summary>Screenshot of existing VAMC form</summary>

![Create_VAMC_System_Health_Service___VA_gov_CMS](https://user-images.githubusercontent.com/643678/134727678-ff91cd45-dde4-4690-b820-8e2be441857d.png)

</details>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
