### ISSUE TITLE
CMS team member access to SSOi in lower environments

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#5838]
## Background

SSOi issue occurred in Prod preventing login for some users. See [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-07-12-CMS_PIV_login_out_of_service.md)

 SSOi lower environment [testing login](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-login)

### User Story or Problem Statement

As a CMS team member, I need SSOi login on lower CMS environments, so I can test and debug issues related to SSOi.

### Affected users and stakeholders

* CMS editors using SSOi
* CMS team members developing, deploying, or testing SSOi

### Hypothesis

We believe that access to SSOi on lower CMS envs will permit prevention and resolution of SSOi issues. We'll know that to be true when SSOi issues are found before reaching prod, or when issues in prod can be fixed more quickly.

### Assumptions
* Some SSOi prod errors can be replicated 
* Validate by replicating SSOi error from [postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Postmortems/2021-07-12-CMS_PIV_login_out_of_service.md)

## Acceptance Criteria

- [ ] All CMS engineers (Core + PS) with PIV cards are able to login to dev/stage using PIV
- [x] Other CMS team members (PMs, POs) with PIV cards are able to login to dev/stage using PIV
- [x] Documentation added to CMS team onboarding docs

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by acrollet** [comment]
@ElijahLynn and I hypothesized that the [additional code path](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/docroot/modules/custom/va_gov_login/va_gov_login.module#L28) may get triggered when the email address for a user coming from SSO does not exactly match the email address (or maybe username?) in Drupal. (including case sensitivity)
