### ISSUE TITLE
Provide CMS users aspect ratios for image

### ISSUE THREAD

**Issue by joshworkscivicactions** [department-of-veterans-affairs/va.gov-cms#5841]
## User Story or Problem Statement

As a CMS Editor, I need to know the aspect ratio that works best for each content type  or image locations so I can prepare the best image to share with Veterans.

or

Problem description. How might we show CMS users what aspect ratio their images should be in?

See https://dsva.slack.com/archives/CDHBKAL9W/p1626112589284800 

https://va-gov.atlassian.net/jira/servicedesk/projects/VAHELP/queues/custom/22/VAHELP-1105

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Core Application Team`
- [x] `Product Support Team`

**Comment by joshworkscivicactions** [comment]
Same as #4391 closing as a result.
