### ISSUE TITLE
Update Knowledge Base view mode for paragraphs 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5847]
## User Story or Problem Statement

As a user of the Knowledge Base, i don't want field labels in the Knowledge Base, because they add no value. 

## Acceptance Criteria

- [ ] User guides view mode for paragraphs has been renamed Knowledge Base

The following Paragraph Types have a Knowledge Base view mode, with field labels removed

- [ ] Accordion group
- [ ] Accordion Item
- [ ] Additional information
- [ ] Address
- [ ] Alert
- [ ] Accordion
- [ ] Call to action
- [ ] Checklist
- [ ] Checklist section
- [ ] Contact information
- [ ] Email address
- [ ] Embedded image
- [ ] Featured content
- [ ] Link teaser
- [ ] Link teaser with image
- [ ] Link to file or video
- [ ] List of link teasers
- [ ] List of links
- [ ] Lists of links
- [ ] Media list - Images
- [ ] Media list - Videos
- [ ] Process list
- [ ] Q&A
- [ ] Q&A group
- [ ] Q&A Section
- [ ] Rich text
- [ ] Table

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
