### ISSUE TITLE
Remove Home breadcrumb on Knowledge Base articles

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5848]
## User Story or Problem Statement

As a Knowledge Base user, i want to click on a breadcrumb that takes me back to the Knowledge Base, not to the CMS home page.

## Acceptance Criteria
- [ ] `Home >` breadcrumb has been removed from `documentation_page` content type.  
- [ ] We can easily add other content types to an array later to apply the same behavior. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
