### ISSUE TITLE
Make it easier to read User history

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5873]
## User Story or Problem Statement

As a CMS account admin, i want to be able to read the user history page more easily so that i can audit changes.

https://prod.cms.va.gov/user/2019/history 

## Acceptance Criteria

- [ ] Switch to views table.

## Implementation steps
- [ ] Create PR from view in comment below

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Dumping this view config for later.

[views.view.user_history.yml.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/6826745/views.view.user_history.yml.txt)
