### ISSUE TITLE
Complete TLS/Venafi/SSO docs

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#5879]
### Tasks:
- [x] Complete [Venafi access documentation](https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates) enough to remove the WIP prefix from it. 
- [x] Add [Venafi TLS create/download docs](https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi%3A+Create+and+download+TLS+certificates)
- [x] Add steps to the onboarding docs to have engineers request access to lower environments (int and preprod) for testing PIV login
- [ ] Add steps to the SSO documentation on how to work with the IAM/SSO team to renew the public certificate with them
- [ ] Add steps to the SSO documentaiton on how to update the CMS with new public certs from the IAM/SSO team/service

### CMS Team

- [x] `Core Application Team`
- [ ] `Product Support Team`

**Comment by ElijahLynn** [comment]
Docs are here https://vfs.atlassian.net/wiki/spaces/OT/pages/1719009302/Venafi+Gain+access+to+manage+internal+TLS+certificates and here https://vfs.atlassian.net/wiki/spaces/OT/pages/1787953328/Venafi%3A+Create+and+download+TLS+certificates.
