### ISSUE TITLE
Prevent duplicate services added to a single Vet Center

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5888]
## User Story or Problem Statement

As a Vet Center editor, i should have guardrails against adding a duplicate services to a Vet Center

![Edit_Vet_Center_Escanaba_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/126105708-4fa720dd-22ea-45dc-8b1a-3c48892e67d5.png)

## More background

Allow only one is already enabled, but apparently not working as expected https://prod.cms.va.gov/admin/structure/types/manage/vet_center_facility_health_servi/fields 

## Acceptance Criteria
- [ ] Users are prevented from adding a duplicate service to Vet Center (eg at https://dev.cms.va.gov/node/3756/edit)
- [ ] Stretch 1: Remove all sorting UI in IEF.
- [ ] Stretch 2: Services are sorted to alpha order after node is saved. 

(Stretch ACs should probably live in their own issue)

## Implementation steps

- Allow only one module config? May not work in an IEF context.  Needs some testing. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
