### ISSUE TITLE
Improve banner alert UX in the absence of refactoring the banner alert product 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5903]
## User Story or Problem Statement

Based on Convo with Randi H July 19

As an alert editor, i shouldn't see the Banner alert fields unless i select banner alert

![Add_Alert_custom_block___VA_gov_CMS](https://user-images.githubusercontent.com/643678/126226302-d64c42c0-0c94-41aa-8156-558cbed689ad.png)

## Acceptance Criteria
- [ ] "If this is a banner alert" fieldgroup label has been changed to "Banner alert settings"
- [ ] the fieldgroup doesn't appear unless "Banner or in-page alert is set to "Banner Alert"

## Implementation steps
- [ ] TBD

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
