### ISSUE TITLE
Remove option in cancel screen to delete users AND their content 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5910]
## User Story or Problem Statement

As a CMS account admin, i shouldn't have an option to delete a user's content. 

![Slack___cms-team___Digital_Service___VA___7_new_items](https://user-images.githubusercontent.com/643678/126364673-2c946fa9-192b-4647-8b3a-d9cd9544ad6f.png)

## Acceptance Criteria
- [ ] The option "Delete the account and its content" is removed from the account cancel screen.

## Implementation steps
TBD
## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by jefflbrauer** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5910?planning-poker) with ZenHub @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5910?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
[There's a Prevent User Delete, Reassign Content to Anonymous contrib module](https://www.drupal.org/project/prevent_user_delete_reassign) to remove #3. 

One implementation idea is to patch the module and extend it to also remove #4 (although that doesn't align with the module's name). Another approach is to make a more generic module "Prevent User Delete".

**Comment by stefaniefgray** [comment]
**Dilemma:** This issue may affect Drupal CMS admins' ability to remove "ghost" users.

“Ghost” accounts are troublesome, because they can block VA Drupal CMS Helpdesk staff from creating new user accounts, and can block [[VA.gov](http://va.gov/)](http://VA.gov) editors from getting logged in.

If you do not cancel the “fake” account created by the user’s attempted PIV card login attempt, they will not be able to log into the real account that a VA Drupal CMS Helpdesk team member has created or will be creating for them.

If you locate an **Active** user account on the production site with no roles added and no sections assigned, it means that they attempted to log into [https://prod.cms.va.gov/](https://prod.cms.va.gov/) using their PIV card ***before their account was actually created.***

In turn, the user cannot get logged into https://prod.cms.va.gov/ using their PIV card until a member of the VA Drupal CMS Helpdesk team has deleted the "ghost" account.

**Here's the user story:**
As an admin, I am adding a new user to Drupal who just joined VA Cityname as their new Public Affairs Officer. 

This user was very excited to use their new PIV card, and had attempted to log into https://prod.cms.va.gov/ before their account was actually created by a member of the VA Drupal CMS Helpdesk team.

In order to create their new Drupal CMS account assigned to the proper roles and sections, I have to delete the falsely created "ghost" user and create a new account from scratch. This allows the new VA Cityname PAO to log in with their PIV card as intended.

**Related Slack thread:** https://dsva.slack.com/archives/CT4GZBM8F/p1657222065278309

@kevwalsh Question: Is there any way we could test whether keeping the mistakenly created "ghost" account is a bad thing? Perhaps we could just add roles/sections to it? But to the best of my knowledge, something technical is blocking us from being able to do that, and that's why the account has to be deleted and recreated -- it might have to do with their PIV card being linked to their account from within the system.
