### ISSUE TITLE
VAMC banner alert should only show VAMCs that editor has access to

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5912]
## User Story or Problem Statement

As a VAMC banner alert creator on /node/add/full_width_banner_alert, i should only see VAMCs that i have access to via workbench access. 

## Acceptance Criteria
- [ ] as user 1625 i should only see Wilmington Health Care
- [ ] as user 31 i should only see VAMCs in VISN 4 

## Implementation steps
- possibly update user section service 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
**Caution:** I think on this one we have to not discard any VAMCs from the list that have already been selected or we are going to end up with data loss.
