### ISSUE TITLE
Improve (or remove?) node link reports about untested links

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5916]
## User Story or Problem Statement

As an editor, i want clear and useful information about content quality without cognitive overload, so that i can accomplish my tasks efficiently without confusion. 

## Background

Editors are confused by guidelines about untested links, like emails and phone numbers. In one case they are testing links by actually _sending_ the email. 

From https://prod.cms.va.gov/escanaba-vet-center

![image](https://user-images.githubusercontent.com/643678/126407242-ce861c90-0417-40ed-800b-4c8f43f76726.png)

In another case, we are suggesting that people test phone number links themselves (including 911!), but that's very hard to do on a desktop computer that may not have any phone capabilities, even if it was advisable, which it is not. 

from https://prod.cms.va.gov/pittsburgh-health-care/operating-status

![image](https://user-images.githubusercontent.com/643678/126407312-a722913c-3c8c-4441-b34d-db8c6603adb5.png)

The node link report also risks adding "alert fatigue" that may make it harder to get users attentions in the future. 

How might we improve the node link report to deal with these concerns?

Ideas

- disable the " Enable reporting of links not processed (skipped)" setting at https://prod.cms.va.gov/admin/config/content/node_link_report (easy)
 - possibly replace it with a message that emails and phone numbers are not tested. (harder)
- improve guidance of the not processed (easy links list)
- others? 
- we may want to consider other node link report improvements together with this

See [slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1626815779366500)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by ryanlink** [comment]
FWIW one user reported that they clicked on the `tel:` link and it didn't work because that protocol is associated with Skype in their OS and they no longer use Skype.

**Comment by kevwalsh** [comment]
This is a dupe of #7299.
