### ISSUE TITLE
Generate a Vet Center - Locations List for each Vet Center section that doesn't already have one. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5917]
## User Story or Problem Statement

As a Veteran, i need a list of all Vet Center locations. 

As a Vet Center editor, i need to add 1) additional mobile vet centers and 2) nearby vet centers and outstations. 

## Acceptance Criteria
- [ ] All 300 Vet Centers have Vet Center - Locations Lists

## Implementation steps

From @swirtSJW via Slack

> we could do all if them in an update hook pretty easily.  It could create them and associate them with proper vet venter and section.  8 pts top.  The most convoluted part would be looking up to see if one already exists, and that is pretty minor.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
