### ISSUE TITLE
Track knowledge base search keywords in GA

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5920]
## User Story or Problem Statement

As a KB manager, i want to know what users are searching for

## Acceptance Criteria
- [ ] GA report for KB search terms is available

## Implementation steps
See https://github.com/department-of-veterans-affairs/va.gov-team/issues/27652 (Platform analytics team)

vide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
Related to #14194 (or possibly even a dupe)

**Comment by productmike** [comment]
@EWashb Definitely a dupe. Will capture Kev's main theme in #14194 moving forward and close this one out.
