### ISSUE TITLE
LMS for CMS training

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5950]
### User Story or Problem Statement

- As a Veteran on VA.gov, I need clear, consistent, accurate, accessible information to get the services I need.
- As a VA staff who provides information to Veterans on VA.gov, I need to know how to use the CMS to provide clear, accurate, accessible information.
- As a VA staff using the CMS, I need to know my status in training so I can get appropriate access to the CMS.
- As a CMS user administrator, I need to know that editors have the appropriate training to effectively use the CMS and to be able to report that to the editors and stakeholders.
- As a CMS instructional designer/trainer, I need to be able to present, track, and report training in an effective and flexible way that allows for learning changes in an agile environment.

### Affected users and stakeholders

* CMS_editors
* CMS_product_owners

<link to any existing research or data supporting this>

### Hypothesis
Making training available in the VA's learning management system will benefit:
- Veterans will have accurate, timely, consistent information on VA.gov.
- CMS editors will have access to training to help them quickly and efficiently learn to use the CMS and they will be able to track their status in training.
- User admins/other stakeholders with appropriate permission/access will be able to view CMS editors' training.
- Instructional designers/trainers will be able to consistently create, assign, track, and report on CMS editors' training.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

## Acceptance Criteria
- [ ] LMS access is feasible for an instructional designer/trainer
- [ ] LMS access is feasible for a CMS editor

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by xiongjaneg** [comment]
As of December 2020, determined to be not feasible for agile needs
- TMS trainer access would be limited to viewing user activity.
- Course content would have to be submitted for review by section508@va.gov first, then once a certificate was received, could be submitted to TMS team for upload to TMS. Process time unknown. This would likely require one mass training module rather than micro-learning.
