### ISSUE TITLE
Small iteration on alert block type to harden governance and support homepage banners

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5969]
## User Story or Problem Statement

As an empowered OPIA content editor, i want to be able to edit the homepage banner myself, without relying on engineers. 

## Background

The current "alert" block type and configuration in Drupal has a number of issues
* only supports placing banner alerts on nodes. The homepage is not a node. 
* has a scope field with very little governance (any empowered CMS editor with access to alert blocks can place them on any node)
* doesn't trigger a content release automatically
* has no specific training materials
* has some confusing UX
* conflates in-page alert blocks with banner alerts. While they share some attributes, they should probably be separate types. 

Public Websites team wants to improve the current workflow for OPIA to publish alert banners to the homepage of VA.gov. (see 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/27852)

Before taking on a larger refactor of the alert block product (#3380), CMS team has identified a number of ways to improve the existing tooling to achieve better governance, UX.  

<details><summary>Screenshot of current experience</summary>
<img width="1067" alt="Edit_custom_block_Coronavirus_site-wide_alert___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/127052050-7bd33032-9d16-42ec-a3cb-f90df26b4fe4.png">
</details>

## Acceptance Criteria

These need revising if we go with the banner as a node approach. 

**Governance**
- [x] We have identified which block will serve as the OPIA managed homepage banner (block 100)
- [x] Any member of the OPIA Section with content_publisher role can edit and publish the homepage banner.  
- [x] #5985
- [ ] #5986

**Publishing**
- [ ] Saving block 100 as archive or published triggers a content build
- [ ]  Slack notification has been designed for homepage banner (and other high priority content?), to alert certain teams (TBD) 

**Change management**
- [ ] Knowledge Base Article: "How to edit the homepage banner"
- [ ] Knowledge Base Article: "How to create and edit a full width banner."
- [ ] PW and Sitewide content team are aligned on governance and business processes for homepage banners and other full width bannerss

**FE**
- [ ] Coordinate with FE eng on PW team

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
We no longer use site alert...we use sitewide alert. Closing
