### ISSUE TITLE
As a content admin, i shouldn't be able to delete nodes from an IEF form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5974]
## User Story or Problem Statement

Deleting nodes is not good. They should be archived. We shouldn't make it easy for content admins to do so.

Replace with "Are you sure you want to remove this [content type] [node type]? Doing so will not delete the content, but my change where it is displayed.

<img width="1001" alt="Edit_VAMC_System_Operating_Status_Operating_status_-_VA_Wilmington_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/127197346-003b10e1-a8d9-4509-aabb-dc6fea332c40.png">

## Acceptance Criteria
- [ ] On node/2370/edit no user can delete the facility or VAMC banner nodes.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
