### ISSUE TITLE
Improve paragraphs browser, possibly more product-specific

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5976]
## User Story or Problem Statement

As an editor of one of the detail page content types that allows flexible structured content components, i want a paragraphs browser that reflects my needs. 

**Background:** The current groupings were designed for Benefits Hub Detail Page editors, and may not reflect the mental models for the bulk of users (VAMC Detail page editors). For example, "most commonly used" includes Set of Q&A, which is not used much in VAMC detail pages, but used extensively in Benefits Hubs

**How might we** restructure the paragraphs browser to match the needs of editors? 
- Do we create different groupings for different use cases? (more custom work to maintain, but potentially better UX)
- and/or Do we rename and and regroup the available paragraphs?
- is it worth improving any existing paragraph descriptions at this time? 

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/643678/127349437-4e1c3023-797f-4aa4-9714-974b2572f6fd.png)

</details>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by Agile6MSkinner** [comment]
This effort was abandoned years ago. Closing.
