### ISSUE TITLE
Implement improved paragraphs browser experience

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5978]
## User Story or Problem Statement

See #5976 

## Acceptance Criteria
- [ ] Design from #5977 is implemented

## Implementation steps
- [ ] TBD, mostly Paragraphs Browser config

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
