### ISSUE TITLE
Allow 2 address lines on CAP nodes and Facility Health Service paragraph type

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#5980]
## User Story or Problem Statement

As a CAP editor I need to have a second address line available for details like suite numbers and such so that Veterans may find our location certainty

Currently on CAPs  address_line_2 is hidden.  It should be set to optional.
![image](https://user-images.githubusercontent.com/5752113/127380917-976e8021-c155-4bbc-b7f2-b6f1a664b0ed.png)

## Acceptance Criteria
- [ ] address_line_2 is optional on CAPs
- [ ] Verify the FE can consume it (should be the same display as vet centers and outstations)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
