### ISSUE TITLE
Prevent content menu items from being placed at the root of VAMC menus

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#5995]
## User Story or Problem Statement

When an editor (must be a content admin) puts a menu item at the root of a VAMC menu, it gets treated as a <nolink> menu item by the FE, much like Locations and services, News and events, and About VA [health care sytem]

The FE should maybe not assume that it's non-linked menu item. But we may also want to add a guardrail in the CMS to prevent this from happening. 

![VA_Butler_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/127685413-c6828d07-5c84-421b-8cb5-7ce40fee33d3.png)

## Acceptance Criteria
- [ ] Editors of VAMC menus cannot save menu items at the root of a VAMC menu, either from a Menu settings in a node form, or from the menu admin page. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
