### ISSUE TITLE
Footer for CMS knowledge base

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#5996]
## User Story or Problem Statement

How can we provide access to documentation about creating content for the knowledge base without confusing regular editors who are looking for articles to read?
Meta, I know.

Proposed first step:
A link to an "About the CMS Knowledge base" page in the footer of /help.

I've already set it up in prod, but it was hard to do it elegantly with the content blocks currently available. Next iteration should smooth out the design for this. 

## Acceptance Criteria
- [ ] Tech feasibility discussion to understand what we can do.
- [ ] Improved content design for the CMS knowledge base footer

## Implementation steps
Pending feasibility discussion

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
Still an interesting concept worth exploring with other KB enhancements

**Comment by EWashb** [comment]
This is still a useful idea and can be implemented as a part of the redesign. There may be other things that are valuable for the footer.
