### ISSUE TITLE
Banner governance - scope field required before publishing, and field permissions

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6015]
## User Story or Problem Statement

As a site content editor I need the follow in  place for banner alert governance so that I may be confident bad banners are not running wild on the site?

## Acceptance Criteria
- [ ] The banner content type should not be able to be published until it contains at least one display path (field_target_paths). (on node edit... bulk publishing is not in scope)
- [ ] Revision logs are required.
- [ ] Only content admins can edit `field_target_paths`  (all logged in users can see, but only content _admin/admin can edit.) - covered already in #6148, but may require some additional conversation. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
