### ISSUE TITLE
[EPIC] [Events] Enable more than one repeating event pattern for events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6058]
## User Story or Problem Statement

As an event creator, i want to either 
- create more than one repeating pattern (eg once a week on Fridays PLUS once a month on Mondays). 
- create multiple instances of the same event with no date pattern (eg This thursday at 11am, next Wednesday 12pm, and again in 6 weeks on Monday at 8am. 

### Background

In #6057 we enabled recurring events for the first date field on an event, **but deliberately removed the ability to create more than one repeating event pattern.** 

![image](https://user-images.githubusercontent.com/643678/128701871-bd71e5c5-5612-474b-a5de-b5566d5abe88.png)

## Acceptance Criteria
- [ ] Remove the code from #6057 that hides "Add another item"
- [ ] Improve UX for multivalue recurring event (TBD)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by FranECross** [comment]
Closing iceboxed ticket; a new one can be created if needed.
