### ISSUE TITLE
Editorial experience design for managing recurring events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6067]
## User Story or Problem Statement

As an editor of recurring events, i have an editorial experience that is efficient, approachable, consistent. 

## Acceptance Criteria
- [ ] Form design improvements are ready to implement (this issue should include engineering feasibility)
- [ ] The imposed 12 month limit on recurring events is "surfaced" to editors somehow. 
- [ ] Various steps in the content editorial workflow still make sense: 
  - [ ] Content findability (hypothesis: Event list pages)
  - [ ] Content creation 
  - [ ] Various recurring event pattern scenarios (see below)
  - [ ] Content editing (making changes to a node that has a recurring event, or make an existing non-recurring event into a recurring one)
  - [ ] Content proofing
  - [ ] ~Content previewing~ (experience depends on FE implementation)
  - [ ] Content archiving (probably not a concern with this experience? Autoarchiving concern can be tracked in #4214)

Scenarios to consider, pulled from a list used by smart_date developer in their testing, (although we currently don't support all day events, iceboxed issue #6041) 

- Aug 14th 2022, all day (single day, all day)
- Aug 14th to 15th 2022, all day (multiple days in the same month, all day)
- Aug 14th to Sep 14th 2022 all day (multiple days in the same year, all day)
- Dec 30th 2021 to Jan 15th 2022, all day (multiple days that span more than one year, all day) 
- Aug 14th 2021, 10am (a time with no duration)
- Aug 14th 2021, 9 to 10am (a time range within the same am/pm span)
- Aug 14th 2021, 11:30am to 12:30pm (a time range within the same day)
- Aug 14th 2021, 11:30pm to Aug 15th 2021, 12:30am (a time range spanning multiple days)

For that last one, I have also seen some sources that suggest a format like:
- Aug 14th/15th 2021, 11:30pm to 12:30am (when a time span flows into the next day)

## Artifacts
- [Ethan's POC tugboat environment](https://master-dzqiprnzpsoj5ifjekygsan9jad6kjdo.demo.cms.va.gov/node/33108/edit)
- [Figma prototype](https://www.figma.com/file/3ysYRmbHbJ2d0auvFDiBgF/Event?node-id=0%3A1)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Adding to current sprint as a stretch, but probably a Sprint 39 issue.

**Comment by kevwalsh** [comment]
Closing this, we'll need to create a new one later when we get back to this.
