### ISSUE TITLE
Swap old top task node with new node upon publishing of new node

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6072]
## User Story or Problem Statement

As a publisher of newly hardened content, i want the content I publish to replace its corresponding non-hardened legacy content, including archiving, taking over its URL alias, and possibly even its menu item, and updating any links that point to the old node IDE, without having to do anything manually.

### Background

We learned a lot from publishing 90 Policies pages with the newly hardened content model, replacing old VAMC policies pages. 
* Swapping out URL aliases was confusing and laborious. 
* links in rich text pointing to the legacy node had to be updated manually. 
* Legacy nodes had to be archived manually. 
* Each VAMC System Policies Page had to be created manually. 

How might we make this a smoother process? 

## Acceptance Criteria
- [ ] We have a reusable method for swapping out VAMC Detail Pages with newly hardened content types

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
