### ISSUE TITLE
Support accordions in KB articles

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6074]
## User Story or Problem Statement

As a KB user, i want concise pages for skimability, and some content to be only visible if it's relevant.

## Acceptance Criteria
- [ ] USWDS/VADS style accordions are supported in two paragraph types in the KB 
  - [ ] Accordion group
  - [ ] Q&A Section (when accordion is chosen)
- [ ] Our approach to accordions is abstracted out enough to support the above two paragraph use cases, but also for other use cases (eg views rows, etc)

## Implementation steps
Drupal theming

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
