### ISSUE TITLE
Add "dismissible"  boolean field to banner content type, defaults to TRUE

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6085]
## User Story or Problem Statement

As a Veteran, i want to be able to dismiss a banner. 

As an editor, i want to be able to disable the default dismissible nature of VA.gov banners, and set the persistence. 

from /block/42
<img width="1368" alt="Edit_custom_block_Coronavirus_site-wide_alert___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/128955256-4d867bef-82d8-4f21-aa11-d4de9f5e9e62.png">

## Acceptance Criteria

Matching the UI from the current alert block
- [ ] ~A new field  boolean `field_dismissible`  is added to banner content type~ Swirt removed this requirement in favor of a streamlined single field.
- [x] A new text (list) field `field_dismissible_option` is added  to banner content type, 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
Should this just be one field?  That way we don't have to make the other one an optional requirement and the Front end doesn't have to deal with a four states (2 on each field)?
1. permanent (not dismissable)
2. Dismissable - reappears every session
3. Dismissable - one time

**Comment by ethanteague** [comment]
> Should this just be one field? That way we don't have to make the other one an optional requirement and the Front end doesn't have to deal with a four states (2 on each field)?
> 
> 1. permanent (not dismissable)
> 2. Dismissable - reappears every session
> 3. Dismissable - one time

I would agree, _however_ the existing pattern (used by alert blocks) has two blocks. It would be a bigger lift (for front end) to introduce a new pattern.

**Comment by swirtSJW** [comment]
They are rebuilding the pattern anyway though because the block method is going away.   What's the right call from a UX point of view?  @kevwalsh @rachel-kauff    We are rebuilding this, I'd rather get it right from the get go than persist with the existing method just because it is existing.

**Comment by rachel-kauff** [comment]
<img width="661" alt="Screen Shot 2021-08-12 at 9 40 30 AM" src="https://user-images.githubusercontent.com/41017988/129235099-eb9d6d8e-91e6-4c17-a2ca-b346177fb41c.png">
<img width="661" alt="Screen Shot 2021-08-12 at 9 41 11 AM" src="https://user-images.githubusercontent.com/41017988/129235141-5bab67fa-af99-407c-9e5a-05e6eadef103.png">

**Comment by rachel-kauff** [comment]
(Haven't landed on the perfect field label, but here's some ideas)

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6094 has been merged.
