### ISSUE TITLE
Increase Tugboat volume size from 2TB to 4TB

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#6092]
## Background

As a Tugboat administrator, I want to not have to nitpick which environments I have to delete. This is a followup from #4129. Use instructions in https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/devops/tugboat-on-premise-installation.md#docker-volume-increase-instructions-for-4tb-adjust-accordingly. 

## Acceptance Criteria

- [x] Tugboat Docker Volume size is increased to 4TB
- [x] Previews still work as expected after upgrade

## Tasks

- [x] Update Terraform code to include new volume size
- [x] Communicate maintenance window to #cms-supprt and #vfs-platform-support
- [x] [Increase volume size](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/devops/tugboat-on-premise-installation.md#docker-volume-increase-instructions-for-4tb-adjust-accordingly)

**Comment by acrollet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6092?planning-poker) with ZenHub @indytechcook @ndouglas @ElijahLynn @olivereri

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/cea7048e-4d7e-442d-aee6-98767eaa06ee)

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/39df8445-6925-4474-9094-69229b03587c)

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/9072e547-f5d4-4797-b527-743a1e6fa0d6)
