### ISSUE TITLE
Add "Main KB article" field to Product taxonomy

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6103]
## User Story or Problem Statement

Product taxonomy terms are going to be everywhere in the CMS, including visible on most KB articles. Instead of building out content design tools (paragraphs etc) on Product taxonomy term pages, it makes sense to make a KB article the canonical landing page for each taxonomy term, and just leverage its content components.

## Acceptance Criteria
- [x] Each product has a canonical KB article that contains the product landing page content in the KB
  - [x] New single value entity reference field `field_kb_landing_page` "Knowledge base landing page" allowing only references to KB landing pages. 
- [ ] Clicking on a product taxonomy term takes a user to the KB article for that product
   - [ ] should this be a redirect to the node? 
   - [ ] or do we use the /taxonomy/term/997 page as the page, enable layout builder for those pages, and embed the node 
     - [ ] ensure that layout builder view can be embedded in another layout builder  
     - [ ] set pathatuo to product taxonomy terms to `/help/[term name]` 
    

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Closed via #6158
