### ISSUE TITLE
Display product terms on KB articles 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6105]
## User Story or Problem Statement

Blocked by making KB product terms multivalue

Related to #6103, Product landing pages in KB driven by product taxonomy

As a KB user, i can click on a product tag and be taken to its KB landing page. 

@rachel-kauff  will upload new design for KB article template

## Acceptance Criteria
- [ ] Clickable product terms are visible on KB pages and search results, and themed per design above
- [ ] Terms do not appear on product landing page (can be done with layout builder overriding, which is already the case)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
closing this since we have a research study going on currently this solution may not fit the appropriate HCD recommendations.
