### ISSUE TITLE
Theme process list paragraph type in KB per design system

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6106]
## User Story or Problem Statement

As a KB user, i want easy to follow how-tos. 

![Screenshot_2021-08-12__3_44_PM](https://user-images.githubusercontent.com/643678/129259316-7fd0cfa1-1f02-418a-911b-e845eb3f95b4.png)

Beth did some work visible in node proofing of `page` content type.  Might be worth looking at a process list in the node proofing experience of a benefits detail page.

## Acceptance Criteria
- [ ]  Process lists in node view of KB article looks the same as they do on VA.gov (see [design system](https://design.va.gov/components/process-list))

## Implementation steps
Drupal theming

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
