### ISSUE TITLE
"Before you start" (aka eligibility filter) for KB articles, featured content component

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6107]
## User Story or Problem Statement

As a KB article, i know if the article is for me or not. 

<details><summary></summary>

KB design (ignore the white box, just the blue box here)

![Linking_from_the_editorial_experience_–_Figma](https://user-images.githubusercontent.com/643678/129255229-fd2be536-74f6-43ec-8389-0f8674b21a16.png)

VA.gov benefits page

![How_To_Apply_For_VA_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/129255316-6c1d1240-535a-49ed-a7b5-7af43043f01a.png)

</details>

## Acceptance Criteria
- [ ] Copy config from `page` content type (Benefits Hub page) for `field_featured`, a pretty flexible paragraphs field.
- [ ] Theme the field like on va.gov (alert background only component)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
This may be a bit too advanced of a solution for now. Enhancements for KB could start with landing pages by product.

**Comment by EWashb** [comment]
Per the KB research completed on 2/13/24, the indication of who an article applies to in the above mockup could provide a useful mental model for users. I will keep this open only as a reference for redesign @gracekretschmer-metrostar. However, pieces of this may no longer apply to our path forward and we might consider creating new tickets with proper references.
