### ISSUE TITLE
Automatically fix broken links to email addresses

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6113]
## User Story or Problem Statement

As a CMS editor, I wish to link to email addresses without having to know that a `mailto:` prefix is required, so that I can accomplish my tasks without additional training.

As a CMS engineer, I wish to not have to switch context to fix broken links whenever possible, so that I can provide greater value to veterans.

## Acceptance Criteria

- [ ] Valid email addresses found in `href` properties of `a` elements have `mailto:` automatically pre-pended when not already present

## Implementation steps

#5376 may provide an effective pattern for meeting this use case. Suggested algorithm:

If the contents of an href meet the following criteria, prepend `mailto:`:
- No protocol given
- Does not begin with `/`
- Contains an `@` symbol (including `%40`?)
- Is a valid email address

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

**Comment by swirtSJW** [comment]
Semi-related to https://www.drupal.org/project/node_link_report/issues/3104861
