### ISSUE TITLE
Make moderation_state filterable in GraphQL

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6118]
## User Story or Problem Statement

As a graphQL user I would like to filter by moderation_state values so that I can build a preview experience that shows draft items but not archived items.

Currently the CMS does not allow to filter by moderation_state and throws a internal error if the query is attempted.

The patch from this issue makes it possible to filter and query moderation_state
https://www.drupal.org/project/drupal/issues/3025164#comment-14190333

With the patch applied, the query is successful.

## Acceptance Criteria
- login as admin
- [ ] Go to /graphql/explorer
- [ ] paste in and execute the query
```
{
  nodeById(id: "736") {
    entityBundle
    entityId
    title
    reverseFieldListingNode(limit: 500, filter: 
      {conditions: 
        [
          {field: "type", value: "event"},
          {field: "moderation_state", value: "archived", operator: NOT_EQUAL}          
        ]},
      sort: {field: "changed", direction: DESC}) {
      entities {
        ... on NodeEvent {
          title
          status
          moderationState
          fieldDatetimeRangeTimezone {
            value
          }
        }
      }
    }
  }
}
```

## Implementation steps
<optional>

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
