### ISSUE TITLE
Implement recurring events

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6122]
## User Story or Problem Statement

As an editor of a recurring event, i have an intuitive editorial experience so that i understand how to make changes to events that repeat. 

Cutover method
| Current                         | [2.0a   (shell game in GraphQL Resolver)](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7170)    |            2.0b (~2 weeks later) |
| ------------------------------ | ------------------------------------------------------------------------ | ------------------------------------- |
| fieldDateTimeZone (object)    |     fieldDateTimeZone (most upcoming from date object)   | fieldDateTimeZone (array of objects) |
|                                      |           pseudofieldDates (array of objects)         |                                       |

## Acceptance Criteria

- [ ] Needs extracting from  the designs created in #6067, as well as the outcome of the FE designs. 
- [ ] No merging without a change management plan in place (#6066, #6073, #6349)

## Implementation steps
Form theming., smart date config

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
