### ISSUE TITLE
Remove Hudson Valley migration endpoint 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6125]
## Acceptance Criteria
- [ ] VA Hudson Valley endpoint has been removed from TeamSite operating status migration

## Implementation steps
<optional>

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
