### ISSUE TITLE
Improve staff profile selectors on paragraph type and leadership list page

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6136]
## User Story or Problem Statement

As a VAMC editor adding a staff profile to a VAMC detail page or a Leadership List, i should be able to find staff profiles easily. 
![Screen Shot 2021-08-16 at 2 30 06 PM](https://user-images.githubusercontent.com/643678/129612401-7f74fb66-41a0-44d1-a2aa-a67ca319859c.png)

## Acceptance Criteria
- [x] "Entity reference: Staff profiles" views display is added to admin/structure/views/view/content_entity_reference_source
  - [x] Results should appear like "[node title] - [office]", eg "[Ethan Teague] - [VA Walla Walla health care"]  
- [x] Staff profile paragraph type is updated to use this views display, with autocomplete (not a select list)
- [x] Leadership List content type is updated to use this views display

## Implementation steps
Drupal views and field config. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
