### ISSUE TITLE
Editorial experience design for banner content type

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6147]
## User Story or Problem Statement

As an editor of banner nodes (for now, OPIA editors for homepage banner, primary JoshT, and sitewide content team editors of Covid Vaccine banner), i have clear guidance and intuitive experience for adding and updating Very Important Content on VA.gov. 

### General guidance

TBD which banner is sorted higher in different situations (out of scope for now)

## Acceptance Criteria
- [ ] Expectations are set about publishing / content release before and after the editor saves 
- [ ] CMS design principles are met for banner content type
- [x] Link to KB article and training [in submission guidelines?]
- [ ] Any links in the form open in new window, and link text is updated to indicate that.
- [x] Clear rules about what banners are for are listed in the submission guidelines - What to use this for / what not to use this for
- [ ] Engineers can implement new designs.
- [ ] Recommendation for proofing experience #6016 (should we theme the content [as per design system](https://design.va.gov/components/alertboxes))?

### Path field (stretch, should be broken out into a separate issue)

(Probably) supported regex for paths field

- exclusions / blocks
- wildcards

![Screenshot_2021-08-17__11_26_AM](https://user-images.githubusercontent.com/643678/129755003-d8e5ca01-cb4d-4349-b782-e0046191b675.png)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

**Comment by rachel-kauff** [comment]
> - [ ] Editors can easily understand what type of banner to use 
cc: @kevwalsh Added another AC. Currently we have guidance in there about banner types, but there's room to make it quicker and easier to understand.

**Comment by rachel-kauff** [comment]
Edited this AC to include a hypothesis:

> Expectations are set about publishing / content release before and after the editor saves

**Comment by FranECross** [comment]
@jilladams I don't think this ticket is a PW task. Can you confirm or provide guidance? Thanks!

**Comment by jilladams** [comment]
It is indeed a PW ticket. We own both Promo Banners and Full Width Alerts, and this regexy experience for managing Paths where the banners/alerts should appear is present in both: 
https://prod.cms.va.gov/node/add/promo_banner
https://prod.cms.va.gov/node/add/banner

**Comment by FranECross** [comment]
Thanks, @jilladams I think I was confused by the CMS Team section with the Product Support Team checked. 😁😇

**Comment by jilladams** [comment]
Good call - that's legacy. Removed!

**Comment by FranECross** [comment]
Closing old iceboxed ticket.
