### ISSUE TITLE
Vet Center satellite locations do not show their moderation state

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6156]
## User Story or Problem Statement

It's not currently clear if Vet Center CAPs are active or archived. Or draft or in review for that matter.

![Hilo_Vet_Center___VA_gov_CMS](https://user-images.githubusercontent.com/643678/129793584-6c404d86-1299-4eb5-9613-574717961417.png)

## Acceptance Criteria
- [ ] Add moderation state to the table that is shown at the bottom of Vet Center dashboards

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
