### ISSUE TITLE
Impose 300 character limit on Facility notes fields in IEF form 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6159]
## User Story or Problem Statement

As an editor of facility status, i shouldn't be able to add facility status notes longer than 300 characters, because of limits on other systems including Lighthouse. 

**Default form**

![Manage_form_display___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/a16f7e74-1c0b-456d-b21b-3bb9b6f84ea5)

**IEF form**

![Manage_form_display___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/3f7a4d1d-ea7c-4d86-8323-78b01207c640)

## Acceptance Criteria
- [ ] IEF form config is updated to match the non-IEF form for VAMC facility 

## Implementation steps
Drupal config

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
