### ISSUE TITLE
Deprecate and/or reduce and standardize the use of Inline Entity Form 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6160]
### User Story or Problem Statement

IEF widgets have proven to be the source of numerous defects, unintended UX, confusing content moderation and governance workflows. 

* IEF forms differ somewhat from non-IEF forms (eg #6159)
* When editing entities inline, editors have to deal with content moderation on the inline entity and the main entity at the same time, which is confusing... what happens when one is set to draft and the other published?  
* form validation is sometimes bypassed #5981

How might we deprecate their use, or else impose configuration "rules" that avoid some of this technical debt or unintended effects? 

1. Audit existing uses (Identify areas of concern and patterns of each use)
2. Identify possibly replacements for each use, and design and implement those changes
3. If we decide to retain IEF, design and document and implement desired patterns 

### Affected users and stakeholders

Editors of the following products
* VAMC (eg VAMC banner form with IEF for facility status)
* Benefits Hubs forms (with IEF for reusable alert blocks)
* Vet Center editors (with IEF for Vet Center services)
* Other?

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] 👀 Needs design review because the work involves changes to labels or other design elements
- [ ] 🙈 Can be implemented without consulting design team members
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z

## Runbook
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by acrollet** [comment]
@ElijahLynn @ndouglas @indytechcook @olivereri Hey team! Can you please add your [planning poker estimates with ZenHub](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6160?planning-poker)

**Comment by FranECross** [comment]
@jilladams None of the tickets on this epic belong to the PW team; should this epic also belong to Facilities? Thanks!

**Comment by jilladams** [comment]
@FranECross I think all 3 teams are tagged because historically we've each had products that used the Inline Entity Form, so changes to it affect us. (We use Inline Entity, I think, for Reusable Q&As to be associated with other content types like FAQs, Resources & Support, etc.) But agree generally: this is mostly a Facilities / core CMS issue at this point. Removing PW label.

**Comment by davidmpickett** [comment]
@jilladams FYI - This used to very a very broad cross-team epic. I split out the Vet Center specific tickets into a [separate epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17708). All that remains here are tickets related to the VAMC System Operating Statue, so I updated title
