### ISSUE TITLE
MVP full width banners for homepage and Covid 19 banner

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6164]
### User Story or Problem Statement

As an OPIA content manager, i want to edit the homepage banner in the CMS, so that i don't have to depend on FE devs to get homepage banners out. 

As a sitewide content team.
* i want a clear experience for editing banners, that doesn't conflate them with alert blocks
* i want an easy way to place alerts on pages without have to specifying each node or URL

### Runbook 

- [x] CMS: #6173 
- [ ] CMS Config 
  - [x] #6007 
  - [x] #6181 
  - [x] #6015 
  - [x] #6305 
  - [x] #6175 
  - [ ] Remove the "Allow site visitors to dismiss banner for a single session" option for Persistence
- [x] #6179 (needs refining by @swirtSJW, see [slack thread](https://dsva.slack.com/archives/C52CL1PKQ/p1629471397294300)
  - [x] https://github.com/department-of-veterans-affairs/vets-website/pull/18316
  - [x] https://github.com/department-of-veterans-affairs/content-build/pull/441
  - [ ] PRs to support multiple business, different statuses https://github.com/department-of-veterans-affairs/component-library/pull/147 
https://github.com/department-of-veterans-affairs/vets-website/pull/18426
  - [ ] archive block 42, test the paths to see that they match prod 
  - [ ] test the homepage banner.

**Launch--mid-week september 8th**
- [ ] PW/Kelson: Remove the non-prod environment spec for new banner 
- [ ] unpublish old banner blocks

**Post-launch**

Remove deprecated code (post-launch)
- [ ] PW: remove FE support for alert-block-based banners.
- [ ] CMS: #6176 

Notifications for banners

Change management (can be post-launch?)
- [ ] CMS: Train OPIA team to edit homepage banner - (and how to handle failing content releases - text Dave)
- [ ] CMS: Train Sitewide content team 
- [ ] CMS: #6178 

Later iteration:
- [ ] CMS #6147
- [ ] Develop path/scope governance (scope field can be smarter? how to handle more than one banner? etc)
- [ ] Develop fulfillment request for new banners
- [ ] Support Announcements in CMS
  - [ ] Support promo banners in CMS
  - [ ] Support Welcome modals in CMS
- [ ] Support site downtime in CMS
- [ ] 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
I've moved a few issues to #6643 (next iteration) so that i can close this.
