### ISSUE TITLE
Audit image and description meta tags across all content types

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6171]
## User Story or Problem Statement

As a product team, i want to see what meta tag is for each content type, so that i can design improvements. 

## Acceptance Criteria

Drupal spec tool bundle tab has been updated so that each content type that has a corresponding VA.gov URL has filled in columns for the following:
- [ ] Current og:image setting	
- [ ] Example og:image	
- [ ] Current description meta tag setting	
- [ ] Example description tag

## Implementation steps
Audit and update spreadsheet. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by JayDarnell** [comment]
VAMC Facility content type - og:image: this one inherits from the content metatag definition so it is also set to use the field_media field and that field does exist on the content type. Sharing the item in slack and on facebook it appears to work but the META SEO plugin says an explicit definition is missing.

![Screen Shot 2021-10-13 at 4 13 33 PM](https://user-images.githubusercontent.com/21045418/137206033-b8158935-d2d3-4466-8c86-2b90da4fa2d5.png)

![Screen Shot 2021-10-13 at 4 10 45 PM](https://user-images.githubusercontent.com/21045418/137206052-03be8d0a-3fe4-4801-9408-01d2952809c0.png)

**Comment by JayDarnell** [comment]
**VAMC System content type - og:image**: this one inherits from the content metatag definition so it is also set to use the field_media field and that field does exist on the content type. Sharing the item in slack and on facebook it appears to work but the META SEO plugin says an explicit definition is missing.

![Screen Shot 2021-10-13 at 4 16 37 PM](https://user-images.githubusercontent.com/21045418/137206538-4a21fea2-a1fb-4d7c-97c1-5a1f32966d02.png)

![Screen Shot 2021-10-13 at 4 15 47 PM](https://user-images.githubusercontent.com/21045418/137206560-51b011ae-95e9-4137-b7aa-e5de0418098a.png)

**Comment by JayDarnell** [comment]
@kevwalsh best I can tell it looks like these images are all technically working but the og:image metatag value may not be explicitly defined on the front end. Comments above show the details for the image files. The details for the recommended description fields are in a new column in the spreadsheet. I believe this is ready for your review.

**Comment by JayDarnell** [comment]
One more item of related interest: I took some time to check how feasible it is to use the site logo as the og:image in metatag and it looks like token support is currently lacking: https://www.drupal.org/project/drupal/issues/2842780
