### ISSUE TITLE
Trigger content build when banner content type is saved as published or archived

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6175]
## User Story or Problem Statement

As an editor of the homepage banner, i want the banner to go out ASAP

## Acceptance Criteria
- [ ] Saving a banner node as published or archived, or deleting a published banner, triggers content build immediately.  
- [ ] Saving a banner as in review or draft does not trigger content build. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
State change truth table
| isPublished | previous state | new state | RELEASE |
| ---------------- | -------------------- | ------------- | ------------- |
| FALSE          | draft                 |  draft       |  NO          |
