### ISSUE TITLE
KB article: Editing full width banners

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6178]
## User Story or Problem Statement

As an editor of VA banners, I have access to documentation. 

For now, this is a stub, pre-editorial experience improvements or other iterations. 

This is already stubbed out at https://prod.cms.va.gov/help/full-width-banners 

## Acceptance Criteria

Documentation including
- [ ] Content strategy and guidelines (not duplicative of, and linking out to, https://design.va.gov/components/alertboxes)
- [ ] Governance (for now, only content admins can create banners, and set scope)
- [ ] Content release: Publishing / Archiving triggers content build
- [ ] Available on KB

## Implementation steps
Create KB article. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by xiongjaneg** [comment]
https://prod.cms.va.gov/help/full-width-banners

@kevwalsh Looks good to me except for the lonely bullet and I thought you said there was a typo but I didn't see it. Did you also mention wanting Swirt or Kauff to review before closing this issue?

**Comment by kevwalsh** [comment]
Fixed, and closing!
