### ISSUE TITLE
Replace links to media with rendered entities for all non-Rich text links to media entities on node proofing

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6188]
## User Story or Problem Statement

Following somewhat from #6172 

There's no good reason to link to a media entity from a node proofing page. All displays of media entities within node view / proofing pages should probably be rendered media, not links to media entities.

Example: 

On https://prod.cms.va.gov/concord-vet-center, the facility photo appears as a link to the media entity, instead of a thumbnail. 
Instead, it should match the image derivative used on the FE at https://www.va.gov/concord-vet-center

![Concord_Vet_Center___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133450493-2b62ef69-5cb0-4c63-ab40-de1447e302ed.png)

## Acceptance Criteria
- [ ] No entity types (paragraphs, nodes, blocks, etc) have any view displays that have media fields rendered simply as links to the media entity. 
- [ ] Rendered entities mirror the FE experience somewhat (images displayed with appropriate image style, download links displayed as download links
- [ ] Possibly: automated test to ensure that we always use "Rendered entity" or "Thumbnail" display widgets for media fields on node displays.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
