### ISSUE TITLE
Infrastructure support for Public Content API

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6236]
### User Story or Problem Statement

As a Veteran, I need CMS content to be available at any time, so that I can discover important information about the VA.

### Affected users and stakeholders

- All end users
- Developers using the Public Content API

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
- All CMS infrastructure must be Highly Available (no single point of failure)
- Code deployments must occur without downtime

## Acceptance Criteria
- [ ] CMS infrastructure can support uptime commitments (TBD)
- [ ]
- [ ] Implementation
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Load testing
- [ ] Metrics (How will we measure any improvements)
