### ISSUE TITLE
Move all #cms-team alerts to #cms-notifications channel

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6252]
## Description

As a CMS team member, I do not wish to have to monitor two channels for alerts, so that I can know where all notifications will be sent.

## Implementation

Review the [notification guidelines](https://github.com/department-of-veterans-affairs/va.gov-cms/commits/master/READMES/cms-alerts.md) doc and ensure that each alert follows guidelines and is sent to #cms-notifications

## Acceptance Criteria
- [x] No CMS alerts are sent to the `#cms-team` channel
- [x] All CMS alerts are sent to the `#cms-notifications` channel
- [x] All alerts follow [our notification guidelines](https://github.com/department-of-veterans-affairs/va.gov-cms/commits/master/READMES/cms-alerts.md)

## Tasks
- [x] Remove `@here` from CMS Periodic task job failed
- [x] Move PROD deploy failure notification from #cms-team to #cms-notifications, add `@here`
- [x] Review https://github.com/department-of-veterans-affairs/devops/pull/10140

**Comment by acrollet** [comment]
Examples of alerts currently sent to `#cms-team`:

- [Failed to deploy cms to vagov-dev!](https://dsva.slack.com/archives/CT4GZBM8F/p1630374106140000)

**Comment by ElijahLynn** [comment]
> Do we still want to keep these notifications going to #cms-team or move to #cms-notifications too? I wonder who finds them useful in the #cms-team channel?

Asked here > https://dsva.slack.com/archives/CT4GZBM8F/p1634598141312900?thread_ts=1634594786.312400&cid=CT4GZBM8F

**Comment by ElijahLynn** [comment]
Based on Slack discussion, I went with trying out tagging the `@sitewide-cms-team` Slack group in the `#cms-notifications` channel. I did that for the `Warn`, `Deploy Start`, `Deploy Success` messages which are of `medium` [alert type](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/READMES/cms-alerts.md), and for the `Deploy Failure` message to PROD I tagged the `@here` group as it is a `high` alert type, but for DEV|STAGING I did not include `@here` as that is `medium`. 

The pipe character | indicates an "either or" declaration. 


Warn: (PROD only, medium)
`@sitewide-cms-team Stand by, deploy for prod.cms.va.gov is coming up in ${params.release_wait} minutes. If you need to cancel the deploy you may do so at http://jenkins.vfs.va.gov/job/deploys/job/cms-auto-deploy/ within ${params.release_wait} minutes."`

Deploy Start: (PROD only, medium)
`@sitewide-cms-team Deploying cms|cms-test to prod.cms.va.gov. <URL of JOB>`

Deploy Success: (PROD only, medium)
`@sitewide-cms-team Successfully deployed cms|cms-test to prod.cms.va.gov. <URL of JOB>`

Deploy Failure: (PROD only, high)
`@here Failed to deploy cms|cms-test to prod.cms.va.gov! <URL of JOB>`

Deploy Failure: (DEV|STAGING only, medium)
`Failed to deploy cms|cms-test to dev|staging.cms.va.gov. <URL of JOB>`

**Comment by ElijahLynn** [comment]
> If tagging `@sitewide-cms-team` is too aggressive then we will have to work something else out.

I actually think we should create a new group name for this and let people opt-in. It is real easy to update the group in Slack and people can opt-in/out as they like. I think we can add and remove ourselves to groups. 

Maybe `@cms-notifications-medium`? `@here` is equivalent to `@cms-notifications-high`, fwiw.

**Comment by ElijahLynn** [comment]
If we are good with the above then https://github.com/department-of-veterans-affairs/devops/pull/10140 is good to merge.

**Comment by ElijahLynn** [comment]
Updated docs in https://github.com/department-of-veterans-affairs/va.gov-cms/commit/aa6a477d1121199bf1e833dee794391918a2d9dd.

**Comment by ElijahLynn** [comment]
I merged this and found one last thing to update, which is the `warn` step to be parameterized for the app name. 

e.g. this was for the `cms-test` app, notice the first message was the wrong app name, because it was hardcoded:

**Before:**
![image](https://user-images.githubusercontent.com/1504756/140234926-31c890d0-5548-4e97-8abb-66d09daaf52d.png)

**After:**
![image](https://user-images.githubusercontent.com/1504756/140234935-99e228e4-110a-4c7e-a617-e04c72c2aacc.png)



Need a review on https://github.com/department-of-veterans-affairs/devops/pull/10230 for merge.
