### ISSUE TITLE
All tests post information & error comments to Github PRs

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6254]
## Description

As a CMS engineer, I want to see the output of failed tests in comments on my pull reviews, so that I can quickly and efficiently address errors introduced by my code.

## Acceptance Criteria
- [ ] All tests should post comments with any errors or other useful information
  - [ ] `va/web/build`
  - [ ] `va/tests/status-error`
  - [ ] `va/tests/revision-log`
  - [ ] `va/tests/phpunit`
  - [ ] `va/tests/phplint`
  - [ ] `va/tests/check-cer`
  - [ ] `va/tests/behavioral`
  - [ ] `va/tests/accessibility`
  - [ ] `va/tests/behat`
