### ISSUE TITLE
Improve guidance for VAMC banner scope field

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6276]
## User Story or Problem Statement

The current guidance is confusing. The machine name `fieldAlertInheritanceSubpages` doesn't help. There may also be some FE issues. See [Slack thread](https://dsva.slack.com/archives/C01H29ERVJ7/p1630014344003100)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/643678/131237304-dd504796-390f-4ec8-b5cb-144b2ee9c3d0.png)

</details>

<details><summary>Possibly improvement</summary>

◽️ Show on all pages
Banner will display only on the home and operating status pages.

</details>

## Acceptance Criteria

- [ ] Field label and help text has been improved

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by Agile6MSkinner** [comment]
This epic never got any stories and was abandoned years ago. Closing.
