### ISSUE TITLE
Update phpmailer package

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6282]
## Description

As a CMS engineer, I need to update the phpmailer package, so that we do not depend on packages with security vulnerabilities.

## Acceptance Criteria
- [x] phpmailer has been updated to 6.5.0
- [x] update has been tested on a BRD env

## Tasks
- [x] Deploy branch to DEV
- [x] Send password reset email for account with an @va.gov email
- [x] confirm password reset email is received

**Comment by acrollet** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6282?planning-poker) with ZenHub @ndouglas @ElijahLynn @indytechcook @olivereri
