### ISSUE TITLE
<Summary of enhancement>

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6284]
## User Story or Problem Statement

Some content types should be deletable but non-administrators. Deleting certain content can have catastrophic results and should only be done by administrators. 

Who should be able to delete what? 

## Acceptance Criteria

Only 'admin' can delete :
- [ ] health_care_local_facility
- [ ] health_care_region_page
- [ ] vet_center
- [ ] vet_center_outstation
- [ ] vet_center_mobile_vet_center

other ACs tbd

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
I'm confused a bit by this title and the following description. **Shouldn't be deleted?

Meaning they currently are able to be deleted? Worth confirming
