### ISSUE TITLE
Re-platform the CMS hosting infrastructure

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6285]
## Problem Statement

The current BRD system is built around Jenkins and Ansible and standardizes a release process for the CMS. The CMS team is considering moving to Amazon EKS for hosting, or continue maintaining the current BRD system with certain upgrades. The team will evaluate multiple tools, considering implementation time, overall lifecycle maintenance, user experience, cost effectiveness and risk, and determine the best approach in support of the Accelerated Publishing initiative. 

### Hypothesis

We believe hosting the Drupal CMS on a new platform will improve the application's performance, scalability, and reliability, and also address some immediate security concerns.

### Goals

- [ ] Maintain high reliability, performance, and stability at all times
- [ ] Ensure scalability - approach will support containerization effort
- [ ] Ensure operating system security requirements are met (i.e. - security need to upgrade from PHP 7.3 to 7.4, and eventually PHP 8)

### Affected users and stakeholders

* CMS engineers

**Comment by ElijahLynn** [comment]
Rubber ducking doc on refactoring this Epic. https://docs.google.com/document/d/1JUSuEs0i6OTVAB93YnAB3SCkk-BtVxa5XgAo-jQi0n4/edit?usp=sharing

**Comment by cweagans** [comment]
I think we can close this and the associated child issues, right?
