### ISSUE TITLE
Hide Path field for non content admins on banner content type

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6305]
## User Story or Problem Statement

The path field is confusing and can't be edited by non-content admins. 

For now it should be hidden. 

## Acceptance Criteria
- [x] As a non content admin with access to editing node/33217 (eg user 30), i should not see the path field on the edit form (but i should still see Path values on node proofing)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Closing again after setting to high priority (sprint goal for Sprint 40, replacing 6105)
