### ISSUE TITLE
Enable styleguide module and page for vagovadmin theme

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6317]
## User Story or Problem Statement

As a designer, i can see the vagovadmin theme's default styles all in one place.

## Acceptance Criteria
- [ ] Styleguide is visible at /admin/appearance/styleguide/vagovadmin to anon users

## Implementation steps
- [ ] install enable styleguide module
- [ ] Set permissions to anon

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
