### ISSUE TITLE
On facility status save for "Normal", push NULL for more info. 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6318]
## User Story or Problem Statement

When a facility of any type is saved with an operating status of "normal"  the status info field should be maintained in Drupal, but we push NULL to Lighthouse.   

## Acceptance Criteria
- [x] On facility status save for "Normal", push NULL for more info
- [x] Across all facilty types (vamc, vetcenters, vba, and cemeteries) When status "normal" is selected, disable or gray out the more info field.  (could use UX guidance on this one)
- [x] When something other than "Normal " is chosen, any previously existing data in the more info is revealed.

![image](https://user-images.githubusercontent.com/5752113/161115068-5d13bb5e-5e04-4d41-b6c0-c3f4b3f39c6e.png)

 
## Implementation steps
Location of existing code docroot/modules/custom/va_gov_post_api/src/Service

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
