### ISSUE TITLE
Add additional logic about Facility status, linking Status options to the Status more info fields

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6319]
## User Story or Problem Statement

- As an editor of ANY facility when I set operating status to "normal" I want the status more info field to be hidden so that I don't get confused.

![image](https://user-images.githubusercontent.com/5752113/169072742-f7deb372-c326-4400-989c-1314c2d9b0d9.png)

- As an editor of ANY facility when I set operating status to anything other than "normal" I want the status more info field to be shown so that I can populate it.

## Acceptance Criteria

"Details" required for 
* Limited services and hours
* Notice.
* Closed

## Implementation steps

- [ ] JS ~hides~ _disables and empties_ field_status_more_info when "Normal" is selected on all Facility content types except Vet Center - Mobile Vet Center. 
- [ ] JS shows field_status_more_info when something other than "normal" is selected
- [ ] When an editor switches to Normal and back to Limited (without saving), the Details is restored. 
- [ ] When an editor saves as normal, the Details gets deleted. 
- [ ] When Details is empty, the field is not displayed on node view.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
This is the facility api side of this change.   https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6318

**Comment by suzanne-gray** [comment]
Here's a quick [content audit](https://docs.google.com/spreadsheets/d/1pARWM1W-DtsVRpH1WXIZPzM6Q_UNef6z-xy9rpkASUo/edit#gid=1516542428) of VAMC facilities that have an operating status of Normal and also have content in the Details field.
![Screen Shot 2022-05-23 at 3 31 21 PM](https://user-images.githubusercontent.com/90172187/169915199-fc64d903-3b08-406b-acad-1e5186205511.png)

**Comment by JayDarnell** [comment]
I'm running into a fairly significant issue which appears to be a bug where the visibility state works but the required state does not when working with radio buttons as the source for the state. I'm currently digging into this issue for some guidance (and possibly a patch) https://www.drupal.org/project/drupal/issues/2731991

**Comment by JayDarnell** [comment]
The following screenshot illustrates the exact problem. The required classes are not being properly applied to the target field.

![Screen Shot 2022-05-30 at 5 21 56 PM](https://user-images.githubusercontent.com/21045418/171060744-d6900788-35a1-4c17-b709-ab57f71acb21.png)

**Comment by JayDarnell** [comment]
I was unable to apply any of the patches from the issue above and rerolling them didn't fix the issue. As a result I've resorted to applying the required behavior in JS like we've done in other areas of the site.
