### ISSUE TITLE
Certain Vet Center services should be required and added to all Vet Centers

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6332]
## User Story or Problem Statement

As a Vet Center editor I need a specific set of health services populated by default on all Vet_Centers so that I do not need to be created by hand every time.

As a Vet Center editor I cannot remove required Vet Center services from my Vet Center.

## Questions that need refining:
Q: Permissions on removing required? A: Editors cannot remove. 
Q: What other content types need be covered ? (CAPS, outstations?) - Only Vet Centers for now.  
Q: If a service taxonomy editor checks the "Required Vet Center boolean" checkbox, what happens? A: Populates a service for every Vet Center where this doesn't already exist. - Dave
Q: If a service taxonomy editor unchecks the boolean? A: Nothing happens, except that an editor would be able to delete. - Dave
Q: Should required appear differently on the Vet Center editor interface? A: We can hide the Remove button for required services and update help text, for MVP. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
@kevwalsh list of required services:

- Addiction and substance abuse care
- Community engagement
- Couples and family counseling
- Grief and bereavement
- Mental health 
- MST
- PTSD
- Returning service member care
- Suicide prevention
- Veteran connections

**Comment by kevwalsh** [comment]
Moved remaining issues to #4623 and #4426
