### ISSUE TITLE
SPIKE: Lat/long lookup for facility data that do not already have it. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6333]
## User Story or Problem Statement

VBA facilities do not have lat/long data. 

But we have street addresses. 

How might Drupal become the source for lat/long data?
* Geolocation module in Drupal can work with various services
* Census bureau has a lookup service that may be free to use, that has an API
* other potential sources: Carto, Mapbox, Google Maps, etc. 

## Acceptance Criteria
- [ ] We have identified various technical solutions to getting lat/long data stored locally in Drupal for facilities that we do not have it, with pros/cons. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
This will be solved, as currently defined, via #8683, so i'm closing it and removing it from the epic #5872
