### ISSUE TITLE
Improve paragraphs editor for admins on Centralized Content node form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6340]
## User Story or Problem Statement

As an admin editing centralized content, i want all the features of the Paragraphs EXPERIMENTAL (_all caps theirs_) form widget so that i can't collapse all, duplicate fields, "add above", etc, and edit content more quickly. 

## Acceptance Criteria
- [ ] "Content" field has been set to to use the following config at admin/structure/types/manage/centralized_content/form-display

![Manage_form_display___VA_gov_CMS](https://user-images.githubusercontent.com/643678/132059816-ab102198-e398-46b4-baa5-e50df2dade2f.png)

## Implementation steps
drupal form config 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
