### ISSUE TITLE
Content model for facility nonclinical services to support Top Tasks

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6341]
## User Story or Problem Statement

On various Top task pages, editors will be adding service locations (admissions offices, medical records offices, copay offices for biling and insurance, etc). Unlike facility health services, the other content type has service locations, there is not facility context. So editors will need to specify a facility for each service location. 

<details><summary>Screenshots</summary>

## Proposed iteration on Service Location bundle

![Create_VAMC_Facility_Health_Service___VA_gov_CMS](https://user-images.githubusercontent.com/643678/132061529-1c310739-80b2-4bf9-bfed-c2b32ed4ea35.png)

## Billing and insurance

Eg https://www.va.gov/northern-california-health-care/billing-and-insurance/ 
![Billing_And_Insurance___VA_Northern_California_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/132061189-487f3603-f873-41ac-942c-381a67459670.png)

## Medical Records

https://www.va.gov/northern-california-health-care/medical-records-office/

![Medical_Records_Office___VA_Northern_California_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/132061144-bc0a0632-90b0-45ba-bdea-7ca17812c4a1.png)

## Register for care

https://www.va.gov/northern-california-health-care/register-for-care

https://www.va.gov/butler-health-care/register-for-care

![Register_For_Care___VA_Northern_California_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/132061041-726992a7-04c5-475c-bd96-cecc5b8f20f9.png)

![Register_For_Care___VA_Butler_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/132061117-edec1593-5917-45c4-8b12-0270f2a97ad4.png)

</details>

In order to reuse the service location component, I propose we add a Facility field to the Service Location paragraph type. On facility health service nodes, this field could be hidden (and we can discuss populating it via the context of the form, see ACs below).  On other places where the Service Location paragraph bundle is used, it would be a required field. 

## Acceptance Criteria
- [ ] New `field_facility` entity reference field is added to the top of the `service_location` bundle form, with the same entity reference view used on node/add/health_care_local_health_service), 

On VAMC Facility Health Service
- [ ] `field_facility` is hidden on the paragraph form (but populated via the parent?)
- [ ] Should "Use the facility's street address" boolean then pull from the field on the paragraph or from the paragraph's parent node? 
- [ ] TBD: Implications for lighthouse and www.va.gov templates?

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
The implementation took a different path than the original spec here. See #6866.
