### ISSUE TITLE
Remove "Nearby Vet Center and Outstations" field and replace with guidance about guidance about automatic 80 mile catchment

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6371]
## User Story or Problem Statement

A decision by Facilities team was made to remove the "curating" of nearby Vet Centers and Outstation, and to replace with automatic 80 mile zone. This may get adjusted in the future (and possibly allow local Vet Center editors to set their radius). 

## Acceptance Criteria
- [ ] Nearby Vet Center and Outstation field has been removed
- [ ] New guidance has been added 

## Implementation steps
Blocked by readiness of FE work in https://github.com/department-of-veterans-affairs/va.gov-team/issues/27813

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
