### ISSUE TITLE
Remove "Nearby Vet Centers and Outstations" field and entity browser

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6372]
## User Story or Problem Statement
See #6371 

## Acceptance Criteria
- [ ] Field has been removed
- [ ] Entity browser and any associated config (views) have been removed. 

## Implementation steps
Config

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
