### ISSUE TITLE
Prevent content release during migration and bulk operations

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6379]
## User Story or Problem Statement

As a engineer concerned about stressing out out content release system I would like to have a flag (semaphore) set as state so that certain processes like bulk operations and migrations can set the semaphor to prevent content releases from being triggered immediately.

Examples:  
1. If 6 facilities have updates to their statuses in the facility status migration, that should not trigger 6 content releases.
2. If VAMC upgrade is publishing a new system via Views Bulk Operation, those published should not trigger content releases mid-flight.

This issue on ViewsBulkOperations is a decent example.  https://www.drupal.org/project/views_bulk_operations/issues/2978075#comment-12649202  Note: patch 13 is the example using states, not the use of database locks (in patch 17) as they do not work correctly with memcache (see my comment in that issue).  Patch 13 is using some outdated code that needs updating but I think it is a better implementation.

## Acceptance Criteria
- [ ] Bulk publishing a facility does not cause content release.
- [ ] Submit the patch to the issue https://www.drupal.org/project/views_bulk_operations/issues/2978075 or create a new issue that creates the semaphore but not the blocking of concurrent runs.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
I started tinkering with this but ran out of time.

here is a change tp patch 13 is needed to get the messaging working
```
    // Check presence of the VBO semaphore to avoid use in concurrency.
    $vbo_semaphore = $this->state->get('views_bulk_operations_semaphore');
    if ($vbo_semaphore &&  ($this->time->getCurrentTime() - $vbo_semaphore < static::SEMAPHORE_MAX_DURATION)) {
      /** @var \Drupal\Core\Messenger\MessengerInterface $mesenger*/
      $messenger = $this->messenger();
      $messenger->addWarning($this->t('A bulk operation is being used in concurrency, please retry a few seconds later.'));
    }
```

**Comment by TheBoatyMcBoatFace** [comment]
@swirtSJW is this still relevant in current Content Release?

**Comment by swirtSJW** [comment]
Related to the three examples some things have changed

> If 6 facilities have updates to their statuses in the facility status migration, that should not trigger 6 content releases.

The facility status migration only runs for one system now (Lovell) and soon that will be removed,  This use case is no longer a good example.

>If VAMC upgrade is publishing a new system via Views Bulk Operation, those published should not trigger content releases mid-flight.

All VAMCs have launched and VAMC upgrade team is no more.  However we are likely to have similar rollouts of the new VBA product so there is still some concern.   However, given that content releases are now triggered based on queued requests, this model resolves most of the concern around bulk publishing.

So I think we can close this issue as "no longer needed" because it has been inadvertently solved by other changes to our content release process.
