### ISSUE TITLE
Design research: Proofing experience for Benefits Detail Pages - improve it? extend it? remove it? 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6390]
## User Story or Problem Statement

Context: This might be better asked in a broader "What is the future of proofing?" research, but a smaller study/spike might facilitate some short term improvements. 

We made a bet in Q1 2021 via #1088 (see other research in the proofing epic #936)  that providing additional features in the node proofing experience to editors, especially metadata about the content blocks (paragraphs),  would help them understand the content structure so that they could edit it more efficiently.  

We focused first on Benefits Hub Detail page content as a POC. 

We gathered feedback from sitewide content team members, which was largely positive. 

Were we on to something? Do those editors appreciate these features? Should they be extended and improved or removed. 

There are a few bugs minor bugs and tech debt associated with this POC--the CSS applies a bit too broadly, including the content edit form instead of just node view. Tech debt is that we support two different experiences in proofing (Benefits Hub Detail Page vs everything else), when we should probably only support one. 

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
