### ISSUE TITLE
Send closed to lighthouse on facility archive

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6392]
## User Story or Problem Statement

As lighthouse data integrity engineer  I need the cms to send us a "closed" status whenever any type of facility is archived so that the cms data reflects the status in the CMS.

As a CMS data integrity engineer I need the status in the cms to be changed to "closed" on the node so that the csm status matches what is sent to lighthouse.

Question:  What should happen to the facility status more info??

## Acceptance Criteria
- [ ] on facility archive, node facility status is set to closed
- [ ] on facility archive,  teh closed status is pushed to lighthouse
- [ ]  facility status more info should be _____

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
This may have already been accounted for but should be verified.
