### ISSUE TITLE
Add EFF fields to 3 top task pages

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6396]
## User Story or Problem Statement

As an editor of a top task page, i can see the nationalized content inline within the editorial experience, so that i can craft my localized content accordingly. 

As a FE developer, i can access nationalized content via a subquery of a top task page, so that i can build a template.

## Acceptance Criteria
- [ ] All centralized content fields on Register for care, Billing and insurance, Medical records have their EFF fields on their respective content types. 

## Implementation steps

Add `field_cc_[fieldname]*` fields to content types, with UUIDs. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by swirtSJW** [comment]
Ended up having to resolve this in order to move forward https://www.drupal.org/project/entity_field_fetch/issues/3236368
