### ISSUE TITLE
Update CMS Product sheets and upload to KB landing page for each product

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6398]
## User Story or Problem Statement

As a CMS team member or OCTO team member, i have overviews of each product with content managed in the CMS.

## Acceptance Criteria
- [ ] [Product sheets](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/VA-CMS-Product-Sheets.pdf) are updated with latest info
- [ ] Product names match those in the CMS Product taxonomy (the source of truth for product names)
- [ ] Single PDFs or PNGs uploaded to their respective KB landing page

## Implementation steps
Airtable update data, export PDF, upload to KB. Create draft KB landing pages if necessary. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by stefaniefgray** [comment]
@EWashb @dawnpruitt Found this Product Sheets ticket from Kev 🥺 

I'd like to close it in favor of opening up a new one about updating the product sheets -- but should we be updating them? Are they relevant/useful anymore? Is Dave interested in new product sheets?

Not sure how to proceed while cleaning up User Support ZenHub board with @TroyA6 🤔

**Comment by EWashb** [comment]
@stefaniefgray sorry I'm many months late. 

while I don't know if we need product sheets right now, it would be helpful for us to keep this information someplace. Possibly we should consider adding the info in these product sheets to our monthly reporting or even to share in ToT. I think the information captured could be valuable again. 

This really should live with the CMS Team right now. I'm going to add the label. Tagging @productmike and @BerniXiongA6 for awareness as I move officially into our backlog

**Comment by BerniXiongA6** [comment]
Makning note to self @BerniXiongA6 to add this into refinement activities in future sprint/s.

**Comment by EWashb** [comment]
We will likely head toward product-specific landing pages rather than sheets per the recent research completed on the knowledge base.
