### ISSUE TITLE
Update high level content model

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6399]
## User Story or Problem Statement

As a content strategist or other CMS team member, i have a visual of a high level content model that represents how content types map to products. 

## Acceptance Criteria
- [ ] [High level content model doc](https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8) has been updated
- [ ] Link has been added to onboarding template. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
i updated the “high level content model” diagram with R&S, Vet Center, and a few other details.  https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/content-model/20210917-VAgov-high-level-content-model.png
