### ISSUE TITLE
Update github issue labels

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6401]
## User Story or Problem Statement

As a CMS team member, i have a coherent set of labels in github

## Acceptance Criteria
- [ ] Product names match those of product sheets 
- [ ] [Github practices](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/github-practices) has been updated accordingly. 

## Implementation steps
Github config. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by kevwalsh** [comment]
Updated this with @cmaeng and @acrollet
