### ISSUE TITLE
COVID surge transitions and onboarding

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6405]
### User Story or Problem Statement

As a new CMS team member, I need to be able to see and track my progress through the onboarding process so I can get a sense of how much needs to be done.

As an existing CMS team member, I need to be able to see and track what my level of effort is to assist folks in the onboarding process so that I can account for that in my capacity.

### Affected users and stakeholders

* Incoming new CMS team members
* Existing CMS team members
* OCTO-DE
* VFS teams we support

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

## Acceptance Criteria
- [ ] New team members have the onboarding template accessible and explained
- [ ] Existing team members have the context to be able to project how much effort they will need to put in per sprint

## Runbook
- [x] Create onboarding ticket for each new member
  - [x] Suzanne Gray
  - [x] Jay Darnell
  - [x] Chris Craig
  - [x] Tim Cosgrove
- [x] Explain the process to each new member
  - [x] Suzanne Gray
  - [x] Jay Darnell
  - [x] Chris Craig
  - [x] Tim Cosgrove
- [x] Schedule meet and greet for each new member and their onboarding buddy
  - [x] Suzanne Gray
  - [x] Jay Darnell
  - [x] Chris Craig
  - [x] Tim Cosgrove

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Core Application Team`
- [x] `Product Support Team`
