### ISSUE TITLE
Improve quality of link text within CMS managed content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6411]
## User Story or Problem Statement

How might we guide CMS editors to create useful, usable, and accessible link text in their content, which explains their target (where they are going) and purpose (what they are doing there). 

Ideas so far:
- Qualitative and quantitative audit of existing editor submitted links to evaluate current state of link text, and to guide priorities & solutions. 
  - By product.
  - By internal/external.
  - By link editing form widget (Link field, Rich text link tool, Button component, etc). 
  - By adherence to target/purpose spec. 
- Training (several small training videos to add to all products training curriculums?)
- KB article(s?) - [see existing articles with "link" in their title](https://prod.cms.va.gov/admin/content/audit/knowledge-base-article-administration?title=link&moderation_state=All&products=All) 
- Improved rich text link widget (may need to be done in coordination with #1969) 
- Improved widgets for structured links (drupal link field, linkit) (to inform #3767) 

See [Josh Kim and Angela Fowler's presentation from September 13 2021](https://docs.google.com/presentation/d/14AwUoFOg_Ix1Txl9oePtPD1ntOpylBWwBJMYq9f5vmo/edit#slide=id.ge8045de9aa_0_0) for ideas and guidance. 

Related issues/epics
* See also #4952 (action links, which we don't support yet but we may)
* #1964 (probably a different widget, but still a link in rich text)

Guidance should align with [Content style guide](https://design.va.gov/content-style-guide/we-us-you)'s approach to we, us, you. 

## Implementation steps

TBD

## CMS Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by EWashb** [comment]
@laflannery I'm cleaning up the backlog. How do you feel about closing this one?

**Comment by laflannery** [comment]
I think this can be closed, I have a more holistic disovery ticket and I boiled the ideas down to [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10274#issuecomment-1301167999) because the ideas are good and things that I have thought of doing so I don't want to lose them they just haven't been priority yet.
