### ISSUE TITLE
Improve communications on how to update Facility data

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#6413]
## User Story or Problem Statement
CMS editors have a hard time understanding what does in to updating data for their facilities. Currently, we have information and guidance in a KB article and in application help text.

As a CMS editor, I need to be able to know how to update my facility's data or who to contact so that what's reflected on the website is accurate.

## Acceptance Criteria
- [ ] The number of helpdesk tickets associated with updating facility data is reduced to zero

## Implementation steps
- [ ] The [existing KB article](https://prod.cms.va.gov/help/vet-centers/how-do-i-update-my-facilitys-basic-location-data) has clear guidance on how to update what data
- [ ] The help text provided links to the associated KB article
- [ ] The Lighthouse team owns the maintenance of the KB article
- [ ] Access to care wait time data in particular, needs more specific guidance

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
