### ISSUE TITLE
Rename "promo block" to make namespace room for promo banners?

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6424]
## User Story or Problem Statement

As an editor, i need a distinct name for each type of thing in the content model, so that i am not confused between promo blocks

Will editors be confused between promo blocks and promo banners? 

Promo blocks are used on va.gov homepage, CLP pages, megamenus, and benefits hub right rails. 

<details>
<summary>Screenshots of promos and promo blocks</summary>

Homepage
![VA_gov_Home___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133276432-78fb392a-90a6-468e-a073-edbb89926a1e.png)

Megamenu

![VA_gov_Home___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133276489-4202a9a7-6d08-49d1-8e09-bf23d86c64a3.png)

Benefits hub landing page 

![VA_Health_Care___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133276589-8b713d4e-eba9-471e-a2c0-58fc3b220806.png)

Campaign Landing Page

![Recognizing_LGBTQ__Veterans_During_Pride_Month___Veterans_Affairs](https://user-images.githubusercontent.com/643678/133277081-32120dd2-0f2c-4f29-8dca-d49fcc1f0a50.png)

</details>

## Acceptance Criteria
- [ ] Decision is made about renaming promo blocks, or not. 
- [ ] If we rename, what should they be called. "Cards"?

## Followup issues, if necessary

- [ ] If we rename promo blocks
  - [ ] Engineering issues 
  - [ ] KB article updates
  - [ ] Existing users are updated as necessary. CLP editors may not need this change management, but editors of homepage, benefits hub, and megamenu promo blocks may need an update. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by FranECross** [comment]
Closing old ticket as obsolete
