### ISSUE TITLE
Remove option on Banners to  "Allow site visitors to dismiss banner for a single session"

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6430]
## User Story or Problem Statement

As an editor of alert banners i have some clear guidance and no confusing choices to make. 

![Create_Banner___VA_gov_CMS](https://user-images.githubusercontent.com/643678/133447635-467f5cb1-df82-49b2-90b8-e51508211fb1.png)

## Acceptance Criteria

- [ ] "Allow site visitors to dismiss banner for a single session" option has been removed 

## Implementation steps
Update config. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`
