### ISSUE TITLE
Links to KB articles or other resources open in new window, and link text is update to indicate that behavior

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6431]
## User Story or Problem Statement

As a CMS editor clicking a link on a form, i want it to be sure that clicking a link will open it in a new tab so that i don't lose any work in my form. 

## Acceptance Criteria
- [ ] All links on forms have been been updated so that they open in a new tab, and the link text has the following appended to it: ` (opens in a new tab)`
- [ ] Automated test is written to ensure that we do not introduce new links that do not follow this pattern. 

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by rachel-kauff** [comment]
YES! This looks good to me. I did an informal poking around, and it looks like currently some links in help text do open in a new tab, while others didn't. Would be great to enforce consistency here.

**Comment by rachel-kauff** [comment]
@kevwalsh Is adding a link out icon a possiblity?

**Comment by rachel-kauff** [comment]
Maybe with something like this? https://www.drupal.org/project/extlink

**Comment by kevwalsh** [comment]
@rachel-kauff i've used that module in the past, although not usually for the editor experience. 

Are you thinking icon instead of, or in addition to, the "(opens in a new tab)" text?

**Comment by rachel-kauff** [comment]
@kevwalsh Just seeing what our options are. I also asked Josh and Angela whether one is better than another. I'm always looking to reduce text on screen, but of course if it's better to put the warning in the link text, then we'll do that.

**Comment by rachel-kauff** [comment]
Instead of

**Comment by rachel-kauff** [comment]
[WebAim on external link icons](https://webaim.org/techniques/hypertext/hypertext_links#new_window):
> Sometimes these icons are used to indicate that a link is to an external site, rather than that it opens a new window, so there's potential for some confusion. As with file types above, these icons (with appropriate alternative text) must appear within the link rather than just after it.

**Comment by rachel-kauff** [comment]
ok never mind about the link icon! 

From Angela:

> It’s my understanding that the external link icon tells you that the link is going to a page outside of the current site, say from va.gov to the centers for disease control website. It does not tell you whether or not the link opens in a new tab. I could be wrong about that though.

From Josh:

> To sighted folks, icons can be a hit or miss in terms of whether or not folks will understand it; (opens in new tab) would be preferred ideally :pray::skin-tone-3:
