### ISSUE TITLE
Discovery: Allow users to select a `vets-website` branch with which to build tugboat previews

### ISSUE THREAD

**Issue by acrollet** [department-of-veterans-affairs/va.gov-cms#6434]
## User Story or Problem Statement

As a front end developer, I need to be able to select a `vets-website` branch when building content previews on tugboat, so that I can verify new functionality works correctly and connect it to a content-build branch/pr

As an engineer on any team I am able to set up a demo environment or PR environment where I am using code from CMS, content-build, and vets-website that has not been merged to main(s) yet.

## Tasks
- [ ] Determine how `vets-website` builds actually occur, and evaluate this in light of the present content release system.
  - [ ] With what steps?
  - [ ] Are there any build tools necessary that aren't currently present on Tugboat?
  - [ ] Are there any data sources necessary that aren't currently present on Tugboat?
  - [ ] Are there any credentials or other sensitive pieces of information that aren't currently present on Tugboat?
  - [ ] Is the current form as used in `vets-website` local development suitable for Tugboat?
  - [ ] Do we need to support performing builds on current checkouts, e.g. if an engineer makes a change within Tugboat and doesn't want to push the commit upstream?
  - [ ] If not, do we need to refactor the current local/Tugboat content release process to support an extension to cover `vets-website`?
    - [ ] If so, how extensive is this? What will it involve? What is the best way of managing this?
  - [ ] Will this be complicated by the need to support changes related to Accelerated Publishing?
    - [ ] If so, how complicated?
  - [ ] Do we need to support specifying a content-build branch _and_ a `vets-website` branch?
    - [ ] If so, how is this currently managed in `vets-website`?
    - [ ] What complications does this flexibility introduce into our system?
    - [ ] How can we avoid repeating ourselves?
  - [ ] Do we need to _newly_ support local checkouts of `vets-website`?
    - [ ] How does this impact the Tugboat base preview flow?
    - [ ] How does this impact the DDEV flow?
    - [ ] How does this complicate the workflow for other environments (i.e. staging, prod)?
    - [ ] Does this have impacts for security or performance?
    - [ ] Does this introduce additional requirements for the GitHub token used in Tugboat environments?
    - [ ] How might this impact infrastructure, e.g. disk usage?
- [ ] Determine dependencies between the 'content-build' and 'vets-website' branches.
  - [ ] Because this is a deliberative process, this shouldn't often be an issue, but this might/will impact how errors need to be propagated for transparency.
- [ ] Determine the requirements for the backend implementation for managing `vets-website` builds.
  - [ ] How is this designed in a way that:
    - [ ] maximizes testability?
    - [ ] maximizes transparency to engineers?
    - [ ] propagates errors effectively?
    - [ ] is documentable and comprehensible?
    - [ ] is the least surprising?
- [ ] Are current systems well-situated to handle this?
  - [ ] What changes are needed to the `FrontendBranchAutocompleteController`?
    - [ ] Do we need to refactor it? I've somewhat anticipated this by specifying that current repo-specific services are named accordingly, but are any further changes needed?
    - [ ] How can this class be made more testable?
    - [ ] How can this class be more transparent? Do we need a progress indicator?
    - [ ] How can this class propagate errors more effectively? (Currently, errors are not reported except through the watchdog log, making the form somewhat mysterious)
- [ ] Determine the requirements for the frontend form implementation.
  - [ ] Do we need design/UX input or can we just hack something out of the current form?
  - [ ] Can the form elements be refactored in such a way that we can test those components independently?
- [ ] Determine followup actions:
  - [ ] What needs to be documented?
  - [ ] What needs to be communicated, and to whom?
  - [ ] Is any cleanup needed?

## Acceptance Criteria
- [ ] Local and Tugboat environments are able to build content previews using:
  - [ ] `main` `content-build`
  - [ ] specific `content-build` branch
  - [ ] specific `content-build` PR
  - [ ] `main` `content-build` and `main` `vets-website`
  - [ ] `main` `content-build` and specific `vets-website` branch
  - [ ] `main` `content-build` and specific `vets-website` PR
  - [ ] specific `content-build` branch and `main` `vets-website` branch
  - [ ] specific `content-build` branch and specific `vets-website` branch
  - [ ] specific `content-build` branch and specific `vets-website` PR
  - [ ] specific `content-build` PR and `main` `vets-website` branch
  - [ ] specific `content-build` PR and specific `vets-website` branch
  - [ ] specific `content-build` PR and specific `vets-website` PR
- [ ] All dependencies, data sources, tools, and credentials necessary for 'vets-website' builds are present and properly configured on Tugboat.
- [ ] All dependencies, data sources, tools, and credentials necessary for 'vets-website' builds are present and properly configured on local environments.
- [ ] All changes on BRD environments have been made and are backward-compatible.
- [ ] Staging environment (including post-deploy tests) is not adversely affected; tested on CMS-Test
- [ ] Production environment (including content release) is not adversely affected
- [ ] The system provides transparent feedback on the build process, including progress indicators and error messages.
- [ ] The new functionality does not introduce significant security risks, performance issues, or excessive disk usage.
- [ ] The change does not disrupt the regular content release system on production or local environments.
- [ ] Documentation is updated to reflect these changes and new functionality.
- [ ] All necessary parties have been communicated with about these changes.

**Comment by jilladams** [comment]
The Public Websites team would like to strongly vote for the priority of this issue. Currently, if we have a CMS page that includes a React widget / vets-website code, it's not possible (as far as we've found) to stage + test that content prior to publishing to production. + @ryguyk for awareness of this ticket.

Our notes on the subject of "dark launches" or how to manage pre-production testing: https://docs.google.com/document/d/1AQkzwPGdaQ8px5Xp88c8wpUOC_ePkSce6DUbA1qlZNA/edit#heading=h.26leo03661re

**Comment by jilladams** [comment]
@EWashb @productmike For awareness: we're recommending prioritizing this task as a postmortem action item from the React outage on Monday: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/975/files

**Comment by EWashb** [comment]
Looks like this one is on @ndouglas radar for upcoming improvements, so I'm moving to the proper pipeline for requirements definition

**Comment by jilladams** [comment]
😭 🎉  Yay.

**Comment by productmike** [comment]
@EWashb For clarity, are you seeing this as something that needs further definition from us around the definition of done? If not, I think we can move this into the prefinement column in preparation for an upcoming refinement sesh.

**Comment by EWashb** [comment]
@productmike feel free to move to prefinement. I don't believe there's anything that needs further definition. At least from my perspective there isn't.

**Comment by productmike** [comment]
Done.

**Comment by ndouglas** [comment]
Added some tasks and expanded on the ACs a bit.

**Comment by productmike** [comment]
Re: 8/2 planning, this will have to be a discovery ticket 1st, with a fast-follow implementation ticket. Won't make sprint 90, but will keep prioritized in the READY FOR SPRINT column for future sprint. Hopefully, sprint 91 if bandwidth allows.

**Comment by jilladams** [comment]
Thank you thank you thank you thank you for prioritizing this work!! The dreamy future is nigh! 😍

**Comment by BerniXiongA6** [comment]
Hi @ndouglas and company, if we weren't able to get to this in S94, I can carry over to S95. Lmk, thanks!

**Comment by ndouglas** [comment]
Hi @BerniXiongA6 it's in progress but will rollover due to factors. I'm going to complete this ticket -- as a discovery ticket, as I originally intended -- in S95 but actual implementation might not be complete until S96. I'm doing that work now too, but there's a lot changing. Just want to warn you 🙂

**Comment by BerniXiongA6** [comment]
@ndouglas Ruh roh!! OK, will roll over to S96. Thanks!
