### ISSUE TITLE
Improve workflow for enforcing a change of facility operating status gets published

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6438]
## User Story or Problem Statement

As an editor I need a clear path of what needs to happen if I make a facility operating status or status more info change when a facility is already published.

## Acceptance Criteria
- [ ] Definition of what ought to happen, if anything, when an editor makes a change to a published facility's operating status /more Info but saves it as a draft rather than published.

Essentially we have to decide whether we want this to:
1.  Force the state to published if they alter the fields.  
2.  fail validation and prevent save if the moderation state is not set to published
3.  Give a warning of some kind
4. Do nothing, because they should understand the basics that unpublished changes do no go anywhere.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Core Application Team`
- [x] `Product Support Team`

**Comment by mmiddaugh** [comment]
This has been addressed
