### ISSUE TITLE
Support Vet Center "official name" to CMS and migrate from Facility API

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6446]
## User Story or Problem Statement

 As a Content admin, i can override the official name with a Veteran-friendly one, so that the front end can use the plain language one as the h1.

This is only the case for <5% of Vet Centers. Priority for this epic is based on when we'll start to set these up. There are no non-plain language names in District 1. The one in District 5 has been dealt with. Risk is that things could go backward.

## Acceptance Criteria
- [ ] URL should use the plain language name (/prescott-vet-center)
- [ ] Field should only be editable by Content Admins, disabled for others
- [ ] Concerns that need to be addressed: Facility API parity, URL aliases.

## Implementation steps

Implementation idea: "Official Vet Center name" field that Facility API migrates into. Available to GraphQL/FE for h1s. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`
