### ISSUE TITLE
Audit tool VAMC system service for headings and "care we provide" text

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6455]
## User Story or Problem Statement

questions we want to answer

1. How many nodes (and which ones) have/have not the "Care we provide at [system]" in heading or otherwise?
1. How many nodes (and which ones) have other headings (list of nids and editors)

## Acceptance Criteria
- [ ] We have answers to the above questions available via the UI at /admin/content/audit/care-we-provide (with CSV export?)
- [ ] Audit can be accessed in the application by Administrator and Content Admin, no one else

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by rachel-kauff** [comment]
@kevwalsh Is it safe to assume this is a totally manual audit?
