### ISSUE TITLE
Remove Care we provide h3 from all "non-drifted" VAMC system services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6456]
## User Story or Problem Statement

See #4799 

## Acceptance Criteria
- [x] `<h3>Care we provide at [Something] health care</h3>`has been removed from DB in VAMC, for VAMC system health services where that string is the first string in the text, and no other markup unique to the the "Rich text" . 
- [x] Nodes get a revision message `Removed "Care we provide" heading` by CMS user `CMS migrator`. 
- [x] PR is marked as Do Not Merge. This PR may be built on, or go into a feature branch. 
- [x] Report is provided about impact (number of VAMC system health service nodes) affected

Note: The changes can be QA'd at /admin/content/audit/vamc-system-service-audit

## Implementation steps
TBD

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Not quite complete 
https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6889#issuecomment-967657412
