### ISSUE TITLE
Reduce opportunities for poorly structured or missing headings

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6499]
### User Story or Problem Statement

Editors should not be depended on for choosing what headings to use (except, possibly, on "Detail pages" where the content structure is less defined. )

#4799 will remove h3s from VAMC System health services content. What other places can editors currently add h3s, but shouldn't? 

### Affected users and stakeholders

* Editors of most CMS products 

### Hypothesis

The limited rich text editor, which doesn't allow editor-defined headings will suffice for most situations. 

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.
