### ISSUE TITLE
Sitewide CMS team - Sprint 42 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6502]
🥅   — Sprint goals (pending Sprint planning)
💧  — Drupal engineering
🎓  — Training / Change management / KB
📟 — Helpdesk
💡 — Design
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

### Context

New team members!
Q4 planning, so a shorter sprint. 

### #6405  Team transition

- [ ] #6398
- [x] #6408 
- [x] #6409

### #6164 Support homepage banner in CMS / refactor existing alert blocks

- [x] #6176 💧

### Content API support for VAMC left nav

- [x] #6561 💧

### #3151 3 VAMC Top task pages

We need to unblock Facilities team ASAP on at least two pages.

- [ ] Finish implementation of content model 🥅  

### Support "VA Lovell Federal health care" name change

- [x] #6512 

### VAMC upgrade team support

- [x] #6532 

### Staff profiles

- [x] #6363 (mostly finished, db update script)💧
- [ ] #6549  Front end starter ticket.🌱

### #4028 Centralized content editorial experience 

- [ ] #4016 💧 

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6414 (tracking issue for LH team)
- [x] #6417 💧 (done but not merged, blocked by LH updates to KB)

### #4799 VAMC Care we provide 

- [ ] #6455 
- [ ] #6456 (Stretch, depends on outcome of #6455, and PR merge depends on FE change) 💧

### #6371 Remove Nearby Vet Center Locations 

Goal is to complete this by 2nd week of October when District 1 is onboarded. 

- [ ] #6372 💧
- [ ] #6374  🎓 

### #6553 Vet Center dashboard usability research

- [ ] #6554   💡 🌱  🥅 
- [ ] Stretch: #6556  💡🌱 

### #6446 Support Vet Center "official name" 

Ready to go
- [x] #6453 💧 🌱
- [ ] #6447 🌱   

Blocked by editorial experience design
- [ ] #6449 💧 🌱
- [ ] #6454 💧 🌱 (stretch, depends on #6453)

## Other 

- [x] #6171 💧
- [ ] Improve alerts content block (refine)

## CMS account admin

- [x] #6504 💧
- [ ] #6558 
  - [x] #6563 📟  🥅  

## CMS Knowledge Base

- [ ] #5714 📟

## Refine / estimate

Customer service
- [ ] #6558 📟  💧

Facilities
- [ ] #6571 
  - [ ] #6574 📟
  - [ ] #6572 💡
  - [x] #6573 💧🥅
  - [ ] #6575 💧
- [ ] #6553 💡
- [ ] #4856 (Followups from #4369, TBD)  💧 
- [ ] #6450
- [ ] #6392 
- [ ] #5072
