### ISSUE TITLE
Remove caching from admin/people view.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6504]
## User Story or Problem Statement

As a trainer I need an accurate display of when people have been active in our system so that I can assess their progress.

Currently our people View is caching based on tags which does not expire the cache when someone logs in.
https://prod.cms.va.gov/admin/people

## Acceptance Criteria
- [ ] Caching on /admin/structure/views/view/user_admin_people is set to `none`
- [ ] Looking at the list should show accurate details for somone who just logged in, while you were already logged in as admin and had already visited /admin/people.

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`
