### ISSUE TITLE
Deprecate Prometheus Usage

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#6533]
### User Story or Problem Statement

As a CMS Pleatform team engineer, I need to deprecate usage of Prometheus, so I can continue having monitoring and alerting when Prometheus is EOL.

### Affected users and stakeholders

* Developers of Platform CMS team
* Developers of Platform Operation team

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### Assumptions
* Prometheus is going to be EOL by Platform Operations
* Any current usage of Prometheus can be achieved in other available tools (Datadog, Sentry, Loki, Grafana)

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] CMS Platform team is not using Prometheus
- [ ] Legacy Prometheus use cases are handled using supported Platform services

## Runbook
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify current Prometheus use cases
* Create issues for migration of each
ype or other design stimula)
- [ ] Implementation
- [ ] Documentation

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform Team`
- [ ] `Sitewide CMS Team`
