### ISSUE TITLE
Vet Center Dashboard Usability Study

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6553]
## Background

We designed and implemented a dashboard for Vet Centers in Q1 2021. 
The design intent was to...
- Provide access to everything a Vet Center editor might need to do in one place, and use the Vet Center page to do so.
- Help Vet Center editors orient to their top tasks through cards that use icons and descriptions.
- Bridge the gap between the content model and users' mental model through action links in cards that jump link to relevant parts of a form.
- Allow editors to review satellite locations and their operating statuses at a glance so they can make see what might need updating.

### User Story or Problem Statement

As a Vet Center editor, I want insights into my content and access to my top tasks so that I can:
* Manage Featured content
* Manage Services
* Manage visitor information
* Manage satellite locations
* Manage Operating status
* See listing of facilities

### Purpose of study

* Understand whether our design hypothesis for the Vet Centers dashboard design are valid
   - We can bridge the gap between users' mental model and the content model by jump linking from cards to forms
   - Icons (in cards) help users recognize the piece of content they need to edit
   -  Surfacing satellite locations and their operating status prompts users to make necessary adjustments
* Build a backlog for a potential future iteration of the Vet Centers dashboard
* Identify design hypothesis and patterns that may help us design the VA Medical Center product dashboard.

### Affected users and stakeholders

* Vet Center editors

## Associated activities/processes

- User recruitment (w/ help from Michelle M) - sprint 42 and 43
- Research plan - spring 42
- Conversation guide - sprint 43
- Study pilot - sprint 43
- Study sessions - sprint 44
- Synthesis and readout - tbd
- Followup: Refine backlog for Vet Center dashboards, Refine future VAMC dashboard work

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [x] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`
