### ISSUE TITLE
CMS account user audit and offboarding policies and procedures

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6558]
## Background

There is risk associated with editors not being offboarded (whether they lose access to VA network, or shift jobs within VA). Some of this may be perceived, but that can cause users to trust the system less. 

### User Story or Problem Statement

As a CMS user who has not accessed the CMS for a certain period, my account should be deactivated. 

As a CMS user whose account will be automatically deactivated, i want to receive a notification, so that i can take action if needed. 

As a CMS user who account is being deactivated, i want to receive a notification when my account is deactivated. 

As a CMS user who will be offboarded, I should be able to trigger that process (or someone should be able to trigger it for me)

As OCTO, I want a clear policy on the sunsetting of accounts. 

**Assumption:** 

Should be the same across all products. 

## Possible approach (needs issues)

- [ ] Research / discovery
  - [x] Create report of users sorted by last access date for analysis 
  - [ ] Comparative analysis with other similar use cases (eg Federal gov Drupal sites)
  - [ ] Service design - where does this fit within the broader CMS user journey, what are the right touchpoints.
  - [ ] Work with OCTO product owner to determine other business requirements
- [ ] Create policy for when and how to block or cancel accounts
  - [x] Determine location for policy (~github~, new CMS knowledge base article called "Offboarding policy" with links from individual product's account admin policies (eg https://prod.cms.va.gov/help/vamc/vamc-cms-account-administration-policy) , as well as https://prod.cms.va.gov/help/cms-basics/about-cms-account-permissions)
  - [ ] Include section for privileged users (any users who have a role that with the word "admin" in it)  
  - [ ] Include section for non-priviledged users (any other users)
  - [ ] Determine when content authorship should be reassigned to another account, if at all
  - [ ] Determine how many warnings user should receive
  - [ ] Write contents of account block notification email(s).
  - [ ] Include business process for requesting offboarding
  - [ ] Include business process for other triggers that should start offboarding (like emails being bounced)
  - [ ] Determine means for automatically or manually blocking accounts
    - [ ] Evaluate suitability of Auto Purge Users or User Expire modules
  - [ ] Review policy with @davidconlon @rachel-kauff @kevwalsh, and others TBD
- [ ] Implement CMS account offboarding policy
  - [ ] Publish policy in Knowledge Base and link to it from various CMS account admin policies
  - [ ] Create fulfillment request procedures (may depend on #6451)
  - [ ] Reassign existing content created blocked users to accounts, per policy
  - [ ] Implement email notification(s)
 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by chriscraiga6** [comment]
Exported Prod User List and wanted to note our oldest accounts here. 

Last Accessed: 7 Months and 3 weeks ago or never
Oldest account: 2 Years 7 months

**Comment by rachel-kauff** [comment]
@kevwalsh Some hypothesis about further stories (which may need some validation):
"As a supervisor or peer in the same section or facility as the person whose account is being deactivated, I want to know so I can:
- confirm this step of their onboarding is complete
- prompt the person to reactivate their account
- assign someone else to take over that person's responsibilities"

This might become redundant with a well-considered account admin role for each section (who has the power/responsibility to periodically audit accounts themselves).

**Comment by timcosgrove** [comment]
All issues in epic are complete. Closing.
