### ISSUE TITLE
Make published state revealed as part of graphQL menuByName query

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6561]
## User Story or Problem Statement

As consumer of the menuByName query I need to know whether a menu item is to a published node or not so I know whether to render the menu item on the front end.

As a consumer of the menuByName I need to have menu items to unpublished content available to me so I can accurately render content on preview.

I should never see menu items to archived nodes.

Related to 
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/29782
* https://dsva.slack.com/archives/C0FQSS30V/p1632770700465500

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by mpelzsherman** [comment]
Suggested edit:

> I need to know whether a menu item is to a published _entity_ or not

**Comment by swirtSJW** [comment]
This query might do the work needed 
![image](https://user-images.githubusercontent.com/5752113/135169980-dc53ed0e-f1be-4617-b0d2-107aa8c65127.png)

but in order to run that query we need to install https://www.drupal.org/project/graphql_menu

**Comment by swirtSJW** [comment]
```
{
  menuByName(name: "va-alexandria-health-care") {
    description
    name
    links {
      ...MenuItem
      links {
        ...MenuItem
        links {
          ...MenuItem
        }
      }
    }
  }
}

fragment MenuItem on MenuLink {
  expanded
  description
  label
  url {
    path
  }
  entity {
    ... on MenuLinkContent {
      linkedEntity(language_fallback: true, bypass_access_check: true) {
        ... on Node {
          entityPublished
          moderationState
        }
      }
    }
  }
}

```
