### ISSUE TITLE
Q3 Account Admin Report

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#6563]
## User Story or Problem Statement

Report for product owners/stakeholders on existing accounts in CMS to determine which accounts need to be turned off or left on.

## Acceptance Criteria
- [x] Active users
- [x] Inactive users
- [x] Roles
- [x] Sections

## Implementation steps
TBD

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [x] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`
