### ISSUE TITLE
Q4 training improvements

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#6564]
## User story
As a Drupal CMS user, I need to be able to provide timely, accurate information to Veterans and other stakeholders using Drupal CMS.

## Acceptance criteria
- [ ] training reflects the current state of Drupal CMS
- [ ] training reflects the questions users are asking helpdesk about
- [ ] training reflects accessibility, VA content style, and plain language guidelines

## Design principles
Which CMS design principle is at play?

 - [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
  - [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
  - [ ] Approachable: Offers friendly guidance over authoritative instruction.
  - [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
  - [x] Empowering: Provide clear information to help editors make decisions about their work.
