### ISSUE TITLE
Add a VistA/Cerner EHR toggle to VAMC system

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6571]
## Background

VistA is the legacy electronic health record (EHR) system, [Cerner is the new one](https://www.hcinnovationgroup.com/cybersecurity/article/13028723/breaking-va-will-replace-vista-with-cerner-ehr-and-intends-to-create-integrated-platform). Each health system will cut over for the next 5 years. 

This is high priority because Spokane is already using Cerner and they are blocked from going live until this is supported. Other VAMCs (Cleveland?) are switching to Cerner soon.

### User Story or Problem Statement

As an admin, I can toggle VAMCs between VISTA (default, legacy system) and Cerner  so that this status is available through the content API for various Veteran products and tools. 

As a content editor, i can see whether my system is set to VISTA or Cerner, and how this is setting governed, and what it affects for Veterans (possibly a link to a KB article), so that i can verify it and request changes if necessary to the right organization. 

As a CMS helpdesk, i have a standardized workflow (request fulfillment) for processing requests.

Example Veteran story (there are others, TBD): As a Veteran, "Make an appointment" component links to the right tool (eg _My VA Health_ not _My HealtheVet_). Possibly others: Refill prescriptions, medical records?

### ACs

- [x] VAMC system content type has `field_vamc_ehr_system`, default value is VISTA, other value is Cerner
- [ ] Clear guidance to editors about what this field does and how to request a change to it. 
  - [ ] Request fulfillment process is documented in a KB article if necessary.
- [x] Spokane has been set to VISTA

### Affected users and stakeholders

* VAMC editors
* Admins
* Helpdesk team

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform Team`
- [x] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
When is the next VAMC going to switch? What is the roadmap for transitions for all VAMCs? Can we count this as done for Q4 knowing that there is some additional UI work needed?

**Comment by kevwalsh** [comment]
@cmaeng I created #7158 for a follow up and and moved the remaining issues #6572 and #6592 to it
