### ISSUE TITLE
CMS User Report Last Accessed in Fixed Time

### ISSUE THREAD

**Issue by chriscraiga6** [department-of-veterans-affairs/va.gov-cms#6602]
## User Story or Problem Statement

As a member of the helpdesk, I need the CMS user report to generate the last accessed date in a fixed time instead of relative so I can more efficiently manage user accounts.

## Acceptance Criteria
- [ ] When the CSV button is pressed, the output displays last accessed field in fixed time (Ex: 13-SEP-21 10:16 AM)

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
