### ISSUE TITLE
Add style options to wysiwyg for action links

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6604]
## User Story or Problem Statement

As an editor I need to be able to set an action link with ckeditor so that I can make use of [action links in the VA Design system](https://design.va.gov/experimental-design/action_links)

- Add class setting to class="vads-c-action-link--blue" 
- Add class="vads-c-action-link--green"
- ~class="vads-c-action-link--white"~  Leaving this one off for now.  Not sure if we can implement this one without also being able to set class="usa-background-dark" on the  wrapper.  It looks problematic on the design system page right now in terms of padding 
![image](https://user-images.githubusercontent.com/5752113/135685487-a1433078-8571-41d9-80ba-8ff3e9f27398.png)

## Acceptance Criteria
- [ ] On a selected link in the ckeditor can select "Action link - primary" and have it assign class="vads-c-action-link--green"
- [ ] On a selected link in the ckeditor can select "Action link - secondary" and have it assign class="vads-c-action-link--blue" 
- [ ] CSS in ckeditor makes them look like https://design.va.gov/experimental-design/action_links
- [ ] CSS on page makes node view (proofing) look like https://design.va.gov/experimental-design/action_links
- [ ] must allow for adding hreflang and lang properties in the source mode and not eat them on save or re-edit.
- [ ] Node view also should get the Action link CSS. (eg [this Centralized content node](https://prod.cms.va.gov/centralized-content/vamc-system-register-for-care-page-content))

```
<a
  className="vads-c-action-link--blue"  
  href="#"
  hreflang="es"
  lang="es"
>En Español</a>
```

## Implementation steps
<optional>

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
I added an AC for node view.
