### ISSUE TITLE
[Events] Update Events View to Filter by Date Created

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#6605]
## User Story or Problem Statement

See VA-HELP 1968

As an Outreach Hub representative, I would like the ability to view how many events were posted to the Outreach Hub within a set date range.

## Acceptance Criteria
- [ ] Can go to the Events view within Drupal and filter by date created: https://prod.cms.va.gov/admin/content/events

## Implementation steps
Events view should filter by or display the creation date, not just the date the event was last updated.

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [x] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by FranECross** [comment]
Closing per Dave C. Filters will be revisited with Events v3 and a new ticket created. Closing
