### ISSUE TITLE
Scheduling, Appointments, and referrals should all be Unknown

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6616]
[for consideration in Sprint 43]

## User Story or Problem Statement

As a VAMC editor adding a facility health service, the default values should be "Unknown" for referrals, walkins, and online scheduling, so that i can create the content without filling out the value. 

## Acceptance Criteria
- [ ] Three fields have had their default value set to "Unknown". 

## Implementation steps
- [ ] 

![Screenshot_2021-10-05__10_59_AM](https://user-images.githubusercontent.com/643678/136054026-9c5c3079-9c2e-4c36-97ee-83f48812b7e9.png)

## Design principles

Which [CMS design principle](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/cms-product-design-principles.md) is at play?
- [ ] Purpose-driven: Creates an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] Efficient: Removes distractions and create clear, straightforward paths to get the job done.
- [ ] Approachable: Offers friendly guidance over authoritative instruction.
- [ ] Consistent: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] Empowering: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by rachel-kauff** [comment]
Mock up of different use cases w/ new label: https://www.figma.com/file/R06MIbS5jKqjZqY4UnTnTy/VA-Medical-Centers-forms?node-id=0%3A1
