### ISSUE TITLE
Update logic around concerns for title and official name

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6623]
Our switch to using the field_official_name as being the one in sync with facility api means that some of the concerns need to be divided amongst the two fields

### Questions:  
- Will outstations, mobile, or caps ever have services connected to them?

### title
- [x] no longer populate or alter this by the actual migration (covered by #6454, listing here for visibility)
- [x] Becomes editable by content_admin users
- [ ] populating the menu item (which controls the alias)
- [x] from #6454 On vet_center node save, if title is not populated then populate with the value of field_official_name (this will cover the case of migration which must no longer be able to populate the title field at all. Otherwise we will end up with nameless nodes.

AC
- [ ] NEW Upon Update of  node:vet_center, update the aliases and titles for  vet_center_facility_health_servi IFF the vet_center title changed.

### field_official_name
- populated during migration (covered by #6453, listing here for visibility)
- This field becomes visible but locked and placed inside the Facility Data section 
![image](https://user-images.githubusercontent.com/5752113/136286884-200b1bdc-bb73-4932-aa93-05fc2ec61685.png)

- [ ] ~POSSIBLY (depending on when this ticket is performed), update logic for https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6519 to track changes to both the title AND the field_official_name~

**Comment by jefflbrauer** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/6623?planning-poker) with ZenHub @cweagans

**Comment by kevwalsh** [comment]
@JayDarnell @swirtSJW to evaluate for duplicateness

**Comment by swirtSJW** [comment]
I think most of these were covered by other tickets.  The only one I have to double check is the menu title poulation.

**Comment by JayDarnell** [comment]
Is the title field actually editable? Was that done elsewhere because I don't think I tackled that need.

**Comment by JayDarnell** [comment]
<img width="1060" alt="Screen Shot 2021-11-22 at 11 48 13 AM" src="https://user-images.githubusercontent.com/21045418/142901669-233b56e0-39e6-4d01-839b-6bf54a93b4eb.png">

**Comment by kevwalsh** [comment]
This was handled via #6449 and #6453
