### ISSUE TITLE
Sitewide CMS team - Sprint 43 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6634]
🥅   — Sprint goals (pending Sprint planning)
💧  — Drupal engineering
🎓  — Training / Change management / KB
📟 — Helpdesk
💡 — Design
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

### Context

New team members!
Drupal GovCon
Q4 epic refinement

### #6405  Team transition

- [ ] #6398 

Onboard
- [ ] Lynn
- [ ] David
- [ ] Denise 

### #6164 Support homepage banner in CMS / refactor existing alert blocks

- [x] #6176 💧  (Done but merge blocked by FE)

### #3151 3 VAMC Top task pages

We need to unblock Facilities team ASAP on at least two pages.

- [ ] Finish implementation of content model 🥅  

### Support "VA Lovell Federal health care" name change

- [ ] Followup to #6512, we need to prepend "VA "

### Staff profiles

- [ ] #6549  Front end starter ticket.🌱

### #4028 Centralized content editorial experience 

- [ ] #4016 💧 

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6414 (tracking issue for LH team)
- [x] #6417 💧 (done but not merged, blocked by LH updates to KB)

### #4799 VAMC Care we provide 

- [ ] #6455 
- [ ] #6456 (Stretch, depends on outcome of #6455, and PR merge depends on FE change) 💧

### #6371 Remove Nearby Vet Center Locations 

Goal is to complete this by 2nd week of October when District 1 is onboarded. 

- [ ] Followup to  #6372, delete the fields 💧
- [ ] #6374  🎓 

### #6553 Vet Center dashboard usability research

- [ ] Stretch: #6556  💡🌱 

### #6446 Support Vet Center "official name" 

Ready to go
- [ ] #6447 🌱   
- [ ] Steve's issue for how to handle these two fields.

Blocked by editorial experience design
- [ ] #6449 💧 🌱
- [ ] #6454 💧 🌱 (stretch, depends on #6453)

## Other 

- [ ] Improve alerts content block (refine)

## CMS account admin

- [ ] #6558 

## CMS Knowledge Base

- [ ] #5714 📟

## Refine / estimate

Customer service
- [ ] #6558 📟  💧

Facilities
- [ ] #6571 
  - [ ] #6574 📟
  - [ ] #6572 💡
  - [ ] #6575 💧
- [ ] #6553 💡
- [ ] #4856 (Followups from #4369, TBD)  💧 
- [ ] #6450
- [ ] #6392 
- [ ] #5072
