### ISSUE TITLE
Prepend "VA " to "Lovell Federal health care" menu name

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6635]
## User Story or Problem Statement

~#6512 incorrectly specifed "Lovell Federal health care" for the new menu name. It should have been "VA Lovell Federal health care"~

UPDATE: This is not true. the problem was that the VAMC system node was titled  "Lovell Federal health care" but should have been titled "VA Lovell Federal health care". Same for the Section name.

## Acceptance Criteria
- [ ] ~Menu label for Lovell Federal health care has been udpate to  "VA Lovell Federal health care"~
- [ ] ~Machine name can remain as is.~
- [ ] VAMC system node title has been updated to "VA Lovell Federal health care"
- [ ] Section name has been updated to "VA Lovell Federal health care"

## Implementation steps
~Update a string in config, and associated behat test. ~

Edit content

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
I just updated thed ACs, which were invalid. This was just a content fix, which i just did on prod.

**Comment by kevwalsh** [comment]
Reopening because i noticed a small error in the menu description.
