### ISSUE TITLE
Delete nearby Vet Center fields that were previously hidden.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6637]
## User Story or Problem Statement

#6606 hid the "Nearby Vet Centers and Outstations" field, but did not delete it. 

## Acceptance Criteria
- [ ] "Nearby Vet Centers and Outstations" field should be deleted
- [ ] Any FE dependency is removed

## Implementation steps

Drupal config, possibly some GraphQL change. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
