### ISSUE TITLE
Accelerated Publishing: epic and ticket review & cleanup

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#6678]
## Description
The existing epics and tickets that fall under the Accelerated Publishing initiative may no longer reflect our current understanding of the work that needs to be done for Accelerated Publishing & Content API. The epics and issues should all be reviewed, refined where we have knowledge to do so, and new ones created if there is known work that is not covered. Epics and tickets that are marked for closing as 'not needed' should be reviewed with the PO and tech lead prior to closing.

## Acceptance Criteria
- [x] All epics are reviewed for relevance to Accelerated Publishing, and labeled as such
- [x] All tickets not in an epic scanned and added to AP epics if appropriate
- [ ] All AP epics and tickets reviewed for relevance to the current understanding  of AP/CAPI. Issues and epics that are still relevant should be refined to become actionable, where possible; Issues and epics with questionable relevance should be marked for review
- [ ] All large scale changes documented on this issue (i.e. removal of epic, significant rewrite of an epic or ticket); Not necessary to document every small change.
- [ ] Review is done with the PO and Tech lead for Accelerated Publishing to check the changes
- [ ] Epics & issues confirmed no longer relevant are closed
- [ ] This work will be timeboxed to the current sprint (current sprint is 44).

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
