### ISSUE TITLE
[Docs] CMS Platform Team internal docs to Platform Confluence

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#6688]
### User Story or Problem Statement

As a CMS Platform team member, I need internal team documentation to be stored on [Platform Confluence](https://vfs.atlassian.net/wiki/spaces/PCMS/overview), so I can find and update information needed to participate on the team.

### Affected users and stakeholders

* Members of Platform CMS team

## Acceptance Criteria
Documents that have been moved to Platform CMS team space:
- [ ] Team norms
- [ ] Meeting cadence
- [ ] Team onboarding process
- [ ] Team OKRs
- [ ] Meeting notes
- [ ] Retro notes / action items
- [ ] Links to boards and roadmaps
- [ ] Reference links for additional materials

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by TheBoatyMcBoatFace** [comment]
Epic still valid

To-Do

- [ ] Review Issues to determine if still valid
- [ ] Prioritize documentation updates

**Comment by EWashb** [comment]
This should be folded into a larger documentation effort for the CMS Team to Platform work.

**Comment by EWashb** [comment]
@BerniXiongA6 I found this old epic and know you are actively working on this. We should probably take this out of the icebox, update, and note all of the things you're working on to do this.
