### ISSUE TITLE
Add "Required Vet Center service" and "Number of Vet Center facilities with service" to the health service dashboard

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6749]
## User Story or Problem Statement

As a manager of VHA services, i want a report of what services are required, and how many Vet Centers currently offer that service, so that i can evaluate any changes that may need to be made. 

## Acceptance Criteria

1. "Required Vet Center service" field
- [ ] https://prod.cms.va.gov/vha-health-services has a new column added called "Required Vet Center service"
- [ ] True is displayed as "Required". False is not displayed. 
- [ ] Column can be sorted  see AC group 3

2. "Number of uses by Vet Centers"
- [ ] Copy the config for "Number of uses by VAMCs", but change it to count references from Vet Center nodes. 

3. All table columns should be sortable. 

4. Move Number of uses by VAMCs to the left of the Vet Center fields. 

5. CSV export should match experience of view. 

![VHA_Health_service_taxonomy___Veterans_Affairs](https://user-images.githubusercontent.com/643678/138328724-c0c7d9b8-b4a8-4967-adc3-d1a79dc22810.png)

## Implementation steps
Update Drupal view. 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
