### ISSUE TITLE
Make audit tool Views available

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6759]
## User Story or Problem Statement

As an audit tool user, I need to be able to get to my audit tools so I can audit stuff.

or

Currently our audit tools are hidden unless you know the specific url
These two audit tools 

![image](https://user-images.githubusercontent.com/5752113/138394909-1e7a2c9d-787b-4abf-a8b5-2587a17051bb.png)

Do not appear in the menu of other Views.
The ideal results would be the equivalent of 
![image](https://user-images.githubusercontent.com/5752113/138394950-0c66d36e-0f5e-45ee-958a-8ec9f9a3f88e.png)
When you are on the audit tool page.  The other audit pages should appear as sub-tabs.

The two good tabs under all content are not defined by the View.  They are defined in code here 
docroot/core/modules/content_moderation/content_moderation.links.task.yml
![image](https://user-images.githubusercontent.com/5752113/138395181-0ec15c85-b278-44a4-82a8-84eeeb098cc1.png)

## Acceptance Criteria
- [ ] Menus for audit tool Views appear on the admin/content menu When the audit tools tab is selected.
- [ ] Content menu IA is as follows
  - Content
    - Overview
    - Moderated content
    - Alerts
    - Events
    - Promos
  - Content audit tools
    - Bulk edit
    - Button Audit
    - Feedback
    - Flagged
    - Messages
    - Rich Text
  - Facilities
  - Resources and support
  - VA Forms
  - Media

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
I started working out some ideas here: https://app.mural.co/invitation/mural/vagov6717/1635876790922?sender=u0213d96dd8b8c144f1f10284&key=3360aded-a676-4e8a-b5c3-610a9f72abfb

**Comment by msbtterswrth** [comment]
I chatted with @EWashb and we're going to adjust this a bit back to just reorganizing the views tabs in content and save the bigger overhauls for later. I'll update the ACs to reflect that.

**Comment by swirtSJW** [comment]
I am going to close this as many of these changes have already been made.
