### ISSUE TITLE
Sitewide CMS team - Sprint 44 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6767]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💧  — Drupal engineering
🎓  — Training / Change management / KB
📟 — Helpdesk
💡 — Design
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

* First full sprint for Tanner
* Iván, Denise, Val onboarding but will pick up work week 2ish.
* Cindy (interaction designer) starting week 2
* Last full sprint before onsite
* Last full sprint before Rachel's Nov 12 leave
* Half the issues don't have estimates
* Review Q4 priorities this Wednesday on Program team
* Zenhub changes incoming
 
</details>

----

<details><summary>Product support</summary>

### #3151 3 VAMC Top task pages

We need to unblock Facilities team ASAP on at least two pages.

- [x] #6725  - Steve
- [x] #6341  🥅  💧

### VAMC upgrade team support

- [x] #6770 💧 - Migration delete code - Steve and Jay?
- [ ] #6771 💧 - Migration add CSV - Steve and Jay?

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6414 - tracking issue for LH team, which blocks...
  - [x] #6417 💧  - done but not merged

### #4799 VAMC Care we provide 

- [x] #6455 💡 💧
   - [ ] #6768 💡 - Val and Denise 
   - [ ] #6456 💧 - Jay / Ivàn? Can be done concurrently with #6768  but cannot be merged
 

### #4743 Support Mobile VHA clinic data in CMS

- [ ] #6769 🥅  - Meeting with Facilities Thursday Oct 28 2pm 

### #6371 Remove Nearby Vet Center Locations 

Final tech debt issue to close the epic. 

- [x] #6637 💧 - Ethan 

### #6553 Vet Center dashboard usability research

- [x] #6555 💡 - Suzanne / Erika
- [ ] #6627 💡 - Suzanne / Erika

### #5800 Show national health service taxonomy content inline

This epic and the next have intertwined design. 

- [x] #6641 💡🥅 - Suzanne / Rachel
  - [x] #6536 💧 - Ethan

### #6332 Required Vet Center Services

Engineering can begin but last step is dependent on design in the above epic.  

- [ ] #6639 💧 Jay/Steve
  - [ ] Then #6640 (depends on #6641) 💧 - Ethan or Jay
    - [ ] #6749 💧 🌱 

### #6446 Support Vet Center "official name" 

Content is migrated and available for development, but this is lesser priority. 

- [ ] #6447 💡🥅 (field is hidden, for now)
- [ ] #6623 💧 - Jay 

## Tech debt 

- [ ] #6629 💧 - Backend, Ethan
- [ ] #6630 💧 - Backend, Ethan

</details>

<details><summary>Content Ops</summary>

## #6170 Improve meta tags across all content types 

- [x] #6171 💧
  - [x] #6646 💧 - Jay
    - [ ] then bring recommendations and visual audit to Product teams to establish next steps. 

## #936 Improve content proofing experience  

- [x] #6188 💧 - Lynn (just tests need fixing)

### CTAs

- [x] #5439 - Backend, Ethan (possibly some with Lynn)

### #2932 Improve table component, guidance, accessibility guidelines, etc

- [ ] #6645 
- [ ] #1171 

## #2427 h1 governance (VAMC, Outreach Hub, Office)

- [x] #6700 💧 - Ethan and Iván 

## CMS Account admin

- [x] #6743 - Lynn 

</details>

<details><summary>CMS experience</summary>

## #1352  CMS Design System MVP (Claro) 

[Needs clarifying... we will start kicking this off again in Sprint 44]

- [ ] #6755 - Tanner w/ Rachel

</details>

<details><summary>Customer service </summary>

## Help desk

- [ ] #5684 
- [x] #6583
- [x] #6574 

## CMS Knowledge Base

- [x] #5714 
- [ ] #6586 
- [ ] #6398 
- [ ] #6737 

</details>

----

<details><summary>Agenda for refine Thursday Oct 28</summary>

- [ ] Review roadmap
- [ ] #6623 (Facility API concerns)

Backend Tech debt 
- [ ] #6629 💧
- [ ] #6630 💧

Customer service
- [ ] #6558 📟  💧

Facilities
- [ ] #4856 (needs user stories first) 💧
- [ ] #6450 

</details>
