### ISSUE TITLE
Qualitative / Quantitative audit of Care we provide fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6768]
## User Story or Problem Statement

See #4799 

## Acceptance Criteria

- [x] [~6000 VAMC system health service nodes](https://prod.cms.va.gov/admin/content/audit/vamc-system-service-audit) have been audited for various patterns
  - [ ] Nodes that follow original content design
  - [ ] Nodes that deviate from original content design 
    - [ ] Are missing the "Care we provide at [Health care system]
    - [ ] Have _additional_ h3s or h4s
    - [ ] Other?
- [ ] Teams have an actionable list for VAMC system health service nodes
  - [ ] Ones that can be likely be updated by script
  - [ ] Ones that may require change management
  - [ ] Other?
- [ ] We have identified a responsible actor for taking these actions
  - [ ] CMS engineers (migration, database updates)
  - [ ] VAMC upgrade team
  - [ ] CMS help desk
  - [ ] Others?

Stretch
- [ ] Identify other opportunities. 
  - [ ] Hardening paragraph or the bullets
  - [ ] Care coordinator pages

Present findings and recommendations to VAMC upgrade, and Facilities  

## Implementation steps

It is possible to export the existing nodes into a CSV that could be imported into Airtable or Google Sheet

One table should be the source of truth and updated periodically with fresh content, with the Node ID as the key

Audit work can happen in other tables in the airtable. 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by ContentBrewmaster** [comment]
Documentation has been updated [here](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/cms/care-we-provide-audit)
