### ISSUE TITLE
Audit rich text fields for what text formats are allowed ("Full" vs "Limited")

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6772]
## User Story or Problem Statement

The first two products (Benefits Hubs, Outreach Hub, and VAMC) were built with a "Full HTML" editor

We then built a "Limited HTML" text format and editor, which does not offer headings or Styles, for the R&S. We want to shift as much as possible to the Limited HTML editor. 

First, we need an audit of existing rich text fields for what configuration exists

## Acceptance Criteria
- [x] The "Fields" worksheets (Content type fields, Block type fields, etc) on Drupal Spec tool has been updated to indicate what text formats are allowed for each rich text field. This should be the source of truth, but we need a decision-making version of this.
- [ ] A separate artefact (possibly a new worksheet?) has been created that lists only rich text fields, their content type(s), their allowed formats, and a notes field. Possilby other data fields. 
- [ ] Others TBD, let's discuss!
- [ ] Next steps are defined for making recommendations, possibly an issue in Sprint 45. 

Stretch
- [ ] Make those recommendations.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
I am not sure if this is fully closed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/6810  as it seems to have some other AC's
