### ISSUE TITLE
Document request fulfillment process for removing facilities from health care system. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6785]
## User Story or Problem Statement

See #6781, which will increase requests to help desk to remove facilities from their health care system. 

As a help desk manager, i need to understand how to process requests from users to remove a facility from a VAMC system. 

It will involve using Facility Locator as a source of truth. 

## Acceptance Criteria
- [ ] Business request fullfilment process is documented. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by xiongjaneg** [comment]
@stefaniefgray Per Dave Conlon, refer editors to the KB article on facility basic data as their first contact (instead of VAST)

**Comment by stefaniefgray** [comment]
@xiongjaneg How does this look?

## **Steps to Archive a Closed Facility**

**Background:** There are outside databases such as the Lighthouse API and VAST which provide information about each facility across multiple VA.gov sites/programs/apps, so it’s important that facilities are first archived within these databases before they are archived from the site itself. (Otherwise, there may be broken links strewn throughout VA.gov, which we want to avoid!)

### Step 1: Locate the Point of Contact For Updating Facility Data

- Depending on the type of information that you wish to update, you will need to find the best point of contact for requesting changes to data that lives outside of Drupal.

- Before proceeding with the steps listed below, please read through the Knowledge Base article titled "How Do I Update My VAMC Facility's Basic Location Data?" and reach out to the appropriate contact(s) listed within the table at the bottom of this page.

### Step 2: Update or Remove the Facility from VAST
- Next, contact your VAST administrator and let them know that the facility information needs to be removed or changed.
Please also ask them to inform you as soon as the facility is removed or changed.

**Comment by xiongjaneg** [comment]
@stefaniefgray Thanks for working on this. Probably don't need step 2. Maybe just add the last sentence in that step to the second bullet point in step 1.

**Comment by stefaniefgray** [comment]
@xiongjaneg Updated per your comment! :) Marking as closed.
https://prod.cms.va.gov/help/vamc/about-locations-content-for-vamcs/how-to-archive-a-closed-facility
