### ISSUE TITLE
FE Displays events that are currently in progress as Past

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6800]
## User Story or Problem Statement
As a content editor in the CMS I would like to create an event that spans  multiple days and have appear on va.gov as upcoming until after the end date has passed.  So that veterans have better insight into what events are happening presently and in the future.

As a veteran using va.gov, I would like events not to appear as past events, if they still going on, so that I am not confused by what the website is showing me.

The current logic on the FE of content-build seems to move events from Upcoming to Past when the time/date is past the start date.  This leads Veterans to not see events that are happening right now.

![image](https://user-images.githubusercontent.com/5752113/138987878-a746cc19-9d41-47fc-828a-6a5a19afd426.png)
example https://www.va.gov/pittsburgh-health-care/events/

Related discussion 
https://dsva.slack.com/archives/C01H29ERVJ7/p1635273694001100
https://dsva.slack.com/archives/CT4GZBM8F/p1634939608166000

## Acceptance Criteria
- [ ] An event that spans multiple days, does not move from "Upcoming events" to "Past events" until its end date has passed.
- [ ] An event that is a single day does not move from "Upcoming events" to "Past events" until its end date has passed. (same criteria and behavior as above)

## Implementation steps
There are no changes need to the CMS, just changes needed to FE logic and templated.   This impacts public websites and Facilities.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by amandeepma** [comment]
Hey @brianalloyd is this the ticket your team could pick up?

**Comment by brianalloyd** [comment]
@amandeepma yes we'll review during planning and might reach out with any questions as we scrub into the work.

**Comment by mpelzsherman** [comment]
I've pushed up a [PR](https://github.com/department-of-veterans-affairs/content-build/pull/723) that might fix this. 

Can someone create a tugboat build off this branch and test?

**Comment by amandeepma** [comment]
You guys are awesome!!
