### ISSUE TITLE
Remove drag and drop paragraph UI for paragraph fields that only have one allowed value. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6821]
## User Story or Problem Statement

 As a user who has added a paragraph to a single value paragraph field, i should not see any interface related to dragging and dropping, because it's useless and doesn't make sense.

![Create_Campaign_Landing_Page___VA_gov_CMS](https://user-images.githubusercontent.com/643678/139176328-a0e40919-684f-47c9-8d44-99472a144e3c.png)

## Acceptance Criteria
- [ ] All Entity reference revision fields (paragraphs) with a cardinality of 1 have no "Drag and drop" option. For example, Primary CTA on https://prod.cms.va.gov/node/add/campaign_landing_page  

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by EWashb** [comment]
Let's confirm if this is still happening. Definitely bad UX
