### ISSUE TITLE
Alert on failed govDelivery Bulletins push

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6833]
## User Story or Problem Statement

As a CMS maintainer I would like to know when a govDelivery Bulletins push fails so that I can assess and take action if needed.

related to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6815

## Acceptance Criteria
- [ ] When the push attempt throws an error like
```
422 unprocessed entity
```
![image](https://user-images.githubusercontent.com/5752113/139335166-80ab5aad-7e5f-4d90-8468-7b935fd9ab8d.png)

something (datadog?) should alert slack.

## Implementation steps
It is not specific to 422 could be anything other than a 200 response.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
