### ISSUE TITLE
Calculate % of VA.gov pages that are managed by Drupal

### ISSUE THREAD

**Issue by jefflbrauer** [department-of-veterans-affairs/va.gov-cms#6843]
###Context

As part of our sitewide crew onsite meeting around content strategy and IA, we would like to discuss the various problems and opportunities we see around content strategy and better alignment between CMS content model and front end components. As part of the deck we assemble for this conversation, we would like to have a real % of pages on va.gov that are managed by Drupal. 

### Tasks:
- [ ] Get metric from Grafana on number of drupal managed URLs
- [ ] Get total number of va.gov pages from vets-website sitemap
- [ ] Calculate % pages 

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
This data may also inform the priority level of making Drupal the source of truth for redirects
