### ISSUE TITLE
Create audit tool for alt text on images

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6860]
## User Story or Problem Statement

As an accessibility advocate for www.va.gov (member of CMS team, or Platform accessibility team, product owner, etc), i want a tool to review alt text in VA.gov CMS to identify and prioritize opportunities for improvement, training, automated tools, and other TBD actions in the name of ensuring accessible content at VA. 

See epic for more info. 

## Acceptance Criteria
- [ ] View display:  /admin/content/audit/media/alt-text 
   - [x] Child of core Media view?
- [x] Menu: Child of core admin/media view
- [ ] Fields
  - [x] image thumbnails (original aspect ratio, but reduced in size to small)
  - [x] What section they belong to
  - [ ] ~What product that section relates to~
  - [x] Which user uploaded them 
  - [x] Alt text 
  - [ ] Stretch: What content uses references it?
- [ ] Access: CMS editor
- [x] 50 pages at a time
- [x] Filters
  - [x] Section
  - [x] Title contains

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
