### ISSUE TITLE
Enable content moderation for VHA facility non-clinical services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6871]
## User Story or Problem Statement

As an editor of VHA facility non-clinical services, i want the same editorial workflow (content moderation) experience as elsewhere in the CMS, for consistency and careful governance.

## Acceptance Criteria
- [x] Content moderation has been enabled for `vha_facility_nonclinical_service` (at /admin/config/workflow/workflows/manage/editorial?destination=/admin/config/workflow/workflows)
- [x] /node/add/vha_facility_nonclinical_service matches other content types for the Editorial Workflow fieldgroup
  - [x] Revision log message field appears in an editorial workflow fieldgroup, following patters on other content types

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
