### ISSUE TITLE
Prepopulate entity reference fields on nonclinical service form, when context is known

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6874]
## User Story or Problem Statement

As an editor of a Top task page that clicks a link to add a non-clinical service, i want the form for non-clinical service to carry some of the context (Service and Section) from the page i was just on. 

[This coudl use some screenshots and URLs in the future]

## Acceptance Criteria
- [ ] Editors that click on the /node/add/vha_facility_nonclinical_service links from within the top taks forms, get Section and Service fields prepopulated on that form, based on parameters on the page from which they are coming.

## Implementation steps

Add prepopulate module (?) so that we can make the “Add a service” link in the header of these views go ahead and prepopulate 2 of the fields on the non-clinical health service form.

Update links in headers on each of the three displays on non_clinical_services to properly prepopulate the fields on the /node/add forms.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by JayDarnell** [comment]
It looks like we have two potential paths for this issue, the prepopulate module (https://www.drupal.org/project/prepopulate)and the entity prepopulate module (https://www.drupal.org/project/epp). 

Prepopulate is a little wonky currently in that it doesn't seem to support prepopulating multiple fields with a single URL:  https://www.drupal.org/project/prepopulate/issues/3045792. Prepopulate also assumes that the URL matches the widget used (at least that is what I'm seeing from some research online) so if the widget changes the URL will also change. 

Given those two issues I'm researching EPP (entity prepopulate) now.

**Comment by swirtSJW** [comment]
Referencing the issue with the patch here https://www.drupal.org/project/viewfield/issues/3252356  Nice work.   Providing an interdiff on on the issue is nice.  Not required, but it makes it easier to see what changed.
