### ISSUE TITLE
Reduce what facilities can be chosen on nonclinical facility service nodes according to Section

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6875]
## User Story or Problem Statement

As a creator of a Non-clinical facility service page, i don’t have to scroll through a million facilities to find mine. That list is already reduced by the Section i’m on.

## Acceptance Criteria
- [x] After choosing VA Sioux Falls health care for Section on /node/add/vha_facility_nonclinical_service, the only facilities in the Facility field are those that contain "VA Sioux Falls health care"

## Implementation steps
Do that thing where the facility list gets winnowed by Section (this can wait until the custom module for vamc has been refactored)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
