### ISSUE TITLE
Hide Service fields on 3 top task pages, because they are set by default

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6876]
## User Story or Problem Statement

As a creator of a Top task page, i want the Service field to be hidden from the form and from the node view, because it’s implict and redundant. 

## Acceptance Criteria
- [ ] On /node/add/vamc_system_billing_insurance, Service field is hidden, but default value is set to Billing and insurance
- [ ] Same for Service fields on Medical Records and Register for Care content types

## Implementation steps
Form config

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by JayDarnell** [comment]
This work is bundled in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7037
