### ISSUE TITLE
Proof of Concept for Claro subtheme, with one component "inherited" from VA

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6885]
## User Story or Problem Statement

As a member of the CMS experience team, I understand technical feasibility and some opportunities for creating a VA.gov CMS design system with VA-flavor subtheme of Claro, so that I can build a roadmap that includes an MVP definition, based on what's feasible, and desirable. 

## Acceptance Criteria
- [ ] Claro subtheme has been created that uses at least one VA design system component, the alerts.
- [ ] We have an understanding for how we might inheriting VA CSS (and possibly HTML?) in our subtheme

Adjacent issues that may come up
- #3700
- #1818 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
