### ISSUE TITLE
Sitewide CMS team - Sprint 45 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6895]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

* Cindy (interaction designer) 
* Veterans day November 11
* Onsite for many folks November 15-18
* Half the issues don't have estimates
 
</details>

----

<details><summary>Prep for Onsite</summary>

- [x] #6937 
  - Agenda planning 🥅
  - Design workshops / design studios (eg #6922 or others)

</details>

<details><summary>Product support</summary>

#### FE dev 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30390 🎉
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30391 🎉
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30392 🎉

#### #6872 Editorial experience 

Idea is to do some functional implementaiton first, then go through a design iteration focused largely on UX writing. 

- [x] #6871 💧  (defect)

Sprint 46?
- [ ] #6875 💧 (Ethan)
- [ ] #6873 💧
  - [ ] #6874 💧
- [ ] #6876 💧

### Service locations on facility health services

- [x] #5387 💧 (Iván)

### #5800 Show national taxonomy service content inline 

- [x] #6917 💧 🥅 (Ethan)

### VAMC upgrade team support

- [x] #6771 💧 (Jay)
- [ ] #6920 💧 (Jay)

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6414 - tracking issue for LH team, which blocks...
  - [ ] #6417 💧  - done but not merged

### #4799 VAMC Care we provide 

- [ ] #6768 💡 - Val and Denise 
- [x] #6456 💧 - Jay / Ivàn? Can be done concurrently with audit
 

#### #6919

A small governance step towards a better experience for one VAMC component, which will prevent FE errors. 

- [ ] #6918 💧 

### #6446 

- [x] #6447 💡 Rachel / Suzanne
  - [ ] #6449 💧

### #6553 Vet Center dashboard usability research

- [x] #6627 💡 🥅 - Suzanne / Erika

### #6332 Required Vet Center Services

Engineering can begin but last step is dependent on design in the above epic.  

- [ ] #6639 💧 Jay/Steve
- [ ] Design editorial experience for required Vet Center services
  - [ ] Then #6640 💧 - Ethan or Jay
    - [ ] Then merge 6639. 

### #6446 Support Vet Center "official name" 

Content is migrated and available for development, but this is lesser priority. 

- [x] #6447 💡
  - [ ] #6623 💧 - Jay (lower priority)

## Tech debt 

- [ ] #6629 💧 - Backend, Ethan
- [x] #6630 💧 - Backend, Ethan

</details>

<details><summary>Content Ops</summary>

## #2045 Connect with us 

Old tech debt... content is stored in Section vocabulary, and should be moved to office. 

- [ ] #2041 💧 (needs PO validation on the approach, won't be merged for now)
  - [ ] #2044 💧 (post merge of 2041)
  - [ ] #2042 🎉  (Sprint 45 or 46)
  - [ ] Unhide new entity ref fields, hide old entity ref field on CLP, and disable feature flag.
  - [ ] #2043 💡

## #6170 Improve meta tags across all content types 

- [ ] #6935

### #2932 Improve table component, guidance, accessibility guidelines, etc

Stretch

- [ ] #6645 
- [ ] #1171 

## CMS Account admin

TBD

</details>

<details><summary>CMS experience</summary>

## #1352  CMS Design System MVP (Claro) 

- [x] #6885 💧(Tanner)
  - [ ] #6887 💧
  - [ ] #1818 💧
- [ ] Other work TBD (Cindy), possibly #6755 💡

</details>

<details><summary>Customer service </summary>

## Help desk

- [ ] #5684 
- [ ] #6897
- [ ] #4721 

## CMS Knowledge Base

- [x] #5714 
- [ ] #6586 
- [ ] #6398 
- [ ] #6737 

</details>

----

<details><summary>Agenda for refinement Thursday November 11 (needs rescheduling for Veteran's Day</summary>

## Content Ops
- [ ] Notifications user stories 

## Facilities
- [ ] #4856 (needs user stories first) 💧
- [ ] #6623 (Facility API concerns)

### VAMC Top tasks
- [ ] Editorial experience
- [ ] Change management

Customer service
- [ ] #6558 📟  💧

</details>
