### ISSUE TITLE
Show national service content inline while editing services, and other followups to #6536 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6917]
## User Story or Problem Statement

As an editor of existing Vet Center or VAMC service content, 
1. I want to see the national service descriptions and other data inline while editing, so that i can make better content decisions.
2. I want guidance that helps me make better content decisions. [@rachel-kauff: feel free to tweak]

<details><summary>Screenshot</summary>

<img width="700" alt="Create_VAMC_System_Health_Service___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/140456170-1db355a6-46ab-4bb2-9cde-4c20e75b4722.png">

</details>

## Acceptance Criteria
- [ ] The experience currently available on https://prod.cms.va.gov/node/add/vet_center_facility_health_servi and https://prod.cms.va.gov/node/add/regional_health_care_service_des, where General service description is shown inline after selecting a service, is also available for existing nodes that already have a service. 
- [ ] The KB link in the submission guidelines reads `How to edit a VAMC System Health Service (opens in a new tab)` to make the link accessible
- [ ] General service description` field label uses sentence case capitalization

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
