### ISSUE TITLE
Improve "Common Links" editorial experience for VAMC systems

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6919]
## User Story or Problem Statement

As a VAMC editor, i want a good an efficient, approachable, and empowering editorial experience for adding the "Common links" that show up on various pages of my health care system website, including on the VAMC system homepage and all facility pages. 

### Background

This was built in a rush to support a FE MVP.

### Content model and editorial experience hypothesis

"Common links" could be migrated to a simple drupal Link field, instead of paragraphs, with better help text that describes what these links do. 

<details><summary>Screenshot</summary>

Current experience

<img width="694" alt="Create_VAMC_System___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/140457793-5c9095ed-2a60-4816-9c5b-d70f67e10f6a.png">

</details>

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by EWashb** [comment]
@xiongjaneg @jilladams I think this should be in your backlog instead of CMS, but correct me if I'm wrong.
