### ISSUE TITLE
Rename VA North Florida health care to VA North Florida/South Georgia health care

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6920]
## User Story or Problem Statement

As a Veteran that searches for South Georgia OR North Florida, i want to find my health care system using a search engine. 

## Acceptance Criteria
- [x] h1 and breadcrumb for https://www.va.gov/north-florida-health-care/ has been changed to VA North Florida/South Georgia health care
- [x] No URLs are updated 
- [x] VAMC system health service nodes (and any other content that uses the VAMC system node title in its autoentity label) have been updated to reflect this 
- [ ] Internal documentation has been updated for "How to update the name of a VAMC system". This can be sent to Help desk team for their documentation. It should live along side the ["How to update the name of a VAMC facility"](https://dsva.slack.com/archives/CDHBKAL9W/p1636151114050100?thread_ts=1636149011.046700&cid=CDHBKAL9W) instructions, which were noted in this slack thread on Fri Nov 5.

> 1. Fix the menu name on the facility and check the box to "Generate automatic URL alias"  then save the facility.
> 2. Go to bulk edit and find all the facility services under the old name and use the option to "update url alias"
> 3. return to bulk edit and find all the facility services under the old name and use the "Resave content" option to cause the titles of the service to pick up the new name.

## Implementation steps

On tugboat
1. Edit node and menu item for the system
2. VBO to update VAMC system health services
3. Content release
4. Smoke test on Tugboat FE
5. Future Points of failure testing Tugboat
   1.    Rename a facility with the N. Florida health care system : /node/1573 (change title, menu title, click the box to create new alias)
   2.   Bulk operation update alias for all facility health services for "Waycross VA clinic"
   3. Bulk save the all facility health services for "Waycross VA clinic" so the title gets picked up.
   4. - [ ] Validate that none of new aliases contain `VA North Florida/South Georgia`
   5. Rebuild tugboat FE.   Check Waycross VA clinic path on FE.
6. Write KB article about what you did
7. Repeat steps 1-2 on prod. 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
This change has the risk if the checkbox is ever checked and saved 
![image](https://user-images.githubusercontent.com/5752113/140960208-3a373b6f-8f56-45e2-9c9e-ec64b688d126.png)

**Comment by swirtSJW** [comment]
It looks like this url is not meant to change... indefinitely https://dsva.slack.com/archives/C0FQSS30V/p1636488112287100

I  don't think it blocks this issue... but we may want to consider an alias entity presave that would catch and prevent it.  It would not be hard to have an entity::presave event    (our replacement for hook_entity_presave.   As much as I hate hard-coding specifics like this..... it would be a good defense.
https://api.drupal.org/api/drupal/core%21modules%21path_alias%21src%21Entity%21PathAlias.php/function/PathAlias%3A%3ApreSave/8.8.x

**Comment by swirtSJW** [comment]
@kevwalsh @JayDarnell We may have a failure related to menus when trying to rebuiild the FE.  They were doing some string matching that may break if the system title does not match the system menu name.

**Comment by swirtSJW** [comment]
@kevwalsh   Should this be updated too?  
![image](https://user-images.githubusercontent.com/5752113/141126911-ffefd0d5-beb7-420a-9111-82525b5b0ef0.png)

**Comment by cmaeng** [comment]
having @JayDarnell take a look at this to see if it's feasible to accomplish in sprint 45.

**Comment by JayDarnell** [comment]
I ran a local test for this and it looks like we can change the title for the VAMC system node, save it and then resave all the VAMS system health service nodes tied to this item to accomplish our goals. The breadcrumb and titles are updated but the URLs do not change. 

However, I have not tested this in a tugboat environment and imagine that is needed to address Swirt's comment above: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6920#issuecomment-965207246

Where is the "internal documentation" referenced in this ticket? I'm unsure where to put the steps for updating names of VAMC systems.

I'm attempting the Tugboat steps above now but may need some assistance tomorrow.

**Comment by JayDarnell** [comment]
@netboss @swirtSJW I can't recall the steps necessary to spin up a tugboat environment on demand. Could we cowork on this tomorrow? I think this ticket can be knocked out quickly now that I've tested it locally but I want to be sure the content build for the frontend doesn't break with the name change.

**Comment by netboss** [comment]
@JayDarnell Sure thing. Ping me whenever you want to meet. I just updated this ticket's status and changed it to "In progress".

**Comment by JayDarnell** [comment]
Testing in tugboat:

On tugboat
1. [ ] Edit node (update title of menu item for the system) **Editing the title of the menu item and saving the node does update the breadcrumb while leaving the url unchanged but the H1 remains unchanged as well**
2. [ ] VBO to update VAMC system health services (update url alias) **NO CHANGE to urls but no change to titles or breadcrumbs either**
3. [ ] VBO to update VAMC system health services (resave content) **NO CHANGE to urls but no change to titles or breadcrumbs either**
3. [ ] Content release **Build succeeds - however the titles for the nodes are unchanged and the breadcrumbs for the VAMC system health services did not update either**
4. [ ] Edit VAMC System VA North Florida health care node and update VAMC system plain language name to "VA North Florida/South Georgia health care" **H1 is now updated**
5. [ ] VBO to update VAMC system health services (update url alias) **NO CHANGE to urls but no change to titles or breadcrumbs either**
6. [ ] VBO to update VAMC system health services (resave content) **NO CHANGE to urls, titles updated but breadcrumbs unchanged**
7. [ ] Content release **Build fails**
4. [ ] Smoke test on Tugboat FE
5. [ ] Future Points of failure testing Tugboat
   1.    Rename a facility with the N. Florida health care system : /node/1573 (change title, menu title, click the box to create new alias)
   2.   Bulk operation update alias for all facility health services for "Waycross VA clinic"
   3. Bulk save the all facility health services for "Waycross VA clinic" so the title gets picked up.
   4. - [ ] Validate that none of new aliases contain `VA North Florida/South Georgia`
   5. Rebuild tugboat FE.   Check Waycross VA clinic path on FE.
6. Write KB article about what you did
7. Repeat steps 1-2 on prod.

**Comment by JayDarnell** [comment]
Follow up testing today also results in a build failure:

- [ ] update plain name and link title for the VAMC system and save it (the breadcrumbs and H1 update)
- [ ] find all related content using view bulk operations (being sure to NOT update the VAMC system node itself) and run update alias (no changes to the URLs detected)
- [ ] find all related content using VBO (being sure to NOT update the VAMC system node itself) and run resave content (no changes to the URLs detected)
- [ ] At this point the VAMC system node is updated and the titles for related content also reflect the new name without any URLs changing BUT the build still fails.

**Comment by JayDarnell** [comment]
@swirtSJW @kevwalsh if I rename the menu (not the menu title described above but the name of the entire menu for the location) for North Florida to match the name change on the VAMC system node then the build succeeds. I don't know what the larger impacts of this are or if changing this name is a suitable solution.

**Comment by JayDarnell** [comment]
- [ ] Edit the VAMC System in question (North Florida health care) and update the **VAMC system plain language name** and **Menu link title** to the new value: **VA North Florida/South Georgia health care** (updating the plain language name will update the H1 while updating the menu link title will update the breadcrumbs)
- [ ] Save the node with the changes above - DO NOT check the box to Generate automatic URL alias
- [ ] Visit /admin/structure/menu and locate the menu corresponding to the VAMC System (the name should match the original name of the VAMC System you just updated)
- [ ] Update the title for the menu to match the plain language name of the VAMC system: **VA North Florida/South Georgia health care** (it is important these two match or the front end build will fail)
- [ ] Visit /admin/content/bulk and update the section filter to match the VAMC System you updated in the first step above and click filter
- [ ] Select all resulting items and apply the **resave content** action, this will update node titles (where applicable: operating status and health services for example) for content in this section based on the VAMC System name change

**Comment by JayDarnell** [comment]
The steps in my last comment result in a build success. We should not deploy this change to production until after the current code freeze has been lifted but the steps seem to work. I will create a follow up issue to lock down the ability to change the alias for VAMC System nodes to prevent someone accidentally changing all the URL aliases.

**Comment by JayDarnell** [comment]
@kevwalsh @swirtSJW Steve had mentioned waiting to tackle this until after the holiday code freeze had been lifted. When exactly am I good to do this on production?

**Comment by swirtSJW** [comment]
@JayDarnell  issue got closed with the PR, but wanted to verify this was done  
> Internal documentation has been updated for "How to update the name of a VAMC system". This can be sent to Help desk team for their documentation. It should live along side the "How to update the name of a VAMC facility" instructions, which were noted in this slack thread on Fri Nov 5.
