### ISSUE TITLE
Proofing experience for services (VAMC and Vet Center)

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#6921]
Broken off from #6641 

## User Story or Problem Statement

As an editor who has saved changes to a VAMC or Vet Center service, I want a proofing page that provides a clear understanding of the content so I can confirm my work. 

## Acceptance Criteria
- [ ] Design recommendations for Vet Center and VAMC proofing pages
- [ ] Implementation

## Implementation steps
TBD

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
This is really a stand-alone epic, i will move it outside the Required Vet Center services epic. Hopefully something we can tackle in Q1.

**Comment by Agile6MSkinner** [comment]
This idea was never developed and has been sitting around for years. Closing as not planned.
