### ISSUE TITLE
CMS UI workshop(s?)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6922]
[This is a draft/brainstorm. Not a plan we're committing to, in its current formulation anyway --kevin]

## User Story or Problem Statement

As a CMS team member, i want to get a sense of the breadth of the CMS, and all its constituent parts, so that I can find opportunities and understand interdependencies, to inform upcoming work across workstreams, including Product Support, Content Ops, Help desk, and CMS experience.

## Acceptance Criteria
- [ ] Workshop participants leave with an understanding of the breadth of the CMS UI, and its constituent parts
- [ ] Others TBD, like identification of product opportunities and/or prioritization

## Implementation steps

A couple ideas for workshop approaches and materials. To do all these would be way too much. We can discuss what lens makes the most sense. 

### 1. Screen audit and workshop
- Create and print out, in large format ideally, the screens for forms, possibly proofing, and FE representations of that content
- Group by product where possible, and possibly arrange products in a meaningful order, such as by size or type of editor base
- Note the number of editors by product, amount of content per content type, GA traffic, and other attributes of each screen
- Explore patterns and variations, strengths and weaknesses, opportunities for alignment and/or additional customization by product, structured vs unstructured content, etc.

<details><summary>Node audit (gives a sense of how prominent/used each screen is)</summary>

VAMC Facility Health Service (12549)
VAMC System Health Service (5834)
VAMC Detail Page (4938)
Staff Profile (3500)
Event (1619)
VAMC Facility (1338)
Vet Center - Facility Service (1194)
Story (608)
VA Form (508)
VBA Facility (474)
News Release (467)
Benefits Detail Page (327)
Vet Center - Locations List (300)
Vet Center (300)
VAMC System Banner Alert with Situation Updates (232)
NCA Facility (191)
Q&A (178)
Publication (177)
News Releases List (140)
Events List (140)
Leadership List (139)
Stories List (139)
VAMC System Locations List (139)
VAMC System (139)
VAMC System Operating Status (139)
Health Services List (139)
VAMC System Policies Page (139)
CMS Knowledge Base Article (122)
Vet Center - Mobile Vet Center (83)
Vet Center - Community Access Point (80)
Resources and support Detail Page (45)
FAQ - multiple Q&As (28)
Vet Center - Outstation (18)
Campaign Landing Page (17)
Support Service (17)
Benefits Hub Landing Page (12)
Step-by-Step (9)
Centralized Content (8)
Banner (2)
Office (2)
Media list - Videos (2)
Checklist (2)
Landing Page (1)
Publication Listing Page (1)
Media list - Images (1)

</details>

### 2. A Design system audit
- print out the VA design system components
- print out example paragraphs UI for each paragraph type or other "organism" from the CMS that relates to the VA design system components
- print out examples from FE for paragarphs
- Gap analysis and look for alignment opportunities between design system and CMS

<details><summary>Paragraphs audit</summary>

"Paragraphs" correspond loosely to VA design system components. 

<img width="252" alt="VA_gov_High_level_content_model" src="https://user-images.githubusercontent.com/643678/140577423-7c8a57d9-b333-4da4-9005-2a43f9bff218.png">

</details>

### 3. Form widgets audit
- take the materials from the screen audit (1) and decompose into form widgets for grouping and comparison
- place like widgets together for group analysis (form into smaller groups?) 
- identify standards, variations, strengths, weaknesses, opportunities. 

<details><summary>Number of instances of each field widget</summary>

<img width="379" alt="CMS_DS_Component___Pattern_inventory__Form_widgets_-_Airtable" src="https://user-images.githubusercontent.com/643678/140570045-4827b723-daf9-40ca-b23a-1d27d7b50807.png">

</details>

### 4. CMS navigation IA audit

- print out existing navigation structures available to CMS users ("normal" users and content admins)
- example screens for these navigations
- card-sorting type exercises 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
