### ISSUE TITLE
Switch service locations to use hours field instead of table_field

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#6931]
## User Story or Problem Statement

As a content architect I want CMS to fully convert to user hours field instead of table_field so that we have data consistency.

The service locations paragraph used on facility health services uses tablefield for hours.  In order to push to lighthouse we want that data to have better structure.
![image](https://user-images.githubusercontent.com/5752113/157314405-78eb2572-e649-4a46-ba9a-2391adbe71ef.png)

History: 
- ~this has already been scripted by Kaise  as it applied to nodes.~  Kaise worked out the logic to take rows of data from the facility API and convert it to the office hours format.  It is in a migrate process plugin here. 
docroot/modules/custom/va_gov_migrate/src/Plugin/migrate/process/VAFieldOfficeHours.php
 I don't think we can fully re-use it, as it is pulling from a  migrate source rather than a node source, but the cleanup and conversion should be similar.  Use it for inspiration.
- Now we need to point it at paragraphs for service locations.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public

## Acceptance Criteria

- [x] On paragraph type `service_location`  the existing field `field_facility_service_hours` has been replaced by the existing field `field_office_hours` and data is moved from the old field to the new field.
- [x] A script located scripts/content/ should use batching and open and save the nodes as it runs.
- [x] Data is not lost.  Anything that can't be a time, must go into the comment field.

## Implementation steps
Steps will need to look like:

- [x] script the migration https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8533
- [x] run the migration on prod to populate data for FE 
- [x] FE builds new display  https://github.com/department-of-veterans-affairs/va.gov-team/issues/39436 
When FE goes live we 
    - [x] Hide field `field_facility_service_hours` and show 'field_office_hours' in cms #8550 
    - [x] Re-run script on prod `drush scr scripts/content/VACMS-6931-switch-service-locations-office-hours.php`
    - [x] Notify editors / process bad entries from the outliers.csv #8708
    - [x] #8709

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Blocks #8017

**Comment by kevwalsh** [comment]
I think this needs to start with an audit of what's in field_hours to see what shape the data is in. @msbtterswrth built a tool for that.

**Comment by JayDarnell** [comment]
@swirtSJW so apparently you can't reuse a field from a node entity on a paragraph entity. That strikes me as odd. If I go to an existing node, add a new field and open the Re-use an existing field drop down I can see field_office_hours but if I go to the service location paragraph and try this the field is not present. I'll have to create a new field with the same name and settings for paragraphs.

**Comment by JayDarnell** [comment]
@swirtSJW Adding AC to make sure the non-clinical services view is updated to utilize this new field.

**Comment by JayDarnell** [comment]
As it turns out, the content currently stored in the table field is quite diverse. The following list of items are just a small subset of what we might encounter while trying to port this data to the new Office Hours field:

- 8:00 a.m. to 4:30 p.m.
- 7:30 a.m. to 3:30 p.m. ET
- 8:00 a.m. – 4:30 p.m. ET
- 8:00 a.m. to noon*
- 8:00 AM to 4:30 PM
- 7:30 a.m. to 4:00 p.m. - inpatient only
- 9:30 a.m. - 11:30 a.m. &amp;amp; 1:00 p.m. - 3:00 p.m.
- 8:00 to 11:30 a.m. and 12:30 to 2:30 p.m.
- 6am-9pm
- Closed/
- Closed*
- 24/7

**Comment by swirtSJW** [comment]
Re-opening as this is the epic.

**Comment by kevwalsh** [comment]
Closing! Related work happening in various sub-epics of #9318
