### ISSUE TITLE
Clarify duplicate place names listed on facility location drop-down menu when creating VA Events

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#6938]
## User Story or Problem Statement

As a content publisher on VA.gov, I need the Facility Location drop-down menu to no longer contain duplicate place name listings when creating a new Event so I can be sure that I am adding my Event to the proper location.

At this time, there are duplicate facility location options listed when creating an Event -- such as 3 instances of "Hamilton VA Clinic" and 4 instances of "Greenville VA Clinic." (see screenshots below)

As a content publisher, how do I know whether this is referring to the Greenville VA Clinic in North Carolina or the Greenville VA Clinic in North Texas? 

According to https://en.wikipedia.org/wiki/Greenville , there are 30 states that have a Greenville -- in fact, California has 2, and Indiana has 3! 

Ultimately, when creating a new Event, I have no way of knowing if I'm assigning it to the proper Greenville.

**Screenshots of facility location drop-down menu on Event creation page:**

![image](https://user-images.githubusercontent.com/9059428/140817312-5cf87444-2093-4467-aeb6-b693bba5a848.png)

![image](https://user-images.githubusercontent.com/9059428/140817423-d8c41207-7d68-45d9-a1f8-143c8d0f2e6a.png)

## Acceptance Criteria

- [ ] ~If these listings are all referring to the _same_ duplicate place name listing (i.e. each listing is referring to the same Greenville), then the duplicates are removed from the list and there is only one displayed, not two/three/four/etc.~

- [ ] The VA system name  should appear  following the facility name like 
![image](https://user-images.githubusercontent.com/5752113/140927075-066490ef-d01e-4a58-a559-7b6cff06e09d.png)

- [ ] Requires design review

## Implementation steps
~We will first need to determine whether these listings are all referring to the same place name listing before proceeding.~ 

~For the four listings of VA Greenville, are they all referring to the same one in the same state, or are they all different Greenvilles in different states? Repeat for each duplicate listing.~

On node bundle `event` the field `field_facility_location` is an entity reference field.  It is using a simple select list.  This needs to be modified to show more information.  This should use the same method as 
node: health_care_local_health_service  ->`field_facility_location`   It will NOT use the javascript winnowing logic, but should display facilities like this  (facility name, followed by system name.)
![image](https://user-images.githubusercontent.com/5752113/140926330-cbeddf1f-a290-4123-b019-e71045f42201.png)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by stefaniefgray** [comment]
Per https://va-gov.atlassian.net/browse/VAHELP-2618

Jacksonville is North Carolina  
Jacksonville 1 is Florida 
Jacksonville 2 is North Carolina  

Additionally, as pointed out by the PAO who filed this ticket, if you've selected the wrong one and the content has been pushed for the live site, then you will need to wait until the next content release for the right one to be published after editing the page.

**Comment by swirtSJW** [comment]
This entity reference View needs to be updated to include the medical system  after the facility name.
![image](https://user-images.githubusercontent.com/5752113/140821180-8ae5cd96-8375-4719-8d2d-1ed31c3e5e1e.png)

**Comment by swirtSJW** [comment]
@netboss  Consult with Ethan if you have trouble figuring out how he appended the system name in the select list.
