### ISSUE TITLE
Content Release Triggered from the CMS should be de-duplicated

### ISSUE THREAD

**Issue by indytechcook** [department-of-veterans-affairs/va.gov-cms#6983]
## Description

Currently when a build is triggered from Drupal to Github Actions it is sent immediately.  Github Actions does not have built in queuing or de-duplicating which fulfills our needs.  To help with not sending too many jobs to GitHub Actions the requests should be queued and run in Drupal cron.

GHA only allows one running and one queued job at a time. When multiple items are sent to GHA, the running job could be canceled if the incoming request is seen as "newer" by GHA.  A new job is specified by the commit.  Since Drupal always sends requests to GHA using the `main` branch, it's possible that the newer job will cancel the currently running job.  Since the content release job can run for 40 minutes, it's possible for a content release to be delayed by hours due to this scenario.  Work is being done in GHA to make sure a currently running job completes fi the "build" step has started.

* Periodic jobs are run using `task`:
  * https://github.com/department-of-veterans-affairs/devops/blob/6f31cd30f1d7091bcd128310d548559023745cb5/ansible/cms/cms-periodic.yml
  * https://github.com/department-of-veterans-affairs/devops/blob/6f31cd30f1d7091bcd128310d548559023745cb5/ansible/cms-test/cms-periodic.yml 
  * https://github.com/department-of-veterans-affairs/devops/blob/f0cde4a913a7a94435bda9bbdc00612022a31877/ansible/Jenkinsfiles/cms-test/cms-periodic.groovy
  * https://github.com/department-of-veterans-affairs/devops/blob/6f31cd30f1d7091bcd128310d548559023745cb5/ansible/cms-test/cms-daily.yml
  * http://jenkins.vfs.va.gov/job/cms/job/cms-periodic-prod/
* Periodic yml job: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tasks-periodic.yml

## Tasks

- [ ] Change the `va_gov_frontend_build_type` `brdgha` to send a job to Drupal queue.
- [ ] Change periodic job to run every 5 minutes
- [ ] Periodic job changes:
  - [ ] Queue job should run every 5 minutes
  - [ ] Current jobs under `periodic` should run every 15 minutes

**Comment by TheBoatyMcBoatFace** [comment]
No longer an issue

Solved w/ continuous release
