### ISSUE TITLE
VAMCs should be listed in alpha order for admins on Banner form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#6995]
## User Story or Problem Statement

As an editor with access to more than one VAMC, i should see them listed alphabetically on `/node/add/full_width_banner_alert`

![image](https://user-images.githubusercontent.com/643678/142439027-a6ee47e0-8294-4c41-9d13-382e93e57870.png)

## Acceptance Criteria
- [ ] VAMC systems are listed alphabetically on the form
- [ ] Test as jorge.cardich-fuster@va.gov, who should see all the VAMC systems in VISN 5, listed alphabetically.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
