### ISSUE TITLE
Build out Confluence documentation

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#6999]
## Background
Documentation is often split across several tools/teams/platforms and can be hard to intake. 

### User Story or Problem Statement

How can we improve the usability and findability of documentation specifically around CMS configurations (content/paragraph types, fields, custom modules etc)?

### Affected users and stakeholders

* Sitewide/Platform Developers
* UX/Design System team members
* Support team members

### Hypothesis

Based on past experience, pulling everything into one central space (whether that is confluence or someplace else)  can improve usability and findability of documentation. It can also provide additional context and notes which may be hard to find/store in other places. 

We believe that moving some cms requirements documentation will allow teams to access the same information and collaborate more seamlessly. 

I have created a *very* basic sample page based on the [Office content type](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1703804976/Office+Content+Type+Requirements).

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by EWashb** [comment]
The documentation process will need to be re-thought. I'm not sure that confluence is the right space. I'm closing this in favor of other issues relating to documentation.
