### ISSUE TITLE
Move text descriptions for all long text fields above the field

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7011]
## User Story or Problem Statement

As an editor of a long text field, i want guidance _before_ i write my content, not after it, so that i don't waste my time, and that i create content that fits the content strategy based on the needs of Veterans. 

### Context

Drupal puts help text for text areas after the field, by default. 

We have 54 textarea fields. Most of them have help text. (aka field "descriptions"). 25 out of 54 also have textcounters, which shows below the field, further displacing the help text. 

<details><summary>Example</summary>

<img width="1220" alt="Edit_Vet_Center_Kona_Vet_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/142674776-f2c50923-585a-4943-99be-40c915084607.png">

</details>

## Acceptance Criteria
- [ ] We have a POC set that moves the help text for textareas above the field for all textarea fields
  - [ ] design review (spacing/hierarchy, unintended impacts, etc)
  - [ ] change management review 
- [ ] Textcounters remain below the field

## Implementation steps
Field widget twig theming? 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
Working on POC for this. Moving the description above the field is _very_ easy. Moving it between the title and the field is _very_ hard. Still thinking up ways to handle that, but here's a ss of what that would look like.

![image](https://user-images.githubusercontent.com/8375335/142698206-0478c750-5d07-4638-b49e-7cf17a05428d.png)
