### ISSUE TITLE
Improve search in Knowledge Base KB

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7012]
## Background

This is a followup to the MVP that was developed in #5705 

### User Story or Problem Statement

As a KB user, i want to be able to find solutions to my problems, or answers to my questions, about the CMS and the product i edit. 

Currently, there are a number of places where keywords are not surfacing the best result. 

[See this slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1642018276390800) for some further reporting and possible solutions, and the [first comment below.](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7012#issuecomment-1011408458)

### ACs

- [x] Work with user support team to find a number of unsuccessful searches
  - [x] Document as many as possible (one bad search is not enough data to make a decision)
- [ ] Identify ways to improve KB search
  - [x] Document ideas as discrete solutions
  - [x] Recommend a subset of these for next steps. 
  - [ ] Any recommendations to overhaul search architecture CMS should go into #1196. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
### Current search is still troublesome:

When searching for "System Health Service," the articles about adding and editing a VAMC System Health Service should appear first.

See example: https://prod.cms.va.gov/help/search?keyword=system+health+service

Instead, the article "How to add a VAMC Facility Health Service" is listed before those -- and it is the 7th result! _This is not even the correct type of health service._

**The article "How to add a VAMC System Health Service" is the 14th result, and "How to edit a VAMC System Health Service" is the 16th result.** 

It is worth noting that the results do not change if you search for "System Health Service" within quotation marks, as they do when using search engines such as Google.

Ultimately, the current search functionality may make things very difficult for our Editors who expect to see the most relevant KB articles listed first. 

### Solution:
I believe that this issue can be rectified by having search prioritize the string _word1+word2+word3_ instead of searching for each word separately (which appears to be what the current search functionality is doing).

By prioritizing the phrase system+health+service instead of searching separately for instances of "system," "health," and "service" appearing on the same page, the Knowledge Base search functionality should be able to pull up the most relevant results first.

**Comment by msbtterswrth** [comment]
List of possible use cases:

1. As a CMS user, I want to find articles about log in help, but the page I want is not at the top of the list. ([it is currently 5th](https://clarodemo-x1iumxudopspquvg1n2h3ylucye7xlhp.demo.cms.va.gov/help/search?keyword=log+in ))

**Comment by kevwalsh** [comment]
I've moved some of this to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8136 so we can close this issue!
