### ISSUE TITLE
Sitewide CMS team - Sprint 46 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7017]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

- Review Q4 goals
- Short sprint because of holidays
- 

</details>

----

<details><summary>Product support</summary>

#### FE dev 

- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30390 🎉
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30391 🎉
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/30392 🎉

#### #6872 Editorial experience 

Idea is to do some functional implementaiton first, then go through a design iteration focused largely on UX writing. 

- [ ] #6875 💧 (Ethan)
- [ ] #6873 💧
  - [ ] #6874 💧
- [ ] #6876 💧

### VAMC upgrade team support

- [ ] #6920 💧 (Jay)
- [ ] #7016 💧 (Jay)

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6414 - tracking issue for LH team, which blocks...
  - [ ] #6417 💧  - done but not merged

### #4799 VAMC Care we provide 

- [ ] #6768 💡 - Val and Denise 
  - [ ] Other issues to flow from 6768, including possibly running the script created in #6456 

#### #6919

A small governance step towards a better experience for one VAMC component, which will prevent FE errors. 

- [ ] #6918 💧 

### #6446 

- [ ] #6449 💧

### #6553 Vet Center dashboard usability research

- Readout from #6627, scheduled for 

### #6332 Required Vet Center Services

Engineering can begin but last step is dependent on design in the above epic.  

- [ ] #6639 💧 Jay/Steve
- [ ] Design editorial experience for required Vet Center services
  - [ ] Then #6640 💧 - Ethan or Jay
    - [ ] Then merge 6639. 

### #6446 Support Vet Center "official name" 

- [ ] #6623 💧 - Jay (lower priority)

## Tech debt 

- [ ] #6629 💧 - Backend, Ethan

</details>

<details><summary>Content Ops</summary>

## #2045 Connect with us 

Old tech debt... content is stored in Section vocabulary, and should be moved to office. 

- [ ] #2041 💧 (ready to merge)
  - [ ] #2044 💧 (post merge of 2041)
  - [ ] #2042 🎉  (Possibly PW team)
  - [ ] Unhide new entity ref fields, hide old entity ref field on CLP, and disable feature flag.
  - [ ] #2043 💡

## #6170 Improve meta tags across all content types 

- [ ] #6935

### #2932 Improve table component, guidance, accessibility guidelines, etc

Stretch

- [ ] #6645 
- [ ] #1171 

## CMS Account admin

TBD

</details>

<details><summary>CMS experience</summary>

## #1352  CMS Design System MVP (Claro) 

- [ ] #6887 💧
- [ ] #1818 💧
- [ ] Other work TBD (Cindy), possibly #6755 💡

</details>

<details><summary>Customer service </summary>

## Help desk

- [ ] #5684 
- [ ] #6897
- [ ] #4721 

## CMS Knowledge Base

- [ ] #6586 
- [ ] #6398 
- [ ] #6737 

</details>

----

<details><summary>Agenda for refinement Thursday November 11 (needs rescheduling for Veteran's Day</summary>

## Content Ops
- [ ] Notifications user stories 

## Facilities
- [ ] #4856 (needs user stories first) 💧
- [ ] #6623 (Facility API concerns)

### VAMC Top tasks
- [ ] Editorial experience
- [ ] Change management

Customer service
- [ ] #6558 📟  💧

</details>
