### ISSUE TITLE
Convert vagovadmin custom theme code to vagovclaro

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7022]
### User Story or Problem Statement

`vagovadmin` custom theme (a child of drupal seven) has a bunch of custom theming, SASS, twig, libraries etc.

What needs keeping? (probably most of it)

How should this porting to claro be handled?

What's the best way of organizing it?  By CMS feature? CMS-supported product? File type? etc.

This epic will contain a breakdown of all the theme poting work. 

### Affected users and stakeholders

* CMS FE devs, mostly
* Designers (design intent, what should be kept or not)

## Assumptions
* Most of the code should be kept.
* The design intent of the code is not always clear.  But folks like Ethan, Kevin, Swirt may have some background, and there's always `git blame`. 

## Acceptance Criteria
- [ ] Custom code has been ported
- [ ] Rationale for keeping vs removing code is clear. 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.
