### ISSUE TITLE
Move help text for single line text fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7048]
Like #7011 but for single line text fields. 

## User Story or Problem Statement

As an editor of a single line text field, i want guidance _before_ i write my content, not after it, so that i don't waste my time, and that i create content that fits the content strategy based on the needs of Veterans. 

### Context

Drupal puts help text for fields after the field, by default. 

We have 100+ fields that use the "Text (plain)". Most of them have help text. (aka field "descriptions").  Many of them also have textcounters, which further displaces the help text. 

<details><summary>Examples</summary>

Log in page
<img width="777" alt="Log_in___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/143158233-73afc2aa-36f4-459e-a7fd-f8ead6b22b47.png">

Campaign landing page form /node/add/campaign_landing_page
<img width="741" alt="Create_Campaign_Landing_Page___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/143158615-bd802b89-8c87-4343-b6be-12c9dcc077dd.png">

</details>

## Acceptance Criteria
- [ ] "Text (plain)" fields have help text between the label and field
  - [ ] design review (spacing/hierarchy, unintended impacts, etc)
  - [ ] change management review 
- [ ] We've identified a sample of node, media, taxonomy forms to test with.
- [ ] Textcounters remain below the field

## Implementation steps
Field widget twig theming? 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
This was taken care of via #7011
