### ISSUE TITLE
Improve login page for Claro-based admin theme

### ISSUE THREAD

**Issue by tjheffner** [department-of-veterans-affairs/va.gov-cms#7068]
## Description
Initial stab at the login page looks like this now:
<img width="1918" alt="Screen Shot 2021-11-26 at 8 31 05 AM" src="https://user-images.githubusercontent.com/11279744/143610112-dc21ca0a-16be-4273-b281-3a4ee18c4026.png">

some context here for work needed / potential pain points:
https://app.mural.co/t/vagov6717/m/vagov6717/1637124735910/44ffc5f6545eb8735dda9b150d565fd1d4440b2b?sender=u256c80c777d9834e05655616

to see this page locally, set the vagovclaro theme as the default theme. "default theme" is what controls the login page, separate from pages handled by the admin theme.

## Acceptance Criteria
- [ ] PIV login emphasized
- [ ] Has password reset available
- [ ] Buttons on the same line
- [ ] Welcome text / help text updated
- [ ] Visible indicator for which environment (local/stage/prod/etc)
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
i'm going to close this one in favour of #1269
