### ISSUE TITLE
[CAPI] API Gateway for POCs

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7080]
## Background

The Platform CMS team will be conducting several POCs to determine which environment will provide the better experience, performance, and workflow for engineers in exposing the API to the public.

### User Story or Problem Statement

As a CMS engineer, I need to make updates to the OpenAPI specification so that I can determine which mechanism (Lighthouse or AWS API Gateway) to use in order to expose the API to the public.

## Acceptance Criteria
- [ ] OpenAPI spec is updated to include entity-based and product-based APIs
- [ ] Drupal is updated to match the spec
- [ ] Dev environment is set up in Lighthouse
- [ ] Dev environment is set up in AWS Gateway

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by timcosgrove** [comment]
Closed because of depioritization
