### ISSUE TITLE
Clean up Node module permissions and consider adding some tests

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7092]
## User Story or Problem Statement

We shouldn't need redundant roles (no user shouuld need editor AND publisher), nor should we have redundant permissions to test for (eg Content Admin has bypass node permissions and shouldn't need any specific node type permissions). 

<details><summary>Screenshot</summary>

![Permissions_filtered_by_modules___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/781903fa-14b7-44b7-84ba-7d295035ad6d)

![Cursor_and_Permissions_filtered_by_modules___VA_gov_CMS.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/6e341ede-9f0d-4fcd-ad98-b92a53c15d71)

</details>

## Acceptance Criteria
- [x] Permissions updates
  - [x] Only "Content creator" roles should have Create permissions. Editor / Reviewer / Publisher should not. 
  - [x] No role should have Delete content
  - [x] No role should have Delete revisions content
  - [x] All node types should be editable by all users. Node access (what nodes can i edit) and content moderation (what moderation state can i save as) are determined by Workbench access and Content moderation respectively. 
  - [x] No role should have any permission related to "edit own" or "delete own"
  - [x] Content publisher should have "Revert revisions" for all content types. (again, access is determined by workbench and conent moderation). 
  - [x] All roles should be able to View revisions for all content type _except Knowledge Base_.
- [ ] Stretch: investigate ways we might be able to abstract out some rules into classes of permissions.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by netboss** [comment]
@kevwalsh 
Just to verify and confirm, the content type "Banner" = "Full Width Alert", correct?

**Comment by kevwalsh** [comment]
> Just to verify and confirm, the content type "Banner" = "Full Width Alert", correct? Or could it be "Banner" = "Promo Banner"? Either way both have the "Content Admin" role with the "Create new content" permission checked. Should both be unchecked (are redundant)?

Both content types (Full width alert and Promo Banner) should have the same permissions as all the other types. Content admin doesn't need it, and should'nt have it,  because they have "bypass content permissions."

> Also, the "VAMC Facility Non-clinical Service: Edit any content" permission for the "Content Editor/Reviewer/Publisher" isn't checked for these roles, should it be checked for these roles?

Yes, but Jay has a separate PR just for that content type. Good catch!

**Comment by netboss** [comment]
@kevwalsh 
I think all permissions should be set now. What I'm not clear about is the _stretch_ part of this request.
