### ISSUE TITLE
Rebuild field_related_links on VAMC system as maximum 8 normal link fields. 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7096]
## User Story or Problem Statement

As a VAMC system editor, 
* i should be able to provide up to 8 links to hightlight content at my VAMC for the "Spotlight" block, so that i can direct Vets to important VAMC specific content
* i should not able to change hte content design from "In the spotlight at [VAMC system]"
* i should not be presented with useless fields
* i should know that i can only add 8 links. There's a limit on the FE already, but i want that limit to be enforced for me in the UI. 

As a Veteran, i should not be overwhelmed with marketing links. 

<details><summary>Screenshot</summary>

https://pr7095-5csv0a1zelzeougjyf7dk6tflgusmttz.ci.cms.va.gov/node/14997/edit

<img width="1273" alt="Edit_VAMC_System_VA_Chillicothe_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/143950499-8c568298-d1dd-4386-addd-ed9d12f86add.png">

</details>

## Acceptance Criteria
- [ ] Feature flag for VAMC_SPOTLIGHT_LINKS
- [ ]  New field `field_vamc_spotlight_links` 
  - [ ] Up to 8 links (field storage setting)
  - [ ] Link field, with required URL and label, external or internal
  - [ ] Linkit enabled. 
  - [ ] Character count set to... TBD.
  - [ ] Field label "In the spotlight"
    - [ ] Stretch: Field label for editors changes to "In the spotlight at [node title]" eg "In the spotlight at VA Chillicothe health care" on node/14997/edit
  - [ ] Field is added to the same spot in the form, and node view, as the existing `field_related_links`
  - [ ] Design review for field labels and help text
- [ ] Update script/migration to move the content from the List of link teasers to the new field.
  - [ ] Abandon the "In the spotlight at []" header, since it will be hardcoded
  - [ ] The first 8 links get migrated to the new content model
- [ ] Runbook 
  - [ ] Seamless transition for editors
  - [ ] Works with feature flag
- [ ] Follwup issue to delete `field_related_links` from VAMC system content type. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
