### ISSUE TITLE
Discovery: Custom contact forms for VAMC pages

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7121]
## User Story or Problem Statement

As a VAMC webmaster, I need a way for VA.gov users to provide feedback, so I can address with content or other webpage based ways.

This request came in through helpdesk ticket [VAHELP-2889](https://va-gov.atlassian.net/browse/VAHELP-2889).

## Acceptance Criteria
- [ ] The PO has agreed to prioritize this
- [ ] Spike on pain points, problem we're trying to solve
- [ ] Scope out solution
- [ ] Implement in relation to other priorities

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
I will run this by Dave to see if he wants to prioritize this.

@davidconlon if you see this before i get a chance to talk it through with you (Tues AM sync or refinement), feel free to comment.

**Comment by davidconlon** [comment]
@cmaeng I'll bring this up with Jenny. We should be clear that product changes are defined both by OCTO and VHA Digital Media jointly. (I don't wanna be the only bad guy here and they need to know that VHA has had a say in this)

Shooting from the hip here I'm pretty sure I'm not going to advocate for prioritization.

Particularly, we need to ensure that all forms comport with VA.gov forms style, flows, etc. and not just any form would be created by folks in the field because of PRA concerns. enabling folks in the field to spin up forms for whatever/however they want would just be bad.

In addition we'd want to understand the workflows inherent with this and responses. 
How many responses do you typically get?
What kinds of responses do you get?
What happens when you get a bad review? How do you act on that? 
What happens if a Veteran in crisis uses it?
How is this different than the Forsee survey in-use?

This is a slippery slope and I would lean more toward "use an email link and/or phone number rather than an online spam form"

**Comment by cmaeng** [comment]
thanks @davidconlon, completely agree with everything stated above. my sense it that the juice is not nearly worth the squeeze for this. i'll wait until you have a chance to sync with JHL before responding any further.

**Comment by Agile6MSkinner** [comment]
Abandoned for years and written off in the last comment. Closing.
