### ISSUE TITLE
Bad URL for default og:image meta tag

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#7141]
## Describe the defect
It looks like frontend is pulling a bad url for og:image meta tag `<meta property="og:image" content="https://www.va.govhttps://www.va.gov/img/design/logo/va-og-image.png">` 

## To Reproduce
1. Go to https://www.va.gov/disability/how-to-file-claim/
2. View source in your browser tools 
3. Find the og:image meta tag 
4. See `<meta property="og:image" content="https://www.va.govhttps://www.va.gov/img/design/logo/va-og-image.png">`  instead of `<meta property="og:image" content="https://www.va.gov/img/design/logo/va-og-image.png">` 
5. Confirm through a testing tool (https://www.opengraph.xyz/url/https%3A%2F%2Fwww.va.gov%2Fdisability%2Fhow-to-file-claim%2F/) the image is not loading.

## Expected behavior
A default image should load in the preview cards (twitter/facebook/slack)

## Screenshots 
![image.png](https://images.zenhubusercontent.com/61671a60c72e6d0337fd8bcd/c5a77822-8173-4ed2-98c8-88252c6dbc75)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
CMS data is correct.   Looks like some bad string concat on the frontend
![image](https://user-images.githubusercontent.com/5752113/144510483-aec4cb4b-0255-46aa-9993-5032f3ee6d50.png)

**Comment by swirtSJW** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #33552](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33552) via [**ZenHub**](https://www.zenhub.com/)
