### ISSUE TITLE
Modify url alias audit tool

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7154]
## User Story or Problem Statement

As someone who needs to audit links and titles I need a report that allows sufficient filtering, searching, and export abilities
to give me data I can operate with.

## Acceptance Criteria
Broaden the scope of https://prod.cms.va.gov/admin/content/audit/detail-pages-urls
- [ ] change path to /admin/content/audit/page-urls
- [ ] Change title to `URL audit and bulk update`
- [ ] add search for url path (might not be possible in Views)
- [ ] 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
@swirtSJW I added some user stories. 

I'd like to keep that view at admin/content/audit/detail-pages-urls focused on VAMC detail pages, which are the enemy of structured, governable content, and which are the focus of the two VHA user stories. 

We already have admin/content/audit for broader. I think your ACs could apply to that broader audit tool. Does that make sense? Maybe we should fix these both at the same time.
