### ISSUE TITLE
Support Oracle Health (formerly Cerner) cutover

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7158]
Previous: #6571. We added a hidden field to VAMC system and set Spokane to Cerner. 

## User Story or Problem Statement

VistA is the legacy electronic health record (EHR) system, [Cerner is the new one](https://www.hcinnovationgroup.com/cybersecurity/article/13028723/breaking-va-will-replace-vista-with-cerner-ehr-and-intends-to-create-integrated-platform). Each health system will cut over for the next 5 years. 

This is high priority because Spokane is already using Cerner and they are blocked from going live until this is supported. Other VAMCs (Cleveland?) are switching to Cerner soon.

### User Story or Problem Statement

As an admin, I can toggle VAMCs between VISTA (default, legacy system) and Cerner so that this status is available through the content API for various Veteran products and tools. 

As a content editor, i can see whether my system is set to VISTA or Cerner, and how this is setting governed, and what it affects for Veterans (possibly a link to a KB article), so that i can verify it and request changes if necessary to the right organization. 

## Collateral
* [React widget Cerner flow Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1651166973924/bc8bc44cab4e4ae7b84819d22ba89b11aa70e5e1?sender=u252e7152800e3981889d1910)
* [React Widget notes (Google doc)](https://docs.google.com/document/d/1uX4mFn4LBPVYpKWpCze8JSC8mBHIFcRtRTqM6ffCMhE/edit#)
* [Test User Dashboard (TUD) usage notes](https://dsva.slack.com/archives/CE4304QPK/p1649684013382119)

## ACs

These still need refining.
- [x] Email notification to editors about the change as their facility moves to Cerner (rolling cutover)

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)## Implementation steps

TBD

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Noting: Lovell is also cutting over to Cerner in 30 days from today-ish, but Facilities team is handling the CMS / FE pieces.

**Comment by mmiddaugh** [comment]
CTA widgets and cutover process largely managed by Health portfolio teams
