### ISSUE TITLE
CMS sitewide team Sprint 47 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7159]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

1. If you want to see this on your board, assign yourself to this issue. (It's also pinned In progress)
2. Q4 priorities review
2. Last full sprint before holidays.
3. Some Q4 epic planning 
4. Various tech debt issues, will  
5. Trying to organize into workstreams

</details>

----

<details><summary>Product support</summary>

##  #6644 Promo banners MVP 

- [x] #7086  🎓  

## Recurring events 

- [ ] #6122 🥅, building off a new feature branch created from #6057 (we need to merge FE spec with our design from #6067)

## #1605 Other event related work (stretch)

- [ ] #2460 💧 

### Detail page reporting 

- [x] #7154 

#### FE dev 

Aman and Ryan

- [ ] #7041 🎉 
- [ ] #7042 🎉
- [ ] #7043  🎉
- [ ] #7133 
- [ ] #7134 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/21561 (possible)

#### #6872 Editorial experience for top tasks and service locations

- [x] #6873 💧 (Jay) 🥅
- [ ] #6874 💧 (Jay)
- [x] #6876 💧 (Jay)
- [ ] #7166 and - #7167 💧Defect
- [ ] #6872 (Design mini-epic)

### VAMC upgrade team support - VAMC system renaming

- [ ] #7163
- [ ] #6920 💧 (Ivan)

### #6413 Improve communications on how to update Facility data #6413

- [ ] #6417 💧  - needs rebasing and merge. 

### #4799 VAMC Care we provide 

- [ ] #6768 💡 - Val and Denise readout this Thursday
  - [ ] Other issues to flow from 6768, including possibly running the script created in #6456 

### #6332 Required Vet Center Services

Followups to #6640 
- [ ] #7144 💧
- [ ] #7145 💧
- [ ] #7146 💧

### #6736 Vet Center dashboard 

Refine Epic based on usability study findings.

</details>

<details><summary>Content Ops</summary>

## Tech debt and defects
- [ ] #7119 💧 Ethan - PR ready 
- [ ] #6950 💧 Iván - PR ready
- [ ] #7161 💧
- [ ] #7162💧
- [ ] #7092 💧

### Connect with us epic

- [x] #6896 
- [ ] Remove other fields

## Accessibility tools

- [ ] #6980 💧

## #6170 Improve meta tags across all content types 

- [ ] #6935 💧

### #2932 Improve table component, guidance, accessibility guidelines, etc

- [ ] #6645 

</details>

<details><summary>CMS experience</summary>

## #1352  CMS Design System MVP (Claro) 

- [ ] Define MVP  🥅
- [ ] Clean up epic and backlog

### Design 
- [ ] Design tokens
- [ ] Other work TBD (Cindy), possibly #6755 💡

### #7022 Port code from vagovadmin to vagovclaro (mostly Tanner)
- [ ] Create MVP feature branch for development
- [ ] #6887 💧 (Tanner, may need some input from Ethan, Kevin, Steve, others)
  - [ ] Individual stories.

### Group 

</details>

<details><summary>Customer service </summary>

## Helpdesk

- [x] #6785 
- [ ] #6807
- [x] #5684 
- [x] #6945 

## CMS Knowledge Base

</details>

----

<details><summary>Needs refinement</summary>

## Content Ops
- [ ] Notifications user stories 

## Facilities
- [ ] #4856 (needs user stories first) 💧

Customer service
- [ ] #6558 📟  💧

</details>
