### ISSUE TITLE
Create smartdate data resolver for recurring events 2a

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7170]
## User Story or Problem Statement

To reduce the effort for the content-build on the conversion from single date events to recurring events we need the new data available along with the old style data. 
on event: field_datetime_range_timezone  

We need to play a shellgame in a resolver where we move the multiovalue recurring array of objects into a different property and re-populate the current properties with the most date-time that is most closely upcoming, but not past.
Prior to recurring we have this data stucture
![image](https://user-images.githubusercontent.com/5752113/145238493-f7f24d90-eda2-45bf-98fe-d0e8e00d674b.png)

This is part 1 of the conversion.  

Sample query 
```
query {
  nodeById(id: "23261") {
    title,
    status,
    type {
      targetId
    },
    ... on NodeEvent {
      fieldDatetimeRangeTimezone{
        value,
        endValue
        timezone
      }
    }
  }
}
```
Once recurring is turned on the data looks like this 
![image](https://user-images.githubusercontent.com/5752113/145246046-ada1473f-b88d-4967-a4e0-c4e6eb00abf6.png)

## Acceptance Criteria
![image](https://user-images.githubusercontent.com/5752113/145263041-4b809ded-7944-434b-bdab-01398eb37bf7.png)
- [ ] creation of va_gov_event module
- [ ] GraphQL data resolver is created for namespace Drupal\va_gov_event\Plugin\GraphQL\Fields\Entity\Fields\smartdate;
example: docroot/modules/contrib/entity_field_fetch/src/Plugin/GraphQL/Fields/Entity/Fields/EntityFieldFetch/EntityFieldFetchFetched.php
  - [ ] data resolver  makes the format of the event data look like it does now in graphQL with the addition of  fieldDates which will  contain the new format.  array of objects
- [ ] Most upcoming dates are swapped in to replace current date time data in fieldDatetimeRangeTimezone  as an object.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Summary of call with @ethanteague:
It may be that the field property level resolver in the example is too deep to be able to pull this off because it only has access to one property at a time.
He is going to do a "quick" test case to see if its possible to get either a  field level resolver or entity level resolver that would have access to all values of the multivalue at the same time.

**Comment by swirtSJW** [comment]
@ethanteague I think you may have to try referencing 
deriver = "Drupal\graphql_core\Plugin\Deriver\Fields\EntityFieldDeriver"

If that doesn't work maybe 
deriver = "Drupal\graphql_core\Plugin\Deriver\Types\EntityBundleDeriver"

Examples of other resolveers are here 
docroot/modules/contrib/graphql/modules/graphql_core/src/Plugin/GraphQL/

You could likely get the fastest answer to where we need to intercept by setting some breakpoints in similar resolvers and see what is available ^^

**Comment by ethanteague** [comment]
Alternate approach (filters in content-build vs cms resolver) will be handled by Public websites team. See: https://dsva.slack.com/archives/C52CL1PKQ/p1639140996475000
