### ISSUE TITLE
Implement improved help text for Vet Center service description, from #7189

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7210]
## User Story or Problem Statement

See #7189

## Acceptance Criteria
- [ ] Help text from #7189 has been implemented to the Vet Center service form.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by suzanne-gray** [comment]
Hi Ethan! This help text is ready for you. View text and instructions in [this figma file](https://www.figma.com/file/SfJsjIxAySehvDsrgyusxh/Standardized-content-design-patterns?node-id=302%3A219)

And here's a screen shot of where we're headed: 
<img width="692" alt="7189 help text" src="https://user-images.githubusercontent.com/90172187/145334960-a9249740-7f4c-4c5d-9da2-0a6e0e25790f.png">
Thanks!!
