### ISSUE TITLE
Create two hidden field_office fields and migrate data from field_related_office

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7219]
## Background

Priority of this is TBD

### User Story or Problem Statement

Via #2045, we got two new fields `field_related_office`. Those two fields should be `field_office` instead, because `field_office` is an existing standard.

 

### ACs
- [ ] `landing_page` and `campaign_landing_page` use `field_office` not `field_related_office`
- [ ] No impact on editors. UI and data should be effectively the same before and after
- [ ] No impact on FE. Transition between fields should be seamless, probably by supporting two content models simulataneously

### Runbook

1. Create the `field_office` fields, hidden on the two content types, but otherwise identical to `field_related_office`. 
2. Create script to sync data from `field_related_office` to `field_office` continuously, to support both content models. This can potentially be combined with 1, or go in a followup PR.
3. Work with PW to refactor FE to use `field_office` instead of `field_related_office`. 
4. When FE is complete, swap fields
5. Remove deprecated `field_related_office` fields. 

### Affected users and stakeholders

* PW FE devs

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by FranECross** [comment]
@jilladams @davidmpickett Do you know if this still needs to happen?

**Comment by jilladams** [comment]
Oof. I'd want a Drupal person to dig in and clarify / confirm. We touched some of this with the "Draft content in prod" epic Connect with us tix - #19547, but I don't know off the top of my head which fields and how they connect here there and everywhere, etc. Although: If we scheduled #19833 along with it, we'd know for sure for sure AND have it documented.

**Comment by davidmpickett** [comment]
Doing a field search in the CMS returns no results for `field_related_office`. @omahane's [recent PR](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/20303/files) seems to have removed all instances, so I think this ticket can safely be closed
