### ISSUE TITLE
VAgovClaro MVP definition

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7225]
## User Story or Problem Statement

CMS team has a common understanding of what's going into our first ship. 

## Acceptance Criteria
- [ ] #1352 is udpated with a list of MVP features, and non-MVP features
- [ ] Other features or product enhancements are added to CMS design system backlog

## Implementation steps
Sprint 47 meetings to align on a feature set. 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
