### ISSUE TITLE
Update section names and urls

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7266]
## User Story or Problem Statement

As a CMS user, i want URLs and breadcrumbs that are concise so that i can see where i am by looking at the URL.

Currently, the top section is quite long and takes up a lot of space.

## Acceptance Criteria
- [ ] All section URLs have been updated to use their respective administration's acronym, not the full name
  - [ ] For example, `/section/vha/vamc-facilities/va-alaska-health-care` has been renamed to `/section/veterans-health-administration/vamc-facilities/va-alaska-health-care`
- [ ] Nothing breaks on the FE (particulary, the benefits hub pages that seem to have some reliance on section names still)

## Implementation steps

This has been tested on staging and works OK, but the FE aspect of this has not been tested
- [ ] Rename the top 5 sections to use their acronym version (_VHA_ not Veterans Health Administraiton)
- [ ] Go to admin/config/search/path/update_bulk Bulk generate URL aliases for taxonomy terms, and update 

<details><summary>Before</summary>

Long URLs
<img width="1004" alt="Cursor_and_kevin_walsh___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145726223-1fcaaed1-a221-4c20-b82c-086278f7aa26.png">

Long breadcrumbs

<img width="1096" alt="Cursor_and_VA_Portland_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145726380-794c8bbc-6025-40b4-bf28-595b48569c8d.png">

</details>

<details><summary>After</summary>

Shorter breadcrumbs and better URLs

<img width="1133" alt="VA_Detroit_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145726477-0b5b028f-8f27-4bb0-860d-1b9e5143640e.png">

Impact to the "home" page

<img width="818" alt="kevin_walsh___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145726207-6e551926-8b22-4f4c-a6af-420b3c7f255a.png">

</details>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
Testing [here](https://main-7jjb45gshbie5yjkpntrlfvjfvgzx2cr.demo.cms.va.gov/admin/content) before updating on prod

**Comment by kevwalsh** [comment]
@msbtterswrth your Front URL should be https://web-7jjb45gshbie5yjkpntrlfvjfvgzx2cr.demo.cms.va.gov/disability/eligibility/ 

I didn't realize this, but apparently when you click through the megamenu in tugboat, it takes you to dev.va.gov instead of to relative paths for the current environment. I'll start a slack thread about this, it would be nice to get this fixed. 

But yeah, Benefits Hub menus seem to be working well and i think you can proceed on prod!

**Comment by msbtterswrth** [comment]
Updated on prod [here](https://prod.cms.va.gov/admin/structure/taxonomy/manage/administration/overview). 

![image](https://user-images.githubusercontent.com/8375335/146395939-526a389d-9ea4-438f-ac0c-088cfa9e57d3.png)

**Comment by swirtSJW** [comment]
This AC seems backwards from the desired outcome:
```
- [ ] For example, /section/vha/vamc-facilities/va-alaska-health-care has been renamed to /section/veterans-health-administration/vamc-facilities/va-alaska-health-care
```

**Comment by swirtSJW** [comment]
Closed by https://github.com/department-of-veterans-affairs/va.gov-cms/pull/7362
