### ISSUE TITLE
Migrate VISN 19 top task content for medical records, register for care, and billing and insurance

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7267]
## User Story or Problem Statement

VISN 19 has agreed to have their top task pages serve as tests for 3 hardened pages. 

We have an opportunity to create test content in prod for both top task pages and their respective nonclincial facility services.

<details><summary>URLs for VISN 19</summary>

Each of these will need at least two nodes: 1 and only one top task page, and at least one nonclinical facility service node.

To track new hardened content, we can use [this filtered view of VISN 19 nodes](https://prod.cms.va.gov/admin/content/audit?title_op=contains&title=&type_op=in&type%5B%5D=vha_facility_nonclinical_service&type%5B%5D=vamc_system_billing_insurance&type%5B%5D=vamc_system_medical_records_offi&type%5B%5D=vamc_system_register_for_care&moderation_state_op=in&section=175). 

- [x] https://prod.cms.va.gov/cheyenne-health-care/register-for-care
- [x] https://prod.cms.va.gov/cheyenne-health-care/billing-and-insurance
- [x] https://prod.cms.va.gov/cheyenne-health-care/medical-records-office
- [x] https://prod.cms.va.gov/eastern-colorado-health-care/register-for-care
- [x] https://prod.cms.va.gov/eastern-colorado-health-care/billing-and-insurance
- [x] https://prod.cms.va.gov/eastern-colorado-health-care/medical-records-office
- [x] https://prod.cms.va.gov/eastern-oklahoma-health-care/register-for-care
- [x] https://prod.cms.va.gov/eastern-oklahoma-health-care/billing-and-insurance
- [x] https://prod.cms.va.gov/eastern-oklahoma-health-care/medical-records-office
- [ ] https://prod.cms.va.gov/montana-health-care/register-for-care
- [ ] https://prod.cms.va.gov/montana-health-care/billing-and-insurance
- [ ] https://prod.cms.va.gov/montana-health-care/medical-records-office
- [ ] https://prod.cms.va.gov/oklahoma-city-health-care/register-for-care
- [ ] https://prod.cms.va.gov/oklahoma-city-health-care/billing-and-insurance
- [ ] https://prod.cms.va.gov/oklahoma-city-health-care/medical-records-office
- [ ] https://prod.cms.va.gov/salt-lake-city-health-care/register-for-care
- [ ] https://prod.cms.va.gov/salt-lake-city-health-care/billing-and-insurance
- [ ] https://prod.cms.va.gov/salt-lake-city-health-care/medical-records-office
- [x] https://prod.cms.va.gov/sheridan-health-care/register-for-care
- [x] https://prod.cms.va.gov/sheridan-health-care/billing-and-insurance
- [x] https://prod.cms.va.gov/sheridan-health-care/medical-records-office
- [x] https://prod.cms.va.gov/western-colorado-health-care/register-for-care
- [x] https://prod.cms.va.gov/western-colorado-health-care/billing-and-insurance
- [x] https://prod.cms.va.gov/western-colorado-health-care/medical-records-office

</details>

## Acceptance Criteria

- [x] A subset (number TBD based on other ACs) of the above pages have had their content migrated to their new "hardened" structured content equivalents. 
- [x] Designers have a sense of the content, for editorial experience design purposes.
- [x] FE and BE devs have some real content to work with for implementation.
- [x] Training / KB / change management team has a sense of how to communicate what each VAMC editor will need to do, and how to document it. 

Possible followup: Test concepts or experience with VISN 19 editors. 

## Implementation steps
- [x] Create clinical health services for each of the services offered
- [x] Fill out any additional fields required by their respective top task pages

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by suzanne-gray** [comment]
Here's a spreadsheet where we're [tracking the migration](https://docs.google.com/spreadsheets/d/1dAGg4RxoirPRpbjkyoIxafoPwcbN7IwuhOkRysd_1mg/edit#gid=1103235992)

**Comment by suzanne-gray** [comment]
@kevwalsh I'm calling this done since the ticket is about prepping for our work, not migrating all of VISN 19 for real.
