### ISSUE TITLE
Remove node link report from node edit screens.

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7268]
## User Story or Problem Statement

On the proofing page (node view), the node link report provides valuable feedback to editors to help them get rid of broken liks in their content.

Earlier hypothesis:
* **Editors may want to be able to refer to node link report results _while editing_, because report is handy.** 

Via user research (Vet Center usability study, for example), we have learned a few things about it
* page load times are hurting the dashboard functionality (anchor links). 
* editors are ignoring it on these pages. "I never look at that". 
* because it almost always shows, whenever there's an untestable links (eg phone numbers), there's some alert fatigue happening. 

New hypothesis
* **_Most_ times that node link report is seen on edit screens, the editor has not recently edit that content, greatly limiting the value of node link report in that space causing unnecessary alert fatigue, and friction on accomplishing their task.**

<details><summary>Diagram showing node link report workflow</summary>

<img width="727" alt="Diagram showing node link report workflow" src="https://user-images.githubusercontent.com/643678/145829877-3fbf5139-0e18-4500-b76b-c1846c6a7f8a.png">

Original is stored in https://app.mural.co/t/vagov6717/m/vagov6717/1582047974352/d8729998a7a3ea6cdd6aae90b83305f46bfa2483?sender=kevinwalsh8610 at the bottom left

</details>

## Acceptance Criteria
- [ ] Node link reports are removed from Vet Center content type edit screens
- [ ] Untested links alert is removed from ALL screens 

## Implementation steps

Block config: hide node link report on Vet Center edit screens

<details><summary>Node link report config</summary>

<img width="1031" alt="Node_Link_Report_Admin___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/146078328-495bda7d-12aa-416e-b436-fd0e6f383f70.png">

</details>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
@kevwalsh  It is just a config change to make it not show the untested links.  I have no concerns about disabling that.

I want to look into bigpipe blocking document ready.   I would think that should not be happening.  I am also not sure that using bigpipe for node link report is not breaking some of the caching that is already baked into node_link_report.

I do have concerns that fixing a broken link... especially one of the 508 fails  is hard to deal with if you can't see it while editing.  But it is an easy toggle to disable it on edit and only have it show on node view.  It is just a config change.

**Comment by kevwalsh** [comment]
@swirtSJW ok let's keep this issue for just removing the link on edit screens. as above, the good intent for putting it there is outweighed by the impact on overall experience, alert fatigue, and some of the technical issues around form load times. We can tackle some of those in a followup. One idea is to show the broken link report on edit only when coming from the node view screen.

**Comment by swirtSJW** [comment]
@kevwalsh  Wait... the scope just changed from vetcenters to ALL.   Lets talk this out, I think there are some other ramifications to doing that.

**Comment by swirtSJW** [comment]
Closing this as I don't think it is a direction we want to go.
