### ISSUE TITLE
Improve Vet Center editor experience - dashboard and other

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7269]
## User Story or Problem Statement

Vet Center dashboard usability research (#6553) yielded some ideas for [low effort, high value improvements](https://app.mural.co/t/vagov6717/m/vagov6717/1638904930544/bf162a8903b637f0e529c179aa6e6e71a90d6b7e?sender=kevinwalsh8610).

Other known stories, not from usability research (this list is incomplete):
- As a Vet Center editor, i want know which of my facilities is archived (and therefore not visible on va.gov), particularly CAPs
- As a Vet Center editor working on draft content (such as a service), i want to know what's in draft vs published, so that i can know what changes are not complete. 
  - Also worth considering - remove editorial workflow tools from certain content types, such as Vet Center services. 
- As a Vet Center editor, I want to easy see the list of satellite locations associated with my Vet Center. 
  - Depending on screen size, the list is often entirely out of view and editors do not realize they need to scroll down slightly to view the area
- As an editor, I want the Dashboard to be an intuitive experience so that I can quickly and easily complete my most common tasks 
 - The text on the Locations page tile is not exactly correct. "Manage the page introduction and select nearby locations." 
   - There is no intro displayed on the Veteran facing page and the only thing which can be managed on the Locations page is the addition of other Mobile Vet Centers which are not already associated. CAPs, which can be managed by editors, can only be viewed, not edited from this screen. [See Cape Cod for an example.](https://prod.cms.va.gov/node/28091/edit)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by mmiddaugh** [comment]
Closing as duplicate to #4643
