### ISSUE TITLE
Do not allow empty media references

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7274]
## User Story or Problem Statement

As an editor of a page with content blocks, i shouldn't be able to add empty media references. 

Related FE ticket to be more defensive: [forthcoming]

<details><summary>FE when form is not filled out</summary>

<img width="1580" alt="Cursor_and_West_Los_Angeles_Healthcare_Center___VA_Greater_Los_Angeles_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/145836911-667ee70b-3ff3-4490-9f56-a03093c77330.png">

</details>

<details><summary>Form showing field that should be required</summary>

<img width="844" alt="Edit_VAMC_Detail_Page_West_Los_Angeles_Healthcare_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145837209-c4aafada-f4ee-41be-a192-19f12ea70270.png">

</details>

## Acceptance Criteria
- [ ] Media field is required on content blocks

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by msbtterswrth** [comment]
Updated in: Embedded Image, Link Teaser with Image
Not updated in: Step, CLP (need to adjust validation when panel is not enabled first), publication, story, vamc facility, vet center, vet center cap, mobile vet center, vet center outstation
