### ISSUE TITLE
Minor improvements to phone number widget

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7276]
## User Story or Problem Statement

This could potentially be split into two tickets, one tiny config change, the other some form theming

Moving the help text above the field input caused two problems on the phone number widget:

1. Some help text was left below the field, in the text counter
2. the extension field has no help text so it now looks out of whack

<details><summary>Screenshot</summary>

<img width="984" alt="Cursor_and_Edit_VAMC_Facility_Non-clinical_Service_Billing_and_insurance_-_Cheyenne_VA_Medical_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/145842223-87c690a0-96c5-4222-b3ba-133bdff7f343.png">

</details>

## Acceptance Criteria
- [ ] Extension field is no longer inline, or otherwise improved to not look strange
- [ ] Help text is moved out of the textcounter field 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by netboss** [comment]
@kevwalsh 
Which content type (or entity) is this? It's not mentioned anywhere and the screen shot isn't clear where this belong.

**Comment by kevwalsh** [comment]
It's in a few places, including the service location paragraph type, which you can see in action on [VAMC facility health service](https://prod.cms.va.gov/node/add/health_care_local_health_service) forms. It's also there as a stand-alone field. 

if you can't find a field, the Drupal Spec tool is probably your friend.

**Comment by netboss** [comment]
> It's in a few places, including the service location paragraph type, which you can see in action on [VAMC facility health service](https://prod.cms.va.gov/node/add/health_care_local_health_service) forms. It's also there as a stand-alone field.
> 
> if you can't find a field, the Drupal Spec tool is probably your friend.

@kevwalsh 
Got it. I checked originally but wasn't sure which phone field (in which content type, entity) to change.

Could this be an accepted workaround (see screen shot)?
![VACMS-7276-phone-paragraph](https://user-images.githubusercontent.com/846871/153088954-8dfc616e-60dc-4955-af1c-946132374dee.png)

**Comment by netboss** [comment]
@kevwalsh 
Also, when moving the "Label" field help text to the field help text area the `@remaining_count` variable doesn't work. See screen shot.
![VACMS-7276-phone-paragraph-label-field-help-text](https://user-images.githubusercontent.com/846871/153089874-61ffc685-1b18-47b9-942d-451ec9940c47.png)

**Comment by kevwalsh** [comment]
So the workaround for "Extension number" is just to add help text? 

I think that works, but _please_ get rid of the "Please". I think we could use a UX writing 🤨 for this more generally. 

For the Label field. We should be treating the help text separately from the Character counter. 
* The help text `Use a label to indicate what office, department, or program can be reached here.`. above the field, in the field description.
* the `@remaining_count characters remaining.` should stay in the form widget setting. 
We're already doing this in a number of other places.

**Comment by netboss** [comment]
> So the workaround for "Extension number" is just to add help text?
> 
> I think that works, but _please_ get rid of the "Please". I think we could use a UX writing raised_eyebrow for this more generally.
> 
> For the Label field. We should be treating the help text separately from the Character counter.
> 
> * The help text `Use a label to indicate what office, department, or program can be reached here.`. above the field, in the field description.
> * the `@remaining_count characters remaining.` should stay in the form widget setting.
>   We're already doing this in a number of other places.

@kevwalsh 
Perfect. Thanks!

**Comment by netboss** [comment]
@kevwalsh 
Here is an updated version:
![VACMS-7276-phone-paragraph-v2](https://user-images.githubusercontent.com/846871/153251057-46a35616-a20a-4a12-9240-b9dd3924909f.png)

**Comment by netboss** [comment]
@kevwalsh 
I'll need to know how to proceed. 

I think a quick fix will be to move forward with the last changes above (updated screen shot) for now and then (in a different ticket?) work a more robust solution based on the options suggested in the Slack thread.

For reference purpose, adding the Slack discussion here: https://dsva.slack.com/archives/CDKB88PS8/p1644424970394409
