### ISSUE TITLE
Improve node view and paths for nonclinical health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7277]
## Acceptance Criteria

- [x] For nonclincial health service, paths set to /[facility-path/[term-name]
  - [ ] https://prod.cms.va.gov/node/41888 
  - [ ] https://prod.cms.va.gov/node/41889
  - [ ] https://prod.cms.va.gov/node/41990 becomes /cheyenne-health-care/cheyenne-va-medical-center/medical-records
- [x] Editorial workflow widget is hidden on non-clinical health service

## Implementation steps
- [x] Remove workflow widget from node view
- [x] Set up Path auto. 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by JayDarnell** [comment]
Using the following pathauto pattern: [node:field_facility_location:entity:url:path]/[node:field_service_name_and_descripti:entity:name]

The url for node/41990 above actually becomes:  /cheyenne-health-care/locations/loveland-va-clinic/medical-records

I believe this is what was asked for from a technical perspective above but the path is not what @kevwalsh initially listed. Checking the path for the referenced facility this appears to be correct.

**Comment by kevwalsh** [comment]
Good catch, thanks Jay.
