### ISSUE TITLE
Front-end architecture - Launch content API in lower env

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7278]
## Problem Statement

Currently, the technical architecture that supports CMS content being pushed to VA.gov causes a publishing delay. When a CMS editor saves content as published, there is a ~1 hour wait before it goes live on VA.gov. The CMS team is currently exploring how to rearchitect the deployment process to reduce or eliminate delays; exposing the API to the public has been proposed as a solution. This initiative will house the exploration for how the FE architecture will be structured, moving towards using React components pulling data directly from the CMS to render pages.

### Hypothesis

We believe a publicly accessible content API will reduce publishing delays, providing CMS editors a desired publishing experience, as well as a quicker developer experience for front-end engineers.

### Goals

- [ ] Product-based content API is accessible by VFS teams in lower environment
- [ ] Ensure 9 content types are available on API
- [ ] Enable real-time resource search
- [ ] Enable real-time deployment of full-width/facilities banners

### Affected users and stakeholders

* CMS editors
* CMS engineers
