### ISSUE TITLE
Make timezone data more rigid

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7285]
## User Story or Problem Statement

As a a content API user I would like there to be consistency in the data provided by the smartdate field in regards to timezone so that I know how to handle the times I am getting from the API.

Currently, if the timezone field is left on the default entry, no data is provided for the timezone property
![image](https://user-images.githubusercontent.com/5752113/146049253-07cc2b44-cf76-4135-9a31-ead5c2f21d07.png)
So even though the default is NY, the timezone is empty.

Upon a follow-up save of the node, or specifically setting the timezone to NY, the timezone is provided.
![image](https://user-images.githubusercontent.com/5752113/146049413-47169c63-4720-46e8-935c-22c34f1a127b.png)

In either case the time provided is for NY, but the API consumer has no way to know that from the data.

Two possible approaches
  A)  A data resolver that sets "timezone" = "America/New_York"  whenever timezone is empty.  
  pro: This would account for all current instances in the db and would fix it across multiple content types.
  con: a GraphQL resolver would have no impact on the new JSON API so it might need its own treatment. 

B) JS that removes the "default entry" and forces the actual selection of NY.  This would fix any future uses.
pro  Makes sure the data goes in right.
con  Would need a database update process that fixes any existing revisions that have no timezone set.
  

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by jilladams** [comment]
Related: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/2470

**Comment by jilladams** [comment]
Per 6/10 Events scrub with Dave: If still valid: need to fix it in Q3 2022. The screenshots here are old, so unclear if the Timezone handling is still this way with new date module. Need to: 

- [ ] repro
- [ ] verify current state
- [ ] Document
- [ ] Refine for points to fix current behavior

**Comment by swirtSJW** [comment]
I think this is still falls to Public Websites.  They own events AND this has both a CMS component and FE component.

**Comment by wesrowe** [comment]
@swirtSJW, can you please put this in context for me. Specifically, the description starts with "As a content API user", and I thought we have no content API. I figure I must be missing something...

**Comment by wesrowe** [comment]
I moved manually to new/unrefined in CMS workspace to reflect the move in PW workspace

**Comment by FranECross** [comment]
@jilladams @dsasser What do you think about changing the Timezone field so it doesn't default to New York, but instead has something like 'Choose timezone'? It seems like that would fix the issue, and also ensure the editor chooses the correct time zone, since it's a required field and if they don't make a choice, they won't be able to save their content. cc @thejordanwood

**Comment by dsasser** [comment]
> @jilladams @dsasser What do you think about changing the Timezone field so it doesn't default to New York, but instead has something like 'Choose timezone'? It seems like that would fix the issue, and also ensure the editor chooses the correct time zone, since it's a required field and if they don't make a choice, they won't be able to save their content. cc @thejordanwood

I think that is essentially what Swirt mentions in the second option in the ticket description:

> JS that removes the "default entry" and forces the actual selection of NY. This would fix any future uses.
> pro Makes sure the data goes in right.
> con Would need a database update process that fixes any existing revisions that have no timezone set.

So this would entail:

- Changing the timezone field to be required (via Javascript)
- Removing the 'default' option (via Javascript)
- Adding a ' - Select - ' option with a value of "" (an empty string, via Javascript)
- A database update script which changes the value of any event timezone from 'default' to NY

**Comment by FranECross** [comment]
Thanks, @dsasser ! I'd missed his 'B' option 😁I'm going to add the AC that you outline above and put this in the next refinement bucket for consideration sometime in January.
