### ISSUE TITLE
POCs for CMS hosting/re-platforming options

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7289]
## Background

In support of the Accelerated Publishing initiative, the CMS team will be restructuring the current hosting platform. Approaches/tools in consideration include the current BRD on Amazon Linux 2, WayPoint, and Lagoon.

### User Story or Problem Statement

As a CMS engineer, I want to explore the feasibility of various hosting tools so that we can evaluate adopting the solution for running and deploying the Drupal CMS.

### Affected users and stakeholders

* CMS engineers

## Acceptance Criteria
- [x] Conduct POCs for 2-3 tool options
- [x] Evaluate the tools against the decision criteria with some info about why the scores were set
- [x] Document findings in each POC ticket
- [x] Determine selected approach and document next steps for implementation in followup ticket(s)

## Implementation

https://docs.google.com/spreadsheets/d/1thN-Hs_k5R3WDVoXZEqb6OIJ3RDJzjlT4Krw2dxYZPE/edit#gid=0 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
