### ISSUE TITLE
Prevent PDFs from being added to link fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7293]
## User Story or Problem Statement

As a CMS editor, I want helpful guardrails that prevent me from adding links to inaccessible or difficult to use content. 

## Acceptance Criteria
- [ ] Editors are prevented from adding PDF links to link fields 
- [ ] Helpful guidance that explains the why is provided

## Implementation steps
Form validation, UX writing for error message.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by EWashb** [comment]
Need to convert this issue to a spike per findings in #8536

**Comment by EWashb** [comment]
- Heavy CM questions
- Editors are adding PDF-type things in other formats as well
- Whatever the change is decided, we need to be mindful of the governance
