### ISSUE TITLE
Structure centralized content to support Cerner medical records action links

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7322]
## User Story or Problem Statement

As a Veteran at a Cerner-supported VAMC, i want the medical records link to take me to the right system.

As a national editor of centralized content, i want to be able to edit the Cerner link and have it update all VAMCs that use Cerner, from one place.

As a local editor, i want to understand the centralized content and how it may show up on the FE, depending on my VAMC's Cerner status. 

<details><summary>Mural showing various experiences</summary>

[See mural here](https://app.mural.co/t/vagov6717/m/vagov6717/1639530168395/b114bb336a1db8c0a571272b10a230e1360d2775?sender=kevinwalsh8610)

<img width="1596" alt="Cursor_and_Medical_records_CTA_for_Cerner_VAMCs_•_VFS-CMS" src="https://user-images.githubusercontent.com/643678/146494750-766a2b27-0af6-45ea-9b0f-ced5a5fe7065.png">

</details>

## Acceptance Criteria
On Centralized content node
- [x] Update centralized content: one field for Cerner, one field for non-Cerner

On VAMC Medical Records page content type
- [x] Create EFF field to pull in the Cerner CTA right below the react widget
- [x] Update field labels (react widget OR cerner CTA, depending on the system)

Also
- [x] Address incorrect placement of the "Medical records office locations", which should come _before_ "Get your records by mail or fax".

<details><summary>Screenshot</summary>

<img width="1061" alt="Create_VAMC_System_Medical_Records_Office___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/159840797-5b0c00c0-567e-4e5f-92d4-325502856a04.png">

</details>

## Implementation steps

Field and form config on Medical Records Office content type

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
This is on hold until we can refine #7158 further.

**Comment by kevwalsh** [comment]
@ethanteague i couldn't figure out how to spec this ticket so i went ahead and did the config in [this tugboat environment](https://main-eyjs0sncpqkjhpxgnkuhzayuve040hg6.demo.cms.va.gov/admin/config/development/configuration)

Could use your support getting the config out of there into a PR and behat tests updated. 

<details><summary>Screenshot</summary>

<img width="1349" alt="Synchronize___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/159841084-dc0951f0-9390-4ac6-9e15-76ac5ae3efa5.png">


</details>
