### ISSUE TITLE
Update VAMC Medical records graphql and template to support Cerner action links 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7323]
[I think this is on hold until a Cerner convo on Feb 3]

## User Story or Problem Statement

See #7322 for some background, user stories, and content design. 

## Acceptance Criteria
- [ ] The new Medical Records pages respect the value of `field_vamc_ehr_system` to determine whether to show a Cerner action link or the normal react widget 
- [ ] www.va.gov/spokane-health-care shows Cerner CTA
- [ ] All others show the react widget

## Implementation steps
Use `field_vamc_ehr_system` field (on the VAMC system page available via `field_office`). If TRUE show Cerner CTA, otherwise show the react widget. 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by kevwalsh** [comment]
I believe this was all performed via #9196
