### ISSUE TITLE
Sprint 48 priorities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7324]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

1. If you want to see this on your board, assign yourself to this issue. (It's also pinned In progress)
2. Q4 priorities review
2. Last full sprint before holidays.
3. Some Q4 epic planning 
4. Various tech debt issues, will  
5. Trying to organize into workstreams

</details>

----

<details><summary>Product support</summary>

## #1605 Other event related work (stretch)

- [ ] #2460 💧 

### Detail page reporting 

- [x] #7154 

#### FE dev 

Aman and Ryan

- [ ] #7041 🎉 
- [ ] #7042 🎉
- [ ] #7043  🎉
- [ ] #7133 
- [ ] #7134 
- [ ] https://github.com/department-of-veterans-affairs/va.gov-team/issues/21561 (possible)

#### #6872 Editorial experience for top tasks and service locations

- [ ] #6874 💧 (Jay)
- [ ] #7166 and - #7167 💧Defect
- [ ] #6872 (Erica picking up where Suzanne left off)
- [ ] #7321
- [ ] #727

### VAMC upgrade team support - VAMC system renaming

- [ ] #7163
- [ ] #6920 💧 (Ivan)

### #4799 VAMC Care we provide 

- [ ] Other issues to flow from #6768 
- [ ] running the script created in #6456 
- [ ] Prepare (send?) message for sending

## Vet Centers

#7309 

### #6332 Required Vet Center Services

Followups to #6640 
- [ ] #7144 💧
- [ ] #7145 💧
- [ ] #7146 💧

### #6736 Vet Center dashboard 

Refine Epic based on usability study findings.

</details>

<details><summary>Content Ops</summary>

## Tech debt and defects
- [ ] #7162💧
- [ ] #7092 💧
- [ ] Rewrite automated tests to be less dependent on names of sections and nodes

## Accessibility tools

- [ ] #6980 💧

## #6170 Improve meta tags across all content types 

- [ ] #6935 💧

## Content blocks

</details>

<details><summary>CMS experience</summary>

## #1352  VAgovClaro theme MVP

See runbook in #1352 

### #7022 Port code from vagovadmin to vagovclaro (mostly Tanner)
- [ ] Create MVP feature branch for development
- [ ] #6887 💧 (Tanner, may need some input from Ethan, Kevin, Steve, others)
  - [ ] Individual stories.

### Group 

</details>

----

<details><summary>Needs refinement</summary>

## Content Ops
- [ ] Notifications user stories 

## Facilities
- [ ] #4856 (needs user stories first) 💧

Customer service
- [ ] #6558 📟  💧

</details>
