### ISSUE TITLE
Generate a report of what facilities do not have services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7325]
## User Story or Problem Statement

As a Facility product team member, i want to monitor the quality of facility content. 

## Implementation steps
Drupal view config to expose service count column. 

From [July 2023 slack discussion](https://dsva.slack.com/archives/C02730UEZPS/p1690289918303779?thread_ts=1690228108.808289&cid=C02730UEZPS) we _could_ add service count column to the main Content audit view, e.g.  https://prod.cms.va.gov/admin/content/audit?title_op=contains&title=&type_op=in&type%5B%5D=health_care_local_facility&moderation_state_op=in&moderation_state%5B%5D=editorial-archived&section=All

## Acceptance Criteria
- [x] Update [this report](https://prod.cms.va.gov/admin/content/facilities) to contain:
  - [x] A services count column
     - [x] vet center
     - [x] vamc
     - [ ] VBA
  - [ ] Rewrite these two columns to coalesce the data into one column 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/3fab8c69-6257-4bf2-8d46-f4df526cd2d8)
- [x] Add CSV export that matches the fields and filters.  This may be the only solution for having the count column be sortable.

Note:  The challenge is going to be on the service counts since the counts will be of reverse entity references AND will be to different content types.   Doing it as a single column is going to make it such that the column can not be sorted or filtered.... which is not ideal either.

**Comment by jilladams** [comment]
Tagging @stefaniefgray for awareness of follow ups here re: a view for Facilities with no Services, per https://dsva.slack.com/archives/C02730UEZPS/p1690232280928109?thread_ts=1690228108.808289&cid=C02730UEZPS

**Comment by swirtSJW** [comment]
I updated the ACs to match what we need and to better reflect the current state.   This is likely not a light lift even though it seems like it should be.

**Comment by swirtSJW** [comment]
@jilladams The problem is, not all things in a View are filterable and sortable.  You can often only filter and sort by things usually that are on the node that shows up in the View.  In this case the count is a count of other nodes that are not in any way referenced by the facility node.  The connection goes the other way.  Services connect to facilities.

There may be some possibilities but it would take some digging.

If we by chance we could get sorting to work, we would not be able to aggregate the columns and would need to have three separate columns (VAMC services, VC Services, and VBA services)  

However, not having sortability or filterability is not a show-stopper because we can filter by types.

**Comment by jilladams** [comment]
Discussion in product sync with DaveP, Dotti, Michelle: 
* Single column that isn't sortable / filterable = not useful.
* Separate columns = better, if they can be sorted/ filtered. Not clear if we need VAMC, VBA, VC. Definitely VAMC. Maybe VC. 
  * @mmiddaugh  to review the Slack thread and notes here for further input on priority.

**Comment by jilladams** [comment]
Cross-posting: a simlar need was logged from 7/10 lighthouse sync: https://trello.com/c/1Zr5UVzu/21-facilities-add-a-view-of-the-facilities-with-a-services-count. Not sure why, and if this ticket is about the actual same topic, or if that LH card is something different / for a different purpose. Do we need to document the LH use case for the Service count, and account for it in the work on this ticket?

**Comment by swirtSJW** [comment]
This should/would cover both needs for HelpDesk and Lighthouse.

**Comment by swirtSJW** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/7325?planning-poker) with Zenhub @omahane

**Comment by swirtSJW** [comment]
Understood that a single column that is sortable and filterable is ideal.  However, we may have to be content with either

1. Separate columns for VBA counts, VAMC counts, Vet Center Counts that are sortable
2. CSV export that can be put in a spreadsheet which would allow sorting

**Comment by jilladams** [comment]
@jilladams double check if this view exists. We think so, and think this can be closed.

**Comment by jilladams** [comment]
cc @omahane 
What we have already built is an audit view of VA Services, with a total count, that can be filtered by content type (VAMC, Vet Center health services): https://prod.cms.va.gov/va-services

That satisfies understanding The service, where it's used, and how many times. 
It does _not_ satisfy understanding which Facilities do not have associated services. Leaving this open.

**Comment by davidmpickett** [comment]
@omahane I have approved your PR. It passes QA and is doing what it says it is doing. 

@jilladams Want to note that the PR does not meet all the ACs listed here. I think we should amend this ticket to just cover the work the PR does.
- Propose moving `add a VBA services count column` to a new ticket that can be considered for National phase
  - Not enough VBA facilities with services now to be a useful column
  - Easy to add later
- Propose striking `rewrite these two columns to coalesce the data into one column`
  - This is a "nice to have" rebasing of the report that is not vital to it's functionality. 
  - It also could easily balloon the size of this ticket because of the potential complexity of combining queries

**Comment by omahane** [comment]
I did try to do that. Because they are not the values but counts of different fields (VAMC and Vet Center services), it got a little weird. I thought I could use conditional field, but there's only one test, and when we add VBA, we'd need to find some other solution, perhaps like a custom field. But given the value to Veterans and who uses this, I would not recommend this kind of dev work for an admin facing report.

**Comment by davidmpickett** [comment]
@omahane I stubbed a new ticket for updating the report with VBA and coalesce  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/18002

Verified the report is operating as intended on Prod
![Screenshot 2024-04-30 at 11 17 33 AM](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/c46b4b5a-a4dc-43cf-b092-9f229fbaa42e)
