### ISSUE TITLE
Write migration to create ~420 non-clinical facility service nodes 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7335]
## User Story or Problem Statement

As part of our change management approach to top tasks, and the scripts to unpublish old top task pages once a new one is created, we realized we need to generate non-clinical facility service nodes first, either by migration or by hand. 

## Acceptance Criteria
- [ ] Nonclinical facility service nodes are created for 3 top task pages. 

## Implementation steps
TBD

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
@kevwalsh  based on what Dave said in sprint planning today, we are going to have editors add these.

We could create empty ones, 1 per system but I am not sure it gains them much, and does not teach them how to add others.

**Comment by swirtSJW** [comment]
Electing to close this since we are going to be having editors do this.
