### ISSUE TITLE
Health service location when "use facility street address" box is checked

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#7339]
## Issue Description
Currently, on Erie health care, the Optometry service accordion displays the Facility street address, although the "use facility street address" box is checked. 
<details>
<summary> screenshots </summary>

![image](https://user-images.githubusercontent.com/55411834/111232489-d2110080-85b0-11eb-874c-0902350a550a.png)

![image](https://user-images.githubusercontent.com/55411834/111324937-d7159480-8630-11eb-91de-682161cf09ca.png)

</details>

The "use facility street address" box is intended to support for backend API details, not for use on the front end. 
Use case: If a service is providing a special offsite vaccination clinic or service at an alternate location, they will leave the box unchecked and specify the address which **will be** displayed on the front end. 

---
## Tasks
Correct logic for the "use facility street address" checkbox according to the following:
- if  "use facility street address" box is checked, do not show the street address on the front end - show only wing/floor/room info
- if "use facility street address" box is not checked, the user will be prompted to enter a street address, which **should be** displayed on the front end
-  [ ] Add unit test for this scenario

## Acceptance Criteria
- [ ] If the "use facility street address" box is checked in CMS for a VAMC health service, the street address does not appear on the front end. Only the wing/floor/room info is displayed within the accordion. 
- [ ] If the "use facility street address" box is **not** checked, the front end will display the alternative location specified by the content editor. 

---
## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [ ] **Attached to an Epic** (what body of work is this a part of?)
- [ ] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `service-design`, `tools-be`, `tools-fe`)
- [ ] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [ ] **Labeled with Type** (`bug`, `request`, `discovery`, `documentation`, etc.)
