### ISSUE TITLE
Make URLs in broken links clickable

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7344]
## User Story or Problem Statement

As a Tier 1 or 2, i want to diagnose and address broken links as soon as possible. 

Currently, we need to copy/paste the URLs into www.va.gov and/or prod.cms.va.gov to diagnose.

<img width="596" alt="Cursor_and_Slack___vfs-platform-builds___Digital_Service___VA___3_new_items" src="https://user-images.githubusercontent.com/643678/146825056-f40e31dd-50cc-4150-bae3-12b11741d837.png">

## Acceptance Criteria
- [ ] Broken link reports in slack have clickable URLs. 

## Implementation steps

Design TBD

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by timcosgrove** [comment]
This was taken care of by #8927
