### ISSUE TITLE
Implement new triage/notification process

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7366]
### User Story or Problem Statement

As a CMS team member, I want to establish a new triage process so that I can be confident that any given critical defects are handled appropriately.

## Acceptance Criteria

- [ ] Document current state, pain points
- [ ] Determine key teams/stakeholders and responsibilities
- [ ] Categorize types of issues encountered
- [ ] Assign modes of notification for types of critical defects (PagerDuty, Slack, etc.)
- [ ] Establish agreed upon response times
- [ ] Document new triage process in Confluence

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by ElijahLynn** [comment]
We should reference a previous triage document that was created by our helpdesk team.

**Comment by indytechcook** [comment]
Here is what we current use for alert levels and how each alert level should notify https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/cms-alerts.md

**Comment by mchelen-gov** [comment]
Here are the previous service desk triage and incident response docs:
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/incident-response.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/broken-link-process.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/cms/helpdesk/helpdesk_workflow_processes_procedures.md

Any revised triage process should update or deprecate these docs.
