### ISSUE TITLE
Vet Center CAP should require time or comment if overriding VC time

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7379]
## User Story or Problem Statement

As a Vet Center CAP editor I should not be able to select "Provide CAP hours online"
![image](https://user-images.githubusercontent.com/5752113/147148682-8b5a50e1-5468-4c0c-924e-81f7e910cf2e.png)

without being forced to enter either hours or a comment for each day.   No days of the week should have nothing.

For now, the FE is going to assume empty means closed, but we want to be explicit about it.

## Acceptance Criteria
- [ ] When editing or adding a vet center cap, and I select "Provide CAP hours online" i must enter hours or comment for each day in order to save.
- [ ] If I fail to provide hours or comment for the day, I should receive a meaningful error that tells me how to make it right.
- [ ] Testable_Outcome_Z

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
