### ISSUE TITLE
Limit menu depth to 5 on VAMC product

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7380]
## User Story or Problem Statement

As a an editor of a VAMC related page, I should not be able to add items to the menu beyond level 5 so that 
  A) I am forced to reconsider my content structure
  B) so my menu is not long and unwieldy

## Acceptance Criteria
- [ ] Editors can not add items beyond level 5 on a VAMC menu

## Implementation steps
This logic should live in our VAMC menu service to restrict it by eliminating available options, not by post save validation.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by davidmpickett** [comment]
**Yes it is still the case**
- As a VAMC editor, I can nest VAMC detail pages more than 5 items deep in a menu in Drupal.
<img width="336" height="479" alt="Image" src="https://github.com/user-attachments/assets/af07ab1f-10fb-4b07-aa31-e1aaf3b3dff7" />

- The FE sidebar will not show this page in the menu at all, it stops at L5

<img width="282" height="441" alt="Image" src="https://github.com/user-attachments/assets/87c63dc2-291c-4985-bf05-11d1ce33cd0f" />

- Breadcrumbs on the page will indicate it is a child of the L5 page
- The page can be published, even if it's deep deep in the menu

<img width="1071" height="797" alt="Image" src="https://github.com/user-attachments/assets/22c29dec-4a60-420f-8ea5-1f3cd155508c" />

**But it's probably fine**
- It does not seem like this is a common editor behavior that we need an automated railing to prevent
- The FE has a graceful solution to this behavior
