### ISSUE TITLE
Prevent url alias updates for VAMC System nodes

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#7388]
## User Story or Problem Statement

Recent work to rename the VAMC Systems for Lovell and North Florida (but not update their URLs) has shined a light on a potential risk with updating URL aliases for VAMC System nodes. We should put safeguards in place to prevent us from changing VAMC System url aliases.

## Acceptance Criteria

- [ ] Editors are no longer able to select the checkbox to update URL aliases for VAMC System nodes
- [ ] Attempts to update URL aliases for VAMC System nodes via views bulk operations should fail gracefully (a status message should be displayed notifying editors that the alias change was not allowed)

## Implementation Steps

1. Disable the URL alias fields on node edit for VAMC System nodes
2. Create an event listener for alias entity update (save) to disallow if the alias belongs to a VAMC System node 
3. Output a status message stating that changes to URL aliases for VAMC System nodes are not allowed

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by Agile6MSkinner** [comment]
This hasn't been since this ticket was created years ago. We will revisit if it comes up again.
