### ISSUE TITLE
Interview VISN 19 editor for text feedback

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#7391]
## User Story or Problem Statement
VISN 19 has agreed to have their top task pages serve as tests for 3 hardened pages. 

We have an opportunity to hear feedback from a VISN 19 editor on their test content in prod to ensure that we are providing the appropriate instruction for their editorial workflow respective to nonclinical facility services.

## Acceptance Criteria

- [x] VAMC Editor understands the concept for the newly implemented card design for non-clinical services.
- [x] Designers iterate on UX writing from the interview process. 

## Implementation steps
- [x] Create interview plan 
- [x] Schedule interview with editor
- [x] Conduct interview and document feedback on help text and other UX writing design decisions
- [x] Iterate on design as needed from editor feedback

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by EWashb** [comment]
Interview is scheduled for Jan. 27

**Comment by EWashb** [comment]
Interview completed Jan. 22, 2022
