### ISSUE TITLE
va_form display of field_va_form_revision_date should show Month YYYY

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7392]
## Description

[Related discussion](https://dsva.slack.com/archives/CUB5X5MGF/p1640290787104900?thread_ts=1640271628.103400&cid=CUB5X5MGF) 
The data from FormsDB only includes month and year for the  revision_date. Drupal doesn't allow dates without a day so populates a "day" as today's date. 

We need to match the display to the valid data we have and follow guidance from https://design.va.gov/content-style-guide/dates-and-numbers

"March 2021"

~~The backend is delivering timestamps to the FE.~~ edit: turns out this is not true. The data supplied to the frontend is in the format YYYY-MM-DD.

We will need to validate how the display change impacts the content-build.  Display of date info may not carry directly in the FE.   If it does not carry into the FE, we will need tickets for both 
- altering the FE (content-build)
- altering the handling that the front-end will handle

## Tasks
- [ ] format the display of VA Forms date to use Month year (e.g. March 2022) - 1hr
- [ ] Validate FE isn't broken - 1hr?
- [ ] PR - 1hr

## Acceptance Criteria
- [ ] CMS display of field_va_form_revision_date shows "Month YYYY" in node view on VA Form content type.  
- [ ] If needed  A FE issue is created.
- [ ] if needed the VA Form team is notified to make the change on their end.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [X] `⭐️ Public Websites`
  - [ ] `⭐️ User support`

**Comment by dsasser** [comment]
## Findings regarding FE and Lighthouse:
Changing the display format of the revision field in Drupal UI has no bearing on the GraphQL output. Therefore FE will in fact need a ticket for updating the format of the date there.

**Comment by jilladams** [comment]
^ Front-end ticket filed. @dsasser feel free to update that with any info FE folks may find useful.
