### ISSUE TITLE
CMS default content release chooser

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7405]
## User Story or Problem Statement

As a CMS engineer I should be able to toggle prod to use GHA or Jenkins as the default for content releases triggered by the CMS so that:
1) we can set it to the one that is reliably working when one is broken, so important and timely content is available to veterans.
2) I can get back to work and not have to babysit content releases all day long.
3) we don't require a cms code release to make the switch.

## Acceptance Criteria
- [ ] An admin can set a feature_flag or other UI setting that is not tracked in config export to choose GHA or Jenkins for our content-release trigger.
- [ ] The choice made persists on prod until someone intentionally changes it back.

## Implementation steps
A feature_flag might be a good choice here Not an ideal location in the UI, but manageable.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by swirtSJW** [comment]
Followup discussion  https://dsva.slack.com/archives/CT4GZBM8F/p1643928211159539

**Comment by TheBoatyMcBoatFace** [comment]
Closing because we no longer run Content Build on Jenkins.
