### ISSUE TITLE
[Design] first Site Alert improvement

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7436]
### User Story or Problem Statement
"As a user I need to know about critical situations that will affect the CMS application so that I understand what's happening with the system."

**Examples of critical situations:**

**System updates (aka CMS deployments)**
- When: every day at 3:30 ET for approx 15 minutes
- Impact: users can't use the cms while deployment is in progress
- Site alert behavior: alerts appear before, during, and after deployment

**Publishing delays**
- When: rare situations with significant publishing delays
- Impact: There will be a significant delay in content going live on VA.gov
- Site alert behavior/content: 

**Problems with single sign on**
- When: rare situations
- Impact: users can't use PIV to log in
- Site alert behavior/content: Directs users to either: wait for ssoi to be fixed, or use a backup login method (probably not likely, Dave wants to avoid doing that)

**Warnings for lower environments like training**

### Background

Site alerts present certain UX challenges

- User control
   - Before/after alerts aren't dismissible, so cause annoyance/fatigue
- Content design
   - Font is all bolded
   - Lacks heading
   - Colors are not aligned with Va.gov Claro theme
- Governance
   - User can't interact with save button when there's multiple site alerts on the screen (See #2289)
   - Probably should have a character limit
- Position
   - Goes against established patterns elsewhere (most other sites put site-wide alerts at the top)

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/643678/147883328-68e180be-6cd8-409f-926e-79ba1575cb54.png)

</details>

### Affected users and stakeholders

All CMS users

### MVP scope
- Separate alerts for separate messages for now
- dissmissability (spin off - #8300)
- position
- headlines
- content style

### Things to consider
- Consider oppys to feed governance + ed ex guardrails back into how we handle constraints for front end alerts

### ACs
- [ ] Design recs
- [ ] Tech feasibility reviewed

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`

**Comment by indytechcook** [comment]
The HTML to generate the site alert are stored in two different places:
* Full HTML during deployment: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/docroot/sites/default/maintenance.html
* Text for post message: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/cms/cms-deploy-live.yml#L30
* text for pre-alert: https://github.com/department-of-veterans-affairs/devops/blob/793326c6d6a6075ecaee746a129203da6f0a2dfe/ansible/cms-test/cms-site-alert.yml#L35
* text for actually alert (included hard coded `string`: https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/cms-test/tasks/pre-deploy-tasks.yml#L19
