### ISSUE TITLE
Keep a log of deleted entities

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7468]
## User Story or Problem Statement

We keep revision history, until nodes are deleted.  Then it can be very difficult to figure out who and when a node is deleted. 

Only content admins can delete content. 

## Acceptance Criteria
- [ ] We have a record of deleted nodes, taxonomy terms, files, users, (nodes are most critical, others are nice to have)

## Implementation steps

Possibly
* install and configure [the d8 port](https://github.com/malaynayak/entity_delete_log_d8) of [Entity Delete Log
](https://www.drupal.org/project/entity_delete_log)
* Evaluate the code for finishing the d8 port

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
