### ISSUE TITLE
CMS Monitoring and Alerting

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7471]
## Background

Our CMS integrates with multiple external systems. The operation and behavior of these systems can negatively affect CMS functionality. Application performance monitoring was implemented in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5796; we will continue to improve visibility into code quality and system performance through further APM enhancements and additional levels of alerting as needed.

### User Story or Problem Statement

As a CMS Engineer, I need to utilize the increased visibility of system usage and performance provided by APM, in order to proactively monitor and improve the system's performance and maintain operation of the CMS system.

### Affected users and stakeholders

* CMS editors
* CMS engineers

### Hypothesis

We believe that documenting and monitoring external dependencies will allow CMS team to be more aware of and respond more effectively to issues that affect the functionality of the CMS. We'll know that to be true when more systems that affect CMS are monitored and the time to resolution is decreased.

## Goals

- [ ] Identify opportunities to proactively address any downtime and system issues 

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`

**Comment by cmaeng** [comment]
this epic will be closed in favor of quarterly timeboxed initiatives. all unfinished tickets have been moved to #11076
