### ISSUE TITLE
Labeling some paragraph types is confusing

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7489]
## User Story or Problem Statement

As a and editor of centralized content I do not want to be confused by the declaration of the centralized content documentor pargraph being labled as "Centralized content..." Which is actully the thing that is NOT centralized content.

![image](https://user-images.githubusercontent.com/5752113/148276398-22ae2aba-7d3e-4fa2-9105-14b542486439.png)

Visit /node/15588/edit  and look above each of the scope entries.

## Acceptance Criteria
- [ ] Paragraph descriptors for centralized content documentor paragraphs are not output.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
