### ISSUE TITLE
Audit tool for facility clinical and non-clinical health services

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7500]
## User Story or Problem Statement

As a product team member, i need to understand existing facility clinical and non-clincial health service data so that i can make design, content model, change management decisions. 

As a VHA digital team member, i can see which facilities provide which services, 

> I'm the Director in VHA Digital Media and in the Health Services taxonomy section I can see the  "Number of Uses" for a Health service. However, all I can see is a number. I cannot tell which locations list it. Is there a way to generate a report of which locations are using a service?  This would be very helpful for quality assurance and auditing purposes at the VHA CO level. For example, I can see that "Transplant Surgery" is used 15 times across all VAMCs. I want to verify known locations list it without visiting site after site after site. If this is not possible in current system, please add as change request to your backlog

Related [Slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1643904676122819)

## Acceptance Criteria

Common to all views

- [x] Fields common to all
  - [x] Standard set from /admin/content
  - [x] Service taxonomy term
  - [x] Ideally, a count of how many service locations
- [x] Filters
  - [x] Content type: VAMC facility health service, VAMC facility non-clinical service, Vet Center Service (one per display)
- [x] Exposed Filters
  - [x] Standard set of filters from /admin/content plus
  - [x] Service taxonomy term
  - [x] Facility
- [x] Permissions
  - [x] Authenticated user
  - [ ] One alternative (not ideal, but for the short term): remove all access permissoins, and easter egg this view URL (it's not sensitive data) to keep it out of the UI for users, and just provide a link to it from the /vha-health-services. 
- [x] Other features
  - [x] Standard Count of results in the header
  - [x] CSV export
- [ ] Once this in a Tugboat environment, send export of data to JHL (Kevin can do this)

New view "Facility services"

3 displays
- VAMC facility health services 
  - /admin/content/facilities/vamc-facility-health-services
  - Unique fields (Referral required, Are walkins accepted, Online scheduling) and filters for each.
  - Number of service locations
  - Filter by facility
- VAMC facility non-clinical services
  - /admin/content/facilities/vamc-facility-non-clinical-services
  - Number of service locations
  - Filter by facility
- Vet Center services
  - /admin/content/facilities/vet-center-services
  - Vet Center service description

## Implementation steps
Drupal views config

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected. If you're not sure, it's fine to leave both selected.

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
