### ISSUE TITLE
Visibility into content release times

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#7532]
## Description
As a CMS user, I want to know where to find things like what the expectations content release statusare so I don't have to send in a helpdesk ticket to ask. 

## Hypothesis
Content release status more visible and accessible through a KB article will reduce the number of tickets asking about these things. A possible status board/page has been discussed but a KB article may be the lightest lift.

https://dsva.slack.com/archives/CT4GZBM8F/p1641583259192200

Idea for a status page was suggested, and could include helpdesk SLA times.

## Acceptance Criteria
- [ ] A plan to make things like SLAs and content release status more visible is approved by the PO
- [ ] If a KB article is chosen as part of the path forward, a draft is run by CMS UX folks
  - [ ] KB article is published

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS Experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product Support`
  - [x] `⭐️ User Support`

**Comment by xiongjaneg** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7608 for current state

**Comment by rachel-kauff** [comment]
[The KB article](https://prod.cms.va.gov/help/cms-basics/when-will-my-content-be-published-live-on-vagov) is done, but I don't expect it to move the needle much on this problem, so I'd consider this user story largely unresolved.

**Other approaches:**
- Status page (suggested by Dave), which could help if it's surfaced in the correct place in the interface. (larger design + dev lift, medium impact). The right part of the interface might be: status messages on save, the knowledge base (eventually when it gets IA attention)
- Set expectations in several key locations in the interface (status messages on save, recent changes summaries). [See this MURAL for details](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1643911701043/ba5def8b2250de9d82181abd8240addccfdce0a9?sender=kevinwalsh8610).

**Comment by rachel-kauff** [comment]
Updated this issue to clarify that the actual problem is understanding content releases, not helpdesk SLA times. Dave suggested that the status page (a possible solution) could be a place to include SLA times.

**Comment by EWashb** [comment]
@stefaniefgray I think we might be ok to close this one. If you continue getting/start receiving inquiries on the help desk about releases, we can reopen it
