### ISSUE TITLE
Add governance measures for unique ID for Service taxonomy terms 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7557]
## User Story or Problem Statement

As a lighthouse engineer for the facility API I need a unique identifier for a service that is more meaningful but as immutable as a term id so that consumers of the API can use semi friendly request names for services instead of term ids.

## Acceptance Criteria
- [ ] ~A new field on health_care_service_taxonomy terms 'field_health_service_uid' (plain text) label: Facility health service UID'~
- [ ]  ~hook_update_N created (must be in separate PR that goes out after the field creation) that populates the field with camel case version of current term name.  (must be stripped of all non-alpha-num characters [no ' " ( ) + - .]~
- [x] #7671
- [x] Disable field_health_service_api_id for all users but admin on health_care_service_taxonomy  (use UserPerms service)
- [x] allow_only_one field is added to  health_care_service_taxonomy so that the `field_health_service_api_id` can never be used twice.
   - [x] Set form display of the allow_only_one field to appear just above  the  field_health_service_api_id field.
- [x] `field_health_service_api_id` is required.
- [ ] Change section for all service taxonomy terms to an OCTO > VA Service taxonomy

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I updated the AC's based on 1/19/22 call with Lighthouse.
