### ISSUE TITLE
Refactor facility health service push to lighthouse to include unique_id.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#7558]
## User Story or Problem Statement

As a lighthouse engineer, I need structured data related to facility health services that includes the [unique service identifier](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7557) 

We are already including this data 
docroot/modules/custom/va_gov_post_api/src/Service/PostFacilityService.php
![image](https://user-images.githubusercontent.com/5752113/152860382-e521d87c-5b2e-4431-a2df-1c238e7b19c0.png)

Blocked by: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7557

## Acceptance Criteria
- [ ] push to lighthouse via `serviceId`

## Implementation steps
The implementation this needs to be coordinated with lighthouse so we are sending what they need, in a way that works for them.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Lighthouse is already being sent this data as part of the current payload as
`health_service_api_id`   we should not need any additional work, unless they need us to change it to `serviceId`

**Comment by swirtSJW** [comment]
Checking with lightouse to see if rekeying is needed
```mermaid
graph TD
  A[health_service_api_id] --> B {re-key to serviceID}
  B -- Yes --> C [Re key it and move on]
  B -- No  --> C[Close this issue]  
  C[I don't get it]
```

**Comment by swirtSJW** [comment]
Closing this based on feedback here https://dsva.slack.com/archives/C02BTJTDFTN/p1644864434634289
we are OK to continue sending as `health_service_api_id`
