### ISSUE TITLE
Rotate Drupal API Credentials for Datadog Monitors

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#7561]
### Acceptance Criteria
- [x] Datadog synthetic tests are using dedicated Drupal API credentials 
- [x] Synthetic tests continue to work successfully

### Tasks:
- [x] Discover all monitors using Drupal credentials that authenticate requests.
- [x] Update monitors to use newly created credentials per related issue below.

### Relations:

https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6973

### Implementation Details:

Drupal user created for Datadog authenticated requests is **datadog_api**. Credentials are stored in DSVA AWS Parameter Store;
* /cms/prod/drupal_api_users/datadog_api/username
* /cms/prod/drupal_api_users/datadog_api/password

These may be the only Synthetic Monitors that send requests to the Drupal API:
* [CMS] Test /api/govdelivery_bulletins/queue?EndTime=1
* [CMS] Test /graphql

### CMS Team:

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jkalexander7** [comment]
@olivereri can Datadog monitors use AWS Parameter store?

**Comment by olivereri** [comment]
> @olivereri can Datadog monitors use AWS Parameter store?

I think it already does, but I don't know how. Need to figure out/ask about it.

**Comment by jkalexander7** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/7561?planning-poker) with ZenHub @amponce @cweagans @ElijahLynn @indytechcook @ndouglas @olivereri @timcosgrove

**Comment by ElijahLynn** [comment]
Per refinement, the most (all?) of our synthetics are in Terraform and pull from SSM, so it _should_ be just updating Terraform. That is my understanding.

**Comment by ndouglas** [comment]
See https://github.com/department-of-veterans-affairs/devops/blob/c304a27d2dbb3e205e27bbc098ad21e4fc256cc5/terraform/environments/datadog/cms.tf#L167 -- these should be re-pointed to the new values.  Then the SSM values should be removed since they don't match the new hotness 😃

**Comment by olivereri** [comment]
After applying the Terraform State the change in datadog is seamless:
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/6e80fd4e-413b-4a5c-87e8-46faf709f690)
