### ISSUE TITLE
Update help text to reflect Vet Centers radius change from 80 to 120 miles

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#7563]
## Description
Facilities team updated Nearby Vet Center area. Up to five nearby Vet Centers are automatically pulled from a 120-mile radius (used to be 80 miles).

## Acceptance Criteria
- [x] Removed exact mile radius from KB article
- [x] Removed mile radius from training video
- [x] Validate which radius is being used to generate the Vet Centers on the FE. (120 miles)
- [x] Update and publish UI help text in Vet Center - Locations List content type. Change "80" to "120" (see screenshot below)

## Implementation steps
- Update the text in `va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php`

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
![Screen Shot 2022-01-12 at 2.29.41 PM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/75663da1-3329-497a-a0b5-17a9e4afb104)

**Comment by xiongjaneg** [comment]
@kevwalsh I check KB and training for this change, so the only remaining change needed is the help text in the UI. Thanks!

**Comment by xiongjaneg** [comment]
would be nice to get in place before first week of March Vet Center District 2 kickoffs

**Comment by xiongjaneg** [comment]
[mobile vet center KB article is updated to 120 miles](https://prod.cms.va.gov/help/vet-centers/how-to-add-a-nearby-mobile-vet-center)

**Comment by davidmpickett** [comment]
Confirm if 80 or 120 is current radius and if this was changed or not

**Comment by xiongjaneg** [comment]
This is still currently in the UI as 80 miles. There is a pending change where this may be expanded to 200 miles if there are no results within 120 miles, so this should wait until that is done.
<img width="916" alt="Screenshot 2023-08-18 at 3 41 54 PM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/2b711e83-d690-4565-a92d-b0b9bd32eada">

**Comment by xiongjaneg** [comment]
This remains at 120 miles

**Comment by xiongjaneg** [comment]
Verified that it is still inaccurate in the Vet Center - Locations List content type. However, it is not in the Structure>fieldhelptext for [vet_center_locations_list](https://prod.cms.va.gov/admin/structure/fieldhelptext/by-bundle/node/vet_center_locations_list)

**Comment by davidmpickett** [comment]
Very strange, but I can't seem to find a corresponding "nearby-vc-information" field when I look at the configuration of Vet Center Location List
![missing_bit](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/51967950/52d1aefc-e8ab-4c8e-934f-35477f134b25)

**Comment by mmiddaugh** [comment]
<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3Q1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--85b667ce783632260a554261b65e48c8311cf1f4/image.png" alt="image.png" />


Visible [here](https://prod.cms.va.gov/node/27778/edit?destination=/section/vha/vet-centers/salem-vet-center)

**Comment by omahane** [comment]
I added an implementation step in the description, referring to `va_gov_vet_center/src/EventSubscriber/EntityEventSubscriber.php`

**Comment by omahane** [comment]
Honestly, if we were to do this today, I would do this text as a markup field or centralized content.

**Comment by swirtSJW** [comment]
> Honestly, if we were to do this today, I would add this text as a markup field.

Can't be done that way because the link needs a token 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/94ea9341-1f60-425e-94ab-21f03a9e92c5)

**Comment by swirtSJW** [comment]
Code was merged and will go out tomorrow.

**Comment by xiongjaneg** [comment]
Verified on prod, thank you!
<img width="936" alt="Screenshot 2023-12-27 at 10 41 12 AM" src="https://github.com/department-of-veterans-affairs/va.gov-cms/assets/73648238/7d68d69d-366d-415d-849a-c2386b29025e">
