### ISSUE TITLE
Develop an actionable understanding of Offices-site visitors to "Pilot Offices"

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7587]
## Background

Early research will focus on 3-4 offices where Tier 3 content is a priority due to dependencies for migrating Tier 1 and 2 content. E.g., Community Care.

### User Story or Problem Statement

The Offices team needs to discover areas of legacy VAgov content where the desire to migrate Tier 1 and 2 content is being held back by uncertainty or poor UX around the remaining content that would be left behind.

### Affected users and stakeholders

No existing users affected

### Hypothesis

We believe that there are several offices with known Tier 1 & 2 content that held back from migrating due to concerns around Tier 3 content. We'll know we found them when we have obtained cooperation from 3-4 of them, evaluated their content, and captured a baseline of their visitor traffic.

## Acceptance Criteria
- [ ] 3-4 pilot offices identified
- [ ] Analytics baseline captured in GA
- [ ] Customer satisfaction monitoring in place
- [ ] Content inventory complete across all tiers for Pilot Offices

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [ ] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
