### ISSUE TITLE
Design an editorial process that respects FOM data source and scales as content grows

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7588]
## Background

The Salesforce database used to build the Functional Organizational Manual (FOM) PDF annually is the existing source of truth for the office and org structure of the VA. There is a lot of process built around keeping it current when offices merge, close, or move around.

### User Story or Problem Statement

The Offices team needs to formulate a technical and process strategy for publishing FOM data from Drupal with minimal disruption to editors or visitors when data changes in the FOM database. 

Assumptions:
 - The FOM editorial process built around Salesforce has sufficient value and stability that VA intends to keep it as the source of truth for org structure data.

### Affected users and stakeholders

No existing users affected, we're just planning right now.

### Hypothesis

If we build an integration from Drupal to Salesforce, then we can publish updated FOM data automatically in all or most cases.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [ ] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange)
- [x] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
