### ISSUE TITLE
Build proof-of-concept version of Office Directory page

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7590]
## Background
Design will be to wireframe, with little/no effort put into final design rendering.
This might not go live until further iteration.
Use FOM database to power.

### User Story or Problem Statement

AS A visitor
I WANT to see a working prototype of the Office Directory powered by the FOM database
SO THAT I feel comfortable that the polished product will be achievable.

### Affected users and stakeholders

none

## Acceptance Criteria
- [ ] Offices down to FOM level 4 are displayed on the screen hierarchically, similar to wireframes
- [ ] Search bar filters the list interactively
- [ ] Drupal data is updated automatically or ad-hoc from FOM database

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [ ] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
