### ISSUE TITLE
Change management milestone schedule

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#7591]
## Description
As part of Q1 2022 planning, CMS site-wide work stream teams are scheduling epics/tasks that may have a change management component. To understand the cumulative impact of these change management efforts and avoid saturating our ecosystem with concurrent changes, we need to create an artefact that:
- captures the change management milestones for each task
- based on a cross-team meeting, is reviewed and adjusted to improve our chances for change management success 

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review

### CMS Team

Please leave only the team that will do this work selected. 

- [] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [X] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
This was worked through previous sprints, can be seen at https://airtable.com/appJCOGGJRTAwcH2v/tblPHoElsBWwr83Z0/viwSfROR69D6seBkB?blocks=hide
