### ISSUE TITLE
Change management framework

### ISSUE THREAD

**Issue by ContentBrewmaster** [department-of-veterans-affairs/va.gov-cms#7593]
## Description
The teams working together to improve VA.gov and use a new CMS need a common basis for framing change management tasks.  There is no current documentation for change management processes and tactics that teams can reference. Teams would also benefit from learning about successful change management efforts since the project's inception.

## Acceptance Criteria
- [ ] Change management success metrics are developed and available to all teams for new work.
- [x] Previous successful change management strategies and tactics are available to all teams.
- [x] Change management processes and terminology are consistent across the Sitewide CMS teams by the end of Q1.
- [x] New change management strategies and plans are available to all teams.
- [x] Roles and responsibilities for change management are established and documented.

[Change management RACI](https://docs.google.com/spreadsheets/d/1BDmdiQcjKAijBGRrq0HsfRZP_bqDm1Ul/edit#gid=1182457863)
[VA.gov CMS change management initiatives](https://airtable.com/appJCOGGJRTAwcH2v/tblPHoElsBWwr83Z0/viwSfROR69D6seBkB?blocks=hide)

### CMS Team

Please leave only the team that will do this work selected. 

- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
@ContentBrewmaster i turned this into an epic and moving it to "Epics in progress". I've drafted three issues so far (#7796, #7798, #7797), but i'm sure there are other to do's we want to capture as individual issues.

**Comment by EWashb** [comment]
@ContentBrewmaster do you feel like this is ready to be closed? I think it probably is ready.

**Comment by EWashb** [comment]
framework has been implemented
