### ISSUE TITLE
Content releases run continually during business hours

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#7600]
## Description
We would like to change content release behavior so that a new content release will be triggered upon completion of a previous one, within business hours. Outside of business hours, content releases will happen as they currently do, either manually triggered from the CMS or else triggered via other CMS actions (i.e. saving an alert). 

### Justification
Currently content release is triggered by certain CMS actions, in addition to scheduled releases. The intention is that information in a facility alert for example is timely and should make it up to the site as soon possible, rather than waiting for the next scheduled content releases. 

If a manually triggered build is running, and another manually triggered build is fired off, the second build cancels the first. In other words, the first manual build is triggered and gets some of the way through; before the first build is finished, a second build is triggered, canceling the third. These cancellations can and do frequently follow one after the other.

If a *scheduled* build is triggered, it overrides any manually triggered build. The result of this is, very often a string of manually triggered builds will cancel each other until the next scheduled build. The manually triggered builds rarely complete, at least inside business hours.

Continually releasing would at least get content up to the site as quickly as possible. This comes at the expense of predictability. However, predictability is already suffering. 

## Acceptance Criteria
- [x] The change in resource usage is discussed with and approved by Infrastructure.
- [x] A new content release is triggered upon completion of a previous one, starting at 9 AM ET and ending at 5 PM ET on Federal working days, except as noted
- [x] Between 9 AM ET and 5 PM ET M-F, manually triggered content releases will be ignored
- [x] Outside of business hours (5 PM ET - 9 AM ET, and weekends), manually triggered content releases will behave as they currently do.
- [x] Sitewide is alerted that the communication can move forward

## Tasks
- [x] Add a drush command to enable/disable continuous release
- [x] Write event subscriber to request a content release when the previous one is completed if it's during business hours and continuous releases are enabled
- [x] Merge CMS PR
- [x] Add metrics to datadog
- [x] Notify sitewide, platform, and program channel that continuous releases are enabled
- [x] Babysit content release to make sure it doesn't explode

### CMS Team

Please leave only the team that will do this work selected. 

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
@cweagans has done an initial pass for this work here: https://github.com/department-of-veterans-affairs/content-build/pull/887

Discussions should still be had with Infrastructure prior to proceeding with further work.

**Comment by timcosgrove** [comment]
It would possibly be nice for this to be able to be set via 'flag'/some sort of env variable. This could both be the mechanism for changing behavior - "we are in continuous release mode; now we are waiting for daily deploy to complete; it is after 5, so switch to manually-triggered mode" - and also allow for easier reversion to the previous behavior if that is needed, rather than just reverting the work out.

**Comment by cmaeng** [comment]
the sense that i get about urgency of this is that it's not currently a burning fire. we had discussions with @davidconlon and VHA Digital Media today, where this will be mitigated with a KB article and better communications on expected timing for content releases. if that changes we'll ping in this ticket but for now this can be planned / prioritized in accordance with our regular processes. @davidconlon let us know if that's incorrect.

**Comment by timcosgrove** [comment]
@cmaeng It would be great to get an update on the urgency of this, if you feel it's changed based on more recent events.

**Comment by cmaeng** [comment]
@timcosgrove i would say urgency for this specific ticket remains as is. urgency around stabilizing content releases in general though has ramped up. because that's not fully on our team to own/resolve it becomes muddy but doing what is within our control to ensure that content is available for hourly releases is high priority. TLDR: i'm not sure what else we can do to help that beyond what we're currently doing and without further clarification from OCTO-DE. more to come.

**Comment by timcosgrove** [comment]
@cmaeng To be 100% clear, this work would be done by whatever team is responsible for CI/CD for Content release, whichever team that turns out to be. This ticket is not intended to say that Platform CMS would do the work; that needs to be aligned with OCTO-DE guidance, as you say. Will wait to hear on guidance. Thanks!

**Comment by cweagans** [comment]
After https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8934 is merged, this ticket should be substantially easier. It should be essentially a single event listener that watches for a transition from `complete` to `ready` and when that transition happens, request a new build.

**Comment by cmaeng** [comment]
@mchelen @davidconlon looking for your formal approval on this before heading down the implementation path. the team is waiting on confidence in Datadog stability as the last technical step (change management to be handled separately).

cc: @ContentBrewmaster

**Comment by mchelen-gov** [comment]
@cmaeng I have no objections to this approach. Implementation and release should include appropriate updates to editor facing documentation and support resources.

**Comment by timcosgrove** [comment]
Prior estimate removed due to
* changed technical requirements and assumptions
* potential additional work for Change Management process

**Comment by ENeal49** [comment]
Initial plans for implementation would be to do a soft rollout and monitor for a week to work through any issues then communicate to all editors.

**Comment by cmaeng** [comment]
thanks @ENeal49 . please let us know when you have a sense of the readiness of this as we'll want to coordinate communications with a small group of folks first (Jenny HL and VHA DM) and then possibly all editors after the week of monitoring.

cc: @ContentBrewmaster @davidconlon

**Comment by cweagans** [comment]
The long and short of this is that at the conclusion of any given content release, we'll kick off another one. Hopefully, the only major thing that changes for editors is that their content goes out faster.

Some changes that might be good to communicate:

* During business hours, it will no longer be necessary to click the manual content release button. It will essentially have no effect on build scheduling (since we'll already be running releases back to back). It doesn't hurt anything to click the button, but it won't expedite a release either (we only ever run one release at a time).
* Same thing with publishing a banner during business hours: it won't really make a difference on release timing. (After hours, publishing a banner will still continue to kick off a release though)
* One implementation detail: if the conclusion of a content release queues another content release during business hours, then it is possible that a content release finishes at 4:59pm ET + queues and runs another content release. The result is that there is one _additional_ content release that will conclude after business hours.
* One of the metrics that we can use to understand the impact of a change to content release scheduling is worst-case publish-to-live time (during business hours)
	* This scenario is if an editor publishes content _right after_ the "Get Drupal Content" step in the build has finished (approximately 4-5 minutes into running the content release workflow), so the rest of the current build has to finish _in addition_ to the subsequent build to get that piece of content out to the live site. (This is a _calculated_ metric and not one that we have automation for, so there is no dashboard to monitor this on. This metric also assumes that things are running properly - scheduled releases are happening as scheduled, workflows aren't failing, etc)
	* Prior to this change, the worst case publish-to-live time is approximately **1hr 31min**.
	* After this change, the worst case publish-to-live time is roughly **56min** (approximately 38% faster)
	* (times are based on a 36 minute total runtime for content release. if content release gets slower, that will of course impact this metric)

If you'd prefer, there is a slightly different direction that we can take this that has approximately the same result:

* We check once per minute if any action has been taken in the CMS that would result in a change to the website.
* If so:
	* If a content release is not currently running, start one.
	* If a content release is currently running, make sure that we request one at the end of the current release.
* Impacts:
	* We'd likely want to remove the manual release button + any special behaviors for banners and the like. They would be unnecessary at this point.
	* We'd definitely want to communicate that any change to content would result in a content release being triggered. 
* (Same impact to worst case publish-to-live time)

**Comment by cmaeng** [comment]
thanks for the detailed description @cweagans . couple of thoughts, please correct me if i'm off track:

- removing the manual release functionality / button and any special behaviors is not something we should entertain yet as they would still be needed to publish after business hours. i'm not too worried about this as manual triggers are only available to content admins and banner alerts are fairly well governed by VHA DM.
- the first approach you described sounds preferable to me but it's hard to say without knowing the data around how many website changes occur on a given day. if <10 then maybe the second approach is sensible but if we're talking 100s or 1000s per day there will likely not be many cases with no changes made before the previous has completed thus rendering this approach moot. my vote, mainly for simplicity's sake is to just roll with option one as MVP, monitor, assess, and adjust as needed.

cc: @swirtSJW @ryguyk @JayDarnell for visibility

**Comment by cweagans** [comment]
> removing the manual release functionality / button and any special behaviors is not something we should entertain yet as they would still be needed to publish after business hours. i'm not too worried about this as manual triggers are only available to content admins and banner alerts are fairly well governed by VHA DM.

Totally agree if we're doing option A. If we're doing option B (which would effectively trigger a content release whenever content changes), manual releases wouldn't _ever_ be necessary. It's not an issue to keep them available from technical standpoint, but I worry about the UX of having a button that effectively does nothing (which would be the case with option b).


> the first approach you described sounds preferable to me but it's hard to say without knowing the data around how many website changes occur on a given day. if <10 then maybe the second approach is sensible but if we're talking 100s or 1000s per day there will likely not be many cases with no changes made before the previous has completed thus rendering this approach moot. my vote, mainly for simplicity's sake is to just roll with option one as MVP, monitor, assess, and adjust as needed.

After #8108, we're batching up all of the different build requests and only sending one. If there's a release in progress, any content change-related build requests would pile up and result in another build starting as soon as the first one is done. During business hours, this would effectively be a continuous content release. After hours, it would _look_ like continuous content release (but really it would just be on-demand).

Technically speaking, they're both very simple changes with the plumbing that we already have in place. I think it would be safe to go either direction - I think it's just a question of user expectations and such.

**Comment by cmaeng** [comment]
is the thought for option B to be only during business hours? currently, we don't support content releases outside of 8am-8pm on business days so if option B will instead be turned on 24/7, we'd need a wider and deeper conversation in order to see if that jives with stakeholders along with the logistics of supporting. this points me back to testing out option A and then having those other discussions separately.

**Comment by cweagans** [comment]
My intent with option B would be that content edits trigger a content release 24/7 (but we still only actively support 8a-8p, M-F). I'm totally fine with either option - just wanted to throw it out there in case that was a more desirable way to go!

**Comment by ContentBrewmaster** [comment]
When is the planned switch to the new release cycle? How long are we watching it before telling editors of the change?

**Comment by davidconlon** [comment]
As @cmaeng and I mentioned in zoom chat the other day, but just so that it's captured here: we are not telling the editors of this change. This does not hit the threshold of when we would announce a change.

**Comment by ContentBrewmaster** [comment]
Per @davidconlon's comment, closing #9968
