### ISSUE TITLE
VA health connect phone number in CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7618]
## User Story or Problem Statement

As a Veteran, I understand all my options for communicating with my VHA health care provider. 

In Drupal: Each health care system needs a field for VA health connect phone number.

Only Admins can edit (request fulfillment) because we'll get that number from OVAC.

## Questions

Who/how will these numbers be populated?

Should this be visible to editors before it does anything on the FE? If no, we could break update #7619 to release the field as hidden, and tackle field permissions and exposing the field to editors in a later followup. 

## Acceptance Criteria

Sprint 50
- [x] Field exists but it's hidden #7619
- [x] Sample content loaded in (877-741-3400 for VAMC Orlando)

Sprint 51
- [ ] Plan for getting these numbers from OVAC is established ([slack thread](https://dsva.slack.com/archives/C0FQSS30V/p1643057905185000))
- [ ] Change request runbook has been written and put to use by CMS user support team 

Later (52?)
- [ ] #7726
- [ ] Field is visible to all users but only editable by admins (#7660)
  - [ ] Field has good guidance for how to request changes (Could be done in design review?)

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`
