### ISSUE TITLE
Sprint 50 priorites - Product Support 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7621]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

If you want to see this on your board, assign yourself to this issue. (It's also pinned In progress)

</details>

## Q1 planning
- [ ] #7442 

## VHA Digital Media - this may need its own epic and issues

- Meet and greet - VAMC upgrade owns this meeting, Thursday 3pm ET
- Listening sessions (in progress) 
- Q1 calendar for change management (see below)
  - Claro
  - Top tasks
  - VAMC dashboard
  - VA health connect
  - Cerner

### #6872 Editorial experience (Jay, Erika, Suzanne)

- [x] #7391 
- [x] #7595 
  - [x] #6877 (possibly can be closed as a dupe) 
  - [ ] #6872 (possibly can be closed as a dupe) 

### #6881 Change management

Timing of these changes need to be sorted out

- [ ] #7551 
- [x] #7335
  - [ ] #7336 
  - [ ] Follow up for creating menu items (?) 💧
- [ ] #6882 (jane)
- [ ] #6883 (jane)
- [ ] #6272 
- [ ] #6273
- [ ] #6274 

Related
- [x] #7166 💧Defect from clinical service locations

## #7618 VA health connect phone number

Needs further refinement.

- [x] #7619 💧🥅 Iván

Later
- [ ] #7620 📟
- [ ] Exposed field to editors but not editable.

## #1447 VAMC dashboard

- Refinement  - The existing github issues are very stale and it might be good to start fresh.

## #7622 Lovell

Wednesday 3pm ET recurring meetings

- [ ] #7626 

## #7518  Cerner cutover strategy

- [ ] #7625

## Facility name changes (Iván, Steve, Jay)

- [x] #7628

## Other teams 

Content Ops
- working on Care we provide
- CMS-wide change management calendar
CMS experience
