### ISSUE TITLE
EPIC: Lovell - content design

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7622]
### User Story or Problem Statement

Lovell Federal health care ([beta modernized site](https://www.va.gov/lovell-federal-health-care/) | [legacy site, still the official one](https://www.lovell.fhcc.va.gov/)) has a VA Medical Center used by both Veterans and active service members and their families. It also has faciltities that are only for service members, and facilities that are only for Veterans.  

### Affected users and stakeholders

* Veterans
* Service members who use Lovell Federal heatlh care

### Hypothesis

There are a number of "forks" in the digital experience for each type of user. We need to determine what forks should or must be CMS-supported, and which are FE or Content-only forks. 

## Acceptance Criteria
- [ ] Lovell Federal health care can be fully launched and its old site turned off. 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by ContentBrewmaster** [comment]
@davidmpickett is it fair to assume that any change management for Lovell will be in Q4 instead of Q3? Is there a need to do any CM prep in Q3 you think?

**Comment by davidmpickett** [comment]
I think this is a pretty small CM lift overall. And yes it's Q4, not Q3.

**Comment by davidmpickett** [comment]
@dsinla @RWEagans This entire Epic is on hold right now since my priority was shifted to Veteran Research.

**Comment by davidmpickett** [comment]
Closing to consolidate remaining Lovell tickets into a single epic: #9656
