### ISSUE TITLE
Improve Related links component for R&S (and beyond?)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7631]
### User Story or Problem Statement

The existing link teaser used on many content types, including in the "Related information" sectino of all R&S content types, allows "internal" URLs (known to Drupal) and "external" URLs (not known to Drupal, but could still be va.gov).  

Currently, editors must re-enter the link summary each time they add a link teaser. This mean the same link on www.va.gov may have dozens of different summaries. 

How might we improve the governance and editorial experience for this component on R&S content types? 

<details><summary>Screenshot</summary>

<img width="970" alt="Create_Step-by-Step___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/149953925-509a2161-e87f-4110-8364-dede48692512.png">

</details>

### Audit

* How many link teasers exist
  * Per component (eg Related links versus elsewhere)
  * Per content type 
  * Internal URLs vs external URLs

### Some questions for discovery

* Internal vs external 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.

  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Closing as a no op; a new epic will be created, or this work rolled into the current centralized forms initiative.
