### ISSUE TITLE
Discovery: Determine strategy for expansion by Office, content type, and audience

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#7638]
### User Story or Problem Statement
We need to focus our work down from the mass of Tier 3 to something manageable. Focus will be along the dimensions of:

- Office – some finite subset of the ~800 offices in the FOM
- Content type – a minimal set of content types with firm governance will be provided
- Audience – prioritization of content for migration within Pilot Offices will start with Vets, with other audiences TBD.

Assumptions:
 - There are a handful of offices (content owners) who are already aware that they have Tier 1 and 2 content that has not yet been modernized. They will be our Pilot Partners (ie, early adopters, allies, etc).

## Acceptance Criteria
- [ ] 3-4 Pilot Offices identified
- [ ] Content types for pilot offices defined and ready for development

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [ ] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange)
- [x] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
This Epic seems like it could be iceboxed? @wesrowe @jilladams

**Comment by wesrowe** [comment]
yes, added icebox label. there are other Offices epics that can get the label also, I'll make a note to look for them
