### ISSUE TITLE
Onboard Search and Discovery team to R&S products in CMS

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7683]
## Background
Search and Discover team members need access to form and R&S content.

## Acceptance Criteria

Megan Gayle, Tyler Simoni and Nicole Leonard need 
- [x] Access to CMS (no roles at first)
- [x] Training to find R&S and Forms content 
- [x] Training to use the Forms flags 

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
Assessed needs: they need to know when forms change, showed how to find forms and flags, they had a feature request for R&S, gave them a preview of Claro, and showed them how to login, sent follow up email with links
