### ISSUE TITLE
Design workflow and governance for machine name for terms in Service taxonomy

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7697]
## User Story or Problem Statement

See #7624

<details><summary>Current experience</summary>

<img width="1053" alt="Edit_term___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/150554642-45ba7583-efa8-4d78-ab3f-d5cb8782c6ef.png">

</details>

## Acceptance Criteria
- [ ] Facilities owns the governance and machine name design process for new taxonomy terms
- [ ] Lighthouse is in agreement with that the (highly trained) CMS users who own the service taxonomy will design the machine names. 
- [ ] New field label and help text for "Health Service API ID" field are designed for #7557 and that issue is updated. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@swirtSJW should this be CMS or facilities? Feels facilities to me

**Comment by davidmpickett** [comment]
I was going to try and edit this ticket to reflect the current reality, but given how much has changed, I think it's better to close this and start fresh
