### ISSUE TITLE
Create Views permissions plugin for Workbench access 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7707]
## User Story or Problem Statement

We have a number of dashboard-type Views, like the VA Forms and Resources and Support views, that should only be visible to a subset of users, but we don't have a role specific to that subset of users. 

There may be some related issues in the Workbench Access issue queue already.  

## Acceptance Criteria
- [ ] Drupal site builders can add section-based access permissions to Views, and that access can be used in combination with another permission system (eg roles)

## Implementation steps
Views plugin? 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Moved to icebox based on: https://dsva.slack.com/archives/C0FQSS30V/p1654630965614079
