### ISSUE TITLE
DevOps support for testing updated theme build process

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#7714]
See #7552 and #7564.  This is just tracking work on the DevOps side that is needed to support proper BRD testing of the theme build changes.

### Tasks:
- [x] Refresh CMS-Test DB
- [x] Open DevOps PR to make necessary changes for testing - department-of-veterans-affairs/devops/pull/10607
- [x] Push CMS branch to va.gov-cms-test to enable deployment to testing
- [x] Build new AMI (see [here](http://jenkins.vfs.va.gov/job/builds/job/cms-test/324/))
- [x] Deploy AMI to test.prod or test.dev since I think Eric is on test.staging (see [here](http://jenkins.vfs.va.gov/job/deploys/job/cms-test-vagov-dev/302/))
- [x] Confer with Tanner and verify everything worked as expected.

### CMS Team

- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
