### ISSUE TITLE
Write improved error message for facility nonclinical service page when user creates more than one of the same service at one facility

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#7720]
## User Story or Problem Statement

As an editor who has just tried to create a facility nonclinical service at a facility that already has a node for that service, I need an error message that explains the problem and takes me straight to the place where I can fix it. 

## Acceptance Criteria
- [ ] Error message language is specific and clear. 
- [ ] Update the link to go to edit node instead of view node
- [ ] Requires design review

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by Agile6MSkinner** [comment]
We're addressing this through other means. Closing.
