### ISSUE TITLE
Q1 2022: Clear Facility flags and update data change issue template with Flag details

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7728]
## User stories

As a help desk or request fulfillment responder
* I want to understand how the new Flag dashboard relates to the runbooks [in the github issue template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/facility-data-change-request.md), so that i can properly unflag content once a runbook has been fulfilled.

As a Faciltiies team member, 
* I want to process the existing Flags backlog 
* I want a shared understanding of the runbook
* I want a schedule to review flags periodically until there's a notifications framework
* I want to contribute to the notifications framework 

As a Lighthouse team, 
* I want some general understanding of CMS content lifecycle. 

## ACs
- [ ] Meet with Facilities team Feb 14 ([See notes here](https://docs.google.com/document/d/17HqSDO5y1wm3M3I4Z3fTDM4CUrZBTJZbADloCjz7-So/edit#heading=h.dzqq3726sgqn))
- [ ] [Existing flag blacklog](https://prod.cms.va.gov/admin/content/flagged) is cleared 
- [ ] [Runbooks](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/facility-data-change-request.md) are updated
- [ ] Any other documentation is updated as necessary 
- [ ] Stretch: [Notifications user stories are updated](https://docs.google.com/document/d/1eBxUfMSrj5RjAuUlRsMSP8QR3zCReIpILc5LbZqxqHI/edit#)

**Comment by JayDarnell** [comment]
Currently seeking guidance from @mmiddaugh regarding the need for redirects for facilities tagged with `Removed from source`

**Comment by JayDarnell** [comment]
All content for the archived Oakland VA Clinic (under VA Northern California health care) appears to be reassigned to the "new" Oakland VA Clinic (under VA San Francisco Health Care) - as such the archiving process for this facility appears to be complete. Removing flag.

**Comment by JayDarnell** [comment]
All content for the archived Twenty First Street VA Clinic (under VA Northern California health care) appears to be reassigned to the "new" Twenty First Street VA Clinic (under VA San Francisco Health Care) - as such the archiving process for this facility appears to be complete. Removing flag.

**Comment by cmaeng** [comment]
next steps after flags: refining workflow and processes to include possible auto-notifications

**Comment by kevwalsh** [comment]
Notifications are in progress via #9097.

I'm closing this epic and we'll open a new one for refining business process.
