### ISSUE TITLE
Expand VAMC system audit for use in reviewing VA health phone connect, and other numbers

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7729]
## User Story or Problem Statement

As a Facilities content admin, I want to be able to see VAMC system specific data in one spot, so that i can review it for completeness on a number of data points.

## Acceptance Criteria
- [ ] `/admin/content/audit/vamc-ehr` has been moved to `/admin/content/audit/vamc-systems`
- [ ] Sortable and filterable data fields 
  - [ ] Title (rename this to "VAMC system plain language name (Title)"
  - [ ] "VAMC system official name"
  - [ ] "EHR system"
  - [ ] "VA health connect phone number"
  - [ ] "Appointments can be made online" boolean field, formatted as Yes/No
  - [ ] Path (URL Alias)
  - [ ] Govdelivery email lists
  - [ ] Last updated date and by, formmated to match the /admin/content 
- [ ] Default sort: "VAMC system plain language name (Title)"
- [ ] Edit link works (it's currently broken)
- [ ] Menu link title is changed to "VAMC systems"

## Implementation steps
- [ ] Update the view

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
In order to think through the ACs, i configured this in a Tugboat environment. i think it hits enough of these ACs and more, but needs behat tests update to pass.

<details><summary>Screenshot</summary>

<img width="1922" alt="Content___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/150875170-46116164-2387-4323-a70a-837b59a68c04.png">


</details>


[views.view.content.yml.txt](https://github.com/department-of-veterans-affairs/va.gov-cms/files/7929230/views.view.content.yml.txt)

**Comment by kevwalsh** [comment]
This was done in [this demo environment ](https://main-g0ovfooigfojcgcoaykq1ghkb0vwg4wd.demo.cms.va.gov/), the config may still be there.
