### ISSUE TITLE
Support Sitewide content team with VHA R&S pilot 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7743]
## User Story or Problem Statement

Sitewide content team is leading [a pilot to move legacy content into Resources and Support](https://docs.google.com/presentation/d/1bikvciXOkgatIfgpQ0i5Zeu3u06w1rfA/edit#slide=id.p1)  as a way to learn more about the product and how we might iterate

[Hypotheses](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/resources-and-support-author-pilot/hypotheses.md) that Sitewide wants to test with this pilot

Background on the [Resources and support product](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/tier-2-content-IA-and-design/learning-center-mvp/product-outline.md).

## Calendar

February: 
- CMS UX Discovery
- Documentation / training materials
- Onboard users
- Confirm governance policies

March
- Study

## Acceptance Criteria

General
- [x] CMS Discovery: Resources and Support #7880
- [x] We have contributed [questions/hypothesis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/resources-and-support-author-pilot/hypotheses.md) that the pilot could help answer

#7683 Onboard and train Search and discovery team members and  VHA Pilot users
- [x] #7610
- [x] #7686
- [ ] Create accounts for VHA Pilot users
- [ ] Create training materials for R&S 

Product documentation
- [ ] Write/rewrite content type descriptions for R&S, and put in the UI and in KB
- [ ] When to use R&S vs when to use Benefit hubs

Governance for R&S 
- [ ] #7609 Drupal account admin policy
  - [ ] Design Sections policy for R&S users and content types
  - [ ] Determine roles for Pilot users (editor vs reviewer vs publisher)

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [x] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [x] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Added CM triage section and made selections.

**Comment by davidmpickett** [comment]
@EWashb I'm trying to clean up design related ticket in the backlog. Would it be safe for me to add the Icebox label to all the remaining tasks in this epic?

**Comment by EWashb** [comment]
@davidmpickett it might be worth a check in with @DanielleThierryUSDSVA to see what the current situation is with the R&S effort. The extent of our research was a survey that we planned to resend after a certain amount of time has passed. We do have some baseline data from this group from when they were onboarding to the CMS. But, I don't think our support is a priority at this moment.

**Comment by jilladams** [comment]
@DanielleThierryUSDSVA @wesrowe FYI that since Public Websites owns the Resources & Support product, moving this into the Public Websites backlog.

**Comment by davidconlon** [comment]
@DanielleThierryUSDSVA @jilladams I recommend that we audit a lot of these issues and close several as "not doing".

Instead, I think we need to pivot to a "CLP 2.0", discovery, etc. especially in light of the 21st c. idea act guidance.

Thoughts?

**Comment by DanielleThierryUSDSVA** [comment]
I think that's a good plan, @davidconlon, yes.

**Comment by FranECross** [comment]
@DanielleThierryUSDSVA (no rush) Will you please take a look at the still open tickets and let me know if they can be closed? (looking at the convo between you and Dave above). I'm not sure if they were left open after an audit, or if all tickets and this epic can be closed. Thanks! cc @jilladams

**Comment by FranECross** [comment]
Per Dave Conlon's suggestion, closing:

I recommend that we audit a lot of these issues and close several as "not doing". Instead, I think we need to pivot to a "CLP 2.0", discovery, etc. especially in light of the 21st c. idea act guidance.
