### ISSUE TITLE
Top tasks show help text and edit links in View Node

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#7749]
## User Story or Problem Statement

As an editor, I want View Node to mimic the content and structure layout of the front end as much as possible, so that I know what to expect. Also, I want the difference between View Node and Edit Node to be clear so I don't have to think too much about where I am. 

Because the location cards on top task pages are drawing content from another node, in View Node you see the help text and add/edit links instead of just the content. This is confusing and could cause more confusion down the line as we start to implement the location card pattern more broadly. 

![Screen Shot 2022-01-25 at 3 18 00 PM](https://user-images.githubusercontent.com/90172187/151076516-ad81518a-7244-4767-84f3-5af1ef8aafe7.png)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Mitigated by access to the Preview link.

**Comment by JonathanKatora** [comment]
@r-bartlett-gsa a couple thoughts on this issue: 
1. this feels like an editor experience ticket more than a service accordion ticket.
2. However, if there opportunity to focus on Facility Service editor experience while working on SA improvements, it should stick around. 
3. The title of this issue is not great, and kind of obfuscates what the intent of the ask. The user story suggests, "As an editor, I want View Node to mimic the content and structure layout of the front end as much as possible, so that I know what to expect." and is probably the biggest pain point for edits **WYSINWYG** when it comes to services. Could we either repurpose this issue to reflect the core of the problem, or close and recreate under a different issue temple to better document the requirements?

**Comment by r-bartlett-gsa** [comment]
@JonathanKatora I'm leaning towards closing this ticket. It's 4 years old... If we uncover these same or similar editor pain points as part of our research, we create new tickets.
