### ISSUE TITLE
<Login Page Error Message Consistency Review>

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#7754]
## User Story or Problem Statement

As an editor logging in with a password, I need consistent error messages when there is a login issue so I can troubleshoot the problem. Currently, there is inconsistent messaging on the banner and beneath the username field. 

## Acceptance Criteria
- [ ] UX writing is clear and consistent
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
![Screen Shot 2022-01-25 at 3.30.13 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/28377298-4e22-488a-8b40-846bfa568407)![Screen Shot 2022-01-25 at 3.35.51 PM.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/20f73c2b-02e0-4202-9f6c-ec4956c665d5)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes, and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ X] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ X] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [] `Platform CMS Team`
- [X] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ X] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Think about it like a combination lock.  A really cheap combination lock like this.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b0900b70-0d03-4337-9eb9-40b5d91fd51a)

Imagine if the first dial (the username) gave an audible click when you hit the right number.
Giving away that the user name was right, would be the same as giving a an audible click.  It significantly cuts down the time it would take you to pick that lock.

**Comment by swirtSJW** [comment]
The misleading part is this
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/285db220-f0aa-4e4f-91ca-5388e9fe8c82)

That message is to draw your attention to the problem and provide an accessible link down to the field.   The confusing bit is that it can only link to one id of one field.  It can't link to both fields.    Probably the best improvement would be to have a field group around the username and password field and have it jump to that where the error message would be.
