### ISSUE TITLE
Improvements to facility nonclinical service node

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#7783]
## User Story or Problem Statement

As an editor, I need to understand what the facility nonclinical service node is and when to use it. Some current issues:

* The easiest way to add and update the facility nonclinical service node is through a top task page. But there are other ways to access this form.
* Facility nonclinical service shows up under Add Content, but top task pages don't. If I try to do top task work through the Content menu I will quickly get confused.
* If I create Facility nonclinical service through the Content menu, there's no context for what it to put on the form.

 
## AC
- [ ]  remove the facilities nonclinical service form from the admin menu (but not from the content types list) 
- [x] DONE elswhere: add help text and/or submission guidelines to help users orient to the form (see #7784)
* ~rename the node to something that's more clear (not for now)~

## Considerations
* how will this form be used in the future? 

## Acceptance Criteria
- [ ] Create Content > VAMC Non-clinical 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`
