### ISSUE TITLE
Feedback mechanism for centralized content

### ISSUE THREAD

**Issue by suzanne-gray** [department-of-veterans-affairs/va.gov-cms#7787]
## User Story or Problem Statement

As an editor, I need a way to suggest changes to the centralized content that appears on my top task pages, so that Veterans get accurate information about the services at my VAMC system. 

As a [VHA national content person?], I need a way to receive feedback about centralized content so that I can make informed decisions about how to present the most useful and relevant content to Veterans.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by suzanne-gray** [comment]
VAMC product team doesn't want to pursue a feedback mechanism right now, per [this slack thread](https://dsva.slack.com/archives/CT4GZBM8F/p1644271041311829)
