### ISSUE TITLE
Sprint 51 priorities - Content Ops

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7795]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

## Q1 planning

Review roadmap 

## #1956 Recurring events (Ethan, Kauff)

- [x] #7803 
  - [ ] Engineering stretch: #7285 
  - [ ] Final design review
  - [ ] Dry launch with Sam from PW 🥅
- [ ] #6066
  - [ ] #6073
  - [ ] #6349 

## #7593 Change management framework 

- [ ] #7796 🥅
- [ ] #7804 (shared with Product support)

Stretch:
- [ ] #7797
- [ ] #7798 
- [ ] #7807

## #4799 VAMC Care we provide (Denise, Jay, Kevin, Steve)
- [x] #7658 (Lynn)
- [x] #6828 
  - [x] Validate the approach to resaving content as Rich text limited (Lynn)
  - [x] Figure out how to run Jay’s script (Lynn, with Steve and/or Jay)
- [x] https://github.com/department-of-veterans-affairs/va.gov-team/issues/22115 (Kevin coordinating with Facilities)
- [ ] Training and KB
- [ ] #7656 (Denise, VHA DM, Facilities team)

## #4856 Better monitoring upstream data changes (Steve)

- [x] #7604 
- [x] #6522 
- [ ] Then we can shift to notifications and iterating on business processes.
- [ ] Refine: 
  - [ ] Group subepics 
  - [ ] Refine Notfications epic.

## #7612 Audit tools improvements 

Possibly refine. 

## #7629 Support discovery for homepage redesign 

Nothing this sprint.

## Benefits Hubs content model iteration

Some discovery and refinement TBD

### Observe and support VHA Pilot

TBD

### #7631 Link teaser component for R&S (and beyond)

TBD

### #6170 Improve meta tags across all content types 

- [ ] #6935 💧

### #832 Entity Revisions

- [x] #829 (merged on Friday late afternoon!)
- [ ] Any followups other than #830 (low priority)? Who needs to know? Sitewide content team, Dave.

### Tech debt and minor improvements (Iván)

- [ ] #7671 
- [x] #7275 
- [x] #4918 
- [x] #7276 
- [x] #7788 
- [x] #6696 
- [x] #7353
