### ISSUE TITLE
FOM Qualitative Audit

### ISSUE THREAD

**Issue by valerierunde** [department-of-veterans-affairs/va.gov-cms#7811]
### User Story or Problem Statement

<As a FOM editor, I need to know whether my FOM content is within plain language guidelines so I can ensure content is understandable and readable to a wide range of audiences.>

### Affected users and stakeholders

* FOM editors
* Sitewide content team

<link to any existing research or data supporting this>

### Hypothesis

We believe that the bulk of FOM content is written at a higher comprehension level than is within content and accessibility guidelines.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by valerierunde** [comment]
Issues moved out of this epic and into 7638.
