### ISSUE TITLE
Improve error experience for Allow Only One

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7818]
## Status
**[2024-06-12] [Jill A]** From onsite / Q3 planning session: once we've solved #17674, this also needs to be revisited for priority for VBA / VAMC.

## User Story or Problem Statement

See #7720. 

Error messages for Allow only one are confusing and not helpful to editors. 

2023 update - this might also be a place where Client-Side validation would be a good addition

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
This is currently already working for Vet Centers. Facilities team has a vested interest in getting this working for VAMCs, so while this is in the CMS backlog, we may opt to try and help work on it. (cc @gracekretschmer-metrostar @EWashb )

**Comment by jilladams** [comment]
TODO: @jilladams @omahane discuss in next eng refinement: do we: 
* Keep this ticket / redefine it to cover the winnower approach OR
* Write ourselves a ticket to describe what we are trying to achieve with the winnower, and deal with this ticket once that's landed, either way.

**Comment by davidmpickett** [comment]
This is the ticket for the winnower approach: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/17674

**Comment by davidmpickett** [comment]
Marking as blocked by #17674. once that ships we can revisit if there are other instances of Allow Only One that could benefit from that same approach

**Comment by jilladams** [comment]
From onsite / Q3 planning session: once we've solved #17674, this also needs to be revisited for priority for VBA / VAMC.

**Comment by davidmpickett** [comment]
Closing as not planned. We have dealt with several specific instances and there's no additional information in this ticket about other places where this is a problem. We should always be mindful of reviewing error messages when updating any product. I don't think an "Allow only one" error message audit has much value at this point.
