### ISSUE TITLE
Discovery: Auditing Offices

### ISSUE THREAD

**Issue by valerierunde** [department-of-veterans-affairs/va.gov-cms#7823]
## Background
Conducting a quantitative audit the following offices to determine content types, documents, cross-linking, intended audiences, and any other risks or information that pops up.
* Veteran's Experience Office
* Education Service
* Mental Health (TBD)

## Acceptance Criteria
- [ ] Screaming Frog report for VEO
- [ ] Screaming Frog report for Education Service
- [ ] Airtable inventory for VEO
- [ ] Airtable inventory for Education Service
- [ ] Insights and analysis summary

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by valerierunde** [comment]
Issues moved out of this epic and into 7638.
