### ISSUE TITLE
Next Build System (Q2 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7852]
## Background

During our POC and research efforts, we came to the conclusion that a Public API needs a modern frontend build system, but a modern frontend build system doesn’t need a publicly accessible API to deliver value. The team will focus on providing a React-based static site generator (SSG) solution to serve as the foundation for implementing a public API.

We want to build a front end for CMS content that is based on a React-based framework, so that front-end engineers are working with a modern toolset that is compatible with the larger VA.gov front-end ecosystem. We also want to prioritize a front end framework that is flexible and that will allow us to make iterative improvements to VA.gov CMS content and its delivery. We evaluated both Next.js and Gatsby, and determined Next is the framework most suitable to meet the needs of this project.

### User Story or Problem Statement

A new, React-based content build system will provide a modern frontend development framework to support the accelerated publishing initiative.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [x] Noticeable performance improvements (publishing speed, predictability)

### Affected users and stakeholders

* CMS editors
* CMS Engineers

### Hypothesis

We believe that the new content build system will ultimately enable faster publishing speeds. We'll know that to be true when content is released without significant delay.

## Acceptance Criteria

- [ ] HTML is rendered and sent to S3 in a more efficient manner (React-based Static Site Generation) using Next.js
- [ ] Component library exists for VFS teams to utilize in Production
- [ ] Content can be previewed in Preview server 

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
