### ISSUE TITLE
Include publisehd/unpublished state on Recent changes block for VAMC alert 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7858]
## User Story or Problem Statement

As a CMS user, i want to see which revisions of my content are  published or not published in the Recent Changes

Problem: this doesn't work on VAMC alert status nodes, like https://prod.cms.va.gov/va-eastern-colorado-health-care/vamc-banner-alert/2022-02-01/hazardous-weather-conditions

<details><summary>Screenshot</summary>

<img width="1151" alt="Hazardous_Weather_Conditions___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/152223420-3ab633f3-d501-4428-8ebd-d4b1ac51ff5a.png">

Rationale for not having editorial workflow statuses is shown on the edit form (eg https://prod.cms.va.gov/node/43397/edit) 

![image](https://user-images.githubusercontent.com/643678/152223438-df1a6f8f-23e0-4dd2-9f66-4bd9d99c80fe.png)

</details>

Moderation also shows as N/A on /admin/content and similar views, which is confusing. 

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/643678/152224436-c5b2d094-5299-4657-86f1-7264c065ac00.png)

</details>

How might we make this content type act more like the other ones, despite its lack of editorial workflow? 

Ideas
* Update the views to have some conditional behavior in them  (eg twig in the views field that shows a different value set depending on the content type (Published/Unpublished for VAMC alerts, Draft/In Review/Published/Archived for everything else)

## Acceptance Criteria
- [ ] TBD

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team

Please leave only the team that will do this work selected.
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team`
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`
