### ISSUE TITLE
Content Release Maintenance (Q3 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#7955]
## Background

Content release has been experiencing significant delays (publishing time ranging anywhere from 30min to up to 2 hours). This is not an ideal experience for editors, additionally, internal teams need better visibility into which stages of the build are impacting the total content release time. Several mitigation steps have been proposed, including reverting the content build from GHA back to using Jenkins; due to the LOE associated with this change, the CMS team will be exploring interim options and evaluating whether any improvements are realized.

Recommendations: https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2070347842/Content+Release+Timing+Issues

### Problem statement

* As a CMS engineer, I want to have the entire content release workflow visible in a dashboard so that I can have an accurate depiction of the build metrics to proactively identify any areas of the workflow needing attention.

* As a CMS engineer, I want to reduce/eliminate any delays in the content build workflow to improve overall content release stability, publishing speeds and editorial transparency.

### Change management triage

The change represented by this epic will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [x] Noticeable performance improvements (publishing speed, predictability)

### Affected users and stakeholders

* CMS editors
* CMS engineers

### Hypothesis

We believe that improving content build metrics visualization and addressing workflow delays will achieve increased visibility for when content will be deployed and improved publishing speeds. We'll know that to be true when content is consistently released in a reasonable timeframe.

## Acceptance Criteria
- [ ] Content release metrics indicate less variation over 7-day average
  * Measures to consider: build time, workflow time, time to deploy content, average time between deploys
- [ ] Content release data (including any wait/delay times) are appropriately tracked and visible in Datadog for identifying trends
- [ ] Existing KB article(s) updated with accurate content publishing expectations for editors

### CMS Team

Please leave only the team that will do this work selected.
- [x] `Platform CMS Team`

**Comment by timcosgrove** [comment]
Closing with the close of Q3. Some issues undone and deprioritized due to team members being unfunded; moved to #10896
