### ISSUE TITLE
Spike: Evaluate Automated Crop

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#7994]
## User Story or Problem Statement

Current automated crops simply take the middle of the image. How might `automated_crop` improve that, if at all? 

## Acceptance Criteria
- [ ] We've investigated https://www.drupal.org/project/automated_crop for potential use on VA.gov CMS
- [ ] Summary of findings is in this issue in a comment. 

## Implementation steps
- [ ] Install locally and experiment
- [ ] Document examples where this would help, or not help, given the existing uses of images on VA.gov.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
### Issue has also been reported by VA Madison in VAHELP-3602:

"How do I know what crop aspect will be applied on images on certain pages? For example, I am updating our Leadership list images using the Staff profile and I have set crops on the new image but the display doesn’t match any of the crops that I set it up. See below. It seems like it is taking the 3:2 crop and then cropping it narrower? Can you advise me on how to get the staff profile to use either the original or square crop that I setup? Sorry if this is a newbie question, this is my first time using the Drupal CMS, but I do have CMS experience. Thank you for the help."

### Screenshots from Editor:
Note that the person's forehead is being cut off midway despite the Editor specifying non-forehead-cropping borders:

![image](https://user-images.githubusercontent.com/9059428/155600756-1e10e98a-b429-4a25-bf93-456c599be018.png)

![image](https://user-images.githubusercontent.com/9059428/155600772-b2134c28-a230-4f2d-86ec-7876bf2161b8.png)

**Comment by kevwalsh** [comment]
@stefaniefgray Lynn fixed a defect in #8149 which will hopefully take care of the issue reported in VAHELP-3602
