### ISSUE TITLE
Spike: evaluate contrib for messages and notifications

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8026]
## User Story or Problem Statement

As a developer I would like to know if a popular stack of modules will accomplish what we need for workflow notifications.

[Message stack](https://www.drupal.org/node/2180145) or [more docs](https://www.drupal.org/node/2919768)
  * [Message](https://www.drupal.org/project/message)
  * [Message subscribe](https://www.drupal.org/project/message_subscribe)
  * [Message notify](https://www.drupal.org/project/message_notify)

perhaps integrating
* [Notifications widget](https://www.drupal.org/project/notificationswidget) 
* [Workbench email](https://www.drupal.org/project/workbench_email) 

## Acceptance Criteria
- [ ] Go or no go decision
- [ ] Suggestions for connectors (custom) that might be needed so they play nicely
- [ ] List of what it won't do

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Closing this as this spike was completed https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8721
