### ISSUE TITLE
Allow auth users to export CSV of users

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8048]
## User Story or Problem Statement

As a business partner such as VHA digital media, i want to know who has access to edit content for my products (like, has a specific role), so that i can review for governance permissions. 

## Acceptance Criteria
- [ ] Non admin users can get CSV reports like this one`prod.cms.va.gov/admin/people/vacms-user-export.csv?user=&status=1&role=vamc_content_creator&workbench_access_section__section=All&page&_format=csv`

## Implementation steps

<details><summary>This approach failed.</summary>

We haven't created product-specific account admin roles, or built out reporting tools (like the Section members tab), Ii think we can solve for this by simply extending access to CSV dumps of /admin/people to authenticated users. 

1. Go to /admin/structure/views/view/user_admin_people/edit/data_export_1
2. Override the display's permission setting (but not the default permission setting) to Role, and make it available to any authenticated users
3. Test `prod.cms.va.gov/admin/people/vacms-user-export.csv?user=&status=1&role=vamc_content_creator&workbench_access_section__section=All&page&_format=csv` as any non-admin user. You should get a download. 

This failed, probably because the user probably needs access to the view with which the CSV export is generated.

</details>

Workaround: 
* CMS help desk team bookmarks [this CSV export link](prod.cms.va.gov/admin/people/vacms-user-export.csv?user=&status=1&role=vamc_content_creator&workbench_access_section__section=All&page&_format=csv) and runs this report periodically on behalf of the users. 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@kevwalsh 
I'm not clear about where should this CSV (or link) should be added.

**Comment by kevwalsh** [comment]
@netboss the links is already there, you can find it at /admin/people

i don't think this issue has a valid implementation approach yet tho. 

Enabling access to the CSV export view display doesn't seem to work, if the user doesn't have access to the view display from which that export is coming. You may want to validate my finding there first. 

Maybe there's a different approach that _could_ work, without having to build a bunch of new custom view displays.

**Comment by netboss** [comment]
@kevwalsh 
The problem I see is that this view /admin/people requires the "Administer users" permission which only "Administrators" and "CMS account admin" roles have.

Question: which roles do we want to provide access to view user details? (not necessarily edit them)

**Comment by swirtSJW** [comment]
Sorry, did simply removing access checks on the existing view not work?

**Comment by netboss** [comment]
@swirtSJW 
Apparently not (I might be doing something wrong though). These are the steps I did in the default "People" view:

1. In the `/admin/structure/views/view/user_admin_people/edit/data_export_1` view display clicked the "Query settings"
2. Checked the "Disable SQL rewriting" checkbox
3. Copied the CSV URL from `/admin/people`: [CSV file URL](https://va-gov-cms.ddev.site:8443/admin/people/vacms-user-export.csv?page&_format=csv)
4. In a different browser logged-in as user with the "Content Admin" role and tried to download the CSV [CSV file URL](https://va-gov-cms.ddev.site:8443/admin/people/vacms-user-export.csv?page&_format=csv) but the download window never showed

It seems that if the role doesn't have access to the default "People" view it also won't have access to download the CSV.

But with the new view which I changed the permission to be by role "Content Admin" and "Administrator" only, if I log-in as a user with the "Content Admin" role I can access the new view and download the CSV. Right now is set to those two roles, but we can add more roles if needed.

**Comment by swirtSJW** [comment]
I got it sort of working with just removing the access checks with the sql-rewriting.  What was not working is that it limited the results to the section the user was in.   Example I logged in as an editor from Pittsburgh VAMC and I could only see other users assigned to that section.   But I did not investigate farther.

**Comment by netboss** [comment]
@swirtSJW 
Yes, I think I noticed something similar when I was still using the permission "View user information" in the new view, when I changed it to permission by role "Content Admin" and "Administrator" then the users' list showed all.
