### ISSUE TITLE
CMS should reflect FE  facility list of link teasers limiting to 8

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8058]
## User Story or Problem Statement

As an editor I would like to know that I can only put up to 8 link teasers in for spotlight since the FE only shows  upto 8 so that I can decide accordingly and get results that makes sense.

FE template code:
https://github.com/department-of-veterans-affairs/content-build/blob/50c15dfa86e34d9f98d20bc99c8f31a89760cf2b/src/site/paragraphs/facilities/list_of_link_teasers_facility.drupal.liquid#L20-L26
FE ticket that created this. https://github.com/department-of-veterans-affairs/content-build/pull/728

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
CLosing as a duplicate of https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7096
