### ISSUE TITLE
Install Datadog APM components on BRD environments

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8075]
## Background 

The CMS team will be implementing additional monitoring in Datadog for better insight and analysis on application performance. APM will allow the team to proactively identify any anomalies or downward performance trends and resolve these issues quicker. APM will be installed in the lower environments first, tested, and then installed in production.

### Acceptance Criteria

- [x] Datadog PHP extension is installed in BRD environment (dev, staging, Prod)
- [x] Ensure agent credentials are configured in Ansible store

### Tasks
- [x] Install the Datadog PHP extension: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=otherenvironments#installation-and-getting-started
- [x] Configure the agent credentials: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=otherenvironments#configure-the-datadog-agent-for-apm
- [x] Ensure that the [automatic instrumentation](https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=otherenvironments#automatic-instrumentation) is working properly
- [x] Ensure that each environment is identified separately in Datadog for filtering purposes

### Implementation

* For the time being, we can see how the automatic instrumentation works and enhance later if needed
* Integration with ecosystem not needed with this ticket
* Implementing in BRD (PHP extension) depends on dogstatsd

### CMS Team
Please check the team(s) that will do this work. 

- [x] `Platform CMS Team`

**Comment by olivereri** [comment]
#### Amazon Linux Install:
```

DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=e21aa8d73b3a48a8f82494bb91a096e7 DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
```
https://app.datadoghq.com/account/settings?_gl=1*qk42rp*_ga*MjU3OTY0OTA2LjE2MjkxMzU0OTI.*_ga_KN80RDFSQK*MTY0NjI1MTAxMi4yMy4xLjE2NDYyNTIyNzEuMA..#agent/aws

#### Basic Commands:
https://docs.datadoghq.com/agent/basic_agent_usage/amazonlinux/?tab=agentv6v7

#### DD Agent Already Installed During Build
Useful Ansible role default vars that can be overridden, i.e. pinning the agent version:
https://github.com/department-of-veterans-affairs/devops/blob/732879f029d1001060e9507878ac8f887225f8b1/ansible/build/roles/datadog/defaults/main.yml

Modify this to include cms overrides to DD Agent install:
https://github.com/department-of-veterans-affairs/devops/blob/134436eba9345b5982d876119d76acaef38762c4/ansible/build/roles/datadog/tasks/main.yml#L9

#### Tasks:

**Comment by olivereri** [comment]
Example DD Trance search
` env:brd-staging  @DB.instance:dsva_cms_staging `

Given tags for Database traces looks like:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/b52fd453-838f-4bdd-bf68-1cb4a1bbb4f8)

**Comment by mchelen-gov** [comment]
Is this in Prod? Don't see CMS in APM service list: https://app.datadoghq.com/apm/services?start=1648217313674&end=1648220913674&paused=false

**Comment by mchelen-gov** [comment]
[Found it](https://app.datadoghq.com/apm/services?env=brd-prod&start=1648218740980&end=1648222340980&paused=false), is there a reason for naming environments `brd-stage` and `brd-prod`? This differs from `vets-api` environment naming conventions.

**Comment by olivereri** [comment]
> 

https://app.datadoghq.com/apm/traces?query=%40_top_level%3A1%20env%3Abrd-prod&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&historicalData=false&messageDisplay=inline&sort=desc&streamTraces=true&start=1648222450736&end=1648223350736&paused=false

**Comment by olivereri** [comment]
> [Found it](https://app.datadoghq.com/apm/services?env=brd-prod&start=1648218740980&end=1648222340980&paused=false), is there a reason for naming environments `brd-stage` and `brd-prod`? This differs from `vets-api` environment naming conventions.

There aren't a lot of easy ways to uniquely identify traces outside of using additional tags.  Using a unique `ENV:` parameter that doesn't conform to another team's convention is an easy way to make this possible.  I think the only other "top level" tag/parameter is `service` that could be used to further filter. Does `vets-api` really have a documented naming convention or did they just simply pick convenient names for their purposes?

**Comment by mchelen-gov** [comment]
@olivereri Why not use the service name to identify CMS services within APM?

**Comment by cweagans** [comment]
@mchelen-gov We have a ton of environments when you consider each individual local + tugboat environment and it didn't seem like a good idea to pollute the list of applications with an entry for each of those (especially related to ephemeral environments like tugboat and local -- you'd essentially see a list of environments corresponding to every PR opened after APM went in + a local environment for each engineer).

Each application only shows the environments that belong to it though (e.g. brd-prod will only show when you're looking at the cms application and not vets api because vets api doesn't have any data for a brd-prod environment). Do we need to conform to another team's naming convention for stuff like this? It seems like this decision really only affects CMS engineers but I could be wrong.

**Comment by olivereri** [comment]
> @cweagans Generally we want keep consistent naming conventions to reduce confusion both within and outside each team. There is no "production" environment other than `brd-prod` so the `brd-` prefix is redundant.

For CMS or all applications on the wider platform? There's a split between platform apps on EKS and BRD. Is the EKS solution being branded as BRD?
