### ISSUE TITLE
Install Datadog APM components on local and CI environments

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8077]
## Background

The CMS team will be implementing additional monitoring in Datadog for better insight and analysis on application performance. APM will allow the team to proactively identify any anomalies or downward performance trends and resolve these issues quicker. APM will be installed in the local/CI environments first, tested, and then installed in production.

### Acceptance Criteria
- [x] Datadog PHP extension is installed in local/CI environments (Tugboat, ddev, lando)
- [x] Document how to configure the agent credentials: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=otherenvironments#configure-the-datadog-agent-for-apm

### Tasks

- [x] Install the Datadog PHP extension: https://docs.datadoghq.com/tracing/setup_overview/setup/php/?tab=otherenvironments#installation-and-getting-started
- [x] Ensure that each environment is identified separately in Datadog for filtering purposes
- [x] Rebuild the Tugboat base preview after making changes there!

### CMS Team
Please check the team(s) that will do this work. 

- [x] `Platform CMS Team`

**Comment by cweagans** [comment]
* Datadog extension should be zero cost (in terms of performance _and_ money) to have installed. It shouldn't be doing anything at all if the API key isn't configured.
* There is some extra overhead to modifying the Tugboat base image (since all the envs have to be rebuilt), so the ticket is a little bigger.

**Comment by cweagans** [comment]
Note that this depends on dogstatsd running, so installation of that component may be necessary as well.

**Comment by olivereri** [comment]
Amazon Linux Install:
```

DD_AGENT_MAJOR_VERSION=7 DD_API_KEY=e21aa8d73b3a48a8f82494bb91a096e7 DD_SITE="datadoghq.com" bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script.sh)"
```
https://app.datadoghq.com/account/settings?_gl=1*qk42rp*_ga*MjU3OTY0OTA2LjE2MjkxMzU0OTI.*_ga_KN80RDFSQK*MTY0NjI1MTAxMi4yMy4xLjE2NDYyNTIyNzEuMA..#agent/aws

**Comment by cweagans** [comment]
I started poking at this at one point. Here's what I did:

```
diff --git a/.ddev/.gitignore b/.ddev/.gitignore
index 9a3d2f0d..23628856 100644
--- a/.ddev/.gitignore
+++ b/.ddev/.gitignore
@@ -22,3 +22,5 @@
 /sequelpro.spf
 /xhprof
 /**/README.*
+!docker-compose.datadog.yaml.example
+docker-compose.datadog.yaml
diff --git a/.ddev/datadog/mcache.conf.yaml b/.ddev/datadog/mcache.conf.yaml
new file mode 100644
index 00000000..8d098888
--- /dev/null
+++ b/.ddev/datadog/mcache.conf.yaml
@@ -0,0 +1,7 @@
+# mounted at mcache.d/conf.yaml
+
+init_config:
+
+instances:
+  - url: memcached
+    service: vagov-memcached
diff --git a/.ddev/datadog/mysql.conf.yaml b/.ddev/datadog/mysql.conf.yaml
new file mode 100644
index 00000000..3a8990ac
--- /dev/null
+++ b/.ddev/datadog/mysql.conf.yaml
@@ -0,0 +1,12 @@
+init_config:
+
+instances:
+  - server: db
+    service: vagov-mariadb
+    user: root
+    pass: root
+    port: 3306
+    options:
+      extra_status_metrics: true
+      extra_performance_metrics: true
+      schema_size_metrics: true
diff --git a/.ddev/docker-compose.datadog.yaml.example b/.ddev/docker-compose.datadog.yaml.example
new file mode 100644
index 00000000..973d79e7
--- /dev/null
+++ b/.ddev/docker-compose.datadog.yaml.example
@@ -0,0 +1,29 @@
+version: '3.6'
+
+services:
+  datadog:
+    container_name: ddev-${DDEV_SITENAME}-datadog
+    image: datadog/agent:latest
+    restart: "no"
+    labels:
+      com.ddev.site-name: ${DDEV_SITENAME}
+    environment:
+      - DD_API_KEY=APIKEYHERE
+      - DD_TAGS=user:YOURNAMEHERE
+      - DD_LOGS_ENABLED=false
+      - DD_ENV=local
+    volumes:
+      - ".:/mnt/ddev_config"
+      - "./datadog/mcache.conf.yaml:/etc/datadog-agent/conf.d/mcache.d/conf.yaml"
+      - "./datadog/mysql.conf.yaml:/etc/datadog-agent/conf.d/mysql.d/conf.yaml"
+    links:
+      - web:web
+      - db:db
+      - memcached:memcached
+  web:
+    environment:
+      - DD_AGENT_HOST=datadog
+      - DD_SERVICE=vagov-cms
+      - DD_SERVICE_MAPPING=pdo:vagov-cms-pdo
+      - DD_PROFILING_ENABLED=true
+      - DD_TRACE_CLI_ENABLED=true
diff --git a/.ddev/web-build/Dockerfile b/.ddev/web-build/Dockerfile
index 53dc4597..0b7899ba 100644
--- a/.ddev/web-build/Dockerfile
+++ b/.ddev/web-build/Dockerfile
@@ -2,3 +2,4 @@
 ARG BASE_IMAGE
 FROM $BASE_IMAGE
 ENV PATH=/var/www/html/vendor/bin:/var/www/html/bin:${PATH}
+RUN sudo dpkg -i $(curl -w "%{filename_effective}" -LO $(curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases | grep browser_download_url | grep 'amd64[.]deb' | head -n 1 | cut -d '"' -f 4))

```

**Comment by olivereri** [comment]
#### Enabling Profiling
```
agile6@va-gov-cms-web:/tmp$ sudo php datadog-setup.php --enable-profiling
Searching for available php binaries, this operation might take a while.
Multiple PHP binaries detected. Please select the binaries the datadog library will be installed to:

   1. php --> /usr/bin/php7.4
   2. php-fpm --> /usr/sbin/php-fpm7.4
   3. php5.6 --> /usr/bin/php5.6
   4. php-fpm5.6 --> /usr/sbin/php-fpm5.6
   5. php7.0 --> /usr/bin/php7.0
   6. php-fpm7.0 --> /usr/sbin/php-fpm7.0
   7. php7.1 --> /usr/bin/php7.1
   8. php-fpm7.1 --> /usr/sbin/php-fpm7.1
   9. php7.2 --> /usr/bin/php7.2
  10. php-fpm7.2 --> /usr/sbin/php-fpm7.2
  11. php7.3 --> /usr/bin/php7.3
  12. php-fpm7.3 --> /usr/sbin/php-fpm7.3
  13. php7.4 --> /usr/bin/php7.4
  14. php-fpm7.4 --> /usr/sbin/php-fpm7.4
  15. php8.0 --> /usr/bin/php8.0
  16. php-fpm8.0 --> /usr/sbin/php-fpm8.0
  17. php8.1 --> /usr/bin/php8.1
  18. php-fpm8.1 --> /usr/sbin/php-fpm8.1

Select binaries using their number. Multiple binaries separated by space (example: 1 3): 13
Downloading installable archive from https://github.com/DataDog/dd-trace-php/releases/download/0.70.1/dd-library-php-0.70.1-x86_64-linux-gnu.tar.gz.
This operation might take a while.
...................
Download completed

Installed required source files to '/opt/datadog/dd-library/0.70.1'
Installing to binary: php7.4 (/usr/bin/php7.4)
Copied '/tmp/dd-install/dd-library-php/trace/ext/20190902/ddtrace.so' to '/usr/lib/php/20190902/ddtrace.so'
Copied '/tmp/dd-install/dd-library-php/profiling/ext/20190902/datadog-profiling.so' to '/usr/lib/php/20190902/datadog-profiling.so'
Copied '/tmp/dd-install/dd-library-php/appsec/ext/20190902/ddappsec.so' to '/usr/lib/php/20190902/ddappsec.so'
Updating existing INI file '/etc/php/7.4/cli/conf.d/98-ddtrace.ini'
Installation to 'php7.4 (/usr/bin/php7.4)' was successful
--------------------------------------------------
SUCCESS

To run this script in a non interactive mode, use the following options:
  php 'datadog-setup.php' '--enable-profiling' '--php-bin=php7.4'

```

**Comment by ndouglas** [comment]
I got distracted by a couple of other things, but this is my progress on Lando:

```diff
diff --git a/.gitignore b/.gitignore
index 9c271539..4c50e738 100644
--- a/.gitignore
+++ b/.gitignore
@@ -84,3 +84,6 @@ node_modules/
 # Ignore WEB (vets-website)
 # web
 # @TODO: Installer paths is not working. Leaving symlink for now.
+
+# Temporary .deb packages
+*.deb
diff --git a/.lando.yml b/.lando.yml
index 62fab5bd..30af29db 100644
--- a/.lando.yml
+++ b/.lando.yml
@@ -38,6 +38,7 @@ services:
       # cypress-axe dependencies - https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements
       - "apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y"
       - .lando/scripts/blackfire-init.sh
+      - dpkg -i $(curl -w "%{filename_effective}" -LO $(curl -s https://api.github.com/repos/DataDog/dd-trace-php/releases | grep browser_download_url | grep 'amd64[.]deb' | head -n 1 | cut -d '"' -f 4))
       - yes | pecl install memcache-4.0.5.2 && docker-php-ext-enable memcache
       - rm -f /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini
       - /etc/init.d/apache2 reload
@@ -85,6 +86,21 @@ services:
     type: memcached:1
     mem: 1024
 
+  datadog:
+    type: compose
+    app_mount: delegated
+    services:
+      image: datadog/agent
+      restart: on-failure
+      ports:
+        - "8126:8126/tcp"
+      command: /bin/entrypoint.sh
+      environment:
+        DD_API_KEY: ~
+        DD_ENV: ~
+        DD_HOSTNAME: ~
+        DD_APM_ENABLED: 'true'
+
   # Uncomment this to work on site build triggers, then export ENV vars below, then `lando rebuild`.
   # Must use lando 3.0.0-rc9+
   # @see /README.md Build Trigger section
```

h/t Cameron for the command to nab the `.deb`.  I'll figure out the actual plumbing of this tomorrow morning and hopefully have something working by scrum.

**Comment by ndouglas** [comment]
think this is working in Lando, more-or-less

<img width="1255" alt="Screen Shot 2022-03-09 at 10 42 50 AM" src="https://user-images.githubusercontent.com/1318579/157476359-d8f23d2a-dc56-4c9d-bcb4-f2f552024405.png">

**Comment by olivereri** [comment]
# Tugboat Configuration for Datdog Tracing

## steps
1. Retrieve CMS_CI_DD_APM_KEY from datadog API Keys.
1. Terminal in to Preview environment's PHP service container
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/1f1ae318-ac52-4959-8290-417d9b38a00b)
1. edit /etc/datadog-agent/datadog.yaml
1. Add retrieved api key to `api_key` field, e.g. `api_key: 'af6546846541354198dfa615'`
1. Restart datadog agent service `service datadog-agent restart`
