### ISSUE TITLE
Document how to access Datadog APM data for various CMS environments

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8078]
### Acceptance Criteria

- [ ] Document in Confluence how to access Datadog and how to pull the APM data 

### Tasks:
- [x] Write a new documentation page about how to access the Datadog APM data, including how to filter the APM data to one particular environment

### CMS Team

- [x] `Platform CMS Team`

**Comment by olivereri** [comment]
# How to Access Datadog (DD) Application Performance Monitoring (APM) Traces for CMS

## Reserved Tags

Unified service tagging ties DD telemetry together through the use of three reserved tags:

`DD_SERVICE`
`DD_ENV`
`DD_VERSION`

With these three tags you can:

- Identify deployment impact with trace and container metrics filtered by version
- Navigate seamlessly across traces, metrics, and logs with consistent tags
- View service data based on environment or version in a unified fashion within the DD site

## User Defined Tags
DD_TAGS sets custom tags in DD. Must be a list of <key>:<value> separated by commas such as: layer:api,team:intake.  Typically this is used for local environments sending APM traces to DD to differentiate them from Production and/or Production-like environments.

Example:
`DD_TAGS=user:myUserName,vacms:0000,branch:myBranchName`

## Searching Traces

### Services
Broadly a service groups together endpoints, queries, or jobs for the purposes of building your application. Services pictured below were automatically mapped by DD:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/61c3b753-4a79-4899-afa9-d59e3640ec72)

### Crafting a Search Query

To immediately start looking at traces for CMS production follow [this link.](https://app.datadoghq.com/apm/traces?saved-view-id=872506). 
DD APM for CMS is configured in deployment code to set the reserved tags as follows:

Production CMS:
`DD_SERVICE=vagov-cms`
`DD_ENV=brd-prod`
`DD_VERSION=`

Staging CMS:
`DD_SERVICE=vagov-cms`
`DD_ENV=brd-staging`
`DD_VERSION=`

Staging CMS:
`DD_SERVICE=vagov-cms`
`DD_ENV=brd-dev`
`DD_VERSION=`

Additionally, the DD Agent configuration remaps PHP Data Objects (PDO) default service name of `pdo` to `vagov-cms-pdo`. With these values in mind it's possible to filter on specifics environments and then services within the environment.

1. Browse to DD [Traces](https://app.datadoghq.com/apm/traces) page
2.
