### ISSUE TITLE
UI audit: right rail of node edit screens

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8090]
## User Story or Problem Statement

As an editor, i want consistency across screens.

As a designer, i want a tool to make design decisions about standards and variations on standards

## Acceptance Criteria
- [ ] A mural with screenshots of right rails
- [ ] Each screenshot is annotated with the content type name
- [ ] Anything that is visible only to admin is highlighted as admin only. You may need to have two sessions going, one as admin, and one with with a content editor that has access to the given content type. 
- [ ] You don't need to evaluate the differences across content types for now, i think we'll want some of the design system folks involved in that analysis. But we can discuss this as a next step. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@kevwalsh 
Here is the mural for this task: https://app.mural.co/t/vagov6717/m/vagov6717/1645206946380/82fd752c64947bf431107c080a28007dcdb6561a?sender=kevinwalsh8610

I'll put this ticket back on to-do and wait to get some feedback on what's in the mural.

**Comment by kevwalsh** [comment]
i'm going to bump this back to new/unrefined. it's a great start, but priority on getting this finished is unclear.
