### ISSUE TITLE
Move responsibility for kicking off content build to the CMS

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8108]
## Background

We've spent a lot of time figuring out how to deduplication build requests, coordinate between manual builds (when banners or status nodes are published) and scheduled builds, etc. Because this coordination is happening across two different systems, it's extremely complicated, fragile, and error prone.

Let's move the triggering logic out of the content build workflow into the CMS so that Drupal is entirely in control of when content build is triggered.

### Acceptance Criteria

- [ ] Add a cron job that runs every minute
- [x] Ensure builds are still requested at the top of the hour
- [x] Ensure builds are requested when an editor creates/updates banner or status nodes
- [x] Make sure we're saving timestamps somewhere for:
    * the last time the build was requested in the CMS, 
    * the last time the build request was processed (GHA API call was fired),
    *  and the last ~time the govdelivery callback notified us that the build was complete~ timestamp passed to us in the govDelivery callback.

### Tasks

- [ ] Debounce build requests so that we're not clogging up the GHA queue
- [ ] If there's a build request when the every minute tasks run, fire the GHA API request

In the future, we could look at:
* Run the builds more frequently (potentially back to back)
* Ignore manual build requests during business hours in favor of frequent scheduled/automatic builds and only allow manual builds to go through after hours
* Push events to Datadog when builds are requested + when build requests are processed

### CMS Team
Please check the team(s) that will do this work. 

- [x] `Platform CMS Team`

**Comment by swirtSJW** [comment]
I updated the doc for this to be more explicit
![image](https://user-images.githubusercontent.com/5752113/155345031-f068e024-c671-4832-8f11-e20b3f57d867.png)

[link to source](https://docs.google.com/drawings/d/1EamG8j7uyXmwTuGWoHQyD4L6Qkf8FTYhBil57RDEZAw/edit?usp=sharing)

**Comment by swirtSJW** [comment]
Benefits:
* No Queue processing or de-duping needed.
* System is self correcting.  If a request does not complete in a certain amount of time, it will try again.
* Leverages the Drupal State API
* State variables become the source of truth both for logic.
* State variables are available to surface in meaningful ways to editors
* State Counter could be added to Squeal loudly and surface to editors when too many requested content builds are not being delivered.   No more failing silently.

**Comment by cweagans** [comment]
@swirtSJW Thanks for the extra info here. One thing that this does not cover is retry at the _beginning_ of the process. We would not want to wait 40 minutes (or whatever) to retry if the API request at the beginning failed because that's a bad experience for editors. We should retry the API request ASAP and that's the place where a queue + [queue_unique](https://www.drupal.org/project/queue_unique) could be beneficial: if the API request fails, we can mark the item as failed and put it back in the queue to retry next time cron runs. This would be in addition to everything you specified in your diagram.

> I don't think there is a good case for keeping the top of the hour releases. I think we just update the build request time whenever a public page revision is published. That will make sure another one fires as needed. We get the effect of daisy chaininig them without any burden of it happening when there is nothing new to go out.

There's not a good case for top of the hour releases, but for now I think it's important to keep them so that we're not changing too much behavior at once because we'd still have to communicate this to a lot of people. If the first change that we make preserves the current _intended_ behaviors and eliminates the _unintended_ behaviors, that's a good first step.

**Comment by swirtSJW** [comment]
> Thanks for the extra info here. One thing that this does not cover is retry at the beginning of the process. We would not want to wait 40 minutes

Sorry I put this in before Tim's count list check came in.   We can add it to the check So that the 40min would not have to be the only fallback.

If  (QueuedTime > RequestedTime)  and    GHAqueueCount == 0)       then trigger.


No need to queue or queue unque.

**Comment by swirtSJW** [comment]
Also just for context.  We (cms team) is the one who asked for the top of the hour content releases.   I don't think anyone else really had any skin in the game on that one.

**Comment by cweagans** [comment]
Follow up tickets:

Now:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9008
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9010
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9014
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9015
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9016

Next:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9012
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9013

Later:
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6008 -- the broken link report was removed as part of 8108, but we should add it back in. Steve has some ideas about how we can better present that data. We need to make sure that it's available in a concise report on Tugboat and local environments in addition to whatever editor-centric stuff we do with that data.
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9009
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8796
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8849
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7600
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7727 (since the rest of the module was refactored in the PR for 8108, it would be nice to finish the refactor and get the environment handling stuff cleaned up)
