### ISSUE TITLE
VAMC editor are re-using VAMC System Banner Alert with Situation Updates

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8141]
## User Story or Problem Statement

Editors should not be  able to re-use an alert.  

Possible solutions:
A) When they unselect "published", the node gets deleted  (nuclear option... not ideal)
B) When they unselect "published",  that checkbox becomes disabled and replaced with a message that alerts can not be re-enabled.
C) When they unselect "published", edit is not possible (remove edit tab for non-admin)
D) When they unselect "published", save of edit is not possible (remove save button for non-admin)

## Acceptance Criteria
- [x] I expect after editors save a VAMC system banner alert with the checkbox published "unselected" THEN edit is not possible (remove edit tab for non-admin)
- [x] I expect there is a message on the screen for editors that persists, work with @BlakeOrgan and @thejordanwood  to craft exact copy for on screen message (or other designated CMS copy stakeholder)
- [x] I expect if the VAMC system banner alert has never been published THEN it can be published 
- [x] I expect screenshots are sent to @kmariepat-cityfriends for KB article update 
- [ ] I expect PR is not merged to main, but instead merged to integration branch as part of #14117 (aka: ticket can close without merged PR)

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by kmariepat-cityfriends** [comment]
Next Steps: put a message on the screen for editors

**Comment by kmariepat-cityfriends** [comment]
Requires KB article update to be completed by @kmariepat-cityfriends

**Comment by swirtSJW** [comment]
@thejordanwood and @laflannery  We are making a change to the logic of VAMC Full width Banners that will prevent editors from re-using them.   
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/59a7e547-957b-40ba-9d74-7717307037ae)

We are going to do that by removing the "Edit" tab at the top of the node once they un-publish the node.
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/4e7facc7-f876-42ef-9c5f-7a17a040b33e)

We want to have a system message at the top of the page that informs editors "Hey editors you can't edit this banner because it is already unpublished.  You will need to go make a new one."  but errr... say it better than that ;)
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/705213df-4ff9-40fb-99f0-1c7675f5bd68)

Can either of you assist with the language?

**Comment by laflannery** [comment]
@swirtSJW 2 questions:
- Will this message only appear when the workflow is Publish > Archive? Or would it happen anytime the node is Archived (i.e. Draft > Archive)?
- Can we put a link in the message?

**Comment by swirtSJW** [comment]
@laflannery 

> Will this message only appear when the workflow is Publish > Archive? Or would it happen anytime the node is Archived (i.e. Draft > Archive)?

That content type does not have workflow at all.  There is no draft or archived, there is only published or not published.
The edit tab will disappear (and the message appear) only when the node has been published and then unpublished.  After that, the message will sit there forever.

> Can we put a link in the message? If I wanted to link them to the create node page for example?  

We could put a link in it.  My  minor concern about putting a link to it is that it assumes they were there with intent to re-use it, so it assumes they want to create another one.  My other concern with putting the link there, is that now I have to sniff the user to see if they even have permission to create one and offer one message with a link if they do, and a different message if they don't.

**Comment by swirtSJW** [comment]
Solution notes:   I think we are going to have to use [node access grants](https://api.drupal.org/api/drupal/core%21modules%21node%21node.api.php/function/hook_node_grants/10)  to sole this because [hook_entity_access](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21entity.api.php/function/hook_entity_access/9.1.x) is not used in Views, which means someone could edit it by the operating links in a View.

**Comment by thejordanwood** [comment]
@laflannery Here's my pass at an error message for this. What do you think?

"This banner alert has already been unpublished, it can no longer be edited. Please create and publish a new banner alert."

**Comment by swirtSJW** [comment]
@thejordanwood  and @laflannery  I wonder about the 'Please create and publish a new banner alert.'  It is pretty prescriptive and gives the impression that they have to create a new one.   They only have to create a new one if they have to have one.

**Comment by swirtSJW** [comment]
> @swirtSJW Will editors only see this error message when they go to edit the alerts? I had assumed that they would be editing the alerts with the hopes to republish them, but is there a use case that I'm not thinking of?
> 
> Edit to clarify: My thinking was if the only use case was an editor trying to edit and republish the alert, then the only next step for them would be to create a new one.

@thejordanwood  they would see this warning whenever they see the node.   Viewing the node is the only option they have.  The "edit" option will not exist.

**Comment by thejordanwood** [comment]
@swirtSJW Thanks for the explanation! Maybe we could change to something like this:

"This banner alert has already been unpublished, it can no longer be edited. If a new notice is needed, please create and publish a new banner alert.”

**Comment by swirtSJW** [comment]
@thejordanwood I am a bit concerned about the naming of this.   We have a couple of products that fall under the "banner alert" category so we try to stick to the official names whenever possible and then we are adding in the term of "a new notice" which doesn't match any content types.

 Here is what just the first sentence looks like with the full product name.  It gets pretty long without using the if clause.
 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/71f413f0-cef6-4ac1-8ea5-e334f35d1887)


How doe you feel about either:
a) Simplifying the if clause: **This VAMC System Banner Alert with Situation Updates has already been unpublished, it can no longer be edited.  If needed, create a new one.**
b) Bypassing the if clause altogether and leave it non-prescriptive:  
**This VAMC System Banner Alert with Situation Updates has already been unpublished, it can no longer be edited.**

**Comment by thejordanwood** [comment]
@swirtSJW I agree that the full product name is a bit long. I'm fine with using option B to cut down on the copy and leave it non-prescriptive.

**Comment by mmiddaugh** [comment]
Noting this for our future selves...
We intended to prevent editors from reusing banners for a number of reasons, including the connection to Gov Delivery. However editors need to be able to add situation updates to published banners and may need to edit to address typos or fix broken links - presenting a loophole. Where possible, we're removing "edit" actions so that we don't advertise the loophole while preserving the ability for editors to edit for the previously mentioned reasons. We'll have to monitor to make sure editors don't use this as a workaround resulting in unintended consequences.

**Comment by swirtSJW** [comment]
@kmariepat-cityfriends Here are some screenshots for the related KB

warning 
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/d8355b65-6301-4665-85f3-d3a421d9231c)

Primary tabs without "Edit" tab
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/1981ad87-7028-46d3-8af9-0ab6aed90830)

Both
![image](https://github.com/department-of-veterans-affairs/va.gov-cms/assets/5752113/b60a0c2e-298e-4993-96b8-21c8ada2cfa1)
