### ISSUE TITLE
Node link report redirect alert could be more nuanced about impact to end users

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8145]
## User Story or Problem Statement

Node link report's "redirected link found" message reads
> Please update the following URLs to prevent the possibility of broken links in the future.

In some cases, the redirect might not just lead to a broken link, but could be a low quality experience.

In this example, the redirect does not actually provide the content promised in the link. 

<img width="1416" alt="Edit_VAMC_Detail_Page_About_us___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/155591554-70fae147-82fe-4c2a-8a0a-18be0bafc550.png">

Redirected links should be reviewed not only for the possibility of it becoming broken, but for the possibility that is not the intended destination. 

## Acceptance Criteria
- [ ] Redirect alert provides some additional guidance that accounts for possibility of bad destination. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by netboss** [comment]
@rachel-kauff 
Hi! I just started working on this, could it possible to get the correct (final) wording needed for this (referenced in the AC)? 
CC @kevwalsh

**Comment by netboss** [comment]
> @rachel-kauff Hi! I just started working on this, when you have a chance, could it be possible to get the correct (final) wording needed for this (referenced in the AC)? CC @kevwalsh

@rachel-kauff @kevwalsh 
Following up regarding above question.
