### ISSUE TITLE
Upgrade to Drupal 10.

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8159]
## Background

The next major version of Drupal 10 is expected to release in August (or perhaps December) of 2022.  

https://www.drupal.org/about/10

**Drupal 10 is planned for August 2022**

<img width="1184" alt="Screen Shot 2022-02-25 at 10 13 26 AM" src="https://user-images.githubusercontent.com/1318579/155755012-5a35f4c2-59e5-43db-b584-c25f67314026.png">

This might be equivalent to Drupal 9.4 or to 9.5, depending on eventual release date.

### User Story or Problem Statement

<As a _____, I need _____ so I can _____.>

_or_

<Problem description. How might we _____________ ?>

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
This is handled elsewhere. Close but not happening yet.

**Comment by EWashb** [comment]
related to #14245

**Comment by productmike** [comment]
Re: duplicate issue above, closing this.
