### ISSUE TITLE
Document audit tools best practices

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8177]
## User Story or Problem Statement

As a content manager, product team member, or content strategist, i want a consistent set of tools on content audit pages

As a drupal engineer, i want standards to follow when creating audit tools

## Acceptance Criteria
- [x] Standards are generated [in this mural](https://app.mural.co/invitation/mural/vagov6717/1635876790922?sender=u0213d96dd8b8c144f1f10284&key=3360aded-a676-4e8a-b5c3-610a9f72abfb) for review by other team members
- [x] Feedback sought out from Val, Kevin, Steve, Suzanne, possibly others.
- [x] Documentation created 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
I have created some draft documentation [here](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Content+Audit+Style+Guide) for creating views. I'm looking to get some input from @valerierunde @kevwalsh @swirtSJW @suzanne-gray if they are interested. 

This will serve as a baseline for all views. Once we finalize these, we'll create a follow up ticket to audit the audits and update them all to follow the standard.

**Comment by swirtSJW** [comment]
This all looks great @msbtterswrth  Nice work getting this going.  There are some minor things noted in the doc itself.    
On a bigger note.   There seems to be so much in this document that is not just specific to audits, but also to all our other Views in the admin/content section, which is exactly what we need.  Could this doc have a broader section that addresses Views up top, and then a section farther in that is more specific to Audits?

Also a nice plus would be a set of bullets that can be copied and pasted into issues as acceptance criteria.

**Comment by msbtterswrth** [comment]
@swirtSJW I think it's a great idea to document some basic views things at the top and then more specific things at the bottom. Can you help me with what you'd like to see there? Same thing with the ACs?

**Comment by kevwalsh** [comment]
@msbtterswrth there are a few comments still on the confluence page to incorporate.

**Comment by msbtterswrth** [comment]
@kevwalsh i see a few comments, but all the last ones are from me to you or swirt and require some feedback. I'll keep an eye on those :)

**Comment by kevwalsh** [comment]
Awesome work Lynn! Closing this, we'll continue to iterate.
