### ISSUE TITLE
Spike: CKeditor 5

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8178]
## User Story or Problem Statement

CKeditor 5 is an experimental module in 9.3

We believe that it may offer an improved UX, and allow new functionality to be added to our rich text editors. 

It also may have a complicated upgrade path. 

## Acceptance Criteria

- [x] We have documented a viable upgrade path for both rich text formats supported by the CMS, and any risk associated with these
- [x] We have investigated opportunities outlined in #1969, including
  - [x] Possibility for adding structured content widgets like phone number and address (useful outside of paragraphs)
  - [x] Improving the Styles dropdown for the "Rich Text"
- [x] We have explored, with screenshots (and/or in a PR environment?), what [the various options](https://ckeditor.com/ckeditor-5/online-builder/) might look like for each of the two rich text editors, so that design team can evaluate. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
I'm going to start adding some screenshots into this thread of things I find. 

![image](https://user-images.githubusercontent.com/8375335/156216096-87f3fbcb-d035-42a9-a81a-80b1b4e75abc.png)

**Comment by kevwalsh** [comment]
[From this google doc](https://docs.google.com/document/d/1m5Phyd6FgoKG7Gtfeitglxq4M_0qqPAOebW43seFEMU/edit#)

CKeditor 5 is an experimental module in 9.3, and is hoped to be shipped as a stable release in 9.4. CKe4 will be removed in 10 and replaced with CKe5. There are a number of steps that will need to occur before a stable CKe5 is released.


## Why upgrade?

1. CKeditor 4 will reach end of life by d10
2. Improved look and feel
    1. Cleaner
    2. Some nice bubbles
    3. Better accessibility
3. Possibility of new features
    4. Accessibility
        1. In-line accessibility tests (such as testing header levels)
        2. Tools for creating more accessible content like phone numbers and action links
    5. Semi-structured content
        3. Phone numbers
        4. Address blocks
        5. Others TBD


### Step 1: Get a stable drupal module

The current roadmap to a stable release can be found in this [drupal issue](https://www.drupal.org/project/drupal/issues/3238333). The most relevant current blockers are:



1. [#3222797: [upstream] Upgrade path from CKEditor 4's StylesCombo](https://www.drupal.org/project/drupal/issues/3222797)
    1. There is currently no styles dropdown. CKe had not intended on creating one for CKe5, but Wim has been working with them to support it. He has stated as recently as a week ago (late February 2022) that this module WILL NOT release without this functionality.
2. [#3194084: Support functionality equivalent to ckeditor_stylesheets](https://www.drupal.org/project/drupal/issues/3194084)
    2. Once this is merged, all styles will need to include “.ck-content” as a parent selector. (see item in step 2)
3. [ensure that sites can update from using CKE4 to CKE5 safely when using no contributed CKEditor modules](https://www.drupal.org/project/ckeditor5/issues/3201637) (this one has been satisfied, but they are [open to get more data](https://wimleers.com/blog/cke5-gcw))


### Step 2: Address technical debt in our existing CKeditor

Can begin immediately



1. Remove old img/media tags from allowable HTML tags (priority)
2. Consider changes to the Styles dropdown (optional)
    1. Consider removing Button style 
    2. Related to deprecating buttons: consider adding support for [Action links](https://design.va.gov/experimental-design/action_links)
    3. Consider the future of the address paragraph block
3. Consider removing the the “Convert URLs to links” filter (blocker to enabling CKe5)
4. There is supposedly a [drush command](https://www.drupal.org/project/ckeditor5/issues/3201637#comment-14092065) to audit text fields but i’m unable to get it working


### Step 3: Convert CKe4 to CKe5 in our drupal instance



1. Enable the CKe5 module
2. Edit each text format type and select ‘CKeditor 5’ from the dropdown
3. Disable the ‘convert URLs to links’ filter per the following screenshot. This is because fully qualified urls are now auto linked without an additional plugin


<img width="1237" alt="CKE_5 config page" src="https://user-images.githubusercontent.com/643678/157122354-547c9574-138e-4777-984b-5c51ab841cb4.png">


4. All styles will need to include “.ck-content” as a parent selector.
5. There’s currently no way to add a link target that I can see out of the box (is this important to us?)


### Step 4: Future state and next steps


1. There is an additional [module](https://www.drupal.org/project/ckeditor5_dev) which will help us create custom plugins such as phone number links, addresses or accessibility checkers
2. [this article](https://www.qed42.com/insights/coe/drupal/everything-you-need-know-about-ckeditor-5-integration-drupal-9) has some useful information about how to extend default cke5 to include other cke plugins including live spellcheck
3. CKe5 does not have all of the same plugins as CKe4, namely it’s accessibility checker. However, it appears that the[ editoria11y folks](https://github.com/ckeditor/ckeditor5/issues/1941#issuecomment-804519388) are working with cke5 to integrate something into core
