### ISSUE TITLE
Keep It Simply Static Data 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8198]
## Background

As a CMS developer working with external teams I need a way to share time synced data with external resources so that Web Apps can have reliable access to data that is managed by the CMS.

![image](https://user-images.githubusercontent.com/5752113/156169905-b8b6de39-4a66-4c99-ada0-fc23c0d67c44.png)

### Affected users and stakeholders
This initial build will directly support the following 

* Facilities App developers neeign access to Health Care Record system data
* FOM App developers

However, this data model has the capacity to support many more products, including our own CMS content-releases.

### Hypothesis

Slides: [History of needing KISS but not having it](https://docs.google.com/presentation/d/1h5BKiVCvw_K6vWH8xn4crjHnLV7ax0L1bVLWI8EWTdg/edit?usp=sharing)
[Diagram](https://docs.google.com/drawings/d/1bx-kyoAmNjtReu8turBIOokyEpW7TCi9fTjxMr6-mfw/edit?usp=sharing)

We believe this architecture is a simple and reliable solution for delivering time synced data to multiple consumers and at the same time, supporting the concept of open data.

## Assumptions
* KISS can immediately support providing health care record system data to facility app developers (VAMC facilities)
* KISS can immediately support the FOM app developers (office product)
* Data provided will be through core drupal json API (not GraphQL)

## Acceptance Criteria
- [ ] Static data about Electronic Health Record systems is made available to VAMC related app developers
- [ ] The system can support additional static data sources in a scalable and easy to implement fashion.
- [ ] Documentation about how to add a new data source endpoint.
- [ ] Failure to build an endpoint results in a build blocking error.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@jilladams can I remove the sitewide label on this?

**Comment by jilladams** [comment]
That may be a question for @swirtSJW ? Looks like Kev originally added it, maybe with the idea that Sitewide CMS is the owner of this kind of high level data system?

**Comment by EWashb** [comment]
@swirtSJW do you have any insight on this?

**Comment by ryguyk** [comment]
@EWashb This having been implemented by me on behalf of the Public Websites team was - even at the time - a sort of interesting thing. It is very arguably _not_ a Sitewide responsibility, but we needed it and implementing it within the context of the first use case seemed appropriate. 

I have no complaints with the Sitewide label being removed. That said, I'm curious if there are plans to do more with this, or if there is something else triggering the proposed cleanup. I'm happy to help in either case in any way I can.

Thanks!

**Comment by EWashb** [comment]
@ryguyk just cleaning up, and no other reason to be asking these questions. I may just icebox this for now and we can leave it as is.
