### ISSUE TITLE
[EPIC] Automatically archive past events after 1 month

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8231]
## Status
**[2025-02-12]** [Jill] Past Events are no longer shown on Event Listing pages in the FE. In Drupal, they still exist, and they still get pages built in Next build, so are still a load on the build system until we explore auto-archiving.
**[2024-08-16] [Fran]** Although we have another ticket to hide past events from the Frontend, we believe this ticket will still be needed (and need to be edited) in order to keep past events from being returned during searches. To be edited/groomed at a future date.

### User Story or Problem Statement

As of February 2025, there are [11372 events](https://prod.cms.va.gov/admin/content/events) on VA.gov managed by the CMS
* 3366 had been added to https://www.va.gov/outreach-and-events/events/ 
* the rest to VAMCs 
* Events may be rolled out in the future to other products, including Vet Center / VBA
* About 100 events are being added per month to va.gov
* By archiving 1000 events that were older than 6 months, on March 1, the content release sped up by five minutes. 

### User stories

As a Veteran, i don't want to accidentally happen across past events, which are mostly likely useless to me. (we think)

As an editor, i want my content to go out quickly. 

As a content release engineer, i don't want to deal with an infinite number of events. 

### Affected users and stakeholders

**Editors**
* VAMC editors
* Outreach hub editors (VEO)

**Business partners**  
* VHA Digital media (VAMC event calendars)
* VEO office that owns the outreach events

**Engineers**
* Content release engineers

**Content admins**
* Those who must manually archive content periodically to prevent bloating of content in the content build.

**Veterans / Other Users**
* People looking for events, and being confused by seeing past events, or not paying close attention and attempting to attend an event that already happened

### Hypothesis

We believe that automatically archiving events after 3 months will 
1. improve Veteran experience by reducing content clutter on VA.gov
2. prevent the slowdown of content releases 
3. reduce content clutter and improve content findability in CMS

We may want to _delete_ really old events, X months/years after they are archived, but that will be considered in a separate initiative. Specific laws (Federal Records Act (44 U.S.C. 31) and corresponding Code of Federal Regulations (CFRs) that we need to comply with). 

### Phase 1: Discovery
- [ ] #4214 (8)
- [ ] We've captured the above inputs into a set of ACs for implementation (as a team)
- [ ] #8236 
- [ ] We have designed a change management plan (timeline, warning/awareness email to editors, follow up with editors after the change) 

### Phase 2: Design/implementation

- [ ] Event node is automatically archived 3 months after its end date  
  - [ ] For recurring events, use the end date of the last event instance 
  - [ ] Archive setting can be relatively easily changed (say, moved to 6 months) 
  - [ ] How might we provide options for auto-archiving (say, be default), vs allowing events to persist on a case-by-case basis. 
  - [ ] How might this relate to other scheduling user stories (like scheduled publishing news releases or stories)
  - [ ] How might notifications fit into this
- [ ] CMS editors understand this setting/policy, and why it exists
  - [ ] UI on /node/add/event form is updated (if deemed necessary)
  - [ ] Knowledge base article for event is updated  (if deemed necessary)
  - [ ] Training is updated  (if deemed necessary)
- [ ] VA.gov front-end Event listing template (Next-build) is updated to reflect any changes, as needed

**Comment by jilladams** [comment]
Per today's PW Events scrub with Dave, he flagged 3 things: 
1. The driver of content build times is not the correct driver -- that's a developer problem, not a veteran problem.
2. There is federal regulation around records preservation that should factor in to path forward on this change. We should not remove pages from the web unless they provide outdated content and are not valuable for historical purposes, if less than 3 yrs old. 
3. Then: let veteran experience decide. Now that V2 filters are shipped, we can reference analytics to understand if the hypothesis in ticket bears out ("i don't want to accidentally happen across past events, which are mostly likely useless to me. (we think)")

Per Dave, Iceboxing until we can demo that it's a problem for vets.  @EWashb I'm stepping into your lanes here, so if this ticket needs a companion discovery ticket to work out the spelunking for data, I'll leave that to you!

**Comment by EWashb** [comment]
@jilladams can you keep me updated when you get more info on the problem space? If it does happen to be an issue we would be happy to support PW in getting the data.

**Comment by jilladams** [comment]
Will do!

**Comment by mmiddaugh** [comment]
@jilladams is this still valid? If so, should it belong to Facilities or Public Websites?

**Comment by aklausmeier** [comment]
@FranECross @mmiddaugh Should this be a fast follow to #9474

**Comment by aklausmeier** [comment]
@bethpottsVADEPO FYA

**Comment by FranECross** [comment]
@aklausmeier We were talking about not using content build for Events v3, so I'm not sure this is still needed, since it seems the main impetus was to speed up content build? @mmiddaugh @dsasser Opinions?

**Comment by aklausmeier** [comment]
@FranECross Depending on direction we go with Events v3 (timing and structure), we should discuss how past events are not only hidden on detail pages but also when searching, the auto archive would solve for this regardless of infrastructure and we could revise this ticket as needed. I think the need is there regardless of content build.

**Comment by FranECross** [comment]
Confirmed that past events are not returned in the FE when searched for prior years. Fran to create a ticket to disallow users from searching using prior years in the Year field. Closing as a no op.

**Comment by jilladams** [comment]
@FranECross I'm gonna reopen bc the Drupal Events are still published, and next-build still creates pages for them, so it's still aload on the build system, even if Veterans can't interact with these pages anymore.

You can't find them in the FE unless you use on-site search -- they're not visible from Event listing pages, but e.g.: https://www.va.gov/search/?query=coffee&t=false will still return the old event listings from 2023, until we archive those Events. 

New events created will also stay published until we establish a Drupal-side fix to auto-archive them / prevent pages from getting created. So we'll still want to explore this with CMS team. 

![Image](https://github.com/user-attachments/assets/761a0c69-df28-4253-8e5d-89c9604c8c85)

![Image](https://github.com/user-attachments/assets/f3ac2ed3-c3ce-40d9-8289-13e6fe015fb8)
