### ISSUE TITLE
Prevent editing of VAMC system banner decorative images

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8233]
## User Story or Problem Statement

As a Veteran that uses a screen-reader, i want to be able to access all content.

As a Veteran with low-sight, i don't want images with text baked in, because they are hard to read. 

As a Veteran, i want consistency across VAMCs.

<details><summary>www.va.gov Screenshots</summary>

How it's supposed to be used

<img width="1200" alt="VA_Pittsburgh_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/156618425-41dc7e9a-f62b-4a6e-835d-a57ddf5ec47d.png">

How it's being used

<img width="1440" alt="VA_Puget_Sound_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/156618289-0d7c3ae7-aea4-4ed0-a6da-b1034757f3d2.png">

</details>

<details><summary>Current banner editing experience</summary>

<img width="880" alt="Edit_VAMC_System_VA_Puget_Sound_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/156619084-9cc7d455-2190-4c1d-bd55-3fab3afb13c4.png">

<img width="871" alt="Edit_VAMC_System_VA_Pittsburgh_health_care___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/156619161-261917e4-329b-4a12-b449-941ac36c97e5.png">

</details>

## Acceptance Criteria

- [ ] Image can only be edited by content admin
- [ ] UI on VAMC system form is updated to use one of the patterns for content that can't be edited, instructing user to contact CMS help desk (attach an image? or send subsequently). 

## Implementation steps
- [ ] Design editorial experience for VAMC system decorative images. (we may want this design to work for Vet Centers in the future, which also considered the need for centrally-managed photos of Vet Center facilities) 
- [ ] Implement editorial experience for VAMC system decorative images.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@Agile6MSkinner I would recommending closing the remaining ticket as not planned and close this epic

**Comment by Agile6MSkinner** [comment]
Done
