### ISSUE TITLE
Content audit tool: "Prepare for your visit" accordions in VAMC product

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8298]
## User Story or Problem Statement

As a VAMC product team member, i want to evaluate the content in the Prepare for your visit accordions on VAMC facility pages

## Acceptance Criteria
- [x] display machine name should not be default
- [x] limit to 100 per page, paginated
- [x] show result count in header
- [x] default sort is last update (newest at top)
- [x] Menu item: Add as a child to the Facilities view
- [x] Relationship "field_location_services" to its paragraph
- [ ] Fields
  - [x] Title (sortable) 
  - [x] Edit button  
  - [x] Moderation State
  - [x] Section (field_administration) (sortable)
  - [x] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] Facility
  - [x] Accordion header field from `field_location_services` paragraphs
- [ ] filters
  - [x] Content type: VAMC facility (not exposed)
  - [x] "Accordion label contains" searching text contains on Accordion header
  - [ ] Facility (exposed)
  - [x] moderation state (exposed)
  - [x] section (exposed) (workbench access section; single select, show children)
  - [x] Reset button exists
  - [x] Apply button says 'filter'
- [x] CSV export that respects the filters.

## Implementation steps
Views config

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
@kevwalsh curious why we need the facility column, if we're already filtering out all content types except facilities, shouldn't the title then be the facility name?
