### ISSUE TITLE
Update to CKeditor 5

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8308]
## Background
The spike in #8178 led to this understanding.

### Why upgrade?

1. CKeditor 4 will reach end of life by d10
2. Improved look and feel ([see demo](https://ckeditor.com/ckeditor-5/demo/#classic))
3. Better accessibility
4. Possibility of new features
    1. Accessibility
        1. In-line accessibility tests (such as testing header levels)
        2. Tools for creating more accessible content like phone numbers and action links
    2. Semi-structured content
        1. Phone numbers
        1. Address blocks
        1. Others TBD

## User Story or Problem Statement

CKeditor 5 is an experimental module in 9.3, and is hoped to be shipped as a stable release in 9.4. CKe4 will be removed in 10 and replaced with CKe5. There are a number of steps that will need to occur before a stable CKe5 is released.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### Step 1: Get a stable Drupal module

The current roadmap to a stable release can be found in this [Drupal issue](https://www.drupal.org/project/drupal/issues/3238333). The most relevant current blockers are:

1. [#3222797: [upstream] Upgrade path from CKEditor 4's StylesCombo](https://www.drupal.org/project/drupal/issues/3222797)
    1. There is currently no styles dropdown. CKe had not intended on creating one for CKe5, but Wim has been working with them to support it. He has stated as recently as a week ago (late February 2022) that this module WILL NOT release without this functionality.
2. [#3194084: Support functionality equivalent to ckeditor_stylesheets](https://www.drupal.org/project/drupal/issues/3194084)
    2. Once this is merged, all styles will need to include “.ck-content” as a parent selector. (see item in step 2)
3. [ensure that sites can update from using CKE4 to CKE5 safely when using no contributed CKEditor modules](https://www.drupal.org/project/ckeditor5/issues/3201637) (this one has been satisfied, but they are [open to get more data](https://wimleers.com/blog/cke5-gcw))

### Step 2: Address technical debt in our existing CKeditor

Can begin immediately

1. Remove old img/media tags from allowable HTML tags (priority)
2. Consider changes to the Styles dropdown (optional)
    1. Consider removing Button style 
    2. Related to deprecating buttons: consider adding support for [Action links](https://design.va.gov/experimental-design/action_links)
    3. Consider the future of the address paragraph block
3. Consider removing the the “Convert URLs to links” filter (blocker to enabling CKe5)
4. There is supposedly a [drush command](https://www.drupal.org/project/ckeditor5/issues/3201637#comment-14092065) to audit text fields but i’m unable to get it working

### Step 3: Convert CKe4 to CKe5 in our drupal instance

1. Enable the CKe5 module
2. Edit each text format type and select ‘CKeditor 5’ from the dropdown
3. Disable the ‘convert URLs to links’ filter per the following screenshot. This is because fully qualified urls are now auto linked without an additional plugin

<img width="1237" alt="CKE_5 config page" src="https://user-images.githubusercontent.com/643678/157122354-547c9574-138e-4777-984b-5c51ab841cb4.png">

4. All styles will need to include “.ck-content” as a parent selector.
5. There’s currently no way to add a link target that I can see out of the box (is this important to us?)

### Step 4: Future state and next steps

1. There is an additional [module](https://www.drupal.org/project/ckeditor5_dev) which will help us create custom plugins such as phone number links, addresses or accessibility checkers
2. [this article](https://www.qed42.com/insights/coe/drupal/everything-you-need-know-about-ckeditor-5-integration-drupal-9) has some useful information about how to extend default cke5 to include other cke plugins including live spellcheck
3. CKe5 does not have all of the same plugins as CKe4, namely it’s accessibility checker. However, it appears that the[ editoria11y folks](https://github.com/ckeditor/ckeditor5/issues/1941#issuecomment-804519388) are working with cke5 to integrate something into core 

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Added CM triage section.

**Comment by ContentBrewmaster** [comment]
Added newest CM criterion: - [ ] Noticeable performance improvements (publishing speed, predictability)

**Comment by ContentBrewmaster** [comment]
Added epic template sections, reorganized previous content into sections and applied change management criteria.

**Comment by EWashb** [comment]
CKeditor5 is not slated to be released until Q4 2022.

**Comment by EWashb** [comment]
As we prepare for Drupal 10 upgrade, we need to start this prior to that work. May need to prioritize this prep initiative early Q1 2023 so that we have time to address CK4 tech debt and prep for CK5 rollover.

**Comment by ndouglas** [comment]
Not even a little.  Absolutely clueless.

**Comment by EWashb** [comment]
Found this: [CKEditor 5 is now a stable core module](https://www.drupal.org/node/3308362)

**Comment by ndouglas** [comment]
Yeah, we need to update to Drupal 9.5 as part of the Drupal 10 process.  I looked for a ticket and didn't find one -- and then remembered that [when I created this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8159), it was still up in the air whether Drupal 9.4 or 9.5 would be equivalent to Drupal 10.

If you don't know, and to clarify for the benefit of anyone else who wanders into this thread, Drupal's release system now is completely different from the one they had prior to Drupal 8.  Drupal 8.9 and Drupal 9.0 were essentially the same code, with the exception being that code that was deprecated in Drupal 8.9 was completely removed in Drupal 9.0.  (And I believe some minimum requirements are changed.)

Similarly, Drupal 9.5 and Drupal 10 are essentially the same, except anything deprecated as of 9.5 is not present in Drupal 10.

So it's definitely important for us to upgrade to Drupal 9.5 as an intermediate step; it's expected to be about as significant as a normal minor version update (so not a huge deal, but some possible aggravation).  The nice thing is that we can evaluate CK5 and CK4 from a position of comparative leisure, rather than as part of the 9.4 -> 9.5 update or the 9.5 -> 10.0 update.

**Comment by ndouglas** [comment]
Opened #11614.  This would be fine to block on that issue.  I don't personally think it's necessary to start investigating Drupal 9.5 _yet_, but we could take a gander, just to check the state of CK5 and if there are any immediate nightmares that pop up in casual testing.

**Comment by EWashb** [comment]
@productmike updating to CKeditor5 is a known priority for Q3 along with with launch of D10. We should bring this up for refinement at the next available opportunity. I think this is another epic that has slipped through the cracks, but I'm sure we still have time to think about this and address any other CKeditor items prior to #14245. I'll move ahead to the top of the requirements definition pipeline although some of this is already in progress

**Comment by productmike** [comment]
Sure @EWashb -- it looks like there are 1-2 tickets left in this epic. Are there additional you're thinking or primarily concerned with prioritizing those remaining tickets in this epic?

**Comment by laflannery** [comment]
@EWashb I want to close this - There are 2 tickets left in here but they are also in [the other epic](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1969) you wanted me to check. And this is being done already in D10 so I don't really see the point in keeping this open any longer?

**Comment by EWashb** [comment]
Agreed. I'll close this @laflannery
