### ISSUE TITLE
Lower deployment_volume_size: 250

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#8317]
We had the deployment_volume_size set to 250 when we were doing things around JSON file export for the transfomers publishing initiative. We since switched back to EFS and don't have that need anymore. This will save money and instance volume creation time, which should marginally affect deploy times in a positive way, not sure it is worth measuring though. 

### Tasks:
- [ ] Lower the deployment_volume_size from 250 to something lower

### CMS Team
Please check the team(s) that will do this work. 

- [x] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
