### ISSUE TITLE
Remove support for _italics_ in rich text

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8319]
## User Story or Problem Statement

Italics are [not supported by the VA Content style guide](https://design.va.gov/content-style-guide/bold-text#:~:text=Note%3A%20Don%E2%80%99t%20use%20italics.%20It%20doesn%E2%80%99t%20show%20up%20well%20on%20a%20screen%2C%20and%20sometimes%20it%20can%20be%20harder%20to%20read%20than%20normal%20text.)

> Note: Don’t use italics. It doesn’t show up well on a screen, and sometimes it can be harder to read than normal text.

Currently, both rich text editors support them. 

There are several technical steps, which can be done all at once, or separately, depending on the strategy
* remove the button in the CK editor
* remove support in the Allowed HTML tags. 
* remove all `<em>` tags in the existing content. 

It's best to do all three steps at once, but that decision should be guided by the change management strategy.

We may want to roll out this change with another rich text change, like the upgrade to Ckeditor 5 #8308

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [x] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.
 
## Acceptance Criteria
- [ ] We have a change management strategy that aligns with other changes to rich text editors
- [ ] Possibly: improve content style guide guidance for how to create empahsis in content without italics? 
- [ ] All `<em>` tags are removed from existing rich text content (OR, possibly, grandfathered in). 
- [ ] Italics button is gone from ckeditor
- [ ] `<em>` is removed as an allowed html tag in rich text

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ContentBrewmaster** [comment]
Added CM triage

**Comment by EWashb** [comment]
@laflannery @productmike this might be duplicative of other recent tickets created. The ACs are interesting and possibly valid to include in the new work, but what say you about closing?

**Comment by laflannery** [comment]
@EWashb I definitely meant to close this epic once this last ticket was closed so I will now.

Regarding the ACs:
- I like the one about the style guidelines and emphasis so I added it to my changement (new word!) ticket
- All the others are about the implementation of how to remove italics and it's all going to happen automagically because of CkEditor 5 so we shouldn't need these. The button will be removed, the`<em>` tag won't be allowed, etc. so these are all going to be covered just with the fact that we are doing this
