### ISSUE TITLE
Content Ops - Sprint 54

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8322]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

- Steve OOO Mar 14-18
- Kevin in DC Tues/Wed and travelling part of Monday and Thursday
- No backlog refinement Thursday

## #1956 Recurring events (Ethan, Kauff)

- [ ] Launch, in concert with FE defects for V2
  - [ ] Should we wait for Steve to come back? 
- [x] #6073

## #7593 Change management framework 
- [ ] #7807 🥅
- [ ] #8015 - Review with VHA, then socialize. 
- [x] #7797
- [x] #7798 

## #4799 VAMC Care we provide (Denise, Jay, Kevin, Steve)

- [ ] #7656 (Denise to communicate with VHA DM)
- [ ] Training and KB

## #4856 Better monitoring upstream data changes

Possible refinement, week of March 18
- [ ] Redefine Notifications MVP 

## #7612 Audit tools improvements 

- [ ] #6645 (part of  #2932)

## Other

- [ ] #6935 Lynn/Kev
- [ ] #7963 and/or #8167 (Ethan)
