### ISSUE TITLE
"Drupal spec tool"  in google sheets --> MVP "Content model documentation" in airtable

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8324]
## Problem statement

The primary purpose of the drupal spec tool is content model documentation, and we make sure it is kept up to date with behat tests. 

But we also have used it for auditing and designing iterations , particularly the Bundles tab, where we have documented the following types of config or governance

* Audited metatags for configuration and designed new specs
* Documented URL patterns 
* Permissions “Who can archive what content type”
* Which bundles have stand-alone URLs on VA.gov 
* Sample CMS and sample Web URLs

<details><summary>Screenshot of various config and governance</summary>

<img width="2931" alt="VA_gov_Drupal_Spec_Tool_v2_0_0_-_Google_Sheets" src="https://user-images.githubusercontent.com/643678/157997156-157f2fcb-1fa2-4ecb-a3c7-61bd601c26a2.png">

</details>

We have also often exported drupal spec tool into airtable for various types of analysis, including mapping content types to products on CMS product sheets. 

Google sheets has worked, but has had some major limitations

* Macros have character count limits that required us to split out fields into different content types, which is an anti-pattern, since many fields are used in more than one product. 
* We can’t produce reports or views of the data specific to certain problems. For example
    * the Bundle table could have Metatag specific views for documenting patterns and designing iterations. 
    * We can’t sort without breaking behat tests
    * We can’t add images (like metatag visualizations) or files
    * We can’t easily link out to our source of truth 

New things we would like to document in our content model documentation

* Visuals (eg, screenshots, not well supported by Google sheets)
* CMS design system components
* design decisions
* Help text
* Fieldgroups
* related KB articles
* some of the items noted in the [this confluence page](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1712390155/Accordion)

## Hypothesis

We believe that Airtable is a better tool than Google Spreadsheets for documenting the design decisions, opportunities, metadata, governance, and other information about the Content model. 

We'll know this to be true when 
* All existing functionality provided by Google sheets is replicated, particularly behat tests
  * We can validate that Engineers are able to use it as effectively as they could in google sheets
* we have positive feedback from about various forms of prototype documentation, including some of the following. 
  * IA documentation about bundles (pathauto, sample URLs, breadcrumb, etc, eg for Mikki)
  * fields tested by behat (for engineers)
  * CMS design system component views/reports (for CMS design system folks)
  * VA design system (eg, which content model components can be mapped to VA design system components)
  * Product specific views (eg VAMC) 
  * metadata documentation for bundles (for product teams)

## Runbook

- [x] Replicate functionality of google sheets
  - [ ] Validate that other engineers can use it to create behat tests
- [x] Prototype new documentation and validate it with their respecitive audiences
  - [ ] Validate utility of prototypes with the respective audiences 
- [ ] Possibly import (or just sync) [the Products table](https://airtable.com/appA1Lf2Iwv4XT3vU/tblFDPzooEhiRdJZb/viwhvxcAy0hN0jSWD?blocks=hide) and [the Sections table](https://airtable.com/appA1Lf2Iwv4XT3vU/tblTEw5LHLaOB5o3A/viwfb1Pwkp8U9QyFI?blocks=hide), although the latter is dated and we may want to just start fresh. 

## Not in MVP

Combine fields tests into one test - https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8586

Possibly ditch behat tests and sync drupal to airtable semi-regularly (upon merge?), while also allowing speccing out of new content model
