### ISSUE TITLE
VAMC facility "Prepare for your visit" content model hardening

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8325]
### User Story or Problem Statement

"Prepare for your visit" is a prominent part of the VAMC facility content design. 

It provides critical information for Veterans about parking, transportation, and some nonclinical services such as Chaplaincy. 

Current state in CMS
* there is no governance or standardization of this content, and some facilities have accordions that have drifted from the MVP design. 
* accordions allow full html, not limited html, which introduces the potential of accessibility errors with bad headings

<details><summary>Veteran experience</summary>

<img width="821" alt="Baltimore_VA_Medical_Center___VA_Maryland_Health_Care___Veterans_Affairs" src="https://user-images.githubusercontent.com/643678/157998242-4d993b90-36b9-4788-bba9-54ee22d926ac.png">

</details>

<details><summary>Editor experience</summary>

<img width="824" alt="Edit_VAMC_Facility_H__John_Heinz_III_Department_of_Veterans_Affairs_Medical_Center___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/157998442-ee56fae3-91d3-408a-a4ab-163bbfa98b65.png">

</details>

### Affected users and stakeholders

* Veterans preparing to visit a facility
* Editors managing content about a facility

[Some research on parking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/facilities/medical-centers/pittsburgh-pilot/content/content%20artifacts/Pittsburgh%20parking%20info%20research.pdf)

 
### Hypothesis

We believe that there are opportunities to 
* improve the the Veteran experience by standardizing it and ensuring key information is available
* improving guidance and governance of the content in ways that facilitate the editor experience
* structure the data so that it can be more easily consumed by multiple consumers

## Acceptance Criteria
- [ ] TBD

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`
