### ISSUE TITLE
Audit italics usage in rich text editors

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8327]
See #8319 for background. 

## User Story or Problem Statement

Before we remove support for italics in the two rich text editors, we need to understand what impact this will have on existing content and content editors, so that we can plan a change management strategy for this change. 

## Acceptance Criteria
- [x] We have a tool for analysing use of italics on CMS-supported pages. it doesn't have to be a drupal view, could be a crawl of www.va.gov sitemap. 
  - [x] the tool provides an export of results
  - [x]  it would be nice if the results did not appear in a modal, but on a full page.
  - [x] stretch the tool can filter results by html tag type
- [x] any patterns that may help our change management team think through the impact of this change for editors (for example, it's mostly on VAMC Detail pages, or it's mostly added by a certain editor) 

## Implementation steps
TBD 

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
I have exported the data from the new module we installed and created an [airtable](https://airtable.com/appsl8nrMBaj2xkeX/tblBL6xzHyc6G5VYk/viwV3zUJSTZvLy5je?blocks=bipS8wfEIaYFSQEBX) in which I'm synthesizing the use of ems.
