### ISSUE TITLE
Iterate VA.gov homepage changes for demo/testing in publicly accessible environment

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8340]
## Background

Ryan Thurlwell designed updates to the VA.gov home page that aspires to improve the Veteran visitor experience in several ways. 

### User Story or Problem Statement

Let's build the new model out quickly to rally stakeholder support and help provide a rationale and path for these changes in production.

### Proposed schedule as of Q4 2022
Updated: **9/19** (Michelle) 
_after Prototype build, we are blocked pending meetings scheduled for 10/19 and 10/20 with Web Governance Board and Digital Modernization Council_

Date | PW Sprint | Activity | Owner
---  |  --- | --- | ---
9/12 | 67 | V2 Design iteration for round 2 UAT | Ryan T
_Complete 9/15_ | 67 | Finalize copy | Danielle + Ryan T
TBD | 67 | Punchlist for links | Michelle? | 
TBD | 67 | Midpoint review (async Collab Cycle) | Michelle
9/23 | 67 | V2 Prototype build iteration | PW
10/11-10/17 | 69 | Dave / Ryan T OOO | |
10/19, 10/20 | 69 | Meetings with Web Governance Board (WGB) and Digital Modernization Council (DMC) | 
~10/24-10/31  | 70  | V2 Usability research | Cindy
~11/? | 70  | V2 Usability research readout for design | Cindy
~by 11/11 | 71 | V3/Final design for launch incl mobile | Ryan T
~11/23 | 72 | V3 Build updates for launch incl Drupalization | PW
11/24-25 | 72 | Thanksgiving | All
TBD |  | QA testing | AdHoc?
TBD | | Staging review & testing | PW
TBD | | Release to prod | PW
12/26-30 | 74 | Christmas holiday, probably reduced staffing | All

Per discussion with @davidconlon  / Michelle on 8/23: prod release may/will likely be the hard-coded prototype, with Drupal/data hooked in as a fast follow. 

We can start the Drupal work in October after V3/Final designs are delivered, but unclear until we know scope of changes whether we can achieve fully drupalized site for Nov launch.

### Affected users and stakeholders

Veterans

### Hypothesis

Goals are TBD

## Assumptions
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [x] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
@mmiddaugh, I pruned redundant stories, although we may learn that the "implement search" story is redundant also.
Also, FYI, in planning yesterday we determined that the most expedient definition of "pencils down" is to actually merge the code and make it available on staging. #8811 now reflects this, with destination URL at /homepage-test. This url is open to change until implementation, in case you have any concerns.

**Comment by jilladams** [comment]
Target timing for Round 2 UAT / launch: 
https://github.com/department-of-veterans-affairs/va.gov-team/issues/40845#issuecomment-1224566198

- Stakeholder discussions, Web Governance Board, and Digital Modernization Council
- Adjustments to ensure critical analytic baselines can be measured with current design
- Usability synthesis report (Cindy) 
- Usability to Ryan T on ~8/29
- Findings presented across teams by 9/8 (Cindy)
- [Discovery: Existing Homepage content model and how to leverage for new design #10302](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10302)
- Iteration on design (Ryan) - complete by 9/12 (regular check-ins with Ryan, PW, Cindy) - **[Design>Eng handoff]**
- Midpoint review (async Collab cycle)
- Punchlist for links
- Engineering for iterations (PW) during Sprint 67 (ends 9/23) - **[Eng delivery]**
- Usability research (Cindy) - conduct week of 9/26, wrap up sessions by 9/30, synth by October 7
- Tweaks to design - date TBD **[Design>Eng handoff]**
- Tweaks to engineering (based on above) - by Oct 24/31 **[Eng delivery]**
- Staging review (check on length - in staging week of Oct 24/31)
- Release to prod (full cutover, same url) - 11/7-11/10 launch window **[Eng delivery]**
  - Fri 11/11 Veterans Day = holiday

Note: prod release may/will likely be the hard-coded prototype, with Drupal/data hooked in as a fast follow.

**Comment by jilladams** [comment]
Note from Dave sync:
* PW should work with @mmiddaugh & @cindymerrill & RyanT to "heatmap" the current designs for which portions are firm/firmish, and which may potentially change between round 2 UAT & Nov launch. This will help inform where PW can invest time now to get Drupal data ready.
* If for some reason full Drupal implementation can't be ready for Nov launch, strong preference to be able to manage hard coded content for the homepage via content-release vs. nightly deploy. I'm a lil ignorant on this point, and hopefully we can fully Drupalize, but if not: need to discuss with team when we get to that bridge what this may mean.

**Comment by jilladams** [comment]
@mmiddaugh  updated schedule looks good -- I just added in holidays and updated V3 build delivery to land day before Thanksgiving. That's a 1.5 week turnaround from V3 designs to PW completing the build for prod. This is assuming that we are working Drupalization in the background starting next sprint (68), and that the V3 designs won't change the data model of any Drupal components. If those change, we may need to revisit that 11/23 delivery. Otherwise, looks good to me! cc @wesrowe

**Comment by wesrowe** [comment]
prototype is ready for round 2 of usability testing. closing this epic
