### ISSUE TITLE
🏗 Improve Test Run Times (Q3 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8357]
## Background

Once a PR is created, PR tests can take up to 2 hours to execute. This increases the code cycle time and negatively impacts the developer experience. The CMS team will assess the viability of parallelization and identify other opportunities for reducing overall test time in order to improve the deployment workflow.

Brainstorming doc: https://docs.google.com/spreadsheets/d/1PenLdmYeVWxwcOFO60TeG8-_H8QeNegRf64-Nj2odKs/edit#gid=0

### Affected users and stakeholders

* CMS engineers

## Acceptance Criteria

- [ ] Existing Behat tests and functionality are ported over to Cypress
- [ ] Tests run locally and in CI are completed in less time (tests are complete in as long as it takes the longest test to run: current state E2E ~45 mins)
  - [ ] Testing in Tugboat is reduced to ~10 minutes for completion
  - [ ] Testing in BRD env is reduced to ~10 minutes for completion 
- [ ] Test run time improvement is monitored, tracked and documented - before/after average test run time

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
Closing this issue as we start Q4
