### ISSUE TITLE
Vet Center Community access point - reset hours

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8368]
## User Story or Problem Statement
As a Vet Center editor, it would be awesome if I could easily reset the hours by line that I previously added. That would save me a ton of time so I don't have to change every menu.

To replicate
1. Go to https://prod.cms.va.gov/node/add/vet_center_cap
2. Under How should CAP hours be communicated?, click Provide CAP hours online
3. Set start and end times using the dropdown menus
4. Try to easily change the start and end times you just added![Screen Shot 2022-03-16 at 9.20.52 AM.png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/2c821552-64d0-44c6-9ed0-1090342530e5)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
See also #4888

**Comment by kevwalsh** [comment]
@xiongjaneg do you think this user's need will be mitigated enough by the greatly simplified html5 time picker? i was hoping to even close #4888 (the epic this is in)

**Comment by xiongjaneg** [comment]
@kevwalsh I'd say yes, the reduction of the sheer number of hours menus should be a big improvement to the problem statement, which was having to click so many dropdown menus. It sounds like this should make it much easier.
