### ISSUE TITLE
Add field_office_hours to paragraphs_type/service_location (reveal on top task) and update all to use HTML5

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8400]
## User Story or Problem Statement
We need to move from field_facility_service_hours (tablefield)  to field_office_hours in advance of the data migration so that it can be used for top task pages.

## Acceptance Criteria
- [ ] The field_office_hours is added to paragraphs_type/service_location
    - [ ] 12 hour time with am/pm
    - [ ] Comments field
    - [ ] Time increments by 15 minute increments
- [ ] The both field_facility_service_hours and field_office_hours both visible to admin only (ALWAYS EVERYWHERE)
- [ ] (non-admins) The field_office_hours is only visible to editors on vha_facility_nonclinical_service. and field_facility_service_hours is NOT visible.   All other places will continue to show field_facility_service_hours 
- [ ] Save data that is currently in the existing top task pages into the new field. (there is only about 5 of them) once this lands on prod.
- [ ] All Office hours fields are updated to HTML5

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I just finished moving the old data into the new field on non-clinical services on prod.  This is now complete.
