### ISSUE TITLE
Next.js Application (Q2 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8425]
## Background

Preliminary research has been conducted on several products selected as potential POC use cases for our React-based content build system (Resources and Support, Facilities' Stories). To properly shift teams/products over, a new build system is needed to render CMS data with the associated components and business logic for their products. 

We want to build a front end for CMS content that is based on a React-based framework, so that front-end engineers are working with a modern toolset that is compatible with the larger VA.gov front-end ecosystem. We also want to prioritize a front end framework that is flexible and that will allow us to make iterative improvements to VA.gov CMS content and its delivery.

### User Story or Problem Statement

As a CMS engineer, I want to build out the foundations of a new build system so that VFS FE teams can start creating and using templates within the new, React-based content build system (teams will be able to browse locally).

### Affected users and stakeholders

* Facilities and Resources and Support teams

## Acceptance Criteria

- [ ] The build system is able to output complete HTML for Facilities Stories 
  - [ ] The build system is able to output complete HTML for Resources and Support
- [ ] These output HTML files are served from a local development server
- [ ] Documents are created outlining the process by which FE teams can migrate their products into the new build system, based upon learnings from the process of porting these products

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
