### ISSUE TITLE
hardcode or require "Request your military service records online" in Vet Center "What to bring"

### ISSUE THREAD

**Issue by xiongjaneg** [department-of-veterans-affairs/va.gov-cms#8439]
## Problem Statement
On Vet Center pages, under Prepare for your visit, the What to bring accordion requires editors to add a link to "Request your military service records online"
![image (1).png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/8787240a-74a8-4414-a5ce-a280c941d78d)
![image (2).png](https://images.zenhubusercontent.com/5fa07f8cd87c6fff07bee6de/8b0da775-481a-456b-9a0e-58e066eaec20)

How might we make it easier for editors to include this and to prevent the link text or link target from being changed?

[See Escanaba Vet Center for example](https://www.va.gov/escanaba-vet-center/#prepare-for-your-visit)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires design review
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by xiongjaneg** [comment]
[See Slack thread](https://dsva.slack.com/archives/C02730UEZPS/p1647980417704379)
