### ISSUE TITLE
Migrate vagov-content content to CMS

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8444]
## Background
The CMS has its origins in a system which built static HTML pages from Markdown files. When the CMS came online, it became the content source for the majority of static content.

The repo which contains the Markdown files is https://github.com/department-of-veterans-affairs/vagov-content. There are still a small number of pages that are built from this repository, using this method. 

When we replace content-build, we will no longer support Markdown files as a content source. Therefore, we need to migrate or retire this content.

### User Story or Problem Statement

As a content creator, I need my content to be managed in the CMS so I can continue to share content updates with Veterans and the VA.

As Platform CMS, I need all content sourced from [vagov-content](https://github.com/department-of-veterans-affairs/vagov-content) to be migrated to the CMS, so that I do not have to support generating content from Markdown files.

### Affected users and stakeholders

* Editors & owners of existing content, who will need to be consulted about their existing content and trained on CMS usage
* Platform CMS and Sitewide CMS team members, who may need to create one or more new content types to support this legacy content.

### Hypothesis

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* We can identify all owners of vagov-content Markdown files
* We can discuss with them options for migration or retirement
* As much as possible, we will use existing content types for migrated content types
* If there is not an existing content type, we should discuss whether the content can be retired or be made available in a different form
* If absolutely necessary, we will create one or more content types to support this legacy content.

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

## Design principles

Veteran-centered
- [X] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [X] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [X] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [X] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [X] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
Work had been done previously to determine what content was in vagov-content and which pieces of content needed to be kept. That spreadsheet is here: https://docs.google.com/spreadsheets/d/1NVFKpE5rGjI3TdUJmMOfiv0tSid7eUvvNu63EzLxML8/edit#gid=0

There are tickets encompassing all the pieces of content which need to be kept or otherwise handled.
