### ISSUE TITLE
Standardize development and CI environments

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/va.gov-cms#8456]
## Background

Setup of Drupal for local development is documented in:
- https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/getting-started.md
- https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/local.md

As development teams have grown, additional ways have been created to configure the local development environment. This results in inconsistencies between tooling and setup steps across developers, which impacts the ability to reproduce issues and to provide current, authoritative documentation.

### User Story or Problem Statement

As a developer running CMS,

- I need to run Drupal locally in a way that is consistent with other developers,
so that I can expect consistent steps and behavior across local development environments.

- I need local development environment to match CI,
so that I can expect consistent behavior across local & CI.

- I need Codespaces configuration to automate creation of development environment,
so that I can get started running CMS with minimal manual setup.

### Affected users and stakeholders

* Developers of CMS Platform team
* Developers of CMS Sitewide teams
* Developers of Platform frontend teams
* Developers of VFS frontend teams

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
