### ISSUE TITLE
Investigate base preview main branch not refreshing

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8472]
## Problem Statement

Base preview usually expected to refresh within ~20 minutes. Base preview took over 2 hours to refresh. 

![image.png](https://images.zenhubusercontent.com/61548ced3c47fd7193066d26/c5c2905b-7dbc-4e4b-880b-9a0e83ae0f3c)

## Acceptance Criteria

- [ ] Implement Datadog monitoring to proactively identify issue in the future (build takes ~over 20 minutes)

## Implementation steps

- Submit feature request to Tugboat to add a preview action timeout that prevents running greater than 1 hour.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
Asked Tugboat support in https://dsva.slack.com/archives/C01A35JDH88/p1648147655334829

**Comment by ElijahLynn** [comment]
Datadog synthetic we discussed can use an alert threshold to check the Base URL for a `200 Ok` response.

**Comment by ElijahLynn** [comment]
I've added a Datadog Synthetic Test (via the UI, not Terraform), I'll also put it in Terraform tomorrow. 

![image](https://user-images.githubusercontent.com/1504756/162414922-84217ef8-747e-41ff-a61c-e5f9b7fda7a3.png)

**Comment by ElijahLynn** [comment]
PR to put this test into Terraform is here: https://github.com/department-of-veterans-affairs/devops/pull/11070

Here are what the notifications to Slack look like: 

![image](https://user-images.githubusercontent.com/1504756/163517874-3b642759-b114-4680-a54c-932ff7ba1d43.png)
![image](https://user-images.githubusercontent.com/1504756/163517876-811f8007-ccf9-453f-a76b-23227ba624a6.png)

Actual test is here: https://app.datadoghq.com/synthetics/details/q87-nat-c2z

![image](https://user-images.githubusercontent.com/1504756/163517925-22cfbf92-fe30-4ccd-b216-01ed5bceebd9.png)

![image](https://user-images.githubusercontent.com/1504756/163517916-6c7ac458-a2dc-41f5-9b8b-9f7982e183db.png)
