### ISSUE TITLE
Improve EFF workflow for devs for Centralized content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8477]
## User Story or Problem Statement

As a site builder creating a content type with Entity Field Fetch that references Centralized Content, i want to easily find paragraph IDs used in Centralized 

## Acceptance Criteria

- [ ] 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
@omahane Given that your work on #14699 will mostly involve entity fetch fields, might be worth seeing if this ticket is still relevant, or updating it with details on the current process and how to improve it

**Comment by omahane** [comment]
Given how rarely these are created (we currently have 8) and that would help one or maybe two people building a content type, I don't think this is needed. While it would be convenient to see the paragraph ids on the node:edit or node:view (or both), the work to surface those for the purposes of the few times this is used is not really commensurate with the value.
