### ISSUE TITLE
Product support - Sprint 55 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8487]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

- Q2 planning coming up Sprint 56.

## Content model hardening

- [x] #8298 (will be on prod on March 28 deploy)
- [x] #6931 🥅  Complete in terms of fields added and data initially migrated.  Waiting on FE removal of old field.

### #3151 3 VAMC Top task pages

- [ ] #8337 
  - [ ] Synthesize next sprint
- [x] Support Napolean with Register for care

When it's time to launch 
- [ ] #8130 

## #7158 Cerner cutover strategy 

- [ ] Internal huddle Platform CMS / Sitewide CMS
- [ ] #7860 (timeline: April, for Columbus go-live to Cerner April 30, which could be done "the Spokane and Walla Walla way"... Roseburg is next, June 11/12. Other context: Other MyVA portal work is looking for Cerner data.) There will be FE work to remove the Spokane/Walla Walla/Columbus when the new approach is ready)

## #7743 Resources and support pilot

- [x] #8035
- [x] #8389
- [x] #8388 

## #7622 Lovell

- [x] #7626 
  - [ ] Proof of concept 
- [x] Refine epic #1939 (for DoD facilities)

### #7624 Support lighthouse with unique ID for health service terms / #5017  Push facility services to lighthouse

Blocked by Lighthouse v1 API
- [ ] #8019 done but not merged, blocked by Lighthouse 
- [ ] #8017  blocked by Lighthouse AND
    - [ ] Field Office Hours hardening https://github.com/department-of-veterans-affairs/va.gov-cms/issues/6931
      - [x] script the migration https://github.com/department-of-veterans-affairs/va.gov-cms/pull/8533
      - [x] run the migration on prod to populate data for FE 
      - [ ] FE builds new display  https://github.com/department-of-veterans-affairs/va.gov-team/issues/39436 
      - [ ] After FE goes live(same day) Hide field `field_facility_service_hours` and show 'field_office_hours' in cms #8550 
      - [ ] Re-run script on prod `drush scr scripts/content/VACMS-6931-switch-service-locations-office-hours.php`
      - [ ] Notify editors / process bad entries from the outliers.csv #8708
      - [ ] #8709

- [ ] Stretch: #7279 

Possible to add to Lighthouse V0 API
- [ ] Stretch: #7726 

## O&M (Iván, Steve, Jay)

- [ ] #7728 and its many children
