### ISSUE TITLE
Dropzone: enhance or remove

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8504]
## User Story or Problem Statement

As a an editor I need to not get conflicting direction from my cms so that am not confused.

![image](https://user-images.githubusercontent.com/5752113/160461177-e155b79f-2fec-4e77-9652-1001a478e03a.png)

I should only be able to add a single file, but the directions from Dropzone make it sound like I can add multiples (which I can not).

Some investigation will be needed.  We need to either
A)  alter the wording on dropzone to use the singular "File" (look for an existing patch?)
B) Remove module from the CMS.

## Acceptance Criteria
- [ ] Either the help text is corrected to be singular
- [ ] or Dropzone plan (set of PRs) to remove dropzone.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Discussed this on a call:  @netboss is going to add his code to this issue https://www.drupal.org/project/dropzonejs/issues/3174484  which results in the plural singular issue being fixed in two locations.

Related discussions

- [What words to use](https://dsva.slack.com/archives/CT4GZBM8F/p1648500688465729)
- [Patch discussion](https://dsva.slack.com/archives/CT4GZBM8F/p1648489950773189).

**Comment by netboss** [comment]
@swirtSJW 
- Followed up in [drupal.org issue](https://www.drupal.org/project/dropzonejs/issues/3174484#comment-14461898) and contributed new patch with improvements.

**Comment by swirtSJW** [comment]
I just changed the upstream issue on d.o to "reviewed and tested by the community"  https://www.drupal.org/project/dropzonejs/issues/3174484#comment-14463473

**Comment by netboss** [comment]
> I just changed the upstream issue on d.o to "reviewed and tested by the community" https://www.drupal.org/project/dropzonejs/issues/3174484#comment-14463473

@swirtSJW 
Thank you!
