### ISSUE TITLE
Inline content guidance

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8541]
## Background

Formerly known as:
- "Learn more" help text pattern
- Extended help text

There is a need for extended help text discovery, guidance, and implementation within the CMS.  Will need to validate that inline content guidance:

1.  helps editor mental model, 
2. Adds context to the component in the system 
3. alleviates dependency on KB
4. Helps harden content guidance
5. provides a more accessible solution for editors by keeping them inside of the form (no additional clicks)

### User Story or Problem Statement

As a CMS editor working on creating content, I need easily accessible guidance so I know how to make decisions about my work.

As a product stakeholder, I want to editors to follow best practices that align with the product's design intent and VA content style.

### Affected users and stakeholders

* All users

### Hypothesis

As a CMS editor, I want a clear understanding of the content guidance so that I am efficient in creating high-quality Veteran-centered content. 

## Assumptions
* Inline content guidance should be "opt-in," and accessible through a collapsible component
* Guidance may take the following forms: annotated screenshots, text, links to KB or content style guide
* Help text is supplemental information that helps editors successfully complete a field. 
* Most people don't read help text unless they are stuck and need help filling out a field
* Guidance is different than help text. It goes beyond simply helping editors complete a field. It prompts editors to make choices that follow content best practices.

## Related artifacts (old -- needs revisiting)
- Mock up of how inline content guidance could be used to support better alt text (ideation in collab w/ Josh Kim): [Figma: Media Library UI](https://www.figma.com/file/Bicr5pUbygcToLltOYtD4X/Media-library-UI?node-id=0%3A1)
- [An ancient treatise on help text](https://app.mural.co/t/vagov6717/m/vagov6717/1586882180337/415aa0adba23f935239d291d83fda234b16f1957)
- [VA design system: "Additional info" component](https://design.va.gov/components/additional-info)

<img width="734" alt="Screen Shot 2022-03-31 at 4 25 02 PM" src="https://user-images.githubusercontent.com/41017988/161165485-2b2450dc-1dcb-4f9b-a2aa-e065e1ca2870.png">

## Acceptance Criteria
- [ ] Inline content guidance for alt text is tested with editors
- [x] Other areas of opportunity are identified
- [x] Change management is consulted
- [ ] Requires KB article update

## Design principles

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [x] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [x] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by rachel-kauff** [comment]
Notes from chat w/ Jane

Which is the idea user group to test with?
- Health service would be great, but it's complicated bc has most active number of users. High risk. 
- Second most confusing thing is Vet Center facility basic data - still big user base, but smaller subset of data
   - Folks struggle with why can't I change my data?
   - Benefit is that it's a less technically-saavy group, so they struggle more (therefore need the guidance the most)
   -

**Comment by rachel-kauff** [comment]
**Recruitment tactics**
- Start w/ VHA digimedia - run research plan by them
- If we go with alt text: involve Blake Skates as stakeholder - VHA a11y expert
- If we go with meta tags: [seo expert]
- Invite folks to come via PAO newsletter
- Pull folks related to top task research work Erika and Suzanne did
- Suzanne might have ideas, repo of willing participants
- Could pick random folks to invite
- Collab w/ vha digimedia - make it easy for them by writing the recruitment email and have them cosign
- Might want to ask Dave to run it by Jenny HL to make sure she's aware 
-

**Comment by rachel-kauff** [comment]
Next steps:
- Refines issues for research plan, prototyping, 
- Run by Dave
- Convos w/ Site and VHA digimedia

**Comment by EWashb** [comment]
Notes from prioritization meeting with Dave on May 10, 2022

- Sync research plan efforts with larger research collab cycle
- Instead of focusing on VAMC first, there is an opportunity to sync with the R&S pilot editors since they are new to the system and have very focused content guidance from the Sitewide Content team. 
- There are also a lot of new Vet Center editors that could be good to test this with first. 
- As we develop an MVP for this we should explore a way to link this to the knowledge base so that it is easier to maintain the content.
- Think of testing this with the "goldilocks model." What is too little, too much, or just right for the amount of content to include. Think of it as preference testing. 
- Once we test with the goldilocks model, build out additional hypotheses. (For example, accordions and other click throughs)
- Remember, we don't do mobile-first testing, but we DO want to keep in mind screen readers and screen sizing. This effort could be out of scope for this, but look into what the collab cycle guidance is here. 
- This is not priority for the current, BUT Dave agrees that it could solve a lot of backlog issues and is ok to proceed to investigate the way forward. This is "exactly what the Sitewide CMS team should focus on for long term"

**Comment by EWashb** [comment]
This is currently on hold to account for UX resourcing.

**Comment by mgifford** [comment]
I posted some options here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8750#issuecomment-1208463026

**Comment by EWashb** [comment]
The roll out could happen on X date and compare after two months. What percentage of change is there? 

VAMCs is the biggest offender.

**Comment by EWashb** [comment]
We did not do any CM for this. This is a silent rollout. We will compare any change in alt text errors after Q4 2022
