### ISSUE TITLE
The old field_facility_service_hours field should be hidden from paragraph edit/displays and views

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8550]
## Acceptance Criteria

- [ ] Hide the old Service Location field_facility_service_hours (table field) on edit/view. 
- [ ] The non-clinical services view needs to be updated to use the new field /admin/structure/views/view/non_clinical_services

## Implementation steps

Once the script from #6931 has been run on production and the FE team has built the new display to use the new office hours field: [Update VAMC Facility Health Service front end to utilize new office hours field](https://github.com/department-of-veterans-affairs/va.gov-team/issues/39436)

- [ ] Deploy this update (hides old field)
- [ ] Re-run script from #6931 

Do we need a separate ticket to remove the old field or should this ticket simply remove it instead of hiding it @swirtSJW
