### ISSUE TITLE
Tweak node link reports to reduce false positives and decrease confusion

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#856]
## User Story

As a content editor, I need node link reports to be accurate. 

## Goal
Node link reports can be made more specific to the decoupled context.

## Acceptance Criteria
* We have analyzed all points of confusion within broken links, and have a plan for resolving it
* we have issues in D.o issue queue and in github to track these enhancements

### Http Links

- [ ]  Network blocks (LinkedIn, Instagram, Youtube) -   Currently resolvable with some additions to the skip urls field.
- [x] Links to self when node unpublished   https://www.drupal.org/project/node_link_report/issues/3114417
- [x]  Links to CMS pages that are not visible to anonymous users (we could make these blocks visible to anonymous users)  - https://www.drupal.org/project/node_link_report/issues/3114415
- [x]  Links to pages that exist on the front end but not in the CMS (we could check va.gov AFTER checking prod.cms.v.agov)   - https://www.drupal.org/project/node_link_report/issues/3114418
- [ ]  Links to users - could be covered by https://www.drupal.org/project/node_link_report/issues/3114415

### Non http links that could use better reporting
* Phone numbers (SMS & tel)
* email

**Comment by swirtSJW** [comment]
I just created relevant issues on D.O and linked them above.   Working on them now.

**Comment by swirtSJW** [comment]
I just committed and closed this issue to remove references to itself from link checking.  https://www.drupal.org/project/node_link_report/issues/3114417

**Comment by swirtSJW** [comment]
I just pushed code tot he d.o repo to handle separate output for redirected links.  https://www.drupal.org/project/node_link_report/issues/3107174

![redirected_links](https://user-images.githubusercontent.com/5752113/74784990-31e68c00-5277-11ea-9483-d56dd677e403.png)

**Comment by swirtSJW** [comment]
I just pushed up a commit to D.0 allow configuration to  ignore internal paths by pattern matching.  https://www.drupal.org/project/node_link_report/issues/3114415   This will handle several of our cases of false alarms.

**Comment by swirtSJW** [comment]
I just completed https://www.drupal.org/project/node_link_report/issues/3114418 which allows for checking the frontend.

**Comment by swirtSJW** [comment]
I just created the release on D.o so that I can pull these new features into our site 
https://www.drupal.org/project/node_link_report/releases/8.x-1.7
