### ISSUE TITLE
Push VAMC system URL to lighthouse, and COVID program URL

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8565]
## User Story or Problem Statement

As a Veteran using a tool supported by Facility API data, I can find the URL of my health care system from related data. 

[Slack discussion ](https://dsva.slack.com/archives/C02BTJTDFTN/p1648751732774999)

## Acceptance Criteria
- [x] Lighthouse receives the name of the health care system and its URL as part of facility status data push.
- [x] Meets agreed upon format
```php
$payload = [
  facility_url => 'https://www.va.gov/phoenix-health-care/locations/payson-va-clinic';
  'operating_status' => [
    'code' => 'Closed',
    'additional_info' => "We are closed due to tornado watch.",
  ],
  system =>[ 
    name => 'VA Phoenix health care';
    url => 'https://www.va.gov/phoenix-health-care';
    covid_url => 'https://www.va.gov/phoenix-health-care/programs/covid-19-vaccines';
  ]
];
```
- [x] If a VAMC system URL, or name changes, it needs to trigger a facility push for all facilities in that system (Looper similar to system service changes)

Possibly
- [x] Push COVID-19 Programs page /[vamc-system]/programs/covid-19-vaccines to Lighthouse

Related: 
- [x] "VA health connect" phone number #7726

Blocked by Lighthouse being able to receive this. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Facility url was omitted from the Payload until lighthouse is able to receive it
![image](https://user-images.githubusercontent.com/5752113/172292814-6cc2b2d0-bb82-4c99-a391-c477eb5c8139.png)
