### ISSUE TITLE
Document what data is pulled/pushed to Facilities API in Content Model documentation 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8567]
## User Story or Problem Statement

As a product team member working with VAMC facilities data, i want documentation about what data originates in Facility API, and what data is pushed to Facility API. 

Airtable link for documentation: https://airtable.com/appSg80z9nVWoesxn/tblPdSdScGDeV1Y6f/viw2mH23ikkayVY2E?blocks=hide

## Acceptance Criteria
- [ ] Create a view on the Bundles and Fields tab, and appropriate metadata to help track what's getting pushed. We may need a "Notes about Facility API" field as well for additional context 
- [ ] Others TBD

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by RWEagans** [comment]
@JayDarnell Is this issue completed? Looks to be completed but wanted to get your go-ahead to close it.

**Comment by JayDarnell** [comment]
This was also moved into airtable here: https://airtable.com/appSg80z9nVWoesxn/tblPdSdScGDeV1Y6f/viw2mH23ikkayVY2E
