### ISSUE TITLE
Push more CMS owned data to Facility API

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8568]
## User Story or Problem Statement

VAMC data not yet Lighthouse

- [ ] System
  - [ ] VAMC system URL (from system node) #8565 
  - [ ] COVID program URL #8565 
  - [ ] VA health connect phone number  (from system node) #7726
  - [ ] Facility
    - [ ] Facility URL #7279 (blocked by Lighthouse)
    - [ ] Facility services (other than COVID) #8019 (blocked by Lighthouse) 
    - [ ] Facility status NULL for Facility status normal #6318 (not blocked) 
   
Vet Center CAP data
- [ ] 
- [ ] Lat / long (blocked by #7490 CMS functionality)

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [x] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by mmiddaugh** [comment]
closing as largely complete
