### ISSUE TITLE
Full page aps need a CMS counterpart

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8576]
## User Story or Problem Statement

As we add more full page and full route aps into our ecosystem it would be helpful from an editorial experience to have a CMS counterpart to represent that page.

The page could use the ap id similar to the way we add them at the paragraph level

## Acceptance Criteria
- [ ] A content type "Ap" exists in the CMS
- [ ] The content type is capable of occupying any path (no alias patterns are used)  ex: `/any/path/x`
   - [ ] The content type has a method for specifying sub paths that may are uses as subroutes within the ap. ex: `/any/path/x/y` and  `/any/path/x/y/z`  using `field_target_paths`
- fields
   - [ ] field_target_paths  unlimited cardinality
   - [ ] field_administration
   - [ ] field_ap_id  (string)
   - [ ] meta tags ??
   - [ ] TBD
- [ ] Validation: alias save on other pages would be prevented if they try to use the same subpaths already defined in an Ap node. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
