### ISSUE TITLE
Remove Lando and cut over fully to DDEV 

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8588]
## Description
Since the current team is committed to converting DDEV, it is time to make it official so that new team members are not confused by conflicting documentation.

## Acceptance Criteria
- [x] Lando config is gone
- [x] Lando documentation is gone.
- [x] DDEV documentation is moved to or linked from documentation in github.  (can be linked as long as the confluence doc is fully public.)
- [x] Github code spaces are using ddev instead of lando.

(all ACs done in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9401)

## Task List
- [ ] Remove lando config
- [ ] Remove lando documentation
  - [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/local.md
  - [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/testing.md
  - [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/READMES/local.md
  - [ ] https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1956937732/ddev
- [ ] Update codespaces config
- [ ] ...

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
I just confirmed that I can get to 
https://vfs.atlassian.net/wiki/spaces/PCMS/pages/1956937732/ddev  
Without being logged in or on the VA network / Socks.

**Comment by cweagans** [comment]
A few things to look at here:

* The pre commit hook switches between running stuff in lando or ddev depending on what's running
* The vscode launch.json has stuff for both lando and ddev
* Codespaces is still set up for lando - might need updated to ddev
* `$settings['va_gov_frontend_build_type']` is set to lando, even in ddev environments
* We may want to consider bringing back `.env` and wiring it up to ddev for working on env-specific functionality, but that could happen later.

Let me know if I can help here!

**Comment by jilladams** [comment]
Voice of a new hire: I followed the Lando route for setup, and suspect I'm not alone, so here's a +1 for prioritizing these documentation updates.

**Comment by ElijahLynn** [comment]
I'm working on this now this sprint, and I'll get it all cleaned up and cutover, including our GitHub Code Spaces config too!

**Comment by cweagans** [comment]
Closed in https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9401
