### ISSUE TITLE
component: paragraph--alert (Alert)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8607]
## Description
A component is needed in the next-build system to render paragraph--alert. This component should be able to be used standalone or to render field data for other nodes and paragraphs. 

## Acceptance Criteria
- [ ] A component exists that can render a `paragraph--alert` data structure
- [ ] A page exists within the next-build repo that demonstrates the rendering of all `paragraph--alert`
- [ ] That component's output is consistent with the existing output of content-build (visually, markup structure)

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8615
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8642
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8688
```

## Supporting detail
**Paragraph/Node**: `paragraph--alert`

**CMS structure**: [`paragraphs_type/alert/fields`](https://prod.cms.va.gov/admin/structure/paragraphs_type/alert/fields)

**API query**:  [`jsonapi/paragraph/alert`](https://prod.cms.va.gov/jsonapi/paragraph/alert)

**Existing template(s)**:[`alert.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/components/alert.drupal.liquid)

**Existing/example existing GraphQL**:[`alert.paragraph.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/paragraph-fragments/alert.paragraph.graphql.js)

**Logic notes**:
Supporting Liquid Template(s):[`blocks/alert.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/blocks/alert.drupal.liquid)

* When `fieldAlertBlockReference` is not empty `include alert = alertBlock`
* When `alertType` equals information assign `alertType = "info"`

**Example to render collection of <component> objects**:

```javascript
    const paragraph--alert = await getResourceCollectionFromContext(
        'paragraph--alert',
        context,
        {} // params 
    );
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "paragraph--alert",
    "id": "019070f3-9e3e-4c69-83e4-c7eace8c414f",
    "drupal_internal__id": 6003,
    "drupal_internal__revision_id": 27807,
    "langcode": "en",
    "status": true,
    "created": "2019-09-04T13:45:29+00:00",
    "parent_id": "876",
    "parent_type": "node",
    "parent_field_name": "field_content_block",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": true,
    "field_alert_heading": "Blue Water Navy Veterans and Agent Orange",
    "field_alert_type": "information",
    "links": {
        "self": {
            "href": "http://va-gov-cms.ddev.site/jsonapi/paragraph/alert/019070f3-9e3e-4c69-83e4-c7eace8c414f"
        }
    },
    "paragraph_type": {
        "type": "paragraphs_type--paragraphs_type",
        "id": "daa6bb41-1b12-46f7-a355-96ceb6fa18dc",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": "alert"
        }
    },
    "field_alert_block_reference": null,
    "field_va_paragraphs": [
        {
            "type": "paragraph--wysiwyg",
            "id": "abb45dcb-b33f-4080-b20f-2f89d4281806",
            "resourceIdObjMeta": {
                "target_revision_id": 27808,
                "drupal_internal__target_id": 6004
            }
        }
    ],
    "relationshipNames": [
        "paragraph_type",
        "field_alert_block_reference",
        "field_va_paragraphs"
    ]
}
```

Further info:[`paragraphs/alert.md`](https://github.com/department-of-veterans-affairs/content-api-react-poc/blob/main/references/paragraphs/alert.md)
