### ISSUE TITLE
component: paragraph--alert_single (Alert (single))

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8608]
## Description
Build out the paragraph--alert_single component.

```[tasklist]
### Tasks
- [ ] All child tasks are complete
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8618
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8688
- [ ] Drupal type definition
- [ ] Next/component type definition
- [ ] Component QueryFormatter created
- [ ] Component & tests created
- [ ] Component in storybook
```

### CMS Info
**Paragraph/Node**: `paragraph--alert_single`
**CMS structure**: [`paragraphs_type/alert_single/fields`](https://prod.cms.va.gov/admin/structure/paragraphs_type/alert_single/fields)
**JSON:API query**:  [`jsonapi/paragraph/alert_single`](https://prod.cms.va.gov/jsonapi/paragraph/alert_single)

### Content Build info
**Existing template(s)**:[`alert_single.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/paragraphs/alert_single.drupal.liquid)
**Existing/example existing GraphQL**:[`alertSingle.paragraph.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/paragraph-fragments/alertSingle.paragraph.graphql.js)
**Logic notes**:
Supporting Liquid Template(s):[`blocks/alert.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/blocks/alert.drupal.liquid)

* When `field_alert_selection` equals `R` include Reusable alert
* When `field_alert_selection` equals `NR` include `fieldAlertNonReusableRef`

### Next Build info
**Example next-drupal query**:

```javascript
  const params = queries
    .getParams()
    .addPageLimit(3)
    .addInclude([
      'field_alert_block_reference',
      'field_alert_block_reference.field_alert_content',
      'field_alert_non_reusable_ref',
      'field_alert_non_reusable_ref.field_va_paragraphs'
    ])
  const data = await drupalClient.getResourceCollection('paragraph--alert_single', {
    params: params.getQueryObject(),
    withAuth: {
      clientId: process.env.DRUPAL_CLIENT_ID,
      clientSecret: process.env.DRUPAL_CLIENT_SECRET,
    }
  })
```

<details>
<summary>Sample complete next-drupal response (expand):</summary>
<code>
{
    "type": "paragraph--alert_single",
    "id": "0e71c5cd-a4e2-4dec-9b1e-0ef1c5666f65",
    "drupal_internal__id": 13070,
    "drupal_internal__revision_id": 145553,
    "langcode": "en",
    "status": true,
    "created": "2020-10-01T15:35:24+00:00",
    "parent_id": "12696",
    "parent_type": "paragraph",
    "parent_field_name": "field_alert",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": null,
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "content_translation_changed": null,
    "field_alert_selection": "R",
    "field_markup": null,
    "links": {
      "self": {
        "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/alert_single/0e71c5cd-a4e2-4dec-9b1e-0ef1c5666f65?resourceVersion=id%3A145553"
      }
    },
    "paragraph_type": {
      "type": "paragraphs_type--paragraphs_type",
      "id": "f2e64319-f14b-4bc1-8674-4661358e4242",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "alert_single"
      }
    },
"field_alert_non_reusable_ref": {
      "type": "paragraph--non_reusable_alert",
      "id": "4eff76c1-5e3e-410b-a56a-64b572f98756",
      "drupal_internal__id": 13072,
      "drupal_internal__revision_id": 145559,
      "langcode": "en",
      "status": true,
      "created": "2020-10-01T17:08:59+00:00",
      "parent_id": "13073",
      "parent_type": "paragraph",
      "parent_field_name": "field_alert_non_reusable_ref",
      "behavior_settings": [],
      "default_langcode": true,
      "revision_translation_affected": null,
      "content_translation_source": "und",
      "content_translation_outdated": false,
      "content_translation_changed": null,
      "field_alert_heading": "Sample non-reusable alert",
      "field_alert_type": "information",
      "links": {
        "self": {
          "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/non_reusable_alert/4eff76c1-5e3e-410b-a56a-64b572f98756?resourceVersion=id%3A145559"
        }
      },
      "resourceIdObjMeta": {
        "target_revision_id": 145559,
        "drupal_internal__target_id": 13072
      },
      "paragraph_type": {
        "type": "paragraphs_type--paragraphs_type",
        "id": "3d633fc0-97d6-4087-b709-edfa2d1e6a1e",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": "non_reusable_alert"
        }
      },
      "field_va_paragraphs": [
        {
          "type": "paragraph--wysiwyg",
          "id": "2fc092f1-969a-4136-9039-4fc50a9f93c4",
          "drupal_internal__id": 13071,
          "drupal_internal__revision_id": 141493,
          "langcode": "en",
          "status": true,
          "created": "2020-10-01T17:09:17+00:00",
          "parent_id": "13072",
          "parent_type": "paragraph",
          "parent_field_name": "field_va_paragraphs",
          "behavior_settings": [],
          "default_langcode": true,
          "revision_translation_affected": true,
          "content_translation_source": "und",
          "content_translation_outdated": false,
          "content_translation_changed": null,
          "field_wysiwyg": {
            "value": "<p>This is where the text goes for the alert</p>\r\n",
            "format": "rich_text",
            "processed": "<p>This is where the text goes for the alert</p>"
          },
          "links": {
            "self": {
              "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/wysiwyg/2fc092f1-969a-4136-9039-4fc50a9f93c4?resourceVersion=id%3A141493"
            }
          },
          "resourceIdObjMeta": {
            "target_revision_id": 141493,
            "drupal_internal__target_id": 13071
          },
          "paragraph_type": {
            "type": "paragraphs_type--paragraphs_type",
            "id": "885e4b61-cfd2-44b9-94ae-f068ba2b48b6",
            "resourceIdObjMeta": {
              "drupal_internal__target_id": "wysiwyg"
            }
          },
          "relationshipNames": [
            "paragraph_type"
          ]
        }
      ],
      "relationshipNames": [
        "paragraph_type",
        "field_va_paragraphs"
      ]
    },
    "field_alert_block_reference": {
      "type": "block_content--alert",
      "id": "ba9dd3f4-4260-4e21-bbf9-a5cf0db49fc1",
      "drupal_internal__id": 45,
      "drupal_internal__revision_id": 994,
      "langcode": "en",
      "revision_created": "2022-09-06T17:30:19+00:00",
      "revision_log": "Archiving as no longer needed per Sitewide Content convo",
      "status": false,
      "info": "COVID-19 alert: Claims and other services",
      "changed": "2022-09-06T17:30:19+00:00",
      "reusable": true,
      "default_langcode": true,
      "revision_translation_affected": true,
      "moderation_state": "archived",
      "metatag": [
        {
          "tag": "meta",
          "attributes": {
            "name": "title",
            "content": "| Veterans Affairs"
          }
        }
      ],
      "field_alert_title": "You can still file a claim and apply for benefits during the coronavirus pandemic",
      "field_alert_type": "information",
      "field_reusability": "reusable",
      "links": {
        "self": {
          "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/block_content/alert/ba9dd3f4-4260-4e21-bbf9-a5cf0db49fc1?resourceVersion=id%3A994"
        }
      },
      "resourceIdObjMeta": {
        "drupal_internal__target_id": 45
      },
      "block_content_type": {
        "type": "block_content_type--block_content_type",
        "id": "278a3f4b-8d89-4768-ab03-869b8cc98613",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": "alert"
        }
      },
      "revision_user": {
        "type": "user--user",
        "id": "38daa8d4-3d05-48a3-bb95-a9c75988e382",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 295
        }
      },
      "field_alert_content": {
        "type": "paragraph--wysiwyg",
        "id": "65fda9e9-1bbb-45f2-bc39-d3c659ba30d1",
        "drupal_internal__id": 10536,
        "drupal_internal__revision_id": 729754,
        "langcode": "en",
        "status": true,
        "created": "2020-05-30T16:44:57+00:00",
        "parent_id": "45",
        "parent_type": "block_content",
        "parent_field_name": "field_alert_content",
        "behavior_settings": [],
        "default_langcode": true,
        "revision_translation_affected": true,
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "content_translation_changed": null,
        "field_wysiwyg": {
          "value": "<p>Get the latest information about in-person services, claim exams, extensions, paperwork, decision reviews and appeals, and how best to contact us during this time.</p>\r\n\r\n<p><a href=\"/coronavirus-veteran-frequently-asked-questions/#claims-and-applications\">Go to our coronavirus FAQs</a></p>\r\n",
          "format": "rich_text",
          "processed": "<p>Get the latest information about in-person services, claim exams, extensions, paperwork, decision reviews and appeals, and how best to contact us during this time.</p>\n\n<p><a href=\"/coronavirus-veteran-frequently-asked-questions/#claims-and-applications\">Go to our coronavirus FAQs</a></p>"
        },
        "links": {
          "self": {
            "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/wysiwyg/65fda9e9-1bbb-45f2-bc39-d3c659ba30d1?resourceVersion=id%3A729754"
          }
        },
        "resourceIdObjMeta": {
          "target_revision_id": 729754,
          "drupal_internal__target_id": 10536
        },
        "paragraph_type": {
          "type": "paragraphs_type--paragraphs_type",
          "id": "885e4b61-cfd2-44b9-94ae-f068ba2b48b6",
          "resourceIdObjMeta": {
            "drupal_internal__target_id": "wysiwyg"
          }
        },
        "relationshipNames": [
          "paragraph_type"
        ]
      },
      "field_owner": {
        "type": "taxonomy_term--administration",
        "id": "40ef8d64-fa92-41b6-88c0-4d85dc24e191",
        "resourceIdObjMeta": {
          "drupal_internal__target_id": 194
        }
      },
      "relationshipNames": [
        "block_content_type",
        "revision_user",
        "field_alert_content",
        "field_owner"
      ]
    },
    "relationshipNames": [
      "paragraph_type",
      "field_alert_non_reusable_ref",
      "field_alert_block_reference"
    ]
  },
</code>
</details>
