### ISSUE TITLE
component: paragraph--collapsible_panel (Accordion group)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8612]
## Description
Build out the paragraph--collapsible_panel component.

```[tasklist]
### Tasks
- [ ] All child tasks are complete
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16741
- [ ] Drupal type definition
- [ ] Next/component type definition
- [ ] Component QueryFormatter created
- [ ] Component & tests created
- [ ] Component in storybook
```

### CMS Info
**Paragraph/Node**: `paragraph--collapsible_panel`
**CMS structure**: [`paragraphs_type/collapsible_panel/fields`](https://prod.cms.va.gov/admin/structure/paragraphs_type/collapsible_panel/fields)
**JSON:API query**:  [`jsonapi/paragraph/collapsible_panel`](https://prod.cms.va.gov/jsonapi/paragraph/collapsible_panel)

### Content Build info
**Existing template(s)**:[`collapsible_panel.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/paragraphs/collapsible_panel.drupal.liquid)
**Existing/example existing GraphQL**:[`collapsiblePanel.paragraph.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/paragraph-fragments/collapsiblePanel.paragraph.graphql.js)
**Logic notes**:
* [`wysiwyg.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/paragraphs/wysiwyg.drupal.liquid)
* Render dependencies : collapsible_panel_item, field_wysiwyg

### Next Build info
**Example next-drupal query**:

```javascript
  const params = queries
    .getParams()
    .addPageLimit(3)
    .addInclude([
      'field_va_paragraphs',
      'field_va_paragraphs.field_va_paragraphs'
    ])

  const data = await drupalClient.getResourceCollection('paragraph--collapsible_panel', {
    params: params.getQueryObject(),
    withAuth: {
      clientId: process.env.DRUPAL_CLIENT_ID,
      clientSecret: process.env.DRUPAL_CLIENT_SECRET,
    }
  })
```

<details>
<summary>Sample complete next-drupal response (expand):</summary>
<code>
 {
    "type": "paragraph--collapsible_panel",
    "id": "580c7141-442a-4848-9f16-212c09fb612d",
    "drupal_internal__id": 4526,
    "drupal_internal__revision_id": 22878,
    "langcode": "en",
    "status": true,
    "created": "2019-07-12T16:47:43+00:00",
    "parent_id": "724",
    "parent_type": "node",
    "parent_field_name": "field_content_block",
    "behavior_settings": [],
    "default_langcode": true,
    "revision_translation_affected": null,
    "content_translation_source": "und",
    "content_translation_outdated": false,
    "content_translation_changed": null,
    "field_collapsible_panel_bordered": false,
    "field_collapsible_panel_expand": false,
    "field_collapsible_panel_multi": false,
    "links": {
      "self": {
        "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/collapsible_panel/580c7141-442a-4848-9f16-212c09fb612d?resourceVersion=id%3A22878"
      }
    },
    "paragraph_type": {
      "type": "paragraphs_type--paragraphs_type",
      "id": "9d342344-615c-4c0b-b4c8-991d7ec4d20c",
      "resourceIdObjMeta": {
        "drupal_internal__target_id": "collapsible_panel"
      }
    },
    "field_va_paragraphs": [
      {
        "type": "paragraph--collapsible_panel_item",
        "id": "e2b52418-f13e-4928-9b5f-418524dfe322",
        "drupal_internal__id": 4527,
        "drupal_internal__revision_id": 22867,
        "langcode": "en",
        "status": true,
        "created": "2019-07-12T16:47:43+00:00",
        "parent_id": "4526",
        "parent_type": "paragraph",
        "parent_field_name": "field_va_paragraphs",
        "behavior_settings": [],
        "default_langcode": true,
        "revision_translation_affected": true,
        "content_translation_source": "und",
        "content_translation_outdated": false,
        "content_translation_changed": null,
        "field_wysiwyg": {
          "value": "<div id=\"Alabama\" class=\"usa-accordion-content\"> </div>",
          "format": "rich_text",
          "processed": ""
        },
        "field_title": "Alabama",
        "links": {
          "self": {
            "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/collapsible_panel_item/e2b52418-f13e-4928-9b5f-418524dfe322?resourceVersion=id%3A22867"
          }
        },
        "resourceIdObjMeta": {
          "target_revision_id": 22867,
          "drupal_internal__target_id": 4527
        },
        "paragraph_type": {
          "type": "paragraphs_type--paragraphs_type",
          "id": "e2a6831d-9d06-45d6-940e-dc542830f6ec",
          "resourceIdObjMeta": {
            "drupal_internal__target_id": "collapsible_panel_item"
          }
        },
        "field_va_paragraphs": [
          {
            "type": "paragraph--table",
            "id": "90824b6b-bc4d-4082-96c9-d82a5ce5ee15",
            "drupal_internal__id": 4528,
            "drupal_internal__revision_id": 22866,
            "langcode": "en",
            "status": true,
            "created": "2019-07-12T16:47:43+00:00",
            "parent_id": "4527",
            "parent_type": "paragraph",
            "parent_field_name": "field_va_paragraphs",
            "behavior_settings": [],
            "default_langcode": true,
            "revision_translation_affected": null,
            "content_translation_source": "und",
            "content_translation_outdated": false,
            "content_translation_changed": null,
            "field_table": {
              "value": [
                [
                  "<strong>School name</strong>",
                  "<strong>VSOC counselor email address</strong>",
                  "<strong>Regional office</strong>"
                ],
                [
                  "Troy University",
                  "Rickey Jones <a href=\"mailto:Rickey.Jones@va.gov\">Rickey.Jones@va.gov</a>",
                  "Montgomery (322)"
                ],
                [
                  "University of Alabama",
                  "Lisa Fells <a href=\"mailto:Lisa.Fells@va.gov\">Lisa.Fells@va.gov</a>",
                  "Montgomery (322)"
                ]
              ],
              "format": "rich_text",
              "caption": ""
            },
            "links": {
              "self": {
                "href": "https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/jsonapi/paragraph/table/90824b6b-bc4d-4082-96c9-d82a5ce5ee15?resourceVersion=id%3A22866"
              }
            },
            "resourceIdObjMeta": {
              "target_revision_id": 22866,
              "drupal_internal__target_id": 4528
            },
            "paragraph_type": {
              "type": "paragraphs_type--paragraphs_type",
              "id": "80b23186-37b2-4c2b-8223-24e952485df8",
              "resourceIdObjMeta": {
                "drupal_internal__target_id": "table"
              }
            },
            "relationshipNames": [
              "paragraph_type"
            ]
          }
        ],
        "relationshipNames": [
          "paragraph_type",
          "field_va_paragraphs"
        ]
      }
    ],
    "relationshipNames": [
      "paragraph_type",
      "field_va_paragraphs"
    ]
  }
</code>
</details>
