### ISSUE TITLE
Main Drupal admin toolbar should have direct link to Helpdesk support form

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#8621]
## User Story or Problem Statement

Problem description: According to Steve T. @ VHA Digital Media, it can sometimes be rather difficult for editors to find where to contact the VA Drupal CMS Helpdesk.

Right now, the easiest way to contact the VA Drupal CMS Helpdesk is to go to the main Knowledge Base page and then click "Contact help desk." 

By having a direct link to the helpdesk submission form within the Drupal admin toolbar (for authenticated users only), this would help make things easier for users who may not know it is located on the main Knowledge Base page.

## Acceptance Criteria
There is a way to access the VA Drupal CMS Helpdesk submission form directly from the Drupal admin toolbar.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [X] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [X] `⭐️ User support`

**Comment by stefaniefgray** [comment]
Discussed during UX/helpdesk check-in -- not a Q2 priority at this time

**Comment by stefaniefgray** [comment]
Closing

Editors should consult Knowledge Base first before submitting requests
