### ISSUE TITLE
Improve editorial experience when adding media to https://prod.cms.va.gov/

### ISSUE THREAD

**Issue by stefaniefgray** [department-of-veterans-affairs/va.gov-cms#8622]
### Via Michelle Middaugh in VAHELP-3907:

> After watching many Vet Center editors struggle with adding media, I think we have an opportunity to make the editorial experience better. **After selecting the media, the pop-up window is too small to see the full flow through alt text, cropping and section selection. Yet the save buttons are always visible, even before the required fields have been completed.** 
>
> **It's easy to understand why they might think it's saved or inserted when they haven't completed all the fields.** 
>
> I'd love to see us revisit this at some point. By the way, the help guide calls out each of these steps but we still have a lot of new editors who struggle."

### **Screenshots:**

Please refer to the four total screenshots added by Michelle to the following Knowledge Base article:
https://prod.cms.va.gov/help/vet-centers/how-to-add-a-vet-center-facility-photo

1. Original pop-up window when adding media:

![image](https://user-images.githubusercontent.com/9059428/161877582-b96f6adb-ac6f-4c6e-8cc3-12ea3c6825d1.png)

2. Relatively small dialog window for filling out information: 

![image](https://user-images.githubusercontent.com/9059428/161877655-02ad160f-090a-4935-b113-5f00361dc8b4.png)

## Acceptance Criteria
- [ ] Pop-up window when adding media should be large enough to accommodate alt text, cropping, and section selection.
- [ ] Save button should no longer be visible when required fields are empty.
- [ ] Requires KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [X] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [X] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [X] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [X] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [X] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by stefaniefgray** [comment]
https://va-gov.atlassian.net/browse/VAHELP-3907

**Comment by davidmpickett** [comment]
Seems more like a core CMS change than a Facilities specific one

**Comment by aklausmeier** [comment]
In Facilities recent FEB 2024 VBA regional office editor research, related insights were uncovered.

- Confusion between alt text and description field, captured in #17443 
- Save message after photo upload flow, mismatch in messaging, captured in #17375 
- Observed lack of overall help text and links within help text to any related KB articles
- Button text not clear/obvious
- remove button was only one that worked well
- As an observer, it would benefit the editor if the overall media upload/edit flows were documented and reviewed for improvements

**Comment by aklausmeier** [comment]
@davidmpickett It's possible Facilities could pull this into Vet Center work. FYA if we uncover as an opportunity.

**Comment by aklausmeier** [comment]
@mmiddaugh and I discussed this as a possible candidate for IIR UX design follow up to the [VAMC editor research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/research/2024%20VAMC%20CMS) they recently completed in collaboration with Facilities team. I have checked in with @EWashb and we are good to move forward if our teams capacity allows.

**Comment by aklausmeier** [comment]
related and possible overlap with https://github.com/department-of-veterans-affairs/va.gov-cms/issues/4895

**Comment by aklausmeier** [comment]
Michelle and I met with IIR team today. They will begin this work and spin up their own tickets on their board based on capacity in their sprints. 

cc @oddballpete
