### ISSUE TITLE
Implement Vet Center CAP geofields

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#8627]
## Description

Vet Center create and edit CAP facilities in Drupal - they are the only VHA facility type that does not get data from VAST. For the Facilty API to accept these, they must have lat/long.

A recommended approach may look something like the following but it needs validating by a developer.

1. Install and configure [geofield](https://www.drupal.org/project/geofield) module
2. Install [geocoder](https://www.drupal.org/project/geocoder) module
3. Configure geocode module use mapbox provider 
4. Add geofields to content type and configure them

## Acceptance Criteria
- [x] Geocoords fields exist in drupal on the Vet Center CAP content type
- [x] Visibility for geocoords is based on role - admins are the only users who can see it
- [x] Coords are calculated based on address using Mapbox as a provider
- [x] Mapbox utilizes credentials stored in documentation via #8733

Not included
- #9544 
- [ ] Separate issue for a KB article.
- [ ] Separate issue for: Cost model is understood and approved by OCTO-DE - what causes lookups?  how often should we expect them (eg number of revisions of Vet Center CAPs per month? Or more future-looking: Number of revisions to an address field per month?). Add this somewhere in the [Vet Center documentation](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/vet-centers), or perhaps in CMS documentation for a broader analysis.
- [ ] Create separate issue: bulk update existing Vet Center CAPs 

### No longer applies
- [ ] ~~Should allow options for pin picker/map UI (possibly https://www.drupal.org/project/geofield_map)~~ (this does not need to be implemented at this time - moved to #9448)
- [ ] ~~Follow up to store creds (#8733)~~

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`

**Comment by msbtterswrth** [comment]
afaik mapbox also generates the coords in addition to displaying the pin selector/map

**Comment by omahane** [comment]
I tested the use of the geocode function under a number of scenarios and came to the following conclusions about when and how the Geolocation field values are created or changed:

# Saving a page with a pre-existing address
When an editor saves a Vet Center Community Access Point page that has an address filled in, the Geolocation field will populate with a latitude and longitude through a call to Mapbox, based on Address field.

# Adding an address 
When an editor adds an address for a Vet Center Community Access Point and save the page, the Geolocation field will populate with a latitude and longitude through a call to Mapbox, based on Address field.

# Changing an address
When an editor changes an address for a Vet Center Community Access Point and save the page, the Geolocation field will change the latitude and longitude through a call to Mapbox, based on the Address field.

# Moving the pin
When an administrator moves a pin on the Geolocation map and saves the page, the Geolocation field will change the latitude and longitude, based on the pin location.
