### ISSUE TITLE
Reusable Q&A on Resources & Support

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#8630]
## Background
**<Overhauled to limit scope to COPE-ified Reusable Q&A on Resources & Support. Outstanding work from original epic definition is now ported to https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10538>**

**Q&A - single node** - This is a standalone content type (which is referenced within Q&A group paragraph) and allows for Q&A content to be reused across the CMS. It has a node title as the question, a paragraph reference to character limited rich text field as the answer, a checkbox to create a standalone page and the ability to add several content components such as alerts, calls to action, related information links, contact information, article categories and tags and related benefit hubs. 
![image](https://user-images.githubusercontent.com/8375335/162208267-8c58f157-3c5d-437d-a02f-d6e8a9ba8345.png)

**FAQ node** - This is a standalone content type which creates a list of multiple Q&As. It contains a paragraph reference to the about Q&A group paragraph, along with several other common content components (nearly identical to the list above in Q&A single nodes).
![image](https://user-images.githubusercontent.com/8375335/162214315-cdf92405-8cd9-434d-87f7-6e4568120021.png)

We want to extend this paradigm to apply to Resources & Support content as well, making Q&A nodes reusable on R&S.

### User Story or Problem Statement
- As a Sitewide Content editor, I want to reuse existing Single Q&A nodes on Resources & Support content
- As a Sitewide Content editor, I want to easily find existing Single Q&A nodes within the Place Q&A modal, and understand the content well enough to build the association with R&S

### Affected users and stakeholders

* CMS editors of R&S content
* Developers of new Next.js content build, PW teams
* Veterans looking for information

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [X] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

**Comment by ContentBrewmaster** [comment]
Added CM triage section and made selection.

**Comment by jilladams** [comment]
Fully launched today, 8/30/22. WIll leave epic open for post-launch monitoring of any issues and close next sprint if none arise.
