### ISSUE TITLE
layout: node--faq_multiple_q_a (FAQ page)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8645]
## Description
A component is needed in the next-build system to render node--faq_multiple_q_a. This component should be able to be used standalone or to render field data for other paragraphs and nodes. 

## Acceptance Criteria
- [ ] A component exists that can render a `node--faq_multiple_q_a` data structure
- [ ] A page exists within the next-build repo that demonstrates the rendering of all `node--faq_multiple_q_a`
- [ ] That component's output is consistent with the existing output of content-build (visually, markup structure)

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16617
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8613
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16601
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16607
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8610
```

## Supporting detail
**node/Node**: `node--faq_multiple_q_a`

**CMS structure**: [`/faq_multiple_q_a/fields`](https://prod.cms.va.gov/admin/structure/types/manage/faq_multiple_q_a/fields)

**API query**:  [`jsonapi/node/faq_multiple_q_a`](https://prod.cms.va.gov/jsonapi/node/faq_multiple_q_a)

**Existing template(s)**:[`faq_multiple_q_a.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/faq_multiple_q_a.drupal.liquid)

**Existing/example existing GraphQL**:[`faqMultipleQa.node.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/faqMultipleQa.graphql.js)

**Logic notes:**

Liquid Template(s): 
#### Header
* `src/site/includes/header.html`
* `src/site/includes/preview-edit.drupal.liquid`
* `src/site/includes/breadcrumbs.drupal.liquid`

#### Body
* `src/site/paragraphs/alert_single.drupal.liquid`
* `src/site/includes/tags.drupal.liquid`
* `src/site/includes/how-do-you-rate.drupal.liquid`
* `src/site/includes/related-information.drupal.liquid`
* `src/site/includes/benefit-hubs-links.drupal.liquid`
* `src/site/paragraphs/contact_information.drupal.liquid`
* `src/site/includes/last-updated.drupal.liquid`

#### Footer
* `src/site/includes/footer.html`
* `src/site/includes/debug.drupal.liquid`
---

#### Functionality
* If `fieldTableOfContentsBoolean` show 'table-of-contents'
* When `fieldAlertSingle` equals `true` include fieldAlertSingle
* When `lists_of_links` equals `true` include browse-by-audience
* When `fieldButtonsRepeat` equals `true` render repeated buttons

**Example to render collection of <component> objects**:

```javascript
    const node--faq_multiple_q_a = await getResourceCollectionFromContext(
        'node--faq_multiple_q_a',
        context,
        {} // params 
    );
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "node--faq_multiple_q_a",
    "id": "0eb99770-bcfd-49e8-9abb-8d9724c3094d",
    "drupal_internal__nid": 8487,
    "drupal_internal__vid": 339178,
    "langcode": "en",
    "revision_timestamp": "2020-11-04T21:54:45+00:00",
    "revision_log": "Bulk operation publish revision",
    "status": true,
    "title": "My HealtheVet FAQs",
    "created": "2020-10-16T22:04:51+00:00",
    "changed": "2020-11-04T21:54:45+00:00",
    "promote": false,
    "sticky": false,
    "default_langcode": true,
    "revision_translation_affected": true,
    "moderation_state": "published",
    "metatag": null,
    "path": {
        "alias": "/resources/my-healthevet-faqs",
        "pid": 11199,
        "langcode": "en"
    },
    "field_buttons_repeat": false,
    "field_intro_text_limited_html": {
        "value": "<p>Get answers to questions you may have about your <strong>My HealtheVet</strong> account.</p>\r\n",
        "format": "rich_text_limited",
        "processed": "<p>Get answers to questions you may have about your <strong>My HealtheVet</strong> account.</p>\n"
    },
    "field_table_of_contents_boolean": false,
    "links": {
        "self": {
            "href": "http://va-gov-cms.ddev.site/jsonapi/node/faq_multiple_q_a/0eb99770-bcfd-49e8-9abb-8d9724c3094d?resourceVersion=id%3A339178"
        }
    },
    "node_type": {
        "type": "node_type--node_type",
        "id": "7394512d-b597-414d-8acf-6e3d447a8510",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": "faq_multiple_q_a"
        }
    },
    "revision_uid": {
        "type": "user--user",
        "id": "38daa8d4-3d05-48a3-bb95-a9c75988e382",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 295
        }
    },
    "uid": {
        "type": "user--user",
        "id": "ee1fb49c-70d5-4e82-9b0d-e6c73dde0489",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 1343
        }
    },
    "field_administration": {
        "type": "taxonomy_term--administration",
        "id": "40ef8d64-fa92-41b6-88c0-4d85dc24e191",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 194
        }
    },
    "field_alert_single": null,
    "field_buttons": [
        {
            "type": "paragraph--button",
            "id": "4e756327-b07e-4fa7-8ad4-d02e1f9dd5ad",
            "resourceIdObjMeta": {
                "target_revision_id": 158207,
                "drupal_internal__target_id": 13645
            }
        },
        {
            "type": "paragraph--button",
            "id": "c3371ec7-008b-4088-906f-6d38850d2ab1",
            "resourceIdObjMeta": {
                "target_revision_id": 158208,
                "drupal_internal__target_id": 14073
            }
        }
    ],
    "field_contact_information": {
        "type": "paragraph--contact_information",
        "id": "b7dd2aac-28ba-4e1e-8520-94a078ca4035",
        "resourceIdObjMeta": {
            "target_revision_id": 158209,
            "drupal_internal__target_id": 13646
        }
    },
    "field_other_categories": [],
    "field_primary_category": {
        "type": "taxonomy_term--lc_categories",
        "id": "5414620f-a6bd-4e05-bafb-c8efde0e3fea",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 282
        }
    },
    "field_q_a_groups": [
        {
            "type": "paragraph--q_a_group",
            "id": "fdf388e5-6ab2-456e-b073-ab9fc4a13aa5",
            "resourceIdObjMeta": {
                "target_revision_id": 158210,
                "drupal_internal__target_id": 13647
            }
        }
    ],
    "field_related_benefit_hubs": [
        {
            "type": "node--landing_page",
            "id": "fd822f25-788f-489c-a0fc-b1f7ad6c20d5",
            "resourceIdObjMeta": {
                "drupal_internal__target_id": 67
            }
        }
    ],
    "field_related_information": [
        {
            "type": "paragraph--link_teaser",
            "id": "93a3624c-b661-46ed-b073-49324a621211",
            "resourceIdObjMeta": {
                "target_revision_id": 154967,
                "drupal_internal__target_id": 13648
            }
        },
        {
            "type": "paragraph--link_teaser",
            "id": "d15a0b25-2443-44e4-b7ce-155fdba6b216",
            "resourceIdObjMeta": {
                "target_revision_id": 154953,
                "drupal_internal__target_id": 14074
            }
        }
    ],
    "field_tags": {
        "type": "paragraph--audience_topics",
        "id": "ddf9435a-3d5c-4122-a147-402b8a2bd974",
        "resourceIdObjMeta": {
            "target_revision_id": 158211,
            "drupal_internal__target_id": 13649
        }
    },
    "relationshipNames": [
        "node_type",
        "revision_uid",
        "uid",
        "field_administration",
        "field_alert_single",
        "field_buttons",
        "field_contact_information",
        "field_other_categories",
        "field_primary_category",
        "field_q_a_groups",
        "field_related_benefit_hubs",
        "field_related_information",
        "field_tags"
    ]
}
```

Further info:[`nodes/faq_multiple_q_a.md`](https://github.com/department-of-veterans-affairs/content-api-react-poc/blob/main/references/content-types/faq_multiple_q_a.md)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
