### ISSUE TITLE
layout: node--q_a (Reusable Q&A)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8650]
## Description
A component is needed in the next-build system to render node--q_a. This component should be able to be used standalone or to render field data for other paragraphs and nodes. 

## Acceptance Criteria
- [ ] A component exists that can render a `node--q_a` data structure
- [ ] A page exists within the next-build repo that demonstrates the rendering of all `node--q_a`
- [ ] That component's output is consistent with the existing output of content-build (visually, markup structure)

```[tasklist]
### Tasks
- [ ] tnh
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16617
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16607
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8639
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8610
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16616
```

## Supporting detail
**Node**: `node--q_a`

**CMS structure**: [`/q_a/fields`](https://prod.cms.va.gov/admin/structure/types/manage/q_a/fields)

**API query**:  [`jsonapi/node/q_a`](https://prod.cms.va.gov/jsonapi/node/q_a)

**Existing template(s)**:[`q_a.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/q_a.drupal.liquid)

**Existing/example existing GraphQL**:[`nodeQa.node.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/nodeQa.graphql.js)

**Logic notes:**

#### Header
* `src/site/includes/header.html`
* `src/site/includes/preview-edit.drupal.liquid`
* `src/site/includes/breadcrumbs.drupal.liquid`

#### Body
* `src/site/includes/support_resources_search_bar.drupal.liquid`
* `src/site/paragraphs/alert_single.drupal.liquid`
* `src/site/paragraphs/action_link.drupal.liquid`
* `src/site/paragraphs/`
* `src/site/includes/tags.drupal.liquid`
* `src/site/includes/how-do-you-rate.drupal.liquid`
* `src/site/includes/related-information.drupal.liquid`
* `src/site/includes/benefit-hubs-links.drupal.liquid`
* `src/site/paragraphs/contact_information.drupal.liquid`
* `src/site/includes/last-updated.drupal.liquid`
#### Footer
* `src/site/includes/footer.html`
* `src/site/includes/debug.drupal.liquid`

**Example to render collection of <component> objects**:

```javascript
    const node--q_a = await getResourceCollectionFromContext(
        'node--q_a',
        context,
        {} // params 
    );
```

**Example data structure (subject to refinement)**:
```javascript
{
    "type": "node--q_a",
    "id": "c2839a4c-c13d-46da-b448-9d1ec389773b",
    "path": {
        "alias": "/resources/how-can-i-find-out-my-va-claim-or-appeal-status",
        "pid": 11255,
        "langcode": "en"
    },
    "drupal_internal__nid": 8504,
    "drupal_internal__vid": 339129,
    "langcode": "en",
    "revision_timestamp": "2020-11-04T21:54:28+00:00",
    "revision_log": "Bulk operation publish revision",
    "status": true,
    "title": "How can I find out the status of my claim, appeal, or decision review?",
    "created": "2020-10-19T17:10:51+00:00",
    "changed": "2020-11-04T21:54:28+00:00",
    "promote": false,
    "sticky": false,
    "default_langcode": true,
    "revision_translation_affected": true,
    "moderation_state": "published",
    "metatag": null,
    "field_standalone_page": false,
    "links": {
        "self": {
            "href": "http://va-gov-cms.ddev.site/jsonapi/node/q_a/c2839a4c-c13d-46da-b448-9d1ec389773b?resourceVersion=id%3A339129"
        }
    },
    "node_type": {
        "type": "node_type--node_type",
        "id": "e1c04503-bcc8-4285-b2be-fa27af3634e4",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": "q_a"
        }
    },
    "revision_uid": {
        "type": "user--user",
        "id": "38daa8d4-3d05-48a3-bb95-a9c75988e382",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 295
        }
    },
    "uid": {
        "type": "user--user",
        "id": "ee1fb49c-70d5-4e82-9b0d-e6c73dde0489",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 1343
        }
    },
    "field_administration": {
        "type": "taxonomy_term--administration",
        "id": "40ef8d64-fa92-41b6-88c0-4d85dc24e191",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 194
        }
    },
    "field_alert_single": {
        "type": "paragraph--alert_single",
        "id": "56238257-28ed-4af2-9160-f32d9d978e0e",
        "resourceIdObjMeta": {
            "target_revision_id": 161346,
            "drupal_internal__target_id": 13769
        }
    },
    "field_answer": {
        "type": "paragraph--rich_text_char_limit_1000",
        "id": "9ce955a1-756d-4ef7-a9b9-7f2bbe80795a",
        "resourceIdObjMeta": {
            "target_revision_id": 161347,
            "drupal_internal__target_id": 13987
        }
    },
    "field_buttons": [
        {
            "type": "paragraph--button",
            "id": "203de085-bb3c-4655-b8ca-0d859a65f5b6",
            "resourceIdObjMeta": {
                "target_revision_id": 158766,
                "drupal_internal__target_id": 13772
            }
        }
    ],
    "field_contact_information": {
        "type": "paragraph--contact_information",
        "id": "d7927466-770d-4fc0-b28b-3bf653f893ba",
        "resourceIdObjMeta": {
            "target_revision_id": 161348,
            "drupal_internal__target_id": 13773
        }
    },
    "field_other_categories": [],
    "field_primary_category": {
        "type": "taxonomy_term--lc_categories",
        "id": "3f79ad6d-7146-464c-9f6a-c3546a90d9a7",
        "resourceIdObjMeta": {
            "drupal_internal__target_id": 283
        }
    },
    "field_related_benefit_hubs": [
        {
            "type": "node--landing_page",
            "id": "0ba73178-25c7-449b-986d-c35a7ea8060a",
            "resourceIdObjMeta": {
                "drupal_internal__target_id": 3071
            }
        },
        {
            "type": "node--landing_page",
            "id": "ac8b805b-e5b7-4cdb-b4c4-fb81956bac65",
            "resourceIdObjMeta": {
                "drupal_internal__target_id": 68
            }
        },
        {
            "type": "node--landing_page",
            "id": "fd822f25-788f-489c-a0fc-b1f7ad6c20d5",
            "resourceIdObjMeta": {
                "drupal_internal__target_id": 67
            }
        }
    ],
    "field_related_information": [
        {
            "type": "paragraph--link_teaser",
            "id": "b5dc447b-5832-4a3f-9e4b-b96cf08a9207",
            "resourceIdObjMeta": {
                "target_revision_id": 158768,
                "drupal_internal__target_id": 13774
            }
        },
        {
            "type": "paragraph--link_teaser",
            "id": "7de62b28-028d-40a1-bafa-fc1113c47aeb",
            "resourceIdObjMeta": {
                "target_revision_id": 158769,
                "drupal_internal__target_id": 13778
            }
        },
        {
            "type": "paragraph--link_teaser",
            "id": "1af2cc04-07c7-4afa-86c9-6ae32b363d32",
            "resourceIdObjMeta": {
                "target_revision_id": 158770,
                "drupal_internal__target_id": 14131
            }
        }
    ],
    "field_tags": {
        "type": "paragraph--audience_topics",
        "id": "d7dd0c3a-5b28-4bb7-8a57-aa520fa7248b",
        "resourceIdObjMeta": {
            "target_revision_id": 161349,
            "drupal_internal__target_id": 13779
        }
    },
    "relationshipNames": [
        "node_type",
        "revision_uid",
        "uid",
        "field_administration",
        "field_alert_single",
        "field_answer",
        "field_buttons",
        "field_contact_information",
        "field_other_categories",
        "field_primary_category",
        "field_related_benefit_hubs",
        "field_related_information",
        "field_tags"
    ]
}
```

Further info:[`nodes/q_a.md`](https://github.com/department-of-veterans-affairs/content-api-react-poc/blob/main/references/content-types/q_a.md)

### CMS Team
Please check the team(s) that will do this work. 

- [ ] `CMS Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide CMS Team ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Offices`
  - [ ] `⭐️ Product support`
  - [ ] `⭐️ User support`
