### ISSUE TITLE
layout: node--step_by_step (Step-by-Step)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8651]
## Description
We need a layout for Step by Step content. Example pages:
- https://www.va.gov/resources/how-to-check-in-with-your-smartphone-for-some-va-appointments/
- https://www.va.gov/resources/how-to-check-your-va-claim-appeal-or-decision-review-status-online/

## Acceptance Criteria
- [ ] Step by step page content renders correctly
- [ ] The layout output is consistent with the existing output of content-build (visually and functionally)

```[tasklist]
### Tasks
- [ ] type definitions - Drupal node type, Next Build page type
- [ ] query definition - query drupal data, map to next bulid type
- [ ] tests for query/formatter
- [ ] layout component
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8641
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16617
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8610
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8613
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16607
```

## Supporting detail
**CMS field implementation:** https://prod.cms.va.gov/admin/structure/types/manage/step_by_step/fields

**Content build template:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/layouts/step_by_step.drupal.liquid

**Content build base GraphQl query:** https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/stages/build/drupal/graphql/nodeStepByStep.graphql.js

**API query for individual node:** https://prod.cms.va.gov/jsonapi/node/step_by_step/769ed6f8-1cc8-4941-825e-40fa9cc9d35b?include=field_alert_single,field_buttons,field_contact_information,field_primary_category,field_other_categories,field_related_benefit_hubs,field_related_information,field_steps,field_tags

**Includes:**
```
field_alert_single
field_buttons
field_contact_information
field_primary_category
field_other_categories
field_related_benefit_hubs
field_related_information
field_steps
field_tags
```
Note: the includes for this are very nested. Many of these fields are also on Resources & Support, and I recommend looking at its query for equivalents. There is a mechanism in that query for getting nested includes.

**Logic notes:**
You can ignore search for this ticket. We need to implement search separately. It is shared by several content types, and will be done at once.

It looks like there will need to be some conversion of number to word; see `numToWord` in the content-build template.
