### ISSUE TITLE
layout: node--support_resources_detail_page (Resources and Support Detail Page)

### ISSUE THREAD

**Issue by amponce** [department-of-veterans-affairs/va.gov-cms#8653]
## Description
A component is needed in the next-build system to render node--support_resources_detail_page. This component should be able to be used standalone or to render field data for other paragraphs and nodes. 

## Acceptance Criteria
- [ ] A component exists that can render a `node--support_resources_detail_page` data structure
- [ ] A page exists within the next-build repo that demonstrates the rendering of all `node--support_resources_detail_page`
- [ ] That component's output is consistent with the existing output of content-build (visually, markup structure)

```[tasklist]
### Tasks
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16617
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8608
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8612
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8636
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8613
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16607
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8610
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8642
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8605
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16601
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8616
- [ ] https://github.com/department-of-veterans-affairs/va.gov-cms/issues/16616
```

## Supporting detail
**Node**: `node--support_resources_detail_page`

**CMS structure**: [`/support_resources_detail_page/fields`](https://prod.cms.va.gov/admin/structure/types/manage/support_resources_detail_page/fields)

**API query**:  [`jsonapi/node/support_resources_detail_page`](https://prod.cms.va.gov/jsonapi/node/support_resources_detail_page)

**Existing template(s)**:[`support_resources_detail_page.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/layouts/support_resources_detail_page.drupal.liquid)

**Existing/example existing GraphQL**:[`nodeSupportResourcesDetailPage.node.graphql.js`](https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/nodeSupportResourcesDetailPage.graphql.js)

Liquid Template(s): 

#### Body
* `src/site/includes/support_resources_search_bar.drupal.liquid`
* `src/site/paragraphs/alert_single.drupal.liquid`
* `src/site/paragraphs/action_link.drupal.liquid`
* `src/site/paragraphs/`
* `src/site/includes/tags.drupal.liquid`
* `src/site/includes/how-do-you-rate.drupal.liquid`
* `src/site/includes/related-information.drupal.liquid`
* `src/site/includes/benefit-hubs-links.drupal.liquid`
* `src/site/paragraphs/contact_information.drupal.liquid`
* `src/site/includes/last-updated.drupal.liquid`

Further info:[`nodes/support_resources_detail_page.md`](https://github.com/department-of-veterans-affairs/content-api-react-poc/blob/main/references/content-types/support_resources_detail_page.md)

**Comment by timcosgrove** [comment]
Flesh out details of what needs to be done re: rendering a paragraph field with multiple items of multiple types in a resuable fashion.
