### ISSUE TITLE
Keep OS-level dependencies up-to-date

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#8660]
### Tasks:
- [ ] Determine the difference between the encrypted AMI build and the app AMI build. If it's necessary, change the encrypted AMI build to happen daily so that app AMI builds are using the most recent version of packaged software.
- [ ] Install unattended upgrades and configure it to run on boot + periodically (suggested starting point is every 30-60 minutes)
- [ ] Audit the ansible playbooks to find places where we're manually downloading stuff and dropping it into /usr/bin or downloading some random RPM from the internet and installing it. Migrate all installation tasks to yum if possible. 
    - [ ] Remove scl-utils installation if it's no longer needed
    - [ ] Remove boto3/botocore installation via pip if it's no longer needed
    - [ ] Remove apcu if it's no longer needed

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide crew `
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by TheBoatyMcBoatFace** [comment]
Closing due to inactivity. Reopen if needed.
