### ISSUE TITLE
Create Cypress step definitions for parity with Behat

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8672]
## Description

There are step definitions that need to be added to give Cypress full feature parity with Behat.

### Example Step Definition
```javascript
Given(`I click the {string} link`, (text) => {
  cy.contains(text).click({ force: true });
});
```

## Acceptance Criteria
- [x] The below step definitions have been ported to Cypress.  
- [x] Tests continue to pass as expected on Tugboat and BRD.

## Implementation Steps

The following step definitions need to be added to Cypress:  

- [x] "I select the <text> radio button" step definition should be ported, but this is trivial because [it's supported in Cypress](https://docs.cypress.io/api/commands/check).  [10 minutes]
- [x] "I release content" step definition to substitute for "I run :command" in `decoupled.feature`.  [15 minutes]
- [x] "I create a taxonomy term" step definition, paralleling "I create a node", and including wrapping the variables and such for the newly created term. [15 minutes]
- [x] "Then the xpath :expression should have no matches" (reworded), involves adding a package like https://www.npmjs.com/package/cypress-xpath [15 minutes]
- [x] "Then :element should have the attribute :attribute", involves adding a package like https://www.chaijs.com/plugins/chai-jquery/ [15 minutes]
- [x] "Then :element should have the attribute :attribute with value :value", extended from above [10 minutes]
- [x] "Then :element should have the attribute :attribute containing value :value", extended from above [10 minutes]
- [x] "Then :element should have the attribute :attribute matching pattern :pattern", extended from above [10 minutes]
- [x] "Then I set the node with title :title to :status" would need to be rewritten, but is mostly a matter of selecting an option and saving [15 minutes]
- [x] "Then I fill in :locator with the text :Value" would need to be slightly rewritten and include refactoring an existing step definition, but it's straightforward [30 minutes]
- [x] "Then the :option from :select should be selected" needs a rewrite but it's just verification with a couple of built-in Cypress commands [30 minutes]
- [x] "Then :selector should contain :item" needs a rewrite for clarity, but should be straightforward [15 minutes]
- [x] "Then :selector should not contain :item" should be a simple extension from above [10 minutes]

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`
