### ISSUE TITLE
Create Cypress tests to replace existing Behat tests

### ISSUE THREAD

**Issue by ndouglas** [department-of-veterans-affairs/va.gov-cms#8675]
## Description

There are Behat tests that need to be recreated in Cypress and removed from Behat.

## Acceptance Criteria
- [x] The below tests have been ported to Cypress with no loss of reliability or have been ported to another test system or deleted as appropriate.

## Implementation steps

- [tests/behat/features/content_editing.feature](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tests/behat/features/content_editing.feature):
  - [x] Scenario: Log in and confirm that System-wide alerts can be created and edited
    - This is quite important.
    - This should be ported but we should improve its implementation.
  - [x] Scenario Outline: Confirm that content cannot be published directly from the node view but can from the node edit form.
    - This is probably a very, very slow test.
    - Think of how to refactor this to give a similar breadth of coverage more efficiently.
    - This might be done better as a unit test on a hook rather than a behavioral test.
  - [x] Scenario: Confirm Generate automatic URL alias is unchecked after node publish.
    - This is really a behavioral test that is confirming that a hook works as intended.
    - Rewrite as a unit test IMHO.
  - [x] Scenario: Confirm Generate automatic URL alias is unchecked after taxonomy term publish.
    - This should be a unit test IMHO.
  - [x] Confirm field group is opened and the required field is presented to editor on CLP page.
    - This might be reevaluated for utility.

- [tests/behat/features/decoupled.feature](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tests/behat/features/decoupled.feature):
  - [x] Scenario: Log in, edit, publish, unpublish, and save nodes and see changes in the CMS and the front end website. Confirm cms menu items are in static site build.
    - Probably add some step definitions here.
    - Revisit scenario title and verify correctness in light of recent changes.

- [tests/behat/features/perms.feature](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tests/behat/features/perms.feature):
  - [x] Scenario: Content Admins should be able to browse sections from their profile even if none have been specifically assigned to them
    - There're existing Cypress tests that cover adjacent functionality.  This should be a quick port, assuming it's not already present.

- [tests/behat/features/save_and_continue.feature](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/tests/behat/features/save_and_continue.feature):
  - [x] Scenario: Log in, edit, and save nodes with save and continue button and confirm revision saves changes.
    - This should be rephrased in terms of Cypress step definitions for brevity.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`
