### ISSUE TITLE
Vet Center CAPs with geodata

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8683]
### User Story or Problem Statement

Lighthouse can't use Vet Center CAP data unless it has Lat/long. (see #5375)

## Acceptance Criteria
- [x] Determine what level of access should be able to edit the pins: content admins or editors?
- [x] CMSx design input on map UI; possibly use https://www.drupal.org/project/geofield_map
- [x] We fetch and store lat/long for Vet Center CAPs upon save (#8627)
- [x] Get mapbox API keys for Sitewide CMS team use and store them in settings (#8733)
- [x] Existing 278+ Vet Center CAPs get lat/long 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [x] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [x] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Related https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8587#issuecomment-1095481266

**Comment by EWashb** [comment]
Removing Lynn from this ticket now that we have split out into separate streams. This is more facilities wheelhouse.

**Comment by jilladams** [comment]
Dupe of #42556, closing

**Comment by kevwalsh** [comment]
I've removed the push to lighthouse from this epic because it's blocked by Lighthouse V1

**Comment by jilladams** [comment]
Closing. Work described here has been completed. Remaining Lighthouse V1 data for CAPs is captured in #9727
