### ISSUE TITLE
Component: block_content--alert

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8688]
## Description
A component is needed in the next-build system to render alert Content Blocks. This component should be able to be used standalone or to render field data for other nodes and paragraphs.

## Acceptance Criteria
- [x] A component exists that can render a `block_content--alert` data structure
- [x] A page exists within the next-build repo that demonstrates the rendering of all `block_content--alert`
- [x] That component's output is consistent with the existing output of content-build (visually, markup structure)

## Tasks
- [x] Create generalized component for Alert and Promo
- [x] Add component to demo page
- [x] Unit tests

## Supporting detail
**Block type**: `alert`

**CMS structure**: https://prod.cms.va.gov/admin/structure/block/block-content/manage/alert/fields

**API query**: https://prod.cms.va.gov/jsonapi/block_content/alert

**Existing template(s)**: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/blocks/alert.drupal.liquid

**Existing/example existing GraphQL**: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/drupal/graphql/paragraph-fragments/alert.paragraph.graphql.js#L30

**Example to retrieve collection of block_content--alert objects**:
```javascript
    const resourceCollection = await getResourceCollectionFromContext(
        'block_content--alert',
        context,
        {} // params
    );
```

**Example data structure (subject to refinement)**:
```
{
  "type": "block_content--alert",
  "id": "838295c0-0263-4b6d-98fc-c02c73ba0057",
  "links": {
    "self": {
      "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057"
    }
  },
  "attributes": {
    "drupal_internal__id": 3,
    "drupal_internal__revision_id": 165,
    "langcode": "en",
    "revision_created": "2019-06-04T17:39:26+00:00",
    "revision_log": null,
    "status": true,
    "info": "You'll need to go to eBenefits to authorize us to share your health information through the Veterans Health Information Exchange.",
    "changed": "2019-06-04T17:39:26+00:00",
    "reusable": true,
    "default_langcode": true,
    "revision_translation_affected": true,
    "moderation_state": "published",
    "metatag": null,
    "field_alert_title": "You'll need to go to eBenefits to authorize us to share your health information through the Veterans Health Information Exchange.",
    "field_alert_type": "information",
    "field_reusability": "reusable"
  },
  "relationships": {
    "block_content_type": {
      "data": {
        "type": "block_content_type--block_content_type",
        "id": "278a3f4b-8d89-4768-ab03-869b8cc98613",
        "meta": {
          "drupal_internal__target_id": "alert"
        }
      },
      "links": {
        "related": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/block_content_type"
        },
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/relationships/block_content_type"
        }
      }
    },
    "revision_user": {
      "data": {
        "type": "user--user",
        "id": "fd71292f-3dc7-409d-b0e8-500204cb005a",
        "meta": {
          "drupal_internal__target_id": 65
        }
      },
      "links": {
        "related": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/revision_user"
        },
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/relationships/revision_user"
        }
      }
    },
    "field_alert_content": {
      "data": {
        "type": "paragraph--expandable_text",
        "id": "a4996639-adb4-4ab5-bd47-35b535f77886",
        "meta": {
          "target_revision_id": 14581,
          "drupal_internal__target_id": 4036
        }
      },
      "links": {
        "related": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/field_alert_content"
        },
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/relationships/field_alert_content"
        }
      }
    },
    "field_owner": {
      "data": {
        "type": "taxonomy_term--administration",
        "id": "e9139b86-b694-4e4a-a156-7fc8fc14485d",
        "meta": {
          "drupal_internal__target_id": 10
        }
      },
      "links": {
        "related": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/field_owner"
        },
        "self": {
          "href": "https://prod.cms.va.gov/jsonapi/block_content/alert/838295c0-0263-4b6d-98fc-c02c73ba0057/relationships/field_owner"
        }
      }
    }
  }
},
```

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`
