### ISSUE TITLE
<Summary of enhancement>

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#8696]
## User Story or Problem Statement

As a site builder or information architect I would like an audit tool that shows me at a glance all fields in use in the system
* field names
* View default mode
* Edit form
* list of entities using it.

other details to consider for display
- visibilty
- cardinality on each use
- display modes  (how to show different display used on each bundle... that could get challenging and messy but would reveal help text, titles and descriptions).

## crude example:
![image](https://user-images.githubusercontent.com/5752113/162449700-75d59226-174a-400b-b756-13d9adf956b4.png)

## Acceptance Criteria
- [ ] Contributed module (field_audit) is already taken but not supported... could take it over.
- [ ]  more fleshed out details than the model ^^
- [ ] 
- [ ] 
## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This is just a concept.   No one is currently asking for this.

**Comment by swirtSJW** [comment]
The pre-existing D7 module field_audit had a place for notes on each.
