### ISSUE TITLE
Make Tugboat Training demo environment available via consistent URL

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8747]
## User Story or Problem Statement

As a CMS engineer, I need to route all traffic through a new proxy URL so that editors can access the training demo environment via both the original and updated URLs.

## Acceptance Criteria
- [ ] Users can access training.cms.va.gov which is routed to the Tugboat training environment

## Implementation steps
* Use AWS API Gateway HTTP passthrough
* Will need a new cert for training.cms.va.gov OR add that to the current cert which has *.ci.cms.va.gov and *.demo.cms.va.gov on it.
* We tried training.demo.cms.va.gov, but the DNS seems to get intercepted by our *.demo.cms.va.gov DNS and routes to Tugboat proper, never making it to the API Gateway config. 

- [x] Create new cert for training.cms.va.gov
- [x] Add new cert to balancer
- [x] Route53 DNS CNAME
- [x] Balancer rule to redirect
- [ ] Terraform the above

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/integration-passthrough-behaviors.html

**Comment by ElijahLynn** [comment]
https://medium.com/@lancers/amazon-api-gateway-explaining-http-proxy-in-http-api-3ea0afe6b03c

**Comment by ElijahLynn** [comment]
https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html

**Comment by ElijahLynn** [comment]
Slack discussion around trying to PoC this. 

https://dsva.slack.com/archives/C02HX4AQZ33/p1649968497438679

**Comment by ElijahLynn** [comment]
I started officially on this today, [ducking here](https://dsva.slack.com/archives/C02HX4AQZ33/p1651525392456469), and the basic path is to setup an AWS API Gateway (REST, not HTTP) with a private VPC Link. But I'm running into issues with complexity around this and VPC peering. 

I'm thinking we may want to just spend the time to build this feature natively into Tugboat itself. That is the right way to do it anyways, and ideally a UI view and update the URL Alias would be the best UX. Otherwise we will perpetually be making Terraform changes to update/add/delete aliases etc. 

Even if we get it working, the API Gateway route requires API Gateway, Route53, NLB, Target Group resources, VPC Links and maybe more. Not saying it cannot be done but the complexity is a bit up there to make a simple change to this, not for us but for newly onboarded devops engineers.

**Comment by ElijahLynn** [comment]
I'm still having trouble registering the correct target group to the NLB. I wonder if we should consider just doing a redirect, which was our fallback that @ndouglas suggested, I think.

**Comment by ElijahLynn** [comment]
K, so I chose the route of adding a rule to our ALB per https://aws.amazon.com/premiumsupport/knowledge-center/route-53-redirect-to-another-domain/. It is working now. Still working on getting it into TF though.

**Comment by ElijahLynn** [comment]
Draft PR is here > https://github.com/department-of-veterans-affairs/devops/pull/11201

**Comment by ElijahLynn** [comment]
This is done now, and I created a document on how to do this if we need to do it again. 

https://vfs.atlassian.net/wiki/spaces/PCMS/pages/2192670825/How+to+create+a+new+domain+alias+for+Tugboat
