### ISSUE TITLE
Update Lower Environment Single Sign-On Internal SAML Certificate

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8748]
## Description
Single Sign-On Internal team is updating their certificates:

> SSOi SAML partners, (Action Required – Certificate Update
The IAM team will be replacing the IDP SSOi SAML certificate in the lower environments (Dev, iDev, SQA, PreProd) on Wednesday April 27, 2022, at 10:00 AM Eastern.
This activity will require action from SSOi SAML Partners Only (NOT WebAgent, OAuth, or STS Partners).
Upon completion of the certificate update, Partners will be required to update the new SSOi SAML certificate in their lower environment keystores.  We will send another notification on Tuesday April 19, 2022, with the updated certificate.
Please note, the required action of SSOi SAML Partners is to replace the existing SSOi SAML certificate with the new certificate provided and to conduct post replacement testing. 
Partners wanting to automate the IdP certificate change can use the new SSOi federation metadata service**.  More information can be found on the SSOi playbook (see Metadata Service)

## Acceptance Criteria
- [ ] Lower environments (dev, staging) have new SSOI SAML Certificate installed, by April 26, 2022 ahead of IAM team update
- [ ] PIV login to lower environments works successfully
- [ ] Ensure "how to" documentation is up to date 

## Implementation Steps

* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md
* https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-braindump.md#testing-login
