### ISSUE TITLE
[cms-ci] BRDize the CMS-CI application

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#875]
Get the CMS-CI application into the BRD system (devops repo) so that we can have a DEV, STAGING, PROD environment for devshop.cms.va.gov to test upstream updates and deploy the latest code. 

This will require:
  - [ ] Getting BRD Playbook code up to date to match what is currently deployed. We had made some manual changes on the live server to meet a deadline. This is technical debt in that sense. 
  - [ ] Setup some Terraform to provision RDS, balancer and security groups.
  - [ ] Setup Jenkins jobs to trigger the deploys and any backups. Define these first.
  - [ ] Setup DNS for dev.devshop.cms.va.gov, staging.devshop.cms.va.gov, prod.devshop.cms.va.gov. And dev.ci.cms.va.gov, staging.ci.cms.va.gov, prod.ci.cms.va.gov. 

This is a partial carry over of this epic in Jira that we are migrating from, https://va-gov.atlassian.net/browse/VAGOV-6145. "CMS-CI BRD Ansible Playbook Finalization"

**Comment by ElijahLynn** [comment]
Closing for now as we are likely moving off of DevShop.
