### ISSUE TITLE
Improve help text for story image field

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8765]
## User Story or Problem Statement

As an editor, I want to know how my story's image will be displayed on my VAMC website. 

## Acceptance Criteria
- [ ] Help text is added `Stories display images with a 2:1 aspect ratio. If you want to crop and size your image before uploading, we recommend 1440x720 pixels.` (pending UX writing and confirmation of ideal pixel size)

<img width="850" alt="Create_Story___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/163415861-9bf4eec0-6bfe-4461-b95c-e70de864b1b1.png">

## Implementation steps
Field config

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [x] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [x] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
See also https://github.com/department-of-veterans-affairs/va.gov-cms/issues/12375

**Comment by xiongjaneg** [comment]
Jordan updated the image help text for campaign landing pages when we decided to change the crop to a 1:1. We could write something similar to this.
[Link to Figma file](https://www.figma.com/file/WBMLh7tvl4FIb1ZLYFHn3h/Campaign-Landing-Pages?type=design&node-id=0%3A1&mode=design&t=0txPxQzghy2lMGNp-1)

**Comment by mmiddaugh** [comment]
For future reference: [Drupal CMS Image Upload Research Findings](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/facilities/medical-centers/research/2024%20VAMC%20CMS/ImageUploader/PostStudy/Findings)
