### ISSUE TITLE
Deep dive on Facility Locator - Engineering, Product, Design

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#8767]
## User Story or Problem Statement

As a member of the Facilities team, I want to understand the Facility Locator product, so that I can design and develop iterations on it. 

Engineering
- Where does it get its data? An intermediate call (Vets API), not Lighthouse itself. "An open window next to a locked door".
  - Connects to Vets API to get the key to Lighthouse / Facility API and PPMS
- Testing stack
- How to run locally
- How to run in a shared environment
- How do react widgets operate 

Product / Design
- Analytics - how are Veterans using Facility Locator, what are the user flows, what are associated funnels 
- Previous Veteran research 

## Acceptance Criteria
- [ ] Each discipline has an understanding of the Facility Locator product, and each has been shared across the team

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by davidmpickett** [comment]
All issues complete
