### ISSUE TITLE
[SPIKE] Next-build: Preview

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#8785]
## Description

Spike/stub for setting up preview.  Products that are migrated to the next-build system will need to point to next-build, while products remaining in content build will need to point to content-build preview. We also need to account for assigning next-drupal preview to its own tab, rather than using the node view tab, which is next-drupal's default.

## Acceptance Criteria
- [x] Research options, determine and document proposed approach
  - Discuss options with Sitewide team 
- [x] Create follow up tickets for implementation
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9885
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9886
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9887
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9888
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9889
  * https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9891

## Tasks
- [x] Review next-drupal's default preview functionality
- [x] Determine best UX for preview going forward, with advice from Sitewide UX/design
  * Given a confluence of situations on the CMS team at the moment, we will opt to keep the preview experience identical to the current one, and make any upgrades to the preview experience a separate effort. 
- [x] Create tickets for work including setting dependencies

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [x] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [ ] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Putting preview in CMS only may compromise our ability to develop on certain features/user stories, like the ones in #9428. Just a consideration!

**Comment by timcosgrove** [comment]
Default setup for preview:
* set up a Next.js 'site' for the given environment, which establishes where the nextjs site feeding that environment is running
* set up a role & user which grants access to Drupal for the purposes of reading unpublished content
* set up a consumer w/ oauth keys to allow communication between Next and Drupal; grant the consumer 
* set up a nextjs entity which establishes behavior for a given entity with respect to node display

**Comment by timcosgrove** [comment]
@kevwalsh 
> Putting preview in CMS only may compromise our ability to develop on certain features/user stories, like the ones in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9428. Just a consideration!

We will make sure a preview-only link is available. A preview link with draft content may be difficult, however. From the linked ticket: 

> As an editor, I need to share a preview link of an Event with stakeholders on and off the VA network for review before publishing (Requestors: VEO and VBA)

This effectively would require access to the CMS be available to the public, which is not on the roadmap for quite some time, and it would require the CMS to allow unauthenticated access to draft content, which is dangerous. The linked story will require a fair amount of discussion with Platform.

The work done in the current ticket (#8785 and follow-up tickets) will not make #9428 more or less difficult; but, #9428 may not be possible for some time, if at all.

**Comment by timcosgrove** [comment]
@kevwalsh also to be clear, putting preview into its own tab will not preclude preview being available at a dedicated link, in-network. However, draft content would need to be discussed even in this context.

**Comment by timcosgrove** [comment]
* nextjs role (config)
* nextjs user (content)
* nextjs site (config)
* simple oauth settings (config) (includes key references)
* consumer (config entity)

**Comment by timcosgrove** [comment]
https://nextjs.org/docs/advanced-features/preview-mode

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9885 for the SitePreviewer

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9886 for preview servers per environment

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9887 for the ability to change branch for the preview server on Tugboat environments

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9888 for next-build dev server running over https

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9889 for Drupal config for next-drupal as relates to preview.

**Comment by timcosgrove** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9891 for next-drupal content type entities.
