### ISSUE TITLE
[BLOCKED] Go-Live Cerner support Boise (531) go live

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8802]
#### High-level user story
As a Veteran using the Outreach Events Calendar page, I need an intuitive filtering functionality, so that can quickly find VA events based on the relevant date, time, keywords, etc.

### Background
[Link to Cerner Run-book](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md)
Timeline for launch: ~~Testing the month of May (possibly including last week of April)
Go live stuff: July 23~~
TBD 

- Facility ID's: Boise, 531

### Considerations
- Follow the Cerner Runbook and prepare Boise Facility for Cerner launch  
- This will need deploy to staging initially in order to be tested by the facility and our team
- Once fully tested and validated in staging, we'll prepare to deploy in production per runbook guidance

### Tasks
- [x] Follow the Cerner Runbook and prepare Boise for Cerner launch 
- [x] Test locally and set up a staging test environment so Facility admins can test.
- [x] Once validated in staging, prepare for the deploy to Prod per the runbook guidance 
- [ ] Run launch steps - https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/public-websites/Cerner-Support/how_to_set_up_vamc_cerner_within_va_health_care_portals.md#step-4-launch
  - [ ] Flipper flip in prod  (Note: the runbook mentions that react widgets will be updated by this change, but in fact: they're now using Drupal as source of truth so will be updated after the Drupal change, not this step)
  - [ ] Drupal EHR value update on Boise VAMC System node - https://prod.cms.va.gov/node/15033/edit
- [ ] Review and close ticket once work is completed

2 hr estimate

### Acceptance Criteria 
- [ ] Local test are completed and show signs of success
- [ ] Boise is now launched in Cerner 
- [ ] Notify DSVA #vagov-cerner-launch-coordination channel when Launch steps are complete
- [ ] Ping Wes / Jill to email [steve.tokar@va.gov](mailto:steve.tokar@va.gov), **from VA email** & cc Denise, to send the Change Management email out to Boise editors (https://dsva.slack.com/archives/C0FQSS30V/p1658166422239289)
  - The email from #9338: https://docs.google.com/document/d/1pkwWH8fTyOq10jQuZgKTWFy9lchPwQB9Z4py8c-6ih4/edit 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Sitewide program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide crew ` (leave Sitewide unchecked and check the specific team instead)
  - [ ] `⭐️ Content ops`
  - [ ] `⭐️ CMS experience`
  - [X] `⭐️ Public websites`
  - [ ] `⭐️ Facilities`
  - [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Boise go live canceled -- https://dsva.slack.com/archives/C0190MTGNUE/p1658340797109159.

Removing from Sprint 63.

**Comment by mmiddaugh** [comment]
closing as no longer needed
