### ISSUE TITLE
Handle SSM rate limiting in content release GHA workflow

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8817]
## Description
Content-Build failed in a new and exciting way. The associated GHA uses the AWS API to look up parameters/secrets stored in SSM Parameter Store.  Many other users and automated jobs send requests to the DSVA AWS Account as well. This particular failure appears to be due to a throttle rate limit that was exceeded.

```
Injecting secret environment variables
  Error: Rate exceeded
  (node:4222) UnhandledPromiseRejectionWarning: ThrottlingException: Rate exceeded
      at constructor.extractError (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:46899)
      at constructor.callListeners (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:102691)
      at constructor.emit (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:102401)
      at constructor.emitEvent (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:168225)
      at constructor.e (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:163732)
      at r.runTo (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:170067)
      at /actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:170273
      at constructor.<anonymous> (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:164002)
      at constructor.<anonymous> (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:168281)
      at constructor.callListeners (/actions-runner/_work/_actions/marvinpinto/action-inject-ssm-secrets/v1.2.1/dist/index.js:1:102797)
  (node:4222) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:4222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Discussion
https://dsva.slack.com/archives/C01512KN35G/p1650399408172069
[AWS Troubleshooting SSM Rate Exceeded](https://aws.amazon.com/premiumsupport/knowledge-center/ssm-parameter-store-rate-exceeded/)

## Acceptance Criteria

- [x] Requested a service quota increase
- [x] Investigated/implemented error retries and/or exponential backoff for SSM API requests (if service quota increase is denied)

## Tasks
- [x] Estimate current quota needs + future needs with continuous releases
- [x] Request service quota increase for SSM API

If request is denied:
- [x] Investigate a new GHA action that can query multiple params and set multiple environment variables. Add/write action if needed
- [x] Investigate exponential backoff for the above jobs if possible/necessary

**Comment by cweagans** [comment]
Parameter store throughput rate limit has been raised. Turns out it was literally just a button that we needed to click in the UI.
