### ISSUE TITLE
Sitewide CMS- Sprint 57

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#8826]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task

</details>

## FYSA 
There will be limited sprint capacity

OOO
Erika: 4/25-29
Tanner: 4/25-29
Lynn: 5/2-6
Steve: OOO as needed
Denise: 4/29 and 5/2

## Transition

- [x] Update labeling in GH

## Features
- [ ] #8299 
- [ ] #8749 (Rachel)

## Design system
- [ ] #8492 
- [ ] #8680
- [ ] #8540 

## Broken Links
- [x] #8783 (Rach)

## "Was This Helpful?" Widget
- [ ] #8842 (Rachel)
- [x] #5811 (Lynn)

## Change management 
- [x] #8603   
  - [x] #6881 🥅
  - [ ] #6066 🥅
  - [ ] #8079 ?

## #8231 Content lifecycle for events
- [ ]  #4214  (stretch)

## Media Upload 
- [ ] #8754 (Ethan)

## Care we provide

- [x] #7657 (Denise, Swirt, Lynn) 🥅  

## #4888 Improve UX for Hours widget  

Via #6931 we got an HTML5 hours editor. 

- [ ] #8474  Rachel  (on hold)
- [ ] Then close this epic

## Dev workflow improvements

- [ ] #8477 (kev to fill this in then handoff/stretch)

## #7490 Lat/long for facilities and events

- [ ] #8776  (stretch)

##  #7963 Phone numbers 

- [ ] #1964 (Tanner- stretch)
