### ISSUE TITLE
Add APM trace and span IDs to application log output

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8844]
### APM Configuration Improvements:
- Correlate traces with logs by injecting `trace_id` and `span_id` in to Drupal Application logs. [Documentation](https://docs.datadoghq.com/tracing/connect_logs_and_traces/php/)

## Acceptance Criteria
- [ ] Install and configure Monolog
- [ ] APM Trace and Span IDs are added to application log output

## Implementation steps

* enable Drupal logging

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ndouglas** [comment]
We can do this most cleanly by installing and configuring Monolog, I think, because Monolog has "processors" for log messages and we can be very OOP about this.  Other option is basically subclassing the `syslog` logger plugin, I think 🤮
