### ISSUE TITLE
Scheduled publishing

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#885]
### User Story or Problem Statement

Publishers can not decide on publication date of content

### Affected users and stakeholders

* Public Affairs Officers (PAOs) and web managers at VAMC system 
* VSA-public-website team membes would like this feature to bulk publish multiple pieces of content at once. 

### Hypothesis

We believe that adding the adding the ability to schedule content moderation transitions, using _mostly_ OOTB drupal contrib (drupal lightning) configuration, will fulfill the needs in most situations. We'll know this to be true when CMS editors start making use of the scheduling features _without relying on support_. 

### Assumptions
* Not all content types need scheduling
* Scheduling will be done on a content by content basis. (no "bulk scheduling"
* Scheduled content will not trigger a front end build. 
* The only transition that should be scheduled is the In Review to Published transition

## Acceptance Criteria
* Testable_Outcome_X
* Testable_Outcome_Y
* Testable_Outcome_Z

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype

- [ ] User research
- [ ] Design
- [ ] Usability testing (eg with a prototype or other design stimula)
- [x] Implementation
- [x] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [x] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

**Comment by EWashb** [comment]
This is no longer within scope. The Sitewide CMS team will be exploring workflows after the implementation of CMS notifications and other automated processes.
