### ISSUE TITLE
Deprecate support for IE11

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#8853]
### User Story or Problem Statement

As a Veteran, I need to be told that I'm using a browser that doesn't support the best experience so that I can change browser.

### Affected users and stakeholders

* Veterans, caregivers and families

### Change management triage

The change represented by this user story will: NONE

### Hypothesis

If we successfully warn VA.gov visitors about the deprecation of support for IE11, there will be a significant reduction in Internet Explorer user as measured by analytics.

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] A visitor using any IE browser, including IE11, will relieve an alert in their UI telling them that changing browsers will lead to a better experience.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cweagans** [comment]
What is the current status of our IE support?

It looks like a lot of stuff has been done here, but I'm not sure what the "official" policy is on using client features that would cause visible breakage in IE. We're looking at image optimization a bit in [this issue](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10438) and it would be cool to use .webp (which isn't supported by any version of IE).

**Comment by wesrowe** [comment]
We no longer support IE browsers and have been notifying users on IE for several months. Would .webp actually break the experience for IE users, or would it just give them a non-optimized experience?

**Comment by cweagans** [comment]
If an IE user were to view a page with .webp images, those images wouldn't be displayed at all. If _all_ of the images on a page were .webp, it could be a little wonky. Here's what the home page looks like without working images (icons and such should still work):

![image](https://user-images.githubusercontent.com/101590/187321949-790fa69a-de1e-43ae-b976-9d990f34666b.png)
