### ISSUE TITLE
Standardize comment variants for time zone, closed and 24/7

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8861]
## User Story or Problem Statement

We recently replaced migrated our office hours data from the old table field format to the new office hours format. The new office hours field stores three items for each day: start time, end time, and a comment. As part of that migration we cleaned up some key items that could end up in the comments field such as:

- Closed
- 24/7
- ET, CT, MT, PT (time zones)

The new office hours comment field is wide open in terms of what editors could enter. As we move forward, on node save, we should inspect the contents of the comments fields and when the contents is a variant of the above make sure the input is standardized.

Examples: 

- CLOSED, closed, Closed, Closed. - should all result in Closed
- EST, est, ET, et - should all result in ET

## Implementation steps

We can repurpose some of the code used in the office hours migration script to check comment field data on node save (with a node hook) and replace (standardize) these variants.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JQuaggles** [comment]
@JayDarnell @swirtSJW 
Is this still relevant or has this been fixed / what's up with it?

**Comment by JayDarnell** [comment]
@JQuaggles this is still relevant. Two related issues were closed which audited these comment fields and then subsequently cleaned up the data. 

Audit: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9358
Cleanup: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8935

We still need to add a validator to these fields to prevent time zones from being entered on save moving forward. This issue wasn't prioritized when it was created due to other more pressing matters at the time.

**Comment by swirtSJW** [comment]
This is related.  #8883 When we bring in time zones, we will want to make sure we are not also getting timezones entered as comments.
