### ISSUE TITLE
Facility Locator expected behavior for VBA "all services" searches

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#8869]
## Issue Description
The Facility Locator is designed to return the closest locations which map to the search parameters. However, there may be a disconnect in the "All services" default, particularly for "VA benefit" searches. 

This is well illustrated by this [example search](https://www.va.gov/find-locations/?page=1&address=22903&facilityType=benefits&serviceType&latitude=38.03&longitude=-78.5&radius=19&bounds%5B%5D=-79.25&bounds%5B%5D=37.28&bounds%5B%5D=-77.75&bounds%5B%5D=38.78&context=Charlottesville%2C%20Virginia%2022903%2C%20United%20States)
1. Enter 22903 as zip code
2. Choose VE benefits
3. Choose All VA benefit services
4. Observe single result is returned: [VetSuccess on Campus at Liberty University](https://www.va.gov/find-locations/facility/vba_314k). This location is on a campus and offers a single service: Education and career counseling.

Returning a location offering a single, particular service is not consistent with an "all services" parameter. Should "all services" map to Benefit region offices which actually offer "all services"? How do we best support Veterans, particularly if no benefit region offices exist within the searched geography?

---
## Tasks
- [ ] Determine ideal behavior
- [ ] Determine how best to support Veterans in a variety of possible scenarios

## Acceptance Criteria
- [ ] Searching for "VA Benefits" -> "All VA Benefit Services" should show the nearest Regional Office as well as any other facilities that may fall within that range.
---

**Comment by swirtSJW** [comment]
Slack and scrum discussion surfaced some questions/concerns:
1. ) The filter is inappropriately named which makes the results unexpected.  The filter returns "Any" not "All"  So should we rename the filter on both VHA and benefits?
![image](https://user-images.githubusercontent.com/5752113/165788874-1fd5290a-7f88-45c4-ae29-1a522351820e.png)
2) Even if we expand the bounds dynamically based on a search for Regional Office, it is entirely possible that regional office may show up on page 2 of the pagination.   Should the regional office be highlihted?

**Comment by davidconlon** [comment]
While I appreciate the identification "inappropriate" label is subjective. We can monitor to see if that's a problem but I'm not sure that has surfaced as a Veteran problem in any of the testing to-date.

I think that where the RO appears in the list it is something that we can consider in a separate issue for "identification of facility" if this is a problem for Veterans in a subsequent iteration and I'd prefer not to change the scope at this time.
