### ISSUE TITLE
Use Lighthouse data for VA health connect number on Facility Locator

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#8870]
## Issue Description
As VISNs have rolled out VA health connect, the number has been hard coded into Facility Locator search results based on VISN. Now that CMS is the source of truth for this number and Lighthouse has added it to the API, we can update the Facility Locator to use the Lighthouse value rather than hard coding each implementation. 

## Data from Lighthouse
Field name [TBD]

---
## Tasks
- [ ] Backend will need to expose VA health connect to front end
- [ ] Front end will add logic to display value for VA health connect when populated
- [ ] Front end to remove hard coded values for VISN 8, 2 and 17

## Acceptance Criteria
When facility type = VA health and VA health connect data is present in Lighthouse for a given facility, the VA health connect phone number is displayed as below
- [ ] Main number: (phone)
- [ ] VA health connect: [TBD]
- [ ] Mental health: (phone)

Hardcoded values are no longer present

**Comment by kevwalsh** [comment]
Ready for testing now that VA health connect is in the Facility API.

**Comment by kevwalsh** [comment]
sounds like this can be closed!
