### ISSUE TITLE
Harden Homepage design refresh for production launch

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#8877]
## Background
#8340 tracks homepage design iterations for user testing. This epic will track tasks that should be done for production launch, but are not top priority for user testing phase.

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [X] Change the front end and be highly visible to the public

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Acceptance Criteria
- [ ] All automated tests pass

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [X] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
This could include #10339 work

**Comment by jilladams** [comment]
10/25 sync with Michelle, new scope that will affect launch timing: 
1. **Soft launch modal design** - we will soft launch to a % of users, using a modal that will pop up on current homepage
  * New homepage will need to live alongside current homepage in prod
  * Modal will redirect users to new homepage, opt-in. 
    * Shown to every user, every visit?
    * Needs Collab Cycle review?
    * How do we consider users moving forward / backward between old & new experiences?
  * Content - from Danielle?
  * Design: will request from Ryan on 11/4. Timeline for design return to follow that
  * Collecting feedback method TBD
  * New URL tbd (not /homepage-test): Michelle vetting with SWC IA
 2. **Sign in modal:** page body prompt to create account (in new design) opens the existing sign-in modal. Michelle investigating with VSP Identity team ways to point directly to Create Account info, rather than sign in options.
   * Need design
   * Need to understand ownership of the changes, likely Identity team. Timing TBD.
   * Could be a fast follow, potentially. TBD DaveC priority / decision.
3. **Analytics** - in order to measure the new homepage, we may need to tweak some current homepage analytics as baseline.
  * Need to scope out the "analytics design" for which events / labels to use
  * PW FE will need to ramp up a bit / 1st rodeo with adding new analytics

**Comment by jilladams** [comment]
New epic tracking the Analytics / QA / soft launch: https://github.com/department-of-veterans-affairs/va.gov-team/issues/48779

**Comment by mmiddaugh** [comment]
Related issues
- Homepage feedback button/Medallia intercept: [Analytics Implementation or QA Support for Sitewide Homepage - VA.gov Homepage #48779](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/48779)
- Modal for new experience: [Content wordsmithing from Sitewide homepage #48783](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/48783)
- URL support: [IA request from Sitewide homepage #48789](https://app.zenhub.com/workspaces/vft-59c95ae5fda7577a9b3184f8/issues/department-of-veterans-affairs/va.gov-team/48789)

**Comment by mmiddaugh** [comment]
Adding related launch milestones here for reference

-  (WIP) Accessibility Testing for [Sitewide Homepage, Redesigned VA.gov homepage] [#50360](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50360)
- Redesigned VA.gov homepage PTEMS-QA Test Plan [#50147](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50147)
- Readiness Review [Sitewide Homepage, Redesigned VA.gov homepage] [#646](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/646)
- Staging Review [Sitewide homepage - Redesigned homepage] [#49802](https://github.com/department-of-veterans-affairs/va.gov-team/issues/49802)

**Comment by jilladams** [comment]
Staging review feedback #49802, Not launch blocking: 
* [team-#50799](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50799) - News promo: Image appears before heading that describes it. Image alt text is not super useful. (Image is suppressed on mobile.)
  * Either move the image under heading and restyle. 
  * Or: if we are confident that images will always be decorative without meaningful alt text, hard-code as "mpalt" attribute so the image doesn't get announced. Better screenreader experience. 
* [team-#50798](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50798) - Other Search Tools menu > Find a VA Location link should keep "Location" rather than "Find a VA Facility" (despite content reco), to keep match with page title / breadcrumb when you land.
* [team-50797](https://github.com/department-of-veterans-affairs/va.gov-team/issues/50797) - Learn how an account helps you = dead link, known issue. (#11771), closed.
