### ISSUE TITLE
Next-Build: Build Pipeline

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8921]
## Description

Our Phase 1 architecture for the new build system expects that we can take output from a SSG, Next-based process and insert it into the Metalsmith build pipeline for further transformation alongside equivalent HTML that Metalsmith has already generated. This was validated in lower environments in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/7986, we will now implement in production.

## Acceptance Criteria

- [ ] Files that have been output from a new SSG process can be ingested into the Metalsmith build in Prod
- [ ] Pages ingested in this manner do not cause issues with the Metalsmith process
- [ ] Pages output in this manner are functionally and visually equivalent to the same pages when generated in their entirety by Metalsmith

## Implementation details

In the existing Metalsmith build, we are looking to ingest files in immediately after Metalsmith applies all layouts to the data it has imported via GraphQL, which is here: https://github.com/department-of-veterans-affairs/content-build/blob/master/src/site/stages/build/index.js#L211

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
