### ISSUE TITLE
Scrub time zones from all existing office hours comments

### ISSUE THREAD

**Issue by JayDarnell** [department-of-veterans-affairs/va.gov-cms#8935]
## User Story or Problem Statement

We recently migrated our office hours data from the old table field format to the new office hours format. The new office hours field stores three items for each day: start time, end time, and a comment. As part of that migration we cleaned up some key items that could end up in the comments field but we did not scrub time zones from this data.

We need a new script we can run to scrub time zones from all existing office hours comments.

## Implementation steps

Generate a new script to scrub time zones from existing office hours comments.

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by RWEagans** [comment]
Moved from S57 to 58
