### ISSUE TITLE
Table audit capability

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8940]
## User Story or Problem Statement
As a Sitewide Content team member, I need an efficient way to know what nodes have tables in them so I can remove or clean them up.

Possibly looking to add to the current audit capabilities in the system to be able to produce them.

[Specific request from Randi in slack.](https://dsva.slack.com/archives/CDHBKAL9W/p1651251013926969)

## Acceptance Criteria
- [ ] Randi has a list of any nodes that contain a table
- [ ] We are able to produce this in an efficient way (needs refinement with Dave to enhance existing audit capabilities or handle through a script ad hoc)
- [ ] May require design review
- [ ] May need KB article creation

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
@swirtSJW mentioned an existing audit tool that would scratch this itch.

**Comment by EWashb** [comment]
@msbtterswrth has this already been resolved?

**Comment by msbtterswrth** [comment]
We do have a very slightly stale [airtable](https://airtable.com/apphETq1vi4mpYD0J/tblXbMw6Ylj6bkNcf/viwVI1TKs3SJm2uKb?blocks=bipnkHDa8xJbjId1c) with this data. Creating a view in drupal would be a bit tricky iirc, which is why this airtable was created by hand with some database wrangling. I think we have a ticket somewhere to create a tool to look for paragraph references, but I don't know the status of that.

**Comment by cmaeng** [comment]
sent the file export from airtable to Randi. any enhancement request to add this functionality into the CMS will need further thought and can be captured in a separate ticket.
