### ISSUE TITLE
[EPIC] Facility COVID status

### ISSUE THREAD

**Issue by cmaeng** [department-of-veterans-affairs/va.gov-cms#8946]
Integration branch: #9028

[Integration Tugboat environment](https://pr9028-sjpg4ebinnl4eooevngpwufok19n4akk.ci.cms.va.gov/) 

### Monday May 9

Engineering
- [x] #8947
- [x] #8988
- [x] Released #8956 to prod
- [x] #8949 to integration environment 
- [x] Create integration branch and environment 

Content 
- [x] #8989 

Change management
- [x] Stub KB article (#8997)

### Tuesday May 10

FE Design (stack ranked by priority)
- #8981 (Cindy)
- #8982 (Cindy)
- #8983 (Cindy)
- #8984 (Cindy)
- Design review with UX 

CMS MVP design
- #8960 (Kauff)
- #8993 (Kauff)
- #9011 (Suzanne)

Facility API
- #8987 (Jay)

CMS engineering
- #9022 
- Consider resetting Facility Status to Normal for all VAMC facilities

Content
- #8998 (Sitewide content team)
- Train Sitewide content team to update standardized facility statuses

General
- [ ] Create QA plan
- [ ] Create launch runbook

### Wednesday May 11

Content
- [ ] #8993 (sitewide content team) 

FE Engineering
- #8985 (Max)
- #8986 (Ethan)

Change management
- #8997 (Denise?)
- Draft #9035
- Demo to PAOs during office hours 2pm ET, with VHA Comms and Jeff G.
0. Jeff and Melody set the stage
1. Cindy: Screenshots of the final Veteran designs (Facility Page, and if possible the other Pages)
2. Rachel: Demo MVP CMS experience 

### Thursday May 12

General
- [ ] QA
- Sync with VHA DM: Jeff G, Dave, Denise, Roger, Kevin, Kauff, Suzanne, Danielle, Michelle (Denise to schedule)

CMS UX
- [ ] Finish user research with editors

Change management
- Finalize #9035

### Friday May 13

- [ ] Any followups based on QA.

Notes: Kevin offline

### Monday May 16

- [ ] Release to prod (morning, off cycle?)
- [ ] Email goes out (from VHA DM?)

### Week of May 16

Design
- [ ] Design updates to Covid Status UI based on user feedback

CMS Engineering
- [x] #8980
- [ ] Updates to CMS UX based on user feedback

Product
- [ ] Analytics - should we be combining the facility statuses? 

## Background
Time sensitive (due by 5/13) VHA initiative to add a separate COVID facility operating status.

From a high level, it's basically a standardization of protocols for VHA facilities based on COVID-19 rates in the community. These "VA Health Protection Levels" cover Veteran-facing info such as mask/screening policies, visitor policies and appointment modality (virtual vs in person) - plus a lot of employee details  like staffing and PPE. There will be onsite posters to inform Veterans. VA.gov will use an FAQ/info page plus the use of these operating statuses to communicate the info.  Danielle Thierry and  Lauren Alexanderson are involved if you need additional business side info.

<details>
<summary> original thoughts - please see the most recent decisions/plan in comments below </summary>

Current thoughts from @mmiddaugh are:
* We think we need to add a new separate COVID facility operating status - Red, Yellow, Green - with standardized "more info details" which will need to be updated every Friday. This impacts VHA - VAMCs and Vet Centers only right now (not VBA).
* If possible, we're thinking it will be easier for PAOs to report to some centralized data source (csv?) and then migrate the data on Friday. (Longer term, maybe it gets added into Drupal?)
* In the short term, since the front end and lighthouse are not prepared to handle two separate types of status, we're thinking it might work to ignore the existing status and just show/send this new COVID facility operating status
  *...except for VBA, CAPs and possibly "Closed" facilities
  * unless there is a way to append other non-COVID related "more info" details
  * I'm hoping there is an easy way to get a report of who is using which status so we can assess other important facility info which could be nixed by this plan
* there's obviously editorial impact here - wouldn't want folks using the existing facility statuses if they aren't displayed on the front end
* I think Jeff Grandon/Jessica/Barb will be handling change management although we'll need to update or add KB articles
* Longer term, we'd plan to return the existing facility operating status as a separate status with strong guidance on how to use them, possibly with standardized language/new levels

![image](https://user-images.githubusercontent.com/60702623/166822377-e1e115b3-60e8-4260-8b31-d88e34fd63ae.png)

</details>

### User Story or Problem Statement
As a facility editor, I need a way to designate a facility at a COVID status level so that this information displays on relevant va.gov pages.

### Affected users and stakeholders
* CMS editors of VAMC, ~VC products~
* VA facility locations

### Change management triage
The current thought is that VHA DM will drive most of the change management around this. We will need to augment from the Sitewide Crew side.

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
Will need a runbook to coordinate launch.

**Comment by cmaeng** [comment]
latest from @mmiddaugh around status specific language:

Still in draft mode...these are the three levels - looks like she is considering Low, Medium, High rather than Green, Yellow, Red or a general status of "Current COVID-19 safety rules" with the specific in the "more info" details.
* **Current COVID-19 safety rules [or COVID-19 safety protocols: Low]**
COVID-19 levels are low. We’re open for in-person care and visitors. Everyone who enters the facility must wear a mask. If you’d prefer an appointment by phone or video, ask your health care team. If you have symptoms of COVID-19, don’t come to the facility in person unless you need care right away.
* **Current COVID-19 safety rules [or COVID-19 safety protocols: Medium]**
COVID-19 levels are medium. We’re open for in-person care and limited visitors. Everyone who enters the facility must wear a mask. Your health care team may recommend a phone or video appointment. If you have symptoms of COVID-19, don’t come to the facility in person unless you need care right away.
* **Current COVID-19 safety rules [or COVID-19 safety protocols: High]**
COVID-19 levels are high. We’re open for some in-person care. But we recommend phone or video appointments whenever possible. We allow only limited visitors. Call first before you arrive. Everyone who enters the facility must wear a mask and complete COVID-19 symptom screening.

**Comment by mmiddaugh** [comment]
Decision recap: 
- The new three COVID-specific operating status options will be added separate from the existing status options as a vocabulary for future fluidity and to support inline editorial visibility and guidance.
- Editors will be able to select the appropriate COVID safety protocol level in CMS but will not be able to edit the "more info" details.
- A status is expected for each VHA facility, updated weekly from a business process. It is not necessary to restrict/limit the editing cadence in Drupal.
- Change management will be coordinated through VHA Digital Media and Vet Center leadership.
- To avoid overlapping/conflicting information with content already in existing status details, editorial guidance for how each status is to be used is forthcoming.
- No default status has been determined. The option to normalize status exists if needed. (for example, any facility currently showing "normal" operating status could be set to "COVID-low")
- Reports can be generated to identify any COVID-related info in non-COVID statuses and/or to identify facilities with null COVID safety protocol levels (once available).
- To preserve the need to provide important non-COVID related facility information, the new statuses will be displayed along with existing operating statuses (if in use).

**Comment by mmiddaugh** [comment]
It was decided on 5/5 that Vet Centers will not be part of this implementation.
