### ISSUE TITLE
Next-Build: Testing and Code Quality (Q2 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#8958]
## Background

Before production launch of the next-build system, we will ensure complete test and code coverage, including but not limited to: typescript, linting, automated testing, and secret scanning, to ensure the quality of deployed code. 

### Problem Statement

As a CMS engineer, I want to have the proper tooling in place so that I can ensure the proper testing, readability, and maintainability of code to reduce errors.

### Affected users and stakeholders

* CMS engineers

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Goals
- [ ] Automated tooling is in place enabling engineers to ensure committed code is free of errors
- [ ] Custom code coverage is monitored and is at least 75% at launch

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
