### ISSUE TITLE
Onboard Sorry-Cypress to EKS Ops Platform

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#8962]
## Background

In support of the effort to speed up current test run times, the CMS team has explored test parallelization in Cypress as an option. To do this, we need to implement an open source dashboard to enable this functionality. 

### User Story or Problem Statement

As a CMS Devops Engineer, I need to start the EKS onboarding process, so that Sorry-Cypress is installed and running on the Platform-Ops created container ecosystem.

## Acceptance Criteria

- [x] Sorry-Cypress successfully runs on containerized platform

## Implementation

Epic dependencies should follow this list of on-boarding tasks/requirements:
https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594142/Onboard+a+New+Application+to+the+EKS+Infrastructure+As+a+VSP+team

This specific solution will likely need tickets created from the below list. Some may overlap with those in the documentation linked above.

- [x] Service account with permissions to push to that ECR repo (terraform)
- [x] Github repo to mirror images to ECR (you can make yourself, but add the infra team as a manager)
- [x] Service account added as credentials to that Github Repo (terraform/Infra can help with that)
- [x] GHA pipelines to mirror each of the images needed to run Sorry Cypress into ECR (you can copy these from existing ones)
- [x] Helm chart modified a little bit and put into the Application Manifests repo (easy enough to do, and you will need extra templates for ingress, secrets, dns, etc)
- [x] GHA pipeline to update the helm chart values file when the version of the containers is updated (you can copy these from existing ones)
- [x] ArgoCD RBAC added to allow you to deploy to a namespace on a cluster (requires a helm update run by infra) (vsp-infra-argocd repo)
- [x] Add your application to the argocd-apps: https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests/blob/main/apps/vsp-operations/argocd-apps/dev/main.jsonnet

Recent thread with VSP-Platform-Support:
https://dsva.slack.com/archives/CBU0KDSB1/p1651613951169729

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
Epic dependencies should follow this list of on-boarding tasks/requirements:
https://vfs.atlassian.net/wiki/spaces/OT/pages/1474594142/Onboard+a+New+Application+to+the+EKS+Infrastructure+As+a+VSP+team

**Comment by ElijahLynn** [comment]
https://docs.sorry-cypress.dev/guide/dashboard-and-api

![image](https://user-images.githubusercontent.com/1504756/169415518-c8ad7196-ef06-4cfb-9fe1-ef242bf3b9f8.png)
