### ISSUE TITLE
Design node view for COVID Facility Status content

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9011]
## User Story or Problem Statement

As an editor i want to see my facility COVID status on the node view and node revision pages so that i can review it before publishing, or see the history of it. 

## Acceptance Criteria
- [x] view node prototype has been designed
- [x] prototype has been reviewed by UX team members
- [x] prototype has been annotated for devs: https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities---COVID-status?node-id=164%3A30682
- [x] annotated prototype has been passed to devs for implementation

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Here is the current version of node view for reference
![image](https://user-images.githubusercontent.com/5752113/167840099-894b0c95-770c-4aba-b3f9-6e783ccc334a.png)

It just shows the 
status term name and the matching description which is what the FE is going to be showing.

At some point it could be updated to use the same design pattern that is being used on the Front End but I think that level of change should be post-mvp

**Comment by swirtSJW** [comment]
I suggest to mimic the FE  we simply remove the node's field lables (in green)
![image](https://user-images.githubusercontent.com/5752113/167841364-4e2c337a-59e4-4f85-a177-11598280e1a0.png)

**Comment by suzanne-gray** [comment]
Final design:  https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities---COVID-status?node-id=164%3A30682
