### ISSUE TITLE
Implement node view design for Facility COVID status

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9034]
## User Story or Problem Statement

As a facility editor I want to see the COVID status description on node view so that I can see what the front end will be showing for the status I selected.

## implementation details.
  Show the rendered entity and control with view mode... or maybe template using the design pattern.

## Acceptance Criteria
- [ ] view node has been updated as per https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities---COVID-status?node-id=164%3A30682
- [ ] Design review

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [X] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
This was done by Ethan via another PR.
