### ISSUE TITLE
Widgets: Replace facility name with system name

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9074]
## Timing note
Let's get Drupal SSOT out into prod and bug-free before attempting this change.

## Description

Prereq: #9787 
https://www.va.gov/data/cms/vamc-ehr.json -- provides Facility Name / System name. In this file, all Facilities are associated with a System.

As a Veteran I want to be shown health system names instead of facility names, so that I can more easily ascertain which button to click to complete my EHRM-related task.

This issue is only to change the text that is displayed per system – e.g., replace "Wylie P Chalmers" with "VA Central Ohio".

Current state for a multi-Cerner patient:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/4054752/168128569-917a8113-71a1-4f97-80bc-9073c8ed8172.png">

Assumptions:
- Doing this work when the hard-code API is still present will lead to a little more complexity/tech debt to clean out later.
- On conditional, Ryan suggests build around presence of new field, not flipper.
- Are all Facilities under a system? We think so.

## Tasks
- JSON file grok (hard coded vs. Drupal data considerations) / replacing text / writing fn - 6
- Local testing: requires Cerner users, vets-api or dev api - 1
- Staging testing - 2
- unit tests - 1
- PR / code review - 2
12 hr 

## Acceptance Criteria
- [ ] This ticket follows Drupal as source of truth, #8687 
- [ ] System names from CMS are listed in widget
- [ ] System names are appropriately associated with VistA or Cerner functionality

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
If someone picks up this ticket, confer with @ryguyk for clarity about current state of Drupal SSOT.

**Comment by jilladams** [comment]
Note: there's a bug in Staging, that will be fixed when this PR merges: https://github.com/department-of-veterans-affairs/vets-website/pull/21809

**Comment by jilladams** [comment]
@ryguyk @allisonlu did you all decide to leave this ticket with Allison or that Ryan you would handle both Facility name issues?

**Comment by ryguyk** [comment]
@jilladams I'm going to take this. I've already begun work on it. It's in good shape overall with just a few question marks that are not blockers or major cause for concern.

**Comment by ryguyk** [comment]
[PR pushed for this](https://github.com/department-of-veterans-affairs/vets-website/pull/21905), but awaiting external review from Release Tools. We've been waiting over 24 hours already, so I'm hopeful this should be approved Monday. It should merge Monday as well, provided that review comes before deployment cutoff. FWIW, it's a change I certainly don't want to merge on a Friday anyway, as it involved a lot of moving things around.

**Comment by ryguyk** [comment]
PR approved and merged. Closing issue.
