### ISSUE TITLE
Public Websites: Content support 2022

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9084]
## Background

For Public Websites to support content-related tasks within our purview, which do NOT involve development directly.

1) Content audits identified by the Sitewide Content team. 
- One-off audits
- Potentially a future tool for audits 

2) Updates to content, knowledge base articles, etc.

### Problem Statement

How might we make content audits easier and more reliable, so that Veteran facing content and support is as trustworthy as possible?

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

## Implementation notes

**Developer version:**
1. Rebuilding [va.gov](http://va.gov/) locally (or grabbing a tarball created during content release, maybe that can be done by a non-dev?)
2. Running grep -i -r "air force" [directoryname] (i think)
3. Copy/pasting the results

**Non-dev version:**
(working on it; possibly downloading lastest content-build tarball to run `grep` command.)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [ ] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Started a draft [content audit runbook](https://docs.google.com/document/d/1BCz8uiwBKuHJWXVjIDjUIlt3rwDD5EaXJTmnrS9xUCM/edit) that we can add to [va.gov-team-sensitive/tree/master/teams/vsa/teams/public-websites](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/teams/vsa/teams/public-websites) when fleshed out / finalized.

**Comment by davidconlon** [comment]
@jilladams This has "content support 2022" as a title. We're 3/4 of the way through 2023.... 
Can we close this? rename this? what is this?
