### ISSUE TITLE
EPIC: Facility COVID status post-launch

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9096]
### User Story or Problem Statement

* As a VAMC editor, i want a satisfying and efficient experience updating my COVID status.
* As a Veteran, caregiver, or Facility visitor, i want clear status on COVID.

### Affected users and stakeholders

* VAMC editors
* VAMC end users
* VHA Digital Media (stakeholder)
* Office of Health Transformation (stakeholder)

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

### Hypothesis

We believe that editors' ability to change the standardized COVID-19 facility operating status content will more closely align to their on-the-ground policies and procedures at each facility. We'll know that to be true when VAMC editors are consistently using the intended node for informing Veterans about the actual masking, screening, visitation and virtual appointment policies related to a COVID status for a facility.

## Assumptions
* The centrally-managed content for COVID-19 facility operating status does not account for local use cases, resulting in the observed use of sitewide banners for COVID policy-related information.
* Discovery with VAMC editors will identify more use cases and context for COVID facility status, and potentially the broader use of facility-related information.

## Acceptance Criteria
- [ ] Updated field for COVID-19 facility status
- [ ] Minimal use by editors of sitewide alerts for COVID-19 policy-related information
- [ ] KB article and video update

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [x] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
And now that I'm looking over this entire epic, we may want to close it. The work being done in #10389 voids this. We won't be creating a separate covid status.

**Comment by jilladams** [comment]
Closing re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13681
