### ISSUE TITLE
Automatically populate Revision log message based on Facility COVID status field update

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9099]
## User Story or Problem Statement

As an editor, I want to update to update my Facility Status quickly, without typing a revision log message every time. 

As a web editor, i want clear, succinct revision log messages so i know what happened.  

## Acceptance Criteria
- [ ] When an editor picks "Low", the revision log message is added: 
`COVID-19 level changed to Low.` 
- [ ] When an editor picks "Medium", the revision log message is added: `COVID-19 level changed to Medium.` 
- [ ] When an editor picks "High", the revision log message is added:  `COVID-19 level changed to High.` 
- [ ] Editor should be able to override the revision log message before save.
- [ ] Ideally, this is done in a way that allows us to do more of this, easily, in the future, for other fields. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by suzanne-gray** [comment]
Added revision log message text to ACs.

**Comment by swirtSJW** [comment]
Risk: The messages as written in the AC are going to lead to a hardcoded message that is going to not stay in line with the term name or the addition of other terms.

**Comment by kevwalsh** [comment]
it was more that we want to think through this in a broader context of automated revision log messages.

**Comment by swirtSJW** [comment]
Closing this as covid status is slated for removal
