### ISSUE TITLE
 Verify Semantic Release Automation to "Release" and "Tag" the Sorry-Cypress GH Repository with a Semantic Version Number

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9108]
## Description
The repository used to build and push Sorry-Cypress Images should use semantic-release to automate the whole package release workflow including. 

## Acceptance Criteria
- [x] Depending on the commit message of PRs merged to main the repository should increment the version number and create a release in the repository.

## Implementation
- Semantic versioning functionality may already be in place, would need to test and tweak syntax for current use case

## Tasks
- [x] Verify semantic release is functioning correctly on Sorry-cypress infrastructure repo.
- [x] Test that semantic release creates a release in an automated fashion.

**Comment by olivereri** [comment]
Semantic versioning is working properly for PR merges that use semantic conventions in commit messages and PR titles.

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/fa5fc86d-39bc-44cf-9f69-c44e6cc4b592)
