### ISSUE TITLE
Secrets and Parameters needed for Sorry-Cypress stored in AWS Systems Manager Parameter Store

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9111]
## Description
As a CMS Devops Engineer, I need to input secrets, build, config, and deploy parameters into AWS Parameter Store, so that they are available for the EKS build, release and deploy pipeline.

## Acceptance Criteria
- [x] Confirm which secrets and parameters should be stored in AWS Parameter Store.
- [x] Necessary secrets, build, config, and deploy parameters are added for Sorry-Cypress
- [x] Ensure that Sorry-Cypress uses the AWS-stored secrets

## Tasks
- [x] Review Sorry-Cypress application configuration for parameters that should be kept secret.
- [x] Manually add secrets to DSVA's AWS Parameter store.
- [x] Modify Sorry-Cypress Helm charts to retrieve parameters from Parameter Store
- [x] Update Sorry-Cypress app config to retrieve parameters from Parameter Store
