### ISSUE TITLE
Add a "is empty" / "is not empty" filter for Supplemental status on Facility Status view

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9117]
## User Story or Problem Statement

As VHA DM, i want to see what facilites have added Facility COVID status, and which have not, so that i can follow up appropriately. 
<img width="1978" alt="Facility_status___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/169091277-6af7ca18-bc66-4f0b-92f7-cb43cb1c5948.png">

## Acceptance Criteria
- [ ] Change existing filter from autocomplete to dropdown
- [ ] Add a new filter with field_supplemental_status for IS EMPTY or IS NOT EMPTY

## Implementation steps
- Views config

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`
