### ISSUE TITLE
CMS Announcement Block

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9122]
## Background

From #9042 the CMS Announcement block was implemented directly related to the covid alert efforts. However, there is a need to use it in a reusable and specific way across role, section, or even page that requires further evaluation from both a technical and UX perspective. In short, current state raises some sizing concerns and governance has not been fleshed out. 

Especially when viewed along with system status alerts, it becomes less readable and scannable. From a readability standpoint, some users will see the following on wide screens:

![169105813-c15bdb39-32f1-4660-92c2-334e7cce0424.png](https://images.zenhubusercontent.com/614b6cbe05afafb268be4c0b/6f221388-3e43-43f9-a54f-ef3ce586a6eb)

### User Story or Problem Statement

As a CMS admin, I need to create announcement blocks for specific use cases that follow proper governance standards.

### Affected users and stakeholders

* CMS editors of all products (not typically at once, but could be depending on the alert type)

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

### Hypothesis

We believe that CMS announcements will provide another touchpoint for communications to editors about action requests. We'll know that to be true when:

1. there are fewer helpdesk tickets about a new process
2. editors indicate in a survey or research study that the announcement block provided help or context about action requirements

## Assumptions
* CMS Annoucenment blocks provide another level of change management communication that assists editors in completing a task
* CMS Announcement block can be used to relay other information (not just action requests) to editors
* Analytics may be helpful in tracking announcements that involve KB articles
* Success can be validated with user testing and surveys. 

## Acceptance Criteria
- [x] Review from tech lead to determine if current config is the most sustainable option for implementation
- [x] UX creation of user stories for each use case 
- [x] UX will determine the width of the content block as it relates to various other alerts that an editor can see at any given time
- [x] UX review of accessibility 
- [ ] If other alerts require updates, tech review will be needed to determine the feasibility
- [x] UX design system review
- [x] Documentation of governance
- [ ] Requires KB article update?

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
TBD

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
MVP for CMS announcement block is done
