### ISSUE TITLE
Super-Epic: PW discovery & onboarding to our portfolio

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9134]
### User Story or Problem Statement

How might we get to know the products in our portfolio in a goal-oriented way, but not waiting till a crisis hits a product to learn about it?

### Products / Projects
* Homepage
* VA Site Search
* Global header / footer - #9136 
* Benefit Hubs
* Events
* React widgets (Cerner & otherwise)
    * Cerner cutovers
    * AskVA 
* Find a Form - #8924 
* Promo Banners
* Campaign Landing Pages (CLP)
* Redirects - #8726 
* Offices
* Content audits - #9084

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Unlinked some still-open epics; closing this super epic.
