### ISSUE TITLE
Documentation: implement Storybook

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9138]
## Description
In https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8433 we determined Storybook may be a useful tool for generating documentation and demonstration of components available for use in Next-build. We need to do some implementation to support this, and make some decisions on what should be documented.

### Acceptance Criteria

- [x] Storybook is implemented in next-build, can be launched in local developer env
  - [x] Stories are implemented for at least two components
- [x] Some guidelines are decided on regarding what stories we will implement, i.e. potentially types, components, etc, and the level of detail or variants that we make available for those stories
- [ ] Tickets are written to create stories retroactively for existing code
  - [ ] **This is not relevant** Note: retroactive tickets are not actionable until https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9730 is completed.

### CMS Team
Please check the team(s) that will do this work.

- [x] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

## Tasks
- [x] install storybook with react & typescript support
- [x] add any necessary additions to storybook's preview.js for compatibility with next. https://storybook.js.org/blog/get-started-with-storybook-and-next-js/
- [x] ensure the regex includes stories files next to the components
- [x] create at least two example stories for initial components / layouts / etc including data mocking
