### ISSUE TITLE
Discovery: CMS-based tool for tracking links

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9150]
## Background

No tool currently exists in the CMS for identifying links and their locations. This is especially useful for tracking broken links. The VA uses siteimprove, but that is operational for the front-end and not the CMS directly. Those FE URLs can translate to the BE via siteimprove, but does not provide a node-level audit. Our team would benefit from a list of links rather than the false alarms that could happen with FE searching. 

Technical discovery should audit tools that currently exist, the Drupal options OOTB, and also what it would mean for a custom solution built by our team. 

Whatever tool or solution is decided should be able to perform a link audit as expected when one piece of content links to another in order to warn on when publishing or unpublishing the content. 

## Acceptance Criteria
- [ ] Technical review of current market solutions
- [ ] Technical review of Drupal 10 options (expected 12/2022)
- [ ] If no other solutions are feasible or provide what is needed, a technical review with tech lead to determine what LOE would be required for a custom-built solution 
- [ ] Assignee should provide documentation of what the options are, level of effort, pros and cons
- [ ] Review with Sitewide CMS and/or Program product manager for next steps

**Comment by stefaniefgray** [comment]
For reference: Editor in VAHELP-4204 asked if such a tool existed after receiving a broken link alert for a page she had archived and thought was not linked anywhere -- turns out it was linked from other pages

**Comment by swirtSJW** [comment]
https://www.drupal.org/project/linkchecker has some promise but does not fully offer the audit others are asking for.  And does not prevent the creation of broken links, only checking them after they are created.

**Comment by swirtSJW** [comment]
Been thinking about this for a while and just logging some thoughts here to get them out of my head.
A new module "Link Audit"  could do the following
- Log all links found on a page  in a db table on publish (so we aren't tracking draft links which would makes things really confusing) in source destination pairs  node/23 => node/78  or node/23 => https://spaceforce.gov 
- Provide a view to see all links with filters for source and destination
- Provide option to prevent unpublish/delete/archive if the node appears as a destination. then warrn and provide info and links to source nodes that have it as a destination.
- Provide a path based do not track... so we can exclude node edit links and media edit links...etc.

**Comment by EWashb** [comment]
There could be a possible path forward with the entity usage module. At first glance, it would get us about 90% of the way there, but there are not currently options to evaluate external links.
