### ISSUE TITLE
React Login Widget for BTSSS (Beneficiary Travel Self-service System)

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9157]
### User Story or Problem Statement

As a Veteran, caregiver, or beneficiary eligible for reimbursement of mileage and other travel expenses to and from approved health care appointments, I need to effectively and efficiently find and log in to the Beneficiary Travel Self-Service System (BTSSS).

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* SW Content team is revising the travel pay landing page.

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Confirmed with Dave: not a priority til Q4 / after OAuth ships.
