### ISSUE TITLE
Determine and Create Additional Sorry-Cypress Helm Templates 

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9158]
## Description

Sorry-cypress has some Ingress templates but additional helm templates are needed in order to ensure it runs in the manner it should within the EKS cluster.

## Acceptance Criteria
- [x] Additional templates needed run Sorry-Cypress are identified.
- [x] Templates are created and deployed to the Sorry-Cypress Application Manifest.

## Implementation Details
- Templates needed for Ingress, Secrets, DNS.
- Link to EKS App Manifests https://github.com/department-of-veterans-affairs/vsp-infra-application-manifests

## Tasks
- [x] Read/review Platform created applications on EKS for required charts.
- [x] Add Charts to use Traefik instead of default sorry-cypress ingress resources.
- [x] Add charts to use DSVA hosted secrets in Parameter Store
- [x] Add charts for DNS resolving in Traefik
