### ISSUE TITLE
Display a preview of the Veteran experience of Facility COVID status within the Faclity form

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9160]
## User Story or Problem Statement

As an Facility editor, i want to see how the Veteran experiences Low/Medium/High for COVID status. 

<details><summary>Design</summary>
​
![Screen Shot 2022-05-24 at 11 04 24 AM](https://user-images.githubusercontent.com/41017988/170102689-bcb1c848-9a7f-4d50-be5f-7c77e0181962.png)

[Figma](https://www.figma.com/file/W4oO1UO0ilSgHu1kXf1Sj0/VAMC-facilities---COVID-status?node-id=0%3A1)

</details>

## Acceptance Criteria
- [ ] When an editor selects a COVID status, they get a preview of the Veteran experience, per the design. 
- [ ] No linked timestamp, for now.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
