### ISSUE TITLE
Load test Authenticated GET requests to various content types

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#9203]
In #8080 we got some baseline metrics for anonymous GET requests to the Benefits Detail Page which was around 217/second. We now need to test authenticated GET requests to various content types as that will be reflective of real world traffic when the new Next.js build system evolves to allowing for public requests. 

## AC
- [ ] Determine the average RPS (requests per second) for authenticated GET requests for a node of the Benefits Detail Page content type. This should be with a warmed cache. 

## Tasks
- [x] Get Umami demo working via simplytest.me (quick hello-world example, not sustained, avoid DDoS)
- [x] Write a test file for to login based on the Umami login code on local DEV
- [x] Document initial setup and how to run load test
- [x] Loadtest the Benefits Detail Page on staging.cms.va.gov
- [x] Get SOCKS passthrough working (https://github.com/tag1consulting/goose/issues/490) with example test file
- [x] Post results to this thread, or maybe Confluence

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8050#issuecomment-1134929759_

> We discussed in planning now, that the public API requests will be authenticated so it is still worth testing authenticated GET requests. I finally got Goose Load Testing working with concurrent requests on Friday so we should still pull in a new story this sprint to get these metrics on the authN GET requests.

**Comment by ElijahLynn** [comment]
Working on getting requests routed through our SOCKS proxy with Goose > https://github.com/tag1consulting/goose/issues/490

**Comment by ElijahLynn** [comment]
`content_build_api` user: 
```
 === PER REQUEST METRICS ===                                                     
 ------------------------------------------------------------------------------  
 Name                     |        # reqs |        # fails |    req/s |  fail/s  
 ------------------------------------------------------------------------------  
 GET auth /disability/h.. |        21,354 |         0 (0%) |    68.01 |    0.00  
```

**Comment by ElijahLynn** [comment]
I cannot upload HTML files but here is the HTML report zipped up from this command, and I took a full page screenshot too:

```shell
 cargo run --release -- --host https://staging.cms.va.gov --report-file report-file.html --running-metrics 1 --users 125 --hatch-rate 10 --run-time 3m --no-reset-metrics
```

![_home_elijah_Projects_va gov_va gov-cms_tests_loadtest_report-file html](https://user-images.githubusercontent.com/1504756/171961787-a8745cfa-7741-4ccd-bedb-078bacb5a38a.png)
[goose-load-test-report-20220603-staging.cms.va.gov.zip](https://github.com/department-of-veterans-affairs/va.gov-cms/files/8836010/goose-load-test-report-20220603-staging.cms.va.gov.zip)
