### ISSUE TITLE
Add slack notification as a messages notification option

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9235]
## User Story or Problem Statement

As a a group of editors in need of notification of something in the CMS (example a new VA Form is created) I need for my team to be notified in slack.

## Acceptance Criteria
- [x] Update existing [slack module](https://www.drupal.org/project/slack) to latest release 1.3
- [x] ~Update existing slack notification in post_api to use the new slack method~ - No change needed
- [x] Add slack as message option in code.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
Epic changed to accommodate current state.

**Comment by swirtSJW** [comment]
Getting pretty close with this.
![image](https://user-images.githubusercontent.com/5752113/174312582-f960d50c-00ef-46fc-afd1-fad59dbf8f33.png)
