### ISSUE TITLE
Improve CMS offboarding with an automated check of active VA accounts

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9239]
## User Story or Problem Statement

The only way we know if a CMS user no longer works at VA, other than getting notified “manually” via Help Desk, is if we send a mass email to them and it bounces back.

We have also manually purged editors who haven't logged in in the last 6 months. 

How might we check if a CMS editor no longer has an active va.gov emaill address? 

If we build an automated check and learn that `justin.bieber@va.gov` no longer works at VA, who should be notified? What are the next steps? 

## Acceptance Criteria
- [ ] TBD 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [x] `⭐️ User support`

**Comment by stefaniefgray** [comment]
@swirtSJW Do you think we're still going to automate alerts for when a user has not logged in for 6+ months? Will we be implementing LDAP to track whether or not they still work for VA.gov? 

Dave C. is still very interested in this subject and in automating this process in general since there are many manual steps we must take each month when tracking inactive accounts and offboarding users

**Comment by TroyA6** [comment]
Just a thought - would it be possible to develop a 'button' that would query for users who had not logged in in 6 months - then set them to Blocked, and generated a list of those set to blocked... ?
The button would only be accessible to CMS Admins/Helpdesk/whoever deemed necessary.
