### ISSUE TITLE
Allow Benefits Hub and Benefits Detail <title> tags to exceed 70 characters

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9242]
## User Story or Problem Statement

As a Benefits hub editor, i want to set page meta-titles longer than 70 characters, on a case by case basis. 

### Background

The [content style guide](https://design.va.gov/content-style-guide/seo#title-tags) specifies 70 characters or less for the two Benefits Hub content types. 

Occasionally, editors want to exceed that, and have page meta-titles match the h1 on the page. See https://github.com/department-of-veterans-affairs/va.gov-team/issues/41185 w/r/t to the [View or change your dependents on your VA disability benefits](https://www.va.gov/view-change-dependents) page. 

<details><summary>Screenshot</summary>

<img width="979" alt="Edit_Benefits_Detail_Page_View_or_change_dependents_on_your_VA_disability_benefits___VA_gov_CMS" src="https://user-images.githubusercontent.com/643678/170359867-14607828-c40d-4769-b98e-93f4c6531521.png">

</details>

## Acceptance Criteria
- [ ] Metatag title field is removed on Benefits Hub Detail Page and Benefits Hub Landing Pages and are populated from default meta tags settings with the pattern `[node:title] | Veterans Affairs`  

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per refinement conversation with Dave: 
1. Not urgent and could be slotted into sprint planning
2. Belongs to Sitewide CMS, not Public Websites, so updating labels

Holler if that confuses / surprises anyone.
