### ISSUE TITLE
CMS personas

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#926]
### User Story
As a CMS team, we want to have a shared understanding of users in terms of goals and capabilities, so that we can design better CMS experiences with them

## Acceptance Criteria

- [x] Segmentation validated
- [x] Persona attributes defined 
- [x] Proof of concept persona defined

Synthesis / Analysis
- [x] Attributes matrix filled out 
- [x] Personas identified

Artifacts
- [ ] Personas socialized with team and stakeholders
- [ ] Personas stored in GitHub
