### ISSUE TITLE
Redirect users on login to their content (section taxonomy term)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#927]
### User Story or Problem Statement

Most CMS users only edit content in one section of the site. Eg

- a Public Affairs Officer at VAMC Pittsburgh only edits VAMC Pittsburgh content
- a Web Manager at edits VISN 4 content (and VAMC system content "below" it)
- a VHA editor edits VHA content (health care benefits hub, VISN 4 content, etc)
- a Content admin on the Public Websites team edits content in sections across the site. 

Ideally upon login, these users would be redirected to a dashboard of their content. 

Content admins and admins, who are typically not assigned to a section, can just be redirected to /admin/content, for now.

### Affected users and stakeholders

* All  users

## Acceptance Criteria
* ~~user X will be redirect to Section Y~~
* ~~user _foo_ will be redirected to Section _bar_~~
* ~~user A will be redirected to Section B~~
* ~~users who are members of more than one section are redirected to a list of sections  they belong to (on user profile page?)~~
*  Send all users to their user page where they will see a view block that shows the section links for any section they belong to.

## Runbook  
This is particularly relevant for feature launches, or for making changes to the content model that require front end changes as well.
1. Step_to_get_to_production_X  
1. Step_to_get_to_production_Y
1. Step_to_get_to_production_Z

## Possible tickets to create for this epic

- [ ] Spike task, with some of the following attributes:
* Identify the baseline against which we will measure improvements
* Ideation (sketching, cross-displinary meeting of minds around how the problem may be solved)
* Analysis of the drupal landscape
* Possible implementation(s)
* Proof of concept or prototype
* UX writing discovery

- [ ] User research
- [ ] Design
- [ ] UX writing
- [ ] Usability testing (eg with a prototype or other design stimula)
- [ ] Implementation
  - [ ] A drupal service that can be called to get  user's "membership"  (getMemberships()) and the memberships parents (getMembershipsParents())  This will also be needed for #930 
- [ ] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [ ] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by swirtSJW** [comment]
@kevwalsh I am thinking that Oksana's work to get the sections you belong to on the user page makes redirecting to the section pages obsolete?  https://github.com/department-of-veterans-affairs/va.gov-cms/issues/1243    Thoughts?

**Comment by swirtSJW** [comment]
Discussion on scrum after meeting today was to alter this to only redirect to the user page since a user will only be presented with the section(s) they belong to.   It would still take an extra click to to get to their section, but they would not be bypassing their established user dashboard, which may contain other blocks in the future.
