### ISSUE TITLE
Facility COVID status audit tool should be visible to members of the VHA Digital Media section

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9286]
## User Story or Problem Statement

As a member of [VHA](https://prod.cms.va.gov/section/vha) section OR as a content admin, i should be able to access the [Facility Status view](https://prod.cms.va.gov/admin/content/facilities/facility-status). 

Relates to #7707 (currently moved to the icebox)

## Acceptance Criteria
- [ ] user `jeffrey.grandon@va.gov`, a content publisher who is a member of "VHA" section, can access that view.
- [ ] user `Victor.A.MCtest` a content publisher who is not a member of "VHA", cannot.
- [ ] user `randi.hecht@va.gov`, a content admin, can access that view

## Implementation steps
* ~~One approach: Apply the plugin from #7707 to admin/content/facilities/facility-status, allowing members of VHA section to access the view. There are a few other views in the Facilities tab that they should also be given access to.~~ (moved to icebox)
* As an alternative we could simply make the views accessible to authenticated users

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by JayDarnell** [comment]
Looking at the proposed implementation steps in the related issue: #7707 (a workbench access views plugin) I'm not sure this is the correct direction given this portion of the description taken from the workbench access module: 

`Note that the module only controls access to content editing. It does not provide any content filtering of access restrictions for users trying to view that content.`

I'm not sure workbench access it the correct direction we should go for controlling access to this. I'll keep digging though.

**Comment by amonoxia** [comment]
The workbench access views plug-in I think is to allow certain roles to edit the view. It sounds like we just need to edit the view/view block permissions within the view itself, independent of #7707

**Comment by EWashb** [comment]
We will probably want to alter the scope of this or close altogether  with the retirement of covid status

**Comment by jilladams** [comment]
Closing re: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/13681
