### ISSUE TITLE
Notify Slack on CMS Build failures

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#9295]
## Background

Action item follow up to #9293. We need to notify Slack on CMS Build failures so we can take swift action. 

_Originally posted by @ElijahLynn in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9293#issuecomment-1145110852_

> This didn't surface because our http://jenkins.vfs.va.gov/job/builds/job/cms/ doesn't notify Slack on failure. We need a new story to add this in so we catch these build failures ahead of time next time.

## Acceptance Criteria

- [ ] Update build failure alert to get sent to #CMS-Notifications

## Tasks
- [x] Update Jenkins build job to notify #cms-notifications channel in addition to the #devops-deploys that it is already doing
  - [x] Update va.gov-cms/Jenkinsfile.cd to use new paramater - https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9356
  - [x] Update devops:jenkins job to accept new parameter, if exists -https://github.com/department-of-veterans-affairs/devops/pull/11382
- [x] Test
  - [x] change branch on :/job/testing/job/cms to test if new param is there, may need to run seed job first
  - [x] run seed job
  - [x] run test build
  - [x] repeat
- [ ] Get PRs approved and merged

**Comment by ElijahLynn** [comment]
This is all ready to go and tested in two PRs:

1. https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9356
2. https://github.com/department-of-veterans-affairs/devops/pull/11382

**Comment by ElijahLynn** [comment]
Just merged the two PRs and watching http://jenkins.vfs.va.gov/job/testing/job/cms/2399/console for final testing to make sure a regular deploy doesn't break (which I tested for, so it shouldn't).
