### ISSUE TITLE
CMS design system user research 

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9325]
## Background

As we onboard new designers to the Sitewide Crew, the Sitewide CMS team needs to understand what types of documentation work for the various product needs. This will also serve as a scenario to determine where the Sitewide CMS review process should be implemented as part of #9152. 

As a result, the Sitewide CMS team can learn from this research to help determine where the gaps are in both the process collaboration cycle and design system governance and Figma files. 

## Acceptance Criteria
- [x] Onboard new designer to current state design system
- [ ] Designers complete scenario outlined in #9339 
- [ ] If other gaps are determined in documentation, Figma, or other parts of the UX process, tickets are created as needed with help of the PM or DM

**Comment by EWashb** [comment]
This is no longer in scope or makes sense with the current roadmap. Closing to refocus efforts.
