### ISSUE TITLE
Remove chatbot traffic control code from codebase

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9337]
## Description

≥2 weeks after chatbot traffic is increased to 100% in #9332 (so, in Sprint 62), the ability to control traffic can be removed forever.

The code that needs to be removed was previously commented out. It simply needs to be removed.

## Tasks
- Remove commented out code. - 30 mins
- Test - 1 hr.
1.5 hrs

## Acceptance Criteria
- [ ] traffic-control code and conditionals removed from codebase
- [ ] possibly needs new test written (Ryan had to remove one in previous ticket)
- [ ] solid QA

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Platform CMS Team`
- [ ] `Sitewide program`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
@allisonlu has seen this code and can field questions from whoever picks this ticket up.

**Comment by jilladams** [comment]
Now unblocked: https://dsva.slack.com/archives/D03E5UZUMPX/p1658507286274079?thread_ts=1656607607.299349&cid=D03E5UZUMPX

**Comment by ryguyk** [comment]
@jilladams @wesrowe It appears that my understanding of what needed to be removed might not have been entirely accurate. We had previously commented out logic that limited the display of this CTA. This resulted in showing the CTA to all users. The thought was that we'd simply remove the code that was commented so that this would permanently show to 100% of users.

However, in looking deeper, it appears that the CTA React widget _has been replaced_ with a statically generated alert.  It seems that we do not only want to remove the commented code. Rather, it seems we might be able to remove the entire React widget. I want to ensure that we all agree on this.

**Comment by jilladams** [comment]
I don't know enough to have a strong opinion here. We don't want to disrupt however it works live, but if we aren't high confidence about what that means in the code, we can prob get a meeting with Ian Santarinala to confirm re: any questions.

**Comment by jilladams** [comment]
Confirmed in scrum: remove gating, per Randi's note on the other ticket, also remove React widget.
