### ISSUE TITLE
"WEB Rebuild" User Interface

### ISSUE THREAD

**Issue by jonpugh** [department-of-veterans-affairs/va.gov-cms#934]
### User Story or Problem Statement

> As a "non-technical user", I need "to quickly trigger WEB rebuilds using any branch of code I want" so I can "test out new functionality in a place I can control".

### Affected users and stakeholders

* Product owners can use these environments to demo new end to end functionality before it goes to production
* CMS & WEB Release Managers: Ability to rebuild and review static site output after content changes in PR environments. 
* CMS & WEB Developers: Ability to quickly reset a static site build to different states from different codebases is very helpful for development and debugging.
* Site owners and users: Demo environments can be setup for any combination of CMS and WEB pull requests.

### Assumptions
* Only open "Pull Request" branches will be available to choose from.
* Users may want to keep the data in their CMS instance when doing a WEB rebuild.
* Users may want the freshest copy of Production data in the CMS when doing a WEB rebuild.
* Users may want to keep changes to their CMS instance configuration (structure, schema, etc) when doing a WEB rebuild.
* Users may want to discard changes to their CMS instance configuration (structure, schema, etc) when doing a WEB rebuild.
* Users don't understand what "database sync" or "config import" means. They know they have a CMS instance, a Website that's built from the CMS content, and they know it's a copy of production running on some developer's copy of code. Design the UX to reflect that. and help them understand what the process is. 

## Acceptance Criteria
* A non-technical user can be granted access to https://devshop.cms.va.gov, and can be trained to:
  * Create a new demo environment.
  * Visit and log in to that demo environment.
  * Rebuild the environment, understanding when and how they might lose changes to their content or configuration.

## Runbook  

The code for the "Rebuild Web" task is currently stored in the "devops" repo: 

- https://github.com/department-of-veterans-affairs/devops/pull/6218
- https://github.com/department-of-veterans-affairs/devops/tree/ansible/build/cms-ci/ansible/build/roles/cms-ci/va_gov_devshop

When the CMS-CI playbook is run, the custom module and a custom makefile is copied into the server, which is then built into the devmaster front-end site.

This means as of right now, to update the server with the latest code, you need to do one of two things:

1. Manually upload the va_gov_devshop module into the server.
2. Run the playbook to upgrade the devshop server, which will include the default devmaster upgrade process (creating a new devmaster platform, then migrating the site to it.).
3. Build and deploy a new devshop image. This will soon be setup to happen in BRD, automatically, at least daily, just like CMS and other apps.

## Possible tickets to create for this epic

- [x] User research
- [x] Design
- [x] Usability testing (eg with a prototype or other design stimula)
- [x] Implementation
  - [x] Front-end.
  - [x] Backend.
- [x] Documentation (What needs changing or adding to the documentation?
- [ ] Product release notes (How will we describe this feature to CMS users?)
- [x] Training (Will any users require additional training?)
- [ ] Metrics (How will we measure any improvements)

## Labels for  this issue
- [/] Issue type (red) (defaults to Epic)

**Comment by ElijahLynn** [comment]
@jonpugh Can you post some screenshots and/or gifs of the new work and behavior?

**Comment by jonpugh** [comment]
Still working on the Docs. Will finish today.

**Comment by jonpugh** [comment]
New Create Environment Form in DEMO project only:

![Screenshot from 2020-02-22 12-16-26](https://user-images.githubusercontent.com/106420/75096509-2c868b80-556e-11ea-8683-04c3440669d2.png)

With advanced options expanded:

![Screenshot from 2020-02-22 12-17-39](https://user-images.githubusercontent.com/106420/75096511-36a88a00-556e-11ea-906f-c4ff77a09e9c.png)

Web Rebuild Button
![Screenshot from 2020-02-22 12-24-29](https://user-images.githubusercontent.com/106420/75096525-59d33980-556e-11ea-94f4-b0c1ffe5cd23.png)

Web Rebuild Form
![Screenshot from 2020-02-22 12-39-59](https://user-images.githubusercontent.com/106420/75096745-82f4c980-5570-11ea-8c5c-30e1a53d6e19.png)

Web Rebuild Form Expanded
![Screenshot from 2020-02-22 12-41-02](https://user-images.githubusercontent.com/106420/75096750-9bfd7a80-5570-11ea-8155-70e2b03fb788.png)

**Comment by jonpugh** [comment]
Docs updated with these screenshots and step by step instructions for creating environments and triggering rebuilds: https://github.com/department-of-veterans-affairs/va.gov-cms/blob/50cb1d6a35ba622c58643fe3432bf73aa9c7f8aa/READMES/environments.md
