### ISSUE TITLE
CMS Implement design showing facility hours when "use facility's hours" is selected

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9357]
Two content types allow VAMC editors to select "use facility's hours": VAMC Facility Health Service and VAMC Facility Non-clinical Service. But editors may not know what the facility's hours are in that context., especially if they are editing services for multiple facilities.

ACs, pending design in #8302 
- [ ] Implementation matches [design spec/mockup ](https://www.figma.com/file/i3dqsSu3ZXtDdlGFNVns7G/Facility-hours?node-id=2%3A6947)
- [ ] Design review passed/accepted 
- [x] #10058

- [ ] When "Use facility hours" is selected, display the hours of the facilities in the form
- [ ] When "Use facility hours" is selected, display the hours of the facilities in node view

**Comment by dsinla** [comment]
Has the assumption that there are no FE changes needed, will revisit if need arises

**Comment by suzanne-gray** [comment]
[Annotated design file ](https://www.figma.com/file/i3dqsSu3ZXtDdlGFNVns7G/Facility-hours?node-id=2%3A6947)is ready in Figma. Any questions, ask me or Cindy. Note that the improvements to the hours widget will be handled separately in #10092.

**Comment by swirtSJW** [comment]
@omahane   I am not sure if this   is using related logic or not
![image](https://user-images.githubusercontent.com/5752113/184724670-297d58bd-168e-447e-ba23-a0df5bc44de9.png)
on facility covid status /node/add/health_care_local_facility

**Comment by swirtSJW** [comment]
Another differently similar case
/node/add/health_care_local_health_service

![image](https://user-images.githubusercontent.com/5752113/184725252-461ffb12-493a-4f01-9593-20257e35131c.png)

**Comment by swirtSJW** [comment]
As you are putting together a solution.  Here is future use case too.
![image](https://user-images.githubusercontent.com/5752113/184725739-fa4b3532-d9f7-4d98-8b34-38801f6e46d0.png)

You don't have to solve it now... but it would do the same thing, even sourcing from the same node.

**Comment by swirtSJW** [comment]
This would also be similar 
![image](https://user-images.githubusercontent.com/5752113/184726021-52471a1b-9438-43fe-8564-9823746360f4.png)
/node/add/health_care_local_health_service

**Comment by omahane** [comment]
# Proposed Approach
## Tasks for edit display 
- Evaluate if selection on "field_office_hours" is "Use Facility Hours"
	- This is a field that of the "Service location" paragraph, which is a referenced entity on field on the VACMS Facility Health Service bundle
- Get the paragraph's parent node 
- Get the hours field of the parent node
- Create "[pseudo field](https://gorannikolovski.com/blog/display-and-form-pseudo-fields-drupal-8-and-9)" in form
- Populate pseudo-field with hours field data 
- Hide pseudo-field if the "Use Facility Hours" is not selected

### Implementation note: 
- Use hook_form_alter in va_gov_vamc.module

## Tasks for view display
- Evaluate if selection on "field_office_hours" is "Use Facility Hours"
- Get the paragraph's parent node 
- Get the hours field of the parent node
- Display hours
	- Create an hours view display (if it doesn't already exist)

### Implementation note:
- Use preprocessor to add the hours to the available variables
- Use a template to display the hours

**Comment by swirtSJW** [comment]
@christianmburk I think that plan sounds great.  This will be your friend `$node->get('field_office')->referencedEntities();`

Consider how we can adapt this so we have some reusability to it if possible.

**Comment by omahane** [comment]
I have the hours displaying, but I need to test this under all conditions:

- Use facility hours = "Use the facility's hours"
- Use facility hours = "Provide specific hours for this service"
- Use facility hours = "Do not specify hours"

**Comment by omahane** [comment]
The PR branch is showing this working when editing a VAMC Facility Health Service with one service location. Facility hours should show when "Use the facility's hours" is selected or if the form opens with them already selected. The select list has also been converted to radio buttons.

Adding a second causes the edit form display to stop working correctly.
