### ISSUE TITLE
Audit Opening Hours Comments fields

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9358]
## User Story or Problem Statement

As a designer or engineer working on Opening Hours, i want to know what editors have added in comment fields

In #8935 we removed time zone content from Opening Hours comment fields. What's left? This will help us learn how editors are using Comments fields, so that we can 
1. Provide better guidance about what to put in Comments
2. Make improvements to the Hours widget, such as a "Closed" option

## References
The following scripts may have some value in terms of code reusability:
1. Script `VACMS-6931-switch-service-locations-office-hours.php` writes to a CSV file
2. Script `VACMS-8935-scrub-tz-in-hours-field-comment.php` manipulates Opening Hours data

## Field Sources
The "Office Hours" field is present on the following content types:
- VAMC Facility (health_care_local_facility - field_office_hours)
- VAMC System Billing and Insurance (vamc_system_billing_insurance - field_hours_for_copay_inquiries_)
- Vet Center (vet_center - field_office_hours)
- Vet Center - Community Access Point (vet_center_cap - field_office_hours)
- Vet Center - Mobile Vet Center (vet_center_mobile_vet_center - field_office_hours)
- Vet Center - Outstation (vet_center_outstation - field_office_hours)

The "Office Hours" field is also present on the following paragraph types:
- Service Location (service_location)

The following content types use the Service Location paragraph type:
- VAMC Facility Health Service (health_care_local_health_service)
- VAMC Facility Non-clinical Service (vha_facility_nonclinical_service)

## Acceptance Criteria

- [ ] We have script(s) to generate CSV(s) showing any Opening Hours data that has comments
- [ ] Should include fields: node id, content type, url, moderation state, comment
- [ ] We may need two CSVs, one for Service Location data. Ideally, it would also show the content type and NID that references it. 
- [ ] Scripts are documented somewhere.

<details><summary>Old ones</summary>

- [ ] display machine, not `default`
- [ ] URL [`/admin/content/audit/opening-hours view`]
- [ ] Menu item setting: parent audit, label "Opening hours"
- [ ] limit to 100 per page, paginated
- [ ] show result count in header
- [ ] default columns
  - [ ] Title (sortable) 
  - [ ] Edit button (not operations, no column heading) 
  - [ ] Content type (sortable)
  - [ ] Moderation State
  - [ ] Section (field_administration) (sortable)
  - [ ] Is Locked (optional)
  - [ ] Last updated (date time and by user) (sortable, default sort, DESC)
  - [ ] Fields (combine into one header)
    - [ ] field_hours_for_copay_inquiries_
   -  [ ] field_office_hours
- [ ] filters
  - [ ] text search (exposed)
  - [ ] content type (exposed): 
    - [ ] multiselect with the following options:  VAMC System Billing and Insurance, Vet Center - Community Access Point, VAMC Facility, Vet Center, Vet Center - Mobile Vet Center Vet Center - Outstation. 
    - [ ] don't allow other content types
    - [ ] preseslect the following: VAMC System Billing and Insurance Vet Center - Community Access Point Service location
  - [ ] moderation state (exposed)
  - [ ] section (exposed) (workbench access section; single select, show children)
  - [ ] "Copay inquriries hours": `field_hours_for_copay_inquiries_`: is any / is empty / is not empty 
  - [ ] "Hours": `field_office_hours`: is any / is empty / is not empty 
  - [ ] Reset button exists
  - [ ] Apply button says 'Filter'

Stretch
- Someway of filtering based on whether Comments are filled out. 

</details>

## Implementation steps

Updating scripts from #6931 and  #8935

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Audit was performed with [this airtable](https://airtable.com/appxsEaJnhCDMPeD2/tblm7ZLbTl7GIeiZG/viwGDP3ub7Dl0zVzb?blocks=hide)

High level summary here
![image.png](https://images.zenhubusercontent.com/5d6e57ad330f64311395f08b/5f4a7fd4-ee8f-4815-9a55-1f44c43e8b92)
