### ISSUE TITLE
Scale the CMS Application

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9368]
## Background

Ensure the CMS infrastructure is performant and scalable for the anticipated increase in site traffic associated with a Public API. Conduct load testing to determine baseline system stress levels and develop strategy to scale.

### Affected users and stakeholders

* CMS engineers

## Acceptance Criteria
- [ ] Assess current average CPU load and adjust instance size as needed
- [ ] Determine baseline for anonymous, authenticated GET requests, and average response time of system through load testing and adjust as needed
- [ ] Create new/modify existing monitoring thresholds in Datadog to identify activity trends

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
All work contained in this epic is closed. Closing.
