### ISSUE TITLE
Treat empty field_office_hours rows as "Closed" on all FE templates

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9390]
## User Story or Problem Statement

As a user of a facility service, i want non-ambiguous opening hours. 

Currently, null rows in opening hours are left empty on th eFE

<details><summary>Screenshots</summary>

Current state

<img width="543" alt="screenshot-of-hours" src="https://user-images.githubusercontent.com/643678/172890448-f19071fa-8380-4510-af51-655e2c25bd4d.png">

corresponding editing experience
​​
<img width="629" alt="screenshot-cms-hours" src="https://user-images.githubusercontent.com/643678/172890717-c5593109-b357-4b3a-a5bd-1fe43ba364e7.png">

affected content types (and templates) and fields, [from airtable](https://airtable.com/shrqxgf0Kj42iVjaV/tblPdSdScGDeV1Y6f)

<img width="615" alt="VA_gov_CMS_content_model_documentation__Fields_-_Airtable" src="https://user-images.githubusercontent.com/643678/172891549-154487e9-2700-4714-a582-df8da131c6fb.png">

Note that field_hours_for_copay_inquiries_ is being replaced with field_office_hours via #9359. 

</details>

## Acceptance Criteria
- [ ] When From, To, and Comment is all empty, print "Closed" on the FE

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
I removed the high priority pin, which we try to reserve for sprint goals and critical defects.
