### ISSUE TITLE
Make file move failures more descriptive or non-build breaking

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9394]
## User Story or Problem Statement

As an engineer investigating a content-build breaking file move failure, I would like to have more information to tell me what is failiing to I can fix it without  guessing.

current failure when a file is incorrectly linked (often occurs with pdfs)
```
Run node ./script/prearchive.js --buildtype=vagovprod
  node ./script/prearchive.js --buildtype=vagovprod
  shell: /usr/bin/bash -e {0}
  env:
    CMS_NOTIFICATIONS_SLACK: CJT90C0UT
    VFS_PLATFORM_BUILDS_SLACK: C0MQ28[1](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:1)DJ
    BROKEN_LINKS_SLACK: C030F5WV[2](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:2)TF
    CONTENT_BUILD_CHANNEL_ID: C02VD909V08
    DSVA_SCHEDULE_ENABLED: true
    NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
    BUILDTYPE: vagovprod
    DEPLOY_BUCKET: content.www.va.gov
    DRUPAL_ADDRESS: https://prod.cms.va.gov
    CHROMEDRIVER_FILEPATH: /usr/local/share/chrome_driver/chromedriver
    vagovprod_buildtime: 1654787974
    AWS_DEFAULT_REGION: us-gov-west-1
    AWS_REGION: us-gov-west-1
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    DRUPAL_PASSWORD: ***
    DRUPAL_USERNAME: ***
internal/fs/utils.js:622
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:468:10)
    at Object.readFileSync (fs.js:[3](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:3)77:35)
    at linkAssetsToBucketProxyRewrite (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/link-assets-to-bucket.js:[4](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:4)1:3[5](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:5))
    at linkAssetsToBucket (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/link-assets-to-bucket.js:5[6](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:6):3)
    at main (/actions-runner/_work/content-build/content-build/content-build/src/site/stages/prearchive/index.js:45:3)
    at Object.<anonymous> (/actions-runner/_work/content-build/content-build/content-build/script/prearchive.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:[7](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:7)6[9](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:9):[14](https://github.com/department-of-veterans-affairs/content-build/runs/6815632952?check_suite_focus=true#step:29:14)) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Error: Process completed with exit code 1.
```
Here is the revision that broke and caused the ^^ error https://prod.cms.va.gov/node/46958/revisions/656988/view

Two things about this would be ideal:
 1) **preferred** if the error were not build breaking failure, it would just get caught later as a broken link when the link scanner runs.
2) If it was build breaking, output the details about the page/node where it was encountered.

## Acceptance Criteria
- [ ] An improper link to a file is not a build breaking failure
OR
- [ ] A build breaking link to the file, provides more details about what page this link is on.

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
