### ISSUE TITLE
Adjust facility migrations timing

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9395]
## User Story or Problem Statement
As a data consumer I want our migrations to run as soon as possible after upstream data is available so that the window where data is out-of-date is kept to a minimum.

### Current problem
FacilityAPI pulls data from VAST at 7:30AM.  CMS pulls data from FacilityAPI at midnight.   That creates a window of up to 40.5hrs where CMS data is out-of-date with VAST and 16.5 hrs out of date with Facility API.

## Acceptance Criteria
- [x] Audit Facility API sources (VAST, access to care, health connect ...) to determine when they are each updated.
   - **Answer:** Lighthouse loads their data from all automated sources at 7:30AM ET.  The time to load is approximately 5 min.
- [x] Based on the audit, the best time(s) for the CMS facility migration  to run are determined
   - **Answer:**  CMS needs to only pull from facility api once, after  7:35AM ET.  swirt recommending moving CMS pull to 8:00AM ET.
- [x] Devops ticket created to switch the time(s). (@swirtSJW ) https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9703
- [x] Update documentation
- [ ]  KB article update

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
Discussed [this in cms-lighthouse slack](https://dsva.slack.com/archives/C02BTJTDFTN/p1654813660583599).  We should move our facility migrations to be pulling at 8:00 AM ET

**Comment by JayDarnell** [comment]
Perhaps we could cowork on this @swirtSJW

**Comment by kevwalsh** [comment]
We can close this as work completed. 

We determined that there are no KB articles affected by this change. 

The rest of the work will be performed by DevOps in an upcoming sprint, via #9703, at which point #9395 can be merged.

**Comment by swirtSJW** [comment]
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9703#issuecomment-1242491879
