### ISSUE TITLE
Add synthetic monitoring of prod Facility Locator

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9399]
## User Story or Problem Statement

As as maintainers of the facility locator, I want synthetic monitoring of the Facility Locator to make sure we are alerted if Veterans are not getting results for their query..

Recommended as a [result of Postmortem](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/pull/501) 

## Acceptance Criteria
- [x] An alert occurs if the facility locator is not present
- [x] An alert occurs if a search fails to return results
- [x] The above checks run every ___ hours.
- [x] notification of some kind should appear ___ and be logged by ____

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by zachclarity** [comment]
I added this[ Datadog Monitor and will review with @jtmst to verify](https://vagov.ddog-gov.com/monitors/88715).   Also [DOTS may provide access to @jtmst ](https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance) and I am getting clarification from my team.  But the process is

**Comment by zachclarity** [comment]
Steps
1 - Go to Max.Gov Jira [HERE](https://login.max.gov/cas/login?service=https%3A%2F%2Fvajira.max.gov%2Fservicedesk%2Fcustomer%2Fportal%2F1%2Fcreate%2F18) 

2 - Submit a request on Max.Gov for access to DataDog (instance name: vagov.ddog-gov.com

3 - Check your email inbox for an invite to Okta

4 - Log in to Ablevets Okta [HERE](https://ablevets-dots-va.okta.com/)

5 - Launch DataDog from Ablevets Okta under “My Apps” (app name: vagov-va-datadog)

**Comment by jilladams** [comment]
Noting: 
* This monitor originated from a post-mortem around COVID status descriptions. From the post mortem: "A change was made to facility locator to pull COVID-19 status descriptions from a static data endpoint in va.gov.  The change mistakenly used the API domain instead of the environment domain.  This caused a failure to find data, and with no fallback present, caused Facility locator to fail to display health care facilities."
* The name of the monitor was: "Facility Locator Covid Location Test"
* This monitor now 404s -- it's been removed from Datadog. I don't find any conversation around that, but presumably it probably got removed once we deprecated COVID facility statuses in #13676 

This original monitor was among the first of its kind for Sitewide, before Code Yellow / Watch officer existed, and before we had teams / dashboards in Facilities, so this monitor alarmed to the #oncall channel in DSVA slack for Platform response, and Facilities team was not responsible for triage afaik.

The ticket here was to let us know if Veterans don't get Facility Locator response as expected from a browser test. We now have a few other monitors on Facility Locator API endpoints that will alert us to anomalies in traffic. We _don't_ have any other browser synthetic test.  

It might be worth reviving this and creating a similar new monitor if Plat can't help us surface the old one / revise it. Plat thread opened here about the fact it's gone now: https://dsva.slack.com/archives/CBU0KDSB1/p1705532707740479

FYI @xiongjaneg

**Comment by jilladams** [comment]
From Plat: 
>  the resources pointed to by this url do not exist.   You can go ahead and recreate it.

Reopening to track in the backlog.

**Comment by xiongjaneg** [comment]
Noting other resources are available from the datadog channel, Adrian Rollett, etc.

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/9399?planning-poker) with Zenhub @eselkin

**Comment by jilladams** [comment]
Noted you'd flagged that concern before, when this came up in refinement today. @eselkin I'd love to get a clear sense of what is different now than when the original synthetic monitor was created / worked. I don't not believe you (double neg?) just we need to sort out how it worked before / doesn't now, and if there's something Datadog owners could enable that would unblock it, or if WebGL is needed, there's potential we could file this as a feature request with Datadog on behalf of VA as well, etc.  Any screenshots or something of what happens when we try could probably help with sorting that out.

**Comment by mmiddaugh** [comment]
@xiongjaneg two additional notes from refinement which may need to be reflected in AC

- Max suggested the monitor should reflect several different searches 
- Since the COVID label was part of the reason the previous monitor was removed, I'd suggest we choose the name for this monitoring intentionally so we don't suffer this fate again.  (i.e., if we don't tie it to something specific, it won't be at risk if the Facility Locator d/c that feature)

**Comment by xiongjaneg** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sitewide-Facilities-639f5253e4b702a32376339e/issues/department-of-veterans-affairs/va.gov-cms/9399?planning-poker) with Zenhub @maxx1128

**Comment by davidmpickett** [comment]
@jilladams @eselkin This doesn't have points or a sprint assigned. Is this actually something that should be considered for Sprint 4?

**Comment by jilladams** [comment]
Noting: today the Facility Locator experienced a spike in 403 errors from the new Facilities-api v2 endpoint: https://vagov.ddog-gov.com/apm/services/facility-locator/operations/rack.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=eks-prod&fromUser=true&groupMapByOperation=null&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A75%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21f%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&view=spans&start=1716924577835&end=1716926350000&paused=true

We are still triaging, and not clear exactly what happened / is happening here, but we should try to prioritize Facility Locator monitoring potentially, pending the results of what we find today.
