### ISSUE TITLE
[EPIC] [Events] Integrate with the National Resource Directory (https://nrd.gov/) to import events

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9429]
Status
[2024-07-25] [Fran] Per Michelle, this will be a separate decision, and then possibly separate effort, from the Events rebuild.

## Description
INITIAL TO DOs:
- [ ] Gather data on this request from Product Owner
- [ ] Update acceptance criteria
- [ ] Create discovery ticket, with info re: stakeholders at NRD

## Acceptance Criteria
- [ ] 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by FranECross** [comment]
Added to Product Syn meeting agenda for Dec 13, 2023
