### ISSUE TITLE
CMS accessibility audit

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9443]
## User Story

As a CMS editor, I need a CMS experience that is accessible and 508 compliant. 

## Background

Claro launched in Q1 2022 and should provide a relatively accessible experience, however, some of the custom upgrades may have introduced accessibility concerns. The CMS experience has improved, but there still may be considerations to provide accessibility compliance. As a Sitewide CMS team, we should identify issues or pain points for CMS editors. Also, we need to ensure that the CMS editorial process is accessible for editors that use screen readers. 

## Description of Work

The accessibility lead should complete an audit of the CMS to determine pain points for editors and areas of opportunity. This audit might help determine a path forward for improving the CMS and completing usability testing through #8526 

## Acceptance Criteria
- [x] Evaluation of CMS current state for each product
- [x] Findings and areas of opportunity are documented

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
This work was completed as a part of the efforts in #9492
