### ISSUE TITLE
Standardize similar fields in CMS content model

### ISSUE THREAD

**Issue by msbtterswrth** [department-of-veterans-affairs/va.gov-cms#9445]
## Background
Given the nature of our products, we have missed several opportunities to resuse fields within multiple products and work streams.

The current list of candidates is as follows (and can also be [found in airtable](https://airtable.com/shrcfrtyqIZeTiRfV)):

**Address fields**
- `field_address` and `field_vamc_med_records_mailing` (all use address field type)

**Date fields**
- `field_publication_date`, `field_release_date` (both dates that signify when something was available) *could go a step deeper and make _all_ date use a `field_date` field*

**Entity Fetch fields**
- `field_cc_faqs`, `field_cc_vet_center_faqs` (both faqs fields)

**Entity Reference fields**
- `field_author`, `field_leadership`, `field_press_release_contact` (all are entity ref to Staff profiles)
- `field_clinical_health_services`, `field_local_health_care_service_`, `field_regional_health_service` (all fields relating to vamc system services)
- `field_media`, `field_image`, `field_hero_image`, `field_press_release_downloads` (potentially split OUT video only or mixed from only images)
- `field_administration`, `field_owner`, ~`field_va_form_administration`~ (all governance fields that reference section)
- `field_office`, `field_related_office` (both reference fields to related offices)

**Link fields**
- `field_link`, `field_clp_stories_cta`, `field_url_of_an_online_event`, `field_va_form_tool_url` (these are content type fields for links; should also migrate `field_SOCIALMEDIA` to use social media link type instead; note to look at operating status link)
-  `field_link`, `field_button_link`, `field_default_link` (these are paragraph fields for links)

**Markup Fields**
- `field_appointments_help_text`, `field_facility_service_loc_help`, `field_fieldset_markup`, `field_markup`, `field_table_of_contents` (could combine all markup fields into `field_markup`)

**Telephone number fields**
- `field_phone_number `, `field_phone_number` (note the space in the machine name)

**Text (formatted, long) fields**
- `field_body`, `field_cc_documentor_description`, `field_full_story`, `field_press_release_fulltext`,  (these are content type fields for body text)
- `field_intro_text_limited_html`, `field_intro_text_limited_html `,  `field_press_release_blurb`, (note the space in the machine name;  used for meta descriptions/page intros)
- `field_description`, `field_rich_wysiwyg`, `field_wysiwyg` (these are paragraph fields for body text)

**Text (plain) fields**
- `field_description`, `field_hero_blurb`,   (these are content type fields;  used for meta descriptions/page intros)
- `field_header`, `field_alert_heading`, `field_section_header`, `field_title`, `field_cc_documentor_title` (these are paragraph fields; used for titles/headers of things) 

### User Story or Problem Statement
How might we combine similar/dupilicative fields into one standardized field?

### Affected users and stakeholders
* CMS editors
* CMS Developers

### Hypothesis
Concatenating similar fields into one base field will improve DX (especially wrt AP inititive) and also help us improve and standardize UX for editors across the CMS as a whole.

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [x] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by kevwalsh** [comment]
Love this!

I see the estimate at 13, but i think it may be premature. We generally we try to keep our estimates on the individual issues, and have those estimates bubble up into the epic. 

And given the code dependencies of these changes (BE, FE, remove deprecated field) and the need for multiple PRs (and multiple issues) for each content model refactor, i think it makes sense to create a mini epic per refactor. 

Finally, each subepic deserves its own 🤨  for merit, and some of those subepics may not get prioritized.

**Comment by kevwalsh** [comment]
My last comment was when there were only 5 of these, now there are a lot more! Maybe we need a spike ticket to triage these by type and priority. There are a couple that stand out as no-brainers, like the field_administration and field_owner, although even that one needs some validation.

**Comment by kevwalsh** [comment]
i think we have missed some opportunities, and after seeing Ethan fix one of these recently with #9359, i think there are a few of these we will want to move forward with, but my guess is that it's a small minority. 

There are a things that may look the same on the surface but are not really the same, and we need to be really careful in this kind of analysis. This already bit us once today in a different context.
> `field_administration`, `field_owner`, `field_va_form_administration` (all governance fields that reference section) 
This is wrong. `field_va_form_administration` is not a governance field on VA Form (it's not used by workbench access), but it does reference the Sections taxonomy (whether it should or not is a separate question).

**Comment by swirtSJW** [comment]
This is not a a light lift at all.  The steps are significant and have top be orchestrated near simultaneously.
* move data to new field while preserving revisions.
* hide the old field.
* change the FE query and template to use the new field 
* change an Views that may have used that field  (not sure why this report is not visible on prod) 
![image](https://user-images.githubusercontent.com/5752113/214166901-9eea73e0-cb8a-4df2-b75d-e35090139875.png)
* remove the old field

I know this housekeeping sounds like a good idea, but is expensive, risky and something no client is asking for.

**Comment by EWashb** [comment]
I am going to close this. I don't believe the outcome intended from this original ticket is worth the squeeze at this time and is not a priority for CMS Team or the associated product teams. We can reopen if we determine later that this extensive effort ties directly to a favorable Veteran impact.
