### ISSUE TITLE
Build content listing pages in Drupal as "dashboards".

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#946]
## User Story or Problem Statement

As a manager of a listing page (events, stories, news releases, health services, locations, leadership) i can see all my listed content *within the CMS*, published and unpublished, so that i can manage the content effectively.

### Hypothesis 

We believe that custom task pages by content type and context, which loosely mimic the front end, will help content editors manage their content more effectively. 

### Assumptions

That the information architecture used on the front end is also the the right IA for content managers, in most cases. 

### Existing research

There may be some helpful data in the dashboard research performed in Summer 2019.

## Acceptance Criteria
- [x] On an event listing node, (eg /outreach-and-events/events, /pittsburgh-health-care/events), 
  - [x] i can see all events in my listing, including published/unpublished, past and future.
  - [x] events are filtered to show only upcoming, by default, but i can filter to see all events
  - [x] events are displayed in a table with these columns:  
      - [x] Rendered content teaser display mode, much like on the front end. (title, teaser, date)
      - [x] Moderation state
      - [x] Last updated
      - [x] Owner
- [ ] On a stories listing node, 
  - [ ] i can see all stories.
  - [ ] they are sorted by most recent, descending
  - [ ] featured stories are pinned to the top
  - [ ] stories are displayed in teaser display mode, which includes _TBD_fields_
- [ ] On a news releases listing node, i can see all news releases.
  - [ ] they are sorted by most recent, descending
  - [ ] featured news releases are pinned to the top
  - [ ] news releases are displayed in teaser display mode, which includes _TBD_fields_
- [ ] On a locations listing node, i can see all facilities.
  - [ ] they are sorted by "Main location" (boolean), descending, then by alphabetical, ASC.
  - [ ] facilities are displayed in teaser display mode, which includes _TBD_fields_
- [ ] On a health services listing node, i can see all health services 
  - [ ] they are sorted and grouped by parent taxonomy term and alpha, [just like on the front end](https://www.va.gov/pittsburgh-health-care/health-services)
  - [ ] Build on the work done in Proofing epic to display health service content
  - [ ] health services are displayed in teaser display mode, which includes _TBD_fields_
- [ ] On a leadership listing page, i can see my leadership staff profiles
  - [ ] they are sorted by the entity reference field for leadership.
  - [ ] health services are displayed in teaser display mode, which includes _TBD_fields_

In each of these listings
- [ ] i can see some kind of "teaser" display mode (fields TBD), as well as some important metadata and actions, including
   - [ ] moderation state
   - [ ] "last edited by"?
   - [ ] a subset of fields and actions seen on /admin/content, _TBD_fields_
- [ ] i can filter by 
   - [ ] moderation state
   - [ ] _TBD_fields_
- [ ] I have a link to add new content of this type.

## Research/ Design

* Design review/crit events dashboard, then a small iteration 
* Quick usability review of /pittsburgh-health-care/events with events managers in PGH
* Apply lessons to the other 5 types, which could lead to help text or other needs

## Implementation steps
* Figure out the page layout architecture. Layout builder? Panelizer? Panels/Page manager? etc.

**Comment by kevwalsh** [comment]
@swirtSJW please confirm estimate with Elijah

**Comment by oksana-c** [comment]
Focus shifted to Product-specific dashboards w/ first pilot VAMC system dashboards #1447.
