### ISSUE TITLE
Automate syncing of CMS Content Model to Airtable to replace Content Spec behat test

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#9497]
## Background
We discussed in a Spike here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8665.

### User Story or Problem Statement
As a CMS Development Team Member I need to see the current state of our deployed content model in the "VA.gov CMS content model documentation" Airtable Base so that I can create additional views, add metadata and collaborate with others on content model changes.

### Affected users and stakeholders

* Product Owners & Managers
* Software Engineers
* UX Engineers
* Delivery Managers

### Hypothesis
We believe that removing the Behat Spec Tool tests and instead, syncing the deployed CMS config directly to the "VA.gov CMS content model documentation" Airtable Base will greatly improve the developer workflow, improve test suite run times, and maintain clarity into the currently deployed content model. 

We will know this is true when we:
* Measure test times before and after
* Developers stop having merge conflicts with the Behat Spec Tool tests
* The deployed Content Model state is accurately reflected in the "VA.gov CMS content model documentation" Airtable Base on an hourly basis

## Assumptions
* That we have all of the state needed from the CMS *.yml config files (PoC proves this already)
* This will improve Developer Experience
* This will decrease test suite run times

## Acceptance Criteria
- [ ] #9506
- [ ] The desired CMS config state is synced:
  - [ ] #9505
  - [ ] Bundle Types
  - [ ] Bundles
  - [ ] Field Types
  - [ ] Fields
  - [ ] Views/Views displays
  - [ ] Modules
  - [ ] Image styles, Image effects
  - [ ] Menus
  - [ ] Form widgets
  - [ ] Workflows, Workflow states, Workflow transitions
- [ ] Measure speed of tests suite runs to see if overall time is decreased
- [ ] Ask developers if their workflow is improved

## Implementation notes

* Current plan is to use a GitHub Action and take the CMS config/*.yml (convert to CSV or JSON) and send it to Airtable with their [API](https://www.airtable.com/developers/scripting/api).
  * Do this on an hourly basis
* The "User roles" table might be the easiest to get started with because it doesn't have any relationships. 
  * It is okay to change the ID on this column for any of the tables, e.g. make it the same as the machine name. Currently the ID field on all tables is the Name or Label field. 
  * We have a TEST Base here https://airtable.com/appZ4csS08RldVOIj/tbl8tQ719TAitQyrz/viwDZf3ewK3bRVB97 that we must test on, ask @msbtterswrth for a "Creator Invite to the Test Content Model Base".
  * Ask @msbtterswrth or @kevwalsh for clarifying questions that were missed here
 
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [x] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
With the recent reduction in staff, this effort will be deprioritized into the backlog.

**Comment by TheBoatyMcBoatFace** [comment]
Closing this due to infrastructure changes per [Slack Conversation](https://dsva.slack.com/archives/C02HX4AQZ33/p1671235015789679)

**Comment by ndouglas** [comment]
@EWashb

**Comment by TheBoatyMcBoatFace** [comment]
> @EWashb We need to figure out _some_ path forward here.

I didn't realize this was still a need. @EWashb, can you get me Airtable access? I've got an idea I've been working on for another syncing that may also work here. I'll touch base next week to get more context on this and hammer out details.

**Comment by EWashb** [comment]
This work will likely not be needed after #12240 is complete
