### ISSUE TITLE
Organize and test redux actions

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#9502]
## Issue Description
The Facility Locator code (src/applications/facility-locator) is in need of some refactoring. This issue focuses on actions/index.js. 

---
## Tasks
- [ ]  Break up src/applications/facility-locator/actions/index.js into functional groups living in separate files, such as 
        - searchActions.js
        - mapActions.js
        - geolocationActions.js
- [ ]  Identify complex actions that need unit tests, and add them.

## Acceptance Criteria
- [ ] The actions in actions/index.js are organized into functional groups
- [ ] Complex actions have unit tests
