### ISSUE TITLE
Check for test coverage related to Facility Locator result header

### ISSUE THREAD

**Issue by mmiddaugh** [department-of-veterans-affairs/va.gov-cms#9503]
## Issue Description
This issue follows the work in department-of-veterans-affairs/va.gov-team#11149 

## Tasks
Check for test coverage on the following functionality for the Facility Locator result header 

- [x] When the user goes to different page of results, the display number updates
- [x] If the user initiates a new search, the display number updates
- [ ] Veterans using screen readers understand the context of the search results list
- [x] Heading includes user search criteria (Search results for near "location parameters")
- [ ] Heading updates with new search criteria if new search is initiated
- [x] Only the standard error displays if no search results are found (no heading displays)
- [x] Results summary header displays when search results are returned.
- [x] Results summary header does not prematurely load (No heading is seen while a search is in progress)
- [x] Heading levels do not skip
- [ ] Ensure focus goes to results summary header consistent with user flow

## Acceptance Criteria
- [x] Create a new issue with tasks to add any missing tests

**Comment by jtmst** [comment]
resulting ticket: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9614
