### ISSUE TITLE
Clear out lat/long when address field changes, before the new lookup, to reduce possibility of mismatched geodata

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9544]
## User Story or Problem Statement

It's better to have no lat/long than the wrong lat/long.

It's currently possible for editors to change the address and produce bad lat/long data.

Reproduce
* As a Vet Center editor (not an admin)... and in the future for VBA facilities.
* Edit a Vet Center CAP with an existing address and a good lat / long
* Put in an address that is not geo-locatable 
* Save
* Get a confusing error message on that complains about not being able to geolocate the address. 

Editor can't see the pin or map, which makes the error message nonsensical

## Mitigating factors

- we don't know how often this happens. 
- may happen more 

## Possible approach

- ~on presave, clear out lat/long if address changes, so that if it fails to geocode, we will have no lat/long instead of the wrong lat/long.~  Turns out this is a config change needed in the module and that's it.
- solve this in the module
- flag content as missing lat/long (see #9616)

## Acceptance Criteria
- [ ] When a Cet Center CAP has an address change, the geofield is updated
- [ ] Validate that lookups are not performed with every node save.  Only when necessary.
- [ ] ~Upstream patch contributed to D.o https://www.drupal.org/project/geocoder/issues/3294811~
- [ ] Document in KB
- [ ] Document in READMES

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`
