### ISSUE TITLE
Prepare AskVA (AVA) widgets for addition of Login.gov as login option

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9566]
## Background

Login.gov is already integrated with VA.gov as a login provider. However, Login.gov is making a change to the data it provides on users, ETA Q3 or Q4. Per our discovery in #9140, Login.gov will provide different service-level attributes from what our React widget expects today (a `loa` attribute). 

LOA stands for Level of Access, and in this context determines what level of support the user receives from AskVA. (Akin to service tiers.)

We intend to prepare the conditional logic in our widgets to look for these new attributes when Login.gov is the authentication provider.

## To Refine:
- **How do we "build ours first"?** – i.e., build and test our implementation before login.gov is implemented by Platform?

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
I emailed Chris Clemens and AskVA team on 8/4 to inquire whether they need any further support from us, now that we verified that the Identity team is handling Login.gov params on their side.

**Comment by wesrowe** [comment]
Haven't heard of any issues from Chris Clemens. We can reopen if something comes up.
