### ISSUE TITLE
VAMC System pages: when no event is Featured, fallback should display next Upcoming event, regardless of recurrences

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9576]
## Describe the defect
On VAMC System main pages, if an Event is marked as Featured, it will display. 
If there are no featured events, code has an if/then fallback to display the next chronological event. However: 
if a recurring event has recurrences prior to today, the Featured spot shows the next recurrence of that event, even if other non-recurring events are scheduled prior to that recurrence, in the future. (Clear as mud?) This is a bug we need to file.

E.g. [Iowa](https://www.va.gov/central-iowa-health-care/) – Pickleball is not the correct fallback in the screenshot below.
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4054752/179055283-f69ef5a5-8b8b-4f7e-a740-c4a58a115f1c.png">

### Create local data
This is hard to repro because it requires: 
* A VAMC recurring event:
  * associated with a VAMC System (Where should the event be listed? > set to a VA healthcare location)
  * with first instance in the past
  * A 2nd recurrence in the near future
* A non-recurring VAMC event 
  * with a date/time in between those 2 event recurrences 
* A VAMC System Events page with no featured events. **This probably needs a SPIKE ticket to understand: how do events get featured on VAMC pages. I don't know that right now. Swirt / Kev do.**

You likely need to create that scenario locally, to see this defect in action. Minneapolis has the most recurring event data in prod so far, that you could modify to establish these conditions instead of creating from scratch.

### Steps to reproduce the behavior:
1. Create the local data
2. Go to the relevant VAMC main page, e.g. https://www.va.gov/minneapolis-health-care
3. Scroll down to Events header 
5. See the featured event is a recurring event recurrence, and note date / time
6. Go to the Events page of that VAMC system, e.g. https://www.va.gov/minneapolis-health-care/events/
7. Make sure your filter is set to All upcoming
8. Note that the Featured Event shown on the prior page is not the top event listed. 

## AC / Expected behavior
- The top event from Upcoming should appear as the Featured Event on the VAMC page, if no events are Featured. Whew.
- Facilities checkpoint - technical awareness/code review

## Screenshots
![Screen Shot 2022-06-23 at 1 36 14 PM](https://user-images.githubusercontent.com/85581471/175395233-8fa8459e-afc5-49da-80a9-84a67aa725a0.png)

![Screen Shot 2022-06-23 at 1 36 49 PM](https://user-images.githubusercontent.com/85581471/175395243-49eda591-8fe2-4951-8027-e29904dad049.png)

 ## Additional context
Slack thread reporting / analyzing this issue: https://dsva.slack.com/archives/CT4GZBM8F/p1655835746501589
Previous issue, closed due to wrong tack on fix: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9549

I suspect this is a front-end bug, but maybe has Drupal pieces? Should confirm in refinement.

## Tasks

- Updating graphql - 1
- Add logic for calculating the next event - 6
- Unit tests - 2
- QA/Functional testing / Staging data review- 1
- Prod verification with live data - 30min
- Code review (Ryan) - 2

12.5 hrs

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jtmst** [comment]
The solution here is going to involve adding another field to the back end, nextEventTime,  and then changing the graphQL query on the front end to consume that new data.

**Comment by jilladams** [comment]
I know you synced with @dsasser on this -- do we need a new ticket for the backend work?

**Comment by wesrowe** [comment]
no longer blocked, solution has been determined (FE only).

**Comment by stefaniefgray** [comment]
Reported once more by VA Minneapolis in https://va-gov.atlassian.net/browse/VAHELP-4526

Today is **August 4th** -- the next recurring event at their VAMC is the Red Cross Blood Drive, tomorrow **August 5th**, per the main Events page:

![Screen Shot 2022-08-04 at 6 12 58 PM](https://user-images.githubusercontent.com/9059428/182975881-71ffe2ed-1c14-417b-abde-ce5f7259a3d1.png)

However, their homepage shows the Farmer's Market event instead, which will be on **August 9th**:

![Screen Shot 2022-08-04 at 6 13 58 PM](https://user-images.githubusercontent.com/9059428/182975936-5c13307f-d9bf-47c3-9dfb-950ea3136a6c.png)

Neither the blood drive nor the farmer's market are marked as "Featured"

**Comment by jilladams** [comment]
good news, @stefaniefgray : this fix is in PR and likely to be live on the site early next week. We'll confirm when everything is verified in production and good to let editors know.

**Comment by ryguyk** [comment]
The change in [this PR](https://github.com/department-of-veterans-affairs/content-build/pull/1241) will fix things in *most* cases.  It's not going to be bullet proof, but it's an improvement that we should get into production asap.

Iterating further needs to address two more issues, captured in [this ticket](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10176).

**Comment by jilladams** [comment]
@stefaniefgray FYI that this code change merged today, and should appear after today's daily deploy. There is a follow on ticket, https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10176, so if you get any editor feedback on further related issues, feel free to ping me or add it to that ticket directly.

**Comment by stefaniefgray** [comment]
See comment on https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10176

**Comment by jilladams** [comment]
Note: #10176 tracks the fact that featured-event display is statically generated, so it's only accurate as of the next content release. If an event expires into the past between content releases, it will still show as Featured, until #10176 / #10307 are resolved.
https://dsva.slack.com/archives/C52CL1PKQ/p1660688195388469
