### ISSUE TITLE
Research possibly additional costs associated with geodata forward lookup

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9594]
## User Story or Problem Statement

As OCTO-DE, i need to understand the expected costs of performing forward lookups to Mapbox for lat/long based on CMS-managed content with address data. 

The CMS performs forward lookup to mapbox upon node save for certain content types.

Phase 1
* [Vet Center CAPs](https://prod.cms.va.gov/admin/content?title=&type=vet_center_cap&moderation_state=All&owner=All) (there are 314 as of July 1 2022)

Phase 2/3
* VBA facilities
* Events (there are > 100 events published per month. About half have events have addresses specified for the event. The other half are associated with facilities and will get their lat/long that way. 

Nancy Smith may be able to help with access to the Mapbox dashboard for reporting. 

## Acceptance Criteria
- [ ] We have documented the expected costs for Mapbox API geodata forward lookups for VA.gov CMS managed data.

## Implementation steps

Calculate the following: [Estimated number of geodata lookups per month, based on estimates] x [cost per lookup]

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
Total nodes:
Vet CAP: 317
Events: 2875
VBA Facilities: 453

Assumptions: 
Mapbox cost for permanent Geocoding: $5/1000
https://www.mapbox.com/pricing

Everything is geocoded twice
1. Staging
2. Production
Vet CAPs: 20% change/revisions per month
Events: 100 added/revised per month
VBA: 5% change/revisions per month

Based on the estimates and pricing, it will be ~$100 for the next 12 months for these 3 content types. (see attached Excel sheet)

[Estimate of costs from gelocation data.xlsx](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9093288/Estimate.of.costs.from.gelocation.data.xlsx)

**Comment by davidconlon** [comment]
I'm also looking at the note of "Results from the Permanent Geocoding API are only available for your own personal or business use, and cannot be used for distribution or sublicense."

What, if any, implications are there for the fact that we intend to push this information to Lighthouse API.

**Comment by kevwalsh** [comment]
@davidconlon Good catch, let's track on that on #9763 for Facilities geodata that we would be pushing

**Comment by kevwalsh** [comment]
From Dave:
>  9594 can be closed b/c we spun up another issue about the potential issue around permanent geocoding api
