### ISSUE TITLE
Add Mapbox token to AWS

### ISSUE THREAD

**Issue by omahane** [department-of-veterans-affairs/va.gov-cms#9601]
### Tasks:
- [ ] Add a Mapbox token (to be provided) to the AWS parameter store
- [ ] Retrieve the token during the build process
- [ ] Make an environment variable (`MAPBOX_TOKEN_CMS`) using the retrieved token value

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by olivereri** [comment]
Parameters in AWS Systems Manager Parameter Store created with placeholder value. Needs to be update with actual Mapbox key:

`/cms/dev/MAPBOX_TOKEN_CMS`
`/cms/staging/MAPBOX_TOKEN_CMS`
`/cms/prod/MAPBOX_TOKEN_CMS`

Recommend sharing secrets through Onceler:
https://onceler.app.cloud.gov/

After the values are in place, merge this PR:
https://github.com/department-of-veterans-affairs/devops/pull/11478

**Comment by ElijahLynn** [comment]
We need to add to Tugboat secrets too.
