### ISSUE TITLE
Fetch lat/long data from Facility API and store it for all VHA facilities (VAMC and Vet Centers)

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9612]
### User Story or Problem Statement

As a Veteran, I want directions to facilities across a variety of VA.gov experiences, including event locations. 

As an editor, i don't want to have to re-enter lat/long data for events that take place at VA facilities.

As VA, I want a single source of truth for facility lat/long, and i don't want to recreate data (say, via forward lookup) if i already have that data in a database.

## Acceptance Criteria
- [ ] All facilities have lat/long fields (even Cemeteries and VBA facilities, although we don't have a source for those yet. 
- [ ] All Facilities with lat/long data in VAST (and therefore Facility API) should have that lat/long data in Drupal
- [ ] Lat/long is not editable by non-admins
- [ ] Documentation is updated to show source of truth for these fields

## How to demo

1. Show that editors can associate events with facilities and describe the need for 
2. Show the documentation 
3. Show that we have geodata fields for all facility types that 
4. Show that these fields are not visible or editable by non-admins.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Runbook
<optional>

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
