### ISSUE TITLE
Create an audit view of all content with geodata

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9615]
## User Story or Problem Statement

As a content manager or content engineer investigating geodata issues, I want a view of all content that has addresses and/or geodata, so that i can take action to remediate issues or plan improvements.

## Acceptance Criteria

- [x] machine name `addresses` on the existing Facilities view
- [x] URL [`/admin/content/facilities/addresses`]
- [x] Menu item setting: Addresses, child tab of Facilities
- [x] limit to 100 per page, paginated
- [x] show result count in header
- [x] default columns
  - [x] Title (sortable) 
  - [x] Edit button (not operations, no heading) 
  - [x] Content type (sortable)
  - [x] Moderation State
  - [x] Section (field_administration) (sortable)
  - [x] Last updated (date time and by user) (sortable, default sort, DESC)
  - [x] Address, one column per field
  - [x] Lat 
  - [x] Lon
- [ ] filters
  - [x] text search (exposed)
  - [x] content type (exposed)
  - [x] moderation state (exposed)
  - [x] section (exposed) (workbench access section; single select, show children)
  - [x] Lat long filters, with operators if they exist (exposed)
  - [x] Address filters, with operators if they exist (exposed)
  - [x] Content type, allow more than one selection, but only show facility content types as options (like admin/content/facilities)
  - [x] Reset button exists
  - [x] Apply button says 'Filter'
- [ ] CSV export, per [Views style guide](https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/1740472321/CMS+Views+Style+Guide)

## Implementation steps

Drupal views config. It will probably help to start by cloning the admin/content/facilities display 

## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [x] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`
