### ISSUE TITLE
Drupal translation integration

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9622]
## Description
As of Q4 2022, the Sitewide CMS team has assumed responsibility for determining the CMS integration of translations. 

This epic tracks discovery and research related to iterating translation architecture to support translating more content, from the CMS perspective.

~The Public Websites team owns supporting FE translation of new content under the current [content localization model](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content-localization/README.md). Related tickets are tracked in #11344~

## Original #9622 description, July 2022

Sitewide Content is working on Content Hub: Spanish translation of disability and Healthcare Eligibility & How to Apply sections. Translations are already in effect in some areas of the site (e.g. https://www.va.gov/health-care/covid-19-vaccine/).

This effort will theoretically be support by an entire scrum team for Translations. 

~But until that team is funded / stood up, Public Websites will support the effort with any requirements meantime~

~Public Websites Goals, from Sitewide perspective:
2022Q3: understand existing translations, what we know / what we don’t; how to maintain / how to extend
2022Q4: Support implementing Spanish translations~
  
### User Story or Problem Statement

As an editor, I need to create Spanish translations of existing content so I can display Spanish translations to veterans.

### Affected users and stakeholders

* CMS editors of disability and Healthcare Eligibility & How to Apply sections
* Sitewide Content contributors / SMEs

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [X] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [ ] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [X] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [X] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
State of research for next gen translation: 
* Document of findings / proposed paths forward: https://docs.google.com/document/d/1OV4760Fg-R8TCSWj_ZnJk0IJbAKEuNTDuZl4cRdyI-o/edit#heading=h.hiwuigkux275
* Recording of workshop with PW / Danielle (Tbd link)

**Comment by EWashb** [comment]
Will refine this epic with Dave C. at our next Sitewide sync. We are looking at tackling this in Q1 2023

**Comment by EWashb** [comment]
Traditional multilingual is the preferred path. We would only want this tab open to certain editors- turn it on by permission.

**Comment by EWashb** [comment]
Let's understand the effects to content build. Choose a content type as a pilot. Then work with PW to show what the FE presentation is.

**Comment by EWashb** [comment]
Path forward:
1. determine effects to content build
2. Determine if this can be allowed for by permission
3. Much later- POC for FE presentation layer (choose one language) pulling the translated content from the BE to the FE

**Comment by wesrowe** [comment]
Closing this epic since it was intended to prepare handoff of translation work from PW to CMS team. All issues are closed.
