### ISSUE TITLE
Income limits web app: Discovery, Design, prototype, user research, MVP

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9626]
## Description
We will improve the experience for Veterans seeking to understand if they qualify for medical benefits from the VA.

Veterans are eligible for benefits based on inputs like:
- income
- location
- number of dependents
- anything else?

Currently, Veterans must reference Income Limits AKA "Means-test Thresholds" truth tables to understand if they qualify:
- https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/HealthBenefits
- https://www.va.gov/healthbenefits/apps/explorer/AnnualIncomeLimits/LegacyGMTThresholds?FiscalYear=2021&PriorityGroupLevel=8

This epic will track work to discover, design, and build and improved solution.

### Requirements / limitations

**Technical details**
- CMS integration is not a requirement. This may be a standalone product.
- Must be able to receive data updates annually, preferably without manual transformation from format of source.

**UX details**
- Veteran location – Based on experience with Facility Locator, Veterans are comfortable with either zip-code or city,state input
- from [Midpoint Review:](https://github.com/department-of-veterans-affairs/va.gov-team/issues/54987) 
  - use hint pattern
  - inputs don't need to be marked required, but need to behave as if required
- Insights from pilot testing
  - On review screen, using "edit" link to edit zip or dependents: takes user to input screen, but then they should be returned immediately to the "review" screen and not have to "continue" past any intervening questions.

### Technical concerns
- Performance for FE is a top concern

## Associated issues

- #11166
- #11167
- #11168

## Acceptance Criteria
- [ ] Understand the veteran experience, and what a veteran needs in terms of experience
- [ ] Design a solution
- [ ] Design intent review
- [ ] Implement MVP prototype
- [ ] Perform User research re: use of prototype to ensure it meets requirements for Vet experience

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Closing. We launched! The remaining Analytics ticket in the Collab cycle epic and CAIA work around entry points don't need this epic.

**Comment by jilladams** [comment]
Noting for future generations, as needed, since the Zenhub epic migration made the ticket list / ordering / Sprint values wonky: this project timeline:
July - August 2022 | Discovery / Research review; Initial design
September - November 2022 | VA project pause
December 2022 - Jan 2023 | Research prep & Prototype DevelopmentBE Technical strategy/architecture
Feb 2023 | VA Stakeholder validation
March 2023 | Prototype iteration, Pilot study, & Usability research prep
April - May 2023 | Usability research & Synthesis; Backend API build; FE core screens build
June - July 2023 | Design iteration; FE build remaining screens; Analytics design
August 2023 | Build completion; Testing; Launch
