### ISSUE TITLE
Benefit detail pages: content model hardening

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9628]
## Background
Benefit Detail Pages are currently so modular as to be unruly. We want to standardize the content model, in partnership with the Sitewide Content team. 
https://prod.cms.va.gov/admin/content?title=&type=page&moderation_state=All&owner=All

**2022Q3 goal:**
- Content audit - Danielle Thierry will ticket for us
- CMS planning / content modeling - we will partner with the Sitewide CMS team as a stakeholder, who will review our content model in a collab cycle review. That process is in development, TBD.
- CMS design
- Front-end low touch design, leaning on the CMS design system

**2022Q4 goal:** 
- CMS build
- Front-end build

### User Story or Problem Statement

As an editor, I need clear structure in the CMS so I can deliver the best content for Veterans.
As a Veteran, I need clear content to help me navigate across different benefit types and find relevant information.

### Affected users and stakeholders

* CMS editors of Benefit Detail Pages
* Veteran consumers of benefit detail content

### Hypothesis
We believe that codifying structure around benefit detail content will improve the Editor experience of creating this content. We'll know that to be true when we have gathered data around the content and structure.

## Acceptance Criteria
- [ ] Content audit has been performed to inform our CMS changes
- [ ] Content model is created
- [ ] CMS design is created using the CMS design system
- [ ] CMS Content model & Design are reviewed with Sitewide CMS in collab cycle review (process TBD), including:
  - [ ] Change management considerations
  - [ ] Knowledge base (KB) articles are considered / ticketed for any Sitewide CMS work required
- [ ] Sitewide CMS Collab cycle feedback is implemented / signed off
- [ ] CMS has been updated to implement content model / design, and reviewed / signed off by designer
- [ ] Change management is ticketed & factored into release plan
- [ ] QA & Release plan are documented & reviewed, including
  - [ ] Repositories that will have PRs to merge
  - [ ] Test cycles and where those will take place in terms of environment(s)
  - [ ] Change management process & timing

### Change management triage

The change represented by this user story will:
- [ ] Be a site-wide change to appearance or key functionality (such as log-in process)
- [ ] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [ ] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [X] Require action by some or all users by a specific deadline
- [ ] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

If you selected an item above, open a new issue using the [change management template](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/main/.github/ISSUE_TEMPLATE/change-management.md).

If you did not select an item above, update issues/PRs in GitHub but don’t plan for change management.

  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Epic")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Backlog refinement note: @kevwalsh  to summarize takeaways re: staffing / this project.

**Comment by jilladams** [comment]
2 sprints: 4 BE tickets
3/w mini-sprint checkins with Wes, Christia, Jordan

**Phase 1: (Sprint 81)**

- CMS field & config working model in draft PR environment for team viewing
- Team checked that the config makes sense architecturally

requires 2 sign offs: Wes, Jordan on this ticket based on demo env (not the draft PR)
- Draft PR gets shared with Daniel / Tony?Nate? for preview?

**Phase 2: (Sprint 81?)**
Design / polish CMS UI layer
- Design elements listed/linked and incorporated
  - editor experience / permissions
  - look and feel
  - help text
  - etc
- CMS and Design roadblocks, changes, or questions uncovered during stage 1 are considered:
  - discussed in mini-sprints and documented in the ticket
  - Scope mgmt: cut new tickets here per item, if they warrant more than a 30 minute conversation during the mini-sprint check-in or need to involved more parties (e.g. we can’t force Drupal to do the thing that’s nice)
- Field config and UI is ready for collab cycle review

- Bring LauraF in to mini-sprints if not during Sprint 82 PTO
- Draft PR gets shared with Daniel / Swirt for preview.

requires 2 sign-offs: Wes, Jordan, DaveP, LauraF for ticket based on demo env, not PR

** Make clear in sprint planning that these tickets will close without merged code

**Phase 3: (Sprint 82?)**

- CMS Flow / Collab cycle review
- 508 concerns
  - Bring LauraF in to mini-sprints if not during Sprint 82 PTO
- Updates/changes to fields and configs, UI, 508, all the things
- Architecture polishing based on collab review
- Updated PR for team review

Would need 3 sign offs: Wes, Jordan, LauraF, DaveP

**Phase 4: (Sprint 82)**

- Final CMS config
- PR review and testing
- concerns addressed
- Interface tested and collab sign-off
- Final PR gets sign off and merges
- needs sign off from: Wes, Dave P. , Daniel, Jordan, Laura, Tony?Nate?

Permissions: Content Admins + Admins - should match whoever can do Benefit Detail Pages and DavePs notes in spreadsheet.
