### ISSUE TITLE
Next Build (Q3 2022)

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9630]
## Background

This effort will focus on providing a React-based static site generator (SSG) solution to serve as the foundation for a new front end for VA.gov CMS content.

We will build a front end for CMS content that is based on a React-based framework, so that front-end engineers are working with a modern toolset that is compatible with the larger VA.gov front-end ecosystem. We also want to prioritize a front end framework that is flexible and that will allow us to make iterative improvements to VA.gov CMS content and its delivery. 

### User Story or Problem Statement

A new, Next.js-based content build system will provide a modern frontend development framework to support the Accelerated Publishing Initiative.

### Affected users and stakeholders

* CMS editors
* CMS Engineers

### Hypothesis

We believe that the new content build system will ultimately enable faster publishing speeds. We'll know that to be true when content is released without significant delay and on a faster cadence than currently.

## Acceptance Criteria

- [ ] HTML is rendered and sent to S3 in a more efficient manner using Next.js
- [ ] Component library exists for VFS teams to utilize in Production
- [ ] Content can be previewed in Preview server
