### ISSUE TITLE
Next.js: Banner placement

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9636]
## Description
Banners, promo banners, and facility banners need to display on pages according to a variety of rules. The endpoint created in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9635 should return the correct set of banners for a given path.

Use this endpoint and the components created in https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8654 and https://github.com/department-of-veterans-affairs/va.gov-cms/issues/8655 to retrieve and display the appropriate banners for a given page. 

## Acceptance Criteria
- [x] Given a path, the Next.js application displays the appropriate banners for that path.
- [x] If multiple banners are returned, multiple banners should display.
- [x] Confirm that adding a banner to be displayed at a given path results in its display, and removing the banner from being displayed at that path results in its removal.
- [ ] Tests are written to confirm appropriate banner placement

## Task List
- [ ] Determine where this logic should live. i.e.Layout, header, etc.
- [ ] Create component to make API request and display banners
- [ ] Unit tests

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [X] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
