### ISSUE TITLE
Event location state toggles do not clear out data from fields hidden by state.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9649]
## Describe the defect
When creating an event there are location related options that toggle states of other fields 
![image](https://user-images.githubusercontent.com/5752113/176598353-56de7073-ad5e-413d-86ea-65e89c6a5d5d.png)

The problem happens if an editor enters values for one state, then changes their mind on the toggle.  Example: sets an online url, then changes toggle to address.  Now the node shows both the url and the address.  This leads to a confusing editor experience AND a confusing VA.gov FE experience.

## To Reproduce
1. Go to '/node/add/event'
2. Fill in all required fields
3. For location, choose online event.  
4. enter a url for the online event. (save the node or not)
5. Change your mind and choose location for a facility or another address.
6. Enter some values.
7. Save the node, notice that data exists for more than one of the choices.

## Tasks
* Add/change Custom JS that applies the form state behavior (not using form states API)

## AC / Expected behavior
When a toggle is changed, all the values controlled by that toggle be cleared out.

 ## Additional context
Add any other context about the problem here. Reach out to the Product Managers to determine if it should be escalated as critical (prevents users from accomplishing their work with no known workaround and needs to be addressed within 2 business days).

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
This is very similar in nature to this issue that was just completed https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9410
