### ISSUE TITLE
Initiative - Discovery & MVP definition for VBA Regional Office product

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9659]
## Background

The Sitewide Facilities team is undertaking the modernization of the VBA Regional Offices websites. The overall goal is to create a modernized, consistent, 508-compliant, and mobile-friendly experience for Veterans seeking information regarding visiting a facility to receive benefits. This initiative should leverage and build upon already established architecture and design patterns developed from the VAMC and Vet Center site modernization products, and should benefit from previous lessons learned.

### User Story or Problem Statement

This epic comprises the efforts necessary to conduct research to understand the veterans, the editors, the content, and the business. 

The result of this epic will be a well-defined MVP including:

- The content model for a VBA RO facility page
- Identification of any sub-pages for child offices of an RO
- A proposed menu structure
- The taxonomy of services
- Proposed editor dashboard with top editor tasks
- Plan for the deprecation of the current VBA database, and for the adoption of the Drupal CMS as the source of truth for VBA Facility data
- What is _not_ in scope 

### Affected users and stakeholders

* CMS_editors_of_X_product
* Developers of Y teams

<link to any existing research or data supporting this>

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that _this_solution_ will achieve _this_outcome_. We'll know that to be true when _this measurable outcome occurs._

## Assumptions
* Tk
* Tk

(How will these assumptions be validated?)

## Acceptance Criteria
At the completion of this epic we will have 
- [ ] Conducted audits of existing VBA sites and 
- [ ] Conduct and audit of current VBA facility data and 

### Change management triage

The change represented by this user story will:
- [x] Be a site-wide change to appearance or key functionality (such as log-in process)
- [x] Be a specific change that requires more than 30 minutes of work by a user to meet a publishing requirement
- [x] Remove a piece of functionality (such as restricting editing functions, or “hardening”)
- [x] Require action by some or all users by a specific deadline
- [x] Change the front end and be highly visible to the public
- [ ] Noticeable performance improvements (publishing speed, predictability)

**Comment by ContentBrewmaster** [comment]
Added epic components and completed CM triage.

**Comment by cmaeng** [comment]
typically we try not to add a sprint designation to epics and super epics until they're closed as they will span multiple sprints.

cc: @dsinla @RWEagans

**Comment by davidmpickett** [comment]
Continuing a thread from slack, I propose renaming this to SE: VBA Regional Offices 1.0 or similar

**Comment by davidmpickett** [comment]
All issues completed
