### ISSUE TITLE
[SPIKE] Static assets storage for CMS

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9667]
## Background

In order to make content publicly available without a deployment process, static assets must also be made publicly available at or before the time content referencing them is published. CMS will conduct a spike to assess desired goals for storing static assets.

## Acceptance Criteria

- [x] Determine if static assets should be directly published to S3 or another publicly available content store, in a new location by Drupal
  - [x] Direct publishing of static assets does not cause unwanted changes to existing, published content
- [x] Create followup tickets for implementing selected approach
  * Several tickets created, see [this comment](https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9667#issuecomment-1185956382)

## Tasks
- [x] Review previous discussions / documentation of this issue: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5480
- [x] Identify all environments and use cases which would be impacted by changing how static assets are handled
  - [x] content release/build
  - [x] staging & dev & prod CMS environments
  - [x] local development environments
  - [x] review instances
- [X] Identify potential solutions/modules
  - [X] Drupal modules that may offer solutions
    * [flysystem](https://www.drupal.org/project/flysystem)/[flysystem_s3](https://www.drupal.org/project/flysystem_s3)
    * [s3fs](https://www.drupal.org/project/s3fs)
  - [X] Custom code solution, if necessary
    * There will need to be some custom configuration to modify the filename so that it contains both ID and revision. 
    * There will also need to be a manageable but non-trivial amount of modification to content-build.
- [x] Compare plus/minuses on solutions & choose best
  * Will go with [flysystem](https://www.drupal.org/project/flysystem)/[flysystem_s3](https://www.drupal.org/project/flysystem_s3), and minor amount of custom code to handle how we plan to do filenames. [s3fs](https://www.drupal.org/project/s3fs) requires bidirectional communication with S3, retrieving metadata and storing it on the CMS's database, which is an unnecessary point of failure.
- [x] Document findings for everything above, as we go
- [x] Write tickets for the epic, taking into account any existing tickets that can be reused, and set up dependencies so they can be ordered 

## Current Situation

The `content-build` build process retrieves static assets from Drupal and publishes them to S3 in one of the build steps. This step takes approximately ~1.5 minutes during the production content build. There are also content build steps that rewrite static asset paths.

Retrieving assets, varying from 50-90s in these samples:
https://github.com/department-of-veterans-affairs/content-build/runs/5118079201?check_suite_focus=true#step:12:17265
https://github.com/department-of-veterans-affairs/content-build/runs/5130372480?check_suite_focus=true#step:12:17306
https://github.com/department-of-veterans-affairs/content-build/runs/5126183253?check_suite_focus=true#step:12:17273

These assets are also pulled as part of the content build in general, which hampers local development. We will pull some examples, but anecdotally, it adds over an hour to content build and makes FE developers hesitant to interact with the CMS.

### User Story or Problem Statement

As a consumer of the Drupal content API, I would like to be able to retrieve static asset paths, so that I may provide access to these assets to Veterans and the public.

As a VFS engineer, I wish to have access to static assets (published and unpublished) on a public endpoint, in order to be able to quickly build the site in a local development environment.

### Affected users and stakeholders

- VFS engineers working on VA.gov templates
- Content API consumers (FE tools)
- CMS engineers

## Hypothesis

We believe that directly publishing static assets to S3 will provide the following benefits:

- Allow providing a public content API
- Improve the local development experience by eliminating the need to cache static assets from behind the SOCKS proxy (We'll know this is true if local development build time is decreased)
- Increased reliability (No worries about TIC blocking requests for assets)
- Increased security (No need to directly expose Drupal to the public via HTTP)

Potentially:
- Reduce the execution time for the current build process by removing the static asset downloading and publishing step and removing static asset path rewriting steps
- Reduce complexity in the `content-build` codebase

## Runbook

1. Assets are published publicly
1. S3 paths are returned by all Content APIs

**Comment by timcosgrove** [comment]
Issues containing discovery information: 
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5640
* https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5481

**Comment by timcosgrove** [comment]
See also questions/discussion on this ticket: https://app.zenhub.com/workspaces/vagov-cms-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/5611

**Comment by timcosgrove** [comment]
Prod, Staging, and Dev CMS will all have dedicated S3 buckets for storing images. This is have Staging and Dev be as similar an environment to Prod as possible, for testing purposes. All these S3 buckets will be public-readable. Prod files will be synced down to Staging and Dev on a nightly basis, as the database is currently. 

Tugboat CMS will continue to use local storage, and will make use of Stage File Proxy to pull down the majority of images. This will allow the images to only be sourced as needed, and will eliminate any need to transfer files for use by a Tugboat instance. 

In all cases, file urls used in markup will be output with complete URLs to the location of their files. This means that for files, content build from Prod will point to the Prod S3 asset bucket, and Staging and Dev to their respective buckets. Tugboat content build will continue to point to the Tugboat instance that are used for content build.

Review instances and other test instances used in content-build CI and the like will point to the current Tugboat instance that is used as the data source for those content builds (https://content-build-medc0xjkxm4jmpzxl3tfbcs7qcddsivh.ci.cms.va.gov/). This means that the HTML for those instances will point to files on that Tugboat instance as well, and will be populated through Stage File Proxy. This may result in longer runs for individual tests that render full HTML, if they need to retrieve assets through Stage File Proxy, but this slight slowdown will be more than offset by the speed increase in content-build itself.

Local development currently points at production instances of the database and files, when needed. We still need to determine whether we will continue to do this, or point to the content-build Tugboat instance. In either case, local development will see an enormous speed increase due to the removal of file download.

**Comment by timcosgrove** [comment]
Tickets created/updated:
* S3 buckets: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/5611
* Flysystem enabled: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9801
* Filenames include revision information: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9803
* Files are uploaded to S3 upon save: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9804
* Convert existing non-media file fields to media fields: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9805
* Convert media fields to use Flysystem S3 file wrapper: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9810
* Updates to content-build to account for S3 file storage: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9814
* Remove 'double saving' of media files: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9815
