### ISSUE TITLE
CMS Collab Cycle Pilot

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9672]
## Background

As we iterate on the idea of a collaboration cycle for the CMS, we will explore a pilot program for Q3 2022. This pilot program will only focus on one touchpoint of the CMS which will be any editorial interface changes which will include:

1. UX writing changes
2. Design system component changes
3. Anything that requires change management
4. Changes to the content model 

## Definition of Done

- [x] A place for collab cycle documentation
- [x] Governance determined
- [x] metric/scale for defining success or survey process identified
- [x] POC identified and worked through
- [ ] Lessons learned noted and shared with PO
- [ ] Plans for iteration determined

**Comment by EWashb** [comment]
@productmike I was thinking we should probably close out this pilot epic and attach the associated tickets to your new epic #14013. I have been referring to your current iteration of this work as V.2 and my early work as V.1 or pilot. What say you?

**Comment by productmike** [comment]
I'm onboard. Closing and shifting now @EWashb!
