### ISSUE TITLE
[cms-ci] Sync files from upstream

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#968]
Sync files from upstream and have all new environments consume that tar file. Create similar command as `cms-db-download` e.g. `cms-files-download`. 

This should be synced at same interval as DB, `10 * * * *`. 

Current logs have a lot of "image download failed" in logs.

cc @swirtSJW

**Comment by ElijahLynn** [comment]
@kevwalsh would like this by 2020.02.18 (Tues).

**Comment by ElijahLynn** [comment]
@jonpugh and I just discussed having this as part of the DevShop install task AND also be able to put in remote URLs so it will just curl the latest dump and not use a cache from a cronjob. This will give us the latest dump on every install.

**Comment by kevwalsh** [comment]
@ElijahLynn can this be done manually for certain Devshop environments? In the absence of this being automated, can we provide this on demand now and then?

**Comment by jonpugh** [comment]
@kevwalsh that is definitely possible, but the effort might about equal to a DevShop PR to add "Path to Files". It already has "path to sql" so adding a form element and an extra rsync command on the backend is really a 1 hr task if @ElijahLynn and I do it together with focus.

**Comment by ElijahLynn** [comment]
Upstream issue is now here > https://github.com/opendevshop/devshop/issues/536, I'll be working on this and plan to have it completed by Friday/Monday.

**Comment by ElijahLynn** [comment]
This is now live on on devshop.cms.va.gov for both new environment forms. And is working for all _new_ site creations. Sites will need to be destroyed and recreated to get this new setting. (we could modify if we really have to but I don't have that mapped out, and won't unless we need to, but it is possible if needed)
![image](https://user-images.githubusercontent.com/1504756/76824589-cf7c9f00-67d4-11ea-9789-446aa151caeb.png)

- [x] Pull in PROD files snapshot every 10 minutes (upstream Jenkins snapshot is created every 60 minutes right now, but can be made manually) for new site (re)builds to grab latest files from
- [x] Set Files snapshot as default on new environment forms  https://github.com/department-of-veterans-affairs/devops/commit/c700bb7f2cb270f66ef88d9a32d059fd125a8e48
- [ ] Make upstream PR for devmaster module modifications. Will wrap that up tomorrow.

**Comment by ElijahLynn** [comment]
This actually wasn't working, and I had to fix some file permissions issues. Fixed now in this upstream PR https://github.com/opendevshop/devshop/pull/542.
