### ISSUE TITLE
Support the retirement of ForeSee survey and the full deployment of the Medalia survey 

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#9697]

**Comment by dsinla** [comment]
## Description


## Acceptance Criteria
- [ ] Customer Satisfaction survey is served from Medalia platform 
- [ ] Site visitors experience no gap (or minimal gap) in being offered the Customer Satisfaction Survey 
- [ ] Customer Satisfaction Survey fires for X% of site visitors (matching current criteria)(
- [ ] Customer Satisfaction Survey is associated with appropriate product/facility 
- [ ] Customer Satisfaction Survey data is successfully written to the back-end db
- [ ] Customer Satisfaction Survey data is accessible via DOMO 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

? Contact Center

**Comment by jwoodman5** [comment]
@dsinla Thanks for reaching out. We do have Medallia surveys in place for a lot of Facilities pages, so to help narrow the scope of this request, do you know what directories/sub-directories you're looking to update now?

**Comment by dsinla** [comment]
Confirmed with @jwoodman5 that this will be managed globally, no action required by Facilities team dev

https://dsva.slack.com/archives/CNCEXNXK4/p1659455878506509
