### ISSUE TITLE
Kick off onboarding process for non-Platform/VFS CMS engineers/users to Okta/Datadog

### ISSUE THREAD

**Issue by ElijahLynn** [department-of-veterans-affairs/va.gov-cms#9709]
Follow up from https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9540

We need to get all of the CMS engineering team added to the Okta and new Datadog GOV instance so that they can view dashboards and logs. 

### Tasks:
- [x] Gather list of users w/email addresses (ideally @va.gov)  
  - civicactions.com, kindsys.us, agile6.com, cityfriends.tech
- [x] Create a ticket with DOTS to add all CMS administrative users to Datadog for read-only access 
  - https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+FedRAMP+Datadog+instance
- [x] Track DOTS Jira ticket [here](https://vajira.max.gov/servicedesk/customer/portal/1/DOTSD-17718)
- [x] Update onboarding documentation to include a new account (after PIV is granted) with Okta
  - https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+DataDog+GovCloud+instance#Support
- [x] Notify users in #sitewide-program Slack

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
BLOCKED: I don't think I read that well when we pulled this in. 

https://vfs.atlassian.net/wiki/spaces/OT/pages/2233598117/Get+access+to+FedRAMP+Datadog+instance

Says:

> NOTE: Datadog is not currently supported for VFS teams. 
> However, if a VFS team previously had access to the Datadog commercial instance, we will provide read access to the new instance. Full support for VFS teams will be addressed as part of this initiative:
> https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081

See https://dsva.slack.com/archives/CJYRZK2HH/p1658275562453169 for a discussion I started with @jhouse-solvd to get clarification on if we should pause or not.

**Comment by ElijahLynn** [comment]
I do have the list of emails that need new, read-only accounts (withholding emails here). 

1. Allison Lu
2. Aslan French
3. Christia Troyer
4. Christian Burk
5. Cindy Terdiman
6. Dave Pickett
7. David Shannon
8. Dawn Pruitt
9. Denise Eisner
10. Erika Washburn
11. Florence McCafferty
12. Jack Watson
13. Jay Darnell
14. Jill Adams
15. John Woolschlager
16. Josh Mills
17. Kevin Walsh
18. Laura Flannery
19. Max Antonucci
20. Roger Eagans
21. Ryan Koch
22. Stefanie Gray
23. Suzanne Gray
24. Tanner Heffner
25. Troy Griffin
26. Valerie Runde
27. Wesley Rowe

**Comment by jhouse-solvd** [comment]
Just a thought: I don't want the Platform Infrastructure team to be a blocker to others getting access to Datadog. The tool is managed and supported by DOTS. So it seems like requesting these accounts would be fine. 

However, I don't think that the Platform Infrastructure team is ready to provide additional support or configuration assistance at this time. That may factor into your decision. We'll be evaluating how to provide i[nfrastructure monitoring guidance for VFS teams in a future initiative](https://github.com/department-of-veterans-affairs/va.gov-team/issues/33081). 

I'd love to get the opinion of @mchelen-gov. He's OOO but is set to return next week. I will be OOO 8/8 - 8/12. @ph-One can help answer other questions that you have while I'm away. ☺️

**Comment by olivereri** [comment]
DOTS ticket for OKta and Datadog access has been submitted for team members that have VA.gov email addresses. The ticket can be found here after logging in to MAX.gov: https://vajira.max.gov/servicedesk/customer/portal/1/DOTSD-17718

These users are still waiting on their VA.gov email addresses:
Aslan French
Christia Troyer
Dawn Pruitt
Florence McCafferty

Onboarding progress is being tacked on the 2nd tab `migrate` of this spreadsheet: https://docs.google.com/spreadsheets/d/1wd04sna-gTN7p82Trt7FuFkZo3vQiN9KNXs4fKyALYk/edit?usp=sharing
