### ISSUE TITLE
Change "Mental health clinic" to "Mental health care" 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9712]
## User Story or Problem Statement

Many facilities have a "Mental health clinic" phone number. In many cases, this phone number is connected to a health care system-wide service, and the word "clinic" is misleading. Per VHA digital media, this label change would also comply with the  [Clay Hunt act](https://www.congress.gov/bill/114th-congress/house-bill/203).

## Acceptance Criteria
- [x] "Mental health clinc:" phone label has been replaced with "Mental health care:"
  - [x] On VAMC system (like on https://www.va.gov/long-beach-health-care/)
  - [x] On Locations listing pages (like https://www.va.gov/long-beach-health-care/locations/)
  - [x] On Locations pages themselves (like https://www.va.gov/long-beach-health-care/locations/anaheim-va-clinic/)

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`
