### ISSUE TITLE
Add support for open rate tracking to email notifications.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-cms#9713]
## User Story or Problem Statement

As an email notifier I would like to track open rates on our email notifications so that I can evaluate whether the notification emails are effective.

The problem: the WYSIWYG on message templates does not allow img tags because rich_text filter does not allow them.  It strips them out.

There are two possible solutions to this:

1. Add a filter that is only available on message templates that allows img tags.
2. Add a plain text field to any message templates that need open rate tracking and make that where the image tracking code is added, then render it on the email view mode for that template.

2 is probably the cleaner way to handle it.

## Acceptance Criteria
- [ ] Open rate tracking pixel (img tag) can be added to an email message template. 

## Implementation steps
<optional>

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by swirtSJW** [comment]
If option 1 is the way to go, then there is a bit of effort to get that in place BEFORE we create an email template we want to track (this is a ways off)

If option 2 is the way to go, then NO advanced work is needed until we have an email that needs tracking
