### ISSUE TITLE
Script to replace instances of 800-273-8255 with 988 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9714]
## User Story or Problem Statement

See epic for context.

We are still discussing if a script is appropriate, or if these content updates will be done manually by editors. 

## Acceptance Criteria
- [ ] Do not merge until July 18th. 
- [ ] As many instances of 800-273-8255 (and variations thereof, including 1-800, 800.273.8255, linked or not linked, variations on links, etc) have been replaced with `<a href="tel:988" aria-label="9 8 8.">988</a>` as is feasible / reasonable ROI
  - [ ] We have a plan for dealing with the rest, if any.
- [x] Phone number links `<a href="tel:"` work as expected
  - [x] Manual: wrap phone numbers as links where they are not (there are 15, but some 7 are stories and 1 is a news release)
  - [x] `aria-label="9 8 8." is added where it doesn't exist` (about 1/3 of linked phone numbers do not have aria labels)
- [x] Revision log message: "800-273-8255 updated to 988."

This script may skip the following (pending Dave's convo with JHL on Tuesday July 12th)
- [ ] News release (33)
- [ ] Stories (54)
- [ ] Events (2, both are archived anyway)
- [ ] Past revisions.

Moderation state
- [ ] If it's published, publish the revision with the new number
- [ ] If it's draft (13 of them), keep in draft, and produce a report?
- [ ] If it's in review, keep in review
- [ ] If it's archived, don't touch it.

## Post Deployment
- [ ] Run Script 
- [ ] Notify @ContentBrewmaster to send email 

Not included
- `, then select 1.` pattern.

## Implementation steps
TODO: [Get latest version of the node](https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9760#discussion_r920238987)

## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by omahane** [comment]
# State of the 988 scripts
Guided by [Airtable of the content audit](https://airtable.com/shrngt7aaXoIwAenS/tblO7nwMBRn1jWpcJ/viwUPS9GYFKTkAK5j?blocks=bipS8wfEIaYFSQEBX)

## Working
_Note: QA needed, of course_

### VACMS-9714-change-crisis-to-988-VAMC-facilities.php
I'm getting 48 nodes changed
for VAMC Detail Page with WYSIWYG paragraphs
https://capture.dropbox.com/RYLWZJuLLs6WF2VK

### VACMS-9714-change-crisis-to-988.php
I'm getting 138 nodes changed
for Operating Status with a Patient Resources field
https://capture.dropbox.com/S1gKlFOeCvlJOOzP

### VACMS-9714-change-crisis-to-988-VAMC-detail-field-description.php
_Note: not in the audit_
I'm getting 140 nodes changes
for VAMC Detail Page on the Meta Description field

## Maybe close to working

### VACMS-9714-change-crisis-to-988-accordion.php
I used the Entity Query approach, which made it cleaner.
I used Michael Chelen's code for using REGEX:
https://gist.github.com/mchelen/0d02801e8a6ac0dde13ab9c0e6864caa

Which took the number to change down to 42.

I have TODOs in the code of what I know needs to be addressed.

https://capture.dropbox.com/owFPRE9ZgLmppDfm

**Comment by swirtSJW** [comment]
Post release steps task here https://github.com/department-of-veterans-affairs/va.gov-cms/issues/10141
