### ISSUE TITLE
Discovery: Find a Form threat space

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9724]
### Purpose

As an ecosystem, what technical and process changes do we need to make to ensure that as few Veterans as possible are blocked from completing online and PDF forms?

KPIs / goals
- [ ] Detection time - elapsed before broken PDF links are detected
- [ ] Response time - elapsed between detection and Vet UX fixed

### Background

Product & Technical discovery to identify threat space / fragility, to inform big big picture. Look at the product, identify failure points, identify where we the VA collective can shore it up. This may be work that our team takes on, or may be priorities we advocate for other teams to take on.

We know that Find a form is brittle. We want to understand: 
* How brittle
* In what areas
* What do we propose to do about it, in an ideal world

This is a far-reaching discovery to go as deep as required to understand our options. We have the option to convert this to its own epic and cut sub-tickets to pull into sprint, in order to manage time / scope. 

**Areas to investigate:** 
- Lighthouse API bandwidth / responsiveness - via discovery meetings with that team
- Forms server being down / not providing downloads - what factors may cause this scenario? Who are points of contact? What are mitigations? How could we influence better outcomes?
- PDF opened in browser not downloading / allowing data entry - how does this happen?
- Interventions toward a proposal: could look like:
  - migrate the forms themselves into Drupal
  - update / change how forms are uploaded/maintained

## Collateral
- Original documentation around moving Find a form into Drupal may be useful for identifying stakeholders / what is already known: https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/find-a-va-form

## Acceptance Criteria
- [ ] Collect KPI baselines for current implementation – time to detect issue, time to resolution
- [ ] Document feedback channels that learn about Vet UX breakage
- [ ] Discovery with Lighthouse API team has happened & been documented
- [ ] Existing documentation is reviewed & distilled into proposals, organized around KPI levels
- [ ] Suggestions around CMS improvements / changes are detailed with t-shirt sized estimates
- [ ] Ticket includes summary of all findings & proposals for how to shore up the system

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [X] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by wesrowe** [comment]
closing – carrying work forward with more targeted epics
