### ISSUE TITLE
Create and Use Separate Webserver TLS Certificate and SAML Request Signing Certificate

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9728]
## Description
As a DevOps engineer, I need to create a separate certificate for signing requests sent to the VA SSOi IdP, so that we can improve the CMS' federated authentication security posture.

* Certificate expires July 31, 2022.

## Acceptance Criteria
- [x] Use Venafi to create a VA signed, signing only certificate.
- [x] Coordinate with IAM SSOi Team to implement the certificate:
  - [x] Provide Public Cert to IAM SSOi Team
  - [x] Update the signing certificate private key on the CMS severs at the same time IAM Team updates.
@jkalexander7 Want to add another AC. I think we should talk about the estimate for this too:
- [x] Document change management process specifically as it applies to updating SSOI signing certificates.

## Implementation Details
https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/platform/cms/cms-sso-saml-iam-login-how-to.md
https://dsva.slack.com/archives/C02HX4AQZ33/p1657135877991339

## Task List
- [x] Onboard with Change Management Services RITM7245871 
- [x] Create a Change Request Ticket (SNOW)
- [x] Receive Fed Lead Approval on created CR.
- [x] **Added 7/20** Fill in CR fields under "Customer Impact tab:"
- [x] **Added 7/20** Attend and speak at Enterprise Change Advisory Board (CAB) @ 1230 pm ct/1330 et.
 - [x] Attain CAB approval.
- [x] Coordinate with IAM team to update CMS Signing Certificate:
  - [x] First Window July 21st 9pm EST
  - [ ] Second Window July 28th 9pm EST
- [x] On the CMS Prod Server manually update certs: 
  - [x] /certs/cms.va.gov.private.key with Parameter Store /devops/certificates/cms-va-gov.key
  - [x] /certs/cms.va.gov.public.crt with Parameter Store /devops/certificates/cms-va-gov.crt
- [x] Restart HTTPd service
- [x] Test PIV login
- [x] Merge [devops PR #11527](https://github.com/department-of-veterans-affairs/devops/pull/11527)

**Comment by ndouglas** [comment]
![Screen Shot 2022-07-12 at 1 40 45 PM](https://user-images.githubusercontent.com/1318579/178557675-93552c8d-dee5-4554-bb2e-5ea8a2a185a6.png)

**Comment by ndouglas** [comment]
I received a reply to the ticket yesterday... which linked me to the IAM Certificate Guidance.

[IAM Certificate Guidance.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9102279/IAM.Certificate.Guidance.pdf)

That linked to a TMS Learning Module so I could learn how to create a ticket in ServiceNow.  So I did the TMS learning module.  It was very helpful in showing me how to create the sort of change request I need to create:

![Screen Shot 2022-07-13 at 8 54 11 AM](https://user-images.githubusercontent.com/1318579/178738306-7d0abc30-f412-43d3-98cf-09a812c004b5.png)

The problem being that my interface didn't look like that:

![Screen Shot 2022-07-13 at 8 54 58 AM](https://user-images.githubusercontent.com/1318579/178738471-21a226ad-8d76-4cd2-93bd-896b07fd0b11.png)

So I spent some time reading other documentation trying to find out how to access ServiceNow, since I was clearly missing out on some critical information.  After following various links I found searching the Slack history for "ServiceNow", I started seeing a different interface:

![Screen Shot 2022-07-13 at 8 56 38 AM](https://user-images.githubusercontent.com/1318579/178738778-ce1b5c4c-f9d1-45ce-ba7b-c6e9af764b29.png)

I don't know why this started happening, but now I'm afraid to close the tab.

Unfortunately, there's still no option to create a "Normal Change Request".

So I created another ticket for a General Change Request, and I'll see if I hear back from anyone about it.  I don't see an option to assign it to a specific team, but I'll keep poking around and see if I find still other interfaces with different options.

**Comment by ndouglas** [comment]
Also found this:

[Revised Testing and Documentation Requirements for Change Control.pdf](https://github.com/department-of-veterans-affairs/va.gov-cms/files/9102351/Revised.Testing.and.Documentation.Requirements.for.Change.Control.pdf)

Wondering if this means that we need new test documentation to confirm that we're testing SSOi sufficiently 🤔

**Comment by ndouglas** [comment]
Original ticket: INC23301676 -- filed with ESD because I couldn't find anything matching the description in the docs

Second ticket is in MAX Jira -- I don't know if that's useful.

Third ticket is RITM7231779.

**Comment by ndouglas** [comment]
![Screen Shot 2022-07-13 at 2 31 28 PM](https://user-images.githubusercontent.com/1318579/178805677-1b776f56-2219-4add-b27d-a52b236929f7.png)

**Comment by olivereri** [comment]
REQ7440749 and RITM7245871 submitted to Service Now. The Change Management Teams says this is feasible before the 28th:


1. Onboard with Change Management Services
1. Create a Change Request
1. Get one of our Fed leads to approve it
1. IAM Team creates a CR to document changing the cert on their end that references our CR
1. We meet up on the 21st or 28th to coordinate the change.

**Comment by olivereri** [comment]
On boarding with change management is being tracked here:
https://yourit.va.gov/nav_to.do?uri=sc_task.do?sys_id=d7b91b3b1b2415d4b114a798624bcb14
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/6361b527-b6d5-43af-9c96-be010296e22c)

**Comment by mchelen-gov** [comment]
It looks like groups have been successfully created:
> Stephen Scott (VAAACScottS)
> 07/20/2022 09:51:48
> Groups created per request.

Let me know if anything further is needed from me.

**Comment by olivereri** [comment]
Task list for tonight's certificate change over.

- [ ] On the CMS Prod Server manually update certs: 
  - [ ] /certs/cms.va.gov.private.key with 
  - [ ] /certs/cms.va.gov.public.crt

**Comment by olivereri** [comment]
@mchelen-gov I think the only thing remaining on the change request is to review and close. It doesn't look like I can do that though. Can you check the ticket and see if it will let you?

https://yourit.va.gov/nav_to.do?uri=change_request.do?sys_id=fcb1423d1b3cd150ba0e8515624bcb93

**Comment by olivereri** [comment]
**TODO:** Lower environment certificate swaps. IAM Lower Environment Trouble Tracker (LETT)

1. Create a Change Request ticket
 - [ ] create change request ticket how-to
1. Create an Incident Ticket assigned to `IO.TPS.IAM.Data Quality Team`
  1. Attach new public certificate.
  1. Include Change Request ticket number.
 - [ ] create Incident ticket how-to
1. Seek approval for Change Request from list of provided CMS team Change Management approvers.
 - [ ] create list of CMS Change Management group approvers.
1. Coordinate with IAM Team to join their Weekly AcS Release Window. Every Thursday @ 9pm ET
1. Attend Change Advisory Board and brief the board on the change.
 - [ ] ~When does CAB meet? Schedule?~ Every Tuesday & Thursday at 1:30pm ET
1. Schedule
