### ISSUE TITLE
Drupal: Implement reusable Q&A Group in R&S Detail content type, with text-filter capability

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9737]
## Description

As an Editor, I want to easily add reusable Q&As to a Q&A Group on Resources & Support Detail pages, so that Veterans get better content with less effort.

## Tasks
Remaining tasks, a draft PR exists, so work to get it over the line: 

- [x] Christia brain refresh - .5hr
- [x] Update [Airtable] - (https://airtable.com/appSg80z9nVWoesxn/tbl5o1AxKu7ufswjv/viwWTQYPMWSOV91rJ?blocks=bipz2F2iCJ6xlOlNM) for source of truth CMS fields. If no permissions, talk to Lynn - 1hr
    - [x] Behat tests for any new fields - ~2hrs~  These are generated by the spectool that was just updated ^^
- [x] GraphQL query in content-build repo, to add Description field - 2hrs
- [x] Code review / shepherding - 1-2hrs

6.5 hrs - 7.5hrs

## Acceptance Criteria
- [x] Add description ~paragraph~ field to Q&A Group
   - [ ] Help text provided/approved by CMS sitewide.
- [x] Make Q&A Group available on R&S Detail content type
- [x] Add text filtering capability to the Add Question modal so Editors can more easily find the reusable Q&A they want
- [x] Show both draft and published Q&As in Add Question modal, but hide archived ones
- [x] Provide GraphQL query / collaborate with FE eng 
- [x] Review permissions to ensure the new fields / QA group configs are editable by the same permission levels / Section editors as Q&A group on FAQ
- [ ] Test/QA
- [x] Requires design review
- [ ] Updates to related knowledge base article(s)  (publishing of the draft can be done in hook_update_n [with this function](https://github.com/department-of-veterans-affairs/va.gov-cms/blob/420d259ba0c8b4e0b52374b29628ae20a30f99e5/docroot/modules/custom/va_gov_db/va_gov_db.install#L239)  it goes out with this merge. 

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Questions about the CMS display for Q&A Groups:

- [ ] Which display or both should show the new Description field? I have defaulted to the assumption that it should be added to both. There is default and Knowledge Base. 

![Screen Shot 2022-07-07 at 5 29 52 PM](https://user-images.githubusercontent.com/22764938/177893595-1bcad3c1-fdb9-4602-83f9-acf7b7163b3b.png)

For default display type, I set the label to show above like the other fields.

![Screen Shot 2022-07-07 at 5 31 52 PM](https://user-images.githubusercontent.com/22764938/177893609-56b77142-1020-4aaf-a5bc-cf8d8a36821b.png)

For Knowledge Base display type, I set the label to not show, like the others.

![Screen Shot 2022-07-07 at 5 32 42 PM](https://user-images.githubusercontent.com/22764938/177893614-d56015a0-eefa-4630-90b2-10213dcded58.png)

In both displays, the Description text will show under the Section Header field.

**Comment by wesrowe** [comment]
This is beyond my understanding. @EWashb, can you help?

**Comment by chri5tia** [comment]
@jcklpe I am not sure how to "Display this set of Q&As as a group of accordions." I kept it as is but am not quite sure how/where this shows up or if it goes through the front-end process to be displayed there.

**Comment by chri5tia** [comment]
Pull request: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746

See this for tugboat testing environment to pass along to partners and interested parties.

**Comment by chri5tia** [comment]
Please see #9579 for detailed notes leading to this implementation ticket.

**Comment by EWashb** [comment]
@wesrowe @chri5tia do you still need help on this one? Sorry for the delay. I was on vacation.

**Comment by jcklpe** [comment]
@chri5tia Not sure. Wes and I tried testing for different QnA pieces last week and were able to find the content block for accordions and the QnA page but that's it. Are you talking about the accordion content type? That is only available on a subset of pages, as shown on this venn diagram: [https://app.mural.co/t/vagov6717/m/vagov6717/1656088606354/882d5358ec3463a39230521d787f0015233e777c?sender=u252e7152800e3981889d1910](https://app.mural.co/t/vagov6717/m/vagov6717/1656088606354/882d5358ec3463a39230521d787f0015233e777c?sender=u252e7152800e3981889d1910)  
  
![](https://user-images.githubusercontent.com/9451726/178533214-ff74c321-1959-465a-a2b5-c9ebcf91ece1.png)

**Comment by EWashb** [comment]
Hey yall. We do have an [airtable](https://airtable.com/appSg80z9nVWoesxn/tbl5o1AxKu7ufswjv/viwWTQYPMWSOV91rJ?blocks=bipz2F2iCJ6xlOlNM) with a lot of this info. If you have any questions @msbtterswrth can help!

**Comment by jcklpe** [comment]
@jilladams  is there a difference really between adding a QnA group with a single QnA Single and having it so that content editors can adding Singles as a content block itself?

**Comment by jilladams** [comment]
I _think_ Christia determined both are possible but we need to validate that.

**Comment by chri5tia** [comment]
I set up a meeting on Monday to discuss how the workflow piece for GraphQL worked in the past so we can hammer out how our team wants to handle it. I have been familiarizing myself with the full content model to be sure that the query I propose makes sense. Will team up with @dsasser on this later today.

**Comment by chri5tia** [comment]
Draft:

```
  query GetNodeSupportResourcesDetailPage($onlyPublishedContent: Boolean!) {
    nodeQuery(limit: 100, filter: {
      conditions: [
        { field: "status", value: ["1"], enabled: $onlyPublishedContent },
        { field: "type", value: ["support_resources_detail_page"] }
        { field: "nid", value: ["47411"]}
      ]
    }) {
      entities {
				... on NodeSupportResourcesDetailPage {
					fieldContentBlock {
					  targetId
					  targetRevisionId
            entity {
              entityId
              ... on ParagraphQAGroup {
                fieldSectionHeader
                fieldRichWysiwyg {
                  value
                  format
                  processed
                }
                queryFieldQAs {
                	entities {
                    entityId
                    entityLabel
                    moderationState
                    ... on NodeQA {
                      fieldAnswer {
                        targetId
                        targetRevisionId
                        ... on FieldNodeQAFieldAnswer {
                          entity {
                            entityId
                            entityLabel
                            
                          }
                        }
                      }
                    }
                  } 
                }
              }
            }
					}
        }
      }
    }
  }
  
  
```

**Comment by chri5tia** [comment]
In the future, I would like to add the airtable/spec tool edit piece to the correlated PR, since the failed behat test for this can be helpful. Moving this item to PR #9745

**Comment by jilladams** [comment]
@chri5tia since PRs don't show in the board, it's easy to lose them if the ticket closes prior to merge (unless PR is imminently merging). Since this PR still needs to pass automation / code review, I'm gonna reopen the ticket just to track that there's outstanding work before it hits prod.

**Comment by fmccaf1** [comment]
### Design review notes
I have two UX-related concerns that I'll note here:

1. The description field is lacking direction for editors. I _believe_ this field is for paragraph text that lives under the section title, before the Q&As. We could add helper text like that shown here in this screenshot: ![image](https://user-images.githubusercontent.com/106624475/183108204-eb5ba4f7-8404-452e-81fb-0c925076714b.png) If we can/want to change this now, I'd recommend calling this field "Section introduction" and including helper text stating, "This is displayed directly beneath the section title, before the first Q&A." I'm not clear on what we want editors to use this field for, but I'd like to offer more helper text with that guidance if we can figure that out. 

2. The answer text shown to editors when they are browsing Q&As to add to page may be too short to be helpful. Is there a way to allow editors to see more of the answer text without going back and forth from preview to browsing Q&As? I'm thinking: giving editors option to expand answer field and see full or more lines of answer before they choose that Q&A.

**Comment by jilladams** [comment]
These are both good notes. I'm also not sure if they should block merge or if we could fast follow to update them. We should have collab cycle review with Sitewide CMS (#10043 ) soon, though need to confirm when this got rescheduled to, and this would likely come up there as well, so we can use that to confirm if they're blockers, I think. Will follow up with Erika. 

I'm also not certain who drafts editor facing copy for the UI, for things like this. I suspect it was Kauff, so in the interim will need to confirm what to do about that.

**Comment by chri5tia** [comment]
I think this can be closed

**Comment by jilladams** [comment]
PR is merged?

**Comment by jilladams** [comment]
@chri5tia it looks like the PR is still in draft mode: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746

We should wait to close the ticket til code review is done / PR merged.

**Comment by dsasser** [comment]
Current status is: blocked. Please see https://github.com/department-of-veterans-affairs/va.gov-cms/pull/9746#issuecomment-1213530186 for more details.
