### ISSUE TITLE
Improve workflow for handling non-geolocatable addresses

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9750]
### User Story or Problem Statement

See #9616 for context. 

Not all addresses are geolocatable

How might we better manage these situations, to ensure that all content that needs geodata gets it.

### Hypothesis

We believe that the process for ensuring geodata exists when Mapbox forward lookup fails should be handled by OCTO-DE teams, with an efficient and documented workflow. We'll know this to be true when we 1) geodata is complete and 2) response times are efficient. 

Also considered: #9448, and to let editors fix their own.

## Acceptance Criteria
- [ ] Documentation exists on workflow
- [x] Requires KB article update

### Change management triage

No change management, other than KB article update.

  
## Design principles

Veteran-centered
- [x] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`
