### ISSUE TITLE
Component: node--full_width_banner_alert

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-cms#9753]
## Description
A component is needed in the next-build system to render node--full_width_banner_alert. This component should be able to be used standalone or within other components based on node data

## Acceptance Criteria
- [ ] A component exists that can render a `node--full_width_banner_alert` data structure
- [ ] A page exists within the next-build repo that demonstrates the rendering of all `node--full_width_banner_alert`
- [ ] That component's output is consistent with the existing output of content-build (visually, markup structure)
- [ ] Create followup ticket to display banners on appropriate pages

## Tasks
- [x] Create NodeFullWidthBannerAlert interface
- [x] Create banner alert component
- [x] Update demo page to account for Full Width Banner Alerts
- [x] Unit tests

## Supporting detail
**Node**: `node--full_width_banner_alert`

**CMS structure**: [`/fullwidth_banner_alerts/fields`](https://prod.cms.va.gov/admin/structure/types/manage/full_width_banner_alert/fields)

**API query**:  [`jsonapi/node/promo_banner`](https://content-api-poc-trbtppyqohmbnfdh8faiwyiic9hby79m.demo.cms.va.gov/jsonapi/node/full_width_banner_alert)

**Existing template(s)**:[`banners.drupal.liquid`](https://github.com/department-of-veterans-affairs/content-build/blob/main/src/site/components/fullwidth_banner_alerts.drupal.liquid)
