### ISSUE TITLE
Sprint 63 - Facilities

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#9771]
<details><summary>Background</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task
</details>

<details><summary>OOO</summary>

Who | When | Backup 
----- | ------ | ------- 
Dave C | July 25-29. |  Danielle / Beth (TBD Wednesday) 
John | Tues July 19 and Fri July 22 |  Max
Kevin | Friday July 22. | David S for Facilities, Clarence for everything else.
Denise | July 22-27 | Val and Denise will determine
Christian | Thursday July 21 - July 29 | Jay

</details>

## #9096 Facility COVID status post-launch

- [ ] #9707

## Facility Locator

None

## VBA facilities

 - Get to know you with Tanekwa and Product Team
 - Goals for sprint: 
   - Understand VBA's criteria for MVP facility selection, and revise 
   - Set up Microsoft Teams working group
   - #9836 

## #9715 Move from 800-273-8255 to 988 

- [ ] #9714 Status check, and Go/NoGo? 
  - Then execute on CM from #9716

## VAMC

- [x] #9738 

### #7622 Lovell

- [x] #9690
- [ ] Content / design
  - [ ] TBD. 
- [ ] Engineering: 
  - [ ] Refine next steps from #7626
  - [ ] Refine epic #1939 (for DoD facilities)
    - [ ] #1940 
    - [ ] #1941 
    - [ ] #1942 
    - [x] #1943  

### #1295 Implement schema.org for Vet Center

- [x] #9764
  - [ ] #9794 (Lynn / Sitewide CMS)
  - [x] Stretch: #1294
  - [ ] Refine: #9795 

### CAP geodata and push to lighthouse

- [x] #9594
- [ ] Refine notifications and business process epic
- [ ] Clarify ToS https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/issues/520
  - [ ] Then possibly push (Issue exists)

## #9612 Fetch lat/long data from Facility API and store it for all VHA facilities (VAMC and Vet Centers)

- [x] #9637 (mostly done)
  - [x] #9627

## Lighthouse / Facility API data

Refine: David / Jay / Dave C needs to talk about Ourobos 

<details><summary>Blocked by V1</summary>

- [ ] #8017  
- [ ] #4769 
- [ ] #4410
  - [ ] #4411 

</details>

###  #9318 Hours

- [ ] #8302 
  - [ ] #9357

## Refinement

TBD
