### ISSUE TITLE
Tech Discovery: Translation test-env implementation and constraints

### ISSUE THREAD

**Issue by wesrowe** [department-of-veterans-affairs/va.gov-cms#9772]
## Description
Sitewide Content (Danielle Thierry) will ultimately be the stakeholder that guides priority / requirements for future iterations on better translation mechanisms. 

This ticket should cover: 
- what's been tried (in the Tugboat env, etc)
- what are the limitations to consider with future plans

It is not an implementation ticket that assumes we have a cohesive plan for next gen translations. 

see [google doc](https://docs.google.com/document/d/1iQnKP8WYndnzLUDu8bu3CmVrilhjXR8TBYM3Dh0Wnz8/edit?usp=sharing) from Danielle meeting for clues. 

## Acceptance Criteria
- [x] Meet with Sitewide Content + Steve W to understand next gen requirements & scope
- [x] Investigate/grok demo environment that previous team set up
- [x] Document findings from the tugboat environment 
- [ ] Document findings 
  - how demo was set up
  - key questions to consider for MVP (eg, do we translate menus)

### Tasks
- meeting - 1h
- demo env research / testing/digging - 6-12h
- documentation of findings - 1-3h
16h (3 days)

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Per sync with Dave today: since we have capacity, unblocking this. Dave emphasized that Danielle on SW Content will be the key stakeholder to speak to requirements / next gen of translations, so it would benefit us to meet with Danielle, @swirtSJW and our team to talk through it. Will work on scheduling a sync.

**Comment by jilladams** [comment]
AC removed: to manage the scope. Limiting it right now to understanding the demo env. In future: we likely still want to meet with Accel Publishing team + Steve W to discuss roadmap implications for how we tackle the plan for next-gen translations.

**Comment by dsasser** [comment]
After a review of the demo environment (notes are forthcoming), I have a basic sense for how the site is setup, but it appears to be incomplete as content types have not been configured with translation support. Therefore my current plan is to rebuild the demo environment locally such that I can toy with the configuration without affecting the original demo (the demo changes are not captured in code, and I want to preserve that state in case I need to refer to it later).

**Comment by wesrowe** [comment]
@dsasser, that sounds good to me – but if this increases the difficulty of the issue we can discuss with Jill on Monday.

**Comment by jilladams** [comment]
Makes sense as a next step.

**Comment by dsasser** [comment]
# The Demo Environment
## Result
The demo was setup following Drupal [best practices for multilingual](https://www.drupal.org/docs/user_guide/en/multilingual-chapter.html), but remains incomplete. The environment was setup by clicking together the modules in the UI, and therefore the configuration is not preserved. This is not a stable jumping off point for navigating the complexities of translations. For this reason, I have 

## Demo Info
Built 9 months ago
https://main-mcrnwpkibovcxkd8psclvwrg15uzknr3.demo.cms.va.gov/
https://tugboat.vfs.va.gov/6193c87c690c684a7a88884a

## Modules
The following modules are enabled for multilingual support: 

Configuration Translation (config_translation): Allows users to translate configuration text
Content Translation (content_translation): Allows users to translate content
Interface Translation (locale): Translates the built-in user interface.
Language (language): Allows users to configure available languages

## Module Configuration
### Configuration Translation
Using default configuration.
### Content Translation
Content Translation module enabled, but only Redirects and URL Aliases have translations enabled. Nodes are therefore not translated in this setup.
### Interface Translation
Using default configuration.
### Language
Spanish language enabled.

## Important Notes
### Paragraphs
Paragraphs need special treatment for translations: https://www.drupal.org/node/2735121
Need to unpack the UX here.
### API
How are API responses changed by adding languages?
Enabling translations in the CMS does not change the GraphQL or JSON:API response.

### FE
How would the FE know if a page is translated, and what languages the page is translated to?
Drupal doesn’t broadcast the languages available for content individually, so the FE won’t natively have the ability to intelligently and efficiently isolate only translated nodes during content release. Therefore, it is assumed that new queries will need to be written to make use of the new translations. In other words, grabbing a node in a particular language is a unique query

### What impact will be on the content build?
This depends on how many translated pages there will ultimately be. But each translation will need a unique static html page, and therefore each will deduct from the max node throughput

**Comment by dsasser** [comment]
New demo environment is up:
https://cms-mlxxvhffgulugk7jvqqytk0avcatdrfy.ci.cms.va.gov/es/butler-health-care/events/48319

**Comment by jilladams** [comment]
@dsasser what is the next step here? You told me to today and I didn't write it down.

**Comment by wesrowe** [comment]
@dsasser, my only comment is an early paragraph is truncated: "For this reason, I have"

It makes sense to get @chri5tia's review to make sure it's clear to someone who speaks Drupal, but I'll close it to keep the trains running on time.

**Comment by chri5tia** [comment]
>> The demo was setup following Drupal [best practices for multilingual](https://www.drupal.org/docs/user_guide/en/multilingual-chapter.html), but remains incomplete. The environment was setup by clicking together the modules in the UI, and therefore the configuration is not preserved. This is not a stable jumping off point for navigating the complexities of translations. For this reason, I have

"I have..." ?

Configuration was not preserved, as in, no one did a `drush cex`? or... Can you compare your observations with what you think of as best practices with this? I have less experience with translation only so much as that I know it's a headache. I'd be interested to know:
- what modules were clicked together
- why was the config not preserved
- what would have been the right way to do it?

My understanding for how this piece was put together in the past is that translation was done by hand and separate nodes are links in a hard-coded menu within the node. I'd love to sync with you on this e.g. do a walk through with me to "talk through" what you want to put in your forthcoming notes... I'm very interested in this piece specifically with respect to:

- future best practices utilizing Drupal translation methods for the future
- how the translation was conducted in the past and submitted for the node
- soft transition plan

I will review this more thoroughly by getting into the demo to see what you are seeing, without necessarily having to meet up.

**Comment by chri5tia** [comment]
>>The demo was setup following Drupal [best practices for multilingual](https://www.drupal.org/docs/user_guide/en/multilingual-chapter.html), but remains incomplete. The environment was setup by clicking together the modules in the UI, and therefore the configuration is not preserved. This is not a stable jumping off point for navigating the complexities of translations. For this reason, I have

"I have..." ?

Configuration was not preserved, as in, no one did a `drush cex`? or... Can you compare your observations with what you think of as best practices with this? I have less experience with translation only so much as that I know it's a headache. I'd be interested to know:
- what modules were clicked together
- why was the config not preserved
- what would have been the right way to do it?
- what makes it incomplete?

My understanding for how this piece was put together in the past is that translation was done by hand and separate nodes are links in a hard-coded menu within the node. I'd love to sync with you on this e.g. do a walk through with me to "talk through" what you want to put in your forthcoming notes... I'm very interested in this piece specifically with respect to:

- future best practices utilizing Drupal translation methods for the future
- how the translation was conducted in the past and submitted for the node
- soft transition plan

I would love to review this more thoroughly by getting into the demo to see what you are seeing, without necessarily having to meet up.

**Comment by chri5tia** [comment]
Sync'd with Daniel and signing off on this.
