### ISSUE TITLE
Required health service  / Care coordinator pages 

### ISSUE THREAD

**Issue by kevwalsh** [department-of-veterans-affairs/va.gov-cms#9773]
## Background

Certain health services are required at every VAMC. Each of these have detail pages, as well as system services. The detail pages have a common design pattern, most of which refer to "Care coordinators" (exception: Women Veterans Program Manager for Women's Veteran Care).

Most of the content on these required health service pages is locally editable but eligible for hardening as it is largely national program content and could be controlled by VHA Digital Media, rather than local editors. 

#### Required services
- Mental health care
- Suicide prevention
- Caregiver support
- Homeless Veteran care
- LGBTQ+ Veteran care
- Minority Veteran care
- Patient advocates
- Returning service member care
- Women Veteran care

## Tasks 
- [ ] Content analysis [#13881](https://app.zenhub.com/workspaces/sitewide-facilities-639f5253e4b702a32376339e/issues/gh/department-of-veterans-affairs/va.gov-team/13881)
- [ ]  Content structure changes
- [ ]  Front end mapped to new data structure
- [ ]  Pages render as expected
- [ ]  Editorial experience review with CMS
- [ ]  Content model review with CMS
- [ ]  Feedback session with VAMC upgrade team
- [ ]  Migration plan
- [ ]  Testing plan
- [ ] Change management 
- [ ] KB articles have been reviewed and updated

## Acceptance Criteria
TBD, but something like: 
  - [ ] All VAMCs have consistent pages for the required health service pages

**Comment by mmiddaugh** [comment]
Content audit started [here in Mural](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1687382640522/24c4ad66c8b3efeb653dfdbc8bb7fee5d5f444e3?sender=u3fcece2648da0fcf15d81890)

**Comment by mmiddaugh** [comment]
Note: Manila (which does not yet have modernized pages and will likely need special handling (like Lovell, but different) needs to be considered in this hardening effort as they can only legally treat service-connected conditions.

**Comment by davidmpickett** [comment]
I moved the tickets here into the larger content hardening epic and am closing this one to reduce noise
