### ISSUE TITLE
[SPIKE] Conduct inventory of vagov-content pages and determine path forward

### ISSUE THREAD

**Issue by jkalexander7** [department-of-veterans-affairs/va.gov-cms#9784]
## User Story or Problem Statement

The vagov-content repo should be deprecated. The CMS team will review all associated pages (~30) within repo and take inventory of what should be deleted and what should be retained.

Repo: https://github.com/department-of-veterans-affairs/vagov-content 

## Acceptance Criteria
- [x] Document remaining pages in vagov-content
- [x] For each page, determine if it needs to be migrated, and, if so, where/how (next-build/Drupal/etc).
- [x] Create follow-up tickets to migrate/perform cleanup

## Tasks

- [x] Identify all files
- [x] Identify team owner/individual who has need for page
  - [x] Assess need for the page: keep/delete

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by ElijahLynn** [comment]
I think it would be good to post in a broader channel like #vfs-engineers to call for history on that repo.

**Comment by timcosgrove** [comment]
I took a first pass at this, in the context of other work: https://docs.google.com/spreadsheets/d/1NVFKpE5rGjI3TdUJmMOfiv0tSid7eUvvNu63EzLxML8/edit#gid=0

There only appears to be one page of content substance here: https://www.va.gov/school-administrators/

I have one lead to try and track down ownership of this page.

There are a number of utility pages that live in this repo that will need to be created through other means, like the 404 page, some pages related to logout and such. Additionally, there are two pages related to analytics that will continue to need to exist.

Many of the pages here appear to relate to efforts that are no longer current. We can contact people found in the git repo and connected Github issues to find out the state of each of these.

**Comment by timcosgrove** [comment]
Tickets are created; See parent epic. https://github.com/department-of-veterans-affairs/va.gov-cms/issues/14712
