### ISSUE TITLE
Create template runbook for adding tracking to notification emails

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#9785]
## Description
A runbook for adding tracking to notification emails will help ensure we follow the same processes every time we add tracking to notification emails. It will also ensure we document things appropriately. Below is a draft of the template, which can be implemented once we've set up the ability to add tracking.

## Template runbook for adding tracking to notification emails
- In Google Analytics
   - [ ] Create UTM code for Google Analytics (used to track click throughs) [How to article](https://blog.hubspot.com/marketing/what-are-utm-tracking-codes-ht)
   - [ ] Create tracking pixel code in Google Analytics (used to track open rate). [How to article](https://www.campaignmonitor.com/resources/knowledge-base/how-does-one-track-email-open-rates-in-google-analytics/) 
-  On email message template https://prod.cms.va.gov/admin/structure/message 
   - [ ] append the UTM tracking parameter to the action link in the message body. 
   - [ ] Add an image tag with a link to the tracking pixel to the bottom of the template.
- Document the setup
  - [ ] In the [Sitewide CMS Data Tracker airtable](https://airtable.com/appNgNXTnOj10esHQ/tblCvQnL1r1dY6qEw/viwrr9f8kjMaSiLkL?blocks=hide), add information that will help others understand the setup in the future. Include information about where to see the data once the tracker/sensor is implemented.

## Acceptance Criteria
- [ ] Template runbook is added to Github issue templates

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
This was not an MVP candidate for the notifications framework, however, this could still be implemented as an enhancement
