### ISSUE TITLE
Draft product release notes strategy

### ISSUE THREAD

**Issue by rachel-kauff** [department-of-veterans-affairs/va.gov-cms#979]
## Description
*Who will release the release notes?* It's a fair question. We need a strategy for product release notes that includes:

* An outline of the process by which we initiate, draft, peer review, document, and socialize release notes
* Templates to support the above process, integrated into the right places (GH repo and Zenhub board)
* Prototypes of a release note that model voice, tone, content, and structure
* Definitions of what does and does not get a release note
* A list of the different kinds of releases and how notes will treat each type, such as an enhancement, bug, etc.

## Acceptance Criteria
* The above outlined and documented in GH
* Our first ever MVP release note (probably on editorial workflow status) published 

## Artifacts
[Notes / WIP outline: Release notes](https://docs.google.com/document/d/1FwyF6T9LBjqqW2BISTNzxTYcb60CMxn17HmKZCZl7bU/edit#)

## Labels
- [/] Issue type (red) (defaults to task)
- [ ] CMS subsystem (green)
- [x] CMS practice area (blue)
- [ ] CMS objective (orange)
- [ ] CMS-supported product (black)

**Comment by rachel-kauff** [comment]
Added a new draft of the release notes to the strategy doc. Will review w/ Kev tomorrow.

**Comment by kevwalsh** [comment]
@rachel-kauff we should add issues to this epic.

**Comment by rachel-kauff** [comment]
Wondering if it would be worth mapping out a proto user journey for release notes, maybe building on some of the work Howie has already done so we have clear understanding of the whole ecosystem of CMS support comms.
