### ISSUE TITLE
CMS WCAG 2.0 Accessibility Compliance

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9796]
## Background

As we build out the CMS accessibility audit, accessibility issues of varying severity will be uncovered. We need to account for these findings in a way that allows for both identification and prioritization. 

### User Story or Problem Statement

As the Sitewide Accessibility Lead, I need to surface compliance issues so I can ensure they are prioritized and acted upon.

As a CMS design system designer, I need to see the accessibility concerns in a way that allows me to correct the errors in the CMS and commit them to the CMS design system standards.

As an editor, I need an accessible website so I can provide veterans with timely and accurate content. 

### Affected users and stakeholders

* CMS editors across products
* Sitewide Crew teams

[WIP accessibility audit ](https://docs.google.com/spreadsheets/d/1kduP98QBltqtFG8sIB-h-vLXkEoZNPFJ14lEfT6icus/edit#gid=1653727169)

### Hypothesis

We believe that CMS audit findings will allow the prioritization of CMS design that improves accessibility and compliance. We'll know this to be true when future audits return fewer errors. 

## Assumptions
* The Drupal CMS is 2.0 compliant out of the box.
* There are improvements that can be made to become WCAG 2.1 compliant.

(How will these assumptions be validated?)

## Acceptance Criteria
- [ ] Testable_Outcome_X
- [ ] Testable_Outcome_Y
- [ ] Testable_Outcome_Z
- [ ] Requires KB article update

  ## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [x] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [x] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce users’ mental load by allowing them to fall back on pattern recognition to complete tasks.
- [ ] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [x] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
@laflannery what about this one?

**Comment by laflannery** [comment]
Ya we can close
