### ISSUE TITLE
Make broken link report from content build available to the CMS

### ISSUE THREAD

**Issue by cweagans** [department-of-veterans-affairs/va.gov-cms#9799]
## Description

We should get the broken link data to the CMS to support effort to surface metrics to Datadog + surface a list of broken links to editors. Step 1 is getting the data into the CMS somehow (it could be as simple as writing the JSON file to disk somewhere).

## Acceptance Criteria
- [ ] Broken link report JSON file is retrieved when a content release completes.

## Tasks
- CMS
  - [x] Make new module or use an existing module (e.g. va_gov_api, va_gov_backend, va_gov_build_trigger)
  - [x] Create an event subscriber that fires on content release completing
  - [x] Store the contents of the file to state
  - [ ] Write test

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cweagans** [comment]
@ElijahLynn if you end up taking this on, we're going for dead-simple implementation. My thought was a controller to POST the data to and then shove the entire object into the Drupal KV store. We don't need a separate db table or anything fancy like that.

**Comment by ElijahLynn** [comment]
K, I'm working on this now. I am going to use the Drupal State API https://www.drupal.org/node/1787278 to accept a JSON payload at the route of `/content-release/broken-link-report` and store it in the `key_value` table (w/State API) under a key format of `content_release.broken_link_report.action_run_id`. That is the working plan though, open to naming changes.

**Comment by timcosgrove** [comment]
Broken links json is available publicly: https://vetsgov-website-builds-s3-upload.s3-us-gov-west-1.amazonaws.com/broken-link-reports/vagovprod-broken-links.json

Updated AC and tasks to reflect that instead of POSTing from content release to CMS, we can just pull within the CMS upon content release completing.
