### ISSUE TITLE
Facility menus for News Story Listings

### ISSUE THREAD

**Issue by timcosgrove** [department-of-veterans-affairs/va.gov-cms#9829]
## Description
News Story Listing pages have a facility menu in the left sidebar. We need the component for this and the menu placed in News Story pages.

## Acceptance Criteria
- [ ] A component exists for facility menu pages, with tests
- [x] That menu is placed on facility pages

### Tasks
- [x] Stub out task
- [x] Add side nav request to global state
- [x] Port side nav behavior functionality from content build to next-build
- [x] Add required filters
- [x] Connect side nav props to story listing page
- [x] Render Sidebar
- [ ] Test Filters
- [ ] Test Data

## Implementation details
See next-drupal examples for specific functions for retrieving menu data. https://github.com/chapter-three/next-drupal/blob/main/examples/example-umami/lib/get-global-elements.ts#L24

To get the menu name needed for menu retrieval requires the following chain of includes: `field_office.field_system_menu`. Example on a single story_listing: https://prod.cms.va.gov/jsonapi/node/story_listing/a75c369c-a7f5-402b-aeb9-74ad8d24fd36?include=field_office.field_system_menu

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
This functionality requires we install https://www.drupal.org/project/jsonapi_menu_items in order to work.

This is blocked due to this issue: https://www.drupal.org/project/jsonapi_menu_items/issues/3276561

We are seeing if we can simply remove menu_item_extras, as we don't appear to use it, but we will need input from Steve Wirt to be sure about that.
