### ISSUE TITLE
Editor Recruitment Pipeline Creation

### ISSUE THREAD

**Issue by EWashb** [department-of-veterans-affairs/va.gov-cms#9864]
## Background

In order to create a more uniform process for recruiting editors for participation in research, we should streamline the recruitment process. 

The [survey](https://www.surveymonkey.com/r/R5TNFVX) for distribution.

### User Story or Problem Statement

As a Sitewide Crew UX researcher I need a pool of editors to reach out to so that I can complete my research studies.

As a CMS editor, I would like the opportunity to participate in research so that I can participate in new workflows and give feedback that helps the product.

### Affected users and stakeholders

* CMS editors
* Developers of Sitewide Crew teams

### Hypothesis

_A hypothesis may depend on a spike ticket to be completed._

We believe that an ongoing initiative for editors to opt-in to research will achieve increased participation and a better sense of community around change. We'll know that to be true when we have a roster of editors willing to participate in research. 

## Acceptance Criteria
- [x] touchpoints for editors to opt-in to research
- [x] Coordination with VHA digital media and other stakeholders
- [x] determine contacts for all editor types (VBA, Vet Centers, VAMC)
  
## Design principles

Veteran-centered
- [ ] `Single source of truth`: Increase reliability and consistency of content on VA.gov by providing a single source of truth.
- [ ] `Accessible, plain language`: Provide guardrails and guidelines to ensure content quality.
- [ ] `Purposely structured content`: Ensure Content API can deliver content whose meaning matches its structure.
- [ ] `Content lifecycle governance`: Produce tools, processes and policies to maintain content quality throughout its lifecycle.

Editor-centered
- [ ] `Purpose-driven`: Create an opportunity to involve the editor community in VA’s mission and content strategy goals.
- [ ] `Efficient`: Remove distractions and create clear, straightforward paths to get the job done.
- [ ] `Approachable`: Offer friendly guidance over authoritative instruction.
- [ ] `Consistent`: Reduce user’s mental load by allowing them to fall back on pattern recognition to complete tasks.
- [x] `Empowering`: Provide clear information to help editors make decisions about their work.

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by EWashb** [comment]
I've done this already
