### ISSUE TITLE
Investigate; How is ForeSee intercept survey launched and prepare to disable when it's retired

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#9894]
## Assure we know how/where to disable ForeSee survey

In preparation for retiring the ForeSee intercept survey, determine how it is launched and how we would 'flip the switch" on its last day. Also assure Medalia survey continues to trigger ongoing.

We are seeing both he ForeSee and Medalia intercept surveys firing. We suspect they may potentially be firing for the same visitor - not sure if they're properly accounting for eachother 

Perhaps there is no action on part of the Facilities team, and this will be done centrally (by platform?) - but need to verify.

### Tasks

- [ ] Determine official ForeSee cutoff date
- [ ] Determine instructions from Analytics or Contact Center team 
- [ ] 

## Acceptance Criteria
- [ ] ForeSee survey is not fired
- [ ] Medalia survey continues to fire

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [x] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by cmaeng** [comment]
removing the sprint 63 designation as this doesn't look like it was completed and not auto-shifting into sprint 64 because it doesn't have an estimated need to complete by date.

cc: @dsinla @RWEagans

**Comment by dsinla** [comment]
I think this ticket got lost in the shuffle somehow. No action is/was required  required - shifting to the new survey was done at the Platform level.
