### ISSUE TITLE
Update next-build Expandable Text component to use Accordion web component

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-cms#9897]
## Description
Currently the next-build Expandable Text component does not function in the way expected. We need to update the current functionality to use the Design System Accordion web component

## Acceptance Criteria
- [x] Expandable Text component works correctly

## Tasks
- [x] Update Expandable Text component to use the Design System Accordion web component
- [x] Update Unit Tests

### CMS Team
Please check the team(s) that will do this work.

https://design.va.gov/storybook/?path=/docs/components-va-accordion--default

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`
