### ISSUE TITLE
CMS user journey maps

### ISSUE THREAD

**Issue by jordanamello** [department-of-veterans-affairs/va.gov-cms#990]
### User Story or Problem Statement

As a CMS team, I want to have a tool that reflects the CMS experience so that we can make product decisions. 

### Hypothesis

We believe that the journey maps will give the CMS team a baseline against which we will measure improvements regarding CMS experience. We'll know that to be true when the improvement opportunities and pain points are addressed and re-evaluated.

## Acceptance Criteria
- [x] Content Editing journey mapped
- [x] CMS Onboarding journey mapped
- [ ] Product Creation journey mapped
- [ ] Journeys socialized with team and stakeholders
- [ ] Journeys stored in GitHub
