### ISSUE TITLE
Discovery for backlog epic "Events near me"

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-cms#9907]
## Description
Learn some context in prep for "events near me" epic, currently in backlog. 

## Acceptance Criteria
- [x] Understand recent events research and how it pertains to this epic
- [x] Understand recent and current event filter designs
- [x] Start to frame up hypothesis for new design

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by jilladams** [comment]
Noted to Dave in email that this ticket may span sprint boundary due to dependency on both Danielle and Dave's time.

**Comment by jilladams** [comment]
FYI @wesrowe : Florence created this ticket out of scrum notes. I added this to the Events geodata epic (#9617 ) for now, though Kev owned that Epic and we probably need to get more familiar with what's documented there. (That can be a part of this discovery?).
