### ISSUE TITLE
VAMC events "where" sometimes not displaying in list view

### ISSUE THREAD

**Issue by fmccaf1** [department-of-veterans-affairs/va.gov-cms#9909]
## Describe the defect
VAMC events' "where" field sometimes does not display in events list view.

## To Reproduce
1. Go to [VA Bedford health care > Events](https://www.va.gov/bedford-health-care/events/)
2. Scroll down to see event called "Gloucester Veterans resource fair & open house" and no "where" field
NOTE: It does show in the Detail View.

###To see editor view for an event that is displaying the "where" field and data:
1. Go to Prod > VHA 
2. Search "one team" and click to edit the event - 
https://www.va.gov/bedford-health-care/events/47460/
https://prod.cms.va.gov/node/47460/edit

###To see editor view for an event that is NOT displaying the "where" field and data:
1. Go to Prod > VHA 
2. Search "Gloucester veterans" and click to edit the event 
https://www.va.gov/bedford-health-care/events/47462/
https://prod.cms.va.gov/node/47462/edit

## AC / Expected behavior
I'd expect to see the "where" field and data populated, like the events above and below the resource fair event. Or else, I'd expect to see something on the CMS side that shows some kind of reason for the discrepancy between these two events.

## Screenshots
![image.png](https://images.zenhubusercontent.com/629a1db0e70457da479e69ae/b5a45f72-f3c3-4d7e-b9f5-63e78c84380e)

## Labels
(You can delete this section once it's complete)
- [x] Issue type (red) (defaults to "Defect")
- [ ] CMS subsystem (green)
- [ ] CMS practice area (blue)
- [x] CMS workstream (orange) (not needed for bug tickets)
- [ ] CMS-supported product (black)

## Assumptions: 
- Data is available in the FE, so it's a logic problem in the template.

## Tasks / Acceptance Criteria

- [ ] - investigate logic issues
- [ ] - get it working locally
- [ ] check unit tests (may not exist), add if not present
  - [ ] Note: confirm BE rules (a location is required in CMS)
- [ ] - code review
- [ ] - QA
- [ ] Design review

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by fmccaf1** [comment]
@wesrowe Does this look right? Also, notice the third event in the screenshot - it's showing the street address for the VA hospital! Not sure if that's another defect, or the same as this one.

**Comment by wesrowe** [comment]
Nice job, @fmccaf1! I added the epic. We'll refine tomorrow

**Comment by jilladams** [comment]
Verified in prod!
