### ISSUE TITLE
Discovery: Understand / document current Drupal implementation of Benefit Detail pages

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-cms#9910]
## Description
This ticket covers the scope of Drupal discovery required for hardening the Benefit detail page content model. 

### 1. Content type differences
The CMS has 2 very similar content types: 

1. Resources & Support
2. Benefit Detail pages

We need to understand the technical differences that matter between them, including:

- Fields / configurations
- Roles / permissions
- Other Guardrails

#### context docs to consult
-  [VA.gov high level content model (whimsical board)](https://whimsical.com/va-gov-high-level-content-model-PyatLZVHkA8QPxzuAqUEe8) -  (being migrated to [this Mural](https://app.mural.co/t/vagov6717/m/vagov6717/1658937741729/88cc653ce1bed251e60940c147867eb061496070?sender=8a525778-085f-425b-b555-a4c06f7b9a92))
- [VA.gov CMS content model documentation](https://airtable.com/appSg80z9nVWoesxn/tbltV84WALyKvpXuc/viwPCTpplznIus6VX?blocks=hide) 

### 2. Reusable content - "reverse engineer current state"
Sitewide Content wants chunks of that content to be reusable -- possibly within other areas of the site, possibly on other platforms / downstream consumers of site content (chatbot, mobile app).  In order to understand if they need to be smaller component content types ( like Q&A), we need to more deeply understand:

1. how do we define the chunks of existing content
2. which chunks _should_ be reusable
3. are any already reusable and where

## Other context
A6 internal notes doc: https://docs.google.com/document/d/1viOAMVIJBaA8SLUmPXX_ue4Zx6C1AS69zeX6M78tcY4/edit#

## Tasks
- Dev env management - .5
- Reading / Possible meetings for historical context - 2
- Documenting outcomes / questions / proposal - 3
- X-factor - 4

9 hrs

## Acceptance Criteria
- [ ] study Drupal implementation
- [ ] get historical context from Steve W
- [ ] first draft of findings
- [ ] (optional) revisions and follow-up after sharing draft

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [ ] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [x] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by chri5tia** [comment]
Existing and Historical documentation on Benefit hubs:

Confluence:
https://va-gov.atlassian.net/wiki/spaces/VAGOV/pages/35717310/Heath+Care+Benefits+Hub+Content+Model

(Updating my doc with CMS architectural narrative, in case it's helpful.)

Presentation slides:
https://va-gov.atlassian.net/wiki/download/attachments/35717310/Proposed%20Health%20Care%20Benefits%20Content%20Model.pdf?version=1&modificationDate=1545239957041&cacheVersion=1&api=v2

Conversation notes:
https://docs.google.com/document/d/1viOAMVIJBaA8SLUmPXX_ue4Zx6C1AS69zeX6M78tcY4/edit#heading=h.6pjtpf65zekx

I have requested access to this benefits hub airtable:
https://airtable.com/tbl1wExn2Cn5Co1LC/viw6st9BDLbcJLn7y

**Comment by chri5tia** [comment]
# CMS Architectural Narrative
Benefit hubs in the CMS as it stands now.
Note: Machines names of components are in `code markup`.

## Components

### Content types
- Benefits detail page (`page`)-
for benefits overview content related to specific things, editor discretion
- Benefits hub landing page (`landing_page`)-
one-off, special layout and/or special content, editor discretion

## Anatomy of Benefits Detail Page
Relevant fields.
- Title
- Page intro
- Meta tags'
- Include table of contents option
- Include an alert
- Featured content
- Main content block (we've seen this already with the FAQ and Resource and Support page). 
  - Available paragraph types: Table, React Widget, Rich text, list of link teasers, Q&A Section (not reusable type), Alert, Process list, Additional information, Accordion group option, Number callout, Embedded images, link to file or video, list of links, 
  - All/any other paragraph types can be made available.
 - Related links

## Anatomy of Benefit Hub Landing Page

Note: I feel like the landing page was only called a benefit landing page because the project started out as a benefit hub and then grew. See Q below about if this can be more generic.

## Questions
- [ ] Can the benefits hub landing page be a generic landing page, what makes it specific to benefits?

**Comment by chri5tia** [comment]
Questions previously raised (from meeting notes, etc.)
- [ ] What are the differences between R&S and BD pages? Check roles, design, guardrails.
- [ ] Content audit: what is different between the different benefit types of pages in terms of field input?  

Previous observations raised:
- BD pages used for four (of the 8) benefit hubs:
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/content/structured-content/core-benefit-content-page-templates.md

**Comment by chri5tia** [comment]
Workshop notes:

Drupalese/ reusable components:

- name/token
- link/teaser
- paragraph/entity references
- FAQs/Q&A group
- [ ]  Others?

benefit reusable paragraphs: description, eligibility, offering summary, offering full details 
- reusable components categorized by hub and/or type 

bite: paragraph title/name
snack: paragraph content

- [ ] bite/snack/meal needs to be defined

- migration? full, manual, hybrid
- schema.org / schemadotorg module
   (governance? collab structure?)

Lift:
- machine names for schema.org
- new content types vs. updating existing

- [ ] digest schema.org, cut ticket

Links:

- https://www.drupal.org/project/schemadotorg
- https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1636828859943/fce7f7349e5a7f0221d081bf0f314bf68feb052d?sender=8309566b-3613-43df-8e91-fa541415d5a4
- https://airtable.com/appojvgFB7lvqgArz/tblT5OO9S1bhT1tzT/viwhIefPZWm7dZIB7?blocks=hide

**Comment by chri5tia** [comment]
prioritize eligibility resuability

**Comment by chri5tia** [comment]
After the workshop today and getting better insight into the scope of the project, I don't believe exploring the current Benefit Hub Detail and Landing pages have much value. There is a good chance that we will be creating new content type(s).

**Comment by dsasser** [comment]
Work meets Acceptance Criteria 👍

**Comment by chri5tia** [comment]
Found this:
https://drive.google.com/drive/folders/1ulvVHIvEAdfKpJqhaUAR2jHN8C-DIYt-?usp=sharing

**Comment by swirtSJW** [comment]
Related schema https://schema.org/GovernmentService
