### ISSUE TITLE
Sprint 64 - Facilities | Aug 1 - Aug 14

### ISSUE THREAD

**Issue by dsinla** [department-of-veterans-affairs/va.gov-cms#9934]
<details><summary>Quarterly Initiatives</summary>
List here the major initiatives (Super Epics) driving work for this quarter 
The majority of the team's work should fall under these initiatives.
There will likely be other bug-fixes and continuing/legacy issues that fall into a Sprint.

- #9659  VBA MVP
- #9655 Lovell 
- #9096 Covid status post-launch
</details>

<details><summary>Issue icon legend</summary>

🥅   — Sprint goals (pending Sprint planning)
💡 — Design
💧  — Drupal engineering
🎉 — FE
🎓  — Training / Change management / KB
📟 — Helpdesk
🔮  —  Planning / roadmap / epic refinement
📊  —  Analytics
🚰  — Service design
🌱 — Good first task
</details>

<details><summary>OOO</summary>

**FYI Canadian Holiday 08/01**

Who | When | Backup 
----- | ------ | ------- 
Aslan | 8/10-8/12  |  Dave P
Denise | 8/1, 8/5 - 8/8 |  
Jay | 8/1 | 
Max | 8/5 - 8/10 | John
Roger | 8/3 - 8/4 | David
</details>

## #9096 Facility COVID status post-launch

- [x] #9707
- [x] #9935
- [ ] #9938 🥅
 

## Facility Locator

None

## VBA Facilities

- [ ] #9961 Select research sites
- [ ] #10002 Coordinate Teams and github for VBA

 Design
   - [x] #10024 
   - [ ] #9978 @davidmpickett 
   - Veteran research plan - @jcklpe 
   - Business research plan - @ContentBrewmaster 

## VAMC

- [ ]  #10023 Add place JSON-LD to Vet Centers (was previously done for VAMCs)

### Lovell #9655 

- Content / design
  - [ ] #9846 @jcklpe 🥅
  - [ ] #9974 @davidmpickett 

- Engineering 
   - [ ] #9349 
   - [x] #9948
  - [ ] Refine Epic #1939 (for DoD facilities)
  

## Lighthouse / Facility API data

AI: Create ticket specifically around storing Lat/Long in concordance with ToS - Mapbox to start, but do we go elsewhere? Work with Nancy, 
Govt source? 
@christianmburk 

## Blocked

<details><summary>Blocked by V1</summary>

- [ ] #8017  
- [ ] #4769 
- [ ] #4410
  - [ ] #4411 

</details>

- [ ]  #9849 = Waiting on VHADM
- [ ] 

## Other

- [x] #9967 
- [ ] #9924 
- [ ] #9714 🥅
  - Then execute on CM from #9716 

Heads up: Supporting PACT act comms might have some impact to this sprint.  Might not. 

## Stretch
NOTE:  Given the scope of work this sprint, all stretches were moved in to next sprint

###  #9318 Hours

- [x] #8302 
  - [ ] #9357
