### ISSUE TITLE
Refactor: audience_topics paragraph

### ISSUE THREAD

**Issue by penny-lischer** [department-of-veterans-affairs/va.gov-cms#9942]
## Description
Refactor to allow for DRUPAL API data to get processed/transformed through data_service. This will allow the component to consume a basic object type.

## Acceptance Criteria
- [x] Component renders as expected
- [x] Component render markup using the transformed data
- [x] data_service will receive JSON:API data and transform it to the format expected by the component
- [x] Existing component tests are revised to test the updated 'pure' component
- [x] The component is added to StoryBook

## Tasks
- [x] Update component to use the new transformed data
- [x] Create data_service to transform DRUPAL API and return new object
- [x] Update Unit tests
- [x] Update demo page
- [x] Add to storybook

### CMS Team
Please check the team(s) that will do this work.

- [ ] `Program`
- [x] `Platform CMS Team`
- [ ] `Sitewide Crew`
- [ ] `⭐️ Sitewide CMS`
- [ ] `⭐️ Public Websites`
- [ ] `⭐️ Facilities`
- [ ] `⭐️ User support`

**Comment by timcosgrove** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VAgov-CMS-team-5c0e7b864b5806bc2bfc2087/issues/department-of-veterans-affairs/va.gov-cms/9942?planning-poker) with ZenHub @penny-lischer @tjheffner

**Comment by timcosgrove** [comment]
Removed the data service testing AC/task. We will instead ultimately move the data service/transforming to next-drupal-query, and will put tests in place when we do that.
