### ISSUE TITLE
Improve Helpdesk Team Awareness of Content-Release Failures and Delays

### ISSUE THREAD

**Issue by olivereri** [department-of-veterans-affairs/va.gov-cms#9972]
## Description
Helpdesk is the first point of contact for content editors and need to be aware of situations that degrade content editor's experience. Specifically, content releases are a frequent pain point for content editors and in turn CMS Helpdesk. 

## Acceptance Criteria

- [ ] Implement an automated process to determine if content-releases has been delayed for [2 hours] and CMS Helpdesk is alerted in slack `@cms-helpdesk`
  - confirm timeframe with Helpdesk

## Implementation Notes
- Implement alerting in DataDog, not GHA

## Task list
- [x] Determine appropriate metric to track content-build "time since last release"
- [x] Create Datadog Metric based monitor
  - [x] Set alert threshold to 2 hours.
  - [x] Point metric alert to cms-notifications in slack for testing
  - [x] Create maintenance window for metric to silence alerts outside of business hours.
- [x] Send a message to Site-Wide that this alert exists.

**Comment by olivereri** [comment]
@stefaniefgray for awareness

**Comment by stefaniefgray** [comment]
Also tagging in @TroyA6 for awareness

Could probably close https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9963 as a duplicate

**Comment by olivereri** [comment]
![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/e0e7459b-eee4-47fb-ac77-4a158553c517)

**Comment by olivereri** [comment]
@ Mentioning a user group in Slack from a Datadog Alert is different and less intuitive than here,channel, or a username:
https://docs.datadoghq.com/integrations/slack/?tab=slackapplication#-mentions-in-slack-from-monitor-alert

It requires knowing the ID of the group. Datadog docs provide information on interacting with the API but I found that too cumbersome since I don't know what I'm doing. Using DSVA slack from a browser, selecting "People & Groups" then searching and selecting the desired work will reveal the ID in the location bar:

![image.png](https://images.zenhubusercontent.com/5f04cf8f49978b1615fee8c2/61e65943-e000-4dbf-8942-760a7a22fea9)

<!subteam^S010U41C30V>

**Comment by olivereri** [comment]
The UI for the DD Downtime scheduler doesn't match the documentation:
https://docs.datadoghq.com/monitors/guide/suppress-alert-with-downtimes/?tab=ui
This may be a case where the DDog FedRAMP version is behind the commercial version.

There is an option to use RRULE or recurrence rule iCalendar RFC standard to define downtimes.
[Recurrence rule examples](https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html)
[Recurrence rule generator](https://icalendar.org/rrule-tool.html)

I've added another downtime schedule to only run on Saturday and Sunday for 24 hours for the TSLCR monitor. The other one was updated to only run Monday, Tuesday, Wednesday, Thursday, and Friday outside of business hours.
